import type { StoryRead } from "../../story-read.page-type.ts"

export const rebornAsADemonicTree = {
  id: "01a0657d-ada4-786e-a739-b34fd02c3f16",
  pageTypeSlug: "story-read",
  slug: "reborn-as-a-demonic-tree",
  title: "Reborn as a Demonic Tree",
  worldSlug: "reborn-as-a-demonic-tree",
  source: "royal-road",
  author: "XKARNATION",
  rank: "B",
  following: true,
  externalTags: [
    "LitRPG",
    "Reincarnation",
    "Progression",
    "Anti-Hero Lead",
    "Kingdom Building",
    "Action",
    "Fantasy",
    "Cultivation",
    "High Fantasy",
    "Magic",
    "Male Lead",
    "Martial Arts",
    "Multiple Lead Characters",
    "Non-Human Lead",
    "Secret Identity",
    "Slice of Life",
    "Strong Lead",
    "Villainous Lead",
  ],
  unitSlug: "words",
  externalLink: "https://www.royalroad.com/fiction/62881/reborn-as-a-demonic-tree",
  externalId: "62881",
  prose: "txt",
} as const satisfies StoryRead
