import { achievementName } from "akasha/temper/addon/pages/world/navigation/modules/destinations-data-runtime/destinations-data-runtime.module.code.ts"
import "akasha/temper/eso/type/eso-globals/eso-globals.type-declaration.d.ts"

export const SETTINGS_STRINGS_01: Record<string, string> = {
  SI_TEMPER_DESTINATIONS_SETTINGS_FISHING_TOGGLE: "Show incomplete positions",
  SI_TEMPER_DESTINATIONS_SETTINGS_FISHING_TOGGLE_TT:
    "Shows Fishing holes where there is a chance of catching fish for achievements",
  SI_TEMPER_DESTINATIONS_SETTINGS_GTRADER_COLOR: "Guild Trader Pin text color",
  SI_TEMPER_DESTINATIONS_SETTINGS_GTRADER_COLOR_TT: "Affects Guild Trader text on wayshrines",
  SI_TEMPER_DESTINATIONS_SETTINGS_IMPROVEMENT_HEADER: "POI Improvement",
  SI_TEMPER_DESTINATIONS_SETTINGS_IMPROVEMENT_HEADER_TT: "Improve unknown and known POI",
  SI_TEMPER_DESTINATIONS_SETTINGS_MAPFILTERS_ACHS_TOGGLE: "Show Achievement Map filters",
  SI_TEMPER_DESTINATIONS_SETTINGS_MAPFILTERS_ACHS_TOGGLE_TT:
    "Shows/hides Map Filters for all Achievements.",
  SI_TEMPER_DESTINATIONS_SETTINGS_MAPFILTERS_COLS_TOGGLE: "Show Collectible Map filters",
  SI_TEMPER_DESTINATIONS_SETTINGS_MAPFILTERS_COLS_TOGGLE_TT:
    "Shows/hides Map Filters for all Collectibles.",
  SI_TEMPER_DESTINATIONS_SETTINGS_MAPFILTERS_FISS_TOGGLE: "Show Fishing Map filters",
  SI_TEMPER_DESTINATIONS_SETTINGS_MAPFILTERS_FISS_TOGGLE_TT:
    "Shows/hides Map Filters for all Fishing holes.",
  SI_TEMPER_DESTINATIONS_SETTINGS_MAPFILTERS_HEADER: "Map Filters",
  SI_TEMPER_DESTINATIONS_SETTINGS_MAPFILTERS_HEADER_TT:
    "This submenu covers all Map Filter related settings.",
  SI_TEMPER_DESTINATIONS_SETTINGS_MAPFILTERS_MISS_TOGGLE: "Show Misc Map filters",
  SI_TEMPER_DESTINATIONS_SETTINGS_MAPFILTERS_MISS_TOGGLE_TT:
    "Shows/hides Map Filters for Miscellaneous pins (Ayleid Wells, Dwemer Ruins, Craglorn Border, as well as all Werewolf and Vampire pins).",
  SI_TEMPER_DESTINATIONS_SETTINGS_MAPFILTERS_POIS_TOGGLE: "Show POI Map filters",
  SI_TEMPER_DESTINATIONS_SETTINGS_MAPFILTERS_POIS_TOGGLE_TT:
    "Shows/hides Map Filters for all Points of Interest.",
  SI_TEMPER_DESTINATIONS_SETTINGS_MAPFILTERS_QUES_TOGGLE: "Show Questgiver Map filters",
  SI_TEMPER_DESTINATIONS_SETTINGS_MAPFILTERS_QUES_TOGGLE_TT:
    "Shows/hides Map Filters for all Questgivers.",
  SI_TEMPER_DESTINATIONS_SETTINGS_MAPFILTERS_SUBHEADER: "Map Filter Settings",
  SI_TEMPER_DESTINATIONS_SETTINGS_MISC_AYLEID_WELL_HEADER: "Ayleid Wells",
  SI_TEMPER_DESTINATIONS_SETTINGS_MISC_BORDER_HEADER: "Craglorn Border",
  SI_TEMPER_DESTINATIONS_SETTINGS_MISC_BORDER_PIN_COLOR: "Pin color for Craglorn Border",
  SI_TEMPER_DESTINATIONS_SETTINGS_MISC_BORDER_PIN_COLOR_TT:
    "Affects the PIN color for Craglorn Border",
  SI_TEMPER_DESTINATIONS_SETTINGS_MISC_BORDER_PIN_TOGGLE: "Show Craglorn Border Line",
  SI_TEMPER_DESTINATIONS_SETTINGS_MISC_BORDER_PIN_TOGGLE_TT:
    "Shows the border line dividing Upper and Lower Craglorn",
  SI_TEMPER_DESTINATIONS_SETTINGS_MISC_BORDER_SIZE: "Pin size for Craglorn Border",
  SI_TEMPER_DESTINATIONS_SETTINGS_MISC_COMPASS_DIST: "Pin distance for POIs on compass",
  SI_TEMPER_DESTINATIONS_SETTINGS_MISC_COMPASS_HEADER: "Misc Settings",
  SI_TEMPER_DESTINATIONS_SETTINGS_MISC_COMPASS_PIN_TOGGLE: "Show misc POIs on compass",
  SI_TEMPER_DESTINATIONS_SETTINGS_MISC_DEADLANDS_ENTRANCE_HEADER: "Deadlands Entrance",
  SI_TEMPER_DESTINATIONS_SETTINGS_MISC_DWEMER_HEADER: "Dwemer Ruins",
  SI_TEMPER_DESTINATIONS_SETTINGS_MISC_DWEMER_PINTEXT_COLOR: "Pin text color for Dwemer Ruins",
  SI_TEMPER_DESTINATIONS_SETTINGS_MISC_DWEMER_PINTEXT_COLOR_TT:
    "Affects the pin TEXT on Dwemer Ruins",
  SI_TEMPER_DESTINATIONS_SETTINGS_MISC_DWEMER_PIN_COLOR: "Pin color for Dwemer Ruins",
  SI_TEMPER_DESTINATIONS_SETTINGS_MISC_DWEMER_PIN_COLOR_TT:
    "Affects the PIN color for Dwemer Ruins",
  SI_TEMPER_DESTINATIONS_SETTINGS_MISC_DWEMER_PIN_SIZE: "Pin size for Dwemer Ruins",
  SI_TEMPER_DESTINATIONS_SETTINGS_MISC_DWEMER_PIN_TOGGLE: "Show Dwemer Ruins",
  SI_TEMPER_DESTINATIONS_SETTINGS_MISC_DWEMER_PIN_TOGGLE_TT:
    "This is for turning Dwemer Ruins on/off on the maps",
  SI_TEMPER_DESTINATIONS_SETTINGS_MISC_HEADER: "Miscellaneous POI Positions",
  SI_TEMPER_DESTINATIONS_SETTINGS_MISC_HEADER_TT:
    "This submenu covers Ayleid Wells, Dwemer Ruins and the Craglorn Border line.",
  SI_TEMPER_DESTINATIONS_SETTINGS_MISC_HIGHISLE_SHRINE_HEADER: "Druidic Shrine",
  SI_TEMPER_DESTINATIONS_SETTINGS_MISC_PINTEXT_AYLEID_WELL_COLOR: "Pin text color for Ayleid Wells",
  SI_TEMPER_DESTINATIONS_SETTINGS_MISC_PINTEXT_AYLEID_WELL_COLOR_TT:
    "Affects the pin TEXT on Ayleid Wells",
  SI_TEMPER_DESTINATIONS_SETTINGS_MISC_PINTEXT_DEADLANDS_ENTRANCE_COLOR:
    "Pin text color for Deadlands Entrance",
  SI_TEMPER_DESTINATIONS_SETTINGS_MISC_PINTEXT_DEADLANDS_ENTRANCE_COLOR_TT:
    "Affects the pin TEXT on Deadlands Entrance",
  SI_TEMPER_DESTINATIONS_SETTINGS_MISC_PINTEXT_HIGHISLE_DRUIDICSHRINES_COLOR:
    "Pin text color for Druidic Shrines",
  SI_TEMPER_DESTINATIONS_SETTINGS_MISC_PINTEXT_HIGHISLE_DRUIDICSHRINES_COLOR_TT:
    "Affects the pin TEXT on Druidic Shrines",
  SI_TEMPER_DESTINATIONS_SETTINGS_MISC_PIN_AYLEID_WELL_COLOR: "Pin color for Ayleid Wells",
  SI_TEMPER_DESTINATIONS_SETTINGS_MISC_PIN_AYLEID_WELL_COLOR_TT:
    "Affects the PIN color for Ayleid Wells",
  SI_TEMPER_DESTINATIONS_SETTINGS_MISC_PIN_AYLEID_WELL_SIZE: "Pin size for Ayleid Wells",
  SI_TEMPER_DESTINATIONS_SETTINGS_MISC_PIN_AYLEID_WELL_TOGGLE: "Show Ayleid Wells",
  SI_TEMPER_DESTINATIONS_SETTINGS_MISC_PIN_AYLEID_WELL_TOGGLE_TT:
    "This is for turning Ayleid Wells on/off on the maps",
  SI_TEMPER_DESTINATIONS_SETTINGS_MISC_PIN_DEADLANDS_ENTRANCE_COLOR:
    "Pin color for Deadlands Entrance",
  SI_TEMPER_DESTINATIONS_SETTINGS_MISC_PIN_DEADLANDS_ENTRANCE_COLOR_TT:
    "Affects the PIN color for Deadlands Entrance",
  SI_TEMPER_DESTINATIONS_SETTINGS_MISC_PIN_DEADLANDS_ENTRANCE_SIZE:
    "Pin size for Deadlands Entrance",
  SI_TEMPER_DESTINATIONS_SETTINGS_MISC_PIN_DEADLANDS_ENTRANCE_TOGGLE: "Show Deadlands Entrance",
  SI_TEMPER_DESTINATIONS_SETTINGS_MISC_PIN_DEADLANDS_ENTRANCE_TOGGLE_TT:
    "This is for turning Deadlands Entrance on/off on the maps",
  SI_TEMPER_DESTINATIONS_SETTINGS_MISC_PIN_HIGHISLE_DRUIDICSHRINES_COLOR:
    "Pin color for Druidic Shrines",
  SI_TEMPER_DESTINATIONS_SETTINGS_MISC_PIN_HIGHISLE_DRUIDICSHRINES_COLOR_TT:
    "Affects the PIN color for Druidic Shrines",
  SI_TEMPER_DESTINATIONS_SETTINGS_MISC_PIN_HIGHISLE_DRUIDICSHRINES_SIZE:
    "Pin size for Druidic Shrines",
  SI_TEMPER_DESTINATIONS_SETTINGS_MISC_PIN_HIGHISLE_DRUIDICSHRINES_TOGGLE: "Show Druidic Shrine",
  SI_TEMPER_DESTINATIONS_SETTINGS_MISC_PIN_HIGHISLE_DRUIDICSHRINES_TOGGLE_TT:
    "This is for turning Druidic Shrines on/off on the maps",
  SI_TEMPER_DESTINATIONS_SETTINGS_MISC_PIN_LAYER: "Pin layer for all miscellaneous POIs",
  SI_TEMPER_DESTINATIONS_SETTINGS_MUNDUS_DETAIL_PIN_TOGGLE: "Show Mundus details",
  SI_TEMPER_DESTINATIONS_SETTINGS_MUNDUS_TXT_COLOR: "Mundus Stone text color",
  SI_TEMPER_DESTINATIONS_SETTINGS_MUNDUS_TXT_COLOR_TT: "Affects the DETAIL TEXT on Mundus Stones",
  SI_TEMPER_DESTINATIONS_SETTINGS_PER_CHAR: "*",
  SI_TEMPER_DESTINATIONS_SETTINGS_PER_CHAR_BUTTON_TT: "This button only affects current character.",
  SI_TEMPER_DESTINATIONS_SETTINGS_PER_CHAR_HEADER:
    "Settings marked with a yellow '*' only affects the current character.",
  SI_TEMPER_DESTINATIONS_SETTINGS_PER_CHAR_TOGGLE_TT: "This switch only affects current character.",
  SI_TEMPER_DESTINATIONS_SETTINGS_POIS_ENGLISH_TEXT_HEADER: "This may be unused",
  SI_TEMPER_DESTINATIONS_SETTINGS_POI_ENGLISH_COLOR: "Text color for English POI names",
  SI_TEMPER_DESTINATIONS_SETTINGS_POI_ENGLISH_COLOR_TT:
    "Set the text color for english translation of POI names",
  SI_TEMPER_DESTINATIONS_SETTINGS_POI_ENGLISH_KEEPS_COLOR: "Text color for English Keeps names",
  SI_TEMPER_DESTINATIONS_SETTINGS_POI_ENGLISH_KEEPS_COLOR_TT:
    "Set the text color for english translation of Keeps names",
  SI_TEMPER_DESTINATIONS_SETTINGS_POI_ENGLISH_KEEPS_HA: "Hide Alliance Name on Keeps Tooltips",
  SI_TEMPER_DESTINATIONS_SETTINGS_POI_ENGLISH_KEEPS_HA_TT: "Hide Alliance Name on Keeps Tooltips",
  SI_TEMPER_DESTINATIONS_SETTINGS_POI_ENGLISH_KEEPS_NL: "Add a new line on Keeps tooltips",
  SI_TEMPER_DESTINATIONS_SETTINGS_POI_ENGLISH_KEEPS_NL_TT:
    "Add a new line on Keeps tooltips for english name",
  SI_TEMPER_DESTINATIONS_SETTINGS_POI_ENGLISH_TEXT_HEADER: "English text on Points of interest",
  SI_TEMPER_DESTINATIONS_SETTINGS_POI_HEADER: "Unknown Points of Interest",
  SI_TEMPER_DESTINATIONS_SETTINGS_POI_HEADER_TT: "This submenu covers Unknown Points of Interest",
  SI_TEMPER_DESTINATIONS_SETTINGS_POI_IMPROVE_CRAFTING: "Improve Crafting POIs",
  SI_TEMPER_DESTINATIONS_SETTINGS_POI_IMPROVE_CRAFTING_TT:
    "Improve Crafting POIs by adding set description on tooltip",
  SI_TEMPER_DESTINATIONS_SETTINGS_POI_IMPROVE_MUNDUS: "Improve Mundus POIs",
  SI_TEMPER_DESTINATIONS_SETTINGS_POI_IMPROVE_MUNDUS_TT:
    "Improve Mundus POIs by adding effect description on tooltip",
  SI_TEMPER_DESTINATIONS_SETTINGS_POI_KNOWN_SUBHEADER: "This may be unused",
  SI_TEMPER_DESTINATIONS_SETTINGS_POI_SHOW_ENGLISH: "Show english POI names",
  SI_TEMPER_DESTINATIONS_SETTINGS_POI_SHOW_ENGLISH_KEEPS: "Show english POI names for Keeps",
  SI_TEMPER_DESTINATIONS_SETTINGS_POI_SHOW_ENGLISH_KEEPS_TT:
    "Show english POI names on the keep tooltip",
  SI_TEMPER_DESTINATIONS_SETTINGS_POI_SHOW_ENGLISH_TT:
    "Show english POI names at the top of the map",
  SI_TEMPER_DESTINATIONS_SETTINGS_POI_UNKOWN_SUBHEADER: "This may be unused",
  SI_TEMPER_DESTINATIONS_SETTINGS_RELOADUI: "ReloadUI",
  SI_TEMPER_DESTINATIONS_SETTINGS_RELOAD_WARNING:
    "Changing this setting will force an instant /reloadui",
  SI_TEMPER_DESTINATIONS_SETTINGS_RESET: "Reset to default settings",
  SI_TEMPER_DESTINATIONS_SETTINGS_TITLE: "Destinations",
  SI_TEMPER_DESTINATIONS_SETTINGS_UNKNOWN_COLOR: "Pin text color for Unknown POI's",
  SI_TEMPER_DESTINATIONS_SETTINGS_UNKNOWN_COLOR_EN: "Pin text color (english)",
  SI_TEMPER_DESTINATIONS_SETTINGS_UNKNOWN_COLOR_EN_TT:
    "Affects the english text for all unknown Points of Interest, if activated",
  SI_TEMPER_DESTINATIONS_SETTINGS_UNKNOWN_COLOR_TT: "Affects all unknown Points of Interest",
  SI_TEMPER_DESTINATIONS_SETTINGS_UNKNOWN_PIN_LAYER: "Pin layer for unknown POIs",
  SI_TEMPER_DESTINATIONS_SETTINGS_UNKNOWN_PIN_SIZE: "Pin size for unknown POIs",
  SI_TEMPER_DESTINATIONS_SETTINGS_UNKNOWN_PIN_STYLE: "Map pins for unknown POIs",
  SI_TEMPER_DESTINATIONS_SETTINGS_UNKNOWN_PIN_TOGGLE: "Show unknown POIs",
  SI_TEMPER_DESTINATIONS_SETTINGS_USE_ACCOUNTWIDE: "Use accountwide settings",
  SI_TEMPER_DESTINATIONS_SETTINGS_USE_ACCOUNTWIDE_TT:
    "If on, then the settings will be the same for ALL characters.",
  SI_TEMPER_DESTINATIONS_SETTINGS_VWW_COMPASS_DIST: "Pin distance for pins on compass",
  SI_TEMPER_DESTINATIONS_SETTINGS_VWW_COMPASS_HEADER: "Misc Settings",
  SI_TEMPER_DESTINATIONS_SETTINGS_VWW_COMPASS_PIN_TOGGLE: "Show pins on compass",
  SI_TEMPER_DESTINATIONS_SETTINGS_VWW_HEADER: "Vampire and Werewolf Positions",
  SI_TEMPER_DESTINATIONS_SETTINGS_VWW_HEADER_TT:
    "This submenu covers Vampires and Werewolfs, including spawns, Alters and Shrines.",
  SI_TEMPER_DESTINATIONS_SETTINGS_VWW_PINTEXT_COLOR: "Pin text color for Werewolfs/Vampires",
  SI_TEMPER_DESTINATIONS_SETTINGS_VWW_PINTEXT_COLOR_TT:
    "Affects the pin TEXT on Werewolf and Vampire spawns, Vampire Altars and Werewolf Shrines",
  SI_TEMPER_DESTINATIONS_SETTINGS_VWW_PIN_COLOR: "Pin color for Werewolfs/Vampires",
  SI_TEMPER_DESTINATIONS_SETTINGS_VWW_PIN_COLOR_TT:
    "Affects the PIN color for Werewolf and Vampire spawns, Vampire Altars and Werewolf Shrines",
  SI_TEMPER_DESTINATIONS_SETTINGS_VWW_PIN_LAYER: "Pin layer for Werewolfs/Vampires",
  SI_TEMPER_DESTINATIONS_SETTINGS_VWW_PIN_VAMP_ALTAR_SIZE: "Pin size for Vampire Altars",
  SI_TEMPER_DESTINATIONS_SETTINGS_VWW_PIN_VAMP_ALTAR_TOGGLE: "Show Vampire Altars",
  SI_TEMPER_DESTINATIONS_SETTINGS_VWW_PIN_VAMP_ALTAR_TOGGLE_TT:
    "This is for turning Vampire Alters on/off on the maps",
  SI_TEMPER_DESTINATIONS_SETTINGS_VWW_PIN_WWVAMP_SIZE: "Pin size for Werewolfs/Vampires",
  SI_TEMPER_DESTINATIONS_SETTINGS_VWW_PIN_WWVAMP_TOGGLE: "Show WW/Vampire spawns",
  SI_TEMPER_DESTINATIONS_SETTINGS_VWW_PIN_WWVAMP_TOGGLE_TT:
    "This is for turning Vampire and Werewolf spawns on/off on the maps",
  SI_TEMPER_DESTINATIONS_SETTINGS_VWW_PIN_WW_SHRINE_SIZE: "Pin size for Werewolf Shrines",
  SI_TEMPER_DESTINATIONS_SETTINGS_VWW_PIN_WW_SHRINE_TOGGLE: "Show Werewolf Shrines",
  SI_TEMPER_DESTINATIONS_SETTINGS_VWW_PIN_WW_SHRINE_TOGGLE_TT:
    "This is for turning Werewolf Shrines on/off on the maps",
  SI_TEMPER_DESTINATIONS_SETTINGS_VWW_VAMP_HEADER: "Vampire Altars",
  SI_TEMPER_DESTINATIONS_SETTINGS_VWW_WWVAMP_HEADER: "Vampire and Werewolf spawns",
  SI_TEMPER_DESTINATIONS_SETTINGS_VWW_WW_HEADER: "Werewolf Shrines",
  SI_TEMPER_DESTINATIONS_SET_REQUIREMENT: "<<1>> traits required",
  SI_TEMPER_DESTINATIONS_FISHING_FOUL: "Foul Water",
  SI_TEMPER_DESTINATIONS_FISHING_FOUL_BAIT: "Crawlers/Fish Roe",
  SI_TEMPER_DESTINATIONS_FISHING_HWBC: "Crab-Slaughter-Crane",
  SI_TEMPER_DESTINATIONS_FISHING_LAKE: "Lake",
  SI_TEMPER_DESTINATIONS_FISHING_LAKE_BAIT: "Guts/Minnow",
  SI_TEMPER_DESTINATIONS_FISHING_OCEAN: "Ocean",
  SI_TEMPER_DESTINATIONS_FISHING_OCEAN_BAIT: "Worms/Chub",
  SI_TEMPER_DESTINATIONS_FISHING_RIVER: "River",
  SI_TEMPER_DESTINATIONS_FISHING_RIVER_BAIT: "Insect Parts/Shad",
  SI_TEMPER_DESTINATIONS_FISHING_UNKNOWN: "- unknown -",
  SI_TEMPER_DESTINATIONS_SETTINGS_SELECT_TEXT_ONLY: "Text only!",
  SI_TEMPER_DESTINATIONS_POITYPE_AOI: "Area of Interest",
  SI_TEMPER_DESTINATIONS_POITYPE_AYLEID_WELL: "Ayleid Well",
  SI_TEMPER_DESTINATIONS_POITYPE_BRAWL: zo_strformat(achievementName(1247)),
  SI_TEMPER_DESTINATIONS_POITYPE_BREAKING_ENTERING: zo_strformat(achievementName(1349)),
  SI_TEMPER_DESTINATIONS_POITYPE_CHAMPION: "Champions/Dungeon Bosses",
  SI_TEMPER_DESTINATIONS_POITYPE_COLLECTIBLE: "Collectibles",
  SI_TEMPER_DESTINATIONS_POITYPE_CRAFTING: "Crafting Location",
  SI_TEMPER_DESTINATIONS_POITYPE_CRIME_PAYS: zo_strformat(achievementName(869)),
  SI_TEMPER_DESTINATIONS_POITYPE_CUTPURSE_ABOVE: zo_strformat(achievementName(1383)),
  SI_TEMPER_DESTINATIONS_POITYPE_DARK_BROTHERHOOD: "Dark Brotherhood",
  SI_TEMPER_DESTINATIONS_POITYPE_DEADLANDS_ENTRANCE: "Deadlands Entrance",
  SI_TEMPER_DESTINATIONS_POITYPE_DELVE: "Delve",
  SI_TEMPER_DESTINATIONS_POITYPE_DOLMEN: "Dolmen",
  SI_TEMPER_DESTINATIONS_POITYPE_DRUIDIC_SHRINE: "Druidic Shrine",
  SI_TEMPER_DESTINATIONS_POITYPE_DWEMER_RUIN: "Dwemer Ruin",
  SI_TEMPER_DESTINATIONS_POITYPE_EARTHLYPOS: zo_strformat(achievementName(1121)),
}
