import type { Finding } from "../finding.page-type.types.ts"

export const aFolderSitsBesideRatherThanUnderThePageDeclaringItAPart = {
  id: "01a08808-c77b-7725-9fff-3f60cc2e9b38",
  pageTypeSlug: "finding",
  slug: "a-folder-sits-beside-rather-than-under-the-page-declaring-it-a-part",
  domain: "relation-property/parts",
  claim:
    "In six places the folder tree and the parts tree disagree: a folder sits beside, or above, the page that names it a part rather than under it. Nothing refuses the declaration, because a part is judged only where the two trees meet, so the disagreement is invisible until a folder shape reads the folder above.",
  evidence:
    'A folder shape asks only what the page directly above a folder declares. `holdingOver` in `checks/code-checks/pages/folder-matches-a-shape/folder-matches-a-shape.code-check.code.ts` reads the one page sitting in the parent folder, and `a-domain-with-its-parts` keeps a subfolder only where that page\'s own `parts` names it. A declaration written on a page in a sibling folder is read by nothing, so it neither clears the folder nor is refused for failing to.\n\n`seat-system/seat-turn/` holds `seat-turn.domain.ts` and is named a part by `seat-system/seat-observation/seat-observation.domain.ts`, which states `parts: ["domain/seat-turn", "list/idle-live-seat"]`. The declarer is a sibling folder, so `seat-system` reads no declaration for `seat-turn` and counts it among its stray subfolders.\n\nFour page types under `domains/standard-agent-english/` are named parts by `domains/standard-agent-english/terms/standard-agent-english-term.domain.ts`, a folder one level beneath them: `allowed-terms`, `banned-terms`, `common-language-terms` and `foreign-name-terms`. `domains/standard-agent-english/non-term-kinds/` is named a part by `domains/standard-agent-english/non-term/standard-agent-english-non-term.domain.ts`, a sibling. All five are counted stray by `domains/standard-agent-english`, which the refusal states as `6 subfolders are no part `standard-agent-english` declares: allowed-terms, banned-terms, common-language-terms, foreign-name-terms, non-term-kinds, terms`.\n\nEach one has two mends and they are not the same mend. Either the folder moves under the page that declares it, which puts `seat-turn` inside `seat-observation` and the four term types inside `terms`, or the declaration moves up to the page above the folder, which puts them on `seat-system` and on `standard-agent-english`. The first says the parts tree is right and the folders drifted. The second says the folders are right and the declarations drifted. Six landings of the mechanical kind were made against this class today by moving the declaration, in `services` and in `seat-system`, and in every one of those the module sat under the page that should declare it and the declaration sat too high. These six are the other shape of the same fault and no one has ruled which way they go.',
} as const satisfies Finding
