import type { Finding } from "../finding.page-type.types.ts"

export const aFolderMoveLeavesAPathSpelledAsDataStaleAndNoGuardReadsIt = {
  id: "01a08864-af81-7f30-ab3b-00862757bc03",
  pageTypeSlug: "finding",
  type: "finding",
  slug: "a-folder-move-leaves-a-path-spelled-as-data-stale-and-no-guard-reads-it",
  domain: "domain/change",
  claim:
    "`move-folder` rewrites relative import specifiers and a manifest's `exports` targets. It does not rewrite a folder path spelled as data — a string in a page's property, a path in a JSON deploy file, a constant in a module body outside the moved folder. `folder-not-left-named` does not catch these either, because it judges only bodies the move writes, and a speller outside the moved folder is a body the move does not write. So a folder move lands green while leaving stale paths behind it. This has already shipped a container command pointing at a directory that is not there.",
  evidence:
    'The guard\'s reach. `move-folder.change-mechanical-folder.ts:79` gives the invariant as `A body the move writes still naming that folder refuses the move`. `movedInto` at `move-folder.change-mechanical-folder.code.ts:28-37` builds the move from `world.under(at)`, so the bodies the move writes are the files inside the moved folder plus the importers whose relative specifiers it respells. A file that names the folder as data and neither sits inside it nor imports from it is in neither set.\n\nAlready shipped, before this session. Commit `970930951e2` moved `infrastructure/auth-proxy/auth-proxy-server` to `.../server`. `infrastructure/networks/auth-proxy/deploy/dockerfile-extensions.json` carried `runtime_cmd` naming `auth-proxy-server/`, a JSON string in a file the move did not write. It was not respelled and the move landed. The container command has pointed at a path that is not there since. Repaired this session in `45dd3fe67f9`.\n\nHit again, twice, this session. `infrastructure/backup-retention` moving under `infrastructure/storage/backups/` left `infrastructure/dockerfiles/built-images/gfs-promoter/gfs-promoter.built-image.ts` spelling `folder: "infrastructure/backup-retention"` — a page property whose whole value is a repository path. `infrastructure/auth-proxy` moving under `infrastructure/networks/` left `auth-proxy.built-image.ts` the same way. Both moves landed green. Repaired in `1e1b644c0d2` and `9f422941a50`.\n\nThe shape of the spellers. Three kinds appeared, none reachable by import rewriting: a `folder` property on a `built-image` page whose value is a path; a `runtime_cmd` string inside a JSON deploy file; and a module constant such as `const REPO_PAGES = "infrastructure/git-repos/repos/pages"` at `pages/checkout-roots/checkout-roots.module.code.ts:10`, which the `git-repos` move left stale and which is stale yet, because editing that file draws `no-index-path-spelled` on its `readdirSync` at line 33.\n\nWhat a mend would need. Either the move reads every body in the tree for the folder path spelled as a string literal and refuses or respells, or a check outside the move judges path-shaped string literals against the tree. The second was there once: `the-check-for-stale-path-literals-was-ablated-hours-before-it-was-needed` records `repo-paths` being ablated on 2026-09-03 with its scanner `ts-path-literals` kept and unread. That finding is about the ablation. This one is about `folder-not-left-named` being unable by its shape to cover the gap the ablation opened, since it reads only what the move writes.\n\nNot measured. No count was taken of how many stale path literals the tree currently holds, and no reading was taken of whether `ts-path-literals` still runs correctly. Four of these were found by hand, one per move, by grepping the old path after each landing.',
} as const satisfies Finding
