import type { Finding } from "../finding.page-type.types.ts"

export const aLandingThatMintsAnIdCannotBeCheckedByComparingDiskAgainstTheBodyHandedIn = {
  id: "01a081f7-f3c6-734b-866b-772daa0024d2",
  pageTypeSlug: "finding",
  slug: "a-landing-that-mints-an-id-cannot-be-checked-by-comparing-disk-against-the-body-handed-in",
  domain: "domain/id-minting",
  claim:
    "A module that lands a page body and then checks the file on disk against the body it handed in cannot have its landing work the id out. The minting address inserts the id into the body before writing, so the file on disk is never equal to the body handed over, and the check throws on every page newly created. That check is why such a module writes an id of its own: the hand-written id is not carelessness but the only way to make the two bodies agree. Pointing such a module at the minting address without first changing the check turns a working landing into a failure on the created path alone, which is the path least often exercised.",
  evidence:
    "Read 2026-09-08 on the akasha checkout, at a HEAD carrying `a59d1810e1`.\n\n`alan/harness/inboxes/email-entry-writing/email-entry-writing.module.code.ts` names the non-minting `change-mechanical-file/add-file` at line 14 and writes an id by hand at line 158 into an `.email-entry.ts` page body. Its page declares at lines 52-54 that the landing's report is checked against the file on disk, and the check at line 142 compares the file on disk against the body handed in.\n\nFolding that same body through `change-mechanical/add-file-of-any-kind` in memory answered the id `01a081f2-6e3e-796c-9941-23e7180739f0` and a body that is not the body handed in: the change inserts the id at its line 37 before writing. So deleting the id written by hand and naming the minting address would let the commit succeed and then throw at line 142 for every day's entry newly created. The patched path is unhurt, because a body already carrying an `id` is passed through unchanged at the change's line 34.\n\nThe failure would be quiet as well as late. `landPage` is called without `await` at lines 157 and 168, so the throw arrives as an unhandled rejection rather than as a refusal anyone reads.\n\nThe same shape sits elsewhere. `seat-system/messaging/message-file/message-file.module.code.ts` writes a uuid by hand at line 98 and derives the page slug from it at line 99, which becomes the landing path at lines 116 and 126 and the value answered to the caller at line 129. There the uuid cannot be deleted at all; only the `id` key at line 107 could go, and the uuid would have to remain to name the file.\n\n`mobile-cli/cut-fingerprint/cut-fingerprint.module.code.ts` names the non-minting address at line 11 and writes an id by hand at line 142 for a page that does not exist, and its page declares that as meant at lines 60-62.\n\nTen modules were surveyed as writing an id by hand, and the survey read most of them as merely redundant, working an id out and then handing it to an address that works one out anyway. These three are not redundant. Each has a second reason for the id it writes that survives pointing at the minting address, and one of them declares that reason on its own page.",
} as const satisfies Finding
