import type { Finding } from "akasha/domains/findings/finding.page-type.types.ts"

export const aLintAuditFallsShortWhenALandingMovesAPathWhileTheLinterWalks = {
  id: "01a095f1-b21b-7d0d-9178-763b3175d66b",
  type: "finding",
  slug: "a-lint-audit-falls-short-when-a-landing-moves-a-path-while-the-linter-walks",
  domain: "domain/check",
  claim:
    "A `lint-clean` audit falls short in about two rounds of five, and the cause is a landing moving a path while the linter reads the live tree rather than any fault in the code being linted. A round that fell short judges nothing about lint quality, so a real lint fault can sit unseen across several rounds. It is not silence: the audit names a check that could not run apart from a check that refused, every time it happens. That is why it went unremarked. A check answering nothing reads the same as a check answering something until the answers are counted.",
  evidence:
    "Read 2026-09-12 from `checks/code-checks/pages/lint-clean/lint-clean.code-check.audit.logs.uncommitted.jsonl`, which holds one row per audit round carrying `ranAt`, `wallMs`, `cpuSeconds` and `refusals`, and from the audit service's journal.\n\nHow often. 70 rounds from 2026-09-10T17:10Z to 2026-09-12T13:47Z, every one of them logged, and every round the journal names has a row, so the check ran in all of them and was never skipped. Rounds answering one refusal: 19 of 70 overall, 17 of 46 since 2026-09-11T21:00Z, and 16 of 37 on 2026-09-12 UTC. The rate rose as the swarm got busier.\n\nWhy that one refusal is the fall rather than a finding. Since 2026-09-11T21:00Z every non-zero round is exactly 1, seventeen times running, never 2 and never 3. The earlier era answers 14, 15, 24 and one round of 926, which is the shape real findings take. The check's own page says every path the linter could not open is answered as one run that fell short, and that a run that fell short says so rather than naming a file at fault.\n\nThe round that shows the cause. The round beginning 2026-09-12T12:10:38Z ran 71 seconds and fell short. Twenty-three commits landed inside that window. Two of them renamed folders that reading was holding: `bfc3edc40b7` at 12:11:07Z moved `pages/indexes/index-keeping` to `pages/indexes/keeping`, 29 seconds in, and `3dd26386629` at 12:11:39Z did the same for `infrastructure-calls`. The path list was right when it was gathered and stale half a minute later.\n\nNot a timeout. Wall times across these rounds run 56 to 76 seconds against `audit: { maxCpuSeconds: 180 }`, and `cpuSeconds` is under one second in every row.\n\nNot silence. `checks/modules/audit-verdict/audit-verdict.module.code.ts:64` answers clean only where a check neither fell short nor refused, and `checks/modules/audit-asking/audit-asking.module.ts:73` states that a check that could not run is named apart from a check that refused.\n\nWhat the design already reaches, and what it does not. `lint-clean.code-check.audit.code.ts:29-38` gathers the folders of every page type stating it is mortal and skips them, because the check's page says a page that can go while the tree is read is judged by no reading of the tree. That covers pages that go. It does not reach an ordinary module folder renamed by a landing, which is what these rounds lose.\n\nThe condition a mend would meet: a check that could not open a path a landing moved is run again rather than answered as fallen short. That is the rule this repository already applies to a check that threw because a concurrent landing left a file momentarily empty. Whether to run it again is a decision about what an audit round may cost rather than a fault to mend, since at this rate about two rounds in five would read the whole tree twice, and the code carrying it, `checks/modules/audit-serving` and `checks/modules/checking`, is shared by every check.",
} as const satisfies Finding
