import type { Finding } from "../finding.page-type.ts"

export const aMechanicalLandingRewritesAFunctionExpressionIntoAnArrowThatCannotBeConstructed = {
  id: "01a06959-659e-7e89-9a8b-bce7deaa69d0",
  pageTypeSlug: "finding",
  slug: "a-mechanical-landing-rewrites-a-function-expression-into-an-arrow-that-cannot-be-constructed",
  domainSlug: "workspace-package/code-system",
  claim:
    "`landedMechanically` does not only format what it lands, it applies lint fixes, and one of them changes behaviour. A `function () {}` handed in as the target of a `new Proxy(...)` lands as `() => {}`. An arrow function is no constructor, so `new` through that proxy throws `TypeError: not a constructor` where it used to answer. The landing reports this as `formatted ... as it landed — what stands there is not what was handed in`, which reads as whitespace. A change-mechanical landing runs no check, so nothing else looks.",
  evidence:
    "Measured 2026-09-03 in this repository, carrying `tools/extension-panel-stub.mjs` in as `akasha/editor-extension/vscode-stub/vscode-stub.javascript-module.javascript.mjs` at commit `d6313506`.\n\nWHAT WAS HANDED IN, at line 17 of the body: `new Proxy(function () {}, { get: ..., apply: () => anything(), construct: () => anything() })`. WHAT LANDED: `new Proxy(() => {}, { ... })`. Confirmed by diffing the body handed in against the file on disk. The whole rest of the 367-line diff is tabs to spaces, single to double quotes, line wrapping, dropped semicolons and a sorted `export {}` list — all inert. This one line is not.\n\nTHE BREAK, PROVED WITH A CONTROL. Two proxies were built under node, one over an arrow and one over a function expression, both carrying the same `construct` trap. Arrow-backed: `TypeError: make(...) is not a constructor`. Function-backed: `new () -> function`. So it is the target and not the trap.\n\nTHE STUB'S OWN ARMS, four of them, three of which had to fail. Subject, the landed file after repair: TreeItem kept its label, the status bar slot kept its text, and `new` through the proxy stood. Control, the same file with an arrow behind the proxy: `TypeError: reached is not a constructor`. Control, the same file whose fallthrough answers undefined: `Cannot read properties of undefined`. Control, the same file whose tree item drops its label: `TreeItem lost its label`. All three fired, so the subject passing is sighted.\n\nWHY IT MATTERS HERE. This stub is what an extension activates against when a panel is read back. Every member the extension reaches that the stub does not name falls through to that proxy, and a `new vscode.Something()` on the fallthrough is ordinary. The failure would have read as the extension throwing rather than as the harness being broken.\n\nWHAT WAS DONE. The proxy now stands on a named `function nothing() {}` declared above it. `useArrowFunction` rewrites function expressions and leaves declarations alone, and the repair landing drew no `formatted` line, so the shape survives a second pass.\n\nWHERE THIS BITES BEYOND ONE FILE. Any migration carrying a file in byte-for-byte is carrying it in through this rewriter. A `function` expression standing where a constructor is needed is the shape at risk, and `new Proxy`, `Object.create` and anything reflective over `.prototype` are where it stands. A landing reporting `formatted` says a file changed and does not say how.\n\nNOT MEASURED. Which rule set the landing applies, and whether any other behaviour-changing fix is in it. Only `useArrowFunction` was caught, and it was caught by reading the diff rather than by anything reporting it.",
} as const satisfies Finding
