import type { Finding } from "akasha/domains/findings/finding.page-type.types.ts"

export const aPinnedWorktreePinsTheEntryModuleAndNothingItImports = {
  id: "01a09cb5-2fa3-7c5c-b1d4-35a3278b66ac",
  type: "finding",
  slug: "a-pinned-worktree-pins-the-entry-module-and-nothing-it-imports",
  domain: "domain/infrastructure",
  claim:
    "Every workstation unit execs one module inside `.git/trees/service-workstation`, and the pin reaches that file alone. The worktree holds no `node_modules` of its own, so bun walks up to the checkout's, where `akasha` is an absolute symlink to the checkout. Every `akasha/...` specifier the entry module imports therefore loads from the live checkout, at whatever the checkout holds that second, while `WorkingDirectory` and `AKASHA_ROOT` name the checkout too. Six worktrees cost 23 GB and buy a one-file pin.",
  evidence:
    "THE UNIT, READ 2026-09-13. `systemctl --user cat code-editor-data-watcher.service` gives `ExecStart=/usr/bin/env bash -c 'exec bun /var/home/walton/repos/akasha/.git/trees/service-workstation/infrastructure/services/workstations/modules/service-running/service-running.module.code.ts code-editor-data-watcher'`, with `WorkingDirectory=%h/repos/akasha` and `Environment=AKASHA_ROOT=%h/repos/akasha` above it. One file out of the worktree; the root the code reads is the checkout.\n\nWHAT THE WORKTREE LACKS. `.git/trees/service-workstation/node_modules` is not there. `du -sh` reads 3.9 GB for that worktree and 23 GB for `.git/trees`.\n\nWHAT THE CHECKOUT'S LINK IS. `node_modules/akasha` is a symlink to `/var/home/walton/repos/akasha`, 29 bytes, dated 2026-09-12 06:41. It is absolute, so it names the checkout from wherever it is reached.\n\nMEASURED 2026-09-13. `block-akasha-shell-writes` refuses a bun run naming a path under `.git/trees`, so I built the same shape in the scratch folder: a root whose `node_modules/pkgname` is an absolute symlink back to that root, a module at `deep/pkg/mod.ts` exporting `LIVE CHECKOUT`, a nested `gitdir/trees/pinned/` carrying its own `deep/pkg/mod.ts` exporting `PINNED TREE` and no `node_modules`, and an entry at `gitdir/trees/pinned/a/b/c/entry.ts` importing `pkgname/deep/pkg/mod.ts`. Run under bun, that entry printed `import gave: LIVE CHECKOUT` and `Bun.resolveSync` answered the root's copy. The copy at the identical relative path inside the pinned folder was never reached.\n\nNOT MEASURED. Whether any entry module is a leaf. `service-running.module.code.ts` is the entry for every workstation unit and it imports, so the fleet's pin is one file deep; I did not read the entries of the other five worktree kinds. I did not measure what advancing a worktree costs, only what one holds.",
} as const satisfies Finding
