import type { Finding } from "akasha/domains/findings/finding.page-type.types.ts"

export const aSpecifierSpelledFromTheRootIsAnsweredAsLandingNowhereByThirteenOfSixteenCallers = {
  id: "01a08e8e-4f87-7977-b6d7-df6713f38c1b",
  pageTypeSlug: "finding",
  type: "finding",
  slug: "a-specifier-spelled-from-the-root-is-answered-as-landing-nowhere-by-thirteen-of-sixteen-callers",
  domain: "domain/check",
  claim:
    "`landingOf` answers a specifier spelled from the root as landing nowhere unless its caller hands in a naming built from a manifest, and thirteen of its sixteen callers hand in none, so a check that reads nowhere as nothing to judge is blind to every import a file spells that way.",
  evidence:
    "`landingOf` in `code-system/code-specifier/code-specifier.module.code.ts:76` joins a relative specifier onto the file's folder and answers every other specifier out of the `naming` handed in, which defaults to `NAMING_NONE`, an empty map. The root manifest is called `akasha` and exports `./*` to `./*`, so `akasha/X` means the repository path `X`; nothing but a naming read off that manifest says so, and the module page declares as much: `A caller handing in no naming is answered as naming no package.` and `A specifier spelt from the root is answered by the naming alone.`\n\nSixteen callers. Three hand in a naming: `move-code-export.change-mechanical.code.ts:304`, `extension-host-reaches-no-bun-code.code-check.decision.code.ts:181`, and `pages/indexes/import/index-import.index.code.ts:26`. The other thirteen hand in none, and three of those read nowhere as skip and `continue`: `no-import-cycle.code-check.decision.code.ts:64`, `import-reaches-a-file.change-guard.code.ts:85`, and `require-import-extension.code-check.decision.code.ts:33`. So a cycle through root-spelled imports is uncounted, a guard no longer catches an import naming a file that is not there, and a specifier written without its extension goes unjudged. `package-reached-where-named.code-check.decision.code.ts:168` and `client-reaches-pages-through-its-hooks.code-check.decision.code.ts:71` are blind the same way.\n\nOne caller reads nowhere the other way round: `packageOf` in `manifest-names-what-is-reached.code-check.decision.code.ts:95` returns null as soon as `landingOf` answers anything, so there nowhere means keep going, and mending `landingOf` turns that caller's behaviour the other way.\n\nTwo callers have already worked around the fault by hand rather than mending it. `browser-code-reads-the-environment-by-a-name.code-check.decision.code.ts:188` cuts the first part off any specifier `landingOf` refused and asks whether that tail is a known path. `change-imports.change-mechanical-file-content.code.ts:23` holds a `ROOT` constant spelled `akasha/` and resolves root-spelled specifiers itself. Both are the naming, rewritten locally, by callers that could not do without it.\n\nThe blindness widens as the repository is rewritten. The `no-file-names-another-file-by-a-relative-path` intent on `initiative/aranya-one-package` is down from 85324 refusals to 3261 over 124576 files, so nearly every specifier left is spelled from the root.",
} as const satisfies Finding
