import type { Finding } from "akasha/domains/findings/finding.page-type.types.ts"

export const aUnitThatFailsAndSucceedsWithinATimerPeriodIsToldToNobody = {
  id: "01a095f0-c2e1-72dc-8f86-8146fd57c1a9",
  type: "finding",
  slug: "a-unit-that-fails-and-succeeds-within-a-timer-period-is-told-to-nobody",
  domain: "domain/service",
  claim:
    "A unit that fails and runs again within one timer period is well again before the watcher's next sample, so its failures are told to nobody and nothing keeps a count.",
  evidence:
    "`workstation-deploying.service` failed nine times between 07:15:07 and 07:46:49 on 2026-09-12, and `service-watching` told nobody. The outage ledger at `~/.local/state/workstation-services/service-outages.json` holds `{}`, so the watcher recorded no outage at all. The two tellings it has ever sent about this unit went to aranya at 06:31:16 and 06:45:11, both before that window opened.\n\nThe unit is a `oneshot` on `workstation-deploying.timer`, which fires every 60 seconds, and `service-watching.timer` samples every 60 seconds. `brokenIn` at `infrastructure/services/workstations/service-health/service-health.module.code.ts:102` reads `ActiveState`: `failed` is broken, `active`, `activating` and `reloading` are well, and a unit with a timer reading `inactive` is well. A oneshot reads `failed` only between the run that failed and the next start, so the watcher sees a failure only by sampling inside that window. At 07:23:22 a run failed and the next run began at 07:23:23, leaving one second. While a deploy is in flight the unit reads `activating`, which is well, and a deploy runs for minutes.\n\nThe nine failures were four faults rather than one. Two were `akasha deploy` running past the 300 seconds its page allows, at 07:15:07 and 07:21:05. One was a scope name loaded with no deploy holding it, at 07:15:09, mended by `602c17195f4`. Six were `akasha deploy service-workstation` refusing because the tests it runs were red, at 07:23:22, 07:30:06, 07:33:55, 07:40:44, 07:43:46 and 07:46:49, over six different commits; the last reported 72 of 1009 tests failing across six test files. In those six the loop was right and the repository was red, and a unit marked failed for that reads exactly like a loop that is broken.\n\nThe failures ended without a mend. The tests are red now: the `tests-pass` verdict at `99172024da6`, recorded 2026-09-12T14:01:24.259Z, refuses with nine test files failing. `akasha deploy` runs only the tests beside what the change carries, so whether a tick refuses depends on which files the swarm landed since the deployed commit rather than on anything having been put right.\n\nA watcher that samples the current state of a unit sees a fault only while that fault is the unit's current state. A unit that fails and runs again on a short timer is well again before the next sample, so its outage is told to nobody and nothing keeps a count of how often it broke.",
} as const satisfies Finding
