import type { Finding } from "../finding.page-type.ts"

export const alansTileRouteRefusesJennysCredentialByDesignRatherThanByAge = {
  id: "01a05ce0-05f3-746e-ad0b-41025105eb09",
  pageTypeSlug: "finding",
  slug: "alans-tile-route-refuses-jennys-credential-by-design-rather-than-by-age",
  domainSlug: "router-app/alan-web",
  claim:
    "The two tile routes shared their answering but never their admission. Jenny admits her ring on one shared secret in a header. Alan admits his on a per-device secret resolving to a person, then a route-access grant. So the copy collapsed onto a handed-in guard rather than a handed-in secret. A shared secret presented to Alan's tile route is refused at HEAD as much as in production, and no deploy turns that 401 into a 503: it is what his route is for rather than what its build is behind on.",
  evidence:
    "alanwalton/web/app/routes/api.categorization.ts was 44 lines and is now 7 over @akasha/readout-system/readout-categorization, as smilingjenny/web/app/routes/api.categorization.ts already was. The 44 lines duplicated the module exactly: same 45-minute staleness window, same 503 body, same 200 shape, same no-store, same readout name. Only the first line diverged. Jenny hands in ringCredential() and the module compares SMILINGJENNY_RING_CREDENTIAL against X-Ring-Credential. Alan calls guardReadout in alanwalton/web/app/readout-credential/lib/readout-credential.server.ts, which resolves X-Device-Secret to a userId and then asks holdsRouteAccess for READOUT_FEED, default deny. His widget sends X-Device-Secret, never X-Ring-Credential. No ALANWALTON_RING_CREDENTIAL is named anywhere in the repository and no such key stands in alanwalton-secrets, so flattening him onto the shared secret would have refused his own tile and admitted anyone holding one static string. The module now carries answerCategorizationAdmittedBy, taking the guard itself; answerCategorization delegates to it with the secret guard, so Jenny is unchanged. Run over real HTTP against Alan's own loader, a bare call, an X-Ring-Credential call and an X-Relay-Secret call each answer 401 no-store, refused by the device-secret path. Against production, alanwalton.com and smilingjenny.me both answer 401 uncredentialed, and both relay routes accept READING_RELAY_SECRET, answering 400 on a body that is no reading. Alan runs f25c8ffc04, Jenny b4289a8e7a.",
} as const satisfies Finding
