import type { Finding } from "../finding.page-type.types.ts"

export const anInstallThatNeverPrunesLeavesEveryRenamedPackageResolvable = {
  id: "01a07ce8-4293-77af-9c39-a58cc6557426",
  pageTypeSlug: "finding",
  type: "finding",
  slug: "an-install-that-never-prunes-leaves-every-renamed-package-resolvable",
  domain: "workspace-package/check",
  claim:
    "A package rename leaves a link under the dead name, and nothing takes that link away, so a name no manifest states goes on resolving for as long as the folder it points at remains.",
  evidence:
    "Measured 2026-09-07 in the working checkout. `node_modules/@akasha` holds 294 entries and every one is a symlink, while only 285 names are stated by any tracked manifest. The nine the manifests do not state are `code-system`, `pages-system`, `persona-system`, `person-system`, `story-tower`, `story-tower-core`, `story-tower-engine`, `story-ui` and `wandering-inn`.\n\nSix of the nine dangle and answer TS2307, which is loud. Three point at live folders and resolve: `code-system` at `code-system`, `pages-system` at `pages`, `persona-system` at `personas`. Each is a name a rename took away, and each still reaches the package that rename renamed.\n\nNothing imports any of the nine today, over every `.ts` and `.tsx` the repository tracks outside the findings. The hole is latent rather than live.\n\nThe reason a stale link matters to a check is that `linkedOf` reaches `realpathSync` through `realOf` when the placement misses a name. A check built to judge an in-memory overlay of what a change leaves therefore asks the disk where a package sits, and the disk answers with what an earlier rename left. Proved in a scratch checkout by renaming a package and importing the old name: typecheck reported clean, the same file with a seeded fault refused with TS2345 typed through the renamed-away folder, and a name that never existed refused with TS2307. The instrument was sighted throughout; it resolved through the corpse.\n\nThe rename command is not what leaves the corpse. It rewrites every importer and every dependent manifest in one change. What leaves the corpse is the install that follows a landing, which adds the new link beside the old one and takes nothing away.\n\nNo check backs the rename up. Read 2026-09-09: `manifest-names-what-is-reached` does not refuse a cross-package import of a workspace name the importer's manifest does not carry. Its `unnamedIn` opens `if (names.has(one)) continue`, and `refusalsIn` builds `names` from `byName.keys()`, which is the name of every package the index files, so a reach at any name any manifest states is waived whoever spells it. Live instance: `alan/web/routes/readout-relay/readout-relay.route.code.ts:6` imports `@akasha/readouts`, `alan/web/package.json` names no such dependency, and both are clean at HEAD.\n\nTwo things this does not measure. Whether a same-package import by a dead name is refused by anything, since no manifest entry contradicts it. And whether a manifest edited as a file rather than through the rename command leaves the same gap.",
} as const satisfies Finding
