import type { Finding } from "../finding.page-type.types.ts"

export const noActRelocatesAPageType = {
  id: "01a08852-3504-7fd0-8f03-3e5a03433b0a",
  pageTypeSlug: "finding",
  type: "finding",
  slug: "no-act-relocates-a-page-type",
  domain: "workspace-package/change",
  claim:
    "No change relocates a page type, so every page-type folder in the repository is stuck where it sits. Moving the folder or the page-type file is refused because the generated `.page-type.types.ts` beside it would be written by hand; removing that types file first is refused because the page type's own pages import it; and no act relocates a page type without doing one or the other.",
  evidence:
    'Met 2026-09-09 trying to move four page-type folders out of `alan/books/all-about-alan/`. All three refusals were run rather than reasoned about.\n\n`move-folder` from `alan/books/all-about-alan/experiments` to `all-about-alan/experiments`: "`all-about-alan/experiments/all-about-alan-experiment.page-type.types.ts` is generated, and a generated file is written by the thing that generates it rather than by hand".\n\n`move-page` on `alan/books/all-about-alan/experiments/all-about-alan-experiment.page-type.ts` alone: the same refusal, because `page-type` declares `types: "ts"`, so the generated file is a claimed part and `move-file-page` carries it. `move-page` reaches `change-mechanical/move-file-of-any-kind`, which dispatches a page-type path to `change-mechanical/move-file-page-type`, which delegates straight to `move-file-page`.\n\n`remove-file` on `alan/books/all-about-alan/experiments/all-about-alan-experiment.page-type.types.ts`, to clear it before moving: "`alan/books/all-about-alan/experiments/pages/exp4-voice-reward-dose/exp4-voice-reward-dose.all-about-alan-experiment.ts` imports `...page-type.types.ts`, and `...page-type.types.ts` holds no body after".\n\nThe guard is `changes/guards/pages/generated-file-not-written/generated-file-not-written.change-guard.code.ts:16-22`. It walks the edits and refuses any whose `kind` is `replace` and whose path `generatedIn` answers for. A move writes a `replace` at the destination, so relocating a generated file reads to the guard exactly like writing one by hand.\n\nNo act closes the loop. The runnable changes include `rename-page-type`, which renames in place and never leaves the folder, and `add-page-type-types`, which regenerates the file where the page type already is. Neither relocates, and there is no `move-page-type`.\n\nWhat does work, and was run: `move-folder` on the page type\'s `pages/` and `properties/` subfolders moves them cleanly, and it carried a non-code sidecar, `exp4-voice-reward-dose.all-about-alan-experiment.line-set.json`, with its page. So only the page-type file and its generated types are stuck; everything under the page type travels.\n\nNot established: whether any page-type folder has ever been relocated, and if so how. I did not search the history for one.',
} as const satisfies Finding
