import type { Finding } from "../finding.page-type.ts"

export const noPassportPathChosen = {
  id: "01a06555-9f3e-7818-94f0-87a5bca66b32",
  pageTypeSlug: "finding",
  slug: "no-passport-path-chosen",
  domainSlug: "domain/all-about-alan",
  claim:
    "Ninety-six files of second-passport research narrow forty-two countries to a handful of survivors and stop before anyone picks one. The two synthesis files rank survivors by clock, cost and financial bar, and record that the two cannot be had together: no surviving EU active-income path meets both a clock under seven years and a city cost under €4,500 a month. Nothing records a country chosen, a budget, a date, a first act, or which criterion the family weighs most.",
  evidence:
    'Read 2026-08-16. I read `active-income.md`, `passive-income.md` and the four summary files myself; the ninety country files under `eu/` and `other/` were read by two delegated seats reporting back, and I checked two directly.\n\nThe shortlists. `active-income.md`: "**Fastest 5 (clock):** 1. **Uruguay 3y family-residence** — ~3.5–4y … 2. **Belgium 5y CBN (Flanders)** — ~5.5y … 5. **Poland (JDG)** — ~8y". `passive-income.md`: "**Fastest 3 (clock):** 1. **Uruguay** … 2. **Luxembourg Investor Track** — ~5.7y … 3. **France Talent Investor** — ~7y."\n\nThe trade-off that does not resolve, `active-income.md`: "**Sweet-spot (clock ≤7y AND city cost ≤€4,500/mo):** - **No surviving EU active-income path hits both thresholds simultaneously.** … - **Uruguay** is the sole sweet-spot survivor". And: "**No surviving EU active-income path has a no-language option.**"\n\nThe scale searched. `eu/citizenship/summary.md`: "27 countries surveyed; 13 retain at least one viable citizenship path AND a viable residency on-ramp". `other/citizenship/summary.md`: "15 non-EU countries surveyed; 2 retain at least one viable path".\n\nThe filters are attributed to Alan without a record of him stating them. `passive-income.md`: "Applicant wants optionality to layer digital-nomad / self-employment work on top." The summaries carry "no employer sponsorship, no endorsement, no >€500k capital" and the profile "married, three kids; family relocates together". No file cites him saying any of it.\n\n`other/citizenship/summary.md` on Uruguay: "**For the user\'s situation … this is the standout non-EU path.**" Nothing follows it. Both synthesis files close on "Decision matrix considerations".\n\nNot measured: I read only `projects/second-passport`. I did not check Alan\'s mail, calendar, finances or the rest of `all-about-alan`, so I cannot say no path was chosen — only that these files record no choice and no act. I verified no legal claim about any country.',
} as const satisfies Finding
