import type { Finding } from "../finding.page-type.ts"

export const noRouteThroughTheGateRemovesAnEmptyDirectory = {
  id: "01a081a1-7ad7-7dd8-8754-cea69a117bc3",
  pageTypeSlug: "finding",
  slug: "no-route-through-the-gate-removes-an-empty-directory",
  domainSlug: "workspace-package/change",
  claim:
    "No route through the akasha gate takes an empty directory away. `akasha change remove-file` takes files only and leaves the folder there; `akasha restore` refuses a path HEAD does not hold; the shell hook refuses `rmdir` inside the checkout as it refuses a write. Git tracks no directory, so an emptied folder is invisible to every check and to `git status`, and the only thing that sees it is `ls`. A folder emptied through the gate is therefore left in the working tree with nothing able to remove it.",
  evidence:
    "Measured 2026-09-08. `persona-system/` held 40 gitignored `*.persona.uncommitted.ts` sidecars the move to `personas/` left behind, one per persona slug at `persona-system/personas/<slug>/`.\n\nForty `akasha change remove-file` calls drafted cleanly and `akasha apply` folded them all in, answering `nothing was committed — the tree already holds what the change asked for`, which is right: the files were gitignored, so removing them changed nothing tracked.\n\nAfterwards `find persona-system -type f` counts 0 and `find persona-system -type d` counts 42: the root, `personas/`, and 40 empty slug folders.\n\n`rmdir persona-system/personas/*/` is refused by `block-akasha-shell-writes`, which names `akasha read`, `akasha apply` and `akasha restore` as the routes. `akasha restore --file-path persona-system` refuses with `HEAD holds no persona-system, so \\`akasha restore\\` has nothing to put back there`. The change acts are `add-copied-property-to-every-page`, `add-file`, `add-property-to-every-page`, `add-property-value`, `change-domain-parent`, `change-file`, `change-page-page-type`, `change-page-property`, `change-page-property-text`, `move-folder`, `move-folder-package`, `move-page`, `remove-file`, `remove-package-alias`, `remove-page`, `remove-page-type`, `remove-property-value`, `rename-code-token`, `rename-package`, `rename-page`, and none of them removes a folder.\n\n`akasha audit --check folder-matches-a-shape --file-path persona-system` refuses with `persona-system is no file this repository holds, and no folder holding one`, so the shape check never judges the empty skeleton either.\n\nThe same shape shows up in an earlier finding: `clearedOff` calls `rmdirSync`, which refuses a folder holding subfolders, so a move leaves a folder there too.",
} as const satisfies Finding
