import type { Finding } from "../finding.page-type.ts"

export const removingTheBareNameSearchEmptiedEveryPageTypeOfItsProperties = {
  id: "01a07353-48b3-79ee-91e0-fc018c3cf453",
  pageTypeSlug: "finding",
  slug: "removing-the-bare-name-search-emptied-every-page-type-of-its-properties",
  domain: "workspace-package/page",
  claim:
    "Taking the bare-name search out of `shapedIn` left 443 of 453 page types declaring no properties at all, and left every one of the 914 unique keys unfiled, because 2563 of the 2601 `pagePropertySlug` values in the tree name a property with no page type before it. Three of the four callers of `schemaOf` hand it a bare name, and each of the three answers a refusal by dropping the result rather than by refusing, so nothing failed loudly and 26 tests went green over the change that did it.",
  evidence:
    "`4eb997e9` took the search across page types out of `shapedIn` in `index-reading.module.code.ts`, so a name with no `/` in it came back refused. `09eb2c73` put the search back.\n\nThe search had four callers, not the one the commit message named. `declared-properties.module.code.ts:70` is the one that mattered: `sourceIn` hands `schemaFor` to `carriedFrom`, which reads `pagePropertySlug` off each entry of a page type's `properties` list at line 82 and asks `schemaOf` for it at line 86. Line 87 drops that property off the page type where the answer came back refused, and says nothing. `context/warrants/file-property/file-property.context-warrant.code.ts:36` and `context/warrants/file-property-file/file-property-file.context-warrant.code.ts:24` are the other two, both `runsOnRead` and `runsOnWrite`, and both answer a refusal with `continue` or `null`.\n\nMeasured against the tree with the search back in, running both arms over the 453 page types the index files, with a control arm that refuses nothing:\n\n  properties declared, whole:   9238\n  properties declared, control: 9238\n  properties declared, broken:  10\n  page types emptied outright:  443\n  unique keys, whole:           914\n  unique keys, broken:          0\n\nThe control equalling the whole arm is what says the instrument sees its subject; an earlier run of the same script answered 0 on every arm because `sourceIn(root, () => null)` reads no page values, and a blind arm and a clean arm read the same.\n\nThe 10 that survive are what is left of the 38 `pagePropertySlug` values that name a page type. The other 2563 name none. Those values are data, so no grep for `schemaOf` reaches them: the census counted the places the function is spelled and missed what the callers were handing it.\n\nTwo signals were already there before the change landed. `index-reading.module.ts` carries two invariants describing the search, `A name saying no page type costs one read for each page type the name might be filed under` and `An address stating no page type is answered under the one its caller names`; both were left alone while the code they describe went. And `declared-properties.module.code.ts:240` holds `schemaAmong`, the same search over an in-memory map, which was left in place, so the search was never removed from akasha at all: one of its two copies went, and the copy that went was the one 2563 values read through.\n\nThe order this puts on the work: the search goes after `pagePropertySlug` values name their page type, never before.",
} as const satisfies Finding
