import type { Finding } from "../finding.page-type.ts"

export const renamingAPageLeavesTheTypeThatPagesFileExportsSpelledTheOldWay = {
  id: "01a0819a-7ad4-7e87-a411-f123c197c1aa",
  pageTypeSlug: "finding",
  slug: "renaming-a-page-leaves-the-type-that-pages-file-exports-spelled-the-old-way",
  domainSlug: "page-type/change",
  claim:
    "`rename-page` restates a page's file name, its slug, the const its file exports and every importer's path, and leaves the type that same file exports spelled the old way. A property page exports both a const named from its slug and a type named from its slug, so half the rename lands, and every check passes because the two sides agree with each other. No other act mends it: `rename-code-token` refuses a page outright, answering that a page's export is its slug. The type has to be restated by hand together with every body importing it, in one landing, or the folder does not compile.",
  evidence:
    "Met 2026-09-08, renaming four coaching note properties.\n\nWHAT LANDED. `akasha change rename-page` handed `alan/values/health/fitness/coaching/notes/properties/coaching-note-active.boolean-property.ts` and `to: fitness-coaching-note-active` landed as `164dbf0892`. It carried the file, restated `slug`, renamed the const to `fitnessCoachingNoteActive`, and repointed both the import path and the `partSlugs` and `pagePropertySlug` entries in `fitness-coaching-note.page-type.ts`. Line 3 of the carried file still read `export type CoachingNoteActive = boolean`, and line 4 of the page type still read `import type { CoachingNoteActive }` against the new path. Every check passed, because both sides agree. They are simply both spelled for a page type deleted an hour earlier.\n\nWHY NO ACT MENDS IT. `akasha change rename-code-token` handed that same file answered ``alan/values/health/fitness/coaching/notes/properties/fitness-coaching-note-active.boolean-property.ts` is a page, and a page's export is its slug`. `changes/agent/file-content/rename-code-token/rename-code-token.change-agent.code.ts:90` admits only `.code.ts`, `.code.tsx`, `.test.ts`, `.test.tsx` and `.test-fixtures.ts`. That guard is right about the const, whose name is the slug, and wrong about the type, which nothing else carries.\n\nTHE REPAIR COST. Four `change-file` calls restating the four exported types each refused with TS2305 against the page type importing the old name, keeping their edits. A fifth restated the four imports and refused again, with four `noUnusedImports` and four TS2304. A sixth restated the four members, folded all six in, and landed as `a6bc529566`. Six calls and five refusals for what the rename should have carried in one.\n\nWHAT WOULD END IT. `rename-page` restates the type a page's file exports alongside the const, and repoints every body naming that type, in the same answer where it already repoints the importers' paths.",
} as const satisfies Finding
