import type { Finding } from "../finding.page-type.ts"

export const seedingAFaultAndWatchingItFireReportsGreenInThisSharedWorktree = {
  id: "01a063f0-2540-79bb-9942-7092618ed438",
  pageTypeSlug: "finding",
  slug: "seeding-a-fault-and-watching-it-fire-reports-green-in-this-shared-worktree",
  domainSlug: "domain/akasha",
  claim:
    "Break-and-watch, the one check that tells a real green from a blind one, returns a false green here. Three agents in one night applied a mutation, asserted from the file that it was in place, ran the test and were told nothing was broken. Re-running gave the correct fail. A seeded fault reported green does not merely fail to inform: it certifies a test as load-bearing when nothing was proved.",
  evidence:
    "Reported 2026-09-02 by two seats working different packages, each having hit it independently and chased it rather than accepted the green. I did not observe it myself and am recording their account.\n\nThe likeliest cause is the `restore-akasha-when-dirty` hook racing in a worktree shared by a dozen agents. It puts a changed and uncommitted file under `akasha/` back as HEAD has it, and it runs after whichever agent's command comes next rather than the one whose work it reverts. A mutation lives on disk uncommitted by design, so it is exactly what the hook takes. The usual recipe guards a no-op replace by asserting the mutated text is present; it does not guard a file restored between that assertion and the test run, and the two are separate calls.\n\nThe hook is firing at that rate. `.git/akasha-restored/` held eight timestamped folders between 19:50:53 and 20:14:48, and a seat running only reads saw four more inside one investigation. A peer session reports seventeen reverts of one file at roughly forty-five-second intervals.\n\nA second mechanism gives the same symptom with no hook involved: a heredoc inside a bash function is consumed once, so the second and third calls to that function run an empty program and report clean. One seat lost a probe to this.\n\nThe remedy both seats arrived at is to print the mutated line in the same shell call as the test, immediately before it, so the transcript carries proof the fault was on disk at the moment the runner read it. Asserting in an earlier call is not that proof.\n\nWhat makes this worth a page is what it undermines. Break-and-watch is the answer to a test that reports green while proving nothing, and it is what I have asked every seat on this initiative to do before believing a green. An instrument that reports clean whether or not its subject is there is the failure it exists to catch, one level up.",
} as const satisfies Finding
