import type { Finding } from "../finding.page-type.ts"

export const theNotifierAndAkashaHoldTwoDisjointDeviceTokenStores = {
  id: "01a060a0-1c52-7627-8206-34821df55117",
  pageTypeSlug: "finding",
  slug: "the-notifier-and-akasha-hold-two-disjoint-device-token-stores",
  domainSlug: "workspace-package/person-system",
  claim:
    "Device tokens are kept in two stores nothing bridges. `apns-push-notifier` reads `pages/device-token/*.md` through the markdown engine under `user-id` and `bundle-id`; akasha holds `device-token` pages under `personSlug` and `iosAppSlug` that nothing on the send road reads. So `registerDeviceToken` is left throwing: a token landed in akasha would be sent nowhere, and one landed in the markdown from the web pod dies at the next pod start. The notifier reading akasha is owed first.",
  evidence:
    "`tools/lib/push-notification/store.ts:12-17` is the one read on the send road: `askComposed` for `page-type: device-token` under `user-id`, taking `token` and `bundle-id`, reaching the in-process markdown engine through `page-query-client.ts:81` rather than the pages system service. Those three keys sit together only in `pages/device-token/*.md`. `akasha/person-system/device-tokens/device-token.page-type.ts:8-13` asks for `personSlug`, `iosAppSlug`, `token` and `lastSeenAt`, and for neither `user-id` nor `bundle-id`.\n\nThe index says the same from the other side: the index holds `akasha` alone, so top-level `pages/` is answered for by nothing, while `akasha/person-system/device-tokens/pages/` and `akasha/person-system/device-secrets/pages/` are both indexed and both answer a live `/ask`.\n\nThree markdown tokens are live: one under `com.alanwalton.app` for Alan's account, two under `me.smilingjenny.app` for Jenny's. The three akasha pages mirror those same tokens and are read by nothing. Alan holds two device secrets and one push token, so one of his two devices is reached by no notification today. A `pages/device-token/` page written in the web pod at 08:58 MDT was untracked and node-local; finding `nothing-the-web-pod-commits-ever-leaves-its-node` already records that road as destroyed at pod start.\n\n`recipientsFor` at `tools/lib/push-notification/payload.ts:75-83` widens to Jenny for `surplus-fall` alone; every other kind reaches its owner only.\n\nTwo repairs landed. `e10c272737` points `DEVICE_SECRETS_FOLDER` at `akasha/person-system/device-secrets/pages`, which the mint had missed by two moves. `64be9616e3` makes the refusal name this split rather than a missing account lookup, which `personSlugForAccount` already does.",
} as const satisfies Finding
