import type { Finding } from "../finding.page-type.ts"

export const thePageTypeRegistryGapIsDuplicateDeclarationsRatherThanMissingTypes = {
  id: "01a06104-5116-7230-ab56-82f0dc1cd4a9",
  pageTypeSlug: "finding",
  slug: "the-page-type-registry-gap-is-duplicate-declarations-rather-than-missing-types",
  domainSlug: "workspace-package/pages",
  claim:
    "`registryOf` resolves 372 markdown page types and none of the 192 `*.page-type.ts` files, which reads as 192 types absent. It is not: 117 of those slugs already resolve from a markdown declaration and only 75 are genuinely absent. The 117 are one page type declared twice, the two halves disagreeing about where its pages are, so unioning the sets would not add types — it would pick a winner for 117 slugs, and pick differently in first-wins and last-wins readers of one process.",
  evidence:
    "Measured 2026-09-02 by running, against the checkout as it is.\n\n`registryOf` answers 368 types over `diskFileTree` and 372 over `spanningFileTree`; every one is a `.md` file. `PAGE_TYPE_GLOBS` at akasha/markdown-pages/markdown-page-types/markdown-page-types.module.code.ts:23-27 names `pages/page-type` and `pages/rules-engine-rule-set` alone, so `indexedPaths` at akasha/markdown-pages/markdown-property-registry/markdown-property-registry.module.code.ts:62 scans `.md` paths only and no `.ts` file reaches the `pageTypeOf` filter at :63 to be rejected by it. The glob is the gate rather than the filter, measured and landed at `52c59e80db`. `pageTypeStatedAt` would refuse a `.ts` file anyway for carrying no frontmatter fence.\n\n192 `*.page-type.ts` sit under `akasha/` — 191 an hour earlier; `eso-daily-tracking.page-type.ts` landed at 01:18 mid-survey. Loading all 192 through `valueAt` costs 291ms against 59ms for the whole current scan.\n\nThe slug sets: 117 in both, 255 markdown-only, 75 akasha-only. Of the 117, 114 have a markdown declaration whose `files:` names only `.md` places, while the akasha declaration carries no `files` key at all — the akasha page type has no such property. `soleRepoOf` at akasha/markdown-pages/markdown-page-types/markdown-page-types.module.code.ts:334-337 already names this state: a type part way through a migration.\n\nA union would change existing answers three ways. The 117 gain a second record with `filed: [{repo, place: null}]`, which `placesOf` turns into `pages/<slug>/**/*.<slug>.md` — a path for a file that cannot exist, the same invention tools/lib/page-write-where.ts:29-42 records as having cost fourteen callers already. `frontmatter.ts:133` is first-wins and `page-rows-resolve.ts:27` is last-wins, so the two would disagree inside one process. And `claimant` would newly resolve 4,172 `.ts` files across 64 slugs that tools/gates/relations-resolve.ts:98 skips today.\n\nThe answer cache would go stale in silence: `shapeMarkOf` derives its mark from `.md` basenames and `git ls-files -- '*.page-type.md'`, so a reader taking in `.ts` files would read outside its own mark.\n\nThe call taken in Alan's absence: `registryOf` left exactly as it is. Closing this needs 117 per-slug decisions about which declaration is the page type, not one design choice.",
} as const satisfies Finding
