import type { Finding } from "akasha/domains/findings/finding.page-type.types.ts"

export const theRefusalAuditOfTheCommandSystemIsUnreviewed = {
  id: "01a09127-8c03-7caf-a082-f7515fdddfd7",
  type: "finding",
  slug: "the-refusal-audit-of-the-command-system-is-unreviewed",
  domain: "page-type/command",
  claim:
    "An audit read what a command does when it will not do the thing, provoking refusals to read them, and proposed sixteen things that are not so and should be. Two were overtaken by an intent that one spelling reaches a command. Eight more are settled: two invariants they rested on were dropped as false; the index refresh and the apply report no longer say nothing happened after it did; an apply reporting its edits gone was ruled too rare to guard; composing a refusal writes wherever the writing is declared; and two have intents of their own, on what a command that wrote before it threw says and on where a fault was thrown. Six are unreviewed and live nowhere but a transcript. A refusal is the main teaching an agent meets, so a refusal that asserts the opposite of what happened is worse than a terse true one. Several rest on subagent sweeps rather than on files the auditor opened, and those are marked.",
  evidence:
    "Unreviewed. A lead is a line from a sweep the auditor did not verify itself.\n\n1. A refusal over a change says nothing was judged and nothing was written. `refusing.module.ts:34` says this; `NOTHING` is appended only by `troubling` at `refusing.module.code.ts:14-17`, whose one production caller is `file-arguing.module.code.ts:312`. The change path refuses through `mistaking` at `change-running.module.code.ts:336-351`, and the provoked refusal carries no such sentence. Lead on the caller.\n\n2. An exit code says whose fault the refusal was. `calling.module.code.ts:238-240` hardcodes code 1, used at `:281-284`, `:286-290`, `:300-305` and `:408-414`. `change-running.module.code.ts:276` gives 1 to a change's own refusal. `command-answering.module.code.ts:6-10` names 1 INPUT, 2 DATA, 3 OPERATIONAL, and `cli.module.ts:48` says the code names the kind.\n\n3. Every refusal names the exact call that would succeed. Provoked: `akasha seat-reset` answers that it names the seat to reset and nothing followed it. `command-flags.module.code.ts:49` refuses with `is no flag this takes`, naming neither the command nor what it takes, and is shared by `file-arguing.module.code.ts:218` and `change-running.module.code.ts:338`. The shape is proven at `warranting.module.code.ts:114-117`, which builds a paste-ready read call. Lead on that last line.\n\n4. A refusal quotes back the part of the call it refused. `block-combined-akasha-calls` emits one body for every failure mode, from `REFUSED` at `:28-68` through `refusalIn` at `:148`, and never names the construct found — the auditor read it after a call joined by a semicolon and drew the wrong conclusion about which part was barred. `block-akasha-reads.agent-hook.code.ts:44-64` does fill its path in.\n\n5. A refusal over a misspelled name points at the nearest name. Provoked: `akasha change-draft change-fil` answers with the whole act list and no nearest match, built at `change-running.module.code.ts:351` from `runsSaid` at `:141-143`. `command-walking.module.code.ts` discards which word broke the descent. `suggestClosest` already exists at `parse-args.module.code.ts:88-92`. Lead on that helper.\n\n6. Something checks that a refusal changed nothing up to the commit. `invariant-earns-its-place.model-check.ts:10-11` is off, with `changeRuns: 0, auditRuns: 0`. `repository-is-written-by-a-change.code-check.ts:35` exempts command code, where the writes are. The invariant this would have judged has since been dropped as false, so what a check holds has to be stated first. Lead.\n",
} as const satisfies Finding
