import type { Finding } from "akasha/domains/findings/finding.page-type.types.ts"

export const thePageAgainstCodeAuditOfCommandsIsUnreviewed = {
  id: "01a09124-b9e2-746a-8af4-128263eace32",
  type: "finding",
  slug: "the-page-against-code-audit-of-commands-is-unreviewed",
  domain: "page-type/command",
  claim:
    "An audit read every command page against the code beside it, asking where the two disagree, and proposed fourteen things that are not so and should be. Five have landed as intents on `initiative/athena-commands-cleanup`: help answering from the page, the `taking` fields, the aliases those fields would carry, the one spelling a command is told, and that a command has no change kind, which absorbed two of the fourteen. Two about the seconds a command is allowed went to Aine and are hers. One was ruled no intent, because the export a command's code offers is named from its slug by the rule every page already follows. Five are still unreviewed.",
  evidence:
    'Unreviewed, each with what it rests on.\n\n1. A command the index does not carry makes the index rebuild itself. `calling.module.ts:49` states it; `calling.module.code.ts:250-268` offers a rebuild only where the whole index is broken — no index at `:256`, no command page-type id at `:259`, no commands at `:265`. A populated index missing one command answers that the command is no command akasha carries, with no repair offered.\n\n2. A command tells its caller the call as that call was written. `calling.module.ts:94-95` states it; `temper-inventory-rule-unlock.command.code.ts:10` hard-codes `const CALLED_AS`, and its exported function at `:14` takes no `given` at all, so it can never read `calledAs` or `root`. The same constant sits in `rule/update`, `rule/list`, `rule/create`, `rule/show` and `item-rule/create`.\n\n3. The nine email flag descriptions exist once. `alan/google/email/email-command-help/email-command-help.module.code.ts:6` and `:24` have no importers; the twelve email commands import `email-command-reading` instead. The same nine flags are described again in `taking` on `email-messages-send.command.ts:11-29` and `email-drafts-create.command.ts:11-29`, in different words. Deleting the dead module must follow the `taking` fields landing, or the only surviving record of `required` and `repeat` for email goes with it.\n\n4. A check refuses a command whose code spells a flag its page states. The only check over commands is placement, and `command-is-in-the-right-folder.code-check.decision.code.ts:55-56` returns null for a command no page names among its parts. Nothing compares `taking` to code, which is why the other faults here ran unnoticed.\n\n5. `loadedBy: "module/calling"` at `commands/command.page-type.ts:125` is honest about reachability — every command has its page, its part and its code — but the property is inert, appearing in no code file anywhere. No intent is proposed for it: a check for a case not here yet earns nothing.',
} as const satisfies Finding
