import type { Finding } from "../finding.page-type.ts"

export const twoOfTenFunctionalTypesCanBeReachedByNothing = {
  id: "01a061e1-9757-7c70-9914-57bf8006a57c",
  pageTypeSlug: "finding",
  slug: "two-of-ten-functional-types-can-be-reached-by-nothing",
  domainSlug: "domain/akasha-check",
  claim:
    "`local-service` and `next-app` are members of `FUNCTIONAL_TYPES` that no package here can ever be. Neither has a discriminator row, and no manifest has declared either in the whole history. The only discriminator for `local-service` probes `apps.workflow.ts`, a file kind that has never existed in this repository. The one check that would report the gap refuses before it looks, and `package add` offers a divergent nine-member roster omitting `io`, which thirteen packages carry.",
  evidence:
    "Measured 2026-09-02. `tools/lib/check-workflow/functional-type.ts:5-16` names ten types. Over 328 tracked manifests, 110 declare one, across eight: addon 34, pure 28, io 13, service 12, next-ui 12, program 7, worker 3, access 1. `local-service` and `next-app` are the two with none, and `git log --all -S` finds no commit declaring either.\n\n`DISCRIMINATOR_CHAIN` at `infra/cluster-checks/src/lib/functional-type-discriminators.ts:23-56` holds ten rows over eight types. `next-app` has no row at all. The row for `local-service` at :40 is `hasAppsWorkflowAtRoot`, which is `existsSync(join(workspaceDir, 'apps.workflow.ts'))` at `functional-type-row-discriminators.ts:142`. No `.workflow.ts` file is tracked, and `apps.workflow.ts` is in no commit here: the code arrived at `fa03a59af6` from the instructions repository, where that kind did exist.\n\nDeclaring one would not help. `functional-type-fixpoint.ts:31-35` seeds the map from what a manifest declares, then :62 overwrites every name with the inferred value on each iteration, so a declaration reaches only the arms that read a dependency's type and never the package's own answer.\n\nNothing reports it. `check-functional-type.ts:24` reads `if (import.meta.main) refuseRetired()`, so the one check comparing declared against inferred exits 2 before it opens a manifest. Its :147 already prints `inferred: no discriminator row matched`.\n\nA second roster drifted the other way. `infra/workspace-cli/src/lib/package-add/derive.ts:4-14` holds nine types and omits `io`, so `package add` cannot make the type thirteen packages carry, and does offer the two nothing can be.\n\n`local-service` is still read: `check-configs-service-typecheck.ts:20-24` leaves it out of leaf typechecking, and `RANK_BY_TYPE` ranks it 4.",
} as const satisfies Finding
