import { expect, test } from "bun:test"
import { isGeneratedFile } from "../../generated-file/generated-file.ts"

test("a page's rows file is generated, being projected from the page beside it", () => {
  expect(isGeneratedFile("pages/monarch-month/2026-08.transactions.jsonl", "{}\n")).toBe(true)
})

test("a rows file carrying its page type is generated too", () => {
  expect(isGeneratedFile("pages/monarch-month/2026-08.monarch-month.transactions.jsonl", "{}\n")).toBe(true)
})

test("a rows part and an uncommitted rows file are generated", () => {
  expect(isGeneratedFile("pages/gadget/widget.rows.part2.jsonl", "{}\n")).toBe(true)
  expect(isGeneratedFile("pages/gadget/widget.rows.uncommitted.jsonl", "{}\n")).toBe(true)
})

test("a page's attachment is generated, being written beside the page rather than authored", () => {
  expect(isGeneratedFile("pages/seat/ryn.seat.readings.uncommitted.attachment.json", "{}\n")).toBe(true)
})

test("what a file kind claims stands on its own is not generated", () => {
  expect(isGeneratedFile("pages/domain/global.domain.md", "# Global\n")).toBe(false)
  expect(isGeneratedFile("tools/lib/generated-file.ts", "const a = 1\n")).toBe(false)
})

test("a jsonl that is not a page's rows file is not generated by that alone", () => {
  expect(isGeneratedFile("data/export.jsonl", "{}\n")).toBe(false)
})

test("what stood generated before still does", () => {
  expect(isGeneratedFile("src/generated/api.ts", "const a = 1\n")).toBe(true)
  expect(isGeneratedFile("src/api.generated.ts", "const a = 1\n")).toBe(true)
  expect(isGeneratedFile("src/api.ts", "// @generated\nconst a = 1\n")).toBe(true)
})
