import type { SetTemplate } from "@akasha/temper-equipment/set-template"

export const SETS_DATA_112: readonly SetTemplate[] = [
  {
    id: "valkyn-skoria",
    name: "Valkyn Skoria",
    esoSetId: 169,
    subcategoryId: "monster",
    valid: ["monster"],
    bonuses: [
      {
        count: 1,
        status: "supported",
        effects: [{ metricId: "penetration", effectType: "integer", effectValue: 1487 }],
        description: "Adds 1487 Offensive Penetration",
      },
      {
        count: 2,
        status: "unsupported",
        effects: [],
        description:
          "When you deal damage with a damage over time effect, you have an 8% chance to summon a meteor that deals 1342 Flame damage to the target and 447 Flame damage to all other enemies within 5 meters. This effect can occur once every 5 seconds and scales off the higher of your Weapon or Spell Damage.",
      },
    ],
    icons: {
      "head:heavy": "/esoui/art/icons/gear_undaunted_lich_head_a.dds",
      "head:light": "/esoui/art/icons/gear_undaunted_lich_head_a.dds",
      "head:medium": "/esoui/art/icons/gear_undaunted_lich_head_a.dds",
      "shoulders:heavy": "/esoui/art/icons/gear_undaunted_lich_shoulders_a.dds",
      "shoulders:light": "/esoui/art/icons/gear_undaunted_lich_shoulders_a.dds",
      "shoulders:medium": "/esoui/art/icons/gear_undaunted_lich_shoulders_a.dds",
    },
  },
  {
    id: "vampire-cloak",
    name: "Vampire Cloak",
    esoSetId: 282,
    subcategoryId: "overland",
    valid: ["*:heavy"],
    bonuses: [
      {
        count: 2,
        status: "supported",
        effects: [{ metricId: "health-maximum", effectType: "integer", effectValue: 1206 }],
        description: "Adds 1206 Maximum Health",
      },
      {
        count: 3,
        status: "supported",
        effects: [{ metricId: "power", effectType: "integer", effectValue: 129 }],
        description: "Adds 129 Weapon and Spell Damage",
      },
      {
        count: 4,
        status: "supported",
        effects: [{ metricId: "health-maximum", effectType: "integer", effectValue: 1206 }],
        description: "Adds 1206 Maximum Health",
      },
      {
        count: 5,
        status: "supported",
        effects: [{ metricId: "power", effectType: "integer", effectValue: 171 }],
        description: "Adds 171 Weapon and Spell Damage",
      },
      {
        count: 5,
        status: "unsupported",
        effects: [],
        description: "Gain Minor Protection at all times, reducing your damage taken by 5%.",
      },
    ],
    icons: {
      "axe": "/esoui/art/icons/gear_breton_1haxe_d.dds",
      "battleaxe": "/esoui/art/icons/gear_breton_2haxe_d.dds",
      "bow": "/esoui/art/icons/gear_breton_bow_d.dds",
      "chest:*": "/esoui/art/icons/gear_orc_heavy_chest_d.dds",
      "dagger": "/esoui/art/icons/gear_breton_dagger_d.dds",
      "feet:*": "/esoui/art/icons/gear_breton_heavy_feet_d.dds",
      "greatsword": "/esoui/art/icons/gear_orc_2hsword_d.dds",
      "hands:*": "/esoui/art/icons/gear_breton_heavy_hands_d.dds",
      "head:*": "/esoui/art/icons/gear_breton_heavy_head_d.dds",
      "ice-staff": "/esoui/art/icons/gear_breton_staff_d.dds",
      "inferno-staff": "/esoui/art/icons/gear_altmer_staff_d.dds",
      "legs:*": "/esoui/art/icons/gear_orc_heavy_legs_d.dds",
      "lightning-staff": "/esoui/art/icons/gear_breton_staff_d.dds",
      "mace": "/esoui/art/icons/gear_nord_1hhammer_d.dds",
      "maul": "/esoui/art/icons/gear_breton_2hhammer_d.dds",
      "necklace": "/esoui/art/icons/quest_hands_002.dds",
      "restoration-staff": "/esoui/art/icons/gear_breton_staff_d.dds",
      "ring": "/esoui/art/icons/gear_breton_ring_a.dds",
      "shield": "/esoui/art/icons/gear_breton_shield_d.dds",
      "shoulders:*": "/esoui/art/icons/gear_nord_heavy_shoulders_d.dds",
      "sword": "/esoui/art/icons/gear_breton_1hsword_d.dds",
      "waist:*": "/esoui/art/icons/gear_breton_heavy_waist_d.dds",
    },
  },
  {
    id: "vampire-lord",
    name: "Vampire Lord",
    esoSetId: 285,
    subcategoryId: "overland",
    valid: ["*:light"],
    bonuses: [
      {
        count: 2,
        status: "supported",
        effects: [{ metricId: "magicka-maximum", effectType: "integer", effectValue: 1096 }],
        description: "Adds 1096 Maximum Magicka",
      },
      {
        count: 3,
        status: "supported",
        effects: [{ metricId: "power", effectType: "integer", effectValue: 129 }],
        description: "Adds 129 Weapon and Spell Damage",
      },
      {
        count: 4,
        status: "supported",
        effects: [{ metricId: "critical-rating", effectType: "integer", effectValue: 657 }],
        description: "Adds 657 Critical Chance",
      },
      {
        count: 5,
        status: "unsupported",
        effects: [],
        description:
          "Increases the bonuses and penalties of your Vampire Stage, depending on how far you've progressed.\n\nStage 1/2/3/4\n\n1%/2%/4%/6% additional Flame Damage Taken.\n1%/2%/4%/6% increased Regular Ability cost.\n5%/10%/15%/20% reduced Vampire Ability cost.",
      },
    ],
    icons: {
      "axe": "/esoui/art/icons/gear_altmer_1haxe_d.dds",
      "battleaxe": "/esoui/art/icons/gear_altmer_2haxe_d.dds",
      "bow": "/esoui/art/icons/gear_altmer_bow_d.dds",
      "chest:*": "/esoui/art/icons/gear_nord_light_robe_d.dds",
      "dagger": "/esoui/art/icons/gear_altmer_dagger_d.dds",
      "feet:*": "/esoui/art/icons/gear_altmer_light_feet_d.dds",
      "greatsword": "/esoui/art/icons/gear_nord_2hsword_d.dds",
      "hands:*": "/esoui/art/icons/gear_altmer_light_hands_d.dds",
      "head:*": "/esoui/art/icons/gear_altmer_light_head_d.dds",
      "ice-staff": "/esoui/art/icons/gear_khajiit_staff_d.dds",
      "inferno-staff": "/esoui/art/icons/gear_altmer_staff_d.dds",
      "legs:*": "/esoui/art/icons/gear_nord_light_legs_d.dds",
      "lightning-staff": "/esoui/art/icons/gear_altmer_staff_d.dds",
      "mace": "/esoui/art/icons/gear_altmer_1hhammer_d.dds",
      "maul": "/esoui/art/icons/gear_altmer_2hhammer_d.dds",
      "necklace": "/esoui/art/icons/gear_breton_neck_a.dds",
      "restoration-staff": "/esoui/art/icons/gear_breton_staff_d.dds",
      "ring": "/esoui/art/icons/gear_redguard_ring_a.dds",
      "shield": "/esoui/art/icons/gear_altmer_shield_d.dds",
      "shoulders:*": "/esoui/art/icons/gear_redguard_light_shoulders_d.dds",
      "sword": "/esoui/art/icons/gear_altmer_1hsword_d.dds",
      "waist:*": "/esoui/art/icons/gear_breton_light_waist_d.dds",
    },
  },
  {
    id: "vampires-kiss",
    name: "Vampire's Kiss",
    esoSetId: 44,
    subcategoryId: "crafted",
    valid: ["*"],
    bonuses: [
      {
        count: 2,
        status: "supported",
        effects: [{ metricId: "stamina-maximum", effectType: "integer", effectValue: 1096 }],
        description: "Adds 1096 Maximum Stamina",
      },
      {
        count: 3,
        status: "supported",
        effects: [{ metricId: "magicka-maximum", effectType: "integer", effectValue: 1096 }],
        description: "Adds 1096 Maximum Magicka",
      },
      {
        count: 4,
        status: "supported",
        effects: [{ metricId: "stamina-maximum", effectType: "integer", effectValue: 1096 }],
        description: "Adds 1096 Maximum Stamina",
      },
      {
        count: 4,
        status: "supported",
        effects: [{ metricId: "magicka-maximum", effectType: "integer", effectValue: 1096 }],
        description: "Adds 1096 Maximum Magicka",
      },
      {
        count: 5,
        status: "supported",
        effects: [{ metricId: "power", effectType: "integer", effectValue: 129 }],
        description: "Adds 129 Weapon and Spell Damage",
      },
      {
        count: 5,
        status: "unsupported",
        effects: [],
        description:
          "When you kill an enemy, you heal for 10956 Health over 10 seconds.  This effect scales off the higher of your Max Magicka or Stamina.",
      },
    ],
    icons: {
      "axe": "/esoui/art/icons/gear_breton_1haxe_d.dds",
      "battleaxe": "/esoui/art/icons/gear_breton_2haxe_d.dds",
      "bow": "/esoui/art/icons/gear_breton_bow_d.dds",
      "chest:heavy": "/esoui/art/icons/gear_breton_heavy_chest_d.dds",
      "chest:light": "/esoui/art/icons/gear_breton_light_robe_d.dds",
      "chest:medium": "/esoui/art/icons/gear_breton_medium_chest_d.dds",
      "dagger": "/esoui/art/icons/gear_breton_dagger_d.dds",
      "feet:heavy": "/esoui/art/icons/gear_breton_heavy_feet_d.dds",
      "feet:light": "/esoui/art/icons/gear_breton_light_feet_d.dds",
      "feet:medium": "/esoui/art/icons/gear_breton_medium_feet_d.dds",
      "greatsword": "/esoui/art/icons/gear_breton_2hsword_d.dds",
      "hands:heavy": "/esoui/art/icons/gear_breton_heavy_hands_d.dds",
      "hands:light": "/esoui/art/icons/gear_breton_light_hands_d.dds",
      "hands:medium": "/esoui/art/icons/gear_breton_medium_hands_d.dds",
      "head:heavy": "/esoui/art/icons/gear_breton_heavy_head_d.dds",
      "head:light": "/esoui/art/icons/gear_breton_light_head_d.dds",
      "head:medium": "/esoui/art/icons/gear_breton_medium_head_d.dds",
      "ice-staff": "/esoui/art/icons/gear_breton_staff_d.dds",
      "inferno-staff": "/esoui/art/icons/gear_breton_staff_d.dds",
      "legs:heavy": "/esoui/art/icons/gear_breton_heavy_legs_d.dds",
      "legs:light": "/esoui/art/icons/gear_breton_light_legs_d.dds",
      "legs:medium": "/esoui/art/icons/gear_breton_medium_legs_d.dds",
      "lightning-staff": "/esoui/art/icons/gear_breton_staff_d.dds",
      "mace": "/esoui/art/icons/gear_breton_1hhammer_d.dds",
      "maul": "/esoui/art/icons/gear_breton_2hhammer_d.dds",
      "necklace": "/esoui/art/icons/gear_breton_neck_a.dds",
      "restoration-staff": "/esoui/art/icons/gear_breton_staff_d.dds",
      "ring": "/esoui/art/icons/gear_breton_ring_a.dds",
      "shield": "/esoui/art/icons/gear_breton_shield_d.dds",
      "shoulders:heavy": "/esoui/art/icons/gear_breton_heavy_shoulders_d.dds",
      "shoulders:light": "/esoui/art/icons/gear_breton_light_shoulders_d.dds",
      "shoulders:medium": "/esoui/art/icons/gear_breton_medium_shoulders_d.dds",
      "sword": "/esoui/art/icons/gear_breton_1hsword_d.dds",
      "waist:heavy": "/esoui/art/icons/gear_breton_heavy_waist_d.dds",
      "waist:light": "/esoui/art/icons/gear_breton_light_waist_d.dds",
      "waist:medium": "/esoui/art/icons/gear_breton_medium_waist_d.dds",
    },
  },
  {
    id: "vandorallens-resonance",
    name: "Vandorallen's Resonance",
    esoSetId: 794,
    subcategoryId: "no-type",
    valid: ["*:light"],
    bonuses: [
      {
        count: 2,
        status: "supported",
        effects: [{ metricId: "penetration", effectType: "integer", effectValue: 1487 }],
        description: "Adds 1487 Offensive Penetration",
      },
      {
        count: 3,
        status: "supported",
        effects: [{ metricId: "critical-rating", effectType: "integer", effectValue: 657 }],
        description: "Adds 657 Critical Chance",
      },
      {
        count: 4,
        status: "supported",
        effects: [{ metricId: "power", effectType: "integer", effectValue: 129 }],
        description: "Adds 129 Weapon and Spell Damage",
      },
      {
        count: 5,
        status: "unsupported",
        effects: [],
        description:
          "Dealing damage with a fully-charged Heavy Attack places an electric charge on yourself and below your enemy. After 1 second, both charges explode in a 4 meter blast, each dealing 914 Shock damage to enemies hit. This effect can occur once every 6 seconds and scales off the higher of your Weapon or Spell Damage.",
      },
    ],
    icons: {
      "axe": "/esoui/art/icons/gear_exilesrevenge_axe_a.dds",
      "battleaxe": "/esoui/art/icons/gear_exilesrevenge_2haxe_a.dds",
      "bow": "/esoui/art/icons/gear_exilesrevenge_bow_a.dds",
      "chest:*": "/esoui/art/icons/gear_exilerevengelgt_robe_a.dds",
      "dagger": "/esoui/art/icons/gear_exilesrevenge_dagger_a.dds",
      "feet:*": "/esoui/art/icons/gear_exilerevengelgt_feet_a.dds",
      "greatsword": "/esoui/art/icons/gear_exilesrevenge_2hsword_a.dds",
      "hands:*": "/esoui/art/icons/gear_exilerevengelgt_hands_a.dds",
      "head:*": "/esoui/art/icons/gear_exilerevengelgt_head_a.dds",
      "ice-staff": "/esoui/art/icons/gear_exilesrevenge_staff_a.dds",
      "inferno-staff": "/esoui/art/icons/gear_exilesrevenge_staff_a.dds",
      "legs:*": "/esoui/art/icons/gear_exilerevengelgt_legs_a.dds",
      "lightning-staff": "/esoui/art/icons/gear_exilesrevenge_staff_a.dds",
      "mace": "/esoui/art/icons/gear_exilesrevenge_mace_a.dds",
      "maul": "/esoui/art/icons/gear_exilesrevenge_2hmace_a.dds",
      "necklace": "/esoui/art/icons/gear_breton_neck_a.dds",
      "restoration-staff": "/esoui/art/icons/gear_exilesrevenge_staff_a.dds",
      "ring": "/esoui/art/icons/gear_breton_ring_a.dds",
      "shield": "/esoui/art/icons/gear_exilesrevenge_shield_a.dds",
      "shoulders:*": "/esoui/art/icons/gear_exilerevengelgt_shoulder_a.dds",
      "sword": "/esoui/art/icons/gear_exilesrevenge_sword_a.dds",
      "waist:*": "/esoui/art/icons/gear_exilerevengelgt_waist_a.dds",
    },
  },
]
