apiVersion: v1
kind: Secret
metadata:
    name: grafana-secrets
    namespace: grafana
    labels:
        app.kubernetes.io/name: grafana
        app.kubernetes.io/instance: grafana
        app.kubernetes.io/component: secrets
        app.kubernetes.io/part-of: monitoring
        app.kubernetes.io/managed-by: bootstrap
type: Opaque
stringData:
    GRAFANA_ADMIN_PASSWORD: ENC[AES256_GCM,data:j3WBwsg1wWpeTFNVfnUnjGRJoSNPIxCR5+OdXONM2vE=,iv:45gdjEwEdcfnmJ8hCsMHm3/sVjgfvB5R/EjmDI4QvPU=,tag:a20C0watzjBEMpcRRin2iQ==,type:str]
    GRAFANA_DB_RO_PASSWORD: ENC[AES256_GCM,data:1cqfVX31miXHHm87eSne+y9kOivdcAdTHDK6AzwEV7MQ+UwS6qJslQ==,iv:Jc/r4IfEncEnDe9OWI+FQh0fV0NuTU7WHuevXSRAvcg=,tag:RRDG0VW082RCB98maInL2A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLZldoU3lUSnNTcy9WN2JG
            NzBzQjdiWWpHOE16U2FpT05iZThwTlk1c2tVCjJNei9TcTN2Wk1lYjI1ZGJLL3NS
            VUxyNXVKeUNZbXBJSGtrM3ZKVDNHMlkKLS0tIGZ6WGdHOXRaUkJpUzh3UzNiY3dR
            RCtYc2JJRldFbWxqSDJWVjVWVi9NUmsKvLhndtll5HNVyhUwJ+Ql2maEwbTJs9N5
            mzv02Lwzp71fsWTdt1u9vgo2TbEMa4nNyRWwH9fLZBi+00k3dX4OOw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-19T23:25:52Z"
    mac: ENC[AES256_GCM,data:1vcQ2xGveaYBySItGXULeUS/W/C8isdnPXah9d5K3ZnIUICiPkvjF5+PAFEvdmSlMRC75zb+fQOn7K9tNQ1CA46DLJe8ftHfrWfrlFD9HA6d9O7JLdB4ip7VDEvXvLwRNASKnBjPJap1ByWBOrQxVfdajkJe1SB6tK0iM+4bY7o=,iv:JlvWcFYwEtwqAti8LG9CbDOaDtATWIQp7VF5dWDnlLk=,tag:M/EQyjeucnFX+1VKGJCzKQ==,type:str]
    version: 3.9.4
