import type { Domain } from "akasha/domains/domain.page-type.types.ts"

export const temperItemsRulesCore = {
  id: "01a060d9-44cd-7bbd-88e3-944b7a932e9a",
  type: "domain",
  slug: "temper-items-rules-core",
  definition:
    "the rules saying what becomes of an item and the conditions those rules are written in",
  parts: [
    "module/action-storage-capability",
    "module/affected-items-tree-builder",
    "module/all-stocked-filter",
    "module/bop-tradeable-filter",
    "module/bound-filter",
    "module/buy-rule-eval",
    "module/buy-rule-settings",
    "module/buy-rule-types",
    "module/can-companion-equip-filter",
    "module/can-give-max-rewards-filter",
    "module/can-inspire-filter",
    "module/can-level-morphs-filter",
    "module/can-level-morphs-filter-types",
    "module/can-list-at-guild-trader-filter",
    "module/can-open-filter",
    "module/can-research-filter",
    "module/can-sell-filter",
    "module/can-unlock-filter",
    "module/comparison-op",
    "module/comparison-op-data",
    "module/conditional-actions",
    "module/crafted-filter",
    "module/crafting-material-actions",
    "module/default-rules-data",
    "module/destination-chain-types",
    "module/eligibility-predicate-composer",
    "module/equipment-config",
    "module/equipment-signature-compiler",
    "module/inventory-destination-parse",
    "module/inventory-rule-action-labels",
    "module/inventory-rule-classify",
    "module/inventory-rule-compiler",
    "module/inventory-rule-compiler-sparse",
    "module/inventory-rule-compiler-types",
    "module/inventory-rule-conditions-shape",
    "module/inventory-rule-controlled",
    "module/inventory-rule-engine",
    "module/inventory-rule-from-pages",
    "module/inventory-rule-goals",
    "module/inventory-rule-mapping",
    "module/inventory-rule-matcher-types",
    "module/inventory-rule-settings",
    "module/inventory-rule-test-utils",
    "module/inventory-rule-to-pages",
    "module/inventory-rule-trait-research",
    "module/inventory-rule-types",
    "module/inventory-rule-writes",
    "module/inventory-settings-types",
    "module/item-category-actions",
    "module/item-category-tree-utils",
    "module/keep-quantity-filter",
    "module/known-filter",
    "module/level-filter",
    "module/location-filter",
    "module/locked-filter",
    "module/market-value-filter",
    "module/merchant-value-filter",
    "module/needed-for-target-character-build-filter",
    "module/needed-for-target-companion-build-filter",
    "module/potion-effects-filter",
    "module/potion-restore-resolve",
    "module/quest-relevant-filter",
    "module/reconstructed-filter",
    "module/replacement-value-filter",
    "module/required-curse-state-filter",
    "module/required-curse-state-filter-types",
    "module/required-skill-lines-filter",
    "module/required-skill-lines-filter-types",
    "module/rule-condition-states",
    "module/rule-constants",
    "module/rule-destinations",
    "module/rule-filter-registry",
    "module/rule-filter-types",
    "module/rule-filter-utils",
    "module/rule-fingerprint",
    "module/rule-item-name-filter",
    "module/rule-matcher-context-types",
    "module/rule-quality-filter",
    "module/rule-template-table",
    "module/rule-template-table-01",
    "module/rule-template-table-02",
    "module/scribing-total-script-count",
    "module/set-sources-filter",
    "module/stack-fullness-filter",
    "module/stock-chain-visit",
    "module/stock-destination-context-builder",
    "module/stock-destination-planner",
    "module/stock-destination-types",
    "module/stock-reconcile-plan",
    "module/stock-threshold-filter",
    "module/stolen-filter",
    "module/target-quantity-filter",
    "module/trait-actions",
    "module/traits-filter",
    "module/transmuted-filter",
    "module/use-destination-context-builder",
    "module/use-destination-planner",
    "module/use-destination-resolver",
    "module/use-destination-types",
    "module/value-filter",
  ],
  invariants: [
    {
      invariantKind: "departure",
      statement: "A rule names the action an item is given.",
    },
    {
      invariantKind: "absence",
      statement: "No code here reaches the game.",
    },
  ],
} as const satisfies Domain
