import type { Domain } from "akasha/domain/domain.page-type.types.ts"

export const pageUiSupabase = {
  id: "01a071d1-ee27-7b2f-8b21-963e117f2e00",
  type: "page-type/domain",
  slug: "page-ui-supabase",
  definition: "the store reached over Supabase",
  parts: [
    "domain/page-ui-supabase-mutation",
    "module/apply-client-view-filters",
    "module/collect-related-ids",
    "module/compose-content-tier-page",
    "module/group-by-hooks",
    "module/hooks",
    "module/hooks-view-query",
    "module/page-resolver-provider",
    "module/page-with-properties",
    "module/record-view-staleness",
    "module/related-pages-coalesce",
    "module/relation-picker",
    "module/use-complete-page-optimistic",
    "module/use-nav-mutations",
    "module/use-option-list-lookup",
    "module/use-page",
    "module/use-page-type-directory",
    "module/use-pages",
    "module/use-record-page-view",
    "module/use-referrers",
    "module/use-set-property-optimistic",
    "module/use-subpages",
    "module/use-view-callbacks",
    "module/use-view-pages",
    "module/view-data-of-page",
    "module/view-filter-to-condition",
  ],
} as const satisfies Domain
