export const LIB_SETS_PRELOADED_SET_NAMES_05: Record<number, Record<string, string>> = {
  [330]: {
    de: "Automatisierte Verteidigung",
    en: "Automated Defense",
    es: "Defensa automática",
    fr: "La Défense automatique",
    ru: "Автоматическая защита",
    zh: "自动防御",
  },
  [331]: {
    de: "Kriegsmaschine",
    en: "War Machine",
    es: "Máquina de guerra",
    fr: "La machine de guerre",
    ru: "Военная машина",
    zh: "战争机器",
  },
  [332]: {
    de: "Meisterarchitekt",
    en: "Master Architect",
    es: "Maestro arquitecto",
    fr: "Le maître architecte",
    ru: "Главный архитектор",
    zh: "建筑大师",
  },
  [333]: {
    de: "Erfindergarde",
    en: "Inventor's Guard",
    es: "Guarda del inventor",
    fr: "La Garde de l'inventeur",
    ru: "Защита изобретателя",
    zh: "发明家的守卫",
  },
  [334]: {
    de: "Unüberwindliche Rüstung",
    en: "Impregnable Armor",
    es: "Armadura inexpugnable",
    fr: "Armure imprenable",
    ru: "Непробиваемая броня",
    zh: "至坚护甲",
  },
  [335]: {
    de: "Draugrruhe",
    en: "Draugr's Rest",
    es: "Remanso del draugr",
    fr: "Le Repos du Draugr",
    ru: "Покой драугра",
    zh: "尸鬼之栖",
  },
  [336]: {
    de: "Säulen von Nirn",
    en: "Pillar of Nirn",
    es: "Pilar de Nirn",
    fr: "Pilier de Nirn",
    ru: "Столп Нирна",
    zh: "奈恩之柱",
  },
  [337]: {
    de: "Eisenblut",
    en: "Ironblood",
    es: "Sangre de hierro",
    fr: "Sang de fer",
    ru: "Железная кровь",
    zh: "铁血",
  },
  [338]: {
    de: "Flammenblüte",
    en: "Flame Blossom",
    es: "Flor de fuego",
    fr: "Fleur de feu",
    ru: "Пламенный цветок",
    zh: "烈焰绽放",
  },
  [339]: {
    de: "Bluttrinker",
    en: "Blooddrinker",
    es: "Chupasangre",
    fr: "La Buveur de sang",
    ru: "Кровопийца",
    zh: "饮血者",
  },
  [340]: {
    de: "Vettelgarten",
    en: "Hagraven's Garden",
    es: "Jardín de la bruja cuervo",
    fr: "Jardin de la harfreuse",
    ru: "Сад ворожеи",
    zh: "渡鸦鬼婆花园",
  },
  [341]: {
    de: "Erdbluter",
    en: "Earthgore",
    es: "Tierra Sangrienta",
    fr: "Sangreterre",
    ru: "Кровь земли",
    zh: "地血",
  },
  [342]: {
    de: "Domihaus",
    en: "Domihaus",
    es: "Domihaus",
    fr: "Domihaus",
    ru: "Домихаус",
    zh: "铎米豪斯",
  },
  [343]: {
    de: "Caluurions Erbe",
    en: "Caluurion's Legacy",
    es: "Legado de Caluurion",
    fr: "L’Héritage de Caluurion",
    ru: "Наследие Калуриона",
    zh: "卡鲁里昂的遗产",
  },
  [344]: {
    de: "Stärkungsprunk",
    en: "Trappings of Invigoration",
    es: "Enseres de vivificación",
    fr: "Apparence de vivification",
    ru: "Второе дыхание",
    zh: "鼓舞礼服",
  },
  [345]: {
    de: "Ulfnors Gunst",
    en: "Ulfnor's Favor",
    es: "Favor de Ulfnor",
    fr: "La Faveur d'Ulfnor",
    ru: "Благосклонность Ульфнора",
    zh: "乌尔夫诺尔的青睐",
  },
  [346]: {
    de: "Jorvulds Führung",
    en: "Jorvuld's Guidance",
    es: "Consejo de Jorvuld",
    fr: "Le Conseil de Jorvuld",
    ru: "Напутствие Йорвульда",
    zh: "约尔沃德的指引",
  },
  [347]: {
    de: "Seuchenschleuder",
    en: "Plague Slinger",
    es: "Azote de la plaga",
    fr: "Lance-peste",
    ru: "Чумной метатель",
    zh: "瘟疫投掷",
  },
  [348]: {
    de: "Fluch von Doylemish",
    en: "Curse of Doylemish",
    es: "Maldición de Doylemish",
    fr: "La Malédiction de Doylemish",
    ru: "Проклятие Дойлемиша",
    zh: "多来米什的诅咒",
  },
  [349]: {
    de: "Thurvokun",
    en: "Thurvokun",
    es: "Thurvokun",
    fr: "Thurvokun",
    ru: "Турвокун",
    zh: "图尔佛昆",
  },
  [350]: { de: "Zaan", en: "Zaan", es: "Zaan", fr: "Zaan", ru: "Заан", zh: "赞恩" },
  [351]: {
    de: "Kernaxiom",
    en: "Innate Axiom",
    es: "Axioma innato",
    fr: "Axiome inné",
    ru: "Врожденная аксиома",
    zh: "天定公理",
  },
  [352]: {
    de: "Messingpanzer",
    en: "Fortified Brass",
    es: "Latón reforzado",
    fr: "Airain fortifié",
    ru: "Прочная латунь",
    zh: "强化黄铜",
  },
  [353]: {
    de: "Mechanikblick",
    en: "Mechanical Acuity",
    es: "Agudeza mecánica",
    fr: "Acuité mécanique",
    ru: "Механическая точность",
    zh: "机械敏锐",
  },
  [354]: {
    de: "Wahntüftler",
    en: "Mad Tinkerer",
    es: "Inventor demente",
    fr: "Bricoleur fou",
    ru: "Безумный изобретатель",
    zh: "疯狂工匠",
  },
  [355]: {
    de: "Unermessliche Dunkelheit",
    en: "Unfathomable Darkness",
    es: "Oscuridad insondable",
    fr: "Ténèbres insondables",
    ru: "Непроницаемая тьма",
    zh: "深邃黑暗",
  },
  [356]: {
    de: "Stromschlag",
    en: "Livewire",
    es: "Energía viva",
    fr: "Haute tension",
    ru: "Высокое напряжение",
    zh: "电路",
  },
  [357]: {
    de: "Perfektionierter disziplinierter Schnitt",
    en: "Perfected Disciplined Slash",
    es: "Corte disciplinado perfeccionado",
    fr: "Entaille disciplinée perfectionnée",
    ru: "Совершенный выверенный удар",
    zh: "完美惩戒斩击",
  },
  [358]: {
    de: "Perfektionierte defensive Position",
    en: "Perfected Defensive Position",
    es: "Posición defensiva perfeccionada",
    fr: "Position défensive perfectionnée",
    ru: "Совершенная оборонительная позиция",
    zh: "完美防御阵地",
  },
  [359]: {
    de: "Perfektionierter chaotischer Wirbelwind",
    en: "Perfected Chaotic Whirlwind",
    es: "Torbellino caótico perfeccionado",
    fr: "Tourbillon chaotique perfectionné",
    ru: "Совершенный хаотичный вихрь",
    zh: "完美混沌旋风",
  },
  [360]: {
    de: "Perfektionierte durchdringende Salve",
    en: "Perfected Piercing Spray",
    es: "Ráfaga perforadora perfeccionada",
    fr: "Jaillissement perforant perfectionné",
    ru: "Совершенный пробивающий веер",
    zh: "完美穿刺箭阵",
  },
  [361]: {
    de: "Perfektionierte konzentrierte Kraft",
    en: "Perfected Concentrated Force",
    es: "Fuerza concentrada perfeccionada",
    fr: "Force concentrée perfectionnée",
    ru: "Совершенная концентрированная сила",
    zh: "完美专注之力",
  },
  [362]: {
    de: "Perfektionierter zeitloser Segen",
    en: "Perfected Timeless Blessing",
    es: "Bendición eterna perfeccionada",
    fr: "Bénédiction intemporelle perfectionnée",
    ru: "Совершенное бесконечное благословение",
    zh: "完美无尽祝福",
  },
  [363]: {
    de: "Disziplinierter Schnitt",
    en: "Disciplined Slash",
    es: "Corte disciplinado",
    fr: "Entaille disciplinée",
    ru: "Выверенный удар",
    zh: "惩戒斩击",
  },
  [364]: {
    de: "Defensive Position",
    en: "Defensive Position",
    es: "Posición defensiva",
    fr: "Position défensive",
    ru: "Оборонительная позиция",
    zh: "防御阵地",
  },
  [365]: {
    de: "Chaotischer Wirbelwind",
    en: "Chaotic Whirlwind",
    es: "Torbellino caótico",
    fr: "Tourbillon chaotique",
    ru: "Хаотичный вихрь",
    zh: "混沌旋风",
  },
  [366]: {
    de: "Durchdringende Salve",
    en: "Piercing Spray",
    es: "Ráfaga perforadora",
    fr: "Jaillissement perforant",
    ru: "Пробивающий веер",
    zh: "穿刺箭阵",
  },
  [367]: {
    de: "Konzentrierte Kraft",
    en: "Concentrated Force",
    es: "Fuerza concentrada",
    fr: "Force concentrée",
    ru: "Концентрированная сила",
    zh: "专注之力",
  },
  [368]: {
    de: "Zeitloser Segen",
    en: "Timeless Blessing",
    es: "Bendición eterna",
    fr: "Bénédiction intemporelle",
    ru: "Бесконечное благословение",
    zh: "无尽祝福",
  },
  [369]: {
    de: "Gnadenloser Ansturm",
    en: "Merciless Charge",
    es: "Carga despiadada",
    fr: "La Charge impitoyable",
    ru: "Безжалостный рывок",
    zh: "无情冲锋",
  },
  [370]: {
    de: "Tobender Schnitt",
    en: "Rampaging Slash",
    es: "Hendidura inexorable",
    fr: "L’Entaille ravageuse",
    ru: "Свирепый удар",
    zh: "狂暴劈斩",
  },
  [371]: {
    de: "Grausamer Schlaghagel",
    en: "Cruel Flurry",
    es: "Ráfaga cruel",
    fr: "Le Déluge cruel",
    ru: "Жестокий шквал",
    zh: "残暴乱舞",
  },
  [372]: {
    de: "Donnernde Salve",
    en: "Thunderous Volley",
    es: "Salva atronadora",
    fr: "La Volée tonitruante",
    ru: "Разрушительный залп",
    zh: "雷霆齐射",
  },
  [373]: {
    de: "Zermalmende Mauer",
    en: "Crushing Wall",
    es: "Muro aplastante",
    fr: "Le Mur écrasant",
    ru: "Сокрушительная стена",
    zh: "碾压之墙",
  },
  [374]: {
    de: "Präzise Regeneration",
    en: "Precise Regeneration",
    es: "Regeneración precisa",
    fr: "La Régénération précise",
    ru: "Точное восстановление",
    zh: "精准再生",
  },
  [380]: {
    de: "Prophet",
    en: "Prophet's",
    es: "Profeta",
    fr: "L’Ensemble du Prophète",
    ru: "Пророк",
    zh: "先知",
  },
  [381]: {
    de: "Zerbrochene Seele",
    en: "Broken Soul",
    es: "Alma desgarrada",
    fr: "L’Âme brisée",
    ru: "Расколотая душа",
    zh: "破碎灵魂",
  },
  [382]: {
    de: "Anmut der Gräue",
    en: "Grace of Gloom",
    es: "Gracia de la penumbra",
    fr: "La Gracieuse mélancolie",
    ru: "Милосердие мрака",
    zh: "幽暗恩惠",
  },
  [383]: {
    de: "Wildheit des Greifen",
    en: "Gryphon's Ferocity",
    es: "Ferocidad del grifo",
    fr: "La Férocité du griffon",
    ru: "Свирепость грифона",
    zh: "狮鹫虐行",
  },
  [384]: {
    de: "Weisheit von Vanus",
    en: "Wisdom of Vanus",
    es: "Sabiduría de Vano",
    fr: "La Sagesse de Vanus",
    ru: "Мудрость Вануса",
    zh: "瓦努斯睿智",
  },
  [385]: {
    de: "Versierter Reiter",
    en: "Adept Rider",
    es: "Jinete adepto",
    fr: "L’Adepte cavalier",
    ru: "Умелый наездник",
    zh: "熟练骑手",
  },
  [386]: {
    de: "Kreckenantlitz",
    en: "Sload's Semblance",
    es: "Semblanza del sload",
    fr: "L’Aspect du Sload",
    ru: "Подобие слоада",
    zh: "蛞蝓人的幻影",
  },
  [387]: {
    de: "Nocturnals Gunst",
    en: "Nocturnal's Favor",
    es: "Favor de Nocturnal",
    fr: "Faveur de Nocturne",
    ru: "Благословение Ноктюрнал",
    zh: "诺克图娜的青睐",
  },
  [388]: {
    de: "Ägis von Galenwe",
    en: "Aegis of Galenwe",
    es: "Égida de Galenwe",
    fr: "L’Égide de Galenwe",
    ru: "Эгида Галенве",
    zh: "加伦韦之护",
  },
  [389]: {
    de: "Waffen von Relequen",
    en: "Arms of Relequen",
    es: "Blasón de Relequen",
    fr: "Les Armes de Relequen",
    ru: "Вооружение Релеквена",
    zh: "瑞利昆恩的武装",
  },
  [390]: {
    de: "Mantel von Siroria",
    en: "Mantle of Siroria",
    es: "Manto de Siroria",
    fr: "Le Manteau de Siroria",
    ru: "Мантия Сирории",
    zh: "希罗利亚衣钵",
  },
  [391]: {
    de: "Gewandung von Olorime",
    en: "Vestment of Olorime",
    es: "Vestimentas de Olorime",
    fr: "La Vêture d'Olorimë",
    ru: "Одеяние Олоримы",
    zh: "奥尔奥瑞姆的法衣",
  },
  [392]: {
    de: "Perfektionierte Ägis von Galenwe",
    en: "Perfected Aegis of Galenwe",
    es: "Égida de Galenwe perfeccionada",
    fr: "L’Égide de Galenwe perfectionnée",
    ru: "Совершенная эгида Галенве",
    zh: "完美加伦韦之护",
  },
  [393]: {
    de: "Perfektionierte Waffen von Relequen",
    en: "Perfected Arms of Relequen",
    es: "Blasón de Relequen perfeccionado",
    fr: "Armes de Relequen perfectionnées",
    ru: "Совершенное вооружение Релеквена",
    zh: "完美瑞利昆恩的武装",
  },
  [394]: {
    de: "Perfektionierter Mantel von Siroria",
    en: "Perfected Mantle of Siroria",
    es: "Manto de Siroria perfeccionado",
    fr: "Le Manteau de Siroria perfectionné",
    ru: "Совершенная мантия Сирории",
    zh: "完美希罗利亚衣钵",
  },
  [395]: {
    de: "Perfektionierte Gewandung von Olorime",
    en: "Perfected Vestment of Olorime",
    es: "Vestimentas de Olorime perfeccionadas",
    fr: "La vêture d'Olorimë perfectionnée",
    ru: "Совершенное одеяние Олоримы",
    zh: "完美奥尔奥瑞姆的法衣",
  },
  [397]: { de: "Balorgh", en: "Balorgh", es: "Balorgh", fr: "Balorgh", ru: "Балорг", zh: "巴洛格" },
  [398]: { de: "Vykosa", en: "Vykosa", es: "Vykosa", fr: "Vykosa", ru: "Вайкоса", zh: "维科萨" },
  [399]: {
    de: "Hanus Mitgefühl",
    en: "Hanu's Compassion",
    es: "Compasión de Hanu",
    fr: "La Compassion de Hanu",
    ru: "Сострадание Хану",
    zh: "哈努的怜悯",
  },
  [400]: {
    de: "Blutmond",
    en: "Blood Moon",
    es: "Luna de sangre",
    fr: "La Lune de sang",
    ru: "Кровавая луна",
    zh: "血月",
  },
  [401]: {
    de: "Zuflucht von Ursus",
    en: "Haven of Ursus",
    es: "Amparo de Ursus",
    fr: "Le Havre d'Ursus",
    ru: "Опека Урсус",
    zh: "乌瑟丝的避风港",
  },
}
