apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/component: maintenance
    app.kubernetes.io/instance: seaweedfs
    app.kubernetes.io/managed-by: bootstrap
    app.kubernetes.io/name: seaweedfs
    app.kubernetes.io/part-of: cluster-object-store
  name: seaweedfs-maintenance
