import type { EsoAddon } from "../../code-system/eso-addon/eso-addon.page-type.ts"

export const temperLibSets = {
  id: "01a0617b-4b72-7c64-bc02-7f49e4f6ee46",
  pageTypeSlug: "eso-addon",
  slug: "temper-lib-sets",
  definition: "an addon library naming every gear set in the game and saying where each one drops",
  manifest: "json",
  addonManifest: "json",
  partSlugs: [
    "module/lib-sets-casts",
    "module/lib-sets-bool-pair",
    "eso-interface/lib-sets-copy-text-dialog",
    "eso-interface/lib-sets-search-ui-shared-xml",
    "eso-interface/lib-sets-search-ui-keyboard-xml",
    "type-declaration/lib-sets-api",
    "type-declaration/lib-sets-api-2",
    "type-declaration/lib-sets-api-3",
    "type-declaration/lib-sets-api-4",
    "type-declaration/lib-sets-api-5",
    "type-declaration/lib-sets-constant-shapes",
    "type-declaration/lib-sets-copy-dialog-shapes",
    "type-declaration/lib-sets-drop-mechanic-ids",
    "type-declaration/lib-sets-misc-ids",
    "type-declaration/lib-sets-search-ui-globals",
    "type-declaration/lib-sets-search-ui-shapes",
    "type-declaration/lib-sets-search-ui-shapes-2",
    "type-declaration/lib-sets-search-ui-shapes-3",
    "type-declaration/lib-sets-search-ui-shapes-4",
    "type-declaration/lib-sets-set-type-ids",
    "type-declaration/lib-sets-table-keys",
    "module/lib-sets-const-base",
    "module/lib-sets-const-settypes",
    "module/lib-sets-const-dropmechanics",
    "module/lib-sets-drop-name-language-codes",
    "module/lib-sets-drop-name-shared-text",
    "module/lib-sets-drop-name-names-de",
    "module/lib-sets-drop-name-names-en",
    "module/lib-sets-drop-name-names-es",
    "module/lib-sets-drop-name-names-fr",
    "module/lib-sets-drop-name-names-jp",
    "module/lib-sets-drop-name-names-pl",
    "module/lib-sets-drop-name-names-ru",
    "module/lib-sets-drop-name-names-zh",
    "module/lib-sets-drop-name-install-names",
    "module/lib-sets-drop-name-dropmechanic-names-index",
    "module/lib-sets-drop-tip-language-codes",
    "module/lib-sets-drop-tip-shared-text",
    "module/lib-sets-drop-tip-tooltips-de",
    "module/lib-sets-drop-tip-tooltips-en",
    "module/lib-sets-drop-tip-tooltips-es",
    "module/lib-sets-drop-tip-tooltips-fr",
    "module/lib-sets-drop-tip-tooltips-jp",
    "module/lib-sets-drop-tip-tooltips-pl",
    "module/lib-sets-drop-tip-tooltips-ru",
    "module/lib-sets-drop-tip-tooltips-zh",
    "module/lib-sets-drop-tip-install-tooltips",
    "module/lib-sets-drop-tip-dropmechanic-tooltips-index",
    "module/lib-sets-loc-game-strings",
    "module/lib-sets-loc-language-codes",
    "module/lib-sets-loc-on-off-labels",
    "module/lib-sets-loc-strings-de",
    "module/lib-sets-loc-strings-en",
    "module/lib-sets-loc-install-localization",
    "module/lib-sets-loc-localization-index",
    "module/lib-sets-loc-rest-game-strings",
    "module/lib-sets-loc-rest-language-codes",
    "module/lib-sets-loc-rest-strings-es",
    "module/lib-sets-loc-rest-strings-fr",
    "module/lib-sets-loc-rest-strings-jp",
    "module/lib-sets-loc-rest-strings-pl",
    "module/lib-sets-loc-rest-strings-ru",
    "module/lib-sets-loc-rest-strings-zh",
    "module/lib-sets-loc-rest-install-localization-rest",
    "module/lib-sets-loc-rest-localization-rest-index",
    "module/lib-sets-const-textures",
    "module/lib-sets-const-textures-maps",
    "module/lib-sets-const-casts",
    "module/lib-sets-const-all-dlc",
    "module/lib-sets-const-all-classdata",
    "module/lib-sets-data-casts",
    "module/lib-sets-gen-blacklisted-set-ids",
    "module/lib-sets-gen-no-set-id-sets",
    "module/lib-sets-preloaded-dungeon-zone-mapping-01",
    "module/lib-sets-preloaded-public-dungeon-zone-mapping-01",
    "module/lib-sets-preloaded-sets-armor-types-01",
    "module/lib-sets-preloaded-sets-equip-types-01",
  ],
  interfaceSlugs: [
    "lib-sets-copy-text-dialog",
    "lib-sets-search-ui-shared-xml",
    "lib-sets-search-ui-keyboard-xml",
  ],
  invariants: [
    {
      invariantKind: "constraint",
      statement: "A caller reaches this library through a game global rather than an import.",
    },
    {
      invariantKind: "departure",
      statement: "Set data is taken from the upstream library at a pinned commit.",
    },
    {
      invariantKind: "departure",
      statement: "A set is looked up by its numeric set id.",
    },
  ],
} as const satisfies EsoAddon
