import type { ServiceCluster } from "akasha/infrastructure/service/akasha-service/service-cluster/service-cluster.page-type.types.ts"

export const alanwaltonWeb = {
  id: "01a05b26-f8b6-7a67-91f5-db8495f03998",
  type: "page-type/service-cluster",
  slug: "alanwalton-web",
  definition: "what runs Alan's command center in the cluster",
  resourceKind: "Deployment",
  namespace: "alanwalton",
  resourceName: "web",
  image: "registry.registry.svc.cluster.local:5000/web-app/alanwalton-web",
  replicas: 1,
  containerPort: 3000,
  probePath: "/api/health",
  workloadClass: "serve",
  runtimeEnv: [
    { name: "PAGE_WRITER", value: "alanwalton-web" },
    {
      name: "HANDOVER_SIGNING_KEY",
      fromSecret: { resourceName: "alanwalton-login-secrets", resourceKey: "HANDOVER_SIGNING_KEY" },
    },
  ],
  minCpuMillicores: 100,
  maxCpuMillicores: 500,
  minMemoryMb: 1024,
  killMemoryMb: 1024,
  manifests: "yaml",
  secrets: [
    "secret/alanwalton-secrets-admin-user-id",
    "secret/alanwalton-secrets-cron-secret",
    "secret/alanwalton-secrets-geoapify-api-key",
    "secret/alanwalton-secrets-mcp-api-key",
    "secret/alanwalton-secrets-reading-relay-secret",
    "secret/alanwalton-secrets-spotify-client-id",
    "secret/alanwalton-secrets-spotify-client-secret",
    "secret/alanwalton-secrets-telnyx-public-key",
    "secret/alanwalton-secrets-webhook-secret",
    "secret/collections-secrets-scraperapi-api-key",
    "secret/collections-secrets-trakt-client-id",
    "secret/git-transport-secrets-git-access-token",
    "secret/alanwalton-secrets-atlas-session-key",
    "secret/alanwalton-secrets-google-oauth-client-id",
    "secret/alanwalton-secrets-google-oauth-client-secret",
    "secret/alanwalton-secrets-handover-public-key",
    "secret/alanwalton-secrets-handover-signing-key",
    "secret/alanwalton-secrets-requests-session-key",
    "secret/alanwalton-secrets-session-key",
    "secret/alanwalton-secrets-stripe-webhook-secret",
  ],
} as const satisfies ServiceCluster
