apiVersion: v1
kind: Secret
metadata:
    name: postgres-cnpg-superuser
    namespace: postgres
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:6lPWa3vS5vA=,iv:6WfXOI9xNkT4TyLIwxj+FrvZWbF0sBlXd9W4eSqfJpo=,tag:j2bamXOdbcdJQf0Stw5hlg==,type:str]
    password: ENC[AES256_GCM,data:qRDIQlLm4r86d4u8Ym9Z78HFam1cbiFC+bY1M3LlgTf1uS6MW1mSmw==,iv:HGWo8KCOcwqJQ3R1BCtUWbonSCYYjuTykdY/zVD7h/o=,tag:h6hQ1Fcqfzt1bAygPbKdfQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvNThEWkx4azlPcEUyYnpa
            MkJwS05vcDh6VURncERGQWdUL01hR214WldjCnNCUVBPRGZIWjZlQzgxTVpoSG5L
            SCt6T2RpMWpISko1MmNWUUNaakc2aUkKLS0tIEFCWkFvV0FVSThIM0Fld0k0eEpU
            R3hPMXlxWVJtRmxZMS9KZkt1WTlod1kKcQumHSWMLbJENBCikN6XI7iuQN/pg/8F
            sxmjtUQhD8eCXN7XFz7lh/o/tZ5ExoR7JrtJvSTQ+lGET/psjiqMmw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-01T15:31:12Z"
    mac: ENC[AES256_GCM,data:dkmaD7EsR4bXVkrWtSZZqxgxYfayBUl7oBUi2Bd/dpWX58cyaq+zE2f8JR6avrMOIIqjBy4e9fwlWu9pYYvpZc+IKZNmmtTRZGA2rEHO5gKNitmoW1UMdV+uLvcJOssFzo4lKMwKFnjKVFAkxdwR0Xvn3FQKGzKnNrSsqwYAuG0=,iv:S9LJY/URRAdDZAa/e5WN+yYNrXdo562wnYEKR9SzVA8=,tag:m5FOTPp5w7QyorZn9mQ1+w==,type:str]
    version: 3.13.1
