import type { SkillTemplate } from "../character-skill-template/character-skill-template.module.code.ts"

export const CHARACTER_SKILLS_29 = {
  "ghostly-embrace": {
    id: "ghostly-embrace" as const,
    esoSkillId: 40118308,
    name: "Ghostly Embrace",
    baseName: "Grave Grasp",
    skillLineId: "necromancer-bone-tyrant" as const,
    skillType: "active" as const,
    description:
      "Summon three patches of skeletal claws from the ground in front of you, each dealing 898 Frost Damage.\n\nThe first area applies the Chilled status effect, the second area deals an additional 1635 Frost Damage over 5 seconds, and the final area creates a corpse if at least one enemy was hit.",
    icon: "/esoui/art/icons/ability_necromancer_009_b.dds",
    isMorph: true,
    morphIndex: 1,
    lineRankNeeded: 42,
    rank: 8,
    subcategoryId: "necromancer-bone-tyrant" as const,
  },
  "ghostly-embrace-118308": {
    id: "ghostly-embrace-118308" as const,
    esoSkillId: 118308,
    name: "Ghostly Embrace",
    baseName: "Grave Grasp",
    skillLineId: "necromancer-bone-tyrant" as const,
    skillType: "active" as const,
    description:
      "Summon three patches of skeletal claws from the ground in front of you, each dealing |cffffff3305|r Frost Damage.\n\nThe first area applies the Chilled status effect, the second area deals an additional |cffffff5375|r Frost Damage over |cffffff5|r seconds, and the final area creates a corpse if at least one enemy was hit.",
    icon: "/esoui/art/icons/ability_necromancer_009_b.dds",
    isMorph: true,
    morphIndex: 1,
    lineRankNeeded: 42,
    rank: 42,
    subcategoryId: "necromancer-bone-tyrant" as const,
  },
  "gibbering-shelter": {
    id: "gibbering-shelter" as const,
    esoSkillId: 40192380,
    name: "Gibbering Shelter",
    baseName: "Gibbering Shield",
    skillLineId: "arcanist-soldier-of-apocrypha" as const,
    skillType: "ultimate" as const,
    description:
      "Gather the true strength of Apocrypha, forming a tentacle damage shield that absorbs 60% of all damage for 10 seconds, up to a max of 31733 damage.\n\nWhen the shield absorbs damage, pseudopods cascade out at up to 11 allies within 15 meters, granting them a damage shield for 4 seconds that absorbs up to 5462 damage. These shields can be applied once every 4 seconds. Both shields scale off your Max Health.",
    icon: "/esoui/art/icons/ability_arcanist_012_b.dds",
    isMorph: true,
    morphIndex: 2,
    lineRankNeeded: 12,
    rank: 12,
    subcategoryId: "arcanist-soldier-of-apocrypha" as const,
  },
  "gibbering-shelter-192380": {
    id: "gibbering-shelter-192380" as const,
    esoSkillId: 192380,
    name: "Gibbering Shelter",
    baseName: "Gibbering Shield",
    skillLineId: "arcanist-soldier-of-apocrypha" as const,
    skillType: "ultimate" as const,
    description:
      "Gather the true strength of Apocrypha, forming a tentacle damage shield that absorbs |cffffff60|r% of all damage for |cffffff10|r seconds, up to a max of |cffffff44973|r damage.\n\nWhen the shield absorbs damage, pseudopods cascade out at up to 11 allies within 15 meters, granting them a damage shield for |cffffff4|r seconds that absorbs up to |cffffff7742|r damage. These shields can be applied once every |cffffff4|r seconds. Both shields scale off your Max Health.",
    icon: "/esoui/art/icons/ability_arcanist_012_b.dds",
    isMorph: true,
    morphIndex: 2,
    lineRankNeeded: 12,
    rank: 12,
    subcategoryId: "arcanist-soldier-of-apocrypha" as const,
  },
  "gibbering-shield": {
    id: "gibbering-shield" as const,
    esoSkillId: 183676,
    name: "Gibbering Shield",
    baseName: "Gibbering Shield",
    skillLineId: "arcanist-soldier-of-apocrypha" as const,
    skillType: "ultimate" as const,
    description:
      "Gather the true strength of Apocrypha around you, forming protective tentacles and a damage shield that absorbs |cffffff60|r% of all damage for |cffffff10|r seconds, up to a max of |cffffff44973|r damage, scaling off your Max Health.\n\nWhen the shield collapses you lash out, dealing all of the damage absorbed as Magic Damage to enemies within 5 meters over |cffffff10|r seconds.",
    icon: "/esoui/art/icons/ability_arcanist_012.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 12,
    rank: 12,
    subcategoryId: "arcanist-soldier-of-apocrypha" as const,
  },
  "gift-of-magnus": {
    id: "gift-of-magnus" as const,
    esoSkillId: 45260,
    name: "Gift of Magnus",
    baseName: "Gift of Magnus",
    skillLineId: "racial-breton-skills" as const,
    skillType: "passive" as const,
    description: "Increases your Max Magicka by 2000.",
    icon: "/esoui/art/icons/ability_armor_004.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 30,
    rank: 3,
    subcategoryId: "racial-breton-skills" as const,
    effects: [
      { "metricId": "magicka-maximum", "effectType": "integer", "effectValue": 2000 },
    ] as const,
    status: "supported" as const,
  },
  "gift-of-magnus-35995": {
    id: "gift-of-magnus-35995" as const,
    esoSkillId: 35995,
    name: "Gift of Magnus",
    baseName: "Gift of Magnus",
    skillLineId: "racial-breton-skills" as const,
    skillType: "passive" as const,
    description: "Increases your Max Magicka by |cffffff600|r.",
    icon: "/esoui/art/icons/ability_armor_004.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 5,
    rank: 5,
    subcategoryId: "racial-breton-skills" as const,
  },
  "glacial-colossus": {
    id: "glacial-colossus" as const,
    esoSkillId: 40122388,
    name: "Glacial Colossus",
    baseName: "Frozen Colossus",
    skillLineId: "necromancer-grave-lord" as const,
    skillType: "ultimate" as const,
    description:
      "Unleash a frostbitten Flesh Colossus to pulverize enemies in the area. The Colossus smashes the ground three times over 3 seconds, dealing 3098 Frost Damage with each smash. The final smash stuns all enemies hit for 4 seconds.\n\nDealing damage applies Major Vulnerability to any enemy hit for 17 seconds, increasing their damage taken by 10%.",
    icon: "/esoui/art/icons/ability_necromancer_006_a.dds",
    isMorph: true,
    morphIndex: 2,
    lineRankNeeded: 12,
    rank: 12,
    subcategoryId: "necromancer-grave-lord" as const,
  },
  "glacial-colossus-122388": {
    id: "glacial-colossus-122388" as const,
    esoSkillId: 122388,
    name: "Glacial Colossus",
    baseName: "Frozen Colossus",
    skillLineId: "necromancer-grave-lord" as const,
    skillType: "ultimate" as const,
    description:
      "Unleash a frostbitten Flesh Colossus to pulverize enemies in the area. The Colossus smashes the ground three times over |cffffff3|r seconds, dealing |cffffff11379|r Frost Damage with each smash. The final smash stuns all enemies hit for |cffffff4|r seconds.\n\nDealing damage applies Major Vulnerability to any enemy hit for |cffffff17|r seconds, increasing their damage taken by |cffffff10|r%.",
    icon: "/esoui/art/icons/ability_necromancer_006_a.dds",
    isMorph: true,
    morphIndex: 2,
    lineRankNeeded: 12,
    rank: 12,
    subcategoryId: "necromancer-grave-lord" as const,
  },
  "glacial-presence": {
    id: "glacial-presence" as const,
    esoSkillId: 86192,
    name: "Glacial Presence",
    baseName: "Glacial Presence",
    skillLineId: "warden-winters-embrace" as const,
    skillType: "passive" as const,
    description:
      "Increases your chance to apply the Chilled status effect by 250% and increases its damage by 105. The damage increasing effect scales off the higher of your Weapon or Spell Damage.",
    icon: "/esoui/art/icons/passive_warden_002.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 18,
    rank: 2,
    subcategoryId: "warden-winters-embrace" as const,
    effects: [] as const,
    status: "unsupported" as const,
  },
  "glacial-presence-86191": {
    id: "glacial-presence-86191" as const,
    esoSkillId: 86191,
    name: "Glacial Presence",
    baseName: "Glacial Presence",
    skillLineId: "warden-winters-embrace" as const,
    skillType: "passive" as const,
    description:
      "Increases your chance to apply the Chilled status effect by |cffffff125|r% and increases its damage done by |cffffff209|r. The damage increasing effect scales off the higher of your Weapon or Spell Damage.",
    icon: "/esoui/art/icons/passive_warden_002.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 8,
    rank: 8,
    subcategoryId: "warden-winters-embrace" as const,
  },
  "glyphic-of-the-tides": {
    id: "glyphic-of-the-tides" as const,
    esoSkillId: 40193794,
    name: "Glyphic of the Tides",
    baseName: "Vitalizing Glyphic",
    skillLineId: "arcanist-curative-runeforms" as const,
    skillType: "ultimate" as const,
    description:
      "Summon an Apocryphal glyphic, which you and your allies can heal. The glyphic spawns at 53% Health and grows stronger the more you heal it.\n\nThe power within the glyphic grants up to 200 Weapon and Spell Damage and heals you and your allies around it for up to 928 Health every 1 second in proportion to its Health.\n\nAt full Health the glyphic grants Major Protection, reducing damage taken by 10%.",
    icon: "/esoui/art/icons/ability_arcanist_018_a.dds",
    isMorph: true,
    morphIndex: 1,
    lineRankNeeded: 12,
    rank: 8,
    subcategoryId: "arcanist-curative-runeforms" as const,
  },
  "glyphic-of-the-tides-193794": {
    id: "glyphic-of-the-tides-193794" as const,
    esoSkillId: 193794,
    name: "Glyphic of the Tides",
    baseName: "Vitalizing Glyphic",
    skillLineId: "arcanist-curative-runeforms" as const,
    skillType: "ultimate" as const,
    description:
      "Summon an Apocryphal glyphic, which you and your allies can heal. The glyphic spawns at |cffffff53|r% Health and grows stronger the more you heal it.\n\nThe power within the glyphic grants up to |cffffff200|r Weapon and Spell Damage and heals you and your allies around it for up to |cffffff2921|r Health every |cffffff1|r second in proportion to its Health.\n\nAt full Health the glyphic grants Major Protection, reducing damage taken by |cffffff10|r%.",
    icon: "/esoui/art/icons/ability_arcanist_018_a.dds",
    isMorph: true,
    morphIndex: 1,
    lineRankNeeded: 12,
    rank: 12,
    subcategoryId: "arcanist-curative-runeforms" as const,
  },
  "gourmand": {
    id: "gourmand" as const,
    esoSkillId: 44610,
    name: "Gourmand",
    baseName: "Gourmand",
    skillLineId: "craft-provisioning" as const,
    skillType: "passive" as const,
    description: "Adds 20 minutes to the duration of any eaten food.",
    icon: "/esoui/art/icons/ability_provisioner_004.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 3,
    rank: 3,
    subcategoryId: "craft-provisioning" as const,
  },
  "grace": {
    id: "grace" as const,
    esoSkillId: 45549,
    name: "Grace",
    baseName: "Grace",
    skillLineId: "armor-light-armor" as const,
    skillType: "passive" as const,
    description:
      "Reduces the effectiveness of snares applied to you by 4% for each piece of Light Armor worn.\n\nCurrent bonus: 0%.\n\nReduces the cost of Sprint by 3% for each piece of Light Armor worn.\n\nCurrent bonus: 0%.",
    icon: "/esoui/art/icons/ability_armor_004.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 2,
    rank: 3,
    subcategoryId: "armor-light-armor" as const,
    effects: [
      {
        "metricId": "stamina-sprint-cost",
        "valueType": "fractional-change",
        "effectType": "armor-piece-scaling",
        "armorWeight": "light",
        "valuePerPiece": -0.03,
      },
    ] as const,
    status: "partially-supported" as const,
  },
  "grand-healing": {
    id: "grand-healing" as const,
    esoSkillId: 28385,
    name: "Grand Healing",
    baseName: "Grand Healing",
    skillLineId: "weapon-restoration-staff" as const,
    skillType: "active" as const,
    description:
      "Summon restoring spirits with your staff, healing you and your allies in the target area for |cffffff14597|r Health over |cffffff10|r seconds.",
    icon: "/esoui/art/icons/ability_restorationstaff_004.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 2,
    rank: 2,
    subcategoryId: "weapon-restoration-staff" as const,
  },
  "grave-grasp": {
    id: "grave-grasp" as const,
    esoSkillId: 115177,
    name: "Grave Grasp",
    baseName: "Grave Grasp",
    skillLineId: "necromancer-bone-tyrant" as const,
    skillType: "active" as const,
    description:
      "Summon three patches of skeletal claws from the ground in front of you. Enemies in the first area are snared by |cffffff30|r% for |cffffff5|r seconds, immobilized in the second area for |cffffff4|r seconds, and stunned in the final area for |cffffff3|r seconds.\n\nEach patch applies Minor Maim to enemies hit for |cffffff10|r seconds, reducing their damage done by |cffffff5|r%.",
    icon: "/esoui/art/icons/ability_necromancer_009.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 42,
    rank: 42,
    subcategoryId: "necromancer-bone-tyrant" as const,
  },
  "grave-lord-s-sacrifice": {
    id: "grave-lord-s-sacrifice" as const,
    esoSkillId: 117749,
    name: "Grave Lord's Sacrifice",
    baseName: "Sacrificial Bones",
    skillLineId: "necromancer-grave-lord" as const,
    skillType: "active" as const,
    description:
      "Summon a skeleton from the ground after |cffffff2.5|r seconds. The skeleton leaps to you, sacrificing the fallen soul within and mastering your necromantic energies for |cffffff20|r seconds, increasing your damage done with Necromancer abilities and damage over time effects by |cffffff15|r%. While active, your third cast of Flame Skull damages in an |cffffff6|r meter area.\n\nCreates a corpse on death if you are in combat.",
    icon: "/esoui/art/icons/ability_necromancer_002_b.dds",
    isMorph: true,
    morphIndex: 2,
    lineRankNeeded: 4,
    rank: 4,
    subcategoryId: "necromancer-grave-lord" as const,
  },
} satisfies Record<string, SkillTemplate>
