import { resolve } from "node:path"
import { clusterRoleRules } from "@akasha/cluster-manifests/rbac-cluster-role-rules"
import { LABELS, SA_NAME, SA_NAMESPACE, SUBJECTS } from "@akasha/cluster-manifests/rbac-identity"
import { tupleOf, tupleSet } from "@akasha/cluster-manifests/rbac-permissions"
import { profileSources } from "@akasha/cluster-manifests/rbac-profiles"
import {
  clusterRoleBinding,
  clusterRoleWithRules,
  serviceAccount,
} from "@akasha/cluster-manifests/rbac-yaml"
import type { Answer, Given } from "@akasha/command-system/calling"
import { whyOf } from "@akasha/command-system/fault-saying"

const DATA = 2

const INPUT = 1

const OPERATIONAL = 3

export const CLUSTER_ROLE_NAME = "pipeline-engine-cluster-deploy"

export const HEADER = `# DO NOT EDIT — generated by \`akasha cluster-rbac-manifest\`
# To modify RBAC permissions, update the rbac-cluster-role-rules module of
# @akasha/cluster-manifests for the ClusterRole, or the per-package rbac module
# beside it for a namespace Role
`

export type Read = { readonly said: true } | { readonly refused: readonly string[] }

export function readIn(argv: readonly string[]): Read {
  const refusals: string[] = []
  for (const one of argv) {
    refusals.push(`\`${one}\` is nothing this takes — this takes nothing at all`)
  }
  if (refusals.length > 0) return { refused: refusals }
  return { said: true }
}

export async function gapsIn(root: string): Promise<readonly string[]> {
  const covered = tupleSet(clusterRoleRules, { skipNamed: true })
  const gaps: string[] = []
  for (const source of await profileSources(root)) {
    for (const profile of source.profiles) {
      for (const rule of profile.rules) {
        for (const apiGroup of rule.apiGroups) {
          for (const resource of rule.resources) {
            for (const verb of rule.verbs) {
              if (covered.has(tupleOf(apiGroup, resource, verb))) continue
              gaps.push(
                `${source.path} — ${profile.namespace}: { apiGroup: "${apiGroup}", ` +
                  `resource: "${resource}", verb: "${verb}" }`
              )
            }
          }
        }
      }
    }
  }
  return gaps
}

export function documentIn(): string {
  const sections = [
    serviceAccount(SA_NAME, SA_NAMESPACE, LABELS),
    clusterRoleWithRules(CLUSTER_ROLE_NAME, LABELS, clusterRoleRules),
    clusterRoleBinding(CLUSTER_ROLE_NAME, LABELS, SUBJECTS),
  ]
  return HEADER + sections.join("\n---\n") + "\n"
}

export function lines(yaml: string): readonly string[] {
  const held = yaml.split("\n")
  while (held.length > 0 && held[held.length - 1] === "") held.pop()
  return held
}

export async function clusterRbacManifest(argv: readonly string[], given: Given): Promise<Answer> {
  const read = readIn(argv)
  if ("refused" in read) return { report: [], refusals: read.refused, code: INPUT }
  let gaps: readonly string[]
  try {
    gaps = await gapsIn(resolve(given.root))
  } catch (thrown) {
    return { report: [], refusals: [whyOf(thrown)], code: OPERATIONAL }
  }
  if (gaps.length > 0) {
    return {
      report: [],
      refusals: [
        `the ClusterRole would not cover ${gaps.length} permission the namespace Roles grant, and applying it would leave the cluster refusing those Roles`,
        ...gaps,
      ],
      code: DATA,
    }
  }
  try {
    return { report: [...lines(documentIn())], refusals: [], code: 0 }
  } catch (thrown) {
    return { report: [], refusals: [whyOf(thrown)], code: OPERATIONAL }
  }
}
