import type { StoryTurnPlayed } from "akasha/story/world/stories/played/turns/story-turn-played.page-type.types.ts"

export const overwhereI00095 = {
  id: "01a0fedf-e541-7886-ae78-96d9c41fe2d0",
  type: "page-type/story-turn-played",
  slug: "overwhere-i-00-095",
  ownLength: 418,
  unit: "unit/words",
  partOfCollections: ["story-played/overwhere-i"],
  position: 95,
  prose: "txt",
  characters: ["character-player/overwhere-i-nala"],
  stepStatus: "step-status/recorders",
  action: "“I’ll take all three”",
  beats: [
    "\"I'll take all three,\" Nala says, and counts out 13 copper into the innkeeper's broad palm.",
    "Mutton stew at the long table; the drover, Hob Tanner, holds forth to anyone who'll listen.",
    '"Factor Ivo Tessaly sold me duds! Dark crystals, empty as a drum, sold to me as full!"',
    "The tub takes a quarter hour of kettles; she sinks into hot water with a cake of lye soap.",
    "Upstairs she bars the door of a narrow room and sleeps on the straw tick through a quiet night.",
    "She wakes whole: the last bolt wounds have closed to tender, healing seams.",
    "At six they roll; she holds the gentle push at the cart's back, steady and easy on the mule.",
    "Farmland slides past, quiet; by half past eleven Wendlow's grey stone wall rises by the river.",
    "At the gate a watchman takes a copper a head and asks each stranger's business.",
    'He eyes Nala, the bulging sack on her shoulder and the crossbow. "And yours, woman?"',
  ],
  lore: [
    "lore/overwhere-i-ivo-tessaly",
    "lore/overwhere-i-nala",
    "lore/overwhere-i-nala-2",
    "lore/overwhere-i-osric-fenn",
    "place/overwhere-i-greyback-and-east-road",
    "place/overwhere-i-wendlow",
  ],
  reviewedBy: ["story-reviewer/style", "story-reviewer/continuity"],
  recordedBy: ["story-recorder/inventory", "story-recorder/memory", "story-recorder/mechanics"],
  endsAt: "2026-10-05T11:30:00.000Z",
} as const satisfies StoryTurnPlayed
