import type { StoryTurnPlayed } from "akasha/story/world/stories/played/turns/story-turn-played.page-type.types.ts"

export const overwhereI00042 = {
  id: "01a0f3c9-c3ee-7cf5-bd94-806823623653",
  type: "page-type/story-turn-played",
  slug: "overwhere-i-00-042",
  unit: "unit/words",
  partOfCollections: ["story-played/overwhere-i"],
  position: 42,
  stepStatus: "step-status/writer",
  action:
    "“Eh, I’ll think about it. Need to do some training first anyways. Worst case, I bet I can outrun them.” Since I’m full on mana, I go out a ways from town into the wilderness then practice. I first practice my movement skills, trying differently combinations of two elements to see which one lets me move fastest, testing on both solid ground and marshy ground. Then I test my fire beam to see how far off a distance it can reach. Then I test air and earth for firing a rock bullet as fast and far as possible to compare. Then I try air and fire mixed to create a wide-effect burst attack.",
  beats: [
    "Nala tells Jory she'll think about Rowan; she needs training first, and bets she can outrun them.",
    "She walks out of Fenwatch past the last fields, to where firm heath meets the edge of the marsh.",
    "She wills air and earth together; the ground kicks back under each stride, a horse's gallop.",
    "On the marsh the same weave sinks into the soft ground and slows her to a fast run.",
    "She wills air and water; she skims over the wet marsh like a skater, gallop-fast again.",
    "On the dry heath the skim finds nothing to ride and gives her no speed at all.",
    "She tries fire and air at her back; it pushes no faster than plain wind and scorches the heather.",
    "She knows her plain Surge wind still wins a short dash, but each weave lasts its full minute.",
    "She points at a lone stone, then further marks, and looses a fire beam at each in turn.",
    "The beam holds whole to about thirty yards, then spreads and cools, gone by fifty.",
    "She weaves air and earth into a rock bullet; it cracks away faster than any sling stone.",
    "It flies about a hundred and fifty yards, and lands true on her marks out to about sixty.",
    "She weaves fire and air and pushes it out wide; flame fans in a half-circle ten yards deep.",
    "The heather in the fan blackens and smokes; each tuft takes half the force of a blast.",
    "[Starfall Weave has reached Level 2.]",
    "[Attunement +3.]",
    "Mana 96 of 232, and the afternoon is still young; she stands on the scorched heath.",
    "Fenwatch is a mile back, Rowan Coalby with it, and the marsh stretches on beside her.",
  ],
  lore: ["lore/overwhere-i-starfall-legacy"],
  endsAt: "2026-09-30T13:48:00.000Z",
} as const satisfies StoryTurnPlayed
