import type { StoryTurnPlayed } from "akasha/story/world/stories/played/turns/story-turn-played.page-type.types.ts"

export const overwhereI00082 = {
  id: "01a0fde2-59b9-7e3d-a6a5-0a8c3566251b",
  type: "page-type/story-turn-played",
  slug: "overwhere-i-00-082",
  ownLength: 186,
  unit: "unit/words",
  partOfCollections: ["story-played/overwhere-i"],
  position: 82,
  prose: "txt",
  characters: [
    "character-player/overwhere-i-nala",
    "character-other/overwhere-i-mirren-dask",
    "character-other/overwhere-i-quarry-crewman-five",
    "character-other/overwhere-i-harl-voss",
    "character-other/overwhere-i-quarry-crewman-three",
  ],
  stepStatus: "step-status/recorders",
  action:
    "I take a blade from one of the downed men and stab both through the neck to make sure they are fully down, then quietly fall back a bit and start quietly circling, giving my mana some time to recharge.",
  beats: [
    "The warm rush floods through her, and a blue System window opens: Level 9.",
    "The window lists Strength +2, Dexterity +2, Vigor +2, Attunement +4, Luck +1.",
    "The pressure behind her breastbone deepens, as it did at every level before.",
    "She takes the short sword from the helmed crossbowman's belt.",
    "She drives it through his neck, then through Crow's among the roots; both are dead already.",
    "Sword in hand, she slips back off the track into the pines and turns north.",
    "She circles wide through the trees, slow and soft-footed, and the woods stay quiet behind her.",
    "Forty minutes on, the ground rises, and she comes to the rim of a hill fold from the north-west.",
    "Thirty yards below lie a turf hut, a smoky fire and four charcoal mounds facing the track.",
    "Three men crouch behind the mounds with crossbows, watching the cart track.",
    "By the hut door Harl Voss packs a sack, glancing again and again at the track.",
    "She lies flat in the pines on the rim as Voss knots the sack shut and looks up the track again.",
  ],
  issues: [
    '"a little fresh mana settles there" - lore: a level-up refills neither health nor mana',
    '"You lie in the pines on the rim, your well half refilled." - Leave It Open',
  ],
  lore: [
    "lore/overwhere-i-nala",
    "lore/overwhere-i-nala-2",
    "lore/overwhere-i-starfall-legacy",
    "lore/overwhere-i-starfall-legacy-2",
    "lore/overwhere-i-the-deserter-crew-2",
    "lore/overwhere-i-the-deserter-crew-2-2",
    "lore/overwhere-i-the-system-2",
  ],
  reviewedBy: ["story-reviewer/continuity", "story-reviewer/style"],
  endsAt: "2026-10-03T17:04:00.000Z",
} as const satisfies StoryTurnPlayed
