import type { StoryTurnPlayed } from "akasha/story/world/stories/played/turns/story-turn-played.page-type.types.ts"

export const overwhereI00100 = {
  id: "01a0ff2a-d3fe-782d-b2c1-4ef28428194e",
  type: "page-type/story-turn-played",
  slug: "overwhere-i-00-100",
  ownLength: 319,
  unit: "unit/words",
  partOfCollections: ["story-played/overwhere-i"],
  position: 100,
  prose: "txt",
  characters: [
    "character-player/overwhere-i-nala",
    "character-other/overwhere-i-harl-voss",
    "character-other/overwhere-i-ghost-eye",
  ],
  stepStatus: "step-status/recorders",
  action: "“I’m Nala, Nala Arthur”",
  beats: [
    '"I\'m Nala. Nala Arthur," she says.',
    'Grete writes "Nala Arthur" on the receipt in a square hand, then signs beneath it.',
    "From the strongbox she counts gold onto the counter in stacks of ten, sixty in all.",
    '"That empties the box. Voss, eight of his crew and Ghost-Eye make seventy-one. Board owes you 11."',
    "She writes a chit for eleven gold to Nala Arthur, signs it, and blots the ink.",
    '"Good in two days. The tax rider brings the magistrate\'s purse on the ninth; bring this back then."',
    'She lifts both heads. "These hang in the hall. Ears and tags go in the Board\'s chest."',
    "By the hearth the two hunters sit with their dice forgotten in their fists, watching the gold.",
    "Grete leans on the counter. \"There's a hunters' roll, free to join. Rolled hunters get first call.\"",
    '"First call on Board contracts. You\'d answer to the Board for your kills,"',
    '"and bring word of any monster you see. Want your name on it, Nala Arthur?"',
  ],
  issues: ['"Costs nothing." - Plain Negation'],
  lore: [
    "lore/overwhere-i-nala",
    "lore/overwhere-i-nala-2",
    "lore/overwhere-i-the-system-2",
    "place/overwhere-i-wendlow",
  ],
  reviewedBy: ["story-reviewer/continuity", "story-reviewer/style"],
  recordedBy: ["story-recorder/mechanics", "story-recorder/inventory"],
  endsAt: "2026-10-05T12:30:00.000Z",
} as const satisfies StoryTurnPlayed
