import type { StoryTurnPlayed } from "akasha/story/world/stories/played/turns/story-turn-played.page-type.types.ts"

export const overwhereI00078 = {
  id: "01a0fdab-3196-7da1-a4fa-b26b501ef619",
  type: "page-type/story-turn-played",
  slug: "overwhere-i-00-078",
  cover: "image/image-64ac8fb6c296c2b5",
  coverAfter: "You stand on the game trail at twenty to four, the deer",
  ownLength: 192,
  unit: "unit/words",
  partOfCollections: ["story-played/overwhere-i"],
  position: 78,
  prose: "txt",
  characters: [
    "character-player/overwhere-i-nala",
    "character-other/overwhere-i-quarry-crewman-one",
    "character-other/overwhere-i-quarry-crewman-two",
  ],
  stepStatus: "step-status/player",
  action:
    "I use my concentrated beam of fire to finish the two men, aiming for the heads, then quietly start tracking the four that got away",
  beats: [
    "From the rim Nala draws a thread of fire tight and looses a beam at the sitting blademan's head.",
    "It burns through; Blademan Two slumps against the wall, dead, his sword sliding off his knees.",
    "Blademan One, half-senseless, only stirs; her second beam takes him in the head, and he is still.",
    "The gallery falls silent but for the tick of cooling stone.",
    "She turns to the goat path top and sets off north-east after the four men's boot prints.",
    "The trail runs hurried through the pines, and she follows it, slow and quiet on her hurt leg.",
    "A quarter mile on, the ground turns to bare rock and deep needle beds between the trunks.",
    "She follows scuffs across the rock for long minutes until they meet a game trail.",
    "The marks she has been following are deer slots, small and split; the boot prints are gone.",
    "She stands on the game trail at twenty to four, deer slots running on ahead into the pines.",
  ],
  issues: ['"Somewhere ahead are the four men ... and you\'ve lost their trail." - Leave It Open'],
  lore: [
    "lore/overwhere-i-nala",
    "lore/overwhere-i-nala-2",
    "lore/overwhere-i-osric-fenn",
    "lore/overwhere-i-starfall-legacy",
    "lore/overwhere-i-starfall-legacy-2",
    "lore/overwhere-i-the-deserter-crew-2",
  ],
  reviewedBy: ["story-reviewer/continuity", "story-reviewer/style"],
  recordedBy: [
    "story-recorder/inventory",
    "story-recorder/memory",
    "story-recorder/picture",
    "story-recorder/mechanics",
  ],
  endsAt: "2026-10-03T15:40:00.000Z",
} as const satisfies StoryTurnPlayed
