import type { StoryTurnPlayed } from "akasha/story/world/stories/played/turns/story-turn-played.page-type.types.ts"

export const overwhereI00059 = {
  id: "01a0f485-ba39-7273-a6fe-5dfdf13e97f5",
  type: "page-type/story-turn-played",
  slug: "overwhere-i-00-059",
  ownLength: 253,
  unit: "unit/words",
  partOfCollections: ["story-played/overwhere-i"],
  position: 59,
  prose: "txt",
  characters: ["character-player/overwhere-i-nala", "character-other/overwhere-i-ghost-eye"],
  stepStatus: "step-status/recorders",
  action: "“Sure thing! I wanted a bath tonight anyway.”",
  beats: [
    "Nala and Rowan walk in along the Greyback as the light goes long and gold, Sedge ranging ahead.",
    "At the gate near twenty to six the watch bristles at the sight of Sedge, hands on their spears.",
    "Rowan steps up and speaks for it, stammering, and they let the three of them through.",
    "The Tarred Stag is full for supper: Garrick at the hearth, Agathe at the long table, a score more.",
    "A stranger in a blue coat and wide-brimmed hat sits near the fire, a silver ring in his ear.",
    "Rowan clears his throat, and the hall turns to look at the charcoal burner and the muddy girl.",
    '"Sh-she killed Ghost-Eye. Today. The alpha, and the biggest of its pack."',
    '"And Sedge n-never took your stock. Not once."',
    "The hall goes silent; then Garrick bellows, and every mug in the Stag comes up to Nala.",
    'Agathe rises on her staff. "Rowan Coalby, my oath against your beast is lifted."',
    "\"And you'll winter inside the palisade, if the winter's bad.\" Rowan's face works; he nods.",
    'Garrick claps Nala\'s shoulder. "Bath, supper and bed tonight are on the Stag, and no argument."',
    'Agathe sits down beside her. "The head, though. Antler Hall pays on the head alone."',
    "Rowan mutters of a drake-pearl down the bench, and the stranger in blue is at her elbow.",
    'He sweeps off his hat. "Osric Fenn, pedlar. I hear you\'ve a drake-pearl. Two gold for it, on sight."',
  ],
  lore: [
    "lore/overwhere-i-agathe-morrow",
    "lore/overwhere-i-fenwatch-2",
    "lore/overwhere-i-garrick-pell",
    "lore/overwhere-i-nala",
    "lore/overwhere-i-nala-2",
    "lore/overwhere-i-osric-fenn",
    "lore/overwhere-i-rowan-coalby",
    "place/overwhere-i-greyback-and-east-road",
  ],
  reviewedBy: ["story-reviewer/continuity", "story-reviewer/style"],
  endsAt: "2026-10-01T17:50:00.000Z",
} as const satisfies StoryTurnPlayed
