import type { StoryTurnPlayed } from "akasha/story/world/stories/played/turns/story-turn-played.page-type.types.ts"

export const overwhereI00002 = {
  id: "01a0ed3c-a86d-7f9b-8d7b-1872063e7eef",
  type: "page-type/story-turn-played",
  slug: "overwhere-i-00-002",
  ownLength: 320,
  unit: "unit/words",
  partOfCollections: ["story-played/overwhere-i"],
  position: 2,
  prose: "txt",
  characters: ["character-player/overwhere-i-nala"],
  stepStatus: "step-status/recorders",
  action:
    "“Okay, Isekai protocol” I say quietly. “Status? System?” I focus on the words to see if I can get more information.",
  beats: [
    'Nala says quietly, "Okay, Isekai protocol. Status? System?" and focuses on the blue letters.',
    "The two lines fold away, and a larger blue screen opens in their place.",
    "Status: Name ???, Species Human, Level 1, Class: None.",
    "Stats: Strength 8, Dexterity 10, Vigor 9, Attunement 30, Luck 12.",
    "Vitals: Health 40/40, Mana 120/120, Stamina 30/30.",
    "Reserves: Earth 20/20, Fire 20/20, Wind 20/20, Water 20/20, Electricity 20/20.",
    "Skills: none listed.",
    "At the bottom, one line on its own: Legacy: ???",
    'A second, smaller line answers "System?": [Unrecognized request. Please see the help menu...]',
    "Attunement 30 stands out, more than double anything else; Mana 120 is triple her Health.",
    "Her eyes rest on Legacy: ??? and the pressure behind her breastbone stirs, as if it heard its name.",
    "Focusing harder on the ??? gives nothing more; the letters stay steady and blank.",
    "Overhead the morning sky is a pale red, and the sun in it is small and white.",
    "Up the far bank, heavy footfalls come down the ridge track, unhurried, not hiding.",
    "A shaggy black beast the size of a small bear shoulders out of the pines above the ford.",
    "Its muzzle is sooty black; its short snout is crowded with pointed teeth.",
    "It is thick-necked and heavy-boned, and its forepaws match the prints in the mud.",
    "It stops at the water's edge, twenty yards across the shallows, and sees her sitting on the stones.",
    "It lowers its head, and hisses at her like an enormous cat.",
  ],
  issues: [
    '"three times anything else" - Luck 12 on the same screen makes Attunement 30 only 2.5 times it',
    '"three times your Strength, three times your Vigor" - Attunement 30 is 3.75x Strength 8, 3.3x Vigor',
  ],
  lore: [
    "lore/overwhere-i-nala",
    "lore/overwhere-i-sootjaw",
    "lore/overwhere-i-the-system",
    "place/overwhere-i-greyfen-ford",
  ],
  reviewedBy: ["story-reviewer/continuity", "story-reviewer/style"],
  recordedBy: ["story-recorder/mechanics"],
  endsAt: "2026-09-29T10:08:00.000Z",
} as const satisfies StoryTurnPlayed
