import type { StoryTurnPlayed } from "akasha/story/world/stories/played/turns/story-turn-played.page-type.types.ts"

export const overwhereI00028 = {
  id: "01a0f342-bd02-794d-b0e8-8005c01008f3",
  type: "page-type/story-turn-played",
  slug: "overwhere-i-00-028",
  ownLength: 246,
  unit: "unit/words",
  partOfCollections: ["story-played/overwhere-i"],
  position: 28,
  prose: "txt",
  characters: ["character-player/overwhere-i-nala"],
  stepStatus: "step-status/recorders",
  action:
    "“Hmm, could you show me the holes? I’d like to try killing them in the daylight first. I think I can get them even where they are hiding if I know where they are. I’d don’t really want to wait until nighttime, that feels like forever away.” I say with a grin.",
  beats: [
    "Nala grins and asks Jory to show her the holes; she wants to try them by daylight, where they hide.",
    'Jory looks at her a long moment, then barks a laugh. "Daylight. Aye, I\'ll take you."',
    "He hangs the last eel, wipes his hands, and leads her out through the village.",
    "His own path crosses the Greyback north of the cart track, steep and narrow through the pines.",
    "From the ridge the Greyfen spreads west below them, reed and alder and dark water.",
    "They come down to the fen's edge an hour after setting out.",
    "The channels here run tea-dark and chest-deep, three or four yards across.",
    "Jory's wicker traps sit in the water, half of them torn open and empty.",
    'He leads her along the bank and stops, pointing. "There. See the slide?"',
    "A smooth mud slide runs down the bank into the water, polished by a long body.",
    "In the reeds above it, a small round air hole.",
    '"Tunnel goes up from under water," Jory says, "to a dry den in the bank, under that hole."',
    "Forty yards on he shows her a second slide, and a second air hole in the reeds above.",
    '"That\'s two," he says. "There\'s three of them, but I\'ve only ever found two holes."',
  ],
  lore: [
    "lore/overwhere-i-greyfen-beasts",
    "lore/overwhere-i-nala",
    "place/overwhere-i-fenwatch",
    "place/overwhere-i-greyback-and-east-road",
    "place/overwhere-i-the-greyfen",
  ],
  reviewedBy: ["story-reviewer/style", "story-reviewer/continuity"],
  recordedBy: ["story-recorder/inventory", "story-recorder/memory", "story-recorder/mechanics"],
  endsAt: "2026-09-30T10:41:00.000Z",
} as const satisfies StoryTurnPlayed
