import type { StoryTurnPlayed } from "akasha/story/world/stories/played/turns/story-turn-played.page-type.types.ts"

export const overwhereI00024 = {
  id: "01a0f221-99c5-7fd4-867f-3bc81de52393",
  type: "page-type/story-turn-played",
  slug: "overwhere-i-00-024",
  cover: "image/image-9f07c3deba31147e",
  ownLength: 189,
  unit: "unit/words",
  partOfCollections: ["story-played/overwhere-i"],
  position: 24,
  prose: "txt",
  characters: ["character-player/overwhere-i-nala"],
  stepStatus: "step-status/recorders",
  action: "I pick up the tusks and bring them back to town for the bounty.",
  beats: [
    "Nala picks up the tusks, one in each hand, and sets off north through the alder carr.",
    "The carr thins to the oat strips, rooted and torn where the sounder fed at dawn.",
    "The fields are empty. Far off, smoke rises from the charcoal mounds; the reed beds are busy.",
    "Some twenty minutes on she reaches the south palisade, muddy and bloodied to the elbows.",
    "The green is quiet this morning, most of the village out at work.",
    "In the Tarred Stag, Garrick Pell is sweeping; Agathe Morrow sits at the long table with her tallies.",
    "Garrick stops sweeping and stares at the tusks, and at the state of her.",
    "Nala lays the tusks on the table in front of the reeve.",
    "Agathe turns one over in her hands, then looks up at Nala.",
    '"The old boar," she says. "The one rooting our oats."',
    "She unlocks the chest and counts five silver coins onto the table.",
    '"The hide and meat are yours by rights," she says. "I\'ll send a cart for the carcass."',
    "\"If you'll sell the meat, I'll buy it for the village at two silver.\"",
  ],
  lore: [
    "lore/overwhere-i-agathe-morrow",
    "lore/overwhere-i-garrick-pell",
    "lore/overwhere-i-greyfen-beasts",
    "lore/overwhere-i-nala",
    "place/overwhere-i-fenwatch",
  ],
  reviewedBy: ["story-reviewer/style", "story-reviewer/continuity"],
  recordedBy: ["story-recorder/memory", "story-recorder/picture", "story-recorder/mechanics"],
  endsAt: "2026-09-30T08:29:00.000Z",
} as const satisfies StoryTurnPlayed
