import type { StoryTurnPlayed } from "akasha/story/world/stories/played/turns/story-turn-played.page-type.types.ts"

export const overwhereI00051 = {
  id: "01a0f436-eeab-75ef-b14d-ccc80bc9fe24",
  type: "page-type/story-turn-played",
  slug: "overwhere-i-00-051",
  ownLength: 135,
  unit: "unit/words",
  partOfCollections: ["story-played/overwhere-i"],
  position: 51,
  prose: "txt",
  characters: [
    "character-player/overwhere-i-nala",
    "character-other/overwhere-i-ghost-eye",
    "character-other/overwhere-i-pine-isle-drakewolf-six",
    "character-other/overwhere-i-pine-isle-drakewolf-seven",
    "character-other/overwhere-i-pine-isle-drakewolf-eight",
  ],
  stepStatus: "step-status/recorders",
  action: "I fire an artillery shot again, seeing if I can hit Ghost-Eye this time",
  beats: [
    "Nala draws another slug and pours two weaves into it, the cost dragging hard on her mana.",
    "She rises on one knee, lifts her aim higher for the drop, and looses.",
    "The slug arcs out over the channel and falls spent, splashing a few yards short of Ghost-Eye.",
    "Ghost-Eye watches the splash, then turns its good eye full on her hummock and holds it there.",
    "Its snarl drops away; it stands easy at the water's edge, unhurried.",
    "It gives a low, short growl to the wolves at its side.",
    "The two biggest slip off the shore, one north and one south, and drop into the reeds.",
    "Ghost-Eye and the last wolf stay on the shore, watching her hummock.",
    "The other two are gone from sight in the reeds, one north of her and one south.",
  ],
  issues: ['"stand watching you, and stay where they are" - No Prompt'],
  lore: [
    "lore/overwhere-i-nala",
    "lore/overwhere-i-nala-2",
    "lore/overwhere-i-the-greyfen-alpha-2",
  ],
  reviewedBy: ["story-reviewer/continuity", "story-reviewer/style"],
  endsAt: "2026-10-01T13:32:00.000Z",
} as const satisfies StoryTurnPlayed
