import type { TemperSet } from "akasha/temper/catalog/gear/temper-set/temper-set.page-type.types.ts"

export const voidBash = {
  id: "019e6484-5fd9-706e-b092-fb9b92bcf419",
  type: "page-type/temper-set",
  slug: "void-bash",
  title: "Void Bash",
  key: "void-bash",
  esoSetId: 558,
  hashPlace: 666,
  esoItemIds: [169876, 169877, 169878, 169879, 169892],
  esoEquipTypes: ["EQUIP_TYPE_OFF_HAND", "EQUIP_TYPE_ONE_HAND"],
  esoWeaponTypes: [
    "WEAPONTYPE_AXE",
    "WEAPONTYPE_DAGGER",
    "WEAPONTYPE_HAMMER",
    "WEAPONTYPE_SHIELD",
    "WEAPONTYPE_SWORD",
  ],
  setWayshrines: [457, 457, 457],
  setTypeId: 1,
  setNameZh: "虚无猛击",
  setNameRu: "Удар пустоты",
  setNameFr: "Percussion du vide",
  setNameEs: "Aporreo del Vacío",
  setNameDe: "Leerenwucht",
  setDropZones: [1227, 1207, 1207],
  setDropMechanics: [5, 5],
  setDlcId: 20,
  itemBrowserSources: ["1227"],
  itemBrowserPlaceKinds: [5],
  itemBrowserItemId: 169994,
  category: "temper-set-category/arena",
  valid: ["sword", "axe", "mace", "dagger", "shield"],
  bonuses: "jsonl",
  icons: "jsonl",
} as const satisfies TemperSet
