import type { TemperSet } from "akasha/temper/catalog/gear/temper-set/temper-set.page-type.types.ts"

export const stormKnightsPlate = {
  id: "019e66e7-6a94-735e-88c4-9213acf42888",
  type: "page-type/temper-set",
  slug: "storm-knights-plate",
  title: "Storm Knight's Plate",
  key: "storm-knights-plate",
  esoSetId: 93,
  hashPlace: 564,
  esoItemIds: [
    86561, 86562, 86563, 86564, 86565, 86566, 86567, 86568, 86569, 86570, 86571, 86572, 86573,
    86574, 86575, 86576, 86577, 86578, 86579, 86580, 86581, 86582,
  ],
  esoArmorTypes: ["ARMORTYPE_HEAVY"],
  esoEquipTypes: [
    "EQUIP_TYPE_CHEST",
    "EQUIP_TYPE_FEET",
    "EQUIP_TYPE_HAND",
    "EQUIP_TYPE_HEAD",
    "EQUIP_TYPE_LEGS",
    "EQUIP_TYPE_NECK",
    "EQUIP_TYPE_OFF_HAND",
    "EQUIP_TYPE_ONE_HAND",
    "EQUIP_TYPE_RING",
    "EQUIP_TYPE_SHOULDERS",
    "EQUIP_TYPE_TWO_HAND",
    "EQUIP_TYPE_WAIST",
  ],
  esoWeaponTypes: [
    "WEAPONTYPE_AXE",
    "WEAPONTYPE_BOW",
    "WEAPONTYPE_DAGGER",
    "WEAPONTYPE_FIRE_STAFF",
    "WEAPONTYPE_FROST_STAFF",
    "WEAPONTYPE_HAMMER",
    "WEAPONTYPE_HEALING_STAFF",
    "WEAPONTYPE_LIGHTNING_STAFF",
    "WEAPONTYPE_SHIELD",
    "WEAPONTYPE_SWORD",
    "WEAPONTYPE_TWO_HANDED_AXE",
    "WEAPONTYPE_TWO_HANDED_HAMMER",
    "WEAPONTYPE_TWO_HANDED_SWORD",
  ],
  setWayshrines: [17, 17, 17],
  setTypeId: 9,
  setNameZh: "风暴骑士铠甲",
  setNameRu: "Панцирь грозового рыцаря",
  setNameFr: "L’Armure de plate du chevalier-tempête",
  setNameEs: "Peto del Caballero de la Tormenta",
  setNameDe: "Wut des Sturmritters",
  setDropZones: [19, 19, 142, 19, 19],
  setDropMechanics: [7, 8, 9, 10, 25],
  setDlcId: 0,
  itemBrowserSources: ["19"],
  itemBrowserItemId: 86596,
  category: "temper-set-category/overland",
  valid: ["*:heavy"],
  bonuses: "jsonl",
  icons: "jsonl",
} as const satisfies TemperSet
