import type { LocationEntry } from "../leads-location-types/leads-location-types.module.code.ts"
import {
  LOCDATA_LONG_ANTIQUEMAP,
  LOCDATA_LONG_EXCAVATIONREWARD,
  LOCDATA_LONG_STARTER,
  LOCDATA_LONG_TREASUREMAP,
  LOCDATA_SHORT_ANTIQUEMAP,
  LOCDATA_SHORT_EXCAVATIONREWARD,
  LOCDATA_SHORT_STARTER,
  LOCDATA_SHORT_TREASUREMAP,
  LOCDATA_TYPE_ALLLOOTTABLES,
  LOCDATA_TYPE_ANTIQUEMAP,
  LOCDATA_TYPE_DAILY,
  LOCDATA_TYPE_DELVE,
  LOCDATA_TYPE_EXCAVATIONREWARD,
  LOCDATA_TYPE_FIXLOCATION,
  LOCDATA_TYPE_GROUPDUNGEON,
  LOCDATA_TYPE_MOB,
  LOCDATA_TYPE_NODE,
  LOCDATA_TYPE_PUBLICDUNGEON,
  LOCDATA_TYPE_SAFEBOX,
  LOCDATA_TYPE_STARTER,
  LOCDATA_TYPE_TREASURECHEST,
  LOCDATA_TYPE_TREASUREMAP,
  LOCDATA_TYPE_WORLDBOSS,
} from "../leads-location-types/leads-location-types.module.code.ts"

export const LOCATIONS_7: Record<number, LocationEntry> = {
  395: {
    description: "Covenant Mobs",
    type: LOCDATA_TYPE_MOB,
    short: "Covenant Mobs",
    complete: true,
  },
  396: {
    description: "(PD) Zenithar's Abbey: All Bosses",
    type: LOCDATA_TYPE_PUBLICDUNGEON,
    short: "(PD) Zenithar's Abbey",
    complete: true,
  },
  397: {
    description: "Dark Brotherhood Supply Drop in Outlaw refuges. Requires Skill point",
    type: "Dark Brotherhood Supply Drop",
    short: "Dark Brotherhood",
    complete: true,
  },
  398: {
    description: "(GD) Cradle of Shadows",
    type: LOCDATA_TYPE_GROUPDUNGEON,
    short: "(GD) Cradle of Shadows",
    complete: true,
  },
  399: {
    description: "Bosses in all Delves",
    type: LOCDATA_TYPE_DELVE,
    short: "(D) All",
    complete: true,
  },
  400: {
    description: "(PD) Forgotten Crypt: All Bosses",
    type: LOCDATA_TYPE_PUBLICDUNGEON,
    short: "(PD) Forgotten Crypt",
    complete: true,
  },
  401: {
    description: "Ruined Hut SW of Stonewastes Wayshrine (59.67,78.86)",
    type: LOCDATA_TYPE_FIXLOCATION,
    short: "Ruined Hut",
    complete: true,
  },
  402: {
    description:
      "West of Vunalk delve behind a large shrine in a long tunnel located (30.75,36.99)",
    type: LOCDATA_TYPE_FIXLOCATION,
    short: "Behind shrine",
    complete: true,
  },
  403: {
    description:
      "In Stonewastes Village in dilapitated building upper floor. have to jump (63.90,79.83)",
    type: LOCDATA_TYPE_FIXLOCATION,
    short: "Dilapitated building",
    complete: true,
  },
  404: {
    description: "In Gulley SSE of The Shattered Xanmeer WB (58.30,85.59)",
    type: LOCDATA_TYPE_FIXLOCATION,
    short: "Gulley",
    complete: true,
  },
  405: {
    description: "Beside Skeleton SE of Leyawin Bridge (30.75,57.69)",
    type: LOCDATA_TYPE_FIXLOCATION,
    short: "Skeleton",
    complete: true,
  },
  406: {
    description: "South of Glenbridge beside tent (66.41,67.52)",
    type: LOCDATA_TYPE_FIXLOCATION,
    short: "Beside tent",
    complete: true,
  },
  407: {
    description: " S-E of Tidewater Cave by tree with Crate, Close to boat (31.74,70.04)",
    type: LOCDATA_TYPE_FIXLOCATION,
    short: "Tree",
    complete: true,
  },
  408: {
    description: "North of Vunalk Delve in House on Island (81.29,63.49)",
    type: LOCDATA_TYPE_FIXLOCATION,
    short: "House on Island",
    complete: true,
  },
  409: {
    description: "North of Silent Halls PD Icon in hole near wheelbarrow (57.91,62.90)",
    type: LOCDATA_TYPE_FIXLOCATION,
    short: "Wheelbarrow",
    complete: true,
  },
  410: {
    description: "Dilapitated Building S-E Xeemhok Lagoon WB (81.66,79.33)",
    type: LOCDATA_TYPE_FIXLOCATION,
    short: "Dilapitated building",
    complete: true,
  },
  411: {
    description: "Ruined Cart S-E of Blueblood wayshrine (37.42,67.77)",
    type: LOCDATA_TYPE_FIXLOCATION,
    short: "Ruined Cart",
    complete: true,
  },
  412: {
    description:
      "castle ruins north of Gideon, east side, down through the trap - Duchess's Private study (56.60,45.35)",
    type: LOCDATA_TYPE_FIXLOCATION,
    short: "Hideout",
    complete: true,
  },
  413: {
    description: "Boat N-W of Xi-Tsei Delve (48.92,75.55)",
    type: LOCDATA_TYPE_FIXLOCATION,
    short: "Boat",
    complete: true,
  },
  414: {
    description: "In cave, NW of Undertow Cavern (17.13,47.40)",
    type: LOCDATA_TYPE_FIXLOCATION,
    short: "Cave",
    complete: true,
  },
  415: {
    description: "South of White Stallion Inn (20.74,45.74)",
    type: LOCDATA_TYPE_FIXLOCATION,
    short: "S White Stallion",
    complete: true,
  },
  416: {
    description: LOCDATA_LONG_TREASUREMAP,
    type: LOCDATA_TYPE_TREASUREMAP,
    short: LOCDATA_SHORT_TREASUREMAP,
    complete: true,
  },
  417: {
    description: LOCDATA_LONG_TREASUREMAP,
    type: LOCDATA_TYPE_TREASUREMAP,
    short: LOCDATA_SHORT_TREASUREMAP,
    complete: true,
  },
  418: {
    description: LOCDATA_LONG_TREASUREMAP,
    type: LOCDATA_TYPE_TREASUREMAP,
    short: LOCDATA_SHORT_TREASUREMAP,
    complete: true,
  },
  419: {
    description: LOCDATA_LONG_TREASUREMAP,
    type: LOCDATA_TYPE_TREASUREMAP,
    short: LOCDATA_SHORT_TREASUREMAP,
    complete: true,
  },
  420: {
    description: LOCDATA_LONG_TREASUREMAP,
    type: LOCDATA_TYPE_TREASUREMAP,
    short: LOCDATA_SHORT_TREASUREMAP,
    complete: true,
  },
  421: {
    description: LOCDATA_LONG_TREASUREMAP,
    type: LOCDATA_TYPE_TREASUREMAP,
    short: LOCDATA_SHORT_TREASUREMAP,
    complete: true,
  },
  422: {
    description: LOCDATA_LONG_TREASUREMAP,
    type: LOCDATA_TYPE_TREASUREMAP,
    short: LOCDATA_SHORT_TREASUREMAP,
    complete: true,
  },
  423: {
    description: LOCDATA_LONG_TREASUREMAP,
    type: LOCDATA_TYPE_TREASUREMAP,
    short: LOCDATA_SHORT_TREASUREMAP,
    complete: true,
  },
  424: {
    description: LOCDATA_LONG_TREASUREMAP,
    type: LOCDATA_TYPE_TREASUREMAP,
    short: LOCDATA_SHORT_TREASUREMAP,
    complete: true,
  },
  425: {
    description: LOCDATA_LONG_TREASUREMAP,
    type: LOCDATA_TYPE_TREASUREMAP,
    short: LOCDATA_SHORT_TREASUREMAP,
    complete: true,
  },
  426: {
    description: LOCDATA_LONG_TREASUREMAP,
    type: LOCDATA_TYPE_TREASUREMAP,
    short: LOCDATA_SHORT_TREASUREMAP,
    complete: true,
  },
  427: {
    description: LOCDATA_LONG_TREASUREMAP,
    type: LOCDATA_TYPE_TREASUREMAP,
    short: LOCDATA_SHORT_TREASUREMAP,
    complete: true,
  },
  428: {
    description: LOCDATA_LONG_TREASUREMAP,
    type: LOCDATA_TYPE_TREASUREMAP,
    short: LOCDATA_SHORT_TREASUREMAP,
    complete: true,
  },
  429: {
    description: LOCDATA_LONG_TREASUREMAP,
    type: LOCDATA_TYPE_TREASUREMAP,
    short: LOCDATA_SHORT_TREASUREMAP,
    complete: true,
  },
  430: {
    description: LOCDATA_LONG_STARTER,
    type: LOCDATA_TYPE_STARTER,
    short: LOCDATA_SHORT_STARTER,
    complete: false,
  },
  431: {
    description: LOCDATA_LONG_EXCAVATIONREWARD,
    type: LOCDATA_TYPE_EXCAVATIONREWARD,
    short: LOCDATA_SHORT_EXCAVATIONREWARD,
    complete: false,
  },
  432: {
    description: LOCDATA_LONG_EXCAVATIONREWARD,
    type: LOCDATA_TYPE_EXCAVATIONREWARD,
    short: LOCDATA_SHORT_EXCAVATIONREWARD,
    complete: false,
  },
  433: { description: "Safebox", type: LOCDATA_TYPE_SAFEBOX, short: "Safebox", complete: false },
  434: {
    description: "Roaming bosses",
    type: LOCDATA_TYPE_WORLDBOSS,
    short: "Roaming bosses",
    complete: false,
  },
  435: {
    description: LOCDATA_LONG_ANTIQUEMAP,
    type: LOCDATA_TYPE_ANTIQUEMAP,
    short: LOCDATA_SHORT_ANTIQUEMAP,
    complete: true,
  },
  436: {
    description:
      "Unusual Metal node beneath thin dead tree north of Wretched Spire wayshrine (81.29,42.29)",
    type: LOCDATA_TYPE_FIXLOCATION,
    short: "Unusual Metal Node",
    complete: false,
  },
  437: {
    description: "(WB)  The Abomination Circle",
    type: LOCDATA_TYPE_WORLDBOSS,
    short: "(WB) The Abomination Circle",
    complete: false,
  },
  438: {
    description: "Daedras anywhere",
    type: LOCDATA_TYPE_ALLLOOTTABLES,
    short: "Daedras",
    complete: false,
  },
  439: { description: "Safebox", type: LOCDATA_TYPE_SAFEBOX, short: "Safebox", complete: false },
  440: {
    description: "(WB) Shivering Shrine",
    type: LOCDATA_TYPE_WORLDBOSS,
    short: "(WB) Shivering Shrine",
    complete: false,
  },
  441: { description: "Clannfear", type: LOCDATA_TYPE_MOB, short: "Clannfear", complete: false },
  442: {
    description: "(WB) Unmaker",
    type: LOCDATA_TYPE_WORLDBOSS,
    short: "(WB) Unmaker",
    complete: false,
  },
  443: {
    description: "(GD) Banished Cells I&II",
    type: LOCDATA_TYPE_GROUPDUNGEON,
    short: "(GD) Banished Cells I&II",
    complete: false,
  },
  444: {
    description: "Deadlands Dailies",
    type: LOCDATA_TYPE_DAILY,
    short: "Deadlands Dailies",
    complete: false,
  },
  445: { description: "Daedrats", type: LOCDATA_TYPE_MOB, short: "Daedrats", complete: false },
  446: {
    description: "Treasure Chest",
    type: LOCDATA_TYPE_TREASURECHEST,
    short: "Treasure Chest",
    complete: false,
  },
  447: {
    description: "Deadlands Dailies",
    type: LOCDATA_TYPE_DAILY,
    short: "Deadlands Dailies",
    complete: false,
  },
  448: {
    description: "(GD) Falkreath Hold Chests",
    type: LOCDATA_TYPE_GROUPDUNGEON,
    short: "(GD) Falkreath Hold Chests",
    complete: false,
  },
  449: {
    description: "(GD) Black Drake Villa",
    type: LOCDATA_TYPE_GROUPDUNGEON,
    short: "(GD) Black Drake Villa",
    complete: false,
  },
  450: {
    description: "Gold Coast Treasure Chest",
    type: LOCDATA_TYPE_TREASURECHEST,
    short: "Treasure Chest",
    complete: false,
  },
  451: {
    description: "(WB) Tribune's Folly",
    type: LOCDATA_TYPE_WORLDBOSS,
    short: "(WB) Tribune's Folly",
    complete: false,
  },
  452: {
    description: "(PD) Atoll of Immolation (Portalevent)",
    type: LOCDATA_TYPE_PUBLICDUNGEON,
    short: "(PD) Atoll of Immolation",
    complete: false,
  },
  453: { description: "Runestone", type: LOCDATA_TYPE_NODE, short: "Runestone", complete: false },
  460: {
    description: "Psijic portals",
    type: LOCDATA_TYPE_NODE,
    short: "Psijic portals",
    complete: false,
  },
  461: { description: "Safebox", type: LOCDATA_TYPE_SAFEBOX, short: "Safebox", complete: false },
  462: {
    description: "(Trial) Sunspire (Dragons)",
    type: "Trial",
    short: "(Trial) Sunspire",
    complete: true,
  },
  463: {
    description: "(GD) Moongrave Fane Adds",
    type: LOCDATA_TYPE_GROUPDUNGEON,
    short: "(GD) Moongrave Fane Adds",
    complete: true,
  },
  464: {
    description: "(GD) Lair of Maarselok, last boss",
    type: LOCDATA_TYPE_GROUPDUNGEON,
    short: "(GD) Lair of Maarselok",
    complete: true,
  },
  465: {
    description: "Watchlings inside Portals (Atoll of Immolation)",
    type: LOCDATA_TYPE_MOB,
    short: "Watchlings inside Portals",
    complete: true,
  },
  466: {
    description: "(GD) Imperial City Prison (Watcher Boss)",
    type: LOCDATA_TYPE_GROUPDUNGEON,
    short: "(GD) Imperial City Prison",
    complete: true,
  },
}
