value: ENC[AES256_GCM,data:1MuQC4JN4tzWtqhpy1DukxElJb6k5mpPGQKMJKECyD4=,iv:OvVdFPO1lB+44DsCZ8XEvZ1Tg/EB4JtfpAIIK2ekcY0=,tag:nco6uhC22aeF9HAr0zn/YA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkN1BXZHRGR1BmMzZFOTh2
            QVYzUTF1WUNkRnNQZllBbmFycEY2VWEvajBFCk00YkVkRVNOY211RnpxcTZyUEg4
            VHViY1VUT25ZMDZRZCs5eFRvSFVCazQKLS0tIC9CUVk4UG9meFV3RW4xaEVMc2JP
            U0UydWp3elhianpSVmxzbHdPV2JPblEKiN+ODyOXh/Q0B3ohV/jCyztgWohy2/4q
            hzAJ4D1Y91knH3gHyO2aRqX+WO2h0KLz+A3mrNdRnVON84EAvDA3Dw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
    lastmodified: "2026-09-06T13:15:39Z"
    mac: ENC[AES256_GCM,data:o6wUsIOO1PNk6EAfwMAtPCa03CpY+jb+PoXNN1UHu3yxf+liINGKvqp9BdQROpQuMlFUm5EypdR0c6q9HbES8E31yMiD2pPIE2Y9v8thsaDIfUGvMvyAjFlWip+DDjdYrni4zVH37ZiWOLbDOAk/E+eNJluP1gX1MCQJkYEwYyA=,iv:l7m9g7E6+qgC4wH8uuaL60E0mi545Nmn5JA5WDnvinE=,tag:kxmuKACKwgdg69Syx/+evA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
