value: ENC[AES256_GCM,data:7ltBxX05zAE3cJ0iVZEZW4DGrWBUT6mBgLdkLnJFUOs=,iv:OBMB2Y9LGPOmQTCbm4KqkOVfx5w1DN9TNeHJWXI3jSs=,tag:ZqxwCpBlbVLMZLF7wJTXLg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwLzZWc3VTRFR0VjVmaUI0
            VnJObjcybFMxNzRCcC9qRExjV01SRStGYXlZCi9zTi9UcG9VbndIUjNyMWdYSXlQ
            NzJLdHU1Z3VzV0d4Ui9WVGFhY2FkK2MKLS0tIEJtRTNCOWVjQzR6QUM3bEorR0VK
            VVQ4blVBNHh1N1hUOVlVVVVsekk0aUEKOp8BElR8FSps412KQgri/Co1AIzoziH1
            T/GAQz31OEaDN+Rs5+G4jXF7ae+LHyx2Ksa7GErmTOIxrKAr6ITRug==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
    lastmodified: "2026-09-06T13:15:52Z"
    mac: ENC[AES256_GCM,data:BNVcyQX7gBewah4HhMl1fKQpH2dlxCLYYibZWglhX+X4CsV/3cBfAcEl6OZqtbsi0tKEdlHjaas5vLIlqenxpRcNNZNwggLS0+KlL7k1HSdwFIp+v/Us9+SW2w5F+XXJz0X/5kwJvfd4uJ9un6CuzyhbEo0Ktip0LXiNOcEX0+w=,iv:G5wXttPWNrVxuR/k7PRXMe99BUUdS6mMK47NIFK+IyY=,tag:FvHx1GBEHkudc2JEK4KVRg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
