value: ENC[AES256_GCM,data:yEtO3iwUmGjgwCvZ3g4k/qtm19ABmg2hk9vNgVchyoAcf5MIHBDeox6P+3AzNE4ilxAhae49JMXHvqMCgmF9Yw==,iv:260aMfUo80hygS40/Y+ZDwp8rS4rk7a9OOIXvLZooY8=,tag:U0QbH8VLRrhbFkdb4mmrCQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBYUtYay9pVGJ1ZWVWYnFU
            UUFvVjB4VkR1V0xPNTk3Zy9KaFcreVhoSkg4CmNLR1dyOVF2L1pOeDFQT3EwZzQ3
            TU13ZUlkMnppME5xNTBlbGt6MGtYOWMKLS0tIFVYKzkrUE10S0hYdlBSdEtPeDQv
            Q2JmaTMraWRwOThNSXNFMWdxR3d4cFEKDCxPE5wr1IU6qzxEp4MjhOwEO+mTCiPU
            FiErz852y+G+2V1SNnrCI2+jQObagnlwX69iFr9CE+qRUT3hI+GX0A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
    lastmodified: "2026-09-21T18:51:35Z"
    mac: ENC[AES256_GCM,data:YTuLsrLs+NgalZUuG6t56Fi0eVE0xb9aIzSC1mV2+RcmWOYnnwDPTAz9AWnYFYJD1hkz0gO9HhPw8vkoCmPX8IRNQhs7KWs1V3yqq5FN9GzYuQ6TM2e+xmpZVqR6yaYVLYfQXs4nvx367iKGUk32HdbnU2z8HYSLfH+bwW+jOXk=,iv:5sbHooueiVuL96Txrfmpb8YCB2SOlt/W+SVlN7WMGkQ=,tag:7R72R3qKeaGbb1JbTxsNRg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
