value: ENC[AES256_GCM,data:SsdqRHO1mVM5mJDKIlyuQgOvx+2heobbN4TBXbGGaCjsEi9IIZQJX+G9+PhpxifhY5hlCTTB7av6Un5NSiaVCg==,iv:SCvCbcns3V8ywoKFH9a4JigMuog4H6qgj2ubZS+iwt0=,tag:pX88wwC2tHgL6rK/fkXUoQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIME53MFlGY1R5ajlUSVg4
            dXVkWkFxdTRyRWozVU5lZnV3LzRKRXFNMXprClU5SGdTN0FtamtPUmRJT0Z0cjY5
            UHpXMm9URWNyWUM1czcrUFBXS1haMWsKLS0tIGhva1RhNHd0UHk5SEFlNmJ1QmtO
            SHVuemN1TjAvb3hZK1RRWmhtRVRURjgKi50PKk0NQUcTQXqgFaU8GH8QOFmjqU1S
            JYt8H2g9zVbPWf2iKuCK1W5mhbmPUG+TbR39l8gdawdOSeMlbmWKcQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
    lastmodified: "2026-09-19T18:31:48Z"
    mac: ENC[AES256_GCM,data:MPiBQhEyUfywXrEw27wVGeOjPI/THguFJfNDDSZPggFUi0aGNRN21i3Cl0Yltq1QeTU2X9sKd6qMHgbLT7LJv7B0v24x49ycCr+cf6XyccpqIlPpGnFDBUVdz9xfFkUGTTfkeWNg9MkPTNULlnISG0GEq/q6xNM289X6G9h6vxI=,iv:S4rkwSegxOWUJ0KhCeWlcKfEmU06ho070TmDXp8kcZ4=,tag:X2IrFYPVqgeegO45GJkKNQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
