value: ENC[AES256_GCM,data:Y5UZyO/Sv8VXld2MzN85YdVSbU09+JI/yqTQ2ibxz10rVGF8,iv:vSM/bHAPQxiGvH8JwWLmYqx6Q9q1tbd9G7EPzrtQfAk=,tag:IWMv5xhvSVJRje5ZvTWj6Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwNGh6bXUzVUs5cEI1b2xM
            V29XOFBTT055aWQyZEtBSDIrTW5oRzl3bkNRCmVLTVo0TS9jbVdsemFnYXJtVEZk
            MFdpaU1nOTloUU4xbHhvcUwwTU5DRW8KLS0tIFV4dHlYU3l0TGp2RytWaUNidHFu
            ck5DMHFMRExab1hWL0xQMmRmRTJzancK77JN7McweG+K04eUbiKHWvLmyu8gXNQm
            y1iCwbBAw2T6uYhMNAkXsGRJdc0BH33/+S+dQ+rQc0aMVvu+n0hNWw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
    lastmodified: "2026-09-06T13:16:38Z"
    mac: ENC[AES256_GCM,data:6Ia7Q8bPCoKqtaSy0ZZ0hOU67haDzrOWChI7SwoLRR7NBbIqKRVfQDmWCkQR5Ku+54tkO9llJZaCbYXSN+LznMhd9oowPAhdBjz/dn91wTUL6c8Rb9j0EbPbPLcYQlKJljr3qjA2/FxgDCHw+3gpHUYWhD4X5H9HhsQKSLopAks=,iv:xfxaJJjVaqqbMycloBhAbifi7DrdyUeXuOt7IuYbR5I=,tag:l4nTBMW1b8kAB7OBrTvS7Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
