value: ENC[AES256_GCM,data:SikyxY43Rc/+z/hHAz1DpgyjKt7pjYSRPcdbYm6VSC5Tc5bnnhgryZEnOy4TyHUptIert4X8GQHe8IUGgyw8Bvaoz128+jlnz7BQK6AqDgg0Pfct4arM4MA1NohrpNwX7xqHLgI76YadV69LKr2dAxI=,iv:menZtzAxLmVuziwhF3Yb1Ww3R43Hn1IXXisxSWYG7YI=,tag:1w+EsxpFTbgL2qLjyvhnAg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyeExJazU0NkRkZ2dwNTFG
            bHBnNkI1KzdrelFqZEdhaTNobXIybUhSelJFCkp6c05SUXJOd0JvUjBxbGQzTkVt
            eVNQNkQ5MDZyMHdHSmQ3U01ENSs2ZkUKLS0tIEc1OEJtdDRab0o2YVVjT1QrRXls
            d2hIMDVwM2R1eFBaR3J4VmVlY25QRkUK6cNN5PmpAnAfP54YNR4UOMvOafTOcD6G
            qZd1f2SOHMNAMHaR0glH/ABS/pQq6+eiiE98r40lxNNnRQDg8QyNBg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
    lastmodified: "2026-09-19T19:54:17Z"
    mac: ENC[AES256_GCM,data:0kUyDMnCGI9qsvRYuRHeZbbMxemHYov8lrd7iqrKmMt/wjRk0tgIHK6es3+vkqyTkd8vlgokSpgFmvfFny95FIslU3CGr8pqLwEFBgtVt7nTflPYLvYCod2Zgd+/MTErTi5IpFQNtV9YCRdyIV4J5ACQfN2YQylLI0y21UDWO0Q=,iv:J3mWLPSJQ+FYjyXOhIvAKNDKHJpToLs4Zdyx2MrnXlY=,tag:4i4UAiJzWKMYM9XUcpKGiA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
