value: ENC[AES256_GCM,data:5+duO6aAApJT+8zVLVtEE0rmLtn+sKq/3SJg/WszPgFKjjn5prA=,iv:hQ2L1KBk9whQ94ppFKli0XV6yLveas+sUmkwhMHQj2A=,tag:kh5W9voruPpZt3NVJx1jtA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiODk3MmFRRmFHUk4zVDFT
            K0RkYURWbnZ1MVlUT2hhR1I4ZGRmV1VzQW5NCldsdmVjMG1XMmI2aE8xYmF0MTYr
            STlBVDArdWRRd3VMc1dUeGRmdlNkOVkKLS0tIE5UU29tVDZnZHdDM2hhd0hhS3hl
            VkZRQk9qTk1YVzlRekF6SisrQnZDem8KZvskc0K8oVlO2wgBzUNiPc3ixdgc80fB
            LhJrQzlWyX+k4x4TvOE/tyeWppThrMF4mB8VIS+HDOsaNv7RyacqtA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
    lastmodified: "2026-09-19T16:55:18Z"
    mac: ENC[AES256_GCM,data:d2dHwkl/UjNN+3PjJpZPW+scB3H2g/gXy/z9Zi9Cj+auyM3erffdVqjpoWXbOAqIKjCwO1mT7pjgrkU8k27Tqse2FKtRoNGzAYCxJkYCfzdK+A6x4LJp/ahSszE9ul+e5wv0y1+l25nKYUbwNIM2nZF/P2zM6apJ0XzMSczT5iI=,iv:Jk68f0xgj520Vnei8D39x4yM0U6tq8SUBfQIWU831ec=,tag:fdU0oeWQCBUzQyr06hu1eQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
