value: ENC[AES256_GCM,data:3lk/9quWpIstmxoMRAQvJzgeuFo9F3146kKeKlNc27E=,iv:l2gX5pbJVzFxNCtzKTtoSy2cWnV5B/wNLuf7P95lZao=,tag:Ep0lq1F93kQlt0KirkYVgA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhdnBhMUpDbFNiaHhpT0JF
            bzhraklWLzNWZlo4cTZTMmRQak1LUHh2WFhvClNzSEo2WUk1bG1mc3JPSmorQmFa
            UDdObEgzT0dGTExHUGQ2aHRNT3ZUd1EKLS0tIGQvMnZBQ0trUGhxWUw0Z3UwYkho
            RWk2OFFENTVmQU1pekVYYU5nblRzY3MKy4U2eoCKBcDOwpOHjPok1hv7TOB7BAf9
            5Ev+3SPR7REUiLkhOAY3ngD9gmUiPiaB3uYFM/0jlgbOSOJvbKEm2w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
    lastmodified: "2026-09-06T13:15:48Z"
    mac: ENC[AES256_GCM,data:mhYLdiy3KRFsu0+JfA7o463m7UH9Cw6FgexPIBT6hAPUfA2tFzaGvmOquuApEAAptzk0htUNVFvxGkENCYvLwnCyEaYStr/b5JSLh51fMmVPn7vSu3MX1FsvfY/wB718CcE6rui/eutyoyZYp3fFpJKG3opBObvAnfOphv5/+bM=,iv:s5BECADRhOpgrrI+kL3x8QSKAdqGmpD9YeLjhlZViwc=,tag:1Mbb+zpNRmWP6PzduMzSYQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
