value: ENC[AES256_GCM,data:5gxZcLj3GtOqtICBjcdSNcQ3sl3DUhnqSo8TS6ujZJ+ud4vt,iv:nQChdIdthr/F0sQh6RP6ZP1q4XAPHsFj3IKTtEra+1Y=,tag:4ivP43R8+yOKbx+aIlehLw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzR29iTS9jS1pCU092bHhK
            elQrM3Zacy96aWdFR1lqT0F2Ulo1Yzh3VlhRCjJWcWpxUXpvbkt3a1dwZ2RnaGpJ
            YTErRDczYWVwWmVRMkNMSW1YdDAyOG8KLS0tIHlrUmkvNDVrZ1BBZllOTEZCMHNM
            VytsTmFKZVd4ajJhaFdxaW9FNHlUb1UKROmUyGd8yC3wg6jM491guB+Z/pSy8I2T
            LlgBb0tomGFFLNo7nYCRkuzX56CFblg9Ah9QUChh07tSoLKrPfX7PA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
    lastmodified: "2026-09-06T13:16:22Z"
    mac: ENC[AES256_GCM,data:zQPhrH682I8ABmAii4HsFc+YNA0ojf12zVPyg6HmeZl8juj0+gviWD7JIzn/3MMoycB54O4V2pUox3buDo3JHCcr+LkpQXbKLBN2FutJBHSv6ASkkYccToGjiWJqyv5bQTEDc+66xtjaGRRrP1Wnz9CeWL18GDjA056M23ro9Uw=,iv:a4Wi1XGUX2+otR0P2Ql6iTOrQncL/ypaCvdM8iQuK4k=,tag:Bw/BI4aeGM8K8LKDAW2Oaw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
