value: ENC[AES256_GCM,data:SB5JuyMyVgrXZONhj1THuuvUkLTV7Y3H5guHDlVmtqGQZNzUzFmGPLMMU7BWBvpWJex4xT2HLbl90JZk3J0LIA==,iv:fyuIA5K8etk5L81DjqYo4ziVy90e62K1xduYphSZj7E=,tag:3O0yr8wnA1GrX2Ll3+vtqA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDK1lhNExQVjJqVkhNYnh0
            VnNqKzE1czB1djlVOGN0VG9aYVhOUVF1UUV3CmFzNTM5U0E3LzRDQzM2SDV2cS96
            V09UMm5UWDE5cVhUQWpXVHd1Z2tUMWcKLS0tIEFUOWZPQlRUZVVZem9QLy9Rai9T
            T0xWOWs4NlI2NzlvdXJSbGlRS3ZVY28Kkk0VGti4tA6mKYWvA2RQQKiSZbSewPDd
            BN12mAmaOSb4jUVGYkIDQ+Qq1FefC40Zk43B33Lbiw48kq+gQk1v/w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
    lastmodified: "2026-09-06T12:39:39Z"
    mac: ENC[AES256_GCM,data:UzxBTtlt+z5KMhNDalsnuOX4q0pMRCy1OrSa0k/2/8YaoWPDXrHvWF1xuLPakCpdRDMLqOdk8Xg7eO/SLZ3okaw9wFl0SUojJ4tWRnTMcHe+H1AdBpiN0X2Z1nhn8UA6EQ4sFvEN/mD6eLQGXIOQiVCGaGbz8S2wXz7PBx+aMdE=,iv:hFrlFuKoYee+xLe58NKYnxpsYfodmoWWnnZeqMcMJCU=,tag:O9r9ll+n1Tjtmm5gFtGv6A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
