value: ENC[AES256_GCM,data:OM9twPAtzvqUO+oDsYB4N74ZSgAj/l6xsgBFw2s025ejKKdNKM9JibkBBpvZD6yVuks=,iv:YO5P/pAr7jnpSIUWHMti8KltxAdItHpbL/K4tc8VskE=,tag:A2gzsh/MTCTGEOs0/l5EwA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuUFJGbjlUL3VkQStIVXVm
            eUxGVHlVakRqYkJCYi9ZTjlEQVFFTjdhcHpVCldRQWJaTHlMNXNkYWdwRk1VTUJv
            OG5yNUZsZ01LcUpINVQzZjB4ZkxQMGMKLS0tIHplSnFRNGhDNE10QWcvY1pBKzNj
            Tk9ka1puTXhCbzFoUkxLOENxbTFybzQKFl1oxsDMzi3JYpKraDdHszn7HJ/PHyLB
            QxCAcFztuDHDBQKTQ4fkATcKYd/tDI20EatAzfTMZjn5wJAAtTsunw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
    lastmodified: "2026-09-06T12:39:02Z"
    mac: ENC[AES256_GCM,data:Ue5puTdUblNJamhvPDx+EXWYagx4PPYVhiIn5fG9qrZ+7Armzkwnk1tQ8xYNRuHAMUuuQzvpeOldzx/bzwqW2JWZSRTmQHPMJRbrOsvJw/vNSxgn0jotyXrI1xp3ed3hiDPIQWFnTiYo3vIcbLrN4n65cXTHd6/efu3NZx/3ePw=,iv:MM1JnBBwCl22CyN64oO82oH5vMuNAYlyIb0/lizYngM=,tag:3I+uslTygkMpyQdfxrigsQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
