value: ENC[AES256_GCM,data:rE82KCfs/+1/InWx7LjJhfO72dPyDcF09RSWpippyG4=,iv:A/eOurFDduwvjrjf7zIsa1LvAuTZfmuZKVMJNT6VbZY=,tag:5EnrKDERhrWRBj5qHAhGwQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYam1iTzBGT3R3YWJ4NGZs
            S1EyOUVYU0J4bEhNS0JwMDZWUndwWHYyb1h3CmhVNitFK0dKODdJcjVhNEFlYUZG
            OHJVL3dSL29BS2dMNzFjZkh2T25sNVEKLS0tIEVkN2w1ZWJDZ0VTQWs3TnJOSUVz
            cEtlRFplbUlnVDJlU0lpQWFoYURYS2MKKYB0O/bugxFTu+kbZlYIOe2UYsgFGicL
            2V7Ssqc7DyIwa3Djrm9TKtmUsylnIwcYj/5sA42dGZ1MDucEUBNTzA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
    lastmodified: "2026-09-06T12:39:18Z"
    mac: ENC[AES256_GCM,data:bpPQexFB2k34508gf3bRQ0ydgT5j2ImU83wKe4iL9t3OUnvoaN55HQvnDOwD9cUTLS6s8u45F0DNTp3OV1xry1DiWXgSOueGQ6jI6EEkv2NK6bEV42sIn83zTD8f1944lBuj24Min18aGeGKsMhYqeMsehS+QksLHhs9hSaKbtY=,iv:bzR3j8EQhnVpk5rfvC5IVY9YzL7tU6iEJBMrq+uFhm4=,tag:h29HpeR9usf683u2K/J3rQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
