value: ENC[AES256_GCM,data:yG7MSVopWhFof/QRpIymh8GEDx8xU12vxcphzDwV8vLlP0cfUwSm3fYn0quvr6ddMmm7ZtgPZRPhXBJq23qAuA==,iv:uAfXysJ1LBnTYWpXNyrWV1KT0cUHMbwBUXp+6P+EnR0=,tag:+7G4NkyFni33rxUtkF0Hlg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMUitMOUR0cUF0UlQraVEy
            SDZFcURsT0luOGtzazYwWElxYktoWnYvSjE0CmhXTmVxNml3d3dUNlpJdEZ4dGZG
            NmJ5NnpEd3lyMU1acEhOOVZ3MXNsZWcKLS0tIDMyalZWeFJTYnBSZjF4aFlwUE96
            ZUFHOHVTTzdIU2x2OGU4YXN6MnBMcm8Kabo0idip6Co468MSPTpFdjXBHDSx6jRT
            RYd5WUrjJVTgFTEO9iS9x8vaSTIGiBeJhCn6reMKl9/JJFK0D5oHGw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
    lastmodified: "2026-09-06T12:39:36Z"
    mac: ENC[AES256_GCM,data:j4Xae41+DqBX07gWTNVEYexcRqfuotkJv3SYQHowCXRpJTMqRcPxRV5LtjLm+dWQCwGjaynOezXyO40C/9/7ZEovfWZJ2tQ4aEPG1Kz0X5dhE+DT9YJiZYppEIPFyh6yCzMsD1vKJ8Wz4MrCnubwCAGR+U2PDQ3USfP0ry2ifuo=,iv:lQ5AhvefzoYpnqvxxL5dmMTE7+QwBeEUMuBrdimL+lM=,tag:Q8S+eGY7JKlUM3+DZwuKcQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
