value: ENC[AES256_GCM,data:jTPuExVv3CdvwjqZ63Uq4dDUfngifhBTKHu01dvl3Ji1mcWdQlhwWu7SXlIpRcCURkJUyw+8DN2l3rzP7qcDzt6Nkzmb1DssUmaBDG4ir2oSSo69SU96QGlldZdZ,iv:Qbr80YDJK+9Q4CNqLA6F2MbTrJiYbUy1VnvdWm7pPgM=,tag:rDuFUp3Nk433vTMXTVhe4g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRdENNMVQ5YWlDb0xqemlS
            VHJqN01MRmxZMEUxaUVpMEdxdHFLTVl3c2c0Ckkyb244SzVxOXYwQmR0cGw3NUdG
            SUlKNS9VaFI4YWNCNmE0dm1WcUU4d1EKLS0tIE5ka25QRVhOeFUrUTkrOHFLRWhO
            M3dubGNmclUwTGkwelU5c0JMamt0YUEKI5GiLuUCv96RCr9Xz3cDjhMe+FnY0M64
            hPU3kMVJlkafK4H/c5PwcN1HrSWIHVFQzBaONIj9bFykT0vcXukXTw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
    lastmodified: "2026-08-28T15:02:41Z"
    mac: ENC[AES256_GCM,data:mqhuIkjahz5MY59Y3GakY09ayNFriENFuIulV26G4A5TCv5wKB/uncOdWYznpWVRJm2NtW5eIU3pEOf95NtZqKs6kZmJmMduVjnwspmbh1KQwzLk+YH2paftst7Y2JbJ72dDM1XIur/AsGTtcWrbyDpgPReBpl+iTdL5k2Xfmwk=,iv:dHkf5nrjYPkWnCiiMbFu5lMDSvbGxtBAEIPa+FSeXMY=,tag:Q3AYgrg+ujbp5rAOOfahEA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
