value: ENC[AES256_GCM,data:PAMbWlSuinrXZfcccQ6W7C7FSz/KWlTiHt5nsMtEHGMJrTqhWdVL2TMgR0rsnXsqcB0WlgVot4MbsFeoy1VFf9Mb4xAoV45v,iv:ksN/DOR1UzsLOVWvqtfnVMrqe7rgUKRMUtFVsEWyhUY=,tag:Vsq9nunkcsX/XN8uAJ00iA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiSmE4YWdCZHRCVG1LSWFP
            ZFc3aUg4MHNDempkWDNpZldxcnQ1cmVDeFc0CjZzM1BRazlMTjZacWJuTmc3MjEz
            c1V4MFlXSWN1L1p6dnE2WDkwZytMSUUKLS0tIE0wbXdHOW9IVWtBazJNWFJHVkwv
            ZityNUlvNWVGaGd3U01FWCtvbTlTWEEKeGDp+LCgMqBmN9jziPkUtASqcvQDRZHZ
            akkUayvaUbhutLHlwVYnX4wEkW83666pulGppsvXaJYFkRScxybQBQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
    lastmodified: "2026-09-06T11:47:48Z"
    mac: ENC[AES256_GCM,data:D7IN/FJSIE23s2Lgz351mX5sCYRMeNsWWprbm4zgXBZP1uMaJBm4TSyRzCWEt54kYGMsJJrhxyQfF9QUz2me5oeQikBB91FS1S9hcasnLLp5ZNU+NWMVE53PrXt9BOd5kAFmlSjWr0dlbe5+xOFyTfewbpeD20COs/pHoDuPkrs=,iv:kO+VIzjloFSuduP+wtFEN1o+4veD+n+1J+SrwgvRmt0=,tag:Wh7OdORowTge5WH2dNJrBQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
