value: ENC[AES256_GCM,data:ak+BQBkzTVvKAU2kwCXrG7lyOqPp4QB2Hsklv7l1dpO+9fTeZ6XejB3s+9vz+40RN8Sy6M8w84fEvAYmYf3d+A==,iv:QjPFBpOwUfdYZ8YHMRKRQQfTtgqYm5zF2zF+YuSomr8=,tag:vbVXB/4VapS6diFwa4UkRA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiUGNEcWJtZW9aK3RScTB6
            eUFKbkw0N0FIQUUrcDhod3hXM3VFZEFldXpJClJwY3JjT0ZJMDQ4SmNsaEQ5dU1U
            VEZhbjF3eTQ0QnVBeUdYRzJORmFmbFEKLS0tIG0wUkpRR1UzQXJLL1ZoS2J3YWwv
            QU95NzE4OTJ0ZVNDNS9JVVQ4NjdHSVEKfulksF9Kq85gOiV35DtcnsdkLpJsaOsF
            5nNL+kUE/qf3z+/KWqLO6t+RtQPTysDXRuk5hjLaexq8CDEfFgw0Fg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
    lastmodified: "2026-09-06T13:16:17Z"
    mac: ENC[AES256_GCM,data:YSXfP7ZtcSqk9B8O+nGSU/gdIFkBednoFRR6dGXis4EHm5Ff0e+8ESy3u0oJRFY9vrms08T78ZyQ92SJIHibeIfMyWhTAavRCqvrc/+HjujlkhrENTEASd7cluZ0mBxdAGaC6Vo77MUPHr1y0h+cT0Qy/3KjXeWC7eWwiiFr0gk=,iv:R9A2EuBZKsjjMct7eU2ioI3ILJ9/8AlZWQwJF2PTqzk=,tag:i2ZAJlTfjicICNYERCAq8A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
