value: ENC[AES256_GCM,data:xyeGcI2D93A83bsRU+1snl3u7Qz1T/kOWUHclh6oibAuFG4q1M7ofqeGUL3veyPga7sJpcENvGdThEPpqgtO0Q==,iv:QGfe4/7qdowoxSquMvCG1zLF+4UrN7Dx5YnuCnHk2gI=,tag:3XNUpVyF447inzfzA9lQZQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWcVhCTWdBdTBrWHVLaTNp
            ZUdKaWJuYkpqRlM1L2xsK2t2OFdsMXlaRDJJCk1RaU1vUWhnZU1OQWFaMGVSdWxE
            MUx0cjFmRjV6RUMrUGdLRTNpWkVEcTgKLS0tIGgwSEdsbmxDN2JUWE1rdnN1Nzd1
            d1g4R0ttbW5PWXduNVdqR05McWVpWmsKZrf12Kpjt+2mb7kdxpr9sfdRppT9fu2x
            uOKxdAQ6oRl3HQWyI9dCFeMDkIdlxEpZ9B66aDrJiiIUZ1FGc/KH8g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
    lastmodified: "2026-09-19T19:42:56Z"
    mac: ENC[AES256_GCM,data:sxiF6OlZEl2zbHYpofOF6NJGr8WPpRBCDhBfwLoAnTmSHneCquxSXiH//90puRKYreRmv2mztixY4d3ITrbABxEQ0Ctng2Xgu7UVbGuMZfpBx9Vzx85CXoPQTP0ji1MLYf0940LPKl4e2ZsFFRT/FDWvpRgIyLctoJ7QjSivKPc=,iv:Gpv/H7qVkdmge0AKu/4DQZ7lsH/6xwVLs2C4NiFeTDc=,tag:LXjuMxWktK5Wd/sxnDhDrw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
