import type { CompanionSkillTemplate } from "../companion-skill-activation-effect-types/companion-skill-activation-effect-types.module.code.ts"

export const COMPANION_SKILLS_03 = {
  "isobel-blessed-sacrament": {
    id: "isobel-blessed-sacrament" as const,
    abilityId: 163614,
    name: "Blessed Sacrament",
    companionId: "isobel" as const,
    skillLineId: "companion-isobel-healing-grace" as const,
    skillType: "active" as const,
    description:
      "Your Companion sends out a burst of soothing light, healing themselves or a nearby ally for $1 Health, and an additional $2 every 2 seconds for $$2 seconds as the light momentarily lingers.",
    icon: "/esoui/art/icons/ability_companion_templar_rushed_ceremony.dds",
    effects: [
      {
        "type": "heal",
        "target": { "type": "self-or-ally", "range": 28, "scope": "single" },
        "formula": {
          "type": "metric-scaling",
          "metricId": "companion-weapon-damage",
          "coefficient": 1.5,
        },
      },
      {
        "type": "hot",
        "target": { "type": "self-or-ally", "range": 28, "scope": "single" },
        "formula": {
          "type": "metric-scaling",
          "metricId": "companion-weapon-damage",
          "coefficient": 0.5625,
          "coefficientType": "per-tick",
        },
        "duration": 8,
        "displayMode": "per-tick",
        "initialTick": true,
        "tickInterval": 2,
        "durationOffset": 2,
      },
      { "type": "cast-time", "duration": 0.76 },
      { "type": "cooldown", "duration": 8 },
    ] as const,
    validRoles: ["healer", "tank"] as const,
    castConditions: [{ "type": "health-threshold", "below": 75, "targetType": "self" }] as const,
  },
  "isobel-divine-destruction": {
    id: "isobel-divine-destruction" as const,
    abilityId: 163564,
    name: "Divine Destruction",
    companionId: "isobel" as const,
    skillLineId: "companion-isobel-blazing-might" as const,
    skillType: "active" as const,
    description:
      "Your Companion unleashes a concentrated beam of divine energy at an enemy, dealing $1 Magic Damage over $$1 seconds.",
    icon: "/esoui/art/icons/ability_companion_templar_over_exposure.dds",
    effects: [
      {
        "type": "dot",
        "target": { "type": "enemy", "range": 28, "scope": "single" },
        "formula": {
          "type": "metric-scaling",
          "metricId": "companion-weapon-damage",
          "coefficient": 11.25,
        },
        "duration": 3,
        "damageType": "magic",
        "displayMode": "total",
        "initialTick": false,
        "tickInterval": 1,
      },
      { "type": "cooldown", "duration": 8 },
      { "type": "channel", "duration": 3 },
    ] as const,
    validRoles: ["dps"] as const,
    castConditions: [{ "type": "health-threshold", "below": 25, "targetType": "enemy" }] as const,
  },
  "isobel-enchanted": {
    id: "isobel-enchanted" as const,
    abilityId: 169474,
    name: "Cunning",
    companionId: "isobel" as const,
    skillLineId: "companion-isobel" as const,
    skillType: "passive" as const,
    description: "Decreases ability cooldowns by 3% and damage taken by 3%.",
    icon: "/esoui/art/icons/ability_companion_templar_cunning.dds",
    effects: [
      {
        "type": "passive",
        "value": -0.03,
        "metricId": "companion-ability-cooldown",
        "modifierType": "fractional-change",
      },
      {
        "type": "passive",
        "value": -0.03,
        "metricId": "companion-damage-taken",
        "modifierType": "fractional-change",
      },
    ] as const,
    validRoles: ["tank"] as const,
  },
  "isobel-gallant-blitz": {
    id: "isobel-gallant-blitz" as const,
    abilityId: 163590,
    name: "Gallant Blitz",
    companionId: "isobel" as const,
    skillLineId: "companion-isobel-brilliant-shield" as const,
    skillType: "active" as const,
    description:
      "Your Companion charges toward their enemy with a vibrant spear that bursts in a flash of light, setting all enemies in the area Off Balance for $$1 seconds.",
    icon: "/esoui/art/icons/ability_companion_templar_focused_charge.dds",
    effects: [
      {
        "type": "apply-status",
        "status": { "status": "off-balance", "duration": 7 },
        "target": { "type": "enemy", "range": 22, "scope": "area" },
      },
      { "type": "cooldown", "duration": 12 },
    ] as const,
    validRoles: [] as const,
  },
  "isobel-holy-ground": {
    id: "isobel-holy-ground" as const,
    abilityId: 163660,
    name: "Holy Ground",
    companionId: "isobel" as const,
    skillLineId: "companion-isobel-healing-grace" as const,
    skillType: "active" as const,
    description:
      "Your Companion consecrates the ground under them for $$1 seconds, healing themselves and nearby allies $1 Health every 2 seconds and snaring enemies by 50%.",
    icon: "/esoui/art/icons/ability_companion_templar_cleansing_ritual.dds",
    effects: [
      {
        "type": "hot",
        "target": { "type": "self-and-ally", "scope": "area", "radius": 12 },
        "formula": {
          "type": "metric-scaling",
          "metricId": "companion-weapon-damage",
          "coefficient": 0.75,
          "coefficientType": "per-tick",
        },
        "duration": 8,
        "displayMode": "per-tick",
        "initialTick": true,
        "tickInterval": 2,
      },
      {
        "type": "apply-status",
        "status": { "status": "snare", "duration": 8, "magnitude": 0.5 },
        "target": { "type": "enemy", "scope": "area", "radius": 12 },
      },
      { "type": "cast-time", "duration": 0.5 },
      { "type": "cooldown", "duration": 16 },
    ] as const,
    validRoles: ["healer", "tank"] as const,
    castConditions: [
      {
        "type": "any",
        "conditions": [
          { "type": "ally-health", "below": 75 },
          { "type": "nearby", "targetType": "enemy" },
        ],
      },
    ] as const,
  },
  "isobel-penetrating-strikes": {
    id: "isobel-penetrating-strikes" as const,
    abilityId: 163458,
    name: "Penetrating Strikes",
    companionId: "isobel" as const,
    skillLineId: "companion-isobel-blazing-might" as const,
    skillType: "active" as const,
    description:
      "Your Companion attacks three times with a magic spear, dealing $1 Magic Damage to all enemies in front of them with each strike. After their assault, Your Companion grants themselves and nearby allies a boon that increases the damage of their next Light or Heavy Attack by 50%.",
    icon: "/esoui/art/icons/ability_companion_templar_trained_attacker.dds",
    effects: [
      {
        "type": "multi-hit",
        "target": { "type": "enemy", "scope": "cone" },
        "formula": {
          "type": "metric-scaling",
          "metricId": "companion-weapon-damage",
          "coefficient": 1,
        },
        "hitCount": 3,
        "damageType": "magic",
      },
      {
        "buff": {
          "buff": "next-attack-damage",
          "value": 0.5,
          "duration": 10,
          "valueType": "fractional-change",
        },
        "type": "apply-buff",
        "target": { "type": "self-and-ally", "scope": "area" },
      },
      { "type": "channel", "duration": 1 },
      { "type": "cooldown", "duration": 16 },
    ] as const,
    validRoles: ["dps", "support"] as const,
  },
  "isobel-solar-ward": {
    id: "isobel-solar-ward" as const,
    abilityId: 163442,
    name: "Solar Ward",
    companionId: "isobel" as const,
    skillLineId: "companion-isobel-brilliant-shield" as const,
    skillType: "active" as const,
    description:
      "Your Companion summons the power of the sun to defend themselves from harm, reducing incoming damage by 20% and granting a damage shield that absorbs up to 12.5% of their Max Health for $$1 seconds.",
    icon: "/esoui/art/icons/ability_companion_templar_sun_shield.dds",
    effects: [
      {
        "buff": {
          "buff": "flat-damage-reduction",
          "value": 0.2,
          "duration": 6,
          "valueType": "fractional-change",
        },
        "type": "apply-buff",
        "target": { "type": "self", "scope": "single" },
      },
      {
        "type": "shield",
        "target": { "type": "self", "scope": "single" },
        "formula": {
          "type": "metric-percent",
          "percent": 12.5,
          "metricId": "companion-health-maximum",
        },
        "duration": 6,
      },
      { "type": "cast-time", "duration": 0.967 },
      { "type": "cooldown", "duration": 8 },
    ] as const,
    validRoles: ["tank"] as const,
  },
  "isobel-spear-of-light": {
    id: "isobel-spear-of-light" as const,
    abilityId: 163725,
    name: "Spear of Light",
    companionId: "isobel" as const,
    skillLineId: "companion-isobel-brilliant-shield" as const,
    skillType: "active" as const,
    description:
      "Your Companion hurls a barrage of spears made of radiant light at all targets in front of them, dealing $1 Magic Damage and knocking them down for $$3 seconds. This attack ignores the enemy's Resistances.",
    icon: "/esoui/art/icons/ability_companion_templar_returning_spear.dds",
    effects: [
      { "type": "special", "effect": "ignore-resistance" },
      {
        "type": "damage",
        "target": { "type": "enemy", "scope": "area" },
        "formula": {
          "type": "metric-scaling",
          "metricId": "companion-weapon-damage",
          "coefficient": 1.5,
        },
        "damageType": "magic",
      },
      {
        "type": "apply-status",
        "status": { "status": "knockup", "duration": 4 },
        "target": { "type": "enemy", "scope": "area" },
      },
      { "type": "cast-time", "duration": 0.467 },
      { "type": "cooldown", "duration": 16 },
    ] as const,
    validRoles: ["dps"] as const,
  },
  "isobel-sun-brand": {
    id: "isobel-sun-brand" as const,
    abilityId: 163452,
    name: "Sun Brand",
    companionId: "isobel" as const,
    skillLineId: "companion-isobel-blazing-might" as const,
    skillType: "active" as const,
    description:
      "Your Companion hurls a blazing ball of fire at an enemy, dealing $1 Flame Damage on impact and an additional $2 Flame Damage over $$2 seconds.",
    icon: "/esoui/art/icons/ability_companion_templar_sun_fire.dds",
    effects: [
      {
        "type": "damage",
        "target": { "type": "enemy", "range": 28, "scope": "single" },
        "formula": {
          "type": "metric-scaling",
          "metricId": "companion-weapon-damage",
          "coefficient": 3,
        },
        "damageType": "flame",
      },
      {
        "type": "dot",
        "target": { "type": "enemy", "range": 28, "scope": "single" },
        "formula": {
          "type": "metric-scaling",
          "metricId": "companion-weapon-damage",
          "coefficient": 2.25,
        },
        "duration": 8,
        "damageType": "flame",
        "displayMode": "total",
        "initialTick": false,
        "tickInterval": 2,
      },
      { "type": "cast-time", "duration": 0.2 },
      { "type": "cooldown", "duration": 12 },
    ] as const,
    validRoles: ["dps"] as const,
  },
  "mirri-blood-transfusion": {
    id: "mirri-blood-transfusion" as const,
    abilityId: 157287,
    name: "Blood Transfusion",
    companionId: "mirri" as const,
    skillLineId: "companion-mirri-soul-thief" as const,
    skillType: "active" as const,
    description:
      "Your Companion infuses an ally with blood, healing them for $1 Health over $$1 seconds.",
    icon: "/esoui/art/icons/ability_companion_nightblade_unique.dds",
    effects: [
      {
        "type": "hot",
        "target": { "type": "ally", "range": 28, "scope": "single" },
        "formula": {
          "type": "metric-scaling",
          "metricId": "companion-weapon-damage",
          "coefficient": 4.5,
        },
        "duration": 8,
        "displayMode": "total",
        "initialTick": true,
        "tickInterval": 2,
      },
      { "type": "cast-time", "duration": 0.366 },
      { "type": "cooldown", "duration": 8 },
    ] as const,
    validRoles: ["healer"] as const,
  },
  "mirri-dynamic": {
    id: "mirri-dynamic" as const,
    abilityId: 157250,
    name: "Dynamic",
    companionId: "mirri" as const,
    skillLineId: "companion-mirri" as const,
    skillType: "passive" as const,
    description: "Increases damage done by 3% and healing done by 3%.",
    icon: "/esoui/art/icons/passive_companion_weapon_023.dds",
    effects: [
      {
        "type": "passive",
        "value": 0.03,
        "metricId": "companion-damage-done",
        "modifierType": "fractional-change",
      },
      {
        "type": "passive",
        "value": 0.03,
        "metricId": "companion-healing-done",
        "modifierType": "fractional-change",
      },
    ] as const,
    validRoles: ["dps", "healer"] as const,
  },
  "mirri-ghostly-evasion": {
    id: "mirri-ghostly-evasion" as const,
    abilityId: 157197,
    name: "Ghostly Evasion",
    companionId: "mirri" as const,
    skillLineId: "companion-mirri-living-shade" as const,
    skillType: "active" as const,
    description:
      "Your Companion surrounds themselves in a phantasmic aura, dodging the next attack made against them while also reducing their damage taken by 20% for $$2 seconds.",
    icon: "/esoui/art/icons/ability_companion_nightblade_009.dds",
    effects: [
      { "type": "special", "effect": "dodge-next-attack" },
      {
        "buff": {
          "buff": "flat-damage-reduction",
          "value": 0.2,
          "duration": 8,
          "valueType": "fractional-change",
        },
        "type": "apply-buff",
        "target": { "type": "self", "scope": "single" },
      },
      { "type": "cast-time", "duration": 0.566 },
      { "type": "cooldown", "duration": 12 },
    ] as const,
    validRoles: ["tank"] as const,
    castConditions: [{ "type": "health-threshold", "below": 75, "targetType": "self" }] as const,
  },
} as const satisfies Record<string, CompanionSkillTemplate>
