import type { WorkspacePackage } from "../../code-system/workspace-package/workspace-package.page-type.ts"

export const temperLorebooks = {
  id: "01a06176-9c44-7c00-8a3b-7cf902e62430",
  pageTypeSlug: "workspace-package",
  slug: "temper-lorebooks",
  definition:
    "the lore books of Tamriel, drawn where a player must go to read one they have not read",
  manifest: "json",
  partSlugs: [
    "module/lorebooks-book-data-00",
    "module/lorebooks-book-data-01",
    "module/lorebooks-book-data-02",
    "module/lorebooks-book-data-03",
    "module/lorebooks-book-data-04",
    "module/lorebooks-book-data-05",
    "module/lorebooks-book-data-06",
    "module/lorebooks-book-data-07",
    "module/lorebooks-book-data-08",
    "module/lorebooks-book-data-09",
    "module/lorebooks-book-data-10",
    "module/lorebooks-book-data-11",
    "module/lorebooks-book-data-12",
    "module/lorebooks-book-data-13",
    "module/lorebooks-book-data-14",
    "module/lorebooks-book-data-15",
    "module/lorebooks-book-data-16",
    "module/lorebooks-book-data-17",
    "module/lorebooks-book-data-18",
    "module/lorebooks-book-data-19",
    "module/lorebooks-book-data-20",
    "module/lorebooks-book-data-21",
    "module/lorebooks-book-data-22",
    "module/lorebooks-book-data-23",
    "module/lorebooks-book-data-24",
    "module/lorebooks-book-data-25",
    "module/lorebooks-book-data-26",
    "module/lorebooks-book-data-27",
    "module/lorebooks-book-data-28",
    "module/lorebooks-book-data-29",
    "module/lorebooks-book-data-30",
    "module/lorebooks-book-data-31",
    "module/lorebooks-book-data-32",
    "module/lorebooks-book-data-33",
    "module/lorebooks-book-data-34",
    "module/lorebooks-book-data-35",
    "module/lorebooks-book-data-36",
    "module/lorebooks-book-data-37",
    "module/lorebooks-book-data-38",
    "module/lorebooks-book-data-39",
    "module/lorebooks-book-data-40",
    "module/lorebooks-book-data-41",
    "module/lorebooks-book-data-42",
    "module/lorebooks-book-data-43",
    "module/lorebooks-book-data-44",
    "module/lorebooks-book-data-45",
    "module/lorebooks-book-data-46",
    "type-declaration/lorebooks-controls",
    "type-declaration/lorebooks-string-ids",
    "module/lorebooks-types",
  ],
  invariants: [
    {
      invariantKind: "departure",
      statement: "Nothing here reaches a Date.",
    },
    {
      invariantKind: "departure",
      statement: "The text here is English alone.",
    },
    {
      invariantKind: "gap",
      statement: "Akasha holds no map pin for a lore book.",
    },
    {
      invariantKind: "gap",
      statement: "Akasha names 4328 of the 4773 book titles this table carries.",
    },
  ],
} as const satisfies WorkspacePackage
