import type { PagePropertyEntry } from "@akasha/pages/page-property-entry"

export type Items = "jsonl"

export const items = {
  id: "01a05fcd-f550-7cd2-9e3a-e8c18d91b7a8",
  pageTypeSlug: "page-property-entry",
  slug: "items",
  propertySlug: "items",
  definition: "every item a sweep read out of the game, one item to a line",
  properties: [
    { pagePropertySlug: "text-property/title", required: true, many: false },
    { pagePropertySlug: "text-property/item-name", required: false, many: false },
    { pagePropertySlug: "text-property/icon", required: true, many: false },
    { pagePropertySlug: "instant-property/mined-at", required: true, many: false },
    { pagePropertySlug: "number-property/item-id", required: true, many: false },
    { pagePropertySlug: "number-property/item-type", required: true, many: false },
    { pagePropertySlug: "number-property/item-quality", required: true, many: false },
    { pagePropertySlug: "number-property/item-style", required: true, many: false },
    { pagePropertySlug: "number-property/merchant-value", required: true, many: false },
    { pagePropertySlug: "number-property/ability-cooldown", required: true, many: false },
    { pagePropertySlug: "text-property/ability-description", required: true, many: false },
    { pagePropertySlug: "text-property/ability-header", required: true, many: false },
    { pagePropertySlug: "number-property/armor-rating", required: true, many: false },
    { pagePropertySlug: "number-property/armor-type", required: true, many: false },
    { pagePropertySlug: "text-property/enchant-description", required: true, many: false },
    { pagePropertySlug: "text-property/enchant-header", required: true, many: false },
    { pagePropertySlug: "number-property/equip-type", required: true, many: false },
    { pagePropertySlug: "number-property/filter-type", required: true, many: false },
    { pagePropertySlug: "number-property/filter-type-specific", required: true, many: false },
    { pagePropertySlug: "text-property/flavor-text", required: true, many: false },
    { pagePropertySlug: "boolean-property/has-on-use-ability", required: true, many: false },
    { pagePropertySlug: "boolean-property/has-set", required: true, many: false },
    { pagePropertySlug: "boolean-property/is-unique", required: true, many: false },
    { pagePropertySlug: "boolean-property/is-unique-equipped", required: true, many: false },
    { pagePropertySlug: "number-property/required-cp", required: true, many: false },
    { pagePropertySlug: "number-property/required-level", required: true, many: false },
    { pagePropertySlug: "record-property/set-bonuses", required: true, many: true, maxCount: null },
    { pagePropertySlug: "number-property/set-id", required: true, many: false },
    { pagePropertySlug: "number-property/set-max-equip", required: true, many: false },
    { pagePropertySlug: "text-property/set-name", required: true, many: false },
    { pagePropertySlug: "number-property/specialized-item-type", required: true, many: false },
    { pagePropertySlug: "text-property/trait-description", required: true, many: false },
    { pagePropertySlug: "number-property/trait-type", required: true, many: false },
    { pagePropertySlug: "number-property/weapon-power", required: true, many: false },
    { pagePropertySlug: "number-property/weapon-type", required: true, many: false },
  ],
} as const satisfies PagePropertyEntry
