import type { Domain } from "../domains/domain.page-type.types.ts"

export const persons = {
  id: "01a053e0-6cf6-7ff5-b070-19e936336f59",
  pageTypeSlug: "domain",
  type: "domain",
  slug: "persons",
  definition: "a human this system reaches, and what serving them takes",

  parts: [
    "page-type/access-kind",
    "page-type/authority-kind",
    "page-type/device-secret",
    "page-type/device-token",
    "page-type/person",
    "page-type/person-access",
    "page-type/person-authority",
    "page-type/sms-consent",
    "module/device-secret-body",
    "module/device-secret-minting",
    "module/device-secret-shape",
    "module/device-secret-keeping",
    "module/device-token-registration",
    "module/health-samples-body",
    "module/person-enrolment",
    "module/person-reading",
    "module/push-apps",
    "module/push-permission",
    "module/push-register-body",
    "module/push-routing",
    "module/route-access",
    "module/sms-consent",
    "module/sms-opt-in",
  ],
} as const satisfies Domain
