import type { Command } from "akasha/commands/command.page-type.types.ts"

export const measureAudit = {
  id: "01a08c17-afc0-7dd8-8fbe-b625407e7a33",
  type: "command",
  slug: "measure-audit",
  definition: "the command saying what a check's audit run cost in processor time and memory",
  code: "ts",
  changeKind: "change-mechanical",
  taking: [
    { said: "--last <count>", takes: "how many of the most recent runs the numbers cover" },
    {
      said: "--last <count>{m|h|d}",
      takes: "the period the numbers cover ending at the moment of asking",
    },
  ],
  helpNotes: [
    "a call naming no argument reads the last one audit run.",
    "a check's runs are kept in two groups, and this command reads the audit group.",
    "`akasha measure checks` reads the other group, holding change, worktree and deploy.",
    "a row of a check's audit logs is an audit run whatever phase that row spells.",
    "the entries beside a check are read too, and hold the history up to today.",
    "an entries row names no group, so the phase that row spells places it.",
    "that placing is the best the entries admit rather than what the writer meant.",
    "a row the logs already hold is not counted again from the entries.",
    "one set of columns is drawn, holding the audit runs alone.",
    "a check holding no audit run is not listed at all.",
    "an audit run judges every page.",
    "one run id is minted for each audit judged.",
    "every check judged over that audit carries that run id.",
    "a record carrying no run id belongs to no run.",
    "a record belonging to no run counts nowhere where runs were counted.",
    "a period counts every record stamped within that period whether a run id is there or not.",
    "a check no run of what was chosen judged is not listed at all.",
    "the total counts the distinct runs read rather than the records read.",
    "the total shares the processor time over the distinct runs read.",
    "the total for one run is exactly what that run took.",
    "the total draws its memory as `-`.",
    "a peak of memory adds to no other peak.",
    "an average is what the runs took together shared out over how many runs there were.",
    "a run's processor time is that run's own together with the children that run reaped.",
    "a run's memory is what that run added over the memory resident when the run opened.",
    "a run that forgot no high-water mark is left out of the memory it would otherwise report.",
    "that run is counted in the processor time all the same.",
    "that run is counted among the runs a check holds all the same.",
    "how many runs a check holds is said before that check's averages.",
    "the paths and the refusals are added up rather than shared out over the runs.",
    "the total counts a run's paths once, since every check of one run judged the same paths.",
    "the total's refusals are the refusals of every record read added together.",
    "checks are ordered by what their runs took on average.",
    "checks taking equal processor time are ordered by name.",
  ],
  invariants: [
    {
      invariantKind: "absence",
      statement: "A run writes no value the commit has.",
    },
    {
      invariantKind: "departure",
      statement: "An argument this command does not take is refused.",
    },
  ],
  name: "audit",
} as const satisfies Command
