import type { StoryTurnPlayed } from "akasha/story/world/stories/played/turns/story-turn-played.page-type.types.ts"

export const otherwhereXi00006 = {
  id: "01a0eabd-fd27-7e7b-b3c3-cfa25d9907bc",
  type: "page-type/story-turn-played",
  slug: "otherwhere-xi-00-006",
  ownLength: 284,
  unit: "unit/words",
  partOfCollections: ["story-played/otherwhere-xi"],
  position: 6,
  prose: "txt",
  characters: [
    "character-player/otherwhere-xi-nala",
    "world-character/otherwhere-xi-wenna-ashlar",
    "world-character/otherwhere-xi-tobin-ashlar",
  ],
  stepStatus: "step-status/recorders",
  action:
    "\"I'm sorry to have pulled your boy from his duties Ma'am. He mentioned that you knew the old stories, so I have come seeking your wisdom, for much truth is preserved only in old stories. What do you know of the Waystones? Are there tales of travelers who arrive at them not by any road?\"",
  beats: [
    "Nala says, \"I'm sorry to have pulled your boy from his duties, Ma'am.\"",
    '"He mentioned that you knew the old stories, so I have come seeking your wisdom."',
    '"For much truth is preserved only in old stories. What do you know of the Waystones?"',
    '"Are there tales of travelers who arrive at them not by any road?"',
    'The woman\'s eyes go to her son. "He pulled himself." Then: "Flock. Now."',
    "Tobin goes, back up the road at a jog, looking over his shoulder twice.",
    "The headcloth is still held out. The woman steps in and lays it over Nala's hair herself.",
    "She tugs it straight at the brow with two hard fingers, and steps back.",
    "The two girls have crept closer behind her, hens forgotten, staring at the red hair under the cloth.",
    '"There are tales," the woman says, flat. "My grandmother\'s."',
    '"A stray steps out of a waystone at dawn. No road dust on her feet."',
    "Her eyes drop to Nala's feet, grey with the road's dust now, and come back up.",
    '"They speak the tongue of wherever they land. Never learned it."',
    "\"One came out at a waystone near Imra, in my grandmother's grandmother's day. A man.\"",
    '"He stayed a year. Mended the mill. Walked off one dawn and wasn\'t seen again."',
    "\"Maradoc doesn't waste a stray, Gran used to say. He sets each one where there's work wants doing.\"",
    "Her eyes go, for a moment, to the lambing pen along the wall, loud with ewes.",
    '"The wayfarer priest comes through each spring. Soon. He\'d know more than me."',
    "She leans on the stick. \"Or it's a tale, and you're a runaway with a clever story.\"",
    '"Which are you?"',
  ],
  lore: ["lore/otherwhere-xi-wenna-ashlar", "place/otherwhere-xi-waystone-shrine"],
  reviewedBy: ["story-reviewer/continuity", "story-reviewer/style"],
  recordedBy: ["story-recorder/memory", "story-recorder/mechanics"],
  endsAt: "2026-09-28T07:31:00.000Z",
} as const satisfies StoryTurnPlayed
