import type { StoryTurnPlayed } from "akasha/story/world/stories/played/turns/story-turn-played.page-type.types.ts"

export const otherwhereXi00009 = {
  id: "01a0eb1a-a146-72b6-81e8-e911d58c6b77",
  type: "page-type/story-turn-played",
  slug: "otherwhere-xi-00-009",
  cover: "image/image-7206b29361de76d7",
  coverAfter: "Then she looks at your hands, holding the ewe's head. Small. Pale.",
  ownLength: 295,
  unit: "unit/words",
  partOfCollections: ["story-played/otherwhere-xi"],
  position: 9,
  prose: "txt",
  characters: ["character-player/otherwhere-xi-nala", "world-character/otherwhere-xi-wenna-ashlar"],
  stepStatus: "step-status/player",
  action: "I watch carefully, learn, and work as I can.",
  beats: [
    "Nala watches Wenna's hands, and does what she can.",
    '"Her head," Wenna says without looking up. "Kneel. Hold it in your lap. Talk to her."',
    "Nala kneels in the straw and takes the ewe's head. It is heavy, hot, and trembling.",
    "The ewe's eye rolls up at her, white-rimmed. Nala talks low, nonsense, and the trembling eases.",
    '"Tallow. The crock on the shelf inside the door. And water from the cistern. Go."',
    "Nala runs, the robe's hem catching at her feet; the crock is where Wenna said.",
    "She hauls a bucket from the cistern, water slopping cold down the red robe.",
    "Her mouth is dry; the water in the bucket smells of stone and snowmelt.",
    "Back in the pen, Wenna greases her hand and forearm to the elbow and goes in.",
    "Nala holds the head again. Wenna's jaw sets; her whole arm strains, and she grunts.",
    "Long minutes. The ewe heaves and cries. Wenna swears under her breath, and pulls her arm out.",
    "She sits back on her heels, breathing hard, and looks at her hand: big, cracked, bleeding a little.",
    "\"Leg's back. I can feel it. I can't get round it. My hand's too big for her.\"",
    'Pell has crept to the hurdles. "That\'s how the other two went, Mam."',
    '"I know what I lost." Wenna doesn\'t take her eyes off the ewe.',
    "Then she looks at Nala's hands, holding the ewe's head. Small. Pale. Narrow at the wrist.",
    '"Your hands," she says. "They\'re small enough."',
    '"Grease to the elbow. In slow, between her pushes. Find the leg, cup the hoof, bring it forward."',
    "\"I'll talk you through it. I'll hold her.\" She holds out the tallow crock.",
    "The ewe heaves again, and cries.",
  ],
  lore: [
    "lore/otherwhere-xi-nala",
    "lore/otherwhere-xi-wenna-ashlar",
    "place/otherwhere-xi-ashlar-farm",
  ],
  reviewedBy: ["story-reviewer/style", "story-reviewer/continuity"],
  recordedBy: ["story-recorder/memory", "story-recorder/picture", "story-recorder/mechanics"],
  endsAt: "2026-09-28T09:09:00.000Z",
} as const satisfies StoryTurnPlayed
