import type { View } from "akasha/page/view/view.page-type.types.ts"

export const storiesPlayed = {
  id: "01a0d444-18f3-7b60-b381-1a06a6081457",
  type: "page-type/view",
  slug: "stories-played",
  title: "Played",
  nav: "nav/stories",
  pageType: "page-type/story-played",
  viewPlace: 0,
  layout: "cards",
  viewSorts: [{ key: "title", descending: false }],
  visibleProperties: ["parts-length-in-words"],
  alwaysShowProperties: ["parts-length-in-words"],
  hiddenPropertiesOrder: [
    "action-draft",
    "author",
    "chapter-break",
    "collection-type",
    "completed-at",
    "completion",
    "coordinator-agent",
    "cover-reroll",
    "cover-reroll-refused",
    "description",
    "domain",
    "entries",
    "external-id",
    "following",
    "grade",
    "opens-at",
    "own-length",
    "own-length-in-words",
    "own-progress",
    "own-progress-in-words",
    "own-remaining",
    "own-remaining-in-words",
    "panels",
    "part-of-collections",
    "parts-progress-in-words",
    "parts-remaining-in-words",
    "phase-timings",
    "position",
    "prose",
    "published-at",
    "referenced-by",
    "slug",
    "status",
    "story-color",
    "tags",
    "total-length",
    "total-length-in-words",
    "total-progress",
    "total-progress-in-words",
    "total-remaining",
    "total-remaining-in-words",
    "turn-undo",
    "turn-undo-refused",
    "type",
    "unit",
    "unit-words",
    "world",
  ],
} as const satisfies View
