import type { TemperSet } from "akasha/temper/catalog/gear/temper-set/temper-set.page-type.types.ts"

export const molagKena = {
  id: "019e6484-6008-7ca5-9aab-b19eb4cf77f1",
  type: "page-type/temper-set",
  slug: "molag-kena",
  title: "Molag Kena",
  key: "molag-kena",
  esoSetId: 183,
  setWayshrines: [247, 247, 247],
  setVeteranEquipTypes: ["EQUIP_TYPE_HEAD"],
  setUndauntedChestId: 3,
  setTypeId: 8,
  setNameZh: "莫拉格·科娜",
  setNameRu: "Молаг Кена",
  setNameFr: "Molag Kena",
  setNameEs: "Molag Kena",
  setNameDe: "Molag Kena",
  setDropZones: [688, 181, 181],
  setDropMechanics: [6],
  setDropLocationNamesEn: ["Molag Kena"],
  setDropLocationNamesDe: ["Molag Kena"],
  setDlcId: 1,
  itemBrowserSources: ["688:-103"],
  itemBrowserPlaceKinds: [3],
  itemBrowserItemId: 68124,
  esoItemIds: [68107, 68113, 68119, 68125, 68131, 68137],
  esoArmorTypes: ["ARMORTYPE_HEAVY", "ARMORTYPE_LIGHT", "ARMORTYPE_MEDIUM"],
  esoEquipTypes: ["EQUIP_TYPE_HEAD", "EQUIP_TYPE_SHOULDERS"],
  category: "temper-set-category/monster",
  valid: ["monster"],
  bonuses: "jsonl",
  icons: "jsonl",
} as const satisfies TemperSet
