import type { TemperSet } from "akasha/temper/catalog/gear/temper-set/temper-set.page-type.types.ts"

export const markynRingOfMajesty = {
  id: "019e6484-6030-7be9-a8fb-89597d47ce9a",
  type: "page-type/temper-set",
  slug: "markyn-ring-of-majesty",
  title: "Markyn Ring of Majesty",
  key: "markyn-ring-of-majesty",
  esoSetId: 625,
  setWayshrines: [130, 491, 493],
  setTypeId: 12,
  setNameZh: "马尔肯恩权力之戒",
  setNameRu: "Кольцо величия Маркина",
  setNameFr: "L’Anneau de majesté de Markyn",
  setNameEs: "Anillo de majestad markyn",
  setNameDe: "Markyn-Ring der Erhabenheit",
  setDropZones: [347, 1286, 1283, 380, 935, 1282],
  setDropMechanics: [10, 27, 8, 27, 27, 23],
  setDropLocationNamesEn: ["", "Deadrats", "Den of the Unmaker", "Any mob", "Any mob"],
  setDropLocationNamesDe: ["", "Todesratten", "Bau des Entschaffers", "Alle Gegner", "Alle Gegner"],
  setDlcId: 24,
  itemBrowserSources: ["-5"],
  itemBrowserPlaceKinds: [6],
  itemBrowserItemId: 182208,
  esoItemIds: [182208],
  esoEquipTypes: ["EQUIP_TYPE_RING"],
  category: "temper-set-category/mythic",
  valid: ["ring"],
  bonuses: "jsonl",
  icons: "jsonl",
} as const satisfies TemperSet
