export interface LocationEntry {
  description: string
  type: string
  short: string
  complete: boolean
}

export const LOCDATA_TYPE_ALLLOOTTABLES = "All loot tables"
export const LOCDATA_SHORT_ALLLOOTTABLES = "All loot tables"
export const LOCDATA_LONG_ALLLOOTTABLES = "Anything and everything. Up to and including trials"
export const LOCDATA_TYPE_EXCAVATIONREWARD = "Excavation reward"
export const LOCDATA_SHORT_EXCAVATIONREWARD = "Excavation reward"
export const LOCDATA_LONG_EXCAVATIONREWARD = "Reward for excavating previous level treasure lead"
export const LOCDATA_TYPE_EXCAVATIONREWARD2 = "Treasure Maps"
export const LOCDATA_SHORT_EXCAVATIONREWARD2 = "Treasure Maps"
export const LOCDATA_LONG_EXCAVATIONREWARD2 = "Treasure Maps in The Reach and Western Skyrim"
export const LOCDATA_TYPE_COFFER = "Coffer"
export const LOCDATA_SHORT_COFFER = "Cyro gladiator coffers"
export const LOCDATA_LONG_COFFER = "Gladiators coffer Cyrodiil"
export const LOCDATA_TYPE_DAILY = "Daily"
export const LOCDATA_SHORT_DAILY = "Daily Reward Coffer"
export const LOCDATA_LONG_DAILY = "Daily Reward Coffer"
export const LOCDATA_TYPE_DELVE = "Delve"
export const LOCDATA_TYPE_FISHING = "Fishing"
export const LOCDATA_TYPE_FIXLOCATION = "Fix location"
export const LOCDATA_TYPE_GROUPDUNGEON = "Group dungeon"
export const LOCDATA_TYPE_MOB = "Mob"
export const LOCDATA_TYPE_NODE = "Node"
export const LOCDATA_TYPE_PUBLICDUNGEON = "Public dungeon"
export const LOCDATA_TYPE_SAFEBOX = "Safebox"
export const LOCDATA_SHORT_SAFEBOX = "Safebox"
export const LOCDATA_TYPE_STARTER = "Starter"
export const LOCDATA_SHORT_STARTER = "Built-in"
export const LOCDATA_LONG_STARTER = "Zone starting lead"
export const LOCDATA_TYPE_TREASURECHEST = "Treasure chest"
export const LOCDATA_SHORT_TREASURECHEST = "Treasure chest"
export const LOCDATA_LONG_TREASURECHEST = "Treasure chest"
export const LOCDATA_TYPE_TREASUREMAP = "Treasure map"
export const LOCDATA_SHORT_TREASUREMAP = "Treasure map"
export const LOCDATA_LONG_TREASUREMAP = "Treasure map chest"
export const LOCDATA_TYPE_ANTIQUEMAP = "Vendor"
export const LOCDATA_SHORT_ANTIQUEMAP = "Innkeeper, general merchant"
export const LOCDATA_LONG_ANTIQUEMAP = "Innkeeper, general merchant. Requiers Pathfinder"
export const LOCDATA_TYPE_WORLDBOSS = "World boss"
export const LOCDATA_SHORT_WORLDBOSSALL = "(WB) all"
export const LOCDATA_LONG_WORLDBOSSALL = "All world bosses"
export const LOCDATA_SHORT_WORLDBOSSDRAGON = "(WB) Dragons"
export const LOCDATA_LONG_WORLDBOSSDRAGON = "Drop from dragons"
export const LOCDATA_SHORT_HARROWSTORMS = "(WB) Harrowstorms"
export const LOCDATA_LONG_HARROWSTORMS = "Drop from harrowstorms"
export const LOCDATA_TYPE_FIX = "Fix Location"
export const LOCDATA_SHORT_FIX = "MapPins Addon"
export const LOCDATA_LONG_FIX = "Use Map Pins Addon by Hoft. Enable Antiquities Filter."
export const UNKNOWN = "Unknown"
export const ENDLESSARCHIVE = "Endless Archive"
