import type { PageType } from "akasha/page/type/page-type.page-type.types.ts"

export const carTrim = {
  id: "01a06827-645d-74f5-957f-25b077d85817",
  type: "page-type/page-type",
  slug: "car-trim",
  definition: "a specification of a model year on sale",
  extends: ["page-type/car"],
  parts: [
    "relation-property/car-year",
    "number-property/msrp",
    "boolean-property/android-auto-wireless",
    "boolean-property/carplay-wireless",
    "boolean-property/federal-tax-credit-eligible",
    "boolean-property/kill-switch-present",
    "boolean-property/runs-offline",
    "select-property/battery-chemistry",
    "select-property/charging-port",
    "select-property/drive-layout",
    "select-property/iihs-rating",
    "select-property/powertrain-type",
    "text-property/adas-optional",
    "text-property/adas-standard",
    "text-property/driver-assist-brand",
    "text-property/drm-notes",
    "text-property/infotainment",
    "text-property/kill-switch-notes",
    "text-property/known-issues",
    "text-property/rear-view-camera-notes",
    "text-property/recalls",
    "text-property/side-view-camera-notes",
    "text-property/state-incentives",
    "text-property/subscription-features",
    "text-property/tco-source",
    "text-property/warranty-basic",
    "text-property/warranty-battery",
    "text-property/warranty-powertrain",
    "number-property/battery-kwh-gross",
    "number-property/battery-kwh-usable",
    "number-property/cargo-behind-row1-cuft",
    "number-property/cargo-behind-row2-cuft",
    "number-property/curb-weight-lb",
    "number-property/dc-fast-charge-peak-kw",
    "number-property/dc-fast-charge10-to80-min",
    "number-property/destination-fee",
    "number-property/epa-range-electric-mi",
    "number-property/epa-range-total-mi",
    "number-property/federal-tax-credit-amount",
    "number-property/ground-clearance-in",
    "number-property/height-in",
    "number-property/horsepower",
    "number-property/l2-home-charge-hr",
    "number-property/length-in",
    "number-property/motor-count",
    "number-property/mpg-combined",
    "number-property/mpge-combined",
    "number-property/width-in",
    "number-property/nhtsa-overall-stars",
    "number-property/payload-capacity-lb",
    "number-property/seating-capacity",
    "number-property/tco-annual-miles",
    "number-property/tco-depreciation",
    "number-property/tco-financing",
    "number-property/tco-fuel",
    "number-property/tco-insurance",
    "number-property/tco-maintenance",
    "number-property/tco-repairs",
    "number-property/tco-taxes-fees",
    "number-property/tco-years",
    "number-property/top-speed-mph",
    "number-property/torque-lbft",
    "number-property/towing-capacity-lb",
    "number-property/transaction-price",
    "number-property/wheelbase-in",
    "number-property/zero-to-sixty-sec",
  ],
  properties: [{ pageProperty: "relation-property/car-year", required: true, many: false }],
  decisions: [
    {
      decisionKind: "decision-kind/departure",
      statement: "A trim names the year above that trim and is the last level of the catalogue.",
    },
    {
      decisionKind: "decision-kind/departure",
      statement: "A trim is a row in its make's file rather than a page filed on its own.",
    },
  ],
  types: "ts",
  schema: "jsonl",
} as const satisfies PageType
