import type { Game } from "../game.page-type.ts"

export const theTower = {
  id: "01a0673f-a3d7-7000-afc1-88181be588cb",
  pageTypeSlug: "game",
  slug: "the-tower",
  title: "The Tower",
  unitSlug: "words",
  externalId: "the-tower",
  gameEngine: "awen",
  coordinatorAgent: "awen-gm--the-tower",
  controlledEntityKind: "single",
  mechanicsWeight: "heavy",
  resolution: "formula",
  genre: ["litrpg"],
  displayConfig: "json",
  gmContext: "json",
  rulebook: "json",
  resolutionMechanism: "json",
  turns: "jsonl",
  entities: "jsonl",
  states: "jsonl",
  rolls: "jsonl",
  characters: "jsonl",
  towerFloors: "jsonl",
  towerSessions: "jsonl",
} as const satisfies Game
