import type { SetTemplate } from "@akasha/temper-equipment/set-template"

export const SETS_DATA_036: readonly SetTemplate[] = [
  {
    id: "giant-spider",
    name: "Giant Spider",
    esoSetId: 264,
    subcategoryId: "other",
    valid: ["head:*"],
    bonuses: [
      {
        count: 1,
        status: "supported",
        effects: [
          { metricId: "healing-taken-base", effectType: "fractional-change", effectValue: 0.04 },
        ],
        description: "Adds 4% Healing Taken",
      },
      {
        count: 2,
        status: "unsupported",
        effects: [],
        description:
          "When you Block an enemy that is between 8 and 22 meters from you, you spin strands of spider silk to pull the enemy to you and taunt them for 15 seconds if they are not already taunted. This effect can occur once every 1 second.",
      },
    ],
    icons: {
      "head:heavy": "/esoui/art/icons/gear_undauntedspider_head_a.dds",
      "head:light": "/esoui/art/icons/gear_undauntedspider_head_a.dds",
      "head:medium": "/esoui/art/icons/gear_undauntedspider_head_a.dds",
    },
  },
  {
    id: "glacial-guardian",
    name: "Glacial Guardian",
    esoSetId: 621,
    subcategoryId: "dungeon",
    valid: ["*:heavy"],
    bonuses: [
      {
        count: 2,
        status: "supported",
        effects: [{ metricId: "resistance", effectType: "integer", effectValue: 743 }],
        description: "Adds 1487 Armor",
      },
      {
        count: 3,
        status: "supported",
        effects: [{ metricId: "stamina-maximum", effectType: "integer", effectValue: 1096 }],
        description: "Adds 1096 Maximum Stamina",
      },
      {
        count: 4,
        status: "supported",
        effects: [{ metricId: "health-recovery", effectType: "integer", effectValue: 129 }],
        description: "Adds 129 Health Recovery",
      },
      {
        count: 5,
        status: "unsupported",
        effects: [],
        description:
          "When you Block, tether to the enemy if they are within 8 meters of you for 8 seconds. While tethered, you deal 261 Frost damage every second to enemies touching the tether and cause them to have a 200% increased Status Effect Chance. The tether breaks if the target moves more than 12 meters away. This effect can occur once every 12 seconds and the damage scales off your Max Health.",
      },
    ],
    icons: {
      "axe": "/esoui/art/icons/gear_scribestruthwpn_1haxe_a.dds",
      "battleaxe": "/esoui/art/icons/gear_scribestruthwpn_2haxe_a.dds",
      "bow": "/esoui/art/icons/gear_scribestruthwpn_bow_a.dds",
      "chest:*": "/esoui/art/icons/gear_scribestruth_hvy_chest_a.dds",
      "dagger": "/esoui/art/icons/gear_scribestruthwpn_dagger_a.dds",
      "feet:*": "/esoui/art/icons/gear_scribestruth_hvy_feet_a.dds",
      "greatsword": "/esoui/art/icons/gear_scribestruthwpn_2hsword_a.dds",
      "hands:*": "/esoui/art/icons/gear_scribestruth_hvy_hands_a.dds",
      "head:*": "/esoui/art/icons/gear_scribestruth_hvy_head_a.dds",
      "ice-staff": "/esoui/art/icons/gear_scribestruthwpn_staff_a.dds",
      "inferno-staff": "/esoui/art/icons/gear_scribestruthwpn_staff_a.dds",
      "legs:*": "/esoui/art/icons/gear_scribestruth_hvy_legs_a.dds",
      "lightning-staff": "/esoui/art/icons/gear_scribestruthwpn_staff_a.dds",
      "mace": "/esoui/art/icons/gear_scribestruthwpn_1hhammer_a.dds",
      "maul": "/esoui/art/icons/gear_scribestruthwpn_2hhammer_a.dds",
      "necklace": "/esoui/art/icons/gear_breton_neck_a.dds",
      "restoration-staff": "/esoui/art/icons/gear_scribestruthwpn_staff_a.dds",
      "ring": "/esoui/art/icons/gear_breton_ring_a.dds",
      "shield": "/esoui/art/icons/gear_scribestruthwpn_shield_a.dds",
      "shoulders:*": "/esoui/art/icons/gear_scribestruth_hvy_shoulders_a.dds",
      "sword": "/esoui/art/icons/gear_scribestruthwpn_1hsword_a.dds",
      "waist:*": "/esoui/art/icons/gear_scribestruth_hvy_waist_a.dds",
    },
  },
  {
    id: "glorgoloch-the-destroyer",
    name: "Glorgoloch the Destroyer",
    esoSetId: 600,
    subcategoryId: "monster",
    valid: ["monster"],
    bonuses: [
      {
        count: 1,
        status: "supported",
        effects: [{ metricId: "health-maximum", effectType: "integer", effectValue: 1206 }],
        description: "Adds 1206 Maximum Health",
      },
      {
        count: 2,
        status: "unsupported",
        effects: [],
        description:
          "While in combat, each second you stand still grants you a stack of Flesh Fortress, up to 10 stacks. Each stack increases your Armor by 380 and your Critical Resistance by 38. Each second you move removes a stack of Flesh Fortress. Exiting combat removes all stacks of Flesh Fortress.\n\nUsing charge and teleport abilities do not remove stacks of Flesh Fortress.",
      },
    ],
    icons: {
      "head:heavy": "/esoui/art/icons/gear_undfleshcolossus_head_a.dds",
      "head:light": "/esoui/art/icons/gear_undfleshcolossus_head_a.dds",
      "head:medium": "/esoui/art/icons/gear_undfleshcolossus_head_a.dds",
      "shoulders:heavy": "/esoui/art/icons/gear_undfleshcolossus_shoulders_a.dds",
      "shoulders:light": "/esoui/art/icons/gear_undfleshcolossus_shoulders_a.dds",
      "shoulders:medium": "/esoui/art/icons/gear_undfleshcolossus_shoulders_a.dds",
    },
  },
  {
    id: "glorious-defender",
    name: "Glorious Defender",
    esoSetId: 213,
    subcategoryId: "arena",
    valid: ["*:heavy"],
    bonuses: [
      {
        count: 2,
        status: "supported",
        effects: [{ metricId: "health-maximum", effectType: "integer", effectValue: 1206 }],
        description: "Adds 1206 Maximum Health",
      },
      {
        count: 3,
        status: "supported",
        effects: [{ metricId: "health-maximum", effectType: "integer", effectValue: 1206 }],
        description: "Adds 1206 Maximum Health",
      },
      {
        count: 4,
        status: "supported",
        effects: [{ metricId: "power", effectType: "integer", effectValue: 129 }],
        description: "Adds 129 Weapon and Spell Damage",
      },
      {
        count: 5,
        status: "unsupported",
        effects: [],
        description:
          "When you Bash an enemy, you gain Glorious Defense for 10 seconds, allowing you to dodge the next attack made against you and all others afterwards for 1 second. This effect can occur once every 13 seconds.",
      },
    ],
    icons: {
      "axe": "/esoui/art/icons/gear_trinimac_1haxe_a.dds",
      "battleaxe": "/esoui/art/icons/gear_trinimac_2haxe_a.dds",
      "bow": "/esoui/art/icons/gear_trinimac_bow_a.dds",
      "chest:*": "/esoui/art/icons/gear_trinimac_heavy_chest_a.dds",
      "dagger": "/esoui/art/icons/gear_trinimac_dagger_a.dds",
      "feet:*": "/esoui/art/icons/gear_trinimac_heavy_feet_a.dds",
      "greatsword": "/esoui/art/icons/gear_trinimac_2hsword_a.dds",
      "hands:*": "/esoui/art/icons/gear_trinimac_heavy_hands_a.dds",
      "head:*": "/esoui/art/icons/gear_trinimac_heavy_head_a.dds",
      "ice-staff": "/esoui/art/icons/gear_trinimac_staff_a.dds",
      "inferno-staff": "/esoui/art/icons/gear_trinimac_staff_a.dds",
      "legs:*": "/esoui/art/icons/gear_trinimac_heavy_legs_a.dds",
      "lightning-staff": "/esoui/art/icons/gear_trinimac_staff_a.dds",
      "mace": "/esoui/art/icons/gear_trinimac_1hhammer_a.dds",
      "maul": "/esoui/art/icons/gear_trinimac_2hhammer_a.dds",
      "necklace": "/esoui/art/icons/gear_breton_neck_a.dds",
      "restoration-staff": "/esoui/art/icons/gear_trinimac_staff_a.dds",
      "ring": "/esoui/art/icons/gear_breton_ring_a.dds",
      "shield": "/esoui/art/icons/gear_trinimac_shield_a.dds",
      "shoulders:*": "/esoui/art/icons/gear_trinimac_heavy_shoulders_a.dds",
      "sword": "/esoui/art/icons/gear_trinimac_1hsword_a.dds",
      "waist:*": "/esoui/art/icons/gear_trinimac_heavy_waist_a.dds",
    },
  },
  {
    id: "gossamer",
    name: "Gossamer",
    esoSetId: 261,
    subcategoryId: "dungeon",
    valid: ["*:light"],
    bonuses: [
      {
        count: 2,
        status: "supported",
        effects: [{ metricId: "magicka-recovery", effectType: "integer", effectValue: 129 }],
        description: "Adds 129 Magicka Recovery",
      },
      {
        count: 3,
        status: "supported",
        effects: [{ metricId: "magicka-maximum", effectType: "integer", effectValue: 1096 }],
        description: "Adds 1096 Maximum Magicka",
      },
      {
        count: 4,
        status: "supported",
        effects: [{ metricId: "magicka-maximum", effectType: "integer", effectValue: 1096 }],
        description: "Adds 1096 Maximum Magicka",
      },
      {
        count: 5,
        status: "unsupported",
        effects: [],
        description:
          "When you heal yourself or an ally, you grant them Major Evasion for 4 seconds, reducing damage from area attacks by 20%.",
      },
    ],
    icons: {},
  },
  {
    id: "grace-of-gloom",
    name: "Grace of Gloom",
    esoSetId: 382,
    subcategoryId: "overland",
    valid: ["*:heavy"],
    bonuses: [
      {
        count: 2,
        status: "supported",
        effects: [{ metricId: "health-maximum", effectType: "integer", effectValue: 1206 }],
        description: "Adds 1206 Maximum Health",
      },
      {
        count: 3,
        status: "supported",
        effects: [
          { metricId: "healing-taken-base", effectType: "fractional-change", effectValue: 0.04 },
        ],
        description: "Adds 4% Healing Taken",
      },
      {
        count: 4,
        status: "supported",
        effects: [{ metricId: "health-maximum", effectType: "integer", effectValue: 1206 }],
        description: "Adds 1206 Maximum Health",
      },
      {
        count: 5,
        status: "unsupported",
        effects: [],
        description:
          "When you take damage, you become a living shadow for 10 seconds, causing you to heal for 962 every 2 seconds and gaining Major Evasion, reducing damage from area attacks by 20%. This effect can occur every 20 seconds and scales off your Max Health.",
      },
    ],
    icons: {
      "axe": "/esoui/art/icons/gear_nocturnal_1haxe_a.dds",
      "battleaxe": "/esoui/art/icons/gear_nocturnal_2haxe_a.dds",
      "bow": "/esoui/art/icons/gear_nocturnal_bow_a.dds",
      "chest:*": "/esoui/art/icons/gear_aldmeri_heavy_chest_a.dds",
      "dagger": "/esoui/art/icons/gear_nocturnal_dagger_a.dds",
      "feet:*": "/esoui/art/icons/gear_aldmeri_heavy_feet_a.dds",
      "greatsword": "/esoui/art/icons/gear_ancient_elf_2hsword_b.dds",
      "hands:*": "/esoui/art/icons/gear_sapiarch_heavy_hands_a.dds",
      "head:*": "/esoui/art/icons/gear_nocturnal_heavy_head_a.dds",
      "ice-staff": "/esoui/art/icons/gear_nocturnal_satff_a.dds",
      "inferno-staff": "/esoui/art/icons/gear_nocturnal_satff_a.dds",
      "legs:*": "/esoui/art/icons/gear_daedric_heavy_legs_a.dds",
      "lightning-staff": "/esoui/art/icons/gear_nocturnal_satff_a.dds",
      "mace": "/esoui/art/icons/gear_nord_1hhammer_d.dds",
      "maul": "/esoui/art/icons/gear_khajiit_2hhammer_d.dds",
      "necklace": "/esoui/art/icons/gear_breton_neck_a.dds",
      "restoration-staff": "/esoui/art/icons/gear_nocturnal_satff_a.dds",
      "ring": "/esoui/art/icons/gear_breton_ring_a.dds",
      "shield": "/esoui/art/icons/gear_daedric_shield_c.dds",
      "shoulders:*": "/esoui/art/icons/gear_daedric_heavy_shoulders_a.dds",
      "sword": "/esoui/art/icons/gear_nocturnal_1hsword_a.dds",
      "waist:*": "/esoui/art/icons/gear_redguard_heavy_waist_d.dds",
    },
  },
  {
    id: "grace-of-the-ancients",
    name: "Grace of the Ancients",
    esoSetId: 126,
    subcategoryId: "pvp",
    valid: ["weapon:*", "jewelry:*"],
    bonuses: [
      {
        count: 2,
        status: "supported",
        effects: [{ metricId: "magicka-maximum", effectType: "integer", effectValue: 1096 }],
        description: "Adds 1096 Maximum Magicka",
      },
      {
        count: 3,
        status: "supported",
        effects: [{ metricId: "magicka-maximum", effectType: "integer", effectValue: 2406 }],
        description: "Adds 2406 Maximum Magicka",
      },
    ],
    icons: {
      "axe": "/esoui/art/icons/gear_breton_1haxe_d.dds",
      "battleaxe": "/esoui/art/icons/gear_breton_2haxe_d.dds",
      "bow": "/esoui/art/icons/gear_breton_bow_d.dds",
      "dagger": "/esoui/art/icons/gear_breton_dagger_d.dds",
      "greatsword": "/esoui/art/icons/gear_breton_2hsword_d.dds",
      "ice-staff": "/esoui/art/icons/gear_breton_staff_d.dds",
      "inferno-staff": "/esoui/art/icons/gear_breton_staff_d.dds",
      "lightning-staff": "/esoui/art/icons/gear_breton_staff_d.dds",
      "mace": "/esoui/art/icons/gear_breton_1hhammer_d.dds",
      "maul": "/esoui/art/icons/gear_breton_2hhammer_d.dds",
      "necklace": "/esoui/art/icons/gear_breton_neck_a.dds",
      "restoration-staff": "/esoui/art/icons/gear_akaviri_staff_b.dds",
      "ring": "/esoui/art/icons/gear_breton_ring_a.dds",
      "shield": "/esoui/art/icons/gear_breton_shield_d.dds",
      "sword": "/esoui/art/icons/gear_breton_1hsword_d.dds",
    },
  },
  {
    id: "grand-rejuvenation",
    name: "Grand Rejuvenation",
    esoSetId: 318,
    subcategoryId: "arena",
    valid: ["restoration-staff"],
    bonuses: [
      {
        count: 2,
        status: "unsupported",
        effects: [],
        description:
          "The initial heal of Grand Healing invigorates you and group members affected for 6 seconds, restoring 224 Magicka and Stamina every 2 seconds.",
      },
    ],
    icons: { "restoration-staff": "/esoui/art/icons/gear_breton_staff_e.dds" },
  },
]
