apiVersion: v1
kind: Secret
metadata:
    name: pgbouncer-auth
    namespace: pgbouncer
    labels:
        app.kubernetes.io/component: database-proxy
        app.kubernetes.io/instance: infra
        app.kubernetes.io/name: pgbouncer
        app.kubernetes.io/part-of: infra
type: Opaque
stringData:
    userlist.txt: ENC[AES256_GCM,data:SsaxSUGHA2KPK5ranz+8X72rff13NeQwK9zGJP8kpHbY0bkhDJZJn23V+Z8tC4Bhkr38AlW6s62ppNxv37Yp5C4uI9YbgAseR5stHgmVgLEEaC06J0M1wzAwSdjBwbogNr0m+d6PhUEWWhZHCNjjTAlbKJbambmHcW0uRpntJERZKX6dRRrsNuxlXR2RRF2wP4KOCIBTM+5yZ/uZk7+04WQ5RNKnvj9+tCa0sW8+ElqnVk/KEhion4KHgw8z/ev040LW/ns+g2+kAYoX+n9rMA7fmVZJflCP3jbcC+kdhO3lTLAiCPLDrjpLxkkANDILOPqG4diEFeN9p37AJtdo4mxNoz5eOAreEFQ4+WMLHv86dMF4hM8TUjV/z5cZWJIlA6uQzhwbNwQhU7eWKZ46iPdN0L6GhUtkzdKVzh/Wej0cA+scKp5+QvVW7AC+rimnVmYikOHS1Y0T052hzOW1dxSPXU22Wq/VILl3yxRoGi68ITBqJgQpDRAv61U0/2HgriBViSyiT6TP8dGXKitTihlEbnvV1WwhyLOaLiTxNFapwYrlgSvj64VSmUvKxWf1POHo1i1lH6180P7UtR8VHfDcD9VJjaI=,iv:56Tr6U783YQ9BMn/QFZm6OpUkW8vEFjqAfVjVYU+cCo=,tag:042uoOln52NOPsKqD6pLkg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRN2NRNWR2Q1BFajRYajBn
            SEV0aFA1VmpDWUttZDU0dnlOYnFDWXVSMVVNCi9ham1sZmFhWjlOSE41YnRTT1BL
            SVBETXJ0emVwU2VmV0JGdS9uWDFTNEUKLS0tIDBvOWJUMTZHY1hFMXByck8wVUJv
            K1Zia0o0ZkRvMXBCd2lVVG14MlpOZXcKEDAFNkNbsrlGjPJ/GOZyfaJzyyo6QDwE
            an2M5T/N+hEYRd8vqmMsEURN0xfLNR9ul9k69nRDMYuHD0/VEdsUag==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-20T00:37:08Z"
    mac: ENC[AES256_GCM,data:8NtMUbt+vacyfVLFGH6SkSha4zsbHz/vLOQ1I7mGlB1yFYrYb/HlRGx5bU8PoDWp2VxIcea7Z7WRdMCvgdgYYlRvFAAvz5XTUd1e88I/0e/G2SSMSvLJfk6kfxk4i6gMdSTnjr780AqPv3yGNU94+oyX7ke1gKJEXtNX3rL4Zak=,iv:87731Z7WQds03YZ5sBlU0LIofAkKAKEL/7oh+o4j0kI=,tag:tPpAiosgVInFavDMt78ljQ==,type:str]
    version: 3.9.4
