import type { Domain } from "akasha/domains/domain.page-type.types.ts"

export const seat = {
  id: "01a09c2b-df31-772b-9dd5-80d1fbe69f2d",
  type: "domain",
  slug: "seat",
  definition: "a seat and what keeps an agent working in it",
  parts: [
    "domain/oauth-proxy",
    "domain/pty",
    "domain/seat-capability",
    "domain/seat-credential",
    "domain/seat-declaration",
    "domain/seat-fleet",
    "domain/seat-launching",
    "domain/seat-name",
    "domain/seat-name-claiming",
    "domain/seat-observation",
    "domain/seat-page",
    "domain/seat-reviving",
    "domain/seat-session",
    "domain/seat-stopping",
    "domain/seat-supervisors",
    "domain/seat-usage",
    "domain/self-healing",
    "module/seat-action",
    "module/seat-control",
    "module/window-duration",
    "page-type/log-source",
    "page-type/seat",
    "page-type/seat-conditions",
    "page-type/seat-log-day",
    "page-type/seat-turn-state",
    "service-workstation/maintain-seat-pending",
    "service-workstation/memory-reaper",
    "service-workstation/recipient-resolver",
    "service-workstation/sweep-log-days",
    "service-workstation/sweep-supervisor-logs",
  ],
} as const satisfies Domain
