import { CUSTOM_PINS_CHAPTERS } from "../map-pins-chapters/map-pins-chapters.module.code.ts"
import { TEXTURE_ROOT } from "../map-pins-names/map-pins-names.module.code.ts"
import type { CustomPinTable } from "../map-pins-pin-types/map-pins-pin-types.module.code.ts"

export const CUSTOM_PINS: CustomPinTable = {
  [1]: {
    name: "pinType_Delve_bosses",
    done: false,
    id: {},
    pin: [],
    maxDistance: 0.05,
    level: 30,
    texture: "/esoui/art/icons/poi/poi_groupboss_incomplete.dds",
    k: 1.25,
  },
  [2]: {
    name: "pinType_Delve_bosses_done",
    done: true,
    id: {},
    pin: [],
    maxDistance: 0.05,
    level: 30,
    texture: "/esoui/art/icons/poi/poi_groupboss_complete.dds",
    k: 1.25,
  },
  [3]: {
    name: "pinType_Skyshards",
    done: false,
    id: {},
    pin: [],
    maxDistance: 0.05,
    level: 100,
    texture: `/${TEXTURE_ROOT}/Skyshard_1.dds`,
    k: 1.4,
  },
  [5]: {
    name: "pinType_Lore_books",
    done: false,
    id: {},
    pin: [],
    maxDistance: 0.05,
    level: 100,
    texture: `/${TEXTURE_ROOT}/Lorebook_1.dds`,
    k: 1,
    tint: ZO_ColorDef.New(0.6, 0.6, 1, 0.8),
  },
  [7]: {
    name: "pinType_Treasure_Chests",
    done: false,
    id: {},
    pin: [],
    maxDistance: 0.05,
    level: 100,
    texture: `/${TEXTURE_ROOT}/Chest_1.dds`,
    k: 1.1,
    tint: ZO_ColorDef.New(1, 1, 1, 0.8),
  },
  [8]: {
    name: "pinType_Unknown_POI",
    done: false,
    id: {},
    pin: [],
    maxDistance: 0.05,
    level: 10,
    texture: (self) => self.m_PinTag.texture,
    def_texture: "/esoui/art/icons/poi/poi_areaofinterest_incomplete.dds",
    size: 40,
    tint: ZO_ColorDef.New(0.7, 0.7, 0.7, 0.6),
  },
  [9]: {
    section: true,
    name: "Undaunted",
    id: {},
    pin: [],
    texture: "/esoui/art/icons/crafting_beer_003.dds",
    [40]: {
      name: "pinType_This_One's_On_Me",
      done: false,
      ach: 704,
      maxDistance: 0.05,
      level: 101,
      texture: "/esoui/art/icons/crafting_beer_003.dds",
      k: 1,
    },
    [41]: {
      name: "pinType_Undaunted_Rescuer",
      done: false,
      ach: 1082,
      maxDistance: 0.05,
      level: 101,
      texture: "/esoui/art/miscellaneous/help_icon.dds",
      k: 1.25,
      def_texture: "/esoui/art/icons/ability_warrior_007.dds",
    },
  },
  [10]: {
    section: true,
    name: "World_achievements",
    id: {},
    pin: [],
    texture: "/esoui/art/progression/progression_indexicon_world_up.dds",
    [42]: {
      name: "pinType_I_like_M'aiq",
      done: false,
      ach: 872,
      maxDistance: 0.05,
      level: 101,
      texture: "/esoui/art/icons/achievement_066.dds",
      k: 1,
    },
    [43]: {
      name: "pinType_Lightbringer",
      done: false,
      ach: 873,
      maxDistance: 0.05,
      level: 101,
      texture: "/esoui/art/miscellaneous/help_icon.dds",
      k: 1.25,
    },
    [44]: {
      name: "pinType_Peacemaker",
      done: false,
      ach: 716,
      maxDistance: 0.05,
      level: 101,
      texture: "/esoui/art/icons/ability_healer_017.dds",
      k: 1,
    },
  },
  [11]: {
    section: true,
    name: "Orsinium",
    id: {},
    pin: [],
    texture: "/esoui/art/treeicons/tutorial_idexicon_wrothgar_up.dds",
    [45]: {
      name: "pinType_One_Last_Brawl",
      done: false,
      ach: 1247,
      maxDistance: 0.05,
      level: 101,
      texture: "/esoui/art/icons/achievement_wrothgar_010.dds",
      k: 1,
    },
    [46]: {
      name: "pinType_Orsinium_world_event",
      done: false,
      maxDistance: 0.05,
      level: 101,
      texture: "/esoui/art/miscellaneous/help_icon.dds",
      k: 1.25,
      def_texture: "/esoui/art/icons/achievement_wrothgar_024.dds",
    },
    [47]: {
      name: "pinType_Wrothgar_Relic_Hunter",
      done: false,
      ach: 1250,
      maxDistance: 0.05,
      level: 101,
      texture: "/esoui/art/icons/achievement_wrothgar_008.dds",
      k: 1,
    },
  },
  [12]: {
    section: true,
    name: "Thieves_guild",
    id: {},
    pin: [],
    texture: "/esoui/art/treeicons/tutorial_idexicon_thievesguild_up.dds",
    [48]: {
      name: "pinType_A_Cutpurse_Above",
      done: false,
      ach: 1383,
      maxDistance: 0.05,
      level: 101,
      texture: "/esoui/art/icons/achievement_thievesguild_044.dds",
      k: 1,
    },
    [49]: {
      name: "pinType_Breaking_And_Entering",
      done: false,
      ach: 1349,
      maxDistance: 0.05,
      level: 101,
      texture: "/esoui/art/icons/perks_theives_guild_004.dds",
      k: 1,
    },
  },
  [13]: {
    section: true,
    name: "Morrowind",
    id: {},
    pin: [],
    texture: "/esoui/art/treeicons/tutorial_idexicon_morrowind_up.dds",
    [50]: {
      name: "pinType_Vivec_Lessons",
      done: false,
      ach: 1824,
      maxDistance: 0.05,
      level: 100,
      texture: `/${TEXTURE_ROOT}/Scroll_1.dds`,
      k: 1,
      tint: ZO_ColorDef.New(0.8, 0.8, 0.8, 0.8),
    },
    [51]: {
      name: "pinType_Ancestral_Tombs",
      done: false,
      ach: 1712,
      maxDistance: 0.05,
      level: 30,
      texture: "/esoui/art/icons/poi/poi_crypt_incomplete.dds",
      k: 1,
    },
    [52]: {
      name: "pinType_Pilgrim's_Path",
      done: false,
      ach: 1827,
      maxDistance: 0.05,
      level: 101,
      texture: "/esoui/art/miscellaneous/help_icon.dds",
      k: 1.25,
      def_texture: "/esoui/art/icons/achievement_vvardenfel_032.dds",
    },
  },
  [14]: {
    section: true,
    name: "Summerset",
    id: {},
    pin: [],
    texture: "/esoui/art/treeicons/tutorial_idexicon_summerset_up.dds",
    [53]: {
      name: "pinType_Summerset_Relics",
      done: false,
      ach: 2099,
      maxDistance: 0.05,
      level: 101,
      texture: "/esoui/art/icons/quest_strosmkai_open_treasure_chest.dds",
      k: 1,
    },
    [54]: {
      name: "pinType_Message_in_Bottle",
      done: false,
      ach: 2211,
      maxDistance: 0.05,
      level: 100,
      texture: "/esoui/art/icons/crafting_stoneware_bottle_003.dds",
      k: 1,
    },
    [55]: {
      name: "pinType_Summerset_world_event",
      done: false,
      ach: 2171,
      maxDistance: 0.05,
      level: 101,
      texture: "/esoui/art/miscellaneous/help_icon.dds",
      k: 1.25,
      def_texture: "/esoui/art/icons/achievement_su_rds_01.dds",
    },
  },
  [15]: {
    name: "pinType_Time_Rifts",
    done: false,
    id: {},
    pin: [],
    maxDistance: 0.05,
    level: 101,
    texture: `/${TEXTURE_ROOT}/Treasure_1-2.dds`,
    k: 1.8,
  },
  [16]: {
    name: "pinType_Shrines",
    done: false,
    id: {},
    pin: [],
    maxDistance: 0.05,
    level: 101,
    texture: "/esoui/art/icons/poi/poi_daedricruin_incomplete.dds",
    k: 1.25,
  },
  [17]: {
    name: "pinType_Fishing_Nodes",
    done: false,
    id: {},
    pin: [],
    maxDistance: 0.05,
    level: 101,
    texture: "/esoui/art/icons/achievements_indexicon_fishing_up.dds",
    k: 1.25,
  },
  [18]: {
    section: true,
    name: "pinType_Clockwork_City",
    id: {},
    pin: [],
    texture: "/esoui/art/treeicons/tutorial_idexicon_cwc_up.dds",
    [56]: {
      name: "pinType_Precursor_Maker",
      done: false,
      ach: 1958,
      maxDistance: 0.05,
      level: 101,
      texture: "/esoui/art/menubar/gamepad/gp_playermenu_icon_settings.dds",
      k: 1,
      def_texture: "/esoui/art/icons/achievement_update16_001.dds",
    },
  },
  [19]: {
    section: true,
    name: "pinType_Murkmire",
    id: {},
    pin: [],
    texture: "/esoui/art/treeicons/tutorial_idexicon_murkmire_up.dds",
    [57]: {
      name: "pinType_Chronic_Chronogler",
      done: false,
      ach: 2320,
      maxDistance: 0.05,
      level: 101,
      texture: "/esoui/art/inventory/gamepad/gp_inventory_icon_craftbag_stylematerial.dds",
      k: 1,
      def_texture: "/esoui/art/icons/achievement_murkmire_museum.dds",
    },
    [58]: {
      name: "pinType_Poems_of_Nothing",
      done: false,
      ach: 2341,
      maxDistance: 0.05,
      level: 101,
      texture: `/${TEXTURE_ROOT}/Scroll_1.dds`,
      k: 1,
    },
    [59]: {
      name: "pinType_Achievement_quests",
      done: false,
      ach: 2355,
      maxDistance: 0.05,
      level: 101,
      texture: "/esoui/art/tutorial/gamepad/gp_icon_new.dds",
      k: 1,
    },
    [60]: {
      name: "pinType_Surreptitiously_Shadowed",
      done: false,
      ach: 2330,
      maxDistance: 0.05,
      level: 111,
      texture: "/esoui/art/miscellaneous/help_icon.dds",
      k: 1,
      def_texture: "/esoui/art/icons/achievement_murkmire_shadowscale_wisdom.dds",
    },
    [61]: {
      name: "pinType_Swamp_Rescuer",
      done: false,
      ach: 2358,
      maxDistance: 0.05,
      level: 101,
      texture: "/esoui/art/death/death_soulreservoir_icon.dds",
      k: 1,
      def_texture: "/esoui/art/icons/achievement_murkmire_rescue_villagers.dds",
    },
    [62]: {
      name: "pinType_Vine-Tongue_Traveler",
      done: false,
      ach: 2357,
      maxDistance: 0.05,
      level: 101,
      texture: `/${TEXTURE_ROOT}/Lorebook_1-2.dds`,
      k: 1,
      def_texture: "/esoui/art/icons/mh_hedgeguardian_strang.dds",
    },
  },
  ...CUSTOM_PINS_CHAPTERS,
}
