[AC]
AutoSuspendAction=0
DimDisplayWhenIdle=false
TurnOffDisplayWhenIdle=false

[Battery]
AutoSuspendAction=0
DimDisplayWhenIdle=false
TurnOffDisplayWhenIdle=false

[LowBattery]
AutoSuspendAction=0
DimDisplayWhenIdle=false
TurnOffDisplayWhenIdle=false
