[AC]
autoSuspendAction=0
dimDisplayWhenIdle=false
turnOffDisplayWhenIdle=false

[Battery]
autoSuspendAction=0
dimDisplayWhenIdle=false
turnOffDisplayWhenIdle=false

[LowBattery]
autoSuspendAction=0
dimDisplayWhenIdle=false
turnOffDisplayWhenIdle=false
