[AC][Display]
DimDisplayWhenIdle=false
TurnOffDisplayIdleTimeoutSec=-1
TurnOffDisplayIdleTimeoutWhenLockedSec=-1

[AC][SuspendAndShutdown]
AutoSuspendAction=0

[Battery][Display]
DimDisplayWhenIdle=false
TurnOffDisplayIdleTimeoutSec=-1
TurnOffDisplayIdleTimeoutWhenLockedSec=-1

[Battery][SuspendAndShutdown]
AutoSuspendAction=0

[LowBattery][Display]
DimDisplayWhenIdle=false
TurnOffDisplayIdleTimeoutSec=-1
TurnOffDisplayIdleTimeoutWhenLockedSec=-1

[LowBattery][SuspendAndShutdown]
AutoSuspendAction=0
