import type { RouterApp } from "akasha/code/router-app/router-app.page-type.types.ts"

export const alanWeb = {
  id: "01a05bb1-0c04-751f-8f51-baadbd134cf6",
  type: "page-type/router-app",
  slug: "alan-web",
  definition: "the routes Alan's site serves to a browser",
  tunnelRoutes: [
    {
      name: "alanwalton",
      hostname: "alanwalton.com",
      service: "http://web.alanwalton.svc.cluster.local:3000",
    },
    {
      name: "alanwalton-webhook",
      hostname: "webhook.alanwalton.com",
      service: "http://web.alanwalton.svc.cluster.local:3000",
    },
    {
      name: "alanwalton-sms",
      hostname: "sms.alanwalton.com",
      service: "http://web.alanwalton.svc.cluster.local:3000",
    },
    {
      name: "alanwalton-idle-legacy",
      hostname: "idle.alanwalton.com",
      service: "http://web.alanwalton.svc.cluster.local:3000",
    },
  ],
  rootRoute: "tsx",
  routeTable: "ts",
  serverEntry: "tsx",
  routerConfig: "ts",
  compileConfig: "json",
  viteConfig: "ts",
  server: "ts",
  sidebarBoot: "js",
  siteIcon: "svg",
  gitIgnore: "gitignore",
  testPreload: "toml",
  routeTypesDirectory: true,
  declarationDirectory: true,
  bundleDirectory: true,
  parts: [
    "app-routes/alan-web-routes",
    "manifest/alanwalton-web",
    "module/alan-answer-page-types",
    "module/alan-answer-page-write",
    "module/alan-answer-pages",
    "module/alan-app-id",
    "module/alan-app-shell",
    "module/alan-auth-provider",
    "module/alan-nav-items",
    "module/alan-reader-neighbors",
    "module/alan-route-guard",
    "module/alan-session-reader",
    "module/api-fetch",
    "module/api-origin",
    "module/app-layout-loading",

    "module/capacitor-bridge",
    "module/capacitor-cors",
    "module/content-pages-cache-core",
    "module/content-pages-fs",
    "module/declared-effects",
    "module/deep-link-open-sync",
    "module/device-secret-context",
    "module/device-secret-sync",
    "module/edge-swipe-nav",

    "module/home-dni",
    "module/home-dni-param",

    "module/nav-command",
    "module/next-unread",
    "module/offline-cache-fs",
    "module/offline-cache-namespace",
    "module/offline-text",
    "module/offline-text-cache",
    "module/offline-text-sync",
    "module/page-detail-error-boundary",
    "module/page-detail-loading",
    "module/page-detail-with-read-mark",
    "module/pages-persistence-core",
    "module/pages-persistence-fs",
    "module/picture-answering",
    "module/pull-to-refresh",
    "module/pull-to-refresh-decider",
    "module/push-registration-sync",

    "module/read-completion",

    "module/readout-guarding",

    "module/route-access-holding",

    "module/signed-in-redirect",
    "module/status-bar-chrome",
    "module/status-bar-sync",
    "module/use-mark-read-on-end",

    "module/widget-tap-answering",
    "stylesheet/alan-web-look",
    "module/stoplights-activity-sync",
    "module/alan-answer-ask",
    "module/action-bar-answering",
  ],
  toolReached: ["react-dom"],
} as const satisfies RouterApp
