import type { TemperSet } from "akasha/temper/catalog/gear/temper-set/temper-set.page-type.types.ts"

export const eternalWarrior = {
  id: "019e66ec-7afd-70a5-ab5b-92eb49017547",
  type: "page-type/temper-set",
  slug: "eternal-warrior",
  title: "Eternal Warrior",
  key: "eternal-warrior",
  esoSetId: 171,
  hashPlace: 168,
  esoItemIds: [
    59738, 59739, 59740, 59741, 59742, 59743, 59744, 79934, 79935, 79936, 79937, 79938, 79939,
    79940, 79941, 79942, 79943, 79944, 79945, 79946, 81164, 81172,
  ],
  esoArmorTypes: ["ARMORTYPE_HEAVY"],
  esoEquipTypes: [
    "EQUIP_TYPE_CHEST",
    "EQUIP_TYPE_FEET",
    "EQUIP_TYPE_HAND",
    "EQUIP_TYPE_HEAD",
    "EQUIP_TYPE_LEGS",
    "EQUIP_TYPE_NECK",
    "EQUIP_TYPE_OFF_HAND",
    "EQUIP_TYPE_ONE_HAND",
    "EQUIP_TYPE_RING",
    "EQUIP_TYPE_SHOULDERS",
    "EQUIP_TYPE_TWO_HAND",
    "EQUIP_TYPE_WAIST",
  ],
  esoWeaponTypes: [
    "WEAPONTYPE_AXE",
    "WEAPONTYPE_BOW",
    "WEAPONTYPE_DAGGER",
    "WEAPONTYPE_FIRE_STAFF",
    "WEAPONTYPE_FROST_STAFF",
    "WEAPONTYPE_HAMMER",
    "WEAPONTYPE_HEALING_STAFF",
    "WEAPONTYPE_LIGHTNING_STAFF",
    "WEAPONTYPE_SHIELD",
    "WEAPONTYPE_SWORD",
    "WEAPONTYPE_TWO_HANDED_AXE",
    "WEAPONTYPE_TWO_HANDED_HAMMER",
    "WEAPONTYPE_TWO_HANDED_SWORD",
  ],
  setWayshrines: [230, 230, 230],
  setTypeId: 11,
  setNameZh: "永恒战士",
  setNameRu: "Вечный воин",
  setNameFr: "L’Éternel Guerrier",
  setNameEs: "Guerrero eterno",
  setNameDe: "Ewiger Krieger",
  setDropZones: [636, 636, 636],
  setDropMechanics: [26, 26, 26],
  setDlcId: 0,
  itemBrowserSubname: "Eternal Yokeda",
  itemBrowserSources: ["636"],
  itemBrowserItemId: 79967,
  category: "temper-set-category/trial",
  valid: ["*:heavy"],
  bonuses: "jsonl",
  icons: "jsonl",
} as const satisfies TemperSet
