import type { SetTemplate } from "@akasha/temper-equipment/set-template"

export const SETS_DATA_058: readonly SetTemplate[] = [
  {
    id: "meritorious-service",
    name: "Meritorious Service",
    esoSetId: 181,
    subcategoryId: "pvp",
    valid: ["*:light"],
    bonuses: [
      {
        count: 2,
        status: "supported",
        effects: [{ metricId: "health-maximum", effectType: "integer", effectValue: 1206 }],
        description: "Adds 1206 Maximum Health",
      },
      {
        count: 3,
        status: "supported",
        effects: [{ metricId: "magicka-maximum", effectType: "integer", effectValue: 1096 }],
        description: "Adds 1096 Maximum Magicka",
      },
      {
        count: 4,
        status: "supported",
        effects: [{ metricId: "power", effectType: "integer", effectValue: 129 }],
        description: "Adds 129 Weapon and Spell Damage",
      },
      {
        count: 5,
        status: "unsupported",
        effects: [],
        description:
          "When you cast a Support ability while in combat, you increase the Physical and Spell Resistance of yourself and up to 5 group members within 10 meters by 3540 for 20 seconds.",
      },
    ],
    icons: {
      "chest:light": "/esoui/art/icons/gear_breton_light_robe_d.dds",
      "head:light": "/esoui/art/icons/gear_breton_light_head_d.dds",
      "necklace": "/esoui/art/icons/gear_breton_neck_a.dds",
      "ring": "/esoui/art/icons/gear_breton_ring_a.dds",
      "shoulders:light": "/esoui/art/icons/gear_breton_light_shoulders_d.dds",
      "waist:light": "/esoui/art/icons/gear_breton_light_waist_d.dds",
    },
  },
  {
    id: "might-of-the-lost-legion",
    name: "Might of the Lost Legion",
    esoSetId: 410,
    subcategoryId: "crafted",
    valid: ["*"],
    bonuses: [
      {
        count: 2,
        status: "supported",
        effects: [{ metricId: "stamina-maximum", effectType: "integer", effectValue: 1096 }],
        description: "Adds 1096 Maximum Stamina",
      },
      {
        count: 3,
        status: "supported",
        effects: [{ metricId: "magicka-maximum", effectType: "integer", effectValue: 1096 }],
        description: "Adds 1096 Maximum Magicka",
      },
      {
        count: 4,
        status: "supported",
        effects: [{ metricId: "power", effectType: "integer", effectValue: 129 }],
        description: "Adds 129 Weapon and Spell Damage",
      },
      {
        count: 5,
        status: "supported",
        effects: [{ metricId: "health-maximum", effectType: "integer", effectValue: 1206 }],
        description: "Adds 1206 Maximum Health",
      },
      {
        count: 5,
        status: "unsupported",
        effects: [],
        description:
          "When you Block, you gain Empower, increasing the damage of your Heavy Attacks against monsters by 70% for 3 seconds.",
      },
    ],
    icons: {
      "axe": "/esoui/art/icons/gear_breton_1haxe_d.dds",
      "battleaxe": "/esoui/art/icons/gear_breton_2haxe_d.dds",
      "bow": "/esoui/art/icons/gear_breton_bow_d.dds",
      "chest:heavy": "/esoui/art/icons/gear_breton_heavy_chest_d.dds",
      "chest:light": "/esoui/art/icons/gear_breton_light_robe_d.dds",
      "chest:medium": "/esoui/art/icons/gear_breton_medium_chest_d.dds",
      "dagger": "/esoui/art/icons/gear_breton_dagger_d.dds",
      "feet:heavy": "/esoui/art/icons/gear_breton_heavy_feet_d.dds",
      "feet:light": "/esoui/art/icons/gear_breton_light_feet_d.dds",
      "feet:medium": "/esoui/art/icons/gear_breton_medium_feet_d.dds",
      "greatsword": "/esoui/art/icons/gear_breton_2hsword_d.dds",
      "hands:heavy": "/esoui/art/icons/gear_breton_heavy_hands_d.dds",
      "hands:light": "/esoui/art/icons/gear_breton_light_hands_d.dds",
      "hands:medium": "/esoui/art/icons/gear_breton_medium_hands_d.dds",
      "head:heavy": "/esoui/art/icons/gear_breton_heavy_head_d.dds",
      "head:light": "/esoui/art/icons/gear_breton_light_head_d.dds",
      "head:medium": "/esoui/art/icons/gear_breton_medium_head_d.dds",
      "ice-staff": "/esoui/art/icons/gear_breton_staff_d.dds",
      "inferno-staff": "/esoui/art/icons/gear_breton_staff_d.dds",
      "legs:heavy": "/esoui/art/icons/gear_breton_heavy_legs_d.dds",
      "legs:light": "/esoui/art/icons/gear_breton_light_legs_d.dds",
      "legs:medium": "/esoui/art/icons/gear_breton_medium_legs_d.dds",
      "lightning-staff": "/esoui/art/icons/gear_breton_staff_d.dds",
      "mace": "/esoui/art/icons/gear_breton_1hhammer_d.dds",
      "maul": "/esoui/art/icons/gear_breton_2hhammer_d.dds",
      "necklace": "/esoui/art/icons/gear_breton_neck_a.dds",
      "restoration-staff": "/esoui/art/icons/gear_breton_staff_d.dds",
      "ring": "/esoui/art/icons/gear_breton_ring_a.dds",
      "shield": "/esoui/art/icons/gear_breton_shield_d.dds",
      "shoulders:heavy": "/esoui/art/icons/gear_breton_heavy_shoulders_d.dds",
      "shoulders:light": "/esoui/art/icons/gear_breton_light_shoulders_d.dds",
      "shoulders:medium": "/esoui/art/icons/gear_breton_medium_shoulders_d.dds",
      "sword": "/esoui/art/icons/gear_breton_1hsword_d.dds",
      "waist:heavy": "/esoui/art/icons/gear_breton_heavy_waist_d.dds",
      "waist:light": "/esoui/art/icons/gear_breton_light_waist_d.dds",
      "waist:medium": "/esoui/art/icons/gear_breton_medium_waist_d.dds",
    },
  },
  {
    id: "mighty-chudan",
    name: "Mighty Chudan",
    esoSetId: 256,
    subcategoryId: "monster",
    valid: ["monster"],
    bonuses: [
      {
        count: 1,
        status: "supported",
        effects: [{ metricId: "resistance", effectType: "integer", effectValue: 1487 }],
        description: "Adds 1487 Armor",
      },
      {
        count: 2,
        status: "supported",
        effects: [{ metricId: "health-maximum", effectType: "integer", effectValue: 1206 }],
        description: "Adds 1206 Maximum Health",
      },
      {
        count: 2,
        status: "supported",
        effects: [{ buffId: "major-resolve" }],
        description:
          "Gain Major Resolve at all times, increasing your Physical and Spell Resistance by 5948.",
      },
    ],
    icons: {
      "head:heavy": "/esoui/art/icons/gear_undauntedclannfear_head_a.dds",
      "head:light": "/esoui/art/icons/gear_undauntedclannfear_head_a.dds",
      "head:medium": "/esoui/art/icons/gear_undauntedclannfear_head_a.dds",
      "shoulders:heavy": "/esoui/art/icons/gear_undauntedclannfear_shoulders_a.dds",
      "shoulders:light": "/esoui/art/icons/gear_undauntedclannfear_shoulders_a.dds",
      "shoulders:medium": "/esoui/art/icons/gear_undauntedclannfear_shoulders_a.dds",
    },
  },
  {
    id: "mighty-glacier",
    name: "Mighty Glacier",
    esoSetId: 429,
    subcategoryId: "dungeon",
    valid: ["*:heavy"],
    bonuses: [
      {
        count: 2,
        status: "supported",
        effects: [{ metricId: "stamina-maximum", effectType: "integer", effectValue: 1096 }],
        description: "Adds 1096 Maximum Stamina",
      },
      {
        count: 3,
        status: "supported",
        effects: [{ metricId: "magicka-maximum", effectType: "integer", effectValue: 1096 }],
        description: "Adds 1096 Maximum Magicka",
      },
      {
        count: 4,
        status: "supported",
        effects: [{ metricId: "stamina-recovery", effectType: "integer", effectValue: 129 }],
        description: "Adds 129 Stamina Recovery",
      },
      {
        count: 4,
        status: "supported",
        effects: [{ metricId: "magicka-recovery", effectType: "integer", effectValue: 129 }],
        description: "Adds 129 Magicka Recovery",
      },
      {
        count: 5,
        status: "unsupported",
        effects: [],
        description:
          "When you activate a snare or immobilize ability or hit a target with a snare or immobilize ability, you and up to 11 group members gain Major Resolve for 15 seconds, increasing your Physical and Spell Resistances by 5948. This effect can occur once every 10 seconds.",
      },
    ],
    icons: {
      "axe": "/esoui/art/icons/gear_coldsnap_1haxe_a.dds",
      "battleaxe": "/esoui/art/icons/gear_coldsnap_2haxe_a.dds",
      "bow": "/esoui/art/icons/gear_coldsnap_bow_a.dds",
      "chest:*": "/esoui/art/icons/gear_coldsnap_heavy_chest_a.dds",
      "dagger": "/esoui/art/icons/gear_coldsnap_dagger_a.dds",
      "feet:*": "/esoui/art/icons/gear_coldsnap_heavy_feet_a.dds",
      "greatsword": "/esoui/art/icons/gear_coldsnap_2hsword_a.dds",
      "hands:*": "/esoui/art/icons/gear_coldsnap_heavy_hand_a.dds",
      "head:*": "/esoui/art/icons/gear_coldsnap_heavy_head_a.dds",
      "ice-staff": "/esoui/art/icons/gear_coldsnap_staff_a.dds",
      "inferno-staff": "/esoui/art/icons/gear_coldsnap_staff_a.dds",
      "legs:*": "/esoui/art/icons/gear_coldsnap_heavy_legs_a.dds",
      "lightning-staff": "/esoui/art/icons/gear_coldsnap_staff_a.dds",
      "mace": "/esoui/art/icons/gear_coldsnap_1hhammer_a.dds",
      "maul": "/esoui/art/icons/gear_coldsnap_2hhammer_a.dds",
      "necklace": "/esoui/art/icons/gear_breton_neck_a.dds",
      "restoration-staff": "/esoui/art/icons/gear_coldsnap_staff_a.dds",
      "ring": "/esoui/art/icons/gear_breton_ring_a.dds",
      "shield": "/esoui/art/icons/gear_coldsnap_shield_a.dds",
      "shoulders:*": "/esoui/art/icons/gear_coldsnap_heavy_shoulder_a.dds",
      "sword": "/esoui/art/icons/gear_coldsnap_1hsword_a.dds",
      "waist:*": "/esoui/art/icons/gear_coldsnap_heavy_waist_a.dds",
    },
  },
  {
    id: "molag-kena",
    name: "Molag Kena",
    esoSetId: 183,
    subcategoryId: "monster",
    valid: ["monster"],
    bonuses: [
      {
        count: 1,
        status: "supported",
        effects: [{ metricId: "power", effectType: "integer", effectValue: 129 }],
        description: "Adds 129 Weapon and Spell Damage",
      },
      {
        count: 2,
        status: "unsupported",
        effects: [],
        description:
          "When you consecutively Light Attack 2 times, you trigger Overkill for 6 seconds, which increases your Weapon and Spell Damage by 560 but also increases the cost of your abilities by 8%. This effect can occur once every 6 seconds.",
      },
    ],
    icons: {
      "head:heavy": "/esoui/art/icons/gear_undauntedgargoyle_head_a.dds",
      "head:light": "/esoui/art/icons/gear_undauntedgargoyle_head_a.dds",
      "head:medium": "/esoui/art/icons/gear_undauntedgargoyle_head_a.dds",
      "shoulders:heavy": "/esoui/art/icons/gear_undauntedgargoyle_shoulders_a.dds",
      "shoulders:light": "/esoui/art/icons/gear_undauntedgargoyle_shoulders_a.dds",
      "shoulders:medium": "/esoui/art/icons/gear_undauntedgargoyle_shoulders_a.dds",
    },
  },
  {
    id: "monolith-of-storms",
    name: "Monolith of Storms",
    esoSetId: 727,
    subcategoryId: "class",
    valid: ["*"],
    bonuses: [
      {
        count: 2,
        status: "supported",
        effects: [{ metricId: "critical-rating", effectType: "integer", effectValue: 657 }],
        description: "Adds 657 Critical Chance",
      },
      {
        count: 3,
        status: "supported",
        effects: [{ metricId: "power", effectType: "integer", effectValue: 129 }],
        description: "Adds 129 Weapon and Spell Damage",
      },
      {
        count: 4,
        status: "supported",
        effects: [{ metricId: "power", effectType: "integer", effectValue: 129 }],
        description: "Adds 129 Weapon and Spell Damage",
      },
      {
        count: 5,
        status: "unsupported",
        effects: [],
        description:
          "Dealing damage with a Storm Calling ability's initial hit or every 5th tick creates a Monolith near the enemy for 10 seconds, up to one every 1 second. You may have up to 3 Monoliths at a time. Monoliths link to your other Monoliths within 28 meters of each other. Each link deals 680 Shock damage, scaling off of the higher of your Weapon or Spell Damage, every 2 seconds to enemies between and near them. An enemy can only take damage from this set once every 2 seconds.",
      },
    ],
    icons: {
      "chest:heavy": "/esoui/art/icons/gear_templarclass_chest_a.dds",
      "chest:light": "/esoui/art/icons/gear_templarclass_chest_a.dds",
      "chest:medium": "/esoui/art/icons/gear_templarclass_chest_a.dds",
      "head:heavy": "/esoui/art/icons/gear_templarclass_head_a.dds",
      "head:light": "/esoui/art/icons/gear_templarclass_head_a.dds",
      "head:medium": "/esoui/art/icons/gear_templarclass_head_a.dds",
      "necklace": "/esoui/art/icons/gear_breton_neck_a.dds",
      "ring": "/esoui/art/icons/gear_breton_ring_a.dds",
      "shoulders:heavy": "/esoui/art/icons/gear_templarclass_shoulders_a.dds",
      "shoulders:light": "/esoui/art/icons/gear_templarclass_shoulders_a.dds",
      "shoulders:medium": "/esoui/art/icons/gear_templarclass_shoulders_a.dds",
      "waist:heavy": "/esoui/art/icons/gear_templarclass_waist_a.dds",
      "waist:light": "/esoui/art/icons/gear_templarclass_waist_a.dds",
      "waist:medium": "/esoui/art/icons/gear_templarclass_waist_a.dds",
    },
    classId: "sorcerer",
  },
  {
    id: "monomyth-reforged",
    name: "Monomyth Reforged",
    esoSetId: 813,
    subcategoryId: "no-type",
    valid: ["ring"],
    bonuses: [
      {
        count: 1,
        status: "unsupported",
        effects: [],
        description:
          "While in combat and on your Primary Weapon gain Major Force, Minor Berserk, and Minor Vulnerability.\n\nWhile in combat and on your Secondary Weapon gain Major Protection, Minor Vitality, and Minor Timidity.",
      },
    ],
    icons: { ring: "/esoui/art/icons/quest_u46_item_mythic_ring.dds" },
  },
]
