import type { TemperLoreBook } from "akasha/temper/catalog/pursuit/temper-lore-collection/temper-lore-book/temper-lore-book.page-type.types.ts"

export const theHorrorOfCastleXyrPart1 = {
  id: "01a0d5f5-7767-7c7b-8064-121e29709327",
  type: "page-type/temper-lore-book",
  slug: "the-horror-of-castle-xyr-part-1",
  title: "The Horror of Castle Xyr, Part 1",
  collection: "temper-lore-collection/tales-of-tamriel",
  esoBookId: 1129,
  bookIndex: 47,
  charted: true,
  onBookshelves: true,
  mapCounts: [
    { mapId: 7, mapCount: 7 },
    { mapId: 10, mapCount: 27 },
    { mapId: 13, mapCount: 3 },
    { mapId: 16, mapCount: 2 },
    { mapId: 22, mapCount: 9 },
    { mapId: 26, mapCount: 12 },
    { mapId: 27, mapCount: 2 },
    { mapId: 30, mapCount: 25 },
    { mapId: 61, mapCount: 12 },
    { mapId: 143, mapCount: 7 },
    { mapId: 255, mapCount: 15 },
    { mapId: 300, mapCount: 18 },
    { mapId: 660, mapCount: 3 },
    { mapId: 667, mapCount: 2 },
    { mapId: 1060, mapCount: 1 },
    { mapId: 1126, mapCount: 5 },
  ],
} as const satisfies TemperLoreBook
