export const SETTINGS_STRINGS_01: Record<string, string> = {
  DEST_SETTINGS_FISHING_PIN_COLOR: "未取得のピンの色",
  DEST_SETTINGS_FISHING_PIN_COLOR_DONE: "完了したピンの色",
  DEST_SETTINGS_FISHING_PIN_COLOR_DONE_TT: "取得済みの魚のピンの色を設定する",
  DEST_SETTINGS_FISHING_PIN_COLOR_TT: "未取得のピンの色を設定する",
  DEST_SETTINGS_FISHING_PIN_LAYER: "釣りのピンのレイヤ",
  DEST_SETTINGS_FISHING_PIN_LAYER_TT: "釣りのピンのレイヤ",
  DEST_SETTINGS_FISHING_PIN_SIZE: "釣りのピンのサイズ",
  DEST_SETTINGS_FISHING_PIN_SIZE_TT: "釣りのピンのサイズ",
  DEST_SETTINGS_FISHING_PIN_STYLE: "釣りのピンのスタイル",
  DEST_SETTINGS_FISHING_PIN_TEXT_HEADER: "釣りのピンのテキスト",
  DEST_SETTINGS_FISHING_SHOW_BAIT: "ピンに最適な餌を表示する",
  DEST_SETTINGS_FISHING_SHOW_BAIT_LEFT: "ピンに残っている餌を表示する",
  DEST_SETTINGS_FISHING_SHOW_BAIT_LEFT_TT:
    "カバンにあとどれくらい最適な餌が残っているかを表示します。3つ目の数字がある場合は、それはシンプルな餌を表します。",
  DEST_SETTINGS_FISHING_SHOW_BAIT_TT: "使用する最適な餌を表示する",
  DEST_SETTINGS_FISHING_SHOW_FISHNAME: "ピンに魚の名前を表示する",
  DEST_SETTINGS_FISHING_SHOW_FISHNAME_TT: "水の種類にあう未取得の魚を表示する",
  DEST_SETTINGS_FISHING_SHOW_WATER: "ピンに水の種類を表示する",
  DEST_SETTINGS_FISHING_SHOW_WATER_TT: "水の種類を表示する",
  DEST_SETTINGS_FISHING_SUBHEADER: "釣りの設定",
  DEST_SETTINGS_FISHING_TOGGLE: "未完了の位置を表示する",
  DEST_SETTINGS_FISHING_TOGGLE_TT: "アチーブメントの魚を釣る機会のある釣り穴を表示する",
  DEST_SETTINGS_GTRADER_COLOR: "ギルド商人のピンテキストの色",
  DEST_SETTINGS_GTRADER_COLOR_TT: "旅の祠の'ギルド商人'テキストを影響する",
  DEST_SETTINGS_IMPROVEMENT_HEADER: "POI Improvement",
  DEST_SETTINGS_IMPROVEMENT_HEADER_TT: "Improve unknown and known POI",
  DEST_SETTINGS_MAPFILTERS_ACHS_TOGGLE: "アチーブメントの地図フィルターを表示する",
  DEST_SETTINGS_MAPFILTERS_ACHS_TOGGLE_TT: "全てのアチーブメントの地図フィルターを表示する/隠す",
  DEST_SETTINGS_MAPFILTERS_COLS_TOGGLE: "収集の地図フィルターを表示する",
  DEST_SETTINGS_MAPFILTERS_COLS_TOGGLE_TT: "収集の地図フィルターを表示する/隠す",
  DEST_SETTINGS_MAPFILTERS_FISS_TOGGLE: "釣りの地図フィルターを表示する",
  DEST_SETTINGS_MAPFILTERS_FISS_TOGGLE_TT: "全ての釣り穴の地図フィルターを表示する/隠す",
  DEST_SETTINGS_MAPFILTERS_HEADER: "地図のフィルター",
  DEST_SETTINGS_MAPFILTERS_HEADER_TT:
    "このサブメニューは全ての地図のフィルターに関連した設定をカバーします",
  DEST_SETTINGS_MAPFILTERS_MISS_TOGGLE: "いろいろな地図フィルターを表示する",
  DEST_SETTINGS_MAPFILTERS_MISS_TOGGLE_TT:
    "いろいろなピン（アイレイドの井戸、ドゥエマーの遺跡、クラグローンの境界線、ウェアウルフ、ヴァンパイアのピン）の地図フィルターを表示する",
  DEST_SETTINGS_MAPFILTERS_POIS_TOGGLE: "地図のフィルターの地点を表示する",
  DEST_SETTINGS_MAPFILTERS_POIS_TOGGLE_TT: "全ての地点の地図フィルターを表示する/隠す",
  DEST_SETTINGS_MAPFILTERS_QUES_TOGGLE: "クエストNPCの地図フィルターを表示する",
  DEST_SETTINGS_MAPFILTERS_QUES_TOGGLE_TT: "全てのクエストNPCの地図フィルターを表示する/隠す",
  DEST_SETTINGS_MAPFILTERS_SUBHEADER: "地図のフィルター設定",
  DEST_SETTINGS_MISC_AYLEID_WELL_HEADER: "アイレイドの井戸",
  DEST_SETTINGS_MISC_BORDER_HEADER: "クラグローンの境界線",
  DEST_SETTINGS_MISC_BORDER_PIN_COLOR: "クラグローンの境界線のピンの色",
  DEST_SETTINGS_MISC_BORDER_PIN_COLOR_TT: "クラグローンの境界線のピンの色に影響する",
  DEST_SETTINGS_MISC_BORDER_PIN_TOGGLE: "クラグローンの境界線を表示",
  DEST_SETTINGS_MISC_BORDER_PIN_TOGGLE_TT: "クラグローンの上層と下層を分ける境界線を表示する",
  DEST_SETTINGS_MISC_BORDER_SIZE: "クラグローンの境界線のピンのサイズ",
  DEST_SETTINGS_MISC_COMPASS_DIST: "コンパス上の地点までのピンの距離",
  DEST_SETTINGS_MISC_COMPASS_HEADER: "いろいろな設定",
  DEST_SETTINGS_MISC_COMPASS_PIN_TOGGLE: "コンパスにその他の地点を表示する",
  DEST_SETTINGS_MISC_DEADLANDS_ENTRANCE_HEADER: "Deadlands Entrance",
  DEST_SETTINGS_MISC_DWEMER_HEADER: "ドゥエマーの遺跡",
  DEST_SETTINGS_MISC_DWEMER_PINTEXT_COLOR: "ドゥエマーの遺跡のピンのテキストの色",
  DEST_SETTINGS_MISC_DWEMER_PINTEXT_COLOR_TT: "ドゥエマーの遺跡のピンのテキストに影響する",
  DEST_SETTINGS_MISC_DWEMER_PIN_COLOR: "ドゥエマーの遺跡のピンの色",
  DEST_SETTINGS_MISC_DWEMER_PIN_COLOR_TT: "ドゥエマーの遺跡のピンの色に影響する",
  DEST_SETTINGS_MISC_DWEMER_PIN_SIZE: "ドゥエマーの遺跡のピンのサイズ",
  DEST_SETTINGS_MISC_DWEMER_PIN_TOGGLE: "ドゥエマーの遺跡を表示する",
  DEST_SETTINGS_MISC_DWEMER_PIN_TOGGLE_TT: "地図上のドゥエマーの遺跡のon/offを調整します",
  DEST_SETTINGS_MISC_HEADER: "その他の地点",
  DEST_SETTINGS_MISC_HEADER_TT:
    "このサブメニューは、アイレイドの井戸、ドゥエマーの遺跡、クラグローンの境界線をカバーします",
  DEST_SETTINGS_MISC_HIGHISLE_SHRINE_HEADER: "Druidic Shrine",
  DEST_SETTINGS_MISC_PINTEXT_AYLEID_WELL_COLOR: "アイレイドの井戸のピンのテキストの色",
  DEST_SETTINGS_MISC_PINTEXT_AYLEID_WELL_COLOR_TT: "アイレイドの井戸のピンのテキストに影響する",
  DEST_SETTINGS_MISC_PINTEXT_DEADLANDS_ENTRANCE_COLOR: "Pin text color for Deadlands Entrance",
  DEST_SETTINGS_MISC_PINTEXT_DEADLANDS_ENTRANCE_COLOR_TT:
    "Affects the pin TEXT on Deadlands Entrance",
  DEST_SETTINGS_MISC_PINTEXT_HIGHISLE_DRUIDICSHRINES_COLOR: "Pin text color for Druidic Shrines",
  DEST_SETTINGS_MISC_PINTEXT_HIGHISLE_DRUIDICSHRINES_COLOR_TT:
    "Affects the pin TEXT on Druidic Shrines",
  DEST_SETTINGS_MISC_PIN_AYLEID_WELL_COLOR: "アイレイドの井戸のピンの色",
  DEST_SETTINGS_MISC_PIN_AYLEID_WELL_COLOR_TT: "アイレイドの井戸のピンの色に影響する",
  DEST_SETTINGS_MISC_PIN_AYLEID_WELL_SIZE: "アイレイドの井戸のピンのサイズ",
  DEST_SETTINGS_MISC_PIN_AYLEID_WELL_TOGGLE: "アイレイドの井戸を表示する",
  DEST_SETTINGS_MISC_PIN_AYLEID_WELL_TOGGLE_TT: "地図上のアイレイドの井戸をのon/offを調整します",
  DEST_SETTINGS_MISC_PIN_DEADLANDS_ENTRANCE_COLOR: "Pin color for Deadlands Entrance",
  DEST_SETTINGS_MISC_PIN_DEADLANDS_ENTRANCE_COLOR_TT:
    "Affects the PIN color for Deadlands Entrance",
  DEST_SETTINGS_MISC_PIN_DEADLANDS_ENTRANCE_SIZE: "Pin size for Deadlands Entrance",
  DEST_SETTINGS_MISC_PIN_DEADLANDS_ENTRANCE_TOGGLE: "Show Deadlands Entrance",
  DEST_SETTINGS_MISC_PIN_DEADLANDS_ENTRANCE_TOGGLE_TT:
    "This is for turning Deadlands Entrance on/off on the maps",
  DEST_SETTINGS_MISC_PIN_HIGHISLE_DRUIDICSHRINES_COLOR: "Pin color for Druidic Shrines",
  DEST_SETTINGS_MISC_PIN_HIGHISLE_DRUIDICSHRINES_COLOR_TT:
    "Affects the PIN color for Druidic Shrines",
  DEST_SETTINGS_MISC_PIN_HIGHISLE_DRUIDICSHRINES_SIZE: "Pin size for Druidic Shrines",
  DEST_SETTINGS_MISC_PIN_HIGHISLE_DRUIDICSHRINES_TOGGLE: "Show Druidic Shrine",
  DEST_SETTINGS_MISC_PIN_HIGHISLE_DRUIDICSHRINES_TOGGLE_TT:
    "This is for turning Druidic Shrines on/off on the maps",
  DEST_SETTINGS_MISC_PIN_LAYER: "その他の地点のピンレイヤー",
  DEST_SETTINGS_MUNDUS_DETAIL_PIN_TOGGLE: "ムンダスの詳細を表示する",
  DEST_SETTINGS_MUNDUS_TXT_COLOR: "ムンダスストーンのテキスト色",
  DEST_SETTINGS_MUNDUS_TXT_COLOR_TT: "ムンダスストーンの詳細テキストを影響する",
  DEST_SETTINGS_PER_CHAR: "*",
  DEST_SETTINGS_PER_CHAR_BUTTON_TT: "このボタンは現在のキャラクターのみに適用されます",
  DEST_SETTINGS_PER_CHAR_HEADER:
    "黄色の '*' のマークのついた設定は、現在のキャラクターのみに適用されます",
  DEST_SETTINGS_PER_CHAR_TOGGLE_TT: "このスイッチは現在のキャラクターのみに適用されます",
  DEST_SETTINGS_POIS_ENGLISH_TEXT_HEADER: "英語表記の地点",
  DEST_SETTINGS_POI_ENGLISH_COLOR: "Text color for English POI names",
  DEST_SETTINGS_POI_ENGLISH_COLOR_TT: "Set the text color for english translation of POI names",
  DEST_SETTINGS_POI_ENGLISH_KEEPS_COLOR: "Text color for English Keeps names",
  DEST_SETTINGS_POI_ENGLISH_KEEPS_COLOR_TT:
    "Set the text color for english translation of Keeps names",
  DEST_SETTINGS_POI_ENGLISH_KEEPS_HA: "Hide Alliance Name on Keeps Tooltips",
  DEST_SETTINGS_POI_ENGLISH_KEEPS_HA_TT: "Hide Alliance Name on Keeps Tooltips",
  DEST_SETTINGS_POI_ENGLISH_KEEPS_NL: "Add a new line on Keeps tooltips",
  DEST_SETTINGS_POI_ENGLISH_KEEPS_NL_TT: "Add a new line on Keeps tooltips for english name",
  DEST_SETTINGS_POI_ENGLISH_TEXT_HEADER: "English text on Points of interest",
  DEST_SETTINGS_POI_HEADER: "地点",
  DEST_SETTINGS_POI_HEADER_TT:
    "このサブメニューはギルドの商人の位置を含む、未知・既知の地点をカバーします",
  DEST_SETTINGS_POI_IMPROVE_CRAFTING: "Improve Crafting POIs",
  DEST_SETTINGS_POI_IMPROVE_CRAFTING_TT:
    "Improve Crafting POIs by adding set description on tooltip",
  DEST_SETTINGS_POI_IMPROVE_MUNDUS: "Improve Mundus POIs",
  DEST_SETTINGS_POI_IMPROVE_MUNDUS_TT:
    "Improve Mundus POIs by adding effect description on tooltip",
  DEST_SETTINGS_POI_KNOWN_SUBHEADER: "既知の地点",
  DEST_SETTINGS_POI_SHOW_ENGLISH: "Show english POI names",
  DEST_SETTINGS_POI_SHOW_ENGLISH_KEEPS: "Show english POI names for Keeps",
  DEST_SETTINGS_POI_SHOW_ENGLISH_KEEPS_TT: "Show english POI names on the keep tooltip",
  DEST_SETTINGS_POI_SHOW_ENGLISH_TT: "Show english POI names at the top of the map",
  DEST_SETTINGS_POI_UNKOWN_SUBHEADER: "未知の地点",
  DEST_SETTINGS_RELOADUI: "UI更新",
  DEST_SETTINGS_RELOAD_WARNING: "この設定を変更するとすぐに /reloadui が実行されます",
  DEST_SETTINGS_RESET: "デフォルト設定にリセット",
  DEST_SETTINGS_TITLE: "Destinations (JP)",
  DEST_SETTINGS_UNKNOWN_COLOR: "未知の地点のピンのテキスト色",
  DEST_SETTINGS_UNKNOWN_COLOR_EN: "ピンのテキストの色(英語)",
  DEST_SETTINGS_UNKNOWN_COLOR_EN_TT: "有効の場合に全ての未知の地点について英語のテキストに影響する",
  DEST_SETTINGS_UNKNOWN_COLOR_TT: "全ての未知の地点に影響する",
  DEST_SETTINGS_UNKNOWN_PIN_LAYER: "未知の地点のピンのレイヤー",
  DEST_SETTINGS_UNKNOWN_PIN_SIZE: "未知の地点のピンのサイズ",
  DEST_SETTINGS_UNKNOWN_PIN_STYLE: "未知の地点の地図上のピン",
  DEST_SETTINGS_UNKNOWN_PIN_TOGGLE: "未知の地点を表示する",
  DEST_SETTINGS_USE_ACCOUNTWIDE: "アカウント共通の設定を使用する",
  DEST_SETTINGS_USE_ACCOUNTWIDE_TT: "オンにすると全てのキャラクターで同じ設定になります",
  DEST_SETTINGS_VWW_COMPASS_DIST: "コンパス上のピンの距離",
}
