import type { EsoAddon } from "../../code-system/eso-addons/eso-addon.page-type.ts"

export const temperCompanionsAddon = {
  id: "01a0611d-84e6-7be5-8c8a-4c6082779c87",
  pageTypeSlug: "eso-addon",
  slug: "temper-companions-addon",
  definition: "the add-on a player reads a companion's gear and skills from and aims at a build",
  manifest: "json",
  addonManifest: "json",
  bundleEntrySlug: "companions-entry",
  bindings: "xml",
  gitIgnore: "gitignore",
  luaModuleSlugs: ["lua-module/companions-config"],
  partSlugs: [
    "module/companion-qol-types",
    "module/companion-qol-casts",
    "module/companion-qol-state",
    "module/companion-qol-bindings",
    "module/companion-qol-compass",
    "module/companion-qol-constants",
    "module/companion-qol-core",
    "module/companion-qol-globals",
    "module/companion-qol-interaction-state",
    "module/companion-qol-interaction-handlers",
    "module/companion-qol-rapport",
    "module/companion-qol-saved-variables",
    "module/companion-qol-settings-menu",
    "module/companion-qol-ui-strings",
    "module/companion-qol-init",
    "module/companions-codec-constants",
    "module/companions-id-map",
    "module/companions-skill-map",
    "module/companions-codec",
    "module/companions-decoder",
    "module/companions-inventory-matcher",
    "module/companions-reverse-mappings",
    "module/companions-scan-upgrades",
    "module/companions-apply-build",
    "module/companions-constants",
    "module/companions-saved-variables",
    "module/companions-progress",
    "module/companions-display-names",
    "module/companions-equipment-formatters",
    "module/companions-selector",
    "module/companions-commands",
    "module/companions-equipment-rows",
    "module/companions-target-build-input",
    "module/companions-equipment-panel",
    "module/companions-equipment-refresh",
    "module/companions-overview-rapport",
    "module/companions-events",
    "module/companions-globals",
    "module/companions-panel",
    "module/companions-skills-panel",
    "module/companions-equipment-match",
    "module/companions-summary-panel",
    "module/companions-entry",
    "type-declaration/companions-declarations",
    "type-declaration/companions-saved-variables-declarations",
    "type-declaration/companions-globals-declarations",
    "type-declaration/companion-qol-globals-declarations",
    "lua-module/companions-config",
  ],
  invariants: [
    {
      invariantKind: "departure",
      statement: "A companion's gear and skills are written out as one hash a player can carry.",
    },
    {
      invariantKind: "constraint",
      statement: "The index a hash carries is the index the codec constants and mappings give.",
    },
    {
      invariantKind: "gap",
      statement: "A mapping index moved to another place breaks every companion hash saved.",
    },
    {
      invariantKind: "departure",
      statement: "The companion panels are registered as a tab of the characters add-on.",
    },
    {
      invariantKind: "departure",
      statement: "Only gear a companion already holds is offered as an upgrade.",
    },
    {
      invariantKind: "departure",
      statement: "Dismissing and resummoning a companion around an interaction is folded in here.",
    },
    {
      invariantKind: "absence",
      statement: "Nothing here reads another player's companion.",
    },
  ],
} as const satisfies EsoAddon
