{"path":"infrastructure/container-image/dockerfiles/modules/dockerfile-bun-service/dockerfile-bun-service.module.code.ts"}
{"path":"infrastructure/container-image/dockerfiles/modules/dockerfile-imports/dockerfile-imports.module.test.ts"}
{"path":"infrastructure/container-image/dockerfiles/modules/dockerfile-nextjs/dockerfile-nextjs.module.code.ts"}
