import type { PageType } from "akasha/pages/types/page-type.page-type.types.ts"

export const exercise = {
  id: "01a0657e-2bbf-7c1f-a05c-77af77f54cbf",
  pageTypeSlug: "page-type",
  type: "page-type",
  slug: "exercise",
  definition: "one movement Alan can be programmed to perform",
  pluralSlug: "exercises",
  extends: ["page-type/page"],
  parts: [
    "boolean-property/is-ballistic",
    "boolean-property/trains-lengthened-range",
    "calendar-date-property/exercise-last-synced-at",
    "file-property/instructions",
    "number-property/implement-count",
    "number-property/load-factor",
    "number-property/sfr-score",
    "select-property/equipment",
    "select-property/exercise-category",
    "select-property/exercise-level",
    "select-property/exercise-source",
    "select-property/force",
    "select-property/grip-demand",
    "select-property/laterality",
    "select-property/mechanic",
    "select-property/movement-pattern",
    "select-property/muscle-focus",
    "select-property/primary-muscles",
    "select-property/scoring-mode",
    "select-property/secondary-muscles",
    "select-property/secondary-pattern",
    "select-property/skill-cost",
    "text-property/exercise-external-id",
    "url-property/exercise-external-link",
    "url-property/image-end-url",
    "url-property/image-start-url",
  ],
  properties: [
    { pageProperty: "text-property/title", required: true, many: false },
    { pageProperty: "select-property/exercise-category", required: true, many: false },
    { pageProperty: "select-property/equipment", required: false, many: false },
    { pageProperty: "text-property/exercise-external-id", required: false, many: false },
    { pageProperty: "url-property/exercise-external-link", required: false, many: false },
    { pageProperty: "select-property/force", required: false, many: false },
    { pageProperty: "select-property/grip-demand", required: true, many: false },
    { pageProperty: "url-property/image-end-url", required: false, many: false },
    { pageProperty: "url-property/image-start-url", required: false, many: false },
    { pageProperty: "number-property/implement-count", required: true, many: false },
    { pageProperty: "boolean-property/is-ballistic", required: true, many: false },
    {
      pageProperty: "calendar-date-property/exercise-last-synced-at",
      required: false,
      many: false,
    },
    { pageProperty: "select-property/laterality", required: true, many: false },
    { pageProperty: "select-property/exercise-level", required: true, many: false },
    { pageProperty: "number-property/load-factor", required: true, many: false },
    { pageProperty: "select-property/mechanic", required: false, many: false },
    { pageProperty: "select-property/movement-pattern", required: true, many: false },
    { pageProperty: "select-property/muscle-focus", required: true, many: false },
    {
      pageProperty: "select-property/primary-muscles",
      required: true,
      many: true,
      maxCount: null,
    },
    { pageProperty: "select-property/scoring-mode", required: true, many: false },
    {
      pageProperty: "select-property/secondary-muscles",
      required: false,
      many: true,
      maxCount: null,
    },
    { pageProperty: "select-property/secondary-pattern", required: false, many: false },
    { pageProperty: "number-property/sfr-score", required: true, many: false },
    { pageProperty: "select-property/skill-cost", required: true, many: false },
    { pageProperty: "select-property/exercise-source", required: true, many: false },
    { pageProperty: "boolean-property/trains-lengthened-range", required: true, many: false },
    { pageProperty: "file-property/instructions", required: false, many: false },
  ],
  invariants: [
    {
      invariantKind: "departure",
      statement:
        "How a movement is performed is in its own file rather than in a value beside that movement.",
    },
    {
      invariantKind: "departure",
      statement: "A movement with an external id was imported and is refreshed from its source.",
    },
    {
      invariantKind: "departure",
      statement: "A movement Alan wrote himself has no field an external source would fill.",
    },
  ],
  types: "ts",
} as const satisfies PageType
