import type { CarMake } from "../../car-make.page-type.ts"

export const ram = {
  id: "019e4af5-7cc6-7874-a6a2-f46879ad1a61",
  pageTypeSlug: "car-make",
  slug: "ram",
  title: "Ram",
  chargingNetworkAccess:
    "Stellantis announced NACS adoption in 2024 for North American EVs but has not specified whether Ram models will ship with a native NACS port or rely on a CCS1-to-NACS adapter, and whether existing BEV/PHEV models will be retrofitted. The 2026 Ram 1500 Ramcharger ships with a CCS1 port and accepts up to 175 kW DC fast charging. Ram has not announced a charging-network partnership equivalent to Ford BlueOval Charge Network or GM Energy. Owners can access public networks (Electrify America, EVgo, ChargePoint) on a pay-per-use or membership basis. Free-charging promotions tied to vehicle purchase are not currently advertised. Sources: https://www.destinationcharged.com/news/stellantis-adopts-nacs-to-expand-fast-charging-availability-in-2026/ , https://insideevs.com/news/751663/ramcharger-ev-and-ice-mpg/",
  country: "United States",
  drmPolicy:
    "Ram vehicles use Stellantis Uconnect 5 infotainment with Connected Services. Some features are subscription-gated through Uconnect Services (~$14.99/month) and Connect Wi-Fi PLUS — these include remote start from the smartphone app, remote door lock/unlock, real-time traffic, navigation map updates (Navigation Package subscription), Dynamic Range Mapping, and SiriusXM. Key-fob remote start works without subscription. Stellantis in 2021 attempted to expand its subscription model and there was consumer backlash against potential retroactive feature-gating; the company appears to have walked back some of those plans. A 10-year Safety & Security Package (automatic SOS, theft alert, roadside assistance) is included with vehicle purchase. No published evidence of Stellantis remotely disabling already-purchased features in Ram trucks post-sale. The vehicle's core driving functions (engine, transmission, brakes, steering) do not require active connectivity. Sources: https://www.driveuconnect.com/faq.html , https://media.stellantisnorthamerica.com/newsrelease.do?id=25241&mid= , https://pickuptrucktalk.com/2021/12/stellantis-subscription-service-includes-remote-start-too/",
  electrificationStrategy:
    "Ram has had a turbulent electrification arc. The brand originally announced an all-electric Ram 1500 REV (BEV) and a range-extended Ram 1500 Ramcharger (EREV) as its two-pronged electrified pickup strategy under Stellantis Dare Forward 2030. The all-electric Ram 1500 REV BEV was canceled in September 2025 due to slowing demand for full-size BEV pickups in North America. The Ramcharger EREV was repeatedly delayed (originally targeting 2024, then 2025, then early 2026) and was renamed the Ram 1500 REV after the BEV cancellation. As of May 2026, the Ramcharger has begun reaching select US dealers as a 2026 model. The Ram 1500 also offers a 48V mild-hybrid (eTorque) on its V6 Pentastar and (returning for 2026) 5.7L HEMI V8, plus a 48V mild-hybrid system on the new 3.0L Hurricane I6. Stellantis has publicly stated electrification pace should be governed by demand rather than command, indicating a slower transition than its earlier all-EV-by-2030 ambitions. Sources: https://insideevs.com/news/772186/ram-1500-rev-dead/ , https://www.wardsauto.com/news/archive-auto-stellantis-cancels-ram-1500-bev-electric-pickup-rev-extended-range/760779/ , https://www.media.stellantis.com/em-en/ram/press/range-extended-ram-1500-ramcharger-to-lead-brand-s-electrification-push",
  foundingYear: 2009,
  killSwitchPolicy:
    "Data unavailable: Stellantis has made no public statement specific to Ram regarding its implementation plan for the IIJA-mandated impaired-driving-detection technology (FMVSS rule expected late 2026 / 2027). The federal rule is itself still being drafted by NHTSA — NHTSA missed its 2024 statutory deadline and has admitted no commercially-available passive detection technology meets the accuracy requirements. Likely implementation across all major makers (including Ram) will be camera-based in-cabin driver monitoring already present in current Uconnect-equipped Ram trucks (driver attention monitoring is part of current ADAS suites). Search of Stellantis/Ram press releases through May 2026 found no Ram-specific statement on hardware vs software architecture, bypass options, or owner override. Sources: https://www.kbb.com/car-news/nhtsas-new-kill-switch-law-approaches-key-deadline/ , https://www.motor1.com/news/794316/new-cars-mandate-impaired-driver-detection-delay/",
  nacsAdoption: "announced",
  parentCorporation: "Stellantis N.V.",
  reliabilityNotes:
    "Ram 1500 historically rated below segment average on Consumer Reports predicted reliability — the brand has had issues with electrical/infotainment systems, transmission shift quality, and recall frequency. J.D. Power Initial Quality Study has placed Ram at or near top of its segment in some recent years (segment-leading IQS 2022) but long-term dependability lags. The new 3.0L Hurricane I6 introduced for 2025 is too new for reliability data; the 5.7L HEMI V8 returning for 2026 has decades of field data and is generally regarded as durable but with known concerns (lifter/cam, MDS). The Ramcharger EREV is a new architecture (first model year 2026) with no field data. Sources: https://www.consumerreports.org/cars/ram/1500/ , https://www.jdpower.com/cars/ram",
  trims: "jsonl",
  shortList: false,
  sources:
    "- https://en.wikipedia.org/wiki/Ram_Trucks\n- https://www.ramtrucks.com/\n- https://insideevs.com/news/772186/ram-1500-rev-dead/\n- https://www.wardsauto.com/news/archive-auto-stellantis-cancels-ram-1500-bev-electric-pickup-rev-extended-range/760779/\n- https://www.media.stellantis.com/em-en/ram/press/range-extended-ram-1500-ramcharger-to-lead-brand-s-electrification-push\n- https://www.media.stellantis.com/em-en/ram/press/the-legend-returns-2026-ram-1500-offers-5-7-liter-hemi-v-8-etorque-engine-with-proven-performance-and-capability\n- https://www.destinationcharged.com/news/stellantis-adopts-nacs-to-expand-fast-charging-availability-in-2026/\n- https://www.driveuconnect.com/\n- https://www.iihs.org/ratings/vehicle/ram/1500-crew-cab-pickup/2025\n- https://www.kbb.com/car-news/nhtsas-new-kill-switch-law-approaches-key-deadline/",
  exclusionReason: "All models excluded",
} as const satisfies CarMake
