import type { Finding } from "../finding.page-type.ts"

export const aFilePropertyIsFoundByAnExactPageTypeSlugRatherThanByWhatItExtends = {
  id: "01a06942-877b-7cc7-b288-3ca4ebcc3f7e",
  pageTypeSlug: "finding",
  slug: "a-file-property-is-found-by-an-exact-page-type-slug-rather-than-by-what-it-extends",
  domainSlug: "workspace-package/pages-system",
  claim:
    "A page property is held in a file only where its property page states a `fileName` or its page type slug is exactly `file-property` or `page-property-entry`. The test is a string match that does not follow `extendsSlug`, so a new page type extending `file-property` would be invisible to the index: no beside-file path would be built for it, `page-property-has-its-file` would ask for nothing and `file-has-its-page` would refuse the carrier as claimed by no page. `named-file-property` escapes this only because it carries a `fileName`. This is why the two icon carriers were declared as plain `file-property` pages rather than under a page type of their own, which would have read as the tidier shape and would have landed a carrier no page claims.",
  evidence:
    'MEASURED by reading the two places that decide it, both in akasha/pages-system/indexes/index-entries/index-entries.module.code.ts.\n\n`besides` at line 50 is the whole rule:\n\n  function besides(pageTypeSlug: string | null): boolean {\n    return pageTypeSlug === FILE_PROPERTY || pageTypeSlug === ENTRY_PROPERTY\n  }\n\nwith FILE_PROPERTY = "file-property" (line 46) and ENTRY_PROPERTY = "page-property-entry" (line 48). It is called twice. At line 66, inside `fileKeysIn`, after a `fileName` has already been taken if one is there. At line 320, inside `carriedBy`: `if (hit.fileName === null && !besides(hit.pageTypeSlug)) continue`, where `hit.pageTypeSlug` is read straight off the property page by `propertiesAmong` at line 280. Neither call consults `extendsSlug`, which `carriedBy` does read at line 297 but only to climb the PAGE TYPE chain, never the property page\'s own kind.\n\nWHAT FOLLOWS. `pathsOf` at line 71 builds a page\'s beside-file paths from `fileProperties.get(pageTypeSlug)`, and that map is what `carriedBy` returns. A property whose page type is neither of the two named strings and which states no `fileName` never enters the map, so `pathsOf` never names its file. page-property-has-its-file walks exactly `pathsOf`, so it would ask for nothing; file-has-its-page asks the index which pages list a path, so the carrier would come back claimed by none. Both failures are quiet in the direction that matters: the first cannot fire at all, and the second fires on the carrier rather than on the declaration that is actually wrong.\n\nWHY IT HAS NOT BITTEN. Only one page type extends file-property today, `named-file-property`, and every one of its instances states a `fileName` — cargo-manifest "Cargo.toml", cargo-build-script "build.rs", git-ignore ".gitignore" — so the first disjunct catches them all and the exact-match rule has never been the load-bearing one.\n\nNOT FIXED, AND DELIBERATELY. Widening `besides` means changing what the index derives, and `akasha index refresh` is the coordinator\'s alone, so a lane cannot rebuild what it would have changed. The cheaper road was to declare the two carriers as `file-property` pages, which the rule already admits, and to record the gap here. A lane adding a file-property page type later should widen `besides` to follow `extendsSlug` and refresh, or state a `fileName` on every instance and know why it is doing so.',
} as const satisfies Finding
