import type { Finding } from "../finding.page-type.ts"

export const aGeneratedTablesOrderIsASortRatherThanARowOrder = {
  id: "01a060b5-ca1f-75e7-a07c-56921cfa024a",
  pageTypeSlug: "finding",
  slug: "a-generated-tables-order-is-a-sort-rather-than-a-row-order",
  domainSlug: "domain/temper",
  claim:
    "The set table's wire order is a sort rather than a row order, so dividing the table cannot move the codec index. generateTemperSet puts `no-set` first and orders the rest by localeCompare on key, and createDataFile takes `ids` from Object.values, so the index is a total function of the keys alone. The ordered id list derived from the 707 akasha pages matches the committed table index for index. The crafted potion corruption came from recombining groups in turn rather than from division as such.",
  evidence:
    "Measured 2026-09-02. akasha/temper/temper-addon-generators/temper-set/temper-set.module.code.ts lines 54 to 56 sort the pages before emitting: `no-set` first, then a.key.localeCompare(b.key). akasha/utils-narrow/create-data-file/create-data-file.module.code.ts lines 24 and 25 take `list` from Object.values(data) and `ids` from list.map over `id`, so the object literal key order is the wire order temper/game-codec/src/character/build-codec-indices.ts reads at line 64.\n\nThe committed temper/game-characters-equipment/src/sets/generated/temper-set.generated.ts was parsed with a brace-matching parser rather than a text match: 707 entries, no spreads, and the key equals the `id` field on every row. The 707 temper-set pages were read back through askComposed, which reaches entriedValue and entriesIn, and the same sort was applied. The two ordered id lists are identical index for index, `no-set` at 0 and zoal-the-ever-wakeful at 706. bitsNeeded(707) is 10, unchanged.\n\nEntry order was measured in the same pass. Over 707 pages and 2,463 bonus rows the order read back equals the file line order in every case, and 550 of the 707 files are in an order that is not their ids sorted, so the agreement is no coincidence of already-sorted rows. entriesIn in akasha/pages-system/page/page-entries/page-entries.module.code.ts splits on newline and pushes in line order, with no sort and no keying.\n\nOne thing found on the way: the generator cannot run today. Its zod schema asks `icons` for a record of text and the pages answer an array of {id, slot, icon} rows, so generateTemperSet throws on the first set. The bonus effects drifted the same way, {metricId, type, value} on the page against {metricId, effectType, effectValue} in the committed table.",
} as const satisfies Finding
