import type { Finding } from "../finding.page-type.ts"

export const aLandedPageTypeCarriesAlmostNoneOfItsOldProperties = {
  id: "01a0685f-1c23-7151-b39a-e580d4fa93bc",
  pageTypeSlug: "finding",
  slug: "a-landed-page-type-carries-almost-none-of-its-old-properties",
  domainSlug: "domain/akasha-migration",
  claim:
    "A page type landing in akasha almost never carries the properties its old definition declared, so migrating `pages/page-type` does not drain `pages/page-property-definition` behind it. As twelve old page types landed, 136 property definitions left the waiting group: one resolved, 81 found a successor declaring no such property, and 54 found no successor at all. Those 54 are manufactured absence rather than evidence, and that group grows whenever a page type is ablated ahead of its counterpart.",
  evidence:
    "Measured 2026-09-03 in `pages/page-property-definition`, 1,057 files at the start.\n\nSix census rounds forty seconds apart. Live old page types 37, 37, 36, 34, 31, 25. Waiting 238, 238, 229, 213, 156, 102. Key-absent 512, 512, 521, 537, 593, 593. Nowhere 248, 248, 248, 248, 248, 302. Resolved 0, 0, 0, 0, 1, 1. The 136 leaving waiting equal 81 plus 54 plus 1 exactly.\n\nResolution runs old `key` to new `propertySlug`. A page type names a property page by that page's `slug`, and that page carries the `propertySlug` which is the real key, so `alert` with key `description` reaches `alert-description` whose `propertySlug` is `description`. Keying on `propertySlug` reaches an unrelated `description` under `temper`. 230 property pages have a `slug` differing from their `propertySlug`. Inheritance counts: `ki-book` reaches `collection-author` only through ki-collection-template, collection-external and collection.\n\nThe nowhere group holds no positive evidence. Its 47 old page types were read out of git, each from the parent of the commit deleting it. Every `files:` field is `none` (160 rows), absent (51) or a repo-wide `akasha:**/*.<slug>.md` glob (48); ten types have no history. That glob names the old system's own file shape: `find akasha -name '*.<slug>.md'` returns zero for log-day, music-day, option-list, package, workflow, worktree, patch, check and story-turn. Commits fee94d0eb1 and afea396f22 restore 316 definitions ablated on that absence.\n\n38 were ablated on a positive per-file match in commit e267d5f7, verified through the index and again by re-reading each successor page type for `pagePropertySlug` and each property page for `propertySlug`. All 38 read back as git blobs first. 176 keys are camelCase; kebab-casing them resolves none. `monarch-transaction` and its 21 definitions are held.",
} as const satisfies Finding
