import type { Finding } from "../finding.page-type.ts"

export const aMappedCounterpartCanHoldTheCalleeAWrapperUsesAndNotTheWrapper = {
  id: "01a06580-eb5b-7000-83e6-96e18ed30d02",
  pageTypeSlug: "finding",
  slug: "a-mapped-counterpart-can-hold-the-callee-a-wrapper-uses-and-not-the-wrapper",
  domainSlug: "domain/akasha-migration",
  claim:
    "A mapped akasha counterpart can carry the callee a wrapper uses without carrying the wrapper. `@akasha/pages-system/page-file-name` exports `besideAt` and not the `attachmentFileOf` that wraps it, so repointing a caller of the wrapper at that counterpart fails to resolve -- and the repair is the hazard, because the nearest name in the target module is `besideAt`, which answers null for every path not ending `.ts`. The wrapper itself was carried in as `@akasha/markdown-pages/attachment-file`, so the repoint has a real destination and the near-name substitution is the trap rather than the fix.",
  evidence:
    '`akasha/pages-system/pages/file-name/page-file-name.module.code.ts:146` is the whole of `besideAt`: `if (!path.endsWith(TS)) return null`, then the `.ts` rewrite. The module carries 21 exports and `attachmentFileOf` is not among them.\n\n`akasha/markdown-pages/markdown-attachment-file/markdown-attachment-file.module.code.ts:3` imports `besideAt` from `@akasha/pages-system/page-file-name`, and `attachmentFileOf` at :32-42 asks it and, where it answers null, falls back to `${relPath.replace(/\\.md$/, "")}.${key}.${tail}`. So over a `.md` page the fallback is the only branch reached and `besideAt` alone would return null at every call.\n\nThe live callers reach the wrapper by package name: `tools/lib/page-write.ts:6-9` takes `attachmentFileOf` from `@akasha/markdown-pages/attachment-file` and calls it at :41, :44, :97 and :100, and `akasha/markdown-pages/markdown-page-file-values/markdown-page-file-values.module.code.ts:94` calls it too.\n\nThis was found while repointing the `tools/` importers of the root `page/` directory. The eight import lines under `tools/ops`, `tools/aw` and the `tools/` root named `frontmatter.ts`, `page-types.ts`, `file-tree.ts` and `property/registry.ts` besides this one; every one of those was carried into `@akasha/markdown-pages` rather than ruled obsolete, so each was a repoint after all. The one call site this finding first measured, `tools/ops/akasha.ts`, was ablated as dead: no `.command.md` file stands in the repo.',
} as const satisfies Finding
