import type { Finding } from "../finding.page-type.ts"

export const aMarkdownPagesIdIsDerivedAndATypescriptPagesIdIsMinted = {
  id: "01a0612e-dead-7d4f-b2fc-b2eb111e10ae",
  pageTypeSlug: "finding",
  slug: "a-markdown-pages-id-is-derived-and-a-typescript-pages-id-is-minted",
  domainSlug: "workspace-package/pages-system",
  claim:
    "A new page's id comes from one of two places depending on the kind of file it is, and nothing anywhere says so. A markdown page takes a uuid version 5 worked out from its own address, `repo:relPath`. An akasha TypeScript page takes a minted version 7, and that minter cannot reach a markdown page at all. Neither wrong choice is refused: the version 7 check reads TypeScript only, and the name format judges the shape while naming version and variant as no concern of its own.",
  evidence:
    "`idDerivedFrom` at `akasha/file-page-identity/file-page/file-page.module.code.ts:21` is a uuid version 5 over the RFC 4122 OID namespace, hashing the page address. `idOfFilePage` at `:33` is `stated ?? idDerivedFrom(at)`, so it only ever fills a blank. `withId` at `tools/lib/page-write-compose.ts:22` fills it for a new markdown page. Measured by calling it: `akasha:pages/refusal/command-help-parser-unread.refusal.md` works out to `c290df61-98e5-5a8c-ba58-31a09479c521`, the id it now carries. 365 of the 54604 markdown pages match their own address, all recent, so this is live, not historical.\n\nThe version 7 half cannot reach markdown. `insertedInto` at `akasha/command-system/value-minting/value-minting.module.code.ts:66` walks a parsed file's statements for a variable holding an object literal and answers null otherwise, so it never inserts an id into a `.md` file. `statedIn` in `id-is-a-uuid-version-7.code-check.code.ts:52` reads the same way, so the check that would refuse a version 5 reads no markdown. `lower-uuid.name-format.ts` names as an absence that a uuid's version and variant are not judged there. That is why 109 of the 110 documents under `pages/refusal/` carry a version 5 and land, and why a hand-minted version 7 lands beside them and is wrong for life.\n\nI made this mistake an hour ago, which is the reason to write it down: I minted a version 7 for a new refusal document because the convention in front of me was version 7 and a sibling carried one. Corrected at `5968f067f6`.\n\nThe legacy ids cannot be recovered here. None of the 110 matches `idDerivedFrom` over any of the 124309 paths that have ever existed in this git history, nor any of 12437536 combinations of 777346 candidate namespaces by 16 name forms. `temper-pages-lose-the-deterministic-ids-their-slugs-used-to-work-out` records that the old generator worked an id out from the slug and is gone; this adds that the recipe is unrecoverable here, so a legacy id is a stamp now whatever it once was.",
} as const satisfies Finding
