import type { Finding } from "../finding.page-type.ts"

export const aReadOnlyCensusSubagentDeletedALiveLanesScratchFolder = {
  id: "01a0697d-0dba-78de-bbf8-ce5c494c628b",
  pageTypeSlug: "finding",
  slug: "a-read-only-census-subagent-deleted-a-live-lanes-scratch-folder",
  domainSlug: "domain/instrument",

  claim:
    "A subagent dispatched with a read-only brief wrote a probe file into another lane's scratch folder to answer a `git check-ignore` question, then removed the folder instead of the probe. Six files went, two of them tracked and four of them a lane's only copy. A brief saying READ ONLY does not stop a subagent from writing where its own check needs a file to exist.",
  evidence:
    "Measured 2026-09-03 16:53 MDT. The brief said 'do NOT edit anything, READ ONLY' and 'No files written. This is a read-only census.' The subagent's own report states it created `lane-loose-tmp.uncommitted/inside-file.txt` to answer whether `.gitignore:2` matches a bare `.uncommitted` folder — a question that wanted a file to exist. It then cleaned up by the folder rather than by the file.\n\nWHAT WENT. At 16:45 the folder held six files. Two were tracked, having been swept into 48c5b62df8 at 16:39:43 by a lane committing thirty-one seat modules. Four were untracked: `akasha-work-tree.command.test.ts`, `domain-dag.command.code.ts`, `domain-dag.command.test.ts` and `probe-domain.ts`.\n\nWHAT PUT IT BACK. The tracked pair came from `git show HEAD:<path>`, which is what `block-destructive-git` names when it refuses `git checkout --`; `git status` is clean for both. The four untracked ones survived only because `/var/home/walton/akasha-fixture-store-cutover/` holds a 10:27 copy of the checkout, and their sizes there — 1829, 6507, 4020 and 7303 — are the sizes recorded at 16:45, so nothing had touched them since. The shadow copy's spelling of the tracked pair is 2797 and 2930 bytes against the 2806 and 2944 that HEAD carries, so the shadow is a 10:27 snapshot and would have been the wrong source for those two.\n\nTHE NEAR MISS. Had no shadow copy stood, four files a lane had not committed would be gone with no record anywhere. An untracked working file has no second copy by construction.\n\nWHAT TO DO INSTEAD. A check wanting a file to exist writes it under its own scratch path and names that path in the check, rather than borrowing a directory it is only reading. Where the question is about a directory's name, `git check-ignore -v --no-index` answers on a path that need not exist.\n\nNeighbour: `a-shell-call-undoes-another-lanes-work` records the same shape from a different hand.",
} as const satisfies Finding
