import type { Finding } from "../finding.page-type.ts"

export const aRenderedTableHeldByThreeModulesReadsAsHeldByNone = {
  id: "01a06369-1e85-7a3d-a289-bf00f6001979",
  pageTypeSlug: "finding",
  slug: "a-rendered-table-held-by-three-modules-reads-as-held-by-none",
  domainSlug: "domain/temper",
  claim:
    "A rendered table can already be held whole by several akasha modules rather than one, and a match keyed on a single module misses it. `skill-line-mappings.generated.ts` declares ten exports and akasha declares all ten, across three modules of one package. It read as one of the nineteen tables with no landed destination when it is the only one of the nineteen wanting no destination at all: what it wants is for the render to go rather than for a module to be named.",
  evidence:
    "Measured 2026-09-02 at HEAD 2bf37355f9. Every `akasha/**/*.module.code.ts` was parsed with the TypeScript parser rather than read as text — 4,753 files, 16,031 distinct exported names — and each rendered table's own exports were parsed the same way. A positive control asked the map for a name known to be there and found it.\n\nWHERE THE TEN ARE. `SKILL_LINE_ESO_ID_TO_INDEX`, `SKILL_LINE_MAX_RANK`, `MORPHABLE_SKILLS_PER_LINE` and `SKILL_LINE_DISPLAY_ORDER` in `character-capture-skill-line-ranks`. `CLASS_ESO_SKILL_LINE_IDS`, `ALL_CLASS_ESO_SKILL_LINE_IDS`, `RACIAL_ESO_LINE_ID_PER_ESO_RACE` and `BASE_APPLICABLE_ESO_LINE_IDS` in `character-capture-skill-line-groups`. `MORPHABLE_SKILLS_DETAIL_PER_LINE` and `getPlayerSkillLineIndex` in `character-capture-skill-line-map`. Ten of ten, three modules, one package, `temper-characters-capture-addon`.\n\nWHY THE MATCH MISSED IT. The derivation that widened the registry from 4 rows to 38 matched a rendered table to the akasha module already holding that table whole. Three modules holding a third each satisfies no such match, so the table fell through into the pile wanting a decision rather than a match. The other eighteen of the nineteen have no akasha declaration of any of their exports, which is the shape that pile was for, so the method was right about eighteen and wrong about one.\n\nTHE REGISTRY CANNOT SAY IT. `AddonDataTarget` carries one `moduleSlug` beside a `partPrefix` and a count, which is one module or one numbered series of one module's parts. Three differently named modules is neither. Naming any one of the three would claim it holds a table two thirds of which is elsewhere, so no row was written for this table.\n\nWHAT IS LEFT. 55 of the 56 tables the pipeline renders now have a destination row. This is the one without, and it is the one that wants none.",
} as const satisfies Finding
