import type { Finding } from "../finding.page-type.ts"

export const aReusedPropertySlugCarriedTwoSensesOfOneIndex = {
  id: "01a06187-77a9-7000-9e44-e40bd8f057e2",
  pageTypeSlug: "finding",
  slug: "a-reused-property-slug-carried-two-senses-of-one-index",
  domainSlug: "domain/temper",
  claim:
    "A property slug is unique across akasha, so a seat recreating a catalog table either reuses the property already holding that name or invents a near-synonym. Reuse is judged by the name, and nothing judges the values. `poi-index` was reused for Cadwell stops while meaning a different number from the `poi-index` the world zones carry: 75 of 78 rows disagreed for the same place. No check compares what two carriers of one property hold, so only reading both tables caught it.",
  evidence:
    'Measured on 2026-09-02, between landing d33fc444a4 and splitting the property in 0e83b29a12.\n\n`poi-index` was declared at `akasha/temper/temper-catalog/temper-world/world-zones/properties/poi-index.number-property.ts` as "where a point of interest falls among the places a zone holds". Recreating `cadwell-data.generated.ts` needed an index of a point of interest within a zone, the slug was taken, and reuse looked right from the definition alone.\n\nThe values disagree. Cadwell numbers only the stops one level sends a player to, densely from 1, over 4 to 8 stops a zone. A world zone numbers every point of interest it holds, 61 to 73 of them. For Auridon the same five places are 4, 1, 5, 3, 2 in Cadwell and 17, 2, 19, 36, 13 in the world zone. Over all 78 rows, 3 agreed and 75 did not, and the 3 agreed by coincidence of small numbers.\n\nThe two names that were reused in the same act were sound, and comparing values is what told them apart from the third. All 78 `poi-name` values are `poi-name` values of the matching world zone, 78 of 78. All 15 zone names are among the 162 distinct `zone-name` values the `temper-mine` sweep holds. Both were lifted to the page type above their carriers in 8192f2bffd and 5d8e46a945. `poi-index` was not lifted; Cadwell stops now carry `stop-index`, "where a stop falls in the list Cadwell names for one zone".\n\nWhat let the merge through is that a page property is reached by slug and judged by shape. `number-property/poi-index` states `max: null` and nothing else, so any number satisfies it under either sense. The refusal that pushed the reuse was real and correct, `poi-index narrows to 2 pages and must name its page type`, but it asks which page a name reaches rather than whether two carriers mean one thing.',
} as const satisfies Finding
