import type { Finding } from "../finding.page-type.ts"

export const aServiceGoingRedTellsNobodyAndWaitsForAHumanToLook = {
  id: "01a06451-9c3e-7000-b4d8-2f7a05e19c64",
  pageTypeSlug: "finding",
  slug: "a-service-going-red-tells-nobody-and-waits-for-a-human-to-look",
  domainSlug: "domain/alan-harness",
  claim:
    "A workstation service that fails goes red and nothing watches for red. `surplus-fall-notifier` states that three thrown ticks in a row exit 1 so a notifier that can no longer read goes red, and that is honoured — but red reaches Alan only when a person happens to look. On 2026-09-02 the red fired at 12:31:37 and was seen at 14:54, two hours and twenty-three minutes later, by an agent auditing something else.",
  evidence:
    "Searched `services/` and `tools/` for `is-failed` and for `list-units --failed`: no hit. No user unit declares `OnFailure=`. So no unit, timer or command asks systemd which units have failed, and nothing carries that answer anywhere Alan reads.\n\nWhat this costs is not the failure. It is that the go-red path and the stay-silent path arrive at the same place. `surplus-fall-notifier.workstation-service.md:30` states the contract: three thrown ticks exit 1, and `restart-prevent-exit-status: 1` at line 13 makes systemd stop retrying. That is a deliberate, correct design — a notifier that cannot read must not sit green. But a red unit on a workstation nobody is watching is a tombstone rather than an alarm, and for the one service whose entire purpose is to tell Alan something, the failure mode and the working mode are both silence.\n\nThat asymmetry decided a design argument earlier the same day. Two readings were weighed for a wrapper defect that killed this unit: one that would restart forever, and one that would go red. Going red won on the warrant that red is a signal and a restart loop is silence. Measured after the fact, red is also silence. The choice was still right — a red unit is at least a fact on the machine, where a loop leaves none — but the warrant it was argued from does not hold, and a later reader would take it as settled.\n\nThe gap is Alan's to close because only he can say what he wants woken by. The shape is small: something already runs on a timer, and asking systemd for its failed units costs one call. What it must not become is another service that fails silently, which is the defect it exists to report.",
} as const satisfies Finding
