import type { Finding } from "../finding.page-type.ts"

export const akashaServiceInstallAllPlansToRemoveEveryUnitWhenTheIndexReadsEmpty = {
  id: "01a0687d-883f-7001-a150-b9ed1b85868b",
  pageTypeSlug: "finding",
  slug: "akasha-service-install-all-plans-to-remove-every-unit-when-the-index-reads-empty",
  domainSlug: "domain/akasha-migration",
  claim:
    "`akasha service install --all` plans to remove every unit it owns when the service index reads empty, because an empty read is not a refusal and `planFor` treats 'nothing should stand' and 'nothing was read' as the same state. The guard that told them apart stood in `tools/lib/service-project.ts` and did not come across.",
  evidence:
    "Measured 2026-09-03 by reading the predicates rather than the refusal texts, while ablating the `tools/lib` service island.\n\nTHE CHAIN, END TO END. `akasha/service-system/workstation-services/service-reading/service-reading.module.code.ts:78-89` — `everyService` collects pages and returns `{ services }`; where the index lists none it returns `{ services: [] }`, which is not the `{ refused }` shape. `akasha/command-system/commands/service/service.command.code.ts:56-57` — `if (\"refused\" in read) return refused(...)`, so an empty list passes. Line 64 then takes `owned = ourInstalled(home)`, every unit symlinked out of our staging directory. `akasha/service-system/workstation-services/service-installing/service-installing.module.code.ts:100-113` — `planFor` builds `ours` from `standing`, so for an empty `standing` it is empty and `remove = owned.filter((one) => !ours.has(one))` is every owned unit.\n\nThe single-slug path is not exposed: line 64 narrows through `ownedByService`, so a bad slug is refused at `readFor` and reaches no plan.\n\nWHAT WAS LOST. `tools/lib/service-project.ts:124-125` raised `NothingRead` — 'no service document was read, so nothing here can say which units should stand' — precisely to keep an empty read from being read as an empty intent. That file is deleted in this same change as unreachable dead code, its command layer `tools/commands/service/` having already gone, so this page is where the guard now stands recorded. The blob is recoverable at `git rev-parse <commit>:tools/lib/service-project.ts`.\n\nWHY IT MATTERS HERE. This is the failure the migration has already paid for once: a service plan that removes 37 units, 20 of them live, among them the seat system and the tracking handler. `--dry-run` shows the plan before it acts, so the hazard is reached only by a writing run over an index that reads empty.\n\nTHE FIX IS ONE BRANCH: refuse in the command where `slug === undefined && read.services.length === 0`, rather than planning from it. Not taken here because the service surface is another lane's live territory and this lane was ablating, not editing it.",
} as const satisfies Finding
