import type { Finding } from "../finding.page-type.ts"

export const akashaHasNoPageTypeForCodeAGeneratorWrites = {
  id: "01a06039-93e2-7c96-9ab1-fc290dbe9584",
  pageTypeSlug: "finding",
  slug: "akasha-has-no-page-type-for-code-a-generator-writes",
  domainSlug: "domain/temper",
  claim:
    "238 of temper's 4,089 files are written out by a generator rather than typed, and they hold 11.1 MB; it was 280 of 4,484 when this was filed. Every tracked path under `temper/` is 25.6 MB, so the 12.6 MB this page gave for the whole folder was wrong as well as stale. akasha has no page type saying a module's code is written out, and its prose check refuses the banner every one of them opens with. 64 of the 78 temper files over the byte ceiling are generated files.",
  evidence:
    "`git ls-files temper` answers 238 paths either under a `generated/` folder or ending `.generated.ts`, totalling 11,134,270 bytes against 25,587,492 for the folder, measured 2026-09-02. The 12.6 MB this page first gave was never right: it would have left 4,204 non-generated files sharing 1.3 MB, about 310 bytes each. A number that was wrong when written is worth telling apart from one that drifted, because re-measuring catches the second and only arithmetic catches the first.\n\nHanding a generated file to `akasha write` refuses it: writing temper/shared-foundation-misc-dungeons/src/generated/temper-dungeons.generated.ts as a module's code answered `line 1 carries prose, which is none of the code comment forms` for the block opening `Temper Dungeons (Generated) ... DO NOT EDIT \u2014 regenerate with: ops temper addon-data generate`. Stripping the banner let the same body through, so the generator would have to stop emitting the one line that tells a reader not to edit.\n\nakasha decides generated-ness by predicate rather than by page type, and by several narrow local predicates rather than one general one: `addon-source-files.module.code.ts:40` matches `\\.generated\\.tsx?$`, and `check-popover-viewport-safety.module.code.ts:76` keeps a list of its own. The one general classifier was root `generated-file/generated-file.ts`, matching `(^|/)generated/`, `\\.generated\\.[a-z0-9]+$`, the lockfiles, any rows file, and a `do not edit` header in the first three lines; it came out at 1a945bcda2 with the `ops page suffix` closure, whose `repoint.ts:22` was its only reader. No page type, file property or named file property answers to it, and the twenty-six page types under `akasha/code-system` hold none either. What a landed generator's output does carry is the module page beside it saying the code is written out rather than typed, which is a sentence rather than a type.\n\nThe data itself is often already in akasha twice over: the 58 pages under akasha/temper/temper-catalog/temper-world/dungeons/pages and the 3 under quest-givers/pages are what tools/lib/temper-addon-data writes temper-dungeons.generated.ts out of.",
} as const satisfies Finding
