import type { Finding } from "../finding.page-type.ts"

export const alansSiteFoldersRestOnPackagesThatMoveAfterThem = {
  id: "01a05b74-1591-74db-8404-4341d750a4c1",
  pageTypeSlug: "finding",
  slug: "alans-site-folders-rest-on-packages-that-move-after-them",
  domainSlug: "domain/akasha-migration",
  claim:
    "The intent moving the folders under Alan's site that name no package of their own stands before the intents moving pages-core, the page readers and writers, the design packages and pages-ui, and 84 of the 149 files in those folders import one of those packages by name. The question this was filed to ask — whether a package inside akasha may depend on one outside it — has since been answered yes by the tree rather than by Alan: two akasha packages now declare `@shared` dependencies.",
  evidence:
    "Counting the imports of `alanwalton/web/app/lib`, `app/awen` and `app/idle`: 149 TypeScript files, of which 84 name a workspace package outside akasha directly. By folder, lib 24 of 51, awen 37 of 51, idle 23 of 47. The packages named most: design-primitives 41, awen-core 36, pages-ui 35, pages-core 21, pages-access 12, object-store 11. Counting only direct imports understates it, since a file reaching one of the other 65 by a sibling import reaches these through it.\n\nWhat has moved since this was filed is its premise. It read `No package under akasha depends on any @shared package today`, and that is now false. `akasha/pages-system/pages-ui-store/package.json` declares `@shared/pages-access`, `@shared/pages-core`, `@shared/pages-url`, `@shared/supabase-database` and `@shared/utils-narrow`; `akasha/person-system/package.json` declares `@shared/pages-url` and `@shared/utils-narrow`. Counting outside this folder, 37 files under `akasha/` name an `@shared` package. So the reach is not barred, and of the two ways out this named, the tree took the second.\n\nThe mechanism stated here was also wrong. `node_modules/@shared` is one symlink to `../shared`, but that does not force a rename on its own: `alanwalton/native-shell` is a git-tracked symlink of mode 120000 pointing at `../akasha/code-system/ios-app/ios-apps/alanwalton`, so `@alanwalton/native-shell` kept its name with no scope rebuilt. See a-package-moving-into-akasha-loses-its-name.\n\nWhat is left for Alan is not the question this filed but the answer taken in his absence: an akasha package depends on packages outside akasha, and the intent ordering was left standing as it was. The call taken at filing was to move only what needs neither, 10 files of the 162.",
} as const satisfies Finding
