import type { Finding } from "../finding.page-type.ts"

export const anAbstractPageTypeCarriesByBeingFlattened = {
  id: "01a0683d-81a0-7e95-8572-c9fe83e4f956",
  pageTypeSlug: "finding",
  slug: "an-abstract-page-type-carries-by-being-flattened",
  domainSlug: "domain/akasha-migration",
  claim:
    "An old page type holding no properties and no instances can carry into akasha with no `.page-type.ts` of its own, because the lanes that moved its children reparented each child past it. `chapter` and `topic` are both such cases, and a slug inventory reports both absent. akasha kept `collection`, the one file-less abstract in the same chain that holds properties of its own, so holding properties is what tells a flattened abstract from a kept one.",
  evidence:
    'Measured 2026-09-03 while moving `pages/page-type`.\n\n`chapter`: the old file declared `extends-slug: collection`, `files: none`, and no property definition names `page-type/chapter`. Its old descendants were `story-chapter`, then `story-chapter-read`, `-played`, `-written`, `-wandering-inn`, `-royal-road`, and `book-chapter` beside them. Every one that has landed in akasha extends `collection` or `collection-external` and none extends a chapter: `akasha/alan/library/reading/book-chapters/book-chapter.page-type.ts` has `extendsSlug: "page-type/collection"` though its old file declared `extends-slug: chapter`, and `akasha/story/story-chapters-read/story-chapter-read.page-type.ts` has `extendsSlug: "page-type/collection-external"`.\n\n`topic`: the old file declared `extends-slug: page`, `files: none`, and two property definitions, `topic-parents-slugs` and `topic-related-slugs`. Both carried, pulled down into each child and retargeted at that child. `akasha/all-about-alan/topics/properties/topic-parent-slugs.relation-property.ts` and `topic-related-slugs.relation-property.ts` both carry `targetPageTypeSlug: "page-type/all-about-alan-topic"`, and `akasha/alan/library/book-of-everything/learn-everything-topics/properties/topic-part-of-slugs.relation-property.ts` carries `targetPageTypeSlug: "page-type/learn-everything-topic"`. All three topic types extend `page-type/page`.\n\nThe trap I nearly fell into: `all-about-alan-topic` carries id `01a01acb-287b-7001-...` against `topic`\'s `01a01acb-287b-7000-...`, one uuid v7 batch apart, which reads as a rename. It is not. `pages/page-type/all-about-alan-topic.page-type.md` stands in the backup as its own source file with that same id, so akasha\'s page carries that file and not `topic`. An adjacent id is a sibling minting, not a rename.\n\nNot measured: whether the lanes that reparented those children meant to drop the abstract or merely did not reach it.',
} as const satisfies Finding
