import type { Finding } from "../finding.page-type.ts"

export const anEsoUiDocumentDividesOnlyBetweenItsTopLevelControls = {
  id: "01a06118-5afa-776b-8194-3fafdf55e8bb",
  pageTypeSlug: "finding",
  slug: "an-eso-ui-document-divides-only-between-its-top-level-controls",
  domainSlug: "domain/temper",
  claim:
    "An addon's manifest names as many XML documents as it likes, so a big interface file divides into siblings the game loads in order. That division reaches only the gaps between top-level controls. Six of the eight tracked XML files over the old ceiling hold one top-level control itself over it, the largest being TemperCombat_Report at 96,277 bytes, so no division ESO admits brings them under 15,000. The markup ceiling is now 131,072, which admits them and still refuses TemperCombat.xml.",
  evidence:
    "Measured over all 68 XML files `git ls-files` reports. Eight are over 15,000 bytes: TemperCombat.xml 164,528, CraftStore.xml 59,060, LibScrollableMenu.xml 33,687, CraftStore_Cook.xml 25,398, LibSets_SearchUI_Keyboard.xml 22,876, CraftStore_Recipe.xml 21,877, CraftStore_Rune.xml 21,729, PotionMaker.xml 19,518. Serialising each top-level child of the root's sections gives the largest indivisible element in each: 96,277 (TopLevelControl TemperCombat_Report), 55,278 (TemperCrafting_Panel), 13,060, 25,046, 21,274, 21,596, 21,411 and 9,525. So only TemperCombat.xml, LibScrollableMenu.xml and PotionMaker.xml could have been divided under 15,000, and six could not.\n\nThat several documents load is not inferred. `akasha/temper/temper-addons-resolve/addon-json/addon-json.module.code.ts:18` shapes `xmlFiles` as `beforeBundle` and `afterBundle`, each an unbounded array; `tools/commands/temper/addon/copy-metadata.ts:108-117` concatenates the two and copies each. `akasha/temper/temper-lib-media-provider` has landed twelve `eso-interface` pages against a manifest naming five `beforeBundle` entries and twelve `assets`, and the finding `an-addon-manifest-names-asset-paths-the-page-layout-broke` records that its load order is load-bearing and holds.\n\nNo XML in the repository carries an include directive, and ESO's GuiXml offers none, so a document never divides inside an element. Order is the only thing a division must keep: across all 68 files, zero `inherits` references reach a control declared under a later top-level element, so any division at those boundaries that keeps document order leaves every reference resolvable.\n\n`generate-load-order.ts:99` loads `<AddonName>.xml` by name where the manifest states no `xmlFiles`, which is how TemperCombat.xml loads today. Dividing it means giving game-combat-addon an explicit `xmlFiles.beforeBundle` list.",
} as const satisfies Finding
