import type { Finding } from "../finding.page-type.ts"

export const bothReasonsUpstreamDataVerifyGivesForRefusingAreNowUntrue = {
  id: "01a0627a-66f8-7b62-bf28-422ff5db9a6a",
  pageTypeSlug: "finding",
  slug: "both-reasons-upstream-data-verify-gives-for-refusing-are-now-untrue",
  domainSlug: "domain/temper",
  claim:
    "`akasha temper-upstream-data-verify` refuses because the upstream library ports are not in akasha, and its package declares a gap waiting on the Lua machine reaching akasha. Both are now false: the eight ports are in akasha and the Lua machine is what the working verifiers already run through. The command sits behind a gate that opened, and nothing tells a reader the gate opened.",
  evidence:
    'The body at `akasha/temper/temper-commands/temper-upstream-data-verify/temper-upstream-data-verify.command.code.ts` is eleven lines, one `return refused("the upstream library ports are not in akasha yet, so nothing here has a port to rule on", DATA)`. It exits 2 in about a second whatever it is called with.\n\nThe ports are in akasha. `treasure-pins-data`, `zone-geo-data`, `zone-names-data`, `zone-public-dungeon-map-ids`, `map-data-table`, `map-data-pseudo-indices`, `housing-library-data-eu` and `housing-library-data-na` each answer two tracked files under `akasha/`. Since `6c8761c0f7` the temper copies they were ported from are gone, so the sentence is false in the strongest way available: there is no longer anywhere else for a port to be.\n\nThe second reason is on the package. `akasha/temper/temper-upstream-data/temper-upstream-data.workspace-package.ts` line 31 declares the gap `No library is copied or ruled on until the Lua machine reaches akasha.` The machine reached akasha: `akasha/temper/temper-lua-runner` holds 21 tracked files, and all four verifiers name `@akasha/temper-lua-runner` directly.\n\nWriting the body is not a fresh piece of work. `tools/lib/temper-upstream-data/{housing,lib-map-data,lib-treasure,lib-zone}/verify.ts` are working code, repointed at akasha and holding no `@temper/` specifier at all — they name only `@akasha/temper-eso-paths`, `@akasha/temper-lua-runner`, and the four data packages. A seat proved all four exit 0 against a synthetic upstream and exit 2 naming the divergent leaf under a one-character perturbation. Carrying that across beats reimplementing it.\n\nThe shape is worth keeping apart from the instance. A refusal reason is a claim about the world, and this one went stale silently, so work stayed parked behind a condition that had already cleared. Whoever writes the body should correct both statements in the same act.',
} as const satisfies Finding
