import type { Finding } from "../finding.page-type.ts"

export const bothReferenceCensusesThisSwarmAblatedOnUnderCountedTheSameWay = {
  id: "01a0658b-c371-7490-8c5d-2568d799b007",
  pageTypeSlug: "finding",
  slug: "both-reference-censuses-this-swarm-ablated-on-under-counted-the-same-way",
  domainSlug: "domain/akasha-migration",
  claim:
    "Two instruments were built to answer what still reaches a file under tools, handed to thirteen agents, and ablations were justified against them. Both under-count, so a file reads deader than it is, and both fail silently. A reference table matched require but not import, missing every literal inside a dynamic import. An import closure of the live entry points stopped at any shell script, missing what that script spawns. Neither error shows as an error.",
  evidence:
    "Measured 2026-09-02 between commits ef1b164 and d6bd0ee.\n\nThe reference table resolved specifiers with `(?:from\\s*|import\\s*|require\\()\\s*[\"']([^\"']+)[\"']`. The alternation spells `require\\(` with its paren but `import\\s*` without one, so `import(\"./x.ts\")` never matches and a dynamic import counts as no reference at all. Fourteen files scored zero inbound for that reason alone, among them `tools/lib/tracking-pillars.ts`, reached from four dynamic imports, and `tools/claude-usage.ts`, reached from `tools/verb-server.ts:71`, a running process. Corroborated independently: bun's bundler follows those specifiers, and one `tracking/*-sync` entry bundles 402 modules against another's 289.\n\nThe closure followed the same specifier shapes, so it stopped at any shell script. It listed `tools/statusline.sh` as a seed but not `tools/lib/seat-children-live.ts`, `seat-usage-keep.ts`, `seat-children.ts` or `seat-usage.ts`, which that script spawns with bun and which run on every statusline render on every seat. Their own dependencies, `seat-roster.ts`, `seat-principal.ts` and `seat-record.ts`, were in the closure by other routes, so the gap read as coverage rather than as a hole.\n\nBoth were used as safety artifacts, with membership treated as a reason for care and absence as a reason for none. Absence was the unsound half in both.\n\nWhat caught each was a second reader rather than the instrument. The closure gap was found by an agent auditing the artifact it had been handed; the dynamic-import gap by an agent whose bundle count did not match the census. A zero neither produced a diagnostic nor differed in shape from a true zero.\n\nWhat this bears on is the ablation rule for the whole initiative. A positive per-file content match answers whether a body was carried in. It does not answer whether something still runs the old copy, and the instruments built to answer that were the ones that were wrong.",
} as const satisfies Finding
