import type { Finding } from "../finding.page-type.ts"

export const envelopeUnassessed = {
  id: "01a06555-9f3d-7608-a08d-7f239ca9d12b",
  pageTypeSlug: "finding",
  slug: "envelope-unassessed",
  domainSlug: "domain/all-about-alan",
  claim:
    "The envelope of the Provo house has never been assessed, and the retrofit turning on it has no settled scope, cost or date. That one measurement picks which of 48,000, 73,000 or 87,000 kWh/yr the project sizes against, and the thread ranks the retrofit its largest controllable lever on cost. Two costs stand for it, $8,000–15,000 and $30,000–80,000, the second silently adding window work the thread ranks worst. Whether it precedes the PV is settled in one file and left conditional in another.",
  evidence:
    'Read 2026-08-16 across the 41 files of `all-about-alan/projects/solar-power`.\n\n`scope.md`: "House: 6000 sq ft, ~50 years old. Envelope quality unknown — will need a blower-door / insulation assessment before final heat-pump sizing."\n\n`sizing/recommendation.md` ranks it first of nine levers, carries a four-row tree keyed on the finding ("Mid-tier (planning assumption) → 49 kWp"; "Leaky and retrofit-deferred → 58 kWp"), rules "**the envelope assessment should run before PV bid finalization**, not after", and ranks it "**Second priority.**" of four open items.\n\nThe two costs. `envelope.md`: "an $8,000–15,000 retrofit". `envelope/retrofits.md` prices the same "high-leverage four" at "**$8,000–15,000**" and defers windows — "Worst $/%, full stop … Windows are 30× worse on the energy metric." `sizing/recommendation.md` instead: "Retrofit cost for a 6000 sq ft 1970s home (blower-door fix, attic R-49, wall blow-in if feasible, window upgrades): **$30,000–$80,000**." `sizing/cost.md` repeats the second.\n\nThe ordering. `envelope/sequence.md` resolves it — "into Option C (parallel) with one hard sequencing constraint: post-retrofit Manual J before heat-pump equipment order" — with a 4–6 month calendar. `sizing/recommendation.md` leaves it open: "**The retrofit timing matters.** If the envelope work happens before PV … If PV goes first …"\n\nNothing records an audit booked or a quote taken. `envelope/incentives.md` names GreenHome Specialties "**First call**"; `envelope/assessment.md` specifies what to ask the auditor. Both written forward.\n\nNot measured: I read only `books/`, so I cannot say no audit was booked. What I checked is that no file carries a measured ACH50, R-value survey, duct-leakage figure or Manual J output.',
} as const satisfies Finding
