import type { Finding } from "../finding.page-type.ts"

export const libAddonMenuLandsBehindADeclarationMergeNotACopy = {
  id: "01a061d3-0ea8-7c7e-9216-5cd558003389",
  pageTypeSlug: "finding",
  slug: "lib-addon-menu-lands-behind-a-declaration-merge-not-a-copy",
  domainSlug: "domain/temper",
  claim:
    "`shared-addon-libraries-lib-addon-menu` is no cheap landing, whatever its 161,363 bytes suggest. Its 20 `.d.ts` redeclare 32 game globals the shared declaration set already holds, add 39 more it does not, and merge members into 11 interfaces it already names. `casts.ts` holds 34 `asX(value: unknown): X` helpers, each a double cast wearing a function's clothes. The census is below; what is left is the reconciliation, the act that took tree-wide typecheck from zero to forty-four.",
  evidence:
    "Measured 2026-09-02 against 139 shared `.d.ts` holding 6,986 globals, 396 interfaces and 273 types.\n\nRedeclared, so a second declaration is TS2451: `ANIMATION_MANAGER`, `ZO_PreHookHandler`, `ZO_NORMAL_TEXT`, `ZO_DISABLED_TEXT`, `ZO_ERROR_COLOR`, `ESO_Dialogs`, `_G`, `ZO_ScrollList_ScrollAbsolute`, `ZO_ScrollList_Commit`, `ZO_ScrollList_GetData`, `ZO_ScrollList_EnableSelection`, `ZO_ScrollList_GetDataTypeTable`, `ZO_FadeSceneFragment`, `LibAddonMenu2`, `LibDebugLogger`, `SCENE_FRAGMENT_SHOWN`, `SCENE_FRAGMENT_HIDDEN`, `SetCameraOptionsPreviewModeEnabled`, `zo_clamp`, `ZO_TableOrderingFunction`, `PlaySound`, `EVENT_GLOBAL_MOUSE_UP`, `DT_HIGH`, `DL_CONTROLS`, `TEX_MODE_WRAP`, and seven `SI_*`. Each has to go, and each going can leave a TS2339 where the shared type is the narrower one.\n\nNew, so each needs a grep for a private `declare global` first: 17 `ZO_*`, `KEYBOARD_OPTIONS`, `COLOR_PICKER_GAMEPAD`, `TEXT_TYPE_ITERATION_BEGIN` and `_END`, 12 `SI_*`, and five `LAM*` publish globals of the addon's own.\n\nMerged into: `Control`, named by five shared files and taking 30 members here; `ZoComboBox`, 18 members; `WindowManager`, `ButtonControl` (`SetText` and `SetFont` already there), `LabelControl`, `TextureControl`, `BackdropControl`, `AnimationManager`, `SceneManager`, `Scene`, `SharedChatSystem` (`primaryContainer` already there).\n\nThe rest is easy but not free: `src/` and `src/widgets/` flatten to 29 modules, all needing a prefix because `types`, `main`, `util`, `state`, `constants` and `casts` are no free slugs; `widgets/dropdown.ts` is 14,612 bytes against a 15,000 ceiling, and the casing renames push it up; 20 module-level bindings are refused by the casing rule; `public-api.ts` orders 15 side-effect imports that register the widgets in that order.",
} as const satisfies Finding
