import type { Finding } from "../finding.page-type.ts"

export const movingAFileUnderToolsReExecsEverySupervisorThreeMinutesLater = {
  id: "01a06557-d298-7ea5-a0cd-85b08639bf87",
  pageTypeSlug: "finding",
  slug: "moving-a-file-under-tools-re-execs-every-supervisor-three-minutes-later",
  domainSlug: "domain/akasha-migration",
  claim:
    "Every live supervisor hashes the paths and bytes of its own import closure, 379 files under tools/lib, and re-execs itself once that hash holds steady for three minutes. Any move inside that closure therefore arms a synchronised re-exec of all twenty seats about three minutes later, unrehearsed. The re-exec spells the launch argv, which is the absolute tools/run-supervisor.ts captured at boot, so moving that one file makes every supervisor exec a path that is gone.",
  evidence:
    'Measured 2026-09-02 at commit ef1b164, with twenty agents running.\n\n`tools/lib/supervisor-file-version.ts` line 43 `supervisorFileSet` walks the relative-import graph from an entry and returns every file reached. Line 51 `hashFileSet` folds each file into a sha256 with `hasher.update(path)` before `hasher.update(await Bun.file(path).bytes())`, so the path is hashed as well as the bytes and a pure move changes the digest with no edit. Line 66 sets `DEBOUNCE_MS = 180_000` and line 68 `CEILING_MS = 900_000`; `decideVersionDelivery` at line 78 delivers once a new digest has held steady for the debounce, or unconditionally past the ceiling.\n\n`tools/lib/supervisor-monitors-wire.ts` line 39 polls that on a timer. `tools/lib/supervisor-self-heal-state.ts` line 17 defines `SUPERVISOR_SCRIPT = process.argv[1] ?? ""`, captured at launch. `tools/lib/supervisor-lifecycle.ts` line 30 builds `[process.execPath, SUPERVISOR_SCRIPT, ...resolveReExecArgv()]` and line 32 hands it to `attemptInPlaceReExec`, which calls `execvpe` in `tools/lib/supervisor-reexec.ts` line 57. On failure it falls back to `Bun.spawn` of the same argv, awaits the child and calls `process.exit(code)`. The pane is launched with `remain-on-exit`, so a supervisor exiting that way is dead with nothing left to restart it.\n\n`ps` shows the launch argv is absolute. The migrated `akasha/seat-system/seat-launching/seat-launching.module.code.ts` composes it, and lines 7 and 9 hold `PTY_PROXY_REL = "tools/lib/pty-proxy.ts"` and `SUPERVISOR_REL = "tools/run-supervisor.ts"`, so the akasha side is not free of tools.\n\nOne further edge: `importGraph` line 18 matches only relative `from` specifiers, so a module repointed to an `@akasha/` specifier drops out of the watched set.',
} as const satisfies Finding
