import type { Finding } from "../finding.page-type.ts"

export const perPackageEsoDeclarationsCollideInOneProgram = {
  id: "01a06066-1e28-731e-9847-06375447d451",
  pageTypeSlug: "finding",
  slug: "per-package-eso-declarations-collide-in-one-program",
  domainSlug: "domain/temper",
  claim:
    "Thirteen ESO addon libraries each restated the game and Lua names that library reaches in a private `declare global`, and akasha compiles one program, so the restatements collide. A name written as `function` merges as an overload; a name written as `const`, `var` or `type` cannot, and raises TS2451 or TS2300. Narrowing a module mends nothing, because the conflict lies between packages rather than inside one. A shared set answered the thirteen, and the shape is back: seven live TS2451 today.",
  evidence:
    "`akasha audit --check typecheck` over 25,144 files answered 567 refusals on 2026-09-01, and 125 of its 137 printed lines named a `*-declarations` module. The thirteen modules declared 413 distinct names, 86 in more than one package: seven `function` everywhere, which merge as overloads; twenty-seven `const` everywhere and twenty-six `const` against `var`, both of which raise TS2451; fourteen `interface`, which merges, with TS2717 following where a member differs. Every name written `function` is a lowercase Lua builtin, and akasha refuses a function whose name is not lowerCamelCase, so a PascalCase game name is pushed into the one form that cannot merge.\n\nMended by the second route named here: a shared set at `temper-eso-types` and `temper-addon-library-types`, judged against itself by `declarations-agree`. Three of the thirteen modules went and ten were trimmed, leaving twelve private `declare global` blocks.\n\nThe shape is back, which is why this page is kept. The same check answers 40 refusals over five packages on 2026-09-02, seven of them TS2451 where a private block restates a name the shared set now holds: `zo_clamp` at `custom-menu-declarations:2`, `ZO_SharedRightPanelBackground` and `ALCHEMY` at `alchemy-station-declarations:4` and `:14`, `LibAlchemyStation` at `alchemy-station-entry:5`, `LibAsync` at `async-global:7`, and `ZO_FadeSceneFragment` and `ZO_MenuBar_SelectFirstVisibleButton` at `main-menu-game-shape-2:16` and `:27`. TS2717 and TS2687 over `lastCategory` and `categoryBar` are the interface half of it.\n\nWhy nothing caught it. `declarations-agree` roots a `.d.ts` alone and never sees a `declare global` in a module body, and a write roots only the changed file's import closure, so each of these met every check at its own write. A tree-wide typecheck number belongs in a coordinator's report rather than on this page: this page was amended at `18c75faff4` to say typecheck was zero, which was true when written and false within the hour.",
} as const satisfies Finding
