import type { Finding } from "../finding.page-type.ts"

export const theFitnessPageTypesAreReadOffTheCheckoutIndexNotTheStore = {
  id: "01a0685d-cca7-732e-8d9b-4b6d6b437e73",
  pageTypeSlug: "finding",
  slug: "the-fitness-page-types-are-read-off-the-checkout-index-not-the-store",
  domainSlug: "domain/akasha-migration",
  claim:
    "Neither road the exercise code was on reaches a fitness page. `@akasha/pages-query/store-spelled-asking` is the store over HTTP, which answers 400 for every fitness page type, and `@tools/lib/page-query`'s `answer(resolveRoots(), ...)` derives only the eleven old markdown page types. The road that works on the workstation is `valuesOfType(root, pageTypeSlug)` from `@akasha/indexes`, whose keys are the page file's own humped names and whose values are the values the page file states rather than their text.",
  evidence:
    "Measured 2026-09-03 in this checkout. `answer(resolveRoots(), { pageType })` returned null for schedule-day, workout-session, set-log, client-profile, mobility-reading, equipment-item, coaching-constraint, workout-schedule and exercise; `backedTypes` named eleven types, every one a `**/*.<slug>.md` glob, and no fitness type among them. `valuesOfType` on the same root answered 14 schedule-days, 16 workout-sessions, 122 set-logs, 13 coaching-constraints, 7 mobility-readings, 2 workout-schedules and 884 exercises.\n\nThree things follow that are not yet fixed.\n\nFirst, a field is named on a row as the page file names it, so a workout-session carries `workoutSessionDate` and `workoutSessionCompletedAt`, a mobility-reading carries `mobilityReadingMetric`, and a coaching-constraint carries `coachingConstraintActive`. `exercise-finding` asked for `completedAt` and `date`, which name nothing; that one is repaired in the commit this finding lands in.\n\nSecond, `selection-policy.module.code.ts` still reads through `@tools/lib/page-query`, so `readBodyweight`, `readSelectionPolicy` and `selectionPolicyStated` refuse, and the eight fitness commands importing them refuse with them. Its `readBodyweight` also duplicates `statedBodyweight` in `session-volume`. Left alone because a sibling lane holds that file.\n\nThird, no client-profile, equipment-item or selection-policy page stands at all, so even the road that works answers nothing for them. Volume counted against a bodyweight nothing states is a gap on `session-volume`, not a bug.",
} as const satisfies Finding
