import type { Finding } from "../finding.page-type.ts"

export const theOpsCommandSetFoldsASurvivingFolderScanInAheadOfThePages = {
  id: "01a06936-c745-7f0d-88fc-4ec1fd170f1e",
  pageTypeSlug: "finding",
  slug: "the-ops-command-set-folds-a-surviving-folder-scan-in-ahead-of-the-pages",
  domainSlug: "domain/akasha-migration",
  claim:
    "The `ops` command set is two lists folded together rather than one. `tools/ops/set.ts:11` puts `declaredCommands()` — a scan of the `tools/commands` tree that outlived the 2026-09-03 conversion — ahead of `forwarderCommands()`, and of two entries sharing command words the first one wins. So for a file under `tools/commands` that also carries an `ops-command` page, the scan gives the code and the page gives only the help. Taking such a file away hands its words to the page forwarder, which then refuses by naming the file, the words and the page. A file under `tools/commands` with no page instead drops out of the set with nothing to say so. Which of the two a removal gets depends only on whether a page names the file.",
  evidence:
    "Measured 2026-09-03 at commit 730c65e226, by loading `declaredCommands`, `forwarderCommands` and `commandDocuments` directly and replaying the fold in `set.ts:11-17` line for line.\n\nTHE SUBJECT. `declaredCommands()` over the repository answers 16 commands, one per file under `tools/commands`. `commandDocuments()` answers 22 `ops-command` pages. The folded set is 22 commands: 16 from the scan and 6 from pages naming a loose file. Fifteen of the sixteen scanned files are also named by a page, and in every one of those the fold keeps the scanned entry and attaches the page as `document` alone — `set.ts:16` is `here.push(document === undefined ? one : { ...one, document })`, which replaces no `load`.\n\nCONTROLS, BOTH SIGHTED. `declaredCommands()` over a folder holding one seeded file answers exactly that one command; over a folder holding an empty `tools/commands` it answers 0. So the 16 is a reading of the tree rather than of a cached list.\n\nTHE REMOVAL, MEASURED ON A ROOT WHERE TWO FILES WERE WITHHELD. A symlink farm was built whose `tools/commands` tree links every real file except `tracking/activity-set.ts` and `tracking/words-sync.ts`, with every other path linked to the real repository, and `AKASHA_ROOT` pointed at it. The scan then answered 14. `tracking activity-set`, which a page names, was answered by the page forwarder instead, and loading and running it threw `tools/commands/tracking/activity-set.ts is not there under <root>, so `ops tracking activity-set` forwards to nothing. The page `ops-tracking-activity-set` still names that file: put the file back, or take the page away with the command` (`tool-forward.ts:68-74`, thrown at `:117`). `tracking words-sync`, which no page named, was absent from the folded set altogether. The untouched `tracking task-sync` was still answered by the scan, so the instrument was sighted on all three arms rather than on one.\n\nWHAT FOLLOWS. A path census over `tools/commands` is worth nothing by itself: `declared.ts:51` is `load: () => import(path)` over a variable, so no import graph reaches any of the sixteen files and each scores zero inbound while running. That much was already filed as `every-ops-command-looks-dead-to-a-static-import-census`. What is added here is that the loudness of a removal is not a property of the `tools/commands` tree at all — it is a property of whether a page names the file, and it was uneven until `tracking words-sync` was given a page at 730c65e226.\n\nA NOTE ON THE OTHER HALF. This scan is not the mechanism `55aa651e35` replaced. That one was `tools/lib/tool-declaration.ts` reading loose `tools/*.ts` files, and it is gone. Reading the conversion as having ended folder scanning in `ops` is the error this finding is filed against.",
} as const satisfies Finding
