import type { Finding } from "../finding.page-type.ts"

export const theEightChecksAblationDropsAreNamedHere = {
  id: "01a0635d-589b-7107-908d-9d1a0ac75937",
  pageTypeSlug: "finding",
  slug: "the-eight-checks-ablation-drops-are-named-here",
  domainSlug: "domain/temper",
  claim:
    "Ablating `temper/shared-build-deploy-checks` drops 8 of its 17 check entry points and 27 of its 58 modules. None of the 8 can be dispatched today, so no judgement is lost, but the rules they carried are. Two of the 27 must be rehomed rather than dropped: `eso-base-game-globals.generated` and `eso-colon-methods.generated` are the last two files in the tree carrying an ESO clone provenance line, and the audit reading them refuses on an empty population.",
  evidence:
    'Measured 2026-09-02 at `909ffc3ad1`, over the 58 modules of the old package against the 22 recreated in `akasha/temper/temper-build-deploy-checks`.\n\nOf 17 check entry points, 6 are already recreated in the twin, 3 are kept because live code imports them — `check-addon-sandbox-safety`, `check-addon-sandbox-load`, `check-addon-removed-refs` — and these 8 are dropped:\n\n`check-addon-cross-cluster-attach`, `check-addon-fingerprint-residue`, `check-addon-hook-fires-before-assignment`, `check-addon-owned-global-clobber`, `check-tstl-anytable-length`, `check-tstl-colon-dot-self-shift`, `check-tstl-range-double-shift`, `check-tstl-this-void-colon-method`.\n\nFour of the eight are TSTL emit rules: a `:` where a `.` was meant shifting `self`, a length read on an any-typed table, a double-shifted range, and a void-this method called with a colon. Four are add-on wiring rules: attaching across clusters, residue from an earlier fingerprint left in the build output, a hook firing before the assignment it reads, and two add-ons clobbering one owned global. The ownership rule alone survives, as the module landed at `fe5bbd3ca9`.\n\nNone of the 8 buys judgement now. Each is named only as a path string under `script:` and `ts-file:code:`, and every such subject is dispatched through `infra/cluster-checks/src/run-check.ts`, whose line 11 exits 2 having judged nothing. A reference count is not a value count: 42 path-string references bought zero judgement here while 4 imports bought all of it.\n\nOne carry-across hides inside the recreation. Of 614 string literals across the twin\'s 45 files, exactly one is rooted at the old tree: `WALK_ROOT = "temper"` at `eso-clone-artifacts.module.code.ts:9`. A twin reproducing the old path constant keeps reading the old tree after that tree is gone.',
} as const satisfies Finding
