import type { Finding } from "../finding.page-type.ts"

export const theMigrationMintsADayNameAndNoCheckMakesItAgreeWithTheFunnel = {
  id: "01a06078-2130-7491-9911-2667afca4fbb",
  pageTypeSlug: "finding",
  slug: "the-migration-mints-a-day-name-and-no-check-makes-it-agree-with-the-funnel",
  domainSlug: "domain/akasha-migration",
  claim:
    "`tools/daily-tracking-migration/convert.ts` decides what Alan's landed days are called, out of `SLUG_PREFIX` in `shape.ts`, and never asks the funnel. `dayNameIn` in `day-place.ts` decides what every reader goes looking for. Nothing made the two agree. Making them agree in code gives `convert.ts` the page store through `day-place.ts` and turns a clean funnel audit into a refusal, so the writer of a day's name cannot take the rule that spells it.",
  evidence:
    "Measured on 2026-09-01 by a census of every restatement of a day's name outside `day-place.ts`. `convert.ts:249` mints a landed day's slug as `${SLUG_PREFIX}${source.day}` from `shape.ts:49`, and `convert.ts:246` refuses a source whose stated slug is not its bare date, which is the markdown half of the same rule. `day-place.ts:66-76` says both halves over again. Neither file imports the other and no test held them to one another; a probe confirmed both spell one name today over four sampled days.\n\nA disagreement would say nothing when it happened. A query for a name no page answers to comes back empty rather than refusing, so Alan's tiles would read zero on days he tracked and his points would be summed from nothing.\n\n`audit tracking-funnel` reads findings=0 over 7292 weighed files and cannot see this. Its rule is a join: a file must name a day page type AND reach a page store road. `convert.ts` names one and reaches no store; `day-place.ts` reaches the store and is the funnel itself. Neither is a finding alone, and the pair is invisible to it.\n\nThe call taken: the agreement is said as a test, `tools/daily-tracking-migration/shape.test.ts` in commit 6cf93bb049, because that audit sets test files aside — 391 weighed before it and 392 after, findings unchanged, exit 0 both times. The code repair, having `convert.ts` ask `dayNameIn`, was not taken: it would give `convert.ts` the store through `day-place.ts` and turn a clean audit into a refusal. That is the same wall the finding `a-pure-naming-rule-lives-in-a-file-that-reaches-the-store` met from the reader's side, met again from the writer's. Lifting `dayNameIn`, `dayNameOf` and `dayOfName` into a file of their own answers both.",
} as const satisfies Finding
