import type { Finding } from "../finding.page-type.ts"

export const theLorebookTablesCarryWhatTheirTypesDeny = {
  id: "01a0619a-e737-78c9-94aa-9e96278ea97d",
  pageTypeSlug: "finding",
  slug: "the-lorebook-tables-carry-what-their-types-deny",
  domainSlug: "domain/temper",
  claim:
    "The three lore book data tables carry fields their TypeScript interfaces never declared, and six helpers shaped `asX(value: unknown): X` kept the compiler from seeing it. The zone entry declares nine keys where the data holds seventeen more. A book name is once a number, a map count is once a boolean, and two zone achievement ids are arrays where the type says number. The tables could not have been recreated under the declared shapes at all.",
  evidence:
    'Measured on 2026-09-02 by importing the three tables and enumerating every key at every depth.\n\n`EideticBookZoneEntry` in `temper/game-collections-addon/src/lorebooks/types.ts` declares `pm`, `zm`, `px`, `py`, `gp`, `c`, `b`, `k` and `q`. The 6,131 entries hold `px` 6,120 times, `py` 6,120, `pm` 6,110, `d` 2,198, `mn` 2,067, `zm` 1,599, `zx` and `zy` 980 each, `fp` 413, `i` 309, `r` 268, `qp` 152, `qc` 89, `sm` 28, `l` 18, `zt` 16, and `ld`, `pnx`, `pny` 7 each. Four declared keys appear in no record: `gp`, and `c`, `b`, `k`, which `LoreBooks_GetEideticData` writes at runtime.\n\n`EideticBook` omits `l`, which book 1733 carries, and declares `en`, which no record carries, so the title fallback reading it can never fire. Book 5666 has `n: 6403`. Book 7130 has `m[2114]: true`. `ShalidorPinEntry` omits `6` and `worldY`, each carried once. `AchievementIdTable` says `Record<number, number>`, yet exploration 25 is `[986, 1126]` and zone quest 14 is `[758, 759, 760, 761, 762]` — and `shouldDisplayLoreBooks` already branches on `type(conditionData) === "table"`, so only the type was wrong.\n\nAll of it reached the compiler through `asEideticBookTable`, `asBookshelfEntryMap`, `asAchievementIdTable`, `asEideticLibraryTable`, `asShalidorDataTable` and `asEideticBookZoneEntries` in `data-accessors.ts`, each `return value as T`. `temper-lorebooks` widens the interfaces to what was measured and drops all six.\n\nThree figures in `akasha-holds-no-lorebook-map-pin-and-not-every-book-name` need correcting. Its 4,773 distinct names counts one undefined and one number; the distinct string titles number 4,771. Its 59 collection names counts undefined; there are 58. Its closing sentence about insertion order does not hold, because every key of `m` is an integer and a runtime answers integer keys in ascending order however they were written.',
} as const satisfies Finding
