import type { Finding } from "../finding.page-type.ts"

export const theClusterSecretsPathNamedNothingSoThePkiOverwriteGuardCouldNotFire = {
  id: "01a068e9-948b-7d22-b918-b6173db25026",
  pageTypeSlug: "finding",
  slug: "the-cluster-secrets-path-named-nothing-so-the-pki-overwrite-guard-could-not-fire",
  domainSlug: "domain/akasha-migration",
  claim:
    "While `clusterSecretsSopsPath` named `pages/cluster/<cluster>.sops.yaml`, which no file was ever at, the `talos-secrets-gen` guard that refuses to write over a cluster's PKI could not fire, because the file it tests for could never be there. A run without `--force` would have written a second bundle and left the real one orphaned. The function now names `akasha/machines/clusters/pages/<cluster>.cluster.sops.yaml`, where the bundle now is.",
  evidence:
    "Measured 2026-09-03 14:0x MDT, after moving the bundle out of `pages/cluster/` and repointing the function.\n\nTHE GUARD. `talos-secrets-gen.command.code.ts:67-68` reads `const destPath = clusterSecretsSopsPath(read.cluster)` and refuses when `existsSync(destPath) && !read.force`, saying that writing again loses every node's PKI. The refusal is right and the input to it was wrong.\n\nCORRECTING THE EARLIER COUNT. An earlier finding said five talos commands reach the secrets through `talos-paths`. Five import the module -- apply, bootstrap, health, kubeconfig and secrets-gen -- but only two reach `clusterSecretsSopsPath`: `talos-apply.command.code.ts:105` and `talos-secrets-gen.command.code.ts:67`. The other three take `clusterTalosconfigPath` or `clusterKubeconfigPath`, neither of which moved.\n\nTHE MOVE. `akasha/machines/clusters/pages/main.cluster.sops.yaml` and the file that was at `pages/cluster/main.cluster.sops.yaml` share sha256 dc4b06e79f55954cb48becb5c98b977115e28e85b328ae4ba080a26c64951db8, so the bytes are the same bytes. `clusterSecretsSopsPath('main')` answers a path `existsSync` says is there, while `clusterSecretsSopsPath('no-such-cluster')` answers one it says is not, so the reading discriminates.\n\nWHY SOPS IS UNAFFECTED. The three creation rules in the root `.sops.yaml` key on `\\.k8s-secret\\.sops\\.yaml$`, on a basename of `secrets.sops.yaml`, and on `[^/]+\\.sops\\.yaml$`. Old path and new path both match the third alone, so the recipient and the encryption are unchanged, and decryption reads the recipient out of the file rather than out of the path.\n\nNOT MEASURED. I did not run `sops decrypt` against the moved bundle, so I do not say from a run that it opens; I say only that nothing the path decides changed. Whoever next runs `akasha talos-apply` will settle it.",
} as const satisfies Finding
