import type { Finding } from "../finding.page-type.ts"

export const theIndexRefreshRebuiltWholeAndItsRefusalsAreDroppedEdges = {
  id: "01a068f6-2f88-7275-86c9-6ad0b11bcb23",
  pageTypeSlug: "finding",
  slug: "the-index-refresh-rebuilt-whole-and-its-refusals-are-dropped-edges",
  domainSlug: "domain/akasha-migration",
  claim:
    "`akasha index refresh` rebuilt the whole index at 14:14 today, after three runs were read as having never rebuilt since 06:42. All 385,469 files under `.git/data/index` were written at or after 14:14:38 and none is older. Its log says `.git/data/index was replaced whole` and counts 70,603 pages and 549,694 entries filed. The 5,240 `the index took less than the whole of it` lines refuse one relation entry each, not the rebuild. No lane's landed work was invisible for want of a rebuild.",
  evidence:
    "Measured 2026-09-03 by mtime rather than by exit code. `find .git/data/index -type f` counts 385,469; `-not -newermt '2026-09-03 14:00'` returns 0, so nothing in the index predates the run. The oldest file is 14:14:38.68 and `stamp.jsonl` was rewritten at 14:19 by later landings, so the index is also being kept up after the rebuild.\n\n" +
    "WHAT THE REFUSALS COST, with a control that fires. `relationIn` at `akasha/pages-system/indexes/index/relation/index-relation.index.code.ts:29-33` pushes the message and `continue`s, so a refused reference has no edge filed. Edges are keyed by the TARGET id, which is why probing the source id finds nothing for refused and unrefused pages alike and reads as a dead instrument. Keyed correctly: `arkendrithyst`, a story read with no book-series twin, has 505 chapters on disk and 505 edges filed. `azarinth-healer`, whose slug is held by both `book-series` and `story-read`, has 24 chapters and no relation directory at all under either twin's id. So the loss is total per colliding parent rather than partial.\n\n" +
    "THE POPULATION IS NOT WHAT THE TAIL OF THE LOG SUGGESTS. By lookup kind the 5,240 are: `part-of-slugs` 5,023, `locations` 125, `part-slugs` 40, `properties page-property-slug` 37, `draws-slug` 8, `domain-slug` 6, `assignment-slug` 1. Reading only the tail gives `part-slugs` and `properties page-property-slug`, which are 77 lines of 5,240. Those two kinds are also not two problems: the 13 distinct slugs under `properties page-property-slug` are exactly the 13 property entries among the 21 under `part-slugs`, one collision seen through two lookups.\n\n" +
    "WHY NAMING THE PAGE TYPE CANNOT REPAIR THE PROPERTY ONES. `part-slugs` already writes them qualified, as `text-property/genre`, and they refuse anyway. `addressIn` cuts at the first slash only, so the qualified form narrows to one page type and no further; `reaches` at `akasha/pages-system/indexes/reaching/reaching.module.code.ts:219-224` then calls `only`, which answers a page only where exactly one was found. Both colliding pages write into `identity/text-property/slug/genre.jsonl`, so no spelling settles it. The repair is to make one slug differ, which `story-genre`, `puzzle-themes` and `notification-link` already do in this repository: the `slug` is qualified while `propertySlug` and the reader-visible key remain bare, so no reader is touched.\n\n" +
    "TWO INSTRUMENTS THAT LOOKED CONTRADICTORY MEASURE DIFFERENT FIELDS. A census of `(pageTypeSlug, slug)` over 1,613 property files returns the same 13 the refusal log names, agreeing exactly. A census of `propertySlug` shared across differently-slugged pages returns 91, including `description`, `notes`, `statement`, `text`, `note`, `runs` and `images`. Neither is partial. A repeated `propertySlug` is legal and intended, being the reader's key; a repeated `slug` breaks the index, being the page's address. Overlap is only where a pair repeats both.",
} as const satisfies Finding
