import type { Finding } from "../finding.page-type.ts"

export const theSixHundredAndEightySevenOldDomainsAreOneDictionaryRatherThanSixHundredDomains = {
  id: "01a06558-53de-7b3a-8486-1305c89f13f4",
  pageTypeSlug: "finding",
  slug: "the-687-old-domains-are-one-dictionary-rather-than-687-akasha-domains",
  domainSlug: "domain/akasha-migration",
  claim:
    "`pages/domain` is a single hierarchical dictionary of every term this system gave a meaning to, not a set of 687 domains owed an akasha counterpart. 552 of the 687 hang off one root, `global`, whose own definition is `the domain every other sits inside`. 363 of the 687 carry a Definition and nothing else: a slug, a parent and one sentence. Migrating them one-for-one into `akasha/domain-system/domains` would multiply akasha's 51 domain pages elevenfold with vocabulary that akasha already carries on the page of the thing itself, because `page-type`, `page-property`, `module`, `workspace-package`, `command`, `code-check`, `invariant-kind`, `directive-kind`, `name-format` and `folder-shape` all extend `domain` and each carries its own definition, invariants and directives.",
  evidence:
    "Measured 2026-09-02 over the 687 `.md` files in `pages/domain`, parsed for frontmatter and body sections, against every `.ts` page under `akasha/` indexed by its `slug:` line.\n\nShape of the tree. 593 of the 687 name another old domain as parent; the remaining 94 name a page type, a value, a package or a person. Rooted, the corpus is 42 trees, and one holds 552 of them. Under `global` the eleven areas are domain-system 185, agent-harness 128, alan-harness 69, change-harness 58, products 53, infrastructure 24, pages-system 21, technology 10, and akasha-system, design-system and graph-system at one each.\n\nWhat is already carried. 72 of the 687 resolve to an akasha page of the same slug, and the kinds they resolve to are the point: 12 land as `domain`, 10 as `workspace-package`, 9 as `name-format`, 8 as `module`, 4 as `page-type`, 3 as `command`, 3 as `text-property`, and the rest one apiece across `claude-account`, `change-kind`, `code-check`, `invariant-kind`, `boolean-property`, `email-address-property`, `ios-app`, `ios-program`, `graph-node`, `readout-group` and four temper page types. Only 12 of the 72 became domains. The other 60 became the thing they were about.\n\nBody weight. Across all 687: 363 carry Definition alone, 217 Definition and Design, 34 Definition, Design and Intent, 24 Definition and Intent, and the remaining 49 spread across Condition, Principles and Rules. Of the 615 with no akasha counterpart by slug, 328 are Definition-only and 287 carry more.\n\nThe reading this supports. The 287 richer unmatched pages are where migration work is, because each carries a claim no akasha page states. The 328 definition-only unmatched pages are worth a decision per area rather than per page, and most of their areas belong to lanes other than the pages system: 40 under ops-cli, 20 under alan-harness-tracking-source, 11 under run-cost, 9 under ops-temper.\n\nWhat this did not measure: whether a concept is carried in akasha under a different slug. The instrument matches slugs, and `a-recreation-that-changes-grain-reads-as-unmigrated` records that shape of false negative. Seven meta domains were checked by hand against akasha and five were carried under other names, so the true carried count is above 72.",
} as const satisfies Finding
