import type { Finding } from "../finding.page-type.ts"

export const threeModulesAnswerWhenAlanWokeAndTwoOfThemGuess = {
  id: "01a0612e-d9b2-7458-a457-c3e8e8985358",
  pageTypeSlug: "finding",
  slug: "three-modules-answer-when-alan-woke-and-two-of-them-guess",
  domainSlug: "domain/alan-harness",
  claim:
    "Three modules answer when Alan woke and two guess: `readouts/session-readings.ts:194` and `tools/lib/wake-day.ts:81` fall back to 06:00 New York, where `@akasha/health-samples-day/wake-day-window` refuses. 94 of his 133 days recorded no wake, and the guess is over 30 minutes out on 40 of the 48 checkable days. It barely moves active calories, under 1 percent on 23 of 30, but moves plant grams over half on 2 of 21. Every day now states how it was spanned, so the guess is labelled not blanked.",
  evidence:
    "Measured 2026-09-02 over the 133 pages in `akasha/alan/wake-day/daily-trackings`. 48 hold a session titled sleep ending inside their own ESO day; 39 hold that and so does the day after, which a whole window needs. The earliest recorded wake is 2026-06-19 and `git log --all --diff-filter=A` over `*.wake-day.sessions.jsonl` finds none earlier, so the days before it recorded none rather than losing them in the move.\n\nHow far out, over the 48 checkable days: 8 within 30 minutes of 06:00, 5 within the hour, 15 by 1 to 2 hours, 15 by 2 to 4, 3 by 4 to 8, 2 by over 8. Active calories, over the 30 days both spans yield one: 23 under 1 percent, 4 by 1 to 5, 1 by 5 to 10, 1 by 10 to 25, 1 by 25 to 50, errors cancelling. Plant grams, over the 21 days either yields one: 19 identical, 2 by over 50 percent, food being a lump a boundary either cuts or does not.\n\nTwo stages of `runCommitPoints` write over the guess: `rollupActiveCaloriesForDay` lands `active-calories`, `rollupNutritionForDay` lands `nutrition-points`.\n\nThe call taken, on the `anchored-from-completion` precedent: a `spanned-from-day-boundary` boolean, decided once per day in the `runCommitPoints` day loop rather than by either rollup, and written false on the 39 as well as true on the 94. It recomputes nothing and says nothing about whether a figure is wrong; on most days it is right anyway.\n\nStill owed: reading the wake from somewhere that knows. That is the real answer for the 94 days, and it needs data that does not exist: nothing recorded sleep before 2026-06-19.\n\nThe repair is proved in production. `daily-tracking-points.service` invocation `bef1071ce1c8` ran 02:17:48 to 02:34:24, `Result=success`, `ExecMainStatus=0`, and stage 8 of 10 printed the module's own refusal count. Controlled three ways: the test fails against the stub, exit 1 on `the module exports no wakeDayWindowIn`; passes against the fix; and fails again with the fixture's sessions file gone, on precisely the assertion reading it.",
} as const satisfies Finding
