import type { Finding } from "../finding.page-type.ts"

export const threeRelationBehavioursWentWithTheMarkdownRelationChecker = {
  id: "01a06864-c80e-798f-be3c-b4247c4cdb48",
  pageTypeSlug: "finding",
  slug: "three-relation-behaviours-went-with-the-markdown-relation-checker",
  domainSlug: "workspace-package/pages-system",
  claim:
    "`page/relation/relation.ts` was ablated in 23df25da on a reading of its successors as carrying it, and the reading was too generous. Most of it did carry, into `pages-access/file-relation` and `indexes/reaching` and the `relation-resolves` code check. Three behaviours did not: address-pointing, what value a candidate page bears for a points mode other than slug, and the refusal that withholds a whole relation verdict when the sweep could not read every page. Nothing read the file, so nothing broke; what is lost is the statement of the gap, which this restores.",
  evidence:
    'The blob is 6643bacb88848e2a189793558791bb4754582e79, read back byte-identical against disk before the ablation and recoverable with `git cat-file blob`. It is also the parent of 23df25da at `page/relation/relation.ts`.\n\nAddress-pointing. The old `pointsBy` at :31 matched `/\\brelation(-(?:slug|seq|id|name|address))?\\b/` and mapped `-address` to a fourth mode. `akasha/pages-system/pages-access/file-relation/file-relation.module.code.ts:11` carries the same regex with the `address` arm absent, and :30 declares `RelationPoints = "id" | "seq" | "name"`. Qualified addressing survives as a form in `pages/address/page-address.module.code.ts`, whose `addressIn` answers kinds `id`, `qualified` and `bare`; what is gone is `relation-address` as a property type a page bears and is swept for.\n\nWhat a candidate bears. `borneBy` at :81 answered, for a points mode, which of a page\'s values a bearer sweep compares: the `id`, the `seq`, an address built from the page type slug and the slug, an arbitrary `slugProperty`, else the slug falling back to the file stem. The new side asks one question, `where: { slug: { is: named } }`, and `pages-access/file-write-values/file-write-values.module.code.ts:139` skips the rest outright with `if (relation.mayBeGone || relation.slugProperty !== null) continue`. So `points` is computed in akasha and only the slug mode is resolved.\n\nThe withheld verdict. `unread` at :205 refused with the count of pages under a relation that could not be read, naming up to ten, and said that no relation there is certified. That is the distinction between a sweep that found nothing and a sweep that could not look, and it is the shape `pages-system.workspace-package.ts` asks for under Answer Or Refuse. `reaches` in `indexes/reaching` refuses per value; the searches run here found nothing in akasha that withholds a relation verdict because its sweep was incomplete.',
} as const satisfies Finding
