import type { Finding } from "../finding.page-type.ts"

export const threeDemandTotalsStand = {
  id: "01a06555-9f3f-76ff-9cfa-25c348960d6d",
  pageTypeSlug: "finding",
  slug: "three-demand-totals-stand",
  domainSlug: "domain/all-about-alan",
  claim:
    "The solar thread carries three unreconciled annual-demand roll-ups and two unreconciled all-in costs, and the file that notices calls both valid rather than choosing. `energy-demand.md` heads 52,000 / 70,000 / 92,000 kWh a year; `totals.md` rolls the same sub-files to 77,950 and 94,400; `sizing/demand.md` plans against 48,000 / 73,000 / 87,000. On cost, `sizing.md` heads ~$172,000 and `cost.md` ~$209,000 for the same case.",
  evidence:
    'Read 2026-08-16 across the 41 files of `all-about-alan/projects/solar-power`.\n\nThe three roll-ups. `energy-demand.md`: "Low … **~52,000** … Nominal … **~70,000** … High … **~92,000**." `energy-demand/totals.md`: "**Nominal: ~78,000 kWh/yr**", "**High: ~94,000 kWh/yr**", from subtotals "**77,950**" and "**94,400**", with its own monthly table totalling "**76,655**". `sizing/demand.md`: "**~48,500**", "**~72,850**" rounded to "**73,000 kWh/yr** as the planning number", "**~87,200**".\n\n`sizing/demand.md` reconciles only against `totals.md` — "Δ | −5,000 (−6%) | −7,400 (−8%)" — never against `energy-demand.md`\'s 52/70/92. Components disagree too: the EVs are 11,000 in the upper two files and 6,200/7,400 in the third; `computers.md` sets "Planning value used in totals.md: 30,000 kWh/yr" then "Round up to 34,000 if heavy is more accurate".\n\nThe two costs. `sizing.md`: "**Pre-ITC total** | **~$172,000**". `sizing/cost.md`, same case: "**~$209,000**", with its own note: "that version assumed no supplement structure and a smaller contingency … Both are valid bid-anchor brackets; the bid stage will resolve which one fits the measured roof." `sizing/recommendation.md` quotes a third pair, "~$200,000 … or ~$170k".\n\nThe unanswered loads. `lights-and-plugs.md`: "Re-asks to put in front of Alan before finalizing: hot tub, home lab, well/irrigation, humidifier. Any \'yes\' materially changes system sizing", sizing irrigation at "~600 kWh/yr if present" and a steam humidifier at "~600–1,500 kWh/yr". `scope.md` answers the hot tub, the home lab and the well, and names neither of the other two. `sizing/demand.md`: "| Steam humidifier | Not flagged in scope; default out | −0 |", with irrigation omitted entirely.\n\nNot measured: I did not re-derive any roll-up from its components, so I report that the headlines differ and by how much, not which is right. I have no record of anyone putting the two loads to Alan beyond these files.',
} as const satisfies Finding
