import type { Finding } from "../finding.page-type.ts"

export const twoThrowingExerciseWritersDiedWithTheirFile = {
  id: "01a06865-c36f-7b3d-a0cb-579da4d8d263",
  pageTypeSlug: "finding",
  slug: "two-throwing-exercise-writers-died-with-their-file",
  domainSlug: "domain/akasha-migration",
  claim:
    "`createPage` and `patchPage` were ablated with `collections/exercises/src/pages/access.ts` and have no akasha counterpart. Both did nothing but throw, so no behaviour was lost, but seven commands under `tools/commands/exercise/` still import them and now import a file that is not there. The working file-write road already stands at `tools/lib/page-write.ts` and one sibling command already takes it.",
  evidence:
    "Measured 2026-09-03 while carrying the exercise collection's code into `akasha/alan/fitness/exercise-access/`.\n\nEvery other export of `access.ts` stands in akasha, adapted, in `akasha/alan/fitness/exercise-access/exercise-rows/exercise-rows.module.code.ts`, landed by a sibling lane: `Json` as `Value`, `Page` as `Row`, `PageCondition` as `Test`, `PageOrder` as `Ordering`, `PageQuery` as `Asking`, `kebabKey` as `dashed`, `camelKey` as `humped`, `pageOfRow` as `rowOf`, `PagesRead` as `Rows`, `getPages` as `rowsFor` and `getPage` as `rowFor`. `composedFor` keeps its name. `pageOf` from `pages/page.ts` had no caller anywhere and went with it.\n\n`AskPages` is not carried and needs no carrying: it existed so a reader could bind these queries to the checkout rather than to the remote index, and `rowsFor` now takes `askComposed` from `@tools/lib/page-query-client` outright, which is the local half.\n\nWhat the two writers did: each threw an Error naming `the page store refuses every keyed write`. Neither reached a store. The finding `ops-exercise-is-down-in-both-halves-and-refuses-loudly` already records that both have thrown since `071b6884d6` on 2026-09-01, so nothing that worked stopped working here.\n\nThe seven callers whose import now dangles: `tools/commands/exercise/add.ts:21`, `constraint-set.ts:12`, `log-activity.ts:6`, `log-set.ts:6`, `schedule-create.ts:4`, `session-finish.ts:6` and `session-start.ts:7`. `tools/commands/exercise/equipment-set.ts:10` is the sibling already off this road; it takes `writePage` and `patchPage` from `tools/lib/page-write.ts`, which lands a body at a path.\n\nThe call taken: the two were not carried, because carrying a function whose whole body is a throw would put dead code in a sibling's module and make the write road look like it exists. Restoring the writes means pointing those seven at `tools/lib/page-write.ts`, which is a change to what those commands do rather than where their code lives.",
} as const satisfies Finding
