import type { Finding } from "../finding.page-type.ts"

export const wholeFileHashingIsBlindToADuplicateGivenAFreshIdAndSlug = {
  id: "01a06769-dbe1-734f-bd0f-8c4c34983f90",
  pageTypeSlug: "finding",
  slug: "whole-file-hashing-is-blind-to-a-duplicate-given-a-fresh-id-and-slug",
  domainSlug: "domain/akasha-migration",
  claim:
    "Hashing whole files finds content re-filed under a different stem and finds nothing when it is re-filed fresh, the shape a migration makes. The body-only arm must take out the export name as well as id and slug, since a page is one exported object named for its slug. And a seeded control proves an instrument only where the seed was built apart from the instrument's own idea of the fault: mine shared the blindness, so it could only agree, and the arm certified itself.",
  evidence:
    'Measured 2026-09-03 over the alert, refusal and domain families, and corrected after publishing.\n\nTHE DEMONSTRATION. A landed alert page was copied under a new id, a new slug, and the new export name its slug forces. Whole files answer two digests; bodies with all three taken out answer one. A migration re-mints ids and re-slugs pages, so a migration is what makes that copy.\n\nTHE STRIP TAKES THE EXPORT NAME TOO:\n\n  .replace(/^\\s*(id|slug):\\s*"[^"]*",?\\s*$/gm, "")\n  .replace(/^export const \\w+ = \\{/m, "export const NAME = {")\n\nA page is one exported object named for its slug, so a page re-filed under a new slug carries a new export name, and taking out id and slug alone leaves that third difference.\n\nA SEEDED CONTROL PROVES AN INSTRUMENT ONLY WHERE THE SEED WAS BUILT APART FROM THE INSTRUMENT\'S OWN IDEA OF THE FAULT. This is the deeper reading and it is not about export names at all. My first strip took out id and slug. The copy I seeded it with changed id and slug and kept the export name. Seed and instrument held one idea of what a duplicate is, so the seed could only ever agree, and the arm certified itself. Seeding diligently is therefore not enough: an instrument built from a wrong idea of the fault gets seeded from that same idea by the same hand. A seed has to come from the shape the world produces rather than the shape the checker looks for.\n\nWHAT THAT COST HERE. My first reading ran the blind strip and was published as proven. Read again on the strip above: 65 alert, 27 refusal and 169 domain bodies, every one distinct. The answers held and were unproven when published, and those are different things.\n\nTHE FIRST ARM IS NOT THE WEAK ONE. Over `pages/temper-inventory-chunk` it found duplicates outright, 458 files against 454 digests. The arms add to one another and none implies another.',
} as const satisfies Finding
