import type { TemperSet } from "akasha/temper/catalog/gear/temper-set/temper-set.page-type.types.ts"

export const perfectedCausticArrow = {
  id: "019e6484-5fb9-708f-9d5b-aad9f2a2071b",
  type: "page-type/temper-set",
  slug: "perfected-caustic-arrow",
  title: "Perfected Caustic Arrow",
  key: "perfected-caustic-arrow",
  esoSetId: 531,
  setWayshrines: [270, 270, 270],
  setVeteran: true,
  setTypeId: 1,
  setNameZh: "完美腐蚀箭矢",
  setNameRu: "Совершенная разъедающая стрела",
  setNameFr: "Flèche caustique perfectionnée",
  setNameEs: "Flecha cáustica perfeccionada",
  setNameDe: "Perfektionierter beißender Pfeil",
  setDropZones: [635, 888, 888],
  setDropMechanics: [5, 5],
  setDlcId: 0,
  itemBrowserSources: ["635"],
  itemBrowserPlaceKinds: [5],
  itemBrowserItemId: 166094,
  esoItemIds: [166060],
  esoEquipTypes: ["EQUIP_TYPE_TWO_HAND"],
  esoWeaponTypes: ["WEAPONTYPE_BOW"],
  category: "temper-set-category/arena",
  valid: ["bow"],
  bonuses: "jsonl",
  icons: "jsonl",
} as const satisfies TemperSet
