import type { Finding } from "akasha/domain/finding/finding.page-type.types.ts"

export const aManifestThatOnlyLostAFieldWasAppliedByNoDeploy = {
  id: "01a0c210-4b77-7e19-8c52-3f0a6d79b415",
  type: "page-type/finding",
  slug: "a-manifest-that-only-lost-a-field-was-applied-by-no-deploy",
  domain: "domain/cluster",
  claim:
    "Until `b33fad78678`, a deploy whose manifest only took a field away applied nothing and said so in words that read like success. `putUp` ran only where `kubectl diff` reported a difference, that diff ran client-side, and a client-side three-way merge cannot see a field the manifest no longer states, because the live object carries no `last-applied-configuration` annotation to compare against. The deploy printed `manifest ... stands` and went on to build and roll out, so a reader watching the output had nothing to distinguish it from a deploy that had no work to do. Every live workload whose manifest lost a field between the diff gate landing and that mend may still carry the field its page no longer states, and each heals only when that workload is deployed again.",
  evidence:
    "Four deploys of `temper-web` in a row removed `NEXT_PUBLIC_SUPABASE_URL`, `NEXT_PUBLIC_SUPABASE_COOKIE_DOMAIN`, `SUPABASE_INTERNAL_URL` and `SUPABASE_JWT_SECRET` from `temper/web/manifests/temper-web-manifests.manifest.code.ts`, each reported `manifest ... web-deployment.generated.yaml stands`, and the live Deployment kept all four.\n\nMeasured rather than reasoned: against the live object `kubectl diff` exited 0 while `kubectl diff --server-side` exited 1 and printed exactly the four removed entries; against an unchanged copy of that same object `--server-side` exited 0, so it raises no false difference. The Deployment's only `Apply` manager is server-side `kubectl`, which writes no `last-applied-configuration`.\n\nThe same silence hid the same removal on three other sites. After `b33fad78678` gave the diff `--server-side --force-conflicts`, redeploying alanwalton-web said `differs`, applied, and left the pod's environment as `NODE_ENV AKASHA_ROOT HOST PORT PAGE_WRITER HANDOVER_SIGNING_KEY` and the four seaweedfs entries, with no supabase entry. Before that redeploy the same Deployment carried `NEXT_PUBLIC_SUPABASE_URL`, `SUPABASE_URL`, `NEXT_PUBLIC_SUPABASE_COOKIE_DOMAIN` and `SUPABASE_JWT_SECRET`.\n\nWhat is not measured is how far the drift reaches. Nothing here sweeps the other workloads, so how many carry a field their page dropped is unknown; a sweep would be `kubectl diff --server-side` against each workload's emitted manifest.",
} as const satisfies Finding
