import type { Finding } from "akasha/domain/finding/finding.page-type.types.ts"

export const aMoveLeavesTheReferencesFileTrackedAtThePathThePageLeft = {
  id: "01a0a3cc-c425-76ae-a832-621af9a4ce9d",
  type: "finding",
  slug: "a-move-leaves-the-references-file-tracked-at-the-path-the-page-left",
  domain: "page-type/change",
  claim:
    "A landing that moves a page writes the page's `referenced-by` file at the new path and leaves the same file tracked at the old one, in the very commit that made the move. Nothing on disk sits at the old path, so git reads the landing as having deleted a file nobody deleted, and every `git status` after it carries that deletion until someone lands a change naming the vacated path. The commit is not wrong about the pages; it is wrong about one generated file per page moved, and it is wrong in the direction that looks like work in progress.",
  evidence:
    "Read on 2026-09-15 over the tree the ryn-file-structure renames left. `git ls-files --deleted` answers 165 paths and every one of them is a `.referenced-by.jsonl`. Grouped by the landing that vacated the path: 79 under `temper/catalog`, 28 under `infrastructure/machines`, 28 under `alan/collection`, 10 under `change/mechanical`, 7 under `product/games`, 5 under `infrastructure/container-image`, 4 under `design/games`, 3 under `infrastructure/cluster` and 1 under `page/type`.\n\nOne case whole. `93723bcf9e9` folded the wrapping domain off `move-folder` and carried the page from `change/mechanical/folder/move/move-folder/` to `change/mechanical/folder/move-folder/`. After it, `move-folder.change-mechanical-folder.referenced-by.jsonl` exists on disk only at the new path, and `git cat-file -e HEAD:change/mechanical/folder/move/move-folder/move-folder.change-mechanical-folder.referenced-by.jsonl` answers that the old path is in `HEAD` too. The same landing put the file in two places and the disk in one.\n\nThe same shape from a plain rename rather than a fold. `f4046d7349f` renamed `machines` to `machine`. `infrastructure/machine/computer/properties/brand.select-property.referenced-by.jsonl` is on disk; `infrastructure/machines/computer/properties/brand.select-property.referenced-by.jsonl` is tracked and absent. So this is not a fold's doing; it is what a move does.\n\nWhat it is not. The `util-hashing` fold in `df053b4b8ae` left nothing behind: `git ls-files util/hashing/` answers with no path at all. So the fault does not follow every move, and which moves it follows is the open question a mend has to answer first.\n\nWhy it reads as somebody's unfinished work. The residue is a deletion in `git status` that no agent made and no agent can explain, on a file class that is generated and therefore easy to dismiss. An agent meeting it has three readings available — another agent is mid-rename, the tree is corrupt, or the file was meant to go — and the true one, that the landing wrote it twice, is not among the ones that come to mind.\n\nThe condition a mend would meet: a landing that moves a page leaves the page's generated files at the path the page landed at and nowhere else, so `git ls-files --deleted` after that landing answers with nothing the landing made.",
} as const satisfies Finding
