import type { Finding } from "akasha/domain/finding/finding.page-type.types.ts"

export const aPageTypeSlugBorrowedAsATestFixtureOutlivesThePageType = {
  id: "01a0c4e7-139b-79a7-ab5e-b08e8234f35e",
  type: "page-type/finding",
  slug: "a-page-type-slug-borrowed-as-a-test-fixture-outlives-the-page-type",
  domain: "page-type/change",
  claim:
    "A page type's slug is written as a plain string wherever a test needs a plausible page path, and `rename-page-type` reaches none of those strings. The test goes on passing, because a fixture is self-consistent: a test that builds `one.eso-addon.ts` and asserts what a reader makes of it passes whether or not `eso-addon` is a page type anywhere. So a rename leaves behind a set of green tests documenting a page type that no longer exists, in files with nothing to do with the domain that renamed it. The next agent reading `extension-carrying` learns a page-type slug no page has carried since the rename, and nothing in the test says it is a ghost.",
  evidence:
    '`eso-addon` was renamed to `temper-addon`, and the rename reached every page file: every add-on page ends `.temper-addon.ts`. It reached no test fixture. Four test files unrelated to add-ons were left spelling the old slug, and every one of them still passed; commit `454c544afd6116b4ff29701f666d628afeaa8807` repointed them and changed nothing else.\n\n`page/index/modules/extension-carrying/extension-carrying.module.test.ts` built `const OWNER = "temper/one-addon/one-addon.eso-addon.ts"`, asserted over `{ pageTypeSlug: "eso-addon", path: at, id: "one", within: null }`, and called `endingOf("temper/one-addon/one.eso-addon.ts")`. It is a test of how an extension is carried; the page type it borrowed is incidental to it.\n\n`check/code/pages/file-length/file-length.check-code.decision.test.ts` built `const BINDINGS = "akasha/one.eso-addon.bindings.xml"`.\n\n`command/pages/measure/modules/gathering/measure-gathering.module.test.ts` built `const PAGE = "temper/held-addon/held-addon.eso-addon.ts"` with two `.eso-addon.entries.uncommitted.jsonl` paths beside it, and `command/pages/measure/test/measure-test.command.test.ts` built the same stem.\n\nWhat makes it easy to miss: nothing refuses, nothing warns, and the four files are reached by no search an agent renaming a page type would think to run. Searching the repository for the old slug answers add-on source comments, ambient declaration paths under `temper/eso/type/eso-addon-list/`, and the in-game sense of the word, all of which are about ESO add-ons rather than about the page type. The four stale fixtures sat inside that noise.\n\nThe condition a mend would meet: a page-type rename either respells the slug wherever a test writes it as a path or a `pageTypeSlug`, or names every file holding the old slug so an agent reads them and decides.',
} as const satisfies Finding
