import type { Finding } from "akasha/domain/finding/finding.page-type.types.ts"

export const federalEscalationSignalsUndefined = {
  id: "01a06555-9f3e-768a-b74c-282f02f8e83b",
  type: "page-type/finding",
  slug: "federal-escalation-signals-undefined",
  domain: "alan-book/all-about-alan",
  claim:
    "Alan's involuntary federal dependencies cannot be exited while he lives in this country, so watching them is the whole of the strategy, and what he watches for is defined only as the grade getting worse. No signal is named that would tell him a grade has turned: nothing on patterns in IRS audit targeting, nothing on passports being denied along political lines beyond the fact that they are, nothing on Selective Service rules changing, nothing on expatriation tax law moving. Escalation on any of those re-opens the whole US-citizenship layer rather than one entry, and no page names one.",
  evidence:
    'Read across `alan/book/pages/all-about-alan/topic/pages/` and `.../question/pages/`.\n\nThe dependencies are worked in full. `where-the-government-touches-me` grades them one by one — "The tax office grades D and the passport office D. Passports get denied along political lines, the appeal is opaque, the fees climb, and the backlog gets used as leverage" — and closes "Registering for the draft is the worst of these." `the-grade-for-something-i-cannot-leave` takes Selective Service as the archetype: "It is compulsory for men from eighteen to twenty-five whatever they believe, no conscientious objection is heard at the point of registering, and leaving the country does not undo having registered. I am on it already. Joseph reaches eighteen in time." `no-exit-against-an-expensive-exit` names the set: "Federal tax, the draft registry, Utah income tax while I live here. The only escape is a different jurisdiction, and for the registry not even that."\n\nThe watch is where it thins out. The protocol on `the-grade-for-something-i-cannot-leave` is three items, the last of them "Watch for the grade getting worse." Nothing says what getting worse would look like, or how he would learn of it. `why-the-tax-office-is-not-an-f` names "enforcement that has started to follow politics" without a trigger behind it, and prices the exit — "Leaving the country would do it, and part of the obligation would follow me out. That is expensive rather than impossible, and the price is one I am not willing to pay now" — with no arithmetic under the price. `how-likely-they-are-to-get-worse` is the generic machinery and names no federal signal.\n\nNo question asks for the signals either. `who-builds-the-watcher-on-filings` asks for a watcher on companies changing hands, not on legislatures or agencies.\n\nNot measured: the signal list in this claim is my own naming of what the exposure would turn on, not a list Alan has given. I checked no bill, no agency practice, and no expatriation rule.',
} as const satisfies Finding
