import type { Finding } from "akasha/domain/finding/finding.page-type.types.ts"

export const folderMatchesAShapeSpendsItsWholeCeilingOnEveryRunNow = {
  id: "01a0c4fc-54ff-73e2-8ff5-8c9631097c04",
  type: "page-type/finding",
  slug: "folder-matches-a-shape-spends-its-whole-ceiling-on-every-run-now",
  domain: "domain/check",
  claim:
    "folder-matches-a-shape spends 117 to 121 processor seconds on every run against the 120 its page states, so it sits on its ceiling rather than under it, and the watchdog kills it at twice that about once in three rounds. On 2026-09-21 it was killed four times. The wall of each run sits within a second of its processor seconds, so no round is crowding it and the cost is the check's own. Two days earlier the same check measured 63.9 on the same node, so what it spends has roughly doubled while the repository it walks has not. This is no longer the contention this domain recorded on 2026-09-19: a run alone would be refused for its ceiling just as a run in a full round is killed for twice it. What the check judges is lost from every third audit, and folder shape is judged by nothing else.",
  evidence:
    "Read on 2026-09-21 out of the audit cost rows beside check/code/pages/folder-matches-a-shape/folder-matches-a-shape.check-code.audit.logs.uncommitted.jsonl, every row on node-06.\n\nThe evening runs. At 16:27:50 cpu 120.7 over wall 119.9. At 16:40:07 cpu 240.5 over wall 162.8, unrun. At 16:47:34 cpu 118.7 over wall 119.4. At 16:54:12 cpu 117.6 over wall 116.6. At 17:11:45 cpu 118.8 over wall 118.3. At 17:15:18 cpu 240.5 over wall 239.9, unrun. Six runs, two of them killed, and the four that finished spent between 117.6 and 120.7 against a ceiling of 120. The run at 16:27 finished over the ceiling and would have been refused for it.\n\nWall against processor seconds. On the four runs that finished, wall and processor seconds differ by at most 1.0 second, and on the kill at 17:15 by 0.6. A run waiting on a crowded machine spends wall it does not spend processor time, as this check did on 2026-09-19 when its wall first went beyond its processor seconds at 67.3 against 66.0. Nothing here is waiting.\n\nWhat it cost before. At 2026-09-19T20:29:16 the same check on node-06 spent 63.9 processor seconds over 60.0 of wall, with readCalls 649432. That run was made by `akasha audit --check folder-matches-a-shape`, which narrows the round to one check. Through 2026-09-20 it ran 112.4, 113.6 and 86.1, and was killed once. Through the afternoon of 2026-09-21 it ran 86.6, 91.9, 101.0, 89.7, 69.3, 86.2 and 119.5, and was killed twice more.\n\nWhat the ceiling does either way. The check's page states audit maxCpuSeconds 120. `ranOver` in check/modules/run-ceiling/run-ceiling.module.code.ts refuses a run whose seconds go beyond that ceiling, and `watching` in code/spawning/modules/running/running.module.code.ts kills one that reaches twice it. At 117 to 121 the check is at the boundary of the first and one bad round from the second, so it answers either a refusal naming its own page or nothing at all.\n\nWhat the reads say. Over ten runs on 2026-09-21 the check made between 648,878 and 653,485 read calls over 1.32 to 1.36 GB, a spread under one percent, while its processor seconds went from 69.3 to 126.7. Processor time over read calls went from 106 microseconds each to 195 across those same hours. At 2026-09-19T20:29 it made 649,432 read calls for 63.9 seconds, which is 98 microseconds each. So the check makes the same calls over the same bytes, and each one now costs about twice what it cost two days ago. The wall sits level with the processor seconds throughout, so none of that is waiting.\n\nWhat is unmeasured. What became dearer is under the check rather than in it, and nothing here names what. The tree it walks held 26,423 folders on 2026-09-19 and its biggest folders were unchanged from that morning, so this is not folders arriving. Nothing here has profiled the check, and no commit has been shown to be the step.",
} as const satisfies Finding
