import type { Finding } from "akasha/domain/finding/finding.page-type.types.ts"

export const noCheckCompilesTheLuaRuntimeHelpersSoTwoUndeclaredTypesGoUnseen = {
  id: "01a0ca12-34c2-736d-8d3b-018d9c86afaf",
  type: "page-type/finding",
  slug: "no-check-compiles-the-lua-runtime-helpers-so-two-undeclared-types-go-unseen",
  domain: "domain/check",
  claim:
    'Four files under `design/language/lua-compiler/lualib-helper` name two types nothing declares. `__TS__Class` in `class-table` answers a `LuaClass` and holds one; `__TS__ClassExtends` in `class-extends` takes two of them; `__TS__New` in `new-instance` takes one; `__TS__InstanceOf` in `instance-of` takes a `LuaClassInstance` and a `LuaClass`. Neither name is declared anywhere in the checkout or under `node_modules`. Nothing says so, because the compiler check never sees those files: `claimedIn` in `check/code/pages/typecheck/typecheck.check-code.decision.code.ts` builds a matcher from the `include` list of each Lua runtime library\'s config, and `foundIn` hands the compiler only the paths that matcher rejects. `design/language/lua-compiler/lualib/tsconfig.json` claims `"../lualib-helper/**/*.lualib-helper.code.ts"`, which is every one of them.',
  evidence:
    'Measured in this checkout at `e8370e394cc`. A grep for `LuaClassInstance` and for `LuaClass` as a whole word over `*.ts`, `*.tsx` and `*.d.ts` answers six lines, every one of them a use and every one in the four files named: `export function __TS__Class(): LuaClass {` and `const c: LuaClass = { prototype: {} }` in `class-table`, `export function __TS__ClassExtends(this: void, target: LuaClass, base: LuaClass): undefined {` in `class-extends`, `export function __TS__New(this: void, target: LuaClass, ...args: any[]): any {` in `new-instance`, and `export function __TS__InstanceOf(this: void, obj: LuaClassInstance, classTbl: LuaClass): boolean {` with `let luaClass: LuaClass | undefined = obj.constructor` in `instance-of`. A second grep, run with `--no-ignore` so the ignored folder is read, finds `LuaClassInstance` nowhere under `node_modules` and finds no `interface LuaClass`, `type LuaClass` or `declare` of that name there either.\n\nThe exclusion is read rather than run. `design/language/lua-compiler/lualib/tsconfig.json` and `tsconfig.lua50.json` beside it both carry `"../lualib-helper/**/*.lualib-helper.code.ts"` in `include`, and `design/language/lua-compiler/lualib/lualib.lua-runtime-library.ts` is the `lua-runtime-library` page that makes the check read them: `claimedIn` walks `librariesIn`, opens `tsconfig.json` and `tsconfig.lua50.json` beside each library page, and turns every `include` entry into a regular expression through `matching`; `foundIn` then keeps only `reached.filter((one) => !claimed(one))`. I did not run the typecheck over the four files, so the consequence is established from that code rather than from a refusal I watched fail to arrive.\n\nWhat I did not establish: what `LuaClass` and `LuaClassInstance` were meant to be, whether a declaration for them was lost or never written, and whether the four helpers are broken in the Lua they compile to. The Lua compiler builds these files by its own run, which this finding did not exercise.',
} as const satisfies Finding
