import type { Finding } from "akasha/domain/finding/finding.page-type.types.ts"

export const threeDemandTotalsStand = {
  id: "01a06555-9f3f-76ff-9cfa-25c348960d6d",
  type: "page-type/finding",
  slug: "three-demand-totals-stand",
  domain: "alan-book/my-projects",
  claim:
    "The solar thread carries three unreconciled annual-demand roll-ups and two unreconciled all-in costs, and the section that notices calls both costs valid rather than choosing. `energy-demand` heads 52,000 / 70,000 / 92,000 kWh a year; `totals` rolls the same sub-sections to 77,950 and 94,400; `demand` plans against 48,000 / 73,000 / 87,000. On cost, `sizing` heads ~$132,000 pre-ITC and `cost` ~$166,000 for the same nominal case, and `recommendation` quotes a third pair.",
  evidence:
    'Read across the solar thread of `alan/book/pages/my-projects/sections/`, whose sections sit under `book-section/my-projects/solar-power`.\n\nThe three roll-ups. `energy-demand`: "Low … **~52,000** … Nominal … **~70,000** … High … **~92,000**." `totals`: "**Nominal: ~78,000 kWh/yr**", "**High: ~94,000 kWh/yr**", from subtotals "**77,950**" and "**94,400**", with its own monthly table totalling "**76,655**". `demand`: "**~48,500**", "**~72,850**" rounded to "**73,000 kWh/yr** as the planning number", "**~87,200**".\n\n`demand` reconciles only against `totals` — "Δ | −5,000 (−6%) | −7,400 (−8%)" — never against `energy-demand`\'s 52/70/92. Components disagree too: the EVs are 11,000 in the upper two and 6,200/7,400 in the third; `computers` sets "Planning value used in totals.md: 30,000 kWh/yr" then "Round up to 34,000 if heavy is more accurate".\n\nThe two costs. `sizing`: "**Pre-ITC total** | **~$132,000**". `cost`, nominal column: "**~$166,000**", with its own note: "The summary in the top-level sizing.md uses a tighter table at $132k pre-ITC — that version assumes no supplement structure and a smaller contingency … Both are valid bid-anchor brackets; the bid stage will resolve which one fits the measured roof." `recommendation` quotes a third pair, "**~$166,000** (with one supplement structure) or ~$142k (no supplement)".\n\nThe unanswered loads. `lights-and-plugs`: "Re-asks to put in front of Alan before finalizing: hot tub, home lab, well/irrigation, humidifier. Any \'yes\' materially changes system sizing", sizing irrigation at "~600 kWh/yr if present" and a steam humidifier at "~600–1,500 kWh/yr". `scope` answers the hot tub, the home lab and the well, and names neither of the other two. `demand`: "| Steam humidifier | Not flagged in scope; default out | −0 |", with irrigation omitted entirely.\n\nNot measured: I did not re-derive any roll-up from its components, so I report that the headlines differ and by how much, not which is right. I have no record of anyone putting the two loads to Alan beyond these sections.',
} as const satisfies Finding
