import type { Finding } from "akasha/domain/finding/finding.page-type.types.ts"

export const turningOnASplitGitIndexEmptiedTheIndexOfThisCheckout = {
  id: "01a0aa60-d151-70fc-9548-93dadceb0ec4",
  type: "page-type/finding",
  slug: "turning-on-a-split-git-index-emptied-the-index-of-this-checkout",
  domain: "domain/git",
  claim:
    "A split git index halves what a landing spends writing git and takes `git status` in this checkout from 477ms to 9ms. Setting `core.splitIndex` on the checkout and letting the next write split the index emptied that index instead: 352,306 entries went to none, and every check that reads the tree refused the folder it was handed. No commit was harmed, because a landing builds its tree from the tree at HEAD rather than from the index. The setting is off, and the way to turn it on safely is not known.",
  evidence:
    "Measured on 2026-09-16 against this checkout, whose index holds 352,306 entries in 58MiB.\n\nIn a linked worktree, `git update-index --split-index` converted the index and left it at 3.1MiB beside a 55MiB `sharedindex.*`. Staging one path went from 63ms to 14ms, and `git status --porcelain -uno` from 477ms to 9ms. Three hundred stages over three hundred distinct paths held at mean 14.4ms, p90 14.9ms, max 20.9ms, so the shared index was not rewritten in that window. Index version 4 shrank the file from 58MiB to 34MiB and made writes no faster at all, 63ms to 65ms, so the cost is per-entry work rather than bytes.\n\nIn a `--shared` clone of this repository, akasha's own `committed` was called five times. Without the split it took 150.0ms and 146.4ms; with `git update-index --split-index` run first it took 76.1ms, 71.8ms and 72.0ms. The working tree came back clean each time and `git fsck --connectivity-only` was clean.\n\nWhat was not tried in a worktree was the route taken on the checkout: `git config core.splitIndex true` alone, leaving the next index write to do the conversion. The next write left `.git/index` at 7.2MiB and `sharedindex.0000000000000000000000000000000000000000` at 168 bytes, and `git ls-files` answered nothing. `folder-matches-a-shape` then refused every folder it was handed, which is what a check reading an empty tree says. `git read-tree HEAD` put the index back at 352,427 entries with nothing staged, in 343ms.\n\nThe difference between the two routes is that `--split-index` converts an index that is already loaded, and the config leaves the conversion to whatever writes next, which here was `git update-index --index-info` naming a handful of paths. Which of those is at fault is not established.",
} as const satisfies Finding
