import type { TemperSet } from "akasha/temper/catalog/gear/temper-set/temper-set.page-type.types.ts"

export const forceOverflow = {
  id: "019e6484-5fae-721a-b197-2f6cf55360c4",
  type: "page-type/temper-set",
  slug: "force-overflow",
  title: "Force Overflow",
  key: "force-overflow",
  esoSetId: 562,
  esoItemIds: [169891],
  esoEquipTypes: ["EQUIP_TYPE_TWO_HAND"],
  esoWeaponTypes: ["WEAPONTYPE_HEALING_STAFF"],
  setWayshrines: [457, 457, 457],
  setTypeId: 1,
  setNameZh: "力量溢流",
  setNameRu: "Переполняющая сила",
  setNameFr: "Le Débordement de force",
  setNameEs: "Desbordamiento de fuerza",
  setNameDe: "Machtüberschuss",
  setDropZones: [1227, 1207, 1207],
  setDropMechanics: [5, 5],
  setDlcId: 20,
  itemBrowserSources: ["1227"],
  itemBrowserPlaceKinds: [5],
  itemBrowserItemId: 169908,
  category: "temper-set-category/arena",
  valid: ["restoration-staff"],
  bonuses: "jsonl",
  icons: "jsonl",
} as const satisfies TemperSet
