import type { TemperLoreBook } from "akasha/temper/catalog/pursuit/temper-lore-collection/temper-lore-book/temper-lore-book.page-type.types.ts"

export const aetherialFragments = {
  id: "01a0d5f3-3fda-7918-9f8c-88f1b2d6c218",
  type: "page-type/temper-lore-book",
  slug: "aetherial-fragments",
  title: "Aetherial Fragments",
  collection: "temper-lore-collection/lore-and-culture",
  esoBookId: 1161,
  bookIndex: 51,
  charted: true,
  onBookshelves: true,
  mapCounts: [
    { mapId: 7, mapCount: 10 },
    { mapId: 10, mapCount: 8 },
    { mapId: 13, mapCount: 14 },
    { mapId: 16, mapCount: 9 },
    { mapId: 20, mapCount: 8 },
    { mapId: 26, mapCount: 11 },
    { mapId: 27, mapCount: 9 },
    { mapId: 30, mapCount: 3 },
    { mapId: 61, mapCount: 1 },
    { mapId: 125, mapCount: 8 },
    { mapId: 143, mapCount: 25 },
    { mapId: 255, mapCount: 58 },
    { mapId: 256, mapCount: 34 },
    { mapId: 439, mapCount: 1 },
    { mapId: 660, mapCount: 7 },
    { mapId: 667, mapCount: 1 },
    { mapId: 994, mapCount: 11 },
    { mapId: 1006, mapCount: 6 },
    { mapId: 1060, mapCount: 32 },
    { mapId: 1126, mapCount: 21 },
    { mapId: 1349, mapCount: 34 },
    { mapId: 1429, mapCount: 12 },
  ],
} as const satisfies TemperLoreBook
