import { achievementName } from "akasha/temper/addon/pages/world/navigation/modules/destinations-data-runtime/destinations-data-runtime.module.code.ts"
import "akasha/temper/eso/type/eso-globals/eso-globals.type-declaration.d.ts"

export const SETTINGS_STRINGS_00: Record<string, string> = {
  SI_TEMPER_DESTINATIONS_COMMANDS: "Destinations コマンド一覧:",
  SI_TEMPER_DESTINATIONS_COMMAND_DHLP:
    "/dhlp (Destinations ヘルプ) : あなたがちょうど使っています ;)",
  SI_TEMPER_DESTINATIONS_COMMAND_DSET:
    "/dset (Destinations 設定) : Destinations の設定ウィンドウを開く",
  SI_TEMPER_DESTINATIONS_FILTER_AYLEID: "(Dest) アイレイドの井戸",
  SI_TEMPER_DESTINATIONS_FILTER_BORDER: "(Dest) クラグローンの境界線",
  SI_TEMPER_DESTINATIONS_FILTER_BRAWL: "(Dest) " + zo_strformat(achievementName(1247)),
  SI_TEMPER_DESTINATIONS_FILTER_BRAWL_DONE:
    "(Dest) " + zo_strformat(achievementName(1247)) + " 完了",
  SI_TEMPER_DESTINATIONS_FILTER_BREAKING_ENTERING: "(Dest) " + zo_strformat(achievementName(1349)),
  SI_TEMPER_DESTINATIONS_FILTER_BREAKING_ENTERING_DONE:
    "(Dest) " + zo_strformat(achievementName(1349)) + " 完了",
  SI_TEMPER_DESTINATIONS_FILTER_CHAMPION: "(Dest) ダンジョンのチャンピオン",
  SI_TEMPER_DESTINATIONS_FILTER_CHAMPION_DONE: "(Dest) ダンジョンのチャンピオン 完了",
  SI_TEMPER_DESTINATIONS_FILTER_COLLECTIBLE: "(Dest) 収集のピン",
  SI_TEMPER_DESTINATIONS_FILTER_COLLECTIBLE_DONE: "(Dest) 収集 完了",
  SI_TEMPER_DESTINATIONS_FILTER_CUTPURSE_ABOVE: "(Dest) " + zo_strformat(achievementName(1383)),
  SI_TEMPER_DESTINATIONS_FILTER_CUTPURSE_ABOVE_DONE:
    "(Dest) " + zo_strformat(achievementName(1383)) + " 完了",
  SI_TEMPER_DESTINATIONS_FILTER_DEADLANDS_ENTRANCE: "(Dest) Deadlands Entrance",
  SI_TEMPER_DESTINATIONS_FILTER_DWEMER: "(Dest) ドゥエマーの遺跡",
  SI_TEMPER_DESTINATIONS_FILTER_EARTHLYPOS: "(Dest) " + zo_strformat(achievementName(1121)),
  SI_TEMPER_DESTINATIONS_FILTER_EARTHLYPOS_DONE:
    "(Dest) " + zo_strformat(achievementName(1121)) + " 完了",
  SI_TEMPER_DESTINATIONS_FILTER_FISHING: "(Dest) 釣りのピン",
  SI_TEMPER_DESTINATIONS_FILTER_FISHING_DONE: "(Dest) 釣り 完了",
  SI_TEMPER_DESTINATIONS_FILTER_HIGHISLE_DRUIDICSHRINE: "(Dest) Druidic Shrine",
  SI_TEMPER_DESTINATIONS_FILTER_KNOWN: "(Dest) 既知の地点",
  SI_TEMPER_DESTINATIONS_FILTER_MAIQ: "(Dest) " + zo_strformat(achievementName(872)),
  SI_TEMPER_DESTINATIONS_FILTER_MAIQ_DONE: "(Dest) " + zo_strformat(achievementName(872)) + " 完了",
  SI_TEMPER_DESTINATIONS_FILTER_NOSEDIVER: "(Dest) " + zo_strformat(achievementName(406)),
  SI_TEMPER_DESTINATIONS_FILTER_NOSEDIVER_DONE:
    "(Dest) " + zo_strformat(achievementName(406)) + " 完了",
  SI_TEMPER_DESTINATIONS_FILTER_ON_ME: "(Dest) " + zo_strformat(achievementName(704)),
  SI_TEMPER_DESTINATIONS_FILTER_ON_ME_DONE:
    "(Dest) " + zo_strformat(achievementName(704)) + " 完了",
  SI_TEMPER_DESTINATIONS_FILTER_OTHER: "(Dest) その他のアチーブメント",
  SI_TEMPER_DESTINATIONS_FILTER_OTHER_DONE: "(Dest) その他のアチーブメント 完了",
  SI_TEMPER_DESTINATIONS_FILTER_PATRON: "(Dest) " + zo_strformat(achievementName(1316)),
  SI_TEMPER_DESTINATIONS_FILTER_PATRON_DONE:
    "(Dest) " + zo_strformat(achievementName(1316)) + " 完了",
  SI_TEMPER_DESTINATIONS_FILTER_PEACEMAKER: "(Dest) " + zo_strformat(achievementName(716)),
  SI_TEMPER_DESTINATIONS_FILTER_PEACEMAKER_DONE:
    "(Dest) " + zo_strformat(achievementName(716)) + " 完了",
  SI_TEMPER_DESTINATIONS_FILTER_RELIC_HUNTER: "(Dest) " + zo_strformat(achievementName(1250)),
  SI_TEMPER_DESTINATIONS_FILTER_RELIC_HUNTER_DONE:
    "(Dest) " + zo_strformat(achievementName(1250)) + " 完了",
  SI_TEMPER_DESTINATIONS_FILTER_UNKNOWN: "(Dest) 未知の地点",
  SI_TEMPER_DESTINATIONS_FILTER_VAMPIRE_ALTAR: "(Dest) ヴァンパイアの変異",
  SI_TEMPER_DESTINATIONS_FILTER_WEREWOLF_SHRINE: "(Dest) ウェアウルフの聖堂",
  SI_TEMPER_DESTINATIONS_FILTER_WROTHGAR_JUMPER: "(Dest) " + zo_strformat(achievementName(1331)),
  SI_TEMPER_DESTINATIONS_FILTER_WROTHGAR_JUMPER_DONE:
    "(Dest) " + zo_strformat(achievementName(1331)) + " 完了",
  SI_TEMPER_DESTINATIONS_FILTER_WWVAMP: "(Dest) ウェアウルフとヴァンパイア",
  SI_TEMPER_DESTINATIONS_SETTINGS_ACH_ALL_COMPASS_DIST: "コンパス上のピンの距離",
  SI_TEMPER_DESTINATIONS_SETTINGS_ACH_ALL_COMPASS_TOGGLE: "コンパスにアチーブメントを表示する",
  SI_TEMPER_DESTINATIONS_SETTINGS_ACH_ALL_PIN_LAYER: "全てのアチーブメントに関するピンのレイヤー",
  SI_TEMPER_DESTINATIONS_SETTINGS_ACH_BRAWL_HEADER: "'最後の乱闘'",
  SI_TEMPER_DESTINATIONS_SETTINGS_ACH_BREAKING_HEADER: "'鍵開けと侵入'",
  SI_TEMPER_DESTINATIONS_SETTINGS_ACH_CHAMPION_FRONT_PIN_TOGGLE: "ゾーンピンを前に",
  SI_TEMPER_DESTINATIONS_SETTINGS_ACH_CHAMPION_FRONT_PIN_TOGGLE_TT:
    "ゾーンのピンが有効ならダンジョンのピンの前に表示するかどうかを調整します",
  SI_TEMPER_DESTINATIONS_SETTINGS_ACH_CHAMPION_PIN_HEADER: "ダンジョンのチャンピオン",
  SI_TEMPER_DESTINATIONS_SETTINGS_ACH_CHAMPION_PIN_SIZE: "ダンジョンのチャンピオンのピンのサイズ",
  SI_TEMPER_DESTINATIONS_SETTINGS_ACH_CHAMPION_ZONE_PIN_TOGGLE: "ゾーン地図を表示する",
  SI_TEMPER_DESTINATIONS_SETTINGS_ACH_CHAMPION_ZONE_PIN_TOGGLE_TT:
    "ゾーン地図のチャンピオン(ソロダンジョンボス）のon/offを調整します",
  SI_TEMPER_DESTINATIONS_SETTINGS_ACH_CUTPURSE_HEADER: "'上級スリ師'",
  SI_TEMPER_DESTINATIONS_SETTINGS_ACH_EARTHLYPOS_HEADER: "'地上の所有'",
  SI_TEMPER_DESTINATIONS_SETTINGS_ACH_GLOBAL_HEADER: "アチーブメントの位置 - 全体設定",
  SI_TEMPER_DESTINATIONS_SETTINGS_ACH_GLOBAL_HEADER_TT:
    "このサブメニューは全体のアチーブメント設定をカバーします",
  SI_TEMPER_DESTINATIONS_SETTINGS_ACH_HEADER: "アチーブメントの位置",
  SI_TEMPER_DESTINATIONS_SETTINGS_ACH_HEADER_TT:
    "このサブメニューはゲーム中の主要なアチーブメントをカバーします（ここで一覧するには多すぎます）",
  SI_TEMPER_DESTINATIONS_SETTINGS_ACH_MAIQ_HEADER: "'ムアイクが好き'",
  SI_TEMPER_DESTINATIONS_SETTINGS_ACH_NOSEDIVER_HEADER: "'ノーズダイバー'",
  SI_TEMPER_DESTINATIONS_SETTINGS_ACH_ON_ME_HEADER: "'これはおごりだ'",
  SI_TEMPER_DESTINATIONS_SETTINGS_ACH_OTHER_HEADER:
    "'光をもたらす者' '貧しい者に恵みを' '犯罪は報われる'",
  SI_TEMPER_DESTINATIONS_SETTINGS_ACH_PATRON_HEADER: "'オルシニウムの後援者'",
  SI_TEMPER_DESTINATIONS_SETTINGS_ACH_PEACEMAKER_HEADER: "'ピースメーカー'",
  SI_TEMPER_DESTINATIONS_SETTINGS_ACH_PIN_COLOR_DONE: "ピンの色(完了)",
  SI_TEMPER_DESTINATIONS_SETTINGS_ACH_PIN_COLOR_DONE_TT:
    "完了したアチーブメントのピンの色に影響する",
  SI_TEMPER_DESTINATIONS_SETTINGS_ACH_PIN_COLOR_MISS: "ピンの色(未完了)",
  SI_TEMPER_DESTINATIONS_SETTINGS_ACH_PIN_COLOR_MISS_TT:
    "未完了のアチーブメントのピンの色に影響する",
  SI_TEMPER_DESTINATIONS_SETTINGS_ACH_PIN_SIZE: "アチーブメントのピンのサイズ",
  SI_TEMPER_DESTINATIONS_SETTINGS_ACH_PIN_STYLE: "アチーブメントのピンのスタイル",
  SI_TEMPER_DESTINATIONS_SETTINGS_ACH_PIN_TOGGLE: "未完了のアチーブメントを表示する",
  SI_TEMPER_DESTINATIONS_SETTINGS_ACH_PIN_TOGGLE_DONE: "完了したアチーブメントを表示する",
  SI_TEMPER_DESTINATIONS_SETTINGS_ACH_RELIC_HUNTER_HEADER: "'ロスガーの達人遺物ハンター'",
  SI_TEMPER_DESTINATIONS_SETTINGS_ACH_TXT_COLOR_DONE: "ピンのテキストの色(完了)",
  SI_TEMPER_DESTINATIONS_SETTINGS_ACH_TXT_COLOR_DONE_TT:
    "完了したアチーブメントのピンのテキストに影響する",
  SI_TEMPER_DESTINATIONS_SETTINGS_ACH_TXT_COLOR_MISS: "ピンのテキストの色(未完了)",
  SI_TEMPER_DESTINATIONS_SETTINGS_ACH_TXT_COLOR_MISS_TT: "未完了のピンのテキストに影響する",
  SI_TEMPER_DESTINATIONS_SETTINGS_ACH_WROTHGAR_JUMPER_HEADER: "'ロスガーの崖から飛び降りし者'",
  SI_TEMPER_DESTINATIONS_SETTINGS_ALL_SHOW_ENGLISH: "英語名の地点を表示する",
  SI_TEMPER_DESTINATIONS_SETTINGS_COLLECTIBLES_COLORS_HEADER: "収集のピンの色 ",
  SI_TEMPER_DESTINATIONS_SETTINGS_COLLECTIBLES_COLOR_DONE: "完了したテキストの色",
  SI_TEMPER_DESTINATIONS_SETTINGS_COLLECTIBLES_COLOR_DONE_TT:
    "完了した収集のピンのテキストに影響する",
  SI_TEMPER_DESTINATIONS_SETTINGS_COLLECTIBLES_COLOR_TITLE: "ヘッダタイトルのテキストの色",
  SI_TEMPER_DESTINATIONS_SETTINGS_COLLECTIBLES_COLOR_TITLE_TT:
    "収集アチーブメントのテキストのタイトルに影響する",
  SI_TEMPER_DESTINATIONS_SETTINGS_COLLECTIBLES_COLOR_UNDONE: "未収集のテキストの色",
  SI_TEMPER_DESTINATIONS_SETTINGS_COLLECTIBLES_COLOR_UNDONE_TT:
    "未収集のピンのテキストの色に影響する",
  SI_TEMPER_DESTINATIONS_SETTINGS_COLLECTIBLES_COMPASS_DIST: "コンパスの距離",
  SI_TEMPER_DESTINATIONS_SETTINGS_COLLECTIBLES_COMPASS_DIST_TT: "コンパスに収集エリアの距離",
  SI_TEMPER_DESTINATIONS_SETTINGS_COLLECTIBLES_COMPASS_TOGGLE: "コンパスに表示する",
  SI_TEMPER_DESTINATIONS_SETTINGS_COLLECTIBLES_COMPASS_TOGGLE_TT: "コンパスに収集を表示する",
  SI_TEMPER_DESTINATIONS_SETTINGS_COLLECTIBLES_DONE_TOGGLE: "完了した収集を表示する",
  SI_TEMPER_DESTINATIONS_SETTINGS_COLLECTIBLES_DONE_TOGGLE_TT: "完了した収集エリアを表示する",
  SI_TEMPER_DESTINATIONS_SETTINGS_COLLECTIBLES_HEADER: "収集位置",
  SI_TEMPER_DESTINATIONS_SETTINGS_COLLECTIBLES_HEADER_TT:
    "このサブメニューは全ての収集に関する設定をカバーします",
  SI_TEMPER_DESTINATIONS_SETTINGS_COLLECTIBLES_MISC_HEADER: "いろいろ",
  SI_TEMPER_DESTINATIONS_SETTINGS_COLLECTIBLES_PIN_COLOR: "未収集のピンの色",
  SI_TEMPER_DESTINATIONS_SETTINGS_COLLECTIBLES_PIN_COLOR_DONE: "完了したピンの色",
  SI_TEMPER_DESTINATIONS_SETTINGS_COLLECTIBLES_PIN_COLOR_DONE_TT:
    "収集を完了したピンの色を設定する",
  SI_TEMPER_DESTINATIONS_SETTINGS_COLLECTIBLES_PIN_COLOR_TT: "未収集のピンの色を設定する",
  SI_TEMPER_DESTINATIONS_SETTINGS_COLLECTIBLES_PIN_LAYER: "収集のピンのレイヤー",
  SI_TEMPER_DESTINATIONS_SETTINGS_COLLECTIBLES_PIN_LAYER_TT: "収集のピンのレイヤー",
  SI_TEMPER_DESTINATIONS_SETTINGS_COLLECTIBLES_PIN_SIZE: "収集のピンのサイズ",
  SI_TEMPER_DESTINATIONS_SETTINGS_COLLECTIBLES_PIN_SIZE_TT: "収集のピンのサイズ",
  SI_TEMPER_DESTINATIONS_SETTINGS_COLLECTIBLES_PIN_STYLE: "収集のピンスタイル",
  SI_TEMPER_DESTINATIONS_SETTINGS_COLLECTIBLES_SHOW_ITEM: "ピンにアイテム名を表示する",
  SI_TEMPER_DESTINATIONS_SETTINGS_COLLECTIBLES_SHOW_ITEM_TT:
    "アチーブメントを完了するために必要なアイテム名を表示する",
  SI_TEMPER_DESTINATIONS_SETTINGS_COLLECTIBLES_SHOW_MOBNAME: "ピンにモンスターの名前を表示する",
  SI_TEMPER_DESTINATIONS_SETTINGS_COLLECTIBLES_SHOW_MOBNAME_TT:
    "アチーブメントを完了するために必要なアイテムをドロップするモンスターの名前(英語)を表示する",
  SI_TEMPER_DESTINATIONS_SETTINGS_COLLECTIBLES_SUBHEADER: "収集の設定",
  SI_TEMPER_DESTINATIONS_SETTINGS_COLLECTIBLES_TOGGLE: "未完了の収集を表示する",
  SI_TEMPER_DESTINATIONS_SETTINGS_COLLECTIBLES_TOGGLE_TT:
    "アチーブメントの収集で殺されたモンスターのエリアを表示する",
  SI_TEMPER_DESTINATIONS_SETTINGS_FISHING_COLOR_BAIT_DONE: "完了した餌のタイプのテキストの色",
  SI_TEMPER_DESTINATIONS_SETTINGS_FISHING_COLOR_BAIT_DONE_TT:
    "有効なら取得済みの魚の餌のピンのテキストに影響する",
  SI_TEMPER_DESTINATIONS_SETTINGS_FISHING_COLOR_BAIT_UNDONE: "未取得の餌のタイプのテキストの色",
  SI_TEMPER_DESTINATIONS_SETTINGS_FISHING_COLOR_BAIT_UNDONE_TT:
    "有効なら未取得の魚の餌のピンのテキストに影響する",
  SI_TEMPER_DESTINATIONS_SETTINGS_FISHING_COLOR_DONE: "完了したテキストの色",
  SI_TEMPER_DESTINATIONS_SETTINGS_FISHING_COLOR_DONE_TT: "完了した魚のピンのテキストに影響する",
  SI_TEMPER_DESTINATIONS_SETTINGS_FISHING_COLOR_HEADER: "釣りのピンの色",
  SI_TEMPER_DESTINATIONS_SETTINGS_FISHING_COLOR_TITLE: "アチーブメントタイトルのテキストの色",
  SI_TEMPER_DESTINATIONS_SETTINGS_FISHING_COLOR_TITLE_TT:
    "釣りのアチーブメントテキストのタイトルに影響する",
  SI_TEMPER_DESTINATIONS_SETTINGS_FISHING_COLOR_UNDONE: "未取得のテキストの色",
  SI_TEMPER_DESTINATIONS_SETTINGS_FISHING_COLOR_UNDONE_TT: "未取得の魚のピンのテキストに影響する",
  SI_TEMPER_DESTINATIONS_SETTINGS_FISHING_COLOR_WATER_DONE: "完了した水の種類のテキストの色",
  SI_TEMPER_DESTINATIONS_SETTINGS_FISHING_COLOR_WATER_DONE_TT:
    "有効なら取得済みの水のピンのテキストに影響する",
  SI_TEMPER_DESTINATIONS_SETTINGS_FISHING_COLOR_WATER_UNDONE: "未取得の水の種類のテキストの色",
  SI_TEMPER_DESTINATIONS_SETTINGS_FISHING_COLOR_WATER_UNDONE_TT:
    "有効なら未取得の魚の水のピンのテキストに影響する",
  SI_TEMPER_DESTINATIONS_SETTINGS_FISHING_COMPASS_DIST: "コンパスの距離",
  SI_TEMPER_DESTINATIONS_SETTINGS_FISHING_COMPASS_DIST_TT: "コンパスの釣り穴までの距離",
  SI_TEMPER_DESTINATIONS_SETTINGS_FISHING_COMPASS_TOGGLE: "コンパスに表示する",
  SI_TEMPER_DESTINATIONS_SETTINGS_FISHING_COMPASS_TOGGLE_TT: "コンパスに釣り穴を表示する",
  SI_TEMPER_DESTINATIONS_SETTINGS_FISHING_DONE_TOGGLE: "完了した位置を表示する",
  SI_TEMPER_DESTINATIONS_SETTINGS_FISHING_DONE_TOGGLE_TT: "完了した釣り穴の位置を表示する",
  SI_TEMPER_DESTINATIONS_SETTINGS_FISHING_HEADER: "釣りの位置",
  SI_TEMPER_DESTINATIONS_SETTINGS_FISHING_HEADER_TT:
    "このサブメニューは釣りに関する全ての設定をカバーします",
  SI_TEMPER_DESTINATIONS_SETTINGS_FISHING_MISC_HEADER: "いろいろ",
}
