import type { FormulaCase } from "./cases.ts"
import { ABSENT, answersNumber, C, COUNT, L, MIXED, NOTHING, num } from "./shorthand.ts"

export const arithmetic: FormulaCase[] = [
  {
    name: "plus adds one number to another",
    group: "arithmetic",
    from: L.opPlus,
    claim: C.opPlus,
    formula: "2 + 3",
    shape: NOTHING,
    values: {},
    expected: answersNumber(5),
  },
  {
    name: "plus over a reference and a literal",
    group: "arithmetic",
    from: L.opPlus,
    claim: C.opPlus,
    formula: "{count} + 1",
    shape: COUNT,
    values: { count: num(41) },
    expected: answersNumber(42),
  },
  {
    name: "plus over fractional numbers",
    group: "arithmetic",
    from: L.opPlus,
    claim: C.opPlus,
    formula: "1.5 + 1.5",
    shape: NOTHING,
    values: {},
    expected: answersNumber(3),
  },
  {
    name: "minus subtracts one number from another",
    group: "arithmetic",
    from: L.opMinus,
    claim: C.opMinus,
    formula: "5 - 3",
    shape: NOTHING,
    values: {},
    expected: answersNumber(2),
  },
  {
    name: "minus can answer a number below zero",
    group: "arithmetic",
    from: L.opMinus,
    claim: C.opMinus,
    formula: "3 - 5",
    shape: NOTHING,
    values: {},
    expected: answersNumber(-2),
  },
  {
    name: "times multiplies one number by another",
    group: "arithmetic",
    from: L.opTimes,
    claim: C.opTimes,
    formula: "3 * 4",
    shape: NOTHING,
    values: {},
    expected: answersNumber(12),
  },
  {
    name: "times by zero",
    group: "arithmetic",
    from: L.opTimes,
    claim: C.opTimes,
    formula: "{count} * 0",
    shape: COUNT,
    values: { count: num(9) },
    expected: answersNumber(0),
  },
  {
    name: "divide divides one number by another",
    group: "arithmetic",
    from: L.opDivide,
    claim: C.opDivide,
    formula: "6 / 3",
    shape: NOTHING,
    values: {},
    expected: answersNumber(2),
  },
  {
    name: "divide answers a fractional number",
    group: "arithmetic",
    from: L.opDivide,
    claim: C.opDivide,
    formula: "7 / 2",
    shape: NOTHING,
    values: {},
    expected: answersNumber(3.5),
  },
  {
    name: "dividing by a zero literal answers absent",
    group: "arithmetic",
    from: L.divideByZero,
    claim: C.divideByZero,
    formula: "{count} / 0",
    shape: COUNT,
    values: { count: num(9) },
    expected: ABSENT,
  },
  {
    name: "dividing by a key holding zero answers absent",
    group: "arithmetic",
    from: L.divideByZero,
    claim: C.divideByZero,
    formula: "{count} / {other}",
    shape: MIXED,
    values: { count: num(9), other: num(0) },
    expected: ABSENT,
  },
  {
    name: "zero divided by zero answers absent",
    group: "arithmetic",
    from: L.divideByZero,
    claim: C.divideByZero,
    formula: "0 / 0",
    shape: NOTHING,
    values: {},
    expected: ABSENT,
  },
  {
    name: "dividing by zero answers absent rather than failing",
    group: "never-fails",
    from: L.neverFails,
    claim: C.neverFails,
    formula: "1 / 0",
    shape: NOTHING,
    values: {},
    expected: ABSENT,
  },
  {
    name: "an absent from a division by zero carries into the operator above it",
    group: "arithmetic",
    from: L.absentOperator,
    claim: C.absentOperator,
    formula: "1 + 1 / 0",
    shape: NOTHING,
    values: {},
    expected: ABSENT,
  },
  {
    name: "a minus with a value to its left subtracts",
    group: "arithmetic",
    from: L.opMinus,
    claim: C.opMinus,
    formula: "{count} - 1",
    shape: COUNT,
    values: { count: num(5) },
    expected: answersNumber(4),
  },
  {
    name: "a minus with nothing to its left negates",
    group: "arithmetic",
    from: L.opMinus,
    claim: C.opMinus,
    formula: "-{count}",
    shape: COUNT,
    values: { count: num(5) },
    expected: answersNumber(-5),
  },
  {
    name: "a minus negates a literal",
    group: "arithmetic",
    from: L.opMinus,
    claim: C.opMinus,
    formula: "-5",
    shape: NOTHING,
    values: {},
    expected: answersNumber(-5),
  },
  {
    name: "a minus standing after another operator negates",
    group: "arithmetic",
    from: L.opMinus,
    claim: C.opMinus,
    formula: "{count} * -1",
    shape: COUNT,
    values: { count: num(5) },
    expected: answersNumber(-5),
  },
  {
    name: "a subtraction whose right side is negated",
    group: "arithmetic",
    from: L.opMinus,
    claim: C.opMinus,
    formula: "{count} - -1",
    shape: COUNT,
    values: { count: num(5) },
    expected: answersNumber(6),
  },
  {
    name: "a negation and a subtraction in one formula",
    group: "arithmetic",
    from: L.opMinus,
    claim: C.opMinus,
    formula: "-{count} - {other}",
    shape: MIXED,
    values: { count: num(5), other: num(3) },
    expected: answersNumber(-8),
  },
  {
    name: "the space around a minus does not decide which one it is",
    group: "arithmetic",
    from: L.opMinus,
    claim: C.opMinus,
    formula: "{count} -1",
    shape: COUNT,
    values: { count: num(5) },
    expected: answersNumber(4),
  },
]
