import type { FormulaCase } from "./cases.ts"
import { bool, C, L, MIXED, NOTHING, NUMBER, num, refused, TEXT, text } from "./shorthand.ts"

export const refusedTypes: FormulaCase[] = [
  {
    name: "adding a text to a number is refused",
    group: "refused-types-do-not-meet",
    from: L.typesMeet,
    claim: C.typesMeet,
    formula: "{name} + 1",
    shape: MIXED,
    values: { name: text("astra") },
    expected: refused("check", "types-do-not-meet", ["name", "text"]),
  },
  {
    name: "adding a boolean to a number is refused",
    group: "refused-types-do-not-meet",
    from: L.typesMeet,
    claim: C.typesMeet,
    formula: "{flag} + 1",
    shape: MIXED,
    values: { flag: bool(true) },
    expected: refused("check", "types-do-not-meet", ["flag", "boolean"]),
  },
  {
    name: "adding a text that looks like a number is still refused",
    group: "refused-types-do-not-meet",
    from: L.declaredNotGuessed,
    claim: C.declaredNotGuessed,
    formula: "{name} + 1",
    shape: MIXED,
    values: { name: text("41") },
    expected: refused("check", "types-do-not-meet", ["name", "text"]),
  },
  {
    name: "no conversion is made to let two types meet",
    group: "refused-types-do-not-meet",
    from: L.refuseNotConvert,
    claim: C.refuseNotConvert,
    formula: "{count} + {name}",
    shape: MIXED,
    values: { count: num(1), name: text("2") },
    expected: refused("check", "types-do-not-meet", ["name", "text"]),
  },
  {
    name: "subtracting a text is refused",
    group: "refused-types-do-not-meet",
    from: L.typesMeet,
    claim: C.typesMeet,
    formula: '{name} - "a"',
    shape: MIXED,
    values: {},
    expected: refused("check", "types-do-not-meet", ["text"]),
  },
  {
    name: "multiplying a text is refused",
    group: "refused-types-do-not-meet",
    from: L.typesMeet,
    claim: C.typesMeet,
    formula: "{name} * 2",
    shape: MIXED,
    values: {},
    expected: refused("check", "types-do-not-meet", ["name", "text"]),
  },
  {
    name: "dividing a boolean is refused",
    group: "refused-types-do-not-meet",
    from: L.typesMeet,
    claim: C.typesMeet,
    formula: "{flag} / 2",
    shape: MIXED,
    values: {},
    expected: refused("check", "types-do-not-meet", ["flag", "boolean"]),
  },
  {
    name: "adding a list is refused",
    group: "refused-types-do-not-meet",
    from: L.typesMeet,
    claim: C.typesMeet,
    formula: "{tags} + 1",
    shape: MIXED,
    values: {},
    expected: refused("check", "types-do-not-meet", ["tags", "list"]),
  },
  {
    name: "and over a number is refused",
    group: "refused-types-do-not-meet",
    from: L.typesMeet,
    claim: C.typesMeet,
    formula: "{count} && true",
    shape: MIXED,
    values: { count: num(1) },
    expected: refused("check", "types-do-not-meet", ["count", "number"]),
  },
  {
    name: "and over a text is refused",
    group: "refused-types-do-not-meet",
    from: L.typesMeet,
    claim: C.typesMeet,
    formula: '{name} && "yes"',
    shape: MIXED,
    values: {},
    expected: refused("check", "types-do-not-meet", ["name", "text"]),
  },
  {
    name: "and over a number on its right is refused",
    group: "refused-types-do-not-meet",
    from: L.typesMeet,
    claim: C.typesMeet,
    formula: "true && 1",
    shape: NOTHING,
    values: {},
    expected: refused("check", "types-do-not-meet", ["number"]),
  },
  {
    name: "a fallback whose two sides are different kinds is refused",
    group: "refused-types-do-not-meet",
    from: L.typesMeet,
    claim: C.typesMeet,
    formula: '{count} ?? "none"',
    shape: MIXED,
    values: {},
    expected: refused("check", "types-do-not-meet", ["number", "text"]),
  },
  {
    name: "a type fault on a side the short circuit never reaches is still refused",
    group: "refused-types-do-not-meet",
    from: L.typesMeet,
    claim: C.typesMeet,
    formula: "false && 1",
    shape: NOTHING,
    values: {},
    expected: refused("check", "types-do-not-meet", ["number"]),
  },
  {
    name: "a type fault on a fallback's unreached side is still refused",
    group: "refused-types-do-not-meet",
    from: L.typesMeet,
    claim: C.typesMeet,
    formula: '{count} ?? "none"',
    shape: MIXED,
    values: { count: num(1) },
    expected: refused("check", "types-do-not-meet", ["number", "text"]),
  },
  {
    name: "a fallback between a boolean and a number is refused",
    group: "refused-types-do-not-meet",
    from: L.typesMeet,
    claim: C.typesMeet,
    formula: "{flag} ?? 0",
    shape: MIXED,
    values: {},
    expected: refused("check", "types-do-not-meet", ["boolean", "number"]),
  },
  {
    name: "a fallback between two lists of different kinds is refused",
    group: "refused-types-do-not-meet",
    from: L.typesMeet,
    claim: C.typesMeet,
    formula: "{tags} ?? {scores}",
    shape: MIXED,
    values: {},
    expected: refused("check", "types-do-not-meet", ["text", "number"]),
  },
  {
    name: "an instant read by an operator rather than a function is refused",
    group: "refused-types-do-not-meet",
    from: L.valueInstant,
    claim: C.valueInstant,
    formula: "{start} < {finish}",
    shape: MIXED,
    values: {},
    expected: refused("check", "instant-read-outside-a-function", ["instant"]),
  },
  {
    name: "an instant added to a number is refused",
    group: "refused-types-do-not-meet",
    from: L.valueInstant,
    claim: C.valueInstant,
    formula: "{start} + 1",
    shape: MIXED,
    values: {},
    expected: refused("check", "types-do-not-meet", ["start", "instant"]),
  },
  {
    name: "an instant compared for equality by an operator is refused",
    group: "refused-types-do-not-meet",
    from: L.valueInstant,
    claim: C.valueInstant,
    formula: "{start} == {finish}",
    shape: MIXED,
    values: {},
    expected: refused("check", "instant-read-outside-a-function", ["instant"]),
  },
  {
    name: "an instant written into a text literal is refused",
    group: "refused-types-do-not-meet",
    from: L.valueInstant,
    claim: C.valueInstant,
    formula: '"at {start}"',
    shape: MIXED,
    values: {},
    expected: refused("check", "instant-read-outside-a-function", ["start"]),
  },
  {
    name: "comparing a number against a text is refused",
    group: "refused-types-do-not-meet",
    from: L.typesMeet,
    claim: C.typesMeet,
    formula: '{count} == "1"',
    shape: MIXED,
    values: { count: num(1) },
    expected: refused("check", "types-do-not-meet", ["number", "text"]),
  },
  {
    name: "comparing a number against a boolean is refused",
    group: "refused-types-do-not-meet",
    from: L.typesMeet,
    claim: C.typesMeet,
    formula: "{count} != {flag}",
    shape: MIXED,
    values: {},
    expected: refused("check", "types-do-not-meet", ["number", "boolean"]),
  },
  {
    name: "a computed key whose own formula's types do not meet is refused",
    group: "refused-types-do-not-meet",
    from: L.typesMeet,
    claim: C.typesMeet,
    formula: "{broken}",
    shape: {
      name: { type: TEXT },
      broken: { type: NUMBER, formula: "{name} + 1" },
    },
    values: { name: text("astra") },
    expected: refused("check", "types-do-not-meet", ["name", "text"]),
  },
  {
    name: "a computed key answering a kind other than the type it declares is refused",
    group: "refused-types-do-not-meet",
    from: L.answersDeclaredType,
    claim: C.answersDeclaredType,
    formula: "{mislabelled}",
    shape: {
      count: { type: NUMBER },
      mislabelled: { type: TEXT, formula: "{count} + 1" },
    },
    values: { count: num(1) },
    expected: refused("check", "types-do-not-meet", ["mislabelled", "text", "number"]),
  },
  {
    name: "less than over two texts is refused",
    group: "refused-types-do-not-meet",
    from: L.opLess,
    claim: C.opLess,
    formula: '"a" < "b"',
    shape: NOTHING,
    values: {},
    expected: refused("check", "types-do-not-meet", ["text"]),
  },
  {
    name: "at most over a text is refused",
    group: "refused-types-do-not-meet",
    from: L.opAtMost,
    claim: C.opAtMost,
    formula: '{name} <= "b"',
    shape: MIXED,
    values: { name: text("a") },
    expected: refused("check", "types-do-not-meet", ["name", "text"]),
  },
  {
    name: "more than over a boolean is refused",
    group: "refused-types-do-not-meet",
    from: L.opMore,
    claim: C.opMore,
    formula: "{flag} > false",
    shape: MIXED,
    values: { flag: bool(true) },
    expected: refused("check", "types-do-not-meet", ["flag", "boolean"]),
  },
  {
    name: "at least over a list is refused",
    group: "refused-types-do-not-meet",
    from: L.opAtLeast,
    claim: C.opAtLeast,
    formula: "{tags} >= {scores}",
    shape: MIXED,
    values: {},
    expected: refused("check", "types-do-not-meet", ["tags", "list"]),
  },
  {
    name: "an instant asked whether it is after another is refused",
    group: "refused-types-do-not-meet",
    from: L.valueInstant,
    claim: C.valueInstant,
    formula: "{start} > {finish}",
    shape: MIXED,
    values: {},
    expected: refused("check", "instant-read-outside-a-function", ["instant"]),
  },
]
