import type { FormulaCase } from "./cases.ts"
import { bool, C, L, MIXED, NOTHING, NUMBER, num, refused, TEXT, text } from "./shorthand.ts"

// ---------------------------------------------------------------------------
// Refused where the types do not meet
// ---------------------------------------------------------------------------

export const refusedTypes: FormulaCase[] = [
  {
    name: "adding a text to a number is refused",
    group: "refused-types-do-not-meet",
    from: L.typesMeet,
    claim: C.typesMeet,
    formula: "{name} + 1",
    shape: MIXED,
    values: { name: text("astra") },
    expected: refused("check", "types-do-not-meet", ["name", "text"]),
  },
  {
    name: "adding a boolean to a number is refused",
    group: "refused-types-do-not-meet",
    from: L.typesMeet,
    claim: C.typesMeet,
    formula: "{flag} + 1",
    shape: MIXED,
    values: { flag: bool(true) },
    expected: refused("check", "types-do-not-meet", ["flag", "boolean"]),
  },
  {
    name: "adding a text that looks like a number is still refused",
    group: "refused-types-do-not-meet",
    from: L.declaredNotGuessed,
    claim: C.declaredNotGuessed,
    formula: "{name} + 1",
    shape: MIXED,
    values: { name: text("41") },
    expected: refused("check", "types-do-not-meet", ["name", "text"]),
    // "Text that looks like a number is still text."
  },
  {
    name: "no conversion is made to let two types meet",
    group: "refused-types-do-not-meet",
    from: L.refuseNotConvert,
    claim: C.refuseNotConvert,
    formula: "{count} + {name}",
    shape: MIXED,
    values: { count: num(1), name: text("2") },
    expected: refused("check", "types-do-not-meet", ["name", "text"]),
  },
  {
    name: "subtracting a text is refused",
    group: "refused-types-do-not-meet",
    from: L.typesMeet,
    claim: C.typesMeet,
    formula: '{name} - "a"',
    shape: MIXED,
    values: {},
    expected: refused("check", "types-do-not-meet", ["text"]),
  },
  {
    name: "multiplying a text is refused",
    group: "refused-types-do-not-meet",
    from: L.typesMeet,
    claim: C.typesMeet,
    formula: "{name} * 2",
    shape: MIXED,
    values: {},
    expected: refused("check", "types-do-not-meet", ["name", "text"]),
  },
  {
    name: "dividing a boolean is refused",
    group: "refused-types-do-not-meet",
    from: L.typesMeet,
    claim: C.typesMeet,
    formula: "{flag} / 2",
    shape: MIXED,
    values: {},
    expected: refused("check", "types-do-not-meet", ["flag", "boolean"]),
  },
  {
    name: "adding a list is refused",
    group: "refused-types-do-not-meet",
    from: L.typesMeet,
    claim: C.typesMeet,
    formula: "{tags} + 1",
    shape: MIXED,
    values: {},
    expected: refused("check", "types-do-not-meet", ["tags", "list"]),
  },
  {
    name: "and over a number is refused",
    group: "refused-types-do-not-meet",
    from: L.typesMeet,
    claim: C.typesMeet,
    formula: "{count} && true",
    shape: MIXED,
    values: { count: num(1) },
    expected: refused("check", "types-do-not-meet", ["count", "number"]),
  },
  {
    name: "and over a text is refused",
    group: "refused-types-do-not-meet",
    from: L.typesMeet,
    claim: C.typesMeet,
    formula: '{name} && "yes"',
    shape: MIXED,
    values: {},
    expected: refused("check", "types-do-not-meet", ["name", "text"]),
  },
  {
    name: "and over a number on its right is refused",
    group: "refused-types-do-not-meet",
    from: L.typesMeet,
    claim: C.typesMeet,
    formula: "true && 1",
    shape: NOTHING,
    values: {},
    expected: refused("check", "types-do-not-meet", ["number"]),
  },
  {
    name: "a fallback whose two sides are different kinds is refused",
    group: "refused-types-do-not-meet",
    from: L.typesMeet,
    claim: C.typesMeet,
    formula: '{count} ?? "none"',
    shape: MIXED,
    values: {},
    expected: refused("check", "types-do-not-meet", ["number", "text"]),
  },
  {
    name: "a type fault on a side the short circuit never reaches is still refused",
    group: "refused-types-do-not-meet",
    from: L.typesMeet,
    claim: C.typesMeet,
    formula: "false && 1",
    shape: NOTHING,
    values: {},
    expected: refused("check", "types-do-not-meet", ["number"]),
    // Running this would never reach the `1`. Checking is not running, and
    // `language-failure.domain.md:27` puts the check before the doing.
  },
  {
    name: "a type fault on a fallback's unreached side is still refused",
    group: "refused-types-do-not-meet",
    from: L.typesMeet,
    claim: C.typesMeet,
    formula: '{count} ?? "none"',
    shape: MIXED,
    values: { count: num(1) },
    expected: refused("check", "types-do-not-meet", ["number", "text"]),
    // `{count}` is there, so running this would answer from the left alone
    // and never reach the text. It is refused before it is ever run.
  },
  {
    name: "a fallback between a boolean and a number is refused",
    group: "refused-types-do-not-meet",
    from: L.typesMeet,
    claim: C.typesMeet,
    formula: "{flag} ?? 0",
    shape: MIXED,
    values: {},
    expected: refused("check", "types-do-not-meet", ["boolean", "number"]),
  },
  {
    name: "a fallback between two lists of different kinds is refused",
    group: "refused-types-do-not-meet",
    from: L.typesMeet,
    claim: C.typesMeet,
    formula: "{tags} ?? {scores}",
    shape: MIXED,
    values: {},
    expected: refused("check", "types-do-not-meet", ["text", "number"]),
  },
  {
    name: "an instant read by an operator rather than a function is refused",
    group: "refused-types-do-not-meet",
    from: L.valueInstant,
    claim: C.valueInstant,
    formula: "{start} < {finish}",
    shape: MIXED,
    values: {},
    expected: refused("check", "instant-read-outside-a-function", ["instant"]),
    // "an instant [...] which only a function taking one may read". An
    // operator is not a function.
  },
  {
    name: "an instant added to a number is refused",
    group: "refused-types-do-not-meet",
    from: L.valueInstant,
    claim: C.valueInstant,
    formula: "{start} + 1",
    shape: MIXED,
    values: {},
    expected: refused("check", "types-do-not-meet", ["start", "instant"]),
  },
  {
    name: "an instant compared for equality by an operator is refused",
    group: "refused-types-do-not-meet",
    from: L.valueInstant,
    claim: C.valueInstant,
    formula: "{start} == {finish}",
    shape: MIXED,
    values: {},
    expected: refused("check", "instant-read-outside-a-function", ["instant"]),
  },
  {
    name: "an instant written into a text literal is refused",
    group: "refused-types-do-not-meet",
    from: L.valueInstant,
    claim: C.valueInstant,
    formula: '"at {start}"',
    shape: MIXED,
    values: {},
    expected: refused("check", "instant-read-outside-a-function", ["start"]),
  },
  {
    name: "comparing a number against a text is refused",
    group: "refused-types-do-not-meet",
    from: L.typesMeet,
    claim: C.typesMeet,
    formula: '{count} == "1"',
    shape: MIXED,
    values: { count: num(1) },
    expected: refused("check", "types-do-not-meet", ["number", "text"]),
    // `==` reaches across absence and nothing else; two kinds that could never
    // be the same are a fault the check can name.
  },
  {
    name: "comparing a number against a boolean is refused",
    group: "refused-types-do-not-meet",
    from: L.typesMeet,
    claim: C.typesMeet,
    formula: "{count} != {flag}",
    shape: MIXED,
    values: {},
    expected: refused("check", "types-do-not-meet", ["number", "boolean"]),
  },
  {
    name: "a computed key whose own formula's types do not meet is refused",
    group: "refused-types-do-not-meet",
    from: L.typesMeet,
    claim: C.typesMeet,
    formula: "{broken}",
    shape: {
      name: { type: TEXT },
      broken: { type: NUMBER, formula: "{name} + 1" },
    },
    values: { name: text("astra") },
    expected: refused("check", "types-do-not-meet", ["name", "text"]),
  },
  {
    name: "a computed key answering a kind other than the type it declares is refused",
    group: "refused-types-do-not-meet",
    from: L.answersDeclaredType,
    claim: C.answersDeclaredType,
    formula: "{mislabelled}",
    shape: {
      count: { type: NUMBER },
      mislabelled: { type: TEXT, formula: "{count} + 1" },
    },
    values: { count: num(1) },
    expected: refused("check", "types-do-not-meet", ["mislabelled", "text", "number"]),
  },
]
