import type { TemperSet } from "akasha/temper/catalog/gear/temper-set/temper-set.page-type.types.ts"

export const iceheart = {
  id: "019e6484-5ffb-7041-8601-b4cfcaf14038",
  type: "page-type/temper-set",
  slug: "iceheart",
  title: "Iceheart",
  key: "iceheart",
  esoSetId: 274,
  hashPlace: 241,
  esoItemIds: [94532, 94668, 94804, 94940, 95076, 95212],
  esoArmorTypes: ["ARMORTYPE_HEAVY", "ARMORTYPE_LIGHT", "ARMORTYPE_MEDIUM"],
  esoEquipTypes: ["EQUIP_TYPE_HEAD", "EQUIP_TYPE_SHOULDERS"],
  setWayshrines: [195, 195, 195],
  setVeteranEquipTypes: ["EQUIP_TYPE_HEAD"],
  setUndauntedChestId: 1,
  setTypeId: 8,
  setNameZh: "寒冰之心",
  setNameRu: "Ледяное Сердце",
  setNameFr: "Cœur-de-glace",
  setNameEs: "Corazón Gélido",
  setNameDe: "Eisherz",
  setDropZones: [449, 101, 101],
  setDropMechanics: [6],
  setDropLocationNamesEn: ["Drodda of Icereach"],
  setDropLocationNamesDe: ["Drodda von Eiskap"],
  setDlcId: 0,
  itemBrowserSources: ["449:-102"],
  itemBrowserPlaceKinds: [3],
  itemBrowserItemId: 94805,
  category: "temper-set-category/monster",
  valid: ["monster"],
  bonuses: "jsonl",
  icons: "jsonl",
} as const satisfies TemperSet
