apiVersion: v1
kind: Secret
metadata:
    name: headscale-secrets
    namespace: headscale
    labels:
        app.kubernetes.io/name: headscale
        app.kubernetes.io/instance: headscale
        app.kubernetes.io/component: control-plane
        app.kubernetes.io/part-of: headscale
        app.kubernetes.io/managed-by: deploy-script
type: Opaque
stringData:
    oidc_client_secret: ENC[AES256_GCM,data:GUFSzObwfvhz6w26xAKNSZHwgQMDNTiKiYRUSKdFEhF2TMA=,iv:ldqRhIlevOwE+Xmc3ky2lAZgLOVhWVga/gkhHqNVSCA=,tag:vJYOCLgiwqpwXWkfnNXSTA==,type:str]
    noise_private_key: ENC[AES256_GCM,data:bkpLmfebH4OV4EVPum4oJMARTTVcF9dr/cf4MrkWnxexIGiXTpHVzrJLt5XAANltSh+etGlat51dP7s9t6PpZIawFrdEmX0r,iv:NVoA1B5Ggzljj4PoPm4pD2oXnj/Xto0QX93pnArMsXU=,tag:jVxv3aEkk6p7B2uDIwUmLw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTcCtqYVpObnRKSUx2Szd4
            UDZVWUViVUxqUWRzNHJsbkpOc0drSWgyUzJJCng3WFZyRk1EU0VUZmVMN3JKbDR3
            VmU4TlkzUmhJaTAzaEpnNnNueGFhWW8KLS0tIGZRei9lcTAzRVBiZFlTRnhTMW00
            NlV0bXMyZE5SS243UmZQWDI2bXZKTzAKbMiEmfXeliifFCYzGWK3ZDYT8iXil02l
            T+FGRvQNe+V3By6PUwop2+vsNhuEE2NBch9+BEEXrZfFRgfAQNIjHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-18T23:43:45Z"
    mac: ENC[AES256_GCM,data:A6Y+keIratnzyrY+bXiPFCQ0iMKxkVZnE9tvUMWO9DmokvxdyEHrnh+ZgWgXbn6vF+5BYlh94nPTF/yoHhkuEfUcmbQEcvZdn1wOYpmxrLBDsWhuI8Y+plsMgEVxVawG2lLcqID0LK21pfDu6OHbyFsMYaG0cxcEXi5TlLzyxns=,iv:lO8Cr9tPmo1BLwHB7iWNdyK5TXjmZTt94+2SiQQF770=,tag:0RGx4BcL0OF9aKadu1TLNw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
