import type { TemperSet } from "akasha/temper/catalog/gear/temper-set/temper-set.page-type.types.ts"

export const twilightRemedy = {
  id: "019e66ec-7ece-7ac4-a18c-1c6a13b1ec85",
  type: "page-type/temper-set",
  slug: "twilight-remedy",
  title: "Twilight Remedy",
  key: "twilight-remedy",
  esoSetId: 229,
  esoItemIds: [
    73011, 73012, 73013, 73014, 73015, 73017, 73018, 73035, 73036, 73285, 73286, 73287, 73288,
    73289, 73290, 73291, 73292, 73293, 73294, 73295, 73296, 73297,
  ],
  esoArmorTypes: ["ARMORTYPE_LIGHT"],
  esoEquipTypes: [
    "EQUIP_TYPE_CHEST",
    "EQUIP_TYPE_FEET",
    "EQUIP_TYPE_HAND",
    "EQUIP_TYPE_HEAD",
    "EQUIP_TYPE_LEGS",
    "EQUIP_TYPE_NECK",
    "EQUIP_TYPE_OFF_HAND",
    "EQUIP_TYPE_ONE_HAND",
    "EQUIP_TYPE_RING",
    "EQUIP_TYPE_SHOULDERS",
    "EQUIP_TYPE_TWO_HAND",
    "EQUIP_TYPE_WAIST",
  ],
  esoWeaponTypes: [
    "WEAPONTYPE_AXE",
    "WEAPONTYPE_BOW",
    "WEAPONTYPE_DAGGER",
    "WEAPONTYPE_FIRE_STAFF",
    "WEAPONTYPE_FROST_STAFF",
    "WEAPONTYPE_HAMMER",
    "WEAPONTYPE_HEALING_STAFF",
    "WEAPONTYPE_LIGHTNING_STAFF",
    "WEAPONTYPE_SHIELD",
    "WEAPONTYPE_SWORD",
    "WEAPONTYPE_TWO_HANDED_AXE",
    "WEAPONTYPE_TWO_HANDED_HAMMER",
    "WEAPONTYPE_TWO_HANDED_SWORD",
  ],
  category: "temper-set-category/trial",
  valid: ["*:light"],
  bonuses: "jsonl",
  icons: "jsonl",
} as const satisfies TemperSet
