import type { Game } from "akasha/story/game/game.page-type.types.ts"

export const haremHotel = {
  id: "01a0673f-a3d6-7001-854b-30d81fd19b31",
  type: "page-type/game",
  slug: "harem-hotel",
  title: "Harem Hotel",
  unit: "unit/words",
  externalId: "harem-hotel",
  gameEngine: "awen",
  coordinatorAgent: "iris-game-master-harem-hotel",
  controlledEntityKind: "single",
  mechanicsWeight: "heavy",
  resolution: "formula",
  currentSession: 1,
  premise:
    "You wake at the bottom of a hotel with no memory of arriving — no name for how you got here, no reason it exists. A pane of pale letters measures your soul and goes quiet. The Harem Hotel rises: clear the challenge at the far end of the floor and the whole floor climbs, endlessly, as far as anyone has ever gone. You are alone at first. You will not stay that way — every fifth height the risen floor opens somewhere new, and a woman is there. The hallway grows her a room. Adventure is how you climb. The women are why it matters — and, if you earn it, how you grow stronger.",
  tone: "Warm, playful, charged — a place you live, not a tower you endure. The name is cheeky; the machine underneath is serious. Combat is real and can kill. Intimacy is explicit when earned, plain-register, never rushed. The mystery of the place is real and behaves as if it has a logic you cannot yet see.",
  readerFraming:
    "Second person, present tense. You are yourself, Alan, arrived at the bottom of the Harem Hotel with no memory of arriving.",
  genre: ["litrpg", "adventure", "progression"],
  config: "json",
  displayConfig: "json",
  gmContext: "json",
  narrativeContinuity: "json",
  resolutionMechanism: "json",
  mechanics: [
    "game-mechanic/affinity-ladder",
    "game-mechanic/attack-resolution",
    "game-mechanic/focus-max",
    "game-mechanic/hp-max",
    "game-mechanic/initiative",
    "game-mechanic/leveling",
    "game-mechanic/ment-atk",
    "game-mechanic/ment-attack",
    "game-mechanic/ment-def",
    "game-mechanic/one-d-twenty",
    "game-mechanic/phys-atk",
    "game-mechanic/phys-attack",
    "game-mechanic/phys-def",
    "game-mechanic/skill-ladder",
    "game-mechanic/stam-max",
    "game-mechanic/two-d-ten",
  ],
  attributes: [
    "game-attribute/finesse",
    "game-attribute/intellect",
    "game-attribute/luck",
    "game-attribute/might",
    "game-attribute/perception",
    "game-attribute/presence",
    "game-attribute/vitality",
    "game-attribute/will",
  ],
  defaultDice: "game-mechanic/two-d-ten",
  cardVocabulary: ["LEVEL UP", "SKILL", "AFFINITY", "CLASS", "TITLE"],
  panels: [
    "game-panel/hotel-hud",
    "game-panel/character-sheet",
    "game-panel/quest-list",
    "game-panel/story-so-far",
    "game-panel/prose-channel",
  ],
  player: "game-entity/harem-hotel-alan",
} as const satisfies Game
