import type { StoryTurnPlayed } from "akasha/story/world/stories/played/turns/story-turn-played.page-type.types.ts"

export const overwhereIi00081 = {
  id: "01a0fe64-def5-7187-a59a-cba34be2f03c",
  type: "page-type/story-turn-played",
  slug: "overwhere-ii-00-081",
  ownLength: 179,
  unit: "unit/words",
  partOfCollections: ["story-played/overwhere-ii"],
  position: 81,
  prose: "txt",
  characters: ["character-player/overwhere-ii-nala"],
  stepStatus: "step-status/reviewers",
  action: "I come over and give a guard salute. “Sir.”",
  beats: [
    "Nala comes down the lane to the Reeve's door and gives the knight a crisp guard's salute.",
    'Nala: "Sir."',
    "Sir Edric's grey brows lift a fraction, as if he has never seen a salute quite like it.",
    "He answers with a short bow from the neck, the way a knight greets a sworn equal.",
    "His eyes rest on her face a long moment, then drop, briefly, to the slow rise of her breath.",
    'Sir Edric, low and unhurried, the vowels clipped: "Nala. Sir Edric Hale, of House Varrow."',
    'Sir Edric: "I heard on the road in that Oswy Crake is dead, and by your hand."',
    "Sir Edric: \"In Lady Varrow's name, I thank you. He's been a blight on that road a long year.\"",
    "He glances up the valley, toward the white heads of the Whitecombs.",
    'Sir Edric: "The stone here hums. Faintly. Even the Reeve\'s doorpost leans toward those peaks."',
    'Sir Edric: "Dray writes that you found a crag split open up there, and something pulling under it."',
    'Sir Edric: "I\'d have you lead me up to it tomorrow, and tell me of the pull, there, on the spot."',
  ],
  lore: [
    "lore/overwhere-ii-nala",
    "lore/overwhere-ii-nala-2",
    "lore/overwhere-ii-nala-3",
    "lore/overwhere-ii-sir-edric-hale",
  ],
  reviewedBy: ["story-reviewer/style"],
  endsAt: "2026-10-18T09:10:00.000Z",
} as const satisfies StoryTurnPlayed
