import type { StoryTurnPlayed } from "akasha/story/world/stories/played/turns/story-turn-played.page-type.types.ts"

export const overwhereIi00028 = {
  id: "01a0f34d-b7b6-7164-80c5-6b1e03dd6119",
  type: "page-type/story-turn-played",
  slug: "overwhere-ii-00-028",
  ownLength: 254,
  unit: "unit/words",
  partOfCollections: ["story-played/overwhere-ii"],
  position: 28,
  prose: "txt",
  characters: ["character-player/overwhere-ii-nala"],
  stepStatus: "step-status/recorders",
  action:
    "“Thank you, guess I’m more tired than I thought. We should also check the wolves for reservoirs while we can, those could be worth quite a bit if they have them.”",
  beats: [
    'Nala: "Thank you, guess I\'m more tired than I thought."',
    "Wren brings the linen, and Garth binds the bite snug from wrist to elbow.",
    'Nala: "We should also check the wolves for reservoirs while we can."',
    'Nala: "Those could be worth quite a bit if they have them."',
    "Garth ties off the binding and sits back, thinking.",
    'Garth: "The Reeve pays two silver a head for any greymaw brought in dead."',
    'Garth: "The chest bones I\'ve only heard of. Carrowmouth folk buy such things, they say. Not here."',
    "He takes his stout skinning knife from its peg and lifts the lantern.",
    'Garth: "Wren, bar the door behind us, and keep Burr in."',
    "Out in the lane the three drained greymaws lie where they dropped, already stiffening.",
    "Garth kneels on the nearest and saws down through its scaled chest, grunting at the work.",
    "Behind the breastbone the knife grates on bone: a fist-sized knot of polished grey.",
    "It is layered like a shell, and whole.",
    "To Nala's inward sense it is dry and silent, empty of any Water.",
    "Garth wipes his brow; the knot is still fast in the chest, half the cut yet to go.",
    "Garth: \"Tough as ram's horn. That's half an hour a beast with this knife, and there's four.\"",
    "Up the fell, the she-wolf's carcass lies dark against the heather.",
    'Garth: "The rest ran, but they hunt dusk and dawn both. Now, by lantern, or in the morning?"',
  ],
  issues: ['"cut from behind a greymaw\'s breastbone" - What It Is'],
  lore: [
    "lore/overwhere-ii-garth-marsh",
    "lore/overwhere-ii-greymaws",
    "lore/overwhere-ii-nala",
    "lore/overwhere-ii-wendle-ford-folk",
  ],
  reviewedBy: ["story-reviewer/style", "story-reviewer/continuity"],
  recordedBy: ["story-recorder/inventory", "story-recorder/memory"],
  endsAt: "2026-09-29T18:42:00.000Z",
} as const satisfies StoryTurnPlayed
