import type { StoryTurnPlayed } from "akasha/story/world/stories/played/turns/story-turn-played.page-type.types.ts"

export const overwhereIi00085 = {
  id: "01a0fe8f-0bc8-76fd-b065-e0585dde1a9c",
  type: "page-type/story-turn-played",
  slug: "overwhere-ii-00-085",
  ownLength: 146,
  unit: "unit/words",
  partOfCollections: ["story-played/overwhere-ii"],
  position: 85,
  prose: "txt",
  characters: ["character-player/overwhere-ii-nala"],
  stepStatus: "step-status/recorders",
  action: "I bow and wait to be spoken to.",
  beats: [
    "Nala bows, and waits to be spoken to.",
    "The woman in the chair watches her a long moment without a word.",
    "She is lean and tall even seated, in a fine grey gown worn thin at the cuffs.",
    "Dark hair pinned tight, one streak of white in it. Pale eyes that go to Nala's hands, then her face.",
    "The air around the chair is cold. A thin skin of frost lies on its carved arms.",
    'Lady Varrow: "Nala. I am Imre Varrow."',
    "Her name, and straight on. Her voice is low and even.",
    'Lady Varrow: "Oswy Crake robbed my road for a year, and took three Talented off it."',
    'Lady Varrow: "That road was mine to keep. You kept it for me. I don\'t forget that."',
    "She lifts a hand. A servant steps forward with a silver bar on a square of grey cloth.",
    'Lady Varrow: "From the House. Take it."',
  ],
  issues: ['"She offers no more courtesy than that" - Plain Negation'],
  lore: [
    "lore/overwhere-ii-lady-imre-varrow",
    "lore/overwhere-ii-nala",
    "lore/overwhere-ii-nala-2",
    "lore/overwhere-ii-nala-3",
  ],
  reviewedBy: ["story-reviewer/continuity", "story-reviewer/style"],
  recordedBy: ["story-recorder/inventory"],
  endsAt: "2026-10-21T08:03:00.000Z",
} as const satisfies StoryTurnPlayed
