import type { StoryTurnPlayed } from "akasha/story/world/stories/played/turns/story-turn-played.page-type.types.ts"

export const overwhereIi00093 = {
  id: "01a0ff09-9736-7029-b1ee-efa78250d393",
  type: "page-type/story-turn-played",
  slug: "overwhere-ii-00-093",
  unit: "unit/words",
  partOfCollections: ["story-played/overwhere-ii"],
  position: 93,
  stepStatus: "step-status/writer",
  action: "I choose a spear, since that’s what I’m used to",
  beats: [
    "Nala takes an ash practice spear from the rack, its head capped in blunt leather.",
    "She sets her feet across from Osric, the spear's point level with his chest.",
    "Osric comes in roaring, the maul high, then crashing down overhead.",
    "Nala gives ground and keeps the point in his face. He swats it aside and comes on.",
    "A sweeping blow, fast for its weight. She slips back, a hand's breadth ahead of it.",
    "After each sweep his left flank hangs open for a heartbeat.",
    "She waits for the next sweep, then steps in under it.",
    "Her blunt point drives hard into his ribs: a clean touch.",
    "The maul's tail end still catches her side as it comes round, a dull, heavy thud.",
    "Her refined ribs take it. The ache spreads, then settles to a bruise.",
    "Osric staggers back, rubbing his ribs, and laughs like a bell.",
    'Osric: "Ha! She keeps you on the end of that stick like a boar."',
    'Hawise: "Clean touch. He caught you after it. Against a blade, that\'s your liver."',
    "Corra stops snapping sparks and watches Nala with narrowed eyes.",
    "Hawise takes two wooden short blades from the rack and steps into the court.",
    'Hawise: "My turn. Talents now, held light."',
  ],
  lore: ["lore/overwhere-ii-varrow-talented"],
  endsAt: "2026-10-22T07:00:00.000Z",
} as const satisfies StoryTurnPlayed
