import type { StoryTurnPlayed } from "akasha/story/world/stories/played/turns/story-turn-played.page-type.types.ts"

export const overwhereIi00096 = {
  id: "01a0ff3c-360a-70a6-8746-af27032f5800",
  type: "page-type/story-turn-played",
  slug: "overwhere-ii-00-096",
  ownLength: 210,
  unit: "unit/words",
  partOfCollections: ["story-played/overwhere-ii"],
  position: 96,
  prose: "txt",
  characters: ["character-player/overwhere-ii-nala"],
  stepStatus: "step-status/reviewers",
  action: "Same strategy",
  beats: [
    "Corra takes a wooden sword from the rack and comes in low and close.",
    "Nala meets her with the spear's point high, low, high, driving her back toward the well.",
    "Corra flicks a dipper of trough water across the flags between them. The stones go dark and wet.",
    "Nala shoves off the wet flags and slides half a step aside.",
    "A blue spark snaps along the wet stone after her and stings her heel.",
    "Nala's tide shoves at Corra's chest, a cold slap.",
    "Corra's fingers are sparking as it lands.",
    "The spark runs back up the tide like fire up a fuse, into Nala's palm.",
    "Her right hand goes numb to the wrist. The spear's shaft drops loose in her grip.",
    "Behind her eyes the tight ache throbs. Her next push slips and comes out a splash.",
    "Corra darts in under the sagging point and raps her wooden blade against Nala's ribs.",
    "A clean touch, on the same bruise.",
    "Corra steps back, grinning, sparks dancing on her knuckles.",
    'Corra: "Water carries, free blade."',
    "Osric roars with laughter. Hawise's mouth twitches.",
    "Feeling creeps back into Nala's hand, pins and needles to the fingertips.",
    'Hawise: "Your head\'s spent, and she knew your trick before you used it."',
    'Hawise: "Again, or done for today?"',
  ],
  lore: [
    "lore/overwhere-ii-nala",
    "lore/overwhere-ii-nala-2",
    "lore/overwhere-ii-nala-3",
    "lore/overwhere-ii-varrow-talented",
  ],
  reviewedBy: ["story-reviewer/style"],
  endsAt: "2026-10-22T07:15:00.000Z",
} as const satisfies StoryTurnPlayed
