import type { StoryTurnPlayed } from "akasha/story/world/stories/played/turns/story-turn-played.page-type.types.ts"

export const overwhereIi00090 = {
  id: "01a0fee3-1c6f-7f0a-8648-21dbf5d21140",
  type: "page-type/story-turn-played",
  slug: "overwhere-ii-00-090",
  ownLength: 192,
  unit: "unit/words",
  partOfCollections: ["story-played/overwhere-ii"],
  position: 90,
  prose: "txt",
  characters: ["character-player/overwhere-ii-nala"],
  stepStatus: "step-status/writer",
  action:
    "“I will not swear, but I will help if I can. I have refined my skin, muscles, and bones since meeting Garth and I still have room to grow, but I am lacking in guidance. I have a feeling I will need all the strength I can get to face whatever lies under that mountain. If you can help me grow my strength, I will stay to face it.”",
  beats: [
    'Nala: "I will not swear. But I will help, if I can."',
    'Nala: "I\'ve refined my skin, muscles and bones since meeting Garth, and I still have room to grow."',
    'Nala: "But I\'m lacking in guidance."',
    'Nala: "I have a feeling I\'ll need all the strength I can get"',
    'Nala: "to face whatever lies under that mountain."',
    'Nala: "If you can help me grow my strength, I will stay to face it."',
    "Lady Varrow's face stays exactly as it was. Only the frost on the chair arms glints.",
    "Then her pale eyes narrow, just slightly.",
    'Lady Varrow: "Skin, muscle and bone. Since Garth Marsh. That is three weeks."',
    'Lady Varrow: "Most Talented take years over that."',
    'Lady Varrow: "Then no oath. A lesser bond. You stay a free blade. The Keep calls on you at need."',
    'Lady Varrow: "A silver bar for every summons you answer."',
    'Lady Varrow: "And in return, the guidance you ask for. Mine, and this house\'s."',
    'Lady Varrow: "I have Descended twice. Refine your organs before you go down."',
    'Lady Varrow: "Few ever have the time, or the Water."',
    'Lady Varrow: "And spar with my Talented here. You have fought one Talent, and nearly died of it."',
    'Lady Varrow: "Learn to fight them well."',
    "She holds Nala's eyes, level and cold.",
    'Lady Varrow: "Will you take that bond?"',
  ],
  issues: [
    '"fought beasts and a thief. Learn to fight a Talent" - Crake, the thief, was a First Depth Talent',
  ],
  lore: [
    "lore/overwhere-ii-lady-imre-varrow",
    "lore/overwhere-ii-nala",
    "lore/overwhere-ii-nala-2",
    "lore/overwhere-ii-nala-3",
  ],
  reviewedBy: ["story-reviewer/style", "story-reviewer/continuity"],
  endsAt: "2026-10-21T08:38:00.000Z",
} as const satisfies StoryTurnPlayed
