import type { StoryTurnPlayed } from "akasha/story/world/stories/played/turns/story-turn-played.page-type.types.ts"

export const overwhereIi00077 = {
  id: "01a0fe33-e0be-7f88-8c1d-2db4a8e173aa",
  type: "page-type/story-turn-played",
  slug: "overwhere-ii-00-077",
  ownLength: 241,
  unit: "unit/words",
  partOfCollections: ["story-played/overwhere-ii"],
  position: 77,
  prose: "txt",
  characters: ["character-player/overwhere-ii-nala"],
  stepStatus: "step-status/recorders",
  action: "I sleep, giving my Locks time to recover",
  beats: [
    "Nala lies down in the straw, wrapped in Anni's cloak, the bars in her purse, and sleeps.",
    "She sleeps black and deep. No dream comes; not even the stair.",
    "Near dawn, something stirs her: a loosening in the soles of her feet.",
    "Penned Water rushes through them like a held breath let go, and the ache there eases.",
    "Then her palms open, one and then the other, the same rush, the same relief.",
    "Last of all her throat. The dull ache she has carried since dusk drains away.",
    "She sinks back under, and in that last hour of sleep the dream returns.",
    "The black stair, going down. The call from below, and it is louder than it has ever been.",
    "She wakes to grey light in the barn doorway, the Loddons stirring and Pells lifting the hurdle.",
    "Her Water is hers again; she can feel it, deep and full. But it moves stiff and slow.",
    "Her sense of the damp in the straw comes faint and slow, like a limb gone to sleep.",
    "The needle dart still hangs in the side of her neck, a small cold sting when she turns her head.",
    "Her mouth is parched, her tongue thick, her stomach a hollow knot.",
    "Outside, Dray is already on his feet, Harl roped between Col and Rob.",
    'Dray: "Morning. We march in a quarter hour. Half a day to the Ford, at the prisoners\' pace."',
  ],
  issues: [
    '"the bars in her coat" - Nala has no coat; she wears Anni\'s cloak and carries a leather purse',
  ],
  lore: [
    "lore/overwhere-ii-nala",
    "lore/overwhere-ii-nala-2",
    "lore/overwhere-ii-nala-3",
    "place/overwhere-ii-ashlin-farm",
  ],
  reviewedBy: ["story-reviewer/style", "story-reviewer/continuity"],
  recordedBy: ["story-recorder/inventory"],
  endsAt: "2026-10-15T06:00:00.000Z",
} as const satisfies StoryTurnPlayed
