import type { StoryTurnPlayed } from "akasha/story/world/stories/played/turns/story-turn-played.page-type.types.ts"

export const overwhereIi00110 = {
  id: "01a101cf-cf5d-75aa-9898-6ea5a0aef90a",
  type: "page-type/story-turn-played",
  slug: "overwhere-ii-00-110",
  unit: "unit/words",
  partOfCollections: ["story-played/overwhere-ii"],
  position: 110,
  stepStatus: "step-status/writer",
  action: "“Yes.” I hold out my hand.",
  beats: [
    'Nala: "Yes." She holds out her hand.',
    "Maud takes it in both of hers. Her palms are warm and rough.",
    "She shuts her eyes. Something light brushes at Nala's skin, then sinks deeper.",
    'Maud: "Skin, whole. Muscle, whole. Bone..." Her brows climb. "Every bone, whole."',
    'Maud: "Lungs. Gut. Liver." A breath. "Kidneys and the small ones still to come. And the heart."',
    'Maud: "A month? Keepers take years over what you\'ve done."',
    'Her touch moves inward, along Nala\'s threads. "Every tributary open. Carved, as if never shut."',
    "Then it slides down, into Nala's well.",
    "Maud's hands go still. Her breath stops.",
    "She draws her hands back as if from cold water, and sits quiet a long moment.",
    "Anselm looks from her to Nala and back. Hawise, by the door, has gone very still.",
    'Maud: "There\'s no floor to it. It just goes on down. Like looking into the Sea."',
    'Maud: "And it\'s straining. Pulling downward, as a well does when Descent is near."',
    'Maud: "You don\'t go down before that heart is refined, girl. Hear me?"',
    "She studies Nala's face with sharp blue eyes, the laughter gone out of them.",
    'Maud: "Now. Where did you come from? And where did you first wake?"',
  ],
  lore: ["lore/overwhere-ii-maud-ashby"],
  endsAt: "2026-10-26T21:08:00.000Z",
} as const satisfies StoryTurnPlayed
