import type { StoryTurnPlayed } from "akasha/story/world/stories/played/turns/story-turn-played.page-type.types.ts"

export const overwhereIi00024 = {
  id: "01a0f250-82a3-7488-85be-9db459b03685",
  type: "page-type/story-turn-played",
  slug: "overwhere-ii-00-024",
  ownLength: 368,
  unit: "unit/words",
  partOfCollections: ["story-played/overwhere-ii"],
  position: 24,
  prose: "txt",
  characters: ["character-player/overwhere-ii-nala"],
  stepStatus: "step-status/reviewers",
  action:
    "I run towards it and when I get close I pull on the reservoir of the beast while pushing on its flesh, then plant the spear directly in front of its charge.",
  beats: [
    "Nala runs at the she-wolf, spear in both hands, the flow roaring hot through her legs.",
    "The heather flies past; the she-wolf lengthens into a charge, huge and silent, jaws open.",
    "At ten paces Nala reaches with the tide for the bone chamber in the wolf's chest, and pulls.",
    "It is deep, far deeper than the others' were, and it fights her like a rope in a current.",
    "At the same moment she shoves with the push against the wolf's body, straight into her charge.",
    "Push and pull at once: the tide strains in two ways, and Nala feels it stretch to breaking.",
    "She holds it. The she-wolf's charge slows as if she runs through deep water, her legs going heavy.",
    "Nala drops to one knee and plants the spear butt in the turf, point up, square in the wolf's path.",
    "The she-wolf comes on anyway, too heavy to stop, and meets the braced point full in the chest.",
    "The iron head punches through scale and sinks deep; the crossbar slams up against her breast.",
    "Something bursts inside her: a cold gush of brine sprays from the wound, reeking of the sea.",
    "Even so, her jaws snap sideways as she falls, and catch Nala's left forearm.",
    "The teeth grind through the tough skin of her arm; hot pain, and blood runs to her fingers.",
    "Then the jaws go slack. The she-wolf slumps over the spear, and her milk-white eye goes dull.",
    "Nala wrenches her arm free, gasping. Inside her, something in the tide gives way once more.",
    "Push and pull no longer fight each other; she knows she can do both at once, whenever she wills.",
    "High on the fell, the rest of the pack begin to howl: thin, broken, fleeing howls.",
    "They fade away up the screes toward the tarn, and do not come back.",
    "Her well sloshes, brimming with cold foreign brine; it churns but does her no harm.",
    "Her forearm throbs, torn in a ragged crescent; under her sense, a thin sourness seeps in the wound.",
    "Behind her, the cottage door scrapes open, and Garth stands in it with a lantern, staring.",
  ],
  lore: [
    "lore/overwhere-ii-greymaws",
    "lore/overwhere-ii-keeper-anselm",
    "lore/overwhere-ii-nala",
    "lore/overwhere-ii-undertow",
  ],
  endsAt: "2026-09-29T18:04:00.000Z",
} as const satisfies StoryTurnPlayed
