import type { StoryTurnPlayed } from "akasha/story/world/stories/played/turns/story-turn-played.page-type.types.ts"

export const overwhereIi00067 = {
  id: "01a0fd84-862f-77bd-9a9c-933ea3062d90",
  type: "page-type/story-turn-played",
  slug: "overwhere-ii-00-067",
  ownLength: 287,
  unit: "unit/words",
  partOfCollections: ["story-played/overwhere-ii"],
  position: 67,
  prose: "txt",
  characters: ["character-player/overwhere-ii-nala"],
  stepStatus: "step-status/recorders",
  action:
    "I charge the voice with my spear, ready to Push an crossbow bolts coming for me and trusting to my reinforced skin and muscles, then use my tricks to get Cray through the chest with the spear, aiming for the heart and keeping him at a distance.",
  beats: [
    "Nala comes up off the mud and charges the barn door, spear levelled, Water ready to Push.",
    "In the loft the Loddons are still bent over their strings, winding; no bolt comes.",
    "Twenty paces of yard, and she crosses them in a heartbeat on her refined legs.",
    "In the dim of the barn stands a lean man, smiling, a ring of keys at his belt. Crake.",
    "She drives the cold-iron spear straight at his heart.",
    "He slips aside, quick, but not quick enough: the point takes him full in the chest.",
    "It does not sink. It grinds on rings under his jerkin, and a few burst loose.",
    "The blow lifts him off his feet and slams him back against a post. His breath goes out.",
    "His heart is armoured. She felt it: a coat of rings over his chest and belly.",
    "Crake doesn't fall. He comes off the post along the shaft, bare hands reaching for hers.",
    "Nala wrenches the spear back and around, and keeps his fingers off her own.",
    "But his left hand flicks from his cuff as he gives ground. Something stings her neck.",
    "A dart, needle-fine. It broke her refined skin, where the bolts would not have.",
    "Cold spreads from the prick, slow and heavy, like river silt seeping toward her Locks.",
    "This is the dart Dray warned of, the venom that chokes a Talent's Locks.",
    "It creeps through her the way the rot crept through Wren.",
    "Crake has backed out of spear's reach, rubbing his chest, still smiling.",
    'Crake: "There. Now we wait a minute, you and I."',
    "Overhead, two crossbow strings click home.",
  ],
  lore: [
    "lore/overwhere-ii-nala",
    "lore/overwhere-ii-nala-2",
    "lore/overwhere-ii-oswy-crake",
    "lore/overwhere-ii-oswy-crake-2",
    "place/overwhere-ii-ashlin-farm",
  ],
  reviewedBy: ["story-reviewer/continuity", "story-reviewer/style"],
  recordedBy: ["story-recorder/inventory", "story-recorder/mechanics"],
  endsAt: "2026-10-14T18:31:00.000Z",
} as const satisfies StoryTurnPlayed
