import type { StoryTurnPlayed } from "akasha/story/world/stories/played/turns/story-turn-played.page-type.types.ts"

export const overwhereIi00015 = {
  id: "01a0f1c9-4808-734e-b2a0-6e3527b3eb4a",
  type: "page-type/story-turn-played",
  slug: "overwhere-ii-00-015",
  ownLength: 340,
  unit: "unit/words",
  partOfCollections: ["story-played/overwhere-ii"],
  position: 15,
  prose: "txt",
  characters: ["character-player/overwhere-ii-nala"],
  stepStatus: "step-status/writer",
  action: "“Yes, if you’ll take me.”",
  beats: [
    '"Yes, if you\'ll take me."',
    "Goody is already out the door, shawl round her shoulders, moving fast for someone so bent.",
    "The mill is a stone's throw along the race: a big stone mill with a slate-hung house joined on.",
    "It is the finest building Nala has seen here; the great wheel turns and groans in the race.",
    "Goody hammers on the house door. A heavy, grey, hard-faced man opens it and fills the doorway.",
    '"Sedge," Goody says. "This is Nala. She\'s to see Tansy."',
    "Horne's eyes go over Nala: the loose shirt under a dead woman's cloak, the too-big boots.",
    '"Talented," he says flatly. "A stranger. I\'ve had my fill of promises."',
    '"She drew the rot out of Garth\'s Wren this morning," Goody snaps. "I\'ll vouch for her. Move."',
    "Horne looks at Garth; Garth nods once. Horne's jaw works, and then he steps aside.",
    "Up a stair, in a warm room, a girl of fourteen lies propped on pillows, grey-faced and sweating.",
    "A worn woman sits by the bed holding her good hand, and does not look up when they come in.",
    "Tansy's right arm lies on the blanket, bandaged; black veins crawl out above the wrappings.",
    "They run past her elbow toward her shoulder, and the room reeks of Goody's bitter poultice.",
    "Nala reaches with her tide, and her breath catches.",
    "This rot is nothing like Wren's small knot: it's a sour tangle soaked all through the arm.",
    "It is threaded deep in the girl's own life, strand around strand, far deeper than Wren's.",
    "And there is so much of it; it would heap far past what one palm could hold.",
    "Behind her, Horne's voice is low and hard. \"If you hurt her, Talented, I'll see you hang for it.\"",
    'The woman by the bed looks up at last, eyes red and raw. "Please," she whispers. "Please."',
  ],
  issues: [
    '"he says flatly, the way Garth did" - Garth never called her Talented; only Nala said it',
    "\"same bitter poultice you smelled at Garth's\" - no poultice was smelled at Garth's before",
  ],
  lore: [
    "lore/overwhere-ii-nala",
    "lore/overwhere-ii-wendle-ford-folk",
    "place/overwhere-ii-wendle-ford",
  ],
  reviewedBy: ["story-reviewer/style", "story-reviewer/continuity"],
  endsAt: "2026-09-29T09:58:00.000Z",
} as const satisfies StoryTurnPlayed
