import type { StoryTurnPlayed } from "akasha/story/world/stories/played/turns/story-turn-played.page-type.types.ts"

export const overwhereIi00097 = {
  id: "01a0ff47-f736-7993-98d4-bf327c7095fe",
  type: "page-type/story-turn-played",
  slug: "overwhere-ii-00-097",
  cover: "image/image-540e2a3946e130d0",
  ownLength: 311,
  unit: "unit/words",
  partOfCollections: ["story-played/overwhere-ii"],
  position: 97,
  prose: "txt",
  characters: ["character-player/overwhere-ii-nala"],
  stepStatus: "step-status/player",
  action: "“Done for today, need to focus on refining my organs.”",
  beats: "jsonl",
  lore: [
    "lore/overwhere-ii-keeper-anselm-2",
    "lore/overwhere-ii-lady-imre-varrow",
    "lore/overwhere-ii-nala",
    "lore/overwhere-ii-nala-2",
    "lore/overwhere-ii-nala-3",
    "place/overwhere-ii-callow-beck",
    "place/overwhere-ii-whitecombs",
  ],
  reviewedBy: ["story-reviewer/continuity", "story-reviewer/style"],
  recordedBy: [
    "story-recorder/inventory",
    "story-recorder/memory",
    "story-recorder/picture",
    "story-recorder/mechanics",
  ],
  endsAt: "2026-10-25T09:00:00.000Z",
  coverAfter: "Go to Callow Beck and hold it. Hawise goes with you.",
} as const satisfies StoryTurnPlayed
