import type { StoryTurnPlayed } from "akasha/story/world/stories/played/turns/story-turn-played.page-type.types.ts"

export const overwhereIi00066 = {
  id: "01a0fd76-f7bc-7755-a38f-691de67dd9c6",
  type: "page-type/story-turn-played",
  slug: "overwhere-ii-00-066",
  ownLength: 389,
  unit: "unit/words",
  partOfCollections: ["story-played/overwhere-ii"],
  position: 66,
  prose: "txt",
  characters: ["character-player/overwhere-ii-nala"],
  stepStatus: "step-status/recorders",
  action:
    "“I don’t know, but this way, you’ll at least have a chance to plead their case and a bit of goodwill to spend on them. If you can get them to surrender quietly, all the better, but don’t give away the trap, that would backfire and end with all of you dead.”",
  beats: [
    "Nala: \"I don't know, but this way you'll at least have a chance to plead their case.\"",
    'Nala: "And a bit of goodwill to spend on them."',
    'Nala: "If you can get them to surrender quietly, all the better."',
    'Nala: "But don\'t give away the trap. That would backfire and end with all of you dead."',
    "Bet is quiet a long moment, then nods, and her shoulders come down a little.",
    'Bet: "I won\'t give it away. I swear it." Her hands still shake.',
    'Bet: "Wil will listen to me. If it goes badly for Crake, I\'ll call to him."',
    "The light goes amber, then grey; the valley road turns off into a lane between high hedges.",
    "At the far end, a lamp burns in the window of a long, low stone farmhouse.",
    "Ashlin Farm: house on the left, stone barn on the right, an open yard of trodden mud between.",
    "The barn's hayloft door stands half open, black, looking straight down the lane.",
    "No crow has called from behind the barn yet.",
    "Nala walks the lane with Bet a step behind, the cold-iron spear easy on her shoulder.",
    "She steps out of the hedges' end, into the open yard, to stop and talk as Dray asked.",
    "Her refined ears catch it at once: the creak of a crossbow stock settling in the loft.",
    "And a second: a soft jangle of keys, from the dark doorway under the loft, inside the barn.",
    "Bet said Crake waits by the farmhouse hearth. Someone is in the barn, right below the loft.",
    "Two strings thrum. Nala is already moving, throwing herself sideways.",
    "Two bolts thud into the mud where her legs just stood, buried to the fletching.",
    "They were aimed low, at her legs, not her heart.",
    "Behind her, Bet presses flat against the hedge at the lane's mouth, untouched.",
    "In the loft, two shapes hunch over their crossbows, winding the strings back.",
    "Then, from the beck gully behind the barn: no crow's caw, but a man's roar.",
    "Iron rings on iron down in the trees. Someone was waiting on Dray's path.",
    "From the dark of the barn door, a soft, pleasant voice, almost smiling.",
    'The voice: "Nimble. They said you were. Put the spear down, healer, and nobody bleeds tonight."',
  ],
  issues: ['"everyone walks away whole tonight" - the beat has him say "nobody bleeds tonight"'],
  lore: [
    "lore/overwhere-ii-bet-loddon",
    "lore/overwhere-ii-nala",
    "lore/overwhere-ii-nala-2",
    "lore/overwhere-ii-oswy-crake",
    "lore/overwhere-ii-reeve-corwin-dray-2",
    "place/overwhere-ii-ashlin-farm",
  ],
  reviewedBy: ["story-reviewer/style", "story-reviewer/continuity"],
  recordedBy: ["story-recorder/inventory"],
  endsAt: "2026-10-14T18:30:00.000Z",
} as const satisfies StoryTurnPlayed
