import type { Domain } from "@akasha/domain-system/domain"

export const modelGateway = {
  id: "01a06227-7bc1-72a3-8056-41b5ba88f99d",
  pageTypeSlug: "domain",
  slug: "model-gateway",
  definition: "what sits between an agent and the model it is asking",
  partSlugs: [
    "module/account-picker",
    "module/account-walk",
    "module/anthropic-error-envelope",
    "module/auth-failed-retry",
    "module/bind-with-retry",
    "module/capacity-classification",
    "module/client-stream",
    "module/committed-keepalive",
    "module/committed-outcome",
    "module/extended-context-model",
    "module/fable-fallback",
    "module/fast-mode-strip",
    "module/forced-tool-choice",
    "module/forward",
    "module/fresh-credential",
    "module/hold-registry",
    "module/idle-timeout",
    "module/in-flight",
    "module/keepalive",
    "module/message-handler",
    "module/model-unavailable",
    "module/model-unavailable-rebind",
    "module/oauth-effects",
    "module/oauth-types",
    "module/observer-slot",
    "module/parse-boot-env",
    "module/parse-error-type",
    "module/peek-response",
    "module/permission-denied",
    "module/permission-denied-rebind",
    "module/pre-forward-queue",
    "module/proxy-entry",
    "module/proxy-headers",
    "module/proxy-process",
    "module/proxy-seats",
    "module/proxy-serving",
    "module/proxy-start",
    "module/queue-step",
    "module/rate-limit-refusal",
    "module/retry",
    "module/server-error",
    "module/server-error-retry",
    "module/sse-error-frame",
    "module/transport-log",
  ],
  invariants: [
    {
      invariantKind: "departure",
      statement: "A gateway serves one seat.",
    },
    {
      invariantKind: "departure",
      statement: "A gateway holds the credentials the seat never sees.",
    },
    {
      invariantKind: "departure",
      statement: "A gateway is spawned by a supervisor on this workstation rather than deployed.",
    },
    {
      invariantKind: "constraint",
      statement: "One thread carries every stream a gateway holds open.",
    },
    {
      invariantKind: "departure",
      statement: "Work a gateway does between two frames is work no stream is being served during.",
    },
  ],
} as const satisfies Domain
