import type { SkillTemplate } from "../character-skill-template/character-skill-template.module.code.ts"

export const CHARACTER_SKILLS_74 = {
  "vengeance-barrier": {
    id: "vengeance-barrier" as const,
    esoSkillId: 244725,
    name: "Vengeance Barrier",
    baseName: "Vengeance Barrier",
    skillLineId: "vengeance-alliance-war-support" as const,
    skillType: "ultimate" as const,
    description:
      "Invoke defensive tactics to protect yourself and up to 2 nearby group members with wards that each absorb up to |cffffff60375|r damage for |cffffff15|r seconds.",
    icon: "/esoui/art/icons/ability_ava_006.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 1,
    rank: 1,
    subcategoryId: "vengeance-alliance-war-support" as const,
  },
  "vengeance-bearer-s-inspiration": {
    id: "vengeance-bearer-s-inspiration" as const,
    esoSkillId: 238191,
    name: "Vengeance-Bearer's Inspiration",
    baseName: "Vengeance-Bearer's Inspiration",
    skillLineId: "vengeance-arcanist-herald-of-the-tome" as const,
    skillType: "active" as const,
    description:
      "Etch a series of runes onto your weapon that pulse with power, generating a Crux if you have none while granting you Minor Force for |cffffff20|r seconds, increasing your Critical Damage done by |cffffff10|r%.\n\nWhile slotted on either ability bar, gain Major Prophecy and Savagery, increasing your Spell and Weapon Critical rating by |cffffff2629|r.",
    icon: "/esoui/art/icons/ability_arcanist_005.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 1,
    rank: 1,
    subcategoryId: "vengeance-arcanist-herald-of-the-tome" as const,
  },
  "vengeance-berserker-strike": {
    id: "vengeance-berserker-strike" as const,
    esoSkillId: 240494,
    name: "Vengeance Berserker Strike",
    baseName: "Vengeance Berserker Strike",
    skillLineId: "vengeance-weapon-two-handed" as const,
    skillType: "ultimate" as const,
    description:
      "Strike at an enemy with a vicious blow, dealing |cffffff17640|r Physical Damage to them and up to 2 nearby enemies.\n\nThis attack cannot be mitigated and grants you |cffffff22081|r Physical and Spell Resistance for |cffffff12|r seconds.",
    icon: "/esoui/art/icons/ability_2handed_006.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 1,
    rank: 1,
    subcategoryId: "vengeance-weapon-two-handed" as const,
  },
  "vengeance-betty-netch": {
    id: "vengeance-betty-netch" as const,
    esoSkillId: 238020,
    name: "Vengeance Betty Netch",
    baseName: "Vengeance Betty Netch",
    skillLineId: "vengeance-warden-animal-companions" as const,
    skillType: "active" as const,
    description:
      "Call a betty netch to your side, which grants you Minor Berserk, increasing your damage done by |cffffff5|r% for |cffffff20|r seconds, and removing a negative effect from yourself.",
    icon: "/esoui/art/icons/ability_warden_017_a.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 1,
    rank: 1,
    subcategoryId: "vengeance-warden-animal-companions" as const,
  },
  "vengeance-bitter-harvest": {
    id: "vengeance-bitter-harvest" as const,
    esoSkillId: 238141,
    name: "Vengeance Bitter Harvest",
    baseName: "Vengeance Bitter Harvest",
    skillLineId: "vengeance-necromancer-bone-tyrant" as const,
    skillType: "active" as const,
    description:
      "Sap the lingering life from up to 3 fresh corpses, granting you |cffffff3|r Ultimate and healing |cffffff1508|r Health per corpse consumed. You also gain Major Protection for |cffffff10|r seconds, reducing your damage taken by |cffffff10|r%. \n\nThis ability can be activated once every |cffffff3|r seconds.",
    icon: "/esoui/art/icons/ability_necromancer_011.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 1,
    rank: 1,
    subcategoryId: "vengeance-necromancer-bone-tyrant" as const,
  },
  "vengeance-blade-cloak": {
    id: "vengeance-blade-cloak" as const,
    esoSkillId: 241188,
    name: "Vengeance Blade Cloak",
    baseName: "Vengeance Blade Cloak",
    skillLineId: "vengeance-weapon-dual-wield" as const,
    skillType: "active" as const,
    description:
      "Envelop yourself in a protective cloak of razors to gain Major Evasion, Minor Savagery, and Minor Prophecy for |cffffff20|r seconds, reducing damage taken from area attacks by |cffffff20|r% and increasing your Weapon and Spell Critical by |cffffff1314|r.",
    icon: "/esoui/art/icons/ability_dualwield_004.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 1,
    rank: 1,
    subcategoryId: "vengeance-weapon-dual-wield" as const,
  },
  "vengeance-blessing-of-protection": {
    id: "vengeance-blessing-of-protection" as const,
    esoSkillId: 246616,
    name: "Vengeance Blessing of Protection",
    baseName: "Vengeance Blessing of Protection",
    skillLineId: "vengeance-weapon-restoration-staff" as const,
    skillType: "active" as const,
    description:
      "Slam your staff down to activate its blessings, healing up to 3 of you and your allies in front of you for |cffffff12048|r Health.",
    icon: "/esoui/art/icons/ability_restorationstaff_003.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 1,
    rank: 1,
    subcategoryId: "vengeance-weapon-restoration-staff" as const,
  },
  "vengeance-blur": {
    id: "vengeance-blur" as const,
    esoSkillId: 237632,
    name: "Vengeance Blur",
    baseName: "Vengeance Blur",
    skillLineId: "vengeance-nightblade-shadow" as const,
    skillType: "active" as const,
    description:
      "Surround yourself in a phantasmic aura to gain Major Resolve and Minor Evasion, increasing your Physical and Spell Resistance by |cffffff5948|r and reducing your damage taken from area attacks by |cffffff10|r% for |cffffff20|r seconds.",
    icon: "/esoui/art/icons/ability_nightblade_009.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 1,
    rank: 1,
    subcategoryId: "vengeance-nightblade-shadow" as const,
  },
  "vengeance-bolstering-darkness": {
    id: "vengeance-bolstering-darkness" as const,
    esoSkillId: 237702,
    name: "Vengeance Bolstering Darkness",
    baseName: "Vengeance Bolstering Darkness",
    skillLineId: "vengeance-nightblade-shadow" as const,
    skillType: "ultimate" as const,
    description:
      "Conjure concealing shadow around you, granting you and up to 3 nearby allies invisibility for |cffffff4|r seconds and Major Protection for |cffffff10|r seconds, reducing damage taken by |cffffff10|r%.",
    icon: "/esoui/art/icons/ability_nightblade_015.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 1,
    rank: 1,
    subcategoryId: "vengeance-nightblade-shadow" as const,
  },
  "vengeance-bolt-escape": {
    id: "vengeance-bolt-escape" as const,
    esoSkillId: 237981,
    name: "Vengeance Bolt Escape",
    baseName: "Vengeance Bolt Escape",
    skillLineId: "vengeance-sorcerer-storm-calling" as const,
    skillType: "active" as const,
    description:
      "Transform yourself into pure energy and flash forward, stunning up to 3 enemies near your final location for |cffffff1|r second. \n\nThis effect cannot be blocked.",
    icon: "/esoui/art/icons/ability_sorcerer_bolt_escape.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 1,
    rank: 1,
    subcategoryId: "vengeance-sorcerer-storm-calling" as const,
  },
  "vengeance-bone-armor": {
    id: "vengeance-bone-armor" as const,
    esoSkillId: 246025,
    name: "Vengeance Bone Armor",
    baseName: "Vengeance Bone Armor",
    skillLineId: "vengeance-necromancer-bone-tyrant" as const,
    skillType: "active" as const,
    description:
      "Wrap yourself in hardened bone, granting you Major Resolve, increasing your Physical Resistance and Spell Resistance by |cffffff5948|r for |cffffff20|r seconds.\n\nYou also count as a corpse, up to once every |cffffff10|r seconds.",
    icon: "/esoui/art/icons/ability_necromancer_008.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 1,
    rank: 1,
    subcategoryId: "vengeance-necromancer-bone-tyrant" as const,
  },
  "vengeance-bone-goliath-transformation": {
    id: "vengeance-bone-goliath-transformation" as const,
    esoSkillId: 238236,
    name: "Vengeance Bone Goliath Transformation",
    baseName: "Vengeance Bone Goliath Transformation",
    skillLineId: "vengeance-necromancer-bone-tyrant" as const,
    skillType: "ultimate" as const,
    description:
      "Become a horrific Bone Goliath, increasing your Max Health by |cffffff70000|r for |cffffff15|r seconds and immediately restoring |cffffff70000|r Health.",
    icon: "/esoui/art/icons/ability_necromancer_012.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 1,
    rank: 1,
    subcategoryId: "vengeance-necromancer-bone-tyrant" as const,
  },
  "vengeance-bone-totem": {
    id: "vengeance-bone-totem" as const,
    esoSkillId: 238178,
    name: "Vengeance Bone Totem",
    baseName: "Vengeance Bone Totem",
    skillLineId: "vengeance-necromancer-bone-tyrant" as const,
    skillType: "active" as const,
    description:
      "Summon an effigy of bone at your feet after |cffffff2|r seconds. Once completed, the totem fears up to 3 nearby enemies, causing them to cower in place for |cffffff4|r seconds and become afflicted with Major Maim for |cffffff10|r seconds, reducing their damage done by |cffffff10|r%.",
    icon: "/esoui/art/icons/ability_necromancer_010.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 1,
    rank: 1,
    subcategoryId: "vengeance-necromancer-bone-tyrant" as const,
  },
  "vengeance-boneyard": {
    id: "vengeance-boneyard" as const,
    esoSkillId: 238095,
    name: "Vengeance Boneyard",
    baseName: "Vengeance Boneyard",
    skillLineId: "vengeance-necromancer-grave-lord" as const,
    skillType: "active" as const,
    description:
      "Desecrate the ground at the target location, dealing |cffffff8820|r Frost Damage to up to 3 enemies inside and applying Minor Vulnerability for |cffffff5|r seconds, increasing their damage taken by |cffffff5|r%.",
    icon: "/esoui/art/icons/ability_necromancer_004.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 1,
    rank: 1,
    subcategoryId: "vengeance-necromancer-grave-lord" as const,
  },
  "vengeance-bound-armor": {
    id: "vengeance-bound-armor" as const,
    esoSkillId: 237930,
    name: "Vengeance Bound Armor",
    baseName: "Vengeance Bound Armor",
    skillLineId: "vengeance-sorcerer-daedric-summoning" as const,
    skillType: "active" as const,
    description:
      "Protect yourself with the power of Oblivion, creating a suit of Daedric mail that grants Major Protection for |cffffff10|r seconds, reducing your damage taken by |cffffff10|r%.",
    icon: "/esoui/art/icons/ability_sorcerer_bound_armor.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 1,
    rank: 1,
    subcategoryId: "vengeance-sorcerer-daedric-summoning" as const,
  },
  "vengeance-caltrops": {
    id: "vengeance-caltrops" as const,
    esoSkillId: 244514,
    name: "Vengeance Caltrops",
    baseName: "Vengeance Caltrops",
    skillLineId: "vengeance-alliance-war-assault" as const,
    skillType: "active" as const,
    description:
      "Hurl a ball of caltrops that scatter over the target area, dealing |cffffff7056|r Physical Damage to up to 3 enemies inside, and reducing their Movement Speed by |cffffff50|r% for |cffffff4|r seconds.",
    icon: "/esoui/art/icons/ability_ava_001.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 1,
    rank: 1,
    subcategoryId: "vengeance-alliance-war-assault" as const,
  },
  "vengeance-chains-of-flame": {
    id: "vengeance-chains-of-flame" as const,
    esoSkillId: 237620,
    name: "Vengeance Chains of Flame",
    baseName: "Vengeance Chains of Flame",
    skillLineId: "vengeance-dragonknight-draconic-power" as const,
    skillType: "active" as const,
    description:
      "Launch a fiery chain to grasp and pull an enemy to you, dealing |cffffff6678|r Flame Damage.\n\nThis attack cannot be dodged or reflected.",
    icon: "/esoui/art/icons/ability_dragonknight_005.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 1,
    rank: 1,
    subcategoryId: "vengeance-dragonknight-draconic-power" as const,
  },
  "vengeance-chakram-shields": {
    id: "vengeance-chakram-shields" as const,
    esoSkillId: 238536,
    name: "Vengeance Chakram Shields",
    baseName: "Vengeance Chakram Shields",
    skillLineId: "vengeance-arcanist-curative-runeforms" as const,
    skillType: "active" as const,
    description:
      "Carve the runes of the Blind Man to call forth spinning mystical discs. Discs surround you or up to 2 allies in front of you, granting a shield that absorbs |cffffff8478|r damage for |cffffff6|r seconds.\n\nDiscs prefer your reticle target, or low-Health targets without shields.",
    icon: "/esoui/art/icons/ability_arcanist_015.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 1,
    rank: 1,
    subcategoryId: "vengeance-arcanist-curative-runeforms" as const,
  },
  "vengeance-circle-of-protection": {
    id: "vengeance-circle-of-protection" as const,
    esoSkillId: 246071,
    name: "Vengeance Circle of Protection",
    baseName: "Vengeance Circle of Protection",
    skillLineId: "vengeance-guild-fighters-guild" as const,
    skillType: "active" as const,
    description:
      "Brand the earth at your location with a rune of protection, granting up to 3 of you and your allies Major Protection, reducing their damage taken by |cffffff10|r% for |cffffff10|r seconds.",
    icon: "/esoui/art/icons/ability_fightersguild_001.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 1,
    rank: 1,
    subcategoryId: "vengeance-guild-fighters-guild" as const,
  },
} satisfies Record<string, SkillTemplate>
