export const summary =
  "Emit the pipeline-engine ServiceAccount, deploy ClusterRole and ClusterRoleBinding, and the ci namespace Role and RoleBinding, as one YAML document"

import type { CommandHelp } from "../ops/surface.ts"
import { errorMessage } from "../lib/check-workflow/error-message.ts"
import { exitOnToolError } from "../lib/check-workflow/violation-reporter.ts"
import { tupleOf, tupleSet } from "../lib/cluster-rbac/permissions.ts"
import { profileSources } from "../lib/cluster-rbac/profiles.ts"
import {
  CI_ROLE_NAME,
  ciRoleRules,
  clusterRoleRules,
  LABELS,
  SA_NAME,
  SA_NAMESPACE,
  SUBJECTS,
} from "../lib/cluster-rbac/rules.ts"
import {
  clusterRoleBinding,
  clusterRoleWithRules,
  namespacedRole,
  namespacedRoleBinding,
  serviceAccount,
} from "../lib/cluster-rbac/yaml-format.ts"
import { parseArgs } from "../lib/parse-args.ts"
import { AKASHA_ROOT_FLAG, surfaceRoots } from "../lib/workflow-surface/roots.ts"

export const help: CommandHelp = {
  flags: [AKASHA_ROOT_FLAG],
  exits: [
    { code: 0, meaning: "the manifest was written to stdout" },
    { code: 2, meaning: "the ClusterRole would not cover the Roles, or the profiles did not read" },
  ],
  examples: [
    "ops cluster-rbac-manifest",
    "ops cluster-rbac-manifest | kubectl apply -f -",
  ],
}

const PREFIX = "[cluster-rbac-manifest]"

const CLUSTER_ROLE_NAME = "pipeline-engine-cluster-deploy"

const HEADER = `# DO NOT EDIT — generated by \`ops cluster-rbac-manifest\`
# To modify RBAC permissions, update tools/lib/cluster-rbac/rules.ts for the
# ClusterRole, or the per-package profile under tools/lib/rbac for a namespace Role
`

export default async function clusterRbacManifest(args: readonly string[]): Promise<void> {
  const parsed = parseArgs(help, args)
  const roots = surfaceRoots({ instructionsRoot: parsed.string("--akasha-root") })

  const covered = tupleSet(clusterRoleRules, { skipNamed: true })
  const gaps: string[] = []
  try {
    for (const source of await profileSources(roots.instructionsRoot)) {
      for (const profile of source.profiles) {
        for (const rule of profile.rules) {
          for (const apiGroup of rule.apiGroups) {
            for (const resource of rule.resources) {
              for (const verb of rule.verbs) {
                if (covered.has(tupleOf(apiGroup, resource, verb))) continue
                gaps.push(
                  `${source.path} — ${profile.namespace}: { apiGroup: "${apiGroup}", ` +
                    `resource: "${resource}", verb: "${verb}" }`
                )
              }
            }
          }
        }
      }
    }
  } catch (err) {
    exitOnToolError({ error: new Error(errorMessage(err)), prefix: PREFIX })
  }

  if (gaps.length > 0) {
    exitOnToolError({
      error: new Error(
        `the ClusterRole about to be emitted does not cover ${gaps.length} permission(s) the ` +
          "namespace Roles grant, and applying it would leave the cluster refusing those Roles:\n  " +
          gaps.join("\n  ")
      ),
      prefix: PREFIX,
    })
  }

  const sections = [
    serviceAccount(SA_NAME, SA_NAMESPACE, LABELS),
    clusterRoleWithRules(CLUSTER_ROLE_NAME, LABELS, clusterRoleRules),
    clusterRoleBinding(CLUSTER_ROLE_NAME, LABELS, SUBJECTS),
    namespacedRole(CI_ROLE_NAME, SA_NAMESPACE, LABELS, ciRoleRules),
    namespacedRoleBinding(CI_ROLE_NAME, SA_NAMESPACE, LABELS, CI_ROLE_NAME, SUBJECTS),
  ]

  process.stdout.write(HEADER + sections.join("\n---\n") + "\n")
}
