import type { TemperSet } from "akasha/temper/catalog/gear/temper-set/temper-set.page-type.types.ts"

export const domihaus = {
  id: "019e6484-5ff2-7ceb-b39a-3b131132b67d",
  type: "page-type/temper-set",
  slug: "domihaus",
  title: "Domihaus",
  key: "domihaus",
  esoSetId: 342,
  esoItemIds: [128308, 128316, 128324, 128332, 128340, 128348],
  esoArmorTypes: ["ARMORTYPE_HEAVY", "ARMORTYPE_LIGHT", "ARMORTYPE_MEDIUM"],
  esoEquipTypes: ["EQUIP_TYPE_HEAD", "EQUIP_TYPE_SHOULDERS"],
  setWayshrines: [332, 332, 332],
  setVeteranEquipTypes: ["EQUIP_TYPE_HEAD"],
  setUndauntedChestId: 3,
  setTypeId: 8,
  setNameZh: "铎米豪斯",
  setNameRu: "Домихаус",
  setNameFr: "Domihaus",
  setNameEs: "Domihaus",
  setNameDe: "Domihaus",
  setDropZones: [974, 888, 888],
  setDropMechanics: [6],
  setDropLocationNamesEn: ["Domihaus the Bloody-Hornedin"],
  setDropLocationNamesDe: ["Domihaus der Blutgehörnte"],
  setDlcId: 7,
  itemBrowserSources: ["974:-103"],
  itemBrowserPlaceKinds: [3],
  itemBrowserItemId: 128309,
  category: "temper-set-category/monster",
  valid: ["monster"],
  bonuses: "jsonl",
  icons: "jsonl",
} as const satisfies TemperSet
