import type { LangTable } from "../craft-lang-lang-table/craft-lang-lang-table.module.code.ts"
import {
  intricate,
  LMB,
  MMB,
  ornate,
  RMB,
} from "../craft-lang-shared/craft-lang-shared.module.code.ts"

export const FR: LangTable = {
  options: {
    showbutton: "Bouton Show TemperCrafting",
    lockbutton: "Bouton Verrouiller TemperCrafting",
    lockelements: "Verrouiller les éléments TemperCrafting",
    closeonmove: "Fermer la fenêtre au déplacement du personnage",
    useartisan: "Utiliser Artisan (pas finalisé)",
    useflask: "Utiliser Flask (pas finalisé)",
    usequest: "Utiliser Quest",
    usecook: "Utiliser Cook",
    userune: "Utiliser Rune",
    displaystyles: "Afficher le style racial dans le tooltip",
    markitems: "Marquer les matériaux requis",
    showsymbols: `Marquer les équipements ${intricate}/${ornate} dans l'inventaire`,
    playrunevoice: "Jouer voix runiques enchanteur",
    marksetitems: "Marquer set-éléments pour la recherche",
    showstock: "Afficher le stock dans le tooltip",
    stacksplit: "Présélectionner l'empilement fractionné",
    markduplicates: "Autoriser le marquage des doublons pour la recherche",
    displayrunelevel: "Afficher le niveau de Rune dans le tooltip",
    displaymm: "Afficher Master Merchant dans le tooltips",
    displayttc: "Afficher Tamriel Trade Centre dans le tooltips",
    timeralarm: "Afficher l'alarme de la minuterie",
    mountalarm: "Afficher l'alarme de montage",
    researchalarm: "Afficher l'alarme de recherche",
    advancedcolorgrid: "Grille de couleur avancée",
    lockprotection: "Activer la protection de verrouillage",
    inspirationgain: "Afficher le gain d'inspiration",
    sortsets: "Trier les ensembles",
    sortstyles: "Trier les styles",
    bulkcraftlimit: "Limite de fabrication en vrac",
    overviewstyle: "Style de présentation du personnage",
    userunecreation: "Utiliser Rune Création",
    useruneextraction: "Utiliser Rune Extraction",
    userunerecipe: "Utiliser Rune Meubles",
    displayunknown: "Afficher l'inconnu dans le tooltips",
    displayknown: "Afficher connu dans le tooltips",
    displaycount: "Afficher les nombres connus/inconnus dans le tooltips",
  },
  suboptions: {
    sortstyles: ["Alphabétiquement", "Motif #", "Interne #"],
    sortsets: ["Alphabétiquement", "Traits"],
    alarms: ["Annoncer", "Bavarder", "Tous les deux", "éteint"],
    overviewstyle: ["Achevé", "Mince", "Minimal"],
  },
  TT: [
    `|cFFFFFF<<C:1>>|r\n${LMB} Sélectionner/désélectionner les recherches\n\n|t20:20:<<2>>|t |cFFFFFFToute la <<C:3>>|r\n${RMB} Sélectionner/désélectionner les recherches`,
    `|cE8DFAF${LMB} Créer x <<1>>|r`,
    `|cE8DFAF${RMB} Créer x <<1>>|r`,
    `|cE8DFAF${MMB} Marquer comme favoris |r|t16:16:esoui/art/characterwindow/equipmentbonusicon_full.dds|t`,
    `|cE8DFAF${LMB} Sélectionner`,
    `|cE8DFAF${RMB} Créer un lien dans le chat|r`,
    `|cE8DFAF${MMB} Marquer les ingrédients|r`,
    `|cE8DFAF${LMB} Affiner la glyphe|r`,
    `|cE8DFAF${LMB} Affiner tous les glyphes pas fabriqués\n${RMB} Affiner les glyphes tous disponibles|r`,
    `|cE8DFAF${LMB} Sélectionner ce personnage\n${RMB}Choisir ce personnage comme personnage principal\n${MMB} Supprimer ce personnage!`,
    "Favoris",
    "L'utilisation en mode rune",
    "Rechercher les styles connus",
    "Rechercher les recettes connus",
    "Afficher TemperCrafting",
    "Transactions disponibles avec le receleur et gains du jour",
    "Eyévéa - Utiliser le portail du bâtiment de la Guilde des Mages le plus proche",
    "Forgeterre - Utiliser le portail du bâtiment de la Guilde des Guerriers le plus proche",
    "Voyager vers l'Oratoire le plus proche de la station de fabrication du Set",
    "|cFFFFFFCompétence de monture|r\nCapacité et endurance\net Vitesse",
    ["Chaque Eaux", "Eaux Usées", "Débit", "Lac", "Ocean"],
    "Affiner les glyphes",
    "Ordonnance",
    "Meubles",
    "Trace les traits connus",
    `|cE8DFAF${LMB} Aperçu du mobilier|r`,
    `|cE8DFAF${RMB} Aperçu du mobilier|r`,
    `|cE8DFAF${RMB} Affiner la pile|r`,
    "|cFFFFFFPoints de compétences|r\nNon Dépensé/Total Gagné",
    "|cFFFFFFPC|r ",
    "|cFFFFFFÉclats célestes|r\nRecueilli/Total",
    "Suit les plans connus",
    `|cE8DFAF${MMB} Recherche|r`,
    `|cE8DFAF${LMB} Piste|r`,
    "Filet",
    "TemperCrafting Styles",
    "TemperCrafting Runes",
    "TemperCrafting Provisioning",
    "TemperCrafting Furnishings",
  ],
  nobagspace: "|cFF0000Pas assez d'espace d'inventaire!|r",
  noSlot: "|cFF0000Aucun emplacement de recherche gratuit ou élément inaccessible!|r",
  noItemPreview: "|cFF0000ItemPreview requis!|r",
  noFurnitureData: "|cFF0000ItemPreview manque de cet article.|r",
  blueprintSearchLimit: "|cFF0000Affinez votre recherche pour afficher tous les résultats.|r",
  removeCurrentCharacter: "|cFF0000Impossible de supprimer le personnage actuel.|r",
  searchfor: "Rechercher: ",
  finished: "complété",
  level: "Niveau",
  rank: "Rang",
  bank: "Banque",
  housebank: "Banque de maison ",
  guildbank: "Banque de guilde",
  craftbag: "Sac d'artisanat",
  chars: "Vue d'ensemble des personnage",
  set: "Sélectionner un Set...",
  unknown: "inconnu",
  knownStyles: "Styles connus",
  unknownStyles: "Styles inconnus",
  finishResearch: "<<C:1>> a terminé la recherche de |c00FF00<<C:2>>|r |c00FF88(<<C:3>>)|r.",
  finishMount: "<<C:1>> a fini l'entrainement de sa monture.",
  finish12: "Le compte à rebours de 12 heures a expiré.",
  finish24: "Le compte à rebours de 24 heures a expiré.",
  itemsearch: "Recherche: <<C:1>> | <<c:2>> ... Offres?",
  hideStyles: "Masquer simples",
  hideCrownStyles: "Masquer couronne",
  hideKnown: "Masquer connus",
  hideUnknown: "Masquer inconnu",
  unselectedWayshrine: "|cFF0000Choisissez un ensemble manufacturable.|r",
  unknownWayshrine: "|cFF0000Impossible de voyager vers des chemins inconnus.|r",
  previewType: ["Lourde", "Moyenne", "Legere + Peignoir", "Legere + Pourpoint"],
  styleNames: {},
  reload: "Nécessite un rechargement",
}
