import type { SkillTemplate } from "../character-skill-template/character-skill-template.module.code.ts"

export const CHARACTER_SKILLS_43 = {
  "miner-hireling": {
    id: "miner-hireling" as const,
    esoSkillId: 48171,
    name: "Miner Hireling",
    baseName: "Miner Hireling",
    skillLineId: "craft-blacksmithing" as const,
    skillType: "passive" as const,
    description:
      "A hireling will send you even more blacksmithing materials and possibly other items every day. You have a greater chance at better quality materials.",
    icon: "/esoui/art/icons/ability_smith_006.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 3,
    rank: 3,
    subcategoryId: "craft-blacksmithing" as const,
  },
  "mirage": {
    id: "mirage" as const,
    esoSkillId: 35916,
    name: "Mirage",
    baseName: "Blur",
    skillLineId: "nightblade-shadow" as const,
    skillType: "active" as const,
    description:
      "Surround yourself in a phantasmic aura to gain Major Evasion and Minor Resolve, reducing damage from area attacks by 20% and increasing your Physical and Spell Resistance by 2974 for 20 seconds.\n\nWhile active, taking direct damage reduces the cost of your next Roll Dodge by 10%, up to a maximum of 100%. This effect can stack up to once every half second.",
    icon: "/esoui/art/icons/ability_nightblade_009_a.dds",
    isMorph: true,
    morphIndex: 1,
    lineRankNeeded: 1,
    rank: 8,
    subcategoryId: "nightblade-shadow" as const,
  },
  "mirage-35414": {
    id: "mirage-35414" as const,
    esoSkillId: 35414,
    name: "Mirage",
    baseName: "Blur",
    skillLineId: "nightblade-shadow" as const,
    skillType: "active" as const,
    description:
      "Surround yourself in a phantasmic aura to gain Major Evasion and Minor Resolve, reducing damage from area attacks by |cffffff20|r% and increasing your Physical and Spell Resistance by |cffffff2974|r for |cffffff20|r seconds.\n\nWhile active, taking direct damage reduces the cost of your next Roll Dodge by |cffffff10|r%, up to a maximum of |cffffff100|r%. This effect can stack up to once every half second.",
    icon: "/esoui/art/icons/ability_nightblade_009_a.dds",
    isMorph: true,
    morphIndex: 1,
    lineRankNeeded: 1,
    rank: 1,
    subcategoryId: "nightblade-shadow" as const,
  },
  "mist-form": {
    id: "mist-form" as const,
    esoSkillId: 32986,
    name: "Mist Form",
    baseName: "Mist Form",
    skillLineId: "world-vampire" as const,
    skillType: "active" as const,
    description:
      "Disperse into a dark mist, causing the next |cffffff3|r projectiles to deal no damage to you for |cffffff1|r second while you dash forward and reappear at your target location after a short duration.\n\nCasting again within |cffffff4|r seconds costs |cffffff33|r% more Magicka.",
    icon: "/esoui/art/icons/ability_u26_vampire_05.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 9,
    rank: 9,
    subcategoryId: "world-vampire" as const,
  },
  "molten-armaments-31888": {
    id: "molten-armaments-31888" as const,
    esoSkillId: 31888,
    name: "Molten Armaments",
    baseName: "Molten Weapons",
    skillLineId: "dragonknight-earthen-heart" as const,
    skillType: "active" as const,
    description:
      "Charge you and your grouped allies' weapons with volcanic power to gain Major Brutality and Sorcery, increasing your Weapon and Spell Damage by |cffffff20|r% for |cffffff30|r seconds.\n\nWhile active, dealing damage with Light and Heavy Attacks causes an additional |cffffff1562|r Flame Damage, up to once every |cffffff1.5|r seconds.\n\nYou also gain Empower for the duration, increasing the damage of your Heavy Attacks against monsters by |cffffff70|r%.",
    icon: "/esoui/art/icons/ability_dragonknight_015_b.dds",
    isMorph: true,
    morphIndex: 2,
    lineRankNeeded: 4,
    rank: 4,
    subcategoryId: "dragonknight-earthen-heart" as const,
  },
  "molten-weapons": {
    id: "molten-weapons" as const,
    esoSkillId: 29043,
    name: "Molten Weapons",
    baseName: "Molten Weapons",
    skillLineId: "dragonknight-earthen-heart" as const,
    skillType: "active" as const,
    description:
      "Charge you and your grouped allies' weapons with volcanic power to gain Major Brutality and Sorcery, increasing your Weapon and Spell Damage by |cffffff20|r% for |cffffff30|r seconds.\n\nWhile active, dealing damage with Light and Heavy Attacks causes an additional |cffffff1562|r Flame Damage, up to once every |cffffff2|r seconds.",
    icon: "/esoui/art/icons/ability_dragonknight_015.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 4,
    rank: 4,
    subcategoryId: "dragonknight-earthen-heart" as const,
  },
  "molten-whip-20805": {
    id: "molten-whip-20805" as const,
    esoSkillId: 20805,
    name: "Molten Whip",
    baseName: "Lava Whip",
    skillLineId: "dragonknight-ardent-flame" as const,
    skillType: "active" as const,
    description:
      "Lash an enemy with flame, dealing |cffffff8342|r Flame Damage.\n\nActivating a different Dragonknight ability while in combat grants a stack of Seething Fury up to 3 times, increasing the damage of your next Molten Whip by |cffffff33|r% and your damage done by |cffffff5|r%, or |cffffff2|r% against players, for |cffffff10|r seconds. The damage done only activates if you are a Dragonknight.",
    icon: "/esoui/art/icons/ability_dragonknight_001_b.dds",
    isMorph: true,
    morphIndex: 1,
    lineRankNeeded: 1,
    rank: 1,
    subcategoryId: "dragonknight-ardent-flame" as const,
  },
  "momentum": {
    id: "momentum" as const,
    esoSkillId: 28297,
    name: "Momentum",
    baseName: "Momentum",
    skillLineId: "weapon-two-handed" as const,
    skillType: "active" as const,
    description:
      "Focus your strength and resolve to gain Major Brutality and Sorcery, increasing your Weapon and Spell Damage by |cffffff20|r%, as well as gaining Minor Endurance, increasing your Stamina Recovery by |cffffff15|r% for |cffffff30|r seconds.",
    icon: "/esoui/art/icons/ability_2handed_005.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 38,
    rank: 38,
    subcategoryId: "weapon-two-handed" as const,
  },
  "monarch": {
    id: "monarch" as const,
    esoSkillId: 39625,
    name: "Monarch",
    baseName: "Monarch",
    skillLineId: "alliance-war-emperor" as const,
    skillType: "passive" as const,
    description:
      "Increases your healing received while in your campaign, depending on how many Home Keeps you own.\n\n1 or less Keep: 25%\n2 Keeps: 30%\n3 Keeps: 35%\n4 Keeps: 40%\n5 Keeps: 45%\n6 Keeps: 50%",
    icon: "/esoui/art/icons/ability_sorcerer_060.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 1,
    rank: 1,
    subcategoryId: "alliance-war-emperor" as const,
    effects: [] as const,
    status: "unsupported" as const,
  },
  "mortal-coil": {
    id: "mortal-coil" as const,
    esoSkillId: 40118122,
    name: "Mortal Coil",
    baseName: "Restoring Tether",
    skillLineId: "necromancer-living-death" as const,
    skillType: "active" as const,
    description:
      "Siphon the last remnants of life from a corpse, healing for 5562 Health over 12 seconds to yourself and all allies between you and the corpse.  \n\nYou also restore 170 Magicka and Stamina every 2 seconds while siphoning the corpse.\n\nWhile slotted, your healing done is increased by 3%.",
    icon: "/esoui/art/icons/ability_necromancer_017_b.dds",
    isMorph: true,
    morphIndex: 2,
    lineRankNeeded: 42,
    rank: 12,
    subcategoryId: "necromancer-living-death" as const,
    effects: [
      {
        "metricId": "healing-done-base",
        "effectType": "fractional-change",
        "effectValue": 0.03,
        "slottedBehavior": "active-bar-only",
      },
    ] as const,
  },
  "mortal-coil-118122": {
    id: "mortal-coil-118122" as const,
    esoSkillId: 118122,
    name: "Mortal Coil",
    baseName: "Restoring Tether",
    skillLineId: "necromancer-living-death" as const,
    skillType: "active" as const,
    description:
      "Siphon the last remnants of life from a corpse, healing for |cffffff17514|r Health over |cffffff12|r seconds to yourself and all allies between you and the corpse.  \n\nYou also restore |cffffff170|r Magicka and Stamina every |cffffff2|r seconds while siphoning the corpse.\n\nWhile slotted, your healing done is increased by |cffffff3|r%.",
    icon: "/esoui/art/icons/ability_necromancer_017_b.dds",
    isMorph: true,
    morphIndex: 2,
    lineRankNeeded: 42,
    rank: 42,
    subcategoryId: "necromancer-living-death" as const,
  },
  "mountain-giant": {
    id: "mountain-giant" as const,
    esoSkillId: 29475,
    name: "Mountain Giant",
    baseName: "Mountain Giant",
    skillLineId: "dragonknight-earthen-heart" as const,
    skillType: "passive" as const,
    description:
      "The strength of mountains fuels your mightiest blows.\n\nDealing damage with a fully-charged Heavy Attack also applies Off Balance to the target.",
    icon: "/esoui/art/icons/ability_dragonknight_034.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 39,
    rank: 39,
    subcategoryId: "dragonknight-earthen-heart" as const,
  },
  "mystic-guard": {
    id: "mystic-guard" as const,
    esoSkillId: 63335,
    name: "Mystic Guard",
    baseName: "Guard",
    skillLineId: "alliance-war-support" as const,
    skillType: "active" as const,
    description:
      "Create a lifebond between you and an allied player. While bonded, 30% of the damage they take is instead redistributed to you.\n\nYou and your bonded ally also gain Minor Vitality, increasing your healing received and damage shield strength by 6%.\n\nThe bond will remain until you recast the spell or move more than 15 meters away from your ally.",
    icon: "/esoui/art/icons/ability_ava_mystic_guard.dds",
    isMorph: true,
    morphIndex: 1,
    lineRankNeeded: 5,
    rank: 8,
    subcategoryId: "alliance-war-support" as const,
  },
  "mystic-guard-61536": {
    id: "mystic-guard-61536" as const,
    esoSkillId: 61536,
    name: "Mystic Guard",
    baseName: "Guard",
    skillLineId: "alliance-war-support" as const,
    skillType: "active" as const,
    description:
      "Create a lifebond between you and an allied player. While bonded, |cffffff30|r% of the damage they take is instead redistributed to you.\n\nYou and your bonded ally also gain Minor Vitality, increasing your healing received and damage shield strength by |cffffff6|r%.\n\nThe bond will remain until you recast the spell or move more than |cffffff15|r meters away from your ally.",
    icon: "/esoui/art/icons/ability_ava_mystic_guard.dds",
    isMorph: true,
    morphIndex: 1,
    lineRankNeeded: 5,
    rank: 5,
    subcategoryId: "alliance-war-support" as const,
  },
  "mystic-orb": {
    id: "mystic-orb" as const,
    esoSkillId: 43415,
    name: "Mystic Orb",
    baseName: "Necrotic Orb",
    skillLineId: "guild-undaunted" as const,
    skillType: "active" as const,
    description:
      "Project a globe of annihilation that slowly floats forward, dealing 326 Magic Damage every 1 second to nearby enemies. \n\nWhile the orb is active you gain 100 Health, Magicka, and Stamina Recovery.\n\nAn ally near the globe can activate the Combustion synergy, causing the orb to explode for 2249 Magic Damage to nearby enemies and restore 3960 Magicka or Stamina to the ally, whichever maximum is higher.",
    icon: "/esoui/art/icons/ability_undaunted_004_a.dds",
    isMorph: true,
    morphIndex: 1,
    lineRankNeeded: 5,
    rank: 8,
    subcategoryId: "guild-undaunted" as const,
  },
  "mystic-orb-42028": {
    id: "mystic-orb-42028" as const,
    esoSkillId: 42028,
    name: "Mystic Orb",
    baseName: "Necrotic Orb",
    skillLineId: "guild-undaunted" as const,
    skillType: "active" as const,
    description:
      "Project a globe of annihilation that slowly floats forward, dealing |cffffff1136|r Magic Damage every |cffffff1|r second to nearby enemies. \n\nWhile the orb is active you gain |cffffff100|r Health, Magicka, and Stamina Recovery.\n\nAn ally near the globe can activate the Combustion synergy, causing the orb to explode for |cffffff8261|r Magic Damage to nearby enemies and restore |cffffff3960|r Magicka or Stamina to the ally, whichever maximum is higher.",
    icon: "/esoui/art/icons/ability_undaunted_004_a.dds",
    isMorph: true,
    morphIndex: 1,
    lineRankNeeded: 5,
    rank: 5,
    subcategoryId: "guild-undaunted" as const,
  },
  "mystic-siphon": {
    id: "mystic-siphon" as const,
    esoSkillId: 40118008,
    name: "Mystic Siphon",
    baseName: "Shocking Siphon",
    skillLineId: "necromancer-grave-lord" as const,
    skillType: "active" as const,
    description:
      "Violently drain the last spark of life from a corpse, dealing 6180 Shock Damage over 20 seconds to all enemies around the corpse and between you and the corpse. You also gain Major Savagery and Prophecy for 20 seconds, increasing your Weapon and Spell Critical rating by 2629.\n\nWhile siphoning the corpse you gain 150 Health, Magicka, and Stamina Recovery.\n\nWhile slotted, your damage done is increased by 3%.",
    icon: "/esoui/art/icons/ability_necromancer_005_a.dds",
    isMorph: true,
    morphIndex: 2,
    lineRankNeeded: 42,
    rank: 12,
    subcategoryId: "necromancer-grave-lord" as const,
    effects: [
      {
        "metricId": "damage-done-base",
        "effectType": "fractional-change",
        "effectValue": 0.03,
        "slottedBehavior": "active-bar-only",
      },
    ] as const,
  },
} satisfies Record<string, SkillTemplate>
