export {}

declare global {
  const SI_TEMPER_COMBAT_FAVOURITE_ADD: number
  const SI_TEMPER_COMBAT_FAVOURITE_REMOVE: number
  const SI_TEMPER_COMBAT_POSTBUFF: number
  const SI_TEMPER_COMBAT_POSTBUFF_BOSS: number
  const SI_TEMPER_COMBAT_POSTBUFF_GROUP: number
  const SI_TEMPER_COMBAT_COLLAPSE: number
  const SI_TEMPER_COMBAT_UNCOLLAPSE: number

  const SI_TEMPER_COMBAT_POSTUNITDPS: number
  const SI_TEMPER_COMBAT_POSTUNITNAMEDPS: number
  const SI_TEMPER_COMBAT_POSTSELECTIONDPS: number
  const SI_TEMPER_COMBAT_POSTSELECTIONHPS: number

  const SI_TEMPER_COMBAT_SHOWIDS: number
  const SI_TEMPER_COMBAT_HIDEIDS: number
  const SI_TEMPER_COMBAT_SHOWOVERHEAL: number
  const SI_TEMPER_COMBAT_HIDEOVERHEAL: number
  const SI_TEMPER_COMBAT_MENU_HIDEPETS: number
  const SI_TEMPER_COMBAT_POSTSINGLEDPS: number
  const SI_TEMPER_COMBAT_POSTSMARTDPS: number
  const SI_TEMPER_COMBAT_POSTMULTIDPS: number
  const SI_TEMPER_COMBAT_POSTALLDPS: number
  const SI_TEMPER_COMBAT_POSTHPS: number
  const SI_TEMPER_COMBAT_POSTDPS: number
  const SI_TEMPER_COMBAT_SETTINGS: number
  const SI_TEMPER_COMBAT_RECALCULATE: number
}
