import type { Domain } from "akasha/domain/domain.page-type.types.ts"

export const temperCharacterStat = {
  id: "01a0612f-aae6-7c1d-a590-b3004241a082",
  type: "page-type/domain",
  slug: "temper-character-stat",
  definition: "the character stats measuring an Elder Scrolls Online build",
  parts: [
    "module/buff-or-debuff-calculator",
    "module/buff-or-debuff-explainer",
    "module/buff-or-debuff-id",
    "module/build-state-adapter",
    "module/compare-stats",
    "module/diff-effect-sources",
    "module/extract-account",
    "module/extract-armor",
    "module/extract-attributes",
    "module/extract-champion-points",
    "module/extract-consumables",
    "module/extract-curse",
    "module/extract-jewelry",
    "module/extract-mundus",
    "module/extract-passives",
    "module/extract-sets",
    "module/extract-skills",
    "module/extract-target",
    "module/extract-weapons",
    "module/extractors",
    "module/format-effects",
    "module/formula-types",
    "module/metric-calculator",
    "module/metric-display-formula",
    "module/metric-formulas",
    "module/metric-template",
    "module/metric-tree",
    "module/metric-tree-queries",
    "module/metric-tree-types",
    "module/metric-value",
    "module/metric-value-types",
    "module/metrics",
    "module/passive-effect-resolution",
    "module/passive-eligibility",
    "module/pipeline-types",
    "module/source-lookup",
    "page-type/temper-metric",
    "module/metric-reading",
    "module/metric-formula-files",
  ],
} as const satisfies Domain
