import type { SetTemplate } from "@akasha/temper-equipment/set-template"

export const SETS_DATA_044: readonly SetTemplate[] = [
  {
    id: "hrothgars-chill",
    name: "Hrothgar's Chill",
    esoSetId: 618,
    subcategoryId: "pvp",
    valid: ["*:heavy"],
    bonuses: [
      {
        count: 2,
        status: "supported",
        effects: [{ metricId: "health-maximum", effectType: "integer", effectValue: 1206 }],
        description: "Adds 1206 Maximum Health",
      },
      {
        count: 3,
        status: "supported",
        effects: [{ metricId: "resistance", effectType: "integer", effectValue: 743 }],
        description: "Adds 1487 Armor",
      },
      {
        count: 4,
        status: "supported",
        effects: [{ metricId: "penetration", effectType: "integer", effectValue: 1487 }],
        description: "Adds 1487 Offensive Penetration",
      },
      {
        count: 5,
        status: "unsupported",
        effects: [],
        description:
          "Stunning or immobilizing your enemy causes them to burst with frost magic, applying the Chilled status effect and dealing 13% of their total Physical and Spell Resistance as Frost Damage to themselves and enemies within 8 meters of them. This effect can occur once every 7 seconds, ignores Spell Resistance, and cannot be blocked.",
      },
    ],
    icons: {
      "axe": "/esoui/art/icons/gear_breton_1haxe_d.dds",
      "battleaxe": "/esoui/art/icons/gear_breton_2haxe_d.dds",
      "bow": "/esoui/art/icons/gear_breton_bow_d.dds",
      "chest:*": "/esoui/art/icons/gear_breton_heavy_chest_d.dds",
      "dagger": "/esoui/art/icons/gear_breton_dagger_d.dds",
      "feet:*": "/esoui/art/icons/gear_breton_heavy_feet_d.dds",
      "greatsword": "/esoui/art/icons/gear_breton_2hsword_d.dds",
      "hands:*": "/esoui/art/icons/gear_breton_heavy_hands_d.dds",
      "head:*": "/esoui/art/icons/gear_breton_heavy_head_d.dds",
      "ice-staff": "/esoui/art/icons/gear_breton_staff_d.dds",
      "inferno-staff": "/esoui/art/icons/gear_breton_staff_d.dds",
      "legs:*": "/esoui/art/icons/gear_breton_heavy_legs_d.dds",
      "lightning-staff": "/esoui/art/icons/gear_breton_staff_d.dds",
      "mace": "/esoui/art/icons/gear_breton_1hhammer_d.dds",
      "maul": "/esoui/art/icons/gear_breton_2hhammer_d.dds",
      "necklace": "/esoui/art/icons/gear_breton_neck_a.dds",
      "restoration-staff": "/esoui/art/icons/gear_breton_staff_d.dds",
      "ring": "/esoui/art/icons/gear_breton_ring_a.dds",
      "shield": "/esoui/art/icons/gear_breton_shield_d.dds",
      "shoulders:*": "/esoui/art/icons/gear_breton_heavy_shoulders_d.dds",
      "sword": "/esoui/art/icons/gear_breton_1hsword_d.dds",
      "waist:*": "/esoui/art/icons/gear_breton_heavy_waist_d.dds",
    },
  },
  {
    id: "hundings-rage",
    name: "Hunding's Rage",
    esoSetId: 80,
    subcategoryId: "crafted",
    valid: ["*"],
    bonuses: [
      {
        count: 2,
        status: "supported",
        effects: [{ metricId: "critical-rating", effectType: "integer", effectValue: 657 }],
        description: "Adds 657 Critical Chance",
      },
      {
        count: 3,
        status: "supported",
        effects: [{ metricId: "stamina-maximum", effectType: "integer", effectValue: 1096 }],
        description: "Adds 1096 Maximum Stamina",
      },
      {
        count: 4,
        status: "supported",
        effects: [{ metricId: "critical-rating", effectType: "integer", effectValue: 657 }],
        description: "Adds 657 Critical Chance",
      },
      {
        count: 5,
        status: "supported",
        effects: [{ metricId: "power", effectType: "integer", effectValue: 300 }],
        description: "Adds 300 Weapon and Spell Damage",
      },
    ],
    icons: {
      "axe": "/esoui/art/icons/gear_breton_1haxe_d.dds",
      "battleaxe": "/esoui/art/icons/gear_breton_2haxe_d.dds",
      "bow": "/esoui/art/icons/gear_breton_bow_d.dds",
      "chest:heavy": "/esoui/art/icons/gear_breton_heavy_chest_d.dds",
      "chest:light": "/esoui/art/icons/gear_breton_light_robe_d.dds",
      "chest:medium": "/esoui/art/icons/gear_breton_medium_chest_d.dds",
      "dagger": "/esoui/art/icons/gear_breton_dagger_d.dds",
      "feet:heavy": "/esoui/art/icons/gear_breton_heavy_feet_d.dds",
      "feet:light": "/esoui/art/icons/gear_breton_light_feet_d.dds",
      "feet:medium": "/esoui/art/icons/gear_breton_medium_feet_d.dds",
      "greatsword": "/esoui/art/icons/gear_breton_2hsword_d.dds",
      "hands:heavy": "/esoui/art/icons/gear_breton_heavy_hands_d.dds",
      "hands:light": "/esoui/art/icons/gear_breton_light_hands_d.dds",
      "hands:medium": "/esoui/art/icons/gear_breton_medium_hands_d.dds",
      "head:heavy": "/esoui/art/icons/gear_breton_heavy_head_d.dds",
      "head:light": "/esoui/art/icons/gear_breton_light_head_d.dds",
      "head:medium": "/esoui/art/icons/gear_breton_medium_head_d.dds",
      "ice-staff": "/esoui/art/icons/gear_breton_staff_d.dds",
      "inferno-staff": "/esoui/art/icons/gear_breton_staff_d.dds",
      "legs:heavy": "/esoui/art/icons/gear_breton_heavy_legs_d.dds",
      "legs:light": "/esoui/art/icons/gear_breton_light_legs_d.dds",
      "legs:medium": "/esoui/art/icons/gear_breton_medium_legs_d.dds",
      "lightning-staff": "/esoui/art/icons/gear_breton_staff_d.dds",
      "mace": "/esoui/art/icons/gear_breton_1hhammer_d.dds",
      "maul": "/esoui/art/icons/gear_breton_2hhammer_d.dds",
      "necklace": "/esoui/art/icons/gear_breton_neck_a.dds",
      "restoration-staff": "/esoui/art/icons/gear_breton_staff_d.dds",
      "ring": "/esoui/art/icons/gear_breton_ring_a.dds",
      "shield": "/esoui/art/icons/gear_breton_shield_d.dds",
      "shoulders:heavy": "/esoui/art/icons/gear_breton_heavy_shoulders_d.dds",
      "shoulders:light": "/esoui/art/icons/gear_breton_light_shoulders_d.dds",
      "shoulders:medium": "/esoui/art/icons/gear_breton_medium_shoulders_d.dds",
      "sword": "/esoui/art/icons/gear_breton_1hsword_d.dds",
      "waist:heavy": "/esoui/art/icons/gear_breton_heavy_waist_d.dds",
      "waist:light": "/esoui/art/icons/gear_breton_light_waist_d.dds",
      "waist:medium": "/esoui/art/icons/gear_breton_medium_waist_d.dds",
    },
  },
  {
    id: "hunt-leader",
    name: "Hunt Leader",
    esoSetId: 216,
    subcategoryId: "arena",
    valid: ["*:medium"],
    bonuses: [
      {
        count: 2,
        status: "supported",
        effects: [{ metricId: "stamina-maximum", effectType: "integer", effectValue: 1096 }],
        description: "Adds 1096 Maximum Stamina",
      },
      {
        count: 3,
        status: "supported",
        effects: [{ metricId: "stamina-maximum", effectType: "integer", effectValue: 1096 }],
        description: "Adds 1096 Maximum Stamina",
      },
      {
        count: 4,
        status: "supported",
        effects: [{ metricId: "power", effectType: "integer", effectValue: 129 }],
        description: "Adds 129 Weapon and Spell Damage",
      },
      {
        count: 5,
        status: "unsupported",
        effects: [],
        description:
          "When your pets attack an enemy you have also attacked in the last 10 seconds, you heal for 2482 Health and restore 1216 Stamina. This effect can occur once every 5 seconds.",
      },
    ],
    icons: {
      "axe": "/esoui/art/icons/gear_malacath_1haxe_a.dds",
      "battleaxe": "/esoui/art/icons/gear_malacath_2haxe_a.dds",
      "bow": "/esoui/art/icons/gear_malacath_bow_a.dds",
      "chest:*": "/esoui/art/icons/gear_malacath_medium_chest_a.dds",
      "dagger": "/esoui/art/icons/gear_malacath_dagger_a.dds",
      "feet:*": "/esoui/art/icons/gear_malacath_medium_feet_a.dds",
      "greatsword": "/esoui/art/icons/gear_malacath_2hsword_a.dds",
      "hands:*": "/esoui/art/icons/gear_malacath_medium_hands_a.dds",
      "head:*": "/esoui/art/icons/gear_malacath_medium_head_a.dds",
      "ice-staff": "/esoui/art/icons/gear_malacath_staff_a.dds",
      "inferno-staff": "/esoui/art/icons/gear_malacath_staff_a.dds",
      "legs:*": "/esoui/art/icons/gear_malacath_medium_legs_a.dds",
      "lightning-staff": "/esoui/art/icons/gear_malacath_staff_a.dds",
      "mace": "/esoui/art/icons/gear_malacath_1hhammer_a.dds",
      "maul": "/esoui/art/icons/gear_malacath_2hhammer_a.dds",
      "necklace": "/esoui/art/icons/gear_imperial_neck_a.dds",
      "restoration-staff": "/esoui/art/icons/gear_malacath_staff_a.dds",
      "ring": "/esoui/art/icons/gear_imperial_ring_a.dds",
      "shield": "/esoui/art/icons/gear_malacath_shield_a.dds",
      "shoulders:*": "/esoui/art/icons/gear_malacath_medium_shoulders_a.dds",
      "sword": "/esoui/art/icons/gear_malacath_1hsword_a.dds",
      "waist:*": "/esoui/art/icons/gear_malacath_medium_waist_a.dds",
    },
  },
  {
    id: "huntsmans-warmask",
    name: "Huntsman's Warmask",
    esoSetId: 845,
    subcategoryId: "no-type",
    valid: ["head:medium"],
    bonuses: [
      {
        count: 1,
        status: "unsupported",
        effects: [],
        description:
          "Dealing damage with a Bash or fully-charged Heavy Attack places the Mark of Hircine on your target for 1 minute. While active, you gain Minor Berserk, increasing damage done by 5%, and deal 15% more damage to the target and 50% less damage to all other enemies. If the enemy dies while marked, you gain 2418 Stamina or Magicka, based off your highest maximum resource. This effect can trigger up to every 10 seconds.",
      },
    ],
    icons: { "head:*": "/esoui/art/icons/gear_hircinessnarlmask_head_a.dds" },
  },
  {
    id: "iceheart",
    name: "Iceheart",
    esoSetId: 274,
    subcategoryId: "monster",
    valid: ["monster"],
    bonuses: [
      {
        count: 1,
        status: "supported",
        effects: [{ metricId: "critical-rating", effectType: "integer", effectValue: 657 }],
        description: "Adds 657 Critical Chance",
      },
      {
        count: 2,
        status: "unsupported",
        effects: [],
        description:
          "When you deal Critical Damage, you have a 20% chance to gain a damage shield that absorbs 5000 damage for 6 seconds. While the damage shield holds, you deal 259 Frost damage to all enemies within 5 meters of you every 1 second. This effect can occur once every 6 seconds and the damage scales off the higher of your Weapon or Spell Damage.",
      },
    ],
    icons: {
      "head:heavy": "/esoui/art/icons/gear_undauntedatronach_head_a.dds",
      "head:light": "/esoui/art/icons/gear_undauntedatronach_head_a.dds",
      "head:medium": "/esoui/art/icons/gear_undauntedatronach_head_a.dds",
      "shoulders:heavy": "/esoui/art/icons/gear_undauntedatronach_shoulders_a.dds",
      "shoulders:light": "/esoui/art/icons/gear_undauntedatronach_shoulders_a.dds",
      "shoulders:medium": "/esoui/art/icons/gear_undauntedatronach_shoulders_a.dds",
    },
  },
  {
    id: "icy-conjurer",
    name: "Icy Conjurer",
    esoSetId: 431,
    subcategoryId: "dungeon",
    valid: ["*:light"],
    bonuses: [
      {
        count: 2,
        status: "supported",
        effects: [{ metricId: "magicka-maximum", effectType: "integer", effectValue: 1096 }],
        description: "Adds 1096 Maximum Magicka",
      },
      {
        count: 3,
        status: "supported",
        effects: [{ metricId: "power", effectType: "integer", effectValue: 129 }],
        description: "Adds 129 Weapon and Spell Damage",
      },
      {
        count: 4,
        status: "supported",
        effects: [{ metricId: "penetration", effectType: "integer", effectValue: 1487 }],
        description: "Adds 1487 Offensive Penetration",
      },
      {
        count: 5,
        status: "unsupported",
        effects: [],
        description:
          "Applying a minor debuff to your enemy summons a non-reflectable Ice Wraith that will charge into your enemy, dealing 3070 Frost damage over 10 seconds. This effect can occur every 10 seconds and scales off the higher of your Weapon or Spell Damage.",
      },
    ],
    icons: {
      "axe": "/esoui/art/icons/gear_coldsnap_1haxe_a.dds",
      "battleaxe": "/esoui/art/icons/gear_coldsnap_2haxe_a.dds",
      "bow": "/esoui/art/icons/gear_coldsnap_bow_a.dds",
      "chest:*": "/esoui/art/icons/gear_coldsnap_light_robe_a.dds",
      "dagger": "/esoui/art/icons/gear_coldsnap_dagger_a.dds",
      "feet:*": "/esoui/art/icons/gear_coldsnap_light_feet_a.dds",
      "greatsword": "/esoui/art/icons/gear_coldsnap_2hsword_a.dds",
      "hands:*": "/esoui/art/icons/gear_coldsnap_light_hand_a.dds",
      "head:*": "/esoui/art/icons/gear_coldsnap_light_head_a.dds",
      "ice-staff": "/esoui/art/icons/gear_coldsnap_staff_a.dds",
      "inferno-staff": "/esoui/art/icons/gear_coldsnap_staff_a.dds",
      "legs:*": "/esoui/art/icons/gear_coldsnap_light_legs_a.dds",
      "lightning-staff": "/esoui/art/icons/gear_coldsnap_staff_a.dds",
      "mace": "/esoui/art/icons/gear_coldsnap_1hhammer_a.dds",
      "maul": "/esoui/art/icons/gear_coldsnap_2hhammer_a.dds",
      "necklace": "/esoui/art/icons/gear_breton_neck_a.dds",
      "restoration-staff": "/esoui/art/icons/gear_coldsnap_staff_a.dds",
      "ring": "/esoui/art/icons/gear_breton_ring_a.dds",
      "shield": "/esoui/art/icons/gear_coldsnap_shield_a.dds",
      "shoulders:*": "/esoui/art/icons/gear_coldsnap_light_shoulder_a.dds",
      "sword": "/esoui/art/icons/gear_coldsnap_1hsword_a.dds",
      "waist:*": "/esoui/art/icons/gear_coldsnap_light_waist_a.dds",
    },
  },
]
