apiVersion: v1
kind: Secret
metadata:
    name: supabase-realtime-admin-secrets
    namespace: postgres
type: Opaque
stringData:
    SUPABASE_REALTIME_ADMIN_PASSWORD: ENC[AES256_GCM,data:/G+x+M5LzPnz7Np0DgzNSjRLweuJcPSmoT9CWMN+wGQ6AmKCQyZNCCw7MG0=,iv:NaWl2pafxoi7g6hVZpb6ePTZwjM+8Wbz4tadySiyVpg=,tag:zRn7QMc6F+52S4qOev3pgw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2TkllclFicm5KY21nVWJP
            VDVidVg3U2Z3RjRNT0ZodkxVa2lpYzI3VTJvCms3RXVYWGZ2Tzhrc3NIMFNrR093
            d3JTRHZkbDJMRWQ1WkZiWUhYWHlRMFEKLS0tIEJ2SkdzeDNlY29NMVB0ZXBDUnNS
            VE5FdVIwbVU1YUdjV1ljVktsK1dsalEK++5o9AQYAxbJpv3Gn+QDx3YmhHwj/kQS
            yQRBazfGkMXSShJ0nNQ3wEdmNc50ZdeQy56pAy1CO51d33T6QM5Jpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-22T23:56:28Z"
    mac: ENC[AES256_GCM,data:Y4KhYa/gSQ7QPAxfyrb6xf7yprSLsmTo3UCxbh+2Z1B+c6BTb6IuOWSZobRBniGbracL0P1TmyPaxyMU4LUZegZUNhtb7frDTMq9aULp+RK0Ukip2MiQW2/mOw+i26yNxXG9eSvaOnk9DSE4LTvANmdkabbEKfMP6Xb3RFmbEf4=,iv:w6YvogJB8xHIgnZrypzLBGqnr390gW0YW39bmKMJDVo=,tag:DLDbuy826QMnnDRLVn8kQA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
