import { parseLuaSavedVariablesFile } from "@akasha/temper-saved-variables/lua-parser"
import { serializeLuaBlock } from "@akasha/temper-saved-variables/lua-serializer"
import { z } from "zod"

const TOP_LEVEL_NAME = "TemperCatalogConfig"
const HEADER_COMMENT = "-- Auto-generated by Temper catalog invalidation; do not edit by hand."
const BLOCK_INDENT = "    "

export const SIDE_FILE_VERSION = 1

function coerceInvalidateDomains(value: unknown): unknown {
  if (Array.isArray(value)) return value
  if (value !== null && typeof value === "object" && Object.keys(value).length === 0) {
    return []
  }
  return value
}

const SideFileSchema = z.object({
  version: z.number().int().nonnegative(),
  invalidateVersion: z.number().int().nonnegative(),
  invalidateDomains: z.preprocess(coerceInvalidateDomains, z.array(z.string()).default([])),
})

export type SideFile = z.infer<typeof SideFileSchema>

export function parseSideFile(content: string): SideFile | undefined {
  const trimmed = content.trim()
  if (trimmed === "") return undefined
  if (/^TemperCatalogConfig\s*=\s*nil\s*$/m.test(trimmed)) return undefined

  let raw: Record<string, unknown>
  try {
    raw = parseLuaSavedVariablesFile(content, TOP_LEVEL_NAME)
  } catch {
    return undefined
  }
  const parsed = SideFileSchema.safeParse(raw)
  if (!parsed.success) return undefined
  return parsed.data
}

export function serializeSideFile(sf: SideFile): string {
  const lines: string[] = []
  lines.push(HEADER_COMMENT)
  lines.push(`${TOP_LEVEL_NAME} =`)
  lines.push("{")
  lines.push(`${BLOCK_INDENT}["version"] = ${sf.version},`)
  lines.push(`${BLOCK_INDENT}["invalidateVersion"] = ${sf.invalidateVersion},`)
  lines.push(...serializeLuaBlock("invalidateDomains", [...sf.invalidateDomains], BLOCK_INDENT))
  lines.push("}")
  lines.push("")
  return lines.join("\n")
}

export function computeNextSideFile(
  prev: SideFile | undefined,
  request: readonly string[],
  now: number = Date.now()
): SideFile {
  const priorVersion = prev?.invalidateVersion ?? 0
  const deduped = Array.from(new Set(request)).sort()
  return {
    version: SIDE_FILE_VERSION,
    invalidateVersion: Math.max(priorVersion + 1, now),
    invalidateDomains: deduped,
  }
}
