apiVersion: v1
kind: Secret
metadata:
    name: grafana-ro-password
    namespace: postgres
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:omlMTf8zf8lqxg==,iv:cXIUVWX3azjs96HvyBKwKKQwOK88ajueAtNKGFtwNco=,tag:QTl0vObYfH58Q/Le7oejrQ==,type:str]
    password: ENC[AES256_GCM,data:KrCBCS02xPaBn/atl2nyHsR/wFg/I9J66U9xyw6Xp0ZYOGHMqA24iQ==,iv:teYBIZ0ROLxIUL+hZPDziEs3G1InU/ii/tLf8eDkFWg=,tag:LlviHN0+8oEOZEo7qevPiQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwTGd0aTI1NkpweVU0MS9x
            VzlWNFJ4SEVxRllIUlVjNGcxazl2NTJzNVFFCmZ2elo4cjN1aS9UbUttTlVkYkVi
            SlpQWGhqaDNtNG5JOTA0MzBQQ3ZXV00KLS0tIE5NaTFJeE1mai80Z1g5M0pJTUtJ
            L29jelJQRnhCSzlZWjJoMVRVcDdKd0EK/aF2pK+/x+HDDmkUBOx+66Bz2ss/VOea
            eo/iZeHCDYXr0i+D+lvdCinEcosQl+Hxjy2SEwqiK2P4dmdEg8w5BA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-19T23:22:48Z"
    mac: ENC[AES256_GCM,data:U0/nw3dFoBgBmu3bp+FWMuR3FW3Db7RpmMW39xeRAgzmmd4ja2f5hYxiRNqNdm0L7ZZCEtde3Wms5zZjEJVMOHZ/U1ACFrdvEvjrpcPNUiSvQu8WwyZLpywesZ1ENHKxqY45leYh0jIe44PTMeKziyCTao56Wyxg76buUDNVE84=,iv:n1fhaUW746UWN+GIFTt8UT2pLSDhnpxORMVU9bslRwA=,tag:SLcHZyS+0Orqf5ZAiylsjQ==,type:str]
    version: 3.13.1
