apiVersion: v1
kind: Secret
metadata:
    name: postgres-secrets
    namespace: postgres
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:mouHHkpDCCDXSXjkkXmnJVGy+4DQNzPgEda8JSO6ZCkGdfpQaAzGi0WGuohjTojB8WoYbXPhaxLgjZkPihIUm3Mu0BpMag2WhQ+FyohmW0yOXZ9y11aVaj8JKiQaB8i/w4gDO4+rJyMm7icMKYEdkg==,iv:y4TgZy51RcjozWYW6ViXm6je3wcMYPJXWT1xZBkWRpk=,tag:7947I4OZBkV2NpBaI2WzmA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:HctnRG1WdrWMQt8L+3wRZCQdDo1ZWKT3JLygUGy4Cl+Euj/pokSIYw==,iv:VlnECwDHTgRejH0IhPKDHVlh76viXgI6Fx99a/uGEVI=,tag:YXa1hJzB0BybPfQ+Kolaeg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvaGJYUWJVNVZTSndNclYz
            L3BRTUVja05CNkg4dU5uUjYxaGRmbXdkYmk0CmNmcWNvKzd3RG9NQW56azBYY2lw
            c0xKYURGWVluMUM3aEcrOU9yRlN6alEKLS0tIHE3K2s1VW5MWEY2Q3RZLzBoRWJN
            RERwdld2Sy9BbHVjcndzSysxclhOZUUKeJakevZCJOd5MOgFWFbyzDvE6KknWO/n
            b3pbMluIFeiqnkzp218hz1wz4fwruUfwurGz0uMevD9zt7DViKh7CA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-04T14:23:35Z"
    mac: ENC[AES256_GCM,data:BCb1LPV0BblADge9DXvxTdJo+oohh7wGAsnBJ7vfh9XBF2QCFM5Jh3Owwl0MA81n1AMYoAu/TnfH9FmcPux2M9dxzrpHbJ2V+gWLlasbqp2MYXUweV7d9h38/X1gHR1XOtefbN5Ark492BQ2aytO2gI8GZmXSx+r60Bk24BVhys=,iv:fmQzkxHi6F9ySUfqS6930NBkwIc41uMXWrluhIy7NXg=,tag:423S3sQhYOn3JQmWg9An3w==,type:str]
    version: 3.9.4
