import type { TemperSet } from "akasha/temper/catalog/gear/temper-set/temper-set.page-type.types.ts"

export const slimecraw = {
  id: "019e6484-6017-776b-90d1-aba01af078e1",
  type: "page-type/temper-set",
  slug: "slimecraw",
  title: "Slimecraw",
  key: "slimecraw",
  esoSetId: 270,
  esoItemIds: [94500, 94636, 94772, 94908, 95044, 95180],
  esoArmorTypes: ["ARMORTYPE_HEAVY", "ARMORTYPE_LIGHT", "ARMORTYPE_MEDIUM"],
  esoEquipTypes: ["EQUIP_TYPE_HEAD", "EQUIP_TYPE_SHOULDERS"],
  setWayshrines: [189, 189, 189],
  setVeteranEquipTypes: ["EQUIP_TYPE_HEAD"],
  setUndauntedChestId: 2,
  setTypeId: 8,
  setNameZh: "黏爪",
  setNameRu: "Слизебрюх",
  setNameFr: "Rampefange",
  setNameEs: "Zarpa Embarrada",
  setNameDe: "Schleimkropf",
  setDropZones: [146, 19, 19],
  setDropMechanics: [6],
  setDropLocationNamesEn: ["Varaine and Allene Pellingare"],
  setDropLocationNamesDe: ["Varaine und Allene Pellingare"],
  setDlcId: 0,
  itemBrowserSources: ["146:-101"],
  itemBrowserPlaceKinds: [3],
  itemBrowserItemId: 94501,
  category: "temper-set-category/monster",
  valid: ["monster"],
  bonuses: "jsonl",
  icons: "jsonl",
} as const satisfies TemperSet
