import type { LoreCollectionEntry } from "../lore-library-types/lore-library-types.module.code.ts"

export const LORE_COLLECTIONS_04: readonly LoreCollectionEntry[] = [
  {
    collectionIndex: 19,
    name: "Ebony Style",
    books: [
      { bookIndex: 1, name: "Crafting Motif 37: Ebony Axes" },
      { bookIndex: 2, name: "Crafting Motif 37: Ebony Belts" },
      { bookIndex: 3, name: "Crafting Motif 37: Ebony Boots" },
      { bookIndex: 4, name: "Crafting Motif 37: Ebony Bows" },
      { bookIndex: 5, name: "Crafting Motif 37: Ebony Chests" },
      { bookIndex: 6, name: "Crafting Motif 37: Ebony Daggers" },
      { bookIndex: 7, name: "Crafting Motif 37: Ebony Gloves" },
      { bookIndex: 8, name: "Crafting Motif 37: Ebony Helmets" },
      { bookIndex: 9, name: "Crafting Motif 37: Ebony Legs" },
      { bookIndex: 10, name: "Crafting Motif 37: Ebony Maces" },
      { bookIndex: 11, name: "Crafting Motif 37: Ebony Shields" },
      { bookIndex: 12, name: "Crafting Motif 37: Ebony Shoulders" },
      { bookIndex: 13, name: "Crafting Motif 37: Ebony Staves" },
      { bookIndex: 14, name: "Crafting Motif 37: Ebony Swords" },
    ],
  },
  {
    collectionIndex: 20,
    name: "Assassins League Style",
    books: [
      { bookIndex: 1, name: "Crafting Motif 34: Assassins League Axes" },
      { bookIndex: 2, name: "Crafting Motif 34: Assassins League Belts" },
      { bookIndex: 3, name: "Crafting Motif 34: Assassins League Boots" },
      { bookIndex: 4, name: "Crafting Motif 34: Assassins League Bows" },
      { bookIndex: 5, name: "Crafting Motif 34: Assassins League Chests" },
      { bookIndex: 6, name: "Crafting Motif 34: Assassins League Daggers" },
      { bookIndex: 7, name: "Crafting Motif 34: Assassins League Gloves" },
      { bookIndex: 8, name: "Crafting Motif 34: Assassins League Helmets" },
      { bookIndex: 9, name: "Crafting Motif 34: Assassins League Legs" },
      { bookIndex: 10, name: "Crafting Motif 34: Assassins League Maces" },
      { bookIndex: 11, name: "Crafting Motif 34: Assassins League Shields" },
      { bookIndex: 12, name: "Crafting Motif 34: Assassins League Shoulders" },
      { bookIndex: 13, name: "Crafting Motif 34: Assassins League Staves" },
      { bookIndex: 14, name: "Crafting Motif 34: Assassins League Swords" },
    ],
  },
  {
    collectionIndex: 21,
    name: "Thieves Guild Style",
    books: [
      { bookIndex: 1, name: "Crafting Motif 33: Thieves Guild Axes" },
      { bookIndex: 2, name: "Crafting Motif 33: Thieves Guild Belts" },
      { bookIndex: 3, name: "Crafting Motif 33: Thieves Guild Boots" },
      { bookIndex: 4, name: "Crafting Motif 33: Thieves Guild Bows" },
      { bookIndex: 5, name: "Crafting Motif 33: Thieves Guild Chests" },
      { bookIndex: 6, name: "Crafting Motif 33: Thieves Guild Daggers" },
      { bookIndex: 7, name: "Crafting Motif 33: Thieves Guild Gloves" },
      { bookIndex: 8, name: "Crafting Motif 33: Thieves Guild Helmets" },
      { bookIndex: 9, name: "Crafting Motif 33: Thieves Guild Legs" },
      { bookIndex: 10, name: "Crafting Motif 33: Thieves Guild Maces" },
      { bookIndex: 11, name: "Crafting Motif 33: Thieves Guild Shields" },
      { bookIndex: 12, name: "Crafting Motif 33: Thieves Guild Shoulders" },
      { bookIndex: 13, name: "Crafting Motif 33: Thieves Guild Staves" },
      { bookIndex: 14, name: "Crafting Motif 33: Thieves Guild Swords" },
    ],
  },
  {
    collectionIndex: 22,
    name: "Abah's Watch Style",
    books: [
      { bookIndex: 1, name: "Crafting Motif 32: Abah's Watch Axes" },
      { bookIndex: 2, name: "Crafting Motif 32: Abah's Watch Belts" },
      { bookIndex: 3, name: "Crafting Motif 32: Abah's Watch Boots" },
      { bookIndex: 4, name: "Crafting Motif 32: Abah's Watch Bows" },
      { bookIndex: 5, name: "Crafting Motif 32: Abah's Watch Chests" },
      { bookIndex: 6, name: "Crafting Motif 32: Abah's Watch Daggers" },
      { bookIndex: 7, name: "Crafting Motif 32: Abah's Watch Gloves" },
      { bookIndex: 8, name: "Crafting Motif 32: Abah's Watch Helmets" },
      { bookIndex: 9, name: "Crafting Motif 32: Abah's Watch Legs" },
      { bookIndex: 10, name: "Crafting Motif 32: Abah's Watch Maces" },
      { bookIndex: 11, name: "Crafting Motif 32: Abah's Watch Shields" },
      { bookIndex: 12, name: "Crafting Motif 32: Abah's Watch Shoulders" },
      { bookIndex: 13, name: "Crafting Motif 32: Abah's Watch Staves" },
      { bookIndex: 14, name: "Crafting Motif 32: Abah's Watch Swords" },
    ],
  },
  {
    collectionIndex: 23,
    name: "Draugr Style",
    books: [
      { bookIndex: 1, name: "Crafting Motif 38: Draugr Axes" },
      { bookIndex: 2, name: "Crafting Motif 38: Draugr Belts" },
      { bookIndex: 3, name: "Crafting Motif 38: Draugr Boots" },
      { bookIndex: 4, name: "Crafting Motif 38: Draugr Bows" },
      { bookIndex: 5, name: "Crafting Motif 38: Draugr Chests" },
      { bookIndex: 6, name: "Crafting Motif 38: Draugr Daggers" },
      { bookIndex: 7, name: "Crafting Motif 38: Draugr Gloves" },
      { bookIndex: 8, name: "Crafting Motif 38: Draugr Helmets" },
      { bookIndex: 9, name: "Crafting Motif 38: Draugr Legs" },
      { bookIndex: 10, name: "Crafting Motif 38: Draugr Maces" },
      { bookIndex: 11, name: "Crafting Motif 38: Draugr Shields" },
      { bookIndex: 12, name: "Crafting Motif 38: Draugr Shoulders" },
      { bookIndex: 13, name: "Crafting Motif 38: Draugr Staves" },
      { bookIndex: 14, name: "Crafting Motif 38: Draugr Swords" },
    ],
  },
  {
    collectionIndex: 24,
    name: "Minotaur Style",
    books: [
      { bookIndex: 1, name: "Crafting Motif 39: Minotaur Axes" },
      { bookIndex: 2, name: "Crafting Motif 39: Minotaur Belts" },
      { bookIndex: 3, name: "Crafting Motif 39: Minotaur Boots" },
      { bookIndex: 4, name: "Crafting Motif 39: Minotaur Bows" },
      { bookIndex: 5, name: "Crafting Motif 39: Minotaur Chests" },
      { bookIndex: 6, name: "Crafting Motif 39: Minotaur Daggers" },
      { bookIndex: 7, name: "Crafting Motif 39: Minotaur Gloves" },
      { bookIndex: 8, name: "Crafting Motif 39: Minotaur Helmets" },
      { bookIndex: 9, name: "Crafting Motif 39: Minotaur Legs" },
      { bookIndex: 10, name: "Crafting Motif 39: Minotaur Maces" },
      { bookIndex: 11, name: "Crafting Motif 39: Minotaur Shields" },
      { bookIndex: 12, name: "Crafting Motif 39: Minotaur Shoulders" },
      { bookIndex: 13, name: "Crafting Motif 39: Minotaur Staves" },
      { bookIndex: 14, name: "Crafting Motif 39: Minotaur Swords" },
    ],
  },
  {
    collectionIndex: 25,
    name: "Order Hour Style",
    books: [
      { bookIndex: 1, name: "Crafting Motif 40: Order Hour Axes" },
      { bookIndex: 2, name: "Crafting Motif 40: Order Hour Belts" },
      { bookIndex: 3, name: "Crafting Motif 40: Order Hour Boots" },
      { bookIndex: 4, name: "Crafting Motif 40: Order Hour Bows" },
      { bookIndex: 5, name: "Crafting Motif 40: Order Hour Chests" },
      { bookIndex: 6, name: "Crafting Motif 40: Order Hour Daggers" },
      { bookIndex: 7, name: "Crafting Motif 40: Order Hour Gloves" },
      { bookIndex: 8, name: "Crafting Motif 40: Order Hour Helmets" },
      { bookIndex: 9, name: "Crafting Motif 40: Order Hour Legs" },
      { bookIndex: 10, name: "Crafting Motif 40: Order Hour Maces" },
      { bookIndex: 11, name: "Crafting Motif 40: Order Hour Shields" },
      { bookIndex: 12, name: "Crafting Motif 40: Order Hour Shoulders" },
      { bookIndex: 13, name: "Crafting Motif 40: Order Hour Staves" },
      { bookIndex: 14, name: "Crafting Motif 40: Order Hour Swords" },
    ],
  },
  {
    collectionIndex: 26,
    name: "Celestial Style",
    books: [
      { bookIndex: 1, name: "Crafting Motif 41: Celestial Axes" },
      { bookIndex: 2, name: "Crafting Motif 41: Celestial Belts" },
      { bookIndex: 3, name: "Crafting Motif 41: Celestial Boots" },
      { bookIndex: 4, name: "Crafting Motif 41: Celestial Bows" },
      { bookIndex: 5, name: "Crafting Motif 41: Celestial Chests" },
      { bookIndex: 6, name: "Crafting Motif 41: Celestial Daggers" },
      { bookIndex: 7, name: "Crafting Motif 41: Celestial Gloves" },
      { bookIndex: 8, name: "Crafting Motif 41: Celestial Helmets" },
      { bookIndex: 9, name: "Crafting Motif 41: Celestial Legs" },
      { bookIndex: 10, name: "Crafting Motif 41: Celestial Maces" },
      { bookIndex: 11, name: "Crafting Motif 41: Celestial Shields" },
      { bookIndex: 12, name: "Crafting Motif 41: Celestial Shoulders" },
      { bookIndex: 13, name: "Crafting Motif 41: Celestial Staves" },
      { bookIndex: 14, name: "Crafting Motif 41: Celestial Swords" },
    ],
  },
  {
    collectionIndex: 27,
    name: "Hollowjack Style",
    books: [
      { bookIndex: 1, name: "Crafting Motif 42: Hollowjack Axes" },
      { bookIndex: 2, name: "Crafting Motif 42: Hollowjack Belts" },
      { bookIndex: 3, name: "Crafting Motif 42: Hollowjack Boots" },
      { bookIndex: 4, name: "Crafting Motif 42: Hollowjack Bows" },
      { bookIndex: 5, name: "Crafting Motif 42: Hollowjack Chests" },
      { bookIndex: 6, name: "Crafting Motif 42: Hollowjack Daggers" },
      { bookIndex: 7, name: "Crafting Motif 42: Hollowjack Gloves" },
      { bookIndex: 8, name: "Crafting Motif 42: Hollowjack Helmets" },
      { bookIndex: 9, name: "Crafting Motif 42: Hollowjack Legs" },
      { bookIndex: 10, name: "Crafting Motif 42: Hollowjack Maces" },
      { bookIndex: 11, name: "Crafting Motif 42: Hollowjack Shields" },
      { bookIndex: 12, name: "Crafting Motif 42: Hollowjack Shoulders" },
      { bookIndex: 13, name: "Crafting Motif 42: Hollowjack Staves" },
      { bookIndex: 14, name: "Crafting Motif 42: Hollowjack Swords" },
    ],
  },
  {
    collectionIndex: 28,
    name: "Dark Brotherhood Style",
    books: [
      { bookIndex: 1, name: "Crafting Motif 36: Dark Brotherhood Axes" },
      { bookIndex: 2, name: "Crafting Motif 36: Dark Brotherhood Belts" },
      { bookIndex: 3, name: "Crafting Motif 36: Dark Brotherhood Boots" },
      { bookIndex: 4, name: "Crafting Motif 36: Dark Brotherhood Bows" },
      { bookIndex: 5, name: "Crafting Motif 36: Dark Brotherhood Chests" },
      { bookIndex: 6, name: "Crafting Motif 36: Dark Brotherhood Daggers" },
      { bookIndex: 7, name: "Crafting Motif 36: Dark Brotherhood Gloves" },
      { bookIndex: 8, name: "Crafting Motif 36: Dark Brotherhood Helmets" },
      { bookIndex: 9, name: "Crafting Motif 36: Dark Brotherhood Legs" },
      { bookIndex: 10, name: "Crafting Motif 36: Dark Brotherhood Maces" },
      { bookIndex: 11, name: "Crafting Motif 36: Dark Brotherhood Shields" },
      { bookIndex: 12, name: "Crafting Motif 36: Dark Brotherhood Shoulders" },
      { bookIndex: 13, name: "Crafting Motif 36: Dark Brotherhood Staves" },
      { bookIndex: 14, name: "Crafting Motif 36: Dark Brotherhood Swords" },
    ],
  },
  {
    collectionIndex: 29,
    name: "",
    books: [
      { bookIndex: 1, name: "Crafting Motif 43: Grim Harlequin Axes" },
      { bookIndex: 2, name: "Crafting Motif 43: Grim Harlequin Belts" },
      { bookIndex: 3, name: "Crafting Motif 43: Grim Harlequin Boots" },
      { bookIndex: 4, name: "Crafting Motif 43: Grim Harlequin Bows" },
      { bookIndex: 5, name: "Crafting Motif 43: Grim Harlequin Chests" },
      { bookIndex: 6, name: "Crafting Motif 43: Grim Harlequin Daggers" },
      { bookIndex: 7, name: "Crafting Motif 43: Grim Harlequin Gloves" },
      { bookIndex: 8, name: "Crafting Motif 43: Grim Harlequin Helmets" },
      { bookIndex: 9, name: "Crafting Motif 43: Grim Harlequin Legs" },
      { bookIndex: 10, name: "Crafting Motif 43: Grim Harlequin Maces" },
      { bookIndex: 11, name: "Crafting Motif 43: Grim Harlequin Shields" },
      { bookIndex: 12, name: "Crafting Motif 43: Grim Harlequin Shoulders" },
      { bookIndex: 13, name: "Crafting Motif 43: Grim Harlequin Staves" },
      { bookIndex: 14, name: "Crafting Motif 43: Grim Harlequin Swords" },
    ],
  },
  {
    collectionIndex: 30,
    name: "Skinchanger Style",
    books: [
      { bookIndex: 1, name: "Crafting Motif 31: Skinchanger Axes" },
      { bookIndex: 2, name: "Crafting Motif 31: Skinchanger Belts" },
      { bookIndex: 3, name: "Crafting Motif 31: Skinchanger Boots" },
      { bookIndex: 4, name: "Crafting Motif 31: Skinchanger Bows" },
      { bookIndex: 5, name: "Crafting Motif 31: Skinchanger Chests" },
      { bookIndex: 6, name: "Crafting Motif 31: Skinchanger Daggers" },
      { bookIndex: 7, name: "Crafting Motif 31: Skinchanger Gloves" },
      { bookIndex: 8, name: "Crafting Motif 31: Skinchanger Helmets" },
      { bookIndex: 9, name: "Crafting Motif 31: Skinchanger Legs" },
      { bookIndex: 10, name: "Crafting Motif 31: Skinchanger Maces" },
      { bookIndex: 11, name: "Crafting Motif 31: Skinchanger Shields" },
      { bookIndex: 12, name: "Crafting Motif 31: Skinchanger Shoulders" },
      { bookIndex: 13, name: "Crafting Motif 31: Skinchanger Staves" },
      { bookIndex: 14, name: "Crafting Motif 31: Skinchanger Swords" },
    ],
  },
]
