import { isAttachmentFile, isSourceAttachmentFile } from "@akasha/markdown-pages/attachment-file"
import { isRowsFile } from "@akasha/markdown-pages/rows-file"

const GENERATED_DIR = /(^|\/)generated\//

const GENERATED_NAME = /\.generated\.[a-z0-9]+$/

const GENERATED_LOCKFILE = /(^|\/)(bun\.lock|package-lock\.json)$/

const GENERATED_HEADER = /(\/\/|#|--|\*)[^\n]*(@generated|generated by|do not edit)/i

export function isGeneratedFile(relPath: string, body: string | Uint8Array): boolean {
  if (GENERATED_DIR.test(relPath)) return true
  if (GENERATED_NAME.test(relPath)) return true
  if (GENERATED_LOCKFILE.test(relPath)) return true
  if (isRowsFile(relPath)) return true
  if (isAttachmentFile(relPath) && !isSourceAttachmentFile(relPath)) return true
  if (typeof body !== "string") return false
  return GENERATED_HEADER.test(body.split("\n").slice(0, 3).join("\n"))
}
