{"path":"infrastructure/container-image/dockerfiles/modules/dockerfile-builder/dockerfile-builder.module.code.ts"}
{"path":"infrastructure/container-image/dockerfiles/modules/dockerfile-bun-service/dockerfile-bun-service.module.code.ts"}
{"path":"infrastructure/container-image/dockerfiles/modules/dockerfile-nextjs/dockerfile-nextjs.module.code.ts"}
{"path":"infrastructure/container-image/dockerfiles/modules/dockerfile-services/dockerfile-services.module.code.ts"}
{"path":"infrastructure/container-image/dockerfiles/modules/dockerfile-tool-image/dockerfile-tool-image.module.code.ts"}
{"path":"infrastructure/container-image/dockerfiles/modules/dockerfile-writing/dockerfile-writing.module.code.ts"}
