import type { LoreCollectionEntry } from "../lore-library-types/lore-library-types.module.code.ts"

export const LORE_COLLECTIONS_05: readonly LoreCollectionEntry[] = [
  {
    collectionIndex: 31,
    name: "Silken Ring Style",
    books: [
      { bookIndex: 1, name: "Crafting Motif 44: Silken Ring Axes" },
      { bookIndex: 2, name: "Crafting Motif 44: Silken Ring Belts" },
      { bookIndex: 3, name: "Crafting Motif 44: Silken Ring Boots" },
      { bookIndex: 4, name: "Crafting Motif 44: Silken Ring Bows" },
      { bookIndex: 5, name: "Crafting Motif 44: Silken Ring Chests" },
      { bookIndex: 6, name: "Crafting Motif 44: Silken Ring Daggers" },
      { bookIndex: 7, name: "Crafting Motif 44: Silken Ring Gloves" },
      { bookIndex: 8, name: "Crafting Motif 44: Silken Ring Helmets" },
      { bookIndex: 9, name: "Crafting Motif 44: Silken Ring Legs" },
      { bookIndex: 10, name: "Crafting Motif 44: Silken Ring Maces" },
      { bookIndex: 11, name: "Crafting Motif 44: Silken Ring Shields" },
      { bookIndex: 12, name: "Crafting Motif 44: Silken Ring Shoulders" },
      { bookIndex: 13, name: "Crafting Motif 44: Silken Ring Staves" },
      { bookIndex: 14, name: "Crafting Motif 44: Silken Ring Swords" },
    ],
  },
  {
    collectionIndex: 32,
    name: "Mazzatun Style",
    books: [
      { bookIndex: 1, name: "Crafting Motif 45: Mazzatun Axes" },
      { bookIndex: 2, name: "Crafting Motif 45: Mazzatun Belts" },
      { bookIndex: 3, name: "Crafting Motif 45: Mazzatun Boots" },
      { bookIndex: 4, name: "Crafting Motif 45: Mazzatun Bows" },
      { bookIndex: 5, name: "Crafting Motif 45: Mazzatun Chests" },
      { bookIndex: 6, name: "Crafting Motif 45: Mazzatun Daggers" },
      { bookIndex: 7, name: "Crafting Motif 45: Mazzatun Gloves" },
      { bookIndex: 8, name: "Crafting Motif 45: Mazzatun Helmets" },
      { bookIndex: 9, name: "Crafting Motif 45: Mazzatun Legs" },
      { bookIndex: 10, name: "Crafting Motif 45: Mazzatun Maces" },
      { bookIndex: 11, name: "Crafting Motif 45: Mazzatun Shields" },
      { bookIndex: 12, name: "Crafting Motif 45: Mazzatun Shoulders" },
      { bookIndex: 13, name: "Crafting Motif 45: Mazzatun Staves" },
      { bookIndex: 14, name: "Crafting Motif 45: Mazzatun Swords" },
    ],
  },
  {
    collectionIndex: 33,
    name: "House Telvanni Style",
    books: [
      { bookIndex: 1, name: "Crafting Motif 50: Telvanni Axes" },
      { bookIndex: 2, name: "Crafting Motif 50: Telvanni Belts" },
      { bookIndex: 3, name: "Crafting Motif 50: Telvanni Boots" },
      { bookIndex: 4, name: "Crafting Motif 50: Telvanni Bows" },
      { bookIndex: 5, name: "Crafting Motif 50: Telvanni Chests" },
      { bookIndex: 6, name: "Crafting Motif 50: Telvanni Daggers" },
      { bookIndex: 7, name: "Crafting Motif 50: Telvanni Gloves" },
      { bookIndex: 8, name: "Crafting Motif 50: Telvanni Helmets" },
      { bookIndex: 9, name: "Crafting Motif 50: Telvanni Legs" },
      { bookIndex: 10, name: "Crafting Motif 50: Telvanni Maces" },
      { bookIndex: 11, name: "Crafting Motif 50: Telvanni Shields" },
      { bookIndex: 12, name: "Crafting Motif 50: Telvanni Shoulders" },
      { bookIndex: 13, name: "Crafting Motif 50: Telvanni Staves" },
      { bookIndex: 14, name: "Crafting Motif 50: Telvanni Swords" },
    ],
  },
  {
    collectionIndex: 34,
    name: "Militant Ordinator Style",
    books: [
      { bookIndex: 1, name: "Crafting Motif 49: Militant Ordinator Axes" },
      { bookIndex: 2, name: "Crafting Motif 49: Militant Ordinator Belts" },
      { bookIndex: 3, name: "Crafting Motif 49: Militant Ordinator Boots" },
      { bookIndex: 4, name: "Crafting Motif 49: Militant Ordinator Bows" },
      { bookIndex: 5, name: "Crafting Motif 49: Militant Ordinator Chests" },
      { bookIndex: 6, name: "Crafting Motif 49: Militant Ordinator Daggers" },
      { bookIndex: 7, name: "Crafting Motif 49: Militant Ordinator Gloves" },
      { bookIndex: 8, name: "Crafting Motif 49: Militant Ordinator Helmets" },
      { bookIndex: 9, name: "Crafting Motif 49: Militant Ordinator Legs" },
      { bookIndex: 10, name: "Crafting Motif 49: Militant Ordinator Maces" },
      { bookIndex: 11, name: "Crafting Motif 49: Militant Ordinator Shields" },
      { bookIndex: 12, name: "Crafting Motif 49: Militant Ordinator Shoulders" },
      { bookIndex: 13, name: "Crafting Motif 49: Militant Ordinator Staves" },
      { bookIndex: 14, name: "Crafting Motif 49: Militant Ordinator Swords" },
    ],
  },
  {
    collectionIndex: 35,
    name: "Buoyant Armiger Style",
    books: [
      { bookIndex: 1, name: "Crafting Motif 47: Buoyant Armiger Axes" },
      { bookIndex: 2, name: "Crafting Motif 47: Buoyant Armiger Belts" },
      { bookIndex: 3, name: "Crafting Motif 47: Buoyant Armiger Boots" },
      { bookIndex: 4, name: "Crafting Motif 47: Buoyant Armiger Bows" },
      { bookIndex: 5, name: "Crafting Motif 47: Buoyant Armiger Chests" },
      { bookIndex: 6, name: "Crafting Motif 47: Buoyant Armiger Daggers" },
      { bookIndex: 7, name: "Crafting Motif 47: Buoyant Armiger Gloves" },
      { bookIndex: 8, name: "Crafting Motif 47: Buoyant Armiger Helmets" },
      { bookIndex: 9, name: "Crafting Motif 47: Buoyant Armiger Legs" },
      { bookIndex: 10, name: "Crafting Motif 47: Buoyant Armiger Maces" },
      { bookIndex: 11, name: "Crafting Motif 47: Buoyant Armiger Shields" },
      { bookIndex: 12, name: "Crafting Motif 47: Buoyant Armiger Shoulders" },
      { bookIndex: 13, name: "Crafting Motif 47: Buoyant Armiger Staves" },
      { bookIndex: 14, name: "Crafting Motif 47: Buoyant Armiger Swords" },
    ],
  },
  {
    collectionIndex: 36,
    name: "Ashlander Style",
    books: [
      { bookIndex: 1, name: "Crafting Motif 48: Ashlander Axes" },
      { bookIndex: 2, name: "Crafting Motif 48: Ashlander Belts" },
      { bookIndex: 3, name: "Crafting Motif 48: Ashlander Boots" },
      { bookIndex: 4, name: "Crafting Motif 48: Ashlander Bows" },
      { bookIndex: 5, name: "Crafting Motif 48: Ashlander Chests" },
      { bookIndex: 6, name: "Crafting Motif 48: Ashlander Daggers" },
      { bookIndex: 7, name: "Crafting Motif 48: Ashlander Gloves" },
      { bookIndex: 8, name: "Crafting Motif 48: Ashlander Helmets" },
      { bookIndex: 9, name: "Crafting Motif 48: Ashlander Legs" },
      { bookIndex: 10, name: "Crafting Motif 48: Ashlander Maces" },
      { bookIndex: 11, name: "Crafting Motif 48: Ashlander Shields" },
      { bookIndex: 12, name: "Crafting Motif 48: Ashlander Cops" },
      { bookIndex: 13, name: "Crafting Motif 48: Ashlander Staves" },
      { bookIndex: 14, name: "Crafting Motif 48: Ashlander Swords" },
    ],
  },
  {
    collectionIndex: 37,
    name: "House Hlaalu Style",
    books: [
      { bookIndex: 1, name: "Crafting Motif 51: Hlaalu Axes" },
      { bookIndex: 2, name: "Crafting Motif 51: Hlaalu Belts" },
      { bookIndex: 3, name: "Crafting Motif 51: Hlaalu Boots" },
      { bookIndex: 4, name: "Crafting Motif 51: Hlaalu Bows" },
      { bookIndex: 5, name: "Crafting Motif 51: Hlaalu Chests" },
      { bookIndex: 6, name: "Crafting Motif 51: Hlaalu Daggers" },
      { bookIndex: 7, name: "Crafting Motif 51: Hlaalu Gloves" },
      { bookIndex: 8, name: "Crafting Motif 51: Hlaalu Helmets" },
      { bookIndex: 9, name: "Crafting Motif 51: Hlaalu Legs" },
      { bookIndex: 10, name: "Crafting Motif 51: Hlaalu Maces" },
      { bookIndex: 11, name: "Crafting Motif 51: Hlaalu Shields" },
      { bookIndex: 12, name: "Crafting Motif 51: Hlaalu Shoulders" },
      { bookIndex: 13, name: "Crafting Motif 51: Hlaalu Staves" },
      { bookIndex: 14, name: "Crafting Motif 51: Hlaalu Swords" },
    ],
  },
  {
    collectionIndex: 38,
    name: "House Redoran Style",
    books: [
      { bookIndex: 1, name: "Crafting Motif 52: Redoran Axes" },
      { bookIndex: 2, name: "Crafting Motif 52: Redoran Belts" },
      { bookIndex: 3, name: "Crafting Motif 52: Redoran Boots" },
      { bookIndex: 4, name: "Crafting Motif 52: Redoran Bows" },
      { bookIndex: 5, name: "Crafting Motif 52: Redoran Chests" },
      { bookIndex: 6, name: "Crafting Motif 52: Redoran Daggers" },
      { bookIndex: 7, name: "Crafting Motif 52: Redoran Gloves" },
      { bookIndex: 8, name: "Crafting Motif 52: Redoran Helmets" },
      { bookIndex: 9, name: "Crafting Motif 52: Redoran Legs" },
      { bookIndex: 10, name: "Crafting Motif 52: Redoran Maces" },
      { bookIndex: 11, name: "Crafting Motif 52: Redoran Shields" },
      { bookIndex: 12, name: "Crafting Motif 52: Redoran Shoulders" },
      { bookIndex: 13, name: "Crafting Motif 52: Redoran Staves" },
      { bookIndex: 14, name: "Crafting Motif 52: Redoran Swords" },
    ],
  },
  {
    collectionIndex: 39,
    name: "Refabricated Style",
    books: [
      { bookIndex: 1, name: "Crafting Motif 79: Refabricated Axes" },
      { bookIndex: 2, name: "Crafting Motif 79: Refabricated Belts" },
      { bookIndex: 3, name: "Crafting Motif 79: Refabricated Boots" },
      { bookIndex: 4, name: "Crafting Motif 79: Refabricated Bows" },
      { bookIndex: 5, name: "Crafting Motif 79: Refabricated Chests" },
      { bookIndex: 6, name: "Crafting Motif 79: Refabricated Daggers" },
      { bookIndex: 7, name: "Crafting Motif 79: Refabricated Gloves" },
      { bookIndex: 8, name: "Crafting Motif 79: Refabricated Helms" },
      { bookIndex: 9, name: "Crafting Motif 79: Refabricated Legs" },
      { bookIndex: 10, name: "Crafting Motif 79: Refabricated Maces" },
      { bookIndex: 11, name: "Crafting Motif 79: Refabricated Shields" },
      { bookIndex: 12, name: "Crafting Motif 79: Refabricated Shoulders" },
      { bookIndex: 13, name: "Crafting Motif 79: Refabricated Staves" },
      { bookIndex: 14, name: "Crafting Motif 79: Refabricated Swords" },
    ],
  },
  {
    collectionIndex: 40,
    name: "Bloodforge Style",
    books: [
      { bookIndex: 1, name: "Crafting Motif 54: Bloodforge Axes" },
      { bookIndex: 2, name: "Crafting Motif 54: Bloodforge Belts" },
      { bookIndex: 3, name: "Crafting Motif 54: Bloodforge Boots" },
      { bookIndex: 4, name: "Crafting Motif 54: Bloodforge Bows" },
      { bookIndex: 5, name: "Crafting Motif 54: Bloodforge Chests" },
      { bookIndex: 6, name: "Crafting Motif 54: Bloodforge Daggers" },
      { bookIndex: 7, name: "Crafting Motif 54: Bloodforge Gloves" },
      { bookIndex: 8, name: "Crafting Motif 54: Bloodforge Helmets" },
      { bookIndex: 9, name: "Crafting Motif 54: Bloodforge Legs" },
      { bookIndex: 10, name: "Crafting Motif 54: Bloodforge Maces" },
      { bookIndex: 11, name: "Crafting Motif 54: Bloodforge Shields" },
      { bookIndex: 12, name: "Crafting Motif 54: Bloodforge Shoulders" },
      { bookIndex: 13, name: "Crafting Motif 54: Bloodforge Staves" },
      { bookIndex: 14, name: "Crafting Motif 54: Bloodforge Swords" },
    ],
  },
  {
    collectionIndex: 41,
    name: "Dreadhorn Style",
    books: [
      { bookIndex: 1, name: "Crafting Motif 55: Dreadhorn Axes" },
      { bookIndex: 2, name: "Crafting Motif 55: Dreadhorn Belts" },
      { bookIndex: 3, name: "Crafting Motif 55: Dreadhorn Boots" },
      { bookIndex: 4, name: "Crafting Motif 55: Dreadhorn Bows" },
      { bookIndex: 5, name: "Crafting Motif 55: Dreadhorn Chests" },
      { bookIndex: 6, name: "Crafting Motif 55: Dreadhorn Daggers" },
      { bookIndex: 7, name: "Crafting Motif 55: Dreadhorn Gloves" },
      { bookIndex: 8, name: "Crafting Motif 55: Dreadhorn Helmets" },
      { bookIndex: 9, name: "Crafting Motif 55: Dreadhorn Legs" },
      { bookIndex: 10, name: "Crafting Motif 55: Dreadhorn Maces" },
      { bookIndex: 11, name: "Crafting Motif 55: Dreadhorn Shields" },
      { bookIndex: 12, name: "Crafting Motif 55: Dreadhorn Shoulders" },
      { bookIndex: 13, name: "Crafting Motif 55: Dreadhorn Staves" },
      { bookIndex: 14, name: "Crafting Motif 55: Dreadhorn Swords" },
    ],
  },
  {
    collectionIndex: 42,
    name: "Apostle Style",
    books: [
      { bookIndex: 1, name: "Crafting Motif 56: Apostle Axes" },
      { bookIndex: 2, name: "Crafting Motif 56: Apostle Belts" },
      { bookIndex: 3, name: "Crafting Motif 56: Apostle Boots" },
      { bookIndex: 4, name: "Crafting Motif 56: Apostle Bows" },
      { bookIndex: 5, name: "Crafting Motif 56: Apostle Chests" },
      { bookIndex: 6, name: "Crafting Motif 56: Apostle Daggers" },
      { bookIndex: 7, name: "Crafting Motif 56: Apostle Gloves" },
      { bookIndex: 8, name: "Crafting Motif 56: Apostle Helmets" },
      { bookIndex: 9, name: "Crafting Motif 56: Apostle Legs" },
      { bookIndex: 10, name: "Crafting Motif 56: Apostle Maces" },
      { bookIndex: 11, name: "Crafting Motif 56: Apostle Shields" },
      { bookIndex: 12, name: "Crafting Motif 56: Apostle Shoulders" },
      { bookIndex: 13, name: "Crafting Motif 56: Apostle Staves" },
      { bookIndex: 14, name: "Crafting Motif 56: Apostle Swords" },
    ],
  },
]
