import type { TemperSet } from "akasha/temper/catalog/gear/temper-set/temper-set.page-type.types.ts"

export const spectralCloak = {
  id: "019e6484-5fd4-7840-884d-84b28a30a91c",
  type: "page-type/temper-set",
  slug: "spectral-cloak",
  title: "Spectral Cloak",
  key: "spectral-cloak",
  esoSetId: 413,
  hashPlace: 542,
  esoItemIds: [145015, 145016, 145017, 145018],
  esoEquipTypes: ["EQUIP_TYPE_ONE_HAND"],
  esoWeaponTypes: ["WEAPONTYPE_AXE", "WEAPONTYPE_DAGGER", "WEAPONTYPE_HAMMER", "WEAPONTYPE_SWORD"],
  setWayshrines: [378, 378, 378],
  setTypeId: 1,
  setNameZh: "幽灵斗篷",
  setNameRu: "Призрачная оборона",
  setNameFr: "Cape spectrale",
  setNameEs: "Manto espectral",
  setNameDe: "Spektraler Mantel",
  setDropZones: [1082, 726, 726],
  setDropMechanics: [5, 5],
  setDlcId: 12,
  itemBrowserSources: ["1082"],
  itemBrowserItemId: 145052,
  category: "temper-set-category/arena",
  valid: ["sword", "axe", "mace", "dagger"],
  bonuses: "jsonl",
  icons: "jsonl",
} as const satisfies TemperSet
