import type { SetTemplate } from "@akasha/temper-equipment/set-template"

export const SETS_DATA_079: readonly SetTemplate[] = [
  {
    id: "quick-serpent",
    name: "Quick Serpent",
    esoSetId: 142,
    subcategoryId: "trial",
    valid: ["*:medium"],
    bonuses: [
      {
        count: 2,
        status: "supported",
        effects: [{ metricId: "critical-rating", effectType: "integer", effectValue: 657 }],
        description: "Adds 657 Critical Chance",
      },
      {
        count: 3,
        status: "supported",
        effects: [{ metricId: "stamina-maximum", effectType: "integer", effectValue: 1096 }],
        description: "Adds 1096 Maximum Stamina",
      },
      {
        count: 4,
        status: "supported",
        effects: [{ metricId: "stamina-maximum", effectType: "integer", effectValue: 1096 }],
        description: "Adds 1096 Maximum Stamina",
      },
      {
        count: 5,
        status: "unsupported",
        effects: [],
        description:
          "Reduces the costs of your Stamina abilities by 8%. When an enemy you have recently damaged dies, you restore 2454 Stamina and gain Major Expedition for 8 seconds, increasing your Movement Speed by 30%. These effects can occur once every second.",
      },
    ],
    icons: {
      "axe": "/esoui/art/icons/gear_celestial_1haxe_a.dds",
      "battleaxe": "/esoui/art/icons/gear_celestial_2haxe_a.dds",
      "bow": "/esoui/art/icons/gear_celestial_bow_a.dds",
      "chest:*": "/esoui/art/icons/gear_craglorn_medium_chest_a.dds",
      "dagger": "/esoui/art/icons/gear_celestial_dagger_a.dds",
      "feet:*": "/esoui/art/icons/gear_craglorn_medium_feet_a.dds",
      "greatsword": "/esoui/art/icons/gear_celestial_2hsword_a.dds",
      "hands:*": "/esoui/art/icons/gear_craglorn_medium_hands_a.dds",
      "head:*": "/esoui/art/icons/gear_craglorn_medium_head_a.dds",
      "ice-staff": "/esoui/art/icons/gear_celestial_staff_a.dds",
      "inferno-staff": "/esoui/art/icons/gear_celestial_staff_a.dds",
      "legs:*": "/esoui/art/icons/gear_craglorn_medium_legs_a.dds",
      "lightning-staff": "/esoui/art/icons/gear_celestial_staff_a.dds",
      "mace": "/esoui/art/icons/gear_celestial_1hhammer_a.dds",
      "maul": "/esoui/art/icons/gear_celestial_2hhammer_a.dds",
      "necklace": "/esoui/art/icons/gear_breton_neck_a.dds",
      "restoration-staff": "/esoui/art/icons/gear_celestial_staff_a.dds",
      "ring": "/esoui/art/icons/gear_breton_ring_a.dds",
      "shield": "/esoui/art/icons/gear_celestial_shield_a.dds",
      "shoulders:*": "/esoui/art/icons/gear_craglorn_medium_shoulders_a.dds",
      "sword": "/esoui/art/icons/gear_celestial_1hsword_a.dds",
      "waist:*": "/esoui/art/icons/gear_craglorn_medium_waist_a.dds",
    },
  },
  {
    id: "radial-uppercut",
    name: "Radial Uppercut",
    esoSetId: 412,
    subcategoryId: "arena",
    valid: ["greatsword", "battleaxe", "maul"],
    bonuses: [
      {
        count: 2,
        status: "unsupported",
        effects: [],
        description: "Uppercut deals 45% of its damage to all enemies near your primary target.",
      },
    ],
    icons: {
      battleaxe: "/esoui/art/icons/gear_honorguard_2haxe_a.dds",
      greatsword: "/esoui/art/icons/gear_honorguard_2hsword_a.dds",
      maul: "/esoui/art/icons/gear_honorguard_2hmace_a.dds",
    },
  },
  {
    id: "radiant-bastion",
    name: "Radiant Bastion",
    esoSetId: 536,
    subcategoryId: "overland",
    valid: ["*:heavy"],
    bonuses: [
      {
        count: 2,
        status: "supported",
        effects: [{ metricId: "health-maximum", effectType: "integer", effectValue: 1206 }],
        description: "Adds 1206 Maximum Health",
      },
      {
        count: 3,
        status: "supported",
        effects: [{ metricId: "power", effectType: "integer", effectValue: 129 }],
        description: "Adds 129 Weapon and Spell Damage",
      },
      {
        count: 4,
        status: "supported",
        effects: [{ metricId: "health-maximum", effectType: "integer", effectValue: 1206 }],
        description: "Adds 1206 Maximum Health",
      },
      {
        count: 5,
        status: "unsupported",
        effects: [],
        description:
          "Deal 10% of all direct damage done to you back to the attacker, up to 4250 damage.",
      },
    ],
    icons: {
      "chest:light": "/esoui/art/icons/gear_reachv2_light_robe_a.dds",
      "head:light": "/esoui/art/icons/gear_nighthollowreg_lgt_head_a.dds",
      "necklace": "/esoui/art/icons/gear_breton_neck_a.dds",
      "ring": "/esoui/art/icons/gear_breton_ring_a.dds",
      "shoulders:light": "/esoui/art/icons/gear_nighthollowreg_lgt_shoulders_a.dds",
      "waist:light": "/esoui/art/icons/gear_nighthollowreg_lgt_waist_a.dds",
    },
  },
  {
    id: "rage-of-the-ursauk",
    name: "Rage of the Ursauk",
    esoSetId: 662,
    subcategoryId: "dungeon",
    valid: ["*:medium"],
    bonuses: [
      {
        count: 2,
        status: "supported",
        effects: [{ metricId: "penetration", effectType: "integer", effectValue: 1487 }],
        description: "Adds 1487 Offensive Penetration",
      },
      {
        count: 3,
        status: "supported",
        effects: [{ metricId: "penetration", effectType: "integer", effectValue: 1487 }],
        description: "Adds 1487 Offensive Penetration",
      },
      {
        count: 4,
        status: "supported",
        effects: [{ metricId: "critical-rating", effectType: "integer", effectValue: 657 }],
        description: "Adds 657 Critical Chance",
      },
      {
        count: 5,
        status: "unsupported",
        effects: [],
        description:
          "When you deal damage with a Heavy Attack, create a 12 meter area for 12 seconds that grants Empower to group members inside, increasing the damage of their Heavy Attacks against monsters by 70%. This effect can occur once every 8 seconds.",
      },
    ],
    icons: {
      "axe": "/esoui/art/icons/gear_feraldruid_1haxe_a.dds",
      "battleaxe": "/esoui/art/icons/gear_feraldruid_2haxe_a.dds",
      "bow": "/esoui/art/icons/gear_feraldruid_bow_a.dds",
      "chest:*": "/esoui/art/icons/gear_feraldruid_medium_chest_a.dds",
      "dagger": "/esoui/art/icons/gear_feraldruid_dagger_a.dds",
      "feet:*": "/esoui/art/icons/gear_feraldruid_medium_feet_a.dds",
      "greatsword": "/esoui/art/icons/gear_feraldruid_2hsword_a.dds",
      "hands:*": "/esoui/art/icons/gear_feraldruid_medium_hands_a.dds",
      "head:*": "/esoui/art/icons/gear_feraldruid_medium_head_a.dds",
      "ice-staff": "/esoui/art/icons/gear_feraldruid_staff_a.dds",
      "inferno-staff": "/esoui/art/icons/gear_feraldruid_staff_a.dds",
      "legs:*": "/esoui/art/icons/gear_feraldruid_medium_legs_a.dds",
      "lightning-staff": "/esoui/art/icons/gear_feraldruid_staff_a.dds",
      "mace": "/esoui/art/icons/gear_feraldruid_1hhamer_a.dds",
      "maul": "/esoui/art/icons/gear_feraldruid_2hhammer_a.dds",
      "necklace": "/esoui/art/icons/gear_breton_neck_a.dds",
      "restoration-staff": "/esoui/art/icons/gear_feraldruid_staff_a.dds",
      "ring": "/esoui/art/icons/gear_breton_ring_a.dds",
      "shield": "/esoui/art/icons/gear_feraldruid_shield_a.dds",
      "shoulders:*": "/esoui/art/icons/gear_feraldruid_medium_shoulder_a.dds",
      "sword": "/esoui/art/icons/gear_feraldruid_1hsword_a.dds",
      "waist:*": "/esoui/art/icons/gear_feraldruid_medium_waist_a.dds",
    },
  },
  {
    id: "rakkhats-voidmantle",
    name: "Rakkhat's Voidmantle",
    esoSetId: 812,
    subcategoryId: "no-type",
    valid: ["shoulders:medium"],
    bonuses: [
      {
        count: 1,
        status: "unsupported",
        effects: [],
        description:
          "Increases your damage done with non-Ultimate Heavy Attacks and decreases your damage done with Light Attacks by 50% each.\n\nDealing damage with a Light Attack restores 431 Magicka or Stamina, depending on your equipped weapon type. This resource restore is treated as a Heavy Attack resource restore for bonuses and penalties. Your Heavy Attacks no longer restore resources.",
      },
    ],
    icons: { "shoulders:*": "/esoui/art/icons/gear_rakkat_shoulder_a.dds" },
  },
  {
    id: "rallying-cry",
    name: "Rallying Cry",
    esoSetId: 629,
    subcategoryId: "pvp",
    valid: ["*:light"],
    bonuses: [
      {
        count: 2,
        status: "supported",
        effects: [{ metricId: "critical-rating", effectType: "integer", effectValue: 657 }],
        description: "Adds 657 Critical Chance",
      },
      {
        count: 3,
        status: "supported",
        effects: [{ metricId: "magicka-maximum", effectType: "integer", effectValue: 1096 }],
        description: "Adds 1096 Maximum Magicka",
      },
      {
        count: 4,
        status: "supported",
        effects: [{ metricId: "critical-rating", effectType: "integer", effectValue: 657 }],
        description: "Adds 657 Critical Chance",
      },
      {
        count: 5,
        status: "unsupported",
        effects: [],
        description:
          "When your healing critically strikes while Battle Spirit is active, you and group members within 12 meters of you gain 1650 Critical Resistance and 300 Weapon and Spell Damage for 20 seconds. Each group member affected reduces the Weapon and Spell Damage by 15 and Critical Resistance by 83. This effect can occur once every 15 seconds.",
      },
    ],
    icons: {
      "axe": "/esoui/art/icons/gear_breton_1haxe_d.dds",
      "battleaxe": "/esoui/art/icons/gear_breton_2haxe_d.dds",
      "bow": "/esoui/art/icons/gear_breton_bow_d.dds",
      "chest:*": "/esoui/art/icons/gear_breton_light_robe_d.dds",
      "dagger": "/esoui/art/icons/gear_breton_dagger_d.dds",
      "feet:*": "/esoui/art/icons/gear_breton_light_feet_d.dds",
      "greatsword": "/esoui/art/icons/gear_breton_2hsword_d.dds",
      "hands:*": "/esoui/art/icons/gear_breton_light_hands_d.dds",
      "head:*": "/esoui/art/icons/gear_breton_light_head_d.dds",
      "ice-staff": "/esoui/art/icons/gear_breton_staff_d.dds",
      "inferno-staff": "/esoui/art/icons/gear_breton_staff_d.dds",
      "legs:*": "/esoui/art/icons/gear_breton_light_legs_d.dds",
      "lightning-staff": "/esoui/art/icons/gear_breton_staff_d.dds",
      "mace": "/esoui/art/icons/gear_breton_1hhammer_d.dds",
      "maul": "/esoui/art/icons/gear_breton_2hhammer_d.dds",
      "necklace": "/esoui/art/icons/gear_breton_neck_a.dds",
      "restoration-staff": "/esoui/art/icons/gear_breton_staff_d.dds",
      "ring": "/esoui/art/icons/gear_breton_ring_a.dds",
      "shield": "/esoui/art/icons/gear_breton_shield_d.dds",
      "shoulders:*": "/esoui/art/icons/gear_breton_light_shoulders_d.dds",
      "sword": "/esoui/art/icons/gear_breton_1hsword_d.dds",
      "waist:*": "/esoui/art/icons/gear_breton_light_waist_d.dds",
    },
  },
  {
    id: "rampaging-slash",
    name: "Rampaging Slash",
    esoSetId: 370,
    subcategoryId: "arena",
    valid: ["sword", "axe", "mace", "dagger", "shield"],
    bonuses: [
      {
        count: 2,
        status: "unsupported",
        effects: [],
        description:
          "When you deal damage with Low Slash, your next fully-charged Heavy Attack used within 5 seconds restores 1904 Magicka and Stamina.",
      },
    ],
    icons: {
      axe: "/esoui/art/icons/gear_dwarvenscavenged_1haxe_a.dds",
      dagger: "/esoui/art/icons/gear_dwarvenscavenged_dagger_a.dds",
      mace: "/esoui/art/icons/gear_dwarvenscavenged_1hhammer_a.dds",
      shield: "/esoui/art/icons/gear_dwarvenscavenged_shield_a.dds",
      sword: "/esoui/art/icons/gear_dwarvenscavenged_1hsword_a.dds",
    },
  },
]
