import type { SetTemplate } from "@akasha/temper-equipment/set-template"

export const SETS_DATA_085: readonly SetTemplate[] = [
  {
    id: "saxhleel-champion",
    name: "Saxhleel Champion",
    esoSetId: 585,
    subcategoryId: "trial",
    valid: ["*:heavy"],
    bonuses: [
      {
        count: 2,
        status: "supported",
        effects: [{ metricId: "magicka-maximum", effectType: "integer", effectValue: 1096 }],
        description: "Adds 1096 Maximum Magicka",
      },
      {
        count: 3,
        status: "unsupported",
        effects: [],
        description:
          "Gain Minor Aegis at all times, reducing your damage taken from Dungeon, Trial, and Arena Monsters by 5%.",
      },
      {
        count: 4,
        status: "supported",
        effects: [{ metricId: "stamina-maximum", effectType: "integer", effectValue: 1096 }],
        description: "Adds 1096 Maximum Stamina",
      },
      {
        count: 5,
        status: "unsupported",
        effects: [],
        description:
          "When you use an Ultimate ability while in combat, you and up to 11 group members within 28 meters of you gain Major Force for 1 second per 15 Ultimate spent, increasing your Critical Damage done by 20%.",
      },
    ],
    icons: {
      "axe": "/esoui/art/icons/gear_rockgrove_1haxe_a.dds",
      "battleaxe": "/esoui/art/icons/gear_rockgrove_2haxe_a.dds",
      "bow": "/esoui/art/icons/gear_rockgrove_bow_a.dds",
      "chest:*": "/esoui/art/icons/gear_rockgrove_heavy_chest_a.dds",
      "dagger": "/esoui/art/icons/gear_rockgrove_dagger_a.dds",
      "feet:*": "/esoui/art/icons/gear_rockgrove_heavy_feet_a.dds",
      "greatsword": "/esoui/art/icons/gear_rockgrove_2hsword_a.dds",
      "hands:*": "/esoui/art/icons/gear_rockgrove_heavy_hands_a.dds",
      "head:*": "/esoui/art/icons/gear_rockgrove_heavy_head_a.dds",
      "ice-staff": "/esoui/art/icons/gear_rockgrove_staff_a.dds",
      "inferno-staff": "/esoui/art/icons/gear_rockgrove_staff_a.dds",
      "legs:*": "/esoui/art/icons/gear_rockgrove_heavy_legs_a.dds",
      "lightning-staff": "/esoui/art/icons/gear_rockgrove_staff_a.dds",
      "mace": "/esoui/art/icons/gear_rockgrove_1hhammer_a.dds",
      "maul": "/esoui/art/icons/gear_rockgrove_2hhammer_a.dds",
      "necklace": "/esoui/art/icons/gear_breton_neck_a.dds",
      "restoration-staff": "/esoui/art/icons/gear_rockgrove_staff_a.dds",
      "ring": "/esoui/art/icons/gear_breton_ring_a.dds",
      "shield": "/esoui/art/icons/gear_rockgrove_shield_a.dds",
      "shoulders:*": "/esoui/art/icons/gear_rockgrove_heavy_shoulders_a.dds",
      "sword": "/esoui/art/icons/gear_rockgrove_1hsword_a.dds",
      "waist:*": "/esoui/art/icons/gear_rockgrove_heavy_waist_a.dds",
    },
  },
  {
    id: "scathing-mage",
    name: "Scathing Mage",
    esoSetId: 190,
    subcategoryId: "dungeon",
    valid: ["*:light"],
    bonuses: [
      {
        count: 2,
        status: "supported",
        effects: [{ metricId: "magicka-maximum", effectType: "integer", effectValue: 1096 }],
        description: "Adds 1096 Maximum Magicka",
      },
      {
        count: 3,
        status: "supported",
        effects: [{ metricId: "critical-rating", effectType: "integer", effectValue: 657 }],
        description: "Adds 657 Critical Chance",
      },
      {
        count: 4,
        status: "supported",
        effects: [{ metricId: "critical-rating", effectType: "integer", effectValue: 657 }],
        description: "Adds 657 Critical Chance",
      },
      {
        count: 5,
        status: "unsupported",
        effects: [],
        description:
          "When you deal direct damage, you have a 20% chance to increase your Weapon and Spell Damage by 516 for 5 seconds. This effect can occur once every 5 seconds.",
      },
    ],
    icons: {
      "axe": "/esoui/art/icons/gear_imperialdaedric_1haxe_c.dds",
      "battleaxe": "/esoui/art/icons/gear_imperialdaedric_2haxe_c.dds",
      "bow": "/esoui/art/icons/gear_imperialerialdaedric_bow_c.dds",
      "chest:*": "/esoui/art/icons/gear_breton_light_robe_d.dds",
      "dagger": "/esoui/art/icons/gear_imperialdaedric_dagger__c.dds",
      "feet:*": "/esoui/art/icons/gear_breton_light_feet_d.dds",
      "greatsword": "/esoui/art/icons/gear_imperialdaedric_2hsword_c.dds",
      "hands:*": "/esoui/art/icons/gear_breton_light_hands_d.dds",
      "head:*": "/esoui/art/icons/gear_breton_light_head_d.dds",
      "ice-staff": "/esoui/art/icons/gear_imperialdaedric_staff_c.dds",
      "inferno-staff": "/esoui/art/icons/gear_imperialdaedric_staff_c.dds",
      "legs:*": "/esoui/art/icons/gear_breton_light_legs_d.dds",
      "lightning-staff": "/esoui/art/icons/gear_imperialdaedric_staff_c.dds",
      "mace": "/esoui/art/icons/gear_imperialdaedric_1hhammer_c.dds",
      "maul": "/esoui/art/icons/gear_imperialdaedric_2hhammer_c.dds",
      "necklace": "/esoui/art/icons/gear_breton_neck_a.dds",
      "restoration-staff": "/esoui/art/icons/gear_imperialdaedric_staff_c.dds",
      "ring": "/esoui/art/icons/gear_breton_ring_a.dds",
      "shield": "/esoui/art/icons/gear_imperialdaedric_shield__c.dds",
      "shoulders:*": "/esoui/art/icons/gear_breton_light_shoulders_d.dds",
      "sword": "/esoui/art/icons/gear_imperialerialdaedric_1hsword_c.dds",
      "waist:*": "/esoui/art/icons/gear_breton_light_waist_d.dds",
    },
  },
  {
    id: "scavenging-demise",
    name: "Scavenging Demise",
    esoSetId: 434,
    subcategoryId: "dungeon",
    valid: ["*:medium"],
    bonuses: [
      {
        count: 2,
        status: "supported",
        effects: [{ metricId: "power", effectType: "integer", effectValue: 129 }],
        description: "Adds 129 Weapon and Spell Damage",
      },
      {
        count: 3,
        status: "supported",
        effects: [{ metricId: "critical-rating", effectType: "integer", effectValue: 657 }],
        description: "Adds 657 Critical Chance",
      },
      {
        count: 4,
        status: "supported",
        effects: [{ metricId: "critical-rating", effectType: "integer", effectValue: 657 }],
        description: "Adds 657 Critical Chance",
      },
      {
        count: 5,
        status: "unsupported",
        effects: [],
        description:
          "When you deal Critical Poison Damage to an enemy, summon the Scavenging Maw which attacks your enemy after 2 seconds. The Scavenging Maw deals 2587 Poison damage and inflicts Minor Vulnerability for 15 seconds, increasing their damage taken by 5%. This effect can occur every 10 seconds and scales off the higher of your Weapon or Spell Damage.",
      },
    ],
    icons: {
      "axe": "/esoui/art/icons/gear_meridian_1haxe_a.dds",
      "battleaxe": "/esoui/art/icons/gear_meridian_2haxe_a.dds",
      "bow": "/esoui/art/icons/gear_meridian_bow_a.dds",
      "chest:*": "/esoui/art/icons/gear_meridian_medium_chest_a.dds",
      "dagger": "/esoui/art/icons/gear_meridian_dagger_a.dds",
      "feet:*": "/esoui/art/icons/gear_meridian_medium_feet_a.dds",
      "greatsword": "/esoui/art/icons/gear_meridian_2hsword_a.dds",
      "hands:*": "/esoui/art/icons/gear_meridian_medium_hands_a.dds",
      "head:*": "/esoui/art/icons/gear_meridian_medium_head_a.dds",
      "ice-staff": "/esoui/art/icons/gear_meridian_staff_a.dds",
      "inferno-staff": "/esoui/art/icons/gear_meridian_staff_a.dds",
      "legs:*": "/esoui/art/icons/gear_meridian_medium_legs_a.dds",
      "lightning-staff": "/esoui/art/icons/gear_meridian_staff_a.dds",
      "mace": "/esoui/art/icons/gear_meridian_1hhammer_a.dds",
      "maul": "/esoui/art/icons/gear_meridian_2hhammer_a.dds",
      "necklace": "/esoui/art/icons/gear_breton_neck_a.dds",
      "restoration-staff": "/esoui/art/icons/gear_meridian_staff_a.dds",
      "ring": "/esoui/art/icons/gear_breton_ring_a.dds",
      "shield": "/esoui/art/icons/gear_meridian_shield_a.dds",
      "shoulders:*": "/esoui/art/icons/gear_meridian_medium_shoulder_a.dds",
      "sword": "/esoui/art/icons/gear_meridian_1hsword_a.dds",
      "waist:*": "/esoui/art/icons/gear_meridian_medium_waist_a.dds",
    },
  },
  {
    id: "scorions-feast",
    name: "Scorion's Feast",
    esoSetId: 603,
    subcategoryId: "dungeon",
    valid: ["*:light"],
    bonuses: [
      {
        count: 2,
        status: "supported",
        effects: [{ metricId: "magicka-maximum", effectType: "integer", effectValue: 1096 }],
        description: "Adds 1096 Maximum Magicka",
      },
      {
        count: 3,
        status: "supported",
        effects: [{ metricId: "magicka-recovery", effectType: "integer", effectValue: 129 }],
        description: "Adds 129 Magicka Recovery",
      },
      {
        count: 4,
        status: "supported",
        effects: [{ metricId: "power", effectType: "integer", effectValue: 129 }],
        description: "Adds 129 Weapon and Spell Damage",
      },
      {
        count: 5,
        status: "unsupported",
        effects: [],
        description:
          "When you deal damage with a fully-charged Heavy Attack, you gain an Imbued Aura for 10 seconds, granting you and up to 3 other group members 307 Magicka and Stamina Recovery. This effect can occur once every 20 seconds.\n\nIf you deal damage with a fully-charged Heavy Attack with an Imbued Aura active, consume it and gain an Overflow Aura for 10 seconds, granting you and up to 3 other group members 307 Weapon and Spell Damage.",
      },
    ],
    icons: {
      "axe": "/esoui/art/icons/gear_blackiron_1haxe.dds",
      "battleaxe": "/esoui/art/icons/gear_blackiron_2haxe.dds",
      "bow": "/esoui/art/icons/gear_blackiron_bow.dds",
      "chest:*": "/esoui/art/icons/gear_blackironlgt_robe_a.dds",
      "dagger": "/esoui/art/icons/gear_blackiron_dagger.dds",
      "feet:*": "/esoui/art/icons/gear_blackironlgt_feet_a.dds",
      "greatsword": "/esoui/art/icons/gear_blackiron_2hsword.dds",
      "hands:*": "/esoui/art/icons/gear_blackironlgt_hands_a.dds",
      "head:*": "/esoui/art/icons/gear_blackironlgt_head_a.dds",
      "ice-staff": "/esoui/art/icons/gear_blackiron_staff.dds",
      "inferno-staff": "/esoui/art/icons/gear_blackiron_staff.dds",
      "legs:*": "/esoui/art/icons/gear_blackironlgt_legs_a.dds",
      "lightning-staff": "/esoui/art/icons/gear_blackiron_staff.dds",
      "mace": "/esoui/art/icons/gear_blackiron_1hhammer.dds",
      "maul": "/esoui/art/icons/gear_blackiron_2hhammer.dds",
      "necklace": "/esoui/art/icons/gear_breton_neck_a.dds",
      "restoration-staff": "/esoui/art/icons/gear_blackiron_staff.dds",
      "ring": "/esoui/art/icons/gear_breton_ring_a.dds",
      "shield": "/esoui/art/icons/gear_blackiron_shield.dds",
      "shoulders:*": "/esoui/art/icons/gear_blackironlgt_shoulder_a.dds",
      "sword": "/esoui/art/icons/gear_blackiron_1hsword.dds",
      "waist:*": "/esoui/art/icons/gear_blackironlgt_waist_a.dds",
    },
  },
  {
    id: "scourge-harvester",
    name: "Scourge Harvester",
    esoSetId: 165,
    subcategoryId: "monster",
    valid: ["monster"],
    bonuses: [
      {
        count: 1,
        status: "supported",
        effects: [{ metricId: "health-maximum", effectType: "integer", effectValue: 1206 }],
        description: "Adds 1206 Maximum Health",
      },
      {
        count: 2,
        status: "unsupported",
        effects: [],
        description:
          "When you take damage, you have a 10% chance to tether to your enemy for 6 seconds, as long as you remain within 8 meters of them. While tethered, you deal 317 Magic damage every second to the enemy, heal for the damage caused, and gain Major Vitality, increasing your healing received and damage shield strength by 12%. This effect can occur once every 6 seconds and scales off your Max Health.",
      },
    ],
    icons: {
      "head:heavy": "/esoui/art/icons/gear_undaunted_hoarvordaedra_head_a.dds",
      "head:light": "/esoui/art/icons/gear_undaunted_hoarvordaedra_head_a.dds",
      "head:medium": "/esoui/art/icons/gear_undaunted_hoarvordaedra_head_a.dds",
      "shoulders:heavy": "/esoui/art/icons/gear_undaunted_hoarvordaedra_shoulders_a.dds",
      "shoulders:light": "/esoui/art/icons/gear_undaunted_hoarvordaedra_shoulders_a.dds",
      "shoulders:medium": "/esoui/art/icons/gear_undaunted_hoarvordaedra_shoulders_a.dds",
    },
  },
  {
    id: "sea-serpents-coil",
    name: "Sea-Serpent's Coil",
    esoSetId: 657,
    subcategoryId: "mythic",
    valid: ["necklace"],
    bonuses: [
      {
        count: 1,
        status: "unsupported",
        effects: [],
        description:
          "While at full Health, you gain 40% damage reduction. After taking damage while at full Health in combat, you gain Serpent's Rebuke for 10 seconds, snaring yourself by 40% and gaining Major Berserk and Major Courage, increasing your damage done by 10% and Weapon and Spell Damage by 430.\n\nThe damage resistance does not apply while Serpent's Rebuke is active.",
      },
    ],
    icons: { necklace: "/esoui/art/icons/u34_mythic_sea-serpents_coil.dds" },
  },
]
