export const UI_STRINGS: Record<string, string> = {
  Lake: "Lake",
  Foul: "Foul",
  River: "River",
  Salt: "Salt",
  Oily: "Oily",
  Mystic: "Mystic",
  Running: "Running",
  Portals: "Portals",
  Celestial_Rifts: "Celestial rifts",
  Dark_Fissures: "Dark fissures",
  Oblivion_Portals: "Oblivion portals",
  Shadow_Fissures: "Shadow fissures",
  Lava_Lashers: "Lava lashers",
  Soul_Reaper: "Soul Reaper",
  Delve_bosses: "Delve bosses",
  Delve_bosses_done: "Delve bosses (done)",
  Skyshards: "Skyshards",
  Skyshards_done: "Skyshards (done)",
  Lore_books: "Lore books",
  Lore_books_done: "Lore books (done)",
  Treasure_Chests: "Treasure chests",
  Unknown_POI: "Unknown POI",
  Undaunted: "Undaunted",
  Time_Rifts: "Time Rifts",
  Shrines: "Shrines",
  Fishing_Nodes: "Fishing nodes",
  Volendrung: "Volendrung",
  Antiquities: "Antiquities",
  Antiquity_Leads: "Antiquity leads",
  Imperial_City: "Imperial City",
  IC_Bosses: "Bosses",
  IC_Respawns: "Respawns",
  Cunning_Scamp: "Cunning Scamp",
  Trove_Scamp: "Trove Scamp",
  World_achievements: "World achievements",
  Orsinium_world_event: "Random encounters",
  Summerset_world_event: "Random encounters",
  Random_Encounters: "Random encounters",
  Orsinium: "Orsinium",
  Thieves_guild: "Thieves guild",
  Morrowind: "Morrowind",
  Summerset: "Summerset",
  Clockwork_City: "Clockwork City",
  Murkmire: "Murkmire",
  Elsweyr: "Elsweyr",
  Blackwood: "Blackwood",
  Greymoor: "Greymoor",
  High_Isle: "High Isle",
  Necrom: "Necrom",
  Gold_Road: "Gold Road",
  Seasons_of_the_Worm_Cult: "Seasons of the Worm Cult",
}

export function loc(this: void, key: string): string {
  return UI_STRINGS[key] ?? key
}
