import type { TemperSet } from "akasha/temper/catalog/gear/temper-set/temper-set.page-type.types.ts"

export const swarmMother = {
  id: "019e6484-601c-71ec-9044-25babff6b440",
  type: "page-type/temper-set",
  slug: "swarm-mother",
  title: "Swarm Mother",
  key: "swarm-mother",
  esoSetId: 267,
  hashPlace: 574,
  esoItemIds: [94476, 94612, 94748, 94884, 95020, 95156],
  esoArmorTypes: ["ARMORTYPE_HEAVY", "ARMORTYPE_LIGHT", "ARMORTYPE_MEDIUM"],
  esoEquipTypes: ["EQUIP_TYPE_HEAD", "EQUIP_TYPE_SHOULDERS"],
  setWayshrines: [193, 193, 193],
  setVeteranEquipTypes: ["EQUIP_TYPE_HEAD"],
  setUndauntedChestId: 2,
  setTypeId: 8,
  setNameZh: "蛛群之母",
  setNameRu: "Мать стаи",
  setNameFr: "La Mère de la nuée",
  setNameEs: "Madre del Enjambre",
  setNameDe: "Schwarmmutter",
  setDropZones: [144, 3, 3],
  setDropMechanics: [6],
  setDropLocationNamesEn: ["The Whisperer"],
  setDropLocationNamesDe: ["Die Flüsterin"],
  setDlcId: 0,
  itemBrowserSources: ["144:-101"],
  itemBrowserItemId: 94477,
  category: "temper-set-category/monster",
  valid: ["monster"],
  bonuses: "jsonl",
  icons: "jsonl",
} as const satisfies TemperSet
