set -g mouse on
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -ga terminal-overrides ",xterm*:smcup@:rmcup@"
bind -n PageUp copy-mode -u
bind -n PageDown send-keys PageDown
