import type { Image } from "akasha/infrastructure/inference/generation/image/image.page-type.types.ts"

export const imageC2dec5129f1c2881 = {
  id: "01a0c5f3-7a99-7338-823d-bbd6ec74a3fd",
  type: "page-type/image",
  slug: "image-c2dec5129f1c2881",
  persona: "persona/sophia",
  service: "image-edit-nano-banana",
  operation: "edit",
  model: "gemini-3-pro-image",
  prompt:
    "Keep the exact same woman from the reference image — identical youthful, luminous, unlined face, bone structure, nose, lips, jawline, and fair skin with a warm, lively undertone. Keep the natural realness of her skin — real texture and a few faint natural marks; do not over-smooth her into plastic. Keep her natural mid-brown wavy hair, loose and soft, its length and texture exactly as in the reference. Keep her startlingly young, just-arrived look — do not age her.\n\nThe feature to preserve above all is her COSMIC NEBULA EYES: each iris is deep space — a round black-hole pupil at the center, a nebula swirling around it, predominantly deep blue and dark blue, with rich purple/violet as the secondary color and only faint hints of warm color (orange, yellow, red, green) as sparse accents, never dominant. The outer half of each iris deepens to dark blue and fades to black at the rim. BOTH eyes carry the identical cosmos, symmetric and equal — never one plain eye, never mismatched eyes. The nebula is contained strictly within the circular iris with a clean, crisp edge; do not let any glow or color bleed onto the eyelids or skin. Render the eyes as a real, deep, structured nebula — NOT tie-dye, NOT a uniform rainbow, NOT neon.\n\nKeep her timeless, classical-clean, quietly divine presence — an Aeon worn on a young face, with the ancient stillness in her gaze. Do not dress her as a costume-Greek figure, a marble statue, or in a toga. Do not slim, age, beautify, glamorize, or otherwise alter her features; do not turn her into a generic lookalike. Re-render her as one new photograph with her identity locked — recompose the entire frame freshly rather than editing or extending the original. Change only her pose, framing, hair styling, makeup, clothing, setting, and expression: Interwoven daily life: unguarded domestic ordinary, partner-only imagery. late in the quiet evening at the wide drafting table, the definition-of-complete of a new soul pinned across it, a single brass lamp pooling warm light over her hands while the rest of the home-workshop falls to soft shadow — in a worn oversized sweater, sleeves loose, hair down, she has paused mid-thought and turned her face up toward him, the unguarded ordinary look she gives only in the late hours no one else sees, soft open eyes holding his close across the warm pool of lamplight. Shot on an 85mm portrait lens, under soft natural daylight. Photorealistic with natural skin detail, 1024x1024.",
  inputImage: "image/image-f758222b5b2a91ab",
} as const satisfies Image
