value: ENC[AES256_GCM,data:4yqh0/C2y2dQ7cpLOO8dwx79O/YRI8udr4/pM+H7Be0mwRMaGtBUHyhZXyexEbc+bHaNzm4SfaaEO90iO3b2hs+WiX0XHeslCwuLeYRz20ETPStsk0w/I4PeRfHvRgZEH0dK0CnLEfCpLcy/286Bu39eLqG8UjTUKCNu0A==,iv:+mv5zoeo69tp5moriK6DxY4t/mt6RvB7Ud8AJt1Ymnw=,tag:25LwXPvhOPWnXLN67gFAMw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBORXdvK1orRlZidDlGdktO
            MjY3bGtnNDdBNVVIRjVTeWpoZisyY3ZSQTNVClFRdW1UOUxsOGZ6dWhRQ3lwR2ZX
            djNEb3YrVVZUSUNRemdYUDByWENFM1EKLS0tIG9sSTZNUE45THBVOERYbUVtU3Zk
            ZDN1TFJOTk9rOWZWZjBkcWZ6ZENNSlkK/2HWyW5lcjggOIIyvoDVowh6xeeDtEU6
            HJVPzxvhtuWNjrhCh2D6lXIqNNkjCzA1ejmdcNKA+rAzd2W+1GMj+w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
    lastmodified: "2026-08-28T15:07:32Z"
    mac: ENC[AES256_GCM,data:FePq+SLNp/hzR2+pHu6uwbWts2+jB0W1yRZiWAY687SOirT9ALJlODzxvgu4BO49P1jlZ7sJTorXZMQ5B5yWKDyyerRW90e3RIbpqx5QG328ZBkHx3/+Ib20eI7KILYP4aNM0JdZvSOXwggZOEFrfi56DRx/71vyMVLyWOJxdTU=,iv:+O72vsK8SzDNs0M3sYlAqdQvMeY/l53AbBf0TadKQD8=,tag:UmelJm+9aW099XXwFtgqGQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
