value: ENC[AES256_GCM,data:bT3Fuu51BnFibqLFNk6LN014KdlQ1jN0K447zDsfFDrsm5clh4ZnSkreGGA8zrJCzNCsizCW7Tt1YI0Hljl+6ZnlNrX3ku9iO9G9fCYxiP200pcblBcvqk9f84igAOBquvHv71tbwHa63nr3KQrKj5yNsO8dzIw8R4NbJYDx2rL0a1q8TeD0vA==,iv:xW7ZN+8Ez4KycXodatU3PsvZfcFUjwjsdiCqGSJ98do=,tag:14KANZbr0p1Gdary7jQYBg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSdFdUOUVJSmtnQ21PdmNL
            TktQYUZmWE1BRDZRSGhBRERHYnZXcFNvVkdNCndVTVYrdDEwdkpMS3hWRng3aVY0
            QkVOa0tJNHc1T3BQN04rV2dHVVJLOGsKLS0tIDlUY3RVQ1dac0FTcWtMUTZwQ1RK
            MWxPcFE1aUd6dHFTRWQyMGVTYW5RbWcKEfRr72bs3lqgeNEoZCig7vzdiwRvQXpw
            n1YY86qat0vP4j+hzfpQTKtHc6x3xHHchVpWk2iNP12uyT4SB8t3pQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
    lastmodified: "2026-08-28T15:07:30Z"
    mac: ENC[AES256_GCM,data:dDw3qx5yoF/ZgSb4tGP35WjJCt0lpJ3LB6tQtRYbqBAEkvc1VCc6alCT//YC4yjRTX1qURp/u2Bi2+J4YWjVhwKacmR1ZiL1cK4pDrSpAJI/S5ryDSju9rRw0sUqeYCROPGxWwuzS2hRlqDgcarKqiVUNMDeTpr2qzz9pJEFL/Q=,iv:XjxQkln4bqjcCAmoDNT6fWBGY3/W82g9aGHLOZCw5Ro=,tag:R3yA1fLZHxxbpntHvIuE6Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
