import type { TemperSet } from "akasha/temper/catalog/gear/temper-set/temper-set.page-type.types.ts"

export const barSakka = {
  id: "019e66e7-69fb-7061-8c1d-cfc0e6d93b3a",
  type: "page-type/temper-set",
  slug: "bar-sakka",
  title: "Bar-Sakka",
  key: "bar-sakka",
  esoSetId: 829,
  hashPlace: 46,
  esoItemIds: [219087, 219093, 219099, 219105, 219111, 219117],
  esoArmorTypes: ["ARMORTYPE_HEAVY", "ARMORTYPE_LIGHT", "ARMORTYPE_MEDIUM"],
  esoEquipTypes: ["EQUIP_TYPE_HEAD", "EQUIP_TYPE_SHOULDERS"],
  setWayshrines: [606, 606, 606],
  setVeteranEquipTypes: ["EQUIP_TYPE_HEAD"],
  setUndauntedChestId: 3,
  setTypeId: 8,
  setNameZh: "巴-萨卡",
  setNameRu: "Бар-Сакка",
  setNameFr: "Bar-Sakka",
  setNameEs: "Bar-Sakka",
  setNameDe: "Bar-Sakka",
  setDropZones: [1551, 1502, 1502],
  setDropMechanics: [6],
  setDropLocationNamesEn: ["Bar-Sakka"],
  setDropLocationNamesDe: ["Bar-Sakka"],
  setDlcId: 39,
  itemBrowserSources: ["1551:-103"],
  itemBrowserItemId: 219092,
  category: "temper-set-category/no-type",
  valid: ["monster"],
  bonuses: "jsonl",
  icons: "jsonl",
} as const satisfies TemperSet
