import type { TemperSet } from "akasha/temper/catalog/gear/temper-set/temper-set.page-type.types.ts"

export const perfectedForceOverflow = {
  id: "019e6484-5fbd-738d-b172-5650ea4cd594",
  type: "page-type/temper-set",
  slug: "perfected-force-overflow",
  title: "Perfected Force Overflow",
  key: "perfected-force-overflow",
  esoSetId: 568,
  esoItemIds: [170010],
  esoEquipTypes: ["EQUIP_TYPE_TWO_HAND"],
  esoWeaponTypes: ["WEAPONTYPE_HEALING_STAFF"],
  setWayshrines: [457, 457, 457],
  setVeteran: true,
  setTypeId: 1,
  setNameZh: "完美力量溢流",
  setNameRu: "Совершенная переполняющая сила",
  setNameFr: "Le Débordement de force perfectionné",
  setNameEs: "Desbordamiento de fuerza perfeccionado",
  setNameDe: "Perfektionierter Machtüberschuss",
  setDropZones: [1227, 1207, 1207],
  setDropMechanics: [5, 5],
  setDlcId: 20,
  itemBrowserSources: ["1227"],
  itemBrowserPlaceKinds: [5],
  itemBrowserItemId: 170027,
  category: "temper-set-category/arena",
  valid: ["restoration-staff"],
  bonuses: "jsonl",
  icons: "jsonl",
} as const satisfies TemperSet
