apiVersion: v1
kind: Secret
metadata:
    name: prometheus-secrets
    namespace: prometheus
    labels:
        app.kubernetes.io/name: prometheus
        app.kubernetes.io/instance: prometheus
        app.kubernetes.io/component: secrets
        app.kubernetes.io/part-of: monitoring
        app.kubernetes.io/managed-by: bootstrap
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:id6RI1/8RE9w0fupw7LlQEPptsJzyAgcWasEL2mFkyeI7xW96dae42o2woN0Py/x73qivbVl3ZuH/wBwvZC4HNpokbHFSEWTWxf6GIWn8IOKiQGK1IvNPykA74kg1Up+ydRWb1rV46DyvumHjHoBVfyytbY8jBruFL703hvX5eSmtRX9rAskXg==,iv:3j8LFjUUST1nnuu0qZkXApE7VVfwDq4wq7sKtuJadV8=,tag:GyIsbn6fV9hmCu0y6sef1g==,type:str]
    PGBOUNCER_STATS_DSN: ENC[AES256_GCM,data:KMQM10AdQv46TFyqDz7plc7OrBS8n4a/omZ4PJ4eQbb1EipkhAs8e0+Z/02NAgfYb7/63axVeRxbb8QY/Zg6ZNsIbAftMrLhdCLZakbhcgPx15WLqgFAwZLJW74x2NssowHdjAnACqPT7gi+WaMglQEOmN5dIthB2FB2AQ==,iv:/nNLMjrznx10gV5DAAOWtlGJK/35AWcKC/XmajbWInM=,tag:1gFsD5chsv7XRmsvgt2gKg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhUTlyUjZtNFF6REE3NmVZ
            T0MzYUQxbUNIMjk0NUdYMkVVTTJhQkp1WVFFClowcWROSWlPSUlnYnJuaUQ3VnV2
            TkFKUjBPQ1lJRDNaYmZydmVWNUY3dWcKLS0tIGJJa0VXTGVlVW04WlczVWRGcVBT
            cTJIQ0psSzhleVNnQWs5N0VGZTNXVnMKk5SBmkuv0iURHYv8SEesEsu+Hx5FZEWo
            kxjKqqIufOZ0kCJ9YXQuFI1Qiyj/MpiAI5NlXwg7AqpELJviqQEDwQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-20T00:37:08Z"
    mac: ENC[AES256_GCM,data:ZBWu5Ewb0xS9OouOnaKkYtHPTdBo/O3picVljLP1Z20sBrRItEck4H+qgCCTnlwu6JLGuHcu4Fcq52taGLjRId6hdd+z8UmJ63w4Q73s8xEtXEEXtGanux2Ijos5XpU9yPdixnwoT7rnOszCLncWZa8Y4UcYgNN8SWIzcMi25HE=,iv:OOT3flxaKPLwG6DwAAaarLjzJGo+9KxqQH06Q9TOO9k=,tag:IAkRF2Rbf/HzRkAaKBpbUw==,type:str]
    version: 3.9.4
