import type { WorkspacePackage } from "@akasha/code-system/workspace-package"

export const pagesUi = {
  id: "01a05c0f-884e-7019-b4e6-08b3faac2e0b",
  pageTypeSlug: "workspace-package",
  slug: "pages-ui",
  definition: "what draws pages in a browser and takes what a reader does to them",
  manifest: "json",
  partSlugs: [
    "workspace-package/components",
    "module/action-verb-registry",
    "module/app-version-check",
    "module/apply-client-view-filters",
    "module/block-type-helpers",
    "module/boot-gate",
    "module/build-patch-plan",
    "module/build-predicted-row",
    "module/capability-hosts",
    "module/collect-related-ids",
    "module/collection-lookup",
    "module/compose-content-tier-page",
    "module/cover-click-registry",
    "module/cover-mask-registry",
    "module/extract-target-ids",
    "module/frame-config",
    "module/is-webkit",
    "module/media-renditions",
    "module/media-src",
    "module/media-token",
    "module/native-tts-adapter",
    "module/navigation-context",
    "module/option-create-context",
    "module/page-card-perf",
    "module/page-display-registry",
    "module/page-resolver-context",
    "module/page-with-properties",
    "module/parent-child-tree",
    "module/play-from-sentence",
    "module/playing-session",
    "module/playing-session-chain",
    "module/playing-session-storage",
    "module/reading-units",
    "module/record-view-staleness",
    "module/related-pages-coalesce",
    "module/relation-picker-context",
    "module/reorder-verb-registry",
    "module/resolve-active-sentence",
    "module/save-queue",
    "module/tanstack-live",
    "module/transport-selection",
    "module/use-app-version-check",
    "module/use-audio-seek-and-play",
    "module/use-audio-time-subscription",
    "module/use-block-collapse",
    "module/use-block-ops",
    "module/use-block-persistence",
    "module/use-block-selection",
    "module/use-coarse-pointer",
    "module/use-core-definitions-ready",
    "module/use-follow-anchor",
    "module/use-keyboard-inset",
    "module/use-native-tts-transport",
    "module/use-page",
    "module/use-pages",
    "module/use-persistent-audio-container",
    "module/use-query",
    "module/use-record-page-view",
    "module/use-referrers",
    "module/use-shell-media-src",
    "module/use-subpages",
    "module/use-user-id",
    "module/use-view-query",
    "module/use-webkit-read-aloud-ensure",
    "module/view-callbacks",
    "module/view-data-of-page",
    "module/view-filter-to-condition",
    "module/viewport-thresholds",
  ],
} as const satisfies WorkspacePackage
