import type { TemperSet } from "akasha/temper/catalog/gear/temper-set/temper-set.page-type.types.ts"

export const grandRejuvenation = {
  id: "019e6484-5fb2-7b67-b3dc-9175b48a5c4f",
  type: "page-type/temper-set",
  slug: "grand-rejuvenation",
  title: "Grand Rejuvenation",
  key: "grand-rejuvenation",
  esoSetId: 318,
  esoItemIds: [55939],
  esoEquipTypes: ["EQUIP_TYPE_TWO_HAND"],
  esoWeaponTypes: ["WEAPONTYPE_HEALING_STAFF"],
  setWayshrines: [270, 270, 270],
  setTypeId: 1,
  setNameZh: "盛大复苏",
  setNameRu: "Высшее восстановление",
  setNameFr: "Grand Rajeunissement",
  setNameEs: "Gran rejuvenecimiento",
  setNameDe: "Große Verjüngung",
  setDropZones: [635, 888, 888],
  setDropMechanics: [5, 5],
  setDlcId: 0,
  itemBrowserSources: ["635"],
  itemBrowserPlaceKinds: [5],
  itemBrowserItemId: 133810,
  category: "temper-set-category/arena",
  valid: ["restoration-staff"],
  bonuses: "jsonl",
  icons: "jsonl",
} as const satisfies TemperSet
