import type { CompanionSkillTemplate } from "../companion-skill-activation-effect-types/companion-skill-activation-effect-types.module.code.ts"

export const COMPANION_SKILLS_09 = {
  "tanlorin-shattered-spirit": {
    id: "tanlorin-shattered-spirit" as const,
    abilityId: 215001,
    name: "Shattered Spirit",
    companionId: "tanlorin" as const,
    skillLineId: "companion-tanlorin-empathic-fighter" as const,
    skillType: "active" as const,
    description:
      "Your Companion burns an enemy from the inside with soulfire, dealing $1 Magic Damage over $$1 seconds. Upon completion, the soulfire overflows and explodes from the enemy, dealing $2 Magic Damage to all enemies near them.",
    icon: "/esoui/art/icons/ability_companion_tanlorin_shattersoul.dds",
    effects: [
      {
        "type": "dot",
        "target": { "type": "enemy", "range": 28, "scope": "single" },
        "formula": {
          "type": "metric-scaling",
          "metricId": "companion-weapon-damage",
          "coefficient": 4.5,
        },
        "duration": 8,
        "damageType": "magic",
        "displayMode": "total",
        "initialTick": true,
        "tickInterval": 2,
      },
      {
        "type": "delayed",
        "delay": 8,
        "effect": {
          "type": "damage",
          "target": { "type": "enemy", "scope": "area", "radius": 6 },
          "formula": {
            "type": "metric-scaling",
            "metricId": "companion-weapon-damage",
            "coefficient": 3,
          },
          "damageType": "magic",
        },
      },
      { "type": "cast-time", "duration": 0.3 },
      { "type": "cooldown", "duration": 16 },
    ] as const,
    validRoles: ["dps"] as const,
  },
  "tanlorin-spirited": {
    id: "tanlorin-spirited" as const,
    abilityId: 214685,
    name: "Spirited",
    companionId: "tanlorin" as const,
    skillLineId: "companion-tanlorin" as const,
    skillType: "passive" as const,
    description: "Decreases damage taken by 3% and increases damage done by 3%.",
    icon: "/esoui/art/icons/ability_companion_tanlorin_passive.dds",
    effects: [
      {
        "type": "passive",
        "value": -0.03,
        "metricId": "companion-damage-taken",
        "modifierType": "fractional-change",
      },
      {
        "type": "passive",
        "value": 0.03,
        "metricId": "companion-damage-done",
        "modifierType": "fractional-change",
      },
    ] as const,
    validRoles: [] as const,
  },
  "tanlorin-volcanic-arms": {
    id: "tanlorin-volcanic-arms" as const,
    abilityId: 214703,
    name: "Volcanic Arms",
    companionId: "tanlorin" as const,
    skillLineId: "companion-tanlorin-radiating-heart" as const,
    skillType: "active" as const,
    description:
      "Your Companion charges their and their grouped allies' weapons with volcanic power to gain Major Brutality and Sorcery, increasing Weapon and Spell Damage by 20% for $$1 seconds.",
    icon: "/esoui/art/icons/ability_companion_dragonknight_volcanicarms.dds",
    effects: [
      {
        "buff": {
          "buff": "major-brutality",
          "value": 0.2,
          "duration": 8,
          "valueType": "fractional-change",
        },
        "type": "apply-buff",
        "target": { "type": "ally", "scope": "area", "radius": 28 },
      },
      {
        "buff": {
          "buff": "major-sorcery",
          "value": 0.2,
          "duration": 8,
          "valueType": "fractional-change",
        },
        "type": "apply-buff",
        "target": { "type": "ally", "scope": "area", "radius": 28 },
      },
      { "type": "cast-time", "duration": 0.23 },
      { "type": "cooldown", "duration": 16 },
    ] as const,
    validRoles: ["dps", "support"] as const,
  },
  "zerith-var-atoning-spirit": {
    id: "zerith-var-atoning-spirit" as const,
    abilityId: 222209,
    name: "Atoning Spirit",
    companionId: "zerith-var" as const,
    skillLineId: "companion-zerith-var-remedy-of-atonement" as const,
    skillType: "active" as const,
    description:
      "Your Companion conjures a ghostly spirit of a fallen Khajiit to redeem its soul in service to Azurah for $$1 seconds. The spirit heals them or the lowest Health ally around them every 2 seconds restoring $1 Health.",
    icon: "/esoui/art/icons/ability_companion_zerith_mendingspirit.dds",
    effects: [
      {
        "type": "hot",
        "target": { "type": "lowest-health-ally", "range": 28, "scope": "area" },
        "formula": {
          "type": "metric-scaling",
          "metricId": "companion-weapon-damage",
          "coefficient": 1.5,
          "coefficientType": "per-tick",
        },
        "duration": 8,
        "displayMode": "per-tick",
        "initialTick": true,
        "tickInterval": 2,
      },
      { "type": "cast-time", "duration": 0.3 },
      { "type": "cooldown", "duration": 16 },
    ] as const,
    validRoles: ["healer"] as const,
  },
  "zerith-var-azurahs-embrace": {
    id: "zerith-var-azurahs-embrace" as const,
    abilityId: 213162,
    name: "Azurah's Embrace",
    companionId: "zerith-var" as const,
    skillLineId: "companion-zerith-var-remedy-of-atonement" as const,
    skillType: "active" as const,
    description:
      "Your Companion absolves the misdeeds of fallen souls at the target location, healing themselves and their allies for $1 Health and removing up to 3 negative effects.",
    icon: "/esoui/art/icons/ability_companion_necromancer_lifeamiddeath.dds",
    effects: [
      {
        "type": "heal",
        "target": { "type": "ally", "scope": "area" },
        "formula": {
          "type": "metric-scaling",
          "metricId": "companion-weapon-damage",
          "coefficient": 0.6,
        },
      },
      { "type": "special", "count": 3, "effect": "cleanse" },
      { "type": "cast-time", "duration": 0.4 },
      { "type": "cooldown", "duration": 12 },
    ] as const,
    validRoles: ["healer"] as const,
    castConditions: [{ "type": "health-threshold", "below": 75, "targetType": "self" }] as const,
  },
  "zerith-var-blade-of-the-crossing": {
    id: "zerith-var-blade-of-the-crossing" as const,
    abilityId: 213169,
    name: "Blade of the Crossing",
    companionId: "zerith-var" as const,
    skillLineId: "companion-zerith-var" as const,
    skillType: "ultimate" as const,
    description:
      "Your Companion calls upon the power of Azurah, swinging a blade of lunar light in front of them, dealing $1 Magic Damage. Enemies damaged by this ability have Minor Magickasteal applied for $$2 seconds, causing them and their allies to restore 168 Magicka to attackers every 1 second when damaging enemies.",
    icon: "/esoui/art/icons/ability_companion_zerith_mooncrescent.dds",
    effects: [
      {
        "type": "damage",
        "target": { "type": "enemy", "range": 15, "scope": "cone" },
        "formula": {
          "type": "metric-scaling",
          "metricId": "companion-weapon-damage",
          "coefficient": 3,
        },
        "damageType": "magic",
      },
      {
        "type": "apply-debuff",
        "debuff": {
          "value": 168,
          "debuff": "minor-magickasteal",
          "duration": 10,
          "valueType": "integer",
        },
        "target": { "type": "enemy", "range": 15, "scope": "cone" },
      },
      { "type": "resource-cost", "amount": 200, "resource": "ultimate" },
      { "type": "cast-time", "duration": 0.5 },
    ] as const,
    validRoles: ["dps"] as const,
    alternateAbilityIds: [213678] as const,
  },
  "zerith-var-crescent-scythe": {
    id: "zerith-var-crescent-scythe" as const,
    abilityId: 213164,
    name: "Crescent Scythe",
    companionId: "zerith-var" as const,
    skillLineId: "companion-zerith-var-guardians-commitment" as const,
    skillType: "active" as const,
    description:
      "Your Companion summons an implement of moonlight that slashes the enemy's life force, dealing $1 Magic Damage. They heal for $2 Health every 2 seconds for $$2 seconds. The healing of this ability scales off their Max Health.",
    icon: "/esoui/art/icons/ability_companion_necromancer_scythe.dds",
    effects: [
      {
        "type": "damage",
        "target": { "type": "enemy", "scope": "cone", "radius": 7 },
        "formula": {
          "type": "metric-scaling",
          "metricId": "companion-weapon-damage",
          "coefficient": 3,
        },
        "damageType": "magic",
      },
      {
        "type": "hot",
        "target": { "type": "self", "scope": "single" },
        "formula": {
          "type": "metric-percent",
          "percent": 50,
          "metricId": "companion-health-maximum",
        },
        "duration": 6,
        "displayMode": "per-tick",
        "initialTick": true,
        "tickInterval": 2,
      },
      { "type": "cast-time", "duration": 0.166 },
      { "type": "cooldown", "duration": 8 },
    ] as const,
    validRoles: ["dps", "tank"] as const,
  },
  "zerith-var-dark-moon-totem": {
    id: "zerith-var-dark-moon-totem" as const,
    abilityId: 213166,
    name: "Dark Moon Totem",
    companionId: "zerith-var" as const,
    skillLineId: "companion-zerith-var-guardians-commitment" as const,
    skillType: "active" as const,
    description:
      "Your Companion summons an effigy of bone harboring the souls of fallen Khajiit at the feet of an enemy for $$2 seconds and applies fear for $$1 seconds. After 2 seconds the totem grants Minor Protection to them and their allies, reducing their damage taken by 5% and begins fearing nearby enemies every 2 seconds, causing them to cower in place for $$1 seconds.",
    icon: "/esoui/art/icons/ability_companion_necromancer_bonetotem.dds",
    effects: [
      {
        "type": "delayed",
        "delay": 2,
        "effect": {
          "type": "apply-status",
          "status": { "status": "fear", "duration": 4 },
          "target": { "type": "enemy", "scope": "area", "radius": 6 },
        },
      },
      {
        "buff": {
          "buff": "minor-protection",
          "value": 0.05,
          "duration": 8,
          "valueType": "fractional-change",
        },
        "type": "apply-buff",
        "target": { "type": "ally", "range": 22, "scope": "area", "radius": 6 },
      },
      { "type": "cast-time", "duration": 0.2 },
      { "type": "cooldown", "duration": 12 },
    ] as const,
    validRoles: ["tank", "support"] as const,
  },
  "zerith-var-penance-of-lorkhaj": {
    id: "zerith-var-penance-of-lorkhaj" as const,
    abilityId: 213160,
    name: "Penance of Lorkhaj",
    companionId: "zerith-var" as const,
    skillLineId: "companion-zerith-var-remedy-of-atonement" as const,
    skillType: "active" as const,
    description:
      "Your Companion sacrifices their own power to repair damaged flesh, healing themselves or an ally in front of them for $1 Health but applying Minor Defile to themselves for 4 seconds, reducing their healing received and damage shield strength by 6%.",
    icon: "/esoui/art/icons/ability_companion_zerith_renderflesh.dds",
    effects: [
      {
        "type": "heal",
        "target": { "type": "ally", "range": 28, "scope": "single" },
        "formula": {
          "type": "metric-scaling",
          "metricId": "companion-weapon-damage",
          "coefficient": 3,
        },
      },
      {
        "type": "apply-debuff",
        "debuff": {
          "value": 0.06,
          "debuff": "minor-defile",
          "duration": 4,
          "valueType": "fractional-change",
        },
        "target": { "type": "self", "scope": "single" },
      },
      { "type": "cast-time", "duration": 0.4 },
      { "type": "cooldown", "duration": 8 },
    ] as const,
    validRoles: ["healer"] as const,
    castConditions: [{ "type": "health-threshold", "below": 75, "targetType": "self" }] as const,
  },
  "zerith-var-perigean-armor": {
    id: "zerith-var-perigean-armor" as const,
    abilityId: 213165,
    name: "Perigean Armor",
    companionId: "zerith-var" as const,
    skillLineId: "companion-zerith-var-guardians-commitment" as const,
    skillType: "active" as const,
    description:
      "Your Companion wraps themselves in moon-empowered bone, granting them Major Resolve, increasing their Spell and Physical Resistance by 5948 for $$1 seconds. While active, enemies that strike them with ranged attacks will be pulled toward them once every 2 seconds and become taunted for $$3 seconds if they are not already taunted. Creates a corpse when effect completes.",
    icon: "/esoui/art/icons/ability_companion_zerith_bonearmor.dds",
    effects: [
      {
        "buff": { "buff": "major-resolve", "value": 5948, "duration": 10, "valueType": "integer" },
        "type": "apply-buff",
        "target": { "type": "self", "scope": "single" },
      },
      {
        "type": "periodic-trigger",
        "effect": { "type": "special", "effect": "pull-to-caster" },
        "duration": 10,
        "interval": 2,
      },
      {
        "type": "apply-status",
        "status": { "status": "taunt", "duration": 15 },
        "target": { "type": "enemy", "scope": "single" },
      },
      {
        "type": "delayed",
        "delay": 15,
        "effect": { "type": "special", "effect": "create-corpse" },
      },
      { "type": "cast-time", "duration": 0.2 },
      { "type": "cooldown", "duration": 16 },
    ] as const,
    validRoles: ["tank"] as const,
  },
} as const satisfies Record<string, CompanionSkillTemplate>
