apiVersion: v1
kind: Secret
metadata:
    name: authenticator-secrets
    namespace: postgres
type: Opaque
stringData:
    AUTHENTICATOR_PASSWORD: ENC[AES256_GCM,data:RTcMHSX9AT29buEwxGaY+65Ae/7wjXuHMp8rYShKlbkyuWy8YUbSYaGgAAF1KwEb,iv:h8z4TJF61xI64mlm9HRT4REoxf9jAZvjR5lOoP8HUBM=,tag:YU8Vkoml6hfVV4aG4x0nfw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5bUdxUGpsUWpvUWpsRnZT
            Q0ZiTnE5T2RaMFR5YWhDNDdtL053RGx0T0NRCkpCL0hPNzZNUTZEOFRsTFRRTGV0
            NTM2ZWNSd0I3YzBxUSt1UHFiTnBaRTgKLS0tIFNlUDF5aTFDRXJ1V2lyM1U5eXYy
            dHUzTEV4UHR1MXdEZFhLeEhyOEJuUXMKZGK8Q2aLrgcIHJH9tZ4qjrJdlAVD/rHA
            62m+AM1/PGVBwVjtxLx5zqUF4Zta8FPQJwRZeMetZTePOzVOYEd/cw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-22T14:08:36Z"
    mac: ENC[AES256_GCM,data:Z5y+MQ/8gLoG4M2tHoovxS2rW+DJAGNW1qJBIFLqDKPdnvS89+H+HZyd0SLD1UKb29LZdJoERZV5IvR8c4AXIbcFj3KNpg0soNehtUYE06InYrSOlAFDoWGJcsGKC8jhfjIox6NUUzJUsfdAx4WTPO2lN/96Q2XQt31BGeT+6gc=,iv:JQvSWLxg+AfJEVtcsKTlBCWRABVKO9lPofOqp4rXn4c=,tag:zWobcHCdgf487ZmGvHt0cw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
