import type { SkillTemplate } from "../character-skill-template/character-skill-template.module.code.ts"

export const CHARACTER_SKILLS_75 = {
  "vengeance-cleansing-ritual": {
    id: "vengeance-cleansing-ritual" as const,
    esoSkillId: 238026,
    name: "Vengeance Cleansing Ritual",
    baseName: "Vengeance Cleansing Ritual",
    skillLineId: "vengeance-templar-restoring-light" as const,
    skillType: "active" as const,
    description:
      "Exalt in the sacred light of the Aedra, cleansing up to |cffffff3|r negative effects from yourself.",
    icon: "/esoui/art/icons/ability_templar_cleansing_ritual.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 1,
    rank: 1,
    subcategoryId: "vengeance-templar-restoring-light" as const,
  },
  "vengeance-cleave": {
    id: "vengeance-cleave" as const,
    esoSkillId: 240480,
    name: "Vengeance Cleave",
    baseName: "Vengeance Cleave",
    skillLineId: "vengeance-weapon-two-handed" as const,
    skillType: "active" as const,
    description:
      "Focus your strength into a mighty swing, dealing |cffffff8820|r Physical Damage to up to 3 enemies in front of you.\n\nYou also gain a damage shield that absorbs |cffffff9056|r damage for |cffffff6|r seconds.",
    icon: "/esoui/art/icons/ability_2handed_002.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 1,
    rank: 1,
    subcategoryId: "vengeance-weapon-two-handed" as const,
  },
  "vengeance-conjured-ward": {
    id: "vengeance-conjured-ward" as const,
    esoSkillId: 237929,
    name: "Vengeance Conjured Ward",
    baseName: "Vengeance Conjured Ward",
    skillLineId: "vengeance-sorcerer-daedric-summoning" as const,
    skillType: "active" as const,
    description:
      "Conjure globes of Daedric energy for protection, granting a damage shield for you that absorbs |cffffff18113|r damage for |cffffff6|r seconds.",
    icon: "/esoui/art/icons/ability_sorcerer_hurricane.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 1,
    rank: 1,
    subcategoryId: "vengeance-sorcerer-daedric-summoning" as const,
  },
  "vengeance-core-of-flame": {
    id: "vengeance-core-of-flame" as const,
    esoSkillId: 237641,
    name: "Vengeance Core of Flame",
    baseName: "Vengeance Core of Flame",
    skillLineId: "vengeance-dragonknight-ardent-flame" as const,
    skillType: "active" as const,
    description:
      "Channel draconic energy to suck in the air around you, increasing your Health, Magicka, and Stamina Recovery by |cffffff1500|r for |cffffff4|r seconds. Afterwards, you exhale fire, dealing |cffffff8820|r Flame Damage to up to 3 nearby enemies.",
    icon: "/esoui/art/icons/ability_dragonknight_012.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 1,
    rank: 1,
    subcategoryId: "vengeance-dragonknight-ardent-flame" as const,
  },
  "vengeance-cripple": {
    id: "vengeance-cripple" as const,
    esoSkillId: 237713,
    name: "Vengeance Cripple",
    baseName: "Vengeance Cripple",
    skillLineId: "vengeance-nightblade-siphoning" as const,
    skillType: "active" as const,
    description:
      "Sap an enemy's agility and wrack them with pain, dealing |cffffff14178|r Magic Damage over |cffffff5|r seconds and reducing their Movement Speed by |cffffff30|r% for |cffffff4|r seconds.",
    icon: "/esoui/art/icons/ability_nightblade_006.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 1,
    rank: 1,
    subcategoryId: "vengeance-nightblade-siphoning" as const,
  },
  "vengeance-critical-charge": {
    id: "vengeance-critical-charge" as const,
    esoSkillId: 240459,
    name: "Vengeance Critical Charge",
    baseName: "Vengeance Critical Charge",
    skillLineId: "vengeance-weapon-two-handed" as const,
    skillType: "active" as const,
    description:
      "Launch across the earth and smash an enemy, dealing |cffffff6678|r Physical Damage. \n\nThis attack is always a Critical Strike.",
    icon: "/esoui/art/icons/ability_2handed_003.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 1,
    rank: 1,
    subcategoryId: "vengeance-weapon-two-handed" as const,
  },
  "vengeance-crystal-shard": {
    id: "vengeance-crystal-shard" as const,
    esoSkillId: 237792,
    name: "Vengeance Crystal Shard",
    baseName: "Vengeance Crystal Shard",
    skillLineId: "vengeance-sorcerer-dark-magic" as const,
    skillType: "active" as const,
    description: "Conjure dark crystals to bombard an enemy, dealing |cffffff11519|r Magic Damage.",
    icon: "/esoui/art/icons/ability_sorcerer_thunderclap.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 1,
    rank: 1,
    subcategoryId: "vengeance-sorcerer-dark-magic" as const,
  },
  "vengeance-crystallized-shield": {
    id: "vengeance-crystallized-shield" as const,
    esoSkillId: 238089,
    name: "Vengeance Crystallized Shield",
    baseName: "Vengeance Crystallized Shield",
    skillLineId: "vengeance-warden-winters-embrace" as const,
    skillType: "active" as const,
    description:
      "Spin a shield of ice around you, absorbing up to |cffffff36225|r damage from projectiles for |cffffff6|r seconds.",
    icon: "/esoui/art/icons/ability_warden_002.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 1,
    rank: 1,
    subcategoryId: "vengeance-warden-winters-embrace" as const,
  },
  "vengeance-daedric-curse": {
    id: "vengeance-daedric-curse" as const,
    esoSkillId: 237876,
    name: "Vengeance Daedric Curse",
    baseName: "Vengeance Daedric Curse",
    skillLineId: "vengeance-sorcerer-daedric-summoning" as const,
    skillType: "active" as const,
    description:
      "Curse an enemy with a destructive rune, dealing |cffffff16027|r Magic Damage to the target after |cffffff6|r seconds.\n\nThis ability cannot be dodged.",
    icon: "/esoui/art/icons/ability_sorcerer_daedric_curse.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 1,
    rank: 1,
    subcategoryId: "vengeance-sorcerer-daedric-summoning" as const,
  },
  "vengeance-daedric-mines": {
    id: "vengeance-daedric-mines" as const,
    esoSkillId: 237812,
    name: "Vengeance Daedric Mines",
    baseName: "Vengeance Daedric Mines",
    skillLineId: "vengeance-sorcerer-dark-magic" as const,
    skillType: "active" as const,
    description:
      "Surprise your foes by detonating |cffffff3|r volatile Daedric mines around you, dealing |cffffff8820|r Magic Damage to up 3 enemies and reducing their movement speed by |cffffff30|r% for |cffffff4|r seconds.",
    icon: "/esoui/art/icons/ability_sorcerer_daedric_mines.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 1,
    rank: 1,
    subcategoryId: "vengeance-sorcerer-dark-magic" as const,
  },
  "vengeance-dark-exchange": {
    id: "vengeance-dark-exchange" as const,
    esoSkillId: 237808,
    name: "Vengeance Dark Exchange",
    baseName: "Vengeance Dark Exchange",
    skillLineId: "vengeance-sorcerer-dark-magic" as const,
    skillType: "active" as const,
    description:
      "Bargain with darkness to restore |cffffff8160|r Health and |cffffff3600|r Magicka.",
    icon: "/esoui/art/icons/ability_sorcerer_dark_exchange.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 1,
    rank: 1,
    subcategoryId: "vengeance-sorcerer-dark-magic" as const,
  },
  "vengeance-dark-talons": {
    id: "vengeance-dark-talons" as const,
    esoSkillId: 237636,
    name: "Vengeance Dark Talons",
    baseName: "Vengeance Dark Talons",
    skillLineId: "vengeance-dragonknight-draconic-power" as const,
    skillType: "active" as const,
    description:
      "Call forth talons from the ground, dealing |cffffff8820|r Flame Damage to up to 3 enemies near you and immobilizing them for |cffffff4|r seconds.",
    icon: "/esoui/art/icons/ability_dragonknight_010.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 1,
    rank: 1,
    subcategoryId: "vengeance-dragonknight-draconic-power" as const,
  },
  "vengeance-dawnbreaker": {
    id: "vengeance-dawnbreaker" as const,
    esoSkillId: 246303,
    name: "Vengeance Dawnbreaker",
    baseName: "Vengeance Dawnbreaker",
    skillLineId: "vengeance-guild-fighters-guild" as const,
    skillType: "ultimate" as const,
    description:
      "Arm yourself with Meridia's sacred sword and dispense her retribution, dealing |cffffff14700|r Physical Damage to up to 3 enemies in front of you and an additional |cffffff15750|r Physical Damage over |cffffff6|r seconds.",
    icon: "/esoui/art/icons/ability_fightersguild_005.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 1,
    rank: 1,
    subcategoryId: "vengeance-guild-fighters-guild" as const,
  },
  "vengeance-death-scythe": {
    id: "vengeance-death-scythe" as const,
    esoSkillId: 238137,
    name: "Vengeance Death Scythe",
    baseName: "Vengeance Death Scythe",
    skillLineId: "vengeance-necromancer-bone-tyrant" as const,
    skillType: "active" as const,
    description:
      "Slice into your enemy's life force, dealing |cffffff2351|r Magic Damage and healing for |cffffff3016|r Health.",
    icon: "/esoui/art/icons/ability_necromancer_007.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 1,
    rank: 1,
    subcategoryId: "vengeance-necromancer-bone-tyrant" as const,
  },
  "vengeance-death-stroke": {
    id: "vengeance-death-stroke" as const,
    esoSkillId: 237619,
    name: "Vengeance Death Stroke",
    baseName: "Vengeance Death Stroke",
    skillLineId: "vengeance-nightblade-assassination" as const,
    skillType: "ultimate" as const,
    description:
      "Ravage an enemy with a swift strike, dealing |cffffff11130|r Magic Damage. Deals up to |cffffff200|r% more damage to enemies under |cffffff50|r% Health.",
    icon: "/esoui/art/icons/ability_nightblade_007.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 1,
    rank: 1,
    subcategoryId: "vengeance-nightblade-assassination" as const,
  },
  "vengeance-defensive-posture": {
    id: "vengeance-defensive-posture" as const,
    esoSkillId: 240560,
    name: "Vengeance Defensive Posture",
    baseName: "Vengeance Defensive Posture",
    skillLineId: "vengeance-weapon-one-hand-and-shield" as const,
    skillType: "active" as const,
    description:
      "Bolster your defenses, gaining a damage shield that absorbs up to |cffffff6802|r damage for |cffffff6|r seconds.  This portion of the ability scales off your Max Health.",
    icon: "/esoui/art/icons/ability_1handed_004.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 1,
    rank: 1,
    subcategoryId: "vengeance-weapon-one-hand-and-shield" as const,
  },
  "vengeance-destructive-touch": {
    id: "vengeance-destructive-touch" as const,
    esoSkillId: 241429,
    name: "Vengeance Destructive Touch",
    baseName: "Vengeance Destructive Touch",
    skillLineId: "vengeance-weapon-destruction-staff" as const,
    skillType: "active" as const,
    description:
      "Devastate an enemy with an enhanced charge from your staff, dealing |cffffff5008|r Magic Damage and an additional |cffffff12285|r Magic Damage over |cffffff6|r seconds. \n\nFlame Touch converts the initial hit into damage over time.\n\nFrost Touch converts some of the damage over time into initial damage.\n\nShock Touch deals damage more rapidly.",
    icon: "/esoui/art/icons/ability_destructionstaff_005.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 1,
    rank: 1,
    subcategoryId: "vengeance-weapon-destruction-staff" as const,
  },
  "vengeance-detonating-siphon": {
    id: "vengeance-detonating-siphon" as const,
    esoSkillId: 238126,
    name: "Vengeance Detonating Siphon",
    baseName: "Vengeance Detonating Siphon",
    skillLineId: "vengeance-necromancer-grave-lord" as const,
    skillType: "active" as const,
    description:
      "Violently drain the last spark of life from a corpse, dealing |cffffff10143|r Disease Damage to up to 3 enemies around the corpse after |cffffff1|r second. Deals up to |cffffff100|r% more damage to enemies under |cffffff50|r% Health.",
    icon: "/esoui/art/icons/ability_necromancer_005_b.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 1,
    rank: 1,
    subcategoryId: "vengeance-necromancer-grave-lord" as const,
  },
  "vengeance-dive": {
    id: "vengeance-dive" as const,
    esoSkillId: 238000,
    name: "Vengeance Dive",
    baseName: "Vengeance Dive",
    skillLineId: "vengeance-warden-animal-companions" as const,
    skillType: "active" as const,
    description:
      "Command a cliff racer to dive bomb an enemy, dealing |cffffff10017|r Magic Damage. \n\nThis ability cannot be blocked.",
    icon: "/esoui/art/icons/ability_warden_013.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 1,
    rank: 1,
    subcategoryId: "vengeance-warden-animal-companions" as const,
  },
  "vengeance-dragon-blood": {
    id: "vengeance-dragon-blood" as const,
    esoSkillId: 237638,
    name: "Vengeance Dragon Blood",
    baseName: "Vengeance Dragon Blood",
    skillLineId: "vengeance-dragonknight-draconic-power" as const,
    skillType: "active" as const,
    description:
      "Draw on your draconic blood to heal for |cffffff5028|r Health, increasing by up to |cffffff50|r% additional healing based on your missing Health. This ability scales off your Max Health.",
    icon: "/esoui/art/icons/ability_dragonknight_011.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 1,
    rank: 1,
    subcategoryId: "vengeance-dragonknight-draconic-power" as const,
  },
  "vengeance-dragon-leap": {
    id: "vengeance-dragon-leap" as const,
    esoSkillId: 237648,
    name: "Vengeance Dragon Leap",
    baseName: "Vengeance Dragon Leap",
    skillLineId: "vengeance-dragonknight-draconic-power" as const,
    skillType: "ultimate" as const,
    description:
      "Launch yourself at an enemy, dealing |cffffff20285|r Physical Damage to up to 3 enemies in the area.",
    icon: "/esoui/art/icons/ability_dragonknight_009.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 1,
    rank: 1,
    subcategoryId: "vengeance-dragonknight-draconic-power" as const,
  },
} satisfies Record<string, SkillTemplate>
