import type { SkillTemplate } from "../character-skill-template/character-skill-template.module.code.ts"

export const CHARACTER_SKILLS_77 = {
  "vengeance-force-shock": {
    id: "vengeance-force-shock" as const,
    esoSkillId: 241291,
    name: "Vengeance Force Shock",
    baseName: "Vengeance Force Shock",
    skillLineId: "vengeance-weapon-destruction-staff" as const,
    skillType: "active" as const,
    description:
      "Focus on one of the elemental energies with your staff and blast an enemy for |cffffff10017|r Flame Damage, |cffffff10017|r Frost Damage, or |cffffff10017|r Shock Damage.",
    icon: "/esoui/art/icons/ability_destructionstaff_001.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 1,
    rank: 1,
    subcategoryId: "vengeance-weapon-destruction-staff" as const,
  },
  "vengeance-force-siphon": {
    id: "vengeance-force-siphon" as const,
    esoSkillId: 241536,
    name: "Vengeance Force Siphon",
    baseName: "Vengeance Force Siphon",
    skillLineId: "vengeance-weapon-restoration-staff" as const,
    skillType: "active" as const,
    description:
      "Focus your staff's power to apply Minor Lifesteal and Minor Magickasteal to an enemy for |cffffff20|r seconds, healing you and your allies for |cffffff600|r Health and restoring |cffffff168|r Magicka every |cffffff1|r second when damaging them.",
    icon: "/esoui/art/icons/ability_restorationstaff_005.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 1,
    rank: 1,
    subcategoryId: "vengeance-weapon-restoration-staff" as const,
  },
  "vengeance-frost-cloak": {
    id: "vengeance-frost-cloak" as const,
    esoSkillId: 238076,
    name: "Vengeance Frost Cloak",
    baseName: "Vengeance Frost Cloak",
    skillLineId: "vengeance-warden-winters-embrace" as const,
    skillType: "active" as const,
    description:
      "Wrap a thick cloak of ice around yourself and up to 2 grouped allies. The ice grants Major Resolve, increasing your Physical and Spell Resistance by |cffffff5948|r for |cffffff20|r seconds.",
    icon: "/esoui/art/icons/ability_warden_001.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 1,
    rank: 1,
    subcategoryId: "vengeance-warden-winters-embrace" as const,
  },
  "vengeance-frozen-colossus": {
    id: "vengeance-frozen-colossus" as const,
    esoSkillId: 238129,
    name: "Vengeance Frozen Colossus",
    baseName: "Vengeance Frozen Colossus",
    skillLineId: "vengeance-necromancer-grave-lord" as const,
    skillType: "ultimate" as const,
    description:
      "Unleash a frostbitten Flesh Colossus to pulverize up to 3 enemies in the area. The Colossus smashes the ground three times over |cffffff3|r seconds, dealing |cffffff13720|r Frost Damage with each smash.",
    icon: "/esoui/art/icons/ability_necromancer_006.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 1,
    rank: 1,
    subcategoryId: "vengeance-necromancer-grave-lord" as const,
  },
  "vengeance-frozen-gate": {
    id: "vengeance-frozen-gate" as const,
    esoSkillId: 238091,
    name: "Vengeance Frozen Gate",
    baseName: "Vengeance Frozen Gate",
    skillLineId: "vengeance-warden-winters-embrace" as const,
    skillType: "active" as const,
    description:
      "Summon an ancient portal, that after |cffffff2|r seconds teleports an enemy in the area to you and immobilizes them for |cffffff3|r seconds.",
    icon: "/esoui/art/icons/ability_warden_005.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 1,
    rank: 1,
    subcategoryId: "vengeance-warden-winters-embrace" as const,
  },
  "vengeance-fungal-growth": {
    id: "vengeance-fungal-growth" as const,
    esoSkillId: 238054,
    name: "Vengeance Fungal Growth",
    baseName: "Vengeance Fungal Growth",
    skillLineId: "vengeance-warden-green-balance" as const,
    skillType: "active" as const,
    description:
      "Seed a large area of mushrooms in front of you, healing up to 3 of you and your allies for |cffffff12048|r Health.",
    icon: "/esoui/art/icons/ability_warden_008.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 1,
    rank: 1,
    subcategoryId: "vengeance-warden-green-balance" as const,
  },
  "vengeance-gibbering-shield": {
    id: "vengeance-gibbering-shield" as const,
    esoSkillId: 238274,
    name: "Vengeance Gibbering Shield",
    baseName: "Vengeance Gibbering Shield",
    skillLineId: "vengeance-arcanist-soldier-of-apocrypha" as const,
    skillType: "ultimate" as const,
    description:
      "Gather the true strength of Apocrypha around you, forming protective tentacles and a damage shield that absorbs |cffffff60%|r of all damage for |cffffff10|r seconds, up to a max of |cffffff80500|r damage.\n\nWhen the shield collapses you lash out, dealing |cffffff13440|r Magic Damage to up to 3 enemies within 5 meters.",
    icon: "/esoui/art/icons/ability_arcanist_012.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 1,
    rank: 1,
    subcategoryId: "vengeance-arcanist-soldier-of-apocrypha" as const,
  },
  "vengeance-grand-healing": {
    id: "vengeance-grand-healing" as const,
    esoSkillId: 241517,
    name: "Vengeance Grand Healing",
    baseName: "Vengeance Grand Healing",
    skillLineId: "vengeance-weapon-restoration-staff" as const,
    skillType: "active" as const,
    description:
      "Summon restoring spirits with your staff at the target location, healing up to 3 of you and your allies for |cffffff24096|r Health over |cffffff5|r seconds.",
    icon: "/esoui/art/icons/ability_restorationstaff_004.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 1,
    rank: 1,
    subcategoryId: "vengeance-weapon-restoration-staff" as const,
  },
  "vengeance-grave-grasp": {
    id: "vengeance-grave-grasp" as const,
    esoSkillId: 253156,
    name: "Vengeance Grave Grasp",
    baseName: "Vengeance Grave Grasp",
    skillLineId: "vengeance-necromancer-bone-tyrant" as const,
    skillType: "active" as const,
    description:
      "Summon three patches of skeletal claws from the ground in front of you to grab up to 3 enemies, immobilizing them for |cffffff3|r seconds and applying Minor Maim for |cffffff10|r seconds, reducing their damage done by |cffffff5|r%.",
    icon: "/esoui/art/icons/ability_necromancer_009.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 1,
    rank: 1,
    subcategoryId: "vengeance-necromancer-bone-tyrant" as const,
  },
  "vengeance-grim-focus": {
    id: "vengeance-grim-focus" as const,
    esoSkillId: 237605,
    name: "Vengeance Grim Focus",
    baseName: "Vengeance Grim Focus",
    skillLineId: "vengeance-nightblade-assassination" as const,
    skillType: "active" as const,
    description:
      "Focus your lethal intent into a spectral bow to fire at an enemy, dealing |cffffff20034|r Magic Damage, up to once every |cffffff5|r seconds.",
    icon: "/esoui/art/icons/ability_nightblade_005.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 1,
    rank: 1,
    subcategoryId: "vengeance-nightblade-assassination" as const,
  },
  "vengeance-guard": {
    id: "vengeance-guard" as const,
    esoSkillId: 245055,
    name: "Vengeance Guard",
    baseName: "Vengeance Guard",
    skillLineId: "vengeance-alliance-war-support" as const,
    skillType: "active" as const,
    description:
      "Create a lifebond between you and a group member for |cffffff20|r seconds. While bonded, your ally reduces their damage taken by |cffffff10|r% and increase your damage taken by |cffffff10|r%.\n\nThe bond will break if you move more than |cffffff17|r meters away from your target.",
    icon: "/esoui/art/icons/ability_ava_guard.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 1,
    rank: 1,
    subcategoryId: "vengeance-alliance-war-support" as const,
  },
  "vengeance-healing-ritual": {
    id: "vengeance-healing-ritual" as const,
    esoSkillId: 238018,
    name: "Vengeance Healing Ritual",
    baseName: "Vengeance Healing Ritual",
    skillLineId: "vengeance-templar-restoring-light" as const,
    skillType: "active" as const,
    description:
      "Focus your spiritual devotion, healing you or up to 3 nearby allies for |cffffff12049|r Health.",
    icon: "/esoui/art/icons/ability_templar_healing_ritual.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 1,
    rank: 1,
    subcategoryId: "vengeance-templar-restoring-light" as const,
  },
  "vengeance-healing-seed": {
    id: "vengeance-healing-seed" as const,
    esoSkillId: 238055,
    name: "Vengeance Healing Seed",
    baseName: "Vengeance Healing Seed",
    skillLineId: "vengeance-warden-green-balance" as const,
    skillType: "active" as const,
    description:
      "Summon a field of flowers which blooms after |cffffff6|r seconds, healing up to 3 of you and your allies in the area for |cffffff16065|r Health.",
    icon: "/esoui/art/icons/ability_warden_007.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 1,
    rank: 1,
    subcategoryId: "vengeance-warden-green-balance" as const,
  },
  "vengeance-hearthfire": {
    id: "vengeance-hearthfire" as const,
    esoSkillId: 237788,
    name: "Vengeance Hearthfire",
    baseName: "Vengeance Hearthfire",
    skillLineId: "vengeance-dragonknight-ardent-flame" as const,
    skillType: "active" as const,
    description:
      "Tend to a warming tinder that heals up to 3 of you and your allies for |cffffff12048|r Health.",
    icon: "/esoui/art/icons/ability_dragonknight_016.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 1,
    rank: 1,
    subcategoryId: "vengeance-dragonknight-ardent-flame" as const,
  },
  "vengeance-hidden-blade": {
    id: "vengeance-hidden-blade" as const,
    esoSkillId: 241234,
    name: "Vengeance Hidden Blade",
    baseName: "Vengeance Hidden Blade",
    skillLineId: "vengeance-weapon-dual-wield" as const,
    skillType: "active" as const,
    description:
      "Fire a secret dagger from your sleeve at an enemy, dealing |cffffff10017|r Physical Damage.\n\nIf the enemy hit is casting an ability they are interrupted, set Off Balance, and stunned for |cffffff3|r seconds.",
    icon: "/esoui/art/icons/ability_dualwield_003.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 1,
    rank: 1,
    subcategoryId: "vengeance-weapon-dual-wield" as const,
  },
  "vengeance-impaling-shards": {
    id: "vengeance-impaling-shards" as const,
    esoSkillId: 238079,
    name: "Vengeance Impaling Shards",
    baseName: "Vengeance Impaling Shards",
    skillLineId: "vengeance-warden-winters-embrace" as const,
    skillType: "active" as const,
    description:
      "Conjure icy shards around you to skewer up to 3 enemies in the area, dealing |cffffff8820|r Frost Damage and immobilizing them for |cffffff3|r seconds.",
    icon: "/esoui/art/icons/ability_warden_004.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 1,
    rank: 1,
    subcategoryId: "vengeance-warden-winters-embrace" as const,
  },
  "vengeance-impulse": {
    id: "vengeance-impulse" as const,
    esoSkillId: 241454,
    name: "Vengeance Impulse",
    baseName: "Vengeance Impulse",
    skillLineId: "vengeance-weapon-destruction-staff" as const,
    skillType: "active" as const,
    description:
      "Release a surge of elemental energy, dealing |cffffff8820|r Magic Damage to up to 3 nearby enemies.\n\nFire Impulse converts some of the initial hit into damage over time.\n\nFrost Impulse costs more but provides Minor Protection.\n\nShock Impulse deals less damage but has a chance to deal increased damage.",
    icon: "/esoui/art/icons/ability_destructionstaff_008.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 1,
    rank: 1,
    subcategoryId: "vengeance-weapon-destruction-staff" as const,
  },
  "vengeance-inferno": {
    id: "vengeance-inferno" as const,
    esoSkillId: 237624,
    name: "Vengeance Inferno",
    baseName: "Vengeance Inferno",
    skillLineId: "vengeance-dragonknight-ardent-flame" as const,
    skillType: "active" as const,
    description:
      "Surround yourself in an aura of flames, granting you Major Berserk for |cffffff20|r seconds, increasing your damage done by |cffffff10|r%.",
    icon: "/esoui/art/icons/ability_dragonknight_002.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 1,
    rank: 1,
    subcategoryId: "vengeance-dragonknight-ardent-flame" as const,
  },
  "vengeance-lacerate": {
    id: "vengeance-lacerate" as const,
    esoSkillId: 241236,
    name: "Vengeance Lacerate",
    baseName: "Vengeance Lacerate",
    skillLineId: "vengeance-weapon-dual-wield" as const,
    skillType: "ultimate" as const,
    description:
      "Slash up to 3 enemies in front of you, causing them to bleed for |cffffff43785|r Bleed Damage over |cffffff8|r seconds. You heal |cffffff3213|r Health every time damage is dealt.",
    icon: "/esoui/art/icons/ability_dualwield_006.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 1,
    rank: 1,
    subcategoryId: "vengeance-weapon-dual-wield" as const,
  },
  "vengeance-lava-whip": {
    id: "vengeance-lava-whip" as const,
    esoSkillId: 237606,
    name: "Vengeance Lava Whip",
    baseName: "Vengeance Lava Whip",
    skillLineId: "vengeance-dragonknight-ardent-flame" as const,
    skillType: "active" as const,
    description: "Lash an enemy with flame, dealing |cffffff11130|r Flame Damage.",
    icon: "/esoui/art/icons/ability_dragonknight_001.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 1,
    rank: 1,
    subcategoryId: "vengeance-dragonknight-ardent-flame" as const,
  },
  "vengeance-life-amid-death": {
    id: "vengeance-life-amid-death" as const,
    esoSkillId: 238258,
    name: "Vengeance Life amid Death",
    baseName: "Vengeance Life amid Death",
    skillLineId: "vengeance-necromancer-living-death" as const,
    skillType: "active" as const,
    description:
      "Release residual fragments of fallen souls at the target location, healing you or up to 3 allies in the area for |cffffff10710|r Health.",
    icon: "/esoui/art/icons/ability_necromancer_016.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 1,
    rank: 1,
    subcategoryId: "vengeance-necromancer-living-death" as const,
  },
} satisfies Record<string, SkillTemplate>
