import { describe, expect, test } from "bun:test"
import {
  type CompanionsConfigFileInputs,
  serializeCompanionsConfigFile,
} from "./export-companion-builds-config-file"

const COMPANIONS_CONFIG_REQUIRED_KEYS = [
  "version",
  "companionTargetBuilds",
  "companionTargetTimestamps",
] as const

const minimalInputs: CompanionsConfigFileInputs = {
  companionTargetBuilds: {},
  companionTargetTimestamps: {},
}

const fullInputs: CompanionsConfigFileInputs = {
  companionTargetBuilds: { 1: "hash-1", 8: "hash-8" },
  companionTargetTimestamps: { 1: 1700000000, 8: 1700000008 },
}

describe("serializeCompanionsConfigFile", () => {
  test("emits the documented header and top-level assignment", () => {
    const out = serializeCompanionsConfigFile(minimalInputs)
    expect(out.startsWith("-- Auto-generated by the Temper watcher; do not edit by hand.\n")).toBe(
      true
    )
    expect(out).toContain("TemperCompanionsConfig =\n{\n")
    expect(out.endsWith("}\n")).toBe(true)
  })

  test("emits version stamp first", () => {
    const out = serializeCompanionsConfigFile(minimalInputs)
    const lines = out.split("\n")
    const openIdx = lines.indexOf("{")
    expect(openIdx).toBeGreaterThanOrEqual(0)
    expect(lines[openIdx + 1]).toBe('    ["version"] = 1,')
  })

  test("emits every required key on minimal inputs", () => {
    const out = serializeCompanionsConfigFile(minimalInputs)
    for (const key of COMPANIONS_CONFIG_REQUIRED_KEYS) {
      expect(out).toContain(`["${key}"]`)
    }
  })

  test("emits every required key on full inputs", () => {
    const out = serializeCompanionsConfigFile(fullInputs)
    for (const key of COMPANIONS_CONFIG_REQUIRED_KEYS) {
      expect(out).toContain(`["${key}"]`)
    }
    expect(out).toContain(`[1] = "hash-1"`)
    expect(out).toContain(`[8] = "hash-8"`)
    expect(out).toContain(`[1] = 1700000000`)
    expect(out).toContain(`[8] = 1700000008`)
  })

  test("emits no unexpected top-level keys", () => {
    const out = serializeCompanionsConfigFile(fullInputs)
    const topLevelKeys = extractTopLevelKeys(out)
    const expected = new Set<string>(COMPANIONS_CONFIG_REQUIRED_KEYS)
    expect(new Set(topLevelKeys)).toEqual(expected)
  })

  test("produces byte-identical output on repeated calls (minimal inputs)", () => {
    const a = serializeCompanionsConfigFile(minimalInputs)
    const b = serializeCompanionsConfigFile(minimalInputs)
    expect(a).toBe(b)
  })

  test("produces byte-identical output on repeated calls (full inputs)", () => {
    const a = serializeCompanionsConfigFile(fullInputs)
    const b = serializeCompanionsConfigFile(fullInputs)
    expect(a).toBe(b)
  })

  test("preserves the documented key order", () => {
    const out = serializeCompanionsConfigFile(fullInputs)
    const indices = ["version", "companionTargetBuilds", "companionTargetTimestamps"].map((k) =>
      out.indexOf(`["${k}"]`)
    )
    for (let i = 1; i < indices.length; i++) {
      const prev = indices[i - 1] ?? -1
      const cur = indices[i] ?? -1
      expect(cur).toBeGreaterThan(prev)
    }
  })

  test("sorts numeric keys in ascending order within each block", () => {
    const out = serializeCompanionsConfigFile({
      companionTargetBuilds: { 8: "hash-8", 1: "hash-1", 3: "hash-3" },
      companionTargetTimestamps: { 8: 800, 1: 100, 3: 300 },
    })
    const idx1 = out.indexOf(`[1] = "hash-1"`)
    const idx3 = out.indexOf(`[3] = "hash-3"`)
    const idx8 = out.indexOf(`[8] = "hash-8"`)
    expect(idx1).toBeGreaterThan(0)
    expect(idx3).toBeGreaterThan(idx1)
    expect(idx8).toBeGreaterThan(idx3)
  })
})

function extractTopLevelKeys(out: string): readonly string[] {
  const keys: string[] = []
  const lines = out.split("\n")
  let depth = 0
  const KEY_PREFIX = '    ["'
  const KEY_SUFFIX = '"]'
  for (const line of lines) {
    const opens = countChar(line, "{")
    const closes = countChar(line, "}")
    if (depth === 1 && line.startsWith(KEY_PREFIX)) {
      const end = line.indexOf(KEY_SUFFIX, KEY_PREFIX.length)
      if (end > KEY_PREFIX.length) {
        keys.push(line.slice(KEY_PREFIX.length, end))
      }
    }
    depth += opens - closes
  }
  return keys
}

function countChar(s: string, ch: string): number {
  let n = 0
  for (const c of s) if (c === ch) n += 1
  return n
}
