const SIDE_FILE_VERSION = 1

const HEADER_COMMENT = "-- Auto-generated by the Temper watcher; do not edit by hand."
const TOP_LEVEL_NAME = "TemperCompanionsConfig"
const BLOCK_INDENT = "    "

export interface CompanionsConfigFileInputs {
  readonly companionTargetBuilds: Readonly<Record<number, string>>
  readonly companionTargetTimestamps: Readonly<Record<number, number>>
}

function serializeNumericKeyedBlock(
  key: string,
  data: Readonly<Record<number, string | number>>,
  indent: string
): readonly string[] {
  const innerIndent = `${indent}    `
  const entries = Object.entries(data).sort(([a], [b]) => Number(a) - Number(b))

  if (entries.length === 0) {
    return [`${indent}["${key}"] = {},`]
  }

  const lines: string[] = []
  lines.push(`${indent}["${key}"] =`)
  lines.push(`${indent}{`)
  for (const [numKey, value] of entries) {
    const luaValue = typeof value === "string" ? `"${value}"` : String(value)
    lines.push(`${innerIndent}[${numKey}] = ${luaValue},`)
  }
  lines.push(`${indent}},`)
  return lines
}

export function serializeCompanionsConfigFile(inputs: CompanionsConfigFileInputs): string {
  const lines: string[] = []
  lines.push(HEADER_COMMENT)
  lines.push(`${TOP_LEVEL_NAME} =`)
  lines.push("{")

  lines.push(`${BLOCK_INDENT}["version"] = ${SIDE_FILE_VERSION},`)

  lines.push(
    ...serializeNumericKeyedBlock(
      "companionTargetBuilds",
      inputs.companionTargetBuilds,
      BLOCK_INDENT
    )
  )
  lines.push(
    ...serializeNumericKeyedBlock(
      "companionTargetTimestamps",
      inputs.companionTargetTimestamps,
      BLOCK_INDENT
    )
  )

  lines.push("}")
  lines.push("")
  return lines.join("\n")
}
