import { describe, expect, test } from "bun:test"
import {
  type CharactersConfigFileInputs,
  serializeCharactersConfigFile,
} from "./export-tasks-config-file"

const CHARACTERS_CONFIG_REQUIRED_KEYS = [
  "version",
  "characterPriority",
  "tasks",
  "completionOverrides",
] as const

const minimalInputs: CharactersConfigFileInputs = {
  characterPriority: [],
  tasks: {},
  completionOverrides: {},
}

const fullInputs: CharactersConfigFileInputs = {
  characterPriority: ["char-1", "char-2"],
  tasks: {
    "task-uuid-1": {
      title: "Daily Writs",
      description: null,
      rrule: "FREQ=DAILY",
      dueDate: null,
      dueTime: null,
      scope: "account",
      esoCharacterId: null,
      sortOrder: 1,
      completionCardId: null,
      completionItemPath: null,
    },
  },
  completionOverrides: {
    "1234567890123456": [
      {
        completionCardId: "skill-points",
        completionItemPath: ["general", "foliumDiscognitum"],
        floor: 1,
      },
    ],
  },
}

describe("serializeCharactersConfigFile", () => {
  test("emits the documented header and top-level assignment", () => {
    const out = serializeCharactersConfigFile(minimalInputs)
    expect(out.startsWith("-- Auto-generated by the Temper watcher; do not edit by hand.\n")).toBe(
      true
    )
    expect(out).toContain("TemperCharactersConfig =\n{\n")
    expect(out.endsWith("}\n")).toBe(true)
  })

  test("emits version stamp first", () => {
    const out = serializeCharactersConfigFile(minimalInputs)
    const lines = out.split("\n")
    const openIdx = lines.indexOf("{")
    expect(openIdx).toBeGreaterThanOrEqual(0)
    expect(lines[openIdx + 1]).toBe('    ["version"] = 1,')
  })

  test("emits every required key on minimal inputs", () => {
    const out = serializeCharactersConfigFile(minimalInputs)
    for (const key of CHARACTERS_CONFIG_REQUIRED_KEYS) {
      expect(out).toContain(`["${key}"]`)
    }
  })

  test("emits every required key on full inputs", () => {
    const out = serializeCharactersConfigFile(fullInputs)
    for (const key of CHARACTERS_CONFIG_REQUIRED_KEYS) {
      expect(out).toContain(`["${key}"]`)
    }
  })

  test("emits no unexpected top-level keys", () => {
    const out = serializeCharactersConfigFile(fullInputs)
    const topLevelKeys = extractTopLevelKeys(out)
    const expected = new Set<string>([...CHARACTERS_CONFIG_REQUIRED_KEYS])
    expect(new Set(topLevelKeys)).toEqual(expected)
  })

  test("produces byte-identical output on repeated calls (minimal inputs)", () => {
    const a = serializeCharactersConfigFile(minimalInputs)
    const b = serializeCharactersConfigFile(minimalInputs)
    expect(a).toBe(b)
  })

  test("produces byte-identical output on repeated calls (full inputs)", () => {
    const a = serializeCharactersConfigFile(fullInputs)
    const b = serializeCharactersConfigFile(fullInputs)
    expect(a).toBe(b)
  })

  test("preserves the documented key order", () => {
    const out = serializeCharactersConfigFile(fullInputs)
    const indices = ["version", "characterPriority", "tasks", "completionOverrides"].map((k) =>
      out.indexOf(`["${k}"]`)
    )
    for (let i = 1; i < indices.length; i++) {
      const prev = indices[i - 1] ?? -1
      const cur = indices[i] ?? -1
      expect(cur).toBeGreaterThan(prev)
    }
  })
})

function extractTopLevelKeys(out: string): readonly string[] {
  const keys: string[] = []
  const lines = out.split("\n")
  let depth = 0
  const KEY_PREFIX = '    ["'
  const KEY_SUFFIX = '"]'
  for (const line of lines) {
    const opens = countChar(line, "{")
    const closes = countChar(line, "}")
    if (depth === 1 && line.startsWith(KEY_PREFIX)) {
      const end = line.indexOf(KEY_SUFFIX, KEY_PREFIX.length)
      if (end > KEY_PREFIX.length) {
        keys.push(line.slice(KEY_PREFIX.length, end))
      }
    }
    depth += opens - closes
  }
  return keys
}

function countChar(s: string, ch: string): number {
  let n = 0
  for (const c of s) if (c === ch) n += 1
  return n
}
