import { serializeLuaBlock } from "@temper/shared-saved-variables/lua-serializer"

const SIDE_FILE_VERSION = 1

const HEADER_COMMENT = "-- Auto-generated by the Temper watcher; do not edit by hand."
const TOP_LEVEL_NAME = "TemperInventoryConfig"
const BLOCK_INDENT = "    "

export interface InventoryConfigFileInputs {
  readonly sell?: unknown
  readonly sellTimestamps?: unknown
  readonly sellCompiled?: unknown
  readonly logging: unknown
  readonly safety: unknown
  readonly backpack: unknown
  readonly automation?: unknown
  readonly currencyRates: Record<string, number>
  readonly crownReplacementCosts: Record<number, number>
}

export function serializeInventoryConfigFile(inputs: InventoryConfigFileInputs): string {
  const lines: string[] = []
  lines.push(HEADER_COMMENT)
  lines.push(`${TOP_LEVEL_NAME} =`)
  lines.push("{")

  lines.push(`${BLOCK_INDENT}["version"] = ${SIDE_FILE_VERSION},`)

  if (inputs.sell !== undefined) {
    lines.push(...serializeLuaBlock("sell", inputs.sell, BLOCK_INDENT))
  }
  if (inputs.sellTimestamps !== undefined) {
    lines.push(...serializeLuaBlock("sellTimestamps", inputs.sellTimestamps, BLOCK_INDENT))
  }
  if (inputs.sellCompiled !== undefined) {
    lines.push(...serializeLuaBlock("sellCompiled", inputs.sellCompiled, BLOCK_INDENT))
  }
  lines.push(...serializeLuaBlock("logging", inputs.logging, BLOCK_INDENT))
  lines.push(...serializeLuaBlock("safety", inputs.safety, BLOCK_INDENT))
  if (inputs.automation !== undefined) {
    lines.push(...serializeLuaBlock("automation", inputs.automation, BLOCK_INDENT))
  }
  lines.push(...serializeLuaBlock("backpack", inputs.backpack, BLOCK_INDENT))
  lines.push(...serializeLuaBlock("currencyRates", inputs.currencyRates, BLOCK_INDENT))
  lines.push(
    ...serializeLuaBlock("crownReplacementCosts", inputs.crownReplacementCosts, BLOCK_INDENT)
  )

  lines.push("}")
  lines.push("")
  return lines.join("\n")
}
