import { serializeLuaBlock } from "@temper/shared-saved-variables/lua-serializer"

const SIDE_FILE_VERSION = 1

const HEADER_COMMENT = "-- Auto-generated by the Temper watcher; do not edit by hand."
const TOP_LEVEL_NAME = "TemperCharactersConfig"
const BLOCK_INDENT = "    "

export interface CharactersConfigFileInputs {
  readonly characterPriority: readonly string[]
  readonly tasks: Readonly<Record<string, unknown>>
  readonly completionOverrides: Readonly<Record<string, unknown>>
}

export function serializeCharactersConfigFile(inputs: CharactersConfigFileInputs): string {
  const lines: string[] = []
  lines.push(HEADER_COMMENT)
  lines.push(`${TOP_LEVEL_NAME} =`)
  lines.push("{")

  lines.push(`${BLOCK_INDENT}["version"] = ${SIDE_FILE_VERSION},`)

  lines.push(...serializeLuaBlock("characterPriority", inputs.characterPriority, BLOCK_INDENT))
  lines.push(...serializeLuaBlock("tasks", inputs.tasks, BLOCK_INDENT))
  lines.push(...serializeLuaBlock("completionOverrides", inputs.completionOverrides, BLOCK_INDENT))

  lines.push("}")
  lines.push("")
  return lines.join("\n")
}
