import type { Domain } from "akasha/domain/domain.page-type.types.ts"

export const temperSkyshard = {
  id: "01a061a8-9c6d-7ae0-b6d1-1fa0685e81a5",
  type: "page-type/domain",
  slug: "temper-skyshard",
  definition: "every skyshard in Tamriel, shown on the map and the compass until the player has it",
  parts: [
    "module/skyshards-constants",
    "module/skyshards-data",
    "module/skyshards-data-accessors",
    "module/skyshards-pages-1",
    "module/skyshards-pages-2",
    "module/skyshards-pages-3",
    "module/skyshards-pages-4",
    "module/skyshards-pages-5",
    "module/skyshards-pages-6",
    "module/skyshards-pages-7",
    "module/skyshards-pages-8",
    "module/skyshards-pages-9",
    "module/skyshards-pages-10",
    "module/skyshards-pc-compass",
    "module/skyshards-pc-events",
    "module/skyshards-pc-immersive",
    "module/skyshards-pc-pin-data",
    "module/skyshards-pc-pins",
    "module/skyshards-pc-settings",
    "module/skyshards-pc-skill-panel",
    "module/skyshards-pc-slash",
    "module/skyshards-pc-state",
    "module/skyshards-pc-tooltip",
    "module/skyshards-skill-point-total",
    "module/skyshards-start",
    "module/skyshards-types",
    "module/skyshards-ui-strings",
    "page-type/temper-world-skyshard",
    "type-declaration/skyshards-controls",
    "type-declaration/skyshards-string-ids",
  ],
  decisions: [
    {
      decisionKind: "decision-kind/departure",
      statement: "Nothing here reaches a Date.",
    },
    {
      decisionKind: "decision-kind/departure",
      statement: "The text here is English alone.",
    },
    {
      decisionKind: "decision-kind/departure",
      statement: "The placement table here is a frozen port of an upstream table.",
    },
    {
      decisionKind: "decision-kind/gap",
      statement: "No program in this repository rebuilds the placement table.",
    },
  ],
} as const satisfies Domain
