import type { TemperSet } from "akasha/temper/catalog/gear/temper-set/temper-set.page-type.types.ts"

export const nightMothersEmbrace = {
  id: "019e66e7-6a74-7e22-88a6-ade5c30eaf2c",
  type: "page-type/temper-set",
  slug: "night-mothers-embrace",
  title: "Night Mother's Embrace",
  key: "night-mothers-embrace",
  esoSetId: 34,
  setWayshrines: [28, 28, 28],
  setTypeId: 9,
  setProcsAllowedInPvp: true,
  setNameZh: "夜母之拥",
  setNameRu: "Объятия Матери Ночи",
  setNameFr: "Étreinte de la Mère de la nuit",
  setNameEs: "Abrazo de la Madre Noche",
  setNameDe: "Umarmung der Mutter der Nacht",
  setDropZones: [57, 57, 306, 57, 101],
  setDropMechanics: [7, 8, 9, 10, 25],
  setDlcId: 0,
  itemBrowserSources: ["57"],
  itemBrowserPlaceKinds: [1],
  itemBrowserItemId: 96979,
  esoItemIds: [
    75063, 75064, 75065, 75066, 75067, 75068, 75069, 75070, 75071, 75072, 75073, 75074, 75075,
    96970, 96971, 96972, 96973, 96974, 96975, 96976, 96977, 96978,
  ],
  esoArmorTypes: ["ARMORTYPE_MEDIUM"],
  esoEquipTypes: [
    "EQUIP_TYPE_CHEST",
    "EQUIP_TYPE_FEET",
    "EQUIP_TYPE_HAND",
    "EQUIP_TYPE_HEAD",
    "EQUIP_TYPE_LEGS",
    "EQUIP_TYPE_NECK",
    "EQUIP_TYPE_OFF_HAND",
    "EQUIP_TYPE_ONE_HAND",
    "EQUIP_TYPE_RING",
    "EQUIP_TYPE_SHOULDERS",
    "EQUIP_TYPE_TWO_HAND",
    "EQUIP_TYPE_WAIST",
  ],
  esoWeaponTypes: [
    "WEAPONTYPE_AXE",
    "WEAPONTYPE_BOW",
    "WEAPONTYPE_DAGGER",
    "WEAPONTYPE_FIRE_STAFF",
    "WEAPONTYPE_FROST_STAFF",
    "WEAPONTYPE_HAMMER",
    "WEAPONTYPE_HEALING_STAFF",
    "WEAPONTYPE_LIGHTNING_STAFF",
    "WEAPONTYPE_SHIELD",
    "WEAPONTYPE_SWORD",
    "WEAPONTYPE_TWO_HANDED_AXE",
    "WEAPONTYPE_TWO_HANDED_HAMMER",
    "WEAPONTYPE_TWO_HANDED_SWORD",
  ],
  category: "temper-set-category/overland",
  valid: ["*"],
  bonuses: "jsonl",
  icons: "jsonl",
} as const satisfies TemperSet
