import type { StoryTurnPlayed } from "akasha/story/world/stories/played/turns/story-turn-played.page-type.types.ts"

export const overwhereIii00060 = {
  id: "01a0fdba-fd20-739e-ab88-f5a06fb59b46",
  type: "page-type/story-turn-played",
  slug: "overwhere-iii-00-060",
  cover: "image/image-1972c1c2c7ffddd0",
  coverAfter: "You sit against the shrine's warm stone in the dark. The white-gold",
  ownLength: 155,
  unit: "unit/words",
  partOfCollections: ["story-played/overwhere-iii"],
  position: 60,
  prose: "txt",
  characters: [
    "character-player/overwhere-iii-nala",
    "character-other/overwhere-iii-marda-hesk",
    "character-other/overwhere-iii-brannagh-tull",
  ],
  stepStatus: "step-status/player",
  action:
    "I go back to the post to finish draining my mana, then to the shrine to recover, then back to Brannagh’s.",
  beats: [
    "Nala hurries down to the Post. Marda is already eyeing the light.",
    '"One," Marda says, and tongs out the wolf\'s second stone.',
    "Nala loops the weave tight. It sinks in deep and clean, and a thick dark vein tears away.",
    "The wolf's stone is over half pale now.",
    "The dusk bell rings. Marda tongs it back into the lead box and locks it. Nala still has mana left.",
    "She walks out the night wicket, past the guard, and two miles down the dark road to the crossroads.",
    "She sits against the shrine's warm stone in the dark. The white-gold threads seep in.",
    "She rests a bit over an hour. Her well is two-thirds full, and the throb in her temples is gone.",
    "She walks the two miles back, in through the wicket, and along the dark streets to Brannagh's lane.",
    "Brannagh's shutters are closed. No light shows under the door. The bench outside is empty.",
  ],
  issues: [
    '"In two hours her well is brimming" - plus 4 miles walked, overruns 5:45 dusk to 8:20 arrival',
  ],
  lore: [
    "lore/overwhere-iii-brannagh-tull",
    "lore/overwhere-iii-brannagh-tull-2",
    "lore/overwhere-iii-cleansing-weave",
    "lore/overwhere-iii-corruption",
    "lore/overwhere-iii-marda-hesk",
    "lore/overwhere-iii-nala",
    "lore/overwhere-iii-nala-2",
    "place/overwhere-iii-merrowgate",
    "place/overwhere-iii-merrowgate-guild-post",
    "place/overwhere-iii-wrenwood-crossroads",
  ],
  reviewedBy: ["story-reviewer/style", "story-reviewer/continuity"],
  recordedBy: [
    "story-recorder/inventory",
    "story-recorder/memory",
    "story-recorder/mechanics",
    "story-recorder/picture",
  ],
  endsAt: "2026-10-05T20:20:00.000Z",
} as const satisfies StoryTurnPlayed
