import type { StoryTurnPlayed } from "akasha/story/world/stories/played/turns/story-turn-played.page-type.types.ts"

export const overwhereIii00051 = {
  id: "01a0fd47-0a92-7774-b434-b28165b003fb",
  type: "page-type/story-turn-played",
  slug: "overwhere-iii-00-051",
  cover: "image/image-39caf7be0dc3039e",
  coverAfter: 'Maud looks you over, sweat-soaked and grass-stained. "Three days. You\'ll do," she',
  ownLength: 262,
  unit: "unit/words",
  partOfCollections: ["story-played/overwhere-iii"],
  position: 51,
  prose: "txt",
  characters: [
    "character-player/overwhere-iii-nala",
    "character-other/overwhere-iii-brannagh-tull",
    "character-other/overwhere-iii-marda-hesk",
    "character-other/overwhere-iii-maud-ferrow",
    "character-other/overwhere-iii-tam-rowe",
  ],
  stepStatus: "step-status/player",
  action:
    "I check in at Brannagh’s and the Post to drain my mana, then train my body with the guards.",
  beats: [
    "At first light Nala looks in at Brannagh's. Nothing fresh on the bench, no new blight.",
    "The drover with the burned arm is there anyway, first name on the slate. He nods to her and waits.",
    "Nala goes on down to the Post. Marda sets the paled wolf's blightstone on the desk.",
    "To Nala's new sight the currents in the room run sharper, and they pour into her weave like a flood.",
    "The first weave bites deep. The second fights her; cold stabs up to her elbow, but the black gives.",
    "The third goes through clean. Then the fourth.",
    "The last dark vein unravels. The wolf's stone cracks and bursts into a clean glimmerstone.",
    "Marda pushes it across the desk to her without a word. Nala's inside is empty again.",
    "Nala jogs to the south green. The watch is already running laps. Maud jerks her chin: fall in.",
    "Laps. Fieldstones, hauled and stacked and hauled back. Her arms burn, and she keeps going.",
    "Staff bouts in pairs. Tam comes at her low and fast, and she reads it wrong.",
    "His staff sweeps her feet. She lands flat on her back on the cold grass. The watch laughs.",
    "Nala gets up. She bouts on with him until the watch changes, taking her knocks.",
    "When Maud calls it, Nala's legs shake under her. A blue box opens.",
    "[New skill acquired – Staff Fighting.]",
    "[Staff Fighting – At [Basic] level, guard, step aside and strike with a staff.]",
    'Maud looks her over, sweat-soaked and grass-stained. "Three days. You\'ll do," she says.',
  ],
  lore: [
    "lore/overwhere-iii-brannagh-tull",
    "lore/overwhere-iii-brannagh-tull-2",
    "lore/overwhere-iii-corruption",
    "lore/overwhere-iii-marda-hesk",
    "lore/overwhere-iii-maud-ferrow",
    "lore/overwhere-iii-mending-weave",
    "lore/overwhere-iii-nala",
    "lore/overwhere-iii-nala-2",
    "lore/overwhere-iii-the-system",
    "place/overwhere-iii-merrowgate-guild-post",
  ],
  reviewedBy: ["story-reviewer/style", "story-reviewer/continuity"],
  recordedBy: [
    "story-recorder/inventory",
    "story-recorder/memory",
    "story-recorder/mechanics",
    "story-recorder/picture",
  ],
  endsAt: "2026-10-04T10:30:00.000Z",
} as const satisfies StoryTurnPlayed
