import type { StoryTurnPlayed } from "akasha/story/world/stories/played/turns/story-turn-played.page-type.types.ts"

export const overwhereIii00008 = {
  id: "01a0f18d-09dc-706d-b098-b0e11b36b533",
  type: "page-type/story-turn-played",
  slug: "overwhere-iii-00-008",
  ownLength: 340,
  unit: "unit/words",
  partOfCollections: ["story-played/overwhere-iii"],
  position: 8,
  prose: "txt",
  characters: [
    "character-player/overwhere-iii-nala",
    "character-other/overwhere-iii-tobin-wick",
    "character-other/overwhere-iii-bet-harrow",
    "character-other/overwhere-iii-marda-hesk",
    "character-other/overwhere-iii-cal-fenn",
    "character-other/overwhere-iii-jory-fenn",
  ],
  stepStatus: "step-status/reviewers",
  action: "“Yes, thank you again.” I sleep the night and them go to the guild post in the morning.",
  beats: [
    '"Yes, thank you again," Nala says.',
    'Tobin nods, satisfied. "Keep the coat for now. I\'ll be on the square." He goes up the stair.',
    "Bet takes a candle and shows Nala up to a small cold room under the eaves.",
    "A straw tick, a wool blanket, a shuttered window and a peg on the wall; nothing else.",
    "Nala lies down under the blanket and Tobin's coat, and sleep takes her fast.",
    "She wakes to gray light at the shutter's edge and a bell ringing slow and deep over the town.",
    "Her stomach is empty again; last night's stew is a long time gone.",
    "Downstairs the common room is quiet, the hearth banked; Bet is busy and doesn't look up.",
    "Outside the air is sharp, frost on the cobbles, cold biting her bare feet on every step.",
    "Across the square, carts are coming in to set up; she doesn't see Tobin's yet.",
    "She walks back down the street to the south gate, to the squat old tollhouse just inside it.",
    "The board by its door is papered with notices, and she reads them as easily as English.",
    'Notice: "Rats in the Carrow wool store. 30 copper."',
    'Notice: "Twenty frostcap mushrooms from the Wrenwood\'s edge. 20 copper."',
    'Notice: "Guard the salt wagon to Applegarth and back. 40 copper."',
    'Notice: "A blighted boar seen by the south road. Kill it: 1 silver 50 copper."',
    'Notice: "Blight bounty: a silver a stone."',
    'In a rough hand at the bottom: "Any word of Cal Fenn, to Jory Fenn. He pays what he has."',
    "Inside is one room: a desk, a bench, a stove ticking with heat, a stair going up.",
    "A long sword hangs on the wall above the desk.",
    "Behind the desk sits a broad-shouldered woman of sixty, gray hair cropped short, a cane beside her.",
    "She looks up at Nala: the coat, the bare feet, the red hair. Her face doesn't move.",
    '"Door\'s open, so come in or don\'t," she says. "What are you after?"',
  ],
  lore: [
    "lore/overwhere-iii-bet-harrow",
    "lore/overwhere-iii-cal-fenn",
    "lore/overwhere-iii-jory-fenn",
    "lore/overwhere-iii-marda-hesk",
    "lore/overwhere-iii-nala",
    "lore/overwhere-iii-tobin-wick",
    "place/overwhere-iii-merrowgate-guild-post",
  ],
  endsAt: "2026-09-30T07:00:00.000Z",
} as const satisfies StoryTurnPlayed
