import type { StoryTurnPlayed } from "akasha/story/world/stories/played/turns/story-turn-played.page-type.types.ts"

export const overwhereIii00077 = {
  id: "01a0fed3-2e42-7022-81b2-70b3f69e0ab9",
  type: "page-type/story-turn-played",
  slug: "overwhere-iii-00-077",
  ownLength: 93,
  unit: "unit/words",
  partOfCollections: ["story-played/overwhere-iii"],
  position: 77,
  prose: "txt",
  characters: ["character-player/overwhere-iii-nala", "character-other/overwhere-iii-marda-hesk"],
  stepStatus: "step-status/recorders",
  action: "I try casting a mending weave on my palms.",
  beats: [
    "Nala turns her left palm up and draws a Mending Weave from her own well.",
    "The thread knits into the pink skin. The tightness eases, and the palm goes smooth and pale.",
    "She turns up the right palm and weaves again. This one drags, and a dull throb wakes in her temples.",
    "But it holds. The second palm smooths over like the first. Both hands are whole again.",
    "Her well is down to a quarter.",
    "Across the desk, Marda's pen has stopped.",
    '"Huh," Marda says. "Didn\'t know you could do that on yourself."',
  ],
  lore: [
    "lore/overwhere-iii-marda-hesk",
    "lore/overwhere-iii-marda-hesk-2",
    "lore/overwhere-iii-mending-weave",
    "lore/overwhere-iii-nala",
    "lore/overwhere-iii-nala-2",
    "lore/overwhere-iii-nala-2-2",
  ],
  reviewedBy: ["story-reviewer/style", "story-reviewer/continuity"],
  recordedBy: ["story-recorder/inventory", "story-recorder/memory"],
  endsAt: "2026-10-07T16:08:00.000Z",
} as const satisfies StoryTurnPlayed
