import type { StoryTurnPlayed } from "akasha/story/world/stories/played/turns/story-turn-played.page-type.types.ts"

export const overwhereIii00054 = {
  id: "01a0fd67-c171-7702-a42c-0ea9e0bee01d",
  type: "page-type/story-turn-played",
  slug: "overwhere-iii-00-054",
  cover: "image/image-e1b224249f32a40d",
  coverAfter: "The white-gold threads seep in. By late afternoon you're full to the",
  ownLength: 138,
  unit: "unit/words",
  partOfCollections: ["story-played/overwhere-iii"],
  position: 54,
  prose: "txt",
  characters: [
    "character-player/overwhere-iii-nala",
    "character-other/overwhere-iii-ivy-marsh",
    "character-other/overwhere-iii-huw-tarrant",
    "character-other/overwhere-iii-marda-hesk",
  ],
  stepStatus: "step-status/player",
  action:
    "“Thanks Ivy” I go rest at the shrine, then back to the Post. “How many blightstones left to cleanse here?”",
  beats: [
    '"Thanks, Ivy." Ivy waves her off from the rail, and Huw lifts his goad in his good right hand.',
    "Nala walks out the south gate and down to the crossroads, and sits against the shrine's warm stone.",
    "The white-gold threads seep in. By late afternoon she's full to the brim again.",
    "She walks back up to town and into the Post before the dusk bell.",
    '"How many blightstones are left to cleanse here?" she asks Marda.',
    'Marda taps the lead box with her cane. "Two whole ones, not the two you cracked."',
    "\"The stag's second stone and the wolf's second. Both still dark.\"",
    '"And the six seed stones you brought in off folk. That\'s all there is in Merrowgate."',
    '"More only come from new kills. The Thornmere wagon takes the box at the new moon, twelve days off."',
  ],
  issues: [
    '"Two whole ones. One stag, one wolf." - Nala cracked both the stag and wolf stones already',
  ],
  lore: [
    "lore/overwhere-iii-corruption",
    "lore/overwhere-iii-huw-tarrant",
    "lore/overwhere-iii-ivy-marsh",
    "lore/overwhere-iii-marda-hesk",
    "lore/overwhere-iii-nala",
    "lore/overwhere-iii-nala-2",
    "place/overwhere-iii-merrowgate-guild-post",
    "place/overwhere-iii-wrenwood-crossroads",
  ],
  reviewedBy: ["story-reviewer/style", "story-reviewer/continuity"],
  recordedBy: [
    "story-recorder/inventory",
    "story-recorder/memory",
    "story-recorder/mechanics",
    "story-recorder/picture",
  ],
  endsAt: "2026-10-04T16:50:00.000Z",
} as const satisfies StoryTurnPlayed
