import type { StoryTurnPlayed } from "akasha/story/world/stories/played/turns/story-turn-played.page-type.types.ts"

export const overwhereIii00084 = {
  id: "01a0ff5d-8f53-7f44-baca-8e53104f53ec",
  type: "page-type/story-turn-played",
  slug: "overwhere-iii-00-084",
  ownLength: 285,
  unit: "unit/words",
  partOfCollections: ["story-played/overwhere-iii"],
  position: 84,
  prose: "txt",
  characters: [
    "character-player/overwhere-iii-nala",
    "character-other/overwhere-iii-edda-crane",
    "character-other/overwhere-iii-mother-sallow",
  ],
  stepStatus: "step-status/reviewers",
  action:
    "“Corrupt wolves, I fought them off, but they hurt me bad, can you get me to the shrine? That’s my best chance to heal myself.”",
  beats: [
    '"Corrupt wolves. I fought them off, but they hurt me bad. Can you get me to the shrine?"',
    '"That\'s my best chance to heal myself."',
    'Edda looks her over, lips tight. "Can\'t carry you. Stay put." She stumps off down the brook.',
    "A quarter hour later she's back, pushing a two-wheeled charcoal barrow, black with soot.",
    "She heaves Nala into it with a grunt and a strength her size doesn't promise.",
    "At the clearing's edge Edda slows. She stares at the hut's open door and the lifted hearthstone.",
    "She says nothing, and wheels on.",
    "Down the south road, two hours of jolting ruts. The blight creeps cold up Nala's arm and calf.",
    "Her well fills a little as she lies there, a slow trickle.",
    "The crossroads shrine comes into sight. White-gold current runs thick around its warm stone.",
    "Edda tips her out against it. The warmth soaks into her back and eases the worst of the ache.",
    "Nala feeds a Mending Weave from the white-gold. It burns her palms, but her strength steadies.",
    "A second one. Then she turns the current on her own bites.",
    "Four pulls, one for each bite. Each one aches cold up her arm, and each drags out the blight.",
    "Four dark seed stones clot on the grass beside her. She's shaking by the last one.",
    "Then four Mendings to close the bites. Two drag, but all four hold. The skin knits pink and whole.",
    "She sags against the stone. Her palms are raw again, but the cold is gone from her blood.",
    "Edda has watched all of it from her barrow, arms folded.",
    '"Sallow\'s door stood open, and her hearthstone up," she says. "Where\'s she gone?"',
  ],
  lore: [
    "lore/overwhere-iii-cleansing-weave",
    "lore/overwhere-iii-current-feed",
    "lore/overwhere-iii-edda-crane",
    "lore/overwhere-iii-mother-sallow",
    "lore/overwhere-iii-nala",
    "lore/overwhere-iii-nala-2",
    "lore/overwhere-iii-nala-2-2",
  ],
  endsAt: "2026-10-08T16:35:00.000Z",
} as const satisfies StoryTurnPlayed
