import type { StoryTurnPlayed } from "akasha/story/world/stories/played/turns/story-turn-played.page-type.types.ts"

export const overwhereIii00079 = {
  id: "01a0ff04-4a58-7ed9-b3bd-2b19b8f415c7",
  type: "page-type/story-turn-played",
  slug: "overwhere-iii-00-079",
  cover: "image/image-9b19c0b9c9743c3e",
  ownLength: 282,
  unit: "unit/words",
  partOfCollections: ["story-played/overwhere-iii"],
  position: 79,
  prose: "txt",
  characters: [
    "character-player/overwhere-iii-nala",
    "character-other/overwhere-iii-marda-hesk",
    "character-other/overwhere-iii-brannagh-tull",
    "character-other/overwhere-iii-maud-ferrow",
    "character-other/overwhere-iii-tam-rowe",
    "character-other/overwhere-iii-edda-crane",
  ],
  stepStatus: "step-status/player",
  action:
    "“Okay, might just hunt my own then.” Dinner, bed, healing, training, then back to the Post for leads on where blighted beasts have been seem.",
  beats: "jsonl",
  issues: [
    '"She reaches the yard late" - Maud drills the watch on the south green, as turn 68 has it',
  ],
  lore: [
    "lore/overwhere-iii-brannagh-tull",
    "lore/overwhere-iii-brannagh-tull-2",
    "lore/overwhere-iii-corruption-2",
    "lore/overwhere-iii-edda-crane",
    "lore/overwhere-iii-marda-hesk",
    "lore/overwhere-iii-marda-hesk-2",
    "lore/overwhere-iii-maud-ferrow",
    "lore/overwhere-iii-nala",
    "lore/overwhere-iii-nala-2",
    "lore/overwhere-iii-nala-3",
    "place/overwhere-iii-merrowgate-guild-post",
    "place/overwhere-iii-wrenwood",
  ],
  reviewedBy: ["story-reviewer/continuity", "story-reviewer/style"],
  recordedBy: [
    "story-recorder/inventory",
    "story-recorder/memory",
    "story-recorder/mechanics",
    "story-recorder/picture",
  ],
  endsAt: "2026-10-08T10:45:00.000Z",
  coverAfter: "Then staff bouts with Tam. You slip his swing and rap his knuckles.",
} as const satisfies StoryTurnPlayed
