import type { StoryTurnPlayed } from "akasha/story/world/stories/played/turns/story-turn-played.page-type.types.ts"

export const overwhereIii00093 = {
  id: "01a101b8-75b7-71e1-a171-abf4f9b51df2",
  type: "page-type/story-turn-played",
  slug: "overwhere-iii-00-093",
  cover: "image/image-b6b61fe4e6377127",
  ownLength: 152,
  unit: "unit/words",
  partOfCollections: ["story-played/overwhere-iii"],
  position: 93,
  prose: "txt",
  characters: [
    "character-player/overwhere-iii-nala",
    "character-other/overwhere-iii-marda-hesk",
    "character-other/overwhere-iii-brannagh-tull",
  ],
  stepStatus: "step-status/recorders",
  action:
    "“Jackalopes.” I go out to the shrine and use ambient weaves to cleanse the five blightstones.",
  beats: [
    '"Jackalopes," Nala tells Marda.',
    'Marda writes it in the ledger: "Kiln jackalopes, three."',
    "Nala walks out the south gate and up the two miles to the shrine.",
    "White-gold current hums thick around the shrine stones as she sits beside them.",
    "She tips Brannagh's clay cup and sets the first seed stone on her palm.",
    "She draws the lent current into a Cleansing Weave; it burns her a little and costs her well nothing.",
    "The black knot splits cleanly. A glimmer speck glows where it was.",
    "The second stone is stubborn; she holds the weave a breath longer before it cracks.",
    "The third and fourth crack at a touch, one after the other.",
    "The fifth fights her, then gives, a speck rolling into her palm.",
    "Five small burns sting her hands. Her own well is untouched, and has filled a little.",
    "The clay cup is empty of seed stones.",
    "Six glimmer specks.",
  ],
  issues: [
    '"The clay cup is empty of seed stones, and six glimmer specks lie in your palm." - Leave It Open',
    '"your well stays full" - braids spent her own mana in turns 89-92; it later "has filled a little"',
  ],
  lore: [
    "lore/overwhere-iii-brannagh-tull",
    "lore/overwhere-iii-brannagh-tull-2",
    "lore/overwhere-iii-marda-hesk",
    "lore/overwhere-iii-marda-hesk-2",
    "lore/overwhere-iii-nala",
    "lore/overwhere-iii-nala-2",
    "lore/overwhere-iii-nala-2-2",
  ],
  reviewedBy: ["story-reviewer/style", "story-reviewer/continuity"],
  recordedBy: ["story-recorder/inventory", "story-recorder/memory", "story-recorder/picture"],
  endsAt: "2026-10-09T14:45:00.000Z",
  coverAfter: "Six glimmer specks.",
} as const satisfies StoryTurnPlayed
