import type { StoryTurnPlayed } from "akasha/story/world/stories/played/turns/story-turn-played.page-type.types.ts"

export const overwhereIii00015 = {
  id: "01a0f1e5-f62c-7cbe-bff3-24fe3aab4a8d",
  type: "page-type/story-turn-played",
  slug: "overwhere-iii-00-015",
  ownLength: 257,
  unit: "unit/words",
  partOfCollections: ["story-played/overwhere-iii"],
  position: 15,
  prose: "txt",
  characters: ["character-player/overwhere-iii-nala"],
  stepStatus: "step-status/recorders",
  action:
    "I go and retrieve the glimmerstone front the rabbit, then I sit and focus on the mana currents, seeing if I can manipulate ones that look like the holy mana I saw on the card and use them to stitch together the cut.",
  beats: [
    "Nala kneels by the dead rabbit and works the knife in at the base of its antlers.",
    "Out comes a small stone the size of a fingernail, faintly glowing. A glimmerstone.",
    "She wipes it clean and tucks it away with her frostcaps.",
    "Then she sits against the beech and looks hard at the currents, for white-gold like the card's.",
    "The currents here hold threads of many colors: blue, green, a dull yellow. None of them white-gold.",
    "Back along the path, where the currents cross at the shrine, something pale gleams among them.",
    "She walks back to the shrine and sits against its warm stone, and looks again.",
    "There: a few white-gold threads, running where the currents meet. Slow, and warm to her touch.",
    "She pays a little of her own mana, draws one thread out, and lays it along the bite.",
    "It won't stay. It slips loose, and she has to catch it and lay it down again, and again.",
    "It takes her the better part of half an hour of stubborn restitching before it holds.",
    "Then warmth sinks into her forearm, white-gold light under the skin.",
    "Slowly the bite knits closed, leaving a raw pink seam and no more blood.",
    "She counts: fourteen frostcaps in her shirt, four still whole under the old beech. Twenty needed.",
    "A blue box opens.",
    "[New skill acquired – Mending Weave.]",
    "[Mending Weave – At [Basic] level, stitch holy current into a wound to close it slowly.]",
  ],
  lore: ["lore/overwhere-iii-nala", "place/overwhere-iii-wrenwood-crossroads"],
  reviewedBy: ["story-reviewer/style", "story-reviewer/continuity"],
  endsAt: "2026-09-30T09:48:00.000Z",
} as const satisfies StoryTurnPlayed
