import type { StoryTurnPlayed } from "akasha/story/world/stories/played/turns/story-turn-played.page-type.types.ts"

export const overwhereIii00029 = {
  id: "01a0f380-1d91-7f00-beb6-663d12e6329b",
  type: "page-type/story-turn-played",
  slug: "overwhere-iii-00-029",
  ownLength: 219,
  unit: "unit/words",
  partOfCollections: ["story-played/overwhere-iii"],
  position: 29,
  prose: "txt",
  characters: [
    "character-player/overwhere-iii-nala",
    "character-other/overwhere-iii-brannagh-tull",
    "character-other/overwhere-iii-garrick-dole",
    "character-other/overwhere-iii-ivy-marsh",
  ],
  stepStatus: "step-status/reviewers",
  action:
    "“Okay, this works, so it’s just a matter of time” I repeat the process, sipping from the mana draught until I can try again, switching to Garrick this time.",
  beats: [
    '"Okay," Nala says. "This works. It\'s just a matter of time."',
    "She tips up the flask and sips. There's barely a swallow left, and then it's empty.",
    "A little warmth, no more. The empty place inside fills only a thin way.",
    "She crosses to the far cot. Brannagh lifts the lamp and shakes the big man there gently awake.",
    "He's about sixty, big-framed and white-bearded, gone gaunt in bed. His eyes wander a moment.",
    "The bite is on his right calf. Purple runs up past the knee.",
    "To her sight the black here sits deeper than in Ivy's hand, knotted down into the muscle.",
    'He looks at her a long moment. "Go on, then, lass."',
    "She pushes out her white-gold thread, reaches down into the calf, and pulls.",
    "The blight bites back hard. The cold rams up the thread past her elbow into her shoulder.",
    "She holds on through it, teeth set, and drags.",
    "The black comes up slow and clots at the lip into a seed-sized stone.",
    "Her arm throbs, cold to the shoulder. She's shaking a little.",
    "To her sight about a third of the black is out. The rest is still knotted in the calf.",
    "Inside, she's nearly empty again. The flask on the cot beside her is dry.",
  ],
  lore: [
    "lore/overwhere-iii-brannagh-tull",
    "lore/overwhere-iii-corruption",
    "lore/overwhere-iii-garrick-dole",
    "lore/overwhere-iii-ivy-marsh",
    "lore/overwhere-iii-nala",
    "lore/overwhere-iii-nala-2",
  ],
  endsAt: "2026-09-30T18:14:00.000Z",
} as const satisfies StoryTurnPlayed
