import type { StoryTurnPlayed } from "akasha/story/world/stories/played/turns/story-turn-played.page-type.types.ts"

export const overwhereIii00028 = {
  id: "01a0f372-fadc-76cf-aa46-a598af9af1c9",
  type: "page-type/story-turn-played",
  slug: "overwhere-iii-00-028",
  ownLength: 301,
  unit: "unit/words",
  partOfCollections: ["story-played/overwhere-iii"],
  position: 28,
  prose: "txt",
  characters: [
    "character-player/overwhere-iii-nala",
    "character-other/overwhere-iii-brannagh-tull",
    "character-other/overwhere-iii-ivy-marsh",
    "character-other/overwhere-iii-garrick-dole",
  ],
  stepStatus: "step-status/recorders",
  action:
    "“Okay, I’ll try. I open the potion and take small sips until I have mana to work with again, then go back and use my mending weave on Ivy, this time focusing on a suction mental model instead of stitching, to pull the corruption out of her.”",
  beats: [
    '"Okay," Nala says. "I\'ll try."',
    "She unstoppers the flask and sips, small sips, waiting between each.",
    "Warmth spreads out from her middle; the empty place inside her fills, slow, until it's full.",
    "Brannagh draws back the curtain. The back room is narrow, lit by one lamp, two cots.",
    "The currents in here are thin and green, drawn to the hanging herbs. No white-gold anywhere.",
    "On the near cot sits a thin, wiry woman of about forty, black hair gone gray at the temples.",
    "Her left hand is bound in a rag gone black. Purple creeps up her forearm, halfway to the elbow.",
    'She looks Nala over. "Come to take the hand off, then?"',
    "Nala unwinds the rag. Across the back of the hand, the bite weeps black.",
    "To her sight the blight sits in the wound like a dark smear, sunk deep into the flesh.",
    "She pushes out her own white-gold mana and reaches in with the mending weave.",
    "This time she doesn't think of stitching. She thinks of suction: drawing the black out.",
    "The first pull slips. Cold shoots up the thread into her arm and aches there. Nothing comes out.",
    'Ivy hisses through her teeth, then laughs. "That it?"',
    "Nala sets her jaw and pulls again, slower, holding the thread tight against the cold.",
    "This time the black comes. It draws up out of the wound in a dark thread and clots at the lip.",
    "It hardens into a black stone the size of a seed. Brannagh sucks in a breath.",
    "The cold ache is back in Nala's arm, deeper. Inside, most of what the draught gave her is spent.",
    "To her sight about half the black is gone from the wound. Half is still sunk in the flesh.",
  ],
  issues: ['"There\'s enough for one more pull, and little after." - No Prompt'],
  lore: [
    "lore/overwhere-iii-brannagh-tull",
    "lore/overwhere-iii-cleansing-weave",
    "lore/overwhere-iii-corruption",
    "lore/overwhere-iii-garrick-dole",
    "lore/overwhere-iii-ivy-marsh",
    "lore/overwhere-iii-nala",
  ],
  reviewedBy: ["story-reviewer/style", "story-reviewer/continuity"],
  recordedBy: ["story-recorder/inventory"],
  endsAt: "2026-09-30T18:04:00.000Z",
} as const satisfies StoryTurnPlayed
