import type { StoryTurnPlayed } from "akasha/story/world/stories/played/turns/story-turn-played.page-type.types.ts"

export const overwhereIii00053 = {
  id: "01a0fd5d-049b-78ef-b530-a0548e8527ab",
  type: "page-type/story-turn-played",
  slug: "overwhere-iii-00-053",
  cover: "image/image-c56e3b314535789b",
  coverAfter: "The drover sets down his goad and comes over, wiping his left",
  ownLength: 234,
  unit: "unit/words",
  partOfCollections: ["story-played/overwhere-iii"],
  position: 53,
  prose: "txt",
  characters: [
    "character-player/overwhere-iii-nala",
    "character-other/overwhere-iii-brannagh-tull",
    "character-other/overwhere-iii-ivy-marsh",
    "character-other/overwhere-iii-huw-tarrant",
  ],
  stepStatus: "step-status/player",
  action:
    "“I'll go find him, since he was first in line, don’t mind some exploring today.” I go find the drover to heal the burn.",
  beats: [
    '"I\'ll go find him," Nala tells Brannagh. "He was first in line. And I don\'t mind exploring today."',
    "She follows the lane to the east gate. The cattle pens smell of dung and wet straw.",
    "Ivy Marsh is up on the rail, hollering at a red steer. She sees Nala and grins.",
    '"Come to take the other hand off, then?" She jerks her head. "Huw! Your healer."',
    "The drover sets down his goad and comes over, wiping his left palm on his breeches.",
    "He holds out his right arm. The burn is old and ridged, and it draws his hand half shut.",
    '"Barn fire," he says. "Ten years back. Calves." That\'s all he says.',
    "Nala lays a holy thread along the scar and stitches. The ridges flatten a little, and pale.",
    "A second weave. The skin loosens. Huw's fingers twitch.",
    "A third, and the thread sings through it. The scar smooths flat and pale under her hand.",
    "Huw opens his hand. All the way. He closes it into a fist, slow, then opens it again.",
    "He picks up his goad in his right hand and grips it hard. He stares at it a long while.",
    "Ivy has gone quiet on the rail.",
    '"Huw knows the Thornmere road and every farm on it," Ivy says. "Hears all the drovers\' talk."',
    '"Whatever you want to know, ask him. He owes you, and so do I."',
  ],
  lore: [
    "lore/overwhere-iii-brannagh-tull",
    "lore/overwhere-iii-brannagh-tull-2",
    "lore/overwhere-iii-huw-tarrant",
    "lore/overwhere-iii-ivy-marsh",
    "lore/overwhere-iii-mending-weave",
    "lore/overwhere-iii-nala",
    "lore/overwhere-iii-nala-2",
    "place/overwhere-iii-merrowgate",
  ],
  reviewedBy: ["story-reviewer/style", "story-reviewer/continuity"],
  recordedBy: [
    "story-recorder/inventory",
    "story-recorder/memory",
    "story-recorder/picture",
    "story-recorder/mechanics",
  ],
  endsAt: "2026-10-04T14:10:00.000Z",
} as const satisfies StoryTurnPlayed
