import type { StoryTurnPlayed } from "akasha/story/world/stories/played/turns/story-turn-played.page-type.types.ts"

export const overwhereIii00065 = {
  id: "01a0fe2b-e5d8-7f0c-ab14-1ed093afc80f",
  type: "page-type/story-turn-played",
  slug: "overwhere-iii-00-065",
  ownLength: 205,
  unit: "unit/words",
  partOfCollections: ["story-played/overwhere-iii"],
  position: 65,
  prose: "txt",
  characters: [
    "character-player/overwhere-iii-nala",
    "character-other/overwhere-iii-oswin-fairley",
    "character-other/overwhere-iii-marda-hesk",
  ],
  stepStatus: "step-status/recorders",
  action: "“I’ll take is back to the post.”",
  beats: [
    '"I\'ll take it back to the Post," Nala says.',
    "Oswin digs out an old leather pouch and flicks the stone into it with the end of his stick.",
    "It's the size of a hazelnut. He cinches the pouch shut and hands it to her.",
    "He cuts the fox's tail, then tucks five copper and a dozen eggs in a cloth into her pack.",
    "\"The farmers' due for a tail. And you'll never pay for an egg or a bed at Fairley Farm.\"",
    "Nala walks the hour back west along the Thornmere road, the pouch held away from her side.",
    "At the Post, Marda tongs the stone out of the pouch and turns it in the light.",
    '"Fox?" Nala tells her how it went: the braid down into the sett, the lash, the leap.',
    'Marda counts out a silver onto the desk. "The stone\'s its own proof. Full bounty."',
    '"One weave\'ll crack that. Only a scrap of blight left in it." She sets it apart in the lead box.',
    "\"It's yours to crack when you've mana again. Three specks, I'd guess.\"",
    'She leans back. "You took a blighted beast yourself. You\'re past needing my leave."',
    '"Hunt small blight where you find it. Bring me the stones."',
  ],
  lore: [
    "lore/overwhere-iii-corruption-2",
    "lore/overwhere-iii-marda-hesk",
    "lore/overwhere-iii-nala",
    "lore/overwhere-iii-nala-2",
    "lore/overwhere-iii-nala-2-2",
    "lore/overwhere-iii-oswin-fairley",
    "place/overwhere-iii-fairley-farm",
    "place/overwhere-iii-merrowgate-guild-post",
  ],
  reviewedBy: ["story-reviewer/style", "story-reviewer/continuity"],
  endsAt: "2026-10-06T10:00:00.000Z",
} as const satisfies StoryTurnPlayed
