import type { StoryTurnPlayed } from "akasha/story/world/stories/played/turns/story-turn-played.page-type.types.ts"

export const otherwhereV00002 = {
  id: "01a0e9f3-9f0f-7c47-ada5-1a3b4c957f2c",
  type: "page-type/story-turn-played",
  slug: "otherwhere-v-00-002",
  cover: "image/image-a24fce681acae75e",
  ownLength: 558,
  unit: "unit/words",
  partOfCollections: ["story-played/otherwhere-v"],
  position: 2,
  prose: "txt",
  characters: ["character-player/otherwhere-v-nala"],
  stepStatus: "step-status/recorders",
  action:
    "“Okay…isekai protocol. System? Status? Davrar? Davrar…I remember that name. Nathan, have you merged with the system yet? If so, could you send me some help? I know you can and wouldn’t want me to go through what you did.”",
  beats: [
    'Nala, sitting in the moss, says in her ordinary speaking voice: "Okay… isekai protocol."',
    'She says "System?" No box comes.',
    'She says "Status?" No box comes.',
    'She says "Davrar?" No box comes; the air in front of her stays empty.',
    "She says the name Davrar again, slower, as a name she half remembers.",
    "She asks Nathan whether he has merged with the system yet.",
    "She asks him, if so, to send her help.",
    "She says he can, and would not want her to go through what he did.",
    "Nothing answers her: no voice, no box, no change in the hollow.",
    "Her voice, clear and a little hoarse, is the only human sound she can hear.",
    "The clicking in the ferns stays quiet a while after she speaks.",
    "Then the ticking starts again, one clicker and then many.",
    "Minutes pass; the golden light slants lower through the grey-scaled trunks.",
    "The air cools against her bare feet.",
    "The three rising whistled notes come again from far off, and the answer comes back.",
    "More faint green lights drift down under the canopy.",
    "A fern frond glows briefly where one of the lights brushes it.",
    "As dusk nears, blue light flashes and a new box opens, turning with her head.",
    'Its lines follow word for word; each "Box:" starts a paragraph, "Box, cont.:" continues one.',
    "Box: Davrar has recognized you, Nala.",
    "Box: You have become fully integrated into Davrar, and are ready to begin!",
    "Box: As you have no Talents, classes or skills despite being of mature age,",
    "Box, cont.: Davrar has deemed you to be at a Disadvantage.",
    "Box: Therefore, Davrar will provide more explanations than usual, and your class,",
    "Box, cont.: Talent and skill gain and progression will be accelerated until you are",
    "Box, cont.: no longer at a Disadvantage.",
    "Box: Davrar is here to help you survive and prosper. It will offer you Talents",
    "Box, cont.: and utility skills according to your innate talents and abilities,",
    "Box, cont.: and allow you to choose a class to suit your deeds.",
    "Box: Talents and utility skills can develop every 10 ranks, but require Insight to do so.",
    "Box: Each class will grant different and unique class skills according to the theme",
    "Box, cont.: of the class.",
    "Box: To unlock classes, reach level 9 and choose from the presented list.",
    "Box, cont.: Classes develop at levels 27, 81, 243 and so on. There are ways to acquire more",
    "Box, cont.: than one class; good luck discovering them!",
    "Box: To level up, overcome challenges. The more dire the challenge, the more you",
    "Box, cont.: will be rewarded.",
    "Box: Davrar hopes you will survive and prosper.",
    "The box hangs in the air in front of her.",
    "Beyond the hollow's rim, the shade between the trunks has gone blue-grey.",
    "She is barefoot, with nothing in her hands, and the brook runs away downhill from the spring.",
  ],
  issues: [
    '"Around it the dusk is coming on, and the forest is full of callers you cannot see." - Leave It Open',
    '"once granted by the gods" - What It Is',
    '"that hunts at dusk and by night" - What It Is',
    '"which Davrar counts and rewards" - What It Is',
  ],
  lore: ["lore/otherwhere-v-nala", "place/otherwhere-v-fern-hollow", "lore/otherwhere-v-gloamcat"],
  reviewedBy: ["story-reviewer/style", "story-reviewer/continuity"],
  recordedBy: ["story-recorder/mechanics", "story-recorder/picture"],
} as const satisfies StoryTurnPlayed
