import type { SetTemplate } from "@akasha/temper-equipment/set-template"

export const SETS_DATA_049: readonly SetTemplate[] = [
  {
    id: "kazpians-cruel-signet",
    name: "Kazpian's Cruel Signet",
    esoSetId: 815,
    subcategoryId: "no-type",
    valid: ["*:medium"],
    bonuses: [
      {
        count: 2,
        status: "supported",
        effects: [{ metricId: "power", effectType: "integer", effectValue: 129 }],
        description: "Adds 129 Weapon and Spell Damage",
      },
      {
        count: 3,
        status: "unsupported",
        effects: [],
        description:
          "Gain Minor Slayer at all times, increasing your damage done to Dungeon, Trial, and Arena Monsters by 5%.",
      },
      {
        count: 4,
        status: "supported",
        effects: [{ metricId: "penetration", effectType: "integer", effectValue: 1487 }],
        description: "Adds 1487 Offensive Penetration",
      },
      {
        count: 5,
        status: "unsupported",
        effects: [],
        description:
          "On dealing area direct damage, place a Sword above an enemy, up to once every 1 second. You cannot place a Sword on an enemy who already has one from you. After 6 seconds, the Sword falls, dealing 772 Physical damage. This damage scales off the higher of your Weapon or Spell Damage. \n\nApplying a Sword increases your damage done by 2% for 6 seconds, stacking up to 6 times.",
      },
    ],
    icons: {
      "axe": "/esoui/art/icons/gear_coldharbourdominator_1haxe_a.dds",
      "battleaxe": "/esoui/art/icons/gear_coldharbourdominator_2haxe_a.dds",
      "bow": "/esoui/art/icons/gear_coldharbourdominator_bow_a.dds",
      "chest:*": "/esoui/art/icons/gear_coldharbordominator_medium_chest_a.dds",
      "dagger": "/esoui/art/icons/gear_coldharbourdominator_dagger_a.dds",
      "feet:*": "/esoui/art/icons/gear_coldharbordominator_medium_feet_a.dds",
      "greatsword": "/esoui/art/icons/gear_coldharbourdominator_2hsword_a.dds",
      "hands:*": "/esoui/art/icons/gear_coldharbordominator_medium_hands_a.dds",
      "head:*": "/esoui/art/icons/gear_coldharbordominator_medium_head_a.dds",
      "ice-staff": "/esoui/art/icons/gear_coldharbourdominator_staff_a.dds",
      "inferno-staff": "/esoui/art/icons/gear_coldharbourdominator_staff_a.dds",
      "legs:*": "/esoui/art/icons/gear_coldharbordominator_medium_legs_a.dds",
      "lightning-staff": "/esoui/art/icons/gear_coldharbourdominator_staff_a.dds",
      "mace": "/esoui/art/icons/gear_coldharbourdominator_1hhammer_a.dds",
      "maul": "/esoui/art/icons/gear_coldharbourdominator_2hhammer_a.dds",
      "necklace": "/esoui/art/icons/gear_breton_neck_a.dds",
      "restoration-staff": "/esoui/art/icons/gear_coldharbourdominator_staff_a.dds",
      "ring": "/esoui/art/icons/gear_breton_ring_a.dds",
      "shield": "/esoui/art/icons/gear_coldharbourdominator_shield_a.dds",
      "shoulders:*": "/esoui/art/icons/gear_coldharbordominator_medium_shoulder_a.dds",
      "sword": "/esoui/art/icons/gear_coldharbourdominator_1hsword_a.dds",
      "waist:*": "/esoui/art/icons/gear_coldharbordominator_medium_waist_a.dds",
    },
  },
  {
    id: "kinrass-wrath",
    name: "Kinras's Wrath",
    esoSetId: 570,
    subcategoryId: "dungeon",
    valid: ["*:medium"],
    bonuses: [
      {
        count: 2,
        status: "supported",
        effects: [{ metricId: "power", effectType: "integer", effectValue: 129 }],
        description: "Adds 129 Weapon and Spell Damage",
      },
      {
        count: 3,
        status: "supported",
        effects: [{ metricId: "critical-rating", effectType: "integer", effectValue: 657 }],
        description: "Adds 657 Critical Chance",
      },
      {
        count: 4,
        status: "supported",
        effects: [{ metricId: "power", effectType: "integer", effectValue: 129 }],
        description: "Adds 129 Weapon and Spell Damage",
      },
      {
        count: 5,
        status: "unsupported",
        effects: [],
        description:
          "Dealing damage with a Light or Heavy Attack grants you a stack of Burning Heart for 5 seconds, up to 5 stacks. While you have 5 stacks, you generate an aura of wrath, granting you Major Berserk, increasing your damage done by 10%. While you have an aura of wrath, group members within 12 meters of you gain Minor Berserk, increasing their damage done by 5%.",
      },
    ],
    icons: {
      "axe": "/esoui/art/icons/gear_blackdrakevilla_1haxe_a.dds",
      "battleaxe": "/esoui/art/icons/gear_blackdrakevilla_2haxe_a.dds",
      "bow": "/esoui/art/icons/gear_blackdrakevilla_bow_a.dds",
      "chest:*": "/esoui/art/icons/gear_blackdrakevilla_med_chest_a.dds",
      "dagger": "/esoui/art/icons/gear_blackdrakevilla_dagger_a.dds",
      "feet:*": "/esoui/art/icons/gear_blackdrakevilla_med_feet_a.dds",
      "greatsword": "/esoui/art/icons/gear_blackdrakevilla_2hsword_a.dds",
      "hands:*": "/esoui/art/icons/gear_blackdrakevilla_med_hands_a.dds",
      "head:*": "/esoui/art/icons/gear_blackdrakevilla_med_head_a.dds",
      "ice-staff": "/esoui/art/icons/gear_blackdrakevilla_staff_a.dds",
      "inferno-staff": "/esoui/art/icons/gear_blackdrakevilla_staff_a.dds",
      "legs:*": "/esoui/art/icons/gear_blackdrakevilla_med_legs_a.dds",
      "lightning-staff": "/esoui/art/icons/gear_blackdrakevilla_staff_a.dds",
      "mace": "/esoui/art/icons/gear_blackdrakevilla_1hhammer_a.dds",
      "maul": "/esoui/art/icons/gear_blackdrakevilla_2hhammer_a.dds",
      "necklace": "/esoui/art/icons/gear_breton_neck_a.dds",
      "restoration-staff": "/esoui/art/icons/gear_blackdrakevilla_staff_a.dds",
      "ring": "/esoui/art/icons/gear_breton_ring_a.dds",
      "shield": "/esoui/art/icons/gear_blackdrakevilla_shield_a.dds",
      "shoulders:*": "/esoui/art/icons/gear_blackdrakevilla_med_shoulders_a.dds",
      "sword": "/esoui/art/icons/gear_blackdrakevilla_1hsword_a.dds",
      "waist:*": "/esoui/art/icons/gear_blackdrakevilla_med_waist_a.dds",
    },
  },
  {
    id: "kjalnars-nightmare",
    name: "Kjalnar's Nightmare",
    esoSetId: 479,
    subcategoryId: "monster",
    valid: ["monster"],
    bonuses: [
      {
        count: 1,
        status: "supported",
        effects: [{ metricId: "power", effectType: "integer", effectValue: 129 }],
        description: "Adds 129 Weapon and Spell Damage",
      },
      {
        count: 2,
        status: "unsupported",
        effects: [],
        description:
          "Damaging an enemy with a Light Attack puts a Bone stack on them for 5 seconds, up to once every 0.5 seconds. \n\nAt 5 stacks, an undodgeable skeletal hand attacks your enemy after 1 second, knocking them into the air and stunning them for 3 seconds, or dealing 2221 Magic damage if they cannot be stunned. Enemies then become immune to Kjalnar's Nightmare stacks for 4 seconds. The damage scales off the higher of your Weapon or Spell Damage.",
      },
    ],
    icons: {
      "head:heavy": "/esoui/art/icons/gear_undbonecolossus_head_a.dds",
      "head:light": "/esoui/art/icons/gear_undbonecolossus_head_a.dds",
      "head:medium": "/esoui/art/icons/gear_undbonecolossus_head_a.dds",
      "shoulders:heavy": "/esoui/art/icons/gear_undbonecolossus_shoulder_a.dds",
      "shoulders:light": "/esoui/art/icons/gear_undbonecolossus_shoulder_a.dds",
      "shoulders:medium": "/esoui/art/icons/gear_undbonecolossus_shoulder_a.dds",
    },
  },
  {
    id: "knight-errants-mail",
    name: "Knight-errant's Mail",
    esoSetId: 309,
    subcategoryId: "dungeon",
    valid: ["*:heavy"],
    bonuses: [
      {
        count: 2,
        status: "supported",
        effects: [{ metricId: "health-maximum", effectType: "integer", effectValue: 1206 }],
        description: "Adds 1206 Maximum Health",
      },
      {
        count: 3,
        status: "supported",
        effects: [{ metricId: "stamina-maximum", effectType: "integer", effectValue: 1096 }],
        description: "Adds 1096 Maximum Stamina",
      },
      {
        count: 4,
        status: "supported",
        effects: [{ metricId: "power", effectType: "integer", effectValue: 129 }],
        description: "Adds 129 Weapon and Spell Damage",
      },
      {
        count: 5,
        status: "unsupported",
        effects: [],
        description:
          "Adds 450 Weapon and Spell Damage to your One Hand and Shield abilities. When you use a One Hand and Shield ability, you heal for 1568 Health.",
      },
    ],
    icons: {
      "axe": "/esoui/art/icons/gear_undaunted_1haxe_c.dds",
      "battleaxe": "/esoui/art/icons/gear_undaunted_2haxe_c.dds",
      "bow": "/esoui/art/icons/gear_undaunted_bow_c.dds",
      "chest:*": "/esoui/art/icons/gear_undaunted_heavy_chest_a.dds",
      "dagger": "/esoui/art/icons/gear_undaunted_dagger_c.dds",
      "feet:*": "/esoui/art/icons/gear_undaunted_heavy_feet_a.dds",
      "greatsword": "/esoui/art/icons/gear_undaunted_2hsword_c.dds",
      "hands:*": "/esoui/art/icons/gear_undaunted_heavy_hands_a.dds",
      "head:*": "/esoui/art/icons/gear_undaunted_heavy_head_a.dds",
      "ice-staff": "/esoui/art/icons/gear_undaunted_staff_c.dds",
      "inferno-staff": "/esoui/art/icons/gear_undaunted_staff_c.dds",
      "legs:*": "/esoui/art/icons/gear_undaunted_heavy_legs_a.dds",
      "lightning-staff": "/esoui/art/icons/gear_undaunted_staff_c.dds",
      "mace": "/esoui/art/icons/gear_undaunted_1hhammer_c.dds",
      "maul": "/esoui/art/icons/gear_undaunted_2hhammer_c.dds",
      "necklace": "/esoui/art/icons/gear_breton_neck_a.dds",
      "restoration-staff": "/esoui/art/icons/gear_undaunted_staff_c.dds",
      "ring": "/esoui/art/icons/gear_breton_ring_a.dds",
      "shield": "/esoui/art/icons/gear_orc_shield_d.dds",
      "shoulders:*": "/esoui/art/icons/gear_undaunted_heavy_shoulders_a.dds",
      "sword": "/esoui/art/icons/gear_undaunted_1hsword_c.dds",
      "waist:*": "/esoui/art/icons/gear_undaunted_heavy_waist_a.dds",
    },
  },
  {
    id: "knight-slayer",
    name: "Knight Slayer",
    esoSetId: 328,
    subcategoryId: "pvp",
    valid: ["*:light"],
    bonuses: [
      {
        count: 2,
        status: "supported",
        effects: [{ metricId: "magicka-maximum", effectType: "integer", effectValue: 1096 }],
        description: "Adds 1096 Maximum Magicka",
      },
      {
        count: 3,
        status: "supported",
        effects: [{ metricId: "power", effectType: "integer", effectValue: 129 }],
        description: "Adds 129 Weapon and Spell Damage",
      },
      {
        count: 4,
        status: "supported",
        effects: [{ metricId: "health-maximum", effectType: "integer", effectValue: 1206 }],
        description: "Adds 1206 Maximum Health",
      },
      {
        count: 5,
        status: "unsupported",
        effects: [],
        description:
          "Your fully-charged Heavy Attacks deal an additional 8% of an enemy's Max Health as Oblivion Damage. This can deal a maximum of 8000 Oblivion Damage.",
      },
    ],
    icons: {
      "axe": "/esoui/art/icons/gear_ordinator_1haxe_a.dds",
      "battleaxe": "/esoui/art/icons/gear_ordinator_2haxe_a.dds",
      "bow": "/esoui/art/icons/gear_ordinator_bow_a.dds",
      "chest:*": "/esoui/art/icons/gear_ordinator_light_robe_a.dds",
      "dagger": "/esoui/art/icons/gear_ordinator_dagger_a.dds",
      "feet:*": "/esoui/art/icons/gear_ordinator_light_feet_a.dds",
      "greatsword": "/esoui/art/icons/gear_ordinator_2hsword_a.dds",
      "hands:*": "/esoui/art/icons/gear_ordinator_light_hands_a.dds",
      "head:*": "/esoui/art/icons/gear_ordinator_light_head_a.dds",
      "ice-staff": "/esoui/art/icons/gear_ordinator_staff_a.dds",
      "inferno-staff": "/esoui/art/icons/gear_ordinator_staff_a.dds",
      "legs:*": "/esoui/art/icons/gear_ordinator_light_legs_a.dds",
      "lightning-staff": "/esoui/art/icons/gear_ordinator_staff_a.dds",
      "mace": "/esoui/art/icons/gear_ordinator_1hhammer_a.dds",
      "maul": "/esoui/art/icons/gear_ordinator_2hhammer_a.dds",
      "necklace": "/esoui/art/icons/gear_breton_neck_a.dds",
      "restoration-staff": "/esoui/art/icons/gear_ordinator_staff_a.dds",
      "ring": "/esoui/art/icons/gear_breton_ring_a.dds",
      "shield": "/esoui/art/icons/gear_ordinator_shield_a.dds",
      "shoulders:*": "/esoui/art/icons/gear_ordinator_light_shoulders_a.dds",
      "sword": "/esoui/art/icons/gear_ordinator_1hsword_a.dds",
      "waist:*": "/esoui/art/icons/gear_ordinator_light_waist_a.dds",
    },
  },
  {
    id: "knightmare",
    name: "Knightmare",
    esoSetId: 35,
    subcategoryId: "dungeon",
    valid: ["*:heavy"],
    bonuses: [
      {
        count: 2,
        status: "supported",
        effects: [{ metricId: "resistance", effectType: "integer", effectValue: 743 }],
        description: "Adds 1487 Armor",
      },
      {
        count: 3,
        status: "supported",
        effects: [{ metricId: "health-maximum", effectType: "integer", effectValue: 1206 }],
        description: "Adds 1206 Maximum Health",
      },
      {
        count: 4,
        status: "supported",
        effects: [{ metricId: "resistance", effectType: "integer", effectValue: 743 }],
        description: "Adds 1487 Armor",
      },
      {
        count: 5,
        status: "supported",
        effects: [{ metricId: "health-maximum", effectType: "integer", effectValue: 1206 }],
        description: "Adds 1206 Maximum Health",
      },
      {
        count: 5,
        status: "unsupported",
        effects: [],
        description:
          "When you deal Martial melee damage, you apply Minor Maim to all enemies within 8 meters of you for 5 seconds, reducing their damage done by 5%.  This effect can occur once every 3 seconds.",
      },
    ],
    icons: {},
  },
]
