{"path":"infrastructure/container-image/dockerfiles/modules/dockerfile-builder/dockerfile-builder.module.test.ts"}
{"path":"infrastructure/container-image/dockerfiles/modules/dockerfile-nextjs/dockerfile-nextjs.module.code.ts"}
