import type { PageType } from "akasha/pages/types/page-type.page-type.types.ts"

export const command = {
  id: "01a04bdd-596d-7b81-9204-1a882f474a5f",
  type: "page-type",
  slug: "command",
  definition: "a module reached by name from the command line",
  pluralSlug: "commands",
  parts: [
    "command/audit",
    "namespace/icloud",
    "command/read",
    "namespace/git",
    "record-property/taking",
    "namespace/imessage",
    "namespace/measure",
    "namespace/seat",
    "namespace/track",
    "namespace/email",
    "namespace/music",
    "namespace/inference",
    "namespace/mobile",
    "namespace/talos",
    "namespace/page",
    "namespace/browser",
    "namespace/sms",
    "namespace/claude-account",
    "namespace/domain",
    "namespace/model",
    "namespace/temper",
    "module/cli",
    "module/change-preparing",
    "module/audit-answering",
    "module/landing-saying",
    "module/restating",
    "module/folder-clearing",
    "module/orphaning",
    "module/change-freshness",
    "module/commit-author",
    "module/yaml-lines",
    "module/change-costing",
    "module/apply-running",
    "module/change-running",
    "module/argument-reading",
    "module/change-acting",
    "module/said-pathing",
    "module/command-flags",
    "module/file-arguing",
    "module/inventory-trace-saying",
    "module/report-answering",
    "module/mechanical-filing",
    "module/command-stopping",
    "module/prose-routing",
    "module/landing-reading",
    "module/command-walking",
    "module/command-leveling",
    "module/warrant-owing",
    "module/namespace-listing",
    "module/value-minting",
    "module/change-kind-running",
    "module/gate-building",
    "module/path-moving",
    "module/edits-landing",
    "module/seat-act-calling",
    "module/parse-args",
    "module/answer-bytes",
    "module/piping",
    "module/command-filling",
    "module/body-reaching",
    "module/refusing",
    "module/applying",
    "module/landing",
    "module/draft-keeping",
    "module/landing-finishing",
    "module/ignored-pathing",
    "module/landing-change-composing",
    "module/command-declaring",
    "module/command-answering",
    "module/calling",
    "module/fault-saying",
    "module/rooting",
    "performance/landing-throughput",
    "namespace/change",
    "namespace/refresh",
    "number-property/timeout",
    "page-type/namespace",
    "namespace/agent",
    "namespace/initiative",
    "namespace/alan",
    "namespace/infrastructure",

    "namespace/index",
    "module/complexity-rowing",
    "module/calendar-eventing",
    "namespace/google",
    "command/deploy",
    "module/folder-linking",
    "module/change-ceiling",
    "module/install-linking",
    "module/unit-landing",
    "module/command-failing",
    "module/argument-narrowing",
    "module/payload",
    "text-property/level-name",
    "module/help-writing",
    "page-type/argument",
    "record-property/command-arguments",
    "select-property/said-as",
    "relation-property/not-with",
    "module/beside-sweeping",
    "module/long-body",
    "boolean-property/repeats",
  ],
  extends: ["page-type/module"],
  loadedBy: "module/calling",
  properties: [
    { pageProperty: "record-property/taking", required: false, many: true, maxCount: null },
    { pageProperty: "number-property/timeout", required: false, many: false },
    { pageProperty: "text-property/level-name", required: false, many: false },
    {
      pageProperty: "record-property/command-arguments",
      required: false,
      many: true,
      maxCount: null,
    },
  ],
  invariants: [
    {
      invariantKind: "departure",
      statement:
        "A command's page states the command's arguments and the notes worth knowing about the taking.",
    },
    {
      invariantKind: "departure",
      statement: "A command under no namespace is one Alan approved at the root by name.",
    },
    {
      invariantKind: "departure",
      statement: "One command puts a thing up, and that command is `akasha deploy`.",
    },
    {
      invariantKind: "departure",
      statement:
        "A path a command is named is read against the repository root rather than the calling folder.",
    },
    {
      invariantKind: "departure",
      statement: "A command cannot see a substitution the shell made in its arguments.",
    },
    {
      invariantKind: "departure",
      statement: "The arguments a command takes are carried here as data rather than as prose.",
    },
    {
      invariantKind: "absence",
      statement:
        "A command's code spells no name of its own call, which the call it is handed carries.",
    },
    {
      invariantKind: "gap",
      statement: "A command's code reads this page rather than declaring the shape again.",
    },
    {
      invariantKind: "upkeep",
      statement: "Every property this page type declares is read by code.",
    },
  ],
  directives: [
    {
      directiveKind: "principle",
      name: "Repeating Problem",
      act: "Write a command only where the problem repeats, and solve it in a repeatable way.",
      warrant:
        "Writing the command costs more than doing the job by hand; everything it saves is in later runs.",
      aids: [
        "A job anyone has done by hand twice repeats.",
        "A run that needs you to decide is not repeatable.",
      ],
    },
  ],
  types: "ts",
} as const satisfies PageType
