export const UNKNOWN_POI_05 = {
  [1160]: {
    [1]: ["Solitude", 7],
    [2]: ["Morthal", 32],
    [3]: ["Karthwatch", 32],
    [4]: ["Dragon Bridge", 32],
    [5]: ["Kilkreath Temple", 10],
    [6]: ["Mor Khazgur", 24],
    [7]: ["The Silver Cormorant", 43],
    [8]: ["Frozen Coast", 3],
    [9]: ["Shadowgreen", 3],
    [10]: ["Chillwind Depths", 3],
    [11]: ["Dragonhome", 3],
    [12]: ["Labyrinthian", 13],
    [13]: ["Karthald Great Lift", 42],
    [15]: ["Hjaalmarch Great Lift", 42],
    [16]: ["Eastern Great Lift", 42],
    [17]: ["Kilkreath Temple Wayshrine", 1],
    [18]: ["Morthal Wayshrine", 1],
    [19]: ["Mor Khazgur Wayshrine", 1],
    [20]: ["Dragon Bridge Wayshrine", 1],
    [21]: ["Southern Watch Wayshrine", 1],
    [22]: ["Frozen Coast Wayshrine", 1],
    [23]: ["Solitude Wayshrine", 1],
    [24]: ["Hordrek's Hunting Grounds", 18],
    [26]: ["Circle of Champions", 18],
    [27]: ["Ysmgar's Beach", 18],
    [28]: ["Shademother's Haven", 18],
    [29]: ["Old Karth Ritual Site", 26],
    [30]: ["Black Morass Ritual Site", 26],
    [31]: ["Giant's Coast Ritual Site", 26],
    [32]: ["Chilblain Peak Ritual Site", 26],
    [33]: ["Hailstone Valley Ritual Site", 26],
    [34]: ["Northern Watch Ritual Site", 26],
    [35]: ["Coastal Giant Camp", 4],
    [36]: ["Karthald Giant Camp", 4],
    [37]: ["Kilkreath Giant Camp", 4],
    [38]: ["Highland Giant Camp", 4],
    [40]: ["Solitude Docks Wayshrine", 1],
    [42]: ["Deepwood Vale Wayshrine", 1],
    [43]: ["Deepwood Giant Camp", 4],
    [48]: ["Hunter's House", 8, [161234, 5]],
    [49]: ["Dragon's Belly", 8, [161608, 7]],
    [50]: ["Lendoran Ruin", 2],
    [51]: ["Storm-Hawk's Altar", 2],
    [52]: ["Sword's Point Watchtower", 2],
    [53]: ["Wolf's Eye Lighthouse", 2],
    [54]: ["Mor Khazgur Giant Camp", 4],
    [58]: ["Giant's Coast Wayshrine", 1],
    [59]: ["Northern Watch Wayshrine", 1],
  },
  [1161]: {
    [1]: ["Dusktown", 32],
    [2]: ["Greymoor Keep", 15],
    [3]: ["The Lightless Hollow", 5],
    [4]: ["Dusktown Wayshrine", 1],
    [5]: ["Greymoor Keep Wayshrine", 1],
    [6]: ["Lightless Hollow Wayshrine", 1],
    [7]: ["Dark Moon Grotto Wayshrine", 1],
    [8]: ["Dark Moon Grotto", 5],
    [9]: ["Lightless Hollow Great Lift", 42],
    [10]: ["Dark Moon Grotto Great Lift", 42],
    [12]: ["Greymoor Cavern Great Lift", 42],
    [13]: ["Midnight Barrow", 3],
    [14]: ["The Scraps", 3],
    [15]: ["Vampire Feeding Grounds", 18],
    [16]: ["Colossus Charging Station", 18],
    [17]: ["Nchuthnkarst", 13],
    [18]: ["Gloomforest Ritual Site", 26],
    [19]: ["Dwarf's Bane Ritual Site", 26],
    [20]: ["Miner's Lament Ritual Site", 26],
    [21]: ["Nightstone Ritual Site", 26],
    [22]: ["Parasite's Cave", 8, [163070, 3]],
    [23]: ["Dwarven Run Wayshrine", 1],
    [24]: ["Grotto Falls Wayshrine", 1],
    [25]: ["Deep Overlook Wayshrine", 1],
    [26]: ["Western Greymoor Wayshrine", 1],
    [27]: ["Darkrise Overlook", 2],
    [28]: ["Gloomstalker Village", 2],
  },
  [1207]: {
    [1]: ["Markarth", 7],
    [2]: ["Karthwasten", 32],
    [3]: ["Briar Rock Ruins", 3],
    [4]: ["Druadach Redoubt", 8, [168386, 6]],
    [6]: ["Arkthzand Great Lift", 42],
    [7]: ["Four Skull Lookout", 18],
    [8]: ["Ragnvald Ritual Site", 26],
    [9]: ["Witchborne Ritual Site", 26],
    [10]: ["Deep Folk Crossing", 2],
    [11]: ["Rebel's Retreat", 2],
    [12]: ["Nalzthdbar Great Lift", 42],
    [13]: ["Harrowed Haunt Ritual Site", 26],
    [14]: ["Reachwind Ritual Site", 26],
    [15]: ["Understone Keep", 15],
    [16]: ["Bthardamz", 2],
    [17]: ["Red Eagle Redoubt", 8, [168012, 3]],
    [18]: ["Reachwind Depths", 14],
    [20]: ["Wildspear Clan Camp", 4],
    [21]: ["Valthume", 6],
    [22]: ["Lost Valley Redoubt", 28],
    [23]: ["Gloomreach", 3],
    [24]: ["Cinder-Heart Clan Camp", 4],
    [25]: ["North Markarth Wayshrine", 1],
    [26]: ["Karthwasten Wayshrine", 1],
    [27]: ["Briar Rock Wayshrine", 1],
    [28]: ["Rebel's Retreat Wayshrine", 1],
    [29]: ["Lost Valley Wayshrine", 1],
    [30]: ["Shadefeather Clan Camp", 4],
    [31]: ["Black-Moon Clan Camp", 4],
    [32]: ["Hroldan Ring", 2],
    [33]: ["Druadach Mountains Wayshrine", 1],
    [34]: ["Markarth Wayshrine", 1],
  },
  [1208]: [
    ["Nchuand-Zel", 14],
    ["Library of Arkthzand", 15],
    ["Bthar-Zel", 14],
    ["Sentinel Point", 18],
    ["Nighthollow Keep", 9],
    ["Gloomreach", 3],
    ["Nalzthdbar Great Lift", 42],
    ["Arkthzand Great Lift", 42],
    ["Arkthzand Wayshrine", 1],
    ["Nighthollow Wayshrine", 1],
    ["Philosopher's Cradle", 8, [168760, 9]],
    ["Ghostlight Grotto", 2],
    ["Mistgloom Thicket", 2],
  ],
  [1261]: {
    [1]: ["Borderwatch", 31],
    [2]: ["White Stallion Inn", 2],
    [3]: ["Undertow Cavern", 3],
    [4]: ["Leyawiin", 7],
    [6]: ["Plateau of the Traveler", 2],
    [7]: ["Tidewater Cave", 5],
    [8]: ["Deepscorn Hollow", 5],
    [9]: ["Shardius's Excavation", 18],
    [10]: ["Fort Blueblood", 2],
    [12]: ["Veyond", 11],
    [14]: ["Fort Redmane", 31],
    [15]: ["Doomvault Vulpinaz", 10],
    [16]: ["Toad-Tongue War Camp", 18],
    [17]: ["Arpenia", 3],
    [18]: ["Shrine to Nocturnal", 2],
    [19]: ["Zenithar's Abbey", 13],
    [20]: ["Sul-Xan Ritual Site", 18],
    [21]: ["Welke", 11],
    [22]: ["Bloodrun Cave", 3],
    [23]: ["Bloodrun Wayshrine", 1],
    [24]: ["Farmer's Nook", 32],
    [25]: ["Old Deathwart's Pond", 18],
    [26]: ["Salvitto Estate", 2],
    [28]: ["Hutan-Tzel", 32],
    [29]: ["Doomvault Porcixid", 3],
    [31]: ["Gideon", 7],
    [32]: ["The Silent Halls", 13],
    [33]: ["Glenbridge", 28],
    [34]: ["Vunalk", 3],
    [35]: ["Xeemhok's Lagoon", 18],
    [39]: ["Ojel-Bak", 2],
    [40]: ["Stonewastes", 32],
    [41]: ["The Shattered Xanmeer", 18],
    [42]: ["Xi-Tsei", 3],
    [43]: ["Leyawiin Wayshrine", 1],
    [44]: ["Gideon Wayshrine", 1],
    [45]: ["Borderwatch Wayshrine", 1],
    [46]: ["Fort Redmane Wayshrine", 1],
    [47]: ["Blueblood Wayshrine", 1],
    [48]: ["Stonewastes Wayshrine", 1],
    [50]: ["Pentric Run", 8, [173216, 5]],
    [51]: ["Sariellen's Sword", 8, [172842, 7]],
    [52]: ["Withered Root", 8, [172468, 3]],
    [68]: ["Ayleid Well", 11],
    [69]: ["Ayleid Well", 11],
    [70]: ["Ayleid Well", 11],
    [71]: ["Ayleid Well", 11],
    [72]: ["Ayleid Well", 11],
    [73]: ["Doomvault Vulpinaz Wayshrine", 1],
    [74]: ["Blackwood Crossroads Wayshrine", 1],
    [75]: ["Hutan-Tzel Wayshrine", 1],
    [76]: ["Vunalk Wayshrine", 1],
  },
  [1282]: {
    [2]: ["Fargrave Outskirts Wayshrine", 1],
    [5]: ["Fargrave Wayshrine", 1],
  },
  [1283]: [
    ["Forgotten Feretory", 8, [179567, 5]],
    ["Skein Row", 2],
    ["The Bathhouse", 28],
    ["The Shambles Wayshrine", 1],
  ],
  [1286]: {
    [1]: ["Raging Coast Wayshrine", 1],
    [2]: ["The Blood Pit Wayshrine", 1],
    [3]: ["Ardent Hope Wayshrine", 1],
    [4]: ["Wretched Spire Wayshrine", 1],
    [5]: ["False Martyrs' Folly Wayshrine", 1],
    [6]: ["Annihilarch's Summit Wayshrine", 1],
    [7]: ["The Blood Pit", 29],
    [8]: ["Burning Gyre Keep", 31],
    [9]: ["Ardent Hope", 17],
    [11]: ["The Brandfire Reformatory", 3],
    [12]: ["Destruction's Solace", 9],
    [13]: ["The Abomination Cradle", 18],
    [14]: ["Annihilarch's Summit", 5],
    [15]: ["False Martyrs' Folly", 3],
    [16]: ["Wretched Spire", 32],
    [17]: ["Portal to Fargrave", 26],
    [18]: ["Portal to Fargrave", 26],
    [19]: ["Stormwright's Cleft", 8, [178819, 3]],
    [20]: ["The Razorworks", 8, [179193, 7]],
    [22]: ["The Tempest Engine", 2],
    [23]: ["Traitor's Ascent", 2],
    [24]: ["Charnel Pulpit", 2],
    [25]: ["Chantry of the Moon Reiver", 2],
    [26]: ["Ravaged Crossing", 2],
    [27]: ["Zynoahz's Gaol", 10],
    [28]: ["Jynd's Foundry", 10],
    [29]: ["Wounded Crossing Wayshrine", 1],
    [30]: ["The Scourshales Wayshrine", 1],
    [31]: ["Den of the Unmaker", 18],
  },
  [1318]: {
    [1]: ["Gonfalon Bay", 32],
    [2]: ["Castle Navire", 31],
    [3]: ["Steadfast Manor", 31],
    [4]: ["Stonelore Grove", 21],
    [5]: ["Garick's Rest", 31],
    [6]: ["All Flags Islet", 31],
    [7]: ["Tor Draioch", 31],
    [8]: ["Amenos Station", 31],
    [9]: ["Brokerock Mine", 31],
    [10]: ["Skulltooth Coast", 12],
    [11]: ["Spire of the Crimson Coin", 13],
    [12]: ["Ghost Haven Bay", 13],
    [13]: ["Breakwater Cave", 3],
    [14]: ["The Firepot", 3],
    [15]: ["Death's Valor Keep", 3],
    [16]: ["Shipwreck Shoals", 3],
    [17]: ["Whalefall", 3],
    [18]: ["Coral Cliffs", 3],
    [19]: ["Y'ffre's Cauldron", 18],
    [20]: ["Serpent Bog", 18],
    [21]: ["Faun Falls", 18],
    [22]: ["Dark Stone Hollow", 18],
    [23]: ["Amenos Basin", 18],
    [24]: ["Mornard Falls", 18],
    [26]: ["Coral Road  Wayshrine", 1],
    [27]: ["Tor Draioch Wayshrine", 1],
    [28]: ["Steadfast Manor Wayshrine", 1],
    [29]: ["Castle Navire Wayshrine", 1],
    [30]: ["Garick's Rest Wayshrine", 1],
    [31]: ["Stonelore Grove Wayshrine", 1],
    [32]: ["Dufort Shipyards Wayshrine", 1],
    [33]: ["Amenos Station Wayshrine", 1],
    [34]: ["Brokerock Wayshrine", 1],
    [36]: ["Stonelore Forge and Craft", 8, [185164, 5]],
    [37]: ["Steadfast Hammer and Saw", 8, [184784, 3]],
    [38]: ["Hidden Foundry", 8, [185544, 7]],
    [39]: ["All Flags Wayshrine", 1],
    [41]: ["Volcanic Vent", 26],
    [42]: ["Volcanic Vent", 26],
    [43]: ["Volcanic Vent", 26],
    [44]: ["Volcanic Vent", 26],
    [45]: ["Volcanic Vent", 26],
    [46]: ["Volcanic Vent", 26],
    [47]: ["Volcanic Vent", 26],
    [48]: ["Trappers Peak Wayshrine", 1],
    [49]: ["Spriggan's Crown", 2],
    [50]: ["Port Navire", 12],
    [52]: ["Druid's Gate", 28],
    [53]: ["Gonfalon Head Lighthouse", 23],
    [54]: ["Westbay Wayshrine", 1],
    [56]: ["Abhain Chapel", 9],
    [61]: ["Augury Monoliths", 2],
    [63]: ["Jheury's Cove", 12],
    [66]: ["Dufort Shipyards", 12],
    [68]: ["Gonfalon Square Wayshrine", 1],
    [72]: ["Serpents Hollow Wayshrine", 1],
    [73]: ["Flooded Coast Wayshrine", 1],
    [78]: ["Green Serpent Getaway", 2],
    [79]: ["Banished Refuge", 2],
    [80]: ["Albatross Leap", 2],
    [81]: ["Colossus View Lighthouse", 23],
    [82]: ["Gonfalon Bay", 32],
    [83]: ["Gonfalon Bay", 32],
    [84]: ["Stonelore Falls", 2],
  },
  [1383]: {
    [1]: ["Vastyr", 32],
    [2]: ["Y'ffre's Path", 31],
    [3]: ["Llanshara", 21],
    [4]: ["Embervine", 3],
    [5]: ["Fauns' Thicket", 3],
    [6]: ["Valley of the Watcher", 18],
    [7]: ["Grove of the Chimera", 18],
    [8]: ["Old Port Mornard", 8, [191625, 3]],
    [9]: ["Fort Avrippe", 8, [191245, 3]],
    [10]: ["Oaken Forge", 8, [192005, 3]],
    [11]: ["Vastyr Outskirts Volcanic Vent", 26],
    [12]: ["Farpoint Volcanic Vent", 26],
    [13]: ["Llanshara Volcanic Vent", 26],
    [14]: ["Telling Stone Volcanic Vent", 26],
    [15]: ["Eastern Shores Volcanic Vent", 26],
    [16]: ["Windwrack Fort", 2],
    [17]: ["Tuinh", 32],
    [18]: ["Suncleft Grotto", 5],
    [19]: ["Castle Tonnere", 2],
    [20]: ["Glimmertarn", 2],
    [21]: ["Clohaigh", 2],
    [22]: ["Westport", 12],
    [23]: ["Ivyhame", 2],
    [25]: ["The Telling Stone", 2],
    [26]: ["Vastyr Outskirts Wayshrine", 1],
    [27]: ["Glimmertarn Wayshrine", 1],
    [28]: ["Embervine Wayshrine", 1],
    [29]: ["Llanshara Wayshrine", 1],
    [30]: ["Y'free's Path Wayshrine", 1],
    [31]: ["Vastyr Wayshrine", 1],
    [32]: ["Eastern Shores Wayshrine", 1],
  },
}
