import type { WorkspacePackage } from "./workspace-package/workspace-package.page-type.ts"

export const codeSystem = {
  id: "01a04a26-9105-7002-aa57-d2c5a03907ce",
  pageTypeSlug: "workspace-package",
  slug: "code-system",
  definition: "how we write what runs",
  manifest: "json",
  partSlugs: [
    "page-type/module",
    "page-type/eso-addon",
    "page-type/eso-interface",
    "page-type/ios-app",
    "page-type/ios-component",
    "page-type/ios-harness",
    "page-type/ios-program",
    "page-type/lua-module",
    "page-type/rust-crate",
    "page-type/rust-module",
    "page-type/shell-script",
    "page-type/stylesheet",
    "page-type/workspace-package",
    "module/body-text",
    "module/code-specifier",
    "module/code-rule",
    "module/code-source",
    "module/code-typing",
    "module/code-tests",
    "module/code-format",
    "module/code-lint",
    "module/package-manifest",
    "module/shape-progress",
  ],
} as const satisfies WorkspacePackage
