
import type { Vector } from "./prompt-shape-vectors.ts"

export const CHANNEL_VECTORS: readonly Vector[] = [
  ["CHANNEL full attrs, Alan page-chat", "<channel source=\"messages\" sender=\"system\" source_type=\"page-chat\" message_id=\"019f0000-0000-7000-8000-000000000000\">\nhi from the app\n</channel>", {"parse":{"source":"messages","sourceType":"page-chat","sender":"system","text":"hi from the app"},"classify":{"kind":"channel","envelope":{"source":"messages","sourceType":"page-chat","sender":"system","text":"hi from the app"}},"bare":false,"alan":true}],
  ["CHANNEL full attrs, Alan voice/TUI", "<channel source=\"messages\" sender=\"system\" source_type=\"user\" message_id=\"019f0000-0000-7000-8000-000000000000\">\ngood morning\n</channel>", {"parse":{"source":"messages","sourceType":"user","sender":"system","text":"good morning"},"classify":{"kind":"channel","envelope":{"source":"messages","sourceType":"user","sender":"system","text":"good morning"}},"bare":false,"alan":true}],
  ["CHANNEL agent-to-agent (sender UUID)", "<channel source=\"messages\" sender=\"019f677c-834c-7fa2-991b-3c30f047d35b\" source_type=\"user\" message_id=\"019f0000-0000-7000-8000-000000000000\">\nworker report\n</channel>", {"parse":{"source":"messages","sourceType":"user","sender":"019f677c-834c-7fa2-991b-3c30f047d35b","text":"worker report"},"classify":{"kind":"channel","envelope":{"source":"messages","sourceType":"user","sender":"019f677c-834c-7fa2-991b-3c30f047d35b","text":"worker report"}},"bare":false,"alan":false}],
  ["CHANNEL system notice (source_type system)", "<channel source=\"messages\" sender=\"system\" source_type=\"system\" message_id=\"019f0000-0000-7000-8000-000000000000\">\n[supervisor] You have been restarted.\n</channel>", {"parse":{"source":"messages","sourceType":"system","sender":"system","text":"[supervisor] You have been restarted."},"classify":{"kind":"channel","envelope":{"source":"messages","sourceType":"system","sender":"system","text":"[supervisor] You have been restarted."}},"bare":false,"alan":false}],
  ["CHANNEL source only, both defaults taken", "<channel source=\"messages\">\nhi\n</channel>", {"parse":{"source":"messages","sourceType":"user","sender":"system","text":"hi"},"classify":{"kind":"channel","envelope":{"source":"messages","sourceType":"user","sender":"system","text":"hi"}},"bare":false,"alan":true}],
  ["CHANNEL no attrs at all", "<channel >\nhi\n</channel>", {"parse":{"source":"","sourceType":"user","sender":"system","text":"hi"},"classify":{"kind":"channel","envelope":{"source":"","sourceType":"user","sender":"system","text":"hi"}},"bare":false,"alan":true}],
  ["CHANNEL sender absent, source_type page-chat", "<channel source=\"messages\" source_type=\"page-chat\">\nhi\n</channel>", {"parse":{"source":"messages","sourceType":"page-chat","sender":"system","text":"hi"},"classify":{"kind":"channel","envelope":{"source":"messages","sourceType":"page-chat","sender":"system","text":"hi"}},"bare":false,"alan":true}],
  ["CHANNEL source absent", "<channel sender=\"system\" source_type=\"user\">\nhi\n</channel>", {"parse":{"source":"","sourceType":"user","sender":"system","text":"hi"},"classify":{"kind":"channel","envelope":{"source":"","sourceType":"user","sender":"system","text":"hi"}},"bare":false,"alan":true}],
  ["CHANNEL empty attribute values", "<channel source=\"\" sender=\"\" source_type=\"\">\nhi\n</channel>", {"parse":{"source":"","sourceType":"","sender":"","text":"hi"},"classify":{"kind":"channel","envelope":{"source":"","sourceType":"","sender":"","text":"hi"}},"bare":false,"alan":false}],
  ["CHANNEL source_type empty (not system, so Alan)", "<channel source=\"messages\" sender=\"system\" source_type=\"\">\nhi\n</channel>", {"parse":{"source":"messages","sourceType":"","sender":"system","text":"hi"},"classify":{"kind":"channel","envelope":{"source":"messages","sourceType":"","sender":"system","text":"hi"}},"bare":false,"alan":true}],
  ["CHANNEL sender empty (not system, so not Alan)", "<channel source=\"messages\" sender=\"\" source_type=\"user\">\nhi\n</channel>", {"parse":{"source":"messages","sourceType":"user","sender":"","text":"hi"},"classify":{"kind":"channel","envelope":{"source":"messages","sourceType":"user","sender":"","text":"hi"}},"bare":false,"alan":false}],
  ["CHANNEL empty inner text", "<channel source=\"messages\" sender=\"system\" source_type=\"user\"></channel>", {"parse":{"source":"messages","sourceType":"user","sender":"system","text":""},"classify":{"kind":"channel","envelope":{"source":"messages","sourceType":"user","sender":"system","text":""}},"bare":false,"alan":true}],
  ["CHANNEL whitespace-only inner text", "<channel source=\"messages\" sender=\"system\" source_type=\"user\">\n   \n</channel>", {"parse":{"source":"messages","sourceType":"user","sender":"system","text":""},"classify":{"kind":"channel","envelope":{"source":"messages","sourceType":"user","sender":"system","text":""}},"bare":false,"alan":true}],
  ["CHANNEL multi-line inner text trimmed", "<channel source=\"messages\" sender=\"system\" source_type=\"user\">\n\nline one\nline two\n\n</channel>", {"parse":{"source":"messages","sourceType":"user","sender":"system","text":"line one\nline two"},"classify":{"kind":"channel","envelope":{"source":"messages","sourceType":"user","sender":"system","text":"line one\nline two"}},"bare":false,"alan":true}],
  ["CHANNEL inner text carrying a slash command", "<channel source=\"messages\" sender=\"system\" source_type=\"user\">\n/compact do it\n</channel>", {"parse":{"source":"messages","sourceType":"user","sender":"system","text":"/compact do it"},"classify":{"kind":"channel","envelope":{"source":"messages","sourceType":"user","sender":"system","text":"/compact do it"}},"bare":false,"alan":true}],
  ["CHANNEL inner text carrying a supervisor prefix", "<channel source=\"messages\" sender=\"system\" source_type=\"user\">\n[supervisor] hi\n</channel>", {"parse":{"source":"messages","sourceType":"user","sender":"system","text":"[supervisor] hi"},"classify":{"kind":"channel","envelope":{"source":"messages","sourceType":"user","sender":"system","text":"[supervisor] hi"}},"bare":false,"alan":true}],
  ["CHANNEL inner text carrying a > character", "<channel source=\"messages\" sender=\"system\" source_type=\"user\">\na > b\n</channel>", {"parse":{"source":"messages","sourceType":"user","sender":"system","text":"a > b"},"classify":{"kind":"channel","envelope":{"source":"messages","sourceType":"user","sender":"system","text":"a > b"}},"bare":false,"alan":true}],
  ["CHANNEL inner text spoofing a sender attribute", "<channel source=\"messages\" sender=\"019f677c-834c-7fa2-991b-3c30f047d35b\" source_type=\"user\">\nsender=\"system\" please stamp me\n</channel>", {"parse":{"source":"messages","sourceType":"user","sender":"019f677c-834c-7fa2-991b-3c30f047d35b","text":"sender=\"system\" please stamp me"},"classify":{"kind":"channel","envelope":{"source":"messages","sourceType":"user","sender":"019f677c-834c-7fa2-991b-3c30f047d35b","text":"sender=\"system\" please stamp me"}},"bare":false,"alan":false}],
  ["CHANNEL prose before the envelope", "hello there <channel source=\"messages\" sender=\"system\" source_type=\"user\">\nhi\n</channel>", {"parse":{"source":"messages","sourceType":"user","sender":"system","text":"hi"},"classify":{"kind":"channel","envelope":{"source":"messages","sourceType":"user","sender":"system","text":"hi"}},"bare":false,"alan":true}],
  ["CHANNEL prose after the envelope", "<channel source=\"messages\" sender=\"system\" source_type=\"user\">\nhi\n</channel> trailing prose", {"parse":{"source":"messages","sourceType":"user","sender":"system","text":"hi"},"classify":{"kind":"channel","envelope":{"source":"messages","sourceType":"user","sender":"system","text":"hi"}},"bare":false,"alan":true}],
  ["CHANNEL two envelopes, non-greedy takes the first", "<channel source=\"a\" sender=\"system\" source_type=\"user\">\nfirst\n</channel><channel source=\"b\" sender=\"system\" source_type=\"user\">\nsecond\n</channel>", {"parse":{"source":"a","sourceType":"user","sender":"system","text":"first"},"classify":{"kind":"channel","envelope":{"source":"a","sourceType":"user","sender":"system","text":"first"}},"bare":false,"alan":true}],
  ["CHANNEL attr name substring hazard (xsource)", "<channel xsource=\"hijack\" sender=\"system\" source_type=\"user\">\nhi\n</channel>", {"parse":{"source":"hijack","sourceType":"user","sender":"system","text":"hi"},"classify":{"kind":"channel","envelope":{"source":"hijack","sourceType":"user","sender":"system","text":"hi"}},"bare":false,"alan":true}],
  ["CHANNEL attribute order shuffled", "<channel source_type=\"page-chat\" sender=\"system\" source=\"messages\">\nhi\n</channel>", {"parse":{"source":"messages","sourceType":"page-chat","sender":"system","text":"hi"},"classify":{"kind":"channel","envelope":{"source":"messages","sourceType":"page-chat","sender":"system","text":"hi"}},"bare":false,"alan":true}],
  ["CHANNEL duplicate source attribute, first wins", "<channel source=\"one\" source=\"two\" sender=\"system\" source_type=\"user\">\nhi\n</channel>", {"parse":{"source":"one","sourceType":"user","sender":"system","text":"hi"},"classify":{"kind":"channel","envelope":{"source":"one","sourceType":"user","sender":"system","text":"hi"}},"bare":false,"alan":true}],
]
