apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-creds
    namespace: cloudflared
    labels:
        app.kubernetes.io/name: cloudflared
        app.kubernetes.io/instance: infra
        app.kubernetes.io/component: tunnel
        app.kubernetes.io/part-of: infra
        app.kubernetes.io/managed-by: deploy-script
type: Opaque
stringData:
    credentials.json: ENC[AES256_GCM,data:rTatFsFVeNcIOkqYvd62mcSBQYR3Zvxchk1K7RTO9JR/lHejTSUOi7PK2epVehdROCgpnhZnJp56SjS2QQmHm5X1umDj7bz9SgdGXTSAYAyBV5O9y0OPBWC43GKQuBrJBA65ES/nY9XS3g1ur535lDtzavOlVKqK6LBP815yBkbFtbr+RuNxR+Sb0K2o4poOsVuptnx2sKB2ztFqGqamGxNoa93ivcYzdI1akKlKvw==,iv:iX7yW/r3OwPbM7v0GTcbVP5hBePjL+QJ7dafWMJbmoY=,tag:7Q/xU0tuoo1mB9iG5eq/Mw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqOXlMYkh4WjNYcnlJaHh1
            WklXYkx4Qld6MUZHUFFXWlpYeU8wZjk4UVIwClNXY0tTUlRNMmRJekxWVFBKQzY0
            SllNczFWYlVyUGRldHpTSDhmZDB0WUEKLS0tIGljNVdZSkpkZktPbUNIMDNhdm9m
            N2Z0bFJNc3dpQlFocnlpUXlXZTVyZEUKCbTZNalCAEG2Gl1aTIvpJlqA0uA2gA9o
            HhkHbttP7yqz2HHl+PWW12YVoRkXSKGLfqv3+/m0kj4ewvmiggCddw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-31T14:36:51Z"
    mac: ENC[AES256_GCM,data:A4shzJVyF+NGD5VGRtm7+sz+WFualgFrMwxIcjETgEWKxUCoDCqeBTezNtwHTU+32wDdN5fOBcV3QBi29/ZL7fZ9vQeBUoNgJrSULcjmG2yMDhKeB9gm3eDu2CAqVbHfhzh37LJBJ9aokROWkTURHYt6od8wTu/1btyFOqN9DnE=,iv:jnDE4hR7yEzQG5CJko6bX9KL+8uAalvBRhNeb8o2BGM=,tag:pHNcvfDGj0qrEdN8qj1oTA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
