import type { SkillTemplate } from "../character-skill-template/character-skill-template.module.code.ts"

export const CHARACTER_SKILLS_32 = {
  "health-avarice-116269": {
    id: "health-avarice-116269" as const,
    esoSkillId: 116269,
    name: "Health Avarice",
    baseName: "Health Avarice",
    skillLineId: "necromancer-bone-tyrant" as const,
    skillType: "passive" as const,
    description:
      "Increase your Healing Received by |cffffff1|r% for each Bone Tyrant ability slotted.\n\nCurrent bonus: |cffffff0|r%.",
    icon: "/esoui/art/icons/passive_necromancer_007.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 22,
    rank: 22,
    subcategoryId: "necromancer-bone-tyrant" as const,
  },
  "healthy-offering": {
    id: "healthy-offering" as const,
    esoSkillId: 36144,
    name: "Healthy Offering",
    baseName: "Malevolent Offering",
    skillLineId: "nightblade-siphoning" as const,
    skillType: "active" as const,
    description:
      "Pour out your lifesblood and channel the arcane, healing yourself or an ally in front of you for 3600 Health, while draining 1080 Health from yourself over 3 seconds.\n\nAfter casting, gain Minor Mending for 10 seconds, increasing your healing done by 8%.",
    icon: "/esoui/art/icons/ability_nightblade_011_a.dds",
    isMorph: true,
    morphIndex: 2,
    lineRankNeeded: 4,
    rank: 12,
    subcategoryId: "nightblade-siphoning" as const,
  },
  "healthy-offering-34727": {
    id: "healthy-offering-34727" as const,
    esoSkillId: 34727,
    name: "Healthy Offering",
    baseName: "Malevolent Offering",
    skillLineId: "nightblade-siphoning" as const,
    skillType: "active" as const,
    description:
      "Pour out your lifesblood and channel the arcane, healing yourself or an ally in front of you for |cffffff11321|r Health, while draining |cffffff1080|r Health from yourself over |cffffff3|r seconds.\n\nAfter casting, gain Minor Mending for |cffffff10|r seconds, increasing your healing done by |cffffff8|r%.",
    icon: "/esoui/art/icons/ability_nightblade_011_a.dds",
    isMorph: true,
    morphIndex: 2,
    lineRankNeeded: 4,
    rank: 4,
    subcategoryId: "nightblade-siphoning" as const,
  },
  "heart-of-flame": {
    id: "heart-of-flame" as const,
    esoSkillId: 32785,
    name: "Heart of Flame",
    baseName: "Core of Flame",
    skillLineId: "dragonknight-ardent-flame" as const,
    skillType: "active" as const,
    description:
      "Let the fire within draw heat to your heart, restoring |cffffff15|r% of your missing Health and |cffffff15|r% of your missing Magicka and Stamina every |cffffff2|r seconds over |cffffff4|r seconds.\n\nWhen this ability completes, you release this heat as a blast of fire that deals |cffffff7361|r Flame Damage to nearby enemies.",
    icon: "/esoui/art/icons/ability_dragonknight_012_b.dds",
    isMorph: true,
    morphIndex: 2,
    lineRankNeeded: 20,
    rank: 20,
    subcategoryId: "dragonknight-ardent-flame" as const,
  },
  "heart-of-stone": {
    id: "heart-of-stone" as const,
    esoSkillId: 29468,
    name: "Heart of Stone",
    baseName: "Heart of Stone",
    skillLineId: "dragonknight-earthen-heart" as const,
    skillType: "passive" as const,
    description:
      "Rock and stone shield your heart, turning aside sharp blades and barbed words.\n\nIncreases your Armor by |cffffff1487|r.",
    icon: "/esoui/art/icons/ability_dragonknight_032.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 8,
    rank: 8,
    subcategoryId: "dragonknight-earthen-heart" as const,
  },
  "hearth-and-home": {
    id: "hearth-and-home" as const,
    esoSkillId: 32710,
    name: "Hearth and Home",
    baseName: "Hearthfire",
    skillLineId: "dragonknight-ardent-flame" as const,
    skillType: "active" as const,
    description:
      "Throw out a protective flame for |cffffff15|r seconds, healing you and allies inside for |cffffff778|r Health every |cffffff1|r second, scaling off your Max Health.\n\nHealed targets gain Minor Fortitude and Minor Heroism while inside, increasing Health Recovery by |cffffff15|r% and generating |cffffff1|r Ultimate every |cffffff1.5|r seconds. You gain Major Protection while inside, reducing damage taken by |cffffff10|r%.\n\nEnemies inside have their Movement Speed reduced by |cffffff70|r%.",
    icon: "/esoui/art/icons/ability_dragonknight_016b.dds",
    isMorph: true,
    morphIndex: 2,
    lineRankNeeded: 30,
    rank: 30,
    subcategoryId: "dragonknight-ardent-flame" as const,
  },
  "hearthfire": {
    id: "hearthfire" as const,
    esoSkillId: 29059,
    name: "Hearthfire",
    baseName: "Hearthfire",
    skillLineId: "dragonknight-ardent-flame" as const,
    skillType: "active" as const,
    description:
      "Throw out a kindled flame, filling a large area with warmth for |cffffff15|r seconds. This fire heals you and your allies at the target location for |cffffff1369|r Health every |cffffff1|r second.\n\nHealed targets gain Minor Fortitude and Minor Heroism while inside, increasing Health Recovery by |cffffff15|r% and generating |cffffff1|r Ultimate every |cffffff1.5|r seconds.",
    icon: "/esoui/art/icons/ability_dragonknight_016.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 30,
    rank: 30,
    subcategoryId: "dragonknight-ardent-flame" as const,
  },
  "heavy-armor-bonuses": {
    id: "heavy-armor-bonuses" as const,
    esoSkillId: 150184,
    name: "Heavy Armor Bonuses",
    baseName: "Heavy Armor Bonuses",
    skillLineId: "armor-heavy-armor" as const,
    skillType: "passive" as const,
    description:
      "Each piece of Heavy Armor does the following:\n\nReduces damage taken from Martial attacks by 1%\n\nIncreases the amount of damage blocked by 1%\n\nIncreases damage done with Bash by 30\n\nReduces your damage taken while immune to crowd control by 1%",
    icon: "/esoui/art/icons/passive_armor2_heavy.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 1,
    rank: 1,
    subcategoryId: "armor-heavy-armor" as const,
    effects: [
      {
        "metricId": "defense-physical-mitigation",
        "valueType": "fractional-change",
        "effectType": "armor-piece-scaling",
        "armorWeight": "heavy",
        "valuePerPiece": 0.01,
      },
      {
        "metricId": "block-mitigation",
        "valueType": "fractional-change",
        "effectType": "armor-piece-scaling",
        "armorWeight": "heavy",
        "valuePerPiece": 0.01,
      },
      {
        "metricId": "bash-damage",
        "valueType": "integer",
        "effectType": "armor-piece-scaling",
        "armorWeight": "heavy",
        "valuePerPiece": 30,
      },
    ] as const,
    status: "partially-supported" as const,
  },
  "heavy-armor-penalties": {
    id: "heavy-armor-penalties" as const,
    esoSkillId: 152780,
    name: "Heavy Armor Penalties",
    baseName: "Heavy Armor Penalties",
    skillLineId: "armor-heavy-armor" as const,
    skillType: "passive" as const,
    description:
      "Each piece of Heavy Armor does the following:\n\nIncreases damage taken from Magical attacks by 1%\n\nReduces the Movement Speed bonus of Sprint by 1%\n\nIncreases the cost of Roll Dodge by 3%\n\nIncreases the size of your detection area while Sneaking by 10%",
    icon: "/esoui/art/icons/passive_armor2_heavy.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 1,
    rank: 1,
    subcategoryId: "armor-heavy-armor" as const,
    effects: [
      {
        "metricId": "defense-spell-mitigation",
        "valueType": "fractional-change",
        "effectType": "armor-piece-scaling",
        "armorWeight": "heavy",
        "valuePerPiece": -0.01,
      },
      {
        "metricId": "stamina-dodge-cost",
        "valueType": "fractional-change",
        "effectType": "armor-piece-scaling",
        "armorWeight": "heavy",
        "valuePerPiece": 0.03,
      },
    ] as const,
    status: "partially-supported" as const,
  },
  "heavy-shovel": {
    id: "heavy-shovel" as const,
    esoSkillId: 139907,
    name: "Heavy Shovel",
    baseName: "Heavy Shovel",
    skillLineId: "world-excavation" as const,
    skillType: "passive" as const,
    description:
      "Removes 1 layer of dirt and rocks from up to a 3x3 area.\n\nThe shovel only affects a single contiguous height of dirt and rocks.\n\nCosts 2 Intuition to use.\nHas a chance to consume no Intuition on use.",
    icon: "/esoui/art/icons/u26_ability_digging_02.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 8,
    rank: 2,
    subcategoryId: "world-excavation" as const,
  },
  "heavy-shovel-139906": {
    id: "heavy-shovel-139906" as const,
    esoSkillId: 139906,
    name: "Heavy Shovel",
    baseName: "Heavy Shovel",
    skillLineId: "world-excavation" as const,
    skillType: "passive" as const,
    description:
      "Removes |cFFFFFF1|r layer of dirt and rocks from up to a |cFFFFFF3x3|r area.\n\nThe shovel only affects a single contiguous height of dirt and rocks.\n\nCosts |c19D3FF2 Intuition|r to use.",
    icon: "/esoui/art/icons/u26_ability_digging_02.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 4,
    rank: 4,
    subcategoryId: "world-excavation" as const,
  },
  "heavy-weapons": {
    id: "heavy-weapons" as const,
    esoSkillId: 45430,
    name: "Heavy Weapons",
    baseName: "Heavy Weapons",
    skillLineId: "weapon-two-handed" as const,
    skillType: "passive" as const,
    description:
      "Grants a bonus based on the type of weapon equipped:\n\nSwords increase your Weapon and Spell Damage by 258.\n\nAxes increase your Critical Damage done by 12%.\n\nMaces increase your Offensive Penetration by 2974.",
    icon: "/esoui/art/icons/passive_dragonknight_026.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 10,
    rank: 2,
    subcategoryId: "weapon-two-handed" as const,
    effects: [
      {
        "metricId": "power",
        "valueType": "integer",
        "effectType": "weapon-type-conditional",
        "effectValue": 258,
        "weaponTypes": ["greatsword"],
      },
      {
        "metricId": "critical-damage",
        "valueType": "fractional-change",
        "effectType": "weapon-type-conditional",
        "effectValue": 0.12,
        "weaponTypes": ["battleaxe"],
      },
      {
        "metricId": "penetration",
        "valueType": "integer",
        "effectType": "weapon-type-conditional",
        "effectValue": 2974,
        "weaponTypes": ["maul"],
      },
    ] as const,
    status: "supported" as const,
  },
  "hemorrhage": {
    id: "hemorrhage" as const,
    esoSkillId: 45060,
    name: "Hemorrhage",
    baseName: "Hemorrhage",
    skillLineId: "nightblade-assassination" as const,
    skillType: "passive" as const,
    description:
      "Increases your Critical Damage by 10%. \n\nDealing Critical Damage grants you and your group Minor Savagery, increasing your Weapon Critical rating by 1314 for 20 seconds.",
    icon: "/esoui/art/icons/passive_weapon_017.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 39,
    rank: 2,
    subcategoryId: "nightblade-assassination" as const,
    effects: [] as const,
    status: "partially-supported" as const,
  },
  "heroic-slash": {
    id: "heroic-slash" as const,
    esoSkillId: 41414,
    name: "Heroic Slash",
    baseName: "Low Slash",
    skillLineId: "weapon-one-hand-and-shield" as const,
    skillType: "active" as const,
    description:
      "Surprise an enemy with a deep lunge, dealing 1438 Physical Damage and afflicting them with Minor Maim, reducing their damage done by 5% for 15 seconds. \n\nYou gain Minor Heroism, granting you 1 Ultimate every 1.5 seconds for 15 seconds.",
    icon: "/esoui/art/icons/ability_1handed_001_a.dds",
    isMorph: true,
    morphIndex: 2,
    lineRankNeeded: 4,
    rank: 12,
    subcategoryId: "weapon-one-hand-and-shield" as const,
  },
  "heroic-slash-38264": {
    id: "heroic-slash-38264" as const,
    esoSkillId: 38264,
    name: "Heroic Slash",
    baseName: "Low Slash",
    skillLineId: "weapon-one-hand-and-shield" as const,
    skillType: "active" as const,
    description:
      "Surprise an enemy with a deep lunge, dealing |cffffff5004|r Physical Damage and afflicting them with Minor Maim, reducing their damage done by |cffffff5|r% for |cffffff15|r seconds. \n\nYou gain Minor Heroism, granting you |cffffff1|r Ultimate every |cffffff1.5|r seconds for |cffffff15|r seconds.",
    icon: "/esoui/art/icons/ability_1handed_001_a.dds",
    isMorph: true,
    morphIndex: 2,
    lineRankNeeded: 4,
    rank: 4,
    subcategoryId: "weapon-one-hand-and-shield" as const,
  },
  "hexproof": {
    id: "hexproof" as const,
    esoSkillId: 40117919,
    name: "Hexproof",
    baseName: "Expunge",
    skillLineId: "necromancer-living-death" as const,
    skillType: "active" as const,
    description:
      "Embrace the power of death, removing up to 4 negative effects from yourself.\n\nWhile slotted, the cost of all your abilities are reduced by 3%.",
    icon: "/esoui/art/icons/ability_necromancer_014_a.dds",
    isMorph: true,
    morphIndex: 2,
    lineRankNeeded: 4,
    rank: 12,
    subcategoryId: "necromancer-living-death" as const,
    effects: [
      {
        "metricId": "magicka-ability-cost",
        "effectType": "fractional-change",
        "effectValue": -0.03,
        "slottedBehavior": "active-bar-only",
      },
      {
        "metricId": "stamina-ability-cost",
        "effectType": "fractional-change",
        "effectValue": -0.03,
        "slottedBehavior": "active-bar-only",
      },
      {
        "metricId": "ultimate-ability-cost",
        "effectType": "fractional-change",
        "effectValue": -0.03,
        "slottedBehavior": "active-bar-only",
      },
    ] as const,
  },
  "hexproof-117919": {
    id: "hexproof-117919" as const,
    esoSkillId: 117919,
    name: "Hexproof",
    baseName: "Expunge",
    skillLineId: "necromancer-living-death" as const,
    skillType: "active" as const,
    description:
      "Embrace the power of death, removing up to |cffffff4|r negative effects from yourself.\n\nWhile slotted, the cost of all your abilities are reduced by |cffffff3|r%.",
    icon: "/esoui/art/icons/ability_necromancer_014_a.dds",
    isMorph: true,
    morphIndex: 2,
    lineRankNeeded: 4,
    rank: 4,
    subcategoryId: "necromancer-living-death" as const,
  },
} satisfies Record<string, SkillTemplate>
