import type { SetTemplate } from "@akasha/temper-equipment/set-template"

export const SETS_DATA_070: readonly SetTemplate[] = [
  {
    id: "perfected-gallant-charge",
    name: "Perfected Gallant Charge",
    esoSetId: 423,
    subcategoryId: "arena",
    valid: ["sword", "axe", "mace", "dagger", "shield"],
    bonuses: [
      {
        count: 2,
        status: "unsupported",
        effects: [],
        description:
          "Reduces the cost of Shield Charge by 25% and reduces the cost of your next non-Shield Charge One Handed and Shield ability cast within 3 seconds by 100%.",
      },
    ],
    icons: {
      axe: "/esoui/art/icons/gear_honorguard_1haxe_a.dds",
      dagger: "/esoui/art/icons/gear_honorguard_dagger_a.dds",
      mace: "/esoui/art/icons/gear_honorguard_1hmace_a.dds",
      shield: "/esoui/art/icons/gear_honorguard_shield_a.dds",
      sword: "/esoui/art/icons/gear_honorguard_1hsword_a.dds",
    },
  },
  {
    id: "perfected-grand-rejuvenation",
    name: "Perfected Grand Rejuvenation",
    esoSetId: 533,
    subcategoryId: "arena",
    valid: ["restoration-staff"],
    bonuses: [
      {
        count: 2,
        status: "unsupported",
        effects: [],
        description:
          "The initial heal of Grand Healing invigorates you and group members affected for 6 seconds, restoring 224 Magicka and Stamina every 2 seconds.",
      },
    ],
    icons: { "restoration-staff": "/esoui/art/icons/gear_breton_staff_e.dds" },
  },
  {
    id: "perfected-harmony-in-chaos",
    name: "Perfected Harmony in Chaos",
    esoSetId: 821,
    subcategoryId: "no-type",
    valid: ["*:light"],
    bonuses: [
      {
        count: 2,
        status: "supported",
        effects: [{ metricId: "power", effectType: "integer", effectValue: 129 }],
        description: "Adds 129 Weapon and Spell Damage",
      },
      {
        count: 3,
        status: "unsupported",
        effects: [],
        description:
          "Gain Minor Slayer at all times, increasing your damage done to Dungeon, Trial, and Arena Monsters by 5%.",
      },
      {
        count: 4,
        status: "supported",
        effects: [{ metricId: "power", effectType: "integer", effectValue: 129 }],
        description: "Adds 129 Weapon and Spell Damage",
      },
      {
        count: 5,
        status: "supported",
        effects: [{ metricId: "power", effectType: "integer", effectValue: 200 }],
        description: "Adds 200 Weapon and Spell Damage",
      },
      {
        count: 5,
        status: "unsupported",
        effects: [],
        description:
          "While in combat, activating a synergy increases your Weapon and Spell Damage by 88 for 15 seconds, stacking up to 5 times.",
      },
    ],
    icons: {
      "axe": "/esoui/art/icons/gear_coldharbourdominator_1haxe_a.dds",
      "battleaxe": "/esoui/art/icons/gear_coldharbourdominator_2haxe_a.dds",
      "bow": "/esoui/art/icons/gear_coldharbourdominator_bow_a.dds",
      "chest:*": "/esoui/art/icons/gear_coldharbordominator_light_robe_a.dds",
      "dagger": "/esoui/art/icons/gear_coldharbourdominator_dagger_a.dds",
      "feet:*": "/esoui/art/icons/gear_coldharbordominator_light_feet_a.dds",
      "greatsword": "/esoui/art/icons/gear_coldharbourdominator_2hsword_a.dds",
      "hands:*": "/esoui/art/icons/gear_coldharbordominator_light_hands_a.dds",
      "head:*": "/esoui/art/icons/gear_coldharbordominator_light_head_a.dds",
      "ice-staff": "/esoui/art/icons/gear_coldharbourdominator_staff_a.dds",
      "inferno-staff": "/esoui/art/icons/gear_coldharbourdominator_staff_a.dds",
      "legs:*": "/esoui/art/icons/gear_coldharbordominator_light_legs_a.dds",
      "lightning-staff": "/esoui/art/icons/gear_coldharbourdominator_staff_a.dds",
      "mace": "/esoui/art/icons/gear_coldharbourdominator_1hhammer_a.dds",
      "maul": "/esoui/art/icons/gear_coldharbourdominator_2hhammer_a.dds",
      "necklace": "/esoui/art/icons/gear_breton_neck_a.dds",
      "restoration-staff": "/esoui/art/icons/gear_coldharbourdominator_staff_a.dds",
      "ring": "/esoui/art/icons/gear_breton_ring_a.dds",
      "shield": "/esoui/art/icons/gear_coldharbourdominator_shield_a.dds",
      "shoulders:*": "/esoui/art/icons/gear_coldharbordominator_light_shoulders_a.dds",
      "sword": "/esoui/art/icons/gear_coldharbourdominator_1hsword_a.dds",
      "waist:*": "/esoui/art/icons/gear_coldharbordominator_light_waist_a.dds",
    },
  },
  {
    id: "perfected-kazpians-cruel-signet",
    name: "Perfected Kazpian's Cruel Signet",
    esoSetId: 820,
    subcategoryId: "no-type",
    valid: ["*:medium"],
    bonuses: [
      {
        count: 2,
        status: "supported",
        effects: [{ metricId: "power", effectType: "integer", effectValue: 129 }],
        description: "Adds 129 Weapon and Spell Damage",
      },
      {
        count: 3,
        status: "unsupported",
        effects: [],
        description:
          "Gain Minor Slayer at all times, increasing your damage done to Dungeon, Trial, and Arena Monsters by 5%.",
      },
      {
        count: 4,
        status: "supported",
        effects: [{ metricId: "penetration", effectType: "integer", effectValue: 1487 }],
        description: "Adds 1487 Offensive Penetration",
      },
      {
        count: 5,
        status: "unsupported",
        effects: [],
        description:
          "On dealing area direct damage, place a Sword above an enemy, up to once every 1 second. You cannot place a Sword on an enemy who already has one from you. After 6 seconds, the Sword falls, dealing 772 Physical Damage. This damage scales off the higher of your Weapon or Spell Damage. \n\nApplying a Sword increases your damage done by 2% for 6 seconds, stacking up to 6 times.",
      },
    ],
    icons: {
      "axe": "/esoui/art/icons/gear_coldharbourdominator_1haxe_a.dds",
      "battleaxe": "/esoui/art/icons/gear_coldharbourdominator_2haxe_a.dds",
      "bow": "/esoui/art/icons/gear_coldharbourdominator_bow_a.dds",
      "chest:*": "/esoui/art/icons/gear_coldharbordominator_medium_chest_a.dds",
      "dagger": "/esoui/art/icons/gear_coldharbourdominator_dagger_a.dds",
      "feet:*": "/esoui/art/icons/gear_coldharbordominator_medium_feet_a.dds",
      "greatsword": "/esoui/art/icons/gear_coldharbourdominator_2hsword_a.dds",
      "hands:*": "/esoui/art/icons/gear_coldharbordominator_medium_hands_a.dds",
      "head:*": "/esoui/art/icons/gear_coldharbordominator_medium_head_a.dds",
      "ice-staff": "/esoui/art/icons/gear_coldharbourdominator_staff_a.dds",
      "inferno-staff": "/esoui/art/icons/gear_coldharbourdominator_staff_a.dds",
      "legs:*": "/esoui/art/icons/gear_coldharbordominator_medium_legs_a.dds",
      "lightning-staff": "/esoui/art/icons/gear_coldharbourdominator_staff_a.dds",
      "mace": "/esoui/art/icons/gear_coldharbourdominator_1hhammer_a.dds",
      "maul": "/esoui/art/icons/gear_coldharbourdominator_2hhammer_a.dds",
      "necklace": "/esoui/art/icons/gear_breton_neck_a.dds",
      "restoration-staff": "/esoui/art/icons/gear_coldharbourdominator_staff_a.dds",
      "ring": "/esoui/art/icons/gear_breton_ring_a.dds",
      "shield": "/esoui/art/icons/gear_coldharbourdominator_shield_a.dds",
      "shoulders:*": "/esoui/art/icons/gear_coldharbordominator_medium_shoulder_a.dds",
      "sword": "/esoui/art/icons/gear_coldharbourdominator_1hsword_a.dds",
      "waist:*": "/esoui/art/icons/gear_coldharbordominator_medium_waist_a.dds",
    },
  },
  {
    id: "perfected-kynes-wind",
    name: "Perfected Kyne's Wind",
    esoSetId: 493,
    subcategoryId: "trial",
    valid: ["*:light"],
    bonuses: [
      {
        count: 2,
        status: "supported",
        effects: [{ metricId: "magicka-recovery", effectType: "integer", effectValue: 129 }],
        description: "Adds 129 Magicka Recovery",
      },
      {
        count: 3,
        status: "unsupported",
        effects: [],
        description:
          "Gain Minor Aegis at all times, reducing your damage taken from Dungeon, Trial, and Arena Monsters by 5%.",
      },
      {
        count: 4,
        status: "supported",
        effects: [
          { metricId: "healing-done-base", effectType: "fractional-change", effectValue: 0.04 },
        ],
        description: "Adds 4% Healing Done",
      },
      {
        count: 5,
        status: "unsupported",
        effects: [],
        description:
          "When you overheal yourself or a group member, you create a pool of Kyne's Blessing under the target for 4 seconds. You and group members standing in Kyne's Blessing restore 420 Stamina and Magicka every 1 second. This effect can occur once every 10 seconds.",
      },
    ],
    icons: {
      "axe": "/esoui/art/icons/gear_seagiant_axe.dds",
      "battleaxe": "/esoui/art/icons/gear_seagiant_2haxe.dds",
      "bow": "/esoui/art/icons/gear_seagiant_bow.dds",
      "chest:*": "/esoui/art/icons/gear_seagiant_robe_a.dds",
      "dagger": "/esoui/art/icons/gear_seagiant_dagger.dds",
      "feet:*": "/esoui/art/icons/gear_seagiantlgt_feet.dds",
      "greatsword": "/esoui/art/icons/gear_seagiant_2hsword.dds",
      "hands:*": "/esoui/art/icons/gear_seagiantlgt_hands.dds",
      "head:*": "/esoui/art/icons/gear_seagiantlgt_helmet.dds",
      "ice-staff": "/esoui/art/icons/gear_seagiant_staff.dds",
      "inferno-staff": "/esoui/art/icons/gear_seagiant_staff.dds",
      "legs:*": "/esoui/art/icons/gear_seagiantlgt_legs.dds",
      "lightning-staff": "/esoui/art/icons/gear_seagiant_staff.dds",
      "mace": "/esoui/art/icons/gear_seagiant_mace.dds",
      "maul": "/esoui/art/icons/gear_seagiant_2hmace.dds",
      "necklace": "/esoui/art/icons/gear_breton_neck_a.dds",
      "restoration-staff": "/esoui/art/icons/gear_seagiant_staff.dds",
      "ring": "/esoui/art/icons/gear_breton_ring_a.dds",
      "shield": "/esoui/art/icons/gear_seagiant_shield.dds",
      "shoulders:*": "/esoui/art/icons/gear_seagiantlgt_shoulders.dds",
      "sword": "/esoui/art/icons/gear_seagiant_sword.dds",
      "waist:*": "/esoui/art/icons/gear_seagiantlgt_waist.dds",
    },
  },
  {
    id: "perfected-lucent-echoes",
    name: "Perfected Lucent Echoes",
    esoSetId: 771,
    subcategoryId: "trial",
    valid: ["*:heavy"],
    bonuses: [
      {
        count: 2,
        status: "supported",
        effects: [
          { metricId: "healing-taken-base", effectType: "fractional-change", effectValue: 0.04 },
        ],
        description: "Adds 4% Healing Taken",
      },
      {
        count: 3,
        status: "unsupported",
        effects: [],
        description:
          "Gain Minor Aegis at all times, reducing your damage taken from Dungeon, Trial, and Arena Monsters by 5%.",
      },
      {
        count: 4,
        status: "supported",
        effects: [{ metricId: "health-maximum", effectType: "integer", effectValue: 1206 }],
        description: "Adds 1206 Maximum Health",
      },
      {
        count: 5,
        status: "unsupported",
        effects: [],
        description:
          "While you have more than 50% Health, the Critical Damage and Critical Healing of any group members not wearing Lucent Echoes within 28 meters of you increases by 11%.\n\nWhile you have 50% or less Health, your damage taken from monsters is reduced by 20%.",
      },
    ],
    icons: {
      "axe": "/esoui/art/icons/gear_lucentguardian_1haxe_a.dds",
      "battleaxe": "/esoui/art/icons/gear_lucentguardian_2haxe_a.dds",
      "bow": "/esoui/art/icons/gear_lucentguardian_bow_a.dds",
      "chest:*": "/esoui/art/icons/gear_lucentguardian_heavy_chest_a.dds",
      "dagger": "/esoui/art/icons/gear_lucentguardian_dagger_a.dds",
      "feet:*": "/esoui/art/icons/gear_lucentguardian_heavy_feet_a.dds",
      "greatsword": "/esoui/art/icons/gear_lucentguardian_2hsword_a.dds",
      "hands:*": "/esoui/art/icons/gear_lucentguardian_heavy_hands_a.dds",
      "head:*": "/esoui/art/icons/gear_lucentguardian_heavy_head_a.dds",
      "ice-staff": "/esoui/art/icons/gear_lucentguardian_staff_a.dds",
      "inferno-staff": "/esoui/art/icons/gear_lucentguardian_staff_a.dds",
      "legs:*": "/esoui/art/icons/gear_lucentguardian_heavy_legs_a.dds",
      "lightning-staff": "/esoui/art/icons/gear_lucentguardian_staff_a.dds",
      "mace": "/esoui/art/icons/gear_lucentguardian_1hhammer_a.dds",
      "maul": "/esoui/art/icons/gear_lucentguardian_2hhammer_a.dds",
      "necklace": "/esoui/art/icons/gear_breton_neck_a.dds",
      "restoration-staff": "/esoui/art/icons/gear_lucentguardian_staff_a.dds",
      "ring": "/esoui/art/icons/gear_breton_ring_a.dds",
      "shield": "/esoui/art/icons/gear_lucentguardian_shield_a.dds",
      "shoulders:*": "/esoui/art/icons/gear_lucentguardian_heavy_shoulders_a.dds",
      "sword": "/esoui/art/icons/gear_lucentguardian_1hsword_a.dds",
      "waist:*": "/esoui/art/icons/gear_lucentguardian_heavy_waist_a.dds",
    },
  },
]
