import type { Domain } from "akasha/domain/domain.page-type.types.ts"

export const temperAddonWorldCollections = {
  id: "01a0c701-b7e2-7653-a42c-091824596cae",
  type: "page-type/domain",
  slug: "temper-addon-world-collections",
  definition:
    "the skyshard, lorebook, treasure, champion and item-set trackers and the journal window they share",
  parts: [
    "eso-interface/item-browser-layout",
    "eso-interface/journal-controls",
    "eso-interface/lorebooks-report-layout",
    "eso-interface/lost-treasure-map-layout",
    "module/collections-addon-entry",
    "module/collections-addon-global",
    "module/collections-addon-loaded",
    "module/collections-addon-names",
    "module/journal-casts",
    "module/journal-core",
    "module/journal-l10n",
    "module/journal-main",
    "module/journal-main-menu",
    "module/journal-shape",
    "module/journal-sort-filter-list",
    "module/journal-state",
    "module/journal-tabs",
    "module/journal-tooltip-colors",
    "module/journal-tooltip-extension",
    "module/journal-tooltips",
    "module/journal-window",
    "module/saved-vars-casts",
    "module/saved-vars-constants",
    "module/saved-vars-data",
    "module/saved-vars-data-active",
    "module/saved-vars-data-constructors",
    "module/saved-vars-data-helpers",
    "module/saved-vars-data-iterator",
    "module/saved-vars-data-migrate",
    "module/saved-vars-data-settings",
    "module/saved-vars-data-state",
    "module/saved-vars-lib-core",
    "module/saved-vars-lib-overrides",
    "module/saved-vars-lib-state",
    "module/saved-vars-main",
    "module/saved-vars-manager",
    "module/saved-vars-manager-core",
    "module/saved-vars-manager-state",
    "module/saved-vars-protected",
    "module/saved-vars-protected-migrate",
    "module/saved-vars-registry",
    "module/saved-vars-types",
    "module/treasure-api",
    "module/treasure-book-ids",
    "module/treasure-build-data",
    "module/treasure-casts",
    "module/treasure-constants",
    "module/treasure-data",
    "module/treasure-icons",
    "module/treasure-pins-data",
    "module/treasure-pins-data-00",
    "module/treasure-pins-data-01",
    "module/treasure-pins-data-02",
    "module/treasure-pins-data-03",
    "module/treasure-types",
    "type-declaration/collections-addon-declarations",
    "type-declaration/journal-control-names",
    "type-declaration/journal-saved-variables",
    "type-declaration/journal-string-ids",
  ],
  decisions: [
    {
      decisionKind: "decision-kind/departure",
      statement: "Each tracker is a workspace package of its own.",
    },
    {
      decisionKind: "decision-kind/departure",
      statement: "This feature starts each tracker and knows nothing else about that tracker.",
    },
    {
      decisionKind: "decision-kind/departure",
      statement: "A tracker publishes its own global rather than a member of the add-on's.",
    },
    {
      decisionKind: "decision-kind/departure",
      statement: "The journal's control document loads before the Lua bundle.",
    },
    {
      decisionKind: "decision-kind/departure",
      statement: "The lorebook, treasure and browser documents load after the Lua bundle.",
    },
    {
      decisionKind: "decision-kind/absence",
      statement: "Nothing here reads the data a tracker keeps.",
    },
    {
      decisionKind: "decision-kind/departure",
      statement:
        "The journal window, the saved-variables scopes and the treasure data are parts of this feature.",
    },
  ],
} as const satisfies Domain
