import type { WorkspacePackage } from "../../code-system/workspace-packages/workspace-package.page-type.ts"

export const temperCompanionsCore = {
  id: "01a06108-0770-7896-af0b-609e72d8fa97",
  pageTypeSlug: "workspace-package",
  slug: "temper-companions-core",
  definition: "the gear, roles and traits a companion in The Elder Scrolls Online is built from",
  manifest: "json",
  partSlugs: [
    "module/companion-armor-slots",
    "module/companion-armor-weights",
    "module/companion-base-roles",
    "module/companion-equipment-qualities",
    "module/companion-eso-trait-map",
    "module/companion-jewelry-slots",
    "module/companion-metric-effect",
    "module/companion-metric-ids",
    "module/companion-metric-template",
    "module/companion-roles",
    "module/companion-traits",
    "module/companion-weapon-roles",
    "module/companion-weapon-slots",
    "module/companion-weapon-types",
    "module/bad-truncate",
    "module/companion-activation-buffs",
    "module/companion-description-utils",
    "module/companion-effect-category",
    "module/companion-effect-formatters",
    "module/companion-effect-labels",
    "module/companion-equipment-quality-rules",
    "module/companion-passive-metrics",
    "module/companion-skill-activation-effect-types",
    "module/companion-skill-effect-components",
    "module/companion-support-types",
    "module/companion-value-formula",
    "module/companion-weapon-base-values",
    "module/rotation-breakdown-rows",
    "module/skill-lines-by-companion",
    "module/companion-skill-slots",
    "module/companion-skills",
    "module/companion-skills-00",
    "module/companion-skills-01",
    "module/companion-skills-02",
    "module/companion-skills-03",
    "module/companion-skills-04",
    "module/companion-skills-05",
    "module/companion-skills-06",
    "module/companion-skills-07",
    "module/companion-skills-08",
    "module/companion-skills-09",
    "module/companion-skills-10",
    "module/companion-types",
    "module/companions",
    "module/companion-armor-base-values",
    "module/companion-build-edits",
    "module/companion-bulk-update-equipment",
    "module/companion-description-formula",
    "module/companion-effect-sources",
    "module/companion-equipment-icons",
    "module/companion-equipment-slots",
    "module/companion-factory",
    "module/companion-formula-evaluator",
    "module/companion-formula-extraction",
    "module/companion-leaderboard",
    "module/companion-light-attack",
    "module/companion-metric-display-formula",
    "module/companion-metrics",
    "module/companion-metrics-00",
    "module/companion-metrics-01",
    "module/companion-metrics-02",
    "module/companion-metric-tree",
    "module/companion-optimizer",
    "module/companion-passive-effects",
    "module/companion-periodic-formula",
    "module/companion-rotation-metrics",
    "module/companion-rotation-results",
    "module/companion-rotation-simulator",
    "module/companion-rotation-slot",
    "module/companion-rotation-state",
    "module/companions-base-source",
    "module/companion-schema",
    "module/companion-skill-executor",
    "module/companion-skill-formula",
    "module/companion-skill-line-queries",
    "module/companion-skill-optimizer",
    "module/companion-skill-tooltip",
    "module/companion-soothing-healing",
    "module/companion-stats-calculator",
    "module/companion-stats-calculator-impl",
    "module/companion-stats-result",
    "module/companion-suggestion-generator",
    "module/companion-support-baseline",
    "module/companion-support-buff-math",
    "module/companion-support-contributions",
    "module/companion-support-evaluator",
    "module/companion-trait-optimizer",
    "module/companion-valid-skills",
    "module/companion-weapon-role-match",
    "module/condition-evaluator",
    "module/reference-build-data",
    "module/rotation-types",
  ],
  invariants: [
    {
      invariantKind: "departure",
      statement: "Every table here is written out from the companion pages rather than by hand.",
    },
    {
      invariantKind: "departure",
      statement:
        "The generator that writes these tables outside akasha reads the same companion pages.",
    },
  ],
} as const satisfies WorkspacePackage
