apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cloudflared
    labels:
        app.kubernetes.io/name: cloudflared
        app.kubernetes.io/instance: ddns
        app.kubernetes.io/component: ddns
        app.kubernetes.io/part-of: cloudflared
        app.kubernetes.io/managed-by: deploy-script
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:DXAGvnRgnJHQkPJqfw5GvI0/3gDMqXv5h2JOe2YobB8xWHS+4S9kNXcl4BI3wURDv8n0vkw=,iv:z7Jt0T27H4mtt+J6QvPMG8gunN8b4XPdTE4VcZB8Mp8=,tag:KokCAPd2F3qCs0Nhh0lFVg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuMVVkM0NWOUtqTFBkVGJq
            eWs2QVJvcHFkZUJ3WW1lTGVHb09JSEtjMFU0CmxTSkxuWTVZeTEyaWFXV1IvUlFU
            RFRXK1dxK1JLcE5XTlFTVzJqQkRDbzQKLS0tIGRMcFZqVTU5a29ZT0t5em1TejRI
            SDZGaWFOVFgzTFo0cEFPRkpOWFlnYWcKoLG3Ap86+coKOLsdZG3FUKb0UlBpUkG3
            hCaIZR09731OIEnVhgzFpcSXMpa1fhWgyWXoaCH4ocwdzvL1Tcx47A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T00:59:30Z"
    mac: ENC[AES256_GCM,data:N8he4Q1AUFwNbLeN/N3uIQBxc1fXMG3YjPd4nhdo43ALTyfDpIfT77Mv5lwMowO/A79fcxaHdtL8R7/p1Tht+T0soAi0ciizEm0Qsx5YSSzOom58eGGtF/wxmPCQOXcLoo7gttj5F6rTwWk/6CVKbBx06Q7SzroQVyk+CnnHLwY=,iv:aYhY72FfRN4hnlsWa21lLQ4c+lSir2Lp35eV4CZJOJc=,tag:MGwgBNx+ExPJcDK2VYypzQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
