import { resolve } from "node:path"
import type { ServiceConfig } from "../dockerfile-extensions/dockerfile-extensions.module.code.ts"

export const ROOT = resolve(import.meta.dirname, "../../../..")
export const HEADER = "# DO NOT EDIT — generated by infrastructure/dockerfiles\n"

export const SERVICES: Record<string, ServiceConfig> = {
  "auth-proxy": { type: "bun-service", dir: "infrastructure/auth-proxy" },
  "gfs-promoter": {
    type: "bun-service",
    dir: "infrastructure/backup-retention",
  },
  "alanwalton-calendar-sync": {
    type: "bun-service",
    dir: "akasha/calendar-sync",
  },
  ci: {
    type: "tool-image",
    dir: "infrastructure/dockerfiles",
    extensionFile: "../built-images/ci/ci.built-image.extensions.json",
  },
  "bun-git": {
    type: "tool-image",
    dir: "infrastructure/dockerfiles",
    extensionFile: "../built-images/bun-git/bun-git.built-image.extensions.json",
  },
  buildkit: {
    type: "tool-image",
    dir: "infrastructure/dockerfiles",
    extensionFile: "../built-images/buildkit/buildkit.built-image.extensions.json",
  },
  kubectl: {
    type: "tool-image",
    dir: "infrastructure/dockerfiles",
    extensionFile: "../built-images/kubectl/kubectl.built-image.extensions.json",
  },
}
