import type { Domain } from "../domain-system/domain/domain.page-type.ts"

export const temper = {
  id: "01a05db7-8d7c-762b-a343-9535d258e0b5",
  pageTypeSlug: "domain",
  slug: "temper",
  definition: "a companion suite for The Elder Scrolls Online",
  pluralSlug: "tempers",
  partSlugs: [
    "workspace-package/temper-addon-library-types",
    "workspace-package/temper-eso-types",
    "workspace-package/temper-catalog-core",
    "domain/temper-catalog",
    "domain/temper-character",
    "domain/temper-holdings",
    "domain/temper-progress",
    "page-type/temper-thing",
    "workspace-package/temper-watcher",
    "workspace-package/temper-inventory-automation",
    "rust-crate/watcher-tray",
    "workspace-package/temper-commands",
    "workspace-package/temper-dungeons",
    "workspace-package/temper-explain",
    "workspace-package/temper-upstream-data",
    "workspace-package/temper-addon-build",
    "workspace-package/temper-capture-shapes",
    "workspace-package/temper-eso-paths",
    "eso-addon/temper-lib-table-functions",
    "workspace-package/temper-saved-variables",
    "workspace-package/temper-settings-panel",
    "workspace-package/temper-capture-descriptor",
    "eso-addon/temper-lib-alchemy-station",
    "workspace-package/temper-lua-runner",
    "eso-addon/temper-lib-notification",
    "eso-addon/temper-lib-addon-keybinds",
    "eso-addon/temper-lib-custom-menu",
    "eso-addon/temper-lib-main-menu",
    "eso-addon/temper-lib-map-ping",
    "eso-addon/temper-lib-chat-message",
    "workspace-package/temper-addons-resolve",
    "eso-addon/temper-lib-debug-logger",
    "eso-addon/temper-lib-data-encode",
    "eso-addon/temper-lib-map-pins",
    "eso-addon/temper-lib-slash-commander",
    "workspace-package/temper-community-addons",
    "eso-addon/temper-lib-media-provider",
    "eso-addon/temper-lib-async",
    "workspace-package/temper-formula-framework",
    "workspace-package/temper-saved-vars-migration",
    "workspace-package/temper-addon-generators",
    "workspace-package/temper-capture-host",
    "workspace-package/temper-champion-points",
    "workspace-package/temper-classes",
    "workspace-package/temper-alchemy",
    "workspace-package/temper-game-collections-antiquities-capture-host",
    "workspace-package/temper-game-collections-capture-host",
    "workspace-package/temper-game-collections-lore-capture-host",
    "workspace-package/temper-game-collections-tribute-capture-host",
    "workspace-package/temper-game-completion-capture-host",
    "workspace-package/temper-game-crafting-capture-host",
    "workspace-package/temper-completion",
    "workspace-package/temper-catalog-host",
    "workspace-package/temper-game-navigation-capture-host",
    "workspace-package/temper-capture-datamining",
    "workspace-package/temper-capture-errors",
    "workspace-package/temper-capture-sales",
    "workspace-package/temper-races",
    "workspace-package/temper-skill-lines",
    "workspace-package/temper-quests-trace",
    "workspace-package/temper-trading-pricing",
    "workspace-package/temper-capture-datamining-reader",
    "workspace-package/temper-build-support",
  ],
  invariants: [
    {
      invariantKind: "departure",
      statement:
        "Where a thing falls among its siblings is stated by `display-order` and by no other property.",
    },
    {
      invariantKind: "departure",
      statement: "A page type temper carries is worked out from what its pages state.",
    },
    {
      invariantKind: "departure",
      statement:
        "A property more than one page type carries is declared by a page type above them.",
    },
  ],
} as const satisfies Domain
