import type { Domain } from "akasha/domain/domain.page-type.types.ts"

export const temperInterface = {
  id: "01a0c718-f838-76e6-8091-7844ddec0b8c",
  type: "page-type/domain",
  slug: "temper-interface",
  definition: "the interface tweaks that no other feature has a home for",
  parts: [
    "module/assistant-bindings",
    "module/assistant-collectibles",
    "module/assistant-entry",
    "module/tweak-after-login",
    "module/tweak-bank",
    "module/tweak-battleground",
    "module/tweak-casts",
    "module/tweak-chat",
    "module/tweak-collectibles",
    "module/tweak-collectibles-mounts",
    "module/tweak-collectibles-tooltips",
    "module/tweak-constants",
    "module/tweak-crafting",
    "module/tweak-crafting-smithing",
    "module/tweak-crafting-smithing-improve",
    "module/tweak-dialogs",
    "module/tweak-entry",
    "module/tweak-functions",
    "module/tweak-global",
    "module/tweak-group",
    "module/tweak-guild-history",
    "module/tweak-inventory",
    "module/tweak-inventory-scrollbar",
    "module/tweak-keybinds",
    "module/tweak-mail",
    "module/tweak-mail-buttons",
    "module/tweak-mail-context-menu",
    "module/tweak-mail-context-submenus",
    "module/tweak-mail-data",
    "module/tweak-mail-events",
    "module/tweak-mail-mass-delete",
    "module/tweak-mail-settings-menu",
    "module/tweak-mail-store",
    "module/tweak-mainmenu",
    "module/tweak-map",
    "module/tweak-overall",
    "module/tweak-panel-action-bars",
    "module/tweak-panel-battleground",
    "module/tweak-panel-chat",
    "module/tweak-panel-features",
    "module/tweak-panel-login",
    "module/tweak-panel-loot",
    "module/tweak-panel-main",
    "module/tweak-panel-progression",
    "module/tweak-panel-skills",
    "module/tweak-panel-storage",
    "module/tweak-panel-tooltips",
    "module/tweak-quest",
    "module/tweak-settings",
    "module/tweak-settings-defaults",
    "module/tweak-settings-empty",
    "module/tweak-settings-menu",
    "module/tweak-skill-action-bar-timers",
    "module/tweak-skills",
    "module/tweak-slash-command",
    "module/tweak-sounds",
    "module/tweak-stable",
    "module/tweak-state",
    "module/tweak-tooltips",
    "module/tweak-types",
    "module/tweak-ui",
    "module/tweak-utils",
    "module/interface-load",
    "module/quiet-alerts",
    "module/quiet-announcements",
    "module/quiet-camera",
    "module/quiet-camera-keybind",
    "module/quiet-craft-bag",
    "module/quiet-defaults",
    "module/quiet-dialogs",
    "module/quiet-entry",
    "module/quiet-guild-applications",
    "module/quiet-guild-invites",
    "module/quiet-guild-motd",
    "module/quiet-guild-roster",
    "module/quiet-identity",
    "module/quiet-list-provider",
    "module/quiet-lua-errors",
    "module/quiet-map-pins",
    "module/quiet-narrow",
    "module/quiet-print",
    "module/quiet-raid-leaderboard",
    "module/quiet-saved-variables",
    "module/quiet-settings-dialogs",
    "module/quiet-settings-guilds",
    "module/quiet-settings-header",
    "module/quiet-settings-menu",
    "module/quiet-settings-messages",
    "module/quiet-settings-world",
    "module/quiet-strings",
    "module/quiet-world",
    "module/shifter-box-class",
    "module/shifter-box-create",
    "module/shifter-box-cursor-label",
    "module/shifter-casts",
    "module/shifter-constants",
    "module/shifter-drag-helpers",
    "module/shifter-helpers",
    "module/shifter-lib-api",
    "module/shifter-list-class",
    "module/shifter-list-methods-drag",
    "module/shifter-list-methods-entries",
    "module/shifter-list-methods-rows",
    "module/shifter-list-ops",
    "module/shifter-public-api",
    "module/shifter-search-header",
    "module/shifter-state",
    "module/shifter-types",
    "module/shifter-validation",
    "type-declaration/assistant-entry-declarations",
    "type-declaration/tweak-controls",
    "type-declaration/tweak-global-declarations",
    "type-declaration/quiet-camera-keybind-declarations",
  ],
  decisions: [
    {
      decisionKind: "decision-kind/departure",
      statement: "Every assistant's keybind is named, whether or not the player has unlocked it.",
    },
    {
      decisionKind: "decision-kind/departure",
      statement: "A shifter box is keyed by the addon name together with the box name.",
    },
    {
      decisionKind: "decision-kind/departure",
      statement: "An entry is held by exactly one of the two lists.",
    },
    {
      decisionKind: "decision-kind/departure",
      statement: "An entry moves to the other list on a double click.",
    },
    {
      decisionKind: "decision-kind/departure",
      statement: "A dragged entry lands in the list the cursor is over.",
    },
    {
      decisionKind: "decision-kind/departure",
      statement: "The search header is hidden until the caller asks for a search box.",
    },
    {
      decisionKind: "decision-kind/departure",
      statement: "The shifter box is reached by import rather than through a global.",
    },
  ],
} as const satisfies Domain
