import type { TemperSet } from "akasha/temper/catalog/gear/temper-set/temper-set.page-type.types.ts"

export const cryptcanonVestments = {
  id: "019e6484-6028-76b1-b968-c2db0d0ac512",
  type: "page-type/temper-set",
  slug: "cryptcanon-vestments",
  title: "Cryptcanon Vestments",
  key: "cryptcanon-vestments",
  esoSetId: 691,
  esoItemIds: [194509],
  esoArmorTypes: ["ARMORTYPE_LIGHT"],
  esoEquipTypes: ["EQUIP_TYPE_CHEST"],
  setWayshrines: [536, 545, 538],
  setTypeId: 12,
  setNameZh: "地穴教士法衣",
  setNameRu: "Одеяние могильного каноника",
  setNameFr: "Vêtements du Chanoine de la crypte",
  setNameEs: "Vestimentas de canónigo de la cripta",
  setNameDe: "Gewandung des Kryptenvogts",
  setDropZones: [1414, 1413, 1414, 1414, 1389],
  setDropMechanics: [23, 7, 8, 10, 28],
  setDropLocationNamesEn: [
    "",
    "Uzur the All-Seeing [The Disquiet Study]",
    "Corlys the chainmaker [Clamorclap Bowl]",
    "",
    "Endboss",
  ],
  setDropLocationNamesDe: [
    "",
    "Uzur der Allessehende [Beunruhigenden Studien]",
    "Corlys der Kenntenschmied [Zeterklatsch Senke]",
    "",
    "Endgegner",
  ],
  setDlcId: 30,
  itemBrowserSources: ["-5"],
  itemBrowserPlaceKinds: [6],
  itemBrowserItemId: 194509,
  category: "temper-set-category/mythic",
  valid: ["chest:light"],
  bonuses: "jsonl",
  icons: "jsonl",
} as const satisfies TemperSet
