{"path":"infrastructure/container-image/dockerfiles/modules/dockerfile-writing/dockerfile-writing.module.test.ts"}
{"path":"infrastructure/container-image/modules/image-build/image-build.module.code.ts"}
