import type { StoryChapterWritten } from "akasha/story/world/stories/written/chapters/story-chapter-written.page-type.types.ts"

export const saltAndLamplight0002HerMothersDress = {
  id: "01a0fd20-a44a-76a5-b117-9d64d5474d7d",
  type: "page-type/story-chapter-written",
  slug: "salt-and-lamplight-0002-her-mothers-dress",
  cover: "image/image-a9468cb1dc383b4e",
  completedAt: "2026-10-02T15:29:36.379Z",
  ownProgress: 3308,
  position: 2,
  unit: "unit/words",
  title: "Her Mother's Dress",
  story: "story-written/salt-and-lamplight",
  ownLength: 3308,
  prose: "txt",
  stepStatus: "step-status/player",
  beats: [
    "Nala wakes in the loft at grey dawn, still in this small body, still Nala.",
    "She lies a while with a hand on her breasts under the shift; it doesn't feel like a dream.",
    "Below, the fire is made up and Morwenna's bed already straightened, the cottage empty.",
    "She has to piss, finds the privy behind the goat shed, and works out how to do it sitting.",
    "Morwenna's voice calls from the tower door: if she wants to see the lamp put out, it's now.",
    "Nala climbs the ninety-six steps on tender feet, slow, gripping the rail; Morwenna waits silent.",
    "The lantern room: the great glass lens, gleaming brass, the grey sea wide all round.",
    "Morwenna puts the lamp out for the day and shows her how the wick is trimmed.",
    "She hands Nala a soft cloth, and they polish the lens together, one each side of the glass.",
    "Through the glass Morwenna's face swims huge and bent; Nala laughs, and Morwenna nearly does.",
    "Morwenna milks Bramble and Sorrow while Nala watches; breakfast is bread, warm milk and an egg.",
    "Morwenna kneels at the chest at the foot of her bed and lifts out a smaller woman's clothes.",
    "A brown wool dress, stockings, a shawl and worn boots, all kept folded.",
    "Nala asks whose; Morwenna says \"My mother's. She's no use for them,\" and turns away.",
    "Nala understands the dry shift she slept in came from the same chest.",
    "The dress is long in the sleeve but fits; Nala fumbles the laces at the back.",
    "Morwenna does them up for her, quick and cold-fingered, and steps back fast.",
    "They walk the cliff path south toward Penmorrow in a hard wind, the sea crashing below.",
    "At a slick stretch Morwenna holds out her hand without a word, and Nala takes it.",
    "Morwenna lets go once the path is dry; Nala's hand stays cold where hers was.",
    "Penmorrow below: grey stone and slate stacked steep round a walled harbour, boats coming in.",
    "On the harbour front people stop and stare at the keeper and the stranger in the brown dress.",
    "A fisherman's eyes go over Nala, slow; startled, she knows she is being looked at as a woman.",
    "Morwenna steps between them without seeming to, and walks on.",
    "At the Anchor, Dilys Rowe comes out wiping floury hands, her sharp grey eyes already on Nala.",
    "Dilys sees the brown dress, stops, and looks at Morwenna a long moment.",
    'Morwenna says only "She\'d nothing to wear," and Dilys lets it go.',
    "Morwenna tells it short: found in the cove last night, calls herself Nala, from far away.",
    "Dilys says no boat on the coast has lost anyone this season, and no one's missing a woman.",
    "Dilys gives Nala a warm bun and won't take a penny; Nala realizes she hasn't one anyway.",
    "Nala asks after a room; Dilys says the Anchor's full of salting crews till the herring closes.",
    "Dilys says Nala had best stay up at the light, and looks at Morwenna as if daring her to refuse.",
    'Morwenna says "Till something\'s known," in a voice with nothing in it.',
    "Dilys tells Morwenna it'll do her good to have someone to talk to besides goats.",
    "Morwenna's jaw sets, and she says she'll fetch the oil from the chandlery, and goes.",
    "Alone with Nala, Dilys says quietly Morwenna's kinder than she lets on, and to mind that.",
    "Outside, Granny Bray sits on the bench by her blue door in a red shawl, shells at her wrist.",
    "Granny Bray beckons them over with her blackthorn stick, pale eyes fixed on Nala.",
    "She says the cove gave a stranger once before, in her grandmother's day.",
    "She says that stranger stayed up at the light with its keeper the rest of her life.",
    'Morwenna says "Granny" sharply; Granny Bray only smiles, and pats Nala\'s hand.',
    "They walk home with a can of lamp oil each, Morwenna silent and fast, Nala hurrying after.",
    "Nala asks if she minds her staying; Morwenna says it's what a keeper does, nothing more.",
    "Nala, stung, says she won't be a burden, and she'll work for her keep.",
    "Morwenna says she'll hold her to that, and doesn't look at her.",
    "At the cottage Nala mucks out the goat shed unasked, clumsy, while Morwenna sees to the light.",
    "Morwenna finds her with straw in her hair and muck on the hem of her mother's dress.",
    "Nala starts to apologize for the dress; Morwenna says her mother did worse to it every day.",
    "Morwenna picks a straw out of Nala's hair, and her fingers stop a moment at her temple.",
    "At dusk Morwenna takes her up the ninety-six steps again and lets her light the lamp.",
    "The flame catches under Nala's hand; Morwenna sets the clockwork going and the lens turns.",
    "They stand watching the beam sweep the Teeth, their shoulders not quite touching.",
    "Looking out to sea, Morwenna says Granny's stranger is likely an old woman's tale.",
    "Nala asks what if it isn't; Morwenna doesn't answer, and goes down first.",
    "In the loft that night Nala hears Morwenna below, awake, turning pages by the spare oil.",
    "Below, the pages stop turning for a long while, and the lamp's glow comes round on the slates.",
  ],
  issues: [
    '"her boots ringing on the iron stair" - the tower stair has stone treads earlier in the chapter',
    '"neither of you moves to close it or to widen it" - Nobody Acts',
    '"You fall asleep to the sound, on your second night as Nala." - Leave It Open',
  ],
  lore: [
    "lore/salt-and-lamplight-agnes",
    "lore/salt-and-lamplight-dilys",
    "lore/salt-and-lamplight-morwenna",
    "lore/salt-and-lamplight-nala",
    "place/salt-and-lamplight-morrow-head",
    "place/salt-and-lamplight-penmorrow",
  ],
  characters: [
    "character-player/salt-and-lamplight-nala",
    "character-other/salt-and-lamplight-morwenna",
    "character-other/salt-and-lamplight-dilys",
    "character-other/salt-and-lamplight-agnes",
  ],
  reviewedBy: ["story-reviewer/continuity", "story-reviewer/style"],
  recordedBy: [
    "story-recorder/mechanics",
    "story-recorder/inventory",
    "story-recorder/memory",
    "story-recorder/picture",
  ],
  scenes: [
    "image/image-352abe57eec803f2",
    "image/image-fb3782dedab6d778",
    "image/image-a9468cb1dc383b4e",
    "image/image-9a7b7d83858a3d40",
    "image/image-58fb12b5dbd18a28",
    "image/image-e640b5d1a8007be4",
    "image/image-ec084fa8b1ed226e",
    "image/image-3c32764b12b6a42a",
    "image/image-a064327f737cebf0",
    "image/image-ded0e0900d66698e",
  ],
  pictured: [
    {
      cover: "image/image-352abe57eec803f2",
      coverAfter: "Inside, you stand in front of the wooden seat for a moment,",
      character: "character-player/salt-and-lamplight-nala",
      outfit: "dry linen shift under a grey wool blanket",
      setting: "the tower stair",
    },
    {
      cover: "image/image-fb3782dedab6d778",
      coverAfter: "The lantern room is all glass. The sea lies wide on every",
      character: "character-player/salt-and-lamplight-nala",
      outfit: "dry linen shift under a grey wool blanket",
      setting: "the lantern room",
    },
    {
      cover: "image/image-a9468cb1dc383b4e",
      coverAfter: "She stays there a moment. Then she lifts things out, slowly, one",
      character: "character-player/salt-and-lamplight-nala",
      outfit: "her mother's brown wool dress",
    },
    {
      cover: "image/image-9a7b7d83858a3d40",
      coverAfter: "The cliff path runs south along the top of the land, a",
      character: "character-other/salt-and-lamplight-morwenna",
      outfit: "navy fisherman's jumper under a long dark wool coat, canvas trousers",
      setting: "the cliff path",
    },
    {
      cover: "image/image-58fb12b5dbd18a28",
      coverAfter: "Grey stone and grey slate, houses stacked one above another up a",
      character: "character-player/salt-and-lamplight-nala",
      outfit: "her mother's brown wool dress",
      setting: "Penmorrow harbour",
    },
    {
      cover: "image/image-e640b5d1a8007be4",
      coverAfter: "She goes inside and comes out with a bun in a cloth,",
      character: "character-player/salt-and-lamplight-nala",
      outfit: "her mother's brown wool dress",
    },
    {
      cover: "image/image-ec084fa8b1ed226e",
      coverAfter: "When Morwenna comes back from the chandlery with two cans of oil,",
      character: "character-other/salt-and-lamplight-dilys",
      outfit: "dark green wool dress, white linen apron",
      setting: "the Anchor",
    },
    {
      cover: "image/image-3c32764b12b6a42a",
      coverAfter: "Granny Bray only smiles at you, a smile with a few teeth",
      character: "character-other/salt-and-lamplight-agnes",
      outfit: "rusty black wool dress, dark red knitted shawl",
    },
    {
      cover: "image/image-a064327f737cebf0",
      coverAfter: "At the cottage she goes straight into the tower. You stand in",
      character: "character-player/salt-and-lamplight-nala",
      outfit: "her mother's brown wool dress",
      setting: "the goat shed",
    },
    {
      cover: "image/image-ded0e0900d66698e",
      coverAfter: "She stays silent. The beam comes round, lights her face for an",
      character: "character-other/salt-and-lamplight-morwenna",
      outfit: "navy fisherman's jumper, canvas trousers, sea boots",
    },
  ],
} as const satisfies StoryChapterWritten
