import type { StoryChapterWritten } from "akasha/story/world/stories/written/chapters/story-chapter-written.page-type.types.ts"

export const saltAndLamplight0003TheBoatSong = {
  id: "01a0fd3b-b750-7e6e-93d6-4356d7c91151",
  type: "page-type/story-chapter-written",
  slug: "salt-and-lamplight-0003-the-boat-song",
  cover: "image/image-1d60a060b39b22e2",
  position: 3,
  unit: "unit/words",
  title: "The Boat Song",
  story: "story-written/salt-and-lamplight",
  ownLength: 3184,
  prose: "txt",
  stepStatus: "step-status/player",
  beats: [
    "Nala wakes to the slates rattling; the wind has swung round to the north in the night.",
    "Below, Morwenna is already dressed, at the window, watching a sky gone yellow-grey.",
    "Morwenna says a gale is coming, a bad one, and there's work to do before it.",
    'Nala says "Then give me some," and Morwenna, after a look, does.',
    "They haul oil cans up the ninety-six steps two at a time; Nala's arms burn by the third trip.",
    "Morwenna lays spare wicks and clean cloths ready in the lantern room, everything in its place.",
    "Nala carries in driftwood and peat; Morwenna nails the garden gate shut and checks the shutters.",
    "In the goat shed Nala hears Morwenna singing under her breath as she lashes the door.",
    "It is an old slow coast song about a boat coming home, low and true.",
    "Nala stands still to listen; a board creaks under her, and Morwenna stops mid-line.",
    "Nala asks her to go on; Morwenna says it was nothing, her mother's, and lashes the door harder.",
    "By noon the sea is white to the horizon and the Teeth are lost in spray.",
    "Rain comes in sideways off the sea, hard as gravel against the shutters.",
    "In the afternoon the goat shed door rips loose and bangs, and the goats scream.",
    "Morwenna is up the tower; Nala, without asking, goes out into the gale to shut it.",
    "The wind knocks her flat on the yard stones and drags her a yard toward the edge.",
    "She crawls to the shed, holds the door shut with her shoulder, and gets the bar down.",
    "Morwenna comes running from the tower, grabs her by the arm and hauls her indoors.",
    "Morwenna shouts that she could have gone over the edge, and what was she thinking.",
    "Nala, soaked and shaking, shouts back that she said she'd work, and she meant it.",
    "Morwenna says not by dying in her yard, and her voice cracks on it.",
    "They stand dripping and glaring, both breathing hard, until Morwenna turns away first.",
    "Without a word Morwenna takes the tin bath down from the wall and sets it before the hearth.",
    "She fills it from the kettle and the black pot, again and again, until it steams.",
    '"Get in," she says, and turns her back, and stays standing there.',
    "Nala strips off the wet dress and shift and steps into the hot water.",
    "She sinks to her chin, knees drawn up; the heat stings, then soaks into her.",
    "She washes this body slowly, learning it: small breasts, soft belly, the red hair over her pussy.",
    "Watching Morwenna's straight back and braid, she feels a warm ache in her pussy, and goes still.",
    "She doesn't know what to do with wanting a woman from inside a woman's body.",
    "To say something, anything, she says she's sorry she frightened her.",
    "Back still turned, Morwenna says her mother died of a winter fever five years ago.",
    "She has kept the light alone since, she says, and she won't have anyone come to harm on it.",
    "Nala says she's sorry; Morwenna says not to be sorry for her, she can't abide it.",
    "Nala says then she's only sorry she frightened her; Morwenna's shoulders ease.",
    "Morwenna holds a towel out behind her without looking, and Nala takes it.",
    "At dusk Morwenna lights the lamp and says she'll be up all night wiping salt from the glass.",
    "Nala says she's coming; Morwenna looks at her, and tells her to bring the blanket.",
    "The lantern room in the gale: the tower hums and shudders, the glass streams with rain and salt.",
    "Every half hour they go round with cloths, wiping the salt off so the beam goes out clear.",
    "Far out past the Teeth a boat's light shows once; Morwenna watches it until it is safe past.",
    "Between rounds they sit on the iron floor against the lamp's warm base, one blanket over both.",
    "Their shoulders press together under the blanket, and neither moves away.",
    "Morwenna says gales frightened her as a girl, and her mother brought her up here to sit them out.",
    "Nala asks what her mother did; Morwenna says she sang.",
    "After a long while, unasked, Morwenna sings the boat song low, all the way through.",
    "Nala listens with her eyes shut, the tower shaking, Morwenna's voice warm beside her ear.",
    "Nala's head drops onto Morwenna's shoulder, and Morwenna lets it lie there.",
    "Morwenna goes on singing, the next song and the next, and the beam goes round over them.",
  ],
  issues: [
    '"You stand at the cottage window" - Morwenna swung every cottage shutter closed that morning',
  ],
  lore: [
    "lore/salt-and-lamplight-morwenna",
    "lore/salt-and-lamplight-nala",
    "lore/salt-and-lamplight-world",
    "place/salt-and-lamplight-morrow-head",
  ],
  characters: [
    "character-player/salt-and-lamplight-nala",
    "character-other/salt-and-lamplight-morwenna",
  ],
  reviewedBy: ["story-reviewer/style", "story-reviewer/continuity"],
  recordedBy: [
    "story-recorder/mechanics",
    "story-recorder/inventory",
    "story-recorder/memory",
    "story-recorder/picture",
  ],
  scenes: [
    "image/image-b056a40293e9e9b4",
    "image/image-70f4d03842a21dba",
    "image/image-094df81a55931be4",
    "image/image-d2092ebdaec6ba83",
    "image/image-19858c9cee80f2d0",
    "image/image-36046ed5ab80536b",
    "image/image-334a7960c0e8ab06",
    "image/image-9f7ee007137889fe",
    "image/image-5359741c52bdf650",
    "image/image-1d60a060b39b22e2",
  ],
  pictured: [
    {
      cover: "image/image-b056a40293e9e9b4",
      coverAfter: "You climb down. Morwenna is already dressed, jumper and boots and braid,",
      character: "character-other/salt-and-lamplight-morwenna",
      outfit: "navy fisherman's jumper, canvas trousers, sea boots",
    },
    {
      cover: "image/image-70f4d03842a21dba",
      coverAfter: "It's barely above her breath. Low, slow, a tune that rises and",
      character: "character-player/salt-and-lamplight-nala",
      outfit: "her mother's brown wool dress",
    },
    {
      cover: "image/image-094df81a55931be4",
      coverAfter: "Then the rain arrives. It comes in sideways off the sea, flung",
      character: "character-other/salt-and-lamplight-morwenna",
      outfit: "navy fisherman's jumper, canvas trousers, sea boots",
    },
    {
      cover: "image/image-f5585bc3542b5cc6",
      coverAfter: "It hits you like a wall falling. The air is solid, a",
      setting: "the Teeth",
    },
    {
      cover: "image/image-19858c9cee80f2d0",
      coverAfter: "You peel off the wet dress. It's heavy as a sodden blanket",
      character: "character-player/salt-and-lamplight-nala",
      outfit: "her mother's brown wool dress",
    },
    {
      cover: "image/image-36046ed5ab80536b",
      coverAfter: "She's still standing with her back to you. Straight as a mast,",
      character: "character-other/salt-and-lamplight-morwenna",
      outfit: "navy fisherman's jumper, canvas trousers, sea boots",
    },
    {
      cover: "image/image-9ec258dd2cd885c4",
      coverAfter: "There's a pause. And then her shoulders ease. They come down a",
      character: "character-player/salt-and-lamplight-nala",
      outfit: "naked",
    },
    {
      cover: "image/image-9f7ee007137889fe",
      coverAfter: "The lantern room in the gale is a different place. The whole",
      character: "character-other/salt-and-lamplight-morwenna",
      outfit: "navy fisherman's jumper, canvas trousers, sea boots",
    },
    {
      cover: "image/image-5359741c52bdf650",
      coverAfter: "Morwenna stands with her hand flat on the glass and watches it.",
      character: "character-other/salt-and-lamplight-morwenna",
      outfit: "navy fisherman's jumper, canvas trousers, sea boots",
    },
    {
      cover: "image/image-1d60a060b39b22e2",
      coverAfter: "Low, very low, almost too low to hear over the storm, but",
      character: "character-player/salt-and-lamplight-nala",
      outfit: "white linen shift under an oatmeal knitted shawl",
    },
  ],
} as const satisfies StoryChapterWritten
