import type { StoryRead } from "../../story-read.page-type.ts"

export const shapeshifterANonHumanLitrpg = {
  id: "01a0657d-ada4-74a6-b60b-8f13554a7bb0",
  pageTypeSlug: "story-read",
  slug: "shapeshifter-a-non-human-litrpg",
  title: "\\nFaceless Hunter",
  worldSlug: "shapeshifter-a-non-human-litrpg",
  source: "royal-road",
  rank: "C",
  externalTags: [
    "LitRPG",
    "Progression",
    "Post Apocalyptic",
    "Villainous Lead",
    "Non-Human Lead",
    "Action",
    "Adventure",
    "Fantasy",
    "Apocalypse",
    "Dungeon Crawler",
    "Local Protagonist",
    "Magic",
    "Male Lead",
    "Modern Knowledge",
    "Monster Evolution",
    "Non-Humanoid Lead",
    "Secret Identity",
    "Strong Lead",
    "Survival",
  ],
  unitSlug: "words",
  externalLink: "https://www.royalroad.com/fiction/123277/shapeshifter-a-non-human-litrpg",
  externalId: "123277",
} as const satisfies StoryRead
