import type { TemperSet } from "akasha/temper/catalog/gear/temper-set/temper-set.page-type.types.ts"

export const blessingOfThePotentates = {
  id: "019e66ec-766f-7a86-8564-a64d14c4d7c4",
  type: "page-type/temper-set",
  slug: "blessing-of-the-potentates",
  title: "Blessing of the Potentates",
  key: "blessing-of-the-potentates",
  esoSetId: 128,
  hashPlace: 66,
  esoItemIds: [
    87747, 87748, 87749, 87750, 87751, 87752, 87753, 87754, 87755, 87756, 87757, 87758, 87759,
    87760, 87761,
  ],
  esoEquipTypes: [
    "EQUIP_TYPE_NECK",
    "EQUIP_TYPE_OFF_HAND",
    "EQUIP_TYPE_ONE_HAND",
    "EQUIP_TYPE_RING",
    "EQUIP_TYPE_TWO_HAND",
  ],
  esoWeaponTypes: [
    "WEAPONTYPE_AXE",
    "WEAPONTYPE_BOW",
    "WEAPONTYPE_DAGGER",
    "WEAPONTYPE_FIRE_STAFF",
    "WEAPONTYPE_FROST_STAFF",
    "WEAPONTYPE_HAMMER",
    "WEAPONTYPE_HEALING_STAFF",
    "WEAPONTYPE_LIGHTNING_STAFF",
    "WEAPONTYPE_SHIELD",
    "WEAPONTYPE_SWORD",
    "WEAPONTYPE_TWO_HANDED_AXE",
    "WEAPONTYPE_TWO_HANDED_HAMMER",
    "WEAPONTYPE_TWO_HANDED_SWORD",
  ],
  setWayshrines: [-1, -1, -1],
  setTypeId: 4,
  setProcsAllowedInPvp: true,
  setNameZh: "首席谋士的祝福",
  setNameRu: "Благословение потентатов",
  setNameFr: "La Bénédiction des monarques",
  setNameEs: "Bendición de los potentados",
  setNameDe: "Segen des Potentaten",
  setDropZones: [181, 181, 181, 181, 181, 181],
  setDropMechanics: [4, 36, 18, 35, 7, 21],
  setDlcId: 0,
  itemBrowserSources: ["181:-203"],
  itemBrowserKinds: ["alliance-style", "jewelry"],
  itemBrowserItemId: 87748,
  category: "temper-set-category/pvp",
  valid: ["weapon:*", "jewelry:*"],
  bonuses: "jsonl",
  icons: "jsonl",
} as const satisfies TemperSet
