import type { Exercise } from "../../exercise.page-type.ts"

export const barbellDeadlift = {
  id: "019ebc76-21f5-7a4d-966d-7b84d8abf48a",
  pageTypeSlug: "exercise",
  slug: "barbell-deadlift",
  title: "Barbell Deadlift",
  exerciseCategory: "strength",
  equipment: "barbell",
  exerciseExternalId: "Barbell_Deadlift",
  exerciseExternalLink:
    "https://github.com/yuhonas/free-exercise-db/tree/main/exercises/Barbell_Deadlift",
  force: "pull",
  gripDemand: "high",
  imageEndUrl:
    "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Deadlift/1.jpg",
  imageStartUrl:
    "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Deadlift/0.jpg",
  implementCount: 1,
  isBallistic: false,
  exerciseLastSyncedAt: "2026-07-25",
  laterality: "bilateral",
  exerciseLevel: "intermediate",
  loadFactor: 0.6,
  mechanic: "compound",
  movementPattern: "hinge",
  muscleFocus: "pull",
  primaryMuscles: ["lower-back"],
  scoringMode: "reps",
  secondaryMuscles: [
    "calves",
    "forearms",
    "glutes",
    "hamstrings",
    "lats",
    "middle-back",
    "quadriceps",
    "traps",
  ],
  sfrScore: 2,
  skillCost: "moderate",
  exerciseSource: "free-exercise-db",
  trainsLengthenedRange: false,
  instructions: "txt",
} as const satisfies Exercise
