import type { Domain } from "akasha/domain/domain.page-type.types.ts"

export const temperAddonMenu = {
  id: "01a0c76d-469e-755a-a04c-cba4133720bf",
  type: "page-type/domain",
  slug: "temper-addon-menu",
  definition: "the settings panel other add-ons declare their options to",
  parts: [
    "module/addon-menu-addon-list",
    "module/addon-menu-casts",
    "module/addon-menu-constants",
    "module/addon-menu-dialogs",
    "module/addon-menu-entry-point",
    "module/addon-menu-messages",
    "module/addon-menu-panel-options",
    "module/addon-menu-public-api",
    "module/addon-menu-settings-layout",
    "module/addon-menu-settings-window",
    "module/addon-menu-state",
    "module/addon-menu-types",
    "module/addon-menu-ui-strings",
    "module/addon-menu-util",
    "module/addon-menu-widget-button",
    "module/addon-menu-widget-checkbox",
    "module/addon-menu-widget-colorpicker",
    "module/addon-menu-widget-custom",
    "module/addon-menu-widget-description",
    "module/addon-menu-widget-divider",
    "module/addon-menu-widget-dropdown",
    "module/addon-menu-widget-dropdown-choices",
    "module/addon-menu-widget-dropdown-scroll",
    "module/addon-menu-widget-dropdown-tooltips",
    "module/addon-menu-widget-editbox",
    "module/addon-menu-widget-header",
    "module/addon-menu-widget-iconpicker",
    "module/addon-menu-widget-iconpicker-menu",
    "module/addon-menu-widget-panel",
    "module/addon-menu-widget-slider",
    "module/addon-menu-widget-submenu",
    "module/addon-menu-widget-texture",
    "type-declaration/addon-menu-eso-combobox",
    "type-declaration/addon-menu-eso-controls",
    "type-declaration/addon-menu-eso-window",
    "type-declaration/addon-menu-logger",
    "type-declaration/addon-menu-string-ids",
  ],
  decisions: [
    {
      decisionKind: "decision-kind/departure",
      statement:
        "An add-on declares a panel and its widgets as data rather than building controls.",
    },
    {
      decisionKind: "decision-kind/departure",
      statement: "A widget kind is added by registering a factory under a name.",
    },
    {
      decisionKind: "decision-kind/departure",
      statement: "The settings panel is published as a global the game's add-ons reach.",
    },
    {
      decisionKind: "decision-kind/constraint",
      statement: "A panel is built the first time a player opens that panel rather than at load.",
    },
    {
      decisionKind: "decision-kind/departure",
      statement: "A control reads its value through a getter the declaring add-on supplies.",
    },
  ],
} as const satisfies Domain
