import type { LangTable } from "../craft-lang-lang-table/craft-lang-lang-table.module.code.ts"
import {
  intricate,
  LMB,
  MMB,
  ornate,
  RMB,
} from "../craft-lang-shared/craft-lang-shared.module.code.ts"

export const EN: LangTable = {
  options: {
    showbutton: "Show TemperCrafting button",
    lockbutton: "Lock TemperCrafting button",
    lockelements: "Lock TemperCrafting elements",
    closeonmove: "Close TemperCrafting window on movement",
    useartisan: "Use Artisan (not ready)",
    useflask: "Use Flask (not ready)",
    usequest: "Use Quest",
    usequestTooltip:
      "Displays the current active crafting writ quest when opening a crafting bench",
    usecook: "Use Cook",
    usecookTooltip:
      "Replaces the default user interface of cooking stations with the Craftstore UI",
    userune: "Use Rune",
    useruneTooltip:
      "Replaces the default user interface of enchanting tables with the Craftstore UI",
    displaystyles: "Display itemstyle in tooltips",
    markitems: "Mark needed items",
    showsymbols: `Show ${intricate}/${ornate}-symbols`,
    marksetitems: "Mark set-items for research",
    showstock: "Show item stock in tooltip",
    stacksplit: "Preselect stack-split",
    markduplicates: "Mark duplicates for research",
    displayrunelevel: "Display rune level in tooltips",
    displaymm: "Show Master Merchant in tooltips",
    displayttc: "Show Tamriel Trade Centre in tooltips",
    timeralarm: "Show timer alarm",
    mountalarm: "Show mount alarm",
    researchalarm: "Show research alarm",
    playrunevoice: "Play enchanting rune voices",
    advancedcolorgrid: "Advanced color coded grid",
    lockprotection: "Enable lock protection",
    inspirationgain: "Show inspiration gained",
    sortsets: "Sort sets",
    sortstyles: "Sort styles",
    bulkcraftlimit: "Bulk craft limit",
    overviewstyle: "Character overview style",
    userunecreation: "Use Rune Creation",
    userunecreationTooltip:
      "Replaces the default user interface for rune crafting with the Craftstore UI",
    useruneextraction: "Use Rune Extraction",
    useruneextractionTooltip:
      "Replaces the default user interface for rune extraction with the Craftstore UI",
    userunerecipe: "Use Rune Furniture",
    userunerecipeTooltip:
      "Replaces the default user interface for furniture blueprint crafting at enchanting tables with the Craftstore UI",
    displayunknown: "Display unknown in tooltips",
    displayknown: "Display known in tooltips",
    displaycount: "Display known/unknown counts in tooltips",
  },
  suboptions: {
    sortstyles: ["Alphabetically", "Motif #", "Internal #"],
    sortsets: ["Alphabetically", "Traits"],
    alarms: ["Announce", "Chat", "Both", "Off"],
    overviewstyle: ["Complete", "Slim", "Minimal"],
  },
  TT: [
    `|cFFFFFF<<C:1>>|r\n${LMB} Select/deselect research\n\n|t20:20:<<2>>|t |cFFFFFFEntire <<C:3>>|r\n${RMB} Select/deselect research`,
    `|cE8DFAF${LMB} Craft x <<1>>|r`,
    `|cE8DFAF${RMB} Craft x <<1>>|r`,
    `|cE8DFAF${MMB} Mark as favorite |r|t16:16:esoui/art/characterwindow/equipmentbonusicon_full.dds|t`,
    `|cE8DFAF${LMB} Select|r`,
    `|cE8DFAF${RMB} Link in chat|r`,
    `|cE8DFAF${MMB} Mark ingredients|r`,
    `|cE8DFAF${LMB} Refine glyph|r`,
    `|cE8DFAF${LMB} Refine all non-crafted glyphs\n${RMB} Refine all available glyphs|r`,
    `|cE8DFAF${LMB} Select this character\n${RMB} Set this character as main character\n${MMB} Remove this character.`,
    "Favorites",
    "Rune-Mode-Crafting",
    "Tracks known styles",
    "Tracks known recipes",
    "Show TemperCrafting",
    "Available fence transactions and today's income",
    "Mage Guild - Eyevea - use portal in the nearest Mage Guild building",
    "Fighters Guild - The Earth Forge - use portal in the nearest Fighters Guild building",
    "Click to travel to the nearest wayshrine of the set-crafting-station",
    "|cFFFFFFMount Skills|r\nCapacity, Stamina\nand Speed",
    ["Any Water", "Foul Water", "River", "Lake", "Ocean"],
    "Refine all glyphs",
    "Writ",
    "Furniture",
    "Tracks known traits",
    `|cE8DFAF${LMB} Furniture Preview|r`,
    `|cE8DFAF${RMB} Furniture Preview|r`,
    `|cE8DFAF${RMB} Refine stack|r`,
    "|cFFFFFFSkill Points|r\nUnspent/Total Earned",
    "|cFFFFFFSP|r ",
    "|cFFFFFFSkyshards|r\nCollected/Total",
    "Tracks known blueprints",
    `|cE8DFAF${MMB} Research|r`,
    `|cE8DFAF${LMB} Track|r`,
    "Fillet",
    "TemperCrafting Styles",
    "TemperCrafting Runes",
    "TemperCrafting Provisioning",
    "TemperCrafting Furnishings",
  ],
  nobagspace: "|cFF0000Not enough bagspace!|r",
  noSlot: "|cFF0000No free research slot or item inaccessible!|r",
  noItemPreview: "|cFF0000ItemPreview required!|r",
  noFurnitureData: "|cFF0000ItemPreview lacks this item.|r",
  blueprintSearchLimit: "|cFF0000Narrow your search to show all results.|r",
  removeCurrentCharacter: "|cFF0000Cannot remove current character.|r",
  searchfor: "Search for: ",
  finished: "finished",
  level: "Level",
  rank: "Rank",
  bank: "Bank",
  housebank: "House Bank ",
  guildbank: "Guildbank",
  craftbag: "Craft Bag",
  chars: "Character-Overview",
  set: "Choose a set...",
  unknown: "unknown",
  knownStyles: "Known styles",
  unknownStyles: "Unknown styles",
  finishResearch: "<<C:1>> has finished |c00FF00<<C:2>>|r |c00FF88(<<C:3>>)|r research.",
  finishMount: "<<C:1>> has completed their mount training.",
  finish12: "The 12-hour-countdown has expired.",
  finish24: "The 24-hour-countdown has expired.",
  itemsearch: "Looking for: <<C:1>> | <<c:2>> ... Offers?",
  hideStyles: "Hide simple",
  hideCrownStyles: "Hide crown",
  hideKnown: "Hide known",
  hideUnknown: "Hide unknown",
  unselectedWayshrine: "|cFF0000Choose a craftable set.|r",
  unknownWayshrine: "|cFF0000Cannot travel to undiscovered wayshrine.|r",
  previewType: ["Heavy", "Medium", "Light + Robe", "Light + Jack"],
  provisioningWritOffset: 7,
  styleNames: {},
  reload: "Requires reload",
}
