value: ENC[AES256_GCM,data:hKos/I22Rrv4yrU=,iv:IAA8tDRLhWeC0zZpZmm2S+vjS2+8UxqP22FSRixccH8=,tag:VD9H6NOX/HkqdQzUJXS/CQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtQXF6eFg5eHh3SHpZVHY5
            MUtYc0NWQmZRZmMvVlFCUGZCdXk5MzdEdkFJCmlOdzhmQnFvRi8zOFRKVmpUM3lo
            YmNaUDBnenlVQjhma1BhK1psaHdRT0UKLS0tIEx2SmdndytCa2xBZnFib3pTQmJv
            eEFHVEliMEJRb2MvYXRUMEhSNVFaVVkKd+3DBcw/bvfgQwnS3GptvAlE88vMLFVU
            vjxeNLLXEInrQTyO+l+zDF3MPxAZfCcwQwS6MOqT6DwmrQY3LW8hUg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
    lastmodified: "2026-09-06T12:06:03Z"
    mac: ENC[AES256_GCM,data:0aN5s0268jzdf9wuw6BhKQLl4TYmppfL5zYGxUYvjbXBqwgUfW8jw3JtzXI4IqY+4A62445Qw4IgnH8tr3xvBzMqG8J00FPYdBPfj3QLalpRhCcQe6DRjf/l+LHTFkdx4m33aDAPO9OMo7Gh4QqQezqUmnVMEaHc9lE3ojpHQcY=,iv:JqVQElVfvzIB76ylHv18XeUxwKjmWvC1rr8pj1+D18o=,tag:LGOeiaksCVyHlfUqOgNXVg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
