value: ENC[AES256_GCM,data:0jL2cBx4mYb5LGFBhORQKiUPALWpVTUqirSf4givZpSXjdk=,iv:wcCKEqSHb+DzBOfBM9jNpakG1dYJa6xbyZKyfDwszi4=,tag:Qto8cYZQn0qLWWGYUzxgMA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArdzFJWTZvdE5DUEwrdGxs
            RzU2ZEZaM2txeStsa3RkSUh6VHh3TDlLRmpJCmVYVi9IdE81YVowaHB3Tms4RU1t
            S3YydTRUcmxISVRWdHduZTlENTN5MDAKLS0tIG1HRFlpTlN2SEZCc0o3QlA2S3hD
            d0daa29hb3h2aUFYUDArU2J5UVhaQkEKro9643zTBnarF7ggIDLC9DkI7Mv0iclo
            LdCLD5lINcN1PMYBrHw9blhrKLfyWkfGWepn2NuLUnzwp9UdIhY9mg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
    lastmodified: "2026-09-19T18:31:44Z"
    mac: ENC[AES256_GCM,data:lLGJZ7yAho9tYwCluFYHMVznoNjLXJNULjiUwNyhUOIKwVT2mtqh/e2/9EmawC3m/H9xaIRcJTALTQIXWF31WbYCWUSkRPomsTKkhL/kk17g7xeIH0pAOYUCfuVnZUNM1zdnYhK7iLlIHTKIiJP6AGNn4EIeYGykChP5UIHAog4=,iv:qUGybds3MDJFru+xvtV1qR18k4QYzbm3Br3AYpCyhgk=,tag:HfnlyrWv9DU84wYuCaDRkg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
