value: ENC[AES256_GCM,data:+A29qY49aRdZCdOGnpC1qtE/Dw==,iv:i48SoOQV6oAEreFeybHeov/9IkEmyNWlM4BvoTZgiMY=,tag:GOxKI9OR/ixglzZvTe8EPQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByWGpuUjZ1a2hQalhaaGdR
            QUxpNVZoUDNXN0UrTWR2NFViWitiY3NWVFg4Cmo3Rm9uSnpIZ3I3bkd1ZXZ5djA5
            RkdObkU5MUdZUmRKUGhWR2M1RHNEdmcKLS0tIEYyUlVqaHNDUjFQeTNuNGczMEF0
            TEIxdlNZUGp6NzBkVmhVdFJtVHlFMmMKMlfQA7QLB90e2+DD0KWgHgGl9pmjp1SM
            y0N7/0eT3lcut3KjuThZHVc4V1NAYsDzoOgAj9XTc+ZujqH+5aDD8Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
    lastmodified: "2026-09-19T17:45:45Z"
    mac: ENC[AES256_GCM,data:43KHk5D9hOrbX46ztEo1rAFy66D9sQjOaJ9V4Tm02dus/YeeuWozT/qu25rr1bxuRjjBzO8ORcLCYZYXJcgvrqL+4XTehvgUeevF/9Uj7+1hHL5vB/w3vcrrAxaxNvfZtHhJHMpFVOLsjde3FgZ3HoqggtE/2IaO/SQdDs3jmLo=,iv:IOAuMR2ZiNTGxT3rm/FaK+NTrQLKTasP2zHATUlBlvs=,tag:KSAz4J8dqbmfxtxLBuHLuA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
