value: ENC[AES256_GCM,data:ca9OwQ9uX9odbitc3QULQgK1haN/r9W1WGfvtHTiHVsGgGzvgSe2ydjqjuUB/vvU1VtTk+fvOA0n1itcd7uZ+Q==,iv:eyYyghYU/M4h7mPjbJxajMSYyCZct2SKsR3DjCPfeGQ=,tag:OgzV/GbtDCk8sbqYvxqFwA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkd05JaTA2M05RanZHTDFU
            dUF3bTdxbWN0d1lRUUV1elZtV0NqRWJHSmdZCmJUSWZtN1JFaC9LQU9mYmZGUlBC
            OHRLdVlqNlI3anlTWEppNHFTdXlxdFUKLS0tIHRiL1M4UDhMdXAvNDJ3ZmJsQ09t
            VzkrbjhWcWp1R1BLTSt3Z2RScTR3dTAKK0v/ccq9IsOPOkgbDOtO36V/GtSR6p8b
            8YpqtQGMfHVDp+iR9iJ6ZNjEEOZysLbxOd7lTXPHQFbAO8Zqxax8Eg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
    lastmodified: "2026-09-19T19:38:50Z"
    mac: ENC[AES256_GCM,data:lzmjTt9pAQJJqDRpkdTqwYQcwnnKmkh8+rrWerdbWYT7gXLPPX7fviAZIm2lW7E2h1D9HaOAUC5z/6oWnPCuCPLMuHkm9AECILtcRmVRP9R1TIJe/uXA6GFWS+2T54Hnr0mSp9lZbdBwy4s4+QPjLzs92cdBgmpgV7P1apKfE6c=,iv:awoU43Q1jTlXZrTT+TD5qpYFrc/+0PrWmDS5DG1WX4I=,tag:VVfrV0YJldUz+zk9IX9vqQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
