value: ENC[AES256_GCM,data:kMpZDMMvOYt140rROA4xp9i015wTkrWjjI6j9jede8Nly4CUGyanNWb1sdeN0XHbzyTa0OFuCdqIQk0appUiybMreeAwOjFc,iv:qK81ACm8Bxz1+2//8t9ImzdCj5+TcjpceufxmcoZHPE=,tag:aSfB2f23uAcuwqQoD6aIhg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxWngrVXorS2RId291bklI
            eWtVT3lJL1FGTDROWDBUTDEwS3dnaFdQS2lnCnY2VFJOWC9qTW11REFmcUpoRUtB
            VnBvK3B3bVRrYzFCTDE0dGhYbmtsMkkKLS0tIDU1MnZaOWpmN2FUbVBqVVp0bERC
            QTFnZzhLQWhLUWljZUVUY0lyK2JDTDQKurMrC8oKHgpoxYH4wJssaIGOjOqxphZ8
            zge9NhSx+O8yttPT3EIuInjUBRn9IQZBO7yh4WzhglWOWh9/7bsW+A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
    lastmodified: "2026-09-19T18:31:40Z"
    mac: ENC[AES256_GCM,data:xjFkYbjLPoQWRCzBwQeUdO8/GtJpmNP0N17sbeATetSm6GEuN6e6nTN660OPx8W1hYbeFKZcyYhyzSUVtnRk2b3KU380p1qp6R1Tg/bn+YLh4oTwNSs6AKNzL+4J085gOuyXXtPpZ8fAtMea+9I4y2yK4HHnmUKAXmmOx0bVqIk=,iv:DPBvshYQj89Ya9oeP3DMk1eb7ScMf24lD1rMDQF4dAQ=,tag:iXHXbW0IRkSacG1bFX247A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
