value: ENC[AES256_GCM,data:N3ll53z5NAor0M9pwv3muglrwkNh+ldv7xlbgEIuvtpUg9lHdfg=,iv:EZo7/d/LMkluRUPBaPb05/1K7vrNLnlgLhu58Qag4cs=,tag:Y3iP8G1P5LGLdD+W8ACLpw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDKzlzSXNHcEJ2Y2FyYnpT
            anIxejYwbm9oclJwY280R2N3YzF5MU50VUF3CkxmTjVUbHo1VWNsNThwZFZaZThK
            QWZvZXlTQXJBV2J2QXd6Y1RwN3E3bmMKLS0tIGk3RXlpaFJEMU9Ea0xreWxBZ2RB
            SzRLZDg3U1hMczhFQmFnWFBIa0p6bTgKbQs1/mHQ6VAJ9rAJ/agmlMay88cPVjzC
            ap4M2pt5RsEtVKhIOV99FoSjt81famwYJMjW6xCys5KU7ObdCASoZQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
    lastmodified: "2026-09-19T17:45:51Z"
    mac: ENC[AES256_GCM,data:scvEpa+y1S5zyPCZR/dYYz+Jr4RwcPgOvq4bV6YLH9uB7qkfOaWSvO7sJuboClvmPU3onzNFPdCkXH/ZhdYCYMu5/V8K1AvqfqQoAfXwh1QNlvc7XhOQ5KBVwACujvHvfTM+abFEzKqSj0JiPCtomVADnN5hb3RuZCwrI7qfgtM=,iv:efbKyqD2tL4E5LrokGRY5g1OmfcbzXX619H8XvnV5aw=,tag:j/T1LmNCzpS+XaslXLf6tg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
