value: ENC[AES256_GCM,data:mUbI5huNl3x+3T84sSSXar96lWNnZmPdw9h5rDQiUr84MmbjARBRbJ2ivQj4Kf5SdtEqzMWw1IXu0u9MOEZbFQ==,iv:pxhCgk4uI44wBpP75jTpb5a1hLiXscl9B/SvxPE2PzQ=,tag:BlAa37fl3uwp3aCIKtxPdQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzZ2JoTWxWd25lRmMwWGNh
            Q2FBR2s1Q242alhFY0NWQ3BPTzE5SlBvZTFBCm91UXRobksyRG0zK3VQUnl2cGxr
            N2dlQytadG1Ua1dvK1pJdUlNK0YzUUEKLS0tIGtkVkcxdXBmZlo2ZFEvY0oxSHFl
            K3VNZDRQR3hSY24yMk5GcjNUV0E3cUUKnRlFhc5xvkumh4Gxhe01uwjuhYzupwJu
            c+WsV9KmZRBXSxuptlvsCcMzswZC3HH96z6tdcPXBPuRe2QPppXxeA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
    lastmodified: "2026-09-21T14:17:31Z"
    mac: ENC[AES256_GCM,data:F2SHmvL7DkPMGRklDGFDvVSmF5cUZZPyMMGjDBt7dJawTw7SEVxwhd/kGCQ/6BJvQavRaCL9ylOpggD4ZYBMT8cRr32dIJqtGk50OWBy2d5eeg3BikzEMMMjIuXbX0kyE4SXN7PiH4UVlaUR5gAedFqyDNpHI8wTowz4LoLpIQs=,iv:o6xuV21HKGKWIm+wC4UgrbXSXZdCtZuDnTa/DLQtqaM=,tag:qcS0KDR9i0jNlIVk0Sx8cQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
