value: ENC[AES256_GCM,data:KX9zaZ643WvsCiUqH6iE9qb6S+sA2FxYlMnLv3In+XDDTqZ0S9H3ASCV8gLshoLdKSXnu+Ta/u+81Chb0+R1MEEhwFrNXktmLPYmChmktk87mcj/mSXrcstfnMsDSVRcvlS+VjDCCJ5g+9zKa821kcM6Qke/ICA=,iv:P8PZC3bikw/Q5wnF5LUy3kqP3DZHLvNxMUpReGYMWlw=,tag:huNmlA0UQ5NNCWzvue5lPQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3OGV3V0lYMmYxSExnREdT
            ZXBoTlp4Q1VvM2Q1SGhpV0laSFh4enpZdEdZCmZMeGZTdkc0a1l5YUNwSU1mWUVn
            dlFGQUlOTVZmUHZocll5WjZoZG1YSzgKLS0tIFRjTEFFVy8vaGlGOG04QStiT21h
            L1VNUUhNcU1ObnhVMWhraThSSkhNeFkK8ZQ7nYNGYiXD2FcX3XPq0iBMVXoAIBYg
            IeHSxtyZwNLAt1SyAdwfyOpRqUQTkrkI+Kl1lFpaxqCTcyaqE3eGOg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
    lastmodified: "2026-09-19T19:54:12Z"
    mac: ENC[AES256_GCM,data:q8XKG+juBdT8dzIR/zU/gQFMqDGcJCOOxXFDq2DkmzgAGDIcw/Fd+rWtYNYc4/Xf6C4kyho1DJxrNuo8rMO8DOYS1DgAjenfSeoE/LuuYuGT/+NiCY+Cz7wT4+8/sUF2NwaQ3WPwb4wAowLm9JWAWspMI9fNewfzlJC86oHXfFo=,iv:x2a31JPemEoegzpJyySlk29c6VDfw5qzYybI3RynMqc=,tag:J36mfLivnGAmaibyTaYH7w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
