value: ENC[AES256_GCM,data:QMYURE42nMC994qt/KlRjCkA8YHFtKzJeTAslX4Kda7Z2JROGsqC2q0VvmZCQmPuQ7kQ3u5iuexTB4qgStiq1A==,iv:YH4i49aPUoItS0nF1ecofqFET5ChzklicPoDdWE2N+Q=,tag:CtAuKKxaUpx1ZAQOPoTeZQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzeHlXTE9DNytHNm5nOERw
            b0E1ZWI5RGhqK1J0cXdCbUNzZjlrd2o2ZlNnCkpkOVpIb3VRUUp2anZ5Um8xcWx1
            VUYvMXNVWG9wYWNMbEQveG5DWUYvcWMKLS0tIGZ2R3JGSVhnVHFEeERBL2JsQ1pm
            TDF0SE10V2V2TlVTZlordXdXODlCRXcKdIYz++O79tG0Hck+WeEuFlSG9LnyxvBL
            hNED9eg5VYkZ3dWejNngaj+/58Tc6KLWsLZ00CHt0qA8NYDNTcYvgw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
    lastmodified: "2026-09-19T19:42:59Z"
    mac: ENC[AES256_GCM,data:QOztwXwLkZRc1t8e39Z9+mMHkAXEYskUjcJoL0oOr+YKwLi3Hq04MQNu1/3sn8fEvDuywZOLZMt3iMpbo+T+InLJB5iE6Ue8+LztjQBR4NdelhKXQJ7O8OwcUmDmfhk/AJO7xzacbvKBPIO/4XDva8h1JnW26s4DsaOxchZdDXQ=,iv:1jfov4M6K9YAt/R8Q1TF7eBoiz/Q40W84+OGnyeyOCo=,tag:IPjAyKXPo9fyTTDIxvts3A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
