value: ENC[AES256_GCM,data:/VTjXHkSLzcgd9EVk2MFp9hrXd3GHUHoqsoFqpi8Lz1cxp7TVZaPvQlRWdAF63Wv3PgVEprtoO1qed/Q0Zd1DA==,iv:TNble++nZZmorrWeoH/Sjc1jlIQPLUScGzwk2uEyutY=,tag:yXEYoWHnDIp3zSrudSAVLQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByMlRTZHBmekFsdmlCSG53
            WGZRaHZseWhVTisxVXlGMkpLYnh1UXNOT2hZCjhzZm5CRnRvcDBmaXBUbHcrN25D
            am5NMW9TcWVhUndHNVkvZEdJeFBsNk0KLS0tIGVodWRkWjZ3SUVpNFhLOE9QL0ox
            SkxsYmg2STJtZ0VSeURJZHhXYVZhTFUK+VcVFhd9lPnJa9saKGJSl0bv/SIK3u5A
            ipVtN3ySC4zpl7imW6pHUFhjF9CgGpJ1dg36F+MUBD+PN+FC5wSb9Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
    lastmodified: "2026-09-19T19:43:03Z"
    mac: ENC[AES256_GCM,data:zrVLh1gotCXn1wbMTR8kVl3Wg02Zw+1z4cwfobCeBeH7jwf/Raa7fvaICVjAITUFBQVHBIL0HsVONVe6CVhrytIxcgtx53zzrGp+EDoMMID5gVnDZ/8mYzzDRpyqcePAAMi6i7iZXoaS8BWeLr0RhWAfqWK59mU0wcLyKj+GTdg=,iv:D5BTYHXCtfQo602pIy7fnN5obwMba/558ffppNS8rZs=,tag:Z2xoO9FitFO1f2FndXMBlQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
