value: ENC[AES256_GCM,data:LoU9fZalx7hhz7eRd/jQlcUMiJrh/QOWgPH76wveFdc62WLltFMcUlpHdnTcB8aO,iv:qZZeDDRJJ6Oaywv0+fbkx7suLVfcL4pmfTjL2uUG/dE=,tag:gMtsxyL4p9szjj9jqN+dJQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZYzdHL2dqWlVVdVpwM0c5
            UGt3Z1kvV3p4aTBRRVd4M1J3UUFmcXlwc1FvCjRaTEFZdFFnTmNYaDA5eEJONGNt
            UnRSK3hha2tMRGIrN05Qa3pSZW12eFEKLS0tIGpxOERIUnI4VXU2S2YrbFJ1ZHJP
            SzNQTnZRWmxnb2M5eTlrdE5HVTFuZXcKIfQKoPx0J4aJs6xNF4dR7gxfNYTDUIqR
            9Nq3YxRoV2djQGHHuZSreVU0kB/sVr9FuC/RB8wslslCIJpukJ+xag==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
    lastmodified: "2026-09-06T12:00:53Z"
    mac: ENC[AES256_GCM,data:hQ6mXQNANipufg8ApqKoq0cahE2qRhjTkOIqxlt7Y9gLVZokkOW+raG56e1vMEVCYcGeZkJ0WIDV3MTnBZiQsnLEze54Xd7ygjw0n9HevtRYnckN1/aY6nV9GlaKqE6F5CtnS8Z3R6K9/5W+tUkiVBlp1Yn50QNCS3A55hfEU2I=,iv:Id29Z56r+8XCCiN959IMknmT0S6JbDL0RLoO7KhbAEE=,tag:kCvnHFRjUjC7yzk/5nudOQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
