value: ENC[AES256_GCM,data:0CqwQwyYSFklCz+jmhw4KTHrGDCacqb9IG6TD98Tka2eYxPohDeMlixpsBSRUftqoU15YijULdyvE+IGC3K0DQ==,iv:xeOuGNkP8jzdD+XgXuEVSuUG/Kju0MWMm4pnPGPVecg=,tag:VrtgMPRfzgOqjf9MmCfm+A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzVU1KZFpOcWNCUW11V01l
            L2I2QVJLcTY2dTllYTV0OXdZSG1jZ21mVHdFCkQ0Vm1IME1oeUxqY2Z1Tnl6Zm54
            UmdsWGwzRUpUc2RNWkhNSzFnZmhBbm8KLS0tIEtXcm5JQ2RPQ2FETWlNckorbmpx
            eHFNQW5ySDl1Wkg1dFczVCtEZVFxSUEK2H24i2UoQEZyTbNh/HzOrkFWYpprLRaw
            ztYd9OyK6PmytwrOkxVPkD1veIlizFOe26Gkj89wWCeEoHRSUrUYag==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
    lastmodified: "2026-09-21T13:43:53Z"
    mac: ENC[AES256_GCM,data:wFagJ8Z5FKV+XhQtakne4rEINF0wJAoTpIgZD4WgtdkzEasepbY53mzfdbJAkrkoXI0YOaEdv7XYKbznvuG3DOhZIeNRyVkylGxaB7xQLB/S6IzjGR4Y9kJrNpPoH/TAxbYYLvMo8JbkYDasoDxP1y9JfuhZoplHOJtaw9+nQdU=,iv:q6rF/Bl9nzf+7r/5nxE7/R9FWA3ufP+linp+3MqOA+E=,tag:zZWqToJAWYG9Rg6zjmQlgQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
