value: ENC[AES256_GCM,data:B6GPoSmPWhlw8StBbuq4dRvDoaDbXvcerXf7kgrSBOsPk65+RnBPJjhwAWm33Ml4WD5ZcJpRMi1UjHXtYaBSKvkpxR1WtHIoRyRaTikwXNk0YT8RSRl91G/FDUN7JAUY/SyB12ZNW30CR5vGAfkIzt9AWVThRGumBj8KdWIz/cJIIaIoVNIn,iv:juf97mbPHnOqqaEBceN09Pytu4YXT8HRTtJw9vgWDwA=,tag:EHwxg++p9uewChTeOr0kOQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1L3A2Y0Y5TEs0VXdwVTd3
            T1c5UXRNOG95c2pGRG51ZFZHYWJNQWhtYWxZCnpsMUpQTlNNWDVHYURtcW5tcE55
            YVc0ZS9lZVBIQ2tIRWlzUndCUUFwa2MKLS0tIGRRZ2lZT2JwOUkrZVJ2MTZWd1ZI
            TUk3NTNBR0RlekNnVDFBU0hLTjNpUTAKNDhd57u12E53KPlvnb29F3+A2qQBCAEc
            ZXa3hjeDHhYk9PEY3W1ZlxwLD9XoxulME5uiCTEiK6Ls5yzgBlP1ew==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
    lastmodified: "2026-09-06T12:39:07Z"
    mac: ENC[AES256_GCM,data:h0gJeAxRwkOefz2xo7zrMIuPoTz01RJCOWU8j7mgDRgKKJqX3JNNkE4Lx9RqHlHHrTJg2PHFRDupEz9KKSnQbsdvmOKEmxNqtJGOsFpBqCMf25aRqjhmbw8GKoflmPjn9ugv+9jknQz37Le2wYZirXIfICJ1sxtr/7cChez2ApE=,iv:PU8FQ4s3DUj5M0SX/hJqBiJPfXbLmD4dCejkPLS3vzI=,tag:N4VhIbjIsDnO1yCsG/AH2Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
