value: ENC[AES256_GCM,data:RE6FzK5VfKqd8nuexUx+0xU67gxh+UmURkC8Gj78,iv:WByY56OA4FgNucwBkerE6Lryhg1z74LxozIIrdXGbHs=,tag:QmerAqkHd+C/udjP59R6Kw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjQWNQQ2FMNjJjeWdMSHlJ
            Y2xKTVZ6ZGgwbE9uRElqanpFMERkTWRxVURVCmpmbWpQNW9uSm0wOXVPNUQ0L2pW
            N25WZ1B0UWhIaXphTUdCcmdkekhzWjAKLS0tIG5Dbi9nWTllK1JDeHU3U0dCZ25R
            VVY4Z1o1aWZoR3NUWFJPdHgzRi8rQ1kKz6KvNajj0Y0qYQaqCluJPQtDTFyL29Hd
            Z+8vcf9GTWYfNqKPrZ5VHUQruLYmF7rPJSi0Gan+NizRbT77PLHV3Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
    lastmodified: "2026-09-06T12:39:52Z"
    mac: ENC[AES256_GCM,data:v5/Bg8+3Cxrtd1P+4tU3WEbEI3+U4GW0xv7nX2BrbRRlSWHo2HcDtQDw1YLCAM9KZid1BgWX89HK2HShvsTVek59MS/apwzqYzLMd1JYER0Dh9lUtRGz/9W/UTyxSWQ5Q1P/c2WYQ2O1FNvsl8y1KL5scFQuR89rcZ7HJuWeYGY=,iv:FwFOXY1QUve5dVcCCzWhGv9fhiSe0ky+YJQJ6lM0fRg=,tag:jfBvnSbEShM4o5uHOGO1yA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
