value: ENC[AES256_GCM,data:zJmzS9TOGCdKe9cFRgdwvCZXiUAJL+WmYN5A4Q0AitetTSF1lLulrEtGzypoYRI+aVod0xvdxkRRdROGY59VPdHg6Xe7c2S3PXBTYU3ve42Fm94v5h1FzCJE3oYeX94OaYt+52dTawl06GB6/qZZZ2iwI/n970Nm0bySwzOLA0oztEZKu1NBvbzDC9VKfYJ5ySVciurLIESc9bGe5aXqhAUB0JUCYPhEe+UgwBnXQ/lSOiHCzq71qcwiWvzAIwEpdpAQ9i8Fr81t77UGHbdIvQuVs5EDu3bpf8igBy2h/mAbBsSDaGO9tK3tRuyXTbHqzUIFgxbxcBkr11FQRykjgCNAogl9blEVEDaE1AwdedNmgYUI0rYoC/OLmGn9lywbO0uFkHOo0zXBhEnCabiGYSMWiJ27Z3+yt95IJ0yxafZw0RW7XFK+GajOiI0DmB0bpKPIboNI1RLJ/W/dhm/aD+R7Uf/fCiVoMif+PaCxp0er0wyWCtBM04OoZ5mIH86GcYIsBmkJ1R0ievjLlWjq7tzrPvci/Us084lPvcQy+nhL756ERTXsrxJnEMnJXo/nk5rzyTpkQJQ0AGd+RBUQWuKBt5ClGo9bK+KGSJnoz1uQIgs8mSGRdgy5QUa8PB4Vhw2DQbcOiEXVAAxDhxDaFwpyNqtLTLyjYypSwSwY88UIcKhhZFiijG40Ful0viGe0gE9wYyuB5HiejfguR2R48iHdwq/29WRGJUjBDdnA4AVa9qAiaH97jobKGkxHAeX,iv:9FcWP+np/EkeEFfvyhUpnp4QeLOAkyTHSo6FACQSp18=,tag:Zke9sv4k8nmeRP/G1EWsbQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxNWNUQmNEYjRDYjd1NzVi
            NktpMTNISVYzN01SSmNKcldyVzRFNWZsOWtzCkFrQnR6Z1Zxa0lCdXRuamdYa3JC
            aGMyemtwQndTQ1BoRkJUUXVaR0lSU3MKLS0tIDlFL1Q2WGZ1em14YlJDZVUxYXRX
            djdvTVBTVWN2dEpSazRFa0F6RjNKaDQKwtQPwRinkON+NrVDA4N1mobVkcW6rO2k
            fAw7nCNVVdgcKtMnEyNE+r+Lpo2RIUIF1uHyS2LH5U7tLTs4C2MYkg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
    lastmodified: "2026-09-06T12:38:59Z"
    mac: ENC[AES256_GCM,data:ssWozVbfNH65KTZ3c+C8SKcdZTK6td3APnMoHRTsjqrUtOuLRdZCc25icdKHS8m5kk9UgJgbbTjg+G9DqkzefGZtTg6hLpWS2h3VRB+9ynpgXGcDrhYl/+i6S0U5FZtDPZaOdNNwipd4O5SdiwbfSQBmsBx6hA2ko8TMJCenhPs=,iv:rU+TU5YemQN+zTOAXo1XL5n8eePJNqX+u6IDkBAdc0c=,tag:CUAe+S2j2ByGR7R4OJqmsQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
