value: ENC[AES256_GCM,data:aDDORxvmLfY/y69RXhFMfp84SmnnzpsAQFeEcYp0DYG7mKrGudcCPye3EuObuSwOgHAm1kXvxLi2r9Op2DYuABNjmquEADBfrkBZqjyDGkPChFFN+awdBnYTQuHk4ETuz5Oipgw4uG7MKJDkX0yB1c0DvNKqzywiBBIC9Q/dTeiT5kQqRfopMhmSxAp7Z9JlyZn4gkOuQIgBIh2oFJvRTN6iK++UiPJnOw==,iv:49cuhwDiPjCluMZv5hasoLELdpkkpwlQfR/4OTtEegM=,tag:JZIZ82VWzJoFu5h+bP8t3Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPWnpEd21FQjdNQU9WYjA5
            b2Npd002bk5Ga0d0dk9md0RrY1BHbnY4SFFNCkxqWnJyTW5iWGpUR3ZrOEpXSVhX
            WUlPUUxJL2ZHWEg0T1BoZk55Zm0zbzAKLS0tIEF5TGJnVUJ5eFZ6Q2Z2M1lBMkcv
            U3dSdTQ5bUJnK1BkOGhUOWREYVpBcTAKAj+aerdpKy8RMIm1Gm9vcFSomVNLZRMf
            7mRdEyAjXLHGWHwGeFlsVIO62j3LlDvnqPCLUzmAiVXq0Th3rSVtkQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
    lastmodified: "2026-09-06T12:38:45Z"
    mac: ENC[AES256_GCM,data:FIyZbEugrROWfuUhPMpz3hOMRNvdeNiKedhuV/bONc1u2efipk+wf+KBxWBWHO+iuIYUhueMZThnjAEllBhTxOz6DimFGn5X2XoE1T66TE57xISKMZAIdL+d+39XqtglIoGshQJsRj/6ubX2l5OzoiEeC5nor9Ts0CkbRKHMMmU=,iv:mhl4c4c2FWX52YkmqjgynowiVIvd9wiZIrtSCoz5x+Y=,tag:9vIC2PnPWoamuTTDLtHg5w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
