value: ENC[AES256_GCM,data:V4uH1+755HnV5I29/L/uGAFSXdkK5zwhXM9vytc0HW/ou+AOjJkS9w==,iv:TXZiu1VRW8Mxd3YPPKho6PG/oHyZ6wINEQwTbN6GLVQ=,tag:bZOFppTg+TAJdwIM0yp3lQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxZjRpejRsb2g2K2JMQlgz
            RWo0VHZEUVhGbk1hQldnUjhoVFM0Tko2ZmlZCndhNUxXd0xnaWV0S0ZHdCt2NTBB
            aVhrRkxmTWY4K295VFNKeWllVTJKazQKLS0tIHlwaWRSaGo1dW5qRTZmaUtNN2dJ
            S3MrM2x1cjVKckJ0bTVyODVZOUVsRlUKX9L1Fe2dmXIPXAMj7MnPexNtJlzz6Sp+
            FNk8IZFJz+OZHFWK+tKAMk3zyJazSpKK/oDGWkR+tyOCRGz/Q9c+cw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
    lastmodified: "2026-08-28T15:02:38Z"
    mac: ENC[AES256_GCM,data:cLhF6hshA7J76VKLIK/UCfUaTgHrlNJLkIITPIizLLEk78kF5D3EAQfqkZe1RJAMBu/I2qqGxspLMQJIob30EVg0HUKuslVTdlbHnEPLokif6lSiuONYB1VLyv9bz4Ns3EMmWb2A5N6dlM2xxOE92StaDj42nw+9UXP0rNJDj4k=,iv:6jnvPD8okhsYF9EXWcu31KWdVLjPc0sKWRPpqxlZbVg=,tag:50aIRqEMxm9qKsUT6yUqjA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
