value: ENC[AES256_GCM,data:CMX9mxSBBsVnrwO7z4rSKeUU3bc2CSEOuynZJJmhK3gPcDD3rgMpszTi4z2t/jIGC3U0lF9i/HtweYYUzz+2gw==,iv:8t+Dj/Y4ZfV4al0yR6RvGzWm3ZOvdmR6wP6NegEZJp8=,tag:LjfmQaXroDXvDuNxnVVE9g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuUGgrN2dnMXltTHB1ME1t
            ajdkWEs4YXRkQWdHS2Zhai9ad1BqM1lCUkVBCk5hVkcrV2FzdDEwbW0yeHlEWHdy
            eWtvYmd2SlkweDI0Z0VvSGhSZGxobGcKLS0tIENhcDJVdW5Yb0VrdXFoVnhCb3lL
            RlJrcTY1MGk4TU5TRkREVzV2UXd1RmcK3L7Yg0Vi9Np6r9/+KwHSkAn+n3EeWRa3
            7UDD7tZ762mt2tpd3NlB8BnY8JCr9XBPb2hOFCMKtAYtczH9A/zVGA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
    lastmodified: "2026-09-06T13:08:28Z"
    mac: ENC[AES256_GCM,data:2M59chwxFmKCIMkGDiVM0xYYPkyZ45DszWU8TI7Rl5GfDx60XxWS4VM/pV3JtvZJj87bTzC9dy/gtYP888au/LQku7k2l/2ubu4E0sV9D/JDUy2ufhF4unC3FwqWg0L6KoBIGzlaN1Qe2PaadCG/xjEwF1URikhuv3AdI005dP8=,iv:HUds2AhzwsNRw9rRqYX9IXpeKa2vXL0LZHXaPqU54Nw=,tag:n+Vh/gfQTIIlAg+sJwQFvg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
