value: ENC[AES256_GCM,data:QzurQ1/rmBWjWP4wJa5txJt4X7K15EO2Rhm0ZB5ReV4=,iv:SHPeA+aBMBzwrPQqYaGX649Xk23CD94T3Q6MscYdkxY=,tag:zkfMVXoJo8nqbeglnSUpDw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzK3pvc2VrRk56aW9lTjls
            QnQ0M3BTZGQ5NXZ5N0ZIWEdZdjVOODV5aGo0Cnc1bnNnYkwrTHRRam5mOWtPcDhO
            eGg4d2lZWnlnamZtQmVGYTdrN0ZOeW8KLS0tIFBiREU3WEZZRDhVbE02Z3VPSGtv
            TUNIdWNZTENSNEI3QktwTk5ubEZVYU0K3zI91vNPDyT9FzcT6mod52IjqqnTILnq
            aox5USm6DG7p8WI5ePnhVfwrzESsd36wAguNMyku/goa/TxYbrShOA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
    lastmodified: "2026-09-06T12:06:06Z"
    mac: ENC[AES256_GCM,data:TqXW4X8fb4589CgVBdGwDEYn0RBimGRbD3BV2uXFJoFhkURGpKwANqSZX07g/kZTIVrXGgYl92FRj4PXI4ONKHIDrwsGzQ7gQ/KwA4EKO32MJ+QAnQNAfEz7gBwsws695r8GWndNV7z0iBfXr+T44ZBoYy8Kmxtcp8Dwhk6CwnU=,iv:tIneZR3bJDNSVCuN5RLGQ97CDDwShkFADfp6jvh2Gro=,tag:NyquViUT4AWlsmwCxTVKfQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
