value: ENC[AES256_GCM,data:1RintWiH44gpDV0vJPRM27Ee4i7iphEHInPREoe482q/2yIbwGo=,iv:KZ7s5xfTAQSVfJ/W581jfOiEOY9ti0t/4YoGpjLOybU=,tag:a7gIXbdOgQU1ePC1JOM1hQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUaVhGZlZzSG9qci84K2s5
            MktTTFZNMXo4Vk90Vm9Rd0dHMkp0SVI3V2hJCnJDcmZxWVRkOEUzK1NIcWFaUloz
            TFd3Y2Y4akpPRWhNSEI4Qy9UcFhLOUUKLS0tIDdhRk1kSk4vbEJWN0VXRnNVZ01h
            RlFDc0w1Qms2cGlBT2lacm9xUjRFS0kKqyLo+V5VnKIgsNx73iXlKf29tkWIPzMy
            ZEXGTtqPTtlNpuooNAaghZblOlwvUuAb2fDiWhTquJ0Yljs1drNpjQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
    lastmodified: "2026-09-19T17:46:12Z"
    mac: ENC[AES256_GCM,data:l6KWR8POpIpjOExfz4sPwsD1vhPi4cNnwkPUAEbdTbcmS7Mz7CxX2I64XEdoCj6QahGG0fgrNmcZGcHv6OlxJnhpvl5wkiZJqWPAGYriep357wCqPBzL/V+3Vn6STL9SWCrUcy7XVf6HrnKi/yaJLDzeMy0f5VuHJ8mF/iXPedE=,iv:4NDKXX2kDqJx8JcwIUdBmv0dudK9xEPQXXUMgYof3pM=,tag:HDwgvSfFC2DADj8F0ChOFQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
