value: ENC[AES256_GCM,data:mlL7CJyAIH+if9FwVYAAK1gMCQ==,iv:Oc0HFr1jsTXcqfarL2YQkY4/Us8snc3g+oi4VOaBuWQ=,tag:VPOfhfda+ejaFerQ4QZYbQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqY2NsSVpFTmJTanJ2OXAr
            SUdoSVFtK1BrZmtyazlYQllXT1h6dFlHNFNzCkVURTljdTV5aUxqZ0piNktzYSt6
            ZWFoMWpGMU93QnNTQ09LU1VsUlhNaEkKLS0tIFRBdnJldkxOR2FxZkwyOEVBaG9v
            aU5WMkpWWVplWkozT2xKdjViK2V3cDQKxZ1iE9M3vTxpgyKFKtBHCau4D6mvATjA
            FdEaVYJFE9aSinudKYFbs7ULYQKHegyc0sx6uMWc1FOSOk5UbA6aEw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
    lastmodified: "2026-09-19T17:46:06Z"
    mac: ENC[AES256_GCM,data:bd9/St5Xmxk1Jel8+ULUlgo6lkefw23QREMzfDVOCOW+6FY69OfMzlk9PIP7COJvQJQzrDLqOyaNc1VW/WM7/Kns2QpIN4GhPDQuoYU4J+4axPM4c9JO6vTBUqbv9OZme5pqFs+E6IfCu48Cn7GJfF0muC+5naZ4g1FEEv/yYQ8=,iv:93uxIQfDdlDwdk9+xmeJHOoD733/JKXknByoItTC/PY=,tag:6o4upKWdpCyQ6QU6FIvFpQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
