value: ENC[AES256_GCM,data:eJga1QRuQN2yOIwo2dVzrXhUSg/6bhw3eFhGy+bU5jeYR7vn0C4=,iv:+KktNeoJCynLmYJ+SpAHG5/eqaLCLS2VlTO1qu1PAEc=,tag:vJF7HAx1qzFwdk2q7eQhaA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaRVVzOUFZR3AyaTRLYWVv
            d2NaUVBHcTQwTjQ0alpnMmJ2T0FqZWk1d1JRClJDaHBEbWZsb25hZnZPRTVzQkM4
            R014U2F2U0xaTmJCYUtZRTRUdk5XNjQKLS0tIGR4UDV3NkZBb2RHOVozZTFYaDB3
            KzB3TG5iOXhJK0FPNzJYeDNUakI2VzQK6rE+AGhFR0Zko4CROcRm9gcx3B7bRopm
            KqABWufAaUD1NS3wDT1i4N2iVlS86zMJ93pYBDi9QvF58n84j08lzw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
    lastmodified: "2026-09-19T17:46:26Z"
    mac: ENC[AES256_GCM,data:/MPb4oKzmylYbNbQMNZnv2Os8P425Yq/ZJ0fgtlNq453FLcsO4bj6B4LVRticTfdcCfvgoOHcBSw2qqo25Kh8ThZXlOPkwu2BPV9cxmLRsJ1lDMFWRBdUWI4h3EQ3+8SFlht7303XXdnHFlw9J0O8WB13xgIndNvCRjFjbhQNUA=,iv:Av2Y6vpEZjqyVhBJum++VyWQPhbziIKONFL9CzrKRVw=,tag:BLBWQM9VP4sR6UbHRB4Ekw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
