value: ENC[AES256_GCM,data:SqxAD9bdVTSpaIhwq3PARDU6aA==,iv:UDlJoRnq7t46NGuKnQo8sr+6jEYWdLDPgaCC4qrh89U=,tag:UYK0MEuGUFEcOSzARz9Kug==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEWit3SndNbjg5TFRjaDd2
            N3pUYWxqUUFxU3FFNS9sWDF3UXR0ckV2Qm5rCkFwV1E3SmFZZVpzVTl3L3hvWk91
            MTFKQ0c3bmpSRHd4OTFJS1ZSYURqekUKLS0tIE53aEZEYUcrdW5LbHA5STNFWjNN
            SDM0Sm55UHRJbkpNaUZ5cEh1b3UzcUEKAtssLxmOISx+h09MTEj9znOdx4MRA8To
            S+GVJtGPFkWv7zVcFH3Xivbv8VXLRX3wzzx1if/mWx0Ek/v6uYDc/w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
    lastmodified: "2026-09-19T17:46:17Z"
    mac: ENC[AES256_GCM,data:axkLv0715eIEz3W8hlrQp4ZdMXx4D/egsWLb8Ch1h0D9jjuCagDp2vpDFFslOHlHrivV+DojZXdi9L2BioZHiwM1h7Tyuxhyt03pppcjy1w44RWNiPV/JOTFfIuA7SNa0KjWt/Rwjn6e431KnUJeHpgrFLoBgHZ374vHYLtmSmM=,iv:hJYXM9oI/itja6KXkS7SrwfBrC8bu0TRy4thd/bzLpY=,tag:wXXGFogvYIlDAV+8EuNiHw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
