value: ENC[AES256_GCM,data:SDDc/kXuDw2gQUhFUwpnucgbEvAAjx6unauyLZrXsDqblVWgx1bMML0sGShTltAK0iqG9d9vgDNYACdp6cvU7/HfTt1N+eg6gfbFnYtcn6FTqqYhBE646LmE62yTGMhp4yuNytnIMHscYNaPd1iN+TaImcY+6C0C2C1MQQ4yUqy3dsfjYgTGPwp3U77V2E2H5aFlohZ+bSlOJfvYrHmrq1FHt9AMMROakD5/qK+MsiVDHjrb2q8fuez5LD4GLK1FB07Pwgm15ftQiuAkVl24z28nISbRVM5urAgd0WRYY+v4gS2TZ1+/lxpb0mnN5KcMrIHk9dZhdKX7K8ZOaj/VpMzF19F6+fghoAxggucFDRnyqgtJV6PBlN1x/pc0q/d1OYKPUUQAXcJkrlYGmYjFjkJez9u0B6Q8zDSCX41ziwgGFh8lYNlqeL4Rfo95/Wp2R6E6IOuyBcQZWkfzRF0m1CdbFFNeVW4AZjvJ6WMxEA71nfOrkm0n4v+DcMxO5KGIcsZTgA8t7KflaD7v/dWV+UQw5Hkqp9CrKJ+IJU79zezcXgSWCfP5e/K95e3/wsGCbZwMk7UidthfCJ5qfF8cpDcg5GT82uw=,iv:HyW5MxlZFCK83+D31lcfSxpNzvoaBCt+Mh2ol/jYKSQ=,tag:DfvcLHMF2U84M97dWkIsbg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkODRlVmdqakNGQVpJbXEx
            d3pQYTJnOHZvR09NczBJZC9iM3c1RW5FbzJrCnZtL3BSWVRBc2VVZ29Wb0hTTlBX
            RkFhQUVrTDFjcHlDU2huMHBwM0hhZTAKLS0tIE1BWVpwZjJiVEhYN2tocHEzZXdR
            Vk1ISlBIN2NHQ2ZjWWh6OVc3QVVPSTAKnkeglJfygQbu1sHbBAPAeJbdg+sRNoY2
            pCbKQVf2CV+IdUx7u1V8ITPHH6llDesZiL096stJPd2cAcXCQ5JlqA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
    lastmodified: "2026-09-06T11:51:40Z"
    mac: ENC[AES256_GCM,data:Q9XXmJO/CqBpHi8I0Rz9xiLKoyKo/G2LLQojjbPveZhpHPd2xnpjTJKMjErQgkWrN2DNDqst03Gu4TtCO8Do0awSlLDfl/+AwYP5LXTLqcWMfgrgv4eNop55QPVb8NdYBMxvdI/Y0xL16msTP4Q+iBYa9huQdC+pAUuBR8qQGWE=,iv:pU5nzafRx8whRiKF2XWgzfcMHYT0VSWjMmGXK+rWBww=,tag:yFSOAdrn4f6EDRGTZt/+SQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
