value: ENC[AES256_GCM,data:8fqRksN2EEFS6XmhI8nRdvzxghL1W+HxU0zFaWxIlNZTDUlSm06gyJS3df6K15zWR+6oJjqQWTJ8LK9mHzgrJxFMFq1j61OLo3WGsez3a7GIvzEDRTfmm4f65L0C6zaKNnmIowkcz7HQAimYRvTIuawzckH1a2P8ScX0RBqY2Y8pzLfy1d1dk/5Q8jaW47MihaOCdokB5dDbxOE4NMddTCIIfKb6Nl3OmrG91O6PGFahhYew1pWQvdjFF6/9um4ZEN+IAS3u+itGCv2xKT+jsM5yCoKKWW4wa6uxL3ZE9weYklALPFA1AlTKsHHjsyoqSI0TsQAY15eqA2JyrimCODorSCFy7Bld2Ce5LmAcaGyeUXM23zcL5Kt7Se35MRaITGnwCkVbO0Q9EssI8V/oUqzph9e51XHQ2NF1/EEywU1PY/kBR15dX/XDGUC4ySc5FByzVphM63tq+5T7yNfl/8tqrROn8kRVH77oLFSggI/cRjlfYi8OVIStY2RcF6rWuDRUBUTfaHi98THKPcBBJuJrFQfN4hVqLDT2kqLOK3RhL0wcfrEPOQ==,iv:vdOfAIIHhw+hLMrW5S/0p3x2NBbc8guMiFxu80HSa6s=,tag:4/RCDhlZsjxoPXpfEoED9A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMQ3R3WDRxQkxXSHpxQkM1
            YmFpdzFRUjJUSzNJUGlRRWF6RlBBYndiQVIwCkJxS1pEZXVuV05EZWxPMVBKNVZj
            b21RTjFmK3VxZjJuMURqdDNHdlllbEUKLS0tIGtxWVJVVEpBNGdTQUJ2V0NuTURN
            bEpKOG1TQ3p0SDd1ckhtMThFcVFvRWMKVW4rwRqWTx/tAX04nCZkX/oGCx1Q2E61
            0wGimmUxK+eHLTTZcBdRuygmG2uwKXNkBj/wI6MaVGDL0G1X6h46Vg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
    lastmodified: "2026-09-06T12:00:59Z"
    mac: ENC[AES256_GCM,data:4LNmjoi0ElbR8DqroecEk1spgKmDQrpGoJax0BeTgWbz0Z1+e7OI8T0Pp3kkCtZ/+H7I1KWvMSNkLSFKgbGoAZ5btJZKTRWECXoWHR71cgx3nQlCPzfqkk6FQn2cWMS72N1m26pewSpkyjmX1OSm8ooUibOOzyHpEEKdyX0kDII=,iv:0fZAsZU5ZXmGosjn5yxCkvgDQDPWMaOmsQK+55FP+S8=,tag:JUOgh1yPOteXv8rcwsyE2A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
