value: ENC[AES256_GCM,data:zD/TQ3ew3rKst+s3O+i5+OACcu7j4aHPkA8kwaEf3CAhInHcJTa/nVhZPX6PDiwncvq1lxz1dgzg8KPni0EdmPWYirdOgSkTq15i7h8BmREFWFFbBQ7KF81Dm7EMccbI7WIPU721CHiFVz6icDvSDyJsQ6RjQIjw9OBMoyA3T+jJ3nqO92GI7g==,iv:U/xOmbgiekd/k+CPz3g7ljyZU54GeSq5ih4HDHk5mN0=,tag:2C/3uY5JKOpPGVwwFI2uhw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2SXFXMDZkU3U5czdnOW5V
            ZTVzakxyNFJZKzZpV3RpQ2xrMFJPYVVtR25VCnA1SWcwVkhZaWRkWjFoNXVHUTRL
            bXpiR1JZSlRVcFBVYUVuRnlLN1pFUWcKLS0tIFhxL3B5RWZDa0x1QkorZDNqaE9B
            Tm9ObDYvZWFCTHN0UTcyNW1rRVBTM3cKLqEf3Qv6bTAuP9ZhmwMqqC7iM1wRJZ16
            uze/SIdcCOVLOwd4C4ImR6nfVdu48kIqKENgOSbbjoRdxZhSvK7l/w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
    lastmodified: "2026-09-06T12:02:03Z"
    mac: ENC[AES256_GCM,data:Kz+AmCExfDv2rRbGDzy5H54RuHDoOI97oQ6l0sFRRqPUyIkxv0JKS0ewKdvew8XxOndPgxetj56hF/AyFXl6McOvh8BEyiNLz2ewUkLznI3cKL7porzSiRz6hCR4KZ86aG6ISG38cPGxJuJrOQYGWOegONwJFxwboZacAddu++Y=,iv:MOeYpfjhyu3zl1FbBAxkONfgkr6bNqf2PkNPG0D/3HY=,tag:xgtvu+OFO+fANAF1/wzINw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
