value: ENC[AES256_GCM,data:o8+UlMl8yMdxXm0X+yzAJJqCMw==,iv:kQfbDxrZ9FiDt111PlS20zExAzXgvu7wBtdXzgJeIGA=,tag:wqDaf7xUUrugBJdyfZXXrA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSM2RxRVVhTFQ0eEhQTnhj
            Q1ZTK3pNWnVqZE43NkRBd3Y2ZnV3V3ROczJvClIvTFdTRnMxRGJXb1FmR1JyN3Nn
            UWsreWpXY1RqSm40RGQ4Z1h6Zk9Kd3cKLS0tIFZBZ0tDZGFkaUxkNk9BaGIyVVB3
            SU5MT0JTQzhmLzhZOGJiTUdZSWdBRjgKa1n7t1OcSwVgPaA9UAenbY5TP+5NiZrJ
            Wwh38EKPs6jDtDfKHJOPBLk3izNZjYEpvDAb3Vcy7YVZpBXf1AysGA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
    lastmodified: "2026-08-28T15:00:06Z"
    mac: ENC[AES256_GCM,data:ezcqaT/enZEzjqvXQsfrUrdq1DFy6UqsZaDXoZYweOxr8S1PqvrwmiVk2AysBLOSx9kZvIzi+TQqBEsEVlngOkrFuZERtGO92lZYOipddrACLwsUJAhFoSAC0YKECj4gNe5Yj/1RexL8nqxQTa1GTaMB+fxUSWh+e8yRMEAwRqc=,iv:yioplOxcY8WhBSdEV3xRT2E55Ap3tv9PS+qQ2dQ866I=,tag:Qi7Hx1BRuygWvP+MN9BtRA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
