value: ENC[AES256_GCM,data:vV8Q7kyyCiVMnz9GriMlyOBvhrRnMNUlp/qeXITRdLFUfAZ/L6U=,iv:OIoNOtTDFDatZcexCEhRXjuqiBgZrzI4KqftD5N1H2U=,tag:WoPKot2uFjpPbe3+Fk5SgQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBueXQzQ0dFcUdtYmF3ZTk5
            LzZBVXpwUVIzbXJna055ZHYyRm5QNUZPcWtFCm1kaTA0eG1LSU9Oa09oaDdrV2hL
            REtERVozYUVlOWlrTEdzbkdHeSt4OEEKLS0tIEIraHlERTJMb0NOTldWOUxlcFZM
            cURZWTRob0I5ZmNxcVdtRUJvV0FNdk0KtEByqiWfnSTVzcgEFUGqoakuCI6tNjID
            wL83r5F5ro6oj7H73+pGj/fu5+2VndNtr3ELSSQqED7FLdjr7Nk9Uw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
    lastmodified: "2026-08-28T15:00:17Z"
    mac: ENC[AES256_GCM,data:jGWUOA/mbpogWwV9x//U7Odc22odLXn+fJVqxrRCuJpPOrnrYunQUqxSlhq3bqw94+7sfElmieeYCApQWFG7QJX17aLVIlBWbvY1mQ1twdiIE1jNMenCGf89NS5vnTdjqeNX40+cBS/fW47u241zi5fou8DuZE4Nt7pXgk/j4VA=,iv:IzjAedFTHWM2Q5Dx4UpXgBU4PF4IV5nwUU8Nt5WtFO4=,tag:7SFzC7RQ9mWyBBeghWX9ww==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
