value: ENC[AES256_GCM,data:jNjD2atDixkuVlnEoYJmkPIFxTDvou0wg4r4sgsPT+2BEdLPr6h5ub4EWhwIc4G2PO8vE0z8qtobUUxoZBh80Q==,iv:TgYqd2LhHSjmbtzuRGewO1sE7Ci2aB9dc+lwUnB5z18=,tag:P4iBDB2abAKER7IwTL4EbQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhRFJDTXAzUGorSEhrbGxL
            OXcwR1ZlbVBsNXBjSm9VY2ZEZWt0ZzFKQUNRCkd4SWFKUGgySXg4VFJlZHZRSENB
            NUtUS25vT3VxODE2a2hRL3FLTlZkancKLS0tIG5mVTY3Rjh3UURyWDNpMndNbFRC
            Q1hJaVBkTkREZkFDRnc4T0lRQkVnb1kKnkROetb6xutotVf6TJN1c6BFeLPHJqoR
            haxxRtvRz7Cat7kXpkrTerPU95RYlmxGH1v/H6ONOrw32wNy168LvQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
    lastmodified: "2026-09-21T00:02:44Z"
    mac: ENC[AES256_GCM,data:cRmQqGOUBsXg8rgC1F4SMl/CvJKgnT9PQoHARtGerOsm3SKh6g6b6MAsP50gh6wL0YgAXZEkA73KmAinOXJ9bbLpbSOMan/1juIccpTRbZ60v1zhRW+68sTf1bv6IUeAYyfAJT/1SkDY7HnCWXMm3geRzTssilP75ORnbWkdS/o=,iv:3TgCTaTftUPPxolxY2uMjWugNLIO90gPaRibvOa1B9I=,tag:kNqwG161G0L0zTxxjRCyZg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
