value: ENC[AES256_GCM,data:QGleByPFjCwUsQ3LrGkekeNr+TrlTb9GcTKCS9K2y3/tEQkzmTUpCInGLWBPp5M3bEOFI3vyim8PAvT8E9gBXltiyHFwjNzaKAydCNxiAwALgPV9jVU4SycyeLoarhMomrY=,iv:BteAC97s15MTk1THzwwE2jx1uYQ7PsI0d/DK4I1oIHc=,tag:CN3IZJnl1IuAcBf5TSHBWA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqWlQwOExianNOWUhDRHRq
            TTdnY1N6b1kzS0l1ekwzVzR5RUo2LzJRUmdzCjF4MTJZN2c2YTVROGcvaW1ySWlX
            R3lLUzEwRTJFcVRlMDJRTDdWcTNuVWsKLS0tIFBvSk9KNTl1Q2dsYW0yVGwwMDBr
            WHZJN2NINlg1NEdFZ3RPQTU1amhYWEEKRDj0H6VZ/1RwZVY4fxvK+jsG/lWB/FP2
            PR4NUhPuk3SNfSjTqf5QXO1Frh7x0c+cKtT+zybxn9TEMzRZKW6lOg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
    lastmodified: "2026-09-06T13:16:01Z"
    mac: ENC[AES256_GCM,data:nXc4Sl/ZOCAQM9VYbWmxM6Ict9YQcLIjQlN1ZEYwqDMzmTiKDorXMJRXXB/gQ2Eh/JJrafjgkVNBc/u2ELEJdzV4xLn4hz6luQm1yIWyYq1ALnG74TS2vcyAXteIxoM6WJnfO5vFkeRuKQ6AKdHDN5EEwsgvpNvqdqtS+UWQNa4=,iv:J6nV1g64pLbIjLzPHRDA5jk3QydpLHD/FoojuCqVk/k=,tag:7cCwedWHGBe070BplrsctQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
