value: ENC[AES256_GCM,data:R6FH2jhFCId5lRRETmWLltWz59XxBoUsH+uX8kuQlA8=,iv:ADdL8pOI0nDyWhlW6CE8JCzkaAvS3crvHuSOYNkPHIA=,tag:8LpHhzXEu4X3RunM2fmFKA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwbm9VMnhyakp6Mzg2V2Jx
            MHlMQmxKNTM2c0FIak16Nk1DNzVxeXJXY0RzCnBjcWoxZUs4Y1FIWDVHVnRlM3Fi
            ZDlxai9NbWozekR2ekcvKytQT2tzNnMKLS0tIHpsQlM1VGN1alpITHVDbUNMd0xF
            Z1dQOFJsNlNFTFBnWlBZa2I1RjRzUjgK5gH8G+HZubznhZQqeO82Ijop/bdAxp3V
            zXSoyGT2a+kfGuhtQgOtThtUjV50MwpqCP7mIUqmsy44cnqtH2UxBg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
    lastmodified: "2026-09-06T13:16:10Z"
    mac: ENC[AES256_GCM,data:QnE7CK0IWcn78zPEBtB3F01WL0BQkW5uJQjj9SyfrgY7u+8VEhLTQY5iJ6+KJT/oJtxawJsb3YPA0gSYiT01tXnMK2kH6eEtum/xrVc9ERky4ma8sHJqjV33WDh1aEL6kC3IF9hGlp1slNDPycPJMh0rqPzyTEDtb4IJ8JHr2BA=,iv:YhdsTJCdX2q54e/c8QCP3yDYdPRqiHAVvJH3Uaq29aI=,tag:pdj22SeXcqr0TZ/J9CPRqw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
