value: ENC[AES256_GCM,data:HOAtwuR+UCRa7zg40RDHLHxorQ==,iv:9D+KBIm+hRl3toIIrAamQEOTr4yMerxv2WmwzBbTT7E=,tag:n/MZy0zL6Lc+oMWtF+Y5GA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuYjRZSGhHbWl6eXJKTm01
            VU5RM0NvT3JJY0QwdmcvL05lV1hYV2Vob0FRCkIzemJBbUtVMHVmckd0cmM1a2dM
            SDRGNmlyQ05BdlI0Y21xL3JlN0xlRkUKLS0tIE1wd2dhNTcwb2xvSkVlNDlXZmNv
            cnFUOWNmSyt2cVJ5WDMweGFhUTBJaEkKz/VPh5cGtZHoItYt1JZbUUn0mR14QO9Q
            ZB7A9gLp20kIh/GNjvQVaWEIgknUdL2/+I8Pa1mmJKUlrSQ0sq5erQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
    lastmodified: "2026-09-19T17:46:33Z"
    mac: ENC[AES256_GCM,data:OpHGMAkT1UoF6ghrk27hXFxXBTAlaehKywUboeCbj6fpNTPFEikTKp4lZZVEuu0boDU5SskdQXU8XCn3yOH3BBRasQukOdXMH8hOHTUaX6iulBEStA57wMP/eV2Xk6fLtHYZDVdDNeeEKLVUnTY1xLVBVmdletacfVZSyUcOT6o=,iv:rgdwJtuzdTVnyynGfnpW7F0r4l7WYbjIe+v468P/18c=,tag:IoS31EW2gLj9jmQ/YMxEtQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
