value: ENC[AES256_GCM,data:wJf66HgGuXctdPTkvJ/KkbMktsGJYY1ZKYKGB8vSdAdaDnY7vqg=,iv:lO6WIoaDpkeEiym9/mUWM84me3a/89orHM0AkDJkaL0=,tag:AshUa4lMHfxhAXgORgwAWg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlbmlvOFZZL2ZEWmp6YXgw
            Yzh0S0xrTUZhcklWOGs0MzJ5YUllSU1YT0VrCmVJUEdSc0x5eFpvT2tMSHBDQ0hR
            SDY4S3ZmQ3Q1MDB6TkkzVmpJKy8wQVkKLS0tIGE3RzJQNDZ0VnZoUEc4UVNVenlH
            OE1kbWtSQ3FBNXd5bUd2MVZES2pEa28KgTEpjKKNp/aee5/EyPjfV3vm9FZ90vCI
            AkLP/ZqIVe5F+fR28WLa7uZwcCcXL0zCeP3WANDV0wT9d5dgswaCuw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
    lastmodified: "2026-09-19T17:46:40Z"
    mac: ENC[AES256_GCM,data:Gxuq7MasxYkA2UqIs8Qke9SMN429Vsk3fgNx2+BjG1Wd9ySAEqroiGggWn/VBqtBsLcRKJM+cvOdsKLIQ5wbPg3PbTj6p5yYkndPXA9OpVi7FEDMpQ6xEBbiESuMDaOYfiTD2m8FYkApHJSh2QG0t/FzupBs8KE2L6gH2COMBhk=,iv:iHle8hMxTg1+9ozaw9k8bU9aMO7r9mFcKSiOOoaO+tc=,tag:EfBAR5iXpTsfExNkykegnA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
