value: ENC[AES256_GCM,data:FVS14dZ/3t9GLWq3WFYqMlIOxajtr0y4ZbZbhdL011ZNtQ6Zh6VvlFv9o3bHo9oGchKEFa3xGQkOYffJx5twIau5HDVT2yO/72HofI3f8WrXOmdgOiEo2HSwNVmP8i3kOHlzZ/6yk3iPVLl1rREeX4qioXhvrNNNKKL6eM/YDp9P7RhcugnWOnufxkfk+dIBL5rmOA0y7xr2JwBbO46qTitovF3rcdX+0O6KXhcKSka6vGVEj9kLjn9x2cI=,iv:oaDPfspV+NsHHCPES2rLoGEV3AYxKxjS/3doODEpEqE=,tag:2iF0lMYV0ntGHRUbxXUodQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtWkhESWp1UTBOTVRPQk5k
            azZaKzRCK2h4bElCSGNZbjhvWTUrVk5DVG1NCmE4U3JRU0lPMGhua25SQWxHQmpG
            YkdmRzg2cmhLYnVSUEtPRFFOMDU2Um8KLS0tIDNETDU4eXkxb1FPYWN1SkwwV1FO
            cSt1cjQxcE55ZVptSm1sZXd5SEppWmMKz4OLni6sHQpLHyQHpD0sMCJQ8b/AAeJw
            7Y4w4zVtlrmBWCo0AoOfXllvpMl8J6qFH3gkADm3wAF6fjqKfLGyrw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
    lastmodified: "2026-09-15T12:35:37Z"
    mac: ENC[AES256_GCM,data:s5R9pQHAtnE0XIfQV6JURUMyXNPPv/XCHyh7JsBJwY3+IprD8GNITukxLxgv82SCywHGYXiKEViUoqv5BKJ0Q18qCbuDg/7PDKt9+ToS9jUmWH8FCIhJ19iMbNTarpWIpT4ZqT6eLYTX9/5m/SMojjQn9q7lY9qfRMeR3a7h8jw=,iv:9Wn3im+FCLdCzCl+vY0Jo/0TTtLQNEIUd4SkFoGtI+8=,tag:bfscOz14BS0g7pJc7q67lQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
