import { describe, expect, test } from "bun:test"
import { fixture, rootsAt } from "./fixture.ts"
import { type Moves, surveyRename } from "./repoint.ts"

function moves(...pairs: readonly (readonly [string, string])[]): Moves {
  return new Map(pairs)
}

const MOVE = moves(["tools/one.ts", "tools/deep/one.ts"])

const SCRIPT_HEADER = "# DO NOT EDIT — generated by generate-dockerfiles\n"

const MODULE_HEADER = "// DO NOT EDIT — generated by codegen\n"

describe("a referrer the repository generates", () => {
  const withMoved = (work: (at: ReturnType<typeof fixture>) => void): void => {
    const at = fixture()
    try {
      at.put("tools/one.ts", "export const one = 1\n")
      work(at)
    } finally {
      at.dispose()
    }
  }

  const patched = (at: ReturnType<typeof fixture>, relPath: string): string | undefined =>
    surveyRename(MOVE, rootsAt(at.root)).entries.find((one) => one.relPath === relPath)?.body

  test("its bare mention of a moved path is left as written", () => {
    withMoved((at) => {
      at.put("deploy/Dockerfile", `${SCRIPT_HEADER}COPY tools/one.ts /app/one.ts\n`)
      expect(patched(at, "deploy/Dockerfile")).toBeUndefined()
    })
  })

  test("its import specifier naming a moved module is left as written", () => {
    withMoved((at) => {
      at.put("src/uses.ts", `${MODULE_HEADER}import { one } from "../tools/one.ts"\n`)
      expect(patched(at, "src/uses.ts")).toBeUndefined()
    })
  })

  test("its markdown link to a moved path is left as written", () => {
    withMoved((at) => {
      at.put("docs/notes.md", `${SCRIPT_HEADER}\nIt names [one](../tools/one.ts).\n`)
      expect(patched(at, "docs/notes.md")).toBeUndefined()
    })
  })

  test("a referrer carrying no such header has that same specifier repointed", () => {
    withMoved((at) => {
      at.put("src/uses.ts", `import { one } from "../tools/one.ts"\n`)
      expect(patched(at, "src/uses.ts")).toContain("../tools/deep/one.ts")
    })
  })

  test("one the same move relocates is carried, its body still being taken away", () => {
    withMoved((at) => {
      at.put("src/gone.ts", `${MODULE_HEADER}export const gone = 1\n`)
      const survey = surveyRename(
        moves(["tools/one.ts", "tools/deep/one.ts"], ["src/gone.ts", "src/moved/gone.ts"]),
        rootsAt(at.root)
      )
      expect(survey.entries.find((one) => one.relPath === "src/moved/gone.ts")?.moved).toBe(true)
    })
  })
})
