import type { Track } from "akasha/alan/music/catalog/track/track.page-type.types.ts"

export const auroraADifferentKindOfHumanStepIiTheSeed = {
  id: "01a0b637-f9f7-7366-bb40-9a5dd2e9fa1a",
  type: "page-type/track",
  slug: "aurora-a-different-kind-of-human-step-ii-the-seed",
  ownLength: 4.449483333333333,
  ownProgress: 4.449483333333333,
  partOfCollections: [
    "release/aurora-a-different-kind-of-human-step-ii",
    "release/aurora-for-the-humans-who-take-long-walks-in-the-forest",
    "release/aurora-for-the-metal-people",
    "release/aurora-music-for-the-fellow-witches-out-there",
    "release/aurora-sky-concert-in-the-light-original-game-soundtrack",
  ],
  status: "completed",
  unit: "unit/minutes",
  title: "The Seed",
  trackType: "studio",
  explicit: false,
  trackArtist: [{ artist: "artist/aurora" }],
  trackKey: "theseed|1WgXqy2Dd70QQOU7Ay074N|266969",
  song: "song/aurora-the-seed",
  carriedBy: [
    {
      release: "release/aurora-a-different-kind-of-human-step-ii",
      discNumber: 1,
      position: 10,
      externalId: "3EUXLUKx2zNUzb2otMc8HH",
      externalLink: "https://open.spotify.com/track/3EUXLUKx2zNUzb2otMc8HH",
    },
    {
      release: "release/aurora-for-the-humans-who-take-long-walks-in-the-forest",
      discNumber: 1,
      position: 6,
      externalId: "4mSg9e09SwKyMzyaP5WD6r",
      externalLink: "https://open.spotify.com/track/4mSg9e09SwKyMzyaP5WD6r",
    },
    {
      release: "release/aurora-for-the-metal-people",
      discNumber: 1,
      position: 2,
      externalId: "2HIkVjn7Mttukqxz7KQxlP",
      externalLink: "https://open.spotify.com/track/2HIkVjn7Mttukqxz7KQxlP",
    },
    {
      release: "release/aurora-music-for-the-fellow-witches-out-there",
      discNumber: 1,
      position: 4,
      externalId: "4IYFiPBWwI6XTtBPINAi9X",
      externalLink: "https://open.spotify.com/track/4IYFiPBWwI6XTtBPINAi9X",
    },
    {
      release: "release/aurora-sky-concert-in-the-light-original-game-soundtrack",
      discNumber: 1,
      position: 12,
      externalId: "75KVxbugVg3andqLN5z8vu",
      externalLink: "https://open.spotify.com/track/75KVxbugVg3andqLN5z8vu",
    },
  ],
} as const satisfies Track
