import type { Track } from "akasha/alan/music/catalog/track/track.page-type.types.ts"

export const thePianoGuys3LullabyOdeToJoy = {
  id: "01a0afa1-dec0-7c17-bf16-6aa5513e867d",
  type: "page-type/track",
  slug: "the-piano-guys-3-lullaby-ode-to-joy",
  ownLength: 1.7685166666666667,
  ownProgress: 1.7685166666666667,
  partOfCollections: [
    "release/the-piano-guys-3-lullaby",
    "release/the-piano-guys-3-wedding-season",
    "release/the-piano-guys-classical-for-studying",
    "release/the-piano-guys-peaceful-summer-nights",
    "release/the-piano-guys-relaxing-piano",
  ],
  status: "completed",
  unit: "unit/minutes",
  title: "Ode To Joy",
  trackType: "studio",
  explicit: false,
  trackArtist: [{ artist: "artist/the-piano-guys" }],
  trackKey: "odetojoy|0jW6R8CVyVohuUJVcuweDI|106111",
  song: "song/the-piano-guys-ode-to-joy",
  carriedBy: [
    {
      release: "release/the-piano-guys-3-lullaby",
      discNumber: 1,
      position: 12,
      externalId: "3xgOuXgX8txPONEVoD5Hqd",
      externalLink: "https://open.spotify.com/track/3xgOuXgX8txPONEVoD5Hqd",
    },
    {
      release: "release/the-piano-guys-3-wedding-season",
      discNumber: 1,
      position: 10,
      externalId: "2ZLfgQqOFzz5UUMJEpAcRc",
      externalLink: "https://open.spotify.com/track/2ZLfgQqOFzz5UUMJEpAcRc",
    },
    {
      release: "release/the-piano-guys-classical-for-studying",
      discNumber: 1,
      position: 3,
      externalId: "0HeQdNfA86f81ht5zAlSSB",
      externalLink: "https://open.spotify.com/track/0HeQdNfA86f81ht5zAlSSB",
    },
    {
      release: "release/the-piano-guys-peaceful-summer-nights",
      discNumber: 1,
      position: 11,
      externalId: "7KswbsyYRYfM53n1QipSB7",
      externalLink: "https://open.spotify.com/track/7KswbsyYRYfM53n1QipSB7",
    },
    {
      release: "release/the-piano-guys-relaxing-piano",
      discNumber: 1,
      position: 13,
      externalId: "3FoabcSrHvvRyNa6GAPaqS",
      externalLink: "https://open.spotify.com/track/3FoabcSrHvvRyNa6GAPaqS",
    },
  ],
} as const satisfies Track
