import type { Track } from "akasha/alan/music/catalog/track/track.page-type.types.ts"

export const thePianoGuys3LoveMeLikeIAmLoveMeLikeIAm = {
  id: "01a0afa1-f32b-7d14-bd17-616ae2c7558b",
  type: "page-type/track",
  slug: "the-piano-guys-3-love-me-like-i-am-love-me-like-i-am",
  ownLength: 4.5694333333333335,
  ownProgress: 4.5694333333333335,
  partOfCollections: [
    "release/the-piano-guys-3-love-me-like-i-am",
    "release/the-piano-guys-3-unstoppable-2",
    "release/the-piano-guys-3-wedding-season",
    "release/the-piano-guys-classical-for-studying",
    "release/the-piano-guys-peaceful-summer-nights",
    "release/the-piano-guys-relaxing-piano",
  ],
  status: "completed",
  unit: "unit/minutes",
  title: "Love Me Like I Am",
  trackType: "studio",
  explicit: false,
  trackArtist: [{ artist: "artist/the-piano-guys" }],
  trackKey: "lovemelikeiam|0jW6R8CVyVohuUJVcuweDI|274166",
  song: "song/the-piano-guys-love-me-like-i-am",
  carriedBy: [
    {
      release: "release/the-piano-guys-3-love-me-like-i-am",
      discNumber: 1,
      position: 1,
      externalId: "0tgo1cmqBUgQs878IKdjXr",
      externalLink: "https://open.spotify.com/track/0tgo1cmqBUgQs878IKdjXr",
    },
    {
      release: "release/the-piano-guys-3-unstoppable-2",
      discNumber: 1,
      position: 15,
      externalId: "5UNqZLvsQaG9rO47bP6Gf4",
      externalLink: "https://open.spotify.com/track/5UNqZLvsQaG9rO47bP6Gf4",
    },
    {
      release: "release/the-piano-guys-3-wedding-season",
      discNumber: 1,
      position: 1,
      externalId: "6VakPwMxYRKiAsNTt5245Q",
      externalLink: "https://open.spotify.com/track/6VakPwMxYRKiAsNTt5245Q",
    },
    {
      release: "release/the-piano-guys-classical-for-studying",
      discNumber: 1,
      position: 16,
      externalId: "6VdYc4CO8q9deMtf1SOjjW",
      externalLink: "https://open.spotify.com/track/6VdYc4CO8q9deMtf1SOjjW",
    },
    {
      release: "release/the-piano-guys-peaceful-summer-nights",
      discNumber: 1,
      position: 10,
      externalId: "6yhy51gaREwlmZArx20Sxs",
      externalLink: "https://open.spotify.com/track/6yhy51gaREwlmZArx20Sxs",
    },
    {
      release: "release/the-piano-guys-relaxing-piano",
      discNumber: 1,
      position: 3,
      externalId: "0lvhurLHOmCWQvDvJP8EAc",
      externalLink: "https://open.spotify.com/track/0lvhurLHOmCWQvDvJP8EAc",
    },
  ],
} as const satisfies Track
