import type { Track } from "akasha/alan/music/catalog/track/track.page-type.types.ts"

export const thePianoGuys3Unstoppable2NeverGonnaGiveYouUp = {
  id: "01a0afa1-db4f-7eba-9a5d-e5ab7acd0c54",
  type: "page-type/track",
  slug: "the-piano-guys-3-unstoppable-2-never-gonna-give-you-up",
  ownLength: 3.04385,
  ownProgress: 3.04385,
  partOfCollections: [
    "release/the-piano-guys-3-unstoppable-2",
    "release/the-piano-guys-3-wedding-season",
    "release/the-piano-guys-3-when-you-re-gone",
    "release/the-piano-guys-classical-for-studying",
    "release/the-piano-guys-peaceful-summer-nights",
    "release/the-piano-guys-relaxing-piano",
  ],
  status: "completed",
  unit: "unit/minutes",
  title: "Never Gonna Give You Up",
  trackType: "studio",
  explicit: false,
  trackArtist: [{ artist: "artist/the-piano-guys" }],
  trackKey: "nevergonnagiveyouup|0jW6R8CVyVohuUJVcuweDI|182631",
  song: "song/the-piano-guys-never-gonna-give-you-up",
  carriedBy: [
    {
      release: "release/the-piano-guys-3-unstoppable-2",
      discNumber: 1,
      position: 11,
      externalId: "5K5kCJ3OZU82Co4eaLE3js",
      externalLink: "https://open.spotify.com/track/5K5kCJ3OZU82Co4eaLE3js",
    },
    {
      release: "release/the-piano-guys-3-wedding-season",
      discNumber: 1,
      position: 17,
      externalId: "42j5dbhzMrr6Zdj6GNY6oA",
      externalLink: "https://open.spotify.com/track/42j5dbhzMrr6Zdj6GNY6oA",
    },
    {
      release: "release/the-piano-guys-3-when-you-re-gone",
      discNumber: 1,
      position: 3,
      externalId: "7wqHcF6k472o8cQRcfWOXY",
      externalLink: "https://open.spotify.com/track/7wqHcF6k472o8cQRcfWOXY",
    },
    {
      release: "release/the-piano-guys-classical-for-studying",
      discNumber: 1,
      position: 9,
      externalId: "0V2tTn2sKjxbbzmcr7RJio",
      externalLink: "https://open.spotify.com/track/0V2tTn2sKjxbbzmcr7RJio",
    },
    {
      release: "release/the-piano-guys-peaceful-summer-nights",
      discNumber: 1,
      position: 6,
      externalId: "3Jru3GCiD7n2JPfQZvjXoC",
      externalLink: "https://open.spotify.com/track/3Jru3GCiD7n2JPfQZvjXoC",
    },
    {
      release: "release/the-piano-guys-relaxing-piano",
      discNumber: 1,
      position: 4,
      externalId: "6AAlGtVKyXWrEMkpSpuaD3",
      externalLink: "https://open.spotify.com/track/6AAlGtVKyXWrEMkpSpuaD3",
    },
  ],
} as const satisfies Track
