import type { Track } from "akasha/alan/music/catalog/track/track.page-type.types.ts"

export const thePianoGuys3ChillMyGirl = {
  id: "01a0afa1-e071-75b5-81bc-6a0be9461795",
  type: "page-type/track",
  slug: "the-piano-guys-3-chill-my-girl",
  ownLength: 3.9403,
  ownProgress: 3.9403,
  partOfCollections: [
    "release/the-piano-guys-3-chill",
    "release/the-piano-guys-3-classical-movie-soundtracks",
    "release/the-piano-guys-3-wedding-season",
    "release/the-piano-guys-piano-focus",
    "release/the-piano-guys-relaxing-piano",
  ],
  status: "completed",
  unit: "unit/minutes",
  title: "My Girl",
  trackType: "studio",
  explicit: false,
  trackArtist: [{ artist: "artist/the-piano-guys" }],
  trackKey: "mygirl|0jW6R8CVyVohuUJVcuweDI|236418",
  song: "song/the-piano-guys-my-girl",
  carriedBy: [
    {
      release: "release/the-piano-guys-3-chill",
      discNumber: 1,
      position: 1,
      externalId: "4WBnIZM50ar3cWplqV4TI4",
      externalLink: "https://open.spotify.com/track/4WBnIZM50ar3cWplqV4TI4",
    },
    {
      release: "release/the-piano-guys-3-classical-movie-soundtracks",
      discNumber: 1,
      position: 10,
      externalId: "3bcpGqB8A84rKZx6KXI34l",
      externalLink: "https://open.spotify.com/track/3bcpGqB8A84rKZx6KXI34l",
    },
    {
      release: "release/the-piano-guys-3-wedding-season",
      discNumber: 1,
      position: 4,
      externalId: "4s4trlpizTeByhgUEJZ7hF",
      externalLink: "https://open.spotify.com/track/4s4trlpizTeByhgUEJZ7hF",
    },
    {
      release: "release/the-piano-guys-piano-focus",
      discNumber: 1,
      position: 7,
      externalId: "2xPeMMqBVtqVnkVZbiSveu",
      externalLink: "https://open.spotify.com/track/2xPeMMqBVtqVnkVZbiSveu",
    },
    {
      release: "release/the-piano-guys-relaxing-piano",
      discNumber: 1,
      position: 11,
      externalId: "0Y76cvCrqviJhODIpcTnWM",
      externalLink: "https://open.spotify.com/track/0Y76cvCrqviJhODIpcTnWM",
    },
  ],
} as const satisfies Track
