import type { Domain } from "../../domains/domain.page-type.ts"

export const alanHarness = {
  id: "01a05381-69f8-77f7-afef-d8329db98385",
  pageTypeSlug: "domain",
  slug: "alan-harness",
  definition: "how Alan does things",
  parts: [
    "domain/alan-harness-agents",
    "domain/code-editor",
    "domain/monarch",
    "domain/safety",
    "domain/surplus",
    "domain/capacity",
    "domain/plants",
    "domain/activity",
    "domain/sleep",
    "domain/inbox",
    "domain/alan-harness-stoplights",
    "domain/alan-readouts",
    "domain/attributes",
    "workspace-package/readout",
    "workspace-package/voice-core",
    "workspace-package/idle-system",
    "domain/sms-access",
    "domain/sms-core",
    "domain/email-inbound",
    "domain/email-watch",
    "domain/ssh-access",
    "workspace-package/calendar-sync",
    "domain/imessage",
    "workspace-package/health-samples-access",
    "domain/health-samples-day",
    "domain/health-samples-import",
    "workspace-package/location-traces-access",
    "domain/day",
    "domain/geo-io",
    "domain/web-static-assets",
    "domain/web-security-headers",
    "domain/web-page-answers",
    "domain/workspace-paths",
    "domain/web-build-version",
    "domain/recurrence",
    "domain/reminder-system",
    "workspace-package/supabase-auth",
    "domain/supabase-server",
    "workspace-package/errors-core",
    "domain/supabase-client",
    "workspace-package/errors-client",
    "workspace-package/supabase-rr",
    "domain/status-bar-access",
    "workspace-package/mobile-cli",
    "domain/icloud-photos",
    "workspace-package/rules-engine",
    "domain/alanwalton-ios-notification",
    "page-type/notification-feed",
    "domain/money",
    "page-type/calendar-event",
    "page-type/calendar-event-source",
    "module/overdue-rolling",
    "workstation-service/overdue-rolling",
    "module/persona-points-rebuilding",
    "workstation-service/persona-points-rebuilding",
  ],
  invariants: [
    {
      invariantKind: "constraint",
      statement: "Alan changes often.",
    },
    {
      invariantKind: "departure",
      statement: "Alan's harness is optimized for fast change over stability.",
    },
    {
      invariantKind: "departure",
      statement: "Alan's harness has a footprint in several products.",
    },
    {
      invariantKind: "gap",
      statement: "Everything in Alan's harness changes without a deploy.",
    },
    {
      invariantKind: "gap",
      statement: "A deploy to Alan's harness adds only the things there to change.",
    },
    {
      invariantKind: "gap",
      statement: "A deploy to Alan's harness removes only the things there to change.",
    },
    {
      invariantKind: "gap",
      statement: "A deploy to Alan's harness replaces only the things there to change.",
    },
    {
      invariantKind: "gap",
      statement: "A deploy to Alan's harness does nothing else.",
    },
    {
      invariantKind: "departure",
      statement: "Every package Alan's harness is made of is in akasha.",
    },
    {
      invariantKind: "departure",
      statement: "Alan's upkeep widget shows all four stoplights.",
    },
    {
      invariantKind: "departure",
      statement: "Health samples are imported by `akasha track health import`.",
    },
    {
      invariantKind: "departure",
      statement: "Alan's inboxes widget shows all three stoplights.",
    },
    {
      invariantKind: "departure",
      statement: "Alan's code editor status line shows Claude usage and the three readout groups.",
    },
    {
      invariantKind: "departure",
      statement: "Nothing reads a readout through the markdown engine.",
    },
    {
      invariantKind: "departure",
      statement:
        "The reading is taken by a workstation timer rather than by a pod serving a route.",
    },
  ],
  directives: [
    {
      directiveKind: "rule",
      name: "His Call",
      act: "Enforce the limits Alan set; never veto a choice he made inside them.",
      warrant:
        "Both refuse him something for his own good, so the veto reads as care while you make it.",
      aids: [
        "Never enforce a limit he did not state.",
        "Saying he is past a limit is not stopping him.",
      ],
    },
  ],
} as const satisfies Domain
