import type { SetTemplate } from "@akasha/temper-equipment/set-template"

export const SETS_DATA_103: readonly SetTemplate[] = [
  {
    id: "the-juggernaut",
    name: "The Juggernaut",
    esoSetId: 63,
    subcategoryId: "pvp",
    valid: ["*:heavy"],
    bonuses: [
      {
        count: 2,
        status: "supported",
        effects: [{ metricId: "health-maximum", effectType: "integer", effectValue: 1206 }],
        description: "Adds 1206 Maximum Health",
      },
      {
        count: 3,
        status: "supported",
        effects: [{ metricId: "resistance", effectType: "integer", effectValue: 743 }],
        description: "Adds 1487 Armor",
      },
      {
        count: 4,
        status: "supported",
        effects: [{ metricId: "health-maximum", effectType: "integer", effectValue: 1206 }],
        description: "Adds 1206 Maximum Health",
      },
      {
        count: 5,
        status: "unsupported",
        effects: [],
        description:
          "When you take damage while under 30% Health, heal for 4595 Health immediately and gain 20000 Armor for 15 seconds. This effect can occur once every 1 minute and the heal scales off your Max Health.",
      },
    ],
    icons: {
      "chest:heavy": "/esoui/art/icons/gear_argonian_heavy_chest_d.dds",
      "head:heavy": "/esoui/art/icons/gear_argonian_heavy_head_d.dds",
      "necklace": "/esoui/art/icons/gear_argonian_neck_a.dds",
      "ring": "/esoui/art/icons/gear_breton_ring_a.dds",
      "shoulders:heavy": "/esoui/art/icons/gear_argonian_heavy_shoulders_d.dds",
      "waist:heavy": "/esoui/art/icons/gear_argonian_heavy_waist_d.dds",
    },
  },
  {
    id: "the-morag-tong",
    name: "The Morag Tong",
    esoSetId: 50,
    subcategoryId: "pvp",
    valid: ["*:medium"],
    bonuses: [
      {
        count: 2,
        status: "supported",
        effects: [{ metricId: "power", effectType: "integer", effectValue: 129 }],
        description: "Adds 129 Weapon and Spell Damage",
      },
      {
        count: 3,
        status: "supported",
        effects: [{ metricId: "stamina-maximum", effectType: "integer", effectValue: 1096 }],
        description: "Adds 1096 Maximum Stamina",
      },
      {
        count: 4,
        status: "supported",
        effects: [{ metricId: "power", effectType: "integer", effectValue: 129 }],
        description: "Adds 129 Weapon and Spell Damage",
      },
      {
        count: 5,
        status: "unsupported",
        effects: [],
        description:
          "When you deal direct damage, you cause the enemy to take 10% more damage from Poison and Disease attacks for 5 seconds.",
      },
    ],
    icons: {
      "axe": "/esoui/art/icons/gear_breton_1haxe_d.dds",
      "battleaxe": "/esoui/art/icons/gear_breton_2haxe_d.dds",
      "bow": "/esoui/art/icons/gear_breton_bow_d.dds",
      "chest:*": "/esoui/art/icons/gear_breton_medium_chest_d.dds",
      "dagger": "/esoui/art/icons/gear_redguard_dagger_d.dds",
      "feet:*": "/esoui/art/icons/gear_redguard_medium_feet_d.dds",
      "greatsword": "/esoui/art/icons/gear_breton_2hsword_d.dds",
      "hands:*": "/esoui/art/icons/gear_redguard_medium_hands_d.dds",
      "head:*": "/esoui/art/icons/gear_redguard_medium_head_d.dds",
      "ice-staff": "/esoui/art/icons/gear_breton_staff_d.dds",
      "inferno-staff": "/esoui/art/icons/gear_breton_staff_d.dds",
      "legs:*": "/esoui/art/icons/gear_breton_medium_legs_d.dds",
      "lightning-staff": "/esoui/art/icons/gear_breton_staff_d.dds",
      "mace": "/esoui/art/icons/gear_breton_1hhammer_d.dds",
      "maul": "/esoui/art/icons/gear_breton_2hhammer_d.dds",
      "necklace": "/esoui/art/icons/gear_breton_neck_a.dds",
      "restoration-staff": "/esoui/art/icons/gear_breton_staff_d.dds",
      "ring": "/esoui/art/icons/gear_breton_ring_a.dds",
      "shield": "/esoui/art/icons/gear_breton_shield_d.dds",
      "shoulders:*": "/esoui/art/icons/gear_breton_medium_shoulders_d.dds",
      "sword": "/esoui/art/icons/gear_breton_1hsword_d.dds",
      "waist:*": "/esoui/art/icons/gear_redguard_medium_waist_d.dds",
    },
  },
  {
    id: "the-saint-and-the-seducer",
    name: "The Saint and the Seducer",
    esoSetId: 762,
    subcategoryId: "mythic",
    valid: ["necklace"],
    bonuses: [
      {
        count: 1,
        status: "unsupported",
        effects: [],
        description:
          "While in combat, you gain one of five random Major buffs which changes every 10 seconds. Enemies within 12 meters of you gain one of five random Minor debuffs depending on which buff you have. The available effects are:\n\nMajor Berserk and Minor Maim\nMajor Resolve and Minor Breach\nMajor Force and Minor Brittle\nMajor Evasion and Minor Vulnerability\nMajor Courage and Minor Cowardice",
      },
    ],
    icons: { necklace: "/esoui/art/icons/antiquities_saintseducernecklace_full.dds" },
  },
  {
    id: "the-shadow-queens-cowl",
    name: "The Shadow Queen's Cowl",
    esoSetId: 761,
    subcategoryId: "mythic",
    valid: ["head:light"],
    bonuses: [
      {
        count: 1,
        status: "unsupported",
        effects: [],
        description:
          "While crouched, you can see Witnesses and Guards through walls.\n\nSuccessfully pickpocketing a Witness or Guard applies Distracted to them for 10 seconds, stunning them and decreasing their Stealth detection radius by 30 meters for the duration.",
      },
    ],
    icons: { "head:*": "/esoui/art/icons/gear_shadowseekerscowl_head_a.dds" },
  },
  {
    id: "the-troll-king",
    name: "The Troll King",
    esoSetId: 278,
    subcategoryId: "monster",
    valid: ["monster"],
    bonuses: [
      {
        count: 1,
        status: "supported",
        effects: [
          { metricId: "healing-done-base", effectType: "fractional-change", effectValue: 0.04 },
        ],
        description: "Adds 4% Healing Done",
      },
      {
        count: 2,
        status: "unsupported",
        effects: [],
        description:
          "When you heal yourself or an ally, if they are still below 50% Health, their Health Recovery is increased by 925 for 10 seconds.",
      },
    ],
    icons: {
      "head:heavy": "/esoui/art/icons/gear_undauntedspider_head_a.dds",
      "head:light": "/esoui/art/icons/gear_undauntedspider_head_a.dds",
      "head:medium": "/esoui/art/icons/gear_undauntedspider_head_a.dds",
      "shoulders:heavy": "/esoui/art/icons/gear_undauntedspider_shoulders_a.dds",
      "shoulders:light": "/esoui/art/icons/gear_undauntedspider_shoulders_a.dds",
      "shoulders:medium": "/esoui/art/icons/gear_undauntedspider_shoulders_a.dds",
    },
  },
  {
    id: "the-worms-raiment",
    name: "The Worm's Raiment",
    esoSetId: 124,
    subcategoryId: "dungeon",
    valid: ["*:light"],
    bonuses: [
      {
        count: 2,
        status: "supported",
        effects: [{ metricId: "magicka-recovery", effectType: "integer", effectValue: 129 }],
        description: "Adds 129 Magicka Recovery",
      },
      {
        count: 3,
        status: "supported",
        effects: [{ metricId: "magicka-maximum", effectType: "integer", effectValue: 1096 }],
        description: "Adds 1096 Maximum Magicka",
      },
      {
        count: 4,
        status: "supported",
        effects: [{ metricId: "magicka-recovery", effectType: "integer", effectValue: 129 }],
        description: "Adds 129 Magicka Recovery",
      },
      {
        count: 5,
        status: "unsupported",
        effects: [],
        description:
          "Grants 145 Magicka Recovery to you and up to 11 other group members within 28 meters of you. This bonus persists through death.",
      },
    ],
    icons: {
      "axe": "/esoui/art/icons/gear_ancient_elf_1haxe_b.dds",
      "battleaxe": "/esoui/art/icons/gear_ancient_elf_2haxe_b.dds",
      "bow": "/esoui/art/icons/gear_soulshriven_bow_a.dds",
      "chest:*": "/esoui/art/icons/gear_artifactwormcultlight_robe_a.dds",
      "dagger": "/esoui/art/icons/gear_soulshriven_dagger_a.dds",
      "feet:*": "/esoui/art/icons/gear_artifactwormcultlight_feet_a.dds",
      "greatsword": "/esoui/art/icons/gear_soulshriven_2hsword_a.dds",
      "hands:*": "/esoui/art/icons/gear_artifactwormcultlight_hands_a.dds",
      "head:*": "/esoui/art/icons/gear_artifactwormcultlight_head_a.dds",
      "ice-staff": "/esoui/art/icons/gear_soulshriven_staff_a.dds",
      "inferno-staff": "/esoui/art/icons/gear_ancient_elf_staff_c.dds",
      "legs:*": "/esoui/art/icons/gear_artifactwormcultlight_legs_a.dds",
      "lightning-staff": "/esoui/art/icons/gear_soulshriven_staff_a.dds",
      "mace": "/esoui/art/icons/gear_soulshriven_1hhammer_a.dds",
      "maul": "/esoui/art/icons/gear_ancient_elf_2hhammer_b.dds",
      "necklace": "/esoui/art/icons/gear_breton_neck_a.dds",
      "restoration-staff": "/esoui/art/icons/gear_ancient_elf_staff_c.dds",
      "ring": "/esoui/art/icons/gear_breton_ring_a.dds",
      "shield": "/esoui/art/icons/gear_ancient_elf_shield_b.dds",
      "shoulders:*": "/esoui/art/icons/gear_artifactwormcult_shoulders_a.dds",
      "sword": "/esoui/art/icons/gear_soulshriven_1hsword_a.dds",
      "waist:*": "/esoui/art/icons/gear_artifactwormcultlight_waist_a.dds",
    },
  },
  {
    id: "thews-of-the-harbinger",
    name: "Thews of the Harbinger",
    esoSetId: 248,
    subcategoryId: "pvp",
    valid: ["*:heavy"],
    bonuses: [
      {
        count: 2,
        status: "supported",
        effects: [{ metricId: "health-maximum", effectType: "integer", effectValue: 1206 }],
        description: "Adds 1206 Maximum Health",
      },
      {
        count: 3,
        status: "supported",
        effects: [{ metricId: "health-maximum", effectType: "integer", effectValue: 1206 }],
        description: "Adds 1206 Maximum Health",
      },
      {
        count: 4,
        status: "supported",
        effects: [{ metricId: "stamina-maximum", effectType: "integer", effectValue: 1096 }],
        description: "Adds 1096 Maximum Stamina",
      },
      {
        count: 5,
        status: "unsupported",
        effects: [],
        description:
          "When you Block, you deal 730 Physical Damage to the attacker. This effect scales off your Max Health.",
      },
    ],
    icons: {
      "axe": "/esoui/art/icons/gear_nord_1haxe_d.dds",
      "battleaxe": "/esoui/art/icons/gear_nord_2haxe_d.dds",
      "bow": "/esoui/art/icons/gear_nord_bow_d.dds",
      "chest:*": "/esoui/art/icons/gear_nord_heavy_chest_d.dds",
      "dagger": "/esoui/art/icons/gear_nord_dagger_d.dds",
      "feet:*": "/esoui/art/icons/gear_nord_heavy_feet_d.dds",
      "greatsword": "/esoui/art/icons/gear_nord_2hsword_d.dds",
      "hands:*": "/esoui/art/icons/gear_nord_heavy_hands_d.dds",
      "head:*": "/esoui/art/icons/gear_nord_heavy_head_d.dds",
      "ice-staff": "/esoui/art/icons/gear_nord_staff_d.dds",
      "inferno-staff": "/esoui/art/icons/gear_nord_staff_d.dds",
      "legs:*": "/esoui/art/icons/gear_nord_heavy_legs_d.dds",
      "lightning-staff": "/esoui/art/icons/gear_nord_staff_d.dds",
      "mace": "/esoui/art/icons/gear_nord_1hhammer_d.dds",
      "maul": "/esoui/art/icons/gear_nord_2hhammer_d.dds",
      "necklace": "/esoui/art/icons/gear_breton_neck_a.dds",
      "restoration-staff": "/esoui/art/icons/gear_nord_staff_d.dds",
      "ring": "/esoui/art/icons/gear_breton_ring_a.dds",
      "shield": "/esoui/art/icons/gear_nord_shield_d.dds",
      "shoulders:*": "/esoui/art/icons/gear_nord_heavy_shoulders_d.dds",
      "sword": "/esoui/art/icons/gear_nord_1hsword_d.dds",
      "waist:*": "/esoui/art/icons/gear_nord_heavy_waist_d.dds",
    },
  },
  {
    id: "thrassian-stranglers",
    name: "Thrassian Stranglers",
    esoSetId: 501,
    subcategoryId: "mythic",
    valid: ["hands:light"],
    bonuses: [
      {
        count: 1,
        status: "unsupported",
        effects: [],
        description:
          "Killing an enemy grants you a stack of Sload's Call for 1 hour, up to a maximum of 50 stacks. Each stack increases your Weapon and Spell Damage by 23, reduces your Maximum Health by 120, and reduces effectiveness of your damage shields by 1%. \n\nSload's Call is lost if you remove Thrassian Stranglers, go invisible, or crouch.",
      },
    ],
    icons: { "hands:*": "/esoui/art/icons/gear_thrassianstranglers_a.dds" },
  },
]
