import type { WorkspacePackage } from "../../code-system/workspace-packages/workspace-package.page-type.ts"

export const temperBuildDeployChecks = {
  id: "01a06287-7841-7e04-b566-2bb1b434877d",
  pageTypeSlug: "workspace-package",
  slug: "temper-build-deploy-checks",
  definition: "how a game add-on is judged before it is built and shipped",
  manifest: "json",
  partSlugs: [
    "module/population-bound",
    "module/error-message",
    "module/suggest-closest",
    "module/cli-args",
    "module/repo-root",
    "module/addon-roster-guard",
    "module/addon-source-files",
    "module/addon-global-ownership",
    "module/ts-node-shapes",
    "module/eso-doc-api-version",
    "module/eso-clone-artifacts",
    "module/check-eso-typings-fresh",
    "module/addon-dependency-cycle",
    "module/check-addon-dependency-cycle",
    "module/addon-dependency-floor",
    "module/check-addon-dependency-floor",
    "module/addon-orphan-xml-handler",
    "module/check-addon-orphan-xml-handler",
    "module/addon-inline-handler-dispatch",
    "module/check-addon-inline-handler-dispatch",
    "module/addon-hook-eager-capture",
    "module/check-addon-hook-eager-capture",
    "module/eso-sandbox-manifest",
    "module/addon-dist-bundles",
    "module/addon-banned-symbols",
    "module/addon-removed-refs-manifest",
    "module/addon-removed-refs",
    "module/eso-sandbox-globals",
    "module/addon-sandbox-load",
    "module/check-addon-sandbox-safety",
    "module/check-addon-removed-refs",
    "module/eso-base-game-string-ids-00",
    "module/eso-base-game-string-ids-01",
    "module/eso-base-game-string-ids-02",
    "module/eso-base-game-string-ids-03",
    "module/eso-base-game-string-ids-04",
    "module/eso-base-game-string-ids-05",
    "module/eso-base-game-string-ids-06",
    "module/eso-base-game-string-ids-07",
    "module/eso-base-game-string-ids-08",
    "module/eso-base-game-string-ids-09",
    "module/eso-base-game-string-ids-10",
    "module/eso-base-game-string-ids-11",
    "module/eso-base-game-string-ids-12",
    "module/eso-base-game-string-ids-13",
    "module/eso-base-game-string-ids-14",
    "module/eso-base-game-string-ids-15",
    "module/eso-base-game-string-ids-16",
    "module/eso-base-game-string-ids-17",
    "module/eso-base-game-string-ids-18",
    "module/eso-base-game-string-ids-19",
    "module/eso-base-game-string-ids-20",
    "module/eso-base-game-string-ids-21",
    "module/eso-base-game-string-ids-22",
    "module/eso-base-game-string-ids-23",
    "module/eso-base-game-string-ids-24",
    "module/eso-base-game-string-ids-25",
    "module/eso-base-game-string-ids-26",
    "module/eso-base-game-string-ids-27",
    "module/eso-base-game-string-ids-28",
    "module/eso-base-game-string-ids-29",
    "module/eso-base-game-string-ids-30",
    "module/eso-base-game-string-ids-31",
    "module/eso-base-game-string-ids-32",
    "module/eso-base-game-string-ids-33",
    "module/eso-base-game-string-ids-34",
    "module/eso-base-game-string-ids-35",
    "module/eso-base-game-string-ids-36",
    "module/eso-base-game-string-ids-37",
    "module/eso-base-game-string-ids",
    "module/check-addon-sandbox-load",
  ],
  invariants: [
    {
      invariantKind: "departure",
      statement: "A run here reads the game add-on tree rather than the akasha tree.",
    },
    {
      invariantKind: "departure",
      statement: "A run states how much of the population the run examined.",
    },
    {
      invariantKind: "constraint",
      statement: "A run that could not look reports that the run could not look.",
    },
    {
      invariantKind: "constraint",
      statement: "One module answers which files under an add-on are that add-on's own.",
    },
    {
      invariantKind: "gap",
      statement: "Most of what this package is made of is still outside akasha.",
    },
  ],
} as const satisfies WorkspacePackage
