import type { Case } from "../../lib/formula-conformance.ts"

export const PATH_CASES: readonly Case[] = [
  {
    id: "dot-reads-an-object-property",
    category: "substrate",
    covers: "a dotted path reads one step into an object",
    expression: "o.k",
    values: { o: { where: "database", json: { k: "v" } } },
    ours: { kind: "value", held: null },
    code: { kind: "value", held: "v" },
    why:
      "`o` has to hold an object with a `k` in it for the step to mean anything, and a page's frontmatter carries text or a list of text, so the file side cannot be handed that object at all. No increment to our evaluator could change that",
  },
  {
    id: "dot-missing-property-is-null",
    category: "substrate",
    covers: "a path step onto a key the object lacks answers null",
    expression: "o.z",
    values: { o: { where: "database", json: { k: "v" } } },
    ours: { kind: "value", held: null },
    code: { kind: "value", held: null },
    why:
      "the key this reads past is missing from an object, and no page can hold the object for it to be missing from. No increment to our evaluator could change that",
  },
  {
    id: "dot-reads-two-steps",
    category: "substrate",
    covers: "a dotted path walks as many steps as it names",
    expression: "o.k.j",
    values: { o: { where: "database", json: { k: { j: 1 } } } },
    ours: { kind: "value", held: null },
    code: { kind: "value", held: "1" },
    why:
      "the second step lands in an object nested under `k`, and frontmatter carries nothing nested two deep for a walk to reach. No increment to our evaluator could change that",
  },
  {
    id: "dot-through-null-is-null",
    category: "agreed",
    covers: "a path step from null answers null rather than rejecting",
    expression: "o.k",
    values: { o: null },
    ours: { kind: "value", held: null },
    code: { kind: "value", held: null },
  },
  {
    id: "dot-null-part-way-along-is-null",
    category: "substrate",
    covers: "a null found part way along a path stops the walk and answers null",
    expression: "o.k.j",
    values: { o: { where: "database", json: { k: null } } },
    ours: { kind: "value", held: null },
    code: { kind: "value", held: null },
    why:
      "the null this stops on is a null standing inside an object, which only the database side can hold — a file has no way to write one. No increment to our evaluator could change that",
  },
  {
    id: "bracket-reads-an-object-property",
    category: "substrate",
    covers: "a bracket access reads a key given as a string literal",
    expression: 'o["k"]',
    values: { o: { where: "database", json: { k: "v" } } },
    ours: { kind: "value", held: null },
    code: { kind: "value", held: "v" },
    why:
      "the object a bracket reads into stands only on the database side, so a file poses nothing for the bracket to be built against. No increment to our evaluator could change that",
  },
  {
    id: "bracket-key-from-a-value",
    category: "substrate",
    covers: "a bracket access takes its key from any expression, which is what a dotted path cannot do",
    expression: "o[k]",
    values: { o: { where: "database", json: { a: "v" } }, k: "a" },
    ours: { kind: "value", held: null },
    code: { kind: "value", held: "v" },
    why:
      "what this case exists to show — a key taken from another value — needs an object to take that key into, and no file carries one. No increment to our evaluator could change that",
  },
  {
    id: "bracket-missing-key-is-null",
    category: "substrate",
    covers: "a bracket access onto a key the object lacks answers null",
    expression: 'o["z"]',
    values: { o: { where: "database", json: { k: "v" } } },
    ours: { kind: "value", held: null },
    code: { kind: "value", held: null },
    why:
      "the key this misses is missing from an object the file side cannot hold, so a file would pose the case with nothing to miss. No increment to our evaluator could change that",
  },
  {
    id: "bracket-on-null-is-null",
    category: "agreed",
    covers: "a bracket access on null answers null before any type is judged",
    expression: 'o["k"]',
    values: { o: null },
    ours: { kind: "value", held: null },
    code: { kind: "value", held: null },
  },
  {
    id: "bracket-with-a-null-key-is-null",
    category: "substrate",
    covers: "a null key answers null rather than rejecting as a non-string key would",
    expression: "o[k]",
    values: { o: { where: "database", json: { a: 1 } }, k: null },
    ours: { kind: "value", held: null },
    code: { kind: "value", held: null },
    why:
      "a null on either side short-circuits before any type is judged, but the object still has to stand there, and frontmatter cannot carry it. No increment to our evaluator could change that",
  },
  {
    id: "bracket-chains",
    category: "substrate",
    covers: "bracket access is postfix and stacks left to right",
    expression: 'o["a"]["b"]',
    values: { o: { where: "database", json: { a: { b: 2 } } } },
    ours: { kind: "value", held: null },
    code: { kind: "value", held: "2" },
    why:
      "stacking one bracket on the next needs an object inside an object, which is a level further than frontmatter reaches. No increment to our evaluator could change that",
  },
  {
    id: "bracket-key-is-a-whole-expression",
    category: "substrate",
    covers: "a bracket key is parsed as a full expression, operators and all",
    expression: "o[a || b]",
    values: { o: { where: "database", json: { p: 1 } }, a: "", b: "p" },
    ours: { kind: "value", held: null },
    code: { kind: "value", held: "1" },
    why:
      "the expression between the brackets resolves to a key of `o`, and `o` is an object no page can state. No increment to our evaluator could change that",
  },
  {
    id: "array-literal-empty",
    category: "agreed",
    covers: "an empty array literal is a value",
    expression: "[]",
    ours: { kind: "value", held: [] },
    code: { kind: "value", held: [] },
  },
  {
    id: "array-literal-of-numbers",
    category: "agreed",
    covers: "an array literal holds the values its elements evaluate to",
    expression: "[1,2]",
    ours: { kind: "value", held: ["1", "2"] },
    code: { kind: "value", held: ["1", "2"] },
  },
  {
    id: "array-literal-of-references",
    category: "agreed",
    covers: "an array literal's elements are expressions rather than literals",
    expression: "[a,b]",
    values: { a: 1, b: "x" },
    ours: { kind: "value", held: ["1", "x"] },
    code: { kind: "value", held: ["1", "x"] },
  },
  {
    id: "array-literal-equality-rejects",
    category: "agreed",
    covers: "two array literals never compare, and both sides reject on the same fault",
    expression: "[1] == [1]",
    ours: { kind: "refused", says: "`==` compares scalars only, and the left side is a list of 1 item" },
    code: { kind: "error", code: "equality_non_scalar" },
  },
  {
    id: "array-literal-nested-refuses",
    category: "refused",
    covers: "an array literal holding another array literal",
    expression: "[[1]]",
    ours: {
      kind: "refused",
      says: "a list literal holds scalars, and one item of this one is a list of 1 item",
    },
    code: { kind: "value", held: ["[1]"] },
    why: "our `Value` is a scalar or a flat list of scalars, so a list inside a list has nowhere to sit, and a page's frontmatter carries no nested list either, so a value of this shape could not be written onto a file even once evaluated",
  },
]
