import type { Case } from "../../lib/formula-conformance.ts"

const TEXT_ONLY =
  "frontmatter carries no numbers, so a file-side evaluator that kept every numeric-looking string a string could compare nothing at all; it reads such text as a number, and the reference keeps it a string"

const PLUS_ON_TEXT =
  "`+` concatenates where either side is already a string and adds otherwise, so it is the one arithmetic operator the two substrates part on: `- * / %` coerce both sides through Number() and agree, while `+` reads the file side's number and the reference's string and takes different branches"

const NO_BOOLEANS =
  "frontmatter carries no booleans, so the word `true` in a file and the boolean true in the database are indistinguishable from the file side; our evaluator refuses to pick rather than guessing"

export const SUBSTRATE_CASES: readonly Case[] = [
  {
    id: "numeric-text-orders-here",
    category: "substrate",
    covers: "text that reads as a number orders on the file side and rejects on the code side",
    expression: "a > b",
    values: { a: { where: "both", json: "12", held: "12" }, b: 0 },
    ours: { kind: "value", held: "true" },
    code: { kind: "error", code: "comparison_type_mismatch" },
    why: TEXT_ONLY,
  },
  {
    id: "negative-numeric-text-orders-here",
    category: "substrate",
    covers: "a leading minus is part of what the file side reads as a number",
    expression: "a > b",
    values: { a: { where: "both", json: "-5", held: "-5" }, b: 0 },
    ours: { kind: "value", held: "false" },
    code: { kind: "error", code: "comparison_type_mismatch" },
    why: TEXT_ONLY,
  },
  {
    id: "numeric-text-equals-a-number-here",
    category: "substrate",
    covers: "== is strict on the code side, so 1 and the string `1` differ there and match here",
    expression: "a == b",
    values: { a: 1, b: { where: "both", json: "1", held: "1" } },
    ours: { kind: "value", held: "true" },
    code: { kind: "value", held: "false" },
    why: TEXT_ONLY,
  },
  {
    id: "decimal-text-equals-a-number-here",
    category: "substrate",
    covers: "trailing zeros are lost where the file side reads text as a number",
    expression: "a == b",
    values: { a: { where: "both", json: "1.50", held: "1.50" }, b: 1.5 },
    ours: { kind: "value", held: "true" },
    code: { kind: "value", held: "false" },
    why: TEXT_ONLY,
  },
  {
    id: "a-text-literal-matches-numeric-text-there",
    category: "substrate",
    covers:
      "a text literal stays text on both sides, so it matches a string the database holds and misses the number the file side reads that same text as",
    expression: '"12" == a',
    values: { a: { where: "both", json: "12", held: "12" } },
    ours: { kind: "value", held: "false" },
    code: { kind: "value", held: "true" },
    why: TEXT_ONLY,
  },
  {
    id: "exponent-text-is-a-number-here",
    category: "substrate",
    covers: "exponent notation is read as a number on the file side",
    expression: "a == b",
    values: { a: { where: "both", json: "1e3", held: "1e3" }, b: 1000 },
    ours: { kind: "value", held: "true" },
    code: { kind: "value", held: "false" },
    why: TEXT_ONLY,
  },
  {
    id: "numeric-text-adds-here-and-concatenates-there",
    category: "substrate",
    covers: "text that reads as a number is added on the file side and joined on the code side",
    expression: "a + b",
    values: { a: { where: "both", json: "12", held: "12" }, b: 3 },
    ours: { kind: "value", held: "15" },
    code: { kind: "value", held: "123" },
    why: PLUS_ON_TEXT,
  },
  {
    id: "numeric-text-on-the-right-adds-here-and-concatenates-there",
    category: "substrate",
    covers: "the split falls on the right operand too, because either side being a string is enough to concatenate",
    expression: "a + b",
    values: { a: 3, b: { where: "both", json: "12", held: "12" } },
    ours: { kind: "value", held: "15" },
    code: { kind: "value", held: "312" },
    why: PLUS_ON_TEXT,
  },
  {
    id: "the-text-zero-is-falsy-here",
    category: "substrate",
    covers:
      "the string `0` is truthy in the language, and falsy on the file side, because the file side reads it as the number zero",
    expression: "a && b",
    values: { a: { where: "both", json: "0", held: "0" }, b: 5 },
    ours: { kind: "value", held: "0" },
    code: { kind: "value", held: "5" },
    why: TEXT_ONLY,
  },
  {
    id: "the-text-false-is-refused-here",
    category: "substrate",
    covers: "the string `false` is truthy in the language, and our evaluator refuses to read it either way",
    expression: "a && b",
    values: { a: { where: "both", json: "false", held: "false" }, b: 5 },
    ours: { kind: "refused", says: "a word to a file and a boolean to the database" },
    code: { kind: "value", held: "5" },
    why: NO_BOOLEANS,
  },
  {
    id: "a-false-value-is-refused-here",
    category: "substrate",
    covers: "a boolean false in the database is the word `false` in a file, and our evaluator will not pick",
    expression: "a || b",
    values: { a: false, b: 5 },
    ours: { kind: "refused", says: "a word to a file and a boolean to the database" },
    code: { kind: "value", held: "5" },
    why: NO_BOOLEANS,
  },
  {
    id: "a-true-value-is-refused-here",
    category: "substrate",
    covers: "a boolean true is refused for the same reason",
    expression: "a && b",
    values: { a: true, b: 5 },
    ours: { kind: "refused", says: "a word to a file and a boolean to the database" },
    code: { kind: "value", held: "5" },
    why: NO_BOOLEANS,
  },
  {
    id: "boolean-equality-is-refused-here",
    category: "substrate",
    covers: "two booleans compare on the code side and are refused here",
    expression: "a == b",
    values: { a: true, b: true },
    ours: { kind: "refused", says: "a word to a file and a boolean to the database" },
    code: { kind: "value", held: "true" },
    why: NO_BOOLEANS,
  },
  {
    id: "equality-is-left-associative",
    category: "substrate",
    covers:
      "== chains left to right, which only a boolean third operand can show: (1 == 1) == true is true, where 1 == (1 == true) would be false",
    expression: "a == b == c",
    values: { a: 1, b: 1, c: true },
    ours: { kind: "refused", says: "a word to a file and a boolean to the database" },
    code: { kind: "value", held: "true" },
    why: NO_BOOLEANS,
  },
  {
    id: "a-list-holding-the-word-true-is-refused-here",
    category: "substrate",
    covers: "a list is read item by item as any other held value is, so the word `true` inside one is as unreadable as the word `true` standing alone",
    expression: "count(a)",
    values: { a: ["true"] },
    ours: { kind: "refused", says: "item 1 of the list `a` holds `true`, which is a word to a file and a boolean to the database" },
    code: { kind: "value", held: "1" },
    why:
      "frontmatter carries no booleans inside a list any more than outside one, so the word `true` in a file and the boolean true in a database array cannot be told apart from the file side; our evaluator reads every item the moment the key is read, so it refuses here even though `count` would never have looked at the item",
  },
  {
    id: "an-object-value-reads-as-absent-here",
    category: "substrate",
    covers: "an object value is truthy on the code side and simply not on the file page at all",
    expression: "a || b",
    values: { a: { where: "database", json: { k: 1 } }, b: 5 },
    ours: { kind: "value", held: "5" },
    code: { kind: "value", held: '{"k":1}' },
    why: "frontmatter holds no nested object, so a property whose database value is one has no file counterpart and reads as absent",
  },
  {
    id: "non-finite-text-is-refused-here",
    category: "substrate",
    covers:
      "text can name a number too large to be finite, which the finite-number guard then rejects; the reference has no counterpart because JSON carries no infinity and `1e999` written out is a parse error",
    expression: "a > b",
    values: { a: { where: "file", held: "1e999" }, b: 0 },
    ours: { kind: "refused", says: "the left side is `Infinity`" },
    why: "only the file side can produce a non-finite number, because only it reads a value out of text",
  },
  {
    id: "the-answer-arrives-as-text",
    category: "substrate",
    covers:
      "our evaluator answers in what a file holds, so every answer is text or null; the runner compares the two sides through that same rendering rather than by type",
    expression: "a == b",
    values: { a: 1, b: 1 },
    ours: { kind: "value", held: "true" },
    code: { kind: "value", held: "true" },
    why: "a file page holds text, so a boolean answer comes back as the word `true`; this case records the rendering the whole table is compared through",
  },
]
