{"propertySlug":"import","fileName":"dockerfile-writing.module.code.ts","path":"infrastructure/container-image/dockerfile/modules/writing/dockerfile-writing.module.test.ts"}
{"propertySlug":"import","fileName":"dockerfile-writing.module.code.ts","path":"infrastructure/container-image/modules/image-build/image-build.module.code.ts"}
{"propertySlug":"parts","path":"infrastructure/container-image/dockerfile/dockerfile.domain.ts","id":"01a06865-abff-7000-a441-7a4caa49c9d9"}
