import type { TemperSet } from "akasha/temper/catalog/gear/temper-set/temper-set.page-type.types.ts"

export const swordSinger = {
  id: "019e66e7-6a97-7d21-9698-6f99a08a58fb",
  type: "page-type/temper-set",
  slug: "sword-singer",
  title: "Sword-Singer",
  key: "sword-singer",
  esoSetId: 283,
  hashPlace: 576,
  esoItemIds: [99283, 99284, 99288, 99289, 99290, 99298, 99299, 99300, 99301, 99302, 99303, 99304],
  esoArmorTypes: ["ARMORTYPE_MEDIUM"],
  esoEquipTypes: [
    "EQUIP_TYPE_CHEST",
    "EQUIP_TYPE_FEET",
    "EQUIP_TYPE_HAND",
    "EQUIP_TYPE_HEAD",
    "EQUIP_TYPE_LEGS",
    "EQUIP_TYPE_NECK",
    "EQUIP_TYPE_RING",
    "EQUIP_TYPE_SHOULDERS",
    "EQUIP_TYPE_TWO_HAND",
    "EQUIP_TYPE_WAIST",
  ],
  esoWeaponTypes: [
    "WEAPONTYPE_TWO_HANDED_AXE",
    "WEAPONTYPE_TWO_HANDED_HAMMER",
    "WEAPONTYPE_TWO_HANDED_SWORD",
  ],
  setWayshrines: [61, 61, 61],
  setTypeId: 9,
  setProcsAllowedInPvp: true,
  setNameZh: "剑咏者",
  setNameRu: "Певец меча",
  setNameFr: "Chante-épée",
  setNameEs: "Cantor de espada",
  setNameDe: "Schwertsänger",
  setDropZones: [104, 104, 308, 104, 104],
  setDropMechanics: [7, 8, 9, 10, 25],
  setDlcId: 0,
  itemBrowserSources: ["104"],
  itemBrowserPlaceKinds: [1],
  itemBrowserItemId: 99318,
  category: "temper-set-category/overland",
  valid: ["*:medium"],
  bonuses: "jsonl",
  icons: "jsonl",
} as const satisfies TemperSet
