import type { RecipeEntry } from "../recipe-types/recipe-types.module.code.ts"

export const RECIPE_ENTRIES_01: readonly RecipeEntry[] = [
  { itemId: 28281, name: "Banana Surprise" },
  { itemId: 28293, name: "Tomato Soup" },
  { itemId: 28305, name: "Banana Millet Muffin" },
  { itemId: 28317, name: "Fried Green Tomatoes" },
  { itemId: 28366, name: "Pumpkin Puree" },
  { itemId: 28378, name: "Bravil Melon Salad" },
  { itemId: 28390, name: "Stuffed Grape Leaves" },
  { itemId: 33490, name: "Garlic Pumpkin Seeds" },
  { itemId: 33508, name: "Cantaloupe Bread" },
  { itemId: 33552, name: "Redoran Peppered Melon" },
  { itemId: 33569, name: "Green Bananas with Garlic" },
  { itemId: 33587, name: "Stormhold Baked Bananas" },
  { itemId: 33789, name: "Cyrodilic Pumpkin Fritters" },
  { itemId: 33825, name: "Grape Preserves" },
  { itemId: 33837, name: "Baked Apples" },
  { itemId: 33843, name: "Melon Jelly" },
  { itemId: 33855, name: "Deshaan Honeydew Hors D'oeuvres" },
  { itemId: 33867, name: "Cinnamon Gorapples" },
  { itemId: 33879, name: "Clan Mother's Banana Pilaf" },
  { itemId: 33891, name: "Apple Cobbler Supreme" },
  { itemId: 33909, name: "Skyrim Jazbay Crostata" },
  { itemId: 33927, name: "Melon-Chevre Salad" },
  { itemId: 42790, name: "Cinnamon Grape Jelly" },
  { itemId: 42807, name: "Pumpkin Cheesecake" },
  { itemId: 42814, name: "Pellitine Tomato Rice" },
  { itemId: 43094, name: "Orcrest Garlic Apple Jelly" },
  { itemId: 43154, name: "Fresh Apples and Eidar Cheese" },
  { itemId: 57083, name: "Rimmen Raisin Cookies" },
  { itemId: 57086, name: "Kragenmoor Pickled Pumpkin" },
  { itemId: 57087, name: "Summer Sundas Soup" },
  { itemId: 57099, name: "Mage's Gorapple Porridge" },
  { itemId: 57100, name: "Mistral Banana Bread" },
  { itemId: 57112, name: "Hag Fen Pumpkin Pie" },
  { itemId: 57113, name: "Ordinator's Beetle-Cheese Soup" },
  { itemId: 57124, name: "Combwort Flatbread" },
  { itemId: 57125, name: "Honey Nut Treat" },
  { itemId: 57138, name: "House Hlaalu Pumpkin Risotto" },
  { itemId: 57139, name: "Bananas in Moon-Sugar Syrup" },
  { itemId: 57140, name: "Garlic Guar Stuffed Grape Leaves" },
  { itemId: 68236, name: "Firsthold Fruit and Cheese Plate" },
  { itemId: 68237, name: "Thrice-Baked Gorapple Pie" },
  { itemId: 68238, name: "Tomato Garlic Chutney" },
]
