import type { CompanionSkillTemplate } from "../companion-skill-activation-effect-types/companion-skill-activation-effect-types.module.code.ts"

export const COMPANION_SKILLS_05 = {
  "shared-crimson-font": {
    id: "shared-crimson-font" as const,
    abilityId: 155515,
    name: "Crimson Font",
    companionId: "all" as const,
    skillLineId: "guild-undaunted" as const,
    skillType: "active" as const,
    description:
      "Your Companion conjures a fountain of blood to sustain themselves and allies around it, healing for $1 Health every 1 second for 16 seconds. Allies near the fountain can activate the Crimson Funnel synergy, healing for 50% of their Max Health.",
    icon: "/esoui/art/icons/ability_companion_undaunted_001.dds",
    effects: [
      {
        "type": "hot",
        "target": { "type": "ally", "scope": "area", "radius": 28 },
        "formula": {
          "type": "metric-scaling",
          "metricId": "companion-weapon-damage",
          "coefficient": 3,
        },
        "duration": 16,
        "displayMode": "per-tick",
        "initialTick": true,
        "tickInterval": 1,
      },
      {
        "name": "Crimson Funnel",
        "type": "synergy",
        "effect": {
          "type": "heal",
          "target": { "type": "ally", "scope": "single" },
          "formula": { "type": "player-health-percent", "percent": 50 },
        },
      },
      { "type": "cast-time", "duration": 0.6 },
      { "type": "cooldown", "duration": 36 },
    ] as const,
    validRoles: ["healer"] as const,
    tags: ["synergy"] as const,
  },
  "shared-destructive-blast": {
    id: "shared-destructive-blast" as const,
    abilityId: 157131,
    name: "Destructive Blast",
    companionId: "all" as const,
    skillLineId: "weapon-destruction-staff" as const,
    skillType: "active" as const,
    description:
      "Your Companion blasts an enemy with magic, dealing $1 Magic Damage. Flame Blast knocks them back 8 meters and stuns them for $$3 seconds. Frost Blast taunts them for $$4 seconds. Shock Blast deals an additional $2 Shock Damage to all other enemies around them.",
    icon: "/esoui/art/icons/ability_companion_destructionstaff_005.dds",
    effects: [
      {
        "type": "damage",
        "target": { "type": "enemy", "range": 28, "scope": "single" },
        "formula": {
          "type": "metric-scaling",
          "metricId": "companion-weapon-damage",
          "coefficient": 3,
        },
        "damageType": "magic",
      },
      {
        "type": "apply-status",
        "status": { "status": "knockback", "distance": 8, "duration": 0 },
        "target": { "type": "enemy", "scope": "single" },
        "conditions": [{ "type": "weapon-type", "weaponType": "flame" }],
      },
      {
        "type": "apply-status",
        "status": { "status": "stun", "duration": 2.5 },
        "target": { "type": "enemy", "scope": "single" },
        "conditions": [{ "type": "weapon-type", "weaponType": "flame" }],
      },
      {
        "type": "apply-status",
        "status": { "status": "taunt", "duration": 15 },
        "target": { "type": "enemy", "scope": "single" },
        "conditions": [{ "type": "weapon-type", "weaponType": "frost" }],
      },
      {
        "type": "damage",
        "target": { "type": "enemy", "scope": "area" },
        "formula": {
          "type": "metric-scaling",
          "metricId": "companion-weapon-damage",
          "coefficient": 1.5,
        },
        "conditions": [{ "type": "weapon-type", "weaponType": "shock" }],
        "damageType": "shock",
      },
      { "type": "cast-time", "duration": 0.466 },
      { "type": "cooldown", "duration": 16 },
    ] as const,
    validRoles: ["dps", "tank"] as const,
    tags: ["elemental-variant"] as const,
  },
  "shared-elemental-barricade": {
    id: "shared-elemental-barricade" as const,
    abilityId: 157140,
    name: "Elemental Barricade",
    companionId: "all" as const,
    skillLineId: "weapon-destruction-staff" as const,
    skillType: "active" as const,
    description:
      "Your Companion slams their staff down to create an elemental wall in front of them, dealing $1 Magic Damage over $$1 seconds.",
    icon: "/esoui/art/icons/ability_companion_destructionstaff_002.dds",
    effects: [
      {
        "type": "dot",
        "target": { "type": "enemy", "range": 18, "scope": "area", "radius": 8 },
        "formula": {
          "type": "metric-scaling",
          "metricId": "companion-weapon-damage",
          "coefficient": 0.333,
          "coefficientType": "per-tick",
        },
        "duration": 8,
        "damageType": "magic",
        "displayMode": "total",
        "initialTick": true,
        "tickInterval": 1,
      },
      { "type": "cooldown", "duration": 8 },
    ] as const,
    validRoles: ["dps"] as const,
    tags: ["ground-aoe"] as const,
  },
  "shared-firmness": {
    id: "shared-firmness" as const,
    abilityId: 157730,
    name: "Firmness",
    companionId: "all" as const,
    skillLineId: "armor-heavy" as const,
    skillType: "passive" as const,
    description:
      "Increases healing received by 1% for each piece of Heavy Armor equipped. Increases damage blocked by 1% for each piece of Heavy Armor equipped.",
    icon: "/esoui/art/icons/passive_companion_armor_heavy.dds",
    effects: [
      {
        "type": "armor-piece-scaling",
        "metricId": "companion-healing-received",
        "armorWeight": "heavy",
        "valuePerPiece": 0.01,
      },
      {
        "type": "armor-piece-scaling",
        "metricId": "companion-damage-blocked",
        "armorWeight": "heavy",
        "valuePerPiece": 0.01,
      },
    ] as const,
    validRoles: [] as const,
  },
  "shared-flexibility": {
    id: "shared-flexibility" as const,
    abilityId: 157729,
    name: "Flexibility",
    companionId: "all" as const,
    skillLineId: "armor-medium" as const,
    skillType: "passive" as const,
    description:
      "Increases damage done by 1% for each piece of Medium Armor equipped. Decreases Roll Dodge cooldown by 5% for each piece of Medium Armor equipped.",
    icon: "/esoui/art/icons/passive_companion_armor_medium.dds",
    effects: [
      {
        "type": "armor-piece-scaling",
        "metricId": "companion-damage-done",
        "armorWeight": "medium",
        "valuePerPiece": 0.01,
      },
      {
        "type": "armor-piece-scaling",
        "metricId": "companion-roll-dodge-cooldown",
        "armorWeight": "medium",
        "valuePerPiece": -0.05,
      },
    ] as const,
    validRoles: [] as const,
  },
  "shared-flow": {
    id: "shared-flow" as const,
    abilityId: 157728,
    name: "Flow",
    companionId: "all" as const,
    skillLineId: "armor-light" as const,
    skillType: "passive" as const,
    description:
      "Increases healing done by 1% for each piece of Light Armor equipped. Decreases Break Free cooldown by 5% for each piece of Light Armor equipped.",
    icon: "/esoui/art/icons/passive_companion_armor_light.dds",
    effects: [
      {
        "type": "armor-piece-scaling",
        "metricId": "companion-healing-done",
        "armorWeight": "light",
        "valuePerPiece": 0.01,
      },
      {
        "type": "armor-piece-scaling",
        "metricId": "companion-break-free-cooldown",
        "armorWeight": "light",
        "valuePerPiece": -0.05,
      },
    ] as const,
    validRoles: [] as const,
  },
  "shared-haste": {
    id: "shared-haste" as const,
    abilityId: 156340,
    name: "Haste",
    companionId: "all" as const,
    skillLineId: "armor-light" as const,
    skillType: "active" as const,
    description:
      "Your Companion focuses their magical energies inward, resetting the cooldown of all their other abilities.",
    icon: "/esoui/art/icons/ability_companion_armor_light.dds",
    effects: [
      { "type": "cooldown-reduction", "scope": "other", "value": "reset" },
      { "type": "cast-time", "duration": 0.566 },
      { "type": "cooldown", "duration": 36 },
    ] as const,
    validRoles: [] as const,
  },
  "shared-mending-incantation": {
    id: "shared-mending-incantation" as const,
    abilityId: 153467,
    name: "Mending Incantation",
    companionId: "all" as const,
    skillLineId: "weapon-restoration-staff" as const,
    skillType: "active" as const,
    description:
      "Your Companion slams their staff down to activate its blessings, healing themselves and allies in front of them for $1 Health. The blessing also grants 7000 Spell and Physical Resistance for $$2 seconds.",
    icon: "/esoui/art/icons/ability_companion_restorationstaff_003.dds",
    effects: [
      {
        "type": "heal",
        "target": { "type": "ally", "range": 20, "scope": "area", "radius": 20 },
        "formula": {
          "type": "metric-scaling",
          "metricId": "companion-weapon-damage",
          "coefficient": 1.5,
        },
      },
      {
        "buff": { "buff": "flat-resistance", "value": 7000, "duration": 8, "valueType": "integer" },
        "type": "apply-buff",
        "target": { "type": "ally", "range": 20, "scope": "area", "radius": 20 },
      },
      { "type": "cast-time", "duration": 0.4 },
      { "type": "cooldown", "duration": 16 },
    ] as const,
    validRoles: ["healer", "tank", "support"] as const,
    tags: ["cone-aoe"] as const,
  },
  "shared-mystic-fortress": {
    id: "shared-mystic-fortress" as const,
    abilityId: 153685,
    name: "Mystic Fortress",
    companionId: "all" as const,
    skillLineId: "weapon-restoration-staff" as const,
    skillType: "active" as const,
    description:
      "Your Companion calls on their staff's strength to protect themselves or the lowest health ally around them, granting a damage shield that absorbs $1 damage over $$1 seconds.",
    icon: "/esoui/art/icons/ability_companion_restorationstaff_001.dds",
    effects: [
      {
        "type": "shield",
        "target": { "type": "self-or-ally", "range": 28, "scope": "single" },
        "formula": {
          "type": "metric-scaling",
          "metricId": "companion-weapon-damage",
          "coefficient": 9,
        },
        "duration": 6,
      },
      { "type": "cast-time", "duration": 0.6 },
      { "type": "cooldown", "duration": 8 },
    ] as const,
    validRoles: ["healer", "tank"] as const,
    castConditions: [{ "type": "health-threshold", "below": 25, "targetType": "self" }] as const,
  },
  "shared-on-guard": {
    id: "shared-on-guard" as const,
    abilityId: 155328,
    name: "On Guard",
    companionId: "all" as const,
    skillLineId: "weapon-one-hand-shield" as const,
    skillType: "active" as const,
    description:
      "Your Companion bolsters their defenses, granting a damage shield that absorbs up to 25% of their Max Health for $$1 seconds.",
    icon: "/esoui/art/icons/ability_companion_1handed_004.dds",
    effects: [
      {
        "type": "shield",
        "target": { "type": "self", "scope": "single" },
        "formula": {
          "type": "metric-percent",
          "percent": 25,
          "metricId": "companion-health-maximum",
        },
        "duration": 6,
      },
      { "type": "cast-time", "duration": 0.566 },
      { "type": "cooldown", "duration": 8 },
    ] as const,
    validRoles: ["tank"] as const,
    tags: ["max-health-shield-25pct"] as const,
  },
  "shared-parallel": {
    id: "shared-parallel" as const,
    abilityId: 155411,
    name: "Parallel",
    companionId: "all" as const,
    skillLineId: "guild-mages" as const,
    skillType: "active" as const,
    description: "Your Companion barters with Oblivion for power, generating 50 Ultimate.",
    icon: "/esoui/art/icons/ability_companion_mageguild_003.dds",
    effects: [
      {
        "type": "ultimate-generation",
        "value": 50,
        "target": { "type": "self", "scope": "single" },
      },
      { "type": "cast-time", "duration": 0.566 },
      { "type": "cooldown", "duration": 16 },
    ] as const,
    validRoles: [] as const,
  },
  "shared-piercing-arrow": {
    id: "shared-piercing-arrow" as const,
    abilityId: 152793,
    name: "Piercing Arrow",
    companionId: "all" as const,
    skillLineId: "weapon-bow" as const,
    skillType: "active" as const,
    description:
      "Your Companion plants a masterfully aimed arrow in an enemy's vital spot, dealing $1 Physical Damage.",
    icon: "/esoui/art/icons/ability_companion_bow_001.dds",
    effects: [
      {
        "type": "damage",
        "target": { "type": "enemy", "range": 35, "scope": "single" },
        "formula": {
          "type": "metric-scaling",
          "metricId": "companion-weapon-damage",
          "coefficient": 3,
        },
        "damageType": "physical",
      },
      { "type": "cast-time", "duration": 1 },
      { "type": "cooldown", "duration": 8 },
    ] as const,
    validRoles: ["dps"] as const,
  },
  "shared-provoke": {
    id: "shared-provoke" as const,
    abilityId: 152625,
    name: "Provoke",
    companionId: "all" as const,
    skillLineId: "weapon-one-hand-shield" as const,
    skillType: "active" as const,
    description:
      "Your Companion thrusts their weapon with disciplined precision at an enemy, dealing $1 Physical Damage and taunting the enemy to attack them for $$2 seconds.",
    icon: "/esoui/art/icons/ability_companion_1handed_002.dds",
    effects: [
      {
        "type": "damage",
        "target": { "type": "enemy", "range": 5, "scope": "single" },
        "formula": {
          "type": "metric-scaling",
          "metricId": "companion-weapon-damage",
          "coefficient": 1.5,
        },
        "damageType": "physical",
      },
      {
        "type": "apply-status",
        "status": { "status": "taunt", "duration": 15 },
        "target": { "type": "enemy", "range": 5, "scope": "single" },
      },
      { "type": "cast-time", "duration": 0.3 },
      { "type": "cooldown", "duration": 12 },
    ] as const,
    validRoles: ["dps", "tank"] as const,
  },
} as const satisfies Record<string, CompanionSkillTemplate>
