import type { Domain } from "akasha/domain/domain.page-type.types.ts"

export const changeAgentFileContent = {
  id: "01a07cc2-6223-7b0c-8d18-b219118df387",
  type: "page-type/domain",
  slug: "change-agent-file-content",
  definition: "a change an agent reaches acting on what a file has",
  parts: [
    "change-agent/add-property-record",
    "change-agent/add-property-values",
    "change-agent/append-lines",
    "change-agent/append-lines-from",
    "change-agent/change-domain-parent",
    "change-agent/change-file",
    "change-agent/change-page-page-property",
    "change-agent/change-page-page-property-text",
    "change-agent/change-property-record-field",
    "change-agent/gather-merging-declarations",
    "change-agent/move-code-export",
    "change-agent/move-property-value",
    "change-agent/remove-property-record",
    "change-agent/remove-property-value",
    "change-agent/remove-unused-export-keywords",
    "change-agent/rename-code-token",
    "change-agent/rename-folder-imports",
    "change-agent/name-ambient-declarations",
    "change-agent/point-book-links-at-sections",
    "change-agent/add-property-to-pages",
    "change-agent/rename-spellings",
    "change-agent/point-track-credits-at-artists",
  ],
} as const satisfies Domain
