import type { HudComponentRecord } from "../hud-component-record/hud-component-record.module.code.ts"
import { HUD_SCENE_SOURCE } from "../hud-scene-source/hud-scene-source.module.code.ts"

export const HUD_CONTROLS = [
  {
    id: "compass-frame",
    name: "Compass frame (control)",
    esoGlobal: "COMPASS_FRAME",
    kind: "non-fragment-control",
    hideMechanism: "SetCompassHidden",
    scenes: ["hud", "hudui", "loot"],
    category: "compass",
    source: { file: HUD_SCENE_SOURCE, line: 23 },
    conditional: false,
    wrapsMultiple: false,
    grainNotes:
      "Bare control given a death-state hide; overlaps COMPASS_FRAME_FRAGMENT (the scene seam).",
  },
  {
    id: "player-to-player",
    name: "Player-to-player interaction prompt",
    esoGlobal: "PLAYER_TO_PLAYER",
    kind: "non-fragment-control",
    hideMechanism: "SetTopLevelHidden",
    scenes: ["hud", "hudui", "loot"],
    category: "interaction",
    source: { file: HUD_SCENE_SOURCE, line: 25 },
    conditional: false,
    wrapsMultiple: false,
  },
  {
    id: "tutorial-system",
    name: "HUD tutorial info box",
    esoGlobal: "TUTORIAL_SYSTEM",
    kind: "non-fragment-control",
    hideMechanism: "SuppressTutorialType",
    scenes: ["hud", "hudui", "loot"],
    category: "tutorial",
    source: { file: HUD_SCENE_SOURCE, line: 26 },
    conditional: false,
    wrapsMultiple: false,
    grainNotes: "Suppressed (TUTORIAL_TYPE_HUD_INFO_BOX) rather than hidden as a control.",
  },
  {
    id: "instance-kick-warning-dead",
    name: "Instance kick warning",
    esoGlobal: "INSTANCE_KICK_WARNING_DEAD",
    kind: "non-fragment-control",
    hideMechanism: "SetHiddenForReason",
    scenes: ["hud", "hudui", "loot"],
    category: "warning",
    source: { file: HUD_SCENE_SOURCE, line: 27 },
    conditional: false,
    wrapsMultiple: false,
  },
  {
    id: "hud-raid-life",
    name: "Raid life display",
    esoGlobal: "HUD_RAID_LIFE",
    kind: "non-fragment-control",
    hideMechanism: "SetHiddenForReason",
    scenes: ["hud", "hudui", "loot"],
    category: "meter",
    source: { file: HUD_SCENE_SOURCE, line: 28 },
    conditional: false,
    wrapsMultiple: false,
  },
  {
    id: "gamepad-chat-system",
    name: "Chat (gamepad HUD)",
    esoGlobal: "GAMEPAD_CHAT_SYSTEM",
    kind: "non-fragment-control",
    hideMechanism: "RefreshVisibility",
    scenes: ["hud", "hudui", "loot"],
    category: "chat",
    source: { file: HUD_SCENE_SOURCE, line: 30 },
    conditional: true,
    wrapsMultiple: false,
    grainNotes: "RefreshVisibility only when ShouldOnlyShowOnHUD (conditional).",
  },
  {
    id: "objective-capture-meter",
    name: "Objective capture meter",
    esoGlobal: "OBJECTIVE_CAPTURE_METER",
    kind: "non-fragment-control",
    hideMechanism: "SetHiddenForReason",
    scenes: ["hud", "hudui", "loot"],
    category: "meter",
    source: { file: HUD_SCENE_SOURCE, line: 33 },
    conditional: false,
    wrapsMultiple: false,
  },
  {
    id: "floating-markers",
    name: "Floating world markers",
    esoGlobal: "FLOATING_MARKERS",
    kind: "non-fragment-control",
    hideMechanism: "SetFloatingMarkerGlobalAlpha",
    scenes: ["hud", "hudui", "loot"],
    category: "markers",
    source: { file: HUD_SCENE_SOURCE, line: 34 },
    conditional: false,
    wrapsMultiple: false,
    grainNotes: "Hidden via the SetFloatingMarkerGlobalAlpha global — no control handle.",
  },
  {
    id: "shared-information-area",
    name: "Shared information area",
    esoGlobal: "SHARED_INFORMATION_AREA",
    kind: "non-fragment-control",
    hideMechanism: "SetSupressed",
    scenes: ["hud", "hudui", "loot"],
    category: "info-area",
    source: { file: HUD_SCENE_SOURCE, line: 35 },
    conditional: false,
    wrapsMultiple: false,
  },
  {
    id: "reticle",
    name: "Reticle",
    esoGlobal: "RETICLE",
    kind: "non-fragment-control",
    hideMechanism: "RequestHidden",
    scenes: ["hud", "hudui", "loot"],
    category: "reticle",
    source: { file: HUD_SCENE_SOURCE, line: 36 },
    conditional: false,
    wrapsMultiple: false,
  },
  {
    id: "hud-infamy-meter",
    name: "Infamy / bounty meter",
    esoGlobal: "HUD_INFAMY_METER",
    kind: "non-fragment-control",
    hideMechanism: "RequestHidden",
    scenes: ["hud", "hudui", "loot"],
    category: "meter",
    source: { file: HUD_SCENE_SOURCE, line: 37 },
    conditional: false,
    wrapsMultiple: false,
  },
  {
    id: "hud-telvar-meter",
    name: "Tel Var stone meter",
    esoGlobal: "HUD_TELVAR_METER",
    kind: "non-fragment-control",
    hideMechanism: "SetHiddenForReason",
    scenes: ["hud", "hudui", "loot"],
    category: "meter",
    source: { file: HUD_SCENE_SOURCE, line: 38 },
    conditional: false,
    wrapsMultiple: false,
  },
  {
    id: "hud-daedric-energy-meter",
    name: "Daedric energy meter",
    esoGlobal: "HUD_DAEDRIC_ENERGY_METER",
    kind: "non-fragment-control",
    hideMechanism: "SetHiddenForReason",
    scenes: ["hud", "hudui", "loot"],
    category: "meter",
    source: { file: HUD_SCENE_SOURCE, line: 39 },
    conditional: false,
    wrapsMultiple: false,
  },
] as const satisfies readonly HudComponentRecord[]
