import type { GlobalTable } from "../map-pins-casts/map-pins-casts.module.code.ts"

import {
  LIBMAPPINS_AVA_IMPERIAL_MAPGROUP,
  LIBMAPPINS_AVA_MAPGROUP,
  LIBMAPPINS_BATTLEGROUND_MAPGROUP,
  LIBMAPPINS_PIN_ACTION_GROUP_FAST_TRAVEL,
  LIBMAPPINS_PIN_ACTION_GROUP_QUEST,
  LIBMAPPINS_PIN_ACTION_GROUP_RESPAWN,
  LIBMAPPINS_PVE_MAPGROUP,
} from "../map-pins-constants/map-pins-constants.module.code.ts"
import { LIB } from "../map-pins-lib/map-pins-lib.module.code.ts"

const glob = globalThis as GlobalTable

glob.LIBMAPPINS_PVE_MAPGROUP = LIBMAPPINS_PVE_MAPGROUP
glob.LIBMAPPINS_AVA_MAPGROUP = LIBMAPPINS_AVA_MAPGROUP
glob.LIBMAPPINS_AVA_IMPERIAL_MAPGROUP = LIBMAPPINS_AVA_IMPERIAL_MAPGROUP
glob.LIBMAPPINS_BATTLEGROUND_MAPGROUP = LIBMAPPINS_BATTLEGROUND_MAPGROUP

glob.LIBMAPPINS_PIN_ACTION_GROUP_QUEST = LIBMAPPINS_PIN_ACTION_GROUP_QUEST
glob.LIBMAPPINS_PIN_ACTION_GROUP_FAST_TRAVEL = LIBMAPPINS_PIN_ACTION_GROUP_FAST_TRAVEL
glob.LIBMAPPINS_PIN_ACTION_GROUP_RESPAWN = LIBMAPPINS_PIN_ACTION_GROUP_RESPAWN

glob.LibMapPins = LIB
