import type { SetTemplate } from "@akasha/temper-equipment/set-template"

export const SETS_DATA_050: readonly SetTemplate[] = [
  {
    id: "kragh",
    name: "Kra'gh",
    esoSetId: 266,
    subcategoryId: "monster",
    valid: ["monster"],
    bonuses: [
      {
        count: 1,
        status: "supported",
        effects: [{ metricId: "penetration", effectType: "integer", effectValue: 1487 }],
        description: "Adds 1487 Offensive Penetration",
      },
      {
        count: 2,
        status: "unsupported",
        effects: [],
        description:
          "When you deal damage, you have a 10% chance to spawn dreugh limbs that create shockwaves in front of you dealing 249 Physical damage every 0.6 seconds for 2.4 seconds. This effect can occur once every 6 seconds and scales off the higher of your Weapon or Spell Damage.",
      },
    ],
    icons: {
      "head:heavy": "/esoui/art/icons/gear_undaunteddreugh_head_a.dds",
      "head:light": "/esoui/art/icons/gear_undaunteddreugh_head_a.dds",
      "head:medium": "/esoui/art/icons/gear_undaunteddreugh_head_a.dds",
      "shoulders:heavy": "/esoui/art/icons/gear_undaunteddreugh_shoulders_a.dds",
      "shoulders:light": "/esoui/art/icons/gear_undaunteddreugh_shoulders_a.dds",
      "shoulders:medium": "/esoui/art/icons/gear_undaunteddreugh_shoulders_a.dds",
    },
  },
  {
    id: "kraglens-howl",
    name: "Kraglen's Howl",
    esoSetId: 517,
    subcategoryId: "dungeon",
    valid: ["*:medium"],
    bonuses: [
      {
        count: 2,
        status: "supported",
        effects: [{ metricId: "critical-rating", effectType: "integer", effectValue: 657 }],
        description: "Adds 657 Critical Chance",
      },
      {
        count: 3,
        status: "supported",
        effects: [{ metricId: "stamina-recovery", effectType: "integer", effectValue: 129 }],
        description: "Adds 129 Stamina Recovery",
      },
      {
        count: 4,
        status: "supported",
        effects: [{ metricId: "power", effectType: "integer", effectValue: 129 }],
        description: "Adds 129 Weapon and Spell Damage",
      },
      {
        count: 5,
        status: "unsupported",
        effects: [],
        description:
          "After an enemy you've recently damaged dies, you let out a howl, granting three allies within 15 meters the Heed the Call synergy. Activating the synergy gives you and the activator 12 Ultimate. This effect can occur once every 20 seconds.",
      },
    ],
    icons: {
      "axe": "/esoui/art/icons/gear_northlandsalch_1haxe_a.dds",
      "battleaxe": "/esoui/art/icons/gear_northlandsalch_2haxe_a.dds",
      "bow": "/esoui/art/icons/gear_northlandsalch_bow_a.dds",
      "chest:*": "/esoui/art/icons/gear_northlandsalchmed_chest_a.dds",
      "dagger": "/esoui/art/icons/gear_northlandsalch_dagger_a.dds",
      "feet:*": "/esoui/art/icons/gear_northlandsalchmed_feet_a.dds",
      "greatsword": "/esoui/art/icons/gear_northlandsalch_2hsword_a.dds",
      "hands:*": "/esoui/art/icons/gear_northlandsalchmed_hands_a.dds",
      "head:*": "/esoui/art/icons/gear_northlandsalchmed_head_a.dds",
      "ice-staff": "/esoui/art/icons/gear_northlandsalch_staff_a.dds",
      "inferno-staff": "/esoui/art/icons/gear_northlandsalch_staff_a.dds",
      "legs:*": "/esoui/art/icons/gear_northlandsalchmed_legs_a.dds",
      "lightning-staff": "/esoui/art/icons/gear_northlandsalch_staff_a.dds",
      "mace": "/esoui/art/icons/gear_northlandsalch_1hhammer_a.dds",
      "maul": "/esoui/art/icons/gear_northlandsalch_2hhammer_a.dds",
      "necklace": "/esoui/art/icons/gear_breton_neck_a.dds",
      "restoration-staff": "/esoui/art/icons/gear_northlandsalch_staff_a.dds",
      "ring": "/esoui/art/icons/gear_breton_ring_a.dds",
      "shield": "/esoui/art/icons/gear_northlandsalch_shield_a.dds",
      "shoulders:*": "/esoui/art/icons/gear_northlandsalchmed_shoulder_a.dds",
      "sword": "/esoui/art/icons/gear_northlandsalch_1hsword_a.dds",
      "waist:*": "/esoui/art/icons/gear_northlandsalchmed_waist_a.dds",
    },
  },
  {
    id: "kvatch-gladiator",
    name: "Kvatch Gladiator",
    esoSetId: 240,
    subcategoryId: "crafted",
    valid: ["*"],
    bonuses: [
      {
        count: 2,
        status: "supported",
        effects: [{ metricId: "critical-rating", effectType: "integer", effectValue: 657 }],
        description: "Adds 657 Critical Chance",
      },
      {
        count: 3,
        status: "supported",
        effects: [{ metricId: "critical-rating", effectType: "integer", effectValue: 657 }],
        description: "Adds 657 Critical Chance",
      },
      {
        count: 4,
        status: "supported",
        effects: [{ metricId: "power", effectType: "integer", effectValue: 129 }],
        description: "Adds 129 Weapon and Spell Damage",
      },
      {
        count: 5,
        status: "unsupported",
        effects: [],
        description:
          "You gain 1475 Weapon and Spell Damage against targets who are at or below 25% Health.",
      },
    ],
    icons: {
      "axe": "/esoui/art/icons/gear_breton_1haxe_d.dds",
      "battleaxe": "/esoui/art/icons/gear_breton_2haxe_d.dds",
      "bow": "/esoui/art/icons/gear_breton_bow_d.dds",
      "chest:heavy": "/esoui/art/icons/gear_breton_heavy_chest_d.dds",
      "chest:light": "/esoui/art/icons/gear_breton_light_robe_d.dds",
      "chest:medium": "/esoui/art/icons/gear_breton_medium_chest_d.dds",
      "dagger": "/esoui/art/icons/gear_breton_dagger_d.dds",
      "feet:heavy": "/esoui/art/icons/gear_breton_heavy_feet_d.dds",
      "feet:light": "/esoui/art/icons/gear_breton_light_feet_d.dds",
      "feet:medium": "/esoui/art/icons/gear_breton_medium_feet_d.dds",
      "greatsword": "/esoui/art/icons/gear_breton_2hsword_d.dds",
      "hands:heavy": "/esoui/art/icons/gear_breton_heavy_hands_d.dds",
      "hands:light": "/esoui/art/icons/gear_breton_light_hands_d.dds",
      "hands:medium": "/esoui/art/icons/gear_breton_medium_hands_d.dds",
      "head:heavy": "/esoui/art/icons/gear_breton_heavy_head_d.dds",
      "head:light": "/esoui/art/icons/gear_breton_light_head_d.dds",
      "head:medium": "/esoui/art/icons/gear_breton_medium_head_d.dds",
      "ice-staff": "/esoui/art/icons/gear_breton_staff_d.dds",
      "inferno-staff": "/esoui/art/icons/gear_breton_staff_d.dds",
      "legs:heavy": "/esoui/art/icons/gear_breton_heavy_legs_d.dds",
      "legs:light": "/esoui/art/icons/gear_breton_light_legs_d.dds",
      "legs:medium": "/esoui/art/icons/gear_breton_medium_legs_d.dds",
      "lightning-staff": "/esoui/art/icons/gear_breton_staff_d.dds",
      "mace": "/esoui/art/icons/gear_breton_1hhammer_d.dds",
      "maul": "/esoui/art/icons/gear_breton_2hhammer_d.dds",
      "necklace": "/esoui/art/icons/gear_breton_neck_a.dds",
      "restoration-staff": "/esoui/art/icons/gear_breton_staff_d.dds",
      "ring": "/esoui/art/icons/gear_breton_ring_a.dds",
      "shield": "/esoui/art/icons/gear_breton_shield_d.dds",
      "shoulders:heavy": "/esoui/art/icons/gear_breton_heavy_shoulders_d.dds",
      "shoulders:light": "/esoui/art/icons/gear_breton_light_shoulders_d.dds",
      "shoulders:medium": "/esoui/art/icons/gear_breton_medium_shoulders_d.dds",
      "sword": "/esoui/art/icons/gear_breton_1hsword_d.dds",
      "waist:heavy": "/esoui/art/icons/gear_breton_heavy_waist_d.dds",
      "waist:light": "/esoui/art/icons/gear_breton_light_waist_d.dds",
      "waist:medium": "/esoui/art/icons/gear_breton_medium_waist_d.dds",
    },
  },
  {
    id: "kynes-kiss",
    name: "Kyne's Kiss",
    esoSetId: 59,
    subcategoryId: "pvp",
    valid: ["*:medium"],
    bonuses: [
      {
        count: 2,
        status: "supported",
        effects: [{ metricId: "stamina-maximum", effectType: "integer", effectValue: 1096 }],
        description: "Adds 1096 Maximum Stamina",
      },
      {
        count: 3,
        status: "supported",
        effects: [{ metricId: "stamina-recovery", effectType: "integer", effectValue: 129 }],
        description: "Adds 129 Stamina Recovery",
      },
      {
        count: 4,
        status: "supported",
        effects: [{ metricId: "critical-rating", effectType: "integer", effectValue: 657 }],
        description: "Adds 657 Critical Chance",
      },
      {
        count: 5,
        status: "unsupported",
        effects: [],
        description:
          "When you deal direct damage while 12 meters or further from your target, you heal for 543 Health and restore 1314 Stamina.  This effect can occur once every 5 seconds and the heal scales off the higher of your Max Magicka or Stamina.",
      },
    ],
    icons: {
      "axe": "/esoui/art/icons/gear_breton_1haxe_d.dds",
      "battleaxe": "/esoui/art/icons/gear_breton_2haxe_d.dds",
      "bow": "/esoui/art/icons/gear_breton_bow_d.dds",
      "chest:*": "/esoui/art/icons/gear_nord_medium_chest_d.dds",
      "dagger": "/esoui/art/icons/gear_breton_dagger_d.dds",
      "feet:*": "/esoui/art/icons/gear_nord_medium_feet_d.dds",
      "greatsword": "/esoui/art/icons/gear_breton_2hsword_d.dds",
      "hands:*": "/esoui/art/icons/gear_nord_medium_hands_d.dds",
      "head:*": "/esoui/art/icons/gear_nord_medium_head_d.dds",
      "ice-staff": "/esoui/art/icons/gear_breton_staff_d.dds",
      "inferno-staff": "/esoui/art/icons/gear_breton_staff_d.dds",
      "legs:*": "/esoui/art/icons/gear_nord_medium_legs_d.dds",
      "lightning-staff": "/esoui/art/icons/gear_breton_staff_d.dds",
      "mace": "/esoui/art/icons/gear_breton_1hhammer_d.dds",
      "maul": "/esoui/art/icons/gear_breton_2hhammer_d.dds",
      "necklace": "/esoui/art/icons/gear_breton_neck_a.dds",
      "restoration-staff": "/esoui/art/icons/gear_breton_staff_d.dds",
      "ring": "/esoui/art/icons/gear_breton_ring_a.dds",
      "shield": "/esoui/art/icons/gear_breton_shield_d.dds",
      "shoulders:*": "/esoui/art/icons/gear_nord_medium_shoulders_d.dds",
      "sword": "/esoui/art/icons/gear_breton_1hsword_d.dds",
      "waist:*": "/esoui/art/icons/gear_nord_medium_waist_d.dds",
    },
  },
  {
    id: "kynes-wind",
    name: "Kyne's Wind",
    esoSetId: 492,
    subcategoryId: "trial",
    valid: ["*:light"],
    bonuses: [
      {
        count: 2,
        status: "supported",
        effects: [{ metricId: "magicka-recovery", effectType: "integer", effectValue: 129 }],
        description: "Adds 129 Magicka Recovery",
      },
      {
        count: 3,
        status: "unsupported",
        effects: [],
        description:
          "Gain Minor Aegis at all times, reducing your damage taken from Dungeon, Trial, and Arena Monsters by 5%.",
      },
      {
        count: 4,
        status: "supported",
        effects: [
          { metricId: "healing-done-base", effectType: "fractional-change", effectValue: 0.04 },
        ],
        description: "Adds 4% Healing Done",
      },
      {
        count: 5,
        status: "unsupported",
        effects: [],
        description:
          "When you overheal yourself or a group member, you create a pool of Kyne's Blessing under the target for 4 seconds. You and group members standing in Kyne's Blessing restore 420 Stamina and Magicka every 1 second. This effect can occur once every 10 seconds.",
      },
    ],
    icons: {
      "axe": "/esoui/art/icons/gear_seagiant_axe.dds",
      "battleaxe": "/esoui/art/icons/gear_seagiant_2haxe.dds",
      "bow": "/esoui/art/icons/gear_seagiant_bow.dds",
      "chest:*": "/esoui/art/icons/gear_seagiant_robe_a.dds",
      "dagger": "/esoui/art/icons/gear_seagiant_dagger.dds",
      "feet:*": "/esoui/art/icons/gear_seagiantlgt_feet.dds",
      "greatsword": "/esoui/art/icons/gear_seagiant_2hsword.dds",
      "hands:*": "/esoui/art/icons/gear_seagiantlgt_hands.dds",
      "head:*": "/esoui/art/icons/gear_seagiantlgt_helmet.dds",
      "ice-staff": "/esoui/art/icons/gear_seagiant_staff.dds",
      "inferno-staff": "/esoui/art/icons/gear_seagiant_staff.dds",
      "legs:*": "/esoui/art/icons/gear_seagiantlgt_legs.dds",
      "lightning-staff": "/esoui/art/icons/gear_seagiant_staff.dds",
      "mace": "/esoui/art/icons/gear_seagiant_mace.dds",
      "maul": "/esoui/art/icons/gear_seagiant_2hmace.dds",
      "necklace": "/esoui/art/icons/gear_breton_neck_a.dds",
      "restoration-staff": "/esoui/art/icons/gear_seagiant_staff.dds",
      "ring": "/esoui/art/icons/gear_breton_ring_a.dds",
      "shield": "/esoui/art/icons/gear_seagiant_shield.dds",
      "shoulders:*": "/esoui/art/icons/gear_seagiantlgt_shoulders.dds",
      "sword": "/esoui/art/icons/gear_seagiant_sword.dds",
      "waist:*": "/esoui/art/icons/gear_seagiantlgt_waist.dds",
    },
  },
]
