declare const STABLES_SCENE: Scene
declare const ZO_StablePanelSpeedTrainRowTrainButton: Control
declare const ZO_StablePanelStaminaTrainRowTrainButton: Control
declare const ZO_StablePanelCarryTrainRowTrainButton: Control
