import type { StoryTurnPlayed } from "akasha/story/world/stories/played/turns/story-turn-played.page-type.types.ts"

export const otherwhereVi00006 = {
  id: "01a0ea57-6ad0-7c2d-b410-9c6dcd93d316",
  type: "page-type/story-turn-played",
  slug: "otherwhere-vi-00-006",
  ownLength: 311,
  unit: "unit/words",
  partOfCollections: ["story-played/otherwhere-vi"],
  position: 6,
  prose: "txt",
  characters: ["character-player/otherwhere-vi-nala"],
  stepStatus: "step-status/reviewers",
  action: "I circle wide around the boars and continue downstream",
  beats: [
    "Nala backs away from the mud and turns up the west slope into the pines, to go round wide.",
    "Under the pines it is near black; the slope is steep and laced with roots.",
    "She climbs slowly, staff planted uphill, the stone in her other hand, the grunting below her.",
    "She keeps well up the slope; below, the big one huffs once, loud, and then goes quiet.",
    "Halfway round, a wind-thrown pine lies across the slope, chest-high, its roots a wall of earth.",
    "She braces the staff and sets one bare foot on a broken stub of branch to climb over the trunk.",
    "The stub snaps under her; her foot skids on the bark and she pitches backward off the trunk.",
    "She hits the slope and goes sliding and rolling down through roots and loose stones.",
    "The stone flies out of her hand; somehow she keeps her grip on the staff.",
    "She fetches up hard against a root near the foot of the slope, the mud and alders close below.",
    "Pain everywhere at once: her hip, an elbow, a burning scrape down one shin.",
    "【HP -11】",
    "Below her the four small ones squeal all together and scramble in behind the big one.",
    "The big one huffs, clacks her teeth with a hard wooden sound, and comes at her through the mud.",
    "She is low, bristled and heavy, and she is fast.",
    "She stops short a few lengths off, head down, blowing hard through her snout.",
    "Her small eyes catch the moonlight; she clacks her teeth again and stands there.",
  ],
  issues: [
    '"She clacks her teeth" - Nala has only seen "the big one"; its being a sow is not hers to know',
  ],
  lore: ["place/otherwhere-vi-hollow-stream"],
  reviewedBy: ["story-reviewer/continuity"],
  endsAt: "2026-09-28T22:17:00.000Z",
} as const satisfies StoryTurnPlayed
