import type { CompanionSkillTemplate } from "../companion-skill-activation-effect-types/companion-skill-activation-effect-types.module.code.ts"

export const COMPANION_SKILLS_07 = {
  "shared-swift-assault": {
    id: "shared-swift-assault" as const,
    abilityId: 152629,
    name: "Swift Assault",
    companionId: "all" as const,
    skillLineId: "weapon-dual-wield" as const,
    skillType: "active" as const,
    description:
      "Your Companion floods an enemy with steel, battering them with five consecutive attacks that each deal $1 Physical Damage.",
    icon: "/esoui/art/icons/ability_companion_dualwield_002.dds",
    effects: [
      {
        "type": "multi-hit",
        "target": { "type": "enemy", "range": 5, "scope": "single" },
        "formula": {
          "type": "metric-scaling",
          "metricId": "companion-weapon-damage",
          "coefficient": 0.6,
        },
        "hitCount": 5,
        "damageType": "physical",
      },
      { "type": "channel", "duration": 0.6 },
      { "type": "cooldown", "duration": 8 },
    ] as const,
    validRoles: ["dps"] as const,
  },
  "shared-trick-shot": {
    id: "shared-trick-shot" as const,
    abilityId: 152701,
    name: "Trick Shot",
    companionId: "all" as const,
    skillLineId: "weapon-bow" as const,
    skillType: "active" as const,
    description:
      "Your Companion fires a burst of arrows to pin enemies in front of them, dealing $1 Physical Damage and immobilizing them for $$2 seconds.",
    icon: "/esoui/art/icons/ability_companion_bow_005.dds",
    effects: [
      {
        "type": "damage",
        "target": { "type": "enemy", "scope": "cone", "radius": 20 },
        "formula": {
          "type": "metric-scaling",
          "metricId": "companion-weapon-damage",
          "coefficient": 1.5,
        },
        "damageType": "physical",
      },
      {
        "type": "apply-status",
        "status": { "status": "immobilize", "duration": 4 },
        "target": { "type": "enemy", "scope": "cone", "radius": 20 },
      },
      { "type": "cast-time", "duration": 0.166 },
      { "type": "cooldown", "duration": 16 },
    ] as const,
    validRoles: ["dps"] as const,
  },
  "shared-vanish": {
    id: "shared-vanish" as const,
    abilityId: 156596,
    name: "Vanish",
    companionId: "all" as const,
    skillLineId: "armor-medium" as const,
    skillType: "active" as const,
    description:
      "Your Companion disappears in a puff of smoke, healing to full Health and becoming invisible for $$2 seconds.",
    icon: "/esoui/art/icons/ability_companion_armor_medium.dds",
    effects: [
      {
        "type": "heal",
        "target": { "type": "self", "scope": "single" },
        "formula": {
          "type": "metric-percent",
          "percent": 100,
          "metricId": "companion-health-maximum",
        },
      },
      { "type": "special", "effect": "become-invisible", "duration": 6 },
      { "type": "cast-time", "duration": 0.433 },
      { "type": "cooldown", "duration": 36 },
    ] as const,
    validRoles: ["tank"] as const,
    castConditions: [{ "type": "health-threshold", "below": 50, "targetType": "self" }] as const,
  },
  "shared-vipers-bite": {
    id: "shared-vipers-bite" as const,
    abilityId: 152863,
    name: "Viper's Bite",
    companionId: "all" as const,
    skillLineId: "weapon-bow" as const,
    skillType: "active" as const,
    description:
      "Your Companion shoots an arrow covered in Baandari poison at an enemy, dealing $1 Poison Damage and an additional $2 Poison Damage over $$2 seconds.",
    icon: "/esoui/art/icons/ability_companion_bow_002.dds",
    effects: [
      {
        "type": "damage",
        "target": { "type": "enemy", "range": 28, "scope": "single" },
        "formula": {
          "type": "metric-scaling",
          "metricId": "companion-weapon-damage",
          "coefficient": 1.5,
        },
        "damageType": "poison",
      },
      {
        "type": "dot",
        "target": { "type": "enemy", "scope": "single" },
        "formula": {
          "type": "metric-scaling",
          "metricId": "companion-weapon-damage",
          "coefficient": 4.5,
        },
        "duration": 8,
        "damageType": "poison",
        "displayMode": "total",
        "initialTick": false,
        "tickInterval": 2,
        "durationOffset": 2,
      },
      { "type": "cast-time", "duration": 0.133 },
      { "type": "cooldown", "duration": 12 },
    ] as const,
    validRoles: ["dps"] as const,
  },
  "sharp-char": {
    id: "sharp-char" as const,
    abilityId: 186486,
    name: "Char",
    companionId: "sharp-as-night" as const,
    skillLineId: "companion-sharp-as-night-beasts-of-the-hunt" as const,
    skillType: "active" as const,
    description:
      "Your Companion unearths a group of fiery shalk that attack dealing $1 Magic Damage to enemies in front of them. After the shalk complete their attack, they burrow underground for 3 seconds and resurface again, dealing $2 Magic Damage to enemies in front of them.",
    icon: "/esoui/art/icons/ability_companion_warden_scorch.dds",
    effects: [
      {
        "type": "damage",
        "target": { "type": "enemy", "scope": "area" },
        "formula": {
          "type": "metric-scaling",
          "metricId": "companion-weapon-damage",
          "coefficient": 1.5,
        },
        "damageType": "magic",
      },
      {
        "type": "delayed",
        "delay": 3,
        "effect": {
          "type": "damage",
          "target": { "type": "enemy", "scope": "area" },
          "formula": {
            "type": "metric-scaling",
            "metricId": "companion-weapon-damage",
            "coefficient": 1.5,
          },
          "damageType": "magic",
        },
      },
      { "type": "cast-time", "duration": 0.5 },
      { "type": "cooldown", "duration": 16 },
    ] as const,
    validRoles: ["dps"] as const,
  },
  "sharp-cold-snap": {
    id: "sharp-cold-snap" as const,
    abilityId: 186604,
    name: "Cold Snap",
    companionId: "sharp-as-night" as const,
    skillLineId: "companion-sharp-as-night-winters-bite" as const,
    skillType: "active" as const,
    description:
      "Your Companion encircles themselves with ice shards to skewer enemies in the area, immobilizing them for $$1 seconds and dealing $1 Frost Damage every 2 seconds for 8 seconds. Damage done is based on Your Companion's Max Health.",
    icon: "/esoui/art/icons/ability_companion_warden_impalingshards.dds",
    effects: [
      {
        "type": "apply-status",
        "status": { "status": "immobilize", "duration": 3 },
        "target": { "type": "enemy", "scope": "area", "radius": 10 },
      },
      {
        "type": "dot",
        "target": { "type": "enemy", "scope": "area", "radius": 10 },
        "formula": {
          "type": "metric-percent",
          "percent": 5,
          "metricId": "companion-health-maximum",
        },
        "duration": 8,
        "damageType": "frost",
        "displayMode": "total",
        "initialTick": true,
        "tickInterval": 1,
      },
      { "type": "cast-time", "duration": 0.633 },
      { "type": "cooldown", "duration": 12 },
    ] as const,
    validRoles: ["dps"] as const,
  },
  "sharp-fungal-forage": {
    id: "sharp-fungal-forage" as const,
    abilityId: 186598,
    name: "Fungal Forage",
    companionId: "sharp-as-night" as const,
    skillLineId: "companion-sharp-as-night-verdant-growth" as const,
    skillType: "active" as const,
    description:
      "Your Companion musters a cluster of mushrooms, healing you and your allies for $1 Health. Heals for 50% more on allies that are within 8 meters of Your Companion.",
    icon: "/esoui/art/icons/ability_companion_warden_fungalgrowth.dds",
    effects: [
      {
        "type": "heal",
        "target": { "type": "ally", "scope": "area", "radius": 20 },
        "formula": {
          "type": "metric-scaling",
          "metricId": "companion-weapon-damage",
          "coefficient": 3,
        },
      },
      {
        "type": "heal",
        "target": { "type": "ally", "scope": "area", "radius": 8 },
        "formula": {
          "type": "metric-scaling",
          "metricId": "companion-weapon-damage",
          "coefficient": 1.5,
        },
        "conditions": [{ "type": "range", "maxDistance": 8 }],
      },
      { "type": "cast-time", "duration": 0.4 },
      { "type": "cooldown", "duration": 12 },
    ] as const,
    validRoles: ["healer"] as const,
    castConditions: [{ "type": "ally-health", "below": 75 }] as const,
  },
  "sharp-gore": {
    id: "sharp-gore" as const,
    abilityId: 186488,
    name: "Gore",
    companionId: "sharp-as-night" as const,
    skillLineId: "companion-sharp-as-night" as const,
    skillType: "ultimate" as const,
    description:
      "Your Companion provokes a spectral kagouti to charge and toss the enemy for $1 Physical Damage, stunning them for $$2 seconds. This ability deals 150% more damage to enemies below 25% Health.",
    icon: "/esoui/art/icons/ability_companion_warden_gore.dds",
    effects: [
      {
        "type": "damage",
        "target": { "type": "enemy", "range": 28, "scope": "single" },
        "formula": {
          "type": "metric-scaling",
          "metricId": "companion-weapon-damage",
          "coefficient": 9,
        },
        "conditions": [{ "type": "health-threshold", "below": 25, "targetType": "enemy" }],
        "damageType": "physical",
        "conditionalMultiplier": 2.5,
      },
      {
        "type": "apply-status",
        "status": { "status": "stun", "duration": 3 },
        "target": { "type": "enemy", "range": 28, "scope": "single" },
      },
      { "type": "resource-cost", "amount": 200, "resource": "ultimate" },
      { "type": "cast-time", "duration": 0.1 },
    ] as const,
    validRoles: ["dps"] as const,
  },
  "sharp-infest": {
    id: "sharp-infest" as const,
    abilityId: 186485,
    name: "Infest",
    companionId: "sharp-as-night" as const,
    skillLineId: "companion-sharp-as-night-beasts-of-the-hunt" as const,
    skillType: "active" as const,
    description:
      "Your Companion provokes a cloud of fetcherflies to swarm an enemy, dealing $1 Magic Damage over $$1 seconds. The fetcherflies rip through the enemy's flesh, afflicting them with Minor Vulnerability for the duration, increasing their damage taken by 5%.",
    icon: "/esoui/art/icons/ability_companion_warden_swarm.dds",
    effects: [
      {
        "type": "dot",
        "target": { "type": "enemy", "range": 28, "scope": "single" },
        "formula": {
          "type": "metric-scaling",
          "metricId": "companion-weapon-damage",
          "coefficient": 4.5,
        },
        "duration": 8,
        "damageType": "magic",
        "displayMode": "total",
        "initialTick": true,
        "tickInterval": 2,
      },
      {
        "type": "apply-debuff",
        "debuff": {
          "value": 0.05,
          "debuff": "minor-vulnerability",
          "duration": 8,
          "valueType": "fractional-change",
        },
        "target": { "type": "enemy", "range": 28, "scope": "single" },
      },
      { "type": "cast-time", "duration": 0.4 },
      { "type": "cooldown", "duration": 12 },
    ] as const,
    validRoles: ["dps", "support"] as const,
  },
  "sharp-perennial-bloom": {
    id: "sharp-perennial-bloom" as const,
    abilityId: 186602,
    name: "Perennial Bloom",
    companionId: "sharp-as-night" as const,
    skillLineId: "companion-sharp-as-night-verdant-growth" as const,
    skillType: "active" as const,
    description:
      "Your Companion summons a field of blooming flowers, healing you and nearby allies for $1 Health every 2 seconds over $$1 seconds.",
    icon: "/esoui/art/icons/ability_companion_warden_healingseed.dds",
    effects: [
      {
        "type": "hot",
        "target": { "type": "ally", "scope": "area", "radius": 8 },
        "formula": {
          "type": "metric-scaling",
          "metricId": "companion-weapon-damage",
          "coefficient": 0.6,
          "coefficientType": "per-tick",
        },
        "duration": 8,
        "displayMode": "per-tick",
        "initialTick": true,
        "tickInterval": 2,
      },
      { "type": "cast-time", "duration": 0.4 },
      { "type": "cooldown", "duration": 12 },
    ] as const,
    validRoles: ["healer"] as const,
    castConditions: [{ "type": "ally-health", "below": 75 }] as const,
  },
  "sharp-petals-of-the-hunter": {
    id: "sharp-petals-of-the-hunter" as const,
    abilityId: 186601,
    name: "Petals of the Hunter",
    companionId: "sharp-as-night" as const,
    skillLineId: "companion-sharp-as-night-verdant-growth" as const,
    skillType: "active" as const,
    description:
      "Your Companion calls on the essence of a carnivorous bloom, causing their Light Attacks to restore $1 Health to themselves or up to 2 nearby allies for $$1 seconds.",
    icon: "/esoui/art/icons/ability_companion_warden_lotusflower.dds",
    effects: [
      {
        "type": "light-attack-heal",
        "target": { "type": "self-and-ally", "range": 28, "scope": "area", "maxTargets": 3 },
        "formula": {
          "type": "metric-scaling",
          "metricId": "companion-weapon-damage",
          "coefficient": 1.25,
        },
        "duration": 8,
      },
      { "type": "cast-time", "duration": 0.5 },
      { "type": "cooldown", "duration": 16 },
    ] as const,
    validRoles: ["healer", "tank"] as const,
  },
  "sharp-sleetmail": {
    id: "sharp-sleetmail" as const,
    abilityId: 186603,
    name: "Sleetmail",
    companionId: "sharp-as-night" as const,
    skillLineId: "companion-sharp-as-night-winters-bite" as const,
    skillType: "active" as const,
    description:
      "Your Companion conjures ice armor for themselves and nearby grouped allies. Your Companion reduces their Damage Taken by 20% for $$1 seconds. Allies gain Major Resolve, increasing Physical and Spell Resistance by 5948 for $$2 seconds.",
    icon: "/esoui/art/icons/ability_companion_warden_frostcloak.dds",
    effects: [
      {
        "buff": {
          "buff": "flat-damage-reduction",
          "value": 0.2,
          "duration": 6,
          "valueType": "fractional-change",
        },
        "type": "apply-buff",
        "target": { "type": "self", "scope": "single" },
      },
      {
        "buff": { "buff": "major-resolve", "value": 5948, "duration": 6, "valueType": "integer" },
        "type": "apply-buff",
        "target": { "type": "ally", "scope": "area", "radius": 12 },
      },
      { "type": "cast-time", "duration": 0.2 },
      { "type": "cooldown", "duration": 8 },
    ] as const,
    validRoles: ["tank", "support"] as const,
  },
} as const satisfies Record<string, CompanionSkillTemplate>
