import type { SkillTemplate } from "../character-skill-template/character-skill-template.module.code.ts"

export const CHARACTER_SKILLS_37 = {
  "keen-eye-dig-sites-140173": {
    id: "keen-eye-dig-sites-140173" as const,
    esoSkillId: 140173,
    name: "Keen Eye: Dig Sites",
    baseName: "Keen Eye: Dig Sites",
    skillLineId: "world-excavation" as const,
    skillType: "passive" as const,
    description:
      "Antiquity Dig Sites will be easier to see when you are |cffffff20|r meters or closer.",
    icon: "/esoui/art/icons/ability_scrying_08a.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 2,
    rank: 2,
    subcategoryId: "world-excavation" as const,
  },
  "keen-eye-jewelry": {
    id: "keen-eye-jewelry" as const,
    esoSkillId: 103639,
    name: "Keen Eye: Jewelry",
    baseName: "Keen Eye: Jewelry",
    skillLineId: "craft-jewelry-crafting" as const,
    skillType: "passive" as const,
    description:
      "Jewelry Seams in the world will be easier to see when you are 40 meters or closer.",
    icon: "/esoui/art/icons/ability_smith_002.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 30,
    rank: 3,
    subcategoryId: "craft-jewelry-crafting" as const,
  },
  "keen-eye-jewelry-103637": {
    id: "keen-eye-jewelry-103637" as const,
    esoSkillId: 103637,
    name: "Keen Eye: Jewelry",
    baseName: "Keen Eye: Jewelry",
    skillLineId: "craft-jewelry-crafting" as const,
    skillType: "passive" as const,
    description:
      "Jewelry Seams in the world will be easier to see when you are |cffffff20|r meters or closer.",
    icon: "/esoui/art/icons/ability_smith_002.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 2,
    rank: 2,
    subcategoryId: "craft-jewelry-crafting" as const,
  },
  "keen-eye-ore": {
    id: "keen-eye-ore" as const,
    esoSkillId: 47856,
    name: "Keen Eye: Ore",
    baseName: "Keen Eye: Ore",
    skillLineId: "craft-blacksmithing" as const,
    skillType: "passive" as const,
    description: "Ore in the world will be easier to see when you are 40 meters or closer.",
    icon: "/esoui/art/icons/ability_smith_002.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 30,
    rank: 3,
    subcategoryId: "craft-blacksmithing" as const,
  },
  "keen-eye-ore-47854": {
    id: "keen-eye-ore-47854" as const,
    esoSkillId: 47854,
    name: "Keen Eye: Ore",
    baseName: "Keen Eye: Ore",
    skillLineId: "craft-blacksmithing" as const,
    skillType: "passive" as const,
    description:
      "Ore in the world will be easier to see when you are |cffffff20|r meters or closer.",
    icon: "/esoui/art/icons/ability_smith_002.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 2,
    rank: 2,
    subcategoryId: "craft-blacksmithing" as const,
  },
  "keen-eye-reagents": {
    id: "keen-eye-reagents" as const,
    esoSkillId: 47842,
    name: "Keen Eye: Reagents",
    baseName: "Keen Eye: Reagents",
    skillLineId: "craft-alchemy" as const,
    skillType: "passive" as const,
    description:
      "Herbs and fungi in the world will be easier to see when you are 40 meters or closer.",
    icon: "/esoui/art/icons/ability_smith_002.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 17,
    rank: 3,
    subcategoryId: "craft-alchemy" as const,
  },
  "keen-eye-reagents-47840": {
    id: "keen-eye-reagents-47840" as const,
    esoSkillId: 47840,
    name: "Keen Eye: Reagents",
    baseName: "Keen Eye: Reagents",
    skillLineId: "craft-alchemy" as const,
    skillType: "passive" as const,
    description:
      "Herbs and fungi in the world will be easier to see when you are |cffffff20|r meters or closer.",
    icon: "/esoui/art/icons/ability_smith_002.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 2,
    rank: 2,
    subcategoryId: "craft-alchemy" as const,
  },
  "keen-eye-rune-stones": {
    id: "keen-eye-rune-stones" as const,
    esoSkillId: 47853,
    name: "Keen Eye: Rune Stones",
    baseName: "Keen Eye: Rune Stones",
    skillLineId: "craft-enchanting" as const,
    skillType: "passive" as const,
    description: "Runes in the world will be easier to see when you are 40 meters or closer.",
    icon: "/esoui/art/icons/ability_smith_002.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 14,
    rank: 3,
    subcategoryId: "craft-enchanting" as const,
  },
  "keen-eye-rune-stones-47851": {
    id: "keen-eye-rune-stones-47851" as const,
    esoSkillId: 47851,
    name: "Keen Eye: Rune Stones",
    baseName: "Keen Eye: Rune Stones",
    skillLineId: "craft-enchanting" as const,
    skillType: "passive" as const,
    description:
      "Runes in the world will be easier to see when you are |cffffff20|r meters or closer.",
    icon: "/esoui/art/icons/ability_smith_002.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 2,
    rank: 2,
    subcategoryId: "craft-enchanting" as const,
  },
  "keen-eye-treasure-chests": {
    id: "keen-eye-treasure-chests" as const,
    esoSkillId: 139772,
    name: "Keen Eye: Treasure Chests",
    baseName: "Keen Eye: Treasure Chests",
    skillLineId: "world-excavation" as const,
    skillType: "passive" as const,
    description: "Treasure Chests will be easier to see when you are 30 meters or closer.",
    icon: "/esoui/art/icons/ability_scrying_08b.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 7,
    rank: 2,
    subcategoryId: "world-excavation" as const,
  },
  "keen-eye-wood": {
    id: "keen-eye-wood" as const,
    esoSkillId: 47859,
    name: "Keen Eye: Wood",
    baseName: "Keen Eye: Wood",
    skillLineId: "craft-woodworking" as const,
    skillType: "passive" as const,
    description: "Wood in the world will be easier to see when you are 40 meters or closer.",
    icon: "/esoui/art/icons/ability_smith_002.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 30,
    rank: 3,
    subcategoryId: "craft-woodworking" as const,
  },
  "keen-eye-wood-47857": {
    id: "keen-eye-wood-47857" as const,
    esoSkillId: 47857,
    name: "Keen Eye: Wood",
    baseName: "Keen Eye: Wood",
    skillLineId: "craft-woodworking" as const,
    skillType: "passive" as const,
    description:
      "Wood in the world will be easier to see when you are |cffffff20|r meters or closer.",
    icon: "/esoui/art/icons/ability_smith_002.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 2,
    rank: 2,
    subcategoryId: "craft-woodworking" as const,
  },
  "kickback": {
    id: "kickback" as const,
    esoSkillId: 63818,
    name: "Kickback",
    baseName: "Kickback",
    skillLineId: "world-legerdemain" as const,
    skillType: "passive" as const,
    description: "Reduces bounties you willingly pay to guards and fences by 40%.",
    icon: "/esoui/art/icons/ability_legerdemain_sly.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 20,
    rank: 4,
    subcategoryId: "world-legerdemain" as const,
  },
  "kickback-63817": {
    id: "kickback-63817" as const,
    esoSkillId: 63817,
    name: "Kickback",
    baseName: "Kickback",
    skillLineId: "world-legerdemain" as const,
    skillType: "passive" as const,
    description: "Reduces bounties you willingly pay to guards and fences by |cffffff30|r%.",
    icon: "/esoui/art/icons/ability_legerdemain_sly.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 6,
    rank: 6,
    subcategoryId: "world-legerdemain" as const,
  },
  "killer-s-blade": {
    id: "killer-s-blade" as const,
    esoSkillId: 34843,
    name: "Killer's Blade",
    baseName: "Assassin's Blade",
    skillLineId: "nightblade-assassination" as const,
    skillType: "active" as const,
    description:
      "Thrust a caustic blade with lethal precision to stab an enemy, dealing |cffffff4038|r Disease Damage. Deals up to |cffffff400|r% more damage to enemies with less than |cffffff50|r% Health.\n\nHeals you for |cffffff7547|r if the enemy dies within |cffffff2|r seconds of being struck.",
    icon: "/esoui/art/icons/ability_nightblade_017_a.dds",
    isMorph: true,
    morphIndex: 1,
    lineRankNeeded: 20,
    rank: 20,
    subcategoryId: "nightblade-assassination" as const,
  },
  "killers-blade": {
    id: "killers-blade" as const,
    esoSkillId: 35590,
    name: "Killer's Blade",
    baseName: "Assassin's Blade",
    skillLineId: "nightblade-assassination" as const,
    skillType: "active" as const,
    description:
      "Thrust a caustic blade with lethal precision to stab an enemy, dealing 1161 Disease Damage. Deals up to 400% more damage to enemies with less than 50% Health.\n\nHeals you for 2399 if the enemy dies within 2 seconds of being struck.",
    icon: "/esoui/art/icons/ability_nightblade_017_a.dds",
    isMorph: true,
    morphIndex: 1,
    lineRankNeeded: 20,
    rank: 8,
    subcategoryId: "nightblade-assassination" as const,
  },
  "laboratory-use": {
    id: "laboratory-use" as const,
    esoSkillId: 45555,
    name: "Laboratory Use",
    baseName: "Laboratory Use",
    skillLineId: "craft-alchemy" as const,
    skillType: "passive" as const,
    description: "Allows the use of up to 3 reagents while mixing Potions or Poisons.",
    icon: "/esoui/art/icons/ability_alchemy_002.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 15,
    rank: 1,
    subcategoryId: "craft-alchemy" as const,
  },
  "lacerate": {
    id: "lacerate" as const,
    esoSkillId: 83600,
    name: "Lacerate",
    baseName: "Lacerate",
    skillLineId: "weapon-dual-wield" as const,
    skillType: "ultimate" as const,
    description:
      "Slash enemies in front of you, causing them to bleed for |cffffff22860|r Bleed Damage over |cffffff8|r seconds and healing you for |cffffff51|r% of the damage done.\n\nEach tick applies the Hemorrhaging status effect.",
    icon: "/esoui/art/icons/ability_dualwield_006.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 50,
    rank: 50,
    subcategoryId: "weapon-dual-wield" as const,
  },
  "landslide": {
    id: "landslide" as const,
    esoSkillId: 29463,
    name: "Landslide",
    baseName: "Landslide",
    skillLineId: "dragonknight-earthen-heart" as const,
    skillType: "passive" as const,
    description:
      "Given time, the smallest rock on the mountain can cascade into pure devastation.\n\nWhenever you deal damage you gain a stack of Landslide which increases your damage done by |cffffff1|r% per stack, up to |cffffff10|r times. This effect can occur once every |cffffff10|r seconds.\n\nEvery |cffffff2|r seconds you do not deal damage, you lose a stack.",
    icon: "/esoui/art/icons/ability_weapon_005.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 14,
    rank: 14,
    subcategoryId: "dragonknight-earthen-heart" as const,
  },
  "lapidary-research": {
    id: "lapidary-research" as const,
    esoSkillId: 108098,
    name: "Lapidary Research",
    baseName: "Lapidary Research",
    skillLineId: "craft-jewelry-crafting" as const,
    skillType: "passive" as const,
    description: "Reduces research times by 25%, and limits research time to 30 days.",
    icon: "/esoui/art/icons/passive_lapidaryresearch.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 45,
    rank: 4,
    subcategoryId: "craft-jewelry-crafting" as const,
  },
  "lapidary-research-103640": {
    id: "lapidary-research-103640" as const,
    esoSkillId: 103640,
    name: "Lapidary Research",
    baseName: "Lapidary Research",
    skillLineId: "craft-jewelry-crafting" as const,
    skillType: "passive" as const,
    description: "Reduces research times by 5%.",
    icon: "/esoui/art/icons/passive_lapidaryresearch.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 8,
    rank: 8,
    subcategoryId: "craft-jewelry-crafting" as const,
  },
  "last-gasp": {
    id: "last-gasp" as const,
    esoSkillId: 116272,
    name: "Last Gasp",
    baseName: "Last Gasp",
    skillLineId: "necromancer-bone-tyrant" as const,
    skillType: "passive" as const,
    description: "Increase your Max Health by 2412.",
    icon: "/esoui/art/icons/passive_necromancer_008.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 50,
    rank: 2,
    subcategoryId: "necromancer-bone-tyrant" as const,
    effects: [
      { "metricId": "health-maximum", "effectType": "integer", "effectValue": 2412 },
    ] as const,
    status: "supported" as const,
  },
  "last-gasp-116271": {
    id: "last-gasp-116271" as const,
    esoSkillId: 116271,
    name: "Last Gasp",
    baseName: "Last Gasp",
    skillLineId: "necromancer-bone-tyrant" as const,
    skillType: "passive" as const,
    description: "Increases your Max Health by |cffffff1206|r.",
    icon: "/esoui/art/icons/passive_necromancer_008.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 39,
    rank: 39,
    subcategoryId: "necromancer-bone-tyrant" as const,
  },
  "lava-whip": {
    id: "lava-whip" as const,
    esoSkillId: 23806,
    name: "Lava Whip",
    baseName: "Lava Whip",
    skillLineId: "dragonknight-ardent-flame" as const,
    skillType: "active" as const,
    description:
      "Lash an enemy with flame, dealing |cffffff8076|r Flame Damage.\n\nHitting an Off Balance enemy grants |cffffff5|r stacks of Volcanic Whip for |cffffff20|r seconds, up to once every |cffffff20|r seconds.\n\nVolcanic Whip replaces this ability and consumes a stack to instead deal |cffffff15931|r Flame Damage to your target and all nearby enemies.",
    icon: "/esoui/art/icons/ability_dragonknight_001.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 1,
    rank: 1,
    subcategoryId: "dragonknight-ardent-flame" as const,
  },
} satisfies Record<string, SkillTemplate>
