apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
    labels:
        app.kubernetes.io/name: cert-manager
        app.kubernetes.io/instance: dns01-solver
        app.kubernetes.io/component: solver-credentials
        app.kubernetes.io/part-of: cert-manager
        app.kubernetes.io/managed-by: deploy-script
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:PuxffleWFmBUPs2LAQ9z4NhCdW9qDrE1xvLNrFiUhyOwyQ+FTUab6PxS+FvDLi9cjnhXKUY=,iv:E15sH3iiRQq1tddYe3tHgjqFmxwM+E/qc8H1+1kCG4c=,tag:NqiIbdi5KVgTewioC6B/Rw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxaERUbUZkd0hZRG9Kc1pj
            YzIxZVFpSktac0xkSnNaaGlkalloZnVScjM4CnZtY1haVVpXb1RYUE1DRG9oczdi
            N3dKOFZOU21qMHc0dW9JWUJRVXdlS28KLS0tIHhobldGckM1VlVPdDcxc1JUOFRO
            Zi9xeE5vckNKc2dyU2hxRlUrV1RWa3cK+hniJYXhB4uER4+9PZoa5jqhHM1TC8zg
            x0y4ldkXploid0wAg9hA7+//XRR1HVdIwAFe5Rf197N5dsBzsCWswg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T00:51:08Z"
    mac: ENC[AES256_GCM,data:lJcT7z4rML1gpuXigwtJIpXCSeNKvvfNcIadnV2F2k3X9VY/dnmUYQ0TE5po6mWJmMsM3iDZW7SkN0ENz+3I8fHNbFK+6ERjq5Td4AtASC4DBXm1iu6mxwyUv/u+ZKKkHCsWR/8Vir6N2whJDJYKrX5bRT4dwB8/ZBnf2OJIMCQ=,iv:vo5Aps6pzLS54sqS+a3ktxvCkr5OWKTy3IwG0o7QWF0=,tag:2ADI0I7hDBLZ7vx37SAv4Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
