import type { StoryChapterWritten } from "akasha/story/world/stories/written/chapters/story-chapter-written.page-type.types.ts"

export const hollowmere0012WithAnyoneWatching = {
  id: "01a0fe85-7bb9-7110-ae6b-c7ba4f14d6f0",
  type: "page-type/story-chapter-written",
  slug: "hollowmere-0012-with-anyone-watching",
  cover: "image/image-109fac87f9b6a1f7",
  completedAt: "2026-10-02T21:51:28.940Z",
  ownProgress: 3192,
  position: 12,
  unit: "unit/words",
  title: "With Anyone Watching",
  story: "story-written/hollowmere",
  ownLength: 3192,
  prose: "txt",
  stepStatus: "step-status/player",
  beats: "jsonl",
  lore: [
    "lore/hollowmere-academy-2",
    "lore/hollowmere-amara",
    "lore/hollowmere-bea",
    "lore/hollowmere-kit",
    "lore/hollowmere-lin",
    "lore/hollowmere-nala",
    "lore/hollowmere-nala-2",
    "lore/hollowmere-penhallow",
    "lore/hollowmere-priya",
    "lore/hollowmere-shiv",
    "place/hollowmere-kendal",
  ],
  characters: [
    "character-player/hollowmere-nala",
    "character-other/hollowmere-penhallow",
    "character-other/hollowmere-kit",
    "character-other/hollowmere-amara",
    "character-other/hollowmere-priya",
    "character-other/hollowmere-shiv",
    "character-other/hollowmere-lin",
    "character-other/hollowmere-bea",
  ],
  reviewedBy: ["story-reviewer/style", "story-reviewer/continuity"],
  recordedBy: [
    "story-recorder/mechanics",
    "story-recorder/inventory",
    "story-recorder/memory",
    "story-recorder/picture",
  ],
  scenes: [
    "image/image-6946c5f16c70b599",
    "image/image-109fac87f9b6a1f7",
    "image/image-f1fe344228a79604",
    "image/image-39d5d1b60ef9e07f",
  ],
} as const satisfies StoryChapterWritten
