import type { StoryChapterWritten } from "akasha/story/world/stories/written/chapters/story-chapter-written.page-type.types.ts"

export const hollowmere0020JustOurs = {
  id: "01a0ff41-e419-7057-a92b-f78efb07d4af",
  type: "page-type/story-chapter-written",
  slug: "hollowmere-0020-just-ours",
  cover: "image/image-53fc2ca8ee6a2c19",
  completedAt: "2026-10-03T01:47:38.418Z",
  ownProgress: 3607,
  position: 20,
  unit: "unit/words",
  title: "Just Ours",
  story: "story-written/hollowmere",
  ownLength: 3607,
  prose: "txt",
  stepStatus: "step-status/player",
  beats: "jsonl",
  issues: [
    '"Not one person noticed," she says - Nobody Acts',
    '"Not one person ever notices when I go quiet." - Nobody Acts',
    '"scrambling out over you" - in ch.19 Nala lay to the wall with Bea behind, on the open side',
    '"That morning. When my glim held." - Bea\'s glim on the rock came in the afternoon (ch.9)',
  ],
  lore: [
    "lore/hollowmere-academy-2",
    "lore/hollowmere-bea",
    "lore/hollowmere-bea-2",
    "lore/hollowmere-kit",
    "lore/hollowmere-kit-2",
    "lore/hollowmere-lin",
    "lore/hollowmere-morwenna",
    "lore/hollowmere-nala",
    "lore/hollowmere-nala-2",
    "lore/hollowmere-priya",
    "lore/hollowmere-shiv",
    "lore/hollowmere-yusra",
  ],
  characters: [
    "character-player/hollowmere-nala",
    "character-other/hollowmere-bea",
    "character-other/hollowmere-shiv",
    "character-other/hollowmere-morwenna",
    "character-other/hollowmere-kit",
    "character-other/hollowmere-lin",
    "character-other/hollowmere-priya",
    "character-other/hollowmere-yusra",
  ],
  reviewedBy: ["story-reviewer/style", "story-reviewer/continuity"],
  recordedBy: [
    "story-recorder/inventory",
    "story-recorder/mechanics",
    "story-recorder/memory",
    "story-recorder/picture",
  ],
  scenes: [
    "image/image-a757d14d85bf2cee",
    "image/image-9a594876d040b832",
    "image/image-f473abc9e191e922",
    "image/image-9b001feba0132602",
    "image/image-12b67f9dc9f6c521",
    "image/image-53fc2ca8ee6a2c19",
  ],
  pictured: [
    {
      cover: "image/image-a757d14d85bf2cee",
      coverAfter: "You're wearing Bea's jumper. The big cream cable-knit one, the one Kit",
      character: "character-player/hollowmere-nala",
      outfit: "Bea's big cream cable-knit jumper, inside out",
    },
    {
      cover: "image/image-9a594876d040b832",
      coverAfter: "On the landing stage afterwards, Morwenna gathers the novices.",
      setting: "the landing stage",
    },
    {
      cover: "image/image-f473abc9e191e922",
      coverAfter: "At the end of the academy jetty, the short wooden one by the",
      setting: "the academy jetty",
    },
    {
      cover: "image/image-9b001feba0132602",
      coverAfter: "Underneath she's bare.",
      character: "character-other/hollowmere-bea",
      outfit: "bare to the waist, black leggings",
    },
    {
      cover: "image/image-12b67f9dc9f6c521",
      coverAfter: "She undresses you slowly. Your jumper first, over your head, her hands",
      character: "character-player/hollowmere-nala",
      outfit: "bare to the waist, dark skirt and tights",
    },
    {
      cover: "image/image-53fc2ca8ee6a2c19",
      coverAfter: "She's shaved bare.",
      character: "character-other/hollowmere-bea",
      outfit: "naked",
    },
  ],
} as const satisfies StoryChapterWritten
