import type { StoryChapterWritten } from "akasha/story/world/stories/written/chapters/story-chapter-written.page-type.types.ts"

export const hollowmere0001Thornfield14 = {
  id: "01a0fd10-48e5-7ba5-86f5-dd3b87362612",
  type: "page-type/story-chapter-written",
  slug: "hollowmere-0001-thornfield-14",
  cover: "image/image-0dd7b4db7b52d492",
  completedAt: "2026-10-02T15:02:42.249Z",
  ownProgress: 6979,
  position: 1,
  unit: "unit/words",
  title: "Thornfield 14",
  story: "story-written/hollowmere",
  ownLength: 6979,
  prose: "txt",
  stepStatus: "step-status/player",
  beats: "jsonl",
  issues: [
    '"and nobody looks twice" (beat) - Nobody Acts',
    '"and nobody looks twice at that either" (beat) - Nobody Acts',
    '"tracing it carefully. Nothing happens." (beat) - Nobody Acts',
    '"You remember nothing of this Nala\'s life" (beat) - Plain Negation',
    '"a small sensitive point at the top of them" - Hollowmere Explicitness',
    '"the place between your legs that is warm and closed and new" - Hollowmere Explicitness',
  ],
  lore: [
    "lore/hollowmere-bea",
    "lore/hollowmere-kit",
    "lore/hollowmere-nala",
    "lore/hollowmere-world",
    "lore/hollowmere-yusra",
    "place/hollowmere-academy",
    "place/hollowmere-thornfield-house",
  ],
  characters: [
    "character-player/hollowmere-nala",
    "character-other/hollowmere-bea",
    "character-other/hollowmere-yusra",
    "character-other/hollowmere-kit",
  ],
  reviewedBy: ["story-reviewer/continuity", "story-reviewer/style"],
  recordedBy: [
    "story-recorder/mechanics",
    "story-recorder/inventory",
    "story-recorder/memory",
    "story-recorder/picture",
  ],
  scenes: [
    "image/image-53ba719b27b5405d",
    "image/image-220f4f497e59334d",
    "image/image-183fc258004e4afb",
    "image/image-d76ee098554c5427",
    "image/image-38bb58521049b61b",
    "image/image-db1356050ec3190c",
    "image/image-b2e099c41984ee4e",
    "image/image-0dd7b4db7b52d492",
    "image/image-bddae35ea9323def",
    "image/image-7d159cd95d1e6912",
  ],
  pictured: [
    {
      cover: "image/image-cb9410a4893a9db7",
      coverAfter: "She's about twenty. She's slim and not tall, standing in a long",
      character: "character-player/hollowmere-nala",
      outfit: "naked",
      setting: "Thornfield 14",
    },
    {
      cover: "image/image-220f4f497e59334d",
      coverAfter: "Everything is lighter. That's the thing that keeps arriving, now that you're",
      character: "character-player/hollowmere-nala",
      outfit: "long white cotton nightshirt",
    },
    {
      cover: "image/image-c0dd8e15f886d933",
      coverAfter: "The shower is a cubicle with a cracked tile and a chrome",
      character: "character-player/hollowmere-nala",
      outfit: "naked",
      setting: "the corridor bathroom",
    },
    {
      cover: "image/image-d76ee098554c5427",
      coverAfter: "You both turn. There's a woman standing in the kitchen doorway, one",
      character: "character-other/hollowmere-bea",
      outfit: "huge knitted jumper over black leggings",
      setting: "the Thornfield kitchen",
    },
    {
      cover: "image/image-38bb58521049b61b",
      coverAfter: "Then she looks up at you again, and this time her dark",
      character: "character-other/hollowmere-yusra",
      outfit: "charcoal knit jumper with a brass warden's badge, grey wool trousers",
    },
    {
      cover: "image/image-ae8b5b24ada3fbee",
      coverAfter: "A quad. A great lawned square, green and wet and immaculate, ringed",
      setting: "the quad",
    },
    {
      cover: "image/image-b2e099c41984ee4e",
      coverAfter: "You feel stupid. You look round at the door to make sure",
      character: "character-player/hollowmere-nala",
      outfit: "grey jumper and jeans",
    },
    {
      cover: "image/image-0dd7b4db7b52d492",
      coverAfter: "The girl in the glass has her dark red hair pinned up",
      character: "character-player/hollowmere-nala",
      outfit: "white blouse under a black academic gown",
    },
    {
      cover: "image/image-bddae35ea9323def",
      coverAfter: "Afterwards everyone pours out of the high doors into the night. The",
      character: "character-other/hollowmere-kit",
      outfit: "high-necked black jumper under a black academic gown",
      setting: "the Great Hall",
    },
    {
      cover: "image/image-7d159cd95d1e6912",
      coverAfter: "You lie in it in the dark with the nightshirt on and",
      character: "character-player/hollowmere-nala",
      outfit: "long white cotton nightshirt",
    },
  ],
} as const satisfies StoryChapterWritten
