import type { StoryChapterWritten } from "akasha/story/world/stories/written/chapters/story-chapter-written.page-type.types.ts"

export const hollowmere0029AskingNotGrabbing = {
  id: "01a101e6-0c7e-70a7-be40-c0a70023915e",
  type: "page-type/story-chapter-written",
  slug: "hollowmere-0029-asking-not-grabbing",
  cover: "image/image-9bb6afb44012e873",
  ownProgress: 399,
  position: 29,
  unit: "unit/words",
  title: "Asking, Not Grabbing",
  story: "story-written/hollowmere",
  ownLength: 3964,
  prose: "txt",
  stepStatus: "step-status/player",
  beats: "jsonl",
  lore: [
    "lore/hollowmere-academy-2",
    "lore/hollowmere-amara",
    "lore/hollowmere-bea",
    "lore/hollowmere-bea-2",
    "lore/hollowmere-kit",
    "lore/hollowmere-kit-2",
    "lore/hollowmere-lin",
    "lore/hollowmere-lin-2",
    "lore/hollowmere-morwenna",
    "lore/hollowmere-nala",
    "lore/hollowmere-nala-2",
    "lore/hollowmere-priya",
    "lore/hollowmere-yusra",
    "lore/hollowmere-yusra-2",
  ],
  characters: [
    "character-player/hollowmere-nala",
    "character-other/hollowmere-bea",
    "character-other/hollowmere-priya",
    "character-other/hollowmere-lin",
    "character-other/hollowmere-yusra",
    "character-other/hollowmere-kit",
    "character-other/hollowmere-amara",
    "character-other/hollowmere-morwenna",
  ],
  reviewedBy: ["story-reviewer/continuity", "story-reviewer/style"],
  recordedBy: [
    "story-recorder/inventory",
    "story-recorder/mechanics",
    "story-recorder/memory",
    "story-recorder/picture",
  ],
  scenes: ["image/image-9bb6afb44012e873"],
} as const satisfies StoryChapterWritten
