import type { StoryChapterWritten } from "akasha/story/world/stories/written/chapters/story-chapter-written.page-type.types.ts"

export const hollowmere0018 = {
  id: "01a0ff1b-8a1a-7dd9-a125-8be00e602104",
  type: "page-type/story-chapter-written",
  slug: "hollowmere-0018",
  position: 18,
  unit: "unit/words",
  title: "Chapter 18",
  story: "story-written/hollowmere",
  ownLength: 0,
  prose: "txt",
  stepStatus: "step-status/writer",
  beats: [
    "Thursday: a hard clear frost; the mere smokes at dawn, and you and Shiv swim the buoy and back.",
    "Shiv asks about the bursar's forms; you tell her you put Bea's name down for emergencies.",
    "Shiv nods slowly, treading water. \"Good choice. She'd come running. She'd bring soup.\"",
    "Ten: History in the Long Room; the lecture is the founding of the colleges, the 1790s.",
    "Hollowmere's founder was Margery Fell, in 1791; the lecturer shows an engraving of her, stern.",
    "Kit leans in and murmurs that the lecturer has every date right today, which is unsettling.",
    "Halfway through you write on the corner of your notes: your number? and slide it to her.",
    "Kit looks at it a long moment, then writes the number under it in her small neat hand.",
    'Under the number she adds: "Don\'t ring. Text. I hate ringing." You fold it into your pocket.',
    "Lunch: Lin finds you at the long table, pale and urgent, holding a notice from the Drawing Room.",
    '"Tonight\'s model dropped out," she says. "Life drawing. They need someone. By seven."',
    "She only looks at you, and then down at her plate, very pink.",
    "You think of Lin's drawings of you, and of whose wanting; you say: I'll do it.",
    'Lin stares. "You\'ll sit?" You nod. "Clothed, or," she says, and can\'t finish. You say: we\'ll see.',
    "Two: practical; the demonstrator walks the benches with tomorrow's list: glim, then a stone.",
    "Bea's stone warms properly at last, steady, the way it should; she sits down hard on the floor.",
    '"I\'ve done it," Bea says from the floor. "I\'ve done the right spell." The bench next door claps.',
    "Six: the empty Practice Hall; you, Bea and Lin on the front bench, three pairs of eyes.",
    "Lin sits with her hands folded and watches Kit the way she watches a model: calm, unhurried.",
    "Kit looks along the three of you, breathes out, and draws the sigil; her hand falters, and goes on.",
    "The glim comes, small and steady, on the first try. You count; Bea mouths it; it holds to twelve.",
    'Kit lowers her hand and stares at it. "Three," she says. "That was three." Bea whoops.',
    'Kit casts again, and again; the third holds to fifteen, and Lin says softly, "It\'s beautiful."',
    'Kit goes scarlet and looks at the floor. "Tomorrow," she says. "Everyone." Her voice is steady.',
    "Seven: the Drawing Room by lamplight; easels in a ring, a dais with a stool, a screen, a robe.",
    "A dozen girls set up charcoal and paper; the third-year who runs it thanks you, warmly, for coming.",
    "Lin is at an easel near the front, very pale, very still, her charcoal not yet lifted.",
    "Behind the screen you take off your clothes and put on the robe; your hands shake on the belt.",
    "You look down at this body: small soft tits, pale freckled skin, the dark red tuft over your cunt.",
    "It's yours. You've been learning it for three weeks; you think, whose wanting, and you step out.",
    "You sit on the stool in the robe for the first short poses, five minutes each, turning as told.",
    "The room is quiet; just charcoal on paper, the hiss of the lamps, and a dozen pairs of eyes.",
    "For the long pose the third-year asks: robe on or off, entirely your choice. You breathe out.",
    "You let the robe fall. The lamplight is warm on your bare shoulders, your breasts, your thighs.",
    "You sit for forty minutes, one knee up, your hair down your back, while they draw you.",
    "Being looked at goes through you like the cold of the mere: a shock, and then a kind of ease.",
    "You find Lin's eyes over her easel once; she looks at you the way she looks at the heron, wholly.",
    "Your nipples tighten in the cool air from the window; you feel it, and let it be, and stay still.",
    "At nine you dress behind the screen, flushed all over; the third-year says you're a natural.",
    "Lin waits by the door with her sketchbook pressed shut to her chest, saying it's private, for now.",
    "You walk back across the frosted quad together; halfway, Lin takes your hand.",
    '"You were so brave," Lin says. "I drew you nine times. I\'ll show you. When I can look at them."',
    "At the foot of the Thornfield stairs she kisses you, quick and soft, and hurries down to room 8.",
    "The top-floor kitchen: Thursday cocoa, Yusra at the stove in her knit, the floor crowded in.",
    "She's leaving for the infirmary at ten; she pours the last mug and holds it out to you.",
    '"Saved you one," Yusra says. "You\'ve got colour in your face, Nala." Her eyes rest on you.',
    "You say you've been sitting for life drawing. Yusra's eyebrows lift, very slightly. \"Have you.\"",
    "Bea, at the table, chokes on her cocoa; the girl beside her thumps her back.",
    '"Good luck tomorrow," Yusra says, going, her coat over her arm. "Glim, then stone. You\'ll pass."',
    'At the door she turns back once. "Breathe out," she says, and goes, and the kitchen hums.',
    "In 14 you text Kit for the first time: Tomorrow. Breathe out. N.",
    "The reply comes after a long minute: You too. K.",
    "You fall asleep warm all over, the phone in your hand, and Kit's handkerchief under your cheek.",
    "A day at Hollowmere ends.",
  ],
  lore: ["lore/hollowmere-academy-2"],
} as const satisfies StoryChapterWritten
