import type { StoryChapterWritten } from "akasha/story/world/stories/written/chapters/story-chapter-written.page-type.types.ts"

export const hollowmere0031DrawWell = {
  id: "01a101fd-88bf-77d0-b795-8fa80381f4af",
  type: "page-type/story-chapter-written",
  slug: "hollowmere-0031-draw-well",
  position: 31,
  unit: "unit/words",
  title: "Draw Well",
  story: "story-written/hollowmere",
  ownLength: 3565,
  prose: "txt",
  stepStatus: "step-status/reviewers",
  beats: [
    "Wednesday of week five: a hard bright frost; the quad white, the mere steaming in the low sun.",
    "Bea runs the shore and comes back pink, and eats porridge with her hand on your knee.",
    "The post is out in the pigeonholes outside the Great Hall; Lin checks hers without hoping.",
    "There's a thin blue envelope in it. Lin goes very still, then takes it out with two fingers.",
    "She looks at you across the hall. You get up and go to her; Bea watches, and nods you on.",
    '"It\'s early," Lin whispers. "It\'s too early. It must be bad." Her hands are shaking.',
    '"Not here," she says. "Will you come up?" You climb to room 8 together, past the drawings.',
    "She sits on the bed, and you sit beside her, and she opens it, and reads it to herself first.",
    "Her face changes as she reads: frightened, then puzzled, then something softer, then wet.",
    '"My father read my letter twice," she says. "Mum says. Twice. At the table. He said nothing."',
    '"Then he went down to the kitchen and cooked. All night. Mum says that\'s how he thinks."',
    '"They\'ll talk to me properly at Christmas," Lin says. "Properly. Not no. Not yes. Christmas."',
    "She turns to the end of the letter and goes quiet; her mouth trembles. She reads it again.",
    '"The last line," she says. "In Cantonese. Draw well. We are proud." Her voice cracks on proud.',
    "She cries then, properly, her face in her hands; you hold her, and she cries into your neck.",
    "It's a different crying: loose, and relieved, and laughing a little at the end of it.",
    '"Proud," she says. "She\'s never said it. Not like that. Not on paper, where it stays."',
    "She pins the letter on her wall beside the drawing of you, in the middle of everything.",
    "Morning: Sigils in the Drawing Room; Lin draws the calling sigil so cleanly the tutor holds it up.",
    '"This," the tutor says. "Again. This is a sigil." Lin goes pink to her ears and smiles at her desk.',
    "Kit leans across at lunch. \"What's happened to Lin? She looks like she's swallowed a lamp.\"",
    'You say her mum wrote back. Kit looks at Lin, glowing over her soup, and says "Good," and means it.',
    "Afternoon: you and Lin walk the shore path in the cold sun; she holds your hand the whole way.",
    "She talks more than you've ever heard her talk: the restaurant, her sister, her father's hands.",
    '"He chops spring onions so fast you can\'t see the knife," she says. "I used to draw his hands."',
    "At the village jetty you sit on the wall, and she leans on you, and watches the water.",
    '"I\'m not crying now," Lin says, very quietly, looking at the mere. "Have you noticed?"',
    'You look at her. She looks back, steady, and goes slowly pink. "Tonight," she says. "If you want."',
    "You say yes. Lin breathes out, a long breath, and laughs at herself, and kisses you on the wall.",
    "Evening: in 15 you tell Bea. Bea listens with her chin on her knees, and then smiles, warm.",
    '"Go," she says. "She\'s waited. Be gentle with her." Then: "Come back and tell me she\'s all right."',
    "At nine you knock on room 8. Lin opens the door in a long soft jumper, her hair down, barefoot.",
    "She's lit the lamp and the candle on her desk; the room smells of charcoal and the tea she's made.",
    'She shuts the door, and leans on it, and looks at you. "I\'ve never," she says. "With anyone."',
    '"Then we go slow," you say. "And you tell me everything. Look more." Lin laughs, shaky.',
    "You kiss her by the door, slowly; her hands come up into your hair, ink-stained and warm.",
    "She pulls your jumper off over your head, carefully, as if she's undressing a drawing.",
    "You undress her: the soft jumper, the long skirt; she stands in the lamplight with her arms crossed.",
    "Then she uncrosses them. Her small soft breasts, light brown nipples hard in the cool room.",
    "The fine dark tuft over her pussy; her slim waist; the whole of her, trembling a little.",
    '"I want you to see me," Lin says. "The way I saw you." You look at her a long time. She lets you.',
    "You lay her down on her narrow bed under the drawings, and lie beside her, and touch her face.",
    "You kiss her throat, her collarbones, her breasts; you take a nipple in your mouth, and she gasps.",
    '"Oh," Lin says, surprised, and then again, softer, and her fingers tighten in your hair.',
    "Your hand slides down to her pussy; she's wet, and opens her thighs, shy and sure.",
    "You stroke her slowly, finding her clit; she watches your face the whole time, the way she draws.",
    '"There," Lin whispers. "There. Don\'t stop." You keep the same slow circle, and she shakes.',
    "You slide one finger inside her, gently; she's tight and hot, and breathes out long, and smiles.",
    "You make love to her slowly, your finger inside her and your thumb on her clit, her hips lifting.",
    "She comes quietly, the way she does everything, a long shudder and a small cry into your shoulder.",
    'After, she lies with her eyes closed and tears on her lashes. "Not crying," she says. "Different."',
    'Then she rolls over you, shy and determined, and kisses down your body. "Let me. I\'ve watched you."',
    "She touches you like she draws: slow, sure, looking; her fingers find your pussy wet for her.",
    "She learns you as she goes, watching your face, until she finds the place that makes you cry out.",
    "She stays there, steady and patient, till you come under her hand with her name in your mouth.",
    "You lie tangled in her narrow bed, under the drawing of you, under her mother's letter on the wall.",
    '"Draw well," Lin murmurs into your shoulder, half asleep. "We are proud." She\'s smiling.',
    "You sleep in room 8, her hair across your face, the candle burnt down to nothing on the desk.",
    "A day at Hollowmere ends.",
  ],
  lore: [
    "lore/hollowmere-bea",
    "lore/hollowmere-bea-2",
    "lore/hollowmere-kit",
    "lore/hollowmere-kit-2",
    "lore/hollowmere-kit-2-2",
    "lore/hollowmere-lin",
    "lore/hollowmere-lin-2",
    "lore/hollowmere-nala",
    "lore/hollowmere-nala-2",
    "lore/hollowmere-nala-2-2",
  ],
  characters: [
    "character-player/hollowmere-nala",
    "character-other/hollowmere-lin",
    "character-other/hollowmere-bea",
    "character-other/hollowmere-kit",
  ],
} as const satisfies StoryChapterWritten
