import type { StoryChapterWritten } from "akasha/story/world/stories/written/chapters/story-chapter-written.page-type.types.ts"

export const hollowmere0007InYourBoat = {
  id: "01a0fe19-eaef-775a-a42c-eca7ab0bc466",
  type: "page-type/story-chapter-written",
  slug: "hollowmere-0007-in-your-boat",
  cover: "image/image-61e5008b567d0f8a",
  ownProgress: 272,
  position: 7,
  unit: "unit/words",
  title: "In Your Boat",
  story: "story-written/hollowmere",
  ownLength: 4736,
  prose: "txt",
  stepStatus: "step-status/player",
  beats: [
    "Sunday: you wake at six on your own, and you know where you're going before you're up.",
    "The fisherman's jumper over knickers and bra again; the shore grey and silent.",
    "Shiv is on the rock, peeling off her socks; she looks up, and this time she just smiles.",
    "You go in together off the edge, hand in hand; the cold is still a fist, but you breathe out.",
    "Two minutes this time, treading water face to face, the mist lifting off the mere around you.",
    "On the rock, wrapped in her parka, your teeth chattering, Shiv puts her cold hands on your face.",
    '"Still might," she says, and you say, "Then do," and she kisses you.',
    "Her mouth is cold and then warm, tasting of the mere; your whole burning body goes quiet under it.",
    "It's your first kiss in this body; your lips feel twice as many things as they ever did before.",
    'She pulls back, grinning now, freckles beaded with water: "Grand. That\'s settled, then."',
    "You tell her again there are others you want; she says she remembers, and kisses you again.",
    "Hot shower; you touch your mouth in the steamed mirror, and laugh at yourself out loud.",
    "Late morning: laundry in Thornfield's cellar, three washers, two dryers, and a Sunday queue.",
    "Bea is in the queue with a basket; she teaches you which things can't go in the dryer.",
    "Bras on the airer, she says, never the dryer, and holds one of yours up, and you both crack up.",
    'She looks at you properly, then: your mouth, your glow. "Something\'s happened," she says.',
    "You tell her: Shiv, the rock, a kiss. Bea goes still, then says she's glad, a bit too brightly.",
    "She busies herself with the washer for a long minute; you see her blink hard.",
    "One o'clock: Sunday roast in the Great Hall, beef and gravy, the last hot food until Monday.",
    "Group F ends up at one table; Amara and Kit sit opposite each other by pure bad luck.",
    "They spar over their shared essay question, politely savage, across the gravy boat.",
    "You ask them each what they actually think; for a moment they both answer honestly.",
    "They find they disagree on exactly one point and agree on everything else, which annoys them both.",
    "Shiv sits down beside you with a full plate, bumps your knee under the table, and says nothing.",
    "Lin, across the table, sees the knee bump, and looks at her plate, thoughtful and calm.",
    "Afternoon: the boathouse lends rowing boats on Sundays; Bea signs one out and takes the oars.",
    "She rows like she was born doing it, long clean strokes, out into the middle of the mere.",
    "She stops, oars dripping, the fells all round you; the academy small and far on the shore.",
    '"Can I be honest?" she says. "When you said about Shiv, it went in me like a splinter."',
    "You tell her the truth: wanting Shiv takes nothing from wanting to be near her; it never would.",
    "Bea says she doesn't know yet what she wants with you, but she knows she wants to be in your boat.",
    '"You\'re in my boat," you say. She laughs, wet-eyed, and splashes you with an oar.',
    "She lets you try rowing; you go in a slow circle; she laughs so hard the boat rocks.",
    "Evening: the library is open till midnight on Sundays; you take your essay and the new pen.",
    "Kit is at the far end of a green-lamped table, alone; she moves her books to make room for you.",
    "You work in silence for an hour; it's the easiest silence you've had since you arrived.",
    'Kit asks to see your paragraph; she reads it twice. "This is good," she says. "Annoyingly."',
    "She says Penhallow will like that you wrote it, not what you read; you glow.",
    "Walking out at ten, Kit asks, very offhand, whether you'd go to the cinema again sometime.",
    "You say yes; she nods once, sharply, and leaves for Ashcombe before you can see her face.",
    "Thornfield kitchen: cold supper, toast and cheese; Bea's there, and Lin up from downstairs.",
    "Lin gives you a small twist of paper: one of the old nibs from Kendal, cleaned and polished.",
    '"It\'s soft," she says. "Like the one I lent you. It\'s yours now." You hold it like treasure.',
    "Bea makes three teas without asking anyone, bumps your shoulder, and her smile is real again.",
    "In bed, your mouth still remembering the mere, you think: one kiss, five girls, and Monday.",
    "A day at Hollowmere ends.",
  ],
  issues: ['"Bea makes three teas without asking anyone; Bea bumps" - doubles the beat before it'],
  lore: [
    "lore/hollowmere-amara",
    "lore/hollowmere-bea",
    "lore/hollowmere-kit",
    "lore/hollowmere-lin",
    "lore/hollowmere-nala",
    "lore/hollowmere-penhallow",
    "lore/hollowmere-priya",
    "lore/hollowmere-shiv",
    "place/hollowmere-academy",
    "place/hollowmere-thornfield-house",
  ],
  characters: [
    "character-player/hollowmere-nala",
    "character-other/hollowmere-shiv",
    "character-other/hollowmere-bea",
    "character-other/hollowmere-amara",
    "character-other/hollowmere-kit",
    "character-other/hollowmere-priya",
    "character-other/hollowmere-lin",
    "character-other/hollowmere-penhallow",
  ],
  reviewedBy: ["story-reviewer/style", "story-reviewer/continuity"],
  recordedBy: [
    "story-recorder/mechanics",
    "story-recorder/inventory",
    "story-recorder/memory",
    "story-recorder/picture",
  ],
  scenes: [
    "image/image-61e5008b567d0f8a",
    "image/image-7d26bc88d62c154c",
    "image/image-4912818b20844e8b",
    "image/image-6894107a63747dc9",
    "image/image-211ff578dfc4062f",
  ],
  pictured: [
    {
      cover: "image/image-61e5008b567d0f8a",
      coverAfter: "On the rock she wraps you in her parka again. She zips it to your chin",
      character: "character-other/hollowmere-shiv",
      outfit: "naked",
    },
    {
      cover: "image/image-7d26bc88d62c154c",
      coverAfter: "In the late morning you go down to the laundry.",
      setting: "the laundry",
    },
    {
      cover: "image/image-4912818b20844e8b",
      coverAfter: "Shiv. Her hair is damp and curling and she's in her grey hoodie, and her plate",
      character: "character-other/hollowmere-shiv",
      outfit: "grey hoodie",
    },
    {
      cover: "image/image-6894107a63747dc9",
      coverAfter: "It's down on the academy shore, past Shiv's rock, a long low wooden building",
      setting: "the boathouse",
    },
    {
      cover: "image/image-211ff578dfc4062f",
      coverAfter: "Bea is there, at the counter, with the kettle. And Lin is there too, up from",
      character: "character-other/hollowmere-lin",
      outfit: "cardigan, hair loose",
    },
  ],
} as const satisfies StoryChapterWritten
