import type { StoryChapterWritten } from "akasha/story/world/stories/written/chapters/story-chapter-written.page-type.types.ts"

export const hollowmere0014Pressure = {
  id: "01a0fea2-c0c7-74d3-b7b8-1eb8473d3ee6",
  type: "page-type/story-chapter-written",
  slug: "hollowmere-0014-pressure",
  cover: "image/image-2e12ba71b8c5002a",
  completedAt: "2026-10-02T23:45:41.156Z",
  ownProgress: 2685,
  position: 14,
  unit: "unit/words",
  title: "Pressure",
  story: "story-written/hollowmere",
  ownLength: 2685,
  prose: "txt",
  stepStatus: "step-status/player",
  beats: "jsonl",
  lore: [
    "lore/hollowmere-academy-2",
    "lore/hollowmere-bea",
    "lore/hollowmere-kit",
    "lore/hollowmere-lin",
    "lore/hollowmere-nala",
    "lore/hollowmere-nala-2",
    "lore/hollowmere-priya",
    "lore/hollowmere-shiv",
    "lore/hollowmere-world",
    "lore/hollowmere-yusra",
    "place/hollowmere-thornfield-house",
  ],
  characters: [
    "character-player/hollowmere-nala",
    "character-other/hollowmere-shiv",
    "character-other/hollowmere-bea",
    "character-other/hollowmere-kit",
    "character-other/hollowmere-lin",
    "character-other/hollowmere-priya",
    "character-other/hollowmere-yusra",
  ],
  reviewedBy: ["story-reviewer/style", "story-reviewer/continuity"],
  recordedBy: [
    "story-recorder/inventory",
    "story-recorder/mechanics",
    "story-recorder/memory",
    "story-recorder/picture",
  ],
  scenes: [
    "image/image-5044081892ae020b",
    "image/image-2e12ba71b8c5002a",
    "image/image-a3b56ed848fa9107",
  ],
} as const satisfies StoryChapterWritten
