import type { StoryChapterWritten } from "akasha/story/world/stories/written/chapters/story-chapter-written.page-type.types.ts"

export const hollowmere0004TenDegrees = {
  id: "01a0fd96-b034-7b7c-8a05-416f56e7e0d3",
  type: "page-type/story-chapter-written",
  slug: "hollowmere-0004-ten-degrees",
  cover: "image/image-1cd418b2447fcc3f",
  completedAt: "2026-10-02T18:03:39.383Z",
  ownProgress: 5699,
  position: 4,
  unit: "unit/words",
  title: "Ten Degrees",
  story: "story-written/hollowmere",
  ownLength: 5699,
  prose: "txt",
  stepStatus: "step-status/player",
  beats: [
    "Thursday: you wake at six, before Bea's knock, with Shiv's \"some morning\" in your head.",
    "You pull on the fisherman's jumper over your knickers and bra and creep down to the shore.",
    "Shiv is on the slab of rock in her parka, peeling off her socks; she sees you and grins slowly.",
    '"Some morning," she says. "Grand." She strips bare, pulls on her cap, and holds out her hand.',
    "You strip to your knickers and bra, shaking already; the mere is ten degrees and black.",
    "Shiv says the trick is not to think; she counts three and you jump together, hand in hand.",
    "The cold hits like a fist; you surface shrieking, and Shiv's hand is still in yours.",
    "She holds you up, laughing, and tells you to breathe out, slow; you do, and the panic loosens.",
    "For one long minute you tread water together, the fells pink, your whole body burning and alive.",
    "She hauls you out onto the rock and wraps you in her parka, rubbing your arms hard.",
    "Up close her wet freckled shoulders are inches from you; she sees you look, and stays close.",
    "Bea comes running along the shore at half six, sees you both, and stops dead, mouth open.",
    '"You went IN?" Bea shrieks; you nod, teeth chattering; she swears she\'s telling Yusra, grinning.',
    "Hot shower, the best of your life; your skin stays pink and humming all through breakfast.",
    "Ten o'clock: History of Magic in the Long Room; the old guilds, then the Licensing Act of 1858.",
    "Kit comes up the benches and, after a pause, silently takes the place beside you.",
    "The lecture names dates and kings you half know from Alan's history, gone strange here.",
    "You frown at a date that's wrong to you; Kit, low, asks what's the matter; you say nothing, sorry.",
    "Kit starts muttering asides about the lecturer's dates and the guildmasters' beards, deadpan.",
    "She's quietly, wickedly funny; you shake with held laughter; Kit's mouth stays perfectly straight.",
    "Amara, two rows down, turns to see what's funny, and her eyes narrow at Kit beside you.",
    "Two o'clock: practical casting in the Practice Hall again; glims, one at a time at the front.",
    "Amara goes first again and her glim is perfect again; the hall murmurs.",
    "Kit is next in line; you see her hand already starting to tremble at her side.",
    "You step out in front of her before she can move, and say you'll go, loud enough to turn heads.",
    "Every eye in the hall swings to you, the girl who'd never cast a spell.",
    "The word; the stroke, the loop, the hook curling in; you mean light with everything you have.",
    "A light rises off your palm: small, wavering, white, and it lifts, and it hangs at your eye level.",
    "It holds, three seconds, five, ten; your first glim; you hear Priya squeal and Shiv whoop.",
    "Behind you, unwatched, Kit casts; her glim rises clean and steady, and she lets it hang.",
    'The demonstrator sees both and says, "Ashby. Ashworth. Good." Then, to the room: "Next."',
    "Your glim gutters out; the headache comes, but lighter; Lin, at the back, is beaming at you.",
    'Kit passes you on the way out and says, low, "You did that on purpose." You shrug.',
    'She looks at you a long moment; "Thank you," she says; you both nearly laugh at once.',
    "Thursday evening: Yusra makes cocoa for the whole top floor in the kitchen, a Thornfield custom.",
    "The kitchen is packed with girls in pyjamas and jumpers; Bea has fetched Lin up from downstairs.",
    "Yusra heats a big pan with a quick sigil, sleeves pushed up, off-duty, sitting on the counter after.",
    "Bea announces to the kitchen that you made a glim today, and makes you show everyone.",
    "You cast it in the crowded kitchen, everyone watching; it rises, small and steady, and holds.",
    "The kitchen cheers; Lin claps her inky hands; Yusra raises her mug to you across the room.",
    "Later, the kitchen emptying, Yusra says quietly that a glim in four days from nothing is good.",
    '"I said some take a month," she says. "You\'re not some." She rinses your mug for you.',
    "Bea follows you into room 14 with her cocoa and sits on your bed, legs crossed, wanting to talk.",
    "She tells you she's kissed girls and boys both, and likes girls best, and has never been in love.",
    "She asks if you have; you say it's complicated, and she accepts that, watching you.",
    "She lies back across your narrow bed beside you, still talking, slower and slower.",
    "Bea falls asleep mid-sentence, her head on your shoulder, her hair coming loose over your neck.",
    "You lie still, the radiator knocking, her warmth all down your side, and let her stay.",
    "A day at Hollowmere ends.",
  ],
  issues: [
    '"her small tits tight-nippled, the sandy tuft over her cunt" - Hollowmere Explicitness',
    '"between her small tits. You watch it go." - Hollowmere Explicitness',
    '"Thornfield custom. Since forever." - Bea is not among those who know the Thursday cocoa custom',
  ],
  lore: [
    "lore/hollowmere-amara",
    "lore/hollowmere-bea",
    "lore/hollowmere-kit",
    "lore/hollowmere-lin",
    "lore/hollowmere-nala",
    "lore/hollowmere-priya",
    "lore/hollowmere-shiv",
    "lore/hollowmere-world",
    "lore/hollowmere-yusra",
    "place/hollowmere-academy",
    "place/hollowmere-thornfield-house",
  ],
  characters: [
    "character-player/hollowmere-nala",
    "character-other/hollowmere-shiv",
    "character-other/hollowmere-bea",
    "character-other/hollowmere-kit",
    "character-other/hollowmere-amara",
    "character-other/hollowmere-priya",
    "character-other/hollowmere-lin",
    "character-other/hollowmere-yusra",
  ],
  reviewedBy: ["story-reviewer/style", "story-reviewer/continuity"],
  recordedBy: [
    "story-recorder/mechanics",
    "story-recorder/inventory",
    "story-recorder/memory",
    "story-recorder/picture",
  ],
  scenes: [
    "image/image-3c295160e7f3f886",
    "image/image-1b6af3543adaa10b",
    "image/image-38838f1f6d33bf73",
    "image/image-6a8cec36e064d1ec",
    "image/image-1cd418b2447fcc3f",
    "image/image-611cd644977cc0a3",
    "image/image-b1d78e100d425174",
    "image/image-c75309434f028d86",
    "image/image-9baa680230eeecef",
  ],
  pictured: [
    {
      cover: "image/image-3c295160e7f3f886",
      coverAfter: "Then you get up. You don't let yourself think about it. You",
      character: "character-player/hollowmere-nala",
      outfit: "cream fisherman's jumper over knickers and a bra, bare legs, trainers",
    },
    {
      cover: "image/image-1b6af3543adaa10b",
      coverAfter: "The shore is grey and silent. The mere lies flat as a",
      setting: "the slab of rock",
    },
    {
      cover: "image/image-38838f1f6d33bf73",
      coverAfter: "She's sitting at the landward end in the big navy parka with",
      character: "character-other/hollowmere-shiv",
      outfit: "navy parka over a grey hoodie, bare legs",
    },
    {
      cover: "image/image-6a8cec36e064d1ec",
      coverAfter: "The cold hits your bare skin at once, everywhere, and you start",
      character: "character-player/hollowmere-nala",
      outfit: "knickers and a bra",
    },
    {
      cover: "image/image-1cd418b2447fcc3f",
      coverAfter: "You're treading water, the two of you, face to face, in the",
      character: "character-player/hollowmere-nala",
      outfit: "Shiv's navy parka over wet knickers and a bra, bare legs",
    },
    {
      cover: "image/image-611cd644977cc0a3",
      coverAfter: "It's Bea. She's come running along the shingle in her rowing top",
      character: "character-other/hollowmere-bea",
      outfit: "navy rowing top and black running tights",
    },
    {
      cover: "image/image-b1d78e100d425174",
      coverAfter: "Bea has been down and fetched Lin up from the floor below.",
      character: "character-other/hollowmere-lin",
      outfit: "flannel pyjamas with a cardigan over them",
    },
    {
      cover: "image/image-c75309434f028d86",
      coverAfter: "She's off duty. You can see it at once. She's in a",
      character: "character-other/hollowmere-yusra",
      outfit: "loose dark jumper with the sleeves pushed up, soft trousers",
    },
    {
      cover: "image/image-9baa680230eeecef",
      coverAfter: "She has her cocoa, a fresh mug of it, which she must",
      character: "character-other/hollowmere-bea",
      outfit: "flannel pyjamas with clouds on them, thick bed socks",
    },
  ],
} as const satisfies StoryChapterWritten
