import type { StoryChapterWritten } from "akasha/story/world/stories/written/chapters/story-chapter-written.page-type.types.ts"

export const hollowmere0006SixtyTwoPounds = {
  id: "01a0fdf3-2a3b-70df-85ff-abe7cbd20b6b",
  type: "page-type/story-chapter-written",
  slug: "hollowmere-0006-sixty-two-pounds",
  cover: "image/image-4898630145bcfb65",
  ownProgress: 3377,
  position: 6,
  unit: "unit/words",
  title: "Sixty-Two Pounds",
  story: "story-written/hollowmere",
  ownLength: 4401,
  prose: "txt",
  stepStatus: "step-status/player",
  beats: [
    "Saturday: you sleep through half six; Bea, cidered too, sleeps through it as well.",
    "You wake at ten with a dry mouth and a soft head, and the sun full on the mere.",
    "Bea hammers on your door: brunch ends at eleven, and then Kendal, everyone goes on Saturdays.",
    "Brunch in the Great Hall: eggs, bacon, mountains of toast; Lin and Priya join you, bleary.",
    "In room 14 you find your purse in your coat: a bank card in your name, a library card, notes.",
    "Sixty-two pounds. You count it twice, and it feels like the first thing that's truly yours here.",
    "The Kendal bus from the village is packed with Hollowmere girls; you squeeze in with Bea.",
    "Lin and Priya share the seat behind; forty minutes of fells and stone walls and sheep.",
    "Priya leans over the seat back and asks you, curious and kind, how you knew you liked girls.",
    "You say it was never something you had to find out; it was just there, like your hair.",
    "Priya says she's only ever gone out with boys, and never once thought hard about girls.",
    '"Isn\'t that odd?" she says. "I think hard about everything." She sits back, thoughtful.',
    "Kendal: a grey stone market town, the Saturday market filling the square.",
    "Fruit, cheese, wool in heaps, boxes of secondhand books, and a stall selling charms.",
    "Priya is lost at the charms stall at once, quizzing the stallholder about how each one works.",
    "Lin finds a box of old nibs and pen holders, and turns each over in her inky fingers.",
    "You buy a cheap fountain pen for your essay, your first purchase, and feel absurdly proud.",
    "Bea buys a bag of apples and eats one walking, offering everyone bites.",
    "The licensed charm-maker's shop: brass bells, glass cases, a framed licence over the till.",
    "Priya presses her nose to a case of charmed clockwork; her whole face lights with want.",
    "The bookshop has a café upstairs; you go up for lunch, Bea leading.",
    "Kit is at a corner table alone, a slim book open in front of her, a pot of tea.",
    'You glance at the cover as you pass: poetry. Kit snaps it shut and says, "It\'s for a friend."',
    '"Course it is," you say; Kit\'s ears go pink; Bea waves at her, beaming, and Kit nods back.',
    "You buy Bea hot chocolate and a scone with cream: a down payment, you tell her, on the scones.",
    "Bea is so delighted she hugs you over the table and knocks the sugar bowl flying.",
    "When your table is laughing loudest, you see Kit watching it over her book.",
    "On your way out you stop at Kit's table and say you're all going to the cinema at seven.",
    'Kit says she has reading; Bea, behind you, says, "Come and bite us in the dark, go on."',
    'Kit stares at Bea; then, to everyone\'s surprise, including hers, she says, "Fine."',
    "Afternoon: you wander, the four of you then five, through ginnels and down to the river.",
    "Kit walks beside you, nearly silent; once she points out a gargoyle that looks like Penhallow.",
    "The cinema is small and old, red velvet seats; the film is a costume drama, very long.",
    "You sit with Bea on one side and Lin on the other; Kit beyond Lin; Priya at the end with popcorn.",
    "In the dark, partway through, Lin's hand finds yours on the armrest, and stays.",
    "Bea, on your other side, leans her head on your shoulder at the sad part, and sniffs.",
    "Down the row, in the light off the screen, Kit is smiling at a line that no one else laughs at.",
    "The film runs late; you all run for the ten o'clock bus, the last one back, and make it.",
    "On the dark bus Kit sits by you, and says quietly it's years since she saw a film with anyone.",
    'You say it won\'t be years till the next time; she looks at her hands and says, "Perhaps."',
    "Off at the village, the five of you walk the dark mile of shore, the stars out again.",
    "Kit peels off towards Ashcombe at the gates with a small stiff wave; Bea waves both arms back.",
    "Back in room 14, with the new pen, you write the first real paragraph of your essay.",
    "It's about the thread, and the mere, and wanting light; this time you keep every word.",
    "A day at Hollowmere ends.",
  ],
  issues: [
    '"A twenty, two tens, a five... another twenty" - sums to £65 plus coins, not sixty-two pounds',
  ],
  lore: [
    "lore/hollowmere-amara",
    "lore/hollowmere-bea",
    "lore/hollowmere-kit",
    "lore/hollowmere-lin",
    "lore/hollowmere-nala",
    "lore/hollowmere-priya",
    "place/hollowmere-academy",
    "place/hollowmere-kendal",
  ],
  characters: [
    "character-player/hollowmere-nala",
    "character-other/hollowmere-bea",
    "character-other/hollowmere-lin",
    "character-other/hollowmere-priya",
    "character-other/hollowmere-kit",
    "character-other/hollowmere-amara",
  ],
  reviewedBy: ["story-reviewer/style", "story-reviewer/continuity"],
  recordedBy: [
    "story-recorder/mechanics",
    "story-recorder/inventory",
    "story-recorder/memory",
    "story-recorder/picture",
  ],
  scenes: [
    "image/image-a63df48a4dcb0612",
    "image/image-fa249f9a14aa3479",
    "image/image-51762549d74dd4a1",
    "image/image-8f70a45ff2ebfd52",
    "image/image-4898630145bcfb65",
    "image/image-96949eef3cbe20b8",
    "image/image-bc0efd2744326868",
    "image/image-e132a1bc4cd5a4c0",
  ],
  pictured: [
    {
      cover: "image/image-a63df48a4dcb0612",
      coverAfter:
        "You and Bea get plates piled high and sit down near the window, and you've barely",
      character: "character-other/hollowmere-lin",
      outfit: "soft grey jumper",
    },
    {
      cover: "image/image-fa249f9a14aa3479",
      coverAfter:
        "Then Priya arrives, in a pinafore the colour of a tangerine, with her curly hair",
      character: "character-other/hollowmere-priya",
      outfit: "tangerine pinafore over a striped long-sleeved top",
    },
    {
      cover: "image/image-51762549d74dd4a1",
      coverAfter: "The bus to Kendal goes from the village, and it's packed with Hollowmere girls.",
      setting: "the Kendal bus",
    },
    {
      cover: "image/image-8f70a45ff2ebfd52",
      coverAfter:
        "Kendal is grey stone. Grey stone houses, grey stone churches, grey stone walls and",
      setting: "the Kendal market square",
    },
    {
      cover: "image/image-4898630145bcfb65",
      coverAfter: "Off the square, down a narrow side street, there's a shop with a bow window",
      setting: "F. Harrowby & Daughters",
    },
    {
      cover: "image/image-96949eef3cbe20b8",
      coverAfter: "The bookshop has a café upstairs, and Bea leads the way.",
      setting: "the bookshop café",
    },
    {
      cover: "image/image-bc0efd2744326868",
      coverAfter: "The afternoon goes slow and golden. You wander, the four of you, and then,",
      setting: "the stone bridge over the river",
    },
    {
      cover: "image/image-e132a1bc4cd5a4c0",
      coverAfter: "The cinema is small and old and smells of popcorn and dust.",
      setting: "the cinema",
    },
  ],
} as const satisfies StoryChapterWritten
