import type { StoryChapterWritten } from "akasha/story/world/stories/written/chapters/story-chapter-written.page-type.types.ts"

export const hollowmere0031DrawWell = {
  id: "01a101fd-88bf-77d0-b795-8fa80381f4af",
  type: "page-type/story-chapter-written",
  slug: "hollowmere-0031-draw-well",
  cover: "image/image-71f478324daf3ee6",
  position: 31,
  unit: "unit/words",
  title: "Draw Well",
  story: "story-written/hollowmere",
  ownLength: 3660,
  prose: "txt",
  stepStatus: "step-status/player",
  beats: "jsonl",
  issues: ['"until she finds the place that makes you cry out" - Hollowmere Explicitness'],
  lore: [
    "lore/hollowmere-bea",
    "lore/hollowmere-bea-2",
    "lore/hollowmere-kit",
    "lore/hollowmere-kit-2",
    "lore/hollowmere-kit-3",
    "lore/hollowmere-lin",
    "lore/hollowmere-lin-2",
    "lore/hollowmere-nala",
    "lore/hollowmere-nala-2",
    "lore/hollowmere-nala-3",
  ],
  characters: [
    "character-player/hollowmere-nala",
    "character-other/hollowmere-lin",
    "character-other/hollowmere-bea",
    "character-other/hollowmere-kit",
  ],
  reviewedBy: ["story-reviewer/style", "story-reviewer/continuity"],
  recordedBy: [
    "story-recorder/inventory",
    "story-recorder/mechanics",
    "story-recorder/memory",
    "story-recorder/picture",
  ],
  scenes: ["image/image-2a05961b75ff1a26", "image/image-71f478324daf3ee6"],
} as const satisfies StoryChapterWritten
