import type { StoryChapterWritten } from "akasha/story/world/stories/written/chapters/story-chapter-written.page-type.types.ts"

export const hollowmere0002InNotOut = {
  id: "01a0fd30-8cbe-7e69-972a-88f5a076a074",
  type: "page-type/story-chapter-written",
  slug: "hollowmere-0002-in-not-out",
  cover: "image/image-7cd8b1d310c7513c",
  completedAt: "2026-10-02T17:08:07.242Z",
  ownProgress: 7315,
  position: 2,
  unit: "unit/words",
  title: "In, Not Out",
  story: "story-written/hollowmere",
  ownLength: 7315,
  prose: "txt",
  stepStatus: "step-status/player",
  beats: [
    "Half six, Tuesday: Bea bangs on your door in running kit, as she threatened.",
    "You say absolutely not through the door; she says hot water; you go.",
    "Your new body runs light and fast on the shingle, then gives out, lungs burning; Bea laughs.",
    "A girl walks out of the forbidden mere, naked but for a swim cap, steaming in the cold.",
    "Strawberry-blonde, wiry, freckled like you, crooked grin; she wraps up in a navy parka unhurried.",
    "\"Don't tell the warden,\" she says, Irish, and you can't stop looking; she clocks it and grins wider.",
    "Back before eight, the shower runs hot; hot water on this body is bliss, and you linger.",
    "Breakfast in the Great Hall with Bea, toast and porridge, the hall loud in daylight.",
    "Nine o'clock: group F climbs the library tower to Dr Penhallow's study, crammed with books.",
    "A round window looks down on the mere; a tin of shortbread sits on the desk.",
    "Dr Penhallow: lean, silver-haired, round glasses on a chain, green tweed, Cornish, kind blue eyes.",
    "The six of group F: you, Kit, and four you only half saw last night.",
    "The swimmer from the mere is here, hair still damp: Shiv, Siobhan Doyle, from Galway; she winks.",
    "Amara Osei: tall, box braids in a high ponytail, gold hoops and watch, sharp tailoring, poised.",
    "Priya Raman: round tortoiseshell glasses, nose stud, corduroy pinafore, a tote full of notebooks.",
    "Lin Zhao: quiet, low black ponytail over one shoulder, ink on her fingertips, says her name softly.",
    "Kit sits apart again, in black, her eyes carefully on the window.",
    "Dr Penhallow asks who here has never cast a single spell; you put your hand up, alone.",
    "The room looks at you; Kit's mouth flattens; Amara's brows lift.",
    'Dr Penhallow beams and hands you shortbread: "Honesty. Rarest thing in this tower. Well done."',
    "She asks what a spell is; Kit answers first, exactly: intent shaped through a focus.",
    "Amara adds a finer point about held foci before Penhallow can nod; Kit's eyes go cold.",
    "Penhallow says, dry, that she has two people competing to come top and it's only nine-fifteen.",
    "Penhallow explains foci plainly for you; Priya asks four questions, and Penhallow relishes each one.",
    "You glance at Lin's notebook: the margins are full of sigils drawn cleaner than the printed ones.",
    "Lin sees you looking and covers the page with her sleeve, pink.",
    "Eleven: the Foundations lecture in the Long Room, rows of first-years, a lecturer far below.",
    "Priya drops in beside you and lends you a pen; she takes notes in three colours.",
    "In whispers she says she did a physics degree in Leicester, then decided magic was more interesting.",
    "She mentions her boyfriend at home in Leicester, and offers to explain anything you lose track of.",
    "She explains half the lecture to you in the margins; you understand more than you feared.",
    "Lunch: group F ends up half together at one table, Shiv's feet up on the bench.",
    "Amara sits across from you, chin on her hand, and flirts with you as easily as breathing.",
    "She calls your freckles criminal; you go red to the hairline; she looks very pleased with herself.",
    "Kit, two seats down, says Amara flirts with furniture; Amara says only furniture worth it.",
    "Two o'clock: the Practice Hall, bare stone, the floorboards scorched black in patches.",
    "A brisk casting demonstrator teaches the glim: one word and one sigil, a floating light.",
    "She shows it: a word, a small sigil drawn over the palm, and a soft bead of light rises and hangs.",
    "Amara casts a glim on her first try, bright and steady; the hall turns to look; she glows too.",
    "Kit steps up next with every eye still on her; her hand lifts and stops, frozen mid-sigil.",
    "Her palm stays dark; Kit goes white, says something cutting about the draught, steps back.",
    "Her hand is shaking at her side; you see it while the others are still watching Amara.",
    "Priya gets a wobbling light that pops; Shiv gets a spark and swears in Irish; both laugh it off.",
    "Your turn: the word, the sigil; your palm stays dark, twice; the headache returns behind your eyes.",
    "Lin is beside you; silently she draws the sigil on a scrap of paper, slow, and points.",
    "Your hook is wrong: it should turn inward, not out; she shows you with an inky fingertip.",
    "You try her way; a spark of light flickers over your palm for one heartbeat, then dies.",
    "It's not a glim; it's something; Lin smiles at you, small and sudden, and looks away.",
    "The demonstrator says most manage a glim within the week, some take a month; work at it.",
    "Dusk: crossing the quad, you pass the Practice Hall and see one light through its windows.",
    "Kit is alone inside, casting glim after glim, perfect, steady, a ring of them around her.",
    "She sees you at the window; her face goes stricken; the lights wink out at once.",
    "You lift a hand, then turn and walk on, eyes ahead, leaving her the hall to herself.",
    "Evening in the Thornfield kitchen: Bea with tea; she managed half a glim and is thrilled.",
    "You tell her about the swimmer, the shortbread, the twitchy rivalry; she wants every detail again.",
    "Lin comes up from the floor below with her notebook, shy, holding out a torn page.",
    "It's the glim sigil, drawn perfectly, with arrows showing the turn of the hook.",
    "You thank her; Bea makes her a tea in a yellow mug; Lin stays, quiet, and laughs once at Bea.",
    'Yusra passes the kitchen door, stops: "Ashby. First day of classes. How was it?"',
    "You show her: the word, the sigil; a spark flickers and dies; the headache pulses.",
    "Yusra says some take a month, and to drink water for the headache; she fills you a glass herself.",
    'Her fingers brush yours handing it over; she says, "Room 1," and goes.',
    "In bed, Lin's page propped on the desk, you trace the sigil in the dark until your eyes close.",
    "You think of Kit's stricken face at the window, and decide it stays between you and her.",
    "A day at Hollowmere ends.",
  ],
  issues: ['"I haven\'t seen you since breakfast" - Bea waved at you in the Practice Hall at two'],
  lore: [
    "lore/hollowmere-amara",
    "lore/hollowmere-bea",
    "lore/hollowmere-kit",
    "lore/hollowmere-lin",
    "lore/hollowmere-nala",
    "lore/hollowmere-penhallow",
    "lore/hollowmere-priya",
    "lore/hollowmere-shiv",
    "lore/hollowmere-world",
    "lore/hollowmere-yusra",
    "place/hollowmere-academy",
  ],
  characters: [
    "character-player/hollowmere-nala",
    "character-other/hollowmere-bea",
    "character-other/hollowmere-shiv",
    "character-other/hollowmere-penhallow",
    "character-other/hollowmere-kit",
    "character-other/hollowmere-amara",
    "character-other/hollowmere-priya",
    "character-other/hollowmere-lin",
    "character-other/hollowmere-yusra",
  ],
  reviewedBy: ["story-reviewer/style", "story-reviewer/continuity"],
  recordedBy: [
    "story-recorder/mechanics",
    "story-recorder/inventory",
    "story-recorder/memory",
    "story-recorder/picture",
  ],
  scenes: [
    "image/image-7ebde942103a976e",
    "image/image-c0d84046e307f702",
    "image/image-7f6201c857ea19df",
    "image/image-5040139d4d52fcde",
    "image/image-debe774ab589521f",
    "image/image-2f8d2b04fa9aead7",
    "image/image-8f6cf462f5e91021",
    "image/image-8f78cd677cd5c52f",
    "image/image-7cd8b1d310c7513c",
    "image/image-0c64735213b65cea",
  ],
  pictured: [
    {
      cover: "image/image-1179e4ffc548e625",
      coverAfter: "She comes up out of the water fifty yards ahead of you,",
      character: "character-other/hollowmere-shiv",
      outfit: "naked but for a white swim cap",
      setting: "the mere",
    },
    {
      cover: "image/image-c0d84046e307f702",
      coverAfter: "She's slim and wiry, a swimmer's body, all long lean muscle, her",
      character: "character-other/hollowmere-penhallow",
      outfit: "green tweed jacket over a cream silk blouse, charcoal wool skirt",
      setting: "Dr Penhallow's study",
    },
    {
      cover: "image/image-7f6201c857ea19df",
      coverAfter: "Books. Books everywhere, floor to ceiling on every wall, stacked on the",
      character: "character-player/hollowmere-nala",
      outfit: "grey jumper and jeans",
    },
    {
      cover: "image/image-5040139d4d52fcde",
      coverAfter: "You feel the whole room turn to look at you. Shiv with",
      character: "character-other/hollowmere-lin",
      outfit: "oatmeal knit turtleneck jumper, dark green pleated skirt",
    },
    {
      cover: "image/image-debe774ab589521f",
      coverAfter: "She explains half the lecture to you in the margins. Little diagrams",
      character: "character-other/hollowmere-priya",
      outfit: "mustard corduroy pinafore over a striped long-sleeved top",
      setting: "the Long Room",
    },
    {
      cover: "image/image-2f8d2b04fa9aead7",
      coverAfter: "It's a bare stone hall at the back of the west range,",
      character: "character-other/hollowmere-amara",
      outfit: "fitted cream knit jumper, gold hoops and a gold watch",
    },
    {
      cover: "image/image-8f6cf462f5e91021",
      coverAfter: "It just stops. Her finger hangs in the air above her palm,",
      character: "character-other/hollowmere-kit",
      outfit: "high-necked black jumper, long black wool skirt",
      setting: "the Practice Hall",
    },
    {
      cover: "image/image-8f78cd677cd5c52f",
      coverAfter: "Glim after glim. You watch her do it: the word, the sigil,",
      character: "character-player/hollowmere-nala",
      outfit: "grey jumper and jeans",
    },
    {
      cover: "image/image-7cd8b1d310c7513c",
      coverAfter: "You don't tell her about the Practice Hall. About the dark palm",
      character: "character-other/hollowmere-kit",
      outfit: "high-necked black jumper, long black wool skirt",
    },
    {
      cover: "image/image-0c64735213b65cea",
      coverAfter: "In bed, with the light off, you've propped Lin's page up against",
      character: "character-player/hollowmere-nala",
      outfit: "long white cotton nightshirt",
    },
  ],
} as const satisfies StoryChapterWritten
