import type { StoryChapterWritten } from "akasha/story/world/stories/written/chapters/story-chapter-written.page-type.types.ts"

export const hollowmere0017EmergencyContact = {
  id: "01a0ff04-8a52-7a81-ab6c-369c74644134",
  type: "page-type/story-chapter-written",
  slug: "hollowmere-0017-emergency-contact",
  cover: "image/image-6fc4a56dc7904e91",
  completedAt: "2026-10-03T00:54:32.099Z",
  ownProgress: 2857,
  position: 17,
  unit: "unit/words",
  title: "Emergency Contact",
  story: "story-written/hollowmere",
  ownLength: 2857,
  prose: "txt",
  stepStatus: "step-status/player",
  beats: "jsonl",
  issues: "txt",
  lore: [
    "lore/hollowmere-academy-2",
    "lore/hollowmere-bea",
    "lore/hollowmere-kit",
    "lore/hollowmere-kit-2",
    "lore/hollowmere-lin",
    "lore/hollowmere-nala",
    "lore/hollowmere-nala-2",
    "lore/hollowmere-shiv",
  ],
  characters: [
    "character-player/hollowmere-nala",
    "character-other/hollowmere-shiv",
    "character-other/hollowmere-bea",
    "character-other/hollowmere-lin",
    "character-other/hollowmere-kit",
  ],
  reviewedBy: ["story-reviewer/style", "story-reviewer/continuity"],
  recordedBy: [
    "story-recorder/mechanics",
    "story-recorder/inventory",
    "story-recorder/memory",
    "story-recorder/picture",
  ],
  scenes: [
    "image/image-6fc4a56dc7904e91",
    "image/image-49c9b21c0881dd3c",
    "image/image-53f61d90b0c4f5a1",
  ],
} as const satisfies StoryChapterWritten
