import type { StoryChapterWritten } from "akasha/story/world/stories/written/chapters/story-chapter-written.page-type.types.ts"

export const hollowmere0009GoodnightNala = {
  id: "01a0fe4e-d2e8-73dc-996c-7cfe9fe2ca75",
  type: "page-type/story-chapter-written",
  slug: "hollowmere-0009-goodnight-nala",
  cover: "image/image-1ae1d72d9abae353",
  ownProgress: 202,
  position: 9,
  unit: "unit/words",
  title: "Goodnight, Nala",
  story: "story-written/hollowmere",
  ownLength: 3505,
  prose: "txt",
  stepStatus: "step-status/player",
  beats: [
    "Tuesday: dawn on Shiv's rock; three minutes in the mere now, and you only gasp once.",
    "Wrapped in her parka, you tell Shiv about Bea and the rock and the kiss on your cheek.",
    'Shiv grins: "Good. She\'s lovely, that one." She kisses you, salt and cold, as if to say so too.',
    "At breakfast Bea sits close, shy and bright; she bumps your shoulder twice before the porridge.",
    "Nine: Penhallow's tutorial; essays due Friday; she asks each of you one line of your argument.",
    'Yours is "wherever the wanting lives"; Penhallow says, "Hm," and writes it down, which is worse.',
    "Lunch: the societies fair fills the Great Hall, trestle tables, banners, girls shouting offers.",
    "Rowing for Bea, who signs before the captain finishes her sentence; debating for Amara.",
    "Priya hovers at charmcraft, already asking how the society's clockwork mouse is wound.",
    "Lin lingers at life drawing, reads the sign-up sheet twice, and signs very small at the bottom.",
    "The cold-water swimmers swim the mere legally, at dawn, with a safety boat and a register.",
    'Shiv calls it swimming with a nanny; then signs, because you do, and writes "Doyle (reluctant)."',
    "At the poetry table Kit stands reading the list of meetings, a pen already in her hand.",
    'She sees you and says, "For a friend." You take the pen from her and sign, and hand it back.',
    "Kit signs directly under you, neat and fast, and walks off silently, ears pink.",
    "Two o'clock: the Practice Hall, the warming charm again, smooth grey stones on the benches.",
    "Amara's stone steams in a minute; Kit's, at her end bench, shimmers; yours is barely warm again.",
    "You push; you grip and pull at the thread from your chest, harder, and harder.",
    "The stone goes hot all at once; and something warm runs from your nose onto your lip.",
    "Blood, bright on the scorched boards; the hall tilts; the demonstrator is there, steadying you.",
    '"Overreaching," she says, not unkind. "Sit. Head forward. Pinch. Nothing more today."',
    "Kit appears beside you and presses a folded black handkerchief into your hand, an initial on it.",
    "She sits with you on the bench in silence until it stops, her shoulder against yours.",
    "By evening the bleeding has stopped, but the headache is the worst yet, a hammer behind your eyes.",
    "At eleven, unable to sleep, you knock on room 1; it's dark and silent.",
    "A girl down the corridor says Yusra does night shifts in the infirmary, Tuesdays and Thursdays.",
    "You go across the cold dark quad in your coat and jumper to the west range.",
    "The infirmary: six white beds, all empty, a dispensary, one lamp lit on a desk.",
    "Yusra is at the desk in a white tunic, hair tied back, reading glasses on; she looks up.",
    '"Ashby." She\'s up and round the desk at once, a hand under your chin, tilting your face to the lamp.',
    "You tell her about the stone and the blood; she checks your eyes with a small light, very close.",
    "She sits you on a bed and gives you water and a draught from the dispensary that tastes of mint.",
    '"You push like someone with something to prove," she says. "Who to?"',
    "You say you don't know; maybe to yourself; maybe to whoever you were before.",
    "Yusra looks at you a long moment, and lets it lie.",
    "She lets you stay an hour on the quiet ward while the headache eases, the lamp low.",
    "She tells you why healing: her father the GP, her mother the midwife, hands that make things better.",
    '"I\'m your warden," she says at last, quietly. "There are lines I keep. You should know that."',
    '"I know," you say; she holds your eyes, and you hold hers, for a long while.',
    'She walks you to the infirmary door; "Goodnight, Nala," she says, the first time she\'s used it.',
    "You cross the dark quad back to Thornfield with your own name ringing in your ears.",
    "A day at Hollowmere ends.",
  ],
  issues: [
    '"the girl in Penhallow\'s study writing down your one line" - Dr Penhallow, 58, wrote it',
  ],
  lore: [
    "lore/hollowmere-amara",
    "lore/hollowmere-bea",
    "lore/hollowmere-kit",
    "lore/hollowmere-lin",
    "lore/hollowmere-nala",
    "lore/hollowmere-nala-2",
    "lore/hollowmere-penhallow",
    "lore/hollowmere-priya",
    "lore/hollowmere-shiv",
    "lore/hollowmere-yusra",
    "place/hollowmere-academy",
  ],
  characters: [
    "character-player/hollowmere-nala",
    "character-other/hollowmere-shiv",
    "character-other/hollowmere-bea",
    "character-other/hollowmere-penhallow",
    "character-other/hollowmere-priya",
    "character-other/hollowmere-amara",
    "character-other/hollowmere-kit",
    "character-other/hollowmere-lin",
    "character-other/hollowmere-yusra",
  ],
  reviewedBy: ["story-reviewer/continuity", "story-reviewer/style"],
  recordedBy: [
    "story-recorder/mechanics",
    "story-recorder/inventory",
    "story-recorder/memory",
    "story-recorder/picture",
  ],
  scenes: [
    "image/image-e68ea34e0c29d660",
    "image/image-cdf11fa6b384f60c",
    "image/image-1ae1d72d9abae353",
  ],
  pictured: [
    {
      cover: "image/image-e68ea34e0c29d660",
      coverAfter: "You go in your coat over your nightshirt and the fisherman's jumper",
      character: "character-player/hollowmere-nala",
      outfit:
        "navy wool coat over a cream fisherman's jumper over the long white nightshirt, trainers",
    },
    {
      cover: "image/image-cdf11fa6b384f60c",
      coverAfter: "It's a long white room. Six beds, three down each side, with",
      setting: "the infirmary",
    },
    {
      cover: "image/image-1ae1d72d9abae353",
      coverAfter: "She's in a white tunic, short-sleeved, buttoned at the shoulder, like a",
      character: "character-other/hollowmere-yusra",
      outfit: "white short-sleeved healer's tunic, reading glasses, hair tied back",
    },
  ],
} as const satisfies StoryChapterWritten
