import type { StoryChapterWritten } from "akasha/story/world/stories/written/chapters/story-chapter-written.page-type.types.ts"

export const hollowmere0026ItKnowsMe = {
  id: "01a101b1-12ba-7361-b460-9ad956d5b980",
  type: "page-type/story-chapter-written",
  slug: "hollowmere-0026-it-knows-me",
  cover: "image/image-6d23a36a37e25d74",
  ownProgress: 1976,
  position: 26,
  unit: "unit/words",
  title: "It Knows Me",
  story: "story-written/hollowmere",
  ownLength: 5080,
  prose: "txt",
  stepStatus: "step-status/player",
  beats: [
    "Friday of week four: a clear cold morning after the rain; the mere is flat and silver from 15.",
    "Bea is up first, doing press-ups on the rug in her vest, counting under her breath, very seriously.",
    '"Tomorrow," she says between them. "Seven. The boathouse. You promised." You say you\'ll be there.',
    "Your ward essay is in your bag, three pages, clean-copied in the Snug yesterday afternoon.",
    "Nine: group F climbs the library tower; Dr Penhallow's round window is full of blue sky and mere.",
    "The essays go on her desk in a pile; you put yours in her hand, as she asked you to once.",
    "Penhallow reads your first line there and then, glasses on their chain, and glances up at you.",
    '"Mending," she says. "Hm." She puts it on the pile, and her mouth twitches. "We\'ll see."',
    "She asks each of you to say in one sentence what your ward kept in. Priya says: the heat, obviously.",
    "Amara says: the flame's own shape. Kit says: a house. Penhallow nods at that, slowly.",
    "Shiv says: breath. She leaves it there; Penhallow looks at her a moment, and lets it be.",
    'Lin says, very quietly: "What you want, until you\'re ready to say it." The room goes still.',
    "Penhallow takes the lid off the shortbread tin and holds it out to Lin. Lin takes one, pink.",
    'You say: what\'s mending. Penhallow looks at you over her glasses and says, "Tuesday. Green ink."',
    "Then she chalks next week's question on her little board: What does a focus remember, and should it?",
    '"Due Friday," she says. "And I want what happened to you." Priya groans again, louder.',
    "You put your hand up. \"I don't know what a focus remembers. I don't know much about foci at all.\"",
    'Penhallow beams at you. "Good. Then find out. Ask someone who makes them." Kit sits up straight.',
    'On the tower stairs Kit catches your sleeve. "The forge," she says. "This afternoon. I\'ll show you."',
    "Lunch in the Great Hall: Bea eats for two, carb-loading, she says, which Priya says isn't a thing.",
    "Shiv eats with you and Bea; she says she'll be on the bank tomorrow too, shouting rude things.",
    "Afternoon: the forge behind the east range, hot and dim, smelling of coal and hot metal.",
    "Kit's in a leather apron with her sleeves rolled up and soot on her cheek, at home here.",
    "She shows you the nibs and rings on her bench, and a small blade half-finished in the vice.",
    'She puts a plain silver ring in your palm. "First one I made. Feel it. It knows me."',
    "It is cool and plain, and it feels like something; you tell her so, and Kit grins, delighted.",
    '"That\'s it," Kit says. "That\'s the question. Does it remember me? Should it?"',
    "She shows you how she draws the metal out, the hammer quick and sure; sparks jump, and she laughs.",
    "You watch her forearms, her quick hands, the sweat at her hairline; Kit catches you looking.",
    "She goes red, and keeps working; at the end she wipes her hands and kisses you, quick, sooty.",
    "You walk back across the quad together; she's left a smudge of soot on your chin, and leaves it.",
    "Evening: the Drowned Bell, the whole table of you, Friday crowded and warm and loud.",
    "Bea drinks one half and switches to lemonade for the race training; everyone cheers her for it.",
    "Lin's had no letter back yet; she says it'll take a week at least, and drinks her half fast.",
    "Priya and Amara sit pressed together on the bench, arguing happily about clockwork and law.",
    "Yusra comes in off duty with two third-years and sits by the fire, in a soft dark jumper.",
    "She finds you across the room, and lifts her pint; then she holds up nine fingers, and you nod.",
    'Bea sees it, and says "Nine o\'clock, eh," in your ear, and squeezes your knee, teasing and warm.',
    "Kit walks back with you and Bea and Lin; at the Thornfield gate she says goodnight to each of you.",
    'Bea goes up to 15 early. "Big day. Bed." She takes your hand on the stairs and pulls you with her.',
    'In 15 she shuts the door and leans on it, looking at you. "Early night," she says. "Not sleep yet."',
    "She undresses you slowly, by the lamp, and kisses each bit of you as she bares it.",
    "You undress her too: her strong shoulders, her breasts, the blistered hands she tries to hide.",
    "On the bed she lies over you, all warmth and weight, and kisses you deep and unhurried.",
    "She kisses down to your breasts and takes a nipple in her mouth; you arch, and hold her head there.",
    "Her hand slides between your legs and finds your pussy wet already; she groans softly at that.",
    '"Look at you," Bea whispers. She strokes you slow, two fingers over your clit, round and round.',
    "You touch her too: her pussy hot and slick under your fingers; she gasps against your neck.",
    "You make love slowly, face to face, your fingers inside each other, moving together.",
    "Bea comes first, shaking and laughing into your shoulder, saying your name over and over.",
    "Then she slides down the bed and puts her mouth on your pussy, licking you, slow and sure.",
    "You come with her tongue on your clit and her hands holding your hips, crying out into the pillow.",
    'After, she lies with her head on your breast, her heart slowing. "Good luck charm," she says.',
    '"Now I can\'t lose," Bea says. You laugh; she sets her alarm for six, and turns out the lamp.',
    "You fall asleep tangled with her, your hand on her back, the mere silver at the window.",
    "A day at Hollowmere ends.",
  ],
  issues: [
    '"You clean-copied it last night ... while Bea read" - in ch25 she talked, then fell asleep',
  ],
  lore: [
    "lore/hollowmere-amara",
    "lore/hollowmere-bea",
    "lore/hollowmere-bea-2",
    "lore/hollowmere-kit",
    "lore/hollowmere-kit-2",
    "lore/hollowmere-lin",
    "lore/hollowmere-lin-2",
    "lore/hollowmere-nala",
    "lore/hollowmere-nala-2",
    "lore/hollowmere-penhallow",
    "lore/hollowmere-priya",
    "lore/hollowmere-shiv",
    "lore/hollowmere-shiv-2",
    "lore/hollowmere-yusra",
    "lore/hollowmere-yusra-2",
  ],
  characters: [
    "character-player/hollowmere-nala",
    "character-other/hollowmere-bea",
    "character-other/hollowmere-penhallow",
    "character-other/hollowmere-priya",
    "character-other/hollowmere-amara",
    "character-other/hollowmere-kit",
    "character-other/hollowmere-shiv",
    "character-other/hollowmere-lin",
    "character-other/hollowmere-yusra",
  ],
  reviewedBy: ["story-reviewer/style", "story-reviewer/continuity"],
  recordedBy: [
    "story-recorder/mechanics",
    "story-recorder/inventory",
    "story-recorder/memory",
    "story-recorder/picture",
  ],
  scenes: [
    "image/image-a9c7c607040ce9d5",
    "image/image-6f91605a6358db9e",
    "image/image-6d23a36a37e25d74",
  ],
  pictured: [
    {
      cover: "image/image-a9c7c607040ce9d5",
      coverAfter: "She's on the rug in the middle of the floor, in her vest",
      character: "character-other/hollowmere-bea",
      outfit: "vest and knickers",
    },
    {
      cover: "image/image-6f91605a6358db9e",
      coverAfter: "It's hot, and dim. After the bright cold outside it takes your eyes",
      setting: "the forge",
    },
    {
      cover: "image/image-6d23a36a37e25d74",
      coverAfter: "She's in a leather apron, heavy and scarred, tied over her black jumper",
      character: "character-other/hollowmere-kit",
      outfit: "leather apron over a black jumper, sleeves rolled past the elbow, soot on her cheek",
    },
  ],
} as const satisfies StoryChapterWritten
