apiVersion: v1
kind: Secret
metadata:
    name: postgrest-secrets
    namespace: postgrest
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:1D4o3orsedVt0rkDpybnjOXbNlxxNCBk2isEEeF6vTYcEx4JWY2ms9YzOL44ywmW+oOYNEIoITdoEsoOXnQg3GLPARWCUqOyzRxOwyn74KRyXEgVcmmDB6bsULBFGDSAiDNQfn1o74kKofx2d/uuHJ69yQHstMYg91oG,iv:1t3t9DZBpzsBlTZR7DH3xRBzUV4/QuDISvaUs8SXuf0=,tag:MOWFHqR92TtCH1RM53LWUw==,type:str]
    PGRST_JWT_SECRET: ENC[AES256_GCM,data:Tqoyk/zK55T8iJjpysrQPY6g/3XGaaIPPucskL3uWLDgq6UgD9ZvLcS1pWioErml4Tpbe4oOSEM+b3nrlIPFmUryJDc+rkz1sEgjUobzA+goop4NjsyvkB2UOdyUxJU/Sj/LM+jeug9cB06AtARsC1o6oZZ/pk5EhwJ/RUNV5wEyqdqK5516ZxrXMvkG3FFk2vInuGAg3SOvXtfaqdLx8BMe7CsubxSA4oOkLm9pCjdRCUazMA4CgFTToLi+VWzWj9kDikfZFES+cCpUXtqpeRPi5mrj5R8aweCtIozrmWE/r6M/dZOUkbOZhjB5ylXnT3BSAgjpcBvfYZFhKjS3sJeDstq94eZMfteXYyHcJAazykAcEGOkdZc6bbwBeq3ptURqvecSmDgm8FYzvMT3LGsIgEjOFaYKH5YY6hNcfkOM2AxubMTM5UwmQzfkDItE6K9H5pflNgY9XqY95uckeK0aMZuUMBwYeudCn99cM7I+jfMUjNQ3QJq1aOjXCinaG2ng4U0RYElxYbak2j8elfSOEA+2D/mCYInSvUwXOXol+j2iDAypJw==,iv:xvTKJiWhdfuHdj72em/G+MPIflYMufIqMkLT1wIK/0Y=,tag:IF+s5JNSSD4sMnCCso145Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnWC9zN0xRdlhZUkUyTTZl
            RE9YalpzSStyalh0QkhOTUVTMUVxYytWY0I4CnB4MVJtMzZORDZ0MTY0b202NzFK
            eEJXYnFEaUxUU1N4YWtId1I1bXNGVmsKLS0tIHpSS3preElLc3hyNEU3Y2hDaS8z
            ME96bUJNQ2tzMldnT3lXRHFRam0wbmMK53ho+iEoEZQK5mebzWo8kxrEnxSlNp6R
            9S8FYPj/pT0wyN67pX9LLwWEYNduWhix7hqrEJsM49oUEW5vtiro+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-25T22:42:55Z"
    mac: ENC[AES256_GCM,data:r8RFbz1I4rvfv8Xck/z5d1RitGeuL+qe32QD+Fi+tEJCfitleBl/5SJh+P5qd5d+y1HyLu6jnctDP6sqlZuSHGEZUmrwzHDiJ4IMYimCzZks/bz4jPk+BF/q1ldN/sRn9xYkny4KBHOuAhLri4OvfJoGlWTo2seAG4I2nCwScYM=,iv:o1bRtOKxKTND49JN7sdi+NfjXPIkOmQS79KIgNxrGNQ=,tag:P827QB+B8jJ7XzyHyffVDw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
