import type { StoryTurnPlayed } from "akasha/story/world/stories/played/turns/story-turn-played.page-type.types.ts"

export const otherwhereIv00012 = {
  id: "01a0eaa4-0862-7a0e-b803-b8ca07e1e46f",
  type: "page-type/story-turn-played",
  slug: "otherwhere-iv-00-012",
  cover: "image/image-f51c0908cdcb557c",
  coverAfter: "Gu takes the three smoking sticks out of your hand, gently, with",
  ownLength: 444,
  unit: "unit/words",
  partOfCollections: ["story-played/otherwhere-iv"],
  position: 12,
  prose: "txt",
  characters: ["character-player/otherwhere-iv-nala", "character-other/otherwhere-iv-zhao-jun"],
  stepStatus: "step-status/player",
  action:
    "\"You two look like just kind of strong lads who would do well on a hunt, but I'm afraid that's not up to me. You'll need to talk with Headman Gu and Zhao Jun about that. I have great knowledge, but when it comes to the hunt itself, Headman Gu is more mighty than I.\"",
  beats: [
    'Nala says, "You two look like just the kind of strong lads who would do well on a hunt."',
    "\"But I'm afraid that's not up to me.\"",
    '"You\'ll need to talk with Headman Gu and Zhao Jun about that."',
    '"I have great knowledge, but when it comes to the hunt itself, Headman Gu is more mighty than I."',
    "The Fang brothers grin at each other as if she had handed them a prize.",
    '"Strong lads!" Fang Da says, loud enough for the back rows. "You heard her. Strong lads!"',
    "A laugh runs through the crowd, and the Fangs puff up like roosters.",
    "Gu takes the three smoking sticks from Nala's hand, gently, with a small bow.",
    "He bows three times to the shrine, plants them in the sand of the burner, and turns to the crowd.",
    '"You heard the honored spirit. The hunt is the headman\'s business. So hear the headman."',
    '"Tie Bo will lead it, if he will. Nobody else. Tie Bo knows boar."',
    '"The Fang boys can beat, with torches and gongs, if they can keep their mouths shut for once."',
    "The laugh this time is louder, and Fang Er goes red to the ears.",
    '"Zhao Jun. You come to my house tonight and tell me all of it about your walls. All of it."',
    "Zhao Jun, somewhere in the crowd, ducks his head.",
    '"The almanac says tomorrow is good for hunting. We will see. Now go home. Eat."',
    "The crowd loosens and breaks up, talking, looking back over their shoulders at Nala.",
    "The tea-stall woman goes among them with her basket, handing out steamed buns.",
    "She stops in front of Nala, bows, and holds out the basket with both hands.",
    '"Lin Qiao, from the stall under the camphor. Please, honored spirit. They\'re still warm."',
    "Her small boy stares up at Nala's hair with his mouth open until she tugs him away.",
    "The square empties. The last light goes out of the sky, and the lamp at the shrine burns alone.",
    "Only one man stays: the lean, weathered one with the bow, who has not moved all this time.",
    "He comes up now, slow and quiet, and bows, not deeply.",
    '"Tie Bo," he says. His voice is low and rough. "The hunter."',
    '"Zhao Jun says you told him it might be a boar. Or a spirit beast."',
    'He looks at her steadily. "Which is it?"',
  ],
  lore: ["lore/otherwhere-iv-gu-household"],
  reviewedBy: ["story-reviewer/style", "story-reviewer/continuity"],
  recordedBy: ["story-recorder/mechanics", "story-recorder/picture", "story-recorder/memory"],
  endsAt: "2026-09-28T19:25:00.000Z",
} as const satisfies StoryTurnPlayed
