import type { StoryTurnPlayed } from "akasha/story/world/stories/played/turns/story-turn-played.page-type.types.ts"

export const otherwhereIv00006 = {
  id: "01a0ea37-506e-7a10-9404-76c29d65c543",
  type: "page-type/story-turn-played",
  slug: "otherwhere-iv-00-006",
  ownLength: 659,
  unit: "unit/words",
  partOfCollections: ["story-played/otherwhere-iv"],
  position: 6,
  prose: "txt",
  characters: ["character-player/otherwhere-iv-nala", "character-other/otherwhere-iv-zhao-jun"],
  stepStatus: "step-status/recorders",
  action: '"Gladly"',
  beats: [
    '"Gladly," Nala says.',
    "Xu Hong bows again and leads the way, and Zhao Jun follows a pace behind Nala with his hoe.",
    "The Zhao house sits just below the track: two rooms of mud brick under thatch, a swept yard.",
    "A girl of about fourteen is feeding a fire by the door, a little one of six beside her.",
    "Both girls freeze at the sight of Nala, and the little one hides behind her sister's legs.",
    '"Mei, the good bowl. Lan, stop staring," Xu Hong says. Neither girl stops staring.',
    "Inside, a small shrine to the ancestors stands against the back wall, a stub of incense before it.",
    "They sit Nala in the seat that faces the door, and nobody else sits until she does.",
    "Mei brings rice in a glazed bowl, the only one without a chip in it.",
    "With it come pickled mustard greens, half a salted duck egg, and a cup of weak, hot tea.",
    "The family eats from plain bowls, squatting, watching her from the corners of their eyes.",
    "The rice is plain and the greens are sour and salty, and it is the best thing she has ever eaten.",
    "She drinks the tea, and then another cup, and the dryness in her mouth is gone.",
    "Mei pulls a stool close to the fire for her, and her wet tights and shirt hem steam and dry.",
    "Little Lan edges closer and closer until she is staring at Nala's hair from arm's length.",
    "When the bowls are empty, Zhao Jun puts on a clean jacket and walks her down to the village.",
    "Xu Hong stays behind, but not before she presses both hands together and bows once more.",
    "The track leaves the terraces and runs in among rammed-earth walls and grey tile and thatch roofs.",
    "Where it enters the village, a big camphor tree shades a stall where a woman sets out stools.",
    "She sees Nala, drops a stool, and doesn't pick it up.",
    "Dogs start barking. Children come running from every yard and trail behind at a safe distance.",
    "Doors open. Faces appear over walls. The whispering follows them all the way in.",
    "At the heart of the village three tall grey stones stand around a small shrine.",
    "Facing the square is the only house with a tiled gate. Zhao Jun knocks, and calls out.",
    "A servant boy opens it, stares, and runs back inside.",
    "In the courtyard beyond sits an old man at a low table spread with ledgers and a pot of tea.",
    "He is past sixty, thin and grey, his bad leg stretched out stiff in front of him.",
    "A grey-haired woman stands in the house door behind him, a cloth in her hands, very still.",
    'Zhao Jun bows almost to the ground. "Headman Gu. This one has brought an honored spirit."',
    "The old man looks at Nala for a long moment: her hair, her face, her bare feet, the strange shirt.",
    "He rises with a cane, slowly, and bows politely, but not deeply.",
    '"Honored guest. Forgive an old man. Folk at the Lanqiao fairs have claimed to be spirits before."',
    '"They took a good many coins from people who believed them."',
    '"Would you permit this old man a question or two, before we speak of anything else?"',
  ],
  lore: ["lore/otherwhere-iv-three-stones-folk"],
  reviewedBy: ["story-reviewer/style", "story-reviewer/continuity"],
  endsAt: "2026-09-28T08:22:00.000Z",
} as const satisfies StoryTurnPlayed
