import type { StoryTurnPlayed } from "akasha/story/world/stories/played/turns/story-turn-played.page-type.types.ts"

export const otherwhereIv00002 = {
  id: "01a0e9f1-31b2-7790-adbb-bbc195f510e9",
  type: "page-type/story-turn-played",
  slug: "otherwhere-iv-00-002",
  cover: "image/image-c360d525f930879f",
  ownLength: 665,
  unit: "unit/words",
  partOfCollections: ["story-played/otherwhere-iv"],
  position: 2,
  prose: "txt",
  characters: ["character-player/otherwhere-iv-nala"],
  stepStatus: "step-status/player",
  action: "A start walking toward the village, keeping my eyes and ears open for signs of danger",
  beats: [
    "Nala sets off barefoot down the cart track on the river's left bank, eyes and ears open.",
    "The packed earth is cool, with pebbles in the ruts, so she walks the grassy crown between them.",
    "Her stride is shorter than she expects, and she keeps misjudging how far a step will carry her.",
    "Her long hair swings against her back with every step.",
    "Every little while she stops, listens, and looks back upstream at the dark pine-and-bamboo hills.",
    "Nothing follows her, and the birds keep singing.",
    "The mist lifts off the river as the sun clears the hills.",
    "Flooded terraces step down the slopes beside the track, rows of young rice standing in them.",
    "Her mouth is dry and her stomach empty and gnawing, and the clear river runs beside her all the way.",
    "Far off, figures in wide straw hats work bent over, knee-deep in the paddies.",
    "A grey water buffalo grazes on a field bank, and white egrets stalk the shallows.",
    "Near the upper terraces, a paddy wall beside the track has been broken open.",
    "The gap is wide, the mud slumped out in a fan, the water drained into the terrace below.",
    "The rice shoots in that corner are flattened and torn.",
    "She looks for what did it, but the ground is churned to soup and she can make nothing of it.",
    "It could be anything, or only a wall that gave way.",
    "She steps onto the slumped bank to see better, and the wet mud gives under her bare foot.",
    "She slides down into the terrace below, up to her knees in cold water and mud.",
    "The mud sucks at her feet, and wading out she tramples a row of the young shoots.",
    "She climbs back onto the track soaked to the thighs, the shirt's hem dripping.",
    "Her tights are mud to the knee, and mud is caked on her feet.",
    "From the next terrace down, a farmer in a straw hat straightens up and splashes toward her.",
    'He shouts, "Hey! Hey! Get out of there! That\'s my rice!"',
    "He is a lean, sunburnt man of middle years, trousers rolled to the knee, a weeding hoe in his hand.",
    "At the bank below her he gets his first proper look at her and stops short.",
    "He stares at her red hair, her freckles, her bare feet and the strange grey shirt.",
    "The hoe comes down to his side.",
    '"Heavens and earth," he says. "What are you?"',
  ],
  issues: [
    '"nobody in the hills has seen" - What It Is',
    '"long enough on her to reach mid-thigh" - What It Is',
  ],
  lore: [
    "place/otherwhere-iv-three-stones-village",
    "lore/otherwhere-iv-three-stones-folk",
    "place/otherwhere-iv-willow-bend",
  ],
  reviewedBy: ["story-reviewer/style", "story-reviewer/continuity"],
  recordedBy: ["story-recorder/mechanics", "story-recorder/memory", "story-recorder/picture"],
  endsAt: "2026-09-28T06:42:00.000Z",
} as const satisfies StoryTurnPlayed
