import type { TemperSet } from "akasha/temper/catalog/gear/temper-set/temper-set.page-type.types.ts"

export const wrathOfTheImperium = {
  id: "019e66ec-7a19-72f9-9c3b-9012b3bc5c9e",
  type: "page-type/temper-set",
  slug: "wrath-of-the-imperium",
  title: "Wrath of the Imperium",
  key: "wrath-of-the-imperium",
  esoSetId: 125,
  hashPlace: 695,
  esoItemIds: [
    89987, 89988, 89989, 89990, 89991, 89992, 89993, 89994, 89995, 89996, 89997, 89998, 89999,
    90000, 90001,
  ],
  esoEquipTypes: [
    "EQUIP_TYPE_NECK",
    "EQUIP_TYPE_OFF_HAND",
    "EQUIP_TYPE_ONE_HAND",
    "EQUIP_TYPE_RING",
    "EQUIP_TYPE_TWO_HAND",
  ],
  esoWeaponTypes: [
    "WEAPONTYPE_AXE",
    "WEAPONTYPE_BOW",
    "WEAPONTYPE_DAGGER",
    "WEAPONTYPE_FIRE_STAFF",
    "WEAPONTYPE_FROST_STAFF",
    "WEAPONTYPE_HAMMER",
    "WEAPONTYPE_HEALING_STAFF",
    "WEAPONTYPE_LIGHTNING_STAFF",
    "WEAPONTYPE_SHIELD",
    "WEAPONTYPE_SWORD",
    "WEAPONTYPE_TWO_HANDED_AXE",
    "WEAPONTYPE_TWO_HANDED_HAMMER",
    "WEAPONTYPE_TWO_HANDED_SWORD",
  ],
  setWayshrines: [-1, -1, -1],
  setTypeId: 4,
  setProcsAllowedInPvp: true,
  setNameZh: "帝国之怒",
  setNameRu: "Гнев Империи",
  setNameFr: "La Fureur de l'Empire",
  setNameEs: "Cólera del Imperio",
  setNameDe: "Zorn des Kaiserreichs",
  setDropZones: [181, 181, 181, 181, 181, 181],
  setDropMechanics: [3, 36, 18, 35, 7, 21],
  setDlcId: 0,
  itemBrowserSources: ["181:-201"],
  itemBrowserPlaceKinds: [2],
  itemBrowserKinds: ["alliance-style", "jewelry"],
  itemBrowserItemId: 89988,
  category: "temper-set-category/pvp",
  valid: ["weapon:*", "jewelry:*"],
  bonuses: "jsonl",
  icons: "jsonl",
} as const satisfies TemperSet
