import { achievementName } from "../destinations-data-runtime/destinations-data-runtime.module.code.ts"

export const SETTINGS_STRINGS_02: Record<string, string> = {
  GLOBAL_SETTINGS_SELECT_TEXT_ONLY: "Nur Text!",
  POITYPE_AOI: "Sehenswürdigkeit",
  POITYPE_AYLEID_WELL: "Ayleïden Brunnen",
  POITYPE_BRAWL: zo_strformat(achievementName(1247)),
  POITYPE_BREAKING_ENTERING: zo_strformat(achievementName(1349)),
  POITYPE_CHAMPION: "Champions/Dungeon Bosses",
  POITYPE_COLLECTIBLE: "Sammlungen",
  POITYPE_CRAFTING: "Handwerksstation",
  POITYPE_CRIME_PAYS: zo_strformat(achievementName(869)),
  POITYPE_CUTPURSE_ABOVE: zo_strformat(achievementName(1383)),
  POITYPE_DARK_BROTHERHOOD: "Dunkle Bruderschaft",
  POITYPE_DEADLANDS_ENTRANCE: "Deadlands Entrance",
  POITYPE_DELVE: "Gewölbe",
  POITYPE_DOLMEN: "Dolmen",
  POITYPE_DRUIDIC_SHRINE: "Druidic Shrine",
  POITYPE_DWEMER_RUIN: "Dwemerruinen",
  POITYPE_EARTHLYPOS: zo_strformat(achievementName(1121)),
  POITYPE_ENDLESS_ARCHIVE: "Endless Archive",
  POITYPE_FISH: "Angeln",
  POITYPE_GATE: "Tor",
  POITYPE_GIVE_TO_THE_POOR: zo_strformat(achievementName(871)),
  POITYPE_GROUPBOSS: "Gruppenboss",
  POITYPE_GROUPDELVE: "Gruppengewölbe",
  POITYPE_GROUPDUNGEON: "Gruppenverlies",
  POITYPE_GROUPEVENT: "Gruppenveranstaltung",
  POITYPE_HOUSING: "Haus",
  POITYPE_LB_GTTP_CP:
    zo_strformat(achievementName(873)) +
    "/" +
    zo_strformat(achievementName(871)) +
    "/" +
    zo_strformat(achievementName(869)),
  POITYPE_LIGHTBRINGER: zo_strformat(achievementName(873)),
  POITYPE_MAIQ: zo_strformat(achievementName(872)),
  POITYPE_MUNDUS: "Mundusstein",
  POITYPE_NOSEDIVER: zo_strformat(achievementName(406)),
  POITYPE_ON_ME: zo_strformat(achievementName(704)),
  POITYPE_PATRON: zo_strformat(achievementName(1316)),
  POITYPE_PEACEMAKER: zo_strformat(achievementName(716)),
  POITYPE_PUBLICDUNGEON: "Öffentliches Verlies",
  POITYPE_QUESTHUB: "Quest Hub",
  POITYPE_RELICHUNTER: zo_strformat(achievementName(1250)),
  POITYPE_SOLOTRIAL: "Prüfung",
  POITYPE_TRADER: "Gildenhändler",
  POITYPE_TRIALINSTANCE: "Prüfungsinstanz",
  POITYPE_UNDETERMINED: "Unbestimmt",
  POITYPE_UNKNOWN: "unbekannt",
  POITYPE_VAMPIRE_ALTAR: "Vampir Altar",
  POITYPE_VAULT: "Trophäenkammer",
  POITYPE_WAYSHRINE: "Wegschrein",
  POITYPE_WEREWOLF_SHRINE: "Werwolf Schrein",
  POITYPE_WROTHGAR_JUMPER: zo_strformat(achievementName(1331)),
  POITYPE_WWVAMP: "Werwölfe/Vampire",
  RELOADUI_INFO: "Erst nach einem 'ReloadUI' werden diese Einstellungen übernommen.",
  RELOADUI_WARNING: "Wenn du diesen Knopf drückst, führt das Spiel einen /reloadui aus",
}
