import { resolve } from "node:path"
import type { ServiceConfig } from "./generate-dockerfiles-types"

export const ROOT = resolve(import.meta.dirname, "../../../..")
export const HEADER = "# DO NOT EDIT — generated by scripts/generate-dockerfiles.ts\n"

export const SERVICES: Record<string, ServiceConfig> = {
  "auth-proxy": { type: "bun-service", dir: "packages/infra/auth-proxy" },
  "gfs-promoter": {
    type: "bun-service",
    dir: "packages/infra/k8s/postgres/gfs-promoter",
  },
  "alanwalton-calendar-sync": {
    type: "bun-service",
    dir: "packages/alanwalton/calendar/sync",
  },
  ci: {
    type: "tool-image",
    dir: "packages/infra/lib",
    extensionFile: "ci.dockerfile-extensions.json",
  },
  "bun-git": {
    type: "tool-image",
    dir: "packages/infra/lib",
    extensionFile: "bun-git.dockerfile-extensions.json",
  },
  buildkit: {
    type: "tool-image",
    dir: "packages/infra/lib",
    extensionFile: "buildkit.dockerfile-extensions.json",
  },
  kubectl: {
    type: "tool-image",
    dir: "packages/infra/lib",
    extensionFile: "kubectl.dockerfile-extensions.json",
  },
}
