import type { SetTemplate } from "@akasha/temper-equipment/set-template"

export const SETS_DATA_005: readonly SetTemplate[] = [
  {
    id: "arkays-charity",
    name: "Arkay's Charity",
    esoSetId: 802,
    subcategoryId: "no-type",
    valid: ["*:light"],
    bonuses: [
      {
        count: 2,
        status: "supported",
        effects: [{ metricId: "magicka-recovery", effectType: "integer", effectValue: 129 }],
        description: "Adds 129 Magicka Recovery",
      },
      {
        count: 3,
        status: "supported",
        effects: [{ metricId: "magicka-recovery", effectType: "integer", effectValue: 129 }],
        description: "Adds 129 Magicka Recovery",
      },
      {
        count: 4,
        status: "supported",
        effects: [{ metricId: "magicka-maximum", effectType: "integer", effectValue: 1096 }],
        description: "Adds 1096 Maximum Magicka",
      },
      {
        count: 5,
        status: "unsupported",
        effects: [],
        description:
          "When you cleanse a negative effect from yourself or an ally, restore 13 Ultimate to the target. This effect can occur once every 9 seconds per target.",
      },
    ],
    icons: {
      "axe": "/esoui/art/icons/gear_breton_1haxe_d.dds",
      "battleaxe": "/esoui/art/icons/gear_breton_2haxe_d.dds",
      "bow": "/esoui/art/icons/gear_breton_bow_d.dds",
      "chest:*": "/esoui/art/icons/gear_breton_light_robe_d.dds",
      "dagger": "/esoui/art/icons/gear_breton_dagger_d.dds",
      "feet:*": "/esoui/art/icons/gear_breton_light_feet_d.dds",
      "greatsword": "/esoui/art/icons/gear_breton_2hsword_d.dds",
      "hands:*": "/esoui/art/icons/gear_breton_light_hands_d.dds",
      "head:*": "/esoui/art/icons/gear_breton_light_head_d.dds",
      "ice-staff": "/esoui/art/icons/gear_breton_staff_d.dds",
      "inferno-staff": "/esoui/art/icons/gear_breton_staff_d.dds",
      "legs:*": "/esoui/art/icons/gear_breton_light_legs_d.dds",
      "lightning-staff": "/esoui/art/icons/gear_breton_staff_d.dds",
      "mace": "/esoui/art/icons/gear_breton_1hhammer_d.dds",
      "maul": "/esoui/art/icons/gear_breton_2hhammer_d.dds",
      "necklace": "/esoui/art/icons/gear_breton_neck_a.dds",
      "restoration-staff": "/esoui/art/icons/gear_breton_staff_d.dds",
      "ring": "/esoui/art/icons/gear_breton_ring_a.dds",
      "shield": "/esoui/art/icons/gear_breton_shield_d.dds",
      "shoulders:*": "/esoui/art/icons/gear_breton_light_shoulders_d.dds",
      "sword": "/esoui/art/icons/gear_breton_1hsword_d.dds",
      "waist:*": "/esoui/art/icons/gear_breton_light_waist_d.dds",
    },
  },
  {
    id: "armor-master",
    name: "Armor Master",
    esoSetId: 178,
    subcategoryId: "crafted",
    valid: ["*"],
    bonuses: [
      {
        count: 2,
        status: "supported",
        effects: [{ metricId: "health-maximum", effectType: "integer", effectValue: 1206 }],
        description: "Adds 1206 Maximum Health",
      },
      {
        count: 3,
        status: "supported",
        effects: [{ metricId: "resistance", effectType: "integer", effectValue: 743 }],
        description: "Adds 1487 Armor",
      },
      {
        count: 4,
        status: "supported",
        effects: [{ metricId: "resistance", effectType: "integer", effectValue: 743 }],
        description: "Adds 1487 Armor",
      },
      {
        count: 5,
        status: "unsupported",
        effects: [],
        description:
          "While you have an Armor ability slotted, your Max Health is increased by 5%. When you use an Armor ability while in combat, your Physical and Spell Resistance is increased by 5940 for 10 seconds.",
      },
    ],
    icons: {
      "axe": "/esoui/art/icons/gear_breton_1haxe_d.dds",
      "battleaxe": "/esoui/art/icons/gear_breton_2haxe_d.dds",
      "bow": "/esoui/art/icons/gear_breton_bow_d.dds",
      "chest:heavy": "/esoui/art/icons/gear_breton_heavy_chest_d.dds",
      "chest:light": "/esoui/art/icons/gear_breton_light_robe_d.dds",
      "chest:medium": "/esoui/art/icons/gear_breton_medium_chest_d.dds",
      "dagger": "/esoui/art/icons/gear_breton_dagger_d.dds",
      "feet:heavy": "/esoui/art/icons/gear_breton_heavy_feet_d.dds",
      "feet:light": "/esoui/art/icons/gear_breton_light_feet_d.dds",
      "feet:medium": "/esoui/art/icons/gear_breton_medium_feet_d.dds",
      "greatsword": "/esoui/art/icons/gear_breton_2hsword_d.dds",
      "hands:heavy": "/esoui/art/icons/gear_breton_heavy_hands_d.dds",
      "hands:light": "/esoui/art/icons/gear_breton_light_hands_d.dds",
      "hands:medium": "/esoui/art/icons/gear_breton_medium_hands_d.dds",
      "head:heavy": "/esoui/art/icons/gear_breton_heavy_head_d.dds",
      "head:light": "/esoui/art/icons/gear_breton_light_head_d.dds",
      "head:medium": "/esoui/art/icons/gear_breton_medium_head_d.dds",
      "ice-staff": "/esoui/art/icons/gear_breton_staff_d.dds",
      "inferno-staff": "/esoui/art/icons/gear_breton_staff_d.dds",
      "legs:heavy": "/esoui/art/icons/gear_breton_heavy_legs_d.dds",
      "legs:light": "/esoui/art/icons/gear_breton_light_legs_d.dds",
      "legs:medium": "/esoui/art/icons/gear_breton_medium_legs_d.dds",
      "lightning-staff": "/esoui/art/icons/gear_breton_staff_d.dds",
      "mace": "/esoui/art/icons/gear_breton_1hhammer_d.dds",
      "maul": "/esoui/art/icons/gear_breton_2hhammer_d.dds",
      "necklace": "/esoui/art/icons/gear_breton_neck_a.dds",
      "restoration-staff": "/esoui/art/icons/gear_breton_staff_d.dds",
      "ring": "/esoui/art/icons/gear_breton_ring_a.dds",
      "shield": "/esoui/art/icons/gear_breton_shield_d.dds",
      "shoulders:heavy": "/esoui/art/icons/gear_breton_heavy_shoulders_d.dds",
      "shoulders:light": "/esoui/art/icons/gear_breton_light_shoulders_d.dds",
      "shoulders:medium": "/esoui/art/icons/gear_breton_medium_shoulders_d.dds",
      "sword": "/esoui/art/icons/gear_breton_1hsword_d.dds",
      "waist:heavy": "/esoui/art/icons/gear_breton_heavy_waist_d.dds",
      "waist:light": "/esoui/art/icons/gear_breton_light_waist_d.dds",
      "waist:medium": "/esoui/art/icons/gear_breton_medium_waist_d.dds",
    },
  },
  {
    id: "armor-of-the-code",
    name: "Armor of the Code",
    esoSetId: 209,
    subcategoryId: "other",
    valid: ["jewelry:*"],
    bonuses: [
      {
        count: 1,
        status: "unsupported",
        effects: [],
        description:
          "Increase your Critical Chance against targets with a lower % of health than you by 2051.",
      },
      {
        count: 2,
        status: "supported",
        effects: [{ metricId: "magicka-maximum", effectType: "integer", effectValue: 1096 }],
        description: "Adds 1096 Maximum Magicka",
      },
      {
        count: 3,
        status: "supported",
        effects: [{ metricId: "magicka-recovery", effectType: "integer", effectValue: 129 }],
        description: "Adds 129 Magicka Recovery",
      },
      {
        count: 4,
        status: "supported",
        effects: [{ metricId: "magicka-maximum", effectType: "integer", effectValue: 1096 }],
        description: "Adds 1096 Maximum Magicka",
      },
    ],
    icons: {
      necklace: "/esoui/art/icons/gear_breton_neck_a.dds",
      ring: "/esoui/art/icons/gear_breton_ring_a.dds",
    },
  },
  {
    id: "armor-of-the-seducer",
    name: "Armor of the Seducer",
    esoSetId: 43,
    subcategoryId: "crafted",
    valid: ["*"],
    bonuses: [
      {
        count: 2,
        status: "supported",
        effects: [{ metricId: "magicka-recovery", effectType: "integer", effectValue: 129 }],
        description: "Adds 129 Magicka Recovery",
      },
      {
        count: 3,
        status: "supported",
        effects: [{ metricId: "magicka-maximum", effectType: "integer", effectValue: 1096 }],
        description: "Adds 1096 Maximum Magicka",
      },
      {
        count: 4,
        status: "supported",
        effects: [{ metricId: "magicka-recovery", effectType: "integer", effectValue: 129 }],
        description: "Adds 129 Magicka Recovery",
      },
      {
        count: 5,
        status: "unsupported",
        effects: [],
        description: "Reduces the cost of your Magicka abilities by 10%.",
      },
    ],
    icons: {
      "axe": "/esoui/art/icons/gear_breton_1haxe_d.dds",
      "battleaxe": "/esoui/art/icons/gear_breton_2haxe_d.dds",
      "bow": "/esoui/art/icons/gear_breton_bow_d.dds",
      "chest:heavy": "/esoui/art/icons/gear_breton_heavy_chest_d.dds",
      "chest:light": "/esoui/art/icons/gear_breton_light_robe_d.dds",
      "chest:medium": "/esoui/art/icons/gear_breton_medium_chest_d.dds",
      "dagger": "/esoui/art/icons/gear_breton_dagger_d.dds",
      "feet:heavy": "/esoui/art/icons/gear_breton_heavy_feet_d.dds",
      "feet:light": "/esoui/art/icons/gear_breton_light_feet_d.dds",
      "feet:medium": "/esoui/art/icons/gear_breton_medium_feet_d.dds",
      "greatsword": "/esoui/art/icons/gear_breton_2hsword_d.dds",
      "hands:heavy": "/esoui/art/icons/gear_breton_heavy_hands_d.dds",
      "hands:light": "/esoui/art/icons/gear_breton_light_hands_d.dds",
      "hands:medium": "/esoui/art/icons/gear_breton_medium_hands_d.dds",
      "head:heavy": "/esoui/art/icons/gear_breton_heavy_head_d.dds",
      "head:light": "/esoui/art/icons/gear_breton_light_head_d.dds",
      "head:medium": "/esoui/art/icons/gear_breton_medium_head_d.dds",
      "ice-staff": "/esoui/art/icons/gear_breton_staff_d.dds",
      "inferno-staff": "/esoui/art/icons/gear_breton_staff_d.dds",
      "legs:heavy": "/esoui/art/icons/gear_breton_heavy_legs_d.dds",
      "legs:light": "/esoui/art/icons/gear_breton_light_legs_d.dds",
      "legs:medium": "/esoui/art/icons/gear_breton_medium_legs_d.dds",
      "lightning-staff": "/esoui/art/icons/gear_breton_staff_d.dds",
      "mace": "/esoui/art/icons/gear_breton_1hhammer_d.dds",
      "maul": "/esoui/art/icons/gear_breton_2hhammer_d.dds",
      "necklace": "/esoui/art/icons/gear_breton_neck_a.dds",
      "restoration-staff": "/esoui/art/icons/gear_breton_staff_d.dds",
      "ring": "/esoui/art/icons/gear_breton_ring_a.dds",
      "shield": "/esoui/art/icons/gear_breton_shield_d.dds",
      "shoulders:heavy": "/esoui/art/icons/gear_breton_heavy_shoulders_d.dds",
      "shoulders:light": "/esoui/art/icons/gear_breton_light_shoulders_d.dds",
      "shoulders:medium": "/esoui/art/icons/gear_breton_medium_shoulders_d.dds",
      "sword": "/esoui/art/icons/gear_breton_1hsword_d.dds",
      "waist:heavy": "/esoui/art/icons/gear_breton_heavy_waist_d.dds",
      "waist:light": "/esoui/art/icons/gear_breton_light_waist_d.dds",
      "waist:medium": "/esoui/art/icons/gear_breton_medium_waist_d.dds",
    },
  },
]
