import type { PageType } from "akasha/page/type/page-type.page-type.types.ts"

export const worldMechanic = {
  id: "01a06558-a991-7f75-b03b-962c2df9e390",
  type: "page-type/page-type",
  slug: "world-mechanic",
  definition: "a thing a world does the same way every time",
  pluralSlug: "mechanics",
  extends: ["page-type/page"],
  runsTabooCheck: false,
  parts: [
    "boolean-property/claimed",
    "boolean-property/effect-claimed",
    "domain/ability",
    "module/action-intent",
    "module/dice-reading",
    "module/dice-rolling",
    "module/dice-throwing",
    "module/linear-stat",
    "module/strike-resolution",
    "module/target-roll",
    "number-property/paragraph",
    "number-property/reference-level",
    "page-property-entry/references",
    "page-type/world-aspect",
    "page-type/world-attunement",
    "page-type/world-boon",
    "page-type/world-carried-memory",
    "page-type/world-check",
    "page-type/world-class",
    "page-type/world-condition",
    "page-type/world-curse",
    "page-type/world-derived-metric",
    "page-type/world-element",
    "page-type/world-enchantment",
    "page-type/world-item",
    "page-type/world-legacy",
    "page-type/world-metric",
    "page-type/world-miracle",
    "page-type/world-quest",
    "page-type/world-recipe",
    "page-type/world-religion",
    "page-type/world-relationship",
    "page-type/world-reputation",
    "page-type/world-skill",
    "page-type/world-song",
    "page-type/world-species",
    "page-type/world-spell",
    "page-type/world-title",
    "page-type/world-trait",
    "text-property/aliases",
    "text-property/chapter-slug",
    "text-property/claimed-by-slug",
    "text-property/effect-quote",
    "multi-relation-property/evolves-from-slugs",
    "multi-relation-property/evolves-to-slugs",
    "text-property/from-slug",
    "text-property/holder-quote",
    "text-property/holder-slug",
    "text-property/reference-event",
    "text-property/reference-kind",
    "text-property/to-slug",
    "text-property/wording",
  ],
  properties: [
    { pageProperty: "relation-property/world", required: false, many: false },
    { pageProperty: "number-property/appearance-count", required: false, many: false },
    { pageProperty: "text-property/aliases", required: false, many: true, maxCount: null },
    {
      pageProperty: "multi-relation-property/evolves-from-slugs",
      required: false,
      many: true,
      maxCount: null,
    },
    {
      pageProperty: "multi-relation-property/evolves-to-slugs",
      required: false,
      many: true,
      maxCount: null,
    },
    { pageProperty: "page-property-entry/references", required: false, many: false },
  ],
  decisions: [
    {
      decisionKind: "decision-kind/departure",
      statement: "A mechanic belongs to one world.",
    },
    {
      decisionKind: "decision-kind/departure",
      statement: "Which kind of mechanic a thing is settles which page type that thing is.",
    },
    {
      decisionKind: "decision-kind/departure",
      statement: "A name two kinds carry is two mechanics rather than a single mechanic.",
    },
    {
      decisionKind: "decision-kind/departure",
      statement:
        "A mechanic is as its own world says rather than as a rulebook outside that world says.",
    },
    {
      decisionKind: "decision-kind/departure",
      statement: "A slug that cannot become an export name has its kind on the front.",
    },
    {
      decisionKind: "decision-kind/departure",
      statement: "An evolution is a fact about the mechanic rather than one place in the text.",
    },
    {
      decisionKind: "decision-kind/departure",
      statement:
        "Where the text shows an evolution the reference beside the evolution has that place.",
    },
    {
      decisionKind: "decision-kind/departure",
      statement:
        "The words a mechanic read out of a story has are the story's rather than akasha's own.",
    },
    {
      decisionKind: "decision-kind/departure",
      statement: "A kind the readings fill adds no property to the properties the base has.",
    },
    {
      decisionKind: "decision-kind/departure",
      statement: "The base leaves the title to each kind.",
    },
    {
      decisionKind: "decision-kind/departure",
      statement: "A generic kind is a mechanic as a world defines it.",
    },
    {
      decisionKind: "decision-kind/departure",
      statement: "A kind holding one character's state extends the generic kind that state is of.",
    },
    {
      decisionKind: "decision-kind/departure",
      statement: "A mechanic no kind fits is a page of the base itself.",
    },
    {
      decisionKind: "decision-kind/departure",
      statement: "A kind is its own page type so one kind's slugs are alone.",
    },
    {
      decisionKind: "decision-kind/departure",
      statement: "Thirty-two names sit in two kinds at once.",
    },
    {
      decisionKind: "decision-kind/upkeep",
      statement: "Every mechanic a world's readings name is a page of a type this domain has.",
    },
    {
      decisionKind: "decision-kind/departure",
      statement: "A mechanic's appearances are how many chapters that mechanic is referenced in.",
    },
  ],
  types: "ts",
  schema: "jsonl",
} as const satisfies PageType
