import type { SkillTemplate } from "../character-skill-template/character-skill-template.module.code.ts"

export const CHARACTER_SKILLS_65 = {
  "spell-recharge-35993": {
    id: "spell-recharge-35993" as const,
    esoSkillId: 35993,
    name: "Spell Recharge",
    baseName: "Spell Recharge",
    skillLineId: "racial-high-elf-skills" as const,
    skillType: "passive" as const,
    description:
      "When you activate an ability, you restore |cffffff200|r Magicka or Stamina, based on whichever is lowest. This effect can occur once every |cffffff6|r seconds.\n\nWhen you are using an ability with a channel or cast time, you take |cffffff1|r% less damage.",
    icon: "/esoui/art/icons/ability_sorcerer_063.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 5,
    rank: 5,
    subcategoryId: "racial-high-elf-skills" as const,
  },
  "spell-symmetry": {
    id: "spell-symmetry" as const,
    esoSkillId: 42263,
    name: "Spell Symmetry",
    baseName: "Equilibrium",
    skillLineId: "guild-mages-guild" as const,
    skillType: "active" as const,
    description:
      "Barter with Oblivion to trade vitality for power, sacrificing your Health in exchange for 3000 Magicka.\n\nAfter the exchange is complete, the cost of your next Magicka ability is reduced by 33% for 5 seconds.\n\nThe exchange reduces your healing done and damage shield strength by 50% for 4 seconds.",
    icon: "/esoui/art/icons/ability_mageguild_003_a.dds",
    isMorph: true,
    morphIndex: 1,
    lineRankNeeded: 8,
    rank: 8,
    subcategoryId: "guild-mages-guild" as const,
  },
  "spell-symmetry-40445": {
    id: "spell-symmetry-40445" as const,
    esoSkillId: 40445,
    name: "Spell Symmetry",
    baseName: "Equilibrium",
    skillLineId: "guild-mages-guild" as const,
    skillType: "active" as const,
    description:
      "Barter with Oblivion to trade vitality for power, sacrificing your Health in exchange for |cffffff3000|r Magicka.\n\nAfter the exchange is complete, the cost of your next Magicka ability is reduced by |cffffff33|r% for |cffffff5|r seconds.\n\nThe exchange reduces your healing done and damage shield strength by |cffffff50|r% for |cffffff4|r seconds.",
    icon: "/esoui/art/icons/ability_mageguild_003_a.dds",
    isMorph: true,
    morphIndex: 1,
    lineRankNeeded: 8,
    rank: 8,
    subcategoryId: "guild-mages-guild" as const,
  },
  "spell-wall": {
    id: "spell-wall" as const,
    esoSkillId: 86333,
    name: "Spell Wall",
    baseName: "Shield Wall",
    skillLineId: "weapon-one-hand-and-shield" as const,
    skillType: "ultimate" as const,
    description:
      "Reinforce your shield, allowing you to automatically block all attacks at no cost and reflect all projectiles cast at you for 7 seconds.",
    icon: "/esoui/art/icons/ability_1handed_006_a.dds",
    isMorph: true,
    morphIndex: 1,
    lineRankNeeded: 50,
    rank: 8,
    subcategoryId: "weapon-one-hand-and-shield" as const,
  },
  "spell-wall-83292": {
    id: "spell-wall-83292" as const,
    esoSkillId: 83292,
    name: "Spell Wall",
    baseName: "Shield Wall",
    skillLineId: "weapon-one-hand-and-shield" as const,
    skillType: "ultimate" as const,
    description:
      "Reinforce your shield, allowing you to automatically block all attacks at no cost and reflect all projectiles cast at you for |cffffff7|r seconds.",
    icon: "/esoui/art/icons/ability_1handed_006_a.dds",
    isMorph: true,
    morphIndex: 1,
    lineRankNeeded: 50,
    rank: 50,
    subcategoryId: "weapon-one-hand-and-shield" as const,
  },
  "spell-warding": {
    id: "spell-warding" as const,
    esoSkillId: 45559,
    name: "Spell Warding",
    baseName: "Spell Warding",
    skillLineId: "armor-light-armor" as const,
    skillType: "passive" as const,
    description:
      "Increases your Spell Resistance by 726 for each piece of Light Armor equipped. \n\nCurrent bonus: 0.",
    icon: "/esoui/art/icons/ability_armor_006.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 14,
    rank: 2,
    subcategoryId: "armor-light-armor" as const,
    effects: [
      {
        "metricId": "resistance-spell",
        "valueType": "integer",
        "effectType": "armor-piece-scaling",
        "armorWeight": "light",
        "valuePerPiece": 726,
      },
    ] as const,
    status: "supported" as const,
  },
  "spiked-bone-shield": {
    id: "spiked-bone-shield" as const,
    esoSkillId: 43323,
    name: "Spiked Bone Shield",
    baseName: "Bone Shield",
    skillLineId: "guild-undaunted" as const,
    skillType: "active" as const,
    description:
      "Surround yourself with a whirlwind of bones, gaining a damage shield that absorbs up to 4958 damage for 6 seconds and returns 100% of direct damage absorbed back to the enemy. This ability scales off your Max Health.\n\nAn ally near you can activate the Bone Wall synergy, granting the ally and up to 5 other allies a damage shield equal to 30% of their Max Health for 6 seconds.",
    icon: "/esoui/art/icons/ability_undaunted_005b.dds",
    isMorph: true,
    morphIndex: 1,
    lineRankNeeded: 4,
    rank: 8,
    subcategoryId: "guild-undaunted" as const,
  },
  "spiked-bone-shield-42138": {
    id: "spiked-bone-shield-42138" as const,
    esoSkillId: 42138,
    name: "Spiked Bone Shield",
    baseName: "Bone Shield",
    skillLineId: "guild-undaunted" as const,
    skillType: "active" as const,
    description:
      "Surround yourself with a whirlwind of bones, gaining a damage shield that absorbs up to |cffffff7027|r damage for |cffffff6|r seconds and returns |cffffff100|r% of direct damage absorbed back to the enemy. This ability scales off your Max Health.\n\nAn ally near you can activate the Bone Wall synergy, granting the ally and up to |cffffff5|r other allies a damage shield equal to |cffffff35|r% of their Max Health for |cffffff6|r seconds.",
    icon: "/esoui/art/icons/ability_undaunted_005b.dds",
    isMorph: true,
    morphIndex: 1,
    lineRankNeeded: 4,
    rank: 4,
    subcategoryId: "guild-undaunted" as const,
  },
  "spirit-guardian": {
    id: "spirit-guardian" as const,
    esoSkillId: 40118912,
    name: "Spirit Guardian",
    baseName: "Spirit Mender",
    skillLineId: "necromancer-living-death" as const,
    skillType: "active" as const,
    description:
      "Conjure a ghostly spirit to do your bidding and stay by your side for 16 seconds. The spirit heals you or the lowest Health ally around you every 2 seconds, restoring 718 Health.\n\nWhile active, 10% of the damage you take is transferred to the spirit instead.\n\nCreates a corpse on death if you are in combat.",
    icon: "/esoui/art/icons/ability_necromancer_015_a.dds",
    isMorph: true,
    morphIndex: 1,
    lineRankNeeded: 30,
    rank: 8,
    subcategoryId: "necromancer-living-death" as const,
  },
  "spirit-guardian-118912": {
    id: "spirit-guardian-118912" as const,
    esoSkillId: 118912,
    name: "Spirit Guardian",
    baseName: "Spirit Mender",
    skillLineId: "necromancer-living-death" as const,
    skillType: "active" as const,
    description:
      "Conjure a ghostly spirit to do your bidding and stay by your side for |cffffff16|r seconds. The spirit heals you or the lowest Health ally around you every |cffffff2|r seconds, restoring |cffffff2262|r Health.\n\nWhile active, |cffffff10|r% of the damage you take is transferred to the spirit instead.\n\nCreates a corpse on death if you are in combat.",
    icon: "/esoui/art/icons/ability_necromancer_015_a.dds",
    isMorph: true,
    morphIndex: 1,
    lineRankNeeded: 30,
    rank: 30,
    subcategoryId: "necromancer-living-death" as const,
  },
  "spirit-mender": {
    id: "spirit-mender" as const,
    esoSkillId: 115710,
    name: "Spirit Mender",
    baseName: "Spirit Mender",
    skillLineId: "necromancer-living-death" as const,
    skillType: "active" as const,
    description:
      "Conjure a ghostly spirit to do your bidding and stay by your side for |cffffff16|r seconds. The spirit heals you or the lowest Health ally around you every |cffffff2|r seconds, restoring |cffffff2191|r Health.\n\nCreates a corpse on death if you are in combat.",
    icon: "/esoui/art/icons/ability_necromancer_015.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 30,
    rank: 30,
    subcategoryId: "necromancer-living-death" as const,
  },
  "spiteward-of-the-lucid-mind": {
    id: "spiteward-of-the-lucid-mind" as const,
    esoSkillId: 40185901,
    name: "Spiteward of the Lucid Mind",
    baseName: "Runespite Ward",
    skillLineId: "arcanist-soldier-of-apocrypha" as const,
    skillType: "active" as const,
    description:
      "Like the rune knights of old, summon a shield that absorbs 4800 damage for 6 seconds, scaling off your Max Health.\n\nThe first time you take direct damage, the shield retaliates and deals 0 Magic Damage to the attacker, scaling off your Armor.\n\nConsume Crux to heal yourself 1600 Health, scaling off your Max Health, and refund 30% of Spiteward of the Lucid Mind cost per Crux spent.",
    icon: "/esoui/art/icons/ability_arcanist_008_a.dds",
    isMorph: true,
    morphIndex: 1,
    lineRankNeeded: 4,
    rank: 8,
    subcategoryId: "arcanist-soldier-of-apocrypha" as const,
  },
  "spiteward-of-the-lucid-mind-185901": {
    id: "spiteward-of-the-lucid-mind-185901" as const,
    esoSkillId: 185901,
    name: "Spiteward of the Lucid Mind",
    baseName: "Runespite Ward",
    skillLineId: "arcanist-soldier-of-apocrypha" as const,
    skillType: "active" as const,
    description:
      "Like the rune knights of old, summon a shield that absorbs |cffffff6802|r damage for |cffffff6|r seconds, scaling off your Max Health.\n\nThe first time you take direct damage, the shield retaliates and deals |cffffff1951|r Magic Damage to the attacker, scaling off your Armor.\n\nConsume Crux to heal yourself |cffffff2010|r Health, scaling off your Max Health, and refund |cffffff30|r% of Spiteward of the Lucid Mind cost per Crux spent.",
    icon: "/esoui/art/icons/ability_arcanist_008_a.dds",
    isMorph: true,
    morphIndex: 1,
    lineRankNeeded: 4,
    rank: 4,
    subcategoryId: "arcanist-soldier-of-apocrypha" as const,
  },
  "splintered-secrets": {
    id: "splintered-secrets" as const,
    esoSkillId: 184887,
    name: "Splintered Secrets",
    baseName: "Splintered Secrets",
    skillLineId: "arcanist-herald-of-the-tome" as const,
    skillType: "passive" as const,
    description:
      "What they don't know can kill them. Increase your Physical and Spell Penetration by 1240 per Herald of the Tome ability slotted.\n\nCurrent bonus: 0.",
    icon: "/esoui/art/icons/passive_arcanist_01.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 39,
    rank: 2,
    subcategoryId: "arcanist-herald-of-the-tome" as const,
    effects: [
      {
        "metricId": "penetration",
        "effectType": "slotted-ability-scaling",
        "skillLineId": "arcanist-herald-of-the-tome",
        "valuePerAbility": 1240,
      },
    ] as const,
    status: "supported" as const,
  },
  "stalwart": {
    id: "stalwart" as const,
    esoSkillId: 45298,
    name: "Stalwart",
    baseName: "Stalwart",
    skillLineId: "racial-nord-skills" as const,
    skillType: "passive" as const,
    description:
      "Increases your Max Stamina by 1500.\n\nWhen you take damage, you gain 5 Ultimate.  This effect can occur once every 10 seconds.",
    icon: "/esoui/art/icons/ability_sorcerer_018.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 40,
    rank: 3,
    subcategoryId: "racial-nord-skills" as const,
    effects: [
      { "metricId": "stamina-maximum", "effectType": "integer", "effectValue": 1500 },
    ] as const,
    status: "partially-supported" as const,
  },
  "stalwart-36064": {
    id: "stalwart-36064" as const,
    esoSkillId: 36064,
    name: "Stalwart",
    baseName: "Stalwart",
    skillLineId: "racial-nord-skills" as const,
    skillType: "passive" as const,
    description:
      "Increases your Max Stamina by |cffffff500|r.\n\nWhen you take damage, you gain |cffffff1|r Ultimate.  This effect can occur once every |cffffff10|r seconds.",
    icon: "/esoui/art/icons/ability_sorcerer_018.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 10,
    rank: 10,
    subcategoryId: "racial-nord-skills" as const,
  },
  "stalwart-guard": {
    id: "stalwart-guard" as const,
    esoSkillId: 63351,
    name: "Stalwart Guard",
    baseName: "Guard",
    skillLineId: "alliance-war-support" as const,
    skillType: "active" as const,
    description:
      "Create a lifebond between you and an allied player. While bonded, 30% of the damage they take is instead redistributed to you.\n\nYou and your bonded ally also gain Minor Force, increasing your Critical Damage by 10%.\n\nThe bond will remain until you recast the spell or move more than 15 meters away from your ally.",
    icon: "/esoui/art/icons/ability_ava_stalwart_guard.dds",
    isMorph: true,
    morphIndex: 2,
    lineRankNeeded: 5,
    rank: 12,
    subcategoryId: "alliance-war-support" as const,
  },
  "stalwart-guard-61529": {
    id: "stalwart-guard-61529" as const,
    esoSkillId: 61529,
    name: "Stalwart Guard",
    baseName: "Guard",
    skillLineId: "alliance-war-support" as const,
    skillType: "active" as const,
    description:
      "Create a lifebond between you and an allied player. While bonded, |cffffff30|r% of the damage they take is instead redistributed to you.\n\nYou and your bonded ally also gain Minor Force, increasing your Critical Damage by |cffffff10|r%.\n\nThe bond will remain until you recast the spell or move more than |cffffff15|r meters away from your ally.",
    icon: "/esoui/art/icons/ability_ava_stalwart_guard.dds",
    isMorph: true,
    morphIndex: 2,
    lineRankNeeded: 5,
    rank: 5,
    subcategoryId: "alliance-war-support" as const,
  },
} satisfies Record<string, SkillTemplate>
