import type { StoryTurnPlayed } from "akasha/story/world/stories/played/turns/story-turn-played.page-type.types.ts"

export const otherwhereIii00024 = {
  id: "01a0eb4b-d223-7504-b197-ab60b4a640e3",
  type: "page-type/story-turn-played",
  slug: "otherwhere-iii-00-024",
  ownLength: 345,
  unit: "unit/words",
  partOfCollections: ["story-played/otherwhere-iii"],
  position: 24,
  prose: "txt",
  characters: [
    "character-player/otherwhere-iii-nala",
    "character-other/super-supportive-gorgon",
    "character-other/otherwhere-iii-onn-desveth",
  ],
  stepStatus: "step-status/recorders",
  action:
    "“That is part of why I believe my Earth cannot be too far distant. In my world your world exists as a story in a book, all the way down to the headlines I saw on the news last night. I know a great deal, but filtered through the lens of a story. So far, all of the details from the story have been accurate, but that doesn’t mean I can speak Artonan, even though the main character of the story could speak Artonan. I also suspect specific events could diverge as my actions have ripple effects, similar to a hypothetical time travel scenario.”",
  beats: [
    "Nala says, \"That's part of why I think my Earth can't be too far off.\"",
    '"In my world, your world exists as a story in a book. Down to the headlines on last night\'s news."',
    '"I know a great deal, but filtered through a story. So far every detail has been accurate."',
    '"That doesn\'t mean I speak Artonan, though the main character of the story could."',
    '"And I suspect events could diverge now. My actions ripple, like in a time-travel story."',
    "Onn-desveth goes very still. For a long moment she does not speak.",
    '"A book," she says quietly. "About us."',
    "She glances once toward the desk, then back. Gorgon's eyes stay on his monitors.",
    '"You must not say this to anyone else. Not in this building. Not outside it."',
    '"If my superiors learn a human holds such a book in her head, it will go badly for you."',
    '"And for me, who heard it first." She folds her long hands.',
    '"So I offer you a contract. Private, sealed properly, by a tattooist, with my name on it."',
    '"You speak of the book, and what it tells, to me alone."',
    '"In return, I report you as I found you. Clean. Unregistered. Nothing more."',
    '"And I tell no one of the book." A pause. "I will also give you a place in our spring classes."',
    '"If you refuse, you are free to walk out that door."',
    '"But then I must report all that you told me."',
    '"I would not have you sign today. Take time. Weigh the terms."',
    '"You may bring someone you trust to hear them read. That is your right."',
    "She takes a card from her sleeve and presses it into Nala's hand.",
  ],
  issues: [
    '"holds it out to you" - beat has her set the card on the counter by the enrollment form',
    '"To no one else." - Plain Negation',
    '"and holds it out to you." - No Prompt',
  ],
  lore: [
    "lore/otherwhere-iii-nala",
    "lore/otherwhere-iii-onn-desveth",
    "lore/super-supportive-contract-tattoo",
    "lore/super-supportive-gorgon",
  ],
  reviewedBy: ["story-reviewer/continuity", "story-reviewer/style"],
  endsAt: "2037-01-31T10:45:00.000Z",
} as const satisfies StoryTurnPlayed
