import type { TemperLoreBook } from "akasha/temper/catalog/pursuit/temper-lore-collection/temper-lore-book/temper-lore-book.page-type.types.ts"

export const heavyArmorForging = {
  id: "01a0d5f6-6d40-7576-b5e2-5a764d818e4f",
  type: "page-type/temper-lore-book",
  slug: "heavy-armor-forging",
  title: "Heavy Armor Forging",
  collection: "temper-lore-collection/skill-books",
  esoBookId: 1125,
  bookIndex: 2,
  charted: true,
  onBookshelves: true,
  mapCounts: [
    { mapId: 1, mapCount: 40 },
    { mapId: 7, mapCount: 48 },
    { mapId: 10, mapCount: 3 },
    { mapId: 13, mapCount: 2 },
    { mapId: 16, mapCount: 6 },
    { mapId: 26, mapCount: 6 },
    { mapId: 27, mapCount: 3 },
    { mapId: 74, mapCount: 15 },
    { mapId: 75, mapCount: 6 },
    { mapId: 143, mapCount: 130 },
    { mapId: 201, mapCount: 23 },
    { mapId: 227, mapCount: 8 },
    { mapId: 255, mapCount: 26 },
    { mapId: 258, mapCount: 8 },
    { mapId: 660, mapCount: 3 },
    { mapId: 667, mapCount: 1 },
    { mapId: 1060, mapCount: 1 },
    { mapId: 1126, mapCount: 10 },
  ],
} as const satisfies TemperLoreBook
