import type { WorkspacePackage } from "@akasha/code/workspace-package"

export const persona = {
  id: "01a0532a-a54c-785e-97fa-4e56cb1bc0d1",
  pageTypeSlug: "workspace-package",
  slug: "persona",
  definition: "who answers for a part of Alan's life, and what is kept of her",
  manifest: "json",
  parts: [
    "domain/persona-points",
    "email-address-property/email-address",
    "page-type/closeness-level",
    "page-type/origin-kind",
    "page-type/persona",
    "page-type/question",
    "page-type/review-session",
    "page-type/persona-anchor-image",
    "page-type/persona-cover-image",
    "page-type/persona-craft-day",
    "page-type/persona-image",
    "page-type/persona-wallpaper",
    "page-type/persona-wallpaper-notification",
    "page-type/persona-points-source",
    "module/persona-reading",
    "module/persona-targets",
    "persona/abby",
    "persona/aelwyn",
    "persona/aine",
    "persona/akasha",
    "persona/ali",
    "persona/amy",
    "persona/aranya",
    "persona/aria",
    "persona/astra",
    "persona/athena",
    "persona/atlas",
    "persona/aura",
    "persona/awen",
    "persona/ceri",
    "persona/claude",
    "persona/dalla",
    "persona/echo",
    "persona/elaine",
    "persona/elin",
    "persona/ember",
    "persona/eppie",
    "persona/erin",
    "persona/grace",
    "persona/ione",
    "persona/iris",
    "persona/lali",
    "persona/mari",
    "persona/natalie",
    "persona/nimue",
    "persona/nova",
    "persona/olwen",
    "persona/rhia",
    "persona/ruby",
    "persona/ryn",
    "persona/selah",
    "persona/shaestrel",
    "persona/sophia",
    "persona/talia",
    "persona/thea",
    "persona/vera",
    "persona/zadi",
    "persona/zeli",
    "text-property/value-slug",
    "module/image-locator",
    "module/anchor-cover-record",
    "module/persona-page-conditions",
    "module/points-source-coherence",
    "module/wallpaper-record",
    "module/image-name",
    "module/voice-spec",
    "module/wallpaper-backfill-execute",
    "module/canonical-image-classify",
    "module/framework",
    "module/git-byte-pathspecs",
    "module/green-day-fraction",
    "module/last-messaged",
    "module/points-source-availability",
    "module/points-source-declarers",
    "module/render-prompt",
    "module/wallpaper-backfill-classify",
    "module/wallpaper-install",
    "module/wallpaper-select",
    "module/wallpaper-order",
    "module/desktop-wallpaper-setting",
    "workstation-service/desktop-wallpaper-setting",
  ],
} as const satisfies WorkspacePackage
