import type { TemperSet } from "akasha/temper/catalog/gear/temper-set/temper-set.page-type.types.ts"

export const ilambris = {
  id: "019e6484-5ffb-7fb2-b363-b681369b1a02",
  type: "page-type/temper-set",
  slug: "ilambris",
  title: "Ilambris",
  key: "ilambris",
  esoSetId: 273,
  hashPlace: 243,
  esoItemIds: [94524, 94660, 94796, 94932, 95068, 95204],
  esoArmorTypes: ["ARMORTYPE_HEAVY", "ARMORTYPE_LIGHT", "ARMORTYPE_MEDIUM"],
  esoEquipTypes: ["EQUIP_TYPE_HEAD", "EQUIP_TYPE_SHOULDERS"],
  setWayshrines: [190, 190, 190],
  setVeteranEquipTypes: ["EQUIP_TYPE_HEAD"],
  setUndauntedChestId: 1,
  setTypeId: 8,
  setNameZh: "伊拉姆布里斯",
  setNameRu: "Иламбрисы",
  setNameFr: "Ilambris",
  setNameEs: "Ilambris",
  setNameDe: "Ilambris",
  setDropZones: [130, 20, 20],
  setDropMechanics: [6],
  setDropLocationNamesEn: ["Ilambris twins (Athor or Zaven)"],
  setDropLocationNamesDe: ["Ilambris Zwillinge (Athor oder Zaven)"],
  setDlcId: 0,
  itemBrowserSources: ["130:-102"],
  itemBrowserPlaceKinds: [3],
  itemBrowserItemId: 94797,
  category: "temper-set-category/monster",
  valid: ["monster"],
  bonuses: "jsonl",
  icons: "jsonl",
} as const satisfies TemperSet
