import type { SkillTemplate } from "../character-skill-template/character-skill-template.module.code.ts"

export const CHARACTER_SKILLS_31 = {
  "harnessed-quintessence": {
    id: "harnessed-quintessence" as const,
    esoSkillId: 184858,
    name: "Harnessed Quintessence",
    baseName: "Harnessed Quintessence",
    skillLineId: "arcanist-herald-of-the-tome" as const,
    skillType: "passive" as const,
    description:
      "You master the warp and weft of your very soul. When you are restored Magicka or Stamina, increase your Weapon and Spell Damage by 284 for 10 seconds.",
    icon: "/esoui/art/icons/passive_arcanist_02.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 14,
    rank: 2,
    subcategoryId: "arcanist-herald-of-the-tome" as const,
    effects: [] as const,
    status: "partially-supported" as const,
  },
  "hasty-prayer": {
    id: "hasty-prayer" as const,
    esoSkillId: 27376,
    name: "Hasty Prayer",
    baseName: "Healing Ritual",
    skillLineId: "templar-restoring-light" as const,
    skillType: "active" as const,
    description:
      "Focus your spiritual devotion, healing you and nearby allies for 2614 Health.\n\nAffected targets gain Minor Expedition, increasing their Movement Speed by 15% for 10 seconds.",
    icon: "/esoui/art/icons/ability_templar_lingering_ritual.dds",
    isMorph: true,
    morphIndex: 2,
    lineRankNeeded: 4,
    rank: 12,
    subcategoryId: "templar-restoring-light" as const,
  },
  "hasty-prayer-22314": {
    id: "hasty-prayer-22314" as const,
    esoSkillId: 22314,
    name: "Hasty Prayer",
    baseName: "Healing Ritual",
    skillLineId: "templar-restoring-light" as const,
    skillType: "active" as const,
    description:
      "Focus your spiritual devotion, healing you and nearby allies for |cffffff8219|r Health.\n\nAffected targets gain Minor Expedition, increasing their Movement Speed by |cffffff15|r% for |cffffff10|r seconds.",
    icon: "/esoui/art/icons/ability_templar_lingering_ritual.dds",
    isMorph: true,
    morphIndex: 2,
    lineRankNeeded: 4,
    rank: 4,
    subcategoryId: "templar-restoring-light" as const,
  },
  "hasty-retreat": {
    id: "hasty-retreat" as const,
    esoSkillId: 45498,
    name: "Hasty Retreat",
    baseName: "Hasty Retreat",
    skillLineId: "weapon-bow" as const,
    skillType: "passive" as const,
    description:
      "Grants you Major Expedition for 4 seconds after you use Roll Dodge.\n\nMajor Expedition increases your Movement Speed by 30%.",
    icon: "/esoui/art/icons/ability_dragonknight_029.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 50,
    rank: 2,
    subcategoryId: "weapon-bow" as const,
    effects: [] as const,
    status: "unsupported" as const,
  },
  "hasty-retreat-30923": {
    id: "hasty-retreat-30923" as const,
    esoSkillId: 30923,
    name: "Hasty Retreat",
    baseName: "Hasty Retreat",
    skillLineId: "weapon-bow" as const,
    skillType: "passive" as const,
    description:
      "Grants you Major Expedition for |cffffff2|r seconds after you use Roll Dodge.\n\nMajor Expedition increases your Movement Speed by |cffffff30|r%.",
    icon: "/esoui/art/icons/ability_dragonknight_029.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 41,
    rank: 41,
    subcategoryId: "weapon-bow" as const,
  },
  "haunting-curse": {
    id: "haunting-curse" as const,
    esoSkillId: 30523,
    name: "Haunting Curse",
    baseName: "Daedric Curse",
    skillLineId: "sorcerer-daedric-summoning" as const,
    skillType: "active" as const,
    description:
      "Curse an enemy with a destructive rune, dealing 2999 Magic Damage to the target and all other nearby enemies after 3.5 seconds.\n\nThe curse will continue to haunt the enemy and explode a second time, dealing 2999 Magic Damage to the target and all other nearby enemies after an additional 8.5 seconds.\n\nYou can have only one Haunting Curse active at a time.",
    icon: "/esoui/art/icons/ability_sorcerer_velocious_curse.dds",
    isMorph: true,
    morphIndex: 2,
    lineRankNeeded: 4,
    rank: 12,
    subcategoryId: "sorcerer-daedric-summoning" as const,
  },
  "haunting-curse-24330": {
    id: "haunting-curse-24330" as const,
    esoSkillId: 24330,
    name: "Haunting Curse",
    baseName: "Daedric Curse",
    skillLineId: "sorcerer-daedric-summoning" as const,
    skillType: "active" as const,
    description:
      "Curse an enemy with a destructive rune, dealing |cffffff11020|r Magic Damage to the target and all other nearby enemies after |cffffff3.5|r seconds.\n\nThe curse will continue to haunt the enemy and explode a second time, dealing |cffffff11020|r Magic Damage to the target and all other nearby enemies after an additional |cffffff8.5|r seconds.\n\nYou can have only one Haunting Curse active at a time.",
    icon: "/esoui/art/icons/ability_sorcerer_velocious_curse.dds",
    isMorph: true,
    morphIndex: 2,
    lineRankNeeded: 4,
    rank: 4,
    subcategoryId: "sorcerer-daedric-summoning" as const,
  },
  "hawk-eye": {
    id: "hawk-eye" as const,
    esoSkillId: 45497,
    name: "Hawk Eye",
    baseName: "Hawk Eye",
    skillLineId: "weapon-bow" as const,
    skillType: "passive" as const,
    description:
      "Dealing damage with a Light or Heavy Attack increases the damage of your Bow abilities by 5% for 5 seconds, stacking up to 5 times.",
    icon: "/esoui/art/icons/passive_armor_002.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 46,
    rank: 2,
    subcategoryId: "weapon-bow" as const,
    effects: [] as const,
    status: "unsupported" as const,
  },
  "hawk-eye-30936": {
    id: "hawk-eye-30936" as const,
    esoSkillId: 30936,
    name: "Hawk Eye",
    baseName: "Hawk Eye",
    skillLineId: "weapon-bow" as const,
    skillType: "passive" as const,
    description:
      "Dealing damage with a Light or Heavy Attack increases the damage of your Bow abilities by |cffffff2|r% for |cffffff5|r seconds, stacking up to |cffffff5|r times.",
    icon: "/esoui/art/icons/passive_armor_002.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 30,
    rank: 30,
    subcategoryId: "weapon-bow" as const,
  },
  "healing-ritual": {
    id: "healing-ritual" as const,
    esoSkillId: 22304,
    name: "Healing Ritual",
    baseName: "Healing Ritual",
    skillLineId: "templar-restoring-light" as const,
    skillType: "active" as const,
    description:
      "Focus your spiritual devotion, healing you and nearby allies for |cffffff8220|r Health.",
    icon: "/esoui/art/icons/ability_templar_healing_ritual.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 4,
    rank: 4,
    subcategoryId: "templar-restoring-light" as const,
  },
  "healing-seed": {
    id: "healing-seed" as const,
    esoSkillId: 85578,
    name: "Healing Seed",
    baseName: "Healing Seed",
    skillLineId: "warden-green-balance" as const,
    skillType: "active" as const,
    description:
      "Summon a field of flowers which blooms after |cffffff6|r seconds, healing you and allies in the area for |cffffff10960|r Health.\n\nAn ally within the field can activate the Harvest synergy, healing for |cffffff10602|r Health over |cffffff5|r seconds.",
    icon: "/esoui/art/icons/ability_warden_007.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 4,
    rank: 4,
    subcategoryId: "warden-green-balance" as const,
  },
  "healing-springs": {
    id: "healing-springs" as const,
    esoSkillId: 41265,
    name: "Healing Springs",
    baseName: "Grand Healing",
    skillLineId: "weapon-restoration-staff" as const,
    skillType: "active" as const,
    description:
      "Summon restoring spirits with your staff, healing you and your allies in the target area for 4642 Health over 10 seconds. \n\nIncreases your Magicka Recovery by 15 for each target affected, stacking up to 20 times.",
    icon: "/esoui/art/icons/ability_restorationstaff_004a.dds",
    isMorph: true,
    morphIndex: 2,
    lineRankNeeded: 2,
    rank: 12,
    subcategoryId: "weapon-restoration-staff" as const,
  },
  "healing-springs-40060": {
    id: "healing-springs-40060" as const,
    esoSkillId: 40060,
    name: "Healing Springs",
    baseName: "Grand Healing",
    skillLineId: "weapon-restoration-staff" as const,
    skillType: "active" as const,
    description:
      "Summon restoring spirits with your staff, healing you and your allies in the target area for |cffffff14608|r Health over |cffffff10|r seconds. \n\nIncreases your Magicka Recovery by |cffffff15|r for each target affected, stacking up to |cffffff20|r times.",
    icon: "/esoui/art/icons/ability_restorationstaff_004a.dds",
    isMorph: true,
    morphIndex: 2,
    lineRankNeeded: 2,
    rank: 2,
    subcategoryId: "weapon-restoration-staff" as const,
  },
  "healing-thicket": {
    id: "healing-thicket" as const,
    esoSkillId: 93974,
    name: "Healing Thicket",
    baseName: "Secluded Grove",
    skillLineId: "warden-green-balance" as const,
    skillType: "ultimate" as const,
    description:
      "Swell a healing forest at the target location, instantly healing the most injured friendly target for 2880 Health. The forest continues to heal you and your allies in the area for 958 every 1 second for 6 seconds.\n\nThe healing over time will continue to heal you or your allies for 4 seconds after leaving the forest.",
    icon: "/esoui/art/icons/ability_warden_012_b.dds",
    isMorph: true,
    morphIndex: 2,
    lineRankNeeded: 12,
    rank: 12,
    subcategoryId: "warden-green-balance" as const,
  },
  "healing-thicket-85807": {
    id: "healing-thicket-85807" as const,
    esoSkillId: 85807,
    name: "Healing Thicket",
    baseName: "Secluded Grove",
    skillLineId: "warden-green-balance" as const,
    skillType: "ultimate" as const,
    description:
      "Swell a healing forest at the target location, instantly healing the most injured friendly target for |cffffff9057|r Health. The forest continues to heal you and your allies in the area for |cffffff3017|r every |cffffff1|r second for |cffffff6|r seconds.\n\nThe healing over time will continue to heal you or your allies for |cffffff4|r seconds after leaving the forest.",
    icon: "/esoui/art/icons/ability_warden_012_b.dds",
    isMorph: true,
    morphIndex: 2,
    lineRankNeeded: 12,
    rank: 12,
    subcategoryId: "warden-green-balance" as const,
  },
  "healing-tides": {
    id: "healing-tides" as const,
    esoSkillId: 185186,
    name: "Healing Tides",
    baseName: "Healing Tides",
    skillLineId: "arcanist-curative-runeforms" as const,
    skillType: "passive" as const,
    description:
      "Your mastery of weaving fate and abyssal water increases your healing done by 4% for each active Crux.",
    icon: "/esoui/art/icons/passive_arcanist_09.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 18,
    rank: 2,
    subcategoryId: "arcanist-curative-runeforms" as const,
    status: "unsupported" as const,
  },
  "healing-tides-185185": {
    id: "healing-tides-185185" as const,
    esoSkillId: 185185,
    name: "Healing Tides",
    baseName: "Healing Tides",
    skillLineId: "arcanist-curative-runeforms" as const,
    skillType: "passive" as const,
    description:
      "Your mastery of weaving fate and abyssal water increases your healing done by |cffffff2|r% for each active Crux.",
    icon: "/esoui/art/icons/passive_arcanist_09.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 8,
    rank: 8,
    subcategoryId: "arcanist-curative-runeforms" as const,
  },
  "healing-ward": {
    id: "healing-ward" as const,
    esoSkillId: 41320,
    name: "Healing Ward",
    baseName: "Steadfast Ward",
    skillLineId: "weapon-restoration-staff" as const,
    skillType: "active" as const,
    description:
      "Call on your staff's strength to protect you or the lowest health ally around you with a damage shield that absorbs 2399 damage.\n\nThe shield's strength is increased by up to 100%, depending on the severity of the target's wounds. \n\nWhile the shield persists, the target is healed for 33% of the shield's remaining strength every second.",
    icon: "/esoui/art/icons/ability_restorationstaff_001_a.dds",
    isMorph: true,
    morphIndex: 2,
    lineRankNeeded: 20,
    rank: 12,
    subcategoryId: "weapon-restoration-staff" as const,
  },
  "healing-ward-40126": {
    id: "healing-ward-40126" as const,
    esoSkillId: 40126,
    name: "Healing Ward",
    baseName: "Steadfast Ward",
    skillLineId: "weapon-restoration-staff" as const,
    skillType: "active" as const,
    description:
      "Call on your staff's strength to protect you or the lowest health ally around you with a damage shield that absorbs |cffffff8508|r damage.\n\nThe shield's strength is increased by up to |cffffff100|r%, depending on the severity of the target's wounds. \n\nWhile the shield persists, the target is healed for |cffffff34|r% of the shield's remaining strength every second.",
    icon: "/esoui/art/icons/ability_restorationstaff_001_a.dds",
    isMorph: true,
    morphIndex: 2,
    lineRankNeeded: 20,
    rank: 20,
    subcategoryId: "weapon-restoration-staff" as const,
  },
  "health-avarice": {
    id: "health-avarice" as const,
    esoSkillId: 116270,
    name: "Health Avarice",
    baseName: "Health Avarice",
    skillLineId: "necromancer-bone-tyrant" as const,
    skillType: "passive" as const,
    description:
      "Increase your Healing Received by 3% for each Bone Tyrant ability slotted.\n\nCurrent bonus: 0%.",
    icon: "/esoui/art/icons/passive_necromancer_007.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 36,
    rank: 2,
    subcategoryId: "necromancer-bone-tyrant" as const,
    effects: [
      {
        "metricId": "healing-received-base",
        "effectType": "slotted-ability-scaling",
        "skillLineId": "necromancer-bone-tyrant",
        "valuePerAbility": 3,
      },
    ] as const,
    status: "supported" as const,
  },
} satisfies Record<string, SkillTemplate>
