export const MORPHABLE_SKILLS_DETAIL_PER_LINE_04: Record<
  number,
  ReadonlyArray<{
    baseName: string
    morph1Name: string
    morph2Name: string
    skillType: "active" | "ultimate"
    lineRankNeeded: number
  }>
> = {
  [317]: [
    {
      baseName: "Vengeance Abyssal Impact",
      morph1Name: "",
      morph2Name: "",
      skillType: "active",
      lineRankNeeded: 0,
    },
    {
      baseName: "Vengeance-Bearer's Inspiration",
      morph1Name: "",
      morph2Name: "",
      skillType: "active",
      lineRankNeeded: 0,
    },
    {
      baseName: "Vengeance Fatecarver",
      morph1Name: "",
      morph2Name: "",
      skillType: "active",
      lineRankNeeded: 0,
    },
    {
      baseName: "Vengeance Runeblades",
      morph1Name: "",
      morph2Name: "",
      skillType: "active",
      lineRankNeeded: 0,
    },
    {
      baseName: "Vengeance The Imperfect Ring",
      morph1Name: "",
      morph2Name: "",
      skillType: "active",
      lineRankNeeded: 0,
    },
    {
      baseName: "Vengeance The Unblinking Eye",
      morph1Name: "",
      morph2Name: "",
      skillType: "ultimate",
      lineRankNeeded: 0,
    },
  ],
  [319]: [
    {
      baseName: "Vengeance Berserker Strike",
      morph1Name: "",
      morph2Name: "",
      skillType: "ultimate",
      lineRankNeeded: 0,
    },
    {
      baseName: "Vengeance Cleave",
      morph1Name: "",
      morph2Name: "",
      skillType: "active",
      lineRankNeeded: 0,
    },
    {
      baseName: "Vengeance Critical Charge",
      morph1Name: "",
      morph2Name: "",
      skillType: "active",
      lineRankNeeded: 0,
    },
    {
      baseName: "Vengeance Momentum",
      morph1Name: "",
      morph2Name: "",
      skillType: "active",
      lineRankNeeded: 0,
    },
    {
      baseName: "Vengeance Reverse Slash",
      morph1Name: "",
      morph2Name: "",
      skillType: "active",
      lineRankNeeded: 0,
    },
    {
      baseName: "Vengeance Uppercut",
      morph1Name: "",
      morph2Name: "",
      skillType: "active",
      lineRankNeeded: 0,
    },
  ],
  [320]: [
    {
      baseName: "Vengeance Defensive Posture",
      morph1Name: "",
      morph2Name: "",
      skillType: "active",
      lineRankNeeded: 0,
    },
    {
      baseName: "Vengeance Low Slash",
      morph1Name: "",
      morph2Name: "",
      skillType: "active",
      lineRankNeeded: 0,
    },
    {
      baseName: "Vengeance Power Bash",
      morph1Name: "",
      morph2Name: "",
      skillType: "active",
      lineRankNeeded: 0,
    },
    {
      baseName: "Vengeance Puncture",
      morph1Name: "",
      morph2Name: "",
      skillType: "active",
      lineRankNeeded: 0,
    },
    {
      baseName: "Vengeance Shield Charge",
      morph1Name: "",
      morph2Name: "",
      skillType: "active",
      lineRankNeeded: 0,
    },
    {
      baseName: "Vengeance Shield Wall",
      morph1Name: "",
      morph2Name: "",
      skillType: "ultimate",
      lineRankNeeded: 0,
    },
  ],
  [321]: [
    {
      baseName: "Vengeance Blade Cloak",
      morph1Name: "",
      morph2Name: "",
      skillType: "active",
      lineRankNeeded: 0,
    },
    {
      baseName: "Vengeance Flurry",
      morph1Name: "",
      morph2Name: "",
      skillType: "active",
      lineRankNeeded: 0,
    },
    {
      baseName: "Vengeance Hidden Blade",
      morph1Name: "",
      morph2Name: "",
      skillType: "active",
      lineRankNeeded: 0,
    },
    {
      baseName: "Vengeance Lacerate",
      morph1Name: "",
      morph2Name: "",
      skillType: "ultimate",
      lineRankNeeded: 0,
    },
    {
      baseName: "Vengeance Twin Slashes",
      morph1Name: "",
      morph2Name: "",
      skillType: "active",
      lineRankNeeded: 0,
    },
    {
      baseName: "Vengeance Whirlwind",
      morph1Name: "",
      morph2Name: "",
      skillType: "active",
      lineRankNeeded: 0,
    },
  ],
  [322]: [
    {
      baseName: "Vengeance Arrow Spray",
      morph1Name: "",
      morph2Name: "",
      skillType: "active",
      lineRankNeeded: 0,
    },
    {
      baseName: "Vengeance Poison Arrow",
      morph1Name: "",
      morph2Name: "",
      skillType: "active",
      lineRankNeeded: 0,
    },
    {
      baseName: "Vengeance Rapid Fire",
      morph1Name: "",
      morph2Name: "",
      skillType: "ultimate",
      lineRankNeeded: 0,
    },
    {
      baseName: "Vengeance Scatter Shot",
      morph1Name: "",
      morph2Name: "",
      skillType: "active",
      lineRankNeeded: 0,
    },
    {
      baseName: "Vengeance Snipe",
      morph1Name: "",
      morph2Name: "",
      skillType: "active",
      lineRankNeeded: 0,
    },
    {
      baseName: "Vengeance Volley",
      morph1Name: "",
      morph2Name: "",
      skillType: "active",
      lineRankNeeded: 0,
    },
  ],
  [323]: [
    {
      baseName: "Vengeance Destructive Touch",
      morph1Name: "",
      morph2Name: "",
      skillType: "active",
      lineRankNeeded: 0,
    },
    {
      baseName: "Vengeance Elemental Storm",
      morph1Name: "",
      morph2Name: "",
      skillType: "ultimate",
      lineRankNeeded: 0,
    },
    {
      baseName: "Vengeance Force Shock",
      morph1Name: "",
      morph2Name: "",
      skillType: "active",
      lineRankNeeded: 0,
    },
    {
      baseName: "Vengeance Impulse",
      morph1Name: "",
      morph2Name: "",
      skillType: "active",
      lineRankNeeded: 0,
    },
    {
      baseName: "Vengeance Wall of Elements",
      morph1Name: "",
      morph2Name: "",
      skillType: "active",
      lineRankNeeded: 0,
    },
    {
      baseName: "Vengeance Weakness to Elements",
      morph1Name: "",
      morph2Name: "",
      skillType: "active",
      lineRankNeeded: 0,
    },
  ],
  [324]: [
    {
      baseName: "Vengeance Blessing of Protection",
      morph1Name: "",
      morph2Name: "",
      skillType: "active",
      lineRankNeeded: 0,
    },
    {
      baseName: "Vengeance Force Siphon",
      morph1Name: "",
      morph2Name: "",
      skillType: "active",
      lineRankNeeded: 0,
    },
    {
      baseName: "Vengeance Grand Healing",
      morph1Name: "",
      morph2Name: "",
      skillType: "active",
      lineRankNeeded: 0,
    },
    {
      baseName: "Vengeance Panacea",
      morph1Name: "",
      morph2Name: "",
      skillType: "ultimate",
      lineRankNeeded: 0,
    },
    {
      baseName: "Vengeance Regeneration",
      morph1Name: "",
      morph2Name: "",
      skillType: "active",
      lineRankNeeded: 0,
    },
    {
      baseName: "Vengeance Steadfast Ward",
      morph1Name: "",
      morph2Name: "",
      skillType: "active",
      lineRankNeeded: 0,
    },
  ],
  [325]: [
    {
      baseName: "Vengeance Caltrops",
      morph1Name: "",
      morph2Name: "",
      skillType: "active",
      lineRankNeeded: 0,
    },
    {
      baseName: "Vengeance Magicka Detonation",
      morph1Name: "",
      morph2Name: "",
      skillType: "active",
      lineRankNeeded: 0,
    },
    {
      baseName: "Vengeance Rapid Maneuver",
      morph1Name: "",
      morph2Name: "",
      skillType: "active",
      lineRankNeeded: 0,
    },
    {
      baseName: "Vengeance Vigor",
      morph1Name: "",
      morph2Name: "",
      skillType: "active",
      lineRankNeeded: 0,
    },
    {
      baseName: "Vengeance War Horn",
      morph1Name: "",
      morph2Name: "",
      skillType: "ultimate",
      lineRankNeeded: 0,
    },
  ],
  [326]: [
    {
      baseName: "Vengeance Barrier",
      morph1Name: "",
      morph2Name: "",
      skillType: "ultimate",
      lineRankNeeded: 0,
    },
    {
      baseName: "Vengeance Guard",
      morph1Name: "",
      morph2Name: "",
      skillType: "active",
      lineRankNeeded: 0,
    },
    {
      baseName: "Vengeance Purge",
      morph1Name: "",
      morph2Name: "",
      skillType: "active",
      lineRankNeeded: 0,
    },
    {
      baseName: "Vengeance Revealing Flare",
      morph1Name: "",
      morph2Name: "",
      skillType: "active",
      lineRankNeeded: 0,
    },
    {
      baseName: "Vengeance Siege Shield",
      morph1Name: "",
      morph2Name: "",
      skillType: "active",
      lineRankNeeded: 0,
    },
  ],
  [330]: [
    {
      baseName: "Vengeance Circle of Protection",
      morph1Name: "",
      morph2Name: "",
      skillType: "active",
      lineRankNeeded: 0,
    },
    {
      baseName: "Vengeance Dawnbreaker",
      morph1Name: "",
      morph2Name: "",
      skillType: "ultimate",
      lineRankNeeded: 0,
    },
    {
      baseName: "Vengeance Expert Hunter",
      morph1Name: "",
      morph2Name: "",
      skillType: "active",
      lineRankNeeded: 0,
    },
    {
      baseName: "Vengeance Silver Bolts",
      morph1Name: "",
      morph2Name: "",
      skillType: "active",
      lineRankNeeded: 0,
    },
    {
      baseName: "Vengeance Trap Beast",
      morph1Name: "",
      morph2Name: "",
      skillType: "active",
      lineRankNeeded: 0,
    },
  ],
  [331]: [
    {
      baseName: "Vengeance Entropy",
      morph1Name: "",
      morph2Name: "",
      skillType: "active",
      lineRankNeeded: 0,
    },
    {
      baseName: "Vengeance Equilibrium",
      morph1Name: "",
      morph2Name: "",
      skillType: "active",
      lineRankNeeded: 0,
    },
    {
      baseName: "Vengeance Fire Rune",
      morph1Name: "",
      morph2Name: "",
      skillType: "active",
      lineRankNeeded: 0,
    },
    {
      baseName: "Vengeance Magelight",
      morph1Name: "",
      morph2Name: "",
      skillType: "active",
      lineRankNeeded: 0,
    },
    {
      baseName: "Vengeance Meteor",
      morph1Name: "",
      morph2Name: "",
      skillType: "ultimate",
      lineRankNeeded: 0,
    },
  ],
  [332]: [
    {
      baseName: "Vengeance Annulment",
      morph1Name: "",
      morph2Name: "",
      skillType: "active",
      lineRankNeeded: 0,
    },
    {
      baseName: "Vengeance Evasion",
      morph1Name: "",
      morph2Name: "",
      skillType: "active",
      lineRankNeeded: 0,
    },
    {
      baseName: "Vengeance Unstoppable",
      morph1Name: "",
      morph2Name: "",
      skillType: "active",
      lineRankNeeded: 0,
    },
  ],
}
