apiVersion: v1
kind: Secret
metadata:
    name: tailnet-egress-auth
    namespace: tailnet-egress
    labels:
        app.kubernetes.io/name: tailnet-egress
        app.kubernetes.io/instance: tailnet-egress
        app.kubernetes.io/component: data-plane
        app.kubernetes.io/part-of: headscale
        app.kubernetes.io/managed-by: deploy-script
type: Opaque
stringData:
    TS_AUTHKEY: ENC[AES256_GCM,data:fDv4v4AZR0F4Rupv+9RYgV0j82a0Z1y/NOgyBTDxDwGmtE5561XNyoVWHTsxAal3APz1E8CdvI6DCmH7sUTyCKv4FxKaH4MIojiFmLlZLwK3YBvn4lCt0Q==,iv:957pb3joJT4fomItyZM/8JERTtWndQNuzF5kCUtvols=,tag:YdW4eCmzDwuOzi+XlhjD+Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyd2dpeG44cGpZR0I2UGs4
            OHdLT3FQcFJIYlFiS0hzU05SalNpSzBONTNJCldhSTllUVFIN3VXRXByTm9oS2JL
            bXBjU1hqRkNTMms1aUZKaytSZGtETGMKLS0tIFNPZkp5K0pKTTBueklINWF5Y1Yw
            RDdsd0FEMTZOeTNuc2p6b3F0N0tkekkKvWzFJMJBsGtnq6r/lasW6a9MXWlCLZ0b
            MOu8YabZKsHctrluPnbmsx1DBHC8xrr3+jM822VdRVXRvi8lfa8Q1A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-05T13:34:27Z"
    mac: ENC[AES256_GCM,data:2Bi06PmNPMDYsuBrcTaUOI0nBiL8CVy7hEZUSGz5oU1D9gVI2t8vdHdsJIUCBJvjhrIUCLSxV1nonb4ChkEo8QSfi3IYdyOhMvYhpJn95sqRlDpY745wQQuaLhi8Y1NSBQBVeiYLGhZ764O8WbN0N5uSEbFOIyudQkHJDMFrVz8=,iv:OLVMQ1nD5s7dlBimRof31fjTU0WgG/CBJk7Cs87eI8U=,tag:ybWShnzoBiAbk1xYzraZbw==,type:str]
    version: 3.13.1
