import type { TemperSet } from "akasha/temper/catalog/gear/temper-set/temper-set.page-type.types.ts"

export const relicsOfTheRebellion = {
  id: "019e6484-604e-7838-8260-35237a7a3374",
  type: "page-type/temper-set",
  slug: "relics-of-the-rebellion",
  title: "Relics of the Rebellion",
  key: "relics-of-the-rebellion",
  esoSetId: 119,
  hashPlace: 472,
  esoItemIds: [55367, 55371, 55372],
  esoEquipTypes: ["EQUIP_TYPE_NECK", "EQUIP_TYPE_OFF_HAND", "EQUIP_TYPE_ONE_HAND"],
  esoWeaponTypes: ["WEAPONTYPE_HAMMER", "WEAPONTYPE_SHIELD"],
  setWayshrines: [194, 194, 194],
  setTypeId: 6,
  setNameZh: "反叛圣遗物",
  setNameRu: "Реликвии восстания",
  setNameFr: "Les Reliques de la rébellion",
  setNameEs: "Reliquias de la rebelión",
  setNameDe: "Relikte der Rebellion",
  setDropZones: [381, 146, 126, 63, 283],
  setDropMechanics: [28, 28, 28, 28, 28],
  setDlcId: 0,
  category: "temper-set-category/other",
  valid: ["mace", "shield", "necklace"],
  bonuses: "jsonl",
  icons: "jsonl",
} as const satisfies TemperSet
