import type { TemperSet } from "akasha/temper/catalog/gear/temper-set/temper-set.page-type.types.ts"

export const hideOfTheWerewolf = {
  id: "019e66e7-6a68-7d59-a4bb-0216587b23f3",
  type: "page-type/temper-set",
  slug: "hide-of-the-werewolf",
  title: "Hide of the Werewolf",
  key: "hide-of-the-werewolf",
  esoSetId: 58,
  hashPlace: 230,
  esoItemIds: [
    86006, 86007, 86008, 86009, 86010, 86011, 86012, 86013, 86014, 86015, 86016, 86017, 86018,
    86019, 86020, 86021, 86022, 86023, 86024, 86025, 86026, 86027,
  ],
  esoArmorTypes: ["ARMORTYPE_MEDIUM"],
  esoEquipTypes: [
    "EQUIP_TYPE_CHEST",
    "EQUIP_TYPE_FEET",
    "EQUIP_TYPE_HAND",
    "EQUIP_TYPE_HEAD",
    "EQUIP_TYPE_LEGS",
    "EQUIP_TYPE_NECK",
    "EQUIP_TYPE_OFF_HAND",
    "EQUIP_TYPE_ONE_HAND",
    "EQUIP_TYPE_RING",
    "EQUIP_TYPE_SHOULDERS",
    "EQUIP_TYPE_TWO_HAND",
    "EQUIP_TYPE_WAIST",
  ],
  esoWeaponTypes: [
    "WEAPONTYPE_AXE",
    "WEAPONTYPE_BOW",
    "WEAPONTYPE_DAGGER",
    "WEAPONTYPE_FIRE_STAFF",
    "WEAPONTYPE_FROST_STAFF",
    "WEAPONTYPE_HAMMER",
    "WEAPONTYPE_HEALING_STAFF",
    "WEAPONTYPE_LIGHTNING_STAFF",
    "WEAPONTYPE_SHIELD",
    "WEAPONTYPE_SWORD",
    "WEAPONTYPE_TWO_HANDED_AXE",
    "WEAPONTYPE_TWO_HANDED_HAMMER",
    "WEAPONTYPE_TWO_HANDED_SWORD",
  ],
  setWayshrines: [62, 62, 62],
  setTypeId: 9,
  setNameZh: "狼人之皮",
  setNameRu: "Шкура вервольфа",
  setNameFr: "La Peau de loup-garou",
  setNameEs: "Piel del hombre lobo",
  setNameDe: "Fell des Werwolfs",
  setDropZones: [3, 3, 284, 3, 3],
  setDropMechanics: [7, 8, 9, 10, 25],
  setDlcId: 0,
  itemBrowserSources: ["3"],
  itemBrowserPlaceKinds: [1],
  itemBrowserItemId: 86041,
  category: "temper-set-category/overland",
  valid: ["*:medium"],
  bonuses: "jsonl",
  icons: "jsonl",
} as const satisfies TemperSet
