import type { TemperSet } from "akasha/temper/catalog/gear/temper-set/temper-set.page-type.types.ts"

export const hatchlingsShell = {
  id: "019e66e7-6a65-738c-9f4e-d94461f7fc4b",
  type: "page-type/temper-set",
  slug: "hatchlings-shell",
  title: "Hatchling's Shell",
  key: "hatchlings-shell",
  esoSetId: 62,
  hashPlace: 218,
  esoItemIds: [
    99064, 99065, 99066, 99067, 99068, 99069, 99070, 99071, 99072, 99073, 99074, 99075, 99076,
    99077, 99078, 99079, 99080, 99081, 99082, 99083, 99084, 99085,
  ],
  esoArmorTypes: ["ARMORTYPE_HEAVY"],
  esoEquipTypes: [
    "EQUIP_TYPE_CHEST",
    "EQUIP_TYPE_FEET",
    "EQUIP_TYPE_HAND",
    "EQUIP_TYPE_HEAD",
    "EQUIP_TYPE_LEGS",
    "EQUIP_TYPE_NECK",
    "EQUIP_TYPE_OFF_HAND",
    "EQUIP_TYPE_ONE_HAND",
    "EQUIP_TYPE_RING",
    "EQUIP_TYPE_SHOULDERS",
    "EQUIP_TYPE_TWO_HAND",
    "EQUIP_TYPE_WAIST",
  ],
  esoWeaponTypes: [
    "WEAPONTYPE_AXE",
    "WEAPONTYPE_BOW",
    "WEAPONTYPE_DAGGER",
    "WEAPONTYPE_FIRE_STAFF",
    "WEAPONTYPE_FROST_STAFF",
    "WEAPONTYPE_HAMMER",
    "WEAPONTYPE_HEALING_STAFF",
    "WEAPONTYPE_LIGHTNING_STAFF",
    "WEAPONTYPE_SHIELD",
    "WEAPONTYPE_SWORD",
    "WEAPONTYPE_TWO_HANDED_AXE",
    "WEAPONTYPE_TWO_HANDED_HAMMER",
    "WEAPONTYPE_TWO_HANDED_SWORD",
  ],
  setWayshrines: [48, 48, 48],
  setTypeId: 9,
  setNameZh: "幼体之壳",
  setNameRu: "Скорлупа детеныша",
  setNameFr: "Coquille du rejeton",
  setNameEs: "Cascarón del retoño",
  setNameDe: "Schlüpflingspanzer",
  setDropZones: [117, 117, 134, 117, 117],
  setDropMechanics: [7, 8, 9, 10, 25],
  setDlcId: 0,
  itemBrowserSources: ["117"],
  itemBrowserItemId: 99099,
  category: "temper-set-category/overland",
  valid: ["*:heavy"],
  bonuses: "jsonl",
  icons: "jsonl",
} as const satisfies TemperSet
