import type { TemperSet } from "akasha/temper/catalog/gear/temper-set/temper-set.page-type.types.ts"

export const infallibleMage = {
  id: "019e66ec-7b57-7669-9c39-ee235c827c35",
  type: "page-type/temper-set",
  slug: "infallible-mage",
  title: "Infallible Mage",
  key: "infallible-mage",
  esoSetId: 172,
  hashPlace: 249,
  esoItemIds: [
    59752, 59753, 59754, 59756, 59757, 59758, 59759, 80238, 80239, 80240, 80241, 80242, 80243,
    80244, 80245, 80246, 80247, 80248, 80249, 80250, 81166, 81174,
  ],
  esoArmorTypes: ["ARMORTYPE_LIGHT"],
  esoEquipTypes: [
    "EQUIP_TYPE_CHEST",
    "EQUIP_TYPE_FEET",
    "EQUIP_TYPE_HAND",
    "EQUIP_TYPE_HEAD",
    "EQUIP_TYPE_LEGS",
    "EQUIP_TYPE_NECK",
    "EQUIP_TYPE_OFF_HAND",
    "EQUIP_TYPE_ONE_HAND",
    "EQUIP_TYPE_RING",
    "EQUIP_TYPE_SHOULDERS",
    "EQUIP_TYPE_TWO_HAND",
    "EQUIP_TYPE_WAIST",
  ],
  esoWeaponTypes: [
    "WEAPONTYPE_AXE",
    "WEAPONTYPE_BOW",
    "WEAPONTYPE_DAGGER",
    "WEAPONTYPE_FIRE_STAFF",
    "WEAPONTYPE_FROST_STAFF",
    "WEAPONTYPE_HAMMER",
    "WEAPONTYPE_HEALING_STAFF",
    "WEAPONTYPE_LIGHTNING_STAFF",
    "WEAPONTYPE_SHIELD",
    "WEAPONTYPE_SWORD",
    "WEAPONTYPE_TWO_HANDED_AXE",
    "WEAPONTYPE_TWO_HANDED_HAMMER",
    "WEAPONTYPE_TWO_HANDED_SWORD",
  ],
  setWayshrines: [230, 230, 230],
  setTypeId: 11,
  setNameZh: "无懈可击法师",
  setNameRu: "Безупречный маг",
  setNameFr: "L’Infaillible Mage",
  setNameEs: "Mago infalible",
  setNameDe: "Unfehlbare Magierin",
  setDropZones: [638, 638, 638],
  setDropMechanics: [26, 26, 26],
  setDropLocationNamesEn: ["Varlariel: Head, chest, shoulders / Two Atronachs: Hands, Waist, Feet"],
  setDropLocationNamesDe: ["Valariel: Kopf. Brust, Schultern / 2 Atronachen: Hände, Hüfte, Füße"],
  setDlcId: 0,
  itemBrowserSubname: "Infallible Aether",
  itemBrowserSources: ["638"],
  itemBrowserPlaceKinds: [4],
  itemBrowserItemId: 80272,
  category: "temper-set-category/trial",
  valid: ["*:light"],
  bonuses: "jsonl",
  icons: "jsonl",
} as const satisfies TemperSet
