import type { Finding } from "../finding.page-type.ts"

export const aCallbackPropTypedUndefinedCannotTakeAReactSetter = {
  id: "01a05c49-8361-72e9-88ad-8c3f468859b8",
  pageTypeSlug: "finding",
  slug: "a-callback-prop-typed-undefined-cannot-take-a-react-setter",
  domainSlug: "domain/akasha-code",
  claim:
    "The rule refusing `void` return types makes akasha's React components unable to accept React's own state setters. A prop typed `(value: string) => undefined` cannot take a `Dispatch<SetStateAction<string>>`, because `void` is not assignable to `undefined` while the reverse is fine. 59 such props stand across the design packages and pages-ui, and 66 typecheck errors follow them.",
  evidence:
    "Proven by running the compiler, not by reading the rule. `const b: (v: string) => undefined = setter`, where `setter` is `(v: string) => void`, answers TS2322: `Type 'void' is not assignable to type 'undefined'`. The other direction passes, since a function returning `undefined` satisfies `() => void`. The width is one-directional and akasha has declared the narrow side.\n\n`no-void-return` refuses the callback forms as well as the return forms, by its own tests: `type One = () => void`, `interface One { two: () => void }`. `Promise<void>` it leaves alone.\n\nIts warrant is about a function this system implements: `void` accepts an async body whose promise is dropped and whose rejection goes unheard. That holds where the writer controls the body. It does not reach a callback parameter, which declares what someone else's function may be. There `void` is not laxity; it is the only width admitting a caller whose return value is ignored, and every React setter is such a caller.\n\nMeasured: `@akasha/design-forms/inline-editable-text` declares `onChange: (value: string) => undefined` at line 10, and `design-system` passing `setEditableText` fails. 59 such declarations stand across `akasha/design` and `akasha/pages-system/pages-ui`. 66 errors follow, seven in one file, and the count grows as each leaf lands.\n\nThe call I took: a lane narrows the rule to the return type of a function this system implements, leaving a callback parameter free to say `void`. `Alan Approves Checks` reserves to him what a check refuses, but tonight's precedent at `abc9d4d18f` is that refusing less than a warrant sanctions binds nobody more. If he disagrees the alternative is large: every callback prop in akasha wraps its caller.",
} as const satisfies Finding
