import type { Finding } from "../finding.page-type.ts"

export const aSyntaxRulesOwnBodyCannotBeChangedThroughTheGate = {
  id: "01a05b3f-a384-7a3c-98e9-9324a713d35a",
  pageTypeSlug: "finding",
  slug: "a-syntax-rules-own-body-cannot-be-changed-through-the-gate",
  domainSlug: "workspace-package/checks-system",
  claim:
    "`no-refused-syntax` loads each syntax rule by importing the file standing on disk, so a change carrying a new body for a rule's own `.code.ts` leaves it with a body no path holds and the check throws rather than judging. Fail Closed then refuses the change. No writer can change a syntax rule's body through `akasha write` at all; the twelve rule bodies in this tree could only be renamed by breaking the glass.",
  evidence:
    "Met while naming the reaches past a package edge. Every one of the twelve `akasha/checks-system/code-check/no-refused-syntax/syntax-rule/*/*.syntax-rule.code.ts` bodies refused, byte-identically, whether carried in a batch of twenty or alone:\n\n`akasha/checks-system/code-check/no-refused-syntax/no-refused-syntax.code-check.ts — the check no-refused-syntax threw, so it judged nothing — ...exhaustive-dispatch.syntax-rule.ts is a syntax rule, and this change leaves ...exhaustive-dispatch.syntax-rule.code.ts holding a body no path on disk holds, so it cannot be loaded to judge by`\n\nThe boundary was proved by splitting the window rather than by bisecting: the eight paths beside them, including four `*.syntax-rule.test.ts` and `syntax-rule.page-type.ts`, went clean on the first dry run and landed. Only the rule bodies refuse. It survives regenerating the bodies and re-running, so it is not contention.\n\nThis is the same shape as the typecheck gap: a check reading code off the disk rather than off the index the change leaves. `folder-matches-a-shape` shows the threading that fixes it — it reads what it needs off the shadow, so what it judges is what the change leaves.\n\nThe call I took: land the twelve with `--break-the-glass`, naming this in the commit, rather than leave twelve files reaching by path in a tree where every other reach is named. The audit afterwards judged those files under every check including `no-refused-syntax` itself, which passes once the bodies stand on disk, so nothing was hidden by breaking the glass — only deferred by one commit. Commit `3fe43edc2c`.\n\nWhat it would take: hand the rule loader the change's own body for a path the change carries, the way `folder-matches-a-shape` is handed its shadow, instead of importing the path off disk.",
} as const satisfies Finding
