import type { Finding } from "../finding.page-type.ts"

export const anUnknownKeyIsAnsweredRatherThanRefused = {
  id: "01a05def-c361-7000-b0ea-1b0b4e6bb77e",
  pageTypeSlug: "finding",
  slug: "an-unknown-key-is-answered-rather-than-refused",
  domainSlug: "workspace-package/pages-system-service",
  claim:
    "`asking` judges the names of the tests a `where` states and never the key they are stated against. A key no page carries reads as bare, so a `where` on it answers no rows, a `sortBy` on it leaves the rows in no order, and a `keys` entry naming it is left out of every row. All three read as an answer rather than as a refusal, and no row answered is the one that reads most like a true result.",
  evidence:
    "Read at `akasha/pages-system/pages-system-service/page-asking/page-asking.module.code.ts`. `unrun` at 58-71 walks each `where` entry and judges only that every test name it carries is one of `TESTS_RUN`. The key the test is stated against is never weighed against what the page type declares.\n\n`meets` at 49-56 then reads `value[key]`, which answers undefined for a key no page carries. `where-testing` states what follows: a value holding nothing reads as bare, and an ordering test answers false over a value that reads as bare. So every page is filtered away and the answer is no rows.\n\n`asking` at 101-106 sorts by `one.value[sortBy]`, undefined on both sides, so a `sortBy` naming an unknown key leaves the rows in whatever order they arrived. `rowOf` at 79-84 takes a key only where `key in value`, so a `keys` entry naming an unknown key is dropped from every row.\n\nThe page-asking page already says a test this does not run is refused rather than dropped. That is true of the test name and there is no like guard for the key.\n\nWhy it matters now: 30 files under `akasha/` are refused by `imports-inside` since `308a810bf0` for reaching `@shared/pages-query`, and must be repointed to `@akasha/pages-query`. The old package carries `store-spelling`, which camelizes a declared kebab key on the way in and answers both spellings back. Six of the thirty state a hyphenated key in a `where` or a `sortBy`: `health-samples-access/latest-arrival`, `health-samples-access/sample-selecting`, `health-samples-access/sample-upsert`, `health-samples-day/wake-day-window`, `location-traces-access/trace-insert`, and `mobile-cli/cut-fingerprint`. Dropping that shim without a guard here turns each into no rows or no order, with nothing said.",
} as const satisfies Finding
