import type { Finding } from "../finding.page-type.ts"

export const namingAReachWouldEmptyTheImportIndex = {
  id: "01a05ad9-3b73-787f-ab20-ed7c86112b62",
  pageTypeSlug: "finding",
  slug: "naming-a-reach-would-empty-the-import-index",
  domainSlug: "workspace-package/pages-system",
  claim:
    "Rewriting the 1298 akasha imports that reach past a package edge to the names their manifests state would file no import edge for any of them. The index only files an edge for a specifier opening with a dot, and every one of those specifiers would stop opening with one. What leans on those edges is the required reading a write is gated by, the ring check, the folder shape check and the repointing a move does.",
  evidence:
    "`landingOf` in `code-specifier` answers null for any specifier that does not match `/^\\.\\.?\\//`, and `edgesIn` in `index-import` drops a null landing. The index page says it outright: `A relative specifier makes an edge and a package specifier makes none.` That was written when a package specifier meant node_modules. Eighteen akasha packages now stand in the root workspaces list, so `@akasha/pages-system/page-value` names a file in this repository, and the index would read it as naming nothing.\n\nWhat reads those edges: `importersOf` in `index-reading`, gated on the stamp; `no-import-cycle`; `folder-matches-a-shape`, which calls `edgesIn` directly; `move-repointing`; and `file-import` in context-system, which is how a write is refused until every imported page has been read. That last one is the one that matters: the gate would quietly stop asking for the pages a file leans on across a package edge.\n\n`package-reached-where-named` and `manifest-names-what-is-reached` both skip a specifier whose landing is null, because a name can only reach what a manifest exports anyway. The checks are fine; it is the index that goes blind.\n\nThe call I took: the intent that a package reaches another package by the name its manifest states is blocked by this, the same way it was blocked by folders that were no packages. Before any specifier is rewritten, the index has to resolve a workspace-package specifier to the file its manifest names, and file an edge for it. That is a change to `edgesIn` and to what `index-import` states, and it is needed whatever happens here: the shared packages already reach each other by name, so the index must see those edges before they move in.\n\nWhat already stands: all eighteen manifests, all eighteen workspace entries, and every one of the 1298 reaches past a package edge lands on a file its package's manifest names. Twelve files went into seven manifests to make that so. The rewrite is mechanical once the index can see through it.",
} as const satisfies Finding
