import type { Finding } from "../finding.page-type.ts"

export const theCallsTakenInAlansAbsenceInTheOrderTheyWantHim = {
  id: "01a05bbd-a646-7a5f-8cfa-d4cb6d7f70b6",
  pageTypeSlug: "finding",
  slug: "the-calls-taken-in-alans-absence-in-the-order-they-want-him",
  domainSlug: "domain/akasha-migration",
  claim:
    "More than a hundred findings stand and the calls inside them were taken while Alan slept. One wants him and nobody else: a credential only he can mint. Two change what the system permits rather than what it holds. Two are reserved to him by a directive, the third of them having been corrected instead. The timer I stopped is still stopped, but the reason has changed and the reason I first gave was wrong.",
  evidence:
    "Only he can do the first. `the-monarch-cookie-standing-tonight-is-dead`: Monarch answers 401, three services fail on it, and the cookie is the whole header from a signed-in browser. Both widget intents wait on that alone.\n\nSecond, where I was wrong twice. I said the timer should stay stopped until `planRescore` carried a date floor; that floor landed at `9a890bc19d`, bounded to fourteen days. I also called the service a crash-restart loop; it is not. The unit is `OnCalendar=hourly` with `Persistent=true` and no restart policy; what I saw was two queued elapses draining back to back. It stays stopped for a narrower reason: it cannot exit 0 until a persona total can land, so each run burns nine minutes to end red, masking the next real failure. Across 27 minutes of it running, zero page bytes changed. Day offsets are `[-1, 0]`, so 2026-09-01 is lost unless something captures it within two days.\n\nThen what the system permits. `the-page-store-takes-a-write-from-anything-on-the-tailnet`: a pod in an unrelated namespace, holding no grant, was answered 200 with a real body. The read half is closed and the write half stands open. `a-deploy-pushes-what-head-carries-onto-origin-main`: origin moved every fifteen minutes tonight.\n\nReserved by Alan Approves Checks, now two rather than three: `a-cycle-through-a-package-edge-goes-unseen`, 707 of 1488 edges invisible, and `a-capacitor-credit-never-fires`, holding what would clear eleven refusals. The third was corrected instead, its `.tsx` blindness widened at `abc9d4d18f` with the refusal set 11 before and after, and a third half found there: it reads no `.css`.\n\nThe call I took: order them, and correct the two I had wrong.",
} as const satisfies Finding
