import type { Finding } from "../finding.page-type.ts"

export const theAudioRoutesReadAPageWithoutSayingWhatTypeItIs = {
  id: "01a05cc1-6d52-7e87-8835-023b3318530a",
  pageTypeSlug: "finding",
  slug: "the-audio-routes-read-a-page-without-saying-what-type-it-is",
  domainSlug: "workspace-package/alanwalton-web",
  claim:
    "Four `getPage` calls under alanwalton/web's audio path pass no `pageTypeSlug`, and `getPage` throws when it is absent, so read-aloud marks, kokoro segments and the audio stream route are dead at run time. One of them cannot be fixed by adding the argument: it reads the page in order to learn its type. The type system does not catch this because `pageTypeSlug` is optional on `GetPageArgs` while `getPage` requires it, so the refusal is a thrown Error rather than a diagnostic.",
  evidence:
    '`getPage` in akasha/pages-system/pages-access/get/get.module.code.ts declares `pageTypeSlug?: string` and opens with `if (args.pageTypeSlug == null) throw new Error("getPage: pageTypeSlug is required, because a page is read from its own files")`. Optional in the type, required in the body: every caller omitting it typechecks and throws.\n\nThe four callers, all reached only from the audio path:\n\n- alanwalton/web/app/lib/read-aloud-marks.ts:28, inside `resolveChapterBody`, which holds `pageTypeSlug` as a parameter and already passes it to `getMediaConfig` on the line above.\n- alanwalton/web/app/lib/kokoro-render.ts:40, inside `resolveChapterKokoroSegments`, same shape and same parameter in scope.\n- alanwalton/web/app/routes/api.media.$pageId.$medium.stream.ts:80, where `pageTypeSlug` is a local computed nine lines earlier.\n- alanwalton/web/app/routes/api.media.$pageId.$medium.stream.ts:71, which is the one that cannot be repaired mechanically: `const page = await getPage({ where: [{ key: "id", eq: pageId }] })` exists precisely to read `page.pageTypeSlug` off the row, and pages-access can no longer answer that, because a page is now found by opening the files of a stated type rather than by scanning a table. There is `getPageByIdSuffixAcrossTypes`, but it takes an eight-hex suffix and these routes carry a whole id.\n\nThree of the four also passed `includeContent: true`, a key `GetPageArgs` has never held; that was the visible half and went at bd04d143fc. This is the half a compiler cannot see.\n\nWhat is undecided is the first call, not the other three: whether the media routes should take the page type in the URL, or pages-access should answer a whole id across types. Adding `pageTypeSlug` to the three that hold it would leave the stream route throwing one line earlier, so it is one decision rather than four.',
} as const satisfies Finding
