import type { Finding } from "../finding.page-type.ts"

export const twoTimedServicesFailEveryTickOnADeletedImport = {
  id: "01a05b4d-c815-72ed-a63c-abe121b4272c",
  pageTypeSlug: "finding",
  slug: "two-timed-services-fail-every-tick-on-a-deleted-import",
  domainSlug: "domain/akasha-migration",
  claim:
    "Three files still import two modules deleted on 2026-08-30, and two of them are workstation services run by timers. `daily-tracking-points` and `great-courses-sync` both stand failed while their timers stand active, so each starts, fails on the missing import, and does it again on the next tick. The third is the `ops deploy` command itself. The commit that deleted the modules said plainly that it was leaving the importers broken, and nothing has picked them up in the day since.",
  evidence:
    "`tools/lib/page-query-in-process.ts` and `tools/ops/page-queries-in-process.ts` are both gone, deleted in b4be591b45 on 2026-08-30, whose message closes `The four files still importing the deleted shims were already broken by the client's removal, and are left that way.` Three importers stand today: `services/daily-tracking-points.ts:5` and `services/great-courses-sync.ts:4` each import `pageQueryInProcess`, and `ops-cli/global/deploy/deploy.command.code.attachment.ts:39` imports `answerPageQueriesInProcess`. The two services are installed and timed. `systemctl --user is-active` answers `failed` for `daily-tracking-points.service` and `great-courses-sync.service`, and `active` for both their timers. The journal shows it firing rather than sitting: `2026-08-31T22:00:00 error: Cannot find module '../tools/lib/page-query-in-process.ts' from '/var/home/walton/repos/akasha/services/daily-tracking-points.ts'`, then `Failed with result 'exit-code'`. `great-courses-sync` fails one import earlier, at `2026-08-31T07:36:01 error: Cannot find module '@shared/pages-query/fetcher'`, so it is half moved to the new client rather than merely stale. Both files already import `fetchThrough` from `@akasha/pages-query/fetcher` beside the dead import, so the intent was to hand the new client an in-process fetcher, and the piece that would have supplied one is what went. No repair is available by simply pointing them at the store: the new client's page and row writers are refusal stubs today. This is not a fault of the port or of tonight's service install; it predates both by a day.",
} as const satisfies Finding
