import type { StoryTurnPlayed } from "akasha/story/world/stories/played/turns/story-turn-played.page-type.types.ts"

export const overwhereIv00073 = {
  id: "01a0fe92-3304-70cf-bf7e-0faf92295f37",
  type: "page-type/story-turn-played",
  slug: "overwhere-iv-00-073",
  ownLength: 273,
  unit: "unit/words",
  partOfCollections: ["story-played/overwhere-iv"],
  position: 73,
  prose: "txt",
  characters: ["character-player/overwhere-iv-nala", "character-other/overwhere-iv-ilsa-crane"],
  stepStatus: "step-status/recorders",
  action:
    "“No, you need someone else to watch. Tonight I’m going hunting.” I go back and train with the guards then get some sleep, then do some more training, working to Rift Rend something I can only see with Spatial Sense.",
  beats: [
    '"No, you need someone else to watch," Nala tells Aldo. "Tonight I\'m going hunting."',
    'Aldo nods slowly. "Then me and my da\'ll sit up ourselves."',
    "She walks back to Millbrook in the early light and falls in with the watch at drill.",
    "The new spear sits right in her hands. Thrust, turn, recover; the crossbar never catches.",
    "<Proficiency gained. [Spearmanship LV 4] improved to [Spearmanship LV 5].>",
    "Porridge after drill. Then her curtained corner of the bunk room, and sleep, deep and dreamless.",
    "She wakes past noon, the warmth behind her ribs full again, and walks out to the downs.",
    "A boulder, five paces off. She sits, shuts her eyes, and finds its crack with her sense.",
    "She holds it as her sense gives it: an edge, a place. No picture. Just the place.",
    "She reaches for a line. The flicker comes, and steadies, and this time it holds.",
    "A black line opens along the crack, felt rather than seen. Stone grates. Something drops.",
    "She opens her eyes. A slab has sheared off the boulder's side and lies in the grass.",
    "<New skill acquired: [Sense Casting LV 1].>",
    "She tries again, eyes shut, on a second boulder. It holds. The cut lands a hand's width off.",
    "And again, on a third. Each line costs her the same handful of warmth as any rend.",
    "The sun is sinking toward the moor. Behind her ribs, the warmth is down to two-thirds.",
    "Dace comes up the slope at a jog, breathing hard, and stops short at the split boulders.",
    '"Ilsa wants her horn back," he says. "Merrit and I have Tull\'s tonight. Where are you hunting?"',
  ],
  issues: [
    '"The sun is sinking toward the moor. Behind your ribs, the warmth is down" - Leave It Open',
  ],
  lore: [
    "lore/overwhere-iv-brookside-four-2",
    "lore/overwhere-iv-ilsa-crane-2",
    "lore/overwhere-iv-millbrook-adventurers-hall-2",
    "lore/overwhere-iv-nala",
    "lore/overwhere-iv-nala-2",
    "lore/overwhere-iv-nala-3",
    "place/overwhere-iv-the-tangle",
    "place/overwhere-iv-tull-farm",
  ],
  reviewedBy: ["story-reviewer/continuity", "story-reviewer/style"],
  recordedBy: ["story-recorder/inventory", "story-recorder/memory"],
  endsAt: "2026-10-06T18:00:00.000Z",
} as const satisfies StoryTurnPlayed
