import type { StoryTurnPlayed } from "akasha/story/world/stories/played/turns/story-turn-played.page-type.types.ts"

export const overwhereIv00017 = {
  id: "01a0f253-d6cc-7e81-9f94-fb66455153ba",
  type: "page-type/story-turn-played",
  slug: "overwhere-iv-00-017",
  cover: "image/image-8051bad0096de64c",
  ownLength: 362,
  unit: "unit/words",
  partOfCollections: ["story-played/overwhere-iv"],
  position: 17,
  prose: "txt",
  characters: [
    "character-player/overwhere-iv-nala",
    "character-other/overwhere-iv-brenna-holt",
    "character-other/overwhere-iv-wat",
    "character-other/overwhere-iv-dell",
    "character-other/overwhere-iv-oswin-pike",
  ],
  stepStatus: "step-status/recorders",
  action:
    "I go to sleep, troubled, then in the morning show up for laps and give it my full effort.",
  beats: [
    "Nala lies awake a long while after Oswin's cot creaks and his steps go. Then sleep takes her.",
    'Holt\'s hand on the curtain, grey light: "Up. Boots. Yard." The warmth behind her ribs is full.',
    "Her mouth is dry, her stomach hollow. Breakfast comes after drill, Holt says. Not before.",
    "Laps are the wall walk, the whole ring of the town, with steep stone steps at every tower.",
    "From the top of the wall, beside the gatehouse, she looks down at the common side.",
    "A dozen slimes are heaped against the foot of the wall, right below the bunk room. Quiet. Waiting.",
    'Dell sees them too and whistles. "There\'s your lambs, then. Come courting in the night."',
    "She runs. She gives it everything. The first lap is fine. The second, her lungs burn.",
    "On the third, at the far tower, the rags slip in her left boot and her foot slides off a step.",
    "She goes down hard on the stone edge. Her shin and knee take it. Pain, white and sudden.",
    "She gets up. The knee holds. She keeps going, but slower, and the others pull away.",
    "Dell laps her on the fourth, grinning over his shoulder. Wat slows, then Holt shouts him on.",
    "She finishes the last lap walking, limping on the steps, a long way behind everyone.",
    "Holt says nothing about it. She only hands her a practice spear and points at the line.",
    "Spear forms: thrust, guard, sweep, recover. Holt shouts them, fifty times over. Her arms shake.",
    "Then shield work with wicker shields, blocking Holt's slow blows until her shoulder aches.",
    'Holt steps back and looks the line over. "Sparring. Blunt spears, shields. Till one yields."',
    '"Wat, you\'re with Oswin." She points her spear at Dell, then at Nala. "Farrow. You\'re with her."',
    'Dell swings his spear round and grins. "Go gentle on me, lamb-girl."',
  ],
  lore: [
    "lore/overwhere-iv-nala",
    "place/overwhere-iv-millbrook",
    "place/overwhere-iv-millbrook-gatehouse",
  ],
  reviewedBy: ["story-reviewer/continuity", "story-reviewer/style"],
  recordedBy: ["story-recorder/inventory", "story-recorder/memory", "story-recorder/picture"],
  endsAt: "2026-09-30T07:15:00.000Z",
} as const satisfies StoryTurnPlayed
