import type { StoryTurnPlayed } from "akasha/story/world/stories/played/turns/story-turn-played.page-type.types.ts"

export const overwhereIv00079 = {
  id: "01a0ff0a-ed06-7393-a8a7-aedff64ad485",
  type: "page-type/story-turn-played",
  slug: "overwhere-iv-00-079",
  cover: "image/image-5e635ce4aeeb09b6",
  ownLength: 158,
  unit: "unit/words",
  partOfCollections: ["story-played/overwhere-iv"],
  position: 79,
  prose: "txt",
  characters: ["character-player/overwhere-iv-nala"],
  stepStatus: "step-status/player",
  action: "I dodge out of the way and run again for the farm.",
  beats: [
    "Nala feels the club coming in her close sense and throws herself aside.",
    "It whistles past her ear and thuds into the trail where her head was.",
    "She turns and runs, down the trail toward the ford, spear in hand.",
    "A sling whirrs behind her. She weaves; the stone hums past and cracks off an oak.",
    "Her sense lays the trail out a stride ahead: every root, every rut. Her feet land true.",
    "Her back burns and her side bleeds, and she runs. The feet behind her fall back, and back.",
    "The shrieks thin out behind her, until there is only her own breath and her own feet.",
    "On and on through the dark, two miles, until the trees thin and the air opens.",
    "The Tangle's edge. Across two hundred paces of meadow, a lantern glows in Tull's fold.",
    "In the fold, a little flame blooms in a raised hand, and turns toward the trees where she stands.",
  ],
  lore: [
    "lore/overwhere-iv-nala",
    "lore/overwhere-iv-nala-2",
    "lore/overwhere-iv-nala-3",
    "lore/overwhere-iv-the-tangle-2",
    "place/overwhere-iv-tull-farm",
  ],
  reviewedBy: ["story-reviewer/style", "story-reviewer/continuity"],
  recordedBy: [
    "story-recorder/inventory",
    "story-recorder/memory",
    "story-recorder/picture",
    "story-recorder/mechanics",
  ],
  endsAt: "2026-10-06T21:47:00.000Z",
  coverAfter: "In the fold, a little flame blooms in a raised hand, and turns",
} as const satisfies StoryTurnPlayed
