import type { StoryTurnPlayed } from "akasha/story/world/stories/played/turns/story-turn-played.page-type.types.ts"

export const overwhereIv00021 = {
  id: "01a0f35c-3453-776a-b2f1-18afd2e61573",
  type: "page-type/story-turn-played",
  slug: "overwhere-iv-00-021",
  unit: "unit/words",
  partOfCollections: ["story-played/overwhere-iv"],
  position: 21,
  stepStatus: "step-status/writer",
  action: "“Deal. I have a lot of growing to do. Rather do it with someone I can trust anyways.”",
  beats: [
    '"Deal," Nala says. "I have a lot of growing to do. Rather do it with someone I can trust anyways."',
    "Ilsa holds her eyes a long moment, then puts out her ink-stained hand. They shake on it. Firm.",
    "\"Then it's sworn. I keep my word, Nala. I expect the same. I don't forgive the other thing.\"",
    "She opens the drawer and takes out a folded page, unsealed. Nala glimpses her own name on it.",
    "Ilsa takes a fresh sheet, dips her pen, and writes right there on the counter where Nala can see.",
    "The new report is three lines: an old cracked crystal, a faint odd light, a crack a little grown.",
    "No colour named. No room bending. No name. Ilsa blots it, folds it, and seals it with wax.",
    "Then she walks the first page down the hall to the hearth and drops it on the coals.",
    "It curls and catches. The hooded woman sits a pace from the fire, and watches it burn.",
    'Ilsa comes back dusting her fingers. "Goes east with Garrett\'s cart. Now. My board."',
    'She taps a notice by the counter. "Hobb farm, on the Tangle\'s edge. Overrun with pest slimes."',
    '"Three copper a core, and a hot dinner at Hobb\'s table. He wants every last one gone."',
    "She reaches under the counter and sets down a pair of old leather gloves, worn soft, a little big.",
    '"From the hall\'s box of things left behind. Wear them, the jelly stings. And mind the wolves."',
  ],
  lore: ["lore/overwhere-iv-ilsa-crane"],
  endsAt: "2026-09-30T09:40:00.000Z",
} as const satisfies StoryTurnPlayed
