import type { StoryTurnPlayed } from "akasha/story/world/stories/played/turns/story-turn-played.page-type.types.ts"

export const overwhereIv00070 = {
  id: "01a0fe69-edba-713e-8516-5d047e44cee2",
  type: "page-type/story-turn-played",
  slug: "overwhere-iv-00-070",
  ownLength: 276,
  unit: "unit/words",
  partOfCollections: ["story-played/overwhere-iv"],
  position: 70,
  prose: "txt",
  characters: ["character-player/overwhere-iv-nala", "character-other/overwhere-iv-ilsa-crane"],
  stepStatus: "step-status/recorders",
  action:
    "“I might be good for a night watch, let me do some training today and I’ll let you know.” I go out from town a ways, close my eyes, and practice my spatial sight, trying to combine it with rift rend, so I can strike without seeing with my eyes.",
  beats: [
    '"I might be good for a night watch," Nala tells Ilsa. "Let me train today, and I\'ll let you know."',
    "She walks out the north gate, onto the empty downs beyond. Short grass, boulders scattered about.",
    "She picks a boulder the size of a crouching man, sits five paces from it, and shuts her eyes.",
    "Her sense finds it at once: its rounded back, a crack running down one side.",
    "She fixes on the crack and reaches for a line. A flicker, and gone.",
    "Again. The flicker lasts a breath longer before it slips. Something in it is learning.",
    "For an hour it goes that way. Each try she pictures the crack as if seen. Each try, gone.",
    "Then she stops picturing. She holds the crack only as her sense gives it: a shape, an edge, a place.",
    "The flicker steadies. For one long heartbeat the line almost holds, laid right along the crack.",
    "Then it slips, like the others. But it slipped later, and she knows why now.",
    "She works at it through the afternoon, boulder after boulder, until the sun swings west.",
    "<Proficiency gained. [Spatial Sense LV 3] improved to [Spatial Sense LV 4].>",
    "The shapes around her reach a little wider again, even when she isn't reaching for them.",
    "She opens her eyes, shoulders her spear, and walks back to town in the late sun.",
    "At the hall, Dace of the Brookside Four is waiting by the board.",
    'He straightens when he sees her. "Heard about the hobgoblin. And the wolf\'s head, after."',
    '"Asked Ilsa if you\'d join us. She said ask you myself." He grins. "So. Join the Four? For good?"',
  ],
  issues: ['"get up, shoulder your spear, and start back for town" - Leave It Open'],
  lore: [
    "lore/overwhere-iv-brookside-four-2",
    "lore/overwhere-iv-ilsa-crane-2",
    "lore/overwhere-iv-nala",
    "lore/overwhere-iv-nala-2",
    "lore/overwhere-iv-nala-3",
    "place/overwhere-iv-north-west-pastures",
  ],
  reviewedBy: ["story-reviewer/style", "story-reviewer/continuity"],
  recordedBy: ["story-recorder/inventory"],
  endsAt: "2026-10-05T16:03:00.000Z",
} as const satisfies StoryTurnPlayed
