import type { StoryTurnPlayed } from "akasha/story/world/stories/played/turns/story-turn-played.page-type.types.ts"

export const overwhereIv00031 = {
  id: "01a0f3ed-0d8e-7a20-a627-fc2a7a7c4abb",
  type: "page-type/story-turn-played",
  slug: "overwhere-iv-00-031",
  ownLength: 208,
  unit: "unit/words",
  partOfCollections: ["story-played/overwhere-iv"],
  position: 31,
  prose: "txt",
  characters: ["character-player/overwhere-iv-nala"],
  stepStatus: "step-status/recorders",
  action:
    "I cast my new spell at the runner, aiming for where its neck will be when the spell hits.",
  beats: [
    "Nala turns from the dead goblin and finds the runner: small, quick, weaving between the yews.",
    "Twenty-five paces and widening. It jinks left of one trunk, then right of the next.",
    "She watches its line, not the goblin. The gap between two yews it has to take.",
    "She fixes her eye on that gap, at neck height, a heartbeat ahead of it. Reaches for the warmth.",
    "A thin black-purple line hangs in the air there, for no time at all.",
    "The runner goes into it at full tilt.",
    "It falls in two pieces. Behind it, a yew bough drops, cut as clean as the goblin.",
    "<Goblin LV 2 defeated. Experience gained.>",
    "The warmth behind her ribs dips again, a handful less. Still more there than gone.",
    'Wren skids to a stop at the hollow\'s edge, staring at the fallen bough. "Gods above."',
    "In the hollow, the two hurt scouts see it too. They shrink back behind the penned sheep.",
    "Dace wades down toward the oak, shield up. Orla is at his shoulder.",
    "Atop the fallen oak, the slinger rises out of its crouch. Smoke curls off its singed hide.",
    "It isn't looking at Dace. It's looking at her. The sling starts to whirl.",
  ],
  lore: [
    "lore/overwhere-iv-brookside-four",
    "lore/overwhere-iv-nala",
    "lore/overwhere-iv-nala-2",
    "place/overwhere-iv-the-tangle",
  ],
  reviewedBy: ["story-reviewer/continuity", "story-reviewer/style"],
  recordedBy: ["story-recorder/inventory", "story-recorder/memory", "story-recorder/mechanics"],
  endsAt: "2026-10-01T13:13:00.000Z",
} as const satisfies StoryTurnPlayed
