import type { StoryTurnPlayed } from "akasha/story/world/stories/played/turns/story-turn-played.page-type.types.ts"

export const overwhereIv00077 = {
  id: "01a0fef5-032c-7168-b29c-da641dc7ade0",
  type: "page-type/story-turn-played",
  slug: "overwhere-iv-00-077",
  cover: "image/image-84b0e9878e992791",
  ownLength: 206,
  unit: "unit/words",
  partOfCollections: ["story-played/overwhere-iv"],
  position: 77,
  prose: "txt",
  characters: ["character-player/overwhere-iv-nala"],
  stepStatus: "step-status/player",
  action:
    "I put one more slice in front of the line, as wide as I can make it, right where they will move into the slice, then get up and race for the farm.",
  beats: [
    "Nala lays one more line downslope, across the climbers' path, as wide as it will go: four paces.",
    "At goblin neck height. She holds it open, and the last of the warmth pours out to keep it there.",
    "Two goblins push through the brambles side by side, straight into it, and drop without a sound.",
    "<Goblin LV 4 defeated. Experience gained.>",
    "<Goblin LV 3 defeated. Experience gained.>",
    "The line closes. She surges up out of the brambles, spear in hand.",
    "A goblin sees her rise and shrieks. The whole band shrieks back.",
    "She leaps down to the trail and runs for the ford, her sense finding the ground a stride ahead.",
    "Behind her the maul-bearer roars. Feet pound after her: the four climbers, and a slinger.",
    "A sling whirrs at her back. She runs hard, but her foot catches a root on a bend.",
    "The stone takes her square between the shoulders. She goes down hard on the trail.",
    "The breath is knocked out of her. Her back burns. The warmth behind her ribs is a last ember.",
    "Feet pound down the trail behind her. In her close sense, the spear goblin is three paces off.",
    "It draws back its spear to stab down at her.",
  ],
  lore: [
    "lore/overwhere-iv-nala",
    "lore/overwhere-iv-nala-2",
    "lore/overwhere-iv-nala-3",
    "lore/overwhere-iv-the-tangle-2",
  ],
  reviewedBy: ["story-reviewer/continuity", "story-reviewer/style"],
  recordedBy: [
    "story-recorder/inventory",
    "story-recorder/mechanics",
    "story-recorder/memory",
    "story-recorder/picture",
  ],
  endsAt: "2026-10-06T21:21:00.000Z",
  coverAfter: "The breath is knocked out of you. Your back burns. The warmth",
} as const satisfies StoryTurnPlayed
