import type { StoryTurnPlayed } from "akasha/story/world/stories/played/turns/story-turn-played.page-type.types.ts"

export const overwhereIv00089 = {
  id: "01a1019a-1b6f-7f2e-a400-3a3550c86369",
  type: "page-type/story-turn-played",
  slug: "overwhere-iv-00-089",
  cover: "image/image-af0caa4b352aef07",
  ownLength: 132,
  unit: "unit/words",
  partOfCollections: ["story-played/overwhere-iv"],
  position: 89,
  prose: "txt",
  characters: ["character-player/overwhere-iv-nala"],
  stepStatus: "step-status/player",
  action: "I slice the horn blower, then the runner, heads off at the neck",
  beats: [
    "Nala fixes her eye on the horn-blower's neck and lays the line before its breath is drawn.",
    "Its head falls from its shoulders. The horn tumbles unblown into the leaves.",
    "<Goblin LV 5 defeated. Experience gained.>",
    "The runner is ten strides up the trail, arms pumping. She lays a second line across its neck.",
    "It drops mid-stride, head and body rolling apart.",
    "<Goblin LV 4 defeated. Experience gained.>",
    "Silence. She spreads her sense wide: birds, nothing else living near. The trail ahead is empty.",
    "In the watchers' hide: a water gourd, a gnawed hare bone, and the horn, of yellowed bone.",
    "From the rise the smoke is plain now, rising above the trees up the trail.",
    "And down from there, faint through the oaks, come axe-strokes: many of them, steady, one on another.",
  ],
  lore: [
    "lore/overwhere-iv-nala",
    "lore/overwhere-iv-nala-2",
    "lore/overwhere-iv-nala-3",
    "lore/overwhere-iv-the-tangle-2",
    "lore/overwhere-iv-the-tangle-3",
  ],
  reviewedBy: ["story-reviewer/continuity", "story-reviewer/style"],
  recordedBy: [
    "story-recorder/inventory",
    "story-recorder/memory",
    "story-recorder/mechanics",
    "story-recorder/picture",
  ],
  endsAt: "2026-10-07T10:51:00.000Z",
  coverAfter: "From the rise the smoke is plain now, rising above the trees up the trail.",
} as const satisfies StoryTurnPlayed
