import type { StoryTurnPlayed } from "akasha/story/world/stories/played/turns/story-turn-played.page-type.types.ts"

export const overwhereIv00060 = {
  id: "01a0fdb3-1333-72d3-b649-a70fc3332c1d",
  type: "page-type/story-turn-played",
  slug: "overwhere-iv-00-060",
  cover: "image/image-8828c02d226e920a",
  coverAfter: "Shapes thick and spiny choke its sides. Gorse. A beck runs in",
  ownLength: 385,
  unit: "unit/words",
  partOfCollections: ["story-played/overwhere-iv"],
  position: 60,
  prose: "txt",
  characters: ["character-player/overwhere-iv-nala", "character-other/overwhere-iv-ilsa-crane"],
  stepStatus: "step-status/player",
  action:
    "“I’ll hunt the wolf today” I get directions to the old quarry and follow them, then close my eyes and focus on navigating by spacial sense. If I find any wolves, I use Rend on their throats with my eyes still closed.",
  beats: [
    '"I\'ll hunt the wolf today," Nala tells Ilsa, and asks the way to the old quarry.',
    '"Out the north gate, left at the shrine\'s stone cross, up through the north-west pastures."',
    '"The quarry\'s two days on, up the old Crowstone track. Nobody walks there and back in a day."',
    "Two miles out, the town gives way to open sheep downs. A stone hut squats beside a fold.",
    "A young shepherd leans on the fold wall. Fen Carrow. He's lost two ewes in three nights.",
    '"Dragged off whole," he says. "Up the track." He points at the mud by the gate.',
    "Paw prints, as wide as a man's spread hand. Drag marks run from them up the grassed-over track.",
    "At the pastures' far edge the cart track runs on north-west, over moor. Nala closes her eyes.",
    "Her always-on sense gives her the ruts underfoot: firm, grassed over. She walks, slowly.",
    "Beside the track the moor is tussock and bog holes. Her sense feels them, but not what's soft.",
    "The prints she saw in the mud are gone now, faint dents among a thousand others.",
    "Every so often she stops and reaches wide, out to forty paces. Sheep. Hares. Nothing big.",
    "The wind is in her face all the way, blowing down the track from the north-west.",
    "Hours of it. Five miles up, the ground ahead drops away: a steep gully crossing the track.",
    "Shapes thick and spiny choke its sides. Gorse. A beck runs in the bottom.",
    "She reaches wide. Up the gully, at its head, a hollow under a shelf of rock. Bones scattered.",
    "And lying among them, thirty paces off, something huge. Four legs. Tall as a pony, curled asleep.",
    "A ridge runs down its spine, hard and thin as a row of blades.",
    "Its ribs rise and fall slowly. It hasn't stirred.",
    "Eyes still shut, she reaches for a line across its throat. There's no spot for her eye to fix on.",
    "The line won't form. Nothing opens, and no warmth is spent.",
    "From the track the gorse stands between her and the overhang. She'd not see it with eyes open.",
    "Her sense holds the shape of the gully: above the overhang, a lip of loose stone, steep and high.",
  ],
  issues: ['"The beast sleeps on, thirty paces away." - Leave It Open'],
  lore: [
    "lore/overwhere-iv-ilsa-crane-2",
    "lore/overwhere-iv-nala",
    "lore/overwhere-iv-nala-2",
    "place/overwhere-iv-crake-gill",
    "place/overwhere-iv-crowstone-quarry",
    "place/overwhere-iv-north-west-pastures",
  ],
  reviewedBy: ["story-reviewer/continuity", "story-reviewer/style"],
  recordedBy: [
    "story-recorder/inventory",
    "story-recorder/mechanics",
    "story-recorder/memory",
    "story-recorder/picture",
  ],
  endsAt: "2026-10-04T14:20:00.000Z",
} as const satisfies StoryTurnPlayed
