import type { StoryTurnPlayed } from "akasha/story/world/stories/played/turns/story-turn-played.page-type.types.ts"

export const overwhereIv00024 = {
  id: "01a0f385-6677-7600-a90c-dc5982ebc9e5",
  type: "page-type/story-turn-played",
  slug: "overwhere-iv-00-024",
  cover: "image/image-38a5af1cf7bbea30",
  ownLength: 359,
  unit: "unit/words",
  partOfCollections: ["story-played/overwhere-iv"],
  position: 24,
  prose: "txt",
  characters: ["character-player/overwhere-iv-nala"],
  stepStatus: "step-status/player",
  action:
    "“Okay, maybe wolves, maybe goblins or something similar. Point me where to go, and I’ll take a look.” Once I know where to go, I stay in that direction and practice combining my Dimensional Magic with the spear, jumping the spear forward beyond its normal reach.",
  beats: [
    '"Okay. Maybe wolves, maybe goblins or something like it. Point me where to go and I\'ll take a look."',
    "Hobb points past the orchard: the far field, and its dry-stone wall where it runs by the trees.",
    "Pim wants to come. Hobb catches his collar. Bran stays too, growling, pressed against Pim's legs.",
    "Nala walks down the far field alone. The grass is wet. The Tangle is a black wall past the stones.",
    "She stops by a fence post near the wall. Her idea: fold the spear mid-thrust, push it past reach.",
    "First try: she thrusts, reaches for the warmth. The click comes early. The point jerks wide.",
    "The shaft wrenches in her grip. Held any looser, it would have torn clean out of her hands.",
    "She grips harder. Thrust, and let the click drop right as her arms reach full length.",
    "The spearpoint lands a foot past where her arms can reach. Splinters fly off the post. It works.",
    "The jar runs up both wrists, like she hit the post with a hammer instead. She shakes her hands out.",
    "Three more thrusts. By the fifth and last, the click meets the thrust. Clean. A foot farther.",
    "Five folds spent. The warmth behind her ribs runs a little under half. Her wrists ache.",
    "At the wall, by a gap where stones have fallen, the mud is churned. She crouches to look.",
    "Tracks, small and bare-toed, with long narrow toes. No paws. A clump of torn fleece in the mud.",
    "Out past the gap, from the black of the Tangle, something moves. Two small shapes, bent low.",
    "They come out of the trees toward the gap, quick and quiet, eyes on the sheep. Thirty paces off.",
    "Child-sized, grey-green skin, dressed in hide scraps. One carries a flint-tipped spear.",
    "The other has a rusty knife. It grins at the sheep in the near field, and licks its teeth.",
  ],
  issues: [
    '"They haven\'t seen you." - No Prompt',
    '"The warmth ... sits at about half now" - 6+ folds done; seven folds run her warmth near empty',
  ],
  lore: ["lore/overwhere-iv-nala", "place/overwhere-iv-hobb-farm"],
  reviewedBy: ["story-reviewer/style", "story-reviewer/continuity"],
  recordedBy: [
    "story-recorder/inventory",
    "story-recorder/mechanics",
    "story-recorder/memory",
    "story-recorder/picture",
  ],
  endsAt: "2026-09-30T18:27:00.000Z",
} as const satisfies StoryTurnPlayed
