import type { StoryTurnPlayed } from "akasha/story/world/stories/played/turns/story-turn-played.page-type.types.ts"

export const overwhereIv00033 = {
  id: "01a0f400-cf26-7981-a501-c1fda0332e56",
  type: "page-type/story-turn-played",
  slug: "overwhere-iv-00-033",
  ownLength: 196,
  unit: "unit/words",
  partOfCollections: ["story-played/overwhere-iv"],
  position: 33,
  prose: "txt",
  characters: ["character-player/overwhere-iv-nala"],
  stepStatus: "step-status/recorders",
  action: "This time, I cast Rift Rend, aiming to cut the slinger in half",
  beats: [
    "Nala stays down in the leaf mould. Her shoulder throbs. She looks up at the oak.",
    "The slinger stands still on the trunk, whirling, its whole body leaning into the throw.",
    "She fixes her eye on its middle, square across. Reaches for the warmth. Cut.",
    "The black-purple line is there, exact, where she looked.",
    "It is already turning into the throw. The line takes its sling arm and bites deep into its side.",
    "Bark splits. The oak limb under its feet parts along the same line and drops.",
    "The slinger drops with it, shrieking, the sling spinning away empty into the brush.",
    "<Proficiency gained. [Rift Rend LV 2] improved to [Rift Rend LV 3].>",
    "The warmth behind her ribs is thinner now. Near half gone, she guesses.",
    "The goblin lands in a heap at the oak's foot, a stride from Dace. It isn't dead. It is gasping.",
    "In the hollow, the two hurt scouts throw down spear and knife and grovel, wailing for mercy.",
    "Dace plants his foot on the slinger's back and looks across at Nala, breathing hard.",
    '"That\'s your cut," he calls. "You want to finish it, or shall I?"',
  ],
  issues: [
    '"Neither moves" - lore: if the slinger falls, the hurt scouts throw down weapons and grovel',
  ],
  lore: ["lore/overwhere-iv-nala", "lore/overwhere-iv-nala-2", "place/overwhere-iv-the-tangle"],
  reviewedBy: ["story-reviewer/continuity", "story-reviewer/style"],
  recordedBy: ["story-recorder/inventory", "story-recorder/mechanics", "story-recorder/memory"],
  endsAt: "2026-10-01T13:15:00.000Z",
} as const satisfies StoryTurnPlayed
