import type { StoryTurnPlayed } from "akasha/story/world/stories/played/turns/story-turn-played.page-type.types.ts"

export const overwhereIv00076 = {
  id: "01a0fed5-e95d-71d0-a9ef-773f747ad587",
  type: "page-type/story-turn-played",
  slug: "overwhere-iv-00-076",
  ownLength: 188,
  unit: "unit/words",
  partOfCollections: ["story-played/overwhere-iv"],
  position: 76,
  prose: "txt",
  characters: ["character-player/overwhere-iv-nala"],
  stepStatus: "step-status/reviewers",
  action:
    "I mix in targeting the ones most likely to find me, the two quiet ones first, then hiding then in the rest",
  beats: [
    "Nala takes the two quiet ones first, before they reach the band.",
    "The nearer, running hard below her bank: she finds its neck by feel and lays the line.",
    "It drops mid-stride without a sound and rolls to the trail's edge.",
    "<Goblin LV 4 defeated. Experience gained.>",
    "The second skids at the body, knife up, peering ahead. Her line takes it through the throat.",
    "<Goblin LV 3 defeated. Experience gained.>",
    "<Racial Experience threshold reached. Human is now LV 6.>",
    "Both lie dead at the foot of her bank, twenty paces from the shrieking knot.",
    "She reaches for the band again, for a slinger whirling at the knot's edge.",
    "Her aim slips. The line goes wide and shears a yew bough over the bank's edge, near her.",
    "The bough crashes down into the brambles, loud in the dark.",
    "Every goblin face in the knot turns toward the sound. The slings swing round to it.",
    "Behind her ribs the warmth runs thin: a fifth left.",
    "The maul-bearer bellows and points his maul at her bank.",
    "Six goblins break from the knot and come at the brambles, clubs and spears up.",
  ],
  lore: [
    "lore/overwhere-iv-nala",
    "lore/overwhere-iv-nala-2",
    "lore/overwhere-iv-nala-3",
    "lore/overwhere-iv-the-tangle-2",
  ],
  reviewedBy: ["story-reviewer/continuity"],
  endsAt: "2026-10-06T21:18:00.000Z",
} as const satisfies StoryTurnPlayed
