import type { Question } from "akasha/personas/questions/question.page-type.types.ts"

export const thirtyThreeOf237CommandsSayListOrShowShouldThe = {
  id: "01a095c0-657e-7a19-933e-00ef1673f20d",
  type: "question",
  slug: "thirty-three-of-237-commands-say-list-or-show-should-the",
  ask: "Thirty-three of 237 commands say `list` or `show`. Should the rule bind on the rest? Counted off the pages now: 13 commands are named exactly `list` and 12 more carry it as a hyphen component — `contact-list`, `recent-list`, `unread-list`, `active-list`, `capability-list`, `transcript-list`, `addon-list`, `error-list`, `category-list`, `log-list`, `declaration-list`, `turn-color-list` — making 25. Eight are named exactly `show`, and no name carries `show` as a component. So 33 conform and 204 do not. Of those, roughly fifty answer something and say neither word, and that figure cannot be made exact mechanically: a command page carries no marker saying whether it reads or writes, so the only way to tell an answering command from an acting one is to read its definition line. Which side each belongs on is softer still. Several are genuinely undecidable from the definition alone — `domain dag` and `initiative work-tree` and `page tree` answer one tree made of many rows, `infrastructure dev-server log` answers one tail made of many lines, `seat compose-notices` answers many notices in one object, and `track session check` reads many rows and answers one verdict. The rule would have to say which of those is many. The sharpest consequence is on the eight commands already named for answering. Seven are named exactly `status` and one is `testflight-status`, and `status` already says that the command answers rather than acts; the rule would append a second answer-word, giving `infrastructure dev-server status show`, `model gateway status list`, `temper catalog status list` and so on, which splits three many and five one. Nothing writes the rule down today. `commands/properties/level-name.text-property.ts` states two invariants about a level name and neither is about the act word, and the command page type states nine and none is either. Renaming is cheap in the places that were feared and dear in one that was not: the shell aliases and the editor extension both take a name off the imported page object rather than spelling it, so neither changes, but a comparable rename earlier today, `1ce847a58b2`, touched 41 files — two in the command's own folder, one namespace parts list, and the rest prose and generated provenance records carrying the rendered call path, which nothing checks and which drift silently.",
  askedBy: "athena",
  askedIn: "01a09264-510d-791b-bed6-6bfd0815b604",
  status: "open",
  offered: [
    "The rule binds everywhere, the roughly fifty act-less commands take `list` or `show`, and the eight `status` commands take a second answer-word as the rule requires",
    "The rule binds except where a command is already named for answering, so `status` is left alone and only the act-less commands are renamed",
    "The rule is narrowed to commands that answer a collection of separate things, which leaves the one-tree and one-tail and one-verdict cases alone and makes the split decidable from the definition line",
    "The rule is dropped as a rule and kept as a habit for new commands, since 204 of 237 commands do not follow it and nothing refuses them",
  ],
} as const satisfies Question
