import type { TemperSet } from "akasha/temper/catalog/gear/temper-set/temper-set.page-type.types.ts"

export const pointBlankSnipe = {
  id: "019e6484-5fcf-7246-9958-304dca92ca90",
  type: "page-type/temper-set",
  slug: "point-blank-snipe",
  title: "Point-Blank Snipe",
  key: "point-blank-snipe",
  esoSetId: 560,
  hashPlace: 444,
  esoItemIds: [169887],
  esoEquipTypes: ["EQUIP_TYPE_TWO_HAND"],
  esoWeaponTypes: ["WEAPONTYPE_BOW"],
  setWayshrines: [457, 457, 457],
  setTypeId: 1,
  setNameZh: "近程狙击",
  setNameRu: "Выстрел в упор",
  setNameFr: "Tir à Bout portant",
  setNameEs: "Disparo a quemarropa",
  setNameDe: "Volltreffer",
  setDropZones: [1227, 1207, 1207],
  setDropMechanics: [5, 5],
  setDlcId: 20,
  itemBrowserSources: ["1227"],
  itemBrowserPlaceKinds: [5],
  itemBrowserItemId: 169921,
  category: "temper-set-category/arena",
  valid: ["bow"],
  bonuses: "jsonl",
  icons: "jsonl",
} as const satisfies TemperSet
