type AbilityType = number
declare const ABILITY_TYPE_ACTIONLIST: number
declare const ABILITY_TYPE_AREAEFFECT: number
declare const ABILITY_TYPE_AREATELEPORT: number
declare const ABILITY_TYPE_ATTACKERINTERCEPT: number
declare const ABILITY_TYPE_ATTACKERREFLECT: number
declare const ABILITY_TYPE_AVAREACH: number
declare const ABILITY_TYPE_AVOIDDEATH: number
declare const ABILITY_TYPE_BASIC: number
declare const ABILITY_TYPE_BLADETURN: number
declare const ABILITY_TYPE_BLINK: number
declare const ABILITY_TYPE_BLOCK: number
declare const ABILITY_TYPE_BONUS: number
declare const ABILITY_TYPE_CHANGEAPPEARANCE: number
declare const ABILITY_TYPE_CHARGE: number
declare const ABILITY_TYPE_CLIENTFX: number
declare const ABILITY_TYPE_COMBATRESOURCE: number
declare const ABILITY_TYPE_COSTMECHANICOVERRIDE: number
declare const ABILITY_TYPE_CREATEINTERACTABLE: number
declare const ABILITY_TYPE_CREATEINVENTORYITEM: number
declare const ABILITY_TYPE_CUSTOMTARGETAREA: number
declare const ABILITY_TYPE_DEPRECATED_0: number
declare const ABILITY_TYPE_DAMAGE: number
declare const ABILITY_TYPE_DAMAGEIMMUNE: number
declare const ABILITY_TYPE_DAMAGELIMIT: number
declare const ABILITY_TYPE_DAMAGESHIELD: number
declare const ABILITY_TYPE_DAMAGETRANSFER: number
declare const ABILITY_TYPE_DEFEND: number
declare const ABILITY_TYPE_DERIVEDSTATCACHE: number
declare const ABILITY_TYPE_DESPAWNOVERRIDE: number
declare const ABILITY_TYPE_DIRECTEDMOVEMENTABILITY: number
declare const ABILITY_TYPE_DISABLECLIENTTURNING: number
declare const ABILITY_TYPE_DISABLEGAMEPLAYMECHANICS: number
declare const ABILITY_TYPE_DISABLEITEMSETS: number
declare const ABILITY_TYPE_DISARM: number
declare const ABILITY_TYPE_DISORIENT: number
declare const ABILITY_TYPE_DISPEL: number
declare const ABILITY_TYPE_DODGE: number
declare const ABILITY_TYPE_EXHAUSTED: number
declare const ABILITY_TYPE_FACETARGET: number
declare const ABILITY_TYPE_FEAR: number
declare const ABILITY_TYPE_FILLSOULGEM: number
declare const ABILITY_TYPE_FIRETRIGGER: number
declare const ABILITY_TYPE_FLIGHT: number
declare const ABILITY_TYPE_FOLLOWWAYPOINTPATH: number
declare const ABILITY_TYPE_FREECAST: number
declare const ABILITY_TYPE_FREEINTERACT: number
declare const ABILITY_TYPE_GRANTABILITY: number
declare const ABILITY_TYPE_HARDDISMOUNT: number
declare const ABILITY_TYPE_HEAL: number
declare const ABILITY_TYPE_HIDE: number
declare const ABILITY_TYPE_HOTBARSLOTOVERRIDE: number
declare const ABILITY_TYPE_IMMUNITY: number
declare const ABILITY_TYPE_INTERACTREFUSALOVERRIDE: number
declare const ABILITY_TYPE_INTERCEPT: number
declare const ABILITY_TYPE_INTERRUPT: number
declare const ABILITY_TYPE_JUMP: number
declare const ABILITY_TYPE_KNOCKBACK: number
declare const ABILITY_TYPE_LOSMOVEPOSITION: number
declare const ABILITY_TYPE_LEAP: number
declare const ABILITY_TYPE_LEVITATE: number
declare const ABILITY_TYPE_LIGHTHEAVYATTACKOVERRIDE: number
declare const ABILITY_TYPE_LINKTARGET: number
declare const ABILITY_TYPE_MISDIRECT: number
declare const ABILITY_TYPE_MODIFYCOOLDOWN: number
declare const ABILITY_TYPE_MODIFYDURATION: number
declare const ABILITY_TYPE_MODIFYSTACKCOUNT: number
declare const ABILITY_TYPE_MOUNT: number
declare const ABILITY_TYPE_MOUNTBLOCK: number
declare const ABILITY_TYPE_MOVEPOSITION: number
declare const ABILITY_TYPE_NOAGGRO: number
declare const ABILITY_TYPE_NOKILL: number
declare const ABILITY_TYPE_NOLOCKPICK: number
declare const ABILITY_TYPE_NOSEETARGET: number
declare const ABILITY_TYPE_NONCOMBATBONUS: number
declare const ABILITY_TYPE_NONEXISTENT: number
declare const ABILITY_TYPE_NONE: number
declare const ABILITY_TYPE_OFFBALANCE: number
declare const ABILITY_TYPE_PACIFY: number
declare const ABILITY_TYPE_PARRY: number
declare const ABILITY_TYPE_PATHLINE: number
declare const ABILITY_TYPE_PAUSECOOLDOWN: number
declare const ABILITY_TYPE_PERSISTENTRADIUS: number
declare const ABILITY_TYPE_PHASETHROUGH: number
declare const ABILITY_TYPE_PLAYERFLIGHT: number
declare const ABILITY_TYPE_PREVENTHEALING: number
declare const ABILITY_TYPE_RANDOMBRANCH: number
declare const ABILITY_TYPE_RECALL: number
declare const ABILITY_TYPE_REFLECTION: number
declare const ABILITY_TYPE_REGISTERTRIGGER: number
declare const ABILITY_TYPE_REMOVETYPE: number
declare const ABILITY_TYPE_REPAIR: number
declare const ABILITY_TYPE_RESOURCETAP: number
declare const ABILITY_TYPE_RESURRECT: number
declare const ABILITY_TYPE_REVEAL: number
declare const ABILITY_TYPE_REWINDTIME: number
declare const ABILITY_TYPE_SEESTEALTH: number
declare const ABILITY_TYPE_SETAIMATTARGET: number
declare const ABILITY_TYPE_SETCOOLDOWN: number
declare const ABILITY_TYPE_SETHOTBAR: number
declare const ABILITY_TYPE_SETPERSONALITY: number
declare const ABILITY_TYPE_SETTARGET: number
declare const ABILITY_TYPE_SHOWNON: number
declare const ABILITY_TYPE_SIEGEAREAEFFECT: number
declare const ABILITY_TYPE_SIEGECLUSTERAREAEFFECT: number
declare const ABILITY_TYPE_SIEGECREATE: number
declare const ABILITY_TYPE_SIEGEPACKUP: number
declare const ABILITY_TYPE_SILENCE: number
declare const ABILITY_TYPE_SLOWFALL: number
declare const ABILITY_TYPE_SNARE: number
declare const ABILITY_TYPE_SOULGEMRESURRECT: number
declare const ABILITY_TYPE_SPECIALMOVEREPLACEMENT: number
declare const ABILITY_TYPE_STAGGER: number
declare const ABILITY_TYPE_STEALTH: number
declare const ABILITY_TYPE_STOPMOVING: number
declare const ABILITY_TYPE_STUN: number
declare const ABILITY_TYPE_SUMMON: number
declare const ABILITY_TYPE_THREAT: number
declare const ABILITY_TYPE_TRAUMA: number
declare const ABILITY_TYPE_UPDATEDEATHDIALOG: number
declare const ABILITY_TYPE_VAMPIRE: number
type MorphSlot = number
declare const MORPH_SLOT_BASE: number
declare const MORPH_SLOT_MORPH_1: number
declare const MORPH_SLOT_MORPH_2: number
type ScribingSlot = number
declare const SCRIBING_SLOT_NONE: number
declare const SCRIBING_SLOT_PRIMARY: number
declare const SCRIBING_SLOT_SECONDARY: number
declare const SCRIBING_SLOT_TERTIARY: number
type LFGActivity = number
declare const LFG_ACTIVITY_ADVENTURE_ZONE: number
declare const LFG_ACTIVITY_ARENA: number
declare const LFG_ACTIVITY_AVA: number
declare const LFG_ACTIVITY_BATTLE_GROUND_CHAMPION: number
declare const LFG_ACTIVITY_BATTLE_GROUND_LOW_LEVEL: number
declare const LFG_ACTIVITY_BATTLE_GROUND_NON_CHAMPION: number
declare const LFG_ACTIVITY_DUNGEON: number
declare const LFG_ACTIVITY_ENDLESS_DUNGEON: number
declare const LFG_ACTIVITY_EXPLORATION: number
declare const LFG_ACTIVITY_HOME_SHOW: number
declare const LFG_ACTIVITY_INVALID: number
declare const LFG_ACTIVITY_MASTER_DUNGEON: number
declare const LFG_ACTIVITY_TRIAL: number
declare const LFG_ACTIVITY_TRIBUTE_CASUAL: number
declare const LFG_ACTIVITY_TRIBUTE_COMPETITIVE: number
type LFGGroupType = number
declare const LFG_GROUP_TYPE_BIG_TEAM_BATTLE: number
declare const LFG_GROUP_TYPE_LARGE: number
declare const LFG_GROUP_TYPE_MEDIUM: number
declare const LFG_GROUP_TYPE_NONE: number
declare const LFG_GROUP_TYPE_REGULAR: number
type LFGRole = number
declare const LFG_ROLE_DPS: number
declare const LFG_ROLE_HEAL: number
declare const LFG_ROLE_INVALID: number
declare const LFG_ROLE_TANK: number
type PromotionalEventRewardFlags = number
declare const PROMOTIONAL_EVENTS_REWARD_FLAG_CLAIMED: number
declare const PROMOTIONAL_EVENTS_REWARD_FLAG_CLAIMED_FALLBACK: number
declare const PROMOTIONAL_EVENTS_REWARD_FLAG_FALLBACK: number
declare const GROUP_FINDER_UNLOCK_LEVEL: number
declare const GROUP_FINDER_MAX_APPLIED_TO_GROUP_LISTING_ATTEMPTS: number
declare const GROUP_FINDER_MAX_SEARCHABLE_SELECTIONS: number
type OutfitSlot = number
declare const OUTFIT_SLOT_BODY_MARKING: number
declare const OUTFIT_SLOT_CHEST: number
declare const OUTFIT_SLOT_COSTUME: number
declare const OUTFIT_SLOT_FACIAL_ACCESSORY: number
declare const OUTFIT_SLOT_FACIAL_HAIR_HORNS: number
declare const OUTFIT_SLOT_FEET: number
declare const OUTFIT_SLOT_HAIR: number
declare const OUTFIT_SLOT_HANDS: number
declare const OUTFIT_SLOT_HAT: number
declare const OUTFIT_SLOT_HEAD: number
declare const OUTFIT_SLOT_HEAD_MARKING: number
declare const OUTFIT_SLOT_LEGS: number
declare const OUTFIT_SLOT_MOUNT: number
declare const OUTFIT_SLOT_PERSONALITY: number
declare const OUTFIT_SLOT_PIERCING_JEWELRY: number
declare const OUTFIT_SLOT_POLYMORPH: number
declare const OUTFIT_SLOT_SHIELD: number
declare const OUTFIT_SLOT_SHIELD_BACKUP: number
declare const OUTFIT_SLOT_SHOULDERS: number
declare const OUTFIT_SLOT_SKIN: number
declare const OUTFIT_SLOT_VANITY_PET: number
declare const OUTFIT_SLOT_WAIST: number
declare const OUTFIT_SLOT_WEAPON_BOW: number
declare const OUTFIT_SLOT_WEAPON_BOW_BACKUP: number
declare const OUTFIT_SLOT_WEAPON_MAIN_HAND: number
declare const OUTFIT_SLOT_WEAPON_MAIN_HAND_BACKUP: number
declare const OUTFIT_SLOT_WEAPON_OFF_HAND: number
declare const OUTFIT_SLOT_WEAPON_OFF_HAND_BACKUP: number
declare const OUTFIT_SLOT_WEAPON_STAFF: number
declare const OUTFIT_SLOT_WEAPON_STAFF_BACKUP: number
declare const OUTFIT_SLOT_WEAPON_TWO_HANDED: number
declare const OUTFIT_SLOT_WEAPON_TWO_HANDED_BACKUP: number
declare const MAX_COMPANION_OUTFITS: number
declare const MAX_ITEM_MATERIALS_PER_OUTFIT_STYLE: number
declare const MAX_OUTFIT_UNLOCKS: number
declare const NUM_OUTFITS_PER_UPGRADE: number
type BattlegroundState = number
declare const BATTLEGROUND_STATE_FINISHED: number
declare const BATTLEGROUND_STATE_NONE: number
declare const BATTLEGROUND_STATE_POSTROUND: number
declare const BATTLEGROUND_STATE_PREROUND: number
declare const BATTLEGROUND_STATE_RUNNING: number
declare const BATTLEGROUND_STATE_STARTING: number
type ObjectiveControlEvent = number
declare const OBJECTIVE_CONTROL_EVENT_AREA_INFLUENCE_CHANGED: number
declare const OBJECTIVE_CONTROL_EVENT_AREA_NEUTRAL: number
declare const OBJECTIVE_CONTROL_EVENT_ASSAULTED: number
declare const OBJECTIVE_CONTROL_EVENT_CAPTURED: number
declare const OBJECTIVE_CONTROL_EVENT_DEACTIVATED: number
declare const OBJECTIVE_CONTROL_EVENT_DEACTIVATE_PENDING: number
declare const OBJECTIVE_CONTROL_EVENT_FLAG_DROPPED: number
declare const OBJECTIVE_CONTROL_EVENT_FLAG_RETURNED: number
declare const OBJECTIVE_CONTROL_EVENT_FLAG_RETURNED_BY_TIMER: number
declare const OBJECTIVE_CONTROL_EVENT_FLAG_SPAWNED: number
declare const OBJECTIVE_CONTROL_EVENT_FLAG_TAKEN: number
declare const OBJECTIVE_CONTROL_EVENT_FULLY_HELD: number
declare const OBJECTIVE_CONTROL_EVENT_HIDDEN: number
declare const OBJECTIVE_CONTROL_EVENT_LOST: number
declare const OBJECTIVE_CONTROL_EVENT_NONE: number
declare const OBJECTIVE_CONTROL_EVENT_RECAPTURED: number
declare const OBJECTIVE_CONTROL_EVENT_UNDER_ATTACK: number
type ObjectiveControlState = number
declare const OBJECTIVE_CONTROL_STATE_AREA_ABOVE_CONTROL_THRESHOLD: number
declare const OBJECTIVE_CONTROL_STATE_AREA_BELOW_CONTROL_THRESHOLD: number
declare const OBJECTIVE_CONTROL_STATE_AREA_INACTIVE: number
declare const OBJECTIVE_CONTROL_STATE_AREA_MAX_CONTROL: number
declare const OBJECTIVE_CONTROL_STATE_AREA_NO_CONTROL: number
declare const OBJECTIVE_CONTROL_STATE_FLAG_AT_BASE: number
declare const OBJECTIVE_CONTROL_STATE_FLAG_AT_ENEMY_BASE: number
declare const OBJECTIVE_CONTROL_STATE_FLAG_DROPPED: number
declare const OBJECTIVE_CONTROL_STATE_FLAG_HELD: number
declare const OBJECTIVE_CONTROL_STATE_POINT_CONTROLLED: number
declare const OBJECTIVE_CONTROL_STATE_POINT_TRANSITIONING: number
declare const OBJECTIVE_CONTROL_STATE_UNKNOWN: number
declare const MAX_PERKS_AVAILABLE_PER_LOADOUT: number
type Chapter = number
declare const CHAPTER_BADLANDS: number
declare const CHAPTER_BASE_GAME: number
declare const CHAPTER_CRAG: number
declare const CHAPTER_DUNE: number
declare const CHAPTER_GLACIER: number
declare const CHAPTER_MAGMA: number
declare const CHAPTER_MESA: number
declare const CHAPTER_PENINSULA: number
declare const CHAPTER_SCARP: number
declare const CHAPTER_VOLCANO: number
type CollectibleCategoryType = number
declare const COLLECTIBLE_CATEGORY_TYPE_ABILITY_FX_OVERRIDE: number
declare const COLLECTIBLE_CATEGORY_TYPE_ACCOUNT_SERVICE: number
declare const COLLECTIBLE_CATEGORY_TYPE_ACCOUNT_UPGRADE: number
declare const COLLECTIBLE_CATEGORY_TYPE_ASSISTANT: number
declare const COLLECTIBLE_CATEGORY_TYPE_BODY_MARKING: number
declare const COLLECTIBLE_CATEGORY_TYPE_CHAPTER: number
declare const COLLECTIBLE_CATEGORY_TYPE_COMBINATION_FRAGMENT: number
declare const COLLECTIBLE_CATEGORY_TYPE_COMPANION: number
declare const COLLECTIBLE_CATEGORY_TYPE_COSTUME: number
declare const COLLECTIBLE_CATEGORY_TYPE_DLC: number
declare const COLLECTIBLE_CATEGORY_TYPE_EMOTE: number
declare const COLLECTIBLE_CATEGORY_TYPE_FACIAL_ACCESSORY: number
declare const COLLECTIBLE_CATEGORY_TYPE_FACIAL_HAIR_HORNS: number
declare const COLLECTIBLE_CATEGORY_TYPE_FURNITURE: number
declare const COLLECTIBLE_CATEGORY_TYPE_HAIR: number
declare const COLLECTIBLE_CATEGORY_TYPE_HAT: number
declare const COLLECTIBLE_CATEGORY_TYPE_HEAD_MARKING: number
declare const COLLECTIBLE_CATEGORY_TYPE_HOUSE: number
declare const COLLECTIBLE_CATEGORY_TYPE_HOUSE_BANK: number
declare const COLLECTIBLE_CATEGORY_TYPE_INVALID: number
declare const COLLECTIBLE_CATEGORY_TYPE_MEMENTO: number
declare const COLLECTIBLE_CATEGORY_TYPE_MOUNT: number
declare const COLLECTIBLE_CATEGORY_TYPE_OUTFIT_STYLE: number
declare const COLLECTIBLE_CATEGORY_TYPE_PERSONALITY: number
declare const COLLECTIBLE_CATEGORY_TYPE_PIERCING_JEWELRY: number
declare const COLLECTIBLE_CATEGORY_TYPE_PLAYER_FX_OVERRIDE: number
declare const COLLECTIBLE_CATEGORY_TYPE_POLYMORPH: number
declare const COLLECTIBLE_CATEGORY_TYPE_REUSE_ME_0: number
declare const COLLECTIBLE_CATEGORY_TYPE_SKIN: number
declare const COLLECTIBLE_CATEGORY_TYPE_TRIBUTE_PATRON: number
declare const COLLECTIBLE_CATEGORY_TYPE_VANITY_PET: number
