import type { RouterApp } from "akasha/code/router-app/router-app.page-type.types.ts"

export const alanRequestsWeb = {
  id: "01a0c537-ba4f-70c8-8138-07fe3a3ea045",
  type: "page-type/router-app",
  slug: "alan-requests-web",
  definition: "the routes the Requests site serves to a browser",
  tunnelRoutes: "ts",
  rootRoute: "tsx",
  routeTable: "ts",
  serverEntry: "tsx",
  routerConfig: "ts",
  compileConfig: "json",
  viteConfig: "ts",
  server: "ts",
  sidebarBoot: "js",
  gitIgnore: "gitignore",
  routeTypesDirectory: true,
  declarationDirectory: true,
  bundleDirectory: true,
  parts: [
    "app-routes/alan-requests-web-routes",
    "module/requests-app-id",
    "module/requests-app-shell",
    "module/requests-auth-provider",
    "module/requests-handover-site",
    "module/requests-nav-command",
    "module/requests-nav-items",
    "stylesheet/alan-requests-web-look",
    "manifest/alanwalton-requests",
  ],
  toolReached: ["react-dom"],
} as const satisfies RouterApp
