import type { TemperLoreBook } from "akasha/temper/catalog/pursuit/temper-lore-collection/temper-lore-book/temper-lore-book.page-type.types.ts"

export const oneStaffManyStaves = {
  id: "01a0d5f6-6d41-733f-97ed-2829b1f3170c",
  type: "page-type/temper-lore-book",
  slug: "one-staff-many-staves",
  title: "One Staff, Many Staves",
  collection: "temper-lore-collection/skill-books",
  esoBookId: 2443,
  bookIndex: 70,
  charted: true,
  onBookshelves: true,
  mapCounts: [
    { mapId: 1, mapCount: 13 },
    { mapId: 7, mapCount: 11 },
    { mapId: 9, mapCount: 39 },
    { mapId: 10, mapCount: 19 },
    { mapId: 12, mapCount: 32 },
    { mapId: 13, mapCount: 17 },
    { mapId: 20, mapCount: 27 },
    { mapId: 22, mapCount: 10 },
    { mapId: 26, mapCount: 19 },
    { mapId: 27, mapCount: 8 },
    { mapId: 30, mapCount: 6 },
    { mapId: 61, mapCount: 15 },
    { mapId: 74, mapCount: 7 },
    { mapId: 75, mapCount: 3 },
    { mapId: 125, mapCount: 6 },
    { mapId: 143, mapCount: 19 },
    { mapId: 227, mapCount: 1 },
    { mapId: 256, mapCount: 25 },
    { mapId: 300, mapCount: 40 },
    { mapId: 1126, mapCount: 4 },
  ],
} as const satisfies TemperLoreBook
