import type { SetTemplate } from "@akasha/temper-equipment/set-template"

export const SETS_DATA_086: readonly SetTemplate[] = [
  {
    id: "seeker-synthesis",
    name: "Seeker Synthesis",
    esoSetId: 697,
    subcategoryId: "crafted",
    valid: ["*"],
    bonuses: [
      {
        count: 2,
        status: "supported",
        effects: [{ metricId: "health-maximum", effectType: "integer", effectValue: 1206 }],
        description: "Adds 1206 Maximum Health",
      },
      {
        count: 3,
        status: "supported",
        effects: [{ metricId: "magicka-maximum", effectType: "integer", effectValue: 1096 }],
        description: "Adds 1096 Maximum Magicka",
      },
      {
        count: 4,
        status: "supported",
        effects: [{ metricId: "stamina-maximum", effectType: "integer", effectValue: 1096 }],
        description: "Adds 1096 Maximum Stamina",
      },
      {
        count: 5,
        status: "unsupported",
        effects: [],
        description:
          "When you cast an ability that costs resources while in combat, you reduce your potion cooldown by 1 second. This effect can occur once every 2 seconds.",
      },
    ],
    icons: {
      "axe": "/esoui/art/icons/gear_breton_1haxe_d.dds",
      "battleaxe": "/esoui/art/icons/gear_breton_2haxe_d.dds",
      "bow": "/esoui/art/icons/gear_breton_bow_d.dds",
      "chest:heavy": "/esoui/art/icons/gear_breton_heavy_chest_d.dds",
      "chest:light": "/esoui/art/icons/gear_breton_light_robe_d.dds",
      "chest:medium": "/esoui/art/icons/gear_breton_medium_chest_d.dds",
      "dagger": "/esoui/art/icons/gear_breton_dagger_d.dds",
      "feet:heavy": "/esoui/art/icons/gear_breton_heavy_feet_d.dds",
      "feet:light": "/esoui/art/icons/gear_breton_light_feet_d.dds",
      "feet:medium": "/esoui/art/icons/gear_breton_medium_feet_d.dds",
      "greatsword": "/esoui/art/icons/gear_breton_2hsword_d.dds",
      "hands:heavy": "/esoui/art/icons/gear_breton_heavy_hands_d.dds",
      "hands:light": "/esoui/art/icons/gear_breton_light_hands_d.dds",
      "hands:medium": "/esoui/art/icons/gear_breton_medium_hands_d.dds",
      "head:heavy": "/esoui/art/icons/gear_breton_heavy_head_d.dds",
      "head:light": "/esoui/art/icons/gear_breton_light_head_d.dds",
      "head:medium": "/esoui/art/icons/gear_breton_medium_head_d.dds",
      "ice-staff": "/esoui/art/icons/gear_breton_staff_d.dds",
      "inferno-staff": "/esoui/art/icons/gear_breton_staff_d.dds",
      "legs:heavy": "/esoui/art/icons/gear_breton_heavy_legs_d.dds",
      "legs:light": "/esoui/art/icons/gear_breton_light_legs_d.dds",
      "legs:medium": "/esoui/art/icons/gear_breton_medium_legs_d.dds",
      "lightning-staff": "/esoui/art/icons/gear_breton_staff_d.dds",
      "mace": "/esoui/art/icons/gear_breton_1hhammer_d.dds",
      "maul": "/esoui/art/icons/gear_breton_2hhammer_d.dds",
      "necklace": "/esoui/art/icons/gear_breton_neck_a.dds",
      "restoration-staff": "/esoui/art/icons/gear_breton_staff_d.dds",
      "ring": "/esoui/art/icons/gear_breton_ring_a.dds",
      "shield": "/esoui/art/icons/gear_breton_shield_d.dds",
      "shoulders:heavy": "/esoui/art/icons/gear_breton_heavy_shoulders_d.dds",
      "shoulders:light": "/esoui/art/icons/gear_breton_light_shoulders_d.dds",
      "shoulders:medium": "/esoui/art/icons/gear_breton_medium_shoulders_d.dds",
      "sword": "/esoui/art/icons/gear_breton_1hsword_d.dds",
      "waist:heavy": "/esoui/art/icons/gear_breton_heavy_waist_d.dds",
      "waist:light": "/esoui/art/icons/gear_breton_light_waist_d.dds",
      "waist:medium": "/esoui/art/icons/gear_breton_medium_waist_d.dds",
    },
  },
  {
    id: "selene",
    name: "Selene",
    esoSetId: 279,
    subcategoryId: "monster",
    valid: ["monster"],
    bonuses: [
      {
        count: 1,
        status: "supported",
        effects: [{ metricId: "power", effectType: "integer", effectValue: 129 }],
        description: "Adds 129 Weapon and Spell Damage",
      },
      {
        count: 2,
        status: "unsupported",
        effects: [],
        description:
          "When you deal Martial melee damage, you call upon a primal spirit that mauls the closest enemy in front of you after 1.3 seconds for 1702 Physical damage. This effect can occur once every 6 seconds and scales off the higher of your Weapon or Spell Damage.",
      },
    ],
    icons: {},
  },
  {
    id: "sellistrix",
    name: "Sellistrix",
    esoSetId: 271,
    subcategoryId: "monster",
    valid: ["monster"],
    bonuses: [
      {
        count: 1,
        status: "supported",
        effects: [{ metricId: "stamina-maximum", effectType: "integer", effectValue: 1096 }],
        description: "Adds 1096 Maximum Stamina",
      },
      {
        count: 2,
        status: "unsupported",
        effects: [],
        description:
          "When you deal damage you create an earthquake under the enemy that erupts after 1.5 seconds, dealing 975 Physical damage to all enemies within 4 meters and stunning them for 3 seconds. This effect can occur once every 6 seconds and the damage scales off the higher of your Weapon or Spell Damage.",
      },
    ],
    icons: {
      "head:heavy": "/esoui/art/icons/gear_undauntedlamia_head_a.dds",
      "head:light": "/esoui/art/icons/gear_undauntedlamia_head_a.dds",
      "head:medium": "/esoui/art/icons/gear_undauntedlamia_head_a.dds",
      "shoulders:heavy": "/esoui/art/icons/gear_undauntedlamia_shoulders_a.dds",
      "shoulders:light": "/esoui/art/icons/gear_undauntedlamia_shoulders_a.dds",
      "shoulders:medium": "/esoui/art/icons/gear_undauntedlamia_shoulders_a.dds",
    },
  },
  {
    id: "senchal-defender",
    name: "Senchal Defender",
    esoSetId: 465,
    subcategoryId: "overland",
    valid: ["*:heavy"],
    bonuses: [
      {
        count: 2,
        status: "supported",
        effects: [{ metricId: "stamina-maximum", effectType: "integer", effectValue: 1096 }],
        description: "Adds 1096 Maximum Stamina",
      },
      {
        count: 3,
        status: "supported",
        effects: [{ metricId: "health-maximum", effectType: "integer", effectValue: 1206 }],
        description: "Adds 1206 Maximum Health",
      },
      {
        count: 4,
        status: "supported",
        effects: [{ metricId: "magicka-maximum", effectType: "integer", effectValue: 1096 }],
        description: "Adds 1096 Maximum Magicka",
      },
      {
        count: 5,
        status: "unsupported",
        effects: [],
        description:
          "Dealing direct damage with a non-Heavy Attack grants you one persistent stack of Senchal's Duty, up to 10 stacks.  After completing a fully-charged Heavy Attack, restore 757 Stamina and Magicka for each stack of Senchal's Duty and consume them.  You can only gain one stack of Senchal's Duty every 1 second.",
      },
    ],
    icons: {
      "axe": "/esoui/art/icons/gear_shieldsenchal_axe_a.dds",
      "battleaxe": "/esoui/art/icons/gear_shieldsenchal_2haxe_a.dds",
      "bow": "/esoui/art/icons/gear_shieldsenchal_bow_a.dds",
      "chest:*": "/esoui/art/icons/gear_imperial_heavy_chest_d.dds",
      "dagger": "/esoui/art/icons/gear_shieldsenchal_dagger_a.dds",
      "feet:*": "/esoui/art/icons/gear_shieldssenchalhvy_feet_a.dds",
      "greatsword": "/esoui/art/icons/gear_shieldsenchal_2hsword_a.dds",
      "hands:*": "/esoui/art/icons/gear_shieldssenchalhvy_hands_a.dds",
      "head:*": "/esoui/art/icons/gear_shieldssenchalhvy_head_a.dds",
      "ice-staff": "/esoui/art/icons/gear_shieldsenchal_staff_a.dds",
      "inferno-staff": "/esoui/art/icons/gear_shieldsenchal_staff_a.dds",
      "legs:*": "/esoui/art/icons/gear_shieldssenchalhvy_legs_a.dds",
      "lightning-staff": "/esoui/art/icons/gear_shieldsenchal_staff_a.dds",
      "mace": "/esoui/art/icons/gear_shieldsenchal_hammer_a.dds",
      "maul": "/esoui/art/icons/gear_shieldsenchal_2hhammer_a.dds",
      "necklace": "/esoui/art/icons/gear_breton_neck_a.dds",
      "restoration-staff": "/esoui/art/icons/gear_shieldsenchal_staff_a.dds",
      "ring": "/esoui/art/icons/gear_breton_ring_a.dds",
      "shield": "/esoui/art/icons/gear_shieldsenchal_shield_a.dds",
      "shoulders:*": "/esoui/art/icons/gear_shieldssenchalhvy_shoulders_a.dds",
      "sword": "/esoui/art/icons/gear_shieldsenchal_sword_a.dds",
      "waist:*": "/esoui/art/icons/gear_shieldssenchalhvy_waist_a.dds",
    },
  },
  {
    id: "senche-rahts-grit",
    name: "Senche-raht's Grit",
    esoSetId: 438,
    subcategoryId: "crafted",
    valid: ["*"],
    bonuses: [
      {
        count: 2,
        status: "supported",
        effects: [
          { metricId: "healing-done-base", effectType: "fractional-change", effectValue: 0.04 },
        ],
        description: "Adds 4% Healing Done",
      },
      {
        count: 3,
        status: "supported",
        effects: [{ metricId: "health-maximum", effectType: "integer", effectValue: 1206 }],
        description: "Adds 1206 Maximum Health",
      },
      {
        count: 4,
        status: "supported",
        effects: [
          { metricId: "healing-taken-base", effectType: "fractional-change", effectValue: 0.04 },
        ],
        description: "Adds 4% Healing Taken",
      },
      {
        count: 5,
        status: "unsupported",
        effects: [],
        description:
          "After being damaged by a damage over time ability, increase your Healing Received by 6% and your Physical and Spell Resistance by 2585 for 3 seconds.",
      },
    ],
    icons: {
      "axe": "/esoui/art/icons/gear_breton_1haxe_d.dds",
      "battleaxe": "/esoui/art/icons/gear_breton_2haxe_d.dds",
      "bow": "/esoui/art/icons/gear_breton_bow_d.dds",
      "chest:heavy": "/esoui/art/icons/gear_breton_heavy_chest_d.dds",
      "chest:light": "/esoui/art/icons/gear_breton_light_robe_d.dds",
      "chest:medium": "/esoui/art/icons/gear_breton_medium_chest_d.dds",
      "dagger": "/esoui/art/icons/gear_breton_dagger_d.dds",
      "feet:heavy": "/esoui/art/icons/gear_breton_heavy_feet_d.dds",
      "feet:light": "/esoui/art/icons/gear_breton_light_feet_d.dds",
      "feet:medium": "/esoui/art/icons/gear_breton_medium_feet_d.dds",
      "greatsword": "/esoui/art/icons/gear_breton_2hsword_d.dds",
      "hands:heavy": "/esoui/art/icons/gear_breton_heavy_hands_d.dds",
      "hands:light": "/esoui/art/icons/gear_breton_light_hands_d.dds",
      "hands:medium": "/esoui/art/icons/gear_breton_medium_hands_d.dds",
      "head:heavy": "/esoui/art/icons/gear_breton_heavy_head_d.dds",
      "head:light": "/esoui/art/icons/gear_breton_light_head_d.dds",
      "head:medium": "/esoui/art/icons/gear_breton_medium_head_d.dds",
      "ice-staff": "/esoui/art/icons/gear_breton_staff_d.dds",
      "inferno-staff": "/esoui/art/icons/gear_breton_staff_d.dds",
      "legs:heavy": "/esoui/art/icons/gear_breton_heavy_legs_d.dds",
      "legs:light": "/esoui/art/icons/gear_breton_light_legs_d.dds",
      "legs:medium": "/esoui/art/icons/gear_breton_medium_legs_d.dds",
      "lightning-staff": "/esoui/art/icons/gear_breton_staff_d.dds",
      "mace": "/esoui/art/icons/gear_breton_1hhammer_d.dds",
      "maul": "/esoui/art/icons/gear_breton_2hhammer_d.dds",
      "necklace": "/esoui/art/icons/gear_breton_neck_a.dds",
      "restoration-staff": "/esoui/art/icons/gear_breton_staff_d.dds",
      "ring": "/esoui/art/icons/gear_breton_ring_a.dds",
      "shield": "/esoui/art/icons/gear_breton_shield_d.dds",
      "shoulders:heavy": "/esoui/art/icons/gear_breton_heavy_shoulders_d.dds",
      "shoulders:light": "/esoui/art/icons/gear_breton_light_shoulders_d.dds",
      "shoulders:medium": "/esoui/art/icons/gear_breton_medium_shoulders_d.dds",
      "sword": "/esoui/art/icons/gear_breton_1hsword_d.dds",
      "waist:heavy": "/esoui/art/icons/gear_breton_heavy_waist_d.dds",
      "waist:light": "/esoui/art/icons/gear_breton_light_waist_d.dds",
      "waist:medium": "/esoui/art/icons/gear_breton_medium_waist_d.dds",
    },
  },
]
