apiVersion: v1
kind: Secret
metadata:
    name: subnet-router-auth
    namespace: headscale
    labels:
        app.kubernetes.io/name: tailscale-subnet-router
        app.kubernetes.io/instance: subnet-router
        app.kubernetes.io/component: data-plane
        app.kubernetes.io/part-of: headscale
        app.kubernetes.io/managed-by: deploy-script
type: Opaque
stringData:
    TS_AUTHKEY: ENC[AES256_GCM,data:mw85Ao5IENUXOd0jrnALv0UQjdz/cM+FHXY0QU5h2J8EKgLPZMAV+HimHE2U5ca+FzwfbCb0nk6+5tDje/aIe0m85tFOVaRHx1fQXZewrdSbZHEmYjjAuA==,iv:WASovNkg93U6A2o6we3591pmllL7T96sOO8NQtZelc8=,tag:wqghryEvKLKlaY9r/iSP+g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByTExXSVNuYVhmUDM3MnBB
            UFI2K3YxRWtNWTdTMFRIU01aVHpJeGhhS3g4ClN1U0g3UnhOYXFCOTVPME9BRnZp
            YllIMEZqV05DM3o2d0J5WVd3a2ZiN0kKLS0tIG5UUFNQbHRCZzRXT3BxMzMwb2Yw
            cDkvM0xybEw2TWtFNnkyOFlOM2NUU1kKVVcKifKrNfIjC0Wfq3M+Z3KmT+ae7+bM
            Me2j84gbwg24i+PJqWYqUngOjO/bMGF1Tp+4+BBHV0Gf/jSjs8IGQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T12:32:13Z"
    mac: ENC[AES256_GCM,data:kvAL5Ae5wuFDMvhQ2AMRy7R8vDq5vhNgFT2PHmw/GgBtDwjP6Ikq6MgAubyIGQ/4lyHpOnRgyHEsmnOFK34MOwBHrJU+hXMO+WRP+v1aW6bPvoMx4dak26wCwKpKWqptMZdpUU03Cf2WTcN3ebnYxVLttQFrIypQmTfbs/OpO+I=,iv:sO8UOYN0Bfc2oeygNAH4iCojfDQPcZ8rDj4oBZdaOsM=,tag:YYOFPm/L8mjU9pZyWcNSBw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
