import type { StoryTurnPlayed } from "akasha/story/world/stories/played/turns/story-turn-played.page-type.types.ts"

export const otherwhereTheLibrary00071 = {
  id: "01a0e948-cd15-78cb-b953-8e9dc8bc0d1f",
  type: "page-type/story-turn-played",
  slug: "otherwhere-the-library-00-071",
  cover: "image/image-7de060c86d9588e0",
  ownLength: 382,
  unit: "unit/words",
  partOfCollections: ["story-played/otherwhere-i"],
  position: 71,
  prose: "txt",
  characters: ["character-player/otherwhere-i-alan", "character-other/otherwhere-i-links"],
  stepStatus: "step-status/player",
  action:
    "**No book that will let me cast a spell to read a book? I'm a speed reader (4000 WPM), so I can read fast, but I'm sure magic could make that faster.** I got and collect the two books and sit down to read them.",
  beats: [
    "Nala asks Links: no book with a spell to read faster? She reads four thousand words a minute.",
    "Links: no book shelved in the lit rooms teaches faster reading.",
    "Links: a plain book like Courtesies reads at the reader's own pace, so her speed serves her there.",
    "Links: a working text's power unfolds only as it is understood; no reader, however fast, hurries it.",
    "Nala takes Counter Keeping down from its low shelf near the Counter.",
    "She rolls a ladder along its brass rail to the west gallery and climbs.",
    "High on the west gallery she finds Courtesies of the Many Peoples and carries it down.",
    "She sits on the step of the Counter's platform with both books, and opens Courtesies first.",
    "At her pace its first part, on the commonest peoples, takes a quarter hour.",
    "Elves give a stranger their house's name before their own, and hear a bare name as cold.",
    "Satyrs take a refused offer of food as a slight, and a shared meal as friendship begun.",
    "The Bectiwode are beetle-like, the size of a Great Dane, and chitter as they speak.",
    "The Bectiwode hear a low chitter back as warmth, and a silent answer as coldness.",
    "The Aracnio greet with a dip of the forelegs; a hand thrust out to shake startles them.",
    "She reads on through the rest of Courtesies; the whole takes her some two hours.",
    "She opens Counter Keeping, a working text of the Library's own magic, dense and exact.",
    "For some three hours she works through it page by page, as she did Shelf Sight.",
    "She follows every word, but the power in it never unfolds; nothing settles behind her eyes.",
    "She reaches the last page, and no window opens.",
    "Links: it hasn't taken. It won't, until she has learned something new.",
    "Links: another power, from another book; then Counter Keeping may give way to her.",
    "Links: until then, the Counter lends no book.",
  ],
  issues: [
    '"It hasn\'t taken" - Links set Counter Keeping to read now; grasped whole, a book grants its power',
  ],
  lore: [
    "lore/otherwhere-the-library-universe",
    "lore/otherwhere-the-library-peoples",
    "lore/otherwhere-the-library-alan",
    "place/otherwhere-the-library-main-hall",
  ],
  reviewedBy: ["story-reviewer/style", "story-reviewer/continuity"],
  recordedBy: ["story-recorder/mechanics", "story-recorder/memory", "story-recorder/picture"],
  endsAt: "2026-09-29T11:52:00.000Z",
} as const satisfies StoryTurnPlayed
