import type { EsoAddon } from "@akasha/code-system/eso-addon"

export const temperCraftingAddon = {
  id: "01a061c7-e8c6-7757-820f-c90f8d327b2e",
  pageTypeSlug: "eso-addon",
  slug: "temper-crafting-addon",
  definition: "the add-on that answers what a character can craft, learn and study",
  manifest: "json",
  addonManifest: "json",
  bindings: "xml",
  bundleEntrySlug: "crafting-entry",
  partSlugs: [
    "module/craft-account-init",
    "module/craft-blueprint-furnisher",
    "module/craft-char-init",
    "module/craft-char-meta",
    "module/craft-character-panel",
    "module/craft-character-panel-init",
    "module/craft-characters",
    "module/craft-cook",
    "module/craft-cooking",
    "module/craft-crafting",
    "module/craft-flask",
    "module/craft-furnisher",
    "module/craft-furnisher-early",
    "module/craft-furnisher-late",
    "module/craft-furnisher-middle",
    "module/craft-icons",
    "module/craft-inventory",
    "module/craft-item-mark",
    "module/craft-item-types",
    "module/craft-knowledge",
    "module/craft-lang-br",
    "module/craft-lang-de",
    "module/craft-lang-en",
    "module/craft-lang-es",
    "module/craft-lang-fr",
    "module/craft-lang-index",
    "module/craft-lang-it",
    "module/craft-lang-lang-table",
    "module/craft-lang-ru",
    "module/craft-lang-shared",
    "module/craft-lang-zh",
    "module/craft-libraries",
    "module/craft-mig-jewelry-swap",
    "module/craft-mig-storage-prune",
    "module/craft-mig-studies-shape",
    "module/craft-options",
    "module/craft-panel-init",
    "module/craft-player-state",
    "module/craft-quality",
    "module/craft-quest-tracking",
    "module/craft-recipe-cooking",
    "module/craft-research",
    "module/craft-research-grid",
    "module/craft-research-tracking",
    "module/craft-rune",
    "module/craft-rune-crafting",
    "module/craft-rune-refining",
    "module/craft-rune-selection",
    "module/craft-set-lam",
    "module/craft-set-updates",
    "module/craft-sets-data",
    "module/craft-sets-data-tiers-2-5",
    "module/craft-sets-data-tiers-6-9",
    "module/craft-storage-counts",
    "module/craft-storage-prune",
    "module/craft-style-tracking",
    "module/craft-styles",
    "module/craft-styles-data",
    "module/craft-styles-data-tables",
    "module/craft-tooltip-handler",
    "module/craft-tooltips",
    "module/craft-ui-updates",
    "module/craft-utilities",
    "module/craft-validation",
    "module/craft-xml-handlers",
    "module/crafting-constants",
    "module/crafting-entry",
    "module/crafting-events",
    "module/crafting-events-handlers",
    "module/crafting-events-inventory",
    "module/crafting-helpers",
    "module/crafting-public-api",
    "module/crafting-slot-handler-stats",
    "module/crafting-state",
    "module/potion-casts",
    "module/potion-constants",
    "module/potion-controls",
    "module/potion-controls-helpers",
    "module/potion-controls-layout",
    "module/potion-events",
    "module/potion-ingredient",
    "module/potion-init",
    "module/potion-inventory",
    "module/potion-job-search",
    "module/potion-keybind-helpers",
    "module/potion-keybinds",
    "module/potion-main-menu",
    "module/potion-potion",
    "module/potion-potion-craft",
    "module/potion-public-api",
    "module/potion-reagent-data",
    "module/potion-reagents",
    "module/potion-refresh-traits",
    "module/potion-render-page",
    "module/potion-result-controls",
    "module/potion-saved-variables",
    "module/potion-search",
    "module/potion-settings-menu",
    "module/potion-state",
    "module/potion-tooltip-helpers",
    "module/potion-tooltips",
    "module/potion-types",
    "module/potion-ui-strings",
    "module/potion-window-helpers",
    "module/potion-windows",
    "module/rune-favorites",
    "module/rune-furniture-recipes",
    "module/rune-glyph-creation",
    "module/rune-glyph-refining",
    "module/rune-mode",
    "module/rune-panel",
    "module/rune-search",
    "module/rune-writs",
    "module/writ-alchemy-data",
    "module/writ-alchemy-parser",
    "module/writ-constants",
    "module/writ-enchanting-parser",
    "module/writ-i18n",
    "module/writ-i18n-client-si",
    "module/writ-i18n-fooddrink",
    "module/writ-i18n-gear",
    "module/writ-i18n-mat",
    "module/writ-i18n-motif",
    "module/writ-i18n-set",
    "module/writ-init",
    "module/writ-know",
    "module/writ-link-data",
    "module/writ-link-data-table",
    "module/writ-link-data-table-early",
    "module/writ-link-data-table-late",
    "module/writ-log",
    "module/writ-mark-analysis",
    "module/writ-mark-casts",
    "module/writ-mark-constants",
    "module/writ-mark-init",
    "module/writ-mark-inventory-tweaks",
    "module/writ-mark-markers",
    "module/writ-mark-safe-tab-filter",
    "module/writ-mark-saved-variables",
    "module/writ-mark-settings",
    "module/writ-mat-row",
    "module/writ-parser-dispatch",
    "module/writ-price",
    "module/writ-price-data-table",
    "module/writ-profiler",
    "module/writ-prov-data",
    "module/writ-prov-parser",
    "module/writ-prov-recipe-map",
    "module/writ-prov-recipe-map-1",
    "module/writ-prov-recipe-map-2",
    "module/writ-public-api",
    "module/writ-required-skill",
    "module/writ-saved-variables",
    "module/writ-settings-window",
    "module/writ-slash-commands",
    "module/writ-smith-parser",
    "module/writ-smith-parser-ops",
    "module/writ-smith-parser-types",
    "module/writ-smith-request-items",
    "module/writ-smith-schema",
    "module/writ-smith-schema-data",
    "module/writ-smith-schema-types",
    "module/writ-smithing",
    "module/writ-tooltip",
    "module/writ-tooltip-text",
    "module/writ-types",
    "module/writ-ui-strings-shorten",
    "module/writ-ui-strings-static",
    "module/writ-util",
    "module/writ-writ-fields",
    "type-declaration/craft-decl-controls",
    "type-declaration/potion-decl-controls",
    "type-declaration/writ-mark-decl-writ-worthy",
    "type-declaration/writ-writworthy-global",
    "eso-interface/craft-store-blueprint-layout",
    "eso-interface/craft-store-cook-layout",
    "eso-interface/craft-store-fonts",
    "eso-interface/craft-store-layout",
    "eso-interface/craft-store-recipe-layout",
    "eso-interface/craft-store-rune-layout",
    "eso-interface/craft-store-style-layout",
    "eso-interface/potion-maker-layout",
  ],
  interfaceSlugs: [
    "craft-store-blueprint-layout",
    "craft-store-cook-layout",
    "craft-store-fonts",
    "craft-store-layout",
    "craft-store-recipe-layout",
    "craft-store-rune-layout",
    "craft-store-style-layout",
    "potion-maker-layout",
  ],
  invariants: [
    {
      invariantKind: "departure",
      statement: "One add-on holds the crafting stations rather than one add-on for each station.",
    },
    {
      invariantKind: "departure",
      statement:
        "The potion window and the writ tracker are folded in here rather than shipped apart.",
    },
    {
      invariantKind: "departure",
      statement: "What a character knows is asked of LibCharacterKnowledge.",
    },
    {
      invariantKind: "departure",
      statement: "The font document loads before the Lua bundle.",
    },
    {
      invariantKind: "departure",
      statement: "Every other markup document loads after the Lua bundle.",
    },
    {
      invariantKind: "constraint",
      statement: "Nothing here reaches a Date.",
    },
  ],
} as const satisfies EsoAddon
