import type { StoryTurnPlayed } from "akasha/story/world/stories/played/turns/story-turn-played.page-type.types.ts"

export const otherwhereVii00009 = {
  id: "01a0eaa6-ece0-7a0e-a49b-7830f575e608",
  type: "page-type/story-turn-played",
  slug: "otherwhere-vii-00-009",
  ownLength: 300,
  unit: "unit/words",
  partOfCollections: ["story-played/otherwhere-vii"],
  position: 9,
  prose: "txt",
  characters: [
    "character-player/otherwhere-vii-nala",
    "character-other/otherwhere-vii-aldo-reeve",
    "character-other/otherwhere-vii-gammer-wyn",
    "character-other/otherwhere-vii-tamsin",
  ],
  stepStatus: "step-status/recorders",
  action:
    "\"Oh. Oh dear. I'm afraid the steward has been cheating you then. For a 10% tithe, he should have taken only seven and a little less than half, not nine. He's taken more than one and a half more than he should have.\"",
  beats: [
    "Nala tells Aldo plainly the steward has cheated him: nine taken where a tenth was seven and a half.",
    "The colour goes out of Aldo's face. He takes the stick back from her hands and says nothing.",
    "Behind him the flails keep on, thud, thud, and one of the men glances over.",
    '"I said it!" Wyn slaps her knee. "Crooked scale. Said it these ten years, and none of you heard."',
    '"Wyn." Aldo says it low, and she shuts her mouth. He looks at Tamsin. "And you. Not a word."',
    "Tamsin looks from him to Nala, her eyes bright, her lips pressed tight on it for now.",
    '"He said our sacks weighed light," Aldo says at last. "His scale said so. Nine made the tenth."',
    '"I made my mark under it." He turns the stick over. "What was I to say, with his mage stood by him?"',
    "He is quiet a long moment. His thumb runs along the crossed notches, one by one.",
    "\"Last year's gone. I'll not go shouting at the mountain's man over a sack and a half.\"",
    '"But he comes again in six days, with his scale and his book." He looks at Nala.',
    '"I\'d sooner have someone by me this time who can read his book and reckon his tenth."',
    '"Stay through the weighing. Bed and board, and ten pennies a day. Joan\'ll say where you sleep."',
    '"No more baskets." He holds the stick out to her again. "Keep your mouth shut, and keep my count."',
  ],
  issues: ['"He stands with the stick in his fist" - Nala holds the stick at the end of turn 8'],
  lore: ["lore/otherwhere-vii-aldo-reeve"],
  reviewedBy: ["story-reviewer/style", "story-reviewer/continuity"],
  recordedBy: ["story-recorder/mechanics"],
  endsAt: "2026-09-28T08:22:00.000Z",
} as const satisfies StoryTurnPlayed
