import type { StoryTurnPlayed } from "akasha/story/world/stories/played/turns/story-turn-played.page-type.types.ts"

export const otherwhereVii00008 = {
  id: "01a0ea98-0c71-7899-a76b-c449911ef597",
  type: "page-type/story-turn-played",
  slug: "otherwhere-vii-00-008",
  cover: "image/image-6e049f24e5022d79",
  ownLength: 289,
  unit: "unit/words",
  partOfCollections: ["story-played/otherwhere-vii"],
  position: 8,
  prose: "txt",
  characters: [
    "character-player/otherwhere-vii-nala",
    "character-other/otherwhere-vii-aldo-reeve",
    "character-other/otherwhere-vii-gammer-wyn",
    "character-other/otherwhere-vii-tamsin",
  ],
  stepStatus: "step-status/recorders",
  action:
    "\"Oh! I've seen these, but only in museums. The stick is split so two people can each hold a half, and neither can change it without the marks no longer matching, right? I'm not completely sure what the marks mean on their own, but at a guess, I'd say that's 74, 7 tens for the deep notches and 4 ones for the shallow, and that the nine crossed through are contracts complete?\"",
  beats: [
    "Nala turns the stick over in her hands and says it all aloud, museums and all.",
    'At "museums" Aldo\'s brow creases. Wyn mouths the word to herself, and Tamsin frowns at it.',
    "Aldo lets the word go by. He is watching the stick in her hands.",
    "When she says the stick is split so each side holds a half, Aldo goes very still.",
    '"Steward has the other half," he says slowly. "We notch \'em together, both at once."',
    "When she says seventy-four, he lets out a long breath through his nose.",
    "He looks at the stick, then at her, as if the stick had spoken.",
    '"Seventy-four," Wyn says. "Hark at that. Took the miller a week of Sundays."',
    '"Not contracts, though." Aldo taps the thin end with a thick finger, the crossed notches.',
    "\"Them's the steward's. The mountain's tenth. A sack a notch, carted off, crossed on both halves.\"",
    "Nala looks at the nine crossed notches, and the sum does itself in her head.",
    "A tenth of seventy-four is seven, and a bit over: seven and a half sacks, no more.",
    "The steward took nine. A sack and a half more than a tenth, carted off last year.",
  ],
  issues: [
    '"Aldo\'s eyes are still on your face, the stick between you." - No Prompt',
    '"Aldo\'s eyes are still on your face, the stick between you." - Leave It Open',
    '"the straw stops moving" - Aldo took the straw out in turn 7 and never put it back',
  ],
  lore: ["lore/otherwhere-vii-aldo-reeve"],
  reviewedBy: ["story-reviewer/style", "story-reviewer/continuity"],
  recordedBy: ["story-recorder/picture", "story-recorder/memory"],
  endsAt: "2026-09-28T08:18:00.000Z",
} as const satisfies StoryTurnPlayed
