import "../histoire-startup/histoire-startup.module.code.ts"
import "../histoire-dialogs/histoire-dialogs.module.code.ts"
import "../histoire-settings/histoire-settings.module.code.ts"
import "../histoire-performance-tracker/histoire-performance-tracker.module.code.ts"
import "../histoire-cache-status-bar/histoire-cache-status-bar.module.code.ts"
import "../histoire-quick-navigation/histoire-quick-navigation.module.code.ts"
import "../histoire-compatibility/histoire-compatibility.module.code.ts"
import "../histoire-legacy-category-lookup/histoire-legacy-category-lookup.module.code.ts"
import "../histoire-adapter/histoire-adapter.module.code.ts"
import "../histoire-adapter-gap-rows/histoire-adapter-gap-rows.module.code.ts"
import "../histoire-status-tooltip/histoire-status-tooltip.module.code.ts"
import "../histoire-status-selection-widget/histoire-status-selection-widget.module.code.ts"
import "../histoire-status-linked-icon/histoire-status-linked-icon.module.code.ts"
import "../histoire-status-window/histoire-status-window.module.code.ts"
import "../histoire-status-window-rows/histoire-status-window-rows.module.code.ts"
import "../histoire-status-window-debug/histoire-status-window-debug.module.code.ts"
import "../histoire-category/histoire-category.module.code.ts"
import "../histoire-category-types/histoire-category-types.module.code.ts"
import "../histoire-category-requests/histoire-category-requests.module.code.ts"
import "../histoire-category-processing/histoire-category-processing.module.code.ts"
import "../histoire-category-ranges/histoire-category-ranges.module.code.ts"
import "../histoire-category-search/histoire-category-search.module.code.ts"
import "../histoire-cache-guild/histoire-cache-guild.module.code.ts"
import "../histoire-cache/histoire-cache.module.code.ts"
import "../histoire-processing-request/histoire-processing-request.module.code.ts"
import "../histoire-event-processor/histoire-event-processor.module.code.ts"
import "../histoire-event-processor-iteration/histoire-event-processor-iteration.module.code.ts"
import "../histoire-legacy-event-listener/histoire-legacy-event-listener.module.code.ts"
import "../histoire-legacy-event-listener-api/histoire-legacy-event-listener-api.module.code.ts"
import "../histoire-server-request/histoire-server-request.module.code.ts"
import "../histoire-server-request-manager/histoire-server-request-manager.module.code.ts"
import "../histoire-api/histoire-api.module.code.ts"

import { internal } from "../histoire-state/histoire-state.module.code.ts"

internal.Initialize()
