import type { TemperSet } from "akasha/temper/catalog/gear/temper-set/temper-set.page-type.types.ts"

export const nikulasHeavyArmor = {
  id: "019e66e6-a0a7-7a85-989a-f4784908d789",
  type: "page-type/temper-set",
  slug: "nikulas-heavy-armor",
  title: "Nikulas' Heavy Armor",
  key: "nikulas-heavy-armor",
  esoSetId: 72,
  setWayshrines: [187, 187, 187],
  setTypeId: 6,
  setNameZh: "尼古拉斯的重甲",
  setNameRu: "Тяжелые доспехи Никуласа",
  setNameFr: "L’Armure lourde de Nikulas",
  setNameEs: "Armadura pesada de Nikulas",
  setNameDe: "Nikulas' schwere Rüstung",
  setDropZones: [64, 103, 103],
  setDropMechanics: [28],
  setDlcId: 0,
  itemBrowserSources: ["64"],
  itemBrowserPlaceKinds: [3],
  itemBrowserItemId: 110058,
  esoItemIds: [
    85269, 85270, 85271, 85272, 85273, 85274, 85275, 85276, 85277, 85278, 85279, 85280, 85281,
    85282, 85283, 85284, 85285, 85286, 85287, 85288, 85289, 85290,
  ],
  esoArmorTypes: ["ARMORTYPE_HEAVY"],
  esoEquipTypes: [
    "EQUIP_TYPE_CHEST",
    "EQUIP_TYPE_FEET",
    "EQUIP_TYPE_HAND",
    "EQUIP_TYPE_HEAD",
    "EQUIP_TYPE_LEGS",
    "EQUIP_TYPE_NECK",
    "EQUIP_TYPE_OFF_HAND",
    "EQUIP_TYPE_ONE_HAND",
    "EQUIP_TYPE_RING",
    "EQUIP_TYPE_SHOULDERS",
    "EQUIP_TYPE_TWO_HAND",
    "EQUIP_TYPE_WAIST",
  ],
  esoWeaponTypes: [
    "WEAPONTYPE_AXE",
    "WEAPONTYPE_BOW",
    "WEAPONTYPE_DAGGER",
    "WEAPONTYPE_FIRE_STAFF",
    "WEAPONTYPE_FROST_STAFF",
    "WEAPONTYPE_HAMMER",
    "WEAPONTYPE_HEALING_STAFF",
    "WEAPONTYPE_LIGHTNING_STAFF",
    "WEAPONTYPE_SHIELD",
    "WEAPONTYPE_SWORD",
    "WEAPONTYPE_TWO_HANDED_AXE",
    "WEAPONTYPE_TWO_HANDED_HAMMER",
    "WEAPONTYPE_TWO_HANDED_SWORD",
  ],
  category: "temper-set-category/dungeon",
  valid: ["*:heavy"],
  bonuses: "jsonl",
  icons: "jsonl",
} as const satisfies TemperSet
