import type { Domain } from "../../../domains/domain.page-type.ts"

export const trackDaily = {
  id: "01a062dc-1b7f-7c99-a886-e67035171fdf",
  pageTypeSlug: "domain",
  slug: "track-daily",
  definition: "what is measured about Alan a day at a time",
  partSlugs: [
    "page-type/email-entry",
    "page-type/eso-day",
    "page-type/wake-day",
    "module/day-narrow-types",
    "module/day-place",
    "module/day-reading",
    "module/day-entry-keys",
    "module/day-stretches",
    "module/day-completions",
    "module/track-shape",
    "module/akasha-day",
    "module/track-pages",
    "module/track-resolve",
    "module/track-format",
    "module/mountain-times",
    "module/day-scan-window",
    "module/air-quality",
    "module/air-quality-fetch",
    "module/persona-recipe-rows",
    "module/session-points-compute",
    "module/session-points-totals",
    "module/points-source-writer",
    "module/health-total-population",
    "module/write-daily-points",
    "module/day-active-calories",
    "module/nutrition-grams",
    "module/nutrition-points",
    "module/task-completions",
    "module/task-points",
    "module/topic-words",
    "workstation-service/topic-words-service",
    "workstation-service/active-calories-service",
    "module/day-opening",
  ],
  invariants: [
    {
      invariantKind: "departure",
      statement: "A wake day is the day Alan lives and an ESO day is the day Alan plays.",
    },
    {
      invariantKind: "departure",
      statement: "The page tracked is a day and the page type says which kind of day.",
    },
  ],
} as const satisfies Domain
