import type { TemperSet } from "akasha/temper/catalog/gear/temper-set/temper-set.page-type.types.ts"

export const shalkExoskeleton = {
  id: "019e66e7-6a89-77c5-a272-6b270c3899b5",
  type: "page-type/temper-set",
  slug: "shalk-exoskeleton",
  title: "Shalk Exoskeleton",
  key: "shalk-exoskeleton",
  esoSetId: 291,
  hashPlace: 514,
  esoItemIds: [
    96587, 96588, 96589, 96590, 96591, 96592, 96593, 96594, 96595, 96596, 96597, 96598, 96599,
    96600, 96601, 96602, 96603, 96604, 96605, 96606, 96607, 96608,
  ],
  esoArmorTypes: ["ARMORTYPE_HEAVY"],
  esoEquipTypes: [
    "EQUIP_TYPE_CHEST",
    "EQUIP_TYPE_FEET",
    "EQUIP_TYPE_HAND",
    "EQUIP_TYPE_HEAD",
    "EQUIP_TYPE_LEGS",
    "EQUIP_TYPE_NECK",
    "EQUIP_TYPE_OFF_HAND",
    "EQUIP_TYPE_ONE_HAND",
    "EQUIP_TYPE_RING",
    "EQUIP_TYPE_SHOULDERS",
    "EQUIP_TYPE_TWO_HAND",
    "EQUIP_TYPE_WAIST",
  ],
  esoWeaponTypes: [
    "WEAPONTYPE_AXE",
    "WEAPONTYPE_BOW",
    "WEAPONTYPE_DAGGER",
    "WEAPONTYPE_FIRE_STAFF",
    "WEAPONTYPE_FROST_STAFF",
    "WEAPONTYPE_HAMMER",
    "WEAPONTYPE_HEALING_STAFF",
    "WEAPONTYPE_LIGHTNING_STAFF",
    "WEAPONTYPE_SHIELD",
    "WEAPONTYPE_SWORD",
    "WEAPONTYPE_TWO_HANDED_AXE",
    "WEAPONTYPE_TWO_HANDED_HAMMER",
    "WEAPONTYPE_TWO_HANDED_SWORD",
  ],
  setWayshrines: [65, 65, 65],
  setTypeId: 9,
  setNameZh: "沙克虫外骨骼",
  setNameRu: "Экзоскелет шалка",
  setNameFr: "Exosquelette de shalk",
  setNameEs: "Exoesqueleto de shalk",
  setNameDe: "Schröterpanzer",
  setDropZones: [41, 41, 216, 41, 41],
  setDropMechanics: [7, 8, 9, 10, 25],
  setDlcId: 0,
  itemBrowserSources: ["41"],
  itemBrowserItemId: 96622,
  category: "temper-set-category/overland",
  valid: ["*:heavy"],
  bonuses: "jsonl",
  icons: "jsonl",
} as const satisfies TemperSet
