import type { Message } from "akasha/agent/messaging/message/message.page-type.types.ts"

export const message928d0346c78a = {
  id: "01a0a317-3e15-7000-8c33-928d0346c78a",
  type: "message",
  slug: "message-928d0346c78a",
  to: "seat/thea",
  from: "audit-running",
  warrant: "announce",
  body: "the audit at 43187f996d1f00dc06a3921923e9486e6cfadf6a found 3 checks newly refusing and 1 check nothing measured.\n`folder-matches-a-shape` refused 166 times:\n  agent/model/family/pages — this folder matches no folder shape — as a-claimed-folder, no page above it claims this folder; as a-domain-with-its-parts, it holds 4 pages rather than one: fable.model-family.ts, haiku.model-family.ts, opus.mode... (1127 characters more)\n  agent/model/test/outcome/pages — this folder matches no folder shape — as a-claimed-folder, no page above it claims this folder; as a-domain-with-its-parts, it holds 5 pages rather than one: negative-false.model-test-outcome.ts, negative-tr... (1518 characters more)\n  agent/role/pages — this folder matches no folder shape — as a-claimed-folder, no page above it claims this folder; as a-domain-with-its-parts, it holds 11 pages rather than one: coach.role.ts, companion.role.ts, definer.role.ts, game-master... (1566 characters more)\n  agent/seat/log-source/pages — this folder matches no folder shape — as a-claimed-folder, no page above it claims this folder; as a-domain-with-its-parts, it holds 3 pages rather than one: oauth-proxy-console.log-source.ts, supervisor-consol... (1152 characters more)\n  agent/seat/supervisor/supervisor-action/pages — this folder matches no folder shape — as a-claimed-folder, no page above it claims this folder; as a-domain-with-its-parts, it holds 3 pages rather than one: restart-now.supervisor-action.ts, ... (1171 characters more)\n`index-is-level-with-the-pages` refused 19 times:\n  seat/pages/alan/alan.seat.referenced-by — the index entry for this file is named by a page and missing from the index\n  argument/properties/said.text-property.referenced-by — the index entry for this file is named by a page and missing from the index\n  argument/properties/takes.text-property.referenced-by — the index entry for this file is named by a page and missing from the index\n  agent/messaging/message/message.page-type.types.ts — the index entry for this file is in the index differing from what its page says\n  messaging/message/message.page-type.referenced-by — the index entry for this file is in the index differing from what its page says\n`tests-pass` refused 1 time:\n  change/mechanical/file/rename/rename-file-page/rename-file-page.change-mechanical.test.ts — Measured between 2026-09-15T03:14:46.526Z and 2026-09-15T03:22:34.929Z. 3 test files failed: (10777 lines more)\n`lint-clean` went unmeasured:\n  agent/agent.page-type.ts — the linter could not read alan/track/daily/day/properties/metric.text-property.ts, alan/track/daily/day/properties/metric.text-property.types.ts, alan/track/daily/day/properties/played-at.instant-property.ts, alan... (254 characters more)\n/var/home/walton/.local/state/workstation-services/audit-verdicts.json holds what each of them answered, whole.\n",
} as const satisfies Message
