import type { WorkspacePackage } from "@akasha/code-system/workspace-package"

export const serviceSystem = {
  id: "01a05a3c-cafd-7ded-8901-f1468940d7ca",
  pageTypeSlug: "workspace-package",
  slug: "service-system",
  definition: "what the system runs without being asked each time",
  manifest: "json",
  partSlugs: [
    "module/tick-sleeping",
    "page-type/service",
    "page-type/workstation-service",
    "page-type/cluster-service",
    "page-type/vendored-workload",
    "page-type/web-app",
    "page-type/secret",
    "module/unit-writing",
    "module/service-reaching",
    "module/file-following",
    "module/service-wrapping",
    "module/service-reading",
    "module/service-installing",
    "module/web-app-reading",
    "module/workload-deploying",
    "module/web-app-building",
    "module/cluster-api-reaching",
    "module/loki-log-fetching",
    "module/log-bound-saying",
    "module/dev-server-stating",
    "module/dev-server-recording",
    "module/dev-server-env-writing",
    "module/dev-server-worktree",
  ],
} as const satisfies WorkspacePackage
