export const PIN_DEFAULTS = {
  pinTextureUnknown: {
    type: 7,
    size: 42,
    level: 80,
    maxDistance: 0.05,
    texture: "",
    tint: [0.7, 0.7, 0.7, 0.6],
    textcolor: [1, 1, 1],
    textcolorEN: [1, 1, 1],
    textcolorTrader: [1, 1, 1],
  },
  pinTextureUnknownOthers: {
    tint: [1, 1, 1, 1],
  },
  pinTextureOther: {
    type: 6,
    size: 26,
    level: 80,
    maxDistance: 0.05,
    texture: "",
    tint: [1, 1, 1, 1],
    textcolor: [1, 1, 1],
  },
  pinTextureOtherDone: {
    type: 6,
    size: 26,
    level: 80,
    maxDistance: 0.05,
    texture: "",
    tint: [1, 1, 1, 1],
    textcolor: [1, 1, 1],
  },
  pinTextureMaiq: {
    type: 6,
    size: 26,
    level: 80,
    maxDistance: 0.05,
    texture: "",
    tint: [1, 1, 1, 1],
    textcolor: [1, 1, 1],
  },
  pinTextureMaiqDone: {
    type: 6,
    size: 26,
    level: 80,
    maxDistance: 0.05,
    texture: "",
    tint: [1, 1, 1, 1],
    textcolor: [1, 1, 1],
  },
  pinTexturePeacemaker: {
    type: 6,
    size: 26,
    level: 80,
    maxDistance: 0.05,
    texture: "",
    tint: [1, 1, 1, 1],
    textcolor: [1, 1, 1],
  },
  pinTexturePeacemakerDone: {
    type: 6,
    size: 26,
    level: 80,
    maxDistance: 0.05,
    texture: "",
    tint: [1, 1, 1, 1],
    textcolor: [1, 1, 1],
  },
  pinTextureNosediver: {
    type: 6,
    size: 26,
    level: 80,
    maxDistance: 0.05,
    texture: "",
    tint: [1, 1, 1, 1],
    textcolor: [1, 1, 1],
  },
  pinTextureNosediverDone: {
    type: 6,
    size: 26,
    level: 80,
    maxDistance: 0.05,
    texture: "",
    tint: [1, 1, 1, 1],
    textcolor: [1, 1, 1],
  },
  pinTextureEarthlyPos: {
    type: 6,
    size: 26,
    level: 80,
    maxDistance: 0.05,
    texture: "",
    tint: [1, 1, 1, 1],
    textcolor: [1, 1, 1],
  },
  pinTextureEarthlyPosDone: {
    type: 6,
    size: 26,
    level: 80,
    maxDistance: 0.05,
    texture: "",
    tint: [1, 1, 1, 1],
    textcolor: [1, 1, 1],
  },
  pinTextureOnMe: {
    type: 6,
    size: 26,
    level: 80,
    maxDistance: 0.05,
    texture: "",
    tint: [1, 1, 1, 1],
    textcolor: [1, 1, 1],
  },
  pinTextureOnMeDone: {
    type: 6,
    size: 26,
    level: 80,
    maxDistance: 0.05,
    texture: "",
    tint: [1, 1, 1, 1],
    textcolor: [1, 1, 1],
  },
  pinTextureBrawl: {
    type: 5,
    size: 26,
    level: 80,
    maxDistance: 0.05,
    texture: "",
    tint: [1, 1, 1, 1],
    textcolor: [1, 1, 1],
  },
  pinTextureBrawlDone: {
    type: 5,
    size: 26,
    level: 80,
    maxDistance: 0.05,
    texture: "",
    tint: [1, 1, 1, 1],
    textcolor: [1, 1, 1],
  },
  pinTexturePatron: {
    type: 5,
    size: 26,
    level: 80,
    maxDistance: 0.05,
    texture: "",
    tint: [1, 1, 1, 1],
    textcolor: [1, 1, 1],
  },
  pinTexturePatronDone: {
    type: 5,
    size: 26,
    level: 80,
    maxDistance: 0.05,
    texture: "",
    tint: [1, 1, 1, 1],
    textcolor: [1, 1, 1],
  },
  pinTextureWrothgarJumper: {
    type: 6,
    size: 26,
    level: 80,
    maxDistance: 0.05,
    texture: "",
    tint: [1, 1, 1, 1],
    textcolor: [1, 1, 1],
  },
  pinTextureWrothgarJumperDone: {
    type: 6,
    size: 26,
    level: 80,
    maxDistance: 0.05,
    texture: "",
    tint: [1, 1, 1, 1],
    textcolor: [1, 1, 1],
  },
  pinTextureRelicHunter: {
    type: 6,
    size: 26,
    level: 80,
    maxDistance: 0.05,
    texture: "",
    tint: [1, 1, 1, 1],
    textcolor: [1, 1, 1],
  },
  pinTextureRelicHunterDone: {
    type: 6,
    size: 26,
    level: 80,
    maxDistance: 0.05,
    texture: "",
    tint: [1, 1, 1, 1],
    textcolor: [1, 1, 1],
  },
  pinTextureChampion: {
    type: 1,
    size: 26,
    level: 80,
    maxDistance: 0.05,
    texture: "",
    tint: [1, 1, 1, 1],
    textcolor: [1, 1, 1],
  },
  pinTextureChampionDone: {
    type: 1,
    size: 26,
    level: 81,
    maxDistance: 0.05,
    texture: "",
    tint: [1, 1, 1, 1],
    textcolor: [1, 1, 1],
  },
  pinTextureBreaking: {
    type: 5,
    size: 26,
    level: 80,
    maxDistance: 0.05,
    texture: "",
    tint: [1, 1, 1, 1],
    textcolor: [1, 1, 1],
  },
  pinTextureBreakingDone: {
    type: 5,
    size: 26,
    level: 80,
    maxDistance: 0.05,
    texture: "",
    tint: [1, 1, 1, 1],
    textcolor: [1, 1, 1],
  },
  pinTextureCutpurse: {
    type: 5,
    size: 26,
    level: 80,
    maxDistance: 0.05,
    texture: "",
    tint: [1, 1, 1, 1],
    textcolor: [1, 1, 1],
  },
  pinTextureCutpurseDone: {
    type: 5,
    size: 26,
    level: 80,
    maxDistance: 0.05,
    texture: "",
    tint: [1, 1, 1, 1],
    textcolor: [1, 1, 1],
  },
  pinTextureAyleid: {
    type: 5,
    size: 26,
    level: 80,
    maxDistance: 0.05,
    texture: "",
    tint: [1, 1, 1, 1],
    textcolor: [1, 1, 1],
  },
  pinTextureDeadlands: {
    type: 1,
    size: 26,
    level: 80,
    maxDistance: 0.05,
    texture: "",
    tint: [1, 1, 1, 1],
    textcolor: [1, 1, 1],
  },
  pinTextureHighIsle: {
    type: 1,
    size: 26,
    level: 80,
    maxDistance: 0.05,
    texture: "",
    tint: [1, 1, 1, 1],
    textcolor: [1, 1, 1],
  },
  pinTextureDwemer: {
    type: 7,
    size: 26,
    level: 145,
    maxDistance: 0.05,
    texture: "",
    tint: [1, 1, 1, 1],
    textcolor: [1, 1, 1],
  },
  pinTextureWWVamp: {
    type: 5,
    size: 26,
    level: 80,
    maxDistance: 0.05,
    texture: "",
    tint: [1, 1, 1, 1],
    textcolor: [1, 1, 1],
  },
  pinTextureWWShrine: {
    type: 5,
    size: 26,
    level: 80,
    maxDistance: 0.05,
    texture: "",
    tint: [1, 1, 1, 1],
    textcolor: [1, 1, 1],
  },
  pinTextureVampAltar: {
    type: 5,
    size: 26,
    level: 80,
    maxDistance: 0.05,
    texture: "",
    tint: [1, 1, 1, 1],
    textcolor: [1, 1, 1],
  },
  pinTextureCollectible: {
    type: 2,
    size: 26,
    level: 80,
    maxDistance: 0.05,
    texture: "",
    tint: [1, 1, 1, 1],
    textcolor: [1, 1, 1],
    textcolortitle: [1, 1, 1],
  },
  pinTextureQolPin: {
    type: 1,
    size: 35,
    level: 45,
    maxDistance: 0.05,
    texture: "",
    tint: [1, 1, 1, 1],
    textcolor: [1, 1, 1],
    textcolortitle: [1, 1, 1],
  },
  pinTextureCollectibleDone: {
    type: 2,
    size: 26,
    level: 80,
    maxDistance: 0.05,
    texture: "",
    tint: [1, 1, 1, 1],
    textcolor: [1, 1, 1],
    textcolortitle: [1, 1, 1],
  },
  pinTextureFish: {
    type: 1,
    size: 26,
    level: 80,
    maxDistance: 0.05,
    texture: "",
    tint: [1, 1, 1, 1],
    textcolor: [1, 1, 1],
    textcolortitle: [1, 1, 1],
    textcolorBait: [1, 1, 1],
    textcolorWater: [1, 1, 1],
  },
  pinTextureFishDone: {
    type: 1,
    size: 26,
    level: 80,
    maxDistance: 0.05,
    texture: "",
    tint: [1, 1, 1, 1],
    textcolor: [1, 1, 1],
    textcolortitle: [1, 1, 1],
    textcolorBait: [1, 1, 1],
    textcolorWater: [1, 1, 1],
  },
}

export type PinDefaultsKey = keyof typeof PIN_DEFAULTS
