pulse.rules = [
    {
        matches = [ { application.name = "Spotify" } ]
        actions = {
            update-props = {
                node.latency      = 2048/48000
                pulse.min.req     = 2048/48000
                pulse.min.quantum = 2048/48000
            }
        }
    }
]
