import type { StoryTurnPlayed } from "akasha/story/world/stories/played/turns/story-turn-played.page-type.types.ts"

export const otherwhere00012 = {
  id: "01a0e482-9a1f-7b07-a762-d934d5616677",
  type: "page-type/story-turn-played",
  slug: "otherwhere-00-012",
  cover: "image/image-7f74cf87c8f002d6",
  ownLength: 367,
  unit: "unit/words",
  partOfCollections: ["story-played/otherwhere"],
  position: 12,
  prose: "txt",
  characters: [
    "character-player/otherwhere-alan",
    "character-other/otherwhere-links",
    "character-other/otherwhere-engorged-bookworm-01",
  ],
  turnStatus: "turn-status/player",
  action:
    "I go back to the door, fill the scoop with salt than get just close enough to fling the salt onto the nearest large bookworm before retreating back to the box",
  beats: [
    "She goes back to the salt box at the edge of the light and fills the tin scoop heaping full.",
    "She walks toward the nearest bookworm, into the gloom, the scoop held low and ready.",
    "About twenty feet out, it stops chewing.",
    "It rears up off the books, as long as a small dog, grey and fat, rings of faded color at each end.",
    "It has no eyes; its front end is a round mouth rimmed with rows of jagged teeth.",
    "It roars at her, a wet, squelching bellow, far too loud for its size.",
    "She keeps coming until she's close enough, about ten feet, and flings the salt.",
    "Most of it goes wide and scatters across the books in the dark, but a spray catches its flank.",
    "Where the salt strikes, the grey skin puckers and shrinks, and the bookworm thrashes and shrieks.",
    "It's hurt, shrunk a little along one side, but far from dried out.",
    "The shriek carries: all through the dark at the back of the hall, the chewing stops.",
    "Other humped shapes lift from the heaps of books, turning blind heads toward the noise.",
    "She backs off fast to the salt box, into the gold light.",
    "The salted bookworm comes after her, slow, dragging through the scattered books.",
    "It is fifteen feet away and closing, mouth open, teeth wet.",
    "Links stands beside the box, fur bristling, his runes racing.",
  ],
  lore: ["place/otherwhere-main-hall"],
  reviewedBy: ["story-reviewer/continuity", "story-reviewer/style"],
  recordedBy: ["story-recorder/memory", "story-recorder/picture", "story-recorder/mechanics"],
} as const satisfies StoryTurnPlayed
