import type { StoryTurnPlayed } from "akasha/story/world/stories/played/turns/story-turn-played.page-type.types.ts"

export const otherwhere00004 = {
  id: "01a0e384-f021-77ff-b75a-4b71dcd52621",
  type: "page-type/story-turn-played",
  slug: "otherwhere-00-004",
  cover: "image/image-05a5e94bf03d21a7",
  ownLength: 418,
  unit: "unit/words",
  partOfCollections: ["story-played/otherwhere"],
  position: 4,
  prose: "txt",
  characters: ["character-player/otherwhere-alan"],
  turnStatus: "turn-status/player",
  action: "I put my other hand to the second light",
  beats: [
    "She lays her other hand on the trunk, over the second knot of light.",
    "Both knots flare bright under her palms at once.",
    "Pain burns up through her hands and along her veins, into her arms, her chest, behind her eyes.",
    "Her hands stay on the trunk; she can't tell whether she's holding on or being held.",
    "Visions flood her: threads of blue light running out through a dark past counting.",
    "The threads join worlds she has never seen, knots of light strung across the dark like beads.",
    "Many of the threads are thin and faint, and some have gone dark entirely.",
    "She feels, vast and old and very tired, something at the center of all of them.",
    "The pain and the visions ebb together, and the chamber comes back.",
    "She finds herself on her knees at the foot of the trunk, her hands slid down its face.",
    "She's wrung out and dizzy, her arms trembling, as if something has drunk her empty.",
    "Her body is whole: no burns on her palms, nothing broken, only the ache fading from her veins.",
    "Above her the trunk's veins stop flickering and burn steady blue, all the way up into the dark.",
    "The alarm still honks overhead, the red light unchanged.",
    "A panel of pale blue light opens before her eyes, and the voice speaks it inside her skull.",
    "The panel reads: Librarian Link: Tentative.",
    "The panel reads: Power Drain: Halted.",
    "The panel reads: Status: Emergency Power Mode.",
    "The panel reads: Operational: 12%.",
    "The panel stays, hanging in the air before her eyes and moving when she turns her head.",
  ],
  lore: ["place/otherwhere-core-chamber"],
  reviewedBy: ["story-reviewer/continuity", "story-reviewer/style"],
  recordedBy: ["story-recorder/mechanics", "story-recorder/memory"],
} as const satisfies StoryTurnPlayed
