apiVersion: v1
kind: Secret
metadata:
    name: supabase-studio-secrets
    namespace: supabase-studio
type: Opaque
stringData:
    DASHBOARD_USERNAME: ENC[AES256_GCM,data:jcXuDHk=,iv:nQnmEzjA3yXN7iEG3pHpqdzGHmXbq2T3uHI5cuGh0Qg=,tag:L+CTo/Ra2Da054yiRtpXXA==,type:str]
    DASHBOARD_PASSWORD: ENC[AES256_GCM,data:Od7USu71rXvsgaKEcqMBBAVb2E1a53iHTeOv5wcH6dI=,iv:pZvUZ16wD7w3jvNN8Qp9q9Pr+18OKs8+z4Zo1taCiyA=,tag:gLiSMt8y2CDfMXuaevthFw==,type:str]
    PG_META_CRYPTO_KEY: ENC[AES256_GCM,data:EN6y7B+/AVtTPsgX7ySfka239sw243N29Qis9j9TcVAQg7graZFwa54z4qY=,iv:NVxFKbTMgHdbCFmcFO4FjyTzqcYoH83dxqTAE4b09Mk=,tag:hyimiEnYdDjbsBQ+gDMcpw==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:XWQFeMoRyOdozAruuLRy/mOXlw+j4bldYGPXLPI4NtlO2Xofxumq9bntbA/wq4JpomlouvQGV8oFA5T5pVngzc0Ce/nCnlyp9EVDF30LBe1GELF1dNqZs7kUrE80akVz6FoztiQZOP0uvwhPCP3bbQ==,iv:Izhq9vwT2en1sbAm9orIOLZLLnoOSSD6tEmYGUzEaHs=,tag:q+wPsNPg5v0p5WVWNJw/LQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFcXovVTRoVHVVZFh0RU1m
            T2Qrbk5UcDlad013dUtoQ1ZWN0l4cXViVDJNCnJJbUVLY2h4QWh1WnJ0ZXZHOHZQ
            ZXZ6MS9UZnlzZ2JKYTUrbWdsWjZsYzQKLS0tIFppUnYrNHNaVko1WWsyOVViclJt
            Zy9QeDZxN2hpVFJXT2xOMit6VkJoU1UKrYVmRa25S8SON18lTv9EuxwTG8ZZyB7g
            FOlr6wJbyaHCdte69gp6ydSscByMU5Wm9FV+2qALPCO+gxX3/gI6kA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-25T22:06:18Z"
    mac: ENC[AES256_GCM,data:JEOfPvZRH55KQriblUAedQhKcHKx5mo2fiQ0A09mw/q/DWlxV9F1ZPJfsW9cdisykioGjcCOkPo0CPeDlDGjrzriSrNCLsBXLicx/0VUxZsqsOvIDJdSolGDXeLesYHoWE2E5M4T8ahgenEeG0NCo4xT3S0cYWIc4LF9HirJg1A=,iv:y/lqEOj6QyQW1sHOcxqHd4ViwWiRC5dX18oAzP6Sxrs=,tag:cGRlNlvD/o5ejTG0tzCEJw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
