import type { StoryTurnPlayed } from "akasha/story/world/stories/played/turns/story-turn-played.page-type.types.ts"

export const otherwhereViii00003 = {
  id: "01a0ea59-b1a3-71bb-9d2e-d2886a26adf4",
  type: "page-type/story-turn-played",
  slug: "otherwhere-viii-00-003",
  ownLength: 239,
  unit: "unit/words",
  partOfCollections: ["story-played/otherwhere-viii"],
  position: 3,
  prose: "txt",
  characters: ["character-player/otherwhere-viii-nala"],
  stepStatus: "step-status/recorders",
  action:
    "\"Just a hard night I think. The gardens are lovely, but I don't think I've been here before. Would you point me the way back to the Academy?\"",
  beats: [
    'Nala tells Maddox, "Just a hard night, I think."',
    "She says the gardens are lovely, but she doesn't think she has been here before.",
    "She asks if he would point her the way back to the Academy.",
    'At "lovely" his eyes flick to the lawns he keeps, and his face eases a little.',
    'At "the Academy" his brows go up.',
    '"You\'ll mean the Institute," he says. "Up in Guildhall. Half an hour\'s walk, all uphill."',
    "Then his eyes go to her bare feet again, slower this time.",
    '"Unless you mean the Imperial one," he says.',
    "He says the Imperial Academy is two days north of here, past Geldor, by train and then bus.",
    "He says it the way a man names a place he has only ever seen on the news.",
    "He studies her face longer than is polite, looking at her eyes the way you check a child's.",
    "He asks her, gently, whether she has taken a knock on the head.",
    "If she truly belongs up at the Academy, he says, the Weir Street police post can sort it.",
    "The post has a booth, he says, that can reach anywhere.",
    "The street past the railings is still quiet; the sky is paler now, and the lamps still lit.",
    "He waits for her answer: the Institute or the Academy, and did she hit her head.",
  ],
  lore: ["place/otherwhere-viii-weir-gardens", "place/otherwhere-viii-low-bank"],
  reviewedBy: ["story-reviewer/continuity", "story-reviewer/style"],
  recordedBy: ["story-recorder/memory"],
  endsAt: "2026-09-28T05:50:00.000Z",
} as const satisfies StoryTurnPlayed
