import type { StoryTurnPlayed } from "akasha/story/world/stories/played/turns/story-turn-played.page-type.types.ts"

export const otherwhereViii00004 = {
  id: "01a0ea77-e9bd-773c-8251-906318dcb84f",
  type: "page-type/story-turn-played",
  slug: "otherwhere-viii-00-004",
  ownLength: 242,
  unit: "unit/words",
  partOfCollections: ["story-played/otherwhere-viii"],
  position: 4,
  prose: "txt",
  characters: ["character-player/otherwhere-viii-nala"],
  stepStatus: "step-status/recorders",
  action:
    '"Sorry, I meant the Institute of course. Still waking up it seems. Point me in the right direction? I\'m not afraid of the hills, give me a chance to clear my head."',
  beats: [
    'Nala says, "Sorry, I meant the Institute, of course. Still waking up, it seems."',
    "She asks him to point her in the right direction.",
    "She says she isn't afraid of the hills, and the walk will give her a chance to clear her head.",
    "Maddox's eyes stay on hers a moment; he notices she let the question about her head go by.",
    "He lets it go too, and turns to point up the street past the railings.",
    "Up Weir Street, he says, past the police post at the top, then straight over Tanners Row.",
    "Past Tanners Row the Long Stair climbs the hill, near three hundred steps, old stone.",
    "It comes out at the corner of Guildhall Square; the Institute is on Mercer Street, just off it.",
    "Or Hill Road winds round the long way, he says, and the buses climb it from half past six.",
    "He looks down at her feet again and shakes his head.",
    '"Not up the Stair like that, you\'re not," he says. "Hang on."',
    "He walks to a small tool shed by the gate, unlocks it, and rummages inside.",
    "He comes back with a pair of men's canvas shoes, grey and scuffed, plainly too big for her.",
    "Over his arm is a worn brown wool coat, long and heavy, with a button missing.",
    "Lost property, he says; folk leave all sorts in the park, and nobody has come for these.",
    "He holds them out to her.",
  ],
  lore: ["place/otherwhere-viii-guildhall", "place/otherwhere-viii-weir-gardens"],
  reviewedBy: ["story-reviewer/style", "story-reviewer/continuity"],
  recordedBy: ["story-recorder/memory"],
  endsAt: "2026-09-28T05:55:00.000Z",
} as const satisfies StoryTurnPlayed
