apiVersion: v1
kind: Secret
metadata:
    name: audhdalan-secrets
    namespace: audhdalan
type: Opaque
stringData:
    SUPABASE_URL: ENC[AES256_GCM,data:kBZ8m3wtMDzD3cq2gEJ/u+yUzQQyhhR79dnzmMqJCg==,iv:2aPNWekBDEmdDky+WAwwiaIkfAlxwK1txgiHjADiW6c=,tag:MFf5hkbLZqMe2uTnqrdVRw==,type:str]
    SUPABASE_SERVICE_ROLE_KEY: ENC[AES256_GCM,data:BFsoX2I56GAdS3YksWvncM9ei1xxs3aerPkqJc/p/EfucZUCtrkFE9xDDwMSSohFHntt48ZwzAlZLtWagSfFoBnBj7xIK0kXvBdyN46ZycpSA8uEjRLhiXzX3IvpioL06K7AOZL46dJbcnoQ9YWvZrUTBnBCMD6kNE790it/MW2OXwM83nOGYFW9oPHuVJUQ6rsjXMXrK86qFF2j9iLaMBYS9hWd7l7MdPAN50iugkvjH5z0lGJkRyZ/oAgdG3OtLhdk6PpvpbBAzxyjXP7ONioVCdx6H/jGPPrNIpU3u4ZUNiqCZFicHI7TUpI1GyB6/ljkhd6s63MGjauaei2pdyq57xgAn3vU1ecMXfBTQXTl4hIy8kig0nu4O1hrwxBvBqms6tImsWk2DqiWbU4xMkfhEj7MK2vK684LAlFFLbggeLfmPBaUn+93gU8/qy8mb80OWq2hKqWJgY2ql4dvFnHqBOB2sLG41hmyenqXseaHJZ5lQ1qfuu9XT9Qf24yWyO7tB76bBEbKJ8jZzBF9QLGvUNxLrzSs0eM9ZmCq7OBDt1sSf4CQoOocNxT1HIryWRNXItHcvhbKR7NwO6r8caNYsdUEoy2ueRXtQHT6TRF3buUK1FMzK1G2ziHEjiF93KDsxVoP6iCOXcVAHroPiXqAoh66ASGxsEYbnrp0OB/MRRM8FZfywm2OnMNoPP3dmvWz/V92QvdCjEtmLjfRyOa6wQbssGn8qv3KutvQy0Y3CmOd1FO3frIn6+x4ED3gx7BlNH2t9ss1mA==,iv:0RAsuurRcNC8zkMQ4PdKdM6tboK3uNIBxxZU3OueA6s=,tag:RIAJ+pm/wcv/3a2ti82ECQ==,type:str]
    SUBSCRIBER_OWNER_USER_ID: ENC[AES256_GCM,data:XReF4DLsNGoE2oaUXU3B+NCwcJF5wh5NPWTln1jrqC6g9HVS,iv:Eiw/EetJa9peCeNtfvcPoBg+Jo4hfOoQl5EPekzk/Wc=,tag:KVbT/9WtfSsnih86AlNznw==,type:str]
    GIT_ACCESS_TOKEN: ENC[AES256_GCM,data:FyiMRDGiAuicwTu9ZZr5A2yqE+UeQ9sgBQHSRXFiLH5TcJspSpuVhA==,iv:qHe2pw9+6xP+VstbHC5AmGzEIg0vlkqJuSQZWEs4Plw=,tag:v1it89oDv9evrYGToT8o4Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNUTZxVG5WMThlS0FhRzY4
            ZVBucXh6L3VuSmY5NisxL3FWL2wvVW51enl3CnhHUzlQYmIrQ0dBN3FqZEtzWk4w
            TVUzS2szbmRKOHdnSzNndGNMeEN5UGMKLS0tIHlaZFNiNS9kNUY0cVlwM1hDcDJt
            WURwQXVvY1lSa3ZteTFjQm9Wbko4aGsKKKDr2VY+PKHaazOfWCYF5lr4RJpHzPCZ
            XSU/GeW6KFcC2/DW589lKKvVMJ1Vh2N3HvUl79rGKbRrIS1ajHgrjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-16T16:27:36Z"
    mac: ENC[AES256_GCM,data:DcuHqxpr57zSRBGpomOIOqdCW+9XUkqQUJxqYI9JSUrJyiqV4ne4e0V3O11Ug7giQRJMiWYoUsQ7dvrAUFwqjzFNoOLl4/b3OgELLpl8KjAQ4FB7mjIMcLXV0Qv2JSgo/X16heKdacSgjzReevHfQukBIePo/BYAAq85wgdpcmI=,iv:/VB8QmJ1AEhMWE4RajhTlmf0YawsZlSCmbXARtE2puA=,tag:9BDLWaQ/uoOD5Y0+Mx/Zeg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
