import { TEXTURE_ROOT } from "../map-pins-names/map-pins-names.module.code.ts"
import type { CustomPinTable } from "../map-pins-pin-types/map-pins-pin-types.module.code.ts"

export const CUSTOM_PINS_CHAPTERS: CustomPinTable = {
  [20]: {
    section: true,
    name: "pinType_Elsweyr",
    id: {},
    pin: [],
    texture: "/esoui/art/treeicons/tutorial_idexicon_elsweyr_up.dds",
    [63]: {
      name: "pinType_Mural_Mender",
      done: false,
      ach: 2463,
      maxDistance: 0.05,
      level: 101,
      texture: "/esoui/art/inventory/gamepad/gp_inventory_icon_craftbag_stylematerial.dds",
      k: 1,
      def_texture: "/esoui/art/icons/achievement_els_museum_mural.dds",
    },
    [64]: {
      name: "pinType_Pieces_of_History",
      done: false,
      ach: 2534,
      maxDistance: 0.05,
      level: 101,
      texture: "/esoui/art/miscellaneous/help_icon.dds",
      k: 1,
      def_texture: "/esoui/art/icons/achievement_u24_museum_tapestry.dds",
    },
    [65]: {
      name: "pinType_Theater_Critic",
      done: false,
      ach: 2619,
      maxDistance: 0.05,
      level: 101,
      texture: `/${TEXTURE_ROOT}/Scroll_1.dds`,
      k: 1,
      def_texture: "/esoui/art/icons/quest_book_003.dds",
    },
    [66]: {
      name: "pinType_Legacy_Slayer",
      done: false,
      ach: 2621,
      maxDistance: 0.05,
      level: 101,
      texture: "/esoui/art/icons/poi/poi_groupboss_incomplete.dds",
      k: 1.25,
      def_texture: "/esoui/art/icons/achievement_u24_familyofpirates.dds",
    },
    [67]: {
      name: "pinType_Grappling_Bow_Pathfinder",
      done: false,
      ach: 2620,
      maxDistance: 0.05,
      level: 101,
      texture: "/esoui/art/tutorial/gamepad/gp_icon_new.dds",
      k: 1,
      def_texture: "/esoui/art/icons/achievement_u24_grappletreasures.dds",
    },
  },
  [21]: {
    name: "pinType_Volendrung",
    id: {},
    pin: [],
    maxDistance: 0.05,
    level: 30,
    texture: "/esoui/art/miscellaneous/help_icon.dds",
    k: 1.25,
  },
  [22]: {
    section: true,
    name: "pinType_Greymoor",
    id: {},
    pin: [],
    texture: "/esoui/art/treeicons/tutorial_indexicon_greymoor_up.dds",
    [68]: {
      name: "pinType_Instrumental_Triumph",
      done: false,
      ach: 2669,
      maxDistance: 0.05,
      level: 101,
      texture: "/esoui/art/miscellaneous/help_icon.dds",
      k: 1,
      def_texture: "/esoui/art/icons/achievement_u26_skyrim_sounds_of_success.dds",
    },
    [69]: {
      name: "Mining_Sample_Collector",
      done: false,
      ach: 2759,
      maxDistance: 0.05,
      level: 101,
      texture: "/esoui/art/icons/poi/poi_mine_compete.dds",
      k: 1,
      def_texture: "/esoui/art/icons/achievement_u26_skyrim_minerquest.dds",
    },
  },
  [23]: {
    section: true,
    name: "pinType_Antiquities",
    id: {},
    pin: [],
    texture: "/esoui/art/icons/servicetooltipicons/servicetooltipicon_antiquities.dds",
    k: 1.4,
    [70]: {
      name: "pinType_Antiquity_Leads",
      done: false,
      maxDistance: 0.05,
      level: 101,
      texture: "/esoui/art/icons/servicetooltipicons/servicetooltipicon_antiquities.dds",
      k: 1.4,
    },
  },
  [24]: {
    section: true,
    name: "pinType_Blackwood",
    id: {},
    pin: [],
    texture: "/esoui/art/treeicons/tutorial_idexicon_blackwood_up.dds",
    [71]: {
      name: "pinType_Lost_in_Wilds",
      done: false,
      ach: 3083,
      maxDistance: 0.05,
      level: 101,
      texture: "/esoui/art/tutorial/gamepad/gp_icon_new.dds",
      k: 1,
      def_texture: "/esoui/art/icons/achievement_u30_flavor4.dds",
    },
    [72]: {
      name: "pinType_Bane_of_Sul-Xan",
      done: false,
      ach: 3081,
      maxDistance: 0.05,
      level: 101,
      texture: "/esoui/art/death/death_soulreservoir_icon.dds",
      k: 1,
      def_texture: "/esoui/art/icons/achievement_u30_flavor2.dds",
    },
    [73]: {
      name: "pinType_Most_Admired",
      done: false,
      ach: 3082,
      maxDistance: 0.05,
      level: 101,
      texture: "/esoui/art/miscellaneous/help_icon.dds",
      k: 1,
      def_texture: "/esoui/art/icons/achievement_u30_rds.dds",
    },
    [74]: {
      name: "pinType_Random_Encounters",
      done: false,
      maxDistance: 0.05,
      level: 101,
      texture: "/esoui/art/miscellaneous/help_icon.dds",
      k: 1,
    },
    [75]: {
      name: "pinType_Leyawiin_Master_Burglar",
      done: false,
      ach: 3080,
      maxDistance: 0.05,
      level: 101,
      texture: "/esoui/art/icons/servicetooltipicons/servicetooltipicon_bagvendor.dds",
      k: 1,
      def_texture: "/esoui/art/icons/achievement_u30_flavor1.dds",
    },
  },
  [25]: {
    section: true,
    name: "pinType_Imperial_City",
    id: {},
    pin: [],
    texture: "/esoui/art/compass/ava_imperialcity_neutral.dds",
    [76]: {
      name: "pinType_IC_Bosses",
      done: false,
      maxDistance: 0.05,
      level: 101,
      texture: "/esoui/art/icons/poi/poi_groupboss_incomplete.dds",
      k: 1.25,
    },
    [77]: {
      name: "pinType_IC_Respawns",
      done: false,
      maxDistance: 0.05,
      level: 101,
      texture: "/esoui/art/death/death_soulreservoir_icon.dds",
      k: 1,
    },
    [78]: {
      name: "pinType_Cunning_Scamp",
      done: false,
      maxDistance: 0.05,
      level: 101,
      texture: "/esoui/art/miscellaneous/help_icon.dds",
      k: 1,
      def_texture: "/esoui/art/icons/achievement_ic_telvarscamp.dds",
    },
    [79]: {
      name: "pinType_Trove_Scamp",
      done: false,
      maxDistance: 0.05,
      level: 101,
      texture: "/esoui/art/miscellaneous/help_icon.dds",
      k: 1,
      def_texture: "/esoui/art/icons/achievement_ic_treasurescamp.dds",
    },
  },
  [26]: {
    name: "pinType_Portals",
    id: {},
    pin: [],
    maxDistance: 0.05,
    level: 30,
    texture: "/esoui/art/icons/poi/poi_portal_complete.dds",
    k: 1.26,
  },
  [27]: {
    section: true,
    name: "pinType_High_Isle",
    id: {},
    pin: [],
    texture: "/esoui/art/treeicons/tutorial_idexicon_highisle_up.dds",
    [80]: {
      name: "pinType_Seeker_of_the_Green",
      done: false,
      ach: 3298,
      maxDistance: 0.05,
      level: 101,
      texture: "/esoui/art/icons/achievement_u34_flavor4_druid.dds",
      k: 1,
      def_texture: "/esoui/art/icons/achievement_u34_flavor4_druid.dds",
    },
    [81]: {
      name: "pinType_No_Regrets",
      done: false,
      ach: 3424,
      maxDistance: 0.05,
      level: 101,
      texture: "/esoui/art/tutorial/gamepad/gp_icon_new.dds",
      k: 1,
      def_texture: "/esoui/art/icons/u34_flavor5_drunkedleap.dds",
    },
    [82]: {
      name: "pinType_Inventor_of_Adventure",
      done: false,
      ach: 3299,
      maxDistance: 0.05,
      level: 101,
      texture: "/esoui/art/miscellaneous/help_icon.dds",
      k: 1,
      def_texture: "/esoui/art/icons/achievement_u34_rds.dds",
    },
    [83]: {
      name: "pinType_Gonfalon_Bays_Master_Burglar",
      done: false,
      ach: 3295,
      maxDistance: 0.05,
      level: 101,
      texture: "/esoui/art/icons/servicetooltipicons/servicetooltipicon_bagvendor.dds",
      k: 1,
      def_texture: "/esoui/art/icons/achievement_u34_flavor1_lockbox.dds",
    },
  },
  [28]: {
    section: true,
    name: "pinType_Necrom",
    id: {},
    pin: [],
    texture: "/esoui/art/treeicons/tutorial_idexicon_necrom_up.dds",
    [84]: {
      name: "pinType_Syzygy",
      done: false,
      ach: 3678,
      maxDistance: 0.05,
      level: 101,
      texture: "/esoui/art/icons/achievement_u38_flavor4.dds",
      k: 1,
      def_texture: "/esoui/art/icons/achievement_u38_flavor4.dds",
    },
    [85]: {
      name: "pinType_Tomes_of_Uknown_Color",
      done: false,
      ach: 3677,
      maxDistance: 0.05,
      level: 101,
      texture: "/esoui/art/icons/achievement_u38_flavor3.dds",
      k: 1,
      def_texture: "/esoui/art/icons/achievement_u38_flavor3.dds",
    },
    [86]: {
      name: "pinType_Grave_Discoveries",
      done: false,
      ach: 3675,
      maxDistance: 0.05,
      level: 101,
      texture: "/esoui/art/icons/achievement_u38_flavor1.dds",
      k: 1,
      def_texture: "/esoui/art/icons/achievement_u38_flavor1.dds",
    },
    [87]: {
      name: "pinType_Slaughtered_by_Tentacles",
      done: false,
      ach: 3749,
      maxDistance: 0.05,
      level: 101,
      texture: "/esoui/art/icons/u38_slaughtered_apocrypha.dds",
      k: 1,
      def_texture: "/esoui/art/icons/u38_slaughtered_apocrypha.dds",
    },
  },
  [29]: {
    section: true,
    name: "pinType_Gold_Road",
    id: {},
    pin: [],
    texture: "/esoui/art/treeicons/tutorial_idexicon_goldroad_up.dds",
    [88]: {
      name: "pinType_Gold_Road_Partaker",
      done: false,
      ach: 3968,
      maxDistance: 0.05,
      level: 101,
      texture: "/esoui/art/icons/achievement_u42_zone_flavor1.dds",
      k: 1,
      def_texture: "/esoui/art/icons/achievement_u42_zone_flavor1.dds",
    },
    [89]: {
      name: "pinType_Wine_and_Warriors",
      done: false,
      ach: 4040,
      maxDistance: 0.05,
      level: 101,
      texture: "/esoui/art/miscellaneous/help_icon.dds",
      k: 1,
      def_texture: "/esoui/art/icons/achievement_u42_rds.dds",
    },
    [90]: {
      name: "pinType_Minotaur_Tracker",
      done: false,
      ach: 4041,
      maxDistance: 0.05,
      level: 101,
      texture: "/esoui/art/icons/u42_wandering_world_boss.dds",
      k: 1,
      def_texture: "/esoui/art/icons/u42_wandering_world_boss.dds",
    },
  },
  [30]: {
    section: true,
    name: "pinType_Seasons_of_the_Worm_Cult",
    id: {},
    pin: [],
    texture: "/esoui/art/treeicons/tutorial_idexicon_goldroad_up.dds",
    [91]: {
      name: "pinType_Wanderers_of_Western_Solstice",
      done: false,
      ach: 4432,
      maxDistance: 0.05,
      level: 101,
      texture: "/esoui/art/miscellaneous/help_icon.dds",
      k: 1,
      def_texture: "/esoui/art/icons/achievement_u46_zone_flavor1.dds",
    },
    [92]: {
      name: "pinType_So_Clean_in_Sunport",
      done: false,
      ach: 4433,
      maxDistance: 0.05,
      level: 101,
      texture: "/esoui/art/icons/achievement_u46_zone_flavor2.dds",
      k: 1,
      def_texture: "/esoui/art/icons/achievement_u46_zone_flavor2.dds",
    },
    [93]: {
      name: "pinType_Sanguine_s_Delights",
      done: false,
      ach: 4435,
      maxDistance: 0.05,
      level: 101,
      texture: "/esoui/art/icons/achievement_u46_zone_flavor4.dds",
      k: 1,
      def_texture: "/esoui/art/icons/achievement_u46_zone_flavor4.dds",
    },
    [94]: {
      name: "pinType_Solstice_Climbing_Club",
      done: false,
      ach: 4434,
      maxDistance: 0.05,
      level: 101,
      texture: "/esoui/art/tutorial/gamepad/gp_icon_new.dds",
      k: 1,
      def_texture: "/esoui/art/icons/achievement_u46_zone_flavor3.dds",
    },
    [95]: {
      name: "pinType_Soul Shriven_on_Solstice",
      done: false,
      ach: 4455,
      maxDistance: 0.05,
      level: 101,
      texture: "/esoui/art/icons/u48_zone_flavor1.dds",
      k: 1,
      def_texture: "/esoui/art/icons/u48_zone_flavor1.dds",
    },
    [96]: {
      name: "pinType_We_Were_Undaunted",
      done: false,
      ach: 4456,
      maxDistance: 0.05,
      level: 101,
      texture: "/esoui/art/icons/u48_zone_flavor2.dds",
      k: 1,
      def_texture: "/esoui/art/icons/u48_zone_flavor2.dds",
    },
    [97]: {
      name: "pinType_The_Legend_of_Atlorn_the_Lost",
      done: false,
      ach: 4457,
      maxDistance: 0.05,
      level: 101,
      texture: "/esoui/art/icons/u48_zone_flavor3.dds",
      k: 1,
      def_texture: "/esoui/art/icons/u48_zone_flavor3.dds",
    },
    [98]: {
      name: "pinType_Wanderers_of_Western_Solstice",
      done: false,
      ach: 4432,
      maxDistance: 0.05,
      level: 101,
      texture: "/esoui/art/miscellaneous/help_icon.dds",
      k: 1,
      def_texture: "/esoui/art/icons/achievement_u46_zone_flavor1.dds",
    },
  },
}
