import type { TemperSet } from "akasha/temper/catalog/gear/temper-set/temper-set.page-type.types.ts"

export const theWormsRaiment = {
  id: "019e66e6-a0d4-7a5a-adfe-c995ce7145e1",
  type: "page-type/temper-set",
  slug: "the-worms-raiment",
  title: "The Worm's Raiment",
  key: "the-worms-raiment",
  esoSetId: 124,
  setWayshrines: [184, 184, 184],
  setTypeId: 6,
  setNameZh: "黑虫的装束",
  setNameRu: "Одежды Червя",
  setNameFr: "La Tenue du Ver",
  setNameEs: "Vestimenta del gusano",
  setNameDe: "Garderobe des Wurms",
  setDropZones: [11, 347, 347],
  setDropMechanics: [28],
  setDlcId: 0,
  itemBrowserSources: ["11"],
  itemBrowserPlaceKinds: [3],
  itemBrowserItemId: 110796,
  esoItemIds: [
    73083, 73084, 73085, 73086, 73087, 73089, 73090, 73107, 73108, 73402, 73403, 73404, 73405,
    73406, 73407, 73408, 73409, 73410, 73411, 73412, 73413, 73414,
  ],
  esoArmorTypes: ["ARMORTYPE_LIGHT"],
  esoEquipTypes: [
    "EQUIP_TYPE_CHEST",
    "EQUIP_TYPE_FEET",
    "EQUIP_TYPE_HAND",
    "EQUIP_TYPE_HEAD",
    "EQUIP_TYPE_LEGS",
    "EQUIP_TYPE_NECK",
    "EQUIP_TYPE_OFF_HAND",
    "EQUIP_TYPE_ONE_HAND",
    "EQUIP_TYPE_RING",
    "EQUIP_TYPE_SHOULDERS",
    "EQUIP_TYPE_TWO_HAND",
    "EQUIP_TYPE_WAIST",
  ],
  esoWeaponTypes: [
    "WEAPONTYPE_AXE",
    "WEAPONTYPE_BOW",
    "WEAPONTYPE_DAGGER",
    "WEAPONTYPE_FIRE_STAFF",
    "WEAPONTYPE_FROST_STAFF",
    "WEAPONTYPE_HAMMER",
    "WEAPONTYPE_HEALING_STAFF",
    "WEAPONTYPE_LIGHTNING_STAFF",
    "WEAPONTYPE_SHIELD",
    "WEAPONTYPE_SWORD",
    "WEAPONTYPE_TWO_HANDED_AXE",
    "WEAPONTYPE_TWO_HANDED_HAMMER",
    "WEAPONTYPE_TWO_HANDED_SWORD",
  ],
  category: "temper-set-category/dungeon",
  valid: ["*:light"],
  bonuses: "jsonl",
  icons: "jsonl",
} as const satisfies TemperSet
