apiVersion: v1
kind: Secret
metadata:
    name: supabase-auth-admin-secrets
    namespace: postgres
type: Opaque
stringData:
    SUPABASE_AUTH_ADMIN_PASSWORD: ENC[AES256_GCM,data:yQfut9Jkzg/n89fE2t4P7jE+qo/Mdl2Bcarys9noVUI7k+GxHcYYtT9Y66U=,iv:0udiKaaKCIrn295ASeHLV85GLF5Rrp+84r3QGz62ByI=,tag:raHgwj/uTLDqk0lwJEWKmA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoZThudmpReG5vM25vTG9S
            YW0wM1FSdzZ2OEowYWRhMWJReGNIM3dCYzBVCmNyLzh4ZEgwVC9qM080U25IV2dt
            T254SjJuWlUxRktVaHhFRlVBTnBNTzAKLS0tIHhwVnF0eHVzc0orL3FDU3BNK3dB
            c0MxeFRKdlM1ZEh6U3lMSXpZVEpmcEUKrRfszcW/Kbw3cB9xzc1i3w4zhI1aSAoe
            v8YBcsyum3L4Dnm30RfZ4JA+DW+8RXs81tLUhW7+00VbBWrmxwqetg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-22T15:26:06Z"
    mac: ENC[AES256_GCM,data:8VwJFFBlCM1lSQ85tqTqDflmg9ChRH/xweq7XpUPrltOEjW0kidT/6p6q/dFknnN8YDLSzZPZ2nDXX1OtIUJhy5AaIJdBIHPTEV9bKVZo2fQ0Mibpg7707tZT75qxSoTOwrzKACPacudOI9YPFw9z04/8XgQXVWT3Jlbam2hBrU=,iv:Dyir1vNpDgOvEKjKQM7YTThZ/7pecglPsZ8RVS1jdN4=,tag:7vzkRU4uR1J047k1sj/svg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
