import type { SetTemplate } from "@akasha/temper-equipment/set-template"

export const SETS_DATA_075: readonly SetTemplate[] = [
  {
    id: "perfected-void-bash",
    name: "Perfected Void Bash",
    esoSetId: 564,
    subcategoryId: "arena",
    valid: ["sword", "axe", "mace", "dagger", "shield"],
    bonuses: [
      {
        count: 2,
        status: "unsupported",
        effects: [],
        description:
          "When you deal damage with Power Bash, you apply Call of the Void to yourself for 2 seconds. Enemies within 12 meters are immediately pulled to you.\n\nAfter Call of the Void ends, you apply Major Maim to enemies in the area for 10 seconds, reducing their damage done by 10%.  This effect can occur once every 13 seconds.",
      },
    ],
    icons: {
      axe: "/esoui/art/icons/gear_reachv2_1haxe_a.dds",
      dagger: "/esoui/art/icons/gear_reachv2_dagger_a.dds",
      mace: "/esoui/art/icons/gear_reachv2_1hhammer_a.dds",
      shield: "/esoui/art/icons/gear_voidrot_shield_a.dds",
      sword: "/esoui/art/icons/gear_reachv2_1hsword_a.dds",
    },
  },
  {
    id: "perfected-vrols-command",
    name: "Perfected Vrol's Command",
    esoSetId: 495,
    subcategoryId: "trial",
    valid: ["*:heavy"],
    bonuses: [
      {
        count: 2,
        status: "supported",
        effects: [{ metricId: "stamina-maximum", effectType: "integer", effectValue: 1096 }],
        description: "Adds 1096 Maximum Stamina",
      },
      {
        count: 3,
        status: "unsupported",
        effects: [],
        description:
          "Gain Minor Aegis at all times, reducing your damage taken from Dungeon, Trial, and Arena Monsters by 5%.",
      },
      {
        count: 4,
        status: "supported",
        effects: [{ metricId: "health-maximum", effectType: "integer", effectValue: 1206 }],
        description: "Adds 1206 Maximum Health",
      },
      {
        count: 5,
        status: "unsupported",
        effects: [],
        description:
          "After completing a fully-charged Heavy Attack, apply Major Aegis to you and up to 11 nearby group members for 12 seconds, reducing damage taken from Dungeon, Trial, and Arena enemies by 10%. This effect can occur once every 21 seconds.",
      },
    ],
    icons: {
      "axe": "/esoui/art/icons/gear_seagiant_axe.dds",
      "battleaxe": "/esoui/art/icons/gear_seagiant_2haxe.dds",
      "bow": "/esoui/art/icons/gear_seagiant_bow.dds",
      "chest:*": "/esoui/art/icons/gear_seagianthvy_chest.dds",
      "dagger": "/esoui/art/icons/gear_seagiant_dagger.dds",
      "feet:*": "/esoui/art/icons/gear_seagianthvy_feet.dds",
      "greatsword": "/esoui/art/icons/gear_seagiant_2hsword.dds",
      "hands:*": "/esoui/art/icons/gear_seagianthvy_hands.dds",
      "head:*": "/esoui/art/icons/gear_seagianthvy_helmet.dds",
      "ice-staff": "/esoui/art/icons/gear_seagiant_staff.dds",
      "inferno-staff": "/esoui/art/icons/gear_seagiant_staff.dds",
      "legs:*": "/esoui/art/icons/gear_seagianthvy_legs.dds",
      "lightning-staff": "/esoui/art/icons/gear_seagiant_staff.dds",
      "mace": "/esoui/art/icons/gear_seagiant_mace.dds",
      "maul": "/esoui/art/icons/gear_seagiant_2hmace.dds",
      "necklace": "/esoui/art/icons/gear_breton_neck_a.dds",
      "restoration-staff": "/esoui/art/icons/gear_seagiant_staff.dds",
      "ring": "/esoui/art/icons/gear_breton_ring_a.dds",
      "shield": "/esoui/art/icons/gear_seagiant_shield.dds",
      "shoulders:*": "/esoui/art/icons/gear_seagianthvy_shoulders.dds",
      "sword": "/esoui/art/icons/gear_seagiant_sword.dds",
      "waist:*": "/esoui/art/icons/gear_seagianthvy_waist.dds",
    },
  },
  {
    id: "perfected-whorl-of-the-depths",
    name: "Perfected Whorl of the Depths",
    esoSetId: 653,
    subcategoryId: "trial",
    valid: ["*:light"],
    bonuses: [
      {
        count: 2,
        status: "supported",
        effects: [{ metricId: "power", effectType: "integer", effectValue: 129 }],
        description: "Adds 129 Weapon and Spell Damage",
      },
      {
        count: 3,
        status: "unsupported",
        effects: [],
        description:
          "Gain Minor Slayer at all times, increasing your damage done to Dungeon, Trial, and Arena Monsters by 5%.",
      },
      {
        count: 4,
        status: "supported",
        effects: [{ metricId: "power", effectType: "integer", effectValue: 129 }],
        description: "Adds 129 Weapon and Spell Damage",
      },
      {
        count: 5,
        status: "unsupported",
        effects: [],
        description:
          "When you deal damage with a Light Attack, you apply Whorl of the Depths to the target, dealing 1016 Frost Damage over 8 seconds. When this effect ends, a 5 meter whirlpool is created under the target for 6 seconds and deals 764 Frost Damage every 1 second. This effect can occur once every 18 seconds and scales off the higher of your Weapon or Spell Damage.",
      },
    ],
    icons: {
      "axe": "/esoui/art/icons/gear_amenossea_axe_a.dds",
      "battleaxe": "/esoui/art/icons/gear_amenossea_2haxe_a.dds",
      "bow": "/esoui/art/icons/gear_amenossea_bow_a.dds",
      "chest:*": "/esoui/art/icons/gear_amenossea_lgt_robe_a.dds",
      "dagger": "/esoui/art/icons/gear_amenossea_dagger_a.dds",
      "feet:*": "/esoui/art/icons/gear_amenossea_lgt_feet_a.dds",
      "greatsword": "/esoui/art/icons/gear_amenossea_2hsword_a.dds",
      "hands:*": "/esoui/art/icons/gear_amenossea_lgt_hands_a.dds",
      "head:*": "/esoui/art/icons/gear_amenossea_lgt_head_a.dds",
      "ice-staff": "/esoui/art/icons/gear_amenossea_staff_a.dds",
      "inferno-staff": "/esoui/art/icons/gear_amenossea_staff_a.dds",
      "legs:*": "/esoui/art/icons/gear_amenossea_lgt_legs_a.dds",
      "lightning-staff": "/esoui/art/icons/gear_amenossea_staff_a.dds",
      "mace": "/esoui/art/icons/gear_amenossea_mace_a.dds",
      "maul": "/esoui/art/icons/gear_amenossea_2hmace_a.dds",
      "necklace": "/esoui/art/icons/gear_breton_neck_a.dds",
      "restoration-staff": "/esoui/art/icons/gear_amenossea_staff_a.dds",
      "ring": "/esoui/art/icons/gear_breton_ring_a.dds",
      "shield": "/esoui/art/icons/gear_amenossea_sheild_a.dds",
      "shoulders:*": "/esoui/art/icons/gear_amenossea_lgt_shoulder_a.dds",
      "sword": "/esoui/art/icons/gear_amenossea_sword_a.dds",
      "waist:*": "/esoui/art/icons/gear_amenossea_lgt_waist_a.dds",
    },
  },
  {
    id: "perfected-wild-impulse",
    name: "Perfected Wild Impulse",
    esoSetId: 427,
    subcategoryId: "arena",
    valid: ["inferno-staff", "ice-staff", "lightning-staff"],
    bonuses: [
      {
        count: 2,
        status: "unsupported",
        effects: [],
        description:
          "Reduce the cost of Impulse by 10%. Impulse places lingering elemental damage on your targets, dealing 605 Flame, 605 Shock, and 605 Frost Damage over 8 seconds. Each element ticks once over the duration and its damage scales off the higher of your Weapon or Spell Damage.",
      },
    ],
    icons: {
      "ice-staff": "/esoui/art/icons/gear_honorguard_staff_a.dds",
      "inferno-staff": "/esoui/art/icons/gear_honorguard_staff_a.dds",
      "lightning-staff": "/esoui/art/icons/gear_honorguard_staff_a.dds",
    },
  },
  {
    id: "perfected-wrath-of-elements",
    name: "Perfected Wrath of Elements",
    esoSetId: 567,
    subcategoryId: "arena",
    valid: ["inferno-staff", "ice-staff", "lightning-staff"],
    bonuses: [
      {
        count: 2,
        status: "unsupported",
        effects: [],
        description:
          "Casting Weakness to Elements on a target within 15 meters of you causes a surge of elemental energy to tether between you for 10 seconds.  While the tether persists, enemies touching the tether take 331 Flame Damage, 331 Shock Damage, or 331 Frost Damage every 1 second, which increases by 1% each time it deals damage, up to 20%. This effect can occur once every 10 seconds, and scales off the higher of your Weapon or Spell Damage.",
      },
    ],
    icons: {
      "ice-staff": "/esoui/art/icons/gear_reachv2_staff_a.dds",
      "inferno-staff": "/esoui/art/icons/gear_reachv2_staff_a.dds",
      "lightning-staff": "/esoui/art/icons/gear_reachv2_staff_a.dds",
    },
  },
  {
    id: "perfected-xoryns-masterpiece",
    name: "Perfected Xoryn's Masterpiece",
    esoSetId: 770,
    subcategoryId: "trial",
    valid: ["*:light"],
    bonuses: [
      {
        count: 2,
        status: "supported",
        effects: [{ metricId: "magicka-maximum", effectType: "integer", effectValue: 1096 }],
        description: "Adds 1096 Maximum Magicka",
      },
      {
        count: 3,
        status: "unsupported",
        effects: [],
        description:
          "Gain Minor Aegis at all times, reducing your damage taken from Dungeon, Trial, and Arena Monsters by 5%.",
      },
      {
        count: 4,
        status: "supported",
        effects: [{ metricId: "magicka-recovery", effectType: "integer", effectValue: 129 }],
        description: "Adds 129 Magicka Recovery",
      },
      {
        count: 5,
        status: "unsupported",
        effects: [],
        description:
          "Increases Max Magicka and Max Stamina by 1667 for you and up to 11 other group members within 28 meters of you. This bonus persists through death.",
      },
    ],
    icons: {
      "axe": "/esoui/art/icons/gear_lucentguardian_1haxe_a.dds",
      "battleaxe": "/esoui/art/icons/gear_lucentguardian_2haxe_a.dds",
      "bow": "/esoui/art/icons/gear_lucentguardian_bow_a.dds",
      "chest:*": "/esoui/art/icons/gear_lucentguardian_light_robe_a.dds",
      "dagger": "/esoui/art/icons/gear_lucentguardian_dagger_a.dds",
      "feet:*": "/esoui/art/icons/gear_lucentguardian_light_feet_a.dds",
      "greatsword": "/esoui/art/icons/gear_lucentguardian_2hsword_a.dds",
      "hands:*": "/esoui/art/icons/gear_lucentguardian_light_hands_a.dds",
      "head:*": "/esoui/art/icons/gear_lucentguardian_light_head_a.dds",
      "ice-staff": "/esoui/art/icons/gear_lucentguardian_staff_a.dds",
      "inferno-staff": "/esoui/art/icons/gear_lucentguardian_staff_a.dds",
      "legs:*": "/esoui/art/icons/gear_lucentguardian_light_legs_a.dds",
      "lightning-staff": "/esoui/art/icons/gear_lucentguardian_staff_a.dds",
      "mace": "/esoui/art/icons/gear_lucentguardian_1hhammer_a.dds",
      "maul": "/esoui/art/icons/gear_lucentguardian_2hhammer_a.dds",
      "necklace": "/esoui/art/icons/gear_breton_neck_a.dds",
      "restoration-staff": "/esoui/art/icons/gear_lucentguardian_staff_a.dds",
      "ring": "/esoui/art/icons/gear_breton_ring_a.dds",
      "shield": "/esoui/art/icons/gear_lucentguardian_shield_a.dds",
      "shoulders:*": "/esoui/art/icons/gear_lucentguardian_light_shoulder_a.dds",
      "sword": "/esoui/art/icons/gear_lucentguardian_1hsword_a.dds",
      "waist:*": "/esoui/art/icons/gear_lucentguardian_light_waist_a.dds",
    },
  },
  {
    id: "perfected-yandirs-might",
    name: "Perfected Yandir's Might",
    esoSetId: 499,
    subcategoryId: "trial",
    valid: ["*:medium"],
    bonuses: [
      {
        count: 2,
        status: "supported",
        effects: [{ metricId: "power", effectType: "integer", effectValue: 129 }],
        description: "Adds 129 Weapon and Spell Damage",
      },
      {
        count: 3,
        status: "unsupported",
        effects: [],
        description:
          "Gain Minor Slayer at all times, increasing your damage done to Dungeon, Trial, and Arena Monsters by 5%.",
      },
      {
        count: 4,
        status: "supported",
        effects: [{ metricId: "power", effectType: "integer", effectValue: 129 }],
        description: "Adds 129 Weapon and Spell Damage",
      },
      {
        count: 5,
        status: "unsupported",
        effects: [],
        description:
          "Dealing Critical Damage increases your Weapon and Spell Damage by 86, stacking up to 5 times. This effect can occur once every 0.5 seconds.\n\nCompleting a fully-charged Heavy Attack removes all stacks and increases your Weapon and Spell Damage by 136 per stack removed.\n\nYou cannot have both effects active at the same time.",
      },
    ],
    icons: {
      "axe": "/esoui/art/icons/gear_seagiant_axe.dds",
      "battleaxe": "/esoui/art/icons/gear_seagiant_2haxe.dds",
      "bow": "/esoui/art/icons/gear_seagiant_bow.dds",
      "chest:*": "/esoui/art/icons/gear_seagiantmed_chest.dds",
      "dagger": "/esoui/art/icons/gear_seagiant_dagger.dds",
      "feet:*": "/esoui/art/icons/gear_seagiantmed_feet.dds",
      "greatsword": "/esoui/art/icons/gear_seagiant_2hsword.dds",
      "hands:*": "/esoui/art/icons/gear_seagiantmed_hands.dds",
      "head:*": "/esoui/art/icons/gear_seagiantmed_head.dds",
      "ice-staff": "/esoui/art/icons/gear_seagiant_staff.dds",
      "inferno-staff": "/esoui/art/icons/gear_seagiant_staff.dds",
      "legs:*": "/esoui/art/icons/gear_seagiantmed_legs.dds",
      "lightning-staff": "/esoui/art/icons/gear_seagiant_staff.dds",
      "mace": "/esoui/art/icons/gear_seagiant_mace.dds",
      "maul": "/esoui/art/icons/gear_seagiant_2hmace.dds",
      "necklace": "/esoui/art/icons/gear_breton_neck_a.dds",
      "restoration-staff": "/esoui/art/icons/gear_seagiant_staff.dds",
      "ring": "/esoui/art/icons/gear_breton_ring_a.dds",
      "shield": "/esoui/art/icons/gear_seagiant_shield.dds",
      "shoulders:*": "/esoui/art/icons/gear_seagiantmed_shoulders.dds",
      "sword": "/esoui/art/icons/gear_seagiant_sword.dds",
      "waist:*": "/esoui/art/icons/gear_seagiantmed_waist.dds",
    },
  },
]
