[Desktop Entry]
Exec=/home/walton/repos/akasha/machines/provisioning/scripts/wallpaper-black/wallpaper-black.shell-script.shell.sh
Name=Wallpaper Black
NoDisplay=true
StartupNotify=false
Type=Application
X-KDE-GlobalAccel-CommandShortcut=true
