apiVersion: v1
kind: Secret
metadata:
    name: archive-of-worlds-secrets
    namespace: archive-of-worlds
type: Opaque
stringData:
    GIT_ACCESS_TOKEN: ENC[AES256_GCM,data:TuxcVEX1nj+qVF18hy40rEaNwxMS7nZHgYvrarjLh6CLHlYnBeWfNQ==,iv:EqfaPD7WDx0noSm6ej/KWx9ydVuZW+sywlktk5xuIAE=,tag:e5DX3UG6v/wUcmq/dLWtpQ==,type:str]
    NEXT_PUBLIC_SUPABASE_ANON_KEY: ENC[AES256_GCM,data:dh+GTlsj1yFaEo9mCkMzJObK0ywK5rYRoflH6QjiChYRMXIY4N1WrJAX+m6F4GmzUsqELSh5H5zXZaT38AeuXh9dsyUXPyFH2AiHjg0X+T2BmSPs0L7/WwHjQc1FTO1R/j++gC04anYvz8+zug3n4h0BtuN9XA9wkC77BABGvy0RTxA7cY7SxWM5cmaZybgCRQQTT103t8cyY0JAvbrO+fY+gYKAhCca2pMC6PFaQe15I2WYSqTQ7n1AYoTZOIuezdjKmqMbpPts9u/noUWZ566KAL4qnF9xeppXn51337oA72ByQqtCCzMxpn+9GpevQXN8HEJ5vCY4vobUTz1uODCa+HQA7e4bQ+XRg5DU6beT8qkNhxQCszb1e3NeRUWOjJXEfGGFj6nAi3Fi58mBm2+Yoq5kEe/6RKaJocfC6cuUF7mwm/xsbBizNAZPhnOsMcXdTteDy48kHDfJpi5mkvVAzGX1fcUOpspewtjrBpwas75z4V9Kav1ecDP7ns5hpJWFuHvYSTXs6aPcvJwPg5DPu5hzPGeEH1XmQxEQUhIPIkf/tAGJLtKKgpB2z6vbFHflcuonjlJ/+u2zsWrKIdvgL6cSJufn5mE0dLv/U9uJnqd09fqFU1nRI3tXjXdi0qlQ/cxtHqn8ipoM9/g4dGWhVMJFCNfF8JCOGJ7Mbdf80Y+MPztpqMxMrp6cAI0zW+JaLPT9y0cqwUBPKttFWhpKSuXSsmbsZdO97lKez/ol23qcNlgwVTOJ93UV0zmIvecfgVVln5QqNrRzO9/x/UeaLrz2D0YcIDCm/KZeHsSejEQRMwngmbtn17xLWDNUiU1AK7NEFx9Nm7siC4Q76DuA8yeS91I/WjSws4ZnyhUok65qHta+egvasNUKmfR8ldXLNnUbSjkH5ueeivi3yZMPa4M6+9oQ40Ww7tjtFzLBjH1lXnvvY7oNgIjM3qzuXAQuQtq40/Ysxx43zV+ovCpUdIIHela6NdgMx/siAtU1A8EP+hHb3jLZY/BXZ9t5,iv:+RwGewGC7tI0QnOAXU6Zh/8nt4QXerWDJo8UAkeaz7c=,tag:7HaSJxOYnm+7D+M9H+BxrA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2ZHlERlNFVE9BNElodmpM
            ODlXK055b0ZMVDlGSnV0U29QTXJqakdCQlRBCkp2c0ZYVkFKM2FCT1BJSUVuUDB5
            VzJnbWFKK0JnalRHY2ZLREZKZ04rNHcKLS0tIDNGbHMxTGdkRUdwQkpNVllCdDhN
            cklSV2Z5MlFLeFRMYkRid002aVArT2MKZuFEWKPsIl/s32Ac7thF/4WUyqEp/bLd
            8MvIx3fdy3FRwbOpZynMIlyVfLMbVaXJQ9LpNeK5KuuqmAx4u0AynA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-28T02:24:39Z"
    mac: ENC[AES256_GCM,data:XIhrgDma7QaC62y7OGgci/5xJ7SybXVSN/JSSHCL1Zu9feFgFv9vAeholp5kFE0KEOTi97EFQd3cdOqYFGY/XY4q2rxF3rLY42o/Avg1MDJ3+PHvnlaJ/cOOBJqaBgKzTAGgkW46rafL4Ok32Kos6jCNyORgjcod3OtqVInxxPM=,iv:T9A+/jAECJunpK1EGINfT1PZ6PpxEdcGmF0DBQ1c5mc=,tag:akbdYQTarTllbCiO6hNCEw==,type:str]
    version: 3.13.1
