import type { Lore } from "akasha/story/lore/lore.page-type.types.ts"

export const theFourLaborsTheFoundingFork = {
  id: "01a0ddff-b8bd-7276-83dc-381b36366bf7",
  type: "page-type/lore",
  slug: "the-four-labors-the-founding-fork",
  title: "The Four Labors (the founding fork)",
  world: "world/cornerstone",
  loreDisclosure: "lore-disclosure/wiki",
  facts: [
    "The settlers had a loud, churning camp-wide argument that did not resolve into one will.",
    "The camp's will broke into four, and the settlers began four labors at once.",
    "The four labors broke over the core's body like four different weathers over one field.",
    "Each labor is born of a different wanting.",
    "The core discovers it can want, and reaches to lean its will toward one labor.",
    "The first labor is a watch-stack on the rise.",
    "For the watch-stack, stone is hauled uphill and stacked high to watch the frontier from.",
    "The watch-stack is born of fear of the hunting dark, where the Circling Hunter prowls.",
    "The watch-stack is the wish for eyes, so nothing crosses the edge unseen.",
    "The watch-stack would end the core's blindness past the rim.",
    "The second labor is a common hearth at the center, over the night-coal.",
    "The hearth is a pit not deep but wide, at the camp's heart, for a lasting fire ringed for all.",
    "The hearth is born of cold and grief and fraying.",
    "The hearth is the wish for a heart to gather round, so no one quietly slips away into the dark.",
    "The hearth would let the core feel the people's inner weather, the child's fear from inside.",
    "The third labor is a storehouse and granary.",
    "The storehouse is the most patient work of all: not a digging but a raising.",
    "The storehouse is a broad floor framed off the center, walled.",
    "The harvest is carried into the storehouse to keep: grain in sacks, racks and bins.",
    "In the store, sacks are set down in rows with the dense weight of grain meant to be kept.",
    "In the store, racks and bins fill with the dry hung lightness of things put by.",
    "The storehouse is born of practicality and an already-felt shortfall.",
    "The storehouse's wanting is to keep.",
    "The store holds the land's giving while the giving is good, against the season's turn.",
    "When the land gives nothing, the store is to have weight to set against the want.",
    "The store is so the settlers do not die of the thin frontier.",
    "The storehouse would let the core feel the land's yield and the coming of want.",
    "The storehouse would let the core feel the filling and the emptying.",
    "The fourth labor, the Marker-Stone, is a raised standing-stone by the grave.",
    "The standing-stone is a single great worked stone set upright.",
    "The standing-stone marks the dead and the founding.",
    "The stone marks the ground forever as where the dead are held and the living remember them.",
    "The Marker-Stone is the one labor that reaches toward the core's lost name.",
    "Each labor belongs to a Faculty of the core.",
    "The watch-stack belongs to Sight, the hearth to Warmth.",
    "The storehouse belongs to Provision, the standing-stone to Memory.",
    "Provision is a store above ground, gathered and kept, of scarcity and yield.",
    "Provision is not a downward dig; a shallow draw-well would still be Provision.",
    "A well or deep shaft, a downward extent, belongs to the Reach Faculty.",
    "The core leans its will toward exactly one labor.",
    "The first foundation pressed down wakes the Faculty its labor belongs to.",
    "The other three Faculties stay dormant for now.",
    "Each labor is a door, and only one opens first.",
  ],
} as const satisfies Lore
