import type { Domain } from "akasha/domains/domain.page-type.types.ts"

export const temperWatcher = {
  id: "01a06039-9c87-70d4-a728-02d7341ee89e",
  type: "domain",
  slug: "temper-watcher",
  definition: "what carries what Alan did in the game across to the web",
  parts: [
    "container-recipe/temper-watcher-image",
    "module/watcher-account-page",
    "module/watcher-daemon",
    "module/watcher-dispatch",
    "module/watcher-dispatch-handling",
    "module/watcher-error-cursor",
    "module/watcher-error-emissions",
    "module/watcher-export-companion-builds",
    "module/watcher-export-settings",
    "module/watcher-export-tasks",
    "module/watcher-file-type",
    "module/watcher-import-companions",
    "module/watcher-import-completion",
    "module/watcher-import-inventory",
    "module/watcher-import-item-rule-verdicts",
    "module/watcher-import-tasks",
    "module/watcher-inventory-snapshot-name",
    "module/watcher-log-line",
    "module/watcher-log-merging",
    "module/watcher-logging",
    "module/watcher-main",
    "module/watcher-net-worth-landing",
    "module/watcher-page-landing",
    "module/watcher-paths",
    "module/watcher-pricing-tables",
    "module/watcher-retry",
    "module/watcher-run-observing",
    "module/watcher-run-outcome",
    "module/watcher-running",
    "module/watcher-runtime",
    "module/watcher-self-write-guard",
    "module/watcher-server-url",
    "module/watcher-settings-consumables",
    "module/watcher-settings-lua-block",
    "module/watcher-settings-normalize",
    "module/watcher-side-file",
    "module/watcher-signed-in-user",
    "module/watcher-stable-read",
    "module/watcher-state",
    "module/watcher-task-landing",
    "module/watcher-task-progress",
    "module/watcher-task-progress-landing",
    "module/watcher-token",
    "module/watcher-token-check",
    "module/watcher-unit",
    "module/watcher-upload-retry",
    "module/watcher-config",
    "module/watcher-config-file",
    "module/watcher-import-catalog",
    "module/watcher-import-characters",
    "module/watcher-import-data-mining",
    "module/watcher-import-errors",
    "module/watcher-import-sales",
    "module/watcher-run-reporting",
    "module/watcher-settings-equipment",
    "module/watcher-task-capture",
    "module/watcher-task-rolling",
    "module/watcher-updating",
    "module/watcher-version",
    "module/watcher-worker",
    "service-workstation/temper-watcher",
  ],
  invariants: [
    {
      invariantKind: "departure",
      statement: "One worker runs at a time.",
    },
    {
      invariantKind: "departure",
      statement:
        "Whether the watcher is carrying anything across is judged from outside the watcher.",
    },
    {
      invariantKind: "departure",
      statement: "A dead daemon reports nothing about itself.",
    },
    {
      invariantKind: "constraint",
      statement: "The watcher runs on the workstation the game writes its files on.",
    },
    {
      invariantKind: "departure",
      statement: "The watcher reaches every page over pages-service rather than over the checkout.",
    },
  ],
} as const satisfies Domain
