import type { CrutchStringId } from "akasha/temper/addon/pages/combat/modules/combat-alerts-lang-ids/combat-alerts-lang-ids.module.code.ts"

export const CRUTCH_BOSS_STRINGS_EN: Partial<Record<CrutchStringId, string>> = {
  CRUTCH_BHB_AGHAEDH_OF_THE_SOLSTICE: "Aghaedh of the Solstice",
  CRUTCH_BHB_ANALA_TUWHA: "Anal'a Tu'wha",
  CRUTCH_BHB_ANSUUL_THE_TORMENTOR: "Ansuul the Tormentor",
  CRUTCH_BHB_ANTHELMIRS_CONSTRUCT: "Anthelmir's Construct",
  CRUTCH_BHB_ARADROS_THE_AWAKENED: "Aradros the Awakened",
  CRUTCH_BHB_ARCHDRUID_DEVYRIC: "Archdruid Devyric",
  CRUTCH_BHB_ARCHIVIST_ERNARDE: "Archivist Ernarde",
  CRUTCH_BHB_ARGENT_EXARCH_MOLONACH: "Argent Exarch Molonach^M",
  CRUTCH_BHB_ARKASIS_THE_MAD_ALCHEMIST: "Arkasis the Mad Alchemist",
  CRUTCH_BHB_ASSEMBLY_GENERAL: "Assembly General",
  CRUTCH_BHB_ATARUS: "Atarus",
  CRUTCH_BHB_BALORGH: "Balorgh",
  CRUTCH_BHB_BLAZEFORGED_VALNEER: "Blazeforged Valneer^M",
  CRUTCH_BHB_CAILLAOIFE: "Caillaoife",
  CRUTCH_BHB_CAPTAIN_GEMINUS: "Captain Geminus",
  CRUTCH_BHB_CAPTAIN_NUMIRRIL: "Captain Numirril",
  CRUTCH_BHB_CAPTAIN_VROL: "Captain Vrol",
  CRUTCH_BHB_CHAMPION_MARCAULD: "Champion Marcauld",
  CRUTCH_BHB_CORRUPTION_OF_ROOT: "Corruption of Root",
  CRUTCH_BHB_CORRUPTION_OF_STONE: "Corruption of Stone",
  CRUTCH_BHB_COUNCILOR_VANDACIA: "Councilor Vandacia",
  CRUTCH_BHB_DARK_ORB: "Dark Orb^n",
  CRUTCH_BHB_DARKSHARD: "Darkshard",
  CRUTCH_BHB_DEATHS_LEVIATHAN: "Death's Leviathan",
  CRUTCH_BHB_DEFENSE_PRISM: "Defense Prism^n",
  CRUTCH_BHB_DOMIHAUS_THE_BLOODYHORNED: "Domihaus the Bloody-Horned",
  CRUTCH_BHB_DOYLEMISH_IRONHEART: "Doylemish Ironheart",
  CRUTCH_BHB_DRANOS_VELADOR: "Dranos Velador",
  CRUTCH_BHB_DROZAKAR: "Dro'zakar",
  CRUTCH_BHB_EARTHEN_HEART_KNIGHT: "Earthen Heart Knight",
  CRUTCH_BHB_EARTHGORE_AMALGAM: "Earthgore Amalgam",
  CRUTCH_BHB_ELIAM_MERICK: "Eliam Merick",
  CRUTCH_BHB_ETERNAL_AEGIS: "Eternal Aegis",
  CRUTCH_BHB_EXARCHANIC_YASEYLA: "Exarchanic Yaseyla",
  CRUTCH_BHB_FLAMEHERALD_BAHSEI: "Flame-Herald Bahsei",
  CRUTCH_BHB_FOREMAN_BRADIGGAN: "Foreman Bradiggan",
  CRUTCH_BHB_GARVIN_THE_TRACKER: "Garvin the Tracker",
  CRUTCH_BHB_GEMCARVER_HYNAX: "Gemcarver Hynax",
  CRUTCH_BHB_GHEMVAS_THE_HARBINGER: "Ghemvas the Harbinger",
  CRUTCH_BHB_GILDED_ALZIRIIX: "Gilded Alziriix^F",
  CRUTCH_BHB_GILDED_BKYFXI: "Gilded B'Kyfxi^F",
  CRUTCH_BHB_GILDED_FATELINES_KNELL: "Gilded Fateline's Knell^F",
  CRUTCH_BHB_GRUNDWULF: "Grundwulf",
  CRUTCH_BHB_HAKGRYM_THE_HOWLER: "Hakgrym the Howler",
  CRUTCH_BHB_HEDGE_MAZE_GUARDIAN: "Hedge Maze Guardian",
  CRUTCH_BHB_HIATH_THE_BATTLEMASTER: "Hiath the Battlemaster",
  CRUTCH_BHB_HIGH_SOULBINDER_VYKAND: "High Soulbinder Vykand^F",
  CRUTCH_BHB_HUNTERKILLER_NEGATRIX: "Hunter-Killer Negatrix",
  CRUTCH_BHB_IBOMEZ_THE_FLESH_SCULPTOR: "Ibomez the Flesh Sculptor",
  CRUTCH_BHB_ICESTALKER: "Icestalker",
  CRUTCH_BHB_JAILER_MELITUS: "Jailer Melitus",
  CRUTCH_BHB_JERENSI: "Executioner Jerensi",
  CRUTCH_BHB_JYNORAH: "Jynorah^F",
  CRUTCH_BHB_KEEPER_OF_THE_KILN: "Keeper of the Kiln",
  CRUTCH_BHB_KJALNAR_TOMBSKALD: "Kjalnar Tombskald",
  CRUTCH_BHB_KOVAN_GIRYON: "Kovan Giryon",
  CRUTCH_BHB_KRAGH_THE_DREUGH_KING: "Kra'gh the Dreugh King",
  CRUTCH_BHB_KUJO_KETHBA: "Kujo Kethba",
  CRUTCH_BHB_LAATVULON: "Laatvulon",
  CRUTCH_BHB_LADY_BELAIN: "Lady Belain",
  CRUTCH_BHB_LADY_MINARA: "Lady Minara",
  CRUTCH_BHB_LADY_THORN: "Lady Thorn",
  CRUTCH_BHB_LOKKESTIIZ: "Lokkestiiz",
  CRUTCH_BHB_LORD_FALGRAVN: "Lord Falgravn",
  CRUTCH_BHB_LORD_WARDEN_DUSK: "Lord Warden Dusk",
  CRUTCH_BHB_LYLANAR: "Lylanar",
  CRUTCH_BHB_MAARSELOK: "Maarselok",
  CRUTCH_BHB_MAGMA_INCARNATE: "Magma Incarnate",
  CRUTCH_BHB_MALIGALIG: "Maligalig",
  CRUTCH_BHB_MATRIARCH_ALDIS: "Matriarch Aldis",
  CRUTCH_BHB_MATRIARCH_LLADI_TELVANNI: "Matriarch Lladi Telvanni",
  CRUTCH_BHB_MAVUS_TALNARITH: "Mavus Talnarith",
  CRUTCH_BHB_MISURA_ASSISTANT_TO_THE_HIGH_SOULBINDER: "Misura, Assistant to the High Soulbinder",
  CRUTCH_BHB_MOLAG_KENA: "Molag Kena",
  CRUTCH_BHB_MULAAMNIR: "Mulaamnir",
  CRUTCH_BHB_MYLENNE_MOONCALLER: "Mylenne Moon-Caller",
  CRUTCH_BHB_NAHVIINTAAS: "Nahviintaas",
  CRUTCH_BHB_NERIENETH: "Nerien'eth",
  CRUTCH_BHB_NORIWEN: "Noriwen",
  CRUTCH_BHB_OAXILTSO: "Oaxiltso",
  CRUTCH_BHB_ONDAGORE_THE_MAD: "Ondagore the Mad",
  CRUTCH_BHB_ORPHEON_THE_TACTICIAN: "Orpheon the Tactician",
  CRUTCH_BHB_ORPHIC_SHATTERED_SHARD: "Orphic Shattered Shard",
  CRUTCH_BHB_OVERFIEND: "Overfiend",
  CRUTCH_BHB_OVERFIEND_KAZPIAN: "Overfiend Kazpian",
  CRUTCH_BHB_OZEZAN_THE_INFERNO: "Ozezan the Inferno",
  CRUTCH_BHB_PINNACLE_FACTOTUM: "Pinnacle Factotum",
  CRUTCH_BHB_PISHNA_LONGSHOT: "Pishna Longshot",
  CRUTCH_BHB_PROSPECTOR_LYRAKTA: "Prospector Lyrakta",
  CRUTCH_BHB_PYROTURGE_ENCRATIS: "Pyroturge Encratis",
  CRUTCH_BHB_QUARRYMASTER_SALDEZAAR: "Quarrymaster Saldezaar",
  CRUTCH_BHB_QUINTUS_VERRES: "Quintus Verres",
  CRUTCH_BHB_RA_KOTU: "Ra Kotu",
  CRUTCH_BHB_RAKKHAT: "Rakkhat",
  CRUTCH_BHB_REACTOR: "Reactor",
  CRUTCH_BHB_REEF_GUARDIAN: "Reef Guardian",
  CRUTCH_BHB_RIFTMASTER_NAQRI: "Riftmaster Naqri",
  CRUTCH_BHB_RISEN_RUINS: "Risen Ruins",
  CRUTCH_BHB_ROKSA_THE_WARPED: "Roksa the Warped",
  CRUTCH_BHB_SAINT_FELMS_THE_BOLD: "Saint Felms the Bold^M",
  CRUTCH_BHB_SAINT_LLOTHIS_THE_PIOUS: "Saint Llothis the Pious^M",
  CRUTCH_BHB_SAINT_OLMS_THE_JUST: "Saint Olms the Just",
  CRUTCH_BHB_SARYDIL: "Sarydil",
  CRUTCH_BHB_SCORION_BROODLORD: "Scorion Broodlord",
  CRUTCH_BHB_SENTINEL_AKSALAZ: "Sentinel Aksalaz",
  CRUTCH_BHB_SHADE_OF_GALENWE: "Shade of Galenwe^M",
  CRUTCH_BHB_SHADE_OF_RELEQUEN: "Shade of Relequen^M",
  CRUTCH_BHB_SHADE_OF_SIRORIA: "Shade of Siroria",
  CRUTCH_BHB_SHATTERED_CHAMPION: "Shattered Champion",
  CRUTCH_BHB_SIEGE_MASTER_MALTHORAS: "Siege Master Malthoras",
  CRUTCH_BHB_SITHERA: "Sithera",
  CRUTCH_BHB_SPARKSTORM_MYRINAX: "Sparkstorm Myrinax^F",
  CRUTCH_BHB_SQUALL_OF_RETRIBUTION: "Squall of Retribution",
  CRUTCH_BHB_STONEHEART: "Stoneheart",
  CRUTCH_BHB_STORMBORN_REVENANT: "Stormborn Revenant",
  CRUTCH_BHB_SYMPHONY_OF_BLADES: "Symphony of Blades",
  CRUTCH_BHB_TALENLAH: "Talen-Lah",
  CRUTCH_BHB_TAMESTHEBEAST: "Tames-the-Beast",
  CRUTCH_BHB_TARCYR: "Tarcyr",
  CRUTCH_BHB_TASKMASTER_VICCIA: "Taskmaster Viccia",
  CRUTCH_BHB_THE_BLIND: "The Blind",
  CRUTCH_BHB_THE_MAGE: "The Mage",
  CRUTCH_BHB_THE_PYRELORD: "The Pyrelord",
  CRUTCH_BHB_THE_SCAVENGING_MAW: "The Scavenging Maw",
  CRUTCH_BHB_THE_STONEKEEPER: "The Stonekeeper",
  CRUTCH_BHB_THE_WARRIOR: "The Warrior",
  CRUTCH_BHB_THE_WEEPING_WOMAN: "The Weeping Woman",
  CRUTCH_BHB_THOAT_REPLICANUM: "Tho'at Replicanum",
  CRUTCH_BHB_THOAT_SHARD: "Tho'at Shard",
  CRUTCH_BHB_THURVOKUN: "Thurvokun",
  CRUTCH_BHB_TIDEBORN_TALERIA: "Tideborn Taleria",
  CRUTCH_BHB_TREEMINDER_NAKESH: "Tree-Minder Na-Kesh",
  CRUTCH_BHB_VALINNA: "Valinna",
  CRUTCH_BHB_VAMPIRE_LORD_THISA: "Vampire Lord Thisa",
  CRUTCH_BHB_VANDORALLEN: "Prime Sorcerer Vandorallen",
  CRUTCH_BHB_VARALLION: "Varallion",
  CRUTCH_BHB_VAULT_PROTECTOR: "Vault Protector",
  CRUTCH_BHB_VELIDRETH: "Velidreth",
  CRUTCH_BHB_VORENOR_WINTERBOURNE: "Vorenor Winterbourne",
  CRUTCH_BHB_VORIA_THE_HEARTTHIEF: "Voria the Heart-Thief",
  CRUTCH_BHB_VOSKRONA_STONEHULK_POXITO: "Voskrona Stonehulk Poxito",
  CRUTCH_BHB_VYKOSA_THE_ASCENDANT: "Vykosa the Ascendant",
  CRUTCH_BHB_WARLORD_TZOGVIN: "Warlord Tzogvin",
  CRUTCH_BHB_XALVAKKA: "Xalvakka",
  CRUTCH_BHB_XEEMHOK_THE_TROPHYTAKER: "Xeemhok the Trophy-Taker",
  CRUTCH_BHB_YANDIR_THE_BUTCHER: "Yandir the Butcher",
  CRUTCH_BHB_YOLNAHKRIIN: "Yolnahkriin",
  CRUTCH_BHB_ZAAN_THE_SCALECALLER: "Zaan the Scalecaller",
  CRUTCH_BHB_ZBAZA: "Z'Baza",
  CRUTCH_BHB_ZELVRAAK_THE_UNBREATHING: "Zelvraak the Unbreathing",
  CRUTCH_BHB_ZHAJHASSA_THE_FORGOTTEN: "Zhaj'hassa the Forgotten",
  CRUTCH_BHB_ZMAJA: "Z'Maja^F",
  CRUTCH_CSA_ARID_VARLET_ESSENCE_COBWEBS: "Arid Varlet Essence Appeared in the Cobwebs",
  CRUTCH_CSA_ARID_VARLET_ESSENCE_ECLIPSE: "Arid Varlet Essence Appeared in the Eclipse",
  CRUTCH_CSA_KNIGHTSHADE_ESSENCE_COBWEBS: "Knightshade Essence Appeared in the Cobwebs",
  CRUTCH_CSA_KNIGHTSHADE_ESSENCE_DRYLANDS: "Knightshade Essence Appeared in the Drylands",
  CRUTCH_CSA_WEB_EATER_ESSENCE_DRYLANDS: "Web Eater Essence Appeared in the Drylands",
  CRUTCH_CSA_WEB_EATER_ESSENCE_ECLIPSE: "Web Eater Essence Appeared in the Eclipse",
}
