import type { Domain } from "akasha/domains/domain.page-type.types.ts"

export const page = {
  id: "01a04a26-9105-7000-ab9a-ee74f7657636",
  pageTypeSlug: "domain",
  type: "domain",
  slug: "page",
  definition: "how we keep track of things",

  parts: [
    "module/entry-ceiling",
    "module/markdown-document",
    "module/markdown-page-at",
    "module/markdown-page-name",
    "module/page-address",
    "module/page-beside",
    "module/page-body",
    "module/page-entries",
    "module/page-entry-landing",
    "module/page-entry-queue",
    "module/page-entry-writing",
    "module/page-export-name",
    "module/page-file-body",
    "module/page-file-name",
    "module/page-file-parts",
    "module/page-secret",
    "module/page-uncommitted",
    "module/page-value",
    "module/page-value-reading",
    "page-type/view",
    "page-type/nav",
    "page-type/page",
    "page-type/page-type",
    "page-type/text-property",
    "page-type/number-property",
    "page-type/computed-property",
    "page-type/computed-property-module",
    "page-type/boolean-property",
    "page-type/instant-property",
    "page-type/relation-property",
    "page-type/record-property",
    "page-type/one-of-property",
    "page-type/url-property",
    "page-type/calendar-date-property",
    "page-type/calendar-time-property",
    "page-type/select-property",
    "page-type/rank-property",
    "page-type/page-property-entry",
    "page-type/file-property",
    "page-type/code-file-property",
    "page-type/file-property-group",
    "page-type/phone-number-property",
    "page-type/email-address-property",
    "page-type/process-property",
    "page-type/name-format",
    "page-type/name-place",
    "page-type/generator-kind",
    "page-type/unique-kind",
    "page-type/page-address-kind",
    "domain/index",
    "domain/pages-query",
    "domain/pages-service",
    "domain/pages-core",
    "domain/pages-access",
    "domain/pages-ui-store",
    "domain/pages-url",
    "domain/pages-ui",
    "domain/naming",
    "domain/page-edge",
    "domain/page-storage",
    "module/change",
    "module/checkout-roots",
    "module/code-root",
    "module/page-answer-sweeping",
    "module/calculation-loading",
    "module/page-carry",
    "module/page-computing",
    "module/page-derive-shape",
    "module/page-landing-journal",
    "module/page-landing-judge",
    "module/page-narrow",
    "module/page-query-day",
    "module/page-query-hold",
    "module/page-query-keys",
    "module/page-query-narrow",
    "module/page-query-reduce",
    "module/page-query-request",
    "module/page-query-shape",
    "module/page-query-values",
    "module/page-value-key",
    "module/repo-path",
    "module/shadow",
    "module/akasha-page-values",
    "module/live-store-write-guard",
    "module/test-run-marking",
    "domain/page-commands",
    "page-type/named-folder-property",
    "page-type/named-extension-property",
    "page-type/build-folder-property",
    "service-workstation/sweep-page-answers",
    "module/type-keys",
    "domain/identity",
    "domain/id",
    "page-type/true-property",
    "page-type/false-property",
  ],
  invariants: [
    {
      invariantKind: "departure",
      statement: "Page types and page property types are themselves page types.",
    },
    {
      invariantKind: "departure",
      statement: "A page is a file whose name has a page type.",
    },
    {
      invariantKind: "departure",
      statement:
        "Code reaching the pages of a type asks the index rather than spelling their folder.",
    },
    {
      invariantKind: "departure",
      statement: "A page's code that lists a folder lists what the index does not hold.",
    },
  ],
} as const satisfies Domain
