export const LIB_SETS_PRELOADED_SET_NAMES_01: Record<number, Record<string, string>> = {
  [19]: {
    de: "Gewänder des Hexers",
    en: "Vestments of the Warlock",
    es: "Vestimentas del mago oscuro",
    fr: "Les Vêtements du sorcier",
    ru: "Одеяние чародея",
    zh: "法士装束",
  },
  [20]: {
    de: "Hexenwerk",
    en: "Witchman Armor",
    es: "Armadura del brujo",
    fr: "Armure d'homme-médecine",
    ru: "Доспех колдуна",
    zh: "巫师护甲",
  },
  [21]: {
    de: "Akavirische Drachengarde",
    en: "Akaviri Dragonguard",
    es: "Guardia del Dragón akaviri",
    fr: "La Garde du dragon akaviroise",
    ru: "Акавирская Драконья стража",
    zh: "阿卡维尔神龙卫",
  },
  [22]: {
    de: "Mantel des Träumers",
    en: "Dreamer's Mantle",
    es: "Manto del soñador",
    fr: "Manteau du rêveur",
    ru: "Накидка сновидца",
    zh: "空想家斗篷",
  },
  [23]: {
    de: "Schützensinn",
    en: "Archer's Mind",
    es: "Mente de arquero",
    fr: "L’Esprit de l'archer",
    ru: "Разум лучника",
    zh: "弓箭手思维",
  },
  [24]: {
    de: "Geschick des Fußsoldaten",
    en: "Footman's Fortune",
    es: "Fortuna del lacayo",
    fr: "La Chance du valet",
    ru: "Удача пехотинца",
    zh: "步兵之幸",
  },
  [25]: {
    de: "Wüstenrose",
    en: "Desert Rose",
    es: "Rosa del desierto",
    fr: "La Rose du désert",
    ru: "Пустынная роза",
    zh: "沙漠玫瑰",
  },
  [26]: {
    de: "Lumpen des Gefangenen",
    en: "Prisoner's Rags",
    es: "Harapos del prisionero",
    fr: "Les Haillons de prisonnier",
    ru: "Лохмотья узника",
    zh: "褴褛囚衣",
  },
  [27]: {
    de: "Fiords Erbe",
    en: "Fiord's Legacy",
    es: "Legado del fiordo",
    fr: "L’Héritage de Fiord",
    ru: "Наследие Фьорда",
    zh: "菲奥德的遗产",
  },
  [28]: {
    de: "Borkenhaut",
    en: "Barkskin",
    es: "Piel robliza",
    fr: "La Peau d'écorce",
    ru: "Древесный покров",
    zh: "树肤",
  },
  [29]: {
    de: "Rüstung des Feldwebels",
    en: "Sergeant's Mail",
    es: "Cota de sargento",
    fr: "La Cotte de mailles du sergent",
    ru: "Доспехи сержанта",
    zh: "中士的锁甲",
  },
  [30]: {
    de: "Donnerkäferpanzer",
    en: "Thunderbug's Carapace",
    es: "Caparazón de bicho de trueno",
    fr: "Carapace de foudroptère",
    ru: "Панцирь грозового жука",
    zh: "雷光虫的甲壳",
  },
  [31]: {
    de: "Sonnenseide",
    en: "Silks of the Sun",
    es: "Seda del sol",
    fr: "Les Atours du soleil",
    ru: "Шелка солнца",
    zh: "太阳之丝",
  },
  [32]: {
    de: "Bräuche des Heilers",
    en: "Healer's Habit",
    es: "Hábito del sanador",
    fr: "Le Froc du guérisseur",
    ru: "Мастерство целителя",
    zh: "治疗者的习惯",
  },
  [33]: {
    de: "Vipernbiss",
    en: "Viper's Sting",
    es: "Picadura de víbora",
    fr: "La Morsure de la vipère",
    ru: "Жало гадюки",
    zh: "毒蛇噬咬",
  },
  [34]: {
    de: "Umarmung der Mutter der Nacht",
    en: "Night Mother's Embrace",
    es: "Abrazo de la Madre Noche",
    fr: "Étreinte de la Mère de la nuit",
    ru: "Объятия Матери Ночи",
    zh: "夜母之拥",
  },
  [35]: {
    de: "Albtraumritter",
    en: "Knightmare",
    es: "Caballero del delirio",
    fr: "Le Chevalier-cauchemar",
    ru: "Кошмарный рыцарь",
    zh: "骑士梦魇",
  },
  [36]: {
    de: "Rüstung des Schleiererbes",
    en: "Armor of the Veiled Heritance",
    es: "Armadura de la Herencia Velada",
    fr: "Armure de l'Héritage voilé",
    ru: "Доспех Скрытого Наследия",
    zh: "面纱遗族护甲",
  },
  [37]: {
    de: "Todeswind",
    en: "Death's Wind",
    es: "Viento de la muerte",
    fr: "Le Vent mortel",
    ru: "Ветер смерти",
    zh: "死亡之风",
  },
  [38]: {
    de: "Zwielichtkuss",
    en: "Twilight's Embrace",
    es: "Abrazo del crepúsculo",
    fr: "L’Étreinte du crépuscule",
    ru: "Объятия сумрака",
    zh: "影暮之拥",
  },
  [39]: {
    de: "Alessianischer Orden",
    en: "Alessian Order",
    es: "Orden de Alessia",
    fr: "L’Ordre d'Alessia",
    ru: "Алессианский орден",
    zh: "阿莱西亚教团",
  },
  [40]: {
    de: "Stille der Nacht",
    en: "Night's Silence",
    es: "Silencio de la noche",
    fr: "Le Silence de la nuit",
    ru: "Молчание ночи",
    zh: "夜之寂静",
  },
  [41]: {
    de: "Weißplankes Vergeltung",
    en: "Whitestrake's Retribution",
    es: "Castigo de Descarga Blanca",
    fr: "La Rétribution de Blancserpent",
    ru: "Возмездие Вайтстрейка",
    zh: "怀特斯垂克的报复",
  },
  [43]: {
    de: "Rüstung der Verführung",
    en: "Armor of the Seducer",
    es: "Armadura de la seductora",
    fr: "L’Armure de la séductrice",
    ru: "Доспех соблазнителя",
    zh: "诱魔铠甲",
  },
  [44]: {
    de: "Kuss des Vampirs",
    en: "Vampire's Kiss",
    es: "Beso vampírico",
    fr: "Le Baiser du vampire",
    ru: "Поцелуй вампира",
    zh: "吸血鬼之吻",
  },
  [46]: {
    de: "Seide des edlen Duellanten",
    en: "Noble Duelist's Silks",
    es: "Atavíos del noble duelista",
    fr: "Atours du noble duelliste",
    ru: "Шелка благородного дуэлянта",
    zh: "高贵决斗者丝绸",
  },
  [47]: {
    de: "Roben der Verdorrten Hand",
    en: "Robes of the Withered Hand",
    es: "Túnica de la Mano Marchita",
    fr: "Robes de la Main de Gloire",
    ru: "Одежды Иссохшей Длани",
    zh: "枯手长袍",
  },
  [48]: {
    de: "Magnus' Gabe",
    en: "Magnus' Gift",
    es: "Don de Magnus",
    fr: "Le Présent de Magnus",
    ru: "Дар Магнуса",
    zh: "马格努斯的赠礼",
  },
  [49]: {
    de: "Schatten des Roten Berges",
    en: "Shadow of the Red Mountain",
    es: "Sombra de la Montaña Roja",
    fr: "L’Ombre du Mont Écarlate",
    ru: "Тень Красной горы",
    zh: "红山之影",
  },
  [50]: {
    de: "Morag Tong",
    en: "The Morag Tong",
    es: "El Morag Tong",
    fr: "La Morag Tong",
    ru: "Мораг Тонг",
    zh: "殁拉格帮",
  },
  [51]: {
    de: "Blick der Mutter der Nacht",
    en: "Night Mother's Gaze",
    es: "Mirada de la Madre Noche",
    fr: "Le Regard de la Mère de la nuit",
    ru: "Взгляд Матери Ночи",
    zh: "夜母的凝视",
  },
  [52]: {
    de: "Klingender Stahl",
    en: "Beckoning Steel",
    es: "Llamada del acero",
    fr: "L’Appel de l'acier",
    ru: "Манящая сталь",
    zh: "召集之钢",
  },
  [53]: {
    de: "Eisschmiede",
    en: "The Ice Furnace",
    es: "Fragua Gélida",
    fr: "Le Fourneau de glace",
    ru: "Ледяное горнило",
    zh: "寒冰熔炉",
  },
  [54]: {
    de: "Aschengriff",
    en: "Ashen Grip",
    es: "Yugo de ceniza",
    fr: "La Poigne de cendres",
    ru: "Пепельная хватка",
    zh: "灰烬之握",
  },
  [55]: {
    de: "Gebetstuch",
    en: "Prayer Shawl",
    es: "Mantón de oración",
    fr: "Châle de prière",
    ru: "Молитвенное покрывало",
    zh: "祈祷披肩",
  },
  [56]: {
    de: "Stendarrs Umarmung",
    en: "Stendarr's Embrace",
    es: "Abrazo de Stendarr",
    fr: "L’Étreinte de Stendarr",
    ru: "Объятия Стендарра",
    zh: "思坦达之拥",
  },
  [57]: {
    de: "Syrabanns Griff",
    en: "Syrabane's Grip",
    es: "Agarre de Syrabane",
    fr: "L’Emprise de Syrabane",
    ru: "Хватка Сирабейна",
    zh: "塞拉班之握",
  },
  [58]: {
    de: "Fell des Werwolfs",
    en: "Hide of the Werewolf",
    es: "Piel del hombre lobo",
    fr: "La Peau de loup-garou",
    ru: "Шкура вервольфа",
    zh: "狼人之皮",
  },
  [59]: {
    de: "Kynes Kuss",
    en: "Kyne's Kiss",
    es: "Beso de Kyne",
    fr: "Le Baiser de Kyne",
    ru: "Поцелуй Кин",
    zh: "凯恩之吻",
  },
  [60]: {
    de: "Dunkelschritt",
    en: "Darkstride",
    es: "Paso sombrío",
    fr: "Le Sentier obscur",
    ru: "Поступь тьмы",
    zh: "黑暗阔步",
  },
  [61]: {
    de: "Dreughkönigsschlächter",
    en: "Dreugh King Slayer",
    es: "Asesino del dreugh rey",
    fr: "Le Tueur du roi dreugh",
    ru: "Победитель короля дреугов",
    zh: "蟹灵王杀手",
  },
  [62]: {
    de: "Schlüpflingspanzer",
    en: "Hatchling's Shell",
    es: "Cascarón del retoño",
    fr: "Coquille du rejeton",
    ru: "Скорлупа детеныша",
    zh: "幼体之壳",
  },
  [63]: {
    de: "Koloss",
    en: "The Juggernaut",
    es: "Mastodonte",
    fr: "Le Mastodonte",
    ru: "Джаггернаут",
    zh: "主宰",
  },
  [64]: {
    de: "Kleidung des Schattentänzers",
    en: "Shadow Dancer's Raiment",
    es: "Vestimenta de bailarín de las sombras",
    fr: "La Parure du bateleur d'ombre",
    ru: "Одежды теневого танцора",
    zh: "暗影舞者装束",
  },
  [65]: {
    de: "Spur eines Blutdorns",
    en: "Bloodthorn's Touch",
    es: "Toque de la Espina Sangrienta",
    fr: "Toucher de Sangrépine",
    ru: "Касание Кровавого Шипа",
    zh: "血棘之触",
  },
  [66]: {
    de: "Roben des Hist",
    en: "Robes of the Hist",
    es: "Túnica del hist",
    fr: "Robes de l'Hist",
    ru: "Облачение хиста",
    zh: "希思特长袍",
  },
  [67]: {
    de: "Schattengänger",
    en: "Shadow Walker",
    es: "Caminante de las sombras",
    fr: "La Marcheuse d'ombres",
    ru: "Теневой ходок",
    zh: "暗影行者",
  },
  [68]: {
    de: "Stygier",
    en: "Stygian",
    es: "Estigio",
    fr: "Le Stygien",
    ru: "Зловещий",
    zh: "幽冥",
  },
  [69]: {
    de: "Laufstil des Waldläufers",
    en: "Ranger's Gait",
    es: "Andares del montaraz",
    fr: "La Parure de l'éclaireur",
    ru: "Поступь следопыта",
    zh: "游侠的身姿",
  },
  [70]: {
    de: "Rohling der Siebten Legion",
    en: "Seventh Legion Brute",
    es: "Bruto de la Séptima Legión",
    fr: "Brute de la septième Légion",
    ru: "Громила Седьмого легиона",
    zh: "第七军团之勇",
  },
  [71]: {
    de: "Duroks Fluch",
    en: "Durok's Bane",
    es: "Perdición de Durok",
    fr: "Le Fléau de Durok",
    ru: "Погибель Дарока",
    zh: "杜洛克的灾祸",
  },
  [72]: {
    de: "Nikulas' schwere Rüstung",
    en: "Nikulas' Heavy Armor",
    es: "Armadura pesada de Nikulas",
    fr: "L’Armure lourde de Nikulas",
    ru: "Тяжелые доспехи Никуласа",
    zh: "尼古拉斯的重甲",
  },
  [73]: {
    de: "Erinnerung",
    en: "Oblivion's Foe",
    es: "Enemigo de Oblivion",
    fr: "L’Adversaire d'Oblivion",
    ru: "Враг Обливиона",
    zh: "湮灭之敌",
  },
  [74]: {
    de: "Schemenauge",
    en: "Spectre's Eye",
    es: "Ojo de espectro",
    fr: "L’Œil du spectre",
    ru: "Глаз призрака",
    zh: "幽鬼之眼",
  },
  [75]: {
    de: "Torugs Pakt",
    en: "Torug's Pact",
    es: "Pacto de Torug",
    fr: "Le Pacte de Torug",
    ru: "Пакт Торуга",
    zh: "托拉格的契约",
  },
  [76]: {
    de: "Roben der Veränderungsbeherrschung",
    en: "Robes of Alteration Mastery",
    es: "Túnica de maestría en alteración",
    fr: "Les Robes de maîtrise de transformation",
    ru: "Облачение мастерства изменения",
    zh: "变化精通长袍",
  },
  [77]: {
    de: "Glaubenskrieger",
    en: "Crusader",
    es: "Cruzado",
    fr: "Le Croisé",
    ru: "Крестоносец",
    zh: "远征者",
  },
  [78]: {
    de: "Histrinde",
    en: "Hist Bark",
    es: "Corteza del hist",
    fr: "L’Écorce d'Hist",
    ru: "Кора хиста",
    zh: "希思特树皮",
  },
  [79]: {
    de: "Weidenpfad",
    en: "Willow's Path",
    es: "Sendero del sauce",
    fr: "Le Sentier des saules",
    ru: "Ивовая тропа",
    zh: "柳树小径",
  },
  [80]: {
    de: "Hundings Zorn",
    en: "Hunding's Rage",
    es: "Rabia de Hunding",
    fr: "La Rage de Hunding",
    ru: "Ярость Хандинга",
    zh: "亨丁之怒",
  },
  [81]: {
    de: "Lamaes Lied",
    en: "Song of Lamae",
    es: "Canción de Lamae",
    fr: "Le Chant de Lamae",
    ru: "Песнь Лами",
    zh: "拉玛耶之歌",
  },
  [82]: {
    de: "Alessias Bollwerk",
    en: "Alessia's Bulwark",
    es: "Baluarte de Alessia",
    fr: "Le Rempart d'Alessia",
    ru: "Бастион Алессии",
    zh: "阿莱西亚的壁垒",
  },
  [83]: {
    de: "Elfenfluch",
    en: "Elf Bane",
    es: "Perdición de los elfos",
    fr: "Le Fléau des Elfes",
    ru: "Бич эльфов",
    zh: "精灵之灾",
  },
  [84]: {
    de: "Orgnums Schuppen",
    en: "Orgnum's Scales",
    es: "Escamas de Orgnum",
    fr: "Les Écailles d'Orgnum",
    ru: "Чешуя Оргнума",
    zh: "奥格努姆之鳞",
  },
  [85]: {
    de: "Almalexias Gnade",
    en: "Almalexia's Mercy",
    es: "Piedad de Almalexia",
    fr: "La Clémence d'Almalexia",
    ru: "Милосердие Алмалексии",
    zh: "阿玛莱西亚的慈悲",
  },
  [86]: {
    de: "Eleganz der Königin",
    en: "Queen's Elegance",
    es: "Elegancia de la reina",
    fr: "Élégance de la reine",
    ru: "Элегантность королевы",
    zh: "女王之优雅",
  },
  [87]: {
    de: "Augen von Mara",
    en: "Eyes of Mara",
    es: "Ojos de Mara",
    fr: "Les Yeux de Mara",
    ru: "Глаза Мары",
    zh: "玛拉之眼",
  },
}
