import type { TemperSet } from "akasha/temper/catalog/gear/temper-set/temper-set.page-type.types.ts"

export const torcOfTheLastAyleidKing = {
  id: "019e6484-6041-7a15-a959-0ed692cc80b9",
  type: "page-type/temper-set",
  slug: "torc-of-the-last-ayleid-king",
  title: "Torc of the Last Ayleid King",
  key: "torc-of-the-last-ayleid-king",
  esoSetId: 693,
  hashPlace: 615,
  esoItemIds: [194511],
  esoEquipTypes: ["EQUIP_TYPE_NECK"],
  setWayshrines: [546, 546, 546],
  setTypeId: 12,
  setNameZh: "末代野精灵王之颈环",
  setNameRu: "Ожерелье последнего короля айлейдов",
  setNameFr: "Le torque du Dernier roi ayléide",
  setNameEs: "Torque del último rey ayleid",
  setNameDe: "Torques des letzten Ayleïdenkönigs",
  setDropZones: [1413, 1413, 1413, 1413, 1413],
  setDropMechanics: [37, 37, 37, 37, 37],
  setDropLocationNamesEn: [
    "Infinite Archive Chest",
    "Infinite Archive Chest",
    "Infinite Archive Chest",
    "Infinite Archive Chest",
    "Infinite Archive Chest",
  ],
  setDropLocationNamesDe: [
    "Endloses Archiv Truhe",
    "Endloses Archiv Truhe",
    "Endloses Archiv Truhe",
    "Endloses Archiv Truhe",
    "Endloses Archiv Truhe",
  ],
  setDlcId: 30,
  itemBrowserSources: ["-5"],
  itemBrowserPlaceKinds: [6],
  itemBrowserItemId: 194511,
  category: "temper-set-category/mythic",
  valid: ["necklace"],
  bonuses: "jsonl",
  icons: "jsonl",
} as const satisfies TemperSet
