import type { TemperSet } from "akasha/temper/catalog/gear/temper-set/temper-set.page-type.types.ts"

export const grothdarr = {
  id: "019e6484-5ff9-70e7-831e-db83ac174eb8",
  type: "page-type/temper-set",
  slug: "grothdarr",
  title: "Grothdarr",
  key: "grothdarr",
  esoSetId: 280,
  esoItemIds: [94580, 94716, 94852, 94988, 95124, 95260],
  esoArmorTypes: ["ARMORTYPE_HEAVY", "ARMORTYPE_LIGHT", "ARMORTYPE_MEDIUM"],
  esoEquipTypes: ["EQUIP_TYPE_HEAD", "EQUIP_TYPE_SHOULDERS"],
  setWayshrines: [184, 184, 184],
  setVeteranEquipTypes: ["EQUIP_TYPE_HEAD"],
  setUndauntedChestId: 1,
  setTypeId: 8,
  setNameZh: "格罗斯达尔",
  setNameRu: "Гротдарр",
  setNameFr: "Grothdarr",
  setNameEs: "Grothdarr",
  setNameDe: "Grothdarr",
  setDropZones: [11, 347, 347],
  setDropMechanics: [6],
  setDropLocationNamesEn: ["Mad Architect"],
  setDropLocationNamesDe: ["Der Verrückte Architekt"],
  setDlcId: 0,
  itemBrowserSources: ["11:-102"],
  itemBrowserPlaceKinds: [3],
  itemBrowserItemId: 94853,
  category: "temper-set-category/monster",
  valid: ["monster"],
  bonuses: "jsonl",
  icons: "jsonl",
} as const satisfies TemperSet
