apiVersion: v1
kind: Secret
metadata:
    name: realtime-secrets
    namespace: supabase-realtime
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:bWEuHTveSs9oOBkA828oLMleSzWRrzpReZ8XevkVHCiUim+3EtnytjHJIZF4AYEcItGVSDkqsbzqj7Ds3KPqGAS5PS5CvL9fVYaNDwUrm+S+CvTrXiE37V27aDyMfq0PkWjl3Fgdaa0kYvnV0a6xo6NFPVHFbQ+Ozs+dlGFe4pDBSYs=,iv:K1zI7LfHzT0sae4k9XtJ7nx8JKwtmlZaV9jWyFqQrrE=,tag:6cHr4CcP9KNnRloYhYP3QA==,type:str]
    DB_ENC_KEY: ENC[AES256_GCM,data:UXVfHsfIDYjqSgO7xtjLpQ==,iv:3hkEd7dZS9LEUt7Q23vX7ussRzJ+l/mdfHlIykyGKiw=,tag:rWu810i3PZlOdpW/M9H7EQ==,type:str]
    API_JWT_SECRET: ENC[AES256_GCM,data:I4Msz+ANNcwtPcCSxaESMOHFWhFZz2dit0LPNAIJ7luo8kgjC624AYvrXQ==,iv:O3WF3PzlLKVS1LhTiMPSZY0QJtnu+NktgUKuvHeORU8=,tag:rFZqDvVQoXWSIQTlzOEoNw==,type:str]
    SECRET_KEY_BASE: ENC[AES256_GCM,data:XiaC9F39HyLQq8wauKqpqjRaaLOHU6VBMlE57xneba4t1wrly7Z8fPT2lPHnhbeezwiA60rYJ/81LMbf2+D4yg==,iv:nnqFXReobSqYivCJqi+cX9wc8yCAYLt1oLyiSc7/x10=,tag:7+Zr4kVbPcMAbV0xoxPcfA==,type:str]
    METRICS_JWT_SECRET: ENC[AES256_GCM,data:0tx2JqyOKgwXKBhPAM5FCSgXKWNq6M6ugciv2aVcPwl98WoGTKV/pw/v8Q==,iv:Q/QHaJw6Tp6ViKScPJVaa2/0THwPFmf2lrScJKj2ilA=,tag:mWqFgQ43w7RlyLNV1CF0bw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Vit0djFlV3hSNGZGY0Ji
            YWplN1QyL3Vxb3dHQ2dRWW9KK2NHb1VNbVg0CjNyUU1uaDlySzFIRzBpTUdQVUF1
            SkpMRDUrdnJXdUkraEhJMnRUZjg1elkKLS0tIHFLcElubkh3bG8zNFQwNWhqMGJn
            dXYxS2dIUDlORGtuS0NjNm1KR1A1aUEKQWsv6djBCPXxhDf5xrny0ZILb5y7K0g7
            jLpmXw1vgE+Us51zGYL3161xdZnHajsBW5FEH+GeVougf8pQG8XvWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-23T13:42:02Z"
    mac: ENC[AES256_GCM,data:Yl1uS457RIVvK2eqTFhwHpMH7mJeqwoEG0LKwBKsqky5VbEBmT2ujpBScCZF0vQ7PVgwQ67qkhWd2aQ/UgHS+4MnsDrd+3kzqC5hqeekUUhe0rHzD5438+lQj1ZKviiSzarzwObCeZAwwXeVZ3OJALWVWjA7yvk4U5qygpE8jBs=,iv:YpRP/wFaCWSMSnHDzNiySjxt5YAXAlkDM5ODeTCwPa8=,tag:I1pwgApbwxNu/zeuAEPFPg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
