import type { TemperSet } from "akasha/temper/catalog/gear/temper-set/temper-set.page-type.types.ts"

export const stormfist = {
  id: "019e6484-601b-7339-ae53-03e22f3a2469",
  type: "page-type/temper-set",
  slug: "stormfist",
  title: "Stormfist",
  key: "stormfist",
  esoSetId: 275,
  setWayshrines: [188, 188, 188],
  setVeteranEquipTypes: ["EQUIP_TYPE_HEAD"],
  setUndauntedChestId: 1,
  setTypeId: 8,
  setNameZh: "暴风拳",
  setNameRu: "Штормовой Кулак",
  setNameFr: "Poigne-tempête",
  setNameEs: "Puño de Tormenta",
  setNameDe: "Sturmfaust",
  setDropZones: [131, 58, 58],
  setDropMechanics: [6],
  setDropLocationNamesEn: ["Stormreeve Neidir"],
  setDropLocationNamesDe: ["Sturmvogt Neidir"],
  setDlcId: 0,
  itemBrowserSources: ["131:-102"],
  itemBrowserPlaceKinds: [3],
  itemBrowserItemId: 95085,
  esoItemIds: [94540, 94676, 94812, 94948, 95084, 95220],
  esoArmorTypes: ["ARMORTYPE_HEAVY", "ARMORTYPE_LIGHT", "ARMORTYPE_MEDIUM"],
  esoEquipTypes: ["EQUIP_TYPE_HEAD", "EQUIP_TYPE_SHOULDERS"],
  category: "temper-set-category/monster",
  valid: ["monster"],
  bonuses: "jsonl",
  icons: "jsonl",
} as const satisfies TemperSet
