import type { SetTemplate } from "@akasha/temper-equipment/set-template"

export const SETS_DATA_095: readonly SetTemplate[] = [
  {
    id: "spider-cultist-cowl",
    name: "Spider Cultist Cowl",
    esoSetId: 297,
    subcategoryId: "dungeon",
    valid: ["*:light"],
    bonuses: [
      {
        count: 2,
        status: "supported",
        effects: [{ metricId: "critical-rating", effectType: "integer", effectValue: 657 }],
        description: "Adds 657 Critical Chance",
      },
      {
        count: 3,
        status: "supported",
        effects: [{ metricId: "magicka-maximum", effectType: "integer", effectValue: 1096 }],
        description: "Adds 1096 Maximum Magicka",
      },
      {
        count: 4,
        status: "supported",
        effects: [{ metricId: "power", effectType: "integer", effectValue: 129 }],
        description: "Adds 129 Weapon and Spell Damage",
      },
      {
        count: 5,
        status: "unsupported",
        effects: [],
        description: "Adds 600 Weapon and Spell Damage to your Destruction Staff abilities.",
      },
    ],
    icons: {
      "axe": "/esoui/art/icons/gear_daedric_1haxe_b.dds",
      "battleaxe": "/esoui/art/icons/gear_daedric_2haxe_c.dds",
      "bow": "/esoui/art/icons/gear_daedric_bow_c.dds",
      "chest:*": "/esoui/art/icons/gear_dunmer_light_robe_d.dds",
      "dagger": "/esoui/art/icons/gear_daedric_dagger_c.dds",
      "feet:*": "/esoui/art/icons/gear_daedric_light_feet_a.dds",
      "greatsword": "/esoui/art/icons/gear_daedric_2hsword_c.dds",
      "hands:*": "/esoui/art/icons/gear_daedric_light_hands_a.dds",
      "head:*": "/esoui/art/icons/gear_nord_light_head_d.dds",
      "ice-staff": "/esoui/art/icons/gear_daedric_staff_c.dds",
      "inferno-staff": "/esoui/art/icons/gear_orc_staff_d.dds",
      "legs:*": "/esoui/art/icons/gear_daedric_light_legs_a.dds",
      "lightning-staff": "/esoui/art/icons/gear_dunmer_staff_d.dds",
      "mace": "/esoui/art/icons/gear_daedric_1hhammer_c.dds",
      "maul": "/esoui/art/icons/gear_daedric_2hhammer_c.dds",
      "necklace": "/esoui/art/icons/gear_breton_neck_a.dds",
      "restoration-staff": "/esoui/art/icons/gear_daedric_staff_c.dds",
      "ring": "/esoui/art/icons/gear_breton_ring_a.dds",
      "shield": "/esoui/art/icons/gear_daedric_shield_c.dds",
      "shoulders:*": "/esoui/art/icons/gear_daedric_light_shoulders_a.dds",
      "sword": "/esoui/art/icons/gear_daedric_1hsword_c.dds",
      "waist:*": "/esoui/art/icons/gear_daedric_light_waist_a.dds",
    },
  },
  {
    id: "spinners-garments",
    name: "Spinner's Garments",
    esoSetId: 289,
    subcategoryId: "overland",
    valid: ["*:light"],
    bonuses: [
      {
        count: 2,
        status: "supported",
        effects: [{ metricId: "magicka-maximum", effectType: "integer", effectValue: 1096 }],
        description: "Adds 1096 Maximum Magicka",
      },
      {
        count: 3,
        status: "supported",
        effects: [{ metricId: "magicka-maximum", effectType: "integer", effectValue: 1096 }],
        description: "Adds 1096 Maximum Magicka",
      },
      {
        count: 4,
        status: "supported",
        effects: [{ metricId: "power", effectType: "integer", effectValue: 129 }],
        description: "Adds 129 Weapon and Spell Damage",
      },
      {
        count: 5,
        status: "supported",
        effects: [{ metricId: "penetration", effectType: "integer", effectValue: 3460 }],
        description: "Adds 3460 Offensive Penetration",
      },
    ],
    icons: {
      "axe": "/esoui/art/icons/gear_bosmer_1haxe_d.dds",
      "battleaxe": "/esoui/art/icons/gear_bosmer_2haxe_d.dds",
      "bow": "/esoui/art/icons/gear_bosmer_bow_d.dds",
      "chest:*": "/esoui/art/icons/gear_bosmer_light_robe_d.dds",
      "dagger": "/esoui/art/icons/gear_bosmer_dagger_d.dds",
      "feet:*": "/esoui/art/icons/gear_redguard_light_feet_d.dds",
      "greatsword": "/esoui/art/icons/gear_bosmer_2hsword_d.dds",
      "hands:*": "/esoui/art/icons/gear_bosmer_light_hands_d.dds",
      "head:*": "/esoui/art/icons/gear_bosmer_light_head_d.dds",
      "ice-staff": "/esoui/art/icons/gear_bosmer_staff_d.dds",
      "inferno-staff": "/esoui/art/icons/gear_bosmer_staff_d.dds",
      "legs:*": "/esoui/art/icons/gear_bosmer_light_legs_d.dds",
      "lightning-staff": "/esoui/art/icons/gear_bosmer_staff_d.dds",
      "mace": "/esoui/art/icons/gear_bosmer_1hhammer_d.dds",
      "maul": "/esoui/art/icons/gear_orc_2hhammer_d.dds",
      "necklace": "/esoui/art/icons/gear_argonian_neck_a.dds",
      "restoration-staff": "/esoui/art/icons/gear_bosmer_staff_d.dds",
      "ring": "/esoui/art/icons/gear_breton_ring_a.dds",
      "shield": "/esoui/art/icons/gear_bosmer_shield_d.dds",
      "shoulders:*": "/esoui/art/icons/gear_bosmer_light_shoulders_d.dds",
      "sword": "/esoui/art/icons/gear_bosmer_1hsword_d.dds",
      "waist:*": "/esoui/art/icons/gear_bosmer_light_waist_d.dds",
    },
  },
  {
    id: "spriggans-thorns",
    name: "Spriggan's Thorns",
    esoSetId: 286,
    subcategoryId: "overland",
    valid: ["*:medium"],
    bonuses: [
      {
        count: 2,
        status: "supported",
        effects: [{ metricId: "stamina-maximum", effectType: "integer", effectValue: 1096 }],
        description: "Adds 1096 Maximum Stamina",
      },
      {
        count: 3,
        status: "supported",
        effects: [{ metricId: "stamina-maximum", effectType: "integer", effectValue: 1096 }],
        description: "Adds 1096 Maximum Stamina",
      },
      {
        count: 4,
        status: "supported",
        effects: [{ metricId: "power", effectType: "integer", effectValue: 129 }],
        description: "Adds 129 Weapon and Spell Damage",
      },
      {
        count: 5,
        status: "supported",
        effects: [{ metricId: "penetration", effectType: "integer", effectValue: 3460 }],
        description: "Adds 3460 Offensive Penetration",
      },
    ],
    icons: {
      "axe": "/esoui/art/icons/gear_redguard_1haxe_d.dds",
      "battleaxe": "/esoui/art/icons/gear_nord_2haxe_d.dds",
      "bow": "/esoui/art/icons/gear_bosmer_bow_d.dds",
      "chest:*": "/esoui/art/icons/gear_redguard_medium_chest_d.dds",
      "dagger": "/esoui/art/icons/gear_redguard_dagger_d.dds",
      "feet:*": "/esoui/art/icons/gear_breton_medium_feet_d.dds",
      "greatsword": "/esoui/art/icons/gear_altmer_2hsword_d.dds",
      "hands:*": "/esoui/art/icons/gear_redguard_medium_hands_d.dds",
      "head:*": "/esoui/art/icons/gear_imperial_medium_head_b.dds",
      "ice-staff": "/esoui/art/icons/gear_bosmer_staff_d.dds",
      "inferno-staff": "/esoui/art/icons/gear_bosmer_staff_d.dds",
      "legs:*": "/esoui/art/icons/gear_breton_medium_legs_d.dds",
      "lightning-staff": "/esoui/art/icons/gear_bosmer_staff_d.dds",
      "mace": "/esoui/art/icons/gear_bosmer_1hhammer_d.dds",
      "maul": "/esoui/art/icons/gear_breton_2hhammer_d.dds",
      "necklace": "/esoui/art/icons/gear_breton_neck_a.dds",
      "restoration-staff": "/esoui/art/icons/gear_bosmer_staff_d.dds",
      "ring": "/esoui/art/icons/gear_altmer_ring_a.dds",
      "shield": "/esoui/art/icons/gear_bosmer_shield_d.dds",
      "shoulders:*": "/esoui/art/icons/gear_bosmer_medium_shoulders_d.dds",
      "sword": "/esoui/art/icons/gear_bosmer_1hsword_d.dds",
      "waist:*": "/esoui/art/icons/gear_redguard_medium_waist_d.dds",
    },
  },
  {
    id: "spriggans-vigor",
    name: "Spriggan's Vigor",
    esoSetId: 624,
    subcategoryId: "dungeon",
    valid: ["*:medium"],
    bonuses: [
      {
        count: 2,
        status: "supported",
        effects: [{ metricId: "critical-rating", effectType: "integer", effectValue: 657 }],
        description: "Adds 657 Critical Chance",
      },
      {
        count: 3,
        status: "supported",
        effects: [{ metricId: "stamina-maximum", effectType: "integer", effectValue: 1096 }],
        description: "Adds 1096 Maximum Stamina",
      },
      {
        count: 4,
        status: "supported",
        effects: [{ metricId: "power", effectType: "integer", effectValue: 129 }],
        description: "Adds 129 Weapon and Spell Damage",
      },
      {
        count: 5,
        status: "unsupported",
        effects: [],
        description:
          "When you deal Critical Damage, restore 100 Stamina and gain a stack of Wild Growth for 5 seconds, increasing your Max Stamina by 222.  This effect can stack up to 10 times and can occur once every 0.5 seconds.",
      },
    ],
    icons: {
      "axe": "/esoui/art/icons/gear_kraken_axe_a.dds",
      "battleaxe": "/esoui/art/icons/gear_kraken_2haxe_a.dds",
      "bow": "/esoui/art/icons/gear_kraken_bow_a.dds",
      "chest:*": "/esoui/art/icons/gear_krakenmedium_chest_a.dds",
      "dagger": "/esoui/art/icons/gear_kraken_dagger_a.dds",
      "feet:*": "/esoui/art/icons/gear_krakenmedium_feet_a.dds",
      "greatsword": "/esoui/art/icons/gear_kraken_2hsword_a.dds",
      "hands:*": "/esoui/art/icons/gear_krakenmedium_hands_a.dds",
      "head:*": "/esoui/art/icons/gear_krakenmedium_head_a.dds",
      "ice-staff": "/esoui/art/icons/gear_kraken_staff_a.dds",
      "inferno-staff": "/esoui/art/icons/gear_kraken_staff_a.dds",
      "legs:*": "/esoui/art/icons/gear_krakenmedium_legs_a.dds",
      "lightning-staff": "/esoui/art/icons/gear_kraken_staff_a.dds",
      "mace": "/esoui/art/icons/gear_kraken_mace_a.dds",
      "maul": "/esoui/art/icons/gear_kraken_2hmace_a.dds",
      "necklace": "/esoui/art/icons/gear_breton_neck_a.dds",
      "restoration-staff": "/esoui/art/icons/gear_kraken_staff_a.dds",
      "ring": "/esoui/art/icons/gear_breton_ring_a.dds",
      "shield": "/esoui/art/icons/gear_kraken_shield_a.dds",
      "shoulders:*": "/esoui/art/icons/gear_krakenmedium_shoulder_a.dds",
      "sword": "/esoui/art/icons/gear_kraken_sword_a.dds",
      "waist:*": "/esoui/art/icons/gear_krakenmedium_waist_a.dds",
    },
  },
  {
    id: "squall-of-retribution",
    name: "Squall of Retribution",
    esoSetId: 797,
    subcategoryId: "no-type",
    valid: ["monster"],
    bonuses: [
      {
        count: 1,
        status: "supported",
        effects: [{ metricId: "health-maximum", effectType: "integer", effectValue: 1206 }],
        description: "Adds 1206 Maximum Health",
      },
      {
        count: 2,
        status: "unsupported",
        effects: [],
        description:
          "When you take damage, gain one random effect for 6 seconds:\nGain Minor Protection, reducing your damage taken by 5%.\nGain a damage shield that absorbs up to 5835 damage.\nHeal for 630 Health every 2 seconds.\n\nThe Health restore scales off of your Max Health. This effect can occur once every 4.5 seconds.",
      },
    ],
    icons: {
      "head:heavy": "/esoui/art/icons/gear_undexilesvengeance_head_a.dds",
      "head:light": "/esoui/art/icons/gear_undexilesvengeance_head_a.dds",
      "head:medium": "/esoui/art/icons/gear_undexilesvengeance_head_a.dds",
      "shoulders:heavy": "/esoui/art/icons/gear_undexilesvengeance_shoulders_a.dds",
      "shoulders:light": "/esoui/art/icons/gear_undexilesvengeance_shoulders_a.dds",
      "shoulders:medium": "/esoui/art/icons/gear_undexilesvengeance_shoulders_a.dds",
    },
  },
  {
    id: "steadfast-hero",
    name: "Steadfast Hero",
    esoSetId: 421,
    subcategoryId: "pvp",
    valid: ["*:heavy"],
    bonuses: [
      {
        count: 2,
        status: "supported",
        effects: [{ metricId: "resistance", effectType: "integer", effectValue: 743 }],
        description: "Adds 1487 Armor",
      },
      {
        count: 3,
        status: "supported",
        effects: [{ metricId: "resistance", effectType: "integer", effectValue: 743 }],
        description: "Adds 1487 Armor",
      },
      {
        count: 4,
        status: "supported",
        effects: [{ metricId: "health-maximum", effectType: "integer", effectValue: 1206 }],
        description: "Adds 1206 Maximum Health",
      },
      {
        count: 5,
        status: "unsupported",
        effects: [],
        description:
          "When you cleanse a negative effect from yourself or an ally, gain Major Protection for 10 seconds, reducing your damage taken by 10%. This effect can occur once every 12 seconds.",
      },
    ],
    icons: {
      "axe": "/esoui/art/icons/gear_breton_1haxe_d.dds",
      "battleaxe": "/esoui/art/icons/gear_breton_2haxe_d.dds",
      "bow": "/esoui/art/icons/gear_breton_bow_d.dds",
      "chest:*": "/esoui/art/icons/gear_breton_heavy_chest_d.dds",
      "dagger": "/esoui/art/icons/gear_breton_dagger_d.dds",
      "feet:*": "/esoui/art/icons/gear_breton_heavy_feet_d.dds",
      "greatsword": "/esoui/art/icons/gear_breton_2hsword_d.dds",
      "hands:*": "/esoui/art/icons/gear_breton_heavy_hands_d.dds",
      "head:*": "/esoui/art/icons/gear_breton_heavy_head_d.dds",
      "ice-staff": "/esoui/art/icons/gear_breton_staff_d.dds",
      "inferno-staff": "/esoui/art/icons/gear_breton_staff_d.dds",
      "legs:*": "/esoui/art/icons/gear_breton_heavy_legs_d.dds",
      "lightning-staff": "/esoui/art/icons/gear_breton_staff_d.dds",
      "mace": "/esoui/art/icons/gear_breton_1hhammer_d.dds",
      "maul": "/esoui/art/icons/gear_breton_2hhammer_d.dds",
      "necklace": "/esoui/art/icons/gear_breton_neck_a.dds",
      "restoration-staff": "/esoui/art/icons/gear_breton_staff_d.dds",
      "ring": "/esoui/art/icons/gear_breton_ring_a.dds",
      "shield": "/esoui/art/icons/gear_breton_shield_d.dds",
      "shoulders:*": "/esoui/art/icons/gear_breton_heavy_shoulders_d.dds",
      "sword": "/esoui/art/icons/gear_breton_1hsword_d.dds",
      "waist:*": "/esoui/art/icons/gear_breton_heavy_waist_d.dds",
    },
  },
]
