import type { Command } from "../../../command-system/commands/command.page-type.ts"

export const measureChecks = {
  id: "01a0796e-60e0-7966-a168-7960d223be13",
  pageTypeSlug: "command",
  slug: "measure-checks",
  definition: "the command saying what a check's run cost in processor time and memory, by phase",
  code: "ts",
  changeKindSlug: "change-mechanical",
  partSlugs: ["module/check-measuring"],
  taking: [
    { said: "--last <count>", takes: "how many of the most recent runs the numbers cover" },
    {
      said: "--last <count>{m|h|d}",
      takes: "the period the numbers cover ending at the moment of asking",
    },
  ],
  helpNotes: [
    "a call naming no argument reads the last one run.",
    "a run is one change judged by every check that change reached.",
    "one run id is minted for each change judged.",
    "every check judged over that change carries that run id.",
    "a record carrying no run id belongs to no run.",
    "a record belonging to no run counts nowhere where runs were counted.",
    "how many records carry no run id is said beneath the table.",
    "a period counts every record stamped within that period whether a run id is there or not.",
    "a check no run of what was chosen judged is not listed at all.",
    "what was chosen is said beneath the table.",
    "the total counts the distinct runs of a phase rather than the records read.",
    "the total shares a phase's processor time over the distinct runs of that phase.",
    "the total for one run is exactly what that run took.",
    "the total draws its memory as `-`.",
    "a peak of memory adds to no other peak.",
    "an average is what a phase's runs took together shared out over how many runs there were.",
    "a patch run judges the paths a change carries.",
    "an audit run judges every page.",
    "a run's processor time is that run's own together with the children that run reaped.",
    "a run's memory is what that run added over the memory resident when the run opened.",
    "a run that forgot no high-water mark is left out of the memory it would otherwise report.",
    "that run is counted in the processor time all the same.",
    "that run is counted among the runs its phase holds all the same.",
    "how many runs a phase holds is said before that phase's averages.",
    "a phase no run was judged at is drawn as `-` rather than as an average of zero.",
    "a phase no run was judged at counts `0` runs rather than an absence.",
    "checks are ordered by what their patch runs took on average.",
    "a check carrying no patch run comes last.",
  ],
  invariants: [
    {
      invariantKind: "absence",
      statement: "A run writes no value the commit holds.",
    },
    {
      invariantKind: "departure",
      statement: "An argument this command does not take is refused.",
    },
  ],
} as const satisfies Command
