import { describe, expect, test } from "bun:test"

import {
  declaresMachineProvenance,
  readLeadingComment,
  scanGeneratedSuffix,
} from "./check-generated-suffix.ts"

describe("declaresMachineProvenance — the incidents that bought this check", () => {
  test("`Generated by <script>` refuses (treasure-pins-data.ts, #13233)", () => {
    const claim = declaresMachineProvenance(
      "// Generated by scripts/port-data.ts from upstream LibTreasure v24 `data.lua` — do not edit by hand.\n// Re-run `bun scripts/port-data.ts` to refresh against a new upstream version."
    )
    expect(claim).toBeDefined()
  })

  test("`AUTO-EXTRACTED from upstream` refuses (base-data.ts, #13239)", () => {
    expect(declaresMachineProvenance("// AUTO-EXTRACTED from upstream Foo v1.2")).toBeDefined()
  })

  test("`Ported 1:1 … via scripts/` passes — the declined family (map-data.ts, #13234)", () => {
    expect(
      declaresMachineProvenance(
        "// Ported 1:1 from LibMapData v1.21 (AddOnVersion 121) LibMapData_Data.lua via scripts/port-data.ts."
      )
    ).toBeUndefined()
  })
})

describe("declaresMachineProvenance — wording nobody wrote into the check", () => {
  test("`Machine-generated …` refuses, the spelling the old marker list was blind to", () => {
    expect(
      declaresMachineProvenance(
        "// Machine-generated boundary brand constructors (project #12456)."
      )
    ).toBeDefined()
  })

  test("`Programmatically synthesised …` refuses, a wording that stands nowhere in the repo", () => {
    expect(
      declaresMachineProvenance("// Programmatically synthesised lookup tables for the zone index.")
    ).toBeDefined()
  })

  test("`Auto-rendered …` refuses, composed from the two classes rather than listed", () => {
    expect(declaresMachineProvenance("// Auto-rendered icon manifest.")).toBeDefined()
  })

  test("`Codegen-emitted …` refuses", () => {
    expect(declaresMachineProvenance("// Codegen-emitted dispatch table.")).toBeDefined()
  })

  test("a stamp below the opening lines refuses, with no self-reference to help", () => {
    const header = [
      "/**",
      " * Zone Lookup Tables",
      " *",
      " * Programmatically synthesised from the upstream zone index.",
      " * Run: bun run generate-zones",
      " */",
    ].join("\n")
    expect(declaresMachineProvenance(header)).toBeDefined()
  })
})

describe("declaresMachineProvenance — the claim has to be about this file", () => {
  test("a self-reference anywhere in the block refuses", () => {
    const header = [
      "/**",
      " * Metrics Data: a–d (alliance through divines)",
      " *",
      " * THIS FILE IS AUTO-GENERATED. Do not edit manually.",
      " * Run: bun run generate-metrics",
      " */",
    ].join("\n")
    expect(declaresMachineProvenance(header)).toBeDefined()
  })

  test("a human's refactor extraction passes — 721 of the repo's files read this way", () => {
    expect(
      declaresMachineProvenance(
        "// Extracted from oauth.ts during project #7800 (500-line remediation)."
      )
    ).toBeUndefined()
  })

  test("a compiler describing what IT emits passes", () => {
    const header = [
      "// TS-source → model-checker compiler entry point. Walks a transition-table",
      "// `.proc.ts` source and renders the spec text.",
      "//",
      "// Lowering rules (deterministic):",
      "//   - Auto-emitted `Init` action constructs each declared instance.",
    ].join("\n")
    expect(declaresMachineProvenance(header)).toBeUndefined()
  })

  test("a spec naming a framework's auto-emitted action passes", () => {
    expect(
      declaresMachineProvenance(
        "// - Two roles are declared (`Older` + `Newer`) so the auto-emitted top-level\n// `Init` action constructs both instances."
      )
    ).toBeUndefined()
  })

  test("a baseline naming a DIFFERENT file as generated passes", () => {
    const header = [
      "/**",
      " * Grandfather-baseline mechanism for `check-tstl-colon-dot-self-shift`.",
      " *",
      " * The pre-existing sites are grandfathered by an auto-generated baseline",
      " * (`tstl-colon-dot-self-shift.baseline.generated.ts`) and burned down by",
      " * sibling per-addon units.",
      " */",
    ].join("\n")
    expect(declaresMachineProvenance(header)).toBeUndefined()
  })

  test("a doc comment quoting the header it WRITES passes", () => {
    const header = [
      "/**",
      " * Serializer for the `TemperCompanionsConfig.lua` side-file.",
      " *",
      " * The emitted file opens with:",
      " *   -- Auto-generated by the Temper watcher; do not edit by hand.",
      " */",
    ].join("\n")
    expect(declaresMachineProvenance(header)).toBeUndefined()
  })

  test("a plain hand-authored header passes", () => {
    expect(declaresMachineProvenance("// Hand-authored business logic for foo.")).toBeUndefined()
  })

  test("a wrapped sentence is judged whole, not from where the line broke", () => {
    const header = [
      "/**",
      " * Grandfather-baseline mechanism for `check-tstl-colon-dot-self-shift`.",
      " *",
      " * The pre-existing sites are grandfathered by an",
      " * auto-generated baseline and burned down by sibling per-addon units.",
      " */",
    ].join("\n")
    expect(declaresMachineProvenance(header)).toBeUndefined()
  })

  test("an elided subject naming what a lowering emits passes", () => {
    const header = [
      "// The owner-reassignment write-boundary guard.",
      "//",
      "// The call to it is emitted by the single `patchUpdate` lowering",
      "// (`@shared/pages-proc-compiler/ctx-mapping-defs.ts`).",
    ].join("\n")
    expect(declaresMachineProvenance(header)).toBeUndefined()
  })

  test("a header saying no emitter owns it passes", () => {
    const header = [
      "// Boundary brand constructors for the ESO API surface (project #12456).",
      "//",
      "// Hand-maintained: no emitter writes these paths. The family came out of a",
      "// tool once, was then split by hand, and has been edited by hand since.",
    ].join("\n")
    expect(declaresMachineProvenance(header)).toBeUndefined()
  })
})

describe("readLeadingComment — the window is the comment, not a line count", () => {
  test("a stamp on the fourth line is inside the block", () => {
    const source = [
      "/**",
      " * Metric IDs Module",
      " *",
      " * THIS FILE IS AUTO-GENERATED. Do not edit manually.",
      " */",
      "",
      "export const METRIC_IDS = [] as const",
    ].join("\n")
    const block = readLeadingComment(source)
    expect(block).toContain("AUTO-GENERATED")
    expect(declaresMachineProvenance(block)).toBeDefined()
  })

  test("the block stops at the first line that is not part of the comment", () => {
    const source = [
      "// A hand-authored header.",
      "",
      "// Auto-generated, says a later comment.",
    ].join("\n")
    expect(readLeadingComment(source)).toBe("// A hand-authored header.")
  })

  test("a shebang above the comment is skipped", () => {
    const source = ["#!/usr/bin/env bun", "", "// Machine-generated dispatch table."].join("\n")
    expect(readLeadingComment(source)).toBe("// Machine-generated dispatch table.")
  })

  test("a file opening with code has no leading comment", () => {
    expect(readLeadingComment("export const x = 1\n")).toBe("")
  })

  test("consecutive line comments are one block", () => {
    const source = ["// one", "// two", "// three", "const x = 1"].join("\n")
    expect(readLeadingComment(source)).toBe("// one\n// two\n// three")
  })
})

describe("scanGeneratedSuffix — naming", () => {
  test("a claim on a *-data.ts file is flagged with the claim it carries", () => {
    const v = scanGeneratedSuffix([
      { file: "x/src/foo-data.ts", header: "// AUTO-EXTRACTED from upstream Foo v1.2" },
    ])
    expect(v).toHaveLength(1)
    expect(v[0]?.file).toBe("x/src/foo-data.ts")
    expect(v[0]?.marker.toLowerCase()).toContain("extracted")
  })

  test("the same claim on a *.generated.ts file passes", () => {
    const v = scanGeneratedSuffix([
      { file: "x/src/foo.generated.ts", header: "// AUTO-EXTRACTED from upstream Foo" },
    ])
    expect(v).toHaveLength(0)
  })

  test("a *.d.ts declaration file is skipped", () => {
    const v = scanGeneratedSuffix([
      { file: "x/src/foo.d.ts", header: "// AUTO-GENERATED — opt-in scoped" },
    ])
    expect(v).toHaveLength(0)
  })

  test(".tsx is scanned and .generated.tsx is skipped", () => {
    const v = scanGeneratedSuffix([
      { file: "x/src/widget.tsx", header: "// Auto-generated widget." },
      { file: "x/src/widget.generated.tsx", header: "// Auto-generated widget." },
    ])
    expect(v).toHaveLength(1)
    expect(v[0]?.file).toBe("x/src/widget.tsx")
  })

  test("only the mis-named file in a mixed batch is flagged", () => {
    const v = scanGeneratedSuffix([
      { file: "x/src/ok.generated.ts", header: "// Auto-generated." },
      { file: "x/src/plain.ts", header: "// nothing here" },
      { file: "x/src/bad-data.ts", header: "// AUTO-EXTRACTED from upstream" },
    ])
    expect(v).toHaveLength(1)
    expect(v[0]?.file).toBe("x/src/bad-data.ts")
  })

  test("case does not decide it", () => {
    const lower = scanGeneratedSuffix([
      { file: "x/src/a-data.ts", header: "// auto-extracted from upstream foo" },
    ])
    const upper = scanGeneratedSuffix([
      { file: "x/src/b-data.ts", header: "// AUTO-EXTRACTED FROM UPSTREAM FOO" },
    ])
    expect(lower).toHaveLength(1)
    expect(upper).toHaveLength(1)
  })

  test("an empty batch yields no violations", () => {
    expect(scanGeneratedSuffix([])).toHaveLength(0)
  })
})
