import type { TemperLoreBook } from "akasha/temper/catalog/pursuit/temper-lore-collection/temper-lore-book/temper-lore-book.page-type.types.ts"

export const cookingMasteryTheEasyWay = {
  id: "01a0d5f6-6d40-77fb-8a02-3b52c5ae21fc",
  type: "page-type/temper-lore-book",
  slug: "cooking-mastery-the-easy-way",
  title: "Cooking Mastery, The Easy Way",
  collection: "temper-lore-collection/skill-books",
  esoBookId: 2419,
  bookIndex: 63,
  charted: true,
  onBookshelves: true,
  mapCounts: [
    { mapId: 1, mapCount: 27 },
    { mapId: 7, mapCount: 27 },
    { mapId: 9, mapCount: 9 },
    { mapId: 10, mapCount: 8 },
    { mapId: 12, mapCount: 12 },
    { mapId: 13, mapCount: 10 },
    { mapId: 20, mapCount: 8 },
    { mapId: 22, mapCount: 18 },
    { mapId: 26, mapCount: 10 },
    { mapId: 27, mapCount: 6 },
    { mapId: 30, mapCount: 3 },
    { mapId: 61, mapCount: 13 },
    { mapId: 74, mapCount: 5 },
    { mapId: 75, mapCount: 2 },
    { mapId: 125, mapCount: 26 },
    { mapId: 143, mapCount: 49 },
    { mapId: 201, mapCount: 15 },
    { mapId: 227, mapCount: 2 },
    { mapId: 256, mapCount: 6 },
    { mapId: 258, mapCount: 15 },
    { mapId: 300, mapCount: 15 },
    { mapId: 1126, mapCount: 15 },
  ],
} as const satisfies TemperLoreBook
