apiVersion: v1
kind: Secret
metadata:
    name: git-transport-secrets
    namespace: git
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:KcJWruLoMj2+HmDwDDn+ge9aNVMtCA9ZqUrpliCP7jOqdkeUMDwpyzHuyyrM7bvdwQxl6CCub5uiAoLZ6aMDCAIuAnhr8Na019tgRmpF+OXDJ8iGQFMO75lNk9qH1TgZP9YzHaE4BAP9GC8ls/ZZngwNpGiC6SaDmi3pqtfVkdc=,iv:laVC/g8g3nHD2H6Z/VMM4J+GPa1ABYWj6NPnX/DwttY=,tag:yKGlEsslUwFz4GL8jH/L8A==,type:str]
    GIT_ACCESS_TOKEN: ENC[AES256_GCM,data:KETbYoDVxp1HdGJar1f1he+3qS1nPC01Kh1gjn2q61zNUcIBUQjb6g==,iv:cQnvpHIuDFKpj78goCv3gCYytCZ07dQ1LQFKzUcFgvI=,tag:6eXhO+1iv80hJwL0TjAhVQ==,type:str]
    GITHUB_ACCESS_TOKEN: ENC[AES256_GCM,data:rS1e4RmKsB8yghCcuSXu4n2venP9027uG4sJQQ+NREbym7p/lo8sk+jeQLNjWjcPA/Epubrzej0eK/ibK/+Ye7mTNWcMp0kUQ9uAUNlY7vHa7xTe+WS9lADi+lfv,iv:l0DW0gT3UnYXcQ1EUnfr6HL1ebIc0CQY/xKmWRr5rkM=,tag:g1bn+614L2bxtdmckaTAIg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCakxRY3Q2OG5sU1V0ZlJK
            aEl6NnE4QnBBenBPVlJNUVlwWDVZNFBYT1hFCmY1Z2M5cm4rL3RuWWxxUmZRYXRP
            cFBOWnJiUzdNanpPWVBSMnVtUXd4UU0KLS0tIE95V0hLT2lzQTZmbWZjS25rdEhh
            QnF5Tkk2NE4vblU3Q1pRVHBGRXpyRUUKERq8uL+j+F3euY3xwcSO4EHkV4pdydwD
            6C//zEshSwFQlfmjcLqSNcG5F54PlqfrblaMup6tL3EXMFKZCDLbIQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-27T19:42:39Z"
    mac: ENC[AES256_GCM,data:Ih2zw/u8r1JsFvXYPTuYvy8NN2nl75U3JtmW2xL0mb/4lDCTLj1T3Rgts75j8fpQb7zLG0nxwvDyvqEEc+sqjdihn1XWmOMT5Q6L8B998ia6pfyZHbypo8fnHnaFDF6bEbcdiKkHIpl1dXUipItVWEfxj8V4LNhZ3wZRVLHQzQg=,iv:0VhHNshRUqpvlxfWFGzO2Rhv1OsJziQijMbIDZ+T0JY=,tag:IbNN7H7+OlLVCTWNz/QNLw==,type:str]
    version: 3.9.4
