import { serializeLuaBlock } from "@akasha/temper-saved-variables/lua-serializer"

export const CONFIG_FILE_HEADER = "-- Auto-generated by the Temper watcher; do not edit by hand."

export const CONFIG_FILE_VERSION = 1

const BLOCK_INDENT = "    "

function configFile(topLevelName: string, blocks: readonly (readonly string[])[]): string {
  return [
    CONFIG_FILE_HEADER,
    `${topLevelName} =`,
    "{",
    `${BLOCK_INDENT}["version"] = ${CONFIG_FILE_VERSION},`,
    ...blocks.flat(),
    "}",
    "",
  ].join("\n")
}

function block(key: string, value: unknown): readonly string[] {
  return serializeLuaBlock(key, value, BLOCK_INDENT)
}

function blockWhenGiven(key: string, value: unknown): readonly string[] {
  return value === undefined ? [] : block(key, value)
}

function luaValue(value: string | number): string {
  return typeof value === "string" ? `"${value}"` : String(value)
}

export function numericKeyedBlock(
  key: string,
  data: Readonly<Record<number, string | number>>,
  indent: string = BLOCK_INDENT
): readonly string[] {
  const entries = Object.entries(data).sort(([a], [b]) => Number(a) - Number(b))
  if (entries.length === 0) return [`${indent}["${key}"] = {},`]
  const innerIndent = `${indent}    `
  return [
    `${indent}["${key}"] =`,
    `${indent}{`,
    ...entries.map(([numKey, value]) => `${innerIndent}[${numKey}] = ${luaValue(value)},`),
    `${indent}},`,
  ]
}

export interface InventoryConfigFileInputs {
  readonly sell?: unknown
  readonly sellTimestamps?: unknown
  readonly sellCompiled?: unknown
  readonly logging: unknown
  readonly safety: unknown
  readonly backpack: unknown
  readonly automation?: unknown
  readonly currencyRates: Record<string, number>
  readonly crownReplacementCosts: Record<number, number>
}

export function serializeInventoryConfigFile(inputs: InventoryConfigFileInputs): string {
  return configFile("TemperInventoryConfig", [
    blockWhenGiven("sell", inputs.sell),
    blockWhenGiven("sellTimestamps", inputs.sellTimestamps),
    blockWhenGiven("sellCompiled", inputs.sellCompiled),
    block("logging", inputs.logging),
    block("safety", inputs.safety),
    blockWhenGiven("automation", inputs.automation),
    block("backpack", inputs.backpack),
    block("currencyRates", inputs.currencyRates),
    block("crownReplacementCosts", inputs.crownReplacementCosts),
  ])
}

export interface CharactersConfigFileInputs {
  readonly characterPriority: readonly string[]
  readonly tasks: Readonly<Record<string, unknown>>
  readonly completionOverrides: Readonly<Record<string, unknown>>
}

export function serializeCharactersConfigFile(inputs: CharactersConfigFileInputs): string {
  return configFile("TemperCharactersConfig", [
    block("characterPriority", inputs.characterPriority),
    block("tasks", inputs.tasks),
    block("completionOverrides", inputs.completionOverrides),
  ])
}

export interface CompanionsConfigFileInputs {
  readonly companionTargetBuilds: Readonly<Record<number, string>>
  readonly companionTargetTimestamps: Readonly<Record<number, number>>
}

export function serializeCompanionsConfigFile(inputs: CompanionsConfigFileInputs): string {
  return configFile("TemperCompanionsConfig", [
    numericKeyedBlock("companionTargetBuilds", inputs.companionTargetBuilds),
    numericKeyedBlock("companionTargetTimestamps", inputs.companionTargetTimestamps),
  ])
}
