import { expect, test } from "bun:test"
import {
  numericKeyedBlock,
  serializeCharactersConfigFile,
  serializeCompanionsConfigFile,
  serializeInventoryConfigFile,
} from "./watcher-config-file.module.code.ts"

test("the inventory config file matches what the legacy serializer wrote", () => {
  expect(
    serializeInventoryConfigFile({
      "sell": {
        "keep": 1,
      },
      "sellTimestamps": {
        "keep": 1700000000,
      },
      "sellCompiled": [
        {
          "id": "a",
        },
      ],
      "logging": {
        "level": "info",
      },
      "safety": {
        "destructive": false,
      },
      "backpack": {
        "reserved": 10,
      },
      "automation": {
        "deconstruct": true,
      },
      "currencyRates": {
        "gold": 1,
        "ap": 0.5,
      },
      "crownReplacementCosts": {
        "1": 2,
        "3": 4,
      },
    })
  ).toBe(
    '-- Auto-generated by the Temper watcher; do not edit by hand.\nTemperInventoryConfig =\n{\n    ["version"] = 1,\n    ["sell"] =\n    {\n        ["keep"] = 1,\n    },\n    ["sellTimestamps"] =\n    {\n        ["keep"] = 1700000000,\n    },\n    ["sellCompiled"] =\n    {\n        {\n            ["id"] = "a",\n        },\n    },\n    ["logging"] =\n    {\n        ["level"] = "info",\n    },\n    ["safety"] =\n    {\n        ["destructive"] = false,\n    },\n    ["automation"] =\n    {\n        ["deconstruct"] = true,\n    },\n    ["backpack"] =\n    {\n        ["reserved"] = 10,\n    },\n    ["currencyRates"] =\n    {\n        ["gold"] = 1,\n        ["ap"] = 0.5,\n    },\n    ["crownReplacementCosts"] =\n    {\n        [1] = 2,\n        [3] = 4,\n    },\n}\n'
  )
})

test("an inventory config file leaves out every block it was told nothing for", () => {
  expect(
    serializeInventoryConfigFile({
      "logging": {
        "level": "info",
      },
      "safety": {
        "destructive": false,
      },
      "backpack": {
        "reserved": 10,
      },
      "currencyRates": {},
      "crownReplacementCosts": {},
    })
  ).toBe(
    '-- Auto-generated by the Temper watcher; do not edit by hand.\nTemperInventoryConfig =\n{\n    ["version"] = 1,\n    ["logging"] =\n    {\n        ["level"] = "info",\n    },\n    ["safety"] =\n    {\n        ["destructive"] = false,\n    },\n    ["backpack"] =\n    {\n        ["reserved"] = 10,\n    },\n    ["currencyRates"] =\n    {},\n    ["crownReplacementCosts"] =\n    {},\n}\n'
  )
})

test("the characters config file matches what the legacy serializer wrote", () => {
  expect(
    serializeCharactersConfigFile({
      "characterPriority": ["Alpha", "Beta"],
      "tasks": {
        "daily": {
          "id": "d1",
        },
      },
      "completionOverrides": {
        "card": true,
      },
    })
  ).toBe(
    '-- Auto-generated by the Temper watcher; do not edit by hand.\nTemperCharactersConfig =\n{\n    ["version"] = 1,\n    ["characterPriority"] =\n    {\n        "Alpha",\n        "Beta",\n    },\n    ["tasks"] =\n    {\n        ["daily"] =\n        {\n            ["id"] = "d1",\n        },\n    },\n    ["completionOverrides"] =\n    {\n        ["card"] = true,\n    },\n}\n'
  )
})

test("the companions config file orders its numeric keys by number", () => {
  expect(
    serializeCompanionsConfigFile({
      "companionTargetBuilds": {
        "2": "def",
        "10": "abc",
      },
      "companionTargetTimestamps": {
        "2": 1600000000,
        "10": 1700000000,
      },
    })
  ).toBe(
    '-- Auto-generated by the Temper watcher; do not edit by hand.\nTemperCompanionsConfig =\n{\n    ["version"] = 1,\n    ["companionTargetBuilds"] =\n    {\n        [2] = "def",\n        [10] = "abc",\n    },\n    ["companionTargetTimestamps"] =\n    {\n        [2] = 1600000000,\n        [10] = 1700000000,\n    },\n}\n'
  )
})

test("a numeric-keyed block holding nothing is written on one line", () => {
  expect(
    serializeCompanionsConfigFile({
      "companionTargetBuilds": {},
      "companionTargetTimestamps": {},
    })
  ).toBe(
    '-- Auto-generated by the Temper watcher; do not edit by hand.\nTemperCompanionsConfig =\n{\n    ["version"] = 1,\n    ["companionTargetBuilds"] = {},\n    ["companionTargetTimestamps"] = {},\n}\n'
  )
})

test("every config file opens with the same header and closes with a newline", () => {
  const written = [
    serializeInventoryConfigFile({
      "logging": { "level": "info" },
      "safety": { "destructive": false },
      "backpack": { "reserved": 10 },
      "currencyRates": {},
      "crownReplacementCosts": {},
    }),
    serializeCharactersConfigFile({
      "characterPriority": ["Alpha", "Beta"],
      "tasks": { "daily": { "id": "d1" } },
      "completionOverrides": { "card": true },
    }),
    serializeCompanionsConfigFile({ "companionTargetBuilds": {}, "companionTargetTimestamps": {} }),
  ]
  for (const text of written) {
    expect(text.startsWith("-- Auto-generated by the Temper watcher; do not edit by hand.\n")).toBe(
      true
    )
    expect(text.endsWith("}\n")).toBe(true)
    expect(text).toContain('    ["version"] = 1,')
  }
})

test("a numeric-keyed block at the default indent is what the companions file already carries", () => {
  const block = numericKeyedBlock("companionTargetBuilds", { "2": "def", "10": "abc" }).join("\n")
  expect(block).toBe(
    '    ["companionTargetBuilds"] =\n    {\n        [2] = "def",\n        [10] = "abc",\n    },'
  )
  expect(
    serializeCompanionsConfigFile({
      "companionTargetBuilds": { "2": "def", "10": "abc" },
      "companionTargetTimestamps": {},
    })
  ).toContain(block)
})

test("a numeric-keyed block takes the indent the caller states", () => {
  expect(numericKeyedBlock("companionTargetBuilds", { "1": "a" }, "            ")).toEqual([
    '            ["companionTargetBuilds"] =',
    "            {",
    '                [1] = "a",',
    "            },",
  ])
})

test("a numeric-keyed block holding nothing takes the stated indent too", () => {
  expect(numericKeyedBlock("companionTargetBuilds", {}, "  ")).toEqual([
    '  ["companionTargetBuilds"] = {},',
  ])
})
