#!/usr/bin/env bash
# Sourced by alanwalton-ios-seam, in the shell that runs it, and cut from
# 10-xcode-project.sh when that seam moved into akasha. It reads the names
# the seam set and is not a program of its own.
if [[ "$WIDGET_ENABLED" != "1" ]]; then
  echo "OK: widget seam (§4) SKIPPED — NATIVE_SHELL_WIDGET is not set (fleet-safe default)."
else

if ! gem list -i xcodeproj >/dev/null 2>&1; then
  echo "OK: installing the xcodeproj gem (user-install) for the widget seam…"
  gem install --user-install xcodeproj
fi

mkdir -p "$WIDGET_DEST"
rm -f "$WIDGET_DEST"/*.swift "$WIDGET_DEST/Info.plist" "$WIDGET_DEST/Widget.entitlements"
copy_widget_components "$SHARED_WIDGET_SRC_DIR" "$WIDGET_DEST" "$WIDGET_COMPONENTS"
cp "$WIDGET_INFO_PLIST" "$WIDGET_DEST/Info.plist"
if [[ ! -f "$WIDGET_ENTITLEMENTS" ]]; then
  echo "ERROR: $WIDGET_ENTITLEMENTS not found — the widget could not read the device secret and every tile would draw 'Sign in'." >&2
  exit 1
fi
cp "$WIDGET_ENTITLEMENTS" "$WIDGET_DEST/Widget.entitlements"
echo "OK: copied widget sources + entitlements into $WIDGET_DEST"

cat > "$WIDGET_DEST/DeviceSecretPins.swift" <<SWIFT_DEVICE_SECRET_PINS
// Generated by 10-xcode-project.sh on every widget seam run, from the values that run
// carries off the ios-app page. Not committed, and nothing here is edited by hand.
//
// The extension reads the per-device credential the app minted, so it must query the same
// keychain service in the same access group. Writing both here rather than restating them
// in the committed Swift is what stops the two sides drifting into an app that writes a
// secret the widget cannot read, which nothing would fail at build time.
enum DeviceSecretPins {
    static let service = "$DEVICE_SECRET_SERVICE"
    static let accessGroup = "$KEYCHAIN_ACCESS_GROUP"
}
SWIFT_DEVICE_SECRET_PINS
echo "OK: wrote $WIDGET_DEST/DeviceSecretPins.swift from the values this run carries"

native_shell_stamp_widget "$WIDGET_DEST"

WIDGET_SEAM_RB=$(mktemp)
cat > "$WIDGET_SEAM_RB" <<'RUBY'
require "xcodeproj"

project_path = ENV.fetch("PROJECT_PBXPROJ")
widget_name  = ENV.fetch("WIDGET_NAME")
bundle_id    = ENV.fetch("WIDGET_BUNDLE_ID")
team         = ENV.fetch("WIDGET_TEAM")
deploy_tgt   = ENV.fetch("WIDGET_DEPLOYMENT_TARGET")
profile_name = ENV.fetch("WIDGET_PROFILE_NAME")
app_profile  = ENV.fetch("APP_PROFILE_NAME")
dest_rel     = "#{widget_name}" # group path relative to ios/App (the project dir)

project = Xcodeproj::Project.open(project_path)
app = project.targets.find { |t| t.name == "App" }
abort("App target not found in #{project_path}") unless app

# Pin the App target to MANUAL distribution signing (against its own ensured App Store
# profile) whenever the widget is embedded. An embedded .appex and its parent app must
# sign with the SAME certificate; left on AUTOMATIC, the App resolves a personal-team
# Apple Development cert (S9NDUWUN6S) during the archive while the widget signs iPhone
# Distribution (M6AN6NM6FL) → "Embedded binary is not signed with the same certificate
# as the parent app" (#15097 dry-run). Both targets manual-distribution → one cert.
app.build_configurations.each do |config|
  bs = config.build_settings
  bs["CODE_SIGN_STYLE"] = "Manual"
  bs["PROVISIONING_PROFILE_SPECIFIER"] = app_profile
  bs["CODE_SIGN_IDENTITY"] = "Apple Distribution"
  bs["DEVELOPMENT_TEAM"] = team
end

# Find-or-create the app-extension target (keyed on name → idempotent across syncs).
widget = project.targets.find { |t| t.name == widget_name }
widget ||= project.new_target(:app_extension, widget_name, :ios, deploy_tgt)

# Build settings on both configurations. CURRENT_PROJECT_VERSION is left to the
# project-wide value the archive passes (CURRENT_PROJECT_VERSION=$BUILD_NUMBER), so
# the widget's CFBundleVersion always matches the app's build number.
app_mv = app.build_configurations.first.build_settings["MARKETING_VERSION"] || "1.0"
widget.build_configurations.each do |config|
  bs = config.build_settings
  bs["PRODUCT_BUNDLE_IDENTIFIER"] = bundle_id
  bs["PRODUCT_NAME"] = "$(TARGET_NAME)"
  bs["INFOPLIST_FILE"] = "#{dest_rel}/Info.plist"
  bs["GENERATE_INFOPLIST_FILE"] = "NO"
  bs["DEVELOPMENT_TEAM"] = team
  # MANUAL signing pinned to the ensured App Store distribution profile (by name).
  # The archive drops the project-wide CODE_SIGN_STYLE=Automatic (testflight-deploy-script.module.code.ts),
  # so this per-target Manual is honored; the App target is pinned to matching manual
  # distribution signing above (both must use the same cert). Automatic here would demand
  # a nonexistent iOS App Development profile for the widget bundle id and time out trying
  # to auto-create one over ssh (#15070 archive failure). The profile is ensured +
  # installed pre-archive by ios-signing.module.code.ts buildEnsureAppStoreProfile.
  bs["CODE_SIGN_STYLE"] = "Manual"
  bs["PROVISIONING_PROFILE_SPECIFIER"] = profile_name
  bs["CODE_SIGN_IDENTITY"] = "Apple Distribution"
  # Keychain sharing with the App target, so the extension can read the per-device
  # credential the app minted (DeviceSecretReader.swift). Path is relative to ios/App,
  # the project dir, exactly as the App target's own CODE_SIGN_ENTITLEMENTS is in §5.
  #
  # NOTHING TO PROVISION FOR IT. There is no keychain capability in the App Store Connect
  # enumeration and every profile already grants the team prefix, so the widget's App ID
  # needs no bundleIdCapabilities call and its profile needs no regeneration — which is why
  # signing.ts's ascCapabilities list for this bundle stays empty.
  bs["CODE_SIGN_ENTITLEMENTS"] = "#{dest_rel}/Widget.entitlements"
  bs["SWIFT_VERSION"] = "5.0"
  bs["SKIP_INSTALL"] = "YES"
  bs["MARKETING_VERSION"] = app_mv
  bs["IPHONEOS_DEPLOYMENT_TARGET"] = deploy_tgt
  bs["TARGETED_DEVICE_FAMILY"] = "1,2"
  bs["LD_RUNPATH_SEARCH_PATHS"] = ["$(inherited)", "@executable_path/Frameworks", "@executable_path/../../Frameworks"]
  bs["SWIFT_EMIT_LOC_STRINGS"] = "YES"
end

# (Re)build the widget's file group + compile sources from disk — clear first so a
# re-run never duplicates references. SwiftUI/WidgetKit auto-link on import, so no
# explicit framework linking is needed.
group = project.main_group.find_subpath(dest_rel, true)
group.set_source_tree("<group>")
group.set_path(dest_rel)
group.children.to_a.each(&:remove_from_project)
widget.source_build_phase.files.to_a.each(&:remove_from_project)
Dir.glob(File.join(File.dirname(project_path), dest_rel, "*.swift")).sort.each do |swift|
  ref = group.new_reference(File.basename(swift))
  widget.source_build_phase.add_file_reference(ref)
end
group.new_reference("Info.plist") # visible in Xcode; not compiled
group.new_reference("Widget.entitlements") # visible in Xcode; not compiled

# App target depends on the widget, and embeds it in an "Embed App Extensions"
# copy-files phase (PlugIns, dstSubfolderSpec 13). Both guarded → idempotent.
app.add_dependency(widget) unless app.dependencies.any? { |d| d.target == widget }
embed = app.copy_files_build_phases.find { |p| p.symbol_dst_subfolder_spec == :plug_ins }
embed ||= app.new_copy_files_build_phase("Embed App Extensions")
embed.symbol_dst_subfolder_spec = :plug_ins
unless embed.files.any? { |bf| bf.file_ref == widget.product_reference }
  bf = embed.add_file_reference(widget.product_reference)
  bf.settings = { "ATTRIBUTES" => ["RemoveHeadersOnCopy"] }
end

project.save
puts "OK: ensured #{widget_name} target (bundle #{bundle_id}) in #{project_path}"
RUBY
PROJECT_PBXPROJ="$PROJECT_PBXPROJ" WIDGET_NAME="$WIDGET_NAME" WIDGET_BUNDLE_ID="$WIDGET_BUNDLE_ID" \
  WIDGET_TEAM="$WIDGET_TEAM" WIDGET_DEPLOYMENT_TARGET="$WIDGET_DEPLOYMENT_TARGET" \
  WIDGET_PROFILE_NAME="$WIDGET_PROFILE_NAME" APP_PROFILE_NAME="$APP_PROFILE_NAME" \
  ruby "$WIDGET_SEAM_RB"
rm -f "$WIDGET_SEAM_RB"

fi
