import type { SetTemplate } from "@akasha/temper-equipment/set-template"

export const SETS_DATA_063: readonly SetTemplate[] = [
  {
    id: "nobility-in-decay",
    name: "Nobility in Decay",
    esoSetId: 724,
    subcategoryId: "class",
    valid: ["*"],
    bonuses: [
      {
        count: 2,
        status: "supported",
        effects: [{ metricId: "health-maximum", effectType: "integer", effectValue: 1206 }],
        description: "Adds 1206 Maximum Health",
      },
      {
        count: 3,
        status: "supported",
        effects: [
          { metricId: "healing-taken-base", effectType: "fractional-change", effectValue: 0.04 },
        ],
        description: "Adds 4% Healing Taken",
      },
      {
        count: 4,
        status: "supported",
        effects: [{ metricId: "health-maximum", effectType: "integer", effectValue: 1206 }],
        description: "Adds 1206 Maximum Health",
      },
      {
        count: 5,
        status: "unsupported",
        effects: [],
        description:
          "Casting a Bone Tyrant ability while in combat grants you Beautiful Corpse and Death's Favor for 16 seconds. Death's Favor increases your healing received and reduces damage taken by up to 12% based on your missing Health. This can occur once every 20 seconds, and is reduced by 2 seconds for each slotted Bone Tyrant ability.\n\nCasting a corpse consumer ability consumes Beautiful Corpse, treating you as a corpse.",
      },
    ],
    icons: {
      "chest:heavy": "/esoui/art/icons/gear_nightbladeclass1_chest_a.dds",
      "chest:light": "/esoui/art/icons/gear_nightbladeclass1_chest_a.dds",
      "chest:medium": "/esoui/art/icons/gear_nightbladeclass1_chest_a.dds",
      "head:heavy": "/esoui/art/icons/gear_nightbladeclass1_head_a.dds",
      "head:light": "/esoui/art/icons/gear_nightbladeclass1_head_a.dds",
      "head:medium": "/esoui/art/icons/gear_nightbladeclass1_head_a.dds",
      "necklace": "/esoui/art/icons/gear_breton_neck_a.dds",
      "ring": "/esoui/art/icons/gear_breton_ring_a.dds",
      "shoulders:heavy": "/esoui/art/icons/gear_nightbladeclass1_shoulder_a.dds",
      "shoulders:light": "/esoui/art/icons/gear_nightbladeclass1_shoulder_a.dds",
      "shoulders:medium": "/esoui/art/icons/gear_nightbladeclass1_shoulder_a.dds",
      "waist:heavy": "/esoui/art/icons/gear_nightbladeclass1_waist_a.dds",
      "waist:light": "/esoui/art/icons/gear_nightbladeclass1_waist_a.dds",
      "waist:medium": "/esoui/art/icons/gear_nightbladeclass1_waist_a.dds",
    },
    classId: "necromancer",
  },
  {
    id: "noble-duelists-silks",
    name: "Noble Duelist's Silks",
    esoSetId: 46,
    subcategoryId: "dungeon",
    valid: ["*:light"],
    bonuses: [
      {
        count: 2,
        status: "supported",
        effects: [{ metricId: "stamina-recovery", effectType: "integer", effectValue: 129 }],
        description: "Adds 129 Stamina Recovery",
      },
      {
        count: 3,
        status: "supported",
        effects: [{ metricId: "power", effectType: "integer", effectValue: 129 }],
        description: "Adds 129 Weapon and Spell Damage",
      },
      {
        count: 4,
        status: "supported",
        effects: [{ metricId: "power", effectType: "integer", effectValue: 129 }],
        description: "Adds 129 Weapon and Spell Damage",
      },
      {
        count: 5,
        status: "unsupported",
        effects: [],
        description:
          "When you deal damage with a Light or Heavy Attack in melee range, you increase the damage of your Light and Heavy Attacks against monsters by 2110 for 15 seconds. This effect can occur once every 12 seconds.",
      },
    ],
    icons: {
      "axe": "/esoui/art/icons/gear_breton_1haxe_d.dds",
      "battleaxe": "/esoui/art/icons/gear_breton_2haxe_d.dds",
      "bow": "/esoui/art/icons/gear_breton_bow_d.dds",
      "chest:*": "/esoui/art/icons/gear_breton_light_robe_d.dds",
      "dagger": "/esoui/art/icons/gear_breton_dagger_c.dds",
      "feet:*": "/esoui/art/icons/gear_breton_light_feet_c.dds",
      "greatsword": "/esoui/art/icons/gear_dunmer_2hsword_d.dds",
      "hands:*": "/esoui/art/icons/gear_breton_light_hands_d.dds",
      "head:*": "/esoui/art/icons/gear_breton_light_head_d.dds",
      "ice-staff": "/esoui/art/icons/gear_breton_staff_d.dds",
      "inferno-staff": "/esoui/art/icons/gear_dunmer_staff_d.dds",
      "legs:*": "/esoui/art/icons/gear_breton_light_legs_c.dds",
      "lightning-staff": "/esoui/art/icons/gear_breton_staff_d.dds",
      "mace": "/esoui/art/icons/gear_argonian_1hhammer_d.dds",
      "maul": "/esoui/art/icons/gear_breton_2hhammer_d.dds",
      "necklace": "/esoui/art/icons/gear_breton_neck_a.dds",
      "restoration-staff": "/esoui/art/icons/gear_breton_staff_d.dds",
      "ring": "/esoui/art/icons/gear_breton_ring_a.dds",
      "shield": "/esoui/art/icons/gear_breton_shield_d.dds",
      "shoulders:*": "/esoui/art/icons/gear_breton_light_shoulders_c.dds",
      "sword": "/esoui/art/icons/gear_breton_1hsword_d.dds",
      "waist:*": "/esoui/art/icons/gear_breton_light_waist_d.dds",
    },
  },
  {
    id: "nobles-conquest",
    name: "Noble's Conquest",
    esoSetId: 176,
    subcategoryId: "crafted",
    valid: ["*"],
    bonuses: [
      {
        count: 2,
        status: "supported",
        effects: [{ metricId: "health-maximum", effectType: "integer", effectValue: 1206 }],
        description: "Adds 1206 Maximum Health",
      },
      {
        count: 3,
        status: "supported",
        effects: [{ metricId: "stamina-maximum", effectType: "integer", effectValue: 1096 }],
        description: "Adds 1096 Maximum Stamina",
      },
      {
        count: 4,
        status: "supported",
        effects: [
          { metricId: "healing-taken-base", effectType: "fractional-change", effectValue: 0.04 },
        ],
        description: "Adds 4% Healing Taken",
      },
      {
        count: 5,
        status: "unsupported",
        effects: [],
        description:
          "When you Bash a target, you heal for 3540 Health over 10 seconds and apply Minor Vulnerability to the enemy for 10 seconds, increasing their damage taken by 5%. The heal can only activate once every 10 seconds and scales off your Max Health.",
      },
    ],
    icons: {
      "chest:heavy": "/esoui/art/icons/gear_breton_heavy_chest_d.dds",
      "chest:light": "/esoui/art/icons/gear_breton_light_robe_d.dds",
      "chest:medium": "/esoui/art/icons/gear_breton_medium_chest_d.dds",
      "head:heavy": "/esoui/art/icons/gear_breton_heavy_head_d.dds",
      "head:light": "/esoui/art/icons/gear_breton_light_head_d.dds",
      "head:medium": "/esoui/art/icons/gear_breton_medium_head_d.dds",
      "necklace": "/esoui/art/icons/gear_breton_neck_a.dds",
      "ring": "/esoui/art/icons/gear_breton_ring_a.dds",
      "shoulders:heavy": "/esoui/art/icons/gear_breton_heavy_shoulders_d.dds",
      "shoulders:light": "/esoui/art/icons/gear_breton_light_shoulders_d.dds",
      "shoulders:medium": "/esoui/art/icons/gear_breton_medium_shoulders_d.dds",
      "waist:heavy": "/esoui/art/icons/gear_breton_heavy_waist_d.dds",
      "waist:light": "/esoui/art/icons/gear_breton_light_waist_d.dds",
      "waist:medium": "/esoui/art/icons/gear_breton_medium_waist_d.dds",
    },
  },
  {
    id: "nocturnals-favor",
    name: "Nocturnal's Favor",
    esoSetId: 387,
    subcategoryId: "crafted",
    valid: ["*"],
    bonuses: [
      {
        count: 2,
        status: "supported",
        effects: [{ metricId: "stamina-recovery", effectType: "integer", effectValue: 129 }],
        description: "Adds 129 Stamina Recovery",
      },
      {
        count: 3,
        status: "supported",
        effects: [{ metricId: "health-maximum", effectType: "integer", effectValue: 1206 }],
        description: "Adds 1206 Maximum Health",
      },
      {
        count: 4,
        status: "supported",
        effects: [{ metricId: "health-maximum", effectType: "integer", effectValue: 1206 }],
        description: "Adds 1206 Maximum Health",
      },
      {
        count: 5,
        status: "unsupported",
        effects: [],
        description:
          "Whenever you successfully Dodge, you heal yourself for 2946 Health over 5 seconds. This effect can occur every 5 seconds and scales off the higher of your Max Magicka or Stamina.",
      },
    ],
    icons: {
      "axe": "/esoui/art/icons/gear_breton_1haxe_d.dds",
      "battleaxe": "/esoui/art/icons/gear_breton_2haxe_d.dds",
      "bow": "/esoui/art/icons/gear_breton_bow_d.dds",
      "chest:heavy": "/esoui/art/icons/gear_breton_heavy_chest_d.dds",
      "chest:light": "/esoui/art/icons/gear_breton_light_robe_d.dds",
      "chest:medium": "/esoui/art/icons/gear_breton_medium_chest_d.dds",
      "dagger": "/esoui/art/icons/gear_breton_dagger_d.dds",
      "feet:heavy": "/esoui/art/icons/gear_breton_heavy_feet_d.dds",
      "feet:light": "/esoui/art/icons/gear_breton_light_feet_d.dds",
      "feet:medium": "/esoui/art/icons/gear_breton_medium_feet_d.dds",
      "greatsword": "/esoui/art/icons/gear_breton_2hsword_d.dds",
      "hands:heavy": "/esoui/art/icons/gear_breton_heavy_hands_d.dds",
      "hands:light": "/esoui/art/icons/gear_breton_light_hands_d.dds",
      "hands:medium": "/esoui/art/icons/gear_breton_medium_hands_d.dds",
      "head:heavy": "/esoui/art/icons/gear_breton_heavy_head_d.dds",
      "head:light": "/esoui/art/icons/gear_breton_light_head_d.dds",
      "head:medium": "/esoui/art/icons/gear_breton_medium_head_d.dds",
      "ice-staff": "/esoui/art/icons/gear_breton_staff_d.dds",
      "inferno-staff": "/esoui/art/icons/gear_breton_staff_d.dds",
      "legs:heavy": "/esoui/art/icons/gear_breton_heavy_legs_d.dds",
      "legs:light": "/esoui/art/icons/gear_breton_light_legs_d.dds",
      "legs:medium": "/esoui/art/icons/gear_breton_medium_legs_d.dds",
      "lightning-staff": "/esoui/art/icons/gear_breton_staff_d.dds",
      "mace": "/esoui/art/icons/gear_breton_1hhammer_d.dds",
      "maul": "/esoui/art/icons/gear_breton_2hhammer_d.dds",
      "necklace": "/esoui/art/icons/gear_breton_neck_a.dds",
      "restoration-staff": "/esoui/art/icons/gear_breton_staff_d.dds",
      "ring": "/esoui/art/icons/gear_breton_ring_a.dds",
      "shield": "/esoui/art/icons/gear_breton_shield_d.dds",
      "shoulders:heavy": "/esoui/art/icons/gear_breton_heavy_shoulders_d.dds",
      "shoulders:light": "/esoui/art/icons/gear_breton_light_shoulders_d.dds",
      "shoulders:medium": "/esoui/art/icons/gear_breton_medium_shoulders_d.dds",
      "sword": "/esoui/art/icons/gear_breton_1hsword_d.dds",
      "waist:heavy": "/esoui/art/icons/gear_breton_heavy_waist_d.dds",
      "waist:light": "/esoui/art/icons/gear_breton_light_waist_d.dds",
      "waist:medium": "/esoui/art/icons/gear_breton_medium_waist_d.dds",
    },
  },
  {
    id: "nocturnals-ploy",
    name: "Nocturnal's Ploy",
    esoSetId: 669,
    subcategoryId: "pvp",
    valid: ["*:medium"],
    bonuses: [
      {
        count: 2,
        status: "supported",
        effects: [{ metricId: "penetration", effectType: "integer", effectValue: 1487 }],
        description: "Adds 1487 Offensive Penetration",
      },
      {
        count: 3,
        status: "supported",
        effects: [{ metricId: "resistance-critical", effectType: "integer", effectValue: 424 }],
        description: "Adds 424 Critical Resistance",
      },
      {
        count: 4,
        status: "supported",
        effects: [{ metricId: "stamina-recovery", effectType: "integer", effectValue: 129 }],
        description: "Adds 129 Stamina Recovery",
      },
      {
        count: 5,
        status: "unsupported",
        effects: [],
        description:
          "When you directly apply a Major Debuff to an enemy, remove a Major Buff with a duration from the target. When you directly apply a Minor Debuff, remove a Minor Buff from the target. These effects can both occur once every 15 seconds and a target can be affected once every 15 seconds.\n\nThis does not apply to abilities with delays.",
      },
    ],
    icons: {
      "axe": "/esoui/art/icons/gear_breton_1haxe_d.dds",
      "battleaxe": "/esoui/art/icons/gear_breton_2haxe_d.dds",
      "bow": "/esoui/art/icons/gear_breton_bow_d.dds",
      "chest:*": "/esoui/art/icons/gear_breton_medium_chest_d.dds",
      "dagger": "/esoui/art/icons/gear_breton_dagger_d.dds",
      "feet:*": "/esoui/art/icons/gear_breton_medium_feet_d.dds",
      "greatsword": "/esoui/art/icons/gear_breton_2hsword_d.dds",
      "hands:*": "/esoui/art/icons/gear_breton_medium_hands_d.dds",
      "head:*": "/esoui/art/icons/gear_breton_medium_head_d.dds",
      "ice-staff": "/esoui/art/icons/gear_breton_staff_d.dds",
      "inferno-staff": "/esoui/art/icons/gear_breton_staff_d.dds",
      "legs:*": "/esoui/art/icons/gear_breton_medium_legs_d.dds",
      "lightning-staff": "/esoui/art/icons/gear_breton_staff_d.dds",
      "mace": "/esoui/art/icons/gear_breton_1hhammer_d.dds",
      "maul": "/esoui/art/icons/gear_breton_2hhammer_d.dds",
      "necklace": "/esoui/art/icons/gear_breton_neck_a.dds",
      "restoration-staff": "/esoui/art/icons/gear_breton_staff_d.dds",
      "ring": "/esoui/art/icons/gear_breton_ring_a.dds",
      "shield": "/esoui/art/icons/gear_breton_shield_d.dds",
      "shoulders:*": "/esoui/art/icons/gear_breton_medium_shoulders_d.dds",
      "sword": "/esoui/art/icons/gear_breton_1hsword_d.dds",
      "waist:*": "/esoui/art/icons/gear_breton_medium_waist_d.dds",
    },
  },
]
