import type { SkillTemplate } from "../character-skill-template/character-skill-template.module.code.ts"

export const CHARACTER_SKILLS_60 = {
  "shadow-silk": {
    id: "shadow-silk" as const,
    esoSkillId: 43489,
    name: "Shadow Silk",
    baseName: "Trapping Webs",
    skillLineId: "guild-undaunted" as const,
    skillType: "active" as const,
    description:
      "Hurl webs to ensnare your foes, reducing the Movement Speed of enemies in the area by 50% and dealing 1799 Physical Damage. After 10 seconds the webs explode, dealing 2399 Poison Damage to enemies within.\n\nA ranged ally can activate the Black Widow synergy on an affected enemy, dealing 2249 Poison Damage to them and summoning a spider to attack for 10 seconds. The spider bites enemies for 673 Physical Damage and can poison them for 4488 Poison Damage over 10 seconds.",
    icon: "/esoui/art/icons/ability_undaunted_003_a.dds",
    isMorph: true,
    morphIndex: 1,
    lineRankNeeded: 2,
    rank: 8,
    subcategoryId: "guild-undaunted" as const,
  },
  "shadow-silk-41990": {
    id: "shadow-silk-41990" as const,
    esoSkillId: 41990,
    name: "Shadow Silk",
    baseName: "Trapping Webs",
    skillLineId: "guild-undaunted" as const,
    skillType: "active" as const,
    description:
      "Hurl webs to ensnare your foes, reducing the Movement Speed of enemies in the area by |cffffff50|r% and dealing |cffffff6611|r Physical Damage. After |cffffff10|r seconds the webs explode, dealing |cffffff8814|r Poison Damage to enemies within.\n\nA ranged ally can activate the Black Widow synergy on an affected enemy, dealing |cffffff7819|r Poison Damage to them and summoning a spider to attack for |cffffff10|r seconds. The spider bites enemies for |cffffff2346|r Physical Damage and can poison them for |cffffff14748|r Poison Damage over |cffffff10|r seconds.",
    icon: "/esoui/art/icons/ability_undaunted_003_a.dds",
    isMorph: true,
    morphIndex: 1,
    lineRankNeeded: 2,
    rank: 2,
    subcategoryId: "guild-undaunted" as const,
  },
  "shadowy-disguise": {
    id: "shadowy-disguise" as const,
    esoSkillId: 36368,
    name: "Shadowy Disguise",
    baseName: "Shadow Cloak",
    skillLineId: "nightblade-shadow" as const,
    skillType: "active" as const,
    description:
      "Cloak yourself in shadow to become invisible. When moving your Magicka Recovery is disabled and when not moving Shadowy Disguise is half cost. Your next direct damage attack will Critically Strike.\n\nWhen Shadowy Disguise begins or ends, you gain Born From Shadow for 10 seconds, increasing your damage done to monsters by 10%.\n\nWhile slotted on either bar, you gain Minor Protection, reducing your damage taken by 5%.",
    icon: "/esoui/art/icons/ability_nightblade_004_a.dds",
    isMorph: true,
    morphIndex: 1,
    lineRankNeeded: 4,
    rank: 8,
    subcategoryId: "nightblade-shadow" as const,
    effects: [
      {
        "buffId": "minor-protection",
        "seconds": Number.POSITIVE_INFINITY,
        "slottedBehavior": "either-bar",
      },
    ] as const,
  },
  "shadowy-disguise-25380": {
    id: "shadowy-disguise-25380" as const,
    esoSkillId: 25380,
    name: "Shadowy Disguise",
    baseName: "Shadow Cloak",
    skillLineId: "nightblade-shadow" as const,
    skillType: "active" as const,
    description:
      "Cloak yourself in shadow to become invisible. When moving your Magicka Recovery is disabled and when not moving Shadowy Disguise is half cost. Your next direct damage attack will Critically Strike.\n\nWhen Shadowy Disguise begins or ends, you gain Born From Shadow for |cffffff10|r seconds, increasing your damage done to monsters by |cffffff10|r%.\n\nWhile slotted on either bar, you gain Minor Protection, reducing your damage taken by |cffffff5|r%.",
    icon: "/esoui/art/icons/ability_nightblade_004_a.dds",
    isMorph: true,
    morphIndex: 1,
    lineRankNeeded: 4,
    rank: 4,
    subcategoryId: "nightblade-shadow" as const,
  },
  "shadowy-supplier": {
    id: "shadowy-supplier" as const,
    esoSkillId: 77396,
    name: "Shadowy Supplier",
    baseName: "Shadowy Supplier",
    skillLineId: "guild-dark-brotherhood" as const,
    skillType: "passive" as const,
    description:
      "A contact from the Brotherhood provides beneficial items once per day. This contact is located in Outlaw Refuges, the Gold Coast Dark Brotherhood Sanctuary, and the Hew's Bane Thieves Den.",
    icon: "/esoui/art/icons/ability_darkbrotherhood_passive_003.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 4,
    rank: 1,
    subcategoryId: "guild-dark-brotherhood" as const,
    effects: [] as const,
    status: "unsupported" as const,
  },
  "shatter-soul": {
    id: "shatter-soul" as const,
    esoSkillId: 43109,
    name: "Shatter Soul",
    baseName: "Soul Strike",
    skillLineId: "world-soul-magic" as const,
    skillType: "ultimate" as const,
    description:
      "Burn an enemy from the inside with soulfire, dealing 14814 Magic Damage over 5 seconds.  Upon completion, the soulfire overflows and explodes from the enemy, dealing 2399 Magic Damage to all enemies near them.\n\nWhile channeling this ability, you gain immunity to all disabling effects.\n\nEnemies affected by this ability are revealed for 3 seconds and may not enter stealth or invisibility.\n\nThis ability is considered direct damage.",
    icon: "/esoui/art/icons/ability_otherclass_002_a.dds",
    isMorph: true,
    morphIndex: 2,
    lineRankNeeded: 6,
    rank: 12,
    subcategoryId: "world-soul-magic" as const,
  },
  "shatter-soul-40414": {
    id: "shatter-soul-40414" as const,
    esoSkillId: 40414,
    name: "Shatter Soul",
    baseName: "Soul Strike",
    skillLineId: "world-soul-magic" as const,
    skillType: "ultimate" as const,
    description:
      "Burn an enemy from the inside with soulfire, dealing |cffffff48576|r Magic Damage over |cffffff5|r seconds.  Upon completion, the soulfire overflows and explodes from the enemy, dealing |cffffff8814|r Magic Damage to all enemies near them.\n\nWhile channeling this ability, you gain immunity to all disabling effects.\n\nEnemies affected by this ability are revealed for |cffffff3|r seconds and may not enter stealth or invisibility.\n\nThis ability is considered direct damage.",
    icon: "/esoui/art/icons/ability_otherclass_002_a.dds",
    isMorph: true,
    morphIndex: 2,
    lineRankNeeded: 6,
    rank: 6,
    subcategoryId: "world-soul-magic" as const,
  },
  "shattering-rocks-32678": {
    id: "shattering-rocks-32678" as const,
    esoSkillId: 32678,
    name: "Shattering Rocks",
    baseName: "Petrify",
    skillLineId: "dragonknight-earthen-heart" as const,
    skillType: "active" as const,
    description:
      "Encase an enemy in molten rock, reducing their movement speed by |cffffff50|r% for |cffffff1|r second. Upon completion, the target is stunned for |cffffff4|r seconds, or |cffffff8|r seconds against monsters. After the stun ends, the target takes |cffffff4796|r Flame Damage and you heal for |cffffff8679|r Health.\n\nThis stun cannot be blocked.\n\nThe molten rock melts through the enemy's armor and applies Minor Breach for |cffffff10|r seconds, reducing Armor by |cffffff2974|r.",
    icon: "/esoui/art/icons/ability_dragonknight_014b.dds",
    isMorph: true,
    morphIndex: 2,
    lineRankNeeded: 30,
    rank: 30,
    subcategoryId: "dragonknight-earthen-heart" as const,
  },
  "shattering-spines": {
    id: "shattering-spines" as const,
    esoSkillId: 30095,
    name: "Shattering Spines",
    baseName: "Encase",
    skillLineId: "sorcerer-dark-magic" as const,
    skillType: "active" as const,
    description:
      "Call forth Daedric shards from the earth to encase and immobilize all enemies in front of you for 4 seconds. After the effect ends the shards shatter, dealing 1979 Magic Damage to any enemy that was encased.\n\nEnemies hit are afflicted with Major Maim, reducing their damage done by 10% for 10 seconds.",
    icon: "/esoui/art/icons/ability_sorcerer_twister.dds",
    isMorph: true,
    morphIndex: 1,
    lineRankNeeded: 4,
    rank: 8,
    subcategoryId: "sorcerer-dark-magic" as const,
  },
  "shattering-spines-28308": {
    id: "shattering-spines-28308" as const,
    esoSkillId: 28308,
    name: "Shattering Spines",
    baseName: "Encase",
    skillLineId: "sorcerer-dark-magic" as const,
    skillType: "active" as const,
    description:
      "Call forth Daedric shards from the earth to encase and immobilize all enemies in front of you for |cffffff4|r seconds. After the effect ends the shards shatter, dealing |cffffff7272|r Magic Damage to any enemy that was encased.\n\nEnemies hit are afflicted with Major Maim, reducing their damage done by |cffffff10|r% for |cffffff10|r seconds.",
    icon: "/esoui/art/icons/ability_sorcerer_twister.dds",
    isMorph: true,
    morphIndex: 1,
    lineRankNeeded: 4,
    rank: 4,
    subcategoryId: "sorcerer-dark-magic" as const,
  },
  "shatterspike-mantle": {
    id: "shatterspike-mantle" as const,
    esoSkillId: 20323,
    name: "Shatterspike Mantle",
    baseName: "Earthspike Mantle",
    skillLineId: "dragonknight-earthen-heart" as const,
    skillType: "active" as const,
    description:
      "Envelop your body in molten spikes to increase your damage done by 100 and gain Major Resolve, increasing Physical and Spell Resistance by 5948 for 20 seconds.\n\nAs the armor forms you blast foes around you with shattered obsidian, causing them to take 17006 Flame Damage over 20 seconds. When this effect deals damage you gain a stack of Landslide, up to once every 10 seconds.",
    icon: "/esoui/art/icons/ability_dragonknight_007_a.dds",
    isMorph: true,
    morphIndex: 2,
    lineRankNeeded: 42,
    rank: 12,
    subcategoryId: "dragonknight-earthen-heart" as const,
  },
  "shield-charge": {
    id: "shield-charge" as const,
    esoSkillId: 28719,
    name: "Shield Charge",
    baseName: "Shield Charge",
    skillLineId: "weapon-one-hand-and-shield" as const,
    skillType: "active" as const,
    description:
      "Rush an enemy and ram them, dealing |cffffff4846|r Physical Damage and stunning them for |cffffff3|r seconds.",
    icon: "/esoui/art/icons/ability_1handed_003.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 20,
    rank: 20,
    subcategoryId: "weapon-one-hand-and-shield" as const,
  },
  "shield-discipline": {
    id: "shield-discipline" as const,
    esoSkillId: 86345,
    name: "Shield Discipline",
    baseName: "Shield Wall",
    skillLineId: "weapon-one-hand-and-shield" as const,
    skillType: "ultimate" as const,
    description:
      "Reinforce your shield, allowing you to automatically block all attacks at no cost for 8 seconds.\n\nYour One Hand and Shield non-Ultimate abilities cost nothing while this effect persists.",
    icon: "/esoui/art/icons/ability_1handed_006_b.dds",
    isMorph: true,
    morphIndex: 2,
    lineRankNeeded: 50,
    rank: 12,
    subcategoryId: "weapon-one-hand-and-shield" as const,
  },
  "shield-discipline-83310": {
    id: "shield-discipline-83310" as const,
    esoSkillId: 83310,
    name: "Shield Discipline",
    baseName: "Shield Wall",
    skillLineId: "weapon-one-hand-and-shield" as const,
    skillType: "ultimate" as const,
    description:
      "Reinforce your shield, allowing you to automatically block all attacks at no cost for |cffffff8|r seconds.\n\nYour One Hand and Shield non-Ultimate abilities cost nothing while this effect persists.",
    icon: "/esoui/art/icons/ability_1handed_006_b.dds",
    isMorph: true,
    morphIndex: 2,
    lineRankNeeded: 50,
    rank: 50,
    subcategoryId: "weapon-one-hand-and-shield" as const,
  },
  "shield-wall": {
    id: "shield-wall" as const,
    esoSkillId: 83272,
    name: "Shield Wall",
    baseName: "Shield Wall",
    skillLineId: "weapon-one-hand-and-shield" as const,
    skillType: "ultimate" as const,
    description:
      "Reinforce your shield, allowing you to automatically block all attacks at no cost for |cffffff6|r seconds.",
    icon: "/esoui/art/icons/ability_1handed_006.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 50,
    rank: 50,
    subcategoryId: "weapon-one-hand-and-shield" as const,
  },
  "shielded-assault": {
    id: "shielded-assault" as const,
    esoSkillId: 41526,
    name: "Shielded Assault",
    baseName: "Shield Charge",
    skillLineId: "weapon-one-hand-and-shield" as const,
    skillType: "active" as const,
    description:
      "Rush an enemy and ram them, dealing 1393 Physical Damage and stunning them for 3 seconds.\n\nYou gain a damage shield after the attack, absorbing 5121 damage for 6 seconds. This portion of the ability scales off your Max Health.",
    icon: "/esoui/art/icons/ability_1handed_003_a.dds",
    isMorph: true,
    morphIndex: 1,
    lineRankNeeded: 20,
    rank: 8,
    subcategoryId: "weapon-one-hand-and-shield" as const,
  },
  "shielded-assault-38401": {
    id: "shielded-assault-38401" as const,
    esoSkillId: 38401,
    name: "Shielded Assault",
    baseName: "Shield Charge",
    skillLineId: "weapon-one-hand-and-shield" as const,
    skillType: "active" as const,
    description:
      "Rush an enemy and ram them, dealing |cffffff4845|r Physical Damage and stunning them for |cffffff3|r seconds.\n\nYou gain a damage shield after the attack, absorbing |cffffff7258|r damage for |cffffff6|r seconds. This portion of the ability scales off your Max Health.",
    icon: "/esoui/art/icons/ability_1handed_003_a.dds",
    isMorph: true,
    morphIndex: 1,
    lineRankNeeded: 20,
    rank: 20,
    subcategoryId: "weapon-one-hand-and-shield" as const,
  },
} satisfies Record<string, SkillTemplate>
