import type { PageType } from "akasha/page/type/page-type.page-type.types.ts"

export const worldCheck = {
  id: "01a0de14-272c-7450-9354-16bc47966044",
  type: "page-type/page-type",
  slug: "world-check",
  definition: "a rule settling a declared action",
  pluralSlug: "checks",
  extends: ["page-type/world-mechanic", "page-type/domain"],
  parts: [
    "module-property-group/settling",
    "world-check/tower-attack-resolution",
    "world-check/tower-attribute-check",
    "world-check/tower-essence-absorption",
    "world-check/the-dating-game-closeness-scoring",
    "world-check/otherwhere-the-library-action-check",
    "world-check/otherwhere-the-library-harm",
    "world-check/otherwhere-the-library-standing",
    "world-check/otherwhere-ii-action-check",
    "world-check/otherwhere-ii-time-passing",
    "world-check/otherwhere-iii-time-passing",
    "world-check/otherwhere-iv-time-passing",
    "world-check/otherwhere-iv-action-check",
    "world-check/otherwhere-iv-needs",
    "world-check/otherwhere-iv-standing",
    "world-check/otherwhere-iv-harm",
    "world-check/otherwhere-iv-cultivating",
    "world-check/otherwhere-v-time-passing",
    "world-check/otherwhere-v-action-check",
    "world-check/otherwhere-v-harm",
    "world-check/otherwhere-v-needs",
    "world-check/otherwhere-v-standing",
    "world-check/otherwhere-v-growth",
    "world-check/otherwhere-v-language",
    "world-check/otherwhere-ii-needs",
    "world-check/otherwhere-ii-harm",
    "world-check/otherwhere-ii-experience",
    "world-check/otherwhere-ii-conditioning",
    "world-check/dragons-and-dungeons-check",
    "world-check/otherwhere-ix-time-passing",
    "world-check/otherwhere-ix-needs",
    "world-check/otherwhere-vii-time-passing",
    "world-check/otherwhere-vii-action-check",
    "world-check/otherwhere-vii-harm",
    "world-check/otherwhere-vii-needs",
    "world-check/otherwhere-vii-standing",
    "world-check/otherwhere-viii-time-passing",
  ],
  properties: [{ pageProperty: "module-property-group/settling", required: true, many: false }],
  decisions: [
    {
      decisionKind: "decision-kind/departure",
      statement:
        "A check's code is handed a reading and the dice rolled, and answers what they settle.",
    },
    {
      decisionKind: "decision-kind/departure",
      statement: "A check that rolls nothing is handed no dice.",
    },
    {
      decisionKind: "decision-kind/absence",
      statement: "Nothing a check's code does rolls a die.",
    },
    {
      decisionKind: "decision-kind/departure",
      statement: "A check refuses a reading that is not the shape its code reads.",
    },
  ],
  types: "ts",
  schema: "jsonl",
  loadedExport: ["settled", "added"],
} as const satisfies PageType
