import type { TemperLoreBook } from "akasha/temper/catalog/pursuit/temper-lore-collection/temper-lore-book/temper-lore-book.page-type.types.ts"

export const theOriginsOfConjuration = {
  id: "01a0d5f5-444c-79e6-8920-2deb4ced5a7e",
  type: "page-type/temper-lore-book",
  slug: "the-origins-of-conjuration",
  title: "The Origins of Conjuration",
  collection: "temper-lore-collection/rituals-and-revelations",
  esoBookId: 1498,
  bookIndex: 56,
  charted: true,
  onBookshelves: true,
  mapCounts: [
    { mapId: 7, mapCount: 8 },
    { mapId: 9, mapCount: 1 },
    { mapId: 10, mapCount: 7 },
    { mapId: 13, mapCount: 3 },
    { mapId: 16, mapCount: 7 },
    { mapId: 20, mapCount: 10 },
    { mapId: 26, mapCount: 8 },
    { mapId: 27, mapCount: 5 },
    { mapId: 125, mapCount: 4 },
    { mapId: 143, mapCount: 3 },
    { mapId: 255, mapCount: 17 },
    { mapId: 256, mapCount: 10 },
    { mapId: 660, mapCount: 9 },
    { mapId: 667, mapCount: 1 },
    { mapId: 1060, mapCount: 2 },
    { mapId: 1126, mapCount: 11 },
  ],
} as const satisfies TemperLoreBook
