import type { PageType } from "@akasha/pages/page-type"

export const computer = {
  id: "01a0658c-329a-7d00-b3f3-8abf47bf46cf",
  pageTypeSlug: "page-type",
  type: "page-type",
  slug: "computer",
  definition: "one machine Alan owns, and what it is worth running",
  pluralSlug: "computers",
  extends: ["page-type/page"],
  parts: [
    "calendar-date-property/purchase-date",
    "number-property/cost",
    "number-property/cpu-score",
    "number-property/gpu-score",
    "number-property/hdd",
    "number-property/ssd",
    "select-property/brand",
    "select-property/computer-status",
    "select-property/cpu",
    "select-property/display",
    "select-property/display-refresh-rate",
    "select-property/display-resolution",
    "select-property/form-factor",
    "select-property/gpu",
    "select-property/gpu-size",
    "select-property/operating-system",
    "select-property/ram",
    "text-property/computer-model",
    "url-property/computer-link",
  ],
  properties: [
    { pageProperty: "text-property/title", required: true, many: false },
    { pageProperty: "select-property/brand", required: false, many: false },
    { pageProperty: "number-property/cost", required: false, many: false },
    { pageProperty: "number-property/cpu-score", required: true, many: false },
    { pageProperty: "select-property/cpu", required: true, many: false },
    { pageProperty: "select-property/display-refresh-rate", required: false, many: false },
    { pageProperty: "select-property/display-resolution", required: false, many: false },
    { pageProperty: "select-property/display", required: false, many: false },
    { pageProperty: "select-property/form-factor", required: true, many: false },
    { pageProperty: "number-property/gpu-score", required: true, many: false },
    { pageProperty: "select-property/gpu-size", required: false, many: false },
    { pageProperty: "select-property/gpu", required: true, many: false },
    { pageProperty: "number-property/hdd", required: false, many: false },
    { pageProperty: "url-property/computer-link", required: false, many: false },
    { pageProperty: "text-property/computer-model", required: false, many: false },
    { pageProperty: "select-property/operating-system", required: true, many: false },
    { pageProperty: "calendar-date-property/purchase-date", required: false, many: false },
    { pageProperty: "select-property/ram", required: true, many: false },
    { pageProperty: "number-property/ssd", required: true, many: false },
    { pageProperty: "select-property/computer-status", required: true, many: false },
  ],
  invariants: [
    {
      invariantKind: "departure",
      statement: "A machine stays on the list once sold.",
    },
    {
      invariantKind: "departure",
      statement: "The cost and the replacement of a sold machine are still read.",
    },
    {
      invariantKind: "departure",
      statement: "Every score a machine has is worked out from its parts rather than written down.",
    },
  ],
  types: "ts",
} as const satisfies PageType
