import type { Domain } from "akasha/domains/domain.page-type.types.ts"

export const agent = {
  id: "01a0535c-f2cf-7d3b-9a3d-826379a0252b",
  type: "domain",
  slug: "agent",
  definition: "an agent and what puts its work to a model",
  parts: [
    "domain/claude-code",
    "domain/hook",
    "domain/messaging",
    "domain/model",
    "module/agent-attributes",
    "module/io-probe",
    "module/acting-agent",
    "module/agent-page-reading",
    "module/agent-proc-liveness",
    "module/agent-proc-tree",
    "module/agent-turn-drawn",
    "module/last-said",
    "module/launch-flags",
    "module/proc-scan",
    "module/read-record",
    "module/refusals-keeping",
    "module/tool-access",
    "page-type/agent",
    "page-type/claude-account",
    "page-type/role",
  ],
} as const satisfies Domain
