import type { Domain } from "akasha/domains/domain.page-type.types.ts"

export const temperAddonGenerators = {
  id: "01a06073-2499-7d6c-8220-9fb541b99067",
  type: "domain",
  slug: "temper-addon-generators",
  definition: "the source text of every data file temper renders from its own pages",
  parts: [
    "module/addon-data-page",
    "module/do-not-edit",
    "module/item-category-tree",
    "module/metric-tree",
    "module/parse-restore-metrics-from-ability-text",
    "module/render-metric-effect",
    "module/render-quality-values",
    "module/temper-armor-enchant",
    "module/temper-armor-trait",
    "module/temper-armor-weight",
    "module/temper-character-skill-activation",
    "module/temper-comparison-op",
    "module/temper-eso-companion-equipment-constant",
    "module/temper-eso-player-equipment-constant",
    "module/temper-eso-trait-map",
    "module/temper-grimoire",
    "module/temper-inventory-currency",
    "module/temper-jewelry-enchant",
    "module/temper-jewelry-trait",
    "module/temper-location-type",
    "module/temper-rule-template",
    "module/temper-scribed-skill",
    "module/temper-set",
    "module/temper-set-category",
    "module/temper-skill",
    "module/temper-weapon-enchant",
    "module/temper-weapon-trait",
    "module/temper-weapon-type",
    "module/tree-node-under",
    "module/web-rule-knowledge",
    "module/web-rule-level",
    "module/web-rule-potion-data",
    "module/web-rule-potion-effects",
    "module/web-rule-quality",
    "module/web-rule-research",
    "module/web-rule-set-sources",
    "module/web-rule-stack-fullness",
    "module/web-rule-traits",
    "module/web-rule-value",
    "module/web-rule-wanted-and-stock",
  ],
  invariants: [
    {
      invariantKind: "departure",
      statement: "A generator here renders source text and writes no file.",
    },
    {
      invariantKind: "departure",
      statement: "A key a generator renders is written as a string literal rather than bare.",
    },
    {
      invariantKind: "departure",
      statement: "Where a rendered file lands is settled by the caller.",
    },
    {
      invariantKind: "departure",
      statement:
        "A rendered file landing outside akasha has a line telling a reader not to edit that file.",
    },
  ],
} as const satisfies Domain
