import type { TemperLoreBook } from "akasha/temper/catalog/pursuit/temper-lore-collection/temper-lore-book/temper-lore-book.page-type.types.ts"

export const confessionsOfAKhajiitiFurTrader = {
  id: "01a0d5f1-f450-7dfc-8373-912d71692ab3",
  type: "page-type/temper-lore-book",
  slug: "confessions-of-a-khajiiti-fur-trader",
  title: "Confessions of a Khajiiti Fur Trader",
  collection: "temper-lore-collection/criminal-correspondence",
  esoBookId: 1155,
  bookIndex: 34,
  charted: true,
  onBookshelves: true,
  mapCounts: [
    { mapId: 7, mapCount: 29 },
    { mapId: 10, mapCount: 11 },
    { mapId: 13, mapCount: 3 },
    { mapId: 16, mapCount: 4 },
    { mapId: 20, mapCount: 6 },
    { mapId: 26, mapCount: 8 },
    { mapId: 27, mapCount: 6 },
    { mapId: 125, mapCount: 7 },
    { mapId: 143, mapCount: 16 },
    { mapId: 255, mapCount: 23 },
    { mapId: 256, mapCount: 17 },
    { mapId: 660, mapCount: 4 },
    { mapId: 667, mapCount: 1 },
    { mapId: 1060, mapCount: 9 },
    { mapId: 1126, mapCount: 9 },
  ],
} as const satisfies TemperLoreBook
