import type { TemperSet } from "akasha/temper/catalog/gear/temper-set/temper-set.page-type.types.ts"

export const knightErrantsMail = {
  id: "019e66e6-a099-79b9-b689-ed17ce46a343",
  type: "page-type/temper-set",
  slug: "knight-errants-mail",
  title: "Knight-errant's Mail",
  key: "knight-errants-mail",
  esoSetId: 309,
  setWayshrines: [186, 186, 186],
  setTypeId: 6,
  setNameZh: "游侠骑士铠甲",
  setNameRu: "Доспех странствующего рыцаря",
  setNameFr: "Maille de chevalier errant",
  setNameEs: "Cota de caballero errante",
  setNameDe: "Platten des Wanderritters",
  setDropZones: [38, 92, 92],
  setDropMechanics: [28],
  setDlcId: 0,
  itemBrowserSources: ["38"],
  itemBrowserPlaceKinds: [3],
  itemBrowserItemId: 107665,
  esoItemIds: [
    107630, 107631, 107632, 107633, 107634, 107638, 107644, 107645, 107646, 107647, 107648, 107649,
    107650, 107651,
  ],
  esoArmorTypes: ["ARMORTYPE_HEAVY"],
  esoEquipTypes: [
    "EQUIP_TYPE_CHEST",
    "EQUIP_TYPE_FEET",
    "EQUIP_TYPE_HAND",
    "EQUIP_TYPE_HEAD",
    "EQUIP_TYPE_LEGS",
    "EQUIP_TYPE_NECK",
    "EQUIP_TYPE_OFF_HAND",
    "EQUIP_TYPE_ONE_HAND",
    "EQUIP_TYPE_RING",
    "EQUIP_TYPE_SHOULDERS",
    "EQUIP_TYPE_WAIST",
  ],
  esoWeaponTypes: [
    "WEAPONTYPE_AXE",
    "WEAPONTYPE_DAGGER",
    "WEAPONTYPE_HAMMER",
    "WEAPONTYPE_SHIELD",
    "WEAPONTYPE_SWORD",
  ],
  category: "temper-set-category/dungeon",
  valid: ["*:heavy"],
  bonuses: "jsonl",
  icons: "jsonl",
} as const satisfies TemperSet
