import { akashaRoot } from "akasha/page/modules/checkout-roots/checkout-roots.module.code.ts"

export const ROOT = akashaRoot()
export const HEADER = "# DO NOT EDIT — generated by infrastructure/container-image/dockerfile\n"
