import { resolve } from "node:path"
import type { ServiceConfig } from "../dockerfile-extensions/dockerfile-extensions.module.code.ts"

export const ROOT = resolve(import.meta.dirname, "../../../..")
export const HEADER = "# DO NOT EDIT — generated by akasha/infrastructure/dockerfiles\n"

export const SERVICES: Record<string, ServiceConfig> = {
  "auth-proxy": { type: "bun-service", dir: "akasha/infrastructure/auth-proxy" },
  "gfs-promoter": {
    type: "bun-service",
    dir: "akasha/infrastructure/backup-retention",
  },
  "alanwalton-calendar-sync": {
    type: "bun-service",
    dir: "akasha/calendar-sync",
  },
  ci: {
    type: "tool-image",
    dir: "infra/lib",
    extensionFile: "ci.dockerfile-extensions.json",
  },
  "bun-git": {
    type: "tool-image",
    dir: "infra/lib",
    extensionFile: "bun-git.dockerfile-extensions.json",
  },
  buildkit: {
    type: "tool-image",
    dir: "infra/lib",
    extensionFile: "buildkit.dockerfile-extensions.json",
  },
  kubectl: {
    type: "tool-image",
    dir: "infra/lib",
    extensionFile: "kubectl.dockerfile-extensions.json",
  },
}
