import type { StoryRead } from "../../story-read.page-type.ts"

export const dungeonDiverStealingAMonstersPower = {
  id: "01a0657d-ada2-75ab-a38a-67c94e81fc08",
  pageTypeSlug: "story-read",
  slug: "dungeon-diver-stealing-a-monsters-power",
  title: "Dungeon Diver: Stealing A Monster’s Power",
  worldSlug: "dungeon-diver-stealing-a-monsters-power",
  source: "royal-road",
  author: "KaeNovels",
  rank: "C",
  publicationStatus: "completed",
  externalTags: [
    "LitRPG",
    "Portal Fantasy / Isekai",
    "Progression",
    "Anti-Hero Lead",
    "Strategy",
    "Action",
    "Adventure",
    "Fantasy",
    "Mystery",
    "Dungeon Crawler",
    "Magic",
    "Male Lead",
    "Secret Identity",
    "Slice of Life",
    "Strong Lead",
  ],
  unitSlug: "words",
  externalLink: "https://www.royalroad.com/fiction/64223/dungeon-diver-stealing-a-monsters-power",
  externalId: "64223",
  prose: "txt",
} as const satisfies StoryRead
