import type { TemperSet } from "akasha/temper/catalog/gear/temper-set/temper-set.page-type.types.ts"

export const mendersWard = {
  id: "019e6484-5fb6-7685-a185-bd0a354b1b95",
  type: "page-type/temper-set",
  slug: "menders-ward",
  title: "Mender's Ward",
  key: "menders-ward",
  esoSetId: 416,
  hashPlace: 314,
  esoItemIds: [145026],
  esoEquipTypes: ["EQUIP_TYPE_TWO_HAND"],
  esoWeaponTypes: ["WEAPONTYPE_HEALING_STAFF"],
  setWayshrines: [378, 378, 378],
  setTypeId: 1,
  setNameZh: "治疗师的结界",
  setNameRu: "Оберег лекаря",
  setNameFr: "Garde du soigneur",
  setNameEs: "Guardia del sanador",
  setNameDe: "Schutz des Pflegers",
  setDropZones: [1082, 726, 726],
  setDropMechanics: [5, 5],
  setDlcId: 12,
  itemBrowserSources: ["1082"],
  itemBrowserItemId: 145043,
  category: "temper-set-category/arena",
  valid: ["restoration-staff"],
  bonuses: "jsonl",
  icons: "jsonl",
} as const satisfies TemperSet
