import type { WorkspacePackage } from "@akasha/code-system/workspace-package"

export const designLayout = {
  id: "01a05b82-8b9b-7e30-9148-8941b6ccd5ff",
  pageTypeSlug: "workspace-package",
  slug: "design-layout",
  definition: "the frame, columns and panels a browser draws a page's content in",
  manifest: "json",
  partSlugs: [
    "module/app-shell",
    "module/app-shell-bottom-nav",
    "module/app-shell-context",
    "module/app-shell-more-drawer",
    "module/app-shell-sidebar",
    "module/balanced-columns",
    "module/balanced-columns-layout",
    "module/column-layout",
    "module/layout-context",
    "module/layout-data",
    "module/list-content-skeleton",
    "module/load-more-button",
    "module/loading-container",
    "module/nav-active",
    "module/nav-types",
    "module/page-layout",
    "module/page-layout-data",
    "module/page-tab-header",
    "module/paginated-card-grid",
    "module/panel-card",
    "module/panel-card-data",
    "module/panel-default-open-context",
    "module/panel-toggle-context",
    "module/panel-toggle-provider",
    "module/responsive-columns",
    "module/responsive-columns-skeleton",
    "module/router-context",
    "module/scroll-to-card",
    "module/select-bottom-nav-items",
    "module/select-drawer-groups",
    "module/sidebar-nav-group",
    "module/skeleton-presets",
    "module/skeleton-text",
    "module/use-column-count",
    "module/use-load-more",
    "module/use-sidebar-state",
    "module/use-stable-scroll",
    "module/virtual-card-grid",
  ],
} as const satisfies WorkspacePackage
