import type { SkillTemplate } from "../character-skill-template/character-skill-template.module.code.ts"

export const CHARACTER_SKILLS_63 = {
  "snipe": {
    id: "snipe" as const,
    esoSkillId: 28882,
    name: "Snipe",
    baseName: "Snipe",
    skillLineId: "weapon-bow" as const,
    skillType: "active" as const,
    description:
      "Plant a masterfully aimed arrow in an enemy's vital spot, dealing |cffffff8359|r Physical Damage.",
    icon: "/esoui/art/icons/ability_bow_001.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 2,
    rank: 2,
    subcategoryId: "weapon-bow" as const,
  },
  "solar-barrage": {
    id: "solar-barrage" as const,
    esoSkillId: 24157,
    name: "Solar Barrage",
    baseName: "Solar Flare",
    skillLineId: "templar-dawns-wrath" as const,
    skillType: "active" as const,
    description:
      "Conjure solar energy to blast enemies around you, dealing 435 Magic Damage every 2 seconds and increasing your damage done with class abilities by 5% for 20 seconds.\n\nWhile this ability is active you gain Empower, increasing the damage of your Heavy Attacks against monsters by 70%.",
    icon: "/esoui/art/icons/ability_templar_solar_power.dds",
    isMorph: true,
    morphIndex: 2,
    lineRankNeeded: 4,
    rank: 12,
    subcategoryId: "templar-dawns-wrath" as const,
  },
  "solar-barrage-22095": {
    id: "solar-barrage-22095" as const,
    esoSkillId: 22095,
    name: "Solar Barrage",
    baseName: "Solar Flare",
    skillLineId: "templar-dawns-wrath" as const,
    skillType: "active" as const,
    description:
      "Conjure solar energy to blast enemies around you, dealing |cffffff1516|r Magic Damage every |cffffff2|r seconds and increasing your damage done with class abilities by |cffffff5|r% for |cffffff20|r seconds.\n\nWhile this ability is active you gain Empower, increasing the damage of your Heavy Attacks against monsters by |cffffff70|r%.",
    icon: "/esoui/art/icons/ability_templar_solar_power.dds",
    isMorph: true,
    morphIndex: 2,
    lineRankNeeded: 4,
    rank: 4,
    subcategoryId: "templar-dawns-wrath" as const,
  },
  "solar-disturbance": {
    id: "solar-disturbance" as const,
    esoSkillId: 24320,
    name: "Solar Disturbance",
    baseName: "Nova",
    skillLineId: "templar-dawns-wrath" as const,
    skillType: "ultimate" as const,
    description:
      "Call down a fragment of the sun, dealing 1161 Magic Damage every 1 second for 8 seconds to enemies in the area and applying Major Maim to them for 10 seconds, reducing their damage done by 10%.\n\nAn ally near the fragment can activate the Supernova synergy, dealing 2607 Magic Damage to all enemies in the area and stunning them for 3 seconds.",
    icon: "/esoui/art/icons/ability_templar_solar_disturbance.dds",
    isMorph: true,
    morphIndex: 2,
    lineRankNeeded: 12,
    rank: 12,
    subcategoryId: "templar-dawns-wrath" as const,
  },
  "solar-disturbance-21758": {
    id: "solar-disturbance-21758" as const,
    esoSkillId: 21758,
    name: "Solar Disturbance",
    baseName: "Nova",
    skillLineId: "templar-dawns-wrath" as const,
    skillType: "ultimate" as const,
    description:
      "Call down a fragment of the sun, dealing |cffffff4038|r Magic Damage every |cffffff1|r second for |cffffff8|r seconds to enemies in the area and applying Major Maim to them for |cffffff10|r seconds, reducing their damage done by |cffffff10|r%.\n\nAn ally near the fragment can activate the Supernova synergy, dealing |cffffff9576|r Magic Damage to all enemies in the area and stunning them for |cffffff3|r seconds.",
    icon: "/esoui/art/icons/ability_templar_solar_disturbance.dds",
    isMorph: true,
    morphIndex: 2,
    lineRankNeeded: 12,
    rank: 12,
    subcategoryId: "templar-dawns-wrath" as const,
  },
  "solar-flare": {
    id: "solar-flare" as const,
    esoSkillId: 22057,
    name: "Solar Flare",
    baseName: "Solar Flare",
    skillLineId: "templar-dawns-wrath" as const,
    skillType: "active" as const,
    description:
      "Conjure a ball of solar energy to heave at an enemy, dealing |cffffff8359|r Magic Damage and increasing your damage done with class abilities by |cffffff5|r% for |cffffff10|r seconds.\n\nAlso grants you Empower for |cffffff10|r seconds, increasing the damage of your Heavy Attacks against monsters by |cffffff70|r%.",
    icon: "/esoui/art/icons/ability_templar_solar_flare.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 4,
    rank: 4,
    subcategoryId: "templar-dawns-wrath" as const,
  },
  "solar-prison": {
    id: "solar-prison" as const,
    esoSkillId: 24301,
    name: "Solar Prison",
    baseName: "Nova",
    skillLineId: "templar-dawns-wrath" as const,
    skillType: "ultimate" as const,
    description:
      "Call down a fragment of the sun, dealing 1199 Magic Damage every 1 second for 8 seconds to enemies in the area and afflicting them with Major Maim, reducing their damage done by 10%.\n\nAn ally near the fragment can activate the Gravity Crush synergy, dealing 5215 Magic Damage to all enemies in the area and stunning them for 5 seconds.",
    icon: "/esoui/art/icons/ability_templar_solar_prison.dds",
    isMorph: true,
    morphIndex: 1,
    lineRankNeeded: 12,
    rank: 8,
    subcategoryId: "templar-dawns-wrath" as const,
  },
  "solar-prison-21755": {
    id: "solar-prison-21755" as const,
    esoSkillId: 21755,
    name: "Solar Prison",
    baseName: "Nova",
    skillLineId: "templar-dawns-wrath" as const,
    skillType: "ultimate" as const,
    description:
      "Call down a fragment of the sun, dealing |cffffff4170|r Magic Damage every |cffffff1|r second for |cffffff8|r seconds to enemies in the area and afflicting them with Major Maim, reducing their damage done by |cffffff10|r%.\n\nAn ally near the fragment can activate the Gravity Crush synergy, dealing |cffffff19152|r Magic Damage to all enemies in the area and stunning them for |cffffff5|r seconds.",
    icon: "/esoui/art/icons/ability_templar_solar_prison.dds",
    isMorph: true,
    morphIndex: 1,
    lineRankNeeded: 12,
    rank: 12,
    subcategoryId: "templar-dawns-wrath" as const,
  },
  "solvent-proficiency": {
    id: "solvent-proficiency" as const,
    esoSkillId: 70043,
    name: "Solvent Proficiency",
    baseName: "Solvent Proficiency",
    skillLineId: "craft-alchemy" as const,
    skillType: "passive" as const,
    description:
      "Allows the Alchemist to use Lorkhan's Tears and Alkahest to make Champion 150 potions and poisons.",
    icon: "/esoui/art/icons/ability_alchemy_001.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 1,
    rank: 8,
    subcategoryId: "craft-alchemy" as const,
  },
  "soothing-spores": {
    id: "soothing-spores" as const,
    esoSkillId: 93777,
    name: "Soothing Spores",
    baseName: "Fungal Growth",
    skillLineId: "warden-green-balance" as const,
    skillType: "active" as const,
    description:
      "Seed a large area of mushrooms in front of you, healing you and your allies for 2700 Health.\n\nHeals for 15% more on allies that are within 8 meters of you.",
    icon: "/esoui/art/icons/ability_warden_008_a.dds",
    isMorph: true,
    morphIndex: 2,
    lineRankNeeded: 1,
    rank: 12,
    subcategoryId: "warden-green-balance" as const,
  },
  "soothing-spores-85863": {
    id: "soothing-spores-85863" as const,
    esoSkillId: 85863,
    name: "Soothing Spores",
    baseName: "Fungal Growth",
    skillLineId: "warden-green-balance" as const,
    skillType: "active" as const,
    description:
      "Seed a large area of mushrooms in front of you, healing you and your allies for |cffffff8489|r Health.\n\nHeals for |cffffff15|r% more on allies that are within |cffffff8|r meters of you.",
    icon: "/esoui/art/icons/ability_warden_008_a.dds",
    isMorph: true,
    morphIndex: 2,
    lineRankNeeded: 1,
    rank: 1,
    subcategoryId: "warden-green-balance" as const,
  },
  "soul-assault": {
    id: "soul-assault" as const,
    esoSkillId: 43099,
    name: "Soul Assault",
    baseName: "Soul Strike",
    skillLineId: "world-soul-magic" as const,
    skillType: "ultimate" as const,
    description:
      "Burn an enemy from the inside with soulfire, dealing 20400 Magic Damage over 6 seconds.\n\nWhile channeling this ability, you gain immunity to all disabling effects.\n\nEnemies affected by this ability are revealed for 3 seconds and may not enter stealth or invisibility.\n\nThis ability is considered direct damage.",
    icon: "/esoui/art/icons/ability_otherclass_002_b.dds",
    isMorph: true,
    morphIndex: 1,
    lineRankNeeded: 6,
    rank: 8,
    subcategoryId: "world-soul-magic" as const,
  },
  "soul-assault-40420": {
    id: "soul-assault-40420" as const,
    esoSkillId: 40420,
    name: "Soul Assault",
    baseName: "Soul Strike",
    skillLineId: "world-soul-magic" as const,
    skillType: "ultimate" as const,
    description:
      "Burn an enemy from the inside with soulfire, dealing |cffffff66904|r Magic Damage over |cffffff6|r seconds.\n\nWhile channeling this ability, you gain immunity to all disabling effects.\n\nEnemies affected by this ability are revealed for |cffffff3|r seconds and may not enter stealth or invisibility.\n\nThis ability is considered direct damage.",
    icon: "/esoui/art/icons/ability_otherclass_002_b.dds",
    isMorph: true,
    morphIndex: 1,
    lineRankNeeded: 6,
    rank: 6,
    subcategoryId: "world-soul-magic" as const,
  },
  "soul-harvest": {
    id: "soul-harvest" as const,
    esoSkillId: 37545,
    name: "Soul Harvest",
    baseName: "Death Stroke",
    skillLineId: "nightblade-assassination" as const,
    skillType: "ultimate" as const,
    description:
      "Ravage an enemy with a spinning attack, dealing 3718 Magic Damage and increasing your damage against them by 20% for 8 seconds.\n\nAlso afflicts the enemy with Major Defile, reducing their healing received and damage shield strength by 12%.\n\nWhile slotted on either bar, any time you kill an enemy you gain 10 Ultimate.",
    icon: "/esoui/art/icons/ability_nightblade_007_b.dds",
    isMorph: true,
    morphIndex: 2,
    lineRankNeeded: 12,
    rank: 12,
    subcategoryId: "nightblade-assassination" as const,
  },
  "soul-harvest-36514": {
    id: "soul-harvest-36514" as const,
    esoSkillId: 36514,
    name: "Soul Harvest",
    baseName: "Death Stroke",
    skillLineId: "nightblade-assassination" as const,
    skillType: "ultimate" as const,
    description:
      "Ravage an enemy with a spinning attack, dealing |cffffff12924|r Magic Damage and increasing your damage against them by |cffffff20|r% for |cffffff8|r seconds.\n\nAlso afflicts the enemy with Major Defile, reducing their healing received and damage shield strength by |cffffff12|r%.\n\nWhile slotted on either bar, any time you kill an enemy you gain |cffffff10|r Ultimate.",
    icon: "/esoui/art/icons/ability_nightblade_007_b.dds",
    isMorph: true,
    morphIndex: 2,
    lineRankNeeded: 12,
    rank: 12,
    subcategoryId: "nightblade-assassination" as const,
  },
  "soul-lock": {
    id: "soul-lock" as const,
    esoSkillId: 45580,
    name: "Soul Lock",
    baseName: "Soul Lock",
    skillLineId: "world-soul-magic" as const,
    skillType: "passive" as const,
    description: "Killing an enemy has a 10% chance of automatically filling an empty Soul Gem.",
    icon: "/esoui/art/icons/ability_sorcerer_043.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 3,
    rank: 2,
    subcategoryId: "world-soul-magic" as const,
    effects: [] as const,
    status: "unsupported" as const,
  },
  "soul-of-flame": {
    id: "soul-of-flame" as const,
    esoSkillId: 32792,
    name: "Soul of Flame",
    baseName: "Core of Flame",
    skillLineId: "dragonknight-ardent-flame" as const,
    skillType: "active" as const,
    description:
      "Let the fire within draw heat to your soul, restoring |cffffff15|r% of your missing Magicka and Stamina every |cffffff2|r seconds over |cffffff4|r seconds.\n\nMuch of this heat is drawn from enemies around you. Those that are casting are interrupted, set Off Balance, and stunned for |cffffff2|r seconds.\n\nWhen this ability completes, you release this heat as a blast of fire that deals |cffffff10138|r Flame Damage to nearby enemies.",
    icon: "/esoui/art/icons/ability_dragonknight_012_a.dds",
    isMorph: true,
    morphIndex: 1,
    lineRankNeeded: 20,
    rank: 20,
    subcategoryId: "dragonknight-ardent-flame" as const,
  },
  "soul-shatter": {
    id: "soul-shatter" as const,
    esoSkillId: 45583,
    name: "Soul Shatter",
    baseName: "Soul Shatter",
    skillLineId: "world-soul-magic" as const,
    skillType: "passive" as const,
    description:
      "When your Health drops below 20% your soul explodes, dealing 1600 Magic Damage to enemies within 8 meters of you.\n\nThis effect can occur once every 2 minutes and scales off your Max Health.",
    icon: "/esoui/art/icons/ability_sorcerer_065.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 2,
    rank: 2,
    subcategoryId: "world-soul-magic" as const,
    effects: [] as const,
    status: "unsupported" as const,
  },
  "soul-shred": {
    id: "soul-shred" as const,
    esoSkillId: 25091,
    name: "Soul Shred",
    baseName: "Soul Shred",
    skillLineId: "nightblade-siphoning" as const,
    skillType: "ultimate" as const,
    description:
      "Ravage nearby enemies' souls with a night rune, dealing |cffffff12802|r Magic Damage and stunning them for |cffffff4|r seconds. \n\nAn ally can target a ravaged enemy and activate the Soul Leech synergy, dealing |cffffff10851|r Magic Damage to them and healing for the damage caused.",
    icon: "/esoui/art/icons/ability_nightblade_018.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 12,
    rank: 12,
    subcategoryId: "nightblade-siphoning" as const,
  },
} satisfies Record<string, SkillTemplate>
