import type { CarMake } from "../../car-make.page-type.ts"

export const dodge = {
  id: "019e4ad8-e1ae-7d32-b452-9036e1f6ab85",
  pageTypeSlug: "car-make",
  slug: "dodge",
  title: "Dodge",
  chargingNetworkAccess:
    "Current Dodge BEVs (Charger Daytona MY2024-MY2026) ship with a CCS1 port. Stellantis (Dodge/Jeep/Ram/Fiat/Maserati) opened Tesla Supercharger access in early 2026: customers use the Free2move Charge NACS-to-CCS1 adapter (sold for ~$230 at Stellantis-certified dealers and Mopar.com) to access ~27,500 V3 and V4 Supercharger stalls in North America. The 2027 model year Charger Daytona will be Stellantis' first vehicle with a factory-built NACS port. Stellantis operates the Free2move Charge app for locating Tesla and other public AC/DC stations; EVgo and ChargePoint roaming are accessible via the same app. No widely advertised free-charging promo currently bundled with new Daytona purchases as of mid-2026. Sources: https://www.prnewswire.com/news-releases/stellantis-expands-north-america-fast-charging-access-as-dodge-jeep-ram-fiat-and-maserati-bevs-plug-in-to-the-tesla-supercharger-network-302718753.html ; https://insideevs.com/news/782330/2027-dodge-charger-daytona-ev-tesla-charging-port-nacs/ ; https://moparinsiders.com/stellantis-expands-charging-access-with-tesla-supercharger-network-integration/",
  country: "United States",
  drmPolicy:
    "Dodge vehicles run Stellantis' Uconnect 5 infotainment, which is deeply tied to manufacturer-side connected services. Starting July 2025 Stellantis simplified its US connected-services tiers to 'Connect ONE' (included free for 10 years on MY2024+ vehicles — covers OTA updates, vehicle health, automatic SOS, remote lock/unlock, basic navigation, EV charging tools) and 'Connect Wi-Fi PLUS' (paid Wi-Fi hotspot tier). Core driving functions do NOT require an internet connection — the car will continue to drive when the cellular modem is offline or the subscription lapses — but features like remote start, remote lock/unlock, vehicle health alerts, and OTA updates stop working without an active subscription. Stellantis has issued multiple OTA-delivered recalls on the Charger Daytona (instrument-cluster blank-out fix, pedestrian-warning sound fix), showing the cars accept remote software changes by default. No widely documented examples of Stellantis remotely disabling already-paid features post-sale, but the Uconnect telematics stack has the technical capability. Sources: https://media.stellantisnorthamerica.com/newsrelease.do?id=25241 ; https://www.driveuconnect.com/ ; https://moparinsiders.com/stellantis-recalls-charger-daytona-ev-and-wagoneer-s-for-display-failure/",
  electrificationStrategy:
    "Dodge's electrification under parent Stellantis launched with the all-electric Charger Daytona BEV (model year 2024+), the brand's first production EV, positioned as an 'electric muscle car'. Parent Stellantis' original 'Dare Forward 2030' plan targeted 50% BEV mix in North America by 2030 and 100% BEV sales in Europe. As of 2026, Stellantis has formally pulled back from the Europe-only-BEV-by-2030 target, citing slow demand, and is leaning on PHEVs/hybrids as a bridge — though for Dodge specifically, the PHEV bridge has narrowed: the Hornet R/T PHEV was discontinued after MY2025 (January 2026 announcement) citing 25% tariff impact and weak sales. A multi-energy Charger lineup including the gasoline 'SIXPACK' inline-six variant is in production for MY2026, signaling Dodge is hedging EV-only positioning. Sources: https://www.media.stellantis.com/em-en/dodge/press/dodge-delivers-world-s-first-and-only-electric-muscle-car-announces-all-new-dodge-charger-multi-energy-lineup ; https://www.autoblog.com/news/why-stellantis-is-backing-off-its-2030-all-electric-plan ; https://www.autoblog.com/news/dodge-officially-kills-hornet",
  foundingYear: 1900,
  killSwitchPolicy:
    "Data unavailable: Stellantis has not made any specific public statements regarding implementation plans for the IIJA / HALT Drunk Driving Act impaired-driving-detection mandate. The NHTSA missed its 2024 rulemaking deadline; the outer statutory deadline for a final rule is now November 2027 and realistic in-vehicle deployment is unlikely before MY2029. Dodge/Stellantis vehicles already ship with the connected-services and OTA infrastructure (Uconnect 5) that would be the natural delivery vehicle for any required software-based driver-monitoring system. No bypass policy, no hardware-vs-software preference, and no production roadmap has been publicly committed. Sources: https://www.kbb.com/car-news/nhtsas-new-kill-switch-law-approaches-key-deadline/ ; https://www.kbb.com/car-news/explaining-the-car-kill-switch-controversy/ ; https://www.congress.gov/bill/119th-congress/house-bill/1137",
  nacsAdoption: "adapter",
  parentCorporation: "Stellantis N.V.",
  reliabilityNotes:
    "Charger Daytona BEV (MY2024-MY2025) has been hit with two early-life NHTSA recalls: ~20,271 units recalled in 2026 for an instrument-panel cluster software fault that can blank critical warning lights (owner letters mailed 2026-05-21), and ~8,390 units recalled in 2025 for missing pedestrian-warning amplifier software. Owner forums report misaligned driver doors, factory paint damage, intermittent passive-entry failures, Uconnect/Wi-Fi error messages, non-functional exterior hatch button, and seat-position reset bugs. The Daytona is Dodge's first production EV, so no multi-year reliability track record exists yet from Consumer Reports / J.D. Power / TrueDelta. Hornet R/T PHEV (Italian-built Tonale platform): J.D. Power rates it average for its segment; no major recall history at the model level distinct from broader Stellantis Uconnect issues. Sources: https://moparinsiders.com/stellantis-recalls-charger-daytona-ev-and-wagoneer-s-for-display-failure/ ; https://www.hotcars.com/2025-dodge-charger-daytona-pain-live-with-user-complains/ ; https://cars.usnews.com/cars-trucks/dodge/charger-daytona/reliability",
  trims: "jsonl",
  shortList: false,
  sources:
    "- https://www.dodge.com/hybrid-and-electric-vehicles.html\n- https://www.media.stellantis.com/em-en/dodge/press/dodge-delivers-world-s-first-and-only-electric-muscle-car-announces-all-new-dodge-charger-multi-energy-lineup\n- https://www.autoblog.com/news/dodge-officially-kills-hornet\n- https://moparinsiders.com/stellantis-recalls-charger-daytona-ev-and-wagoneer-s-for-display-failure/\n- https://www.prnewswire.com/news-releases/stellantis-expands-north-america-fast-charging-access-as-dodge-jeep-ram-fiat-and-maserati-bevs-plug-in-to-the-tesla-supercharger-network-302718753.html\n- https://insideevs.com/news/782330/2027-dodge-charger-daytona-ev-tesla-charging-port-nacs/\n- https://www.kbb.com/car-news/explaining-the-car-kill-switch-controversy/\n- https://media.stellantisnorthamerica.com/newsrelease.do?id=25241",
  exclusionReason: "All models excluded",
} as const satisfies CarMake
