import type { RouterApp } from "../../code-system/router-apps/router-app.page-type.ts"

export const alanAtlasWeb = {
  id: "01a06582-6b30-78d1-8b0b-1d3af65a8bcd",
  pageTypeSlug: "router-app",
  slug: "alan-atlas-web",
  definition: "the routes Alan's map site serves to a browser",
  manifest: "json",
  tunnelRoutes: "ts",
  appLayout: "tsx",
  rootRoute: "tsx",
  routeTable: "ts",
  serverEntry: "tsx",
  routerConfig: "ts",
  compileConfig: "json",
  viteConfig: "ts",
  server: "ts",
  sidebarBoot: "js",
  gitIgnore: "gitignore",
  routeTypesDirectory: true,
  declarationDirectory: true,
  bundleDirectory: true,
  parts: [
    "manifest/alanwalton-atlas",
    "stylesheet/alan-atlas-web-look",
    "module/atlas-answer-page-types",
    "module/atlas-answer-page-write",
    "module/atlas-answer-pages",
    "module/atlas-app-id",
    "module/atlas-app-shell",
    "module/atlas-auth-provider",
    "module/atlas-nav-commands",
    "module/atlas-nav-icon-svg",
    "module/atlas-nav-items",
    "module/basemap-range",
    "module/geoapify-search",
    "module/location-batch",
    "module/location-capture",
    "module/location-capture-client",
    "module/location-ingest-context",
    "module/location-map",
    "module/memory-watch",
    "module/pin-time-color",
    "module/pins",
    "module/place-candidate",
    "module/request-log",
    "route/atlas-api-pages",
    "route/atlas-api-nav-icon",
  ],
} as const satisfies RouterApp
