import type { GameLocation } from "akasha/story/game/location/game-location.page-type.types.ts"

export const theTowerFloor03 = {
  id: "01a0c661-21f0-7e01-b130-2149f9190b2b",
  type: "page-type/game-location",
  slug: "the-tower-floor-03",
  title: "The Gallery of Echoes",
  game: "game/the-tower",
  depth: 3,
  theme:
    "The spiral stair climbs into warmth and dry air at last — and into sound. A long vaulted gallery, walls lined with shattered statuary and tall bronze resonance-plates green with age. Every footstep returns threefold. The light is amber and sourceless, seeming to hum. At the far end, a raised dais and a sealed archway up. Two things wait: a wraith of folded sound drifting between the plates, and a stone Warden seated unmoving before the arch.",
  exits: ["ascending archway, far dais (sealed until the floor is cleared)"],
  note: "FLOOR 3 — the mind floor, and the first that DIRECTLY tests Alan's build identity. Two distinct threat types: the Cantor attacks his MIND (Focus pool, his deep 104 stat — survivable but bleeds if mismanaged), the Golem attacks his BODY (his fatal weakness — VIT 6). The whole floor is engineered so Alan's actual edge (INT 18 reading + FIN placement) is the ONLY efficient solution and his weakness (MIGHT/VIT) is irrelevant-to-fatal if he plays to it. DAMAGE-GATE MODEL (continued from floor 2, see that file's note — REQUIRED reading): both enemies have steep mitigation gates (Cantor x0.4 to direct hits / scales with plates standing; Golem x0.25 to non-keystone, x3 to keystone). Brute force is explicitly a LOSING line on the Golem — by design, to force the read. The wall-note in the dead alcove states both solutions plainly, REWARDING exploration (Alan's PER is weak, so a discoverable written gate is fairer than a spot-check). SEQUENCING IS THE REAL DIFFICULTY: fighting both at once with Focus drained by the Cantor right as the Golem's hammer lands = the kill scenario. A reader separates them — clear the Cantor (kill the plates / use the alcove + whistle) FIRST and safely, recover, THEN wake and keystone the Golem. DIFFICULTY CURVE: this is a genuine step up from floors 1–2 and a real death-risk floor — appropriate as floor 3, and (LOOP NOTE, coordinator-only) a natural candidate for a first death if Alan brute-forces it, after which the retained-progress re-climb teaches the system. Reward path: by floor 3's end Alan has armor (pauldron+gauntlet → physDef ~12.5+), 3–4 affinity seeds (cinder/heat-rivet/sound-shard/keystone), and his first emergent SKILL (Resonance Reading) — the progression axes from DESIGN.md start unlocking exactly as the spec wants. NO water on this floor (decided) — a deliberate resource contrast with the Cistern so players can't reuse the douse trick; the gallery's resource is the BRONZE, not water.",
} as const satisfies GameLocation
