value: ENC[AES256_GCM,data:1RqMjiFbyFC6lrtGDOyC+13fju5RdWOmxYWIpcvRJp8IFxAReSey7w==,iv:DFo8lnuA/kHhvoWFRapsKzkMRSWG8zZv3DHBOdHMKJE=,tag:m4LLNi8jikX0M0ckYaewDg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoY2pyK1o1S0JuNXJha09x
            VXVVVEVnaHlZQXorQWFBMklTb3o0Yjl1emxrCmdsb3FMTy8wSXJEZnJ4NStXTnVJ
            bDJ6WUJiZ2RubWdrYmFHSS9oK0FpSUEKLS0tIFpiaEtSMENhMGZQQmZkRmxicndI
            bXk5RjRhMDMvcVE2RHJQMXJsa2xCTmsK6c3gXPKCy67/a7nmid3cqMtl21ZAlpUF
            flC+kr+cfjnV1zpFVDP7tCTpBHZIerhKp29hRamS5CTwzvdhER+9Nw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
    lastmodified: "2026-09-06T12:05:59Z"
    mac: ENC[AES256_GCM,data:l9GQy0128g/QQpn+cQixP2h9P61Ck1JwtuB8zffw9lh472fNusE6gu+zOojyfY92N3yAIIYvqHQ7QNF3xmp6Gpq69uNPY0PKKR7sLOSWBI4MYAKip74B/u3n4UIej2+dMrKOm+iRbpt5g2kmJs7aAeJVoTtjZ9JpJh6pyb8tvBM=,iv:oLOHkyqy1NkTFW+ubmHsCZiNE54sWIMNWjpHaomRLZc=,tag:sq1OgMwj313yVP7pbcU5sg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
