value: ENC[AES256_GCM,data:KgYvKK+kP/HVOCQpHOLX2TcBHoaCb0bHnjCt7pZDXTd+52KOB9tPkXduptQfqYeK6d+krGAkBsdrcZr9cRQsZw==,iv:fgf6NdRJJKLi/YQcwRL/udGyiMTVUwIr/ybChlNil+o=,tag:cg23fn/oMt4FnPgaiUxKRw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmSDJlN2lmNlQzL2FPTmg4
            Y0lxcGovYUphODV5TVpVOVdaeGZ2bnNVbEhZCnlOMjJIT0xYZm9XMlhYZ2w2dDBs
            Zm5TeHRyWk9sSUFoVUJHTWNSYWh5encKLS0tIFlSdytrRkFwNDFoR0RYUnZyUHd6
            MnBIQ0VuYnd1VHY1cFM1K2hpKzdaUnMKMg3X2dpSVcUXgaSixfRYzrGtwlE16LdV
            l+UlUF8VoWx2shHMdIG0w33uETeXrYGV3WCyDcAecKVFllp+7eIr6A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
    lastmodified: "2026-09-06T13:15:58Z"
    mac: ENC[AES256_GCM,data:C8c97pkvIOvn0e0sHKSpKd2z96IHy9w6TJC6rlb0hDk1gZONBg5q+D9OH3AVO/XKXrMDajTpKmxKAlAOJBllG+qpM8i/JdPvuBtK/pPk45y2lS7mbFaKnqxb+7y8D/tnpuPhjEuixPnpmMZ3spNvWtJJwRxANZ5femjNhKqR8Wk=,iv:OT+lf585puOnTDW/W0a9AXupMDxRcqJNxXEAkxTmknE=,tag:nMyy0De+wBu+h4vCaTK5Rw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
