value: ENC[AES256_GCM,data:ubs7WBowkvR5Y5vFOg/HzuoDyg9y3wjRy5r6svFxnPkEUF3YYqhufZl7Efi5tZjmiaGHJ6Z2t0Dn7pW13nGiFA==,iv:yJKoBKky6EP6tO3z9JFgqOExcXnzoJLhZqzNS3Dg+a0=,tag:Sj6szlwmxZdEFJSJ38rPLQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVVXozdzRlQmExLzFpUFpZ
            UTFpVFFRc3VwUFFXTG1PZUdFd0hHSytGVHpzCnhqYU0yNTZHNExyVUZXTFdJcjRZ
            SzFMbDRybWRSWkxrWWc1WG9iSk9kMFUKLS0tIDBWeEg0N1k5UkU5bGRIMHFmQ3hl
            aHN1OHM1MGp6cGdJQUpNblYxd2FKZzAKQqh4WFKh9morceXk0rc/2oaYds5Y2mJn
            x+0yLxPiGYmKWUo6745J0yWIpUYAi8UvRq9DpAoKwhZcHNKFQUXbFQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
    lastmodified: "2026-09-06T13:16:42Z"
    mac: ENC[AES256_GCM,data:QilNOv9ziR1U3jOmA56R/iLi5O036YZIV1VYmdKOvbUlPKtEgDF4beBimXZbSaMNoXV2DiAeZaFBJweLyknogI2uWqB0vXIwEyhjfMeiV34n7fqYLN95X3nLH3iNaDpl6tKN0M5epd1b2mSWoGxSP0rxAHdQX8u98JpS6hjTpBo=,iv:l52fGBM46wdrb2RATA2WcZxSLyPOypDwS0o9Vh13o/E=,tag:PGwSoRQ12dQx2WO2eg4ueg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
