value: ENC[AES256_GCM,data:Lk9h93G96B/uMX4ZUBO9TOtvhPf5YTaqsZHatUdutv/4oy8Vr1qPFpTbyCw4+KbN8dpLv8Rsiby31cuJwukdhGzqrbpF9yH06GIOC4x2lszjzJwJJm8QDU/tFPlrUhYy9SR0lMrVydAzk9vjjXBliAwM04V0pEZ7sJ+th7rl0c2yY2rjJPaOW1ea56LX0e8QyfLe0WV6OGddFSLw3GX9Gur9fRgsvMIHvhQzyxAe8g==,iv:kn+XUE6k/DxTmF7d4xumIvcYxdMpvC4V7yKyAQqPVHw=,tag:MibcPobirrsoPQrjMk9iiQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlVkE3bzhObW9zL0xiTnBL
            QTI5aW1IbC9rYlZYVHYvRXkyZGRnaWN4aGxJCnBXK05aazhrTXlpWit0V0F1MC9w
            TUFRa2o5VVhBMnlwM3hNODFVWHlZSFEKLS0tIGdxTXpzWmNRQzVZRDZ5by9aQzk0
            dGhmYlZIRlZWb0p3NW1CeGpINUlxa1kK9p1iOdkRJu1X82+HsmyWUKf0xZ6zGs8o
            sO0akJhLrlcTIgJPv7oBghDlt62zOad/oQiX/jBORLeXP42S7Ryl1Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
    lastmodified: "2026-09-06T12:02:04Z"
    mac: ENC[AES256_GCM,data:vySsYljBll2ztDJZFAVr52HW7JlIpndLouZaeTjTDPfhVwzmhCahwv2Fz03pcnwNCARMwymyzroecg0EIC9+BQHyMld58BjZx+J/WOBuZzjOU9QutmGo9CB4/YWzbbiJ8ERAcypVQlfXbP4FWfQ/WOy2fSC9y4gKyOr+hEQWsIk=,iv:UmuYy6G1MeSmhaak9qenFmSaC1HLZQTYn8xTKQ+QGMU=,tag:7HvnN5gPIKMA74hBm6OwiA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
