value: ENC[AES256_GCM,data:I1pwCn52HPE=,iv:pv7cK9KXa+w+FH0QCebCMkYuSBcvTv7rvw7EE8hH6R8=,tag:tOH+5yfTeJoWndIL5l7oKQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzL3h4cGtsWEZlcmoyRElu
            RHlGcE1VUVgwOHZtRFF1UER2bnFTL0c2ZlNBCm1tL2dITGhVVUNOZzB4TDFlYmR1
            OWw0TlZXRlRqNmdlNXlZaloyNUMxdnMKLS0tIHVNWG8vUjRCZk5lS0EzbFQxcUhn
            eXNjUFVzRVBUTFdxT0hpb2tISkxTU0UKrmgJdVY8HwA6Oi4lwxEbyTCbltWy5d35
            QCFmdQ+XNv2phG/NCFqrQbVyI/3IUprXbOXmWll0nQzSkJhbZQajFQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
    lastmodified: "2026-09-06T12:39:44Z"
    mac: ENC[AES256_GCM,data:0o6P3l9PNRe20+Loy9Ht5HMh6nGy3qzPjdtOk8seh6tzqK8/gKtjOrod/GnslhV7vL+QsqfHyJeheR9j4a9YUYK3jElD8L8+E4UfnOMUaSEta+paxYG2IjBSJixc1q73IBbt1Hl45+yZk/HLyVR/4hbpEGGlGGYZo9eIWjtV+Fc=,iv:5iIWMTfl1IZrIOSLttfvklng603XburxCfPvKGZY1WA=,tag:iNzYO1+wiL3qqkH1SBgaZg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
