value: ENC[AES256_GCM,data:nFC8qOvnoH0eavAg+v7HDnFzBPo=,iv:WNf8f0pgDsel8Sda3WhywkC0T+6A+UVB71c8ClNcd0E=,tag:6Hj9LxNVPMD1IKxJViQw+Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4T0ZPbFAzbE8rMFBrcDhw
            NmdKMnlpSm9TcGNwVDYxVXFJYWdyNkZQRkJzCjR4UDVtRlJGQm5qa01QdHNkZ0Zk
            WEd5S3BkRklVQ0xIKysrL3h5dW14Y3cKLS0tIDVEWHpRUDNLdDVtRnNQNjZaQU03
            ekIrd25DNkd6WVJkQkwyQkhab3RMcEkKsZdOlNkE36qUf8ZRNxSp6+u7QnAXgab9
            OT9LbD19C7STpDI/tkk7gsumG7z1v6mE8jaD2cWarNIgxyXwv1MNLg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
    lastmodified: "2026-09-06T12:39:13Z"
    mac: ENC[AES256_GCM,data:EWhH0W8jkPTNoDRi4lDXLgr3cNIowVSwmi2zdk4DvHWWjG0kWgpvt/j66mHWHeSM+ZAneMgWo4J6sVO+E8xDnQW7OIqQKWXxQfaC54nW8Hl8pQ2FOBAIVFHOUTOisWpSOImQscQnM2RvmVEzYDr26CpBpSj4MN++kTw7TPzfH+g=,iv:yHIjZknBWHU/vozJjY2ahUPq8BgOrkfG7mFVLCzRdAo=,tag:NzkCOHUE6OWqHmBgxjSdQw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
