value: ENC[AES256_GCM,data:yZeN+5pj0sPTXzfZTOjxwhis753C4VdbCXcXAPcF6EHWPxTSncA5AaK7PPk6JGLyYBmvjkHKwRaYWiZ8o8+oyvaxbARsP6c8M5NSI92rXZkwLIcxQ4BM72pj+7rpXzyehLvurCStNshyxBkIaxjuuGqHPtxslsQN+SJott+BPb7HJ7Rrmsxtt82sniGM1qJit0pnYVXBGCpXD7WL7OjInNgQe8IUy9I12R1zibh8NofePLKI,iv:2J/0ZyaJ3vDxIPYvAmiUBxJU5O0jOEFdM3UVeXQ8Ng8=,tag:Ym93GifFIMo6q9Gbh0lpfg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFb3VOeGhsOHl6VEZaRHoz
            d1Fvd2ZRYm0wdlBlclZVWHgzMFpLakNWRXhRCktVdzFJRDlUODAvRGlSUUFORVZF
            T0tjZzQ3NmF4bldTejJsYWJHd3A2NGMKLS0tIGZXdzVOWVlPRGcyUGNEOWZzaUFE
            RVRPVy9XbTVXVzRoZ09sR3VSSzQ0ZncKAsdE8/Hs3OtVzGPf83Lc607pluhSyrHR
            9cd6PBfWIaajSwPw3U4wUmyL5W0r9Bs1BbpQ7uogrMyuhGEhnPyC8g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
    lastmodified: "2026-09-06T12:39:25Z"
    mac: ENC[AES256_GCM,data:lUT/0OpRJ3tbzyVxc0Cw+L/G6vQu6J0nDb/T572mUczzl4wtutw3ZBrQ4qAA+tHNAvk5wJqzhKO42tdEXNxjRXnuHBv9Y9DEh1672Vp5amYyNvTiVI6l28z3qAbL62MDIl60Tbh+nQ6sENvQhaVmrjxjF3uhMNgWVbpsPtIqTaI=,iv:eZ2CgjsPqKMghgVwbxaxm3qOdxPHYCjq3yPWfI7klGE=,tag:GqkE9r5sc8BT/Eo/cmRExg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
