value: ENC[AES256_GCM,data:FFbxmSE8kQcYiU8DYpHKEeqgWOicFB65vKgkefoKhukx+fgDSRawqDoXaA==,iv:ud5t5umQyGmwSmPEmL7baK0gBJEUqxwnyo1VVePMVEY=,tag:lt1dSUpVX42nZ+T5Kd7V0A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2TW8zK3Q0UWs4YjA0SCtF
            aXJRSVRrV0JlZVpKRVNQRkJxREJGNVVMSVNRCnNJYlhXVXZPWkErTjQyNjkzOXBu
            eWNqTEluSmx3N0FkVG5IWWNTRngzYncKLS0tIFNlZSt5cjlKVnhGRk5iTHN0SUhG
            am4wTHZqMm1Wc0laVWp5eHBmN3ZMTFEKe7LczwaPyR58Z+lz5QeHc+UmhkJt1K2X
            VHaDZ5LRzNsp+2bLbEh4Wz/3Kfdw3Dvixmf4NqV0uDIVVIM806sbGA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
    lastmodified: "2026-09-06T12:03:56Z"
    mac: ENC[AES256_GCM,data:qgNQyT2N2KVFalajhdYX0P+ieyGz564JJOcLavGFHol3gEVdcu3OW0sMvRmNd8H8PH6QYoRi6EPCYAo1RUKlwPid3Li4f6ldlKXzDhapS2hKOB+kIHZqs5GoKZE50htIzMjyc4b1Cc1Yf4pAoDSGmjn3QNsqobeXLLmiVke0xfk=,iv:lBgL+5KTEN9d/o9OxF6R5MN6Gk9QeftjcoDC3LZUroU=,tag:hAyN9jw6opkZdzUjjxBlzQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
