value: ENC[AES256_GCM,data:wtL3YvPuE0E5HmSLOqNqK+1LBi8Q50YcVGVTLCSEkqOYF8AvX5a5hf8tO73jg8iIdgVmNnTkosHdB8ZCjsqTKF2vyYpTS0jUkOSEcNnBu4CXH1ch/k1ZaQ==,iv:/kFSWYxtw38m+qn/vLDzSmvgz9oqOMqC8dxORRonc5s=,tag:/UkhrjaZZP1Ic/Neraqgjw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUUWM1RGlPc1orY3k4STZn
            aUZVRXBmRi9pMjcyUWd5ekNJUzltSS9SMWxrCmM0MStzZUVzbjgyMjZLNnJzL0oy
            TytxR2VVM0lpdW5EQ2JCU2NlTEhPOTQKLS0tIHBnZEx5djh1TWZDQTRUaE5tTXI5
            TjJFdjRBYXo2dS9kTG9RTk5qMUJaM1kK5THrDjpI/Gla6qGUwjHFWMLhMjVZ/ee+
            Sp5NUfZbjQDBF+8phBJYiFopOPgI5MeWzuUrUrYiNN75EbrpoxkOfQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
    lastmodified: "2026-08-28T15:00:51Z"
    mac: ENC[AES256_GCM,data:4cE7vzCnap5k7CvQHtGQLr8yfjF+B/Z/l1+T/EPQbgLyDOdZoETNXQp+At1FZRm0Pa108nj1X4a4vqf8fYD9gCeoEvcZPZDJ4c+L99LqzPMbbMVVDRPNoT37lmxz3dcsA2HXqQAOo3jKXsMdr7JgkaY5Xd7SVWqFZmCvzOPC5uA=,iv:564q8dx3qnE3AMtYFjTcV5a5YXmCmxMTL86b31u1A/Q=,tag:aAvopqwRfveQssIf56EFww==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
