import type { TemperSet } from "akasha/temper/catalog/gear/temper-set/temper-set.page-type.types.ts"

export const wayOfAir = {
  id: "019e66e7-6aad-78bb-9970-dd7bb86bab14",
  type: "page-type/temper-set",
  slug: "way-of-air",
  title: "Way of Air",
  key: "way-of-air",
  esoSetId: 146,
  setWayshrines: [220, 220, 220],
  setTypeId: 9,
  setProcsAllowedInPvp: true,
  setNameZh: "气之道",
  setNameRu: "Путь воздуха",
  setNameFr: "La Voie de l'air",
  setNameEs: "Senda del aire",
  setNameDe: "Weg der Luft",
  setDropZones: [888, 888, 888, 888],
  setDropMechanics: [7, 8, 10, 25],
  setDlcId: 0,
  itemBrowserSources: ["888"],
  itemBrowserPlaceKinds: [1],
  itemBrowserItemId: 95698,
  esoItemIds: [
    95643, 95644, 95645, 95646, 95647, 95648, 95649, 95650, 95651, 95652, 95653, 95654, 95655,
    95656, 95657, 95658, 95659, 95660, 95661, 95662, 95663, 95664,
  ],
  esoArmorTypes: ["ARMORTYPE_MEDIUM"],
  esoEquipTypes: [
    "EQUIP_TYPE_CHEST",
    "EQUIP_TYPE_FEET",
    "EQUIP_TYPE_HAND",
    "EQUIP_TYPE_HEAD",
    "EQUIP_TYPE_LEGS",
    "EQUIP_TYPE_NECK",
    "EQUIP_TYPE_OFF_HAND",
    "EQUIP_TYPE_ONE_HAND",
    "EQUIP_TYPE_RING",
    "EQUIP_TYPE_SHOULDERS",
    "EQUIP_TYPE_TWO_HAND",
    "EQUIP_TYPE_WAIST",
  ],
  esoWeaponTypes: [
    "WEAPONTYPE_AXE",
    "WEAPONTYPE_BOW",
    "WEAPONTYPE_DAGGER",
    "WEAPONTYPE_FIRE_STAFF",
    "WEAPONTYPE_FROST_STAFF",
    "WEAPONTYPE_HAMMER",
    "WEAPONTYPE_HEALING_STAFF",
    "WEAPONTYPE_LIGHTNING_STAFF",
    "WEAPONTYPE_SHIELD",
    "WEAPONTYPE_SWORD",
    "WEAPONTYPE_TWO_HANDED_AXE",
    "WEAPONTYPE_TWO_HANDED_HAMMER",
    "WEAPONTYPE_TWO_HANDED_SWORD",
  ],
  category: "temper-set-category/overland",
  valid: ["*:medium"],
  bonuses: "jsonl",
  icons: "jsonl",
} as const satisfies TemperSet
