apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-config
    namespace: prometheus
    labels:
        app.kubernetes.io/name: prometheus
        app.kubernetes.io/instance: prometheus
        app.kubernetes.io/component: alertmanager
        app.kubernetes.io/part-of: monitoring
        app.kubernetes.io/managed-by: bootstrap
type: Opaque
stringData:
    alertmanager.yml: ENC[AES256_GCM,data:/BzligR4f9ZozwZ3rAKi10dS3qvzNFN38OLvAuBBBTQDV8mvWnkQ7mryJNB4bxFKjsDit1anOAgIOMPWvmwdMkmRHiKwcmL3yzGg67kafUzw46gba045yNEijcnB1JoBofLmJZbpBzYcLJpAOrcCgXqFhucr2AA8qE2eBXoXYQerXZUchfT0H2Pn/0IbCPbax8jOSpvZleFc5jUn8aCRTNpAkpPiRrEiQ7Htvjm42Zh5vdznhs8NbMhd6D1gc4bJenw1UxGs+MEXtdcca8I8ATRe8cFq2JzavE1zK9BYh429EL788D5m//+nNXnmdGfkSY1nNNkHnghgIABC8U+rJjqSB1tK5yUtS7t4HG+qJK3tCAu8fuHiHzTRSx4j3bFo3ZJB9ETEGau685ow/TW9gX9KsXA8HIpaffmmSpw=,iv:dBWr07ha9cn+1PWrRdvnxTc7HM+c7p/w/wdpAzigb48=,tag:XZYd9pShgBCBvfkK0A33HA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjdURyREtJcFFQL0dUSGVN
            SFRyMzdJOTJkRzArYWJBZXFLc002RlNlZFZrClVlckZCWjl0WnlxR2paUTlnVGQv
            SVd5RFh0bjdlaGtsQzhObWYvNlpldFEKLS0tIC9zU3Rqci85TzgwTk43VGZHK3lL
            Rk1mMnUrK2lHL3V6angyTllJTCt2OXMKnL7TJgINv/ekrxIGTr96yaRhJCBlE2L9
            GTCJ98Lom4fmJ76ToUnvflGqIdkANkPm3RQ5V/LTzj8M02hPc9Z24g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-03T10:34:02Z"
    mac: ENC[AES256_GCM,data:fJger45ACtsOZa1FqDqDOSh+I8DBSfBG7GRgzp8x0WPMx9rCQdgGHDHG6hYQtZePlVb/AisbIY8XWZjsHo1lMDqPe3+pWj829utotdtW5ueHPfjjfBuekaCHg/jnYm7Ff0YcInTXCaDigRuC1FIFaBdd9GkTyDRpgPi2yqKqc0g=,iv:kp6dXcK0qXWiiFbeFsvYySzBXp69ZZfb49Ejkx7ZpY0=,tag:028nJZX3F0x8N5Tw6rGnKw==,type:str]
    version: 3.13.1
