import type { TemperSet } from "akasha/temper/catalog/gear/temper-set/temper-set.page-type.types.ts"

export const gloriousDefender = {
  id: "019e6484-5fb1-7a44-9db5-3fbecdf9b128",
  type: "page-type/temper-set",
  slug: "glorious-defender",
  title: "Glorious Defender",
  key: "glorious-defender",
  esoSetId: 213,
  esoItemIds: [
    68696, 68697, 68698, 68699, 68700, 68701, 68702, 71263, 71272, 131673, 131674, 131675, 131676,
    131677, 131678, 131679, 131680, 131681, 131682, 131683, 131684, 131685,
  ],
  esoArmorTypes: ["ARMORTYPE_HEAVY"],
  esoEquipTypes: [
    "EQUIP_TYPE_CHEST",
    "EQUIP_TYPE_FEET",
    "EQUIP_TYPE_HAND",
    "EQUIP_TYPE_HEAD",
    "EQUIP_TYPE_LEGS",
    "EQUIP_TYPE_NECK",
    "EQUIP_TYPE_OFF_HAND",
    "EQUIP_TYPE_ONE_HAND",
    "EQUIP_TYPE_RING",
    "EQUIP_TYPE_SHOULDERS",
    "EQUIP_TYPE_TWO_HAND",
    "EQUIP_TYPE_WAIST",
  ],
  esoWeaponTypes: [
    "WEAPONTYPE_AXE",
    "WEAPONTYPE_BOW",
    "WEAPONTYPE_DAGGER",
    "WEAPONTYPE_FIRE_STAFF",
    "WEAPONTYPE_FROST_STAFF",
    "WEAPONTYPE_HAMMER",
    "WEAPONTYPE_HEALING_STAFF",
    "WEAPONTYPE_LIGHTNING_STAFF",
    "WEAPONTYPE_SHIELD",
    "WEAPONTYPE_SWORD",
    "WEAPONTYPE_TWO_HANDED_AXE",
    "WEAPONTYPE_TWO_HANDED_HAMMER",
    "WEAPONTYPE_TWO_HANDED_SWORD",
  ],
  setWayshrines: [249, 249, 249],
  setTypeId: 1,
  setNameZh: "光荣防御者",
  setNameRu: "Прославленный защитник",
  setNameFr: "Défense glorieuse",
  setNameEs: "Protector glorioso",
  setNameDe: "Ruhmreicher Verteidiger",
  setDropZones: [677, 684, 684],
  setDropMechanics: [5, 5],
  setDlcId: 2,
  itemBrowserSources: ["677"],
  itemBrowserPlaceKinds: [5],
  itemBrowserItemId: 68740,
  category: "temper-set-category/arena",
  valid: ["*:heavy"],
  bonuses: "jsonl",
  icons: "jsonl",
} as const satisfies TemperSet
