import type { TemperLoreBook } from "akasha/temper/catalog/pursuit/temper-lore-collection/temper-lore-book/temper-lore-book.page-type.types.ts"

export const apocryphaApocrypha = {
  id: "01a0d5f2-253a-71f5-b724-ab2a0c3a1021",
  type: "page-type/temper-lore-book",
  slug: "apocrypha-apocrypha",
  title: "Apocrypha, Apocrypha",
  collection: "temper-lore-collection/daedric-cults",
  esoBookId: 68,
  bookIndex: 1,
  charted: true,
  onBookshelves: true,
  mapCounts: [
    { mapId: 7, mapCount: 6 },
    { mapId: 10, mapCount: 17 },
    { mapId: 13, mapCount: 5 },
    { mapId: 16, mapCount: 4 },
    { mapId: 26, mapCount: 7 },
    { mapId: 27, mapCount: 6 },
    { mapId: 61, mapCount: 6 },
    { mapId: 143, mapCount: 6 },
    { mapId: 255, mapCount: 24 },
    { mapId: 256, mapCount: 2 },
    { mapId: 439, mapCount: 3 },
    { mapId: 660, mapCount: 7 },
    { mapId: 667, mapCount: 1 },
    { mapId: 994, mapCount: 5 },
    { mapId: 1006, mapCount: 20 },
    { mapId: 1060, mapCount: 30 },
    { mapId: 1126, mapCount: 10 },
    { mapId: 1313, mapCount: 1 },
    { mapId: 1349, mapCount: 35 },
    { mapId: 1429, mapCount: 9 },
    { mapId: 1887, mapCount: 1 },
  ],
} as const satisfies TemperLoreBook
