import type { Domain } from "akasha/domain/domain.page-type.types.ts"

export const temperAddonType = {
  id: "01a06090-f5ac-7f47-be1b-dc303670f2ad",
  type: "page-type/domain",
  slug: "temper-addon-type",
  definition: "the types a compiler reads for what an add-on leaves in the game's globals",
  parts: [
    "type-declaration/arkadius-trade-tools",
    "type-declaration/bui",
    "type-declaration/crafting-addon-neighbours",
    "type-declaration/custom-compass-pins",
    "type-declaration/fcois",
    "type-declaration/furniture-catalogue",
    "type-declaration/interface-addon-neighbours",
    "type-declaration/lib-addon-menu",
    "type-declaration/temper-async-global",
    "type-declaration/temper-chat-message-global",
    "type-declaration/lib-codes-common-code",
    "type-declaration/lib-custom-menu",
    "type-declaration/lib-debug-logger",
    "type-declaration/lib-gps",
    "type-declaration/lib-group-broadcast",
    "type-declaration/lib-lua-52",
    "type-declaration/lib-main-menu",
    "type-declaration/lib-main-menu-shape",
    "type-declaration/lib-map-ping",
    "type-declaration/lib-map-pins",
    "type-declaration/lib-multi-account-sets",
    "type-declaration/temper-notification-global",
    "type-declaration/lib-qr-code",
    "type-declaration/lib-radial-menu",
    "type-declaration/lib-scrollable-menu",
    "type-declaration/sets-api",
    "type-declaration/lib-undaunted-pledges",
    "type-declaration/master-merchant",
    "type-declaration/temper-addons-global",
    "type-declaration/temper-catalog-global",
    "type-declaration/temper-hud-global",
    "type-declaration/temper-items-global",
    "type-declaration/temper-keybinder-global",
    "type-declaration/temper-saved-variables-global",
  ],
} as const satisfies Domain
