import { akashaRoot } from "@akasha/pages/checkout-roots"
import { alanwaltonCalendarSync } from "../built-images/alanwalton-calendar-sync/alanwalton-calendar-sync.built-image.ts"
import { authProxy } from "../built-images/auth-proxy/auth-proxy.built-image.ts"
import { buildkit } from "../built-images/buildkit/buildkit.built-image.ts"
import type { BuiltImage } from "../built-images/built-image.page-type.ts"
import { bunGit } from "../built-images/bun-git/bun-git.built-image.ts"
import { ci } from "../built-images/ci/ci.built-image.ts"
import { gfsPromoter } from "../built-images/gfs-promoter/gfs-promoter.built-image.ts"
import { kubectl } from "../built-images/kubectl/kubectl.built-image.ts"
import type { ServiceConfig } from "../dockerfile-extensions/dockerfile-extensions.module.code.ts"

export const ROOT = akashaRoot()
export const HEADER = "# DO NOT EDIT — generated by infrastructure/container-image/dockerfiles\n"

const IMAGES: readonly BuiltImage[] = [
  authProxy,
  gfsPromoter,
  alanwaltonCalendarSync,
  ci,
  bunGit,
  buildkit,
  kubectl,
]

const IMAGES_FROM_DEPLOY = "../built-images"

function configOf(image: BuiltImage): ServiceConfig {
  if (image.extensions === undefined) return { type: image.kind, dir: image.folder }
  const named = `${image.slug}.built-image.extensions.${image.extensions}`
  return {
    type: image.kind,
    dir: image.folder,
    extensionFile: `${IMAGES_FROM_DEPLOY}/${image.slug}/${named}`,
  }
}

export const SERVICES: Record<string, ServiceConfig> = Object.fromEntries(
  IMAGES.map((image) => [image.slug, configOf(image)])
)
