import { authProxy } from "akasha/infrastructure/container-image/dockerfiles/built-images/auth-proxy/auth-proxy.built-image.ts"
import { buildkit } from "akasha/infrastructure/container-image/dockerfiles/built-images/buildkit/buildkit.built-image.ts"
import type { BuiltImage } from "akasha/infrastructure/container-image/dockerfiles/built-images/built-image.page-type.types.ts"
import { bunGit } from "akasha/infrastructure/container-image/dockerfiles/built-images/bun-git/bun-git.built-image.ts"
import { ci } from "akasha/infrastructure/container-image/dockerfiles/built-images/ci/ci.built-image.ts"
import { gfsPromoter } from "akasha/infrastructure/container-image/dockerfiles/built-images/gfs-promoter/gfs-promoter.built-image.ts"
import { kubectl } from "akasha/infrastructure/container-image/dockerfiles/built-images/kubectl/kubectl.built-image.ts"
import type { ServiceConfig } from "akasha/infrastructure/container-image/dockerfiles/dockerfile-extensions/dockerfile-extensions.module.code.ts"
import { akashaRoot } from "akasha/pages/modules/checkout-roots/checkout-roots.module.code.ts"

export const ROOT = akashaRoot()
export const HEADER = "# DO NOT EDIT — generated by infrastructure/container-image/dockerfiles\n"

export const IMAGES: readonly BuiltImage[] = [authProxy, gfsPromoter, ci, bunGit, buildkit, kubectl]

const BUILT_IMAGES = "infrastructure/container-image/dockerfiles/built-images"

function configOf(image: BuiltImage): ServiceConfig {
  if (image.extensions === undefined) return { type: image.kind, dir: image.folder }
  const named = `${image.slug}.built-image.extensions.${image.extensions}`
  return {
    type: image.kind,
    dir: image.folder,
    extensionFile: `${BUILT_IMAGES}/${image.slug}/${named}`,
  }
}

export const SERVICES: Record<string, ServiceConfig> = Object.fromEntries(
  IMAGES.map((image) => [image.slug, configOf(image)])
)
