import type { SkillLineTemplate } from "../skill-line-template/skill-line-template.module.code.ts"

export const RACIAL_AND_CRAFT_SKILL_LINES = {
  "racial-high-elf-skills": {
    id: "racial-high-elf-skills" as const,
    name: "High Elf Skills",
    subcategoryId: "racial" as const,
    displayOrder: 46,
    esoSkillLineId: 56,
    maxRank: 50,
  },
  "racial-orc-skills": {
    id: "racial-orc-skills" as const,
    name: "Orc Skills",
    subcategoryId: "racial" as const,
    displayOrder: 47,
    esoSkillLineId: 52,
    maxRank: 50,
  },
  "racial-wood-elf-skills": {
    id: "racial-wood-elf-skills" as const,
    name: "Wood Elf Skills",
    subcategoryId: "racial" as const,
    displayOrder: 48,
    esoSkillLineId: 57,
    maxRank: 50,
  },
  "racial-khajiit-skills": {
    id: "racial-khajiit-skills" as const,
    name: "Khajiit Skills",
    subcategoryId: "racial" as const,
    displayOrder: 49,
    esoSkillLineId: 58,
    maxRank: 50,
  },
  "racial-imperial-skills": {
    id: "racial-imperial-skills" as const,
    name: "Imperial Skills",
    subcategoryId: "racial" as const,
    displayOrder: 50,
    esoSkillLineId: 59,
    maxRank: 50,
  },
  "racial-breton-skills": {
    id: "racial-breton-skills" as const,
    name: "Breton Skills",
    subcategoryId: "racial" as const,
    displayOrder: 51,
    esoSkillLineId: 60,
    maxRank: 50,
  },
  "racial-redguard-skills": {
    id: "racial-redguard-skills" as const,
    name: "Redguard Skills",
    subcategoryId: "racial" as const,
    displayOrder: 52,
    esoSkillLineId: 62,
    maxRank: 50,
  },
  "racial-argonian-skills": {
    id: "racial-argonian-skills" as const,
    name: "Argonian Skills",
    subcategoryId: "racial" as const,
    displayOrder: 53,
    esoSkillLineId: 63,
    maxRank: 50,
  },
  "racial-dark-elf-skills": {
    id: "racial-dark-elf-skills" as const,
    name: "Dark Elf Skills",
    subcategoryId: "racial" as const,
    displayOrder: 54,
    esoSkillLineId: 64,
    maxRank: 50,
  },
  "racial-nord-skills": {
    id: "racial-nord-skills" as const,
    name: "Nord Skills",
    subcategoryId: "racial" as const,
    displayOrder: 55,
    esoSkillLineId: 65,
    maxRank: 50,
  },
  "craft-alchemy": {
    id: "craft-alchemy" as const,
    name: "Alchemy",
    subcategoryId: "craft" as const,
    displayOrder: 56,
    esoSkillLineId: 77,
    maxRank: 50,
  },
  "craft-blacksmithing": {
    id: "craft-blacksmithing" as const,
    name: "Blacksmithing",
    subcategoryId: "craft" as const,
    displayOrder: 57,
    esoSkillLineId: 79,
    maxRank: 50,
  },
  "craft-clothing": {
    id: "craft-clothing" as const,
    name: "Clothing",
    subcategoryId: "craft" as const,
    displayOrder: 58,
    esoSkillLineId: 81,
    maxRank: 50,
  },
  "craft-enchanting": {
    id: "craft-enchanting" as const,
    name: "Enchanting",
    subcategoryId: "craft" as const,
    displayOrder: 59,
    esoSkillLineId: 78,
    maxRank: 50,
  },
  "craft-jewelry-crafting": {
    id: "craft-jewelry-crafting" as const,
    name: "Jewelry Crafting",
    subcategoryId: "craft" as const,
    displayOrder: 60,
    esoSkillLineId: 141,
    maxRank: 50,
  },
  "craft-provisioning": {
    id: "craft-provisioning" as const,
    name: "Provisioning",
    subcategoryId: "craft" as const,
    displayOrder: 61,
    esoSkillLineId: 76,
    maxRank: 50,
  },
  "craft-woodworking": {
    id: "craft-woodworking" as const,
    name: "Woodworking",
    subcategoryId: "craft" as const,
    displayOrder: 62,
    esoSkillLineId: 80,
    maxRank: 50,
  },
} satisfies Record<string, SkillLineTemplate>
