import type { Exercise } from "../../exercise.page-type.ts"

export const muscleUp = {
  id: "019ebc77-ae07-7feb-9b57-bc6e20171495",
  pageTypeSlug: "exercise",
  slug: "muscle-up",
  title: "Muscle Up",
  exerciseCategory: "strength",
  equipment: "other",
  exerciseExternalId: "Muscle_Up",
  exerciseExternalLink: "https://github.com/yuhonas/free-exercise-db/tree/main/exercises/Muscle_Up",
  force: "pull",
  gripDemand: "low",
  imageEndUrl:
    "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Muscle_Up/1.jpg",
  imageStartUrl:
    "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Muscle_Up/0.jpg",
  implementCount: 1,
  isBallistic: false,
  exerciseLastSyncedAt: "2026-07-25",
  laterality: "bilateral",
  exerciseLevel: "intermediate",
  loadFactor: 0,
  mechanic: "compound",
  movementPattern: "v-pull",
  muscleFocus: "pull",
  primaryMuscles: ["lats"],
  scoringMode: "reps",
  secondaryMuscles: [
    "abdominals",
    "biceps",
    "forearms",
    "middle-back",
    "shoulders",
    "traps",
    "triceps",
  ],
  sfrScore: 3,
  skillCost: "moderate",
  exerciseSource: "free-exercise-db",
  trainsLengthenedRange: false,
  instructions: "txt",
} as const satisfies Exercise
