import type { StoryTurnPlayed } from "akasha/story/world/stories/played/turns/story-turn-played.page-type.types.ts"

export const otherwhereX00008 = {
  id: "01a0eaf5-1ab9-7092-a4e9-1303fbe3f93e",
  type: "page-type/story-turn-played",
  slug: "otherwhere-x-00-008",
  cover: "image/image-8820be32a2308ad3",
  coverAfter: "It's a stranger's song, about a stranger far from home. Standing here",
  ownLength: 353,
  unit: "unit/words",
  partOfCollections: ["story-played/otherwhere-x"],
  position: 8,
  prose: "txt",
  characters: [
    "character-player/otherwhere-x-nala",
    "character-other/otherwhere-x-aldous-crane",
    "character-other/otherwhere-x-martha-deane",
  ],
  stepStatus: "step-status/player",
  action:
    'I choose to sing "O Danny Boy", since I don\'t know if they will understand the words, but the emotions can still come through the music. After that I sing "Homeward Bound"',
  beats: "jsonl",
  issues: "txt",
  lore: [
    "lore/otherwhere-x-aldous-crane",
    "lore/otherwhere-x-language",
    "lore/otherwhere-x-martha-deane",
    "lore/otherwhere-x-nala",
    "lore/otherwhere-x-progression",
    "lore/otherwhere-x-resolution",
    "lore/otherwhere-x-standing",
    "lore/otherwhere-x-survival",
    "lore/otherwhere-x-time",
    "place/otherwhere-x-harrow",
    "place/otherwhere-x-harrow-green",
    "place/otherwhere-x-the-sheaf",
  ],
  reviewedBy: ["story-reviewer/style", "story-reviewer/continuity"],
  recordedBy: ["story-recorder/memory", "story-recorder/mechanics", "story-recorder/picture"],
  endsAt: "2026-09-28T19:13:00.000Z",
} as const satisfies StoryTurnPlayed
