import type { StoryTurnPlayed } from "akasha/story/world/stories/played/turns/story-turn-played.page-type.types.ts"

export const otherwhereX00008 = {
  id: "01a0eaf5-1ab9-7092-a4e9-1303fbe3f93e",
  type: "page-type/story-turn-played",
  slug: "otherwhere-x-00-008",
  cover: "image/image-8820be32a2308ad3",
  coverAfter: "It's a stranger's song, about a stranger far from home. Standing here",
  ownLength: 353,
  unit: "unit/words",
  partOfCollections: ["story-played/otherwhere-x"],
  position: 8,
  prose: "txt",
  characters: [
    "character-player/otherwhere-x-nala",
    "world-character/otherwhere-x-aldous-crane",
    "world-character/otherwhere-x-martha-deane",
  ],
  stepStatus: "step-status/player",
  action:
    'I choose to sing "O Danny Boy", since I don\'t know if they will understand the words, but the emotions can still come through the music. After that I sing "Homeward Bound"',
  beats: [
    'Nala stands up at the trestle and sings "O Danny Boy", slow and low, for the room.',
    "The voice that comes out is not the one she left behind; she has to find it as she goes.",
    "The tune is nothing Harrow knows. Ned Fuller the smith sets his cup down to listen.",
    "Every word lands: a farewell, someone gone away, a promise to be there when they come home.",
    "A lad at the far trestle stops chewing. Martha's ladle hangs over the pot.",
    "On the high climb of the chorus her new voice cracks, and she has to drop under the note.",
    "She finds it again for the last lines, and holds the last note and lets it die out.",
    "Nobody claps. They knock the trestles with their knuckles, which is what Harrow does.",
    'She goes straight on into "Homeward Bound", a plainer song, faster, about going home.',
    "It is a stranger's song about a stranger far from home, sung by a stranger with no home to name.",
    "Hattie Rook leans to the woman beside her and whispers, eyes on Nala's bare feet.",
    "Nala reaches the last verse, about wanting to be home, and her voice scrapes on it.",
    "She finishes with her throat raw and her hands not quite steady, in a body that isn't hers.",
    "Aldous hasn't moved from the door, and his face has gone still the way it went still at her name.",
    "The room is pleased with her and uneasy about her at once, and neither feeling wins.",
    'Martha breaks it. "Well. The lass can sing." She hooks a stool out from under the next trestle.',
    "Coppers go down on the wood: three of them, from Ned and Hattie and a hand at the back.",
    'The question the whole room is holding comes out of the back: "Where\'d you learn songs like that?"',
    'Martha sets a cup in front of her. "Another. Then you\'ll say where a girl gets songs like that."',
  ],
  issues: [
    '"nobody here has pipes, or the word" - Harrow folk understand every word Nala sings',
    '"the room has no such word" - Harrow folk understand every word Nala sings, per the Sheaf',
  ],
  lore: [
    "lore/otherwhere-x-aldous-crane",
    "lore/otherwhere-x-language",
    "lore/otherwhere-x-martha-deane",
    "lore/otherwhere-x-nala",
    "lore/otherwhere-x-progression",
    "lore/otherwhere-x-resolution",
    "lore/otherwhere-x-standing",
    "lore/otherwhere-x-survival",
    "lore/otherwhere-x-time",
    "place/otherwhere-x-harrow",
    "place/otherwhere-x-harrow-green",
    "place/otherwhere-x-the-sheaf",
  ],
  reviewedBy: ["story-reviewer/style", "story-reviewer/continuity"],
  recordedBy: ["story-recorder/memory", "story-recorder/mechanics", "story-recorder/picture"],
  endsAt: "2026-09-28T19:13:00.000Z",
} as const satisfies StoryTurnPlayed
