import type { EsoAddon } from "../../code-system/eso-addon/eso-addon.page-type.ts"

export const temperInterfaceAddon = {
  id: "01a060e7-1bea-7ec8-9343-b0e442437b98",
  pageTypeSlug: "eso-addon",
  slug: "temper-interface-addon",
  definition: "the add-on holding the interface tweaks that no other add-on has a home for",
  manifest: "json",
  addonManifest: "json",
  partSlugs: [
    "module/assistant-collectibles",
    "module/assistant-bindings",
    "module/assistant-entry",
    "module/quiet-alerts",
    "module/quiet-announcements",
    "module/quiet-camera-keybind",
    "module/quiet-camera",
    "module/quiet-craft-bag",
    "module/quiet-defaults",
    "module/quiet-dialogs",
    "module/quiet-entry",
    "module/quiet-guild-applications",
    "module/quiet-guild-invites",
    "module/quiet-guild-motd",
    "module/quiet-guild-roster",
    "module/quiet-identity",
    "module/quiet-list-provider",
    "module/quiet-lua-errors",
    "module/quiet-map-pins",
    "module/quiet-narrow",
    "module/quiet-print",
    "module/quiet-raid-leaderboard",
    "module/quiet-saved-variables",
    "module/quiet-settings-dialogs",
    "module/quiet-settings-guilds",
    "module/quiet-settings-header",
    "module/quiet-settings-menu",
    "module/quiet-settings-messages",
    "module/quiet-settings-world",
    "module/quiet-strings",
    "module/quiet-world",
  ],
  invariants: [
    {
      invariantKind: "departure",
      statement: "Three separate add-ons were folded into this one.",
    },
    {
      invariantKind: "departure",
      statement: "A keybind is named after the assistant the player has unlocked.",
    },
  ],
} as const satisfies EsoAddon
