import type { LoreCollectionEntry } from "../lore-library-types/lore-library-types.module.code.ts"

export const LORE_COLLECTIONS_07: readonly LoreCollectionEntry[] = [
  {
    collectionIndex: 55,
    name: "Dead-Water Style",
    books: [
      { bookIndex: 1, name: "Crafting Motif 69: Dead-Water Axes" },
      { bookIndex: 2, name: "Crafting Motif 69: Dead-Water Belts" },
      { bookIndex: 3, name: "Crafting Motif 69: Dead-Water Boots" },
      { bookIndex: 4, name: "Crafting Motif 69: Dead-Water Bows" },
      { bookIndex: 5, name: "Crafting Motif 69: Dead-Water Chests" },
      { bookIndex: 6, name: "Crafting Motif 69: Dead-Water Daggers" },
      { bookIndex: 7, name: "Crafting Motif 69: Dead-Water Gloves" },
      { bookIndex: 8, name: "Crafting Motif 69: Dead-Water Helmets" },
      { bookIndex: 9, name: "Crafting Motif 69: Dead-Water Leg Greaves" },
      { bookIndex: 10, name: "Crafting Motif 69: Dead-Water Maces" },
      { bookIndex: 11, name: "Crafting Motif 69: Dead-Water Shields" },
      { bookIndex: 12, name: "Crafting Motif 69: Dead-Water Shoulders" },
      { bookIndex: 13, name: "Crafting Motif 69: Dead-Water Staves" },
      { bookIndex: 14, name: "Crafting Motif 69: Dead-Water Swords" },
    ],
  },
  {
    collectionIndex: 56,
    name: "Elder Argonian Style",
    books: [
      { bookIndex: 1, name: "Crafting Motif 70: Elder Argonian Axes" },
      { bookIndex: 2, name: "Crafting Motif 70: Elder Argonian Belts" },
      { bookIndex: 3, name: "Crafting Motif 70: Elder Argonian Boots" },
      { bookIndex: 4, name: "Crafting Motif 70: Elder Argonian Bows" },
      { bookIndex: 5, name: "Crafting Motif 70: Elder Argonian Chests" },
      { bookIndex: 6, name: "Crafting Motif 70: Elder Argonian Daggers" },
      { bookIndex: 7, name: "Crafting Motif 70: Elder Argonian Gloves" },
      { bookIndex: 8, name: "Crafting Motif 70: Elder Argonian Helmets" },
      { bookIndex: 9, name: "Crafting Motif 70: Elder Argonian Legs" },
      { bookIndex: 10, name: "Crafting Motif 70: Elder Argonian Maces" },
      { bookIndex: 11, name: "Crafting Motif 70: Elder Argonian Shields" },
      { bookIndex: 12, name: "Crafting Motif 70: Elder Argonian Shoulders" },
      { bookIndex: 13, name: "Crafting Motif 70: Elder Argonian Staves" },
      { bookIndex: 14, name: "Crafting Motif 70: Elder Argonian Swords" },
    ],
  },
  {
    collectionIndex: 57,
    name: "Coldsnap Style",
    books: [
      { bookIndex: 1, name: "Crafting Motif 71: Coldsnap Axes" },
      { bookIndex: 2, name: "Crafting Motif 71: Coldsnap Belts" },
      { bookIndex: 3, name: "Crafting Motif 71: Coldsnap Boots" },
      { bookIndex: 4, name: "Crafting Motif 71: Coldsnap Bows" },
      { bookIndex: 5, name: "Crafting Motif 71: Coldsnap Chests" },
      { bookIndex: 6, name: "Crafting Motif 71: Coldsnap Daggers" },
      { bookIndex: 7, name: "Crafting Motif 71: Coldsnap Gloves" },
      { bookIndex: 8, name: "Crafting Motif 71: Coldsnap Helmets" },
      { bookIndex: 9, name: "Crafting Motif 71: Coldsnap Legs" },
      { bookIndex: 10, name: "Crafting Motif 71: Coldsnap Maces" },
      { bookIndex: 11, name: "Crafting Motif 71: Coldsnap Shields" },
      { bookIndex: 12, name: "Crafting Motif 71: Coldsnap Shoulders" },
      { bookIndex: 13, name: "Crafting Motif 71: Coldsnap Staves" },
      { bookIndex: 14, name: "Crafting Motif 71: Coldsnap Swords" },
    ],
  },
  {
    collectionIndex: 58,
    name: "Meridian Style",
    books: [
      { bookIndex: 1, name: "Crafting Motif 72: Meridian Axes" },
      { bookIndex: 2, name: "Crafting Motif 72: Meridian Belts" },
      { bookIndex: 3, name: "Crafting Motif 72: Meridian Boots" },
      { bookIndex: 4, name: "Crafting Motif 72: Meridian Bows" },
      { bookIndex: 5, name: "Crafting Motif 72: Meridian Chests" },
      { bookIndex: 6, name: "Crafting Motif 72: Meridian Daggers" },
      { bookIndex: 7, name: "Crafting Motif 72: Meridian Gloves" },
      { bookIndex: 8, name: "Crafting Motif 72: Meridian Helmets" },
      { bookIndex: 9, name: "Crafting Motif 72: Meridian Legs" },
      { bookIndex: 10, name: "Crafting Motif 72: Meridian Maces" },
      { bookIndex: 11, name: "Crafting Motif 72: Meridian Shields" },
      { bookIndex: 12, name: "Crafting Motif 72: Meridian Shoulders" },
      { bookIndex: 13, name: "Crafting Motif 72: Meridian Staves" },
      { bookIndex: 14, name: "Crafting Motif 72: Meridian Swords" },
    ],
  },
  {
    collectionIndex: 59,
    name: "Anequina Style",
    books: [
      { bookIndex: 1, name: "Crafting Motif 73: Anequina Axes" },
      { bookIndex: 2, name: "Crafting Motif 73: Anequina Belts" },
      { bookIndex: 3, name: "Crafting Motif 73: Anequina Boots" },
      { bookIndex: 4, name: "Crafting Motif 73: Anequina Bows" },
      { bookIndex: 5, name: "Crafting Motif 73: Anequina Chests" },
      { bookIndex: 6, name: "Crafting Motif 73: Anequina Daggers" },
      { bookIndex: 7, name: "Crafting Motif 73: Anequina Gloves" },
      { bookIndex: 8, name: "Crafting Motif 73: Anequina Helmets" },
      { bookIndex: 9, name: "Crafting Motif 73: Anequina Legs" },
      { bookIndex: 10, name: "Crafting Motif 73: Anequina Maces" },
      { bookIndex: 11, name: "Crafting Motif 73: Anequina Shields" },
      { bookIndex: 12, name: "Crafting Motif 73: Anequina Shoulders" },
      { bookIndex: 13, name: "Crafting Motif 73: Anequina Staves" },
      { bookIndex: 14, name: "Crafting Motif 73: Anequina Swords" },
    ],
  },
  {
    collectionIndex: 60,
    name: "Pellitine Style",
    books: [
      { bookIndex: 1, name: "Crafting Motif 74: Pellitine Axes" },
      { bookIndex: 2, name: "Crafting Motif 74: Pellitine Belts" },
      { bookIndex: 3, name: "Crafting Motif 74: Pellitine Boots" },
      { bookIndex: 4, name: "Crafting Motif 74: Pellitine Bows" },
      { bookIndex: 5, name: "Crafting Motif 74: Pellitine Chests" },
      { bookIndex: 6, name: "Crafting Motif 74: Pellitine Daggers" },
      { bookIndex: 7, name: "Crafting Motif 74: Pellitine Gloves" },
      { bookIndex: 8, name: "Crafting Motif 74: Pellitine Helmets" },
      { bookIndex: 9, name: "Crafting Motif 74: Pellitine Legs" },
      { bookIndex: 10, name: "Crafting Motif 74: Pellitine Maces" },
      { bookIndex: 11, name: "Crafting Motif 74: Pellitine Shields" },
      { bookIndex: 12, name: "Crafting Motif 74: Pellitine Shoulders" },
      { bookIndex: 13, name: "Crafting Motif 74: Pellitine Staves" },
      { bookIndex: 14, name: "Crafting Motif 74: Pellitine Swords" },
    ],
  },
  {
    collectionIndex: 61,
    name: "Sunspire Style",
    books: [
      { bookIndex: 1, name: "Crafting Motif 75: Sunspire Axes" },
      { bookIndex: 2, name: "Crafting Motif 75: Sunspire Belts" },
      { bookIndex: 3, name: "Crafting Motif 75: Sunspire Boots" },
      { bookIndex: 4, name: "Crafting Motif 75: Sunspire Bows" },
      { bookIndex: 5, name: "Crafting Motif 75: Sunspire Chests" },
      { bookIndex: 6, name: "Crafting Motif 75: Sunspire Daggers" },
      { bookIndex: 7, name: "Crafting Motif 75: Sunspire Gloves" },
      { bookIndex: 8, name: "Crafting Motif 75: Sunspire Helmets" },
      { bookIndex: 9, name: "Crafting Motif 75: Sunspire Legs" },
      { bookIndex: 10, name: "Crafting Motif 75: Sunspire Maces" },
      { bookIndex: 11, name: "Crafting Motif 75: Sunspire Shields" },
      { bookIndex: 12, name: "Crafting Motif 75: Sunspire Shoulders" },
      { bookIndex: 13, name: "Crafting Motif 75: Sunspire Staves" },
      { bookIndex: 14, name: "Crafting Motif 75: Sunspire Swords" },
    ],
  },
  {
    collectionIndex: 62,
    name: "Dragonguard Style",
    books: [
      { bookIndex: 1, name: "Crafting Motif 76: Dragonguard Axes" },
      { bookIndex: 2, name: "Crafting Motif 76: Dragonguard Belts" },
      { bookIndex: 3, name: "Crafting Motif 76: Dragonguard Boots" },
      { bookIndex: 4, name: "Crafting Motif 76: Dragonguard Bows" },
      { bookIndex: 5, name: "Crafting Motif 76: Dragonguard Chests" },
      { bookIndex: 6, name: "Crafting Motif 76: Dragonguard Daggers" },
      { bookIndex: 7, name: "Crafting Motif 76: Dragonguard Gloves" },
      { bookIndex: 8, name: "Crafting Motif 76: Dragonguard Helmets" },
      { bookIndex: 9, name: "Crafting Motif 76: Dragonguard Legs" },
      { bookIndex: 10, name: "Crafting Motif 76: Dragonguard Maces" },
      { bookIndex: 11, name: "Crafting Motif 76: Dragonguard Shields" },
      { bookIndex: 12, name: "Crafting Motif 76: Dragonguard Shoulders" },
      { bookIndex: 13, name: "Crafting Motif 76: Dragonguard Staves" },
      { bookIndex: 14, name: "Crafting Motif 76: Dragonguard Swords" },
    ],
  },
  {
    collectionIndex: 63,
    name: "Stags of Z'en Style",
    books: [
      { bookIndex: 1, name: "Crafting Motif 77: Stags of Z'en Axes" },
      { bookIndex: 2, name: "Crafting Motif 77: Stags of Z'en Belts" },
      { bookIndex: 3, name: "Crafting Motif 77: Stags of Z'en Boots" },
      { bookIndex: 4, name: "Crafting Motif 77: Stags of Z'en Bows" },
      { bookIndex: 5, name: "Crafting Motif 77: Stags of Z'en Chests" },
      { bookIndex: 6, name: "Crafting Motif 77: Stags of Z'en Daggers" },
      { bookIndex: 7, name: "Crafting Motif 77: Stags of Z'en Gloves" },
      { bookIndex: 8, name: "Crafting Motif 77: Stags of Z'en Helmets" },
      { bookIndex: 9, name: "Crafting Motif 77: Stags of Z'en Legs" },
      { bookIndex: 10, name: "Crafting Motif 77: Stags of Z'en Maces" },
      { bookIndex: 11, name: "Crafting Motif 77: Stags of Z'en Shields" },
      { bookIndex: 12, name: "Crafting Motif 77: Stags of Z'en Shoulders" },
      { bookIndex: 13, name: "Crafting Motif 77: Stags of Z'en Staves" },
      { bookIndex: 14, name: "Crafting Motif 77: Stags of Z'en Swords" },
    ],
  },
  {
    collectionIndex: 64,
    name: "Moongrave Fane Style",
    books: [
      { bookIndex: 1, name: "Crafting Motif 78: Moongrave Axes" },
      { bookIndex: 2, name: "Crafting Motif 78: Moongrave Belts" },
      { bookIndex: 3, name: "Crafting Motif 78: Moongrave Boots" },
      { bookIndex: 4, name: "Crafting Motif 78: Moongrave Bows" },
      { bookIndex: 5, name: "Crafting Motif 78: Moongrave Chests" },
      { bookIndex: 6, name: "Crafting Motif 78: Moongrave Daggers" },
      { bookIndex: 7, name: "Crafting Motif 78: Moongrave Gloves" },
      { bookIndex: 8, name: "Crafting Motif 78: Moongrave Helmets" },
      { bookIndex: 9, name: "Crafting Motif 78: Moongrave Legs" },
      { bookIndex: 10, name: "Crafting Motif 78: Moongrave Maces" },
      { bookIndex: 11, name: "Crafting Motif 78: Moongrave Shields" },
      { bookIndex: 12, name: "Crafting Motif 78: Moongrave Shoulders" },
      { bookIndex: 13, name: "Crafting Motif 78: Moongrave Staves" },
      { bookIndex: 14, name: "Crafting Motif 78: Moongrave Swords" },
    ],
  },
  {
    collectionIndex: 65,
    name: "New Moon Priest Style",
    books: [
      { bookIndex: 1, name: "Crafting Motif 81: New Moon Priest Axes" },
      { bookIndex: 2, name: "Crafting Motif 81: New Moon Priest Belts" },
      { bookIndex: 3, name: "Crafting Motif 81: New Moon Priest Boots" },
      { bookIndex: 4, name: "Crafting Motif 81: New Moon Priest Bows" },
      { bookIndex: 5, name: "Crafting Motif 81: New Moon Priest Chests" },
      { bookIndex: 6, name: "Crafting Motif 81: New Moon Priest Daggers" },
      { bookIndex: 7, name: "Crafting Motif 81: New Moon Priest Gloves" },
      { bookIndex: 8, name: "Crafting Motif 81: New Moon Priest Helmets" },
      { bookIndex: 9, name: "Crafting Motif 81: New Moon Priest Legs" },
      { bookIndex: 10, name: "Crafting Motif 81: New Moon Priest Maces" },
      { bookIndex: 11, name: "Crafting Motif 81: New Moon Priest Shields" },
      { bookIndex: 12, name: "Crafting Motif 81: New Moon Priest Shoulders" },
      { bookIndex: 13, name: "Crafting Motif 81: New Moon Priest Staves" },
      { bookIndex: 14, name: "Crafting Motif 81: New Moon Priest Swords" },
    ],
  },
  {
    collectionIndex: 66,
    name: "Shield of Senchal Style",
    books: [
      { bookIndex: 1, name: "Crafting Motif 80: Shield of Senchal Axes" },
      { bookIndex: 2, name: "Crafting Motif 80: Shield of Senchal Belts" },
      { bookIndex: 3, name: "Crafting Motif 80: Shield of Senchal Boots" },
      { bookIndex: 4, name: "Crafting Motif 80: Shield of Senchal Bows" },
      { bookIndex: 5, name: "Crafting Motif 80: Shield of Senchal Chests" },
      { bookIndex: 6, name: "Crafting Motif 80: Shield of Senchal Daggers" },
      { bookIndex: 7, name: "Crafting Motif 80: Shield of Senchal Gloves" },
      { bookIndex: 8, name: "Crafting Motif 80: Shield of Senchal Helmets" },
      { bookIndex: 9, name: "Crafting Motif 80: Shield of Senchal Legs" },
      { bookIndex: 10, name: "Crafting Motif 80: Shield of Senchal Maces" },
      { bookIndex: 11, name: "Crafting Motif 80: Shield of Senchal Shields" },
      { bookIndex: 12, name: "Crafting Motif 80: Shield of Senchal Shoulders" },
      { bookIndex: 13, name: "Crafting Motif 80: Shield of Senchal Staves" },
      { bookIndex: 14, name: "Crafting Motif 80: Shield of Senchal Swords" },
    ],
  },
]
