import type { StoryTurnPlayed } from "akasha/story/world/stories/played/turns/story-turn-played.page-type.types.ts"

export const theDatingGame00002 = {
  id: "01a0de91-c157-7f6c-afd3-7ec7f69e7a94",
  type: "page-type/story-turn-played",
  slug: "the-dating-game-00-002",
  cover: "image/image-7fec5bc2c573fb74",
  coverAfter: "She looks mid-twenties. Her dark brown hair is knotted by the wind,",
  ownLength: 473,
  partOfCollections: ["story-played/the-dating-game"],
  position: 2,
  prose: "txt",
  characters: ["character-player/the-dating-game-alan", "character-other/the-dating-game-echo"],
  unit: "unit/words",
  stepStatus: "step-status/player",
  action:
    "I eat a quiet breakfast, looking out over the valley, then get dressed in my favorite comfortable clothing: black shorts over black compression tights, light blue dusty Ecco slip-ons, and a loose grey athletic shirt, then go out my door, and start hiking up to Rock Canyon",
  beats: [
    "Alan eats the eggs and toast at his table by the back window, cocoa in his one mug.",
    "The window looks west over the valley to Utah Lake, and he takes his time over breakfast.",
    "He dresses: black shorts over black compression tights, a loose grey athletic shirt.",
    "He puts on his dusty light blue Ecco slip-ons, his favorite comfortable clothes.",
    "He goes out his door on Apple Avenue and starts walking up toward Rock Canyon.",
    "Lawns give way to scrub oak, then the park's grass bowl at the canyon mouth, then gravel trail.",
    "Within minutes the quartzite walls close in on both sides.",
    "The creek runs low under willows; side-draw maples are red and the scrub oak is bronzing.",
    "The shade between the walls is cold, and pale dust lifts off the trail under his slip-ons.",
    'Climbers are roped up on the first walls; one calls "Take!" down to his belayer.',
    "The shout echoes twice off the rock.",
    'Then a third "Take!" comes back, late and close, in a woman\'s voice.',
    "None of the climbers look around.",
    "Around the bend past the first walls, a car-sized boulder sits by the creek.",
    "A woman sits on top of it, knees up, head tilted toward the walls.",
    "She looks mid-twenties: wind-knotted dark brown hair, thick freckles, grey-green eyes.",
    "She wears a rock-grey canvas jacket over something pale.",
    "Black-and-gold headphones rest at her collarbones, their cable running to nothing he can see.",
    "She turns her head and meets his eyes.",
    'She says "Take," quietly, and smiles at him.',
  ],
  lore: [
    "lore/the-dating-game-alan",
    "place/the-dating-game-rock-canyon",
    "lore/the-dating-game-boulder-woman",
  ],
  reviewedBy: ["story-reviewer/continuity"],
  recordedBy: ["story-recorder/memory"],
  endsAt: "2026-09-26T09:25:00.000Z",
} as const satisfies StoryTurnPlayed
