import type { CarMake } from "../../car-make.page-type.ts"

export const landRover = {
  id: "019e4ae6-ba21-77a8-8272-98b4f26665f6",
  pageTypeSlug: "car-make",
  slug: "land-rover",
  title: "Land Rover",
  chargingNetworkAccess:
    "JLR (Jaguar + Land Rover) announced in 2024 that future Jaguar EVs will adopt the Tesla NACS port and gain Supercharger access; the Range Rover Electric (the brand's first BEV) is widely expected to follow the same NACS path though Range Rover has not issued a separate brand-level press release. Current 2025/2026 Land Rover PHEVs (Range Rover P460e/P550e, Range Rover Sport P460e/P550e, Defender P400e) all use the CCS1 (J1772 Combo) port for DC fast charging at peak rates around 43–50 kW, with public access through Electrify America, EVgo, ChargePoint, and Blink networks. No brand-level free-charging program is bundled with the PHEV lineup in the US; charging credits and roadside assistance are negotiated at the dealer level. Sources: https://insideevs.com/news/688021/jaguar-access-tesla-supercharging-network/ , https://www.motorauthority.com/news/1140893_jaguar-to-adopt-tesla-s-nacs-connector-from-2025 , https://www.rangerover.com/en-us/electric/index.html",
  country: "United Kingdom",
  drmPolicy:
    "Land Rover uses InControl + Pivi Pro connected services. Remote App functionality (remote start/precondition, lock/unlock, vehicle status, geofencing, find-my-car) requires an active InControl Remote subscription; subscriptions come complimentary for an initial period and must be renewed via the in-vehicle Services Store. Per Land Rover's own FAQ: 'If you do not renew InControl Remote or InControl Protect then the associated services will be disabled on your vehicle following the expiry of your subscription.' Core driving and powertrain functions do not require connectivity to operate. SOS Emergency Call (Protect) is also a subscription service. Over-the-air updates are delivered through Pivi Pro and (for newer MY24+ vehicles) the SOTA architecture introduced with the new Range Rover/Range Rover Sport. No widely reported instance of JLR remotely disabling already-purchased hardware features (heated seats, performance) post-sale — unlike BMW's ConnectedDrive seat-heating subscription, JLR has not gated previously standard hardware behind a paywall, though some convenience apps and Wi-Fi data plans are subscription-only. Sources: https://www.landroverusa.com/ownership/infotainment-systems/pivi-faqs.html , https://www.landroverusa.com/ownership/infotainment-systems/subscriptions.html , https://incontrol.landrover.com/jlr-portal-owner-web/static/docs/manuals/owner/MyJaguarLandRoverInControlManual_en_BW.pdf",
  electrificationStrategy:
    "JLR's Reimagine strategy (Feb 2021) committed to all Jaguar and Land Rover nameplates having pure-electric variants by 2030 and JLR achieving net-zero across supply chain, products, and operations by 2039. The first BEV from the Range Rover brand (Range Rover Electric) opened reservations in 2024 and was originally planned for 2025 delivery; deliveries have slipped into 2026. Land Rover Defender BEV is confirmed for ~2027 and a Defender Sport BEV is projected for early 2027. Velar and Range Rover Sport BEVs are anticipated 2026/2027 on the new MLA-derived EMA/Modular Longitudinal Architecture. Until BEVs ship, the lineup is electrified via 48V MHEV (Defender P400 inline-6) and 38.2 kWh PHEV (Range Rover P460e/P550e, Range Rover Sport P460e/P550e, Defender 110 P400e in select global markets). Sources: https://media.jaguarlandrover.com/news/2021/02/reimagine-jaguar-land-rover-strategy-real-change , https://www.landroverusa.com/vehicles/phev/index.html , https://topelectricsuv.com/news/land-rover/land-rover-defender-electric/",
  foundingYear: 1948,
  killSwitchPolicy:
    "Data unavailable: Land Rover has made no public statement specific to the IIJA Section 24220 advanced impaired-driving prevention mandate. JLR does include camera-based Driver Condition Monitor (drowsiness/inattention warning) as part of the standard ADAS stack on new Range Rover and Range Rover Sport, which is the foundational hardware NHTSA is expected to leverage in any final rule, but JLR has not announced whether implementation will be hardware-based (passive cabin alcohol/BAC sensing) or software-based (camera + steering input pattern analysis), and has not commented on bypass behavior. NHTSA itself has stated no technology yet meets the accuracy threshold the rule will require; the rulemaking timeline has slipped beyond the original 2024 target with implementation expected ~2027 at the earliest. Sources: https://www.motor1.com/news/794316/new-cars-mandate-impaired-driver-detection-delay/ , https://madd.org/wp-content/uploads/2023/12/Advanced-Impaired-Driving-Prevention-Technology-Fact-Sheet-December-2023-1.pdf",
  nacsAdoption: "announced",
  parentCorporation: "JLR (Jaguar Land Rover), owned by Tata Motors",
  reliabilityNotes:
    "Land Rover consistently ranks at or near the bottom of US reliability surveys. Consumer Reports's 2024 Brand Reliability rankings placed Land Rover 22nd of 22 brands surveyed (lowest), with a predicted reliability score of 14/100; JD Power's 2024 Vehicle Dependability Study (3-year-old vehicles) had Land Rover at 215 problems per 100 vehicles, substantially worse than the industry average of ~190. Range Rover and Range Rover Sport historically suffer high incidence of air-suspension faults, electrical/InControl gremlins, and infotainment glitches; Defender (L663) is newer and has shown more electronic-architecture teething issues than mechanical ones. The new MLA-Flex platform under the L460 Range Rover and L461 Range Rover Sport remains relatively unproven; TrueDelta long-term tracking shows above-average frequency of unscheduled service visits in the first ownership year. Sources: https://www.consumerreports.org/cars/car-reliability-owner-satisfaction/who-makes-the-most-reliable-cars-a7824554938/ , https://www.jdpower.com/cars/ratings/dependability , https://www.truedelta.com/Land-Rover",
  trims: "jsonl",
  shortList: false,
  sources:
    "- https://www.landroverusa.com/ — official US site, lineup and trim configuration\n- https://www.rangerover.com/en-us/ — Range Rover US site\n- https://media.jaguarlandrover.com/news/2021/02/reimagine-jaguar-land-rover-strategy-real-change — JLR Reimagine strategy press release\n- https://insideevs.com/news/688021/jaguar-access-tesla-supercharging-network/ — JLR NACS adoption\n- https://www.consumerreports.org/cars/car-reliability-owner-satisfaction/who-makes-the-most-reliable-cars-a7824554938/ — CR brand reliability ranking\n- https://www.landroverusa.com/ownership/infotainment-systems/pivi-faqs.html — Pivi Pro / InControl FAQ\n- https://www.fueleconomy.gov/ — EPA range and MPG/MPGe ratings\n- https://topelectricsuv.com/news/land-rover/land-rover-defender-electric/ — Defender Electric / Defender Sport timeline",
  exclusionReason: "All models excluded",
} as const satisfies CarMake
