apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: ddns-headscale
    labels:
        app.kubernetes.io/name: ddns-headscale
        app.kubernetes.io/instance: ddns-headscale
        app.kubernetes.io/component: ddns
        app.kubernetes.io/part-of: ddns-headscale
        app.kubernetes.io/managed-by: deploy-script
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:s41RX19KLGQpIBtIaD4gsaigHCyxLNGYpoInMWl9VjqjlC36/znqJIXK8oUpUDbuJOdpMxE=,iv:aGzlRkQ10tp4n6BdFaM5pTJOoJ9L+P8XAekBDJhiO80=,tag:boxFQTdFLJlEEin1N/SIaQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2NENnV285MHZiRlNENDR0
            b3MzUmxiUUZQQzkvWVR0bG5xa3RNZitqTWg4CmE4dmNTcFpNVVRVQnZENGQyK29v
            NTMxTncxZ0hNMWJxZnpVN0JpWlYwQzQKLS0tIElvbDFGMi9tOEhndzVWUnJYMVlQ
            R1Yrb3NLaEt4bXR5NmtkdDhNd24xSk0KBkbuZKgzKiSVoSMB8u/3z8SiPyDPGTVt
            YqChpAhnPz82d/nJ37KT+pjcBpGFQ63R0G1opluKEPw5aRy4E42+zw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-27T22:29:20Z"
    mac: ENC[AES256_GCM,data:7pG7faO1vAjgXTe4aeq0MSbmpgr7kz1jugRd78kFXz/yOQJyw/zezVN4ac+8+j6rZPiUqzECFU/d/HXqDuwLCqFfTw544Bug6k5TyT+XizOBrZTL9XJ+/HUMoPylR5EUnKrswSE1UTS9qInNSLdG2CouguzTvveuw53MDRtK7Ck=,iv:yfiX1Q5NSb9anz2/Js67wnIhi2gPUDA1PqcEvYJqg4I=,tag:2deZsfvFKW44AQ4kZP3JCQ==,type:str]
    version: 3.13.1
