import type { TemperSet } from "akasha/temper/catalog/gear/temper-set/temper-set.page-type.types.ts"

export const defensivePosition = {
  id: "019e66ec-7aca-7af0-8deb-91f46cebf23c",
  type: "page-type/temper-set",
  slug: "defensive-position",
  title: "Defensive Position",
  key: "defensive-position",
  esoSetId: 364,
  esoItemIds: [133396, 133397, 133398, 133399, 133412],
  esoEquipTypes: ["EQUIP_TYPE_OFF_HAND", "EQUIP_TYPE_ONE_HAND"],
  esoWeaponTypes: [
    "WEAPONTYPE_AXE",
    "WEAPONTYPE_DAGGER",
    "WEAPONTYPE_HAMMER",
    "WEAPONTYPE_SHIELD",
    "WEAPONTYPE_SWORD",
  ],
  setWayshrines: [346, 346, 346],
  setTypeId: 11,
  setNameZh: "防御阵地",
  setNameRu: "Оборонительная позиция",
  setNameFr: "Position défensive",
  setNameEs: "Posición defensiva",
  setNameDe: "Defensive Position",
  setDropZones: [1000, 1000, 1000],
  setDropMechanics: [26, 26, 26],
  setDlcId: 8,
  itemBrowserSources: ["1000"],
  itemBrowserPlaceKinds: [4],
  itemBrowserItemId: 133514,
  category: "temper-set-category/trial",
  valid: ["sword", "axe", "mace", "dagger", "shield"],
  bonuses: "jsonl",
  icons: "jsonl",
} as const satisfies TemperSet
