import type { TemperSet } from "akasha/temper/catalog/gear/temper-set/temper-set.page-type.types.ts"

export const elementalSuccession = {
  id: "019e6484-5fa9-7498-a3d1-0deb1cf2af01",
  type: "page-type/temper-set",
  slug: "elemental-succession",
  title: "Elemental Succession",
  key: "elemental-succession",
  esoSetId: 215,
  esoItemIds: [
    68703, 68704, 68705, 68706, 68707, 68709, 68710, 71264, 71273, 131790, 131791, 131792, 131793,
    131794, 131795, 131796, 131797, 131798, 131799, 131800, 131801, 131802,
  ],
  esoArmorTypes: ["ARMORTYPE_LIGHT"],
  esoEquipTypes: [
    "EQUIP_TYPE_CHEST",
    "EQUIP_TYPE_FEET",
    "EQUIP_TYPE_HAND",
    "EQUIP_TYPE_HEAD",
    "EQUIP_TYPE_LEGS",
    "EQUIP_TYPE_NECK",
    "EQUIP_TYPE_OFF_HAND",
    "EQUIP_TYPE_ONE_HAND",
    "EQUIP_TYPE_RING",
    "EQUIP_TYPE_SHOULDERS",
    "EQUIP_TYPE_TWO_HAND",
    "EQUIP_TYPE_WAIST",
  ],
  esoWeaponTypes: [
    "WEAPONTYPE_AXE",
    "WEAPONTYPE_BOW",
    "WEAPONTYPE_DAGGER",
    "WEAPONTYPE_FIRE_STAFF",
    "WEAPONTYPE_FROST_STAFF",
    "WEAPONTYPE_HAMMER",
    "WEAPONTYPE_HEALING_STAFF",
    "WEAPONTYPE_LIGHTNING_STAFF",
    "WEAPONTYPE_SHIELD",
    "WEAPONTYPE_SWORD",
    "WEAPONTYPE_TWO_HANDED_AXE",
    "WEAPONTYPE_TWO_HANDED_HAMMER",
    "WEAPONTYPE_TWO_HANDED_SWORD",
  ],
  setWayshrines: [249, 249, 249],
  setTypeId: 1,
  setNameZh: "元素继承",
  setNameRu: "Преемственность стихий",
  setNameFr: "Succession élémentaire",
  setNameEs: "Sucesión elemental",
  setNameDe: "Elementarfolge",
  setDropZones: [677, 684, 684],
  setDropMechanics: [5, 5],
  setDlcId: 2,
  itemBrowserSources: ["677"],
  itemBrowserPlaceKinds: [5],
  itemBrowserItemId: 68747,
  category: "temper-set-category/arena",
  valid: ["*:light"],
  bonuses: "jsonl",
  icons: "jsonl",
} as const satisfies TemperSet
