apiVersion: v1
kind: Secret
metadata:
    name: agent-adhoc-password
    namespace: postgres
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:adpDJtLEJsacmYU=,iv:47U4o7/ztiDvTHaizcJxDaLkOUscjHz3z7evsyvZWkw=,tag:fBY67kyAZH8W7p4Sj3EzwQ==,type:str]
    password: ENC[AES256_GCM,data:peT/bz8MVDR6kpy876sYSSaFK9vKsGRjgaRbHtFn7qxasyeIKEicQA==,iv:PCmuwmAqjmZvJ0RYxzfNUyTzvIi8UmLotnlk9avhz0A=,tag:NvGdCgYysZ94DGMB3bufpg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4SkQ5MkhYSks2MXliaGNG
            T3ZMbXRCV3hKK1haZU01LzRKaWMxMmtMQnhvCmVJZEl3dDVZL3ppZEpuZDZsTith
            N0dvT2IwMFhKRDN2M252dlNmL3Y5cjAKLS0tIEZRSm1WbHJNbUp1d0szUmgzNGRP
            OFptUC9SYkgxbFZmTXFRcndDZ3B1L0EKCUykr7jjS/jj4x98wjhVrjqyj0Nd8I7P
            SBTVyknjWsd2+jho1uKOkvjKtCQzQMfs/Tkquh13WJVgRW+9m17kEg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-26T04:21:10Z"
    mac: ENC[AES256_GCM,data:nqoEgfpz3pvS5w5q02+npkSQjlcP5ufHVx4Cs2DJMBkuUoHF/QEDo6q3VudIKunJDoZbW+XOtl2o1WwJQXdMyYiTxXcG9tHoTAQG/hN9uf67vXLG2kG9gAUqQjTfG196OfLf3cMlJu1K70fwqJ93NLj02K6UVCA0Sws2iPavhxs=,iv:N8r8/oF1hHOQSAXjxwdBxnbmY1he+ZBIMGzSX2BMVSQ=,tag:CiRC2/+xfOULJ2Kh5yAo+A==,type:str]
    version: 3.13.1
