import type { StoryChapterWritten } from "akasha/story/world/stories/written/chapters/story-chapter-written.page-type.types.ts"

export const fairweather0002SkillsUsedNone = {
  id: "01a1047a-4936-79ff-b6a2-84bbb8667f63",
  type: "page-type/story-chapter-written",
  slug: "fairweather-0002-skills-used-none",
  cover: "image/image-62a2c513db876d22",
  position: 2,
  unit: "unit/words",
  title: "Skills Used, None",
  story: "story-written/fairweather",
  ownLength: 8135,
  prose: "txt",
  stepStatus: "step-status/game-master",
  beats: "jsonl",
  issues: "txt",
  lore: [
    "lore/fairweather-cora",
    "lore/fairweather-elsie",
    "lore/fairweather-tamsin",
    "lore/fairweather-tilly",
    "lore/fairweather-world",
    "place/fairweather-crooked-kettle",
    "place/fairweather-guild-hall",
    "place/fairweather-honeycomb",
    "place/fairweather-lanternmere",
  ],
  characters: [
    "character-player/fairweather-elsie",
    "character-other/fairweather-cora",
    "character-other/fairweather-tamsin",
    "character-other/fairweather-tilly",
  ],
  reviewedBy: ["story-reviewer/scene", "story-reviewer/continuity", "story-reviewer/holdings"],
  recordedBy: [
    "story-recorder/plan",
    "story-recorder/inventory",
    "story-recorder/mechanics",
    "story-recorder/memory",
    "story-recorder/picture",
  ],
  rulings: "jsonl",
  scenes: [
    "image/image-0abfb4e300caad61",
    "image/image-83e68522e504c116",
    "image/image-81d915d9181f6846",
    "image/image-62a2c513db876d22",
    "image/image-fa1871c68858070c",
    "image/image-39186e168859295d",
  ],
} as const satisfies StoryChapterWritten
