import type { SkillTemplate } from "../character-skill-template/character-skill-template.module.code.ts"

export const CHARACTER_SKILLS_07 = {
  "blue-betty-86054": {
    id: "blue-betty-86054" as const,
    esoSkillId: 86054,
    name: "Blue Betty",
    baseName: "Betty Netch",
    skillLineId: "warden-animal-companions" as const,
    skillType: "active" as const,
    description:
      "Call a betty netch to your side, which restores |cffffff4992|r Magicka to you over |cffffff25|r seconds and grants you Major Brutality and Sorcery, increasing your Weapon and Spell Damage by |cffffff20|r%.\n\nEvery |cffffff5|r seconds, the netch removes |cffffff1|r negative effect from you. If no negative effects are removed you instead increase your damage done by |cffffff5|r% for |cffffff5|r seconds.",
    icon: "/esoui/art/icons/ability_warden_017.dds",
    isMorph: true,
    morphIndex: 1,
    lineRankNeeded: 30,
    rank: 30,
    subcategoryId: "warden-animal-companions" as const,
  },
  "blur": {
    id: "blur" as const,
    esoSkillId: 33375,
    name: "Blur",
    baseName: "Blur",
    skillLineId: "nightblade-shadow" as const,
    skillType: "active" as const,
    description:
      "Surround yourself in a phantasmic aura to gain Major Evasion, reducing damage from area attacks by |cffffff20|r% for |cffffff20|r seconds.\n\nWhile active, taking direct damage reduces the cost of your next Roll Dodge by |cffffff10|r%, up to a maximum of |cffffff100|r%. This effect can stack up to once every half second.",
    icon: "/esoui/art/icons/ability_nightblade_009.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 1,
    rank: 1,
    subcategoryId: "nightblade-shadow" as const,
  },
  "bolstering-darkness": {
    id: "bolstering-darkness" as const,
    esoSkillId: 37744,
    name: "Bolstering Darkness",
    baseName: "Consuming Darkness",
    skillLineId: "nightblade-shadow" as const,
    skillType: "ultimate" as const,
    description:
      "Conjure a ring of shadow, reducing the Movement Speed of enemies by 70% and granting you and your allies Major Protection for 10 seconds, reducing your damage taken by 10%.\n\nAllies in the area can activate the Hidden Refresh synergy, granting them invisibility, increasing their Movement Speed by 70%, and healing them for 9110 Health over 4 seconds.",
    icon: "/esoui/art/icons/ability_nightblade_015_a.dds",
    isMorph: true,
    morphIndex: 1,
    lineRankNeeded: 12,
    rank: 8,
    subcategoryId: "nightblade-shadow" as const,
  },
  "bolstering-darkness-36493": {
    id: "bolstering-darkness-36493" as const,
    esoSkillId: 36493,
    name: "Bolstering Darkness",
    baseName: "Consuming Darkness",
    skillLineId: "nightblade-shadow" as const,
    skillType: "ultimate" as const,
    description:
      "Conjure a ring of shadow, reducing the Movement Speed of enemies by |cffffff70|r% and granting you and your allies Major Protection for |cffffff10|r seconds, reducing your damage taken by |cffffff10|r%.\n\nAllies in the area can activate the Hidden Refresh synergy, granting them invisibility, increasing their Movement Speed by |cffffff70|r%, and healing them for |cffffff28640|r Health over |cffffff4|r seconds.",
    icon: "/esoui/art/icons/ability_nightblade_015_a.dds",
    isMorph: true,
    morphIndex: 1,
    lineRankNeeded: 12,
    rank: 12,
    subcategoryId: "nightblade-shadow" as const,
  },
  "bolt-escape": {
    id: "bolt-escape" as const,
    esoSkillId: 23234,
    name: "Bolt Escape",
    baseName: "Bolt Escape",
    skillLineId: "sorcerer-storm-calling" as const,
    skillType: "active" as const,
    description:
      "Transform yourself into pure energy and flash forward, stunning enemies near your final location for |cffffff3|r seconds. \n\nThis effect cannot be blocked.\n\nCasting again within |cffffff4|r seconds costs |cffffff33|r% more Magicka.",
    icon: "/esoui/art/icons/ability_sorcerer_bolt_escape.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 42,
    rank: 42,
    subcategoryId: "sorcerer-storm-calling" as const,
  },
  "bombard": {
    id: "bombard" as const,
    esoSkillId: 40777,
    name: "Bombard",
    baseName: "Arrow Spray",
    skillLineId: "weapon-bow" as const,
    skillType: "active" as const,
    description:
      "Fire a burst of arrows in one shot, dealing 1742 Physical Damage to enemies in front of you. \n\nEnemies hit are immobilized for 4 seconds.",
    icon: "/esoui/art/icons/ability_bow_005_a.dds",
    isMorph: true,
    morphIndex: 1,
    lineRankNeeded: 20,
    rank: 8,
    subcategoryId: "weapon-bow" as const,
  },
  "bombard-38705": {
    id: "bombard-38705" as const,
    esoSkillId: 38705,
    name: "Bombard",
    baseName: "Arrow Spray",
    skillLineId: "weapon-bow" as const,
    skillType: "active" as const,
    description:
      "Fire a burst of arrows in one shot, dealing |cffffff6401|r Physical Damage to enemies in front of you. \n\nEnemies hit are immobilized for |cffffff4|r seconds.",
    icon: "/esoui/art/icons/ability_bow_005_a.dds",
    isMorph: true,
    morphIndex: 1,
    lineRankNeeded: 20,
    rank: 20,
    subcategoryId: "weapon-bow" as const,
  },
  "bond-with-nature": {
    id: "bond-with-nature" as const,
    esoSkillId: 86065,
    name: "Bond with Nature",
    baseName: "Bond with Nature",
    skillLineId: "warden-animal-companions" as const,
    skillType: "passive" as const,
    description: "Anytime one of your Animal Companion skills end, you are healed for 1530 Health.",
    icon: "/esoui/art/icons/passive_warden_010.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 18,
    rank: 2,
    subcategoryId: "warden-animal-companions" as const,
    effects: [] as const,
    status: "unsupported" as const,
  },
  "bond-with-nature-86064": {
    id: "bond-with-nature-86064" as const,
    esoSkillId: 86064,
    name: "Bond with Nature",
    baseName: "Bond with Nature",
    skillLineId: "warden-animal-companions" as const,
    skillType: "passive" as const,
    description:
      "Anytime one of your Animal Companion skills end, you are healed for |cffffff780|r Health.",
    icon: "/esoui/art/icons/passive_warden_010.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 8,
    rank: 8,
    subcategoryId: "warden-animal-companions" as const,
  },
  "bone-armor": {
    id: "bone-armor" as const,
    esoSkillId: 115206,
    name: "Bone Armor",
    baseName: "Bone Armor",
    skillLineId: "necromancer-bone-tyrant" as const,
    skillType: "active" as const,
    description:
      "Wrap yourself in hardened bone, granting you Major Resolve and Minor Resolve for |cffffff20|r seconds, increasing your Physical Resistance and Spell Resistance by |cffffff5948|r and |cffffff2974|r.\n\nIf cast during combat, you can cast a corpse consuming ability on yourself. This effect can occur once every |cffffff10|r seconds.",
    icon: "/esoui/art/icons/ability_necromancer_008.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 4,
    rank: 4,
    subcategoryId: "necromancer-bone-tyrant" as const,
  },
  "bone-goliath-transformation": {
    id: "bone-goliath-transformation" as const,
    esoSkillId: 115001,
    name: "Bone Goliath Transformation",
    baseName: "Bone Goliath Transformation",
    skillLineId: "necromancer-bone-tyrant" as const,
    skillType: "ultimate" as const,
    description:
      "Become a horrific Bone Goliath, increasing your Max Health by |cffffff30000|r for |cffffff20|r seconds and immediately restoring |cffffff30000|r Health. \n\nWhile transformed, your damaging Light Attacks restore |cffffff402|r Health and your fully-charged Heavy Attacks restore |cffffff1005|r Health. This ability scales off your Max Health.",
    icon: "/esoui/art/icons/ability_necromancer_012.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 12,
    rank: 12,
    subcategoryId: "necromancer-bone-tyrant" as const,
  },
  "bone-shield": {
    id: "bone-shield" as const,
    esoSkillId: 39369,
    name: "Bone Shield",
    baseName: "Bone Shield",
    skillLineId: "guild-undaunted" as const,
    skillType: "active" as const,
    description:
      "Surround yourself with a whirlwind of bones, gaining a damage shield that absorbs up to |cffffff7026|r damage for |cffffff6|r seconds. This ability scales off your Max Health.\n\nAn ally near you can activate the Bone Wall synergy, granting the ally and up to |cffffff5|r other allies a damage shield equal to |cffffff35|r% of their Max Health for |cffffff6|r seconds.",
    icon: "/esoui/art/icons/ability_undaunted_005.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 4,
    rank: 4,
    subcategoryId: "guild-undaunted" as const,
  },
  "bone-surge": {
    id: "bone-surge" as const,
    esoSkillId: 43334,
    name: "Bone Surge",
    baseName: "Bone Shield",
    skillLineId: "guild-undaunted" as const,
    skillType: "active" as const,
    description:
      "Surround yourself with a whirlwind of bones, gaining a damage shield that absorbs up to 5121 damage for 6 seconds. This ability scales off your Max Health.\n\nAn ally near you can activate the Spinal Surge synergy, granting up to 6 allies a damage shield that absorbs up to 30% of their Max Health for 6 seconds and Major Vitality, increasing their healing received and damage shield strength by 12%.",
    icon: "/esoui/art/icons/ability_undaunted_005a.dds",
    isMorph: true,
    morphIndex: 2,
    lineRankNeeded: 4,
    rank: 12,
    subcategoryId: "guild-undaunted" as const,
  },
  "bone-surge-42176": {
    id: "bone-surge-42176" as const,
    esoSkillId: 42176,
    name: "Bone Surge",
    baseName: "Bone Shield",
    skillLineId: "guild-undaunted" as const,
    skillType: "active" as const,
    description:
      "Surround yourself with a whirlwind of bones, gaining a damage shield that absorbs up to |cffffff7258|r damage for |cffffff6|r seconds. This ability scales off your Max Health.\n\nAn ally near you can activate the Spinal Surge synergy, granting up to |cffffff6|r allies a damage shield that absorbs up to |cffffff35|r% of their Max Health for |cffffff6|r seconds and Major Vitality, increasing their healing received and damage shield strength by |cffffff12|r%.",
    icon: "/esoui/art/icons/ability_undaunted_005a.dds",
    isMorph: true,
    morphIndex: 2,
    lineRankNeeded: 4,
    rank: 4,
    subcategoryId: "guild-undaunted" as const,
  },
  "bone-totem": {
    id: "bone-totem" as const,
    esoSkillId: 115093,
    name: "Bone Totem",
    baseName: "Bone Totem",
    skillLineId: "necromancer-bone-tyrant" as const,
    skillType: "active" as const,
    description:
      "Summon an effigy of bone at your feet for |cffffff11|r seconds that grants Minor Protection to you and your allies, reducing damage taken by |cffffff5|r%. Enemies in the area are afflicted with Major Cowardice, reducing their Weapon and Spell Damage by |cffffff430|r.\n\nAfter |cffffff2|r seconds, the totem begins fearing nearby enemies every |cffffff2|r seconds, causing them to cower in place for |cffffff4|r seconds.",
    icon: "/esoui/art/icons/ability_necromancer_010.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 30,
    rank: 30,
    subcategoryId: "necromancer-bone-tyrant" as const,
  },
  "boneyard": {
    id: "boneyard" as const,
    esoSkillId: 115252,
    name: "Boneyard",
    baseName: "Boneyard",
    skillLineId: "necromancer-grave-lord" as const,
    skillType: "active" as const,
    description:
      "Desecrate the ground at the target location, dealing |cffffff10747|r Frost Damage over |cffffff10|r seconds to enemies inside and applying Minor Vulnerability, increasing their damage taken by |cffffff5|r%.\n\nConsumes a corpse on cast to deal |cffffff30|r% more damage.\n\nAn ally in the area can activate the Grave Robber synergy, dealing |cffffff8261|r Frost Damage to nearby enemies and healing for the damage done.",
    icon: "/esoui/art/icons/ability_necromancer_004.dds",
    isMorph: false,
    morphIndex: 0,
    lineRankNeeded: 20,
    rank: 20,
    subcategoryId: "necromancer-grave-lord" as const,
  },
  "borrowed-time": {
    id: "borrowed-time" as const,
    esoSkillId: 40104059,
    name: "Borrowed Time",
    baseName: "Time Stop",
    skillLineId: "guild-psijic-order" as const,
    skillType: "active" as const,
    description:
      "Freeze the passage of time at the target location, gradually reducing the Movement Speed of enemies in the area during the channel before finally stunning them in place for 3 seconds when the channel completes.\n\nEnemies that are stunned gain 5000 Heal Absorption for 3 seconds, negating the next 5000 points of healing done.",
    icon: "/esoui/art/icons/ability_psijic_002_a.dds",
    isMorph: true,
    morphIndex: 1,
    lineRankNeeded: 2,
    rank: 8,
    subcategoryId: "guild-psijic-order" as const,
  },
  "borrowed-time-104059": {
    id: "borrowed-time-104059" as const,
    esoSkillId: 104059,
    name: "Borrowed Time",
    baseName: "Time Stop",
    skillLineId: "guild-psijic-order" as const,
    skillType: "active" as const,
    description:
      "Freeze the passage of time at the target location, gradually reducing the Movement Speed of enemies in the area during the channel before finally stunning them in place for |cffffff3|r seconds when the channel completes.\n\nEnemies that are stunned gain |cffffff5000|r Heal Absorption for |cffffff3|r seconds, negating the next |cffffff5000|r points of healing done.",
    icon: "/esoui/art/icons/ability_psijic_002_a.dds",
    isMorph: true,
    morphIndex: 1,
    lineRankNeeded: 2,
    rank: 2,
    subcategoryId: "guild-psijic-order" as const,
  },
} satisfies Record<string, SkillTemplate>
