import type { EsoAddon } from "../../code-system/eso-addons/eso-addon.page-type.ts"

export const temperHousingAddon = {
  id: "01a06113-b7cb-7519-aaf3-198045bc75aa",
  pageTypeSlug: "eso-addon",
  slug: "temper-housing-addon",
  definition: "the add-on for travelling to a house, whether a friend's, your own or a shared one",
  manifest: "json",
  addonManifest: "json",
  bundleEntrySlug: "housing-entry",
  bindings: "xml",
  partSlugs: [
    "module/housing-addon-names",
    "module/housing-build-casts",
    "module/housing-build-house-tab",
    "module/housing-build-library-tab",
    "module/housing-build-my-houses-tab",
    "module/housing-build-visit-cards-tab",
    "module/housing-build-window",
    "module/housing-chat-capture",
    "module/housing-comboboxes",
    "module/housing-constants",
    "module/housing-context-menu",
    "module/housing-dropdowns",
    "module/housing-entry",
    "module/housing-favorites-helpers",
    "module/housing-favorites-render",
    "module/housing-holder-types",
    "module/housing-house-list",
    "module/housing-house-names",
    "module/housing-hover",
    "module/housing-init",
    "module/housing-library-data-eu",
    "module/housing-library-data-eu-1",
    "module/housing-library-data-eu-2",
    "module/housing-library-data-eu-3",
    "module/housing-library-data-eu-4",
    "module/housing-library-data-eu-5",
    "module/housing-library-data-eu-6",
    "module/housing-library-data-na",
    "module/housing-library-lookup",
    "module/housing-library-tab",
    "module/housing-load",
    "module/housing-menu-state",
    "module/housing-my-houses",
    "module/housing-porting",
    "module/housing-ptf-publish",
    "module/housing-publish",
    "module/housing-search",
    "module/housing-settings-menu",
    "module/housing-slash",
    "module/housing-sliders",
    "module/housing-state",
    "module/housing-state-types",
    "module/housing-tabs",
    "module/housing-types",
    "module/housing-ui-strings",
    "module/housing-visit-card-send",
    "module/housing-visit-cards-interact",
    "module/housing-visit-cards-render",
    "module/housing-visit-cards-view",
    "module/housing-window-controls",
    "type-declaration/housing-declarations",
    "type-declaration/housing-ptf-publish-declarations",
    "type-declaration/housing-publish-declarations",
  ],
  invariants: [
    {
      invariantKind: "departure",
      statement: "A port to another player's house asks the game rather than moving the player.",
    },
    {
      invariantKind: "departure",
      statement: "A visit card travels as an ordinary chat line carrying an agreed key word.",
    },
    {
      invariantKind: "departure",
      statement: "The community library of shared houses is carried with the add-on.",
    },
    {
      invariantKind: "departure",
      statement: "Every keybind reaches the add-on through one published global holder.",
    },
    {
      invariantKind: "absence",
      statement: "Nothing here asks a server outside the game.",
    },
    {
      invariantKind: "gap",
      statement: "The upstream arm asking a player to donate to the author was left behind.",
    },
  ],
} as const satisfies EsoAddon
