import "akasha/temper/eso/type/eso-api-2/eso-api-2.type-declaration.d.ts"
import "akasha/temper/eso/type/eso-globals/eso-globals.type-declaration.d.ts"

const STRINGS: Record<string, string> = {
  SI_KEYBINDINGS_CATEGORY_TEMPER_MINIMAP: "Mini Map",
  SI_BINDING_NAME_VOTANS_TOGGLE_MAP_SHOW: "Toggle Show Map",
  SI_BINDING_NAME_VOTANS_TOGGLE_MAP_SHOW_HUD: "Toggle Show HUD",
  SI_BINDING_NAME_VOTANS_TOGGLE_MAP_SHOW_SIEGE_HUD: "Toggle Show Siege",
  SI_BINDING_NAME_VOTANS_TOGGLE_MAP_SHOW_IN_HOUSING: "Toggle Show in Housing",
  SI_BINDING_NAME_VOTANS_TOGGLE_MAP_SHOW_COMBAT: "Toggle Show Map In Combat",
  SI_BINDING_NAME_VOTANS_TOGGLE_MAP_ZOOM_OUT: "Zoom Max Out",
  SI_BINDING_NAME_VOTANS_TOGGLE_MAP_ZOOM_IN: "Zoom Max In",
  SI_BINDING_NAME_VOTANS_TOGGLE_MAP_ZOOM_PLUS: "Zoom Step In",
  SI_BINDING_NAME_VOTANS_TOGGLE_MAP_ZOOM_MINUS: "Zoom Step Out",
  SI_BINDING_NAME_VOTANS_TOGGLE_MAP_OFFSET_FIX: "Toggle Fixed Mini Map Position",
  SI_TEMPERMINIMAP_WORLD_MAP_TWEAKS: "World Map Tweaks",
  SI_TEMPERMINIMAP_WORLD_MAP_TWEAKS_TOOLTIP: "Enable tweaks to spread CPU load over time.",
  SI_TEMPERMINIMAP_MINI_MAP: "Mini Map",
  SI_TEMPERMINIMAP_MINI_MAP_TOOLTIP: "Enable Mini Map feature of in-build map.",
  SI_TEMPERMINIMAP_APPLY_BUTTON: "Apply",
  SI_TEMPERMINIMAP_LOCK_POSITION: "Lock Position & Size",
  SI_TEMPERMINIMAP_LOCK_POSITION_TOOLTIP: "Do not allow to move and resize the window.",
  SI_TEMPERMINIMAP_ZOOM: "Zoom",
  SI_TEMPERMINIMAP_ZOOM_TOOLTIP: "Zoom relative to native map resolution.",
  SI_TEMPERMINIMAP_MOUNTED_ZOOM: "Mounted Zoom Scale",
  SI_TEMPERMINIMAP_MOUNTED_ZOOM_TOOLTIP:
    "Relative zoom factor, if mounted. Value 1 keeps the current zoom.",
  SI_TEMPERMINIMAP_SUB_ZONE_ZOOM: "Sub-Zone Zoom",
  SI_TEMPERMINIMAP_SUB_ZONE_ZOOM_TOOLTIP:
    "Zoom relative to native map resolution, if in a sub-zone.",
  SI_TEMPERMINIMAP_DUNGEON_ZOOM: "Dungeon Zoom",
  SI_TEMPERMINIMAP_DUNGEON_ZOOM_TOOLTIP: "Zoom relative to native map resolution, if in a dungeon.",
  SI_TEMPERMINIMAP_BG_ZOOM: "Battleground Zoom",
  SI_TEMPERMINIMAP_BG_ZOOM_TOOLTIP: "Zoom relative to native map resolution, if on a battleground.",
  SI_TEMPERMINIMAP_UNIT_PINS_MINIMUM_SIZE: "Unit Pins Minimum Size",
  SI_TEMPERMINIMAP_UNIT_PINS_MINIMUM_SIZE_TOOLTIP: "Unit Pins are not scaled below this factor.",
  SI_TEMPERMINIMAP_SHOW_MAP: "Show Map",
  SI_TEMPERMINIMAP_SHOW_MAP_TOOLTIP: "Show mini map at all.",
  SI_TEMPERMINIMAP_SHOW_HUD: "Show in HUD",
  SI_TEMPERMINIMAP_SHOW_HUD_TOOLTIP: "Show while walking in world",
  SI_TEMPERMINIMAP_SHOW_LOOTING: "Show while Looting.",
  SI_TEMPERMINIMAP_SHOW_LOOTING_TOOLTIP: "Less hide and show.",
  SI_TEMPERMINIMAP_ZOOM_TO_PLAYER: "Zoom World Map to Player",
  SI_TEMPERMINIMAP_ZOOM_TO_PLAYER_TOOLTIP: "Show World Map either max zoomed in or zoomed out.",
  SI_TEMPERMINIMAP_SHOW_MOUNTED: "Show while Mounted",
  SI_TEMPERMINIMAP_SHOW_MOUNTED_TOOLTIP:
    "Show while sitting on your mount. Has priority over show in combat.",
  SI_TEMPERMINIMAP_SHOW_COMBAT: "Show in Combat",
  SI_TEMPERMINIMAP_SHOW_COMBAT_TOOLTIP: "Show while in combat.",
  SI_TEMPERMINIMAP_SHOW_SIEGE: "Show at Siege",
  SI_TEMPERMINIMAP_SHOW_SIEGE_TOOLTIP: "Show while at siege.",
  SI_TEMPERMINIMAP_SHOW_IN_HOUSING: "Show in Houses",
  SI_TEMPERMINIMAP_SHOW_IN_HOUSING_TOOLTIP: "Show while in a house.",
  SI_TEMPERMINIMAP_KEYBINDINGS_ZOOM: "Keybindings Zoom",
  SI_TEMPERMINIMAP_ZOOM_OUT: "Zoom Out",
  SI_TEMPERMINIMAP_ZOOM_OUT_TOOLTIP: "Zoom factor for Zoom Out key-bind.\n(Hold key pressed.)",
  SI_TEMPERMINIMAP_ZOOM_IN: "Zoom In",
  SI_TEMPERMINIMAP_ZOOM_IN_TOOLTIP: "Zoom factor for Zoom In key-bind.\n(Hold key pressed.)",
  SI_TEMPERMINIMAP_APPEARANCE: "Appearance",
  SI_TEMPERMINIMAP_BORDER_STYLE: "Border Style",
  SI_TEMPERMINIMAP_BORDER_OPACITY: "Border Opacity",
  SI_TEMPERMINIMAP_BORDER_OPACITY_TOOLTIP: "",
  SI_TEMPERMINIMAP_TITLE_FONT: "Title Font",
  SI_TEMPERMINIMAP_TITLE_FONT_SIZE: "Title Font Size",
  SI_TEMPERMINIMAP_TITLE_COLOR: "Title Color",
  SI_TEMPERMINIMAP_TITLE_POSITION: "Title Position",
  SI_TEMPERMINIMAP_SHOW_FULL_TITLE: "Show Full Title",
  SI_TEMPERMINIMAP_SHOW_FULL_TITLE_TOOLTIP:
    "Shows the full title. Including campaign name and difficulty, even if it may too long for a mini map window.",
  SI_TEMPERMINIMAP_SHOW_CLOCK: "Show Clock",
  SI_TEMPERMINIMAP_SHOW_CLOCK_TOOLTIP: "Show clock in mini map.",
  SI_TEMPERMINIMAP_TIME_FORMAT: "Time Format",
  SI_TEMPERMINIMAP_SHOW_CLOCK0: "Off",
  SI_TEMPERMINIMAP_SHOW_CLOCK1: "Real Time",
  SI_TEMPERMINIMAP_SHOW_CLOCK2: "In-Game Time",
  SI_TEMPERMINIMAP_SHOW_CLOCK3: "Real & In-Game Time",
  SI_TEMPERMINIMAP_ZONE_CHANGE_ALERT: "Zone Change Alert",
  SI_TEMPERMINIMAP_SHOW_COMPASS: "Show/Hide Compass",
  SI_TEMPERMINIMAP_SHOW_COMPASS_TOOLTIP:
    "Show or hide compass, if mini map is shown or keep untouched and let other addons change the compass visibility.",
  SI_TEMPERMINIMAP_FRAMEDROP_DEBUG: "Framedrop Debug",
  SI_TEMPERMINIMAP_SHOW_FREEZE_WARNING: "Show Freeze Warning",
  SI_TEMPERMINIMAP_SHOW_FREEZE_WARNING_TOOLTIP:
    "Show a warning if action exceeds frametime for 60fps.",
  SI_TEMPERMINIMAP_SHOW_CAMERA_HEADING: "Show Camera Heading",
  SI_TEMPERMINIMAP_SHOW_CAMERA_HEADING_TOOLTIP: "Show camera heading on world and mini map.",
  SI_TEMPERMINIMAP_CAMERA_HEADING_ANGLE: "Marker Angle",
  SI_TEMPERMINIMAP_CAMERA_HEADING_ANGLE_TOOLTIP: "The angle of the marker line.",
  SI_TEMPERMINIMAP_SHOW_ON_TOP: "Show On Top",
  SI_TEMPERMINIMAP_SHOW_ON_TOP_TOOLTIP: "Put MiniMap in front of other elements.",
  SI_TEMPERMINIMAP_ZONEALERTMODE_ALWAYS: "Always",
  SI_TEMPERMINIMAP_ZONEALERTMODE_MAP_HIDDEN: "Mini Map Hidden",
  SI_TEMPERMINIMAP_ZONEALERTMODE_NEVER: "Never",
  SI_TEMPERMINIMAP_COMPASSMODE_UNTOUCHED: "Untouched",
  SI_TEMPERMINIMAP_COMPASSMODE_HIDDEN: "Hidden",
  SI_TEMPERMINIMAP_COMPASSMODE_SHOWN: "Shown",
  SI_TEMPERMINIMAP_KEEP_SQUARE: "Keep Square",
  SI_TEMPERMINIMAP_KEEP_SQUARE_TOOLTIP: "Keep the map area square. Default behavior.",
  SI_TEMPERMINIMAP_ASYNC_UPDATE: "Asynchronous Update",
  SI_TEMPERMINIMAP_ASYNC_UPDATE_TOOLTIP: "On: Framerate over update.\nOff: Update over framerate.",
  SI_TEMPERMINIMAP_PINSIZE_KEEP_FAST_TRAVEL: "Transitus Shrine",
  SI_TEMPERMINIMAP_PINSIZE_KEEPS: "Keeps",
  SI_TEMPERMINIMAP_PINSIZE_DISTRICTS: "Districts",
  SI_TEMPERMINIMAP_SHOW_ALL_TRAVEL_NODES: "Show all way shrines",
  SI_TEMPERMINIMAP_SHOW_ALL_TRAVEL_NODES_TOOLTIP: "",
  SI_TEMPERMINIMAP_SHOW_IN_SETTINGS: "Show mini map now",
  SI_TEMPERMINIMAP_GRID_X: "Position - Grid X",
  SI_TEMPERMINIMAP_GRID_Y: "Position - Grid Y",
  SI_TEMPERMINIMAP_GRID_W: "Size - Grid Width",
  SI_TEMPERMINIMAP_GRID_H: "Size - Grid Height",
  SI_TEMPERMINIMAP_GRID_TOOLTIP:
    "Position & size in an 8x8 grid. But you can also use the mouse to change position and size.",
}

export function registerStrings(this: void): undefined {
  for (const [stringId, stringValue] of Object.entries(STRINGS)) {
    ZO_CreateStringId(stringId, stringValue)
    SafeAddVersion(stringId, 1)
  }
}
