value: ENC[AES256_GCM,data:ia+Ts6Oqk6FreRRvI2N+6cImTFXSlc2J+tbYIvaRSrfAxTTVOj8UUhLuvXZLwlA9ksoNw7/maK/BLjBCTNNQvS5pD6IYFRAklohQPpoYvh3by6zA/CJWqw+HIOFR7bX7TQf2WqJS5HwqMbNGzAL0+5AI7FiQtVpQNXIH+L4KAj+0DcTIEo3F+54W5CDK+m3DLr7rm+lfpjTB2GlOrwGbTe8SRi83VAlg4ZUirKd+szPNoeGYsZovIt7EChuscvec7OEZ05njVhXJZtR/5MW90JB0uuVVwH/CM8nguGZKSEBxqOTClsHUnvADWtQ8Pq9OsjVCwWmTvXjpb34kjvoE1vmS1audPYmocUXc45uke0U8BBSctpN71338m4SsYSGuEULNwordv7jpOTa6BdDl63/Ba/dr95M8UtKk70Y=,iv:dcmEx3ZUpFacY+8ucLvTxkhE0BZVK0pSx/h/VMyP3uY=,tag:aoV29ZlBV7jmlv5HA5uMyw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuWjNheTRuRnBGOENLSHlu
            MFEvY1pGL1RncVM4OW1ob2NaMXV0MTVvVzEwCnExaTJBdHcwd0Jpa1Y1dEJRZ0Iz
            S3Qvb1F2RzJaelk2eDdha3BkRGJ2eHcKLS0tIGRPMXBZU1h5VXdRVDJ2OVd0dWVC
            SXdIakVidmtZRDA2NVNUb2dVSWcwVzAKKvMhqjrUzeXm/AD8dCX+7QWYrjP1D9+5
            a06Zc024zbKDgC9yBLNVq3sfZef/Pzd5jZZVPyc0r7dlwD2aUVFqxg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
    lastmodified: "2026-09-06T12:01:54Z"
    mac: ENC[AES256_GCM,data:vqhQ6NzsReoNQGb6e4xnVtGo1eHTQDz7h8Ew1JWW8/hWjUmWWzNveCECnB+8wDq1bApgtW7LQvL1+NkseJ0p4Z+8wIAQo8P3NPNyGXFRU3VeK1qWE0UxF6sFN3sFesz2eKkvpehml/M6OLOp419Xz4nUcqhkc/OpFRMkDILuIpc=,iv:kx7gDIpPOL+5qQt/OhZAXnwnNK9wHYcs0pwTmZ30jOA=,tag:+b0FxJat0rhhD/Ve9ld0Tw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
