value: ENC[AES256_GCM,data:4PTbEMtuEuxUFd5LssI9+rxioFsqE78bbrHUdA4+F2eyMbIAk4W78oCdF9+0yloDNfqros8OmW3LHUG+Dxrt66J0NuYkM7Re5owOmAydgUSy8FZhbiwXXlMk7JFiOKicEVuw63AuEIguLnv7lmTOyX2mcOezpVRIWxRz0w==,iv:WawGH7CWSEiDDbpvAl4jQ2QLjKWbCE4z716bCLZgEe8=,tag:XR7J/Twky9W2oF+vqseWnQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIVEhGUHFNbEs2ZlpCd3VP
            L3Z3Z05yTzJaSm9qNC9ZVmFYWkZYdFAwdUJ3CmpzTytJL3Viekk2ZEVmREpQNlNx
            K0ZUZCtrUmhGRUtNcndidkE0dXJJc1UKLS0tIGN3bml6ZmZpa1hlRVNiMmxaZ1Ix
            WTBDNFp6QnRvdnA4SGxLQjN3RDRGTGMKc9ZSeJROcKN3khbsdRDiqVvg37klazK4
            8VBQW7bjLSRARCOOx0mz7UviO5SsC8ukq2qVKDIgUUqa6wmY7nTkhg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
    lastmodified: "2026-09-06T12:02:11Z"
    mac: ENC[AES256_GCM,data:6HJkVWm9SEw9v9rKvB4k4o9GkWNJ+Ii/0xu443Fat06dLeP3k1bsRCiHXKEhMPHwokMqbliDheEIq2YAu75D1yYaHpCsRmY52byzkxZVRRgnkJjqIgsi6+CmE0CJRTdkaKiAr90twr46ovCx8HEfF2T0DU5X0Mw/hYgtWrbPTP8=,iv:PpY5u3ukW1enYSxGK1POLNaZjSS/MN4ggDvWtTkEdx4=,tag:ULkwP2tjCcWjV4zi5qwFmg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
