value: ENC[AES256_GCM,data:a9lQnZ1RvTxn3gqr3a1fRmskEs2AL0bzROXT3m8pGc66glTsKdcJ8uAjp6mqPpDJNUrThizZ7AnePbx8A+9EHFCgQ2G8Ozr4NJR/+Mj/sUKJWOhEv46x5C+9NZ0B/CuXvSCdd/2M+72T5owc2wJQ245wM/CI2wx892eT9r7/NEOK+lFZT4oxxQFrgWMajoBy2s8sAvLULvUBnRR53BEE99J3c7gP6Nyh5iG7geEPRJjwozVsI/xi8D+ZEtM2a7pF,iv:/5UphTY1QG5+bRQkggd48n4xmWKv+68BwhsaGR54Hgw=,tag:c7P/ijoXQCd9wSDYhE2mVA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiT0dTTDVZZXpBdStUeHJk
            azI1dDBIK0FRT2Z1YitZUXRnck1mcnBRRm1BCjZQUEhWcFhjV2pZcHRFL280dmxE
            VEswSmhUU1hGZHlSZXkrYUsrbHFTdXcKLS0tIG9FWGN3NGRoUjB6ZHEveUE3eExm
            R3dLNUZYR1hxelAycmFJVVoyUnRaQVEKWfbyxgAitfao/ywAMVRSgR6y4goEftBm
            dkS3x2kp3MwOw0G10tmV4QUK9o3SGGuSjnfXG9OcacvTblR0bUWKgg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g23777pz5n0hm7umfm7a8vhl8sk2e4k8zwk8ht7j86fpssky0geqeqcxh2
    lastmodified: "2026-08-28T15:00:32Z"
    mac: ENC[AES256_GCM,data:n21E7Z9jA411U1tc8D3wapWyimdqnBw4z011Bm3wYnBpAC5w+sfEHCSKlC1bd0Mos3lM9TQW3IAKsdEVybqhfsTyMGIV1S2Zk2ZGPBecL4f/ncVs5tXzXVUZnxH6BYExYDYHGQ9CNeNZNoVafNaRJadUiNUbmJ3u6aeX4dcLVCw=,iv:PBch8ukg7AxQp64OVOWxwzOvCRiCnKl31b0g8qvepbw=,tag:VmqtQ1dNG2/O7FuIFHqwIA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
