import type { EsoAddon } from "akasha/code/eso-addons/eso-addon.page-type.types.ts"

export const temperLibCharacterKnowledge = {
  id: "01a061fa-8034-72e8-8175-6440e4c91a6d",
  type: "eso-addon",
  slug: "temper-lib-character-knowledge",
  definition: "what every character on every account knows how to make",

  addonManifest: "json",
  bundleEntry: "knowledge-main",
  parts: [
    "module/knowledge-base-data",
    "module/knowledge-base-data-motifs",
    "module/knowledge-base-data-plans",
    "module/knowledge-base-data-recipes",
    "module/knowledge-casts",
    "module/knowledge-core",
    "module/knowledge-curated-invalid-ids",
    "module/knowledge-curated-motifs",
    "module/knowledge-curated-style-quality",
    "module/knowledge-init",
    "module/knowledge-init-chardata",
    "module/knowledge-item-knowledge",
    "module/knowledge-ldei",
    "module/knowledge-lookups",
    "module/knowledge-main",
    "module/knowledge-motif",
    "module/knowledge-public-api",
    "module/knowledge-public-callbacks",
    "module/knowledge-public-core",
    "module/knowledge-public-research",
    "module/knowledge-public-scribing",
    "module/knowledge-register-strings",
    "module/knowledge-research",
    "module/knowledge-research-get",
    "module/knowledge-scan",
    "module/knowledge-scribing",
    "module/knowledge-settings-controls",
    "module/knowledge-settings-export-import",
    "module/knowledge-settings-main-section",
    "module/knowledge-settings-panel",
    "module/knowledge-shape",
    "module/knowledge-state",
    "module/knowledge-strings-default",
    "module/knowledge-strings-es",
    "module/knowledge-strings-fr",
    "module/knowledge-strings-ru",
    "module/knowledge-strings-zh",
    "module/knowledge-types",
    "type-declaration/knowledge-string-ids",
  ],
  invariants: [
    {
      invariantKind: "departure",
      statement: "One character's knowledge is kept as a bitfield over the whole item table.",
    },
    {
      invariantKind: "departure",
      statement: "The item table is scanned once per game update rather than once per session.",
    },
    {
      invariantKind: "departure",
      statement: "A character on another account is read from the shared saved record alone.",
    },
    {
      invariantKind: "departure",
      statement: "A character's knowledge travels between accounts as one line of text.",
    },
    {
      invariantKind: "constraint",
      statement: "A console client cannot scan the item table and reads the shipped list.",
    },
    {
      invariantKind: "constraint",
      statement: "This library depends on no other add-on.",
    },
  ],
} as const satisfies EsoAddon
