import type { FormulaCase } from "./cases.ts"
import {
  ABSENT,
  answersBoolean,
  answersNumber,
  answersText,
  C,
  COUNT,
  call,
  caseForm,
  FLAG,
  L,
  MIXED,
  NAME,
  NOTHING,
  num,
  text,
} from "./shorthand.ts"

export const absence: FormulaCase[] = [
  {
    name: "plus given an absent left side answers absent",
    group: "absence",
    from: L.absentOperator,
    claim: C.absentOperator,
    formula: "{count} + 1",
    shape: COUNT,
    values: {},
    expected: ABSENT,
  },
  {
    name: "plus given an absent right side answers absent",
    group: "absence",
    from: L.absentOperator,
    claim: C.absentOperator,
    formula: "1 + {count}",
    shape: COUNT,
    values: {},
    expected: ABSENT,
  },
  {
    name: "minus given an absent value answers absent",
    group: "absence",
    from: L.absentOperator,
    claim: C.absentOperator,
    formula: "{count} - 1",
    shape: COUNT,
    values: {},
    expected: ABSENT,
  },
  {
    name: "times given an absent value answers absent",
    group: "absence",
    from: L.absentOperator,
    claim: C.absentOperator,
    formula: "{count} * 2",
    shape: COUNT,
    values: {},
    expected: ABSENT,
  },
  {
    name: "times by zero given an absent value still answers absent",
    group: "absence",
    from: L.absentOperator,
    claim: C.absentOperator,
    formula: "{count} * 0",
    shape: COUNT,
    values: {},
    expected: ABSENT,
  },
  {
    name: "divide given an absent value answers absent",
    group: "absence",
    from: L.absentOperator,
    claim: C.absentOperator,
    formula: "{count} / 2",
    shape: COUNT,
    values: {},
    expected: ABSENT,
  },
  {
    name: "less than given an absent value answers absent",
    group: "absence",
    from: L.absentOperator,
    claim: C.absentOperator,
    formula: "{count} < 1",
    shape: COUNT,
    values: {},
    expected: ABSENT,
  },
  {
    name: "at most given an absent value answers absent",
    group: "absence",
    from: L.absentOperator,
    claim: C.absentOperator,
    formula: "{count} <= 1",
    shape: COUNT,
    values: {},
    expected: ABSENT,
  },
  {
    name: "more than given an absent value answers absent",
    group: "absence",
    from: L.absentOperator,
    claim: C.absentOperator,
    formula: "1 > {count}",
    shape: COUNT,
    values: {},
    expected: ABSENT,
  },
  {
    name: "at least given an absent value answers absent",
    group: "absence",
    from: L.absentOperator,
    claim: C.absentOperator,
    formula: "1 >= {count}",
    shape: COUNT,
    values: {},
    expected: ABSENT,
  },
  {
    name: "and given an absent right side answers absent",
    group: "absence",
    from: L.absentOperator,
    claim: C.absentOperator,
    formula: "true && {flag}",
    shape: FLAG,
    values: {},
    expected: ABSENT,
  },
  {
    name: "and given an absent left side answers absent",
    group: "absence",
    from: L.absentOperator,
    claim: C.absentOperator,
    formula: "{flag} && true",
    shape: FLAG,
    values: {},
    expected: ABSENT,
  },
  {
    name: "a false left side answers false without reaching an absent right",
    group: "absence",
    from: L.shortCircuit,
    claim: C.shortCircuit,
    formula: "false && {flag}",
    shape: FLAG,
    values: {},
    expected: answersBoolean(false),
  },
  {
    name: "an absent left side answers absent without working out its right",
    group: "absence",
    from: L.shortCircuit,
    claim: C.shortCircuit,
    formula: "{flag} && {count} / 0 > 0",
    shape: MIXED,
    values: { count: num(1) },
    expected: ABSENT,
  },
  {
    name: "and given the word absent answers absent",
    group: "absence",
    from: L.absentOperator,
    claim: C.absentOperator,
    formula: "true && absent",
    shape: NOTHING,
    values: {},
    expected: ABSENT,
  },
  {
    name: "absence carries up through nested operators",
    group: "absence",
    from: L.absentOperator,
    claim: C.absentOperator,
    formula: "({count} + 1) * 2",
    shape: COUNT,
    values: {},
    expected: ABSENT,
  },
  {
    name: "absence in one arm does not spare the other arm's operator",
    group: "absence",
    from: L.absentOperator,
    claim: C.absentOperator,
    formula: "{count} + {other} * 2",
    shape: MIXED,
    values: { other: num(3) },
    expected: ABSENT,
  },
  {
    name: "equal against absent answers a boolean, not absent",
    group: "absence",
    from: L.absentEquality,
    claim: C.absentEquality,
    formula: "{count} == absent",
    shape: COUNT,
    values: {},
    expected: answersBoolean(true),
  },
  {
    name: "equal against absent answers false where the value is there",
    group: "absence",
    from: L.absentEquality,
    claim: C.absentEquality,
    formula: "{count} == absent",
    shape: COUNT,
    values: { count: num(0) },
    expected: answersBoolean(false),
  },
  {
    name: "an absent value is not equal to a number",
    group: "absence",
    from: L.absentEquality,
    claim: C.absentEquality,
    formula: "{count} == 1",
    shape: COUNT,
    values: {},
    expected: answersBoolean(false),
  },
  {
    name: "a number is not equal to an absent value, the other way round",
    group: "absence",
    from: L.absentEquality,
    claim: C.absentEquality,
    formula: "1 == {count}",
    shape: COUNT,
    values: {},
    expected: answersBoolean(false),
  },
  {
    name: "an absent value is not equal to zero",
    group: "absence",
    from: L.absentEquality,
    claim: C.absentEquality,
    formula: "{count} == 0",
    shape: COUNT,
    values: {},
    expected: answersBoolean(false),
  },
  {
    name: "an absent value is not equal to empty text",
    group: "absence",
    from: L.absentEquality,
    claim: C.absentEquality,
    formula: '{name} == ""',
    shape: NAME,
    values: {},
    expected: answersBoolean(false),
  },
  {
    name: "an absent value is not equal to false",
    group: "absence",
    from: L.absentEquality,
    claim: C.absentEquality,
    formula: "{flag} == false",
    shape: FLAG,
    values: {},
    expected: answersBoolean(false),
  },
  {
    name: "absent equals absent",
    group: "absence",
    from: L.absentEquality,
    claim: C.absentEquality,
    formula: "absent == absent",
    shape: NOTHING,
    values: {},
    expected: answersBoolean(true),
  },
  {
    name: "two absent keys are equal",
    group: "absence",
    from: L.absentEquality,
    claim: C.absentEquality,
    formula: "{count} == {other}",
    shape: MIXED,
    values: {},
    expected: answersBoolean(true),
  },
  {
    name: "an absent key is not equal to a present one",
    group: "absence",
    from: L.absentEquality,
    claim: C.absentEquality,
    formula: "{count} == {other}",
    shape: MIXED,
    values: { other: num(1) },
    expected: answersBoolean(false),
  },
  {
    name: "not-equal against absent answers a boolean, not absent",
    group: "absence",
    from: L.absentEquality,
    claim: C.absentEquality,
    formula: "{count} != absent",
    shape: COUNT,
    values: {},
    expected: answersBoolean(false),
  },
  {
    name: "not-equal against absent answers true where the value is there",
    group: "absence",
    from: L.absentEquality,
    claim: C.absentEquality,
    formula: "{count} != absent",
    shape: COUNT,
    values: { count: num(5) },
    expected: answersBoolean(true),
  },
  {
    name: "an absent value differs from a number",
    group: "absence",
    from: L.absentEquality,
    claim: C.absentEquality,
    formula: "{count} != 1",
    shape: COUNT,
    values: {},
    expected: answersBoolean(true),
  },
  {
    name: "absent does not differ from absent",
    group: "absence",
    from: L.absentEquality,
    claim: C.absentEquality,
    formula: "absent != absent",
    shape: NOTHING,
    values: {},
    expected: answersBoolean(false),
  },
  {
    name: "an equality against absent can be tested by a case row",
    group: "absence",
    from: L.absentEquality,
    claim: C.absentEquality,
    formula: caseForm([{ test: "{count} == absent", value: '"missing"' }], '"there"'),
    shape: COUNT,
    values: {},
    expected: answersText("missing"),
  },
  {
    name: "an absent value stops the whole answer where no fallback catches it",
    group: "absence",
    from: L.absentStopsAnswer,
    claim: C.absentStopsAnswer,
    formula: "{count} + {other} + 1",
    shape: MIXED,
    values: { other: num(2) },
    expected: ABSENT,
  },
  {
    name: "a function reaching an absent value answers absent",
    group: "absence",
    from: L.absentFunction,
    claim: C.absentFunction,
    formula: call("hasWord", "{name}", '"cat"'),
    shape: NAME,
    values: {},
    expected: ABSENT,
  },
  {
    name: "a function reaching an absent list answers absent",
    group: "absence",
    from: L.absentFunction,
    claim: C.absentFunction,
    formula: call("contains", "{tags}", '"green"'),
    shape: MIXED,
    values: {},
    expected: ABSENT,
  },
  {
    name: "a function whose arguments are all there is untouched by absence elsewhere",
    group: "absence",
    from: L.absentFunction,
    claim: C.absentFunction,
    formula: call("hasWord", "{name}", '"cat"'),
    shape: MIXED,
    values: { name: text("the cat sat") },
    expected: answersBoolean(true),
  },
  {
    name: "a function reaching nothing is untouched by absence",
    group: "absence",
    from: L.absentFunction,
    claim: C.absentFunction,
    formula: call("hoursBetween", call("now"), call("now")),
    shape: MIXED,
    values: {},
    now: "2026-01-01T03:00:00Z",
    expected: answersNumber(0),
  },
  {
    name: "negation reaching an absent value answers absent",
    group: "absence",
    from: L.absentOperator,
    claim: C.absentOperator,
    formula: "-{count}",
    shape: COUNT,
    values: {},
    expected: ABSENT,
  },
]
