import type { FormulaCase } from "./cases.ts"
import {
  ABSENT,
  answersBoolean,
  answersNumber,
  C,
  call,
  instant,
  L,
  listOfValues,
  MIXED,
  NAME,
  NOTHING,
  num,
  refused,
  text,
} from "./shorthand.ts"

export const functions: FormulaCase[] = [
  {
    name: "hours between two instants",
    group: "functions",
    from: L.fnHoursBetween,
    claim: C.fnHoursBetween,
    formula: call("hoursBetween", "{start}", "{finish}"),
    shape: MIXED,
    values: {
      start: instant("2026-01-01T00:00:00Z"),
      finish: instant("2026-01-01T05:00:00Z"),
    },
    expected: answersNumber(5),
  },
  {
    name: "hours between two instants, fractional",
    group: "functions",
    from: L.fnHoursBetween,
    claim: C.fnHoursBetween,
    formula: call("hoursBetween", "{start}", "{finish}"),
    shape: MIXED,
    values: {
      start: instant("2026-01-01T00:00:00Z"),
      finish: instant("2026-01-01T01:30:00Z"),
    },
    expected: answersNumber(1.5),
  },
  {
    name: "hours between one instant and itself is zero",
    group: "functions",
    from: L.fnHoursBetween,
    claim: C.fnHoursBetween,
    formula: call("hoursBetween", "{start}", "{start}"),
    shape: MIXED,
    values: { start: instant("2026-01-01T00:00:00Z") },
    expected: answersNumber(0),
  },
  {
    name: "hours between instants crossing a day boundary",
    group: "functions",
    from: L.fnHoursBetween,
    claim: C.fnHoursBetween,
    formula: call("hoursBetween", "{start}", "{finish}"),
    shape: MIXED,
    values: {
      start: instant("2026-01-01T23:00:00Z"),
      finish: instant("2026-01-02T02:00:00Z"),
    },
    expected: answersNumber(3),
  },
  {
    name: "now is the moment the formula is worked out",
    group: "functions",
    from: L.fnNow,
    claim: C.fnNow,
    formula: call("hoursBetween", "{start}", call("now")),
    shape: MIXED,
    values: { start: instant("2026-01-01T00:00:00Z") },
    now: "2026-01-01T03:00:00Z",
    expected: answersNumber(3),
  },
  {
    name: "now answers one moment for the whole working-out",
    group: "functions",
    from: L.fnNow,
    claim: C.fnNow,
    formula: call("hoursBetween", call("now"), call("now")),
    shape: NOTHING,
    values: {},
    now: "2026-01-01T03:00:00Z",
    expected: answersNumber(0),
  },
  {
    name: "hours between with an absent instant",
    group: "functions",
    from: L.absentFunction,
    claim: C.absentFunction,
    formula: call("hoursBetween", "{start}", "{finish}"),
    shape: MIXED,
    values: { start: instant("2026-01-01T00:00:00Z") },
    expected: ABSENT,
  },
  {
    name: "contains answers true where the list holds the value",
    group: "functions",
    from: L.fnContains,
    claim: C.fnContains,
    formula: call("contains", "{tags}", '"green"'),
    shape: MIXED,
    values: { tags: listOfValues(text("red"), text("green")) },
    expected: answersBoolean(true),
  },
  {
    name: "contains answers false where the list does not hold the value",
    group: "functions",
    from: L.fnContains,
    claim: C.fnContains,
    formula: call("contains", "{tags}", '"blue"'),
    shape: MIXED,
    values: { tags: listOfValues(text("red"), text("green")) },
    expected: answersBoolean(false),
  },
  {
    name: "contains answers false over an empty list",
    group: "functions",
    from: L.fnContains,
    claim: C.fnContains,
    formula: call("contains", "{tags}", '"green"'),
    shape: MIXED,
    values: { tags: listOfValues() },
    expected: answersBoolean(false),
  },
  {
    name: "contains over a list of numbers",
    group: "functions",
    from: L.fnContains,
    claim: C.fnContains,
    formula: call("contains", "{scores}", "3"),
    shape: MIXED,
    values: { scores: listOfValues(num(1), num(2), num(3)) },
    expected: answersBoolean(true),
  },
  {
    name: "contains matches a whole element, not a part of one",
    group: "functions",
    from: L.fnContains,
    claim: C.fnContains,
    formula: call("contains", "{tags}", '"gree"'),
    shape: MIXED,
    values: { tags: listOfValues(text("green")) },
    expected: answersBoolean(false),
  },
  {
    name: "has word answers true where the text holds the word",
    group: "functions",
    from: L.fnHasWord,
    claim: C.fnHasWord,
    formula: call("hasWord", '"red green blue"', '"green"'),
    shape: NOTHING,
    values: {},
    expected: answersBoolean(true),
  },
  {
    name: "has word answers false where the word is only part of a longer one",
    group: "functions",
    from: L.fnHasWord,
    claim: C.fnHasWord,
    formula: call("hasWord", '"greenhouse gases"', '"green"'),
    shape: NOTHING,
    values: {},
    expected: answersBoolean(false),
  },
  {
    name: "has word answers false where the word is only the end of a longer one",
    group: "functions",
    from: L.fnHasWord,
    claim: C.fnHasWord,
    formula: call("hasWord", '"evergreen leaves"', '"green"'),
    shape: NOTHING,
    values: {},
    expected: answersBoolean(false),
  },
  {
    name: "has word answers true where the word is the whole text",
    group: "functions",
    from: L.fnHasWord,
    claim: C.fnHasWord,
    formula: call("hasWord", '"green"', '"green"'),
    shape: NOTHING,
    values: {},
    expected: answersBoolean(true),
  },
  {
    name: "has word answers true for the first word of a text",
    group: "functions",
    from: L.fnHasWord,
    claim: C.fnHasWord,
    formula: call("hasWord", '"green day units"', '"green"'),
    shape: NOTHING,
    values: {},
    expected: answersBoolean(true),
  },
  {
    name: "has word answers true for the last word of a text",
    group: "functions",
    from: L.fnHasWord,
    claim: C.fnHasWord,
    formula: call("hasWord", '"units green day green"', '"day"'),
    shape: NOTHING,
    values: {},
    expected: answersBoolean(true),
  },
  {
    name: "has word over a reference",
    group: "functions",
    from: L.fnHasWord,
    claim: C.fnHasWord,
    formula: call("hasWord", "{name}", '"cat"'),
    shape: NAME,
    values: { name: text("the cat sat") },
    expected: answersBoolean(true),
  },
  {
    name: "has word answers false over empty text",
    group: "functions",
    from: L.fnHasWord,
    claim: C.fnHasWord,
    formula: call("hasWord", '""', '"green"'),
    shape: NOTHING,
    values: {},
    expected: answersBoolean(false),
  },
  {
    name: "a function this language does not have is refused",
    group: "functions",
    from: L.noUpperFunction,
    claim: C.noUpperFunction,
    formula: call("upper", "{name}"),
    shape: NAME,
    values: { name: text("astra") },
    expected: refused("check", "unknown-function", ["upper"]),
  },
  {
    name: "a substring test is not a function this language has",
    group: "functions",
    from: L.noIncludesFunction,
    claim: C.noIncludesFunction,
    formula: call("includes", "{name}", '"a"'),
    shape: NAME,
    values: { name: text("astra") },
    expected: refused("check", "unknown-function", ["includes"]),
  },
  {
    name: "hours between given one argument is refused",
    group: "functions",
    from: L.fnHoursBetween,
    claim: C.fnHoursBetween,
    formula: call("hoursBetween", "{start}"),
    shape: MIXED,
    values: { start: instant("2026-01-01T00:00:00Z") },
    expected: refused("check", "wrong-argument-count", ["hoursBetween"]),
  },
  {
    name: "hours between given three arguments is refused",
    group: "functions",
    from: L.fnHoursBetween,
    claim: C.fnHoursBetween,
    formula: call("hoursBetween", "{start}", "{finish}", "{start}"),
    shape: MIXED,
    values: {},
    expected: refused("check", "wrong-argument-count", ["hoursBetween"]),
  },
  {
    name: "now given an argument is refused",
    group: "functions",
    from: L.fnNow,
    claim: C.fnNow,
    formula: call("hoursBetween", "{start}", call("now", "{start}")),
    shape: MIXED,
    values: {},
    expected: refused("check", "wrong-argument-count", ["now"]),
  },
  {
    name: "contains given one argument is refused",
    group: "functions",
    from: L.fnContains,
    claim: C.fnContains,
    formula: call("contains", "{tags}"),
    shape: MIXED,
    values: {},
    expected: refused("check", "wrong-argument-count", ["contains"]),
  },
  {
    name: "has word given one argument is refused",
    group: "functions",
    from: L.fnHasWord,
    claim: C.fnHasWord,
    formula: call("hasWord", "{name}"),
    shape: NAME,
    values: {},
    expected: refused("check", "wrong-argument-count", ["hasWord"]),
  },
  {
    name: "hours between given a number is refused",
    group: "functions",
    from: L.fnHoursBetween,
    claim: C.fnHoursBetween,
    formula: call("hoursBetween", "{start}", "{count}"),
    shape: MIXED,
    values: {},
    expected: refused("check", "types-do-not-meet", ["count", "number", "instant"]),
  },
  {
    name: "contains given something other than a list is refused",
    group: "functions",
    from: L.fnContains,
    claim: C.fnContains,
    formula: call("contains", "{name}", '"a"'),
    shape: NAME,
    values: { name: text("astra") },
    expected: refused("check", "types-do-not-meet", ["name", "text"]),
  },
  {
    name: "contains looking for a value of a different kind than the list holds",
    group: "functions",
    from: L.fnContains,
    claim: C.fnContains,
    formula: call("contains", "{tags}", "3"),
    shape: MIXED,
    values: {},
    expected: refused("check", "types-do-not-meet", ["tags", "text", "number"]),
  },
  {
    name: "has word given a number is refused",
    group: "functions",
    from: L.fnHasWord,
    claim: C.fnHasWord,
    formula: call("hasWord", "{count}", '"3"'),
    shape: MIXED,
    values: {},
    expected: refused("check", "types-do-not-meet", ["count", "number", "text"]),
  },
  {
    name: "has word given a number as its word is refused",
    group: "functions",
    from: L.fnHasWord,
    claim: C.fnHasWord,
    formula: call("hasWord", "{name}", "3"),
    shape: MIXED,
    values: {},
    expected: refused("check", "types-do-not-meet", ["number", "text"]),
  },
  {
    name: "a function name without a call is not a word standing for a value",
    group: "functions",
    from: L.callSpelling,
    claim: C.callSpelling,
    formula: "now",
    shape: NOTHING,
    values: {},
    expected: refused("read", "unknown-word", ["now"]),
  },
  {
    name: "a call written without its parentheses is refused",
    group: "functions",
    from: L.callSpelling,
    claim: C.callSpelling,
    formula: 'hasWord {name} "cat"',
    shape: NAME,
    values: { name: text("the cat sat") },
    expected: refused("read", "unreadable"),
  },
  {
    name: "hours between two instants with the later one first is not negative",
    group: "functions",
    from: L.fnHoursBetween,
    claim: C.fnHoursBetween,
    formula: call("hoursBetween", "{finish}", "{start}"),
    shape: MIXED,
    values: {
      start: instant("2026-01-01T00:00:00Z"),
      finish: instant("2026-01-01T05:00:00Z"),
    },
    expected: answersNumber(5),
  },
  {
    name: "hours between with the later one first, fractional",
    group: "functions",
    from: L.fnHoursBetween,
    claim: C.fnHoursBetween,
    formula: call("hoursBetween", "{finish}", "{start}"),
    shape: MIXED,
    values: {
      start: instant("2026-01-01T00:00:00Z"),
      finish: instant("2026-01-01T01:30:00Z"),
    },
    expected: answersNumber(1.5),
  },
  {
    name: "hours between answers the same whichever instant is given first",
    group: "functions",
    from: L.fnHoursBetween,
    claim: C.fnHoursBetween,
    formula: `${call("hoursBetween", "{start}", "{finish}")} == ${call("hoursBetween", "{finish}", "{start}")}`,
    shape: MIXED,
    values: {
      start: instant("2026-01-01T00:00:00Z"),
      finish: instant("2026-01-01T05:00:00Z"),
    },
    expected: answersBoolean(true),
  },
  {
    name: "has word folds the case of the text",
    group: "functions",
    from: L.fnHasWord,
    claim: C.fnHasWord,
    formula: call("hasWord", '"Green fields"', '"green"'),
    shape: NOTHING,
    values: {},
    expected: answersBoolean(true),
  },
  {
    name: "has word folds the case of the word",
    group: "functions",
    from: L.fnHasWord,
    claim: C.fnHasWord,
    formula: call("hasWord", '"green fields"', '"GREEN"'),
    shape: NOTHING,
    values: {},
    expected: answersBoolean(true),
  },
  {
    name: "a hyphen bounds a word",
    group: "functions",
    from: L.fnHasWord,
    claim: C.fnHasWord,
    formula: call("hasWord", '"A-green-B"', '"green"'),
    shape: NOTHING,
    values: {},
    expected: answersBoolean(true),
  },
  {
    name: "an underscore bounds a word",
    group: "functions",
    from: L.fnHasWord,
    claim: C.fnHasWord,
    formula: call("hasWord", '"a_green_b"', '"green"'),
    shape: NOTHING,
    values: {},
    expected: answersBoolean(true),
  },
  {
    name: "a digit does not bound a word",
    group: "functions",
    from: L.fnHasWord,
    claim: C.fnHasWord,
    formula: call("hasWord", '"green9 fields"', '"green"'),
    shape: NOTHING,
    values: {},
    expected: answersBoolean(false),
  },
]
