import type { SetTemplate } from "@akasha/temper-equipment/set-template"

export const SETS_DATA_066: readonly SetTemplate[] = [
  {
    id: "orpheon-the-tactician",
    name: "Orpheon the Tactician",
    esoSetId: 801,
    subcategoryId: "no-type",
    valid: ["monster"],
    bonuses: [
      {
        count: 1,
        status: "supported",
        effects: [{ metricId: "power", effectType: "integer", effectValue: 129 }],
        description: "Adds 129 Weapon and Spell Damage",
      },
      {
        count: 2,
        status: "unsupported",
        effects: [],
        description:
          "While in combat, casting an ability that leaves an effect on the ground summons a tentacle at the target's location. After 2 seconds, the tentacle swings wildly in a 5 meter radius, dealing 229 Physical damage and stunning up to 6 enemies for 3 seconds. Enemies immune to stun take 1429 Physical damage instead. This effect can occur every 8 seconds and the damage scales off the higher of your Weapon or Spell Damage.",
      },
    ],
    icons: {
      "head:heavy": "/esoui/art/icons/gear_undremanimp_head_a.dds",
      "head:light": "/esoui/art/icons/gear_undremanimp_head_a.dds",
      "head:medium": "/esoui/art/icons/gear_undremanimp_head_a.dds",
      "shoulders:heavy": "/esoui/art/icons/gear_undremanimp_shoulders_a.dds",
      "shoulders:light": "/esoui/art/icons/gear_undremanimp_shoulders_a.dds",
      "shoulders:medium": "/esoui/art/icons/gear_undremanimp_shoulders_a.dds",
    },
  },
  {
    id: "overwhelming-surge",
    name: "Overwhelming Surge",
    esoSetId: 193,
    subcategoryId: "dungeon",
    valid: ["*:light"],
    bonuses: [
      {
        count: 2,
        status: "supported",
        effects: [{ metricId: "magicka-maximum", effectType: "integer", effectValue: 1096 }],
        description: "Adds 1096 Maximum Magicka",
      },
      {
        count: 3,
        status: "supported",
        effects: [{ metricId: "power", effectType: "integer", effectValue: 129 }],
        description: "Adds 129 Weapon and Spell Damage",
      },
      {
        count: 4,
        status: "supported",
        effects: [{ metricId: "power", effectType: "integer", effectValue: 129 }],
        description: "Adds 129 Weapon and Spell Damage",
      },
      {
        count: 5,
        status: "unsupported",
        effects: [],
        description:
          "When you deal damage with a Class ability, you surround yourself with a torrent that deals 149 Shock damage to enemies within 8 meters of you every 1 second for 6 seconds. 15% of the damage you deal this way is restored to you as Magicka. This effect can occur every 7 seconds and scales off the higher of your Weapon or Spell Damage.",
      },
    ],
    icons: {
      "axe": "/esoui/art/icons/gear_ancient_elf_1haxe_c.dds",
      "battleaxe": "/esoui/art/icons/gear_ancient_elf_2haxe_c.dds",
      "bow": "/esoui/art/icons/gear_ancient_elf_bow_c.dds",
      "chest:*": "/esoui/art/icons/gear_breton_light_robe_d.dds",
      "dagger": "/esoui/art/icons/gear_ancient_elf_dagger_c.dds",
      "feet:*": "/esoui/art/icons/gear_breton_light_feet_d.dds",
      "greatsword": "/esoui/art/icons/gear_ancient_elf_2hsword_c.dds",
      "hands:*": "/esoui/art/icons/gear_breton_light_hands_d.dds",
      "head:*": "/esoui/art/icons/gear_breton_light_head_d.dds",
      "ice-staff": "/esoui/art/icons/gear_ancient_elf_staff_c.dds",
      "inferno-staff": "/esoui/art/icons/gear_ancient_elf_staff_c.dds",
      "legs:*": "/esoui/art/icons/gear_breton_light_legs_d.dds",
      "lightning-staff": "/esoui/art/icons/gear_altmer_staff_d.dds",
      "mace": "/esoui/art/icons/gear_ancient_elf_1hhammer_c.dds",
      "maul": "/esoui/art/icons/gear_ancient_elf_2hhammer_c.dds",
      "necklace": "/esoui/art/icons/gear_breton_neck_a.dds",
      "restoration-staff": "/esoui/art/icons/gear_ancient_elf_staff_c.dds",
      "ring": "/esoui/art/icons/gear_breton_ring_a.dds",
      "shield": "/esoui/art/icons/gear_ancient_elf_shield_c.dds",
      "shoulders:*": "/esoui/art/icons/gear_breton_light_shoulders_d.dds",
      "sword": "/esoui/art/icons/gear_ancient_elf_1hsword_c.dds",
      "waist:*": "/esoui/art/icons/gear_breton_light_waist_d.dds",
    },
  },
  {
    id: "ozezan-the-inferno",
    name: "Ozezan the Inferno",
    esoSetId: 687,
    subcategoryId: "monster",
    valid: ["monster"],
    bonuses: [
      {
        count: 1,
        status: "supported",
        effects: [{ metricId: "magicka-recovery", effectType: "integer", effectValue: 129 }],
        description: "Adds 129 Magicka Recovery",
      },
      {
        count: 2,
        status: "unsupported",
        effects: [],
        description:
          "Overhealing yourself or an ally grants them 4272 Armor for 1.1 seconds. Healing yourself or an ally grants them Minor Vitality for 1.1 seconds, increasing their healing received and damage shield strength by 6%.",
      },
    ],
    icons: {
      "head:heavy": "/esoui/art/icons/gear_undinfernium_head_a.dds",
      "head:light": "/esoui/art/icons/gear_undinfernium_head_a.dds",
      "head:medium": "/esoui/art/icons/gear_undinfernium_head_a.dds",
      "shoulders:heavy": "/esoui/art/icons/gear_undinfernium_shoulder_a.dds",
      "shoulders:light": "/esoui/art/icons/gear_undinfernium_shoulder_a.dds",
      "shoulders:medium": "/esoui/art/icons/gear_undinfernium_shoulder_a.dds",
    },
  },
  {
    id: "pangrit-denmother",
    name: "Pangrit Denmother",
    esoSetId: 663,
    subcategoryId: "dungeon",
    valid: ["*:heavy"],
    bonuses: [
      {
        count: 2,
        status: "supported",
        effects: [
          { metricId: "healing-taken-base", effectType: "fractional-change", effectValue: 0.04 },
        ],
        description: "Adds 4% Healing Taken",
      },
      {
        count: 3,
        status: "supported",
        effects: [{ metricId: "resistance", effectType: "integer", effectValue: 743 }],
        description: "Adds 1487 Armor",
      },
      {
        count: 4,
        status: "supported",
        effects: [{ metricId: "health-recovery", effectType: "integer", effectValue: 129 }],
        description: "Adds 129 Health Recovery",
      },
      {
        count: 5,
        status: "supported",
        effects: [{ metricId: "stamina-maximum", effectType: "integer", effectValue: 1890 }],
        description: "Adds 1890 Maximum Stamina",
      },
      {
        count: 5,
        status: "unsupported",
        effects: [],
        description:
          "When you Block, you and up to 3 group members within 12 meters gain Minor Courage for 10 seconds, increasing your Weapon and Spell Damage by 215. This effect can occur once every 5 seconds.",
      },
    ],
    icons: {
      "axe": "/esoui/art/icons/gear_shipwreck_1haxe_a.dds",
      "battleaxe": "/esoui/art/icons/gear_shipwreck_2haxe_a.dds",
      "bow": "/esoui/art/icons/gear_shipwreck_bow_a.dds",
      "chest:*": "/esoui/art/icons/gear_shipwreck_heavy_chest_a.dds",
      "dagger": "/esoui/art/icons/gear_shipwreck_dagger_a.dds",
      "feet:*": "/esoui/art/icons/gear_shipwreck_heavy_feet_a.dds",
      "greatsword": "/esoui/art/icons/gear_shipwreck_2hsword_a.dds",
      "hands:*": "/esoui/art/icons/gear_shipwreck_heavy_hands_a.dds",
      "head:*": "/esoui/art/icons/gear_shipwreck_heavy_head_a.dds",
      "ice-staff": "/esoui/art/icons/gear_shipwreck_staff_a.dds",
      "inferno-staff": "/esoui/art/icons/gear_shipwreck_staff_a.dds",
      "legs:*": "/esoui/art/icons/gear_shipwreck_heavy_legs_a.dds",
      "lightning-staff": "/esoui/art/icons/gear_shipwreck_staff_a.dds",
      "mace": "/esoui/art/icons/gear_shipwreck_1hhamer_a.dds",
      "maul": "/esoui/art/icons/gear_shipwreck_2hhammer_a.dds",
      "necklace": "/esoui/art/icons/gear_breton_neck_a.dds",
      "restoration-staff": "/esoui/art/icons/gear_shipwreck_staff_a.dds",
      "ring": "/esoui/art/icons/gear_breton_ring_a.dds",
      "shield": "/esoui/art/icons/gear_shipwreck_shield_a.dds",
      "shoulders:*": "/esoui/art/icons/gear_shipwreck_heavy_shoulder_a.dds",
      "sword": "/esoui/art/icons/gear_shipwreck_sword_a.dds",
      "waist:*": "/esoui/art/icons/gear_shipwreck_heavy_waist_a.dds",
    },
  },
  {
    id: "para-bellum",
    name: "Para Bellum",
    esoSetId: 214,
    subcategoryId: "arena",
    valid: ["*:medium"],
    bonuses: [
      {
        count: 2,
        status: "supported",
        effects: [{ metricId: "stamina-maximum", effectType: "integer", effectValue: 1096 }],
        description: "Adds 1096 Maximum Stamina",
      },
      {
        count: 3,
        status: "supported",
        effects: [{ metricId: "health-maximum", effectType: "integer", effectValue: 1206 }],
        description: "Adds 1206 Maximum Health",
      },
      {
        count: 4,
        status: "supported",
        effects: [{ metricId: "stamina-maximum", effectType: "integer", effectValue: 1096 }],
        description: "Adds 1096 Maximum Stamina",
      },
      {
        count: 5,
        status: "unsupported",
        effects: [],
        description:
          "When you deal damage you gain a damage shield that absorbs up to 8412 damage for 6 seconds.  This effect can occur once every 6 seconds.",
      },
    ],
    icons: {
      "axe": "/esoui/art/icons/gear_trinimac_1haxe_a.dds",
      "battleaxe": "/esoui/art/icons/gear_trinimac_2haxe_a.dds",
      "bow": "/esoui/art/icons/gear_trinimac_bow_a.dds",
      "chest:*": "/esoui/art/icons/gear_trinimac_medium_chest_a.dds",
      "dagger": "/esoui/art/icons/gear_trinimac_dagger_a.dds",
      "feet:*": "/esoui/art/icons/gear_trinimac_medium_feet_a.dds",
      "greatsword": "/esoui/art/icons/gear_trinimac_2hsword_a.dds",
      "hands:*": "/esoui/art/icons/gear_trinimac_medium_hands_a.dds",
      "head:*": "/esoui/art/icons/gear_trinimac_medium_head_a.dds",
      "ice-staff": "/esoui/art/icons/gear_trinimac_staff_a.dds",
      "inferno-staff": "/esoui/art/icons/gear_trinimac_staff_a.dds",
      "legs:*": "/esoui/art/icons/gear_trinimac_medium_legs_a.dds",
      "lightning-staff": "/esoui/art/icons/gear_trinimac_staff_a.dds",
      "mace": "/esoui/art/icons/gear_trinimac_1hhammer_a.dds",
      "maul": "/esoui/art/icons/gear_trinimac_2hhammer_a.dds",
      "necklace": "/esoui/art/icons/gear_breton_neck_a.dds",
      "restoration-staff": "/esoui/art/icons/gear_trinimac_staff_a.dds",
      "ring": "/esoui/art/icons/gear_breton_ring_a.dds",
      "shield": "/esoui/art/icons/gear_trinimac_shield_a.dds",
      "shoulders:*": "/esoui/art/icons/gear_trinimac_medium_shoulders_a.dds",
      "sword": "/esoui/art/icons/gear_trinimac_1hsword_a.dds",
      "waist:*": "/esoui/art/icons/gear_trinimac_medium_waist_a.dds",
    },
  },
  {
    id: "peace-and-serenity",
    name: "Peace and Serenity",
    esoSetId: 701,
    subcategoryId: "trial",
    valid: ["*:light"],
    bonuses: [
      {
        count: 2,
        status: "supported",
        effects: [{ metricId: "critical-rating", effectType: "integer", effectValue: 657 }],
        description: "Adds 657 Critical Chance",
      },
      {
        count: 3,
        status: "unsupported",
        effects: [],
        description:
          "Gain Minor Slayer at all times, increasing your damage done to Dungeon, Trial, and Arena Monsters by 5%.",
      },
      {
        count: 4,
        status: "supported",
        effects: [{ metricId: "power", effectType: "integer", effectValue: 129 }],
        description: "Adds 129 Weapon and Spell Damage",
      },
      {
        count: 5,
        status: "unsupported",
        effects: [],
        description:
          "While you are standing still, you gain 465 Weapon and Spell Damage. While you are moving, you gain 203 Health, Magicka, and Stamina Recovery.",
      },
    ],
    icons: {
      "axe": "/esoui/art/icons/gear_clandreamcarver_1haxe_a.dds",
      "battleaxe": "/esoui/art/icons/gear_clandreamcarver_2haxe_a.dds",
      "bow": "/esoui/art/icons/gear_clandreamcarver_bow_a.dds",
      "chest:*": "/esoui/art/icons/gear_clandreamcarver_light_robe_a.dds",
      "dagger": "/esoui/art/icons/gear_clandreamcarver_dagger_a.dds",
      "feet:*": "/esoui/art/icons/gear_clandreamcarver_light_feet_a.dds",
      "greatsword": "/esoui/art/icons/gear_clandreamcarver_2hsword_a.dds",
      "hands:*": "/esoui/art/icons/gear_clandreamcarver_light_hands_a.dds",
      "head:*": "/esoui/art/icons/gear_clandreamcarver_light_head_a.dds",
      "ice-staff": "/esoui/art/icons/gear_clandreamcarver_staff_a.dds",
      "inferno-staff": "/esoui/art/icons/gear_clandreamcarver_staff_a.dds",
      "legs:*": "/esoui/art/icons/gear_clandreamcarver_light_legs_a.dds",
      "lightning-staff": "/esoui/art/icons/gear_clandreamcarver_staff_a.dds",
      "mace": "/esoui/art/icons/gear_clandreamcarver_1hhammer_a.dds",
      "maul": "/esoui/art/icons/gear_clandreamcarver_2hhammer_a.dds",
      "necklace": "/esoui/art/icons/gear_breton_neck_a.dds",
      "restoration-staff": "/esoui/art/icons/gear_clandreamcarver_staff_a.dds",
      "ring": "/esoui/art/icons/gear_breton_ring_a.dds",
      "shield": "/esoui/art/icons/gear_clandreamcarver_shield_a.dds",
      "shoulders:*": "/esoui/art/icons/gear_clandreamcarver_light_shoulders_a.dds",
      "sword": "/esoui/art/icons/gear_clandreamcarver_1hsword_a.dds",
      "waist:*": "/esoui/art/icons/gear_clandreamcarver_light_waist_a.dds",
    },
  },
]
