import type { Finding } from "../finding.page-type.ts"

export const aBarePartOfSlugIsQualifiedWithThePageTypeItsReferrersAlreadyReach = {
  id: "01a06924-02b7-7744-97a3-26c7f871b3fc",
  pageTypeSlug: "finding",
  slug: "a-bare-part-of-slug-is-qualified-with-the-page-type-its-referrers-already-reach",
  domainSlug: "domain/akasha-migration",
  claim:
    "A `part-of-slugs` value written bare is refused wherever a book series and a story read, or a game and a story played, share a name, and 5,022 references were refused this way at the last index refresh. Which page type a referrer means is settled by the references from that page type that already resolve rather than by guessing: every story chapter read, book, story turn played and story chapter played whose reference resolves lands on one page type, and the ambiguous ones were qualified with that page type. Where a module slug is held by two unrelated modules, the one with fewer readers is prefixed with what owns it, as `jenny-capacitor-bridge` and `alan-nav-icon-svg` already are.",
  evidence:
    "Measured 2026-09-03 over the pages read straight off disk, with the repository's own `reaches` deciding each value, and seeded before it was believed: a second `module/reaching` page raised the count by one and a `story-read` page slugged `delve` raised it by 273, and taking both away returned it to 5,031.\n\nOf the 5,031 ambiguity refusals, 5,022 were `part-of-slugs` and 9 were `part-slugs`. The referrers were story-chapter-read 4,486, book 358, story-turn-played 139, story-chapter-played 27, and 12 pages naming `sword-art-online`, which four pages carry: a book, a fandom, a franchise and a show.\n\nWhat settles each: 14,438 story-chapter-read references already resolve and every one lands on a story-read; 3 book references resolve and every one lands on a book-series; 13 story-turn-played and 96 story-chapter-played references resolve and every one lands on a story-played, and no reference in the tree lands on a game. A second arm the ambiguity census cannot see: 4,205 of the story chapters carry a `source` equal to the story-read's and unequal to the book-series', and 0 disagree; and all 5,010 target slugs are a prefix of the referring page's own slug. The census alone could not tell a right page type from a wrong one, since either candidate resolves once named: a deliberately wrong mapping also left 9 refusals.\n\nFor `sword-art-online`, seasons were qualified `show/`, as the other 665 season references are; movies, shows and the two collections were qualified `fandom/`, as 239 references already are, while nothing in the tree names a franchise and one franchise page exists.\n\nLanded in 13 mechanical commits, 7404d54d87 through 7f0d79b8db, 5,022 files. The census afterward read 9, all `part-slugs`.\n\nThe nine module and shell-script collisions: `answer-page-types`, `answer-pages` and `format-relative-time` under temper-web were the same code as the declared copy under `web-page-answers` or `format-time-ago`, byte for byte or differing only in the exported name, and went with their readers repointed. `nav-icon-svg` under temper-web was the pre-generalisation body at the stroke width the package defaults to, and went the same way, with its color grant. `push-registration-sync`, `population-bound` and `bash-env` were unrelated pairs: Alan's push component routes a tap and signs its request while Jenny's does neither; the cluster-checks bound reports unexaminable and never-arrived members while the temper one reports a count; the provisioning bash-env finds the repo then sources the harness one. Each was renamed with an owner prefix: `jenny-push-registration-sync`, `cluster-population-bound`, `provisioning-bash-env`. `answer-page-write` under temper-web is the same route pre-generalisation; its change is prepared and not landed, since a peer lane is repointing the write road.",
} as const satisfies Finding
