import type { Finding } from "../finding.page-type.ts"

export const aDeadDetachedLoopReportsNothingAndNothingReadsAsNoWorkFound = {
  id: "01a0683c-738a-72d3-9c6e-a34511cb9b99",
  pageTypeSlug: "finding",
  slug: "a-dead-detached-loop-reports-nothing-and-nothing-reads-as-no-work-found",
  domainSlug: "domain/akasha-migration",
  claim:
    "A detached loop that dies stops writing, and a loop that finds no work also stops writing. The two are the same silence. A lane watching such a loop reads the silence as `nothing to do` and reports a block as quiet when the instrument watching it is dead. Any long-running detached loop needs a liveness line distinguishable from a null result, and something that notices when the line stops.",
  evidence:
    "Measured on 2026-09-03 migrating `pages/page-property-definition`. I ran a poller detached that re-censused the folder every 90 seconds and landed whatever had become migratable as page types arrived from another lane. It logged one line per round whether or not it found work, which I thought was enough.\n\nIt died after round 7. `ps aux | grep poll.sh` returned 0. The log's last line was an ordinary round-7 census with no error, no exit code and no truncation — indistinguishable from a round that found nothing.\n\nI did not detect it from the log. I detected it because a file count moved without a matching log line: the block held 1,062 files when the last logged round had said 1,086, and I had ablated nothing in between. The 24 files had gone to a co-writing lane's commit. Had that lane not been working my folder, the count would have sat still, the silence would have been consistent with `no work found`, and I would have reported the block quiet with the poller dead for the rest of the session.\n\nThis is the same shape as a parser fault I had fixed an hour earlier, one level up. There a list parser returned the right answer for the wrong reason and a false negative and a true negative were the same string; here a dead process and an idle process are the same string. Both were caught by an outside observation rather than by reading the instrument's own output, which is the only thing that can catch either.\n\nWhat I did: restarted it under a monitor watching the log for the lines that mean work happened, so a stall now surfaces as an absence of expected events rather than as ordinary quiet. That is a weaker guard than a heartbeat the reader checks the age of, which is what I would build with more time. The general shape holds past this migration: silence is not success, and a loop nobody is watching is not running.",
} as const satisfies Finding
