import type { Finding } from "../finding.page-type.ts"

export const aFileWithNoExportsAndNoImportersIsRunByPathEveryTurn = {
  id: "01a0687e-5372-7000-9c4e-1b8c2f3d4a55",
  pageTypeSlug: "finding",
  slug: "a-file-with-no-exports-and-no-importers-is-run-by-path-every-turn",
  domainSlug: "domain/akasha-migration",
  claim:
    "Swarm guidance tells workers that a file exporting nothing is usually a re-export shim and so among the most certainly ablatable files in a block. In the seat block that reading is inverted: the two files scoring zero exports and zero importers are the two that are executed, by path, on a schedule. An export census and an importer census are the same instrument pointed twice, and a script is invisible to both because a script is not imported and exports nothing by design.",
  evidence:
    "Measured 2026-09-03 over the 38 flat `tools/lib/seat-[o-z]*.ts` files. Exactly two score zero on `export (function|const|type|class|interface)`: `tools/lib/seat-usage-keep.ts` (9 lines) and `tools/lib/seat-usage-show.ts` (19 lines). Exactly the same two score zero inbound importers across the tracked tree.\n\nBoth are executed by a path built at runtime. `akasha/code-system/shell-scripts/pages/statusline/statusline.shell-script.shell.sh` line 32 pipes the statusline payload into ``\"$HERE/lib/seat-usage-keep.ts\"`` — once per turn per seat — and ends the line `>/dev/null 2>&1 || true`. `akasha/machines/provisioning/scripts/ci-cost-snapshot/ci-cost-snapshot.shell-script.shell.sh` line 26 runs ``\"$TOOLS/lib/seat-usage-show.ts\"``. Neither caller reports a missing file, so ablating either would have stopped the model and context-window readings being recorded for every seat, silently.\n\nThe shape generalises past these two. A file that exports nothing is either a re-export shim, which is safe to ablate, or an entrypoint, which is the least safe file in the block; the export census cannot tell them apart, and neither can the importer census, because the two cases score identically on both. What tells them apart is one line of the body: a shim's body is `export ... from`, an entrypoint's body reads `process.argv`. Both of these read `process.argv[2]`.\n\nThis bears on the guidance rather than on the two files. Two censuses agreeing is not corroboration where both censuses are blind the same way, and 'scores zero on every instrument I have' is the reading an entrypoint produces.",
} as const satisfies Finding
