import type { Finding } from "../finding.page-type.ts"

export const aGeneratedTableLostAnOrderWithoutLosingAValue = {
  id: "01a06197-c81d-790f-9ebc-46f6d81e215e",
  pageTypeSlug: "finding",
  slug: "a-generated-table-lost-an-order-without-losing-a-value",
  domainSlug: "domain/temper",
  claim:
    "A migration can keep every value of a list and lose the sequence. `temper-grimoire` carries `compatibleSignatureScripts` and `compatibleAffixScripts` for twelve grimoires. Every id came across and no sequence did: the rows behind each array were written sorted by length and then alphabetically, while the table on disk holds the authored sequence. Building the arrays from the rows would emit twenty-four reordered lists and report success.",
  evidence:
    "Measured 2026-09-02 driving `buildAddonDataWrites` one section at a time over the real pages.\n\nThe `skills` section throws at its second write. `generateTemperGrimoire` asks for `compatibleFocusScripts`, `compatibleSignatureScripts` and `compatibleAffixScripts`; the page carries `focusScripts`, `signatureScripts` and `affixScripts`. The first is a plain array and matches the checked-in table for all twelve grimoires, sequence included. The other two arrive as rows through `withSidecars`, which builds a record in row order.\n\nComparing that row order against `temper/game-characters-skills/src/generated/temper-grimoire.generated.ts`: twelve arrays identical, twenty-four differing, zero differing by membership. Every id is present on both sides.\n\nThe row order is derived rather than authored. `vault.temper-grimoire.affix-scripts.jsonl` reads maim, force, berserk, evasion, lifesteal, expedition, off-balance, vulnerability, brutality-and-sorcery, savagery-and-prophecy, intellect-and-endurance, which is that set sorted by length and then alphabetically. The table on disk reads off-balance, savagery-and-prophecy, expedition, evasion, berserk, brutality-and-sorcery, intellect-and-endurance, force, vulnerability, maim, lifesteal, which is no sort at all. So the authored sequence lives only in the generated file.\n\nThe one consumer is `getGrimoireCompatibleScripts` at `temper/game-characters-skills/src/scribing/grimoires-data.ts:40-52`, which hands the three arrays out whole. Nothing indexes them, so no wire index moves. What moves is the order a script picker offers.\n\nThe generator is correct and is left throwing. A throw naming a missing field is louder than a table quietly rebuilt in the wrong sequence, and the sequence is recoverable from the file on disk. Mending this is page work rather than generator work.",
} as const satisfies Finding
