import type { Finding } from "../finding.page-type.ts"

export const aGeneratorReadingARenamedFieldEmptiesTheColumn = {
  id: "01a0611d-19bb-7ee9-804c-a4d97b6c1de3",
  pageTypeSlug: "finding",
  slug: "a-generator-reading-a-renamed-field-empties-the-column",
  domainSlug: "domain/temper",
  claim:
    "The `temper-companion-trait` generator reads `row.effectType`, and its page type declares that field as `type`. Zod's `.default(null)` swallows the absent key, so a regeneration succeeds and writes `effectType: null` on all nine real companion traits. `getCompanionTraitMetricEffect` gates on that null, so every companion trait would silently contribute zero. The file on disk is correct and the generator is the stale party.",
  evidence:
    "Measured 2026-09-02 by `tools/w-companion-proof.ts`, which runs each of the fifteen generators named by `tools/lib/temper-addon-data/writes-companions.ts` against the live pages and compares to disk. Twelve reproduce byte for byte. `temper-companion-trait.generated.ts` does not: disk 4199 characters, regenerated 4003, and the whole difference is `effectType` falling from `fractional-change` or `integer` to null on aggressive, augmented, bolstered, focused, prolific, quickened, shattering, soothing and vigorous.\n\nThe cause is a name. `temper-companion-trait.page-type.ts:10` declares `type?: EffectType` and every trait page carries `type`. The generator at `temper-addon-generators/temper-companion-trait/temper-companion-trait.module.code.ts:47` passes `row.effectType` into a zod field that is `.nullable().default(null)`. An absent key is no parse error, so nothing throws and the run reports success.\n\nThis is the third shape in one family and the dangerous one. Two generators want fields their page types dropped and throw at the zod parse, which is loud. `skill-mappings.generated.ts` is written by nothing and carries a wire order about 66 index assignments away from live, which at least leaves a file nobody claims. This one runs clean and empties a column.\n\nTwo further faults block `ops temper addon-data generate` outright. `catalog-sidecars.ts:74` asks the store for page types `temper-metric-effect`, `temper-quality-value` and `temper-grimoire-script`; no page type carries those slugs, the store answers 400, and `fetchAddonDataPages` throws before any generator runs. The select list at `addon-data-pages.ts:22` names `castConditions`, which `temper-companion-skill` no longer declares.\n\nThe call taken: the tables landed in `temper-companions-core` inline the bytes on disk, each carrying a departure saying so and a gap saying the generator cannot reproduce them.",
} as const satisfies Finding
