import type { Finding } from "../finding.page-type.ts"

export const aLegacyPackagePageComesDownWithItsPackageRatherThanOutlivingIt = {
  id: "01a06356-a962-7cb0-8f1f-2fc971785d7c",
  pageTypeSlug: "finding",
  slug: "a-legacy-package-page-comes-down-with-its-package-rather-than-outliving-it",
  domainSlug: "domain/temper",
  claim:
    "A page under `pages/package/` is deleted in the same change that ablates the package it names, because the akasha twin's own workspace-package page is that record in the new paradigm. Two seats took opposite calls on this in one night and this settles it for deletion. One exception is measured rather than supposed: four of the 23 temper pages carry a name that is also an akasha twin's directory, and those are checked against the twin first.",
  evidence:
    "Measured at `2ef5c16ee5`: 51 tracked `.md` pages under `pages/package/`, of which 23 name a temper package, and 19 of those 23 name one still tracked under `temper/`. A seat reported the population as 59 and as naming legacy packages only; both are wrong. It was 55 at `332ccc4e98`, so the count moves as ablations run and any figure needs its commit. Four page names — `temper-player-completion`, `temper-player-completion-ui`, `temper-player-completion-skills-morphs-ui`, `temper-player-profile` — are exactly the names of directories under `akasha/temper`, of the 143 there. For those four the slug is ambiguous between the legacy package and its twin, so a deletion taken on the rule alone removes a record that reads as the twin's. One seat deleted `temper-game-combat-addon` alongside its package at `f8f7c0025d`. Another left `temper-game-characters-equipment` and `temper-shared-interface-interface-addon`, reasoning that each is a concept record carrying a slug and no repository path, so neither is a dangling reference and deleting it loses a record whose subject survives. That reasoning is right about the mechanism and wrong about the subject: the concept survives as the twin's page under `akasha/temper`, a page in the current system rather than a record in the one being replaced, and the constraint that temper is recreated in the new paradigms rather than carried across decides it. A page left behind is not inert prose either. `pages/package/` is one of the eight reference sites an ablation census reads, and a stale one misleads the next census: `temper-scripts.package.md` still defines that package as loose command-line scripts after two ablations removed the last one, and `pages/domain/ops-temper.domain.md:17` links it.",
} as const satisfies Finding
