import type { Finding } from "../finding.page-type.ts"

export const aMalformedOptionalMarkerInTstlEsoSandboxBarsTheLuaStringLibrary = {
  id: "01a060ab-ec71-74ab-8f68-81c112b6248d",
  pageTypeSlug: "finding",
  slug: "a-malformed-optional-marker-in-tstl-eso-sandbox-bars-the-lua-string-library",
  domainSlug: "workspace-package/temper-eso-types",
  claim:
    "Fifteen members of `LuaMetatable` in `tstl-eso-sandbox` carry a second `?` after the colon, which TypeScript does not parse. Importing that one subpath answers 51 parse errors, and `skipLibCheck` does not quiet them, because a parse error is not a type error. The Lua `string` library and `tonumber` are declared in that same file and nowhere else, so no akasha module may reach `string.len` today.",
  evidence:
    "`akasha/temper/temper-eso-types/tstl-eso-sandbox/tstl-eso-sandbox.type-declaration.d.ts` lines 9 to 27 read `__add?: ?(this: T, operand: unknown) => unknown` and the same shape for `__sub`, `__mul`, `__div`, `__mod`, `__pow`, `__unm`, `__concat`, `__len`, `__eq`, `__lt`, `__le`, `__call`, `__tostring` and `__gc`. The `?` between the colon and the parenthesis is not TypeScript. The intended text is `__add?: (this: T, operand: unknown) => unknown`, or the typescript-to-lua original `__add?(this: T, operand: unknown): unknown`.\n\nMeasured with `@typescript/native-preview`: a scratch file importing only this subpath answers 51 errors, all `TS1005`, `TS1109`, `TS1128` and `TS1131`. The parser recovers far enough that `string.len` and `tonumber` still resolve, so the names are reachable while the build is red.\n\nEvery other declaration in the package is clean. A probe importing `eso-globals`, `eso-event-manager`, `eso-events`, `eso-functions-01`, `eso-functions-03`, `eso-enums-07`, `eso-enums-08`, `eso-enums-11`, `eso-enums-14` and `tstl-language-extensions` together typechecked with nothing to say.\n\nWhat this holds up: `temper/shared-foundation-misc-codec/src/base64url.ts` line 10 calls `string.len(str)` and is the one file of that package still outside akasha. Its three siblings need only `eso-functions-01`, `eso-enums-07`, `eso-enums-08` and `eso-enums-11`, all of which parse. `@temper/shared-narrow`'s `requireNumericKey` wraps `tonumber` from the same file, so the fold of shared-narrow waits on this too.\n\nThe fix is fifteen characters. This seat did not make it, to keep clear of the seat that owns `temper-eso-types`.",
} as const satisfies Finding
