import type { Finding } from "../finding.page-type.ts"

export const aMechanicalAblationIsTheOneLandingNothingCanBeReadBackFrom = {
  id: "01a0675b-057c-7407-819a-f4a787635d69",
  pageTypeSlug: "finding",
  slug: "a-mechanical-ablation-is-the-one-landing-nothing-can-be-read-back-from",
  domainSlug: "domain/akasha-migration",
  claim:
    "A mechanical landing of new content can be read against the content it composed, so a wrong one is recoverable by reading. A mechanical deletion composes nothing, runs no check, and leaves only the backup and a one-line commit message, so where its reason is given at folder grain there is nothing later to rebuild the per-file case from. Constraint 23 asks for a positive match per file, and for a deletion that evidence exists only while the lane still holds the mapping.",
  evidence:
    "Measured 2026-09-03. Two landings nearly cost real data by this shape within one hour.\n\nFIRST. `fb018236edaae0e25ee7e1d44b4caaf2bc2bfe0e` took away 90 files, every one a deletion, 46 under `pages/domain` and 44 under `pages/page-type`, carrying `Checks-bypassed: a change-mechanical change runs no check`. Its reason is `ablate page-type and domain metadata carried into akasha or obsolete with the markdown system`, which is a judgement about a folder. Counting arrivals rather than departures: `pages/domain` went 94 to 48 while `.domain.ts` files inside akasha held at 129, and of the 94 old slugs one is inside, the one that already matched before the work began. 44 of the 46 are the `ops-*` group, and the reason given for them is false: `tools/ops/` and `tools/commands/` are whole with a 233 to 233 bijection, so what ended was the markdown command system rather than the commands.\n\nSECOND. `pages/temper-inventory-chunk` holds 458 attachments whose pages are all inside akasha and whose bytes are not. Each page carries a `byteCount` matching its orphaned file exactly, which is what made the case provable per file. Nothing inside akasha declares a property those bytes could occupy.\n\nWHAT MAKES THE DELETION DIFFERENT. Both were mechanical and neither was judged. The second is recoverable by reading, because the composed pages are there to compare against. The first is not, because a deletion composes nothing: the only readings left are the backup and the message, and the message answers at the wrong grain.\n\nSo a mechanical ablation names where each file's content went, emitted as the ablation lands. The lane holds that mapping at the moment it composes the removals and never holds it again.\n\nBearing directly on this, `migration-reach --told` pushes to `strong` on a path existing and compares no content, so a lane feeding `--takeable` back as its removals is deleting on a path resolving.",
} as const satisfies Finding
