import type { Finding } from "../finding.page-type.ts"

export const aOneOfMemberIsRefusedForNotBeingDeclaredByAPageType = {
  id: "01a062f7-9a09-7e0b-906e-d92abaa01b06",
  pageTypeSlug: "finding",
  slug: "a-one-of-member-is-refused-for-not-being-declared-by-a-page-type",
  domainSlug: "workspace-package/checks",
  claim:
    "`property-is-declared-by-a-type` refuses a page property that pages do carry. Its one guard asks whether a page type names the property under `page-property-slug`, so a property carried through a one-of is invisible to it. It refuses `relation-property/initiative-slug` saying it is a property no page can ever carry, and 30 pages carry it as `assignmentSlug`. The sibling member `domain-slug` passes only because two page types also declare it outright, which has nothing to do with membership.",
  evidence:
    'Measured 2026-09-02 at 4db63dc250. `akasha audit --check property-is-declared-by-a-type` answers `1 check judged 30143 files, and 1 refusal in all`, against `akasha/domain-system/initiatives/properties/initiative-slug.relation-property.ts`.\n\nIt is not an unqualified name. One file in the tree carries `slug: "initiative-slug"`.\n\nThe guard is one line, `:53`, `if (shadow.index.idsNaming(id, DECLARES).length > 0) return`, where `DECLARES` is `page-property-slug` at `:13`. Nothing asks after `memberSlugs`.\n\nThe index already files what that guard does not ask for. Asked what names each member: `initiative-slug` (01a062b2-e0ca-7d66) is named under `part-slugs` by the initiative page type and under `member-slugs` by 01a053a2-d0e7, which is `assignment-slug`, and under `page-property-slug` by nothing at all. `domain-slug` (01a04a08-fcf3-7003) is named under `member-slugs` by that same `assignment-slug`, and under `page-property-slug` by two, `initiative.page-type.ts` and `finding.page-type.ts`. Both are members; only one is declared outright.\n\nThe chain the check misses is whole. `agent.page-type.ts` (01a06257-7813) declares `assignment-slug` under `page-property-slug`, `assignment-slug` names both members under `member-slugs`, and 30 pages carry an initiative that way, among them `akasha/seat-system/seat/seats/aine.seat.ts`.\n\nRequiring a member to be declared on its own would force an `initiativeSlug` property onto a page type no page carries, so the page is right and the check is wrong.\n\nThe mend is reachable through the API the check already uses: `idsNaming(id, "member-slugs")` answers `assignment-slug` for this id. Admitting a member whose naming one-of is itself declared clears this without admitting a member of a one-of nobody declares. Changing what a check refuses is Alan\'s, so nothing here is built.',
} as const satisfies Finding
