import type { Finding } from "../finding.page-type.ts"

export const aPartialWriteThroughThePagesServiceErasesEveryKeyTheCallerDidNotName = {
  id: "01a068fd-e798-75b9-ba9e-c7042eaa1523",
  pageTypeSlug: "finding",
  slug: "a-partial-write-through-the-pages-service-erases-every-key-the-caller-did-not-name",
  domainSlug: "domain/akasha-migration",
  claim:
    "`composedFor` in the pages system service composes a page body out of the values the caller hands over and out of nothing else. A caller sending a subset of a page's keys gets a body carrying that subset and the id alone, and every key the caller did not name is erased. All 36 of the old file-write sites are partial writes, so the whole-page-replace road their refusals point them at destroys data on arrival. The obvious repair is worse: a read-modify-write through `asking()` expands a property held in a file beside the page into its records, and composing that answer back writes the records inline and destroys the `jsonl` declaration. 289 of 436 page types declare such a property, so that is the majority case rather than an edge.",
  evidence:
    "Measured 2026-09-03 by calling `composedFor` directly, which is pure and writes nothing.\n\nThree arms, on real pages. `wake-day-2026-03-06` with the partial `{lastViewedAt}` composed a body carrying `id` and `lastViewedAt` alone, losing `title`, `date`, `spannedFromDayBoundary` and `completedTasks`. The control — the same page with every value named — kept every key, so the loss follows from the values being partial rather than from the function being broken. `idle-game/idle` with the same partial composed a body carrying `id` alone, losing `description`, `unitSlug`, `gameEngine` and `favoritedAt`, while `kept` routed `lastViewedAt` to the file beside the page correctly.\n\nThe mechanism is two blocks of `page-composing.module.code.ts`: the loop over the declared properties copies only the keys `named.values` carries, and the block after it carries `id` forward and nothing else.\n\nThe naive repair measured worse. `asking()` on that same `wake-day` answered `completedTasks` as an array of ten records, where the file carries the string `jsonl`. Composing that answer back wrote all ten records inline into the page body and destroyed the declaration saying those records live in a file beside the page.\n\nA census through the service's own predicate — `propertiesFrom` against `fileKeysAt`, over the ancestor chain — counts 289 of 436 page types declaring at least one property the index files as a file. Controls: `wake-day` and `agent` are counted, both known to carry one, and `invariant-kind` is not. The first run of that census answered zero for every page type and zero for the controls too, because `everyOfType` answers `{path, id}` and no `slug`, so every row had been skipped. That zero was a dead instrument rather than an absence, and only the controls told them apart.\n\nThe road that works is to merge the caller's keys over `valueAt(path, root)` — the declared value, where a property held in a file is still the string `jsonl` — and compose that. A merge naming nothing reproduces both pages byte for byte against what is on disk.\n\nThe call taken: a `merge` flag was added to the service write path rather than leaving the 36 sites blocked. The replace road is unchanged and still erases, which is what a caller stating no `merge` asks for.",
} as const satisfies Finding
