import type { Finding } from "../finding.page-type.ts"

export const aPageTypesDetailConfigHasNoHomeInAkasha = {
  id: "01a06828-198c-728d-9805-87aea5092281",
  pageTypeSlug: "finding",
  slug: "a-page-types-detail-config-has-no-home-in-akasha",
  domainSlug: "domain/akasha-migration",
  claim:
    "akasha's `page-type` carries `sequence` and `media-config` as record properties but carries neither `detail-config` nor `listing-config`, though all four sit side by side in the schema the reader parses. Six `*.page-type.detail-config.attachment.json` sidecars in `pages/page-type/` therefore have no `.ts` field to land in, while the code reading `detailConfig` is live. The home is one record property and its leaves on `page-type` itself, and it belongs to one worker rather than to each of the six sidecars' owners.",
  evidence:
    'Measured 2026-09-03. `akasha/pages-system/pages-core/schema/pages/pages.module.code.ts:178` declares `pageTypeDataSchema` with `sequence`, `listingConfig`, `detailConfig` and `mediaConfig` alongside `propertyDefinitions`. `akasha/pages-system/page-types/page-type.page-type.ts` carries `mediaConfig?: MediaConfig` and `sequence?: Sequence`, backed by `properties/media-config.record-property.ts` and `properties/sequence.record-property.ts`, and carries no field for the other two.\n\nThe configuration is read, not dead. `akasha/pages-system/pages-core/schema/detail-config/detail-config.module.code.ts` is a full zod schema with `parseDetailConfig` and `resolveDisplayKind`, `akasha/alan/web/use-mark-read-on-end/use-mark-read-on-end.module.code.ts:32` pulls `detailConfig` out of `parsePageTypeData(pageType?.properties)` for `progressPropertyId` and `lengthPropertyId`, and `content-tier.module.code.ts:14` reads `detailConfig?.bodyPropertyId`. All of them read the service row\'s `properties` blob, so nothing in the checkout supplies the value.\n\nThe six sidecars are chess-game, game, image, persona, story-chapter and story, and between them they exercise almost the whole schema: story-chapter sets `bodyPropertyId`, `display`, `frame.autoScroll.loadScroll`, `frame.edgeToEdge`, `frame.focusMode`, `fullBleed`, `lengthPropertyId`, `markReadOnEnd`, `progressPropertyId` and `showReadingProgress`; story sets `childCollection` and `header`. A property covering the family needs roughly four record properties and fourteen leaves, parallel to how `media-config` nests `audio-media` and `image-media`.\n\nNo akasha page type sets `mediaConfig` yet, so the pattern is established and unexercised, and nothing in akasha holds a `*.page-type.*.json` sidecar. The `game` sidecar was left in place rather than deleted, holding `{"display": "game"}`.',
} as const satisfies Finding
