import type { Finding } from "../finding.page-type.ts"

export const aRebuiltReaderDropsADefaultedFieldAndAbsenceReadsAsOff = {
  id: "01a06882-0672-7000-ac6d-4bd75a3cf051",
  pageTypeSlug: "finding",
  slug: "a-rebuilt-reader-drops-a-defaulted-field-and-absence-reads-as-off",
  domainSlug: "domain/akasha-migration",
  claim:
    "A rebuilt reader turns a field that defaulted to on into an optional field defaulting to off, so every page written without it takes the opposite setting. Nothing in the new tree reads wrong: the page type permits the absence, and the writer demands the field be exactly true. The defect is an absence, so grepping the field name finds nothing. Nine workstation services lost their credentials this way, and none had failed, because the units on disk were the ones the old default wrote.",
  evidence:
    "Measured 2026-09-03, repaired at 39f5e8cdbe.\n\nTHE INVERSION. The old markdown reader `tools/lib/service-project.ts:32` read `booleanField(fm, \"needs-secrets\", true)` — absent meant on. The rebuild declares `needsSecrets?` at `workstation-service.page-type.ts:14` and emits the `. ~/.secrets.env` prefix at `unit-writing.module.code.ts:60` only where it is `=== true`. Absent now means off. No commit removed it: `git log -S` shows it was never in the nine pages, written at b6e75aae6d when the services landed in akasha. The eleven services carrying it were akasha pages already, written by hand.\n\nWHY NOTHING HAD BROKEN. The units under ~/.config/systemd/user were written in August by the old writer, so all nine still carry the prefix on their ExecStart line. Pages and units disagreed and the units were right. The next `akasha service install` rewrites units from pages and would have dropped the prefix from all nine at once, with no lane's change to point at.\n\nTHE NINE: apns-push-notifier, ci-container-dispatcher, ci-container-reaper, inbox-tracking-poll, main-pipeline-creator, monarch-poll, monarch-sync, orphaned-resources-sweep, sweep-pipeline-pages.\n\nTHE INSTRUMENT, because the obvious one is blind. Reading an entrypoint's relative imports finds nothing, since akasha modules reach each other by package specifier; that reading reported zero for all forty and the zero was false. Bundling resolves the graph: `bun build --target=bun <entrypoint>` grepped for the names in ~/.secrets.env, parsed allowing a leading `export ` or the set comes back empty and every service reports clean. The controls are in the output: eleven services carry the flag and show the secret each reads, five show none.\n\nTHE SHAPE. An ablation check asks whether the new tree holds the old content. This is content the new tree holds and reads differently. A defaulted field's default is written on no page relying on it — it lives in the reader, and the reader is what gets replaced.",
} as const satisfies Finding
