import type { Finding } from "../finding.page-type.ts"

export const aReadoutAblatedInTypescriptIsStillAnsweredFromItsMarkdownTwin = {
  id: "01a06274-d2eb-7919-b8e5-37e2a37d0ef2",
  pageTypeSlug: "finding",
  slug: "a-readout-ablated-in-typescript-is-still-answered-from-its-markdown-twin",
  domainSlug: "workspace-package/readout-system",
  claim:
    "Two engines answer readout groups and neither can see the other's pages. `answerStoplightsAdmittedBy` asks the akasha store, feeding the HTTP routes and the iOS widget. `readoutCatalog` reads `*.readout.md` out of the checkout, feeding the editor status bar and the daily-points denominator. The readout page type's markdown-only `files:` glob is what parts them. So an inbox ablation reached three on the wire while the status bar answered five, and no check compares the two.",
  evidence:
    "Measured 2026-09-02 by running both rather than reading. `resolveReadoutGroup(\"inboxes\")` answered 5: inboxes-email, inboxes-tasks, inboxes-temper-tasks, inboxes-texts, inboxes-questions. `askingFor` for readouts whose `groupSlugs` has `inboxes` answered 3, the first three. `upkeep` answered 6 either way, so the disagreement is one group wide. `alan/harness/alan-harness.domain.ts:109` settles which is right: Alan's inboxes widget shows all three stoplights.\n\n`readouts/readout/readout.page-type.md:5` declares `files: akasha:**/*.readout.md`, and `readout-catalog.ts:96-111` builds its page-type table from `files:` alone. The akasha readout page type declares no such field, so the 10 TypeScript readouts are unreachable from that catalog and the 22 markdown ones are all it sees.\n\n`e0015925ad` added two tests meant for this exact failure; its message says a readout left behind by a half-finished removal is named there by its own slug. But `api.inbox-stoplights.test.ts:186` scans `**/*.readout.ts` under `akasha/` only, so the unfinished half cannot appear in it. It reported clean because it cannot see its subject. `code-outside-akasha-has-no-gate-an-agent-can-use` holds the rest: `readouts/` is committed and never judged.\n\nThe missing instrument is one check resolving each group through both engines and refusing where the member sets differ. Without it the ablation reported success, the tests were green, the wire answered three, and the status bar went on answering five.\n\n`870e74ebbc` records Alan's rule that the old pages remain, so `e5b3f47a24` marks the two `enabled: false` and removes nothing. `tools/lib/ios-widget-swift.ts:90-103` filters on `groupSlugs` and never reads `enabled`, so generated Swift still names 5 rings where the route answers 3.",
} as const satisfies Finding
