import type { Finding } from "../finding.page-type.ts"

export const aServerOnlyModuleKeepsItsBoundaryThroughADotServerDirectory = {
  id: "01a0640f-8510-7017-8dbd-776f88adb0d2",
  pageTypeSlug: "finding",
  slug: "a-server-only-module-keeps-its-boundary-through-a-dot-server-directory",
  domainSlug: "domain/temper",
  claim:
    "Temper's `*.server.ts` modules could not carry their suffix into akasha, whose grammar has one shape for a module's code. A directory recovers the boundary: the resolver matches `/.server//` too, and akasha reads a file's basename only, so a folder named `.server` satisfies both. Ten modules sit there. `.server/` is the sole exception to the ruling that temper-web modules land flat, and is meant to be: the bundler reads it, and an import announcing it crosses into server-only code is a feature.",
  evidence:
    'Verified 2026-09-02 from the resolver source after a coordinator asked that the reading be checked rather than trusted.\n\n`@react-router/dev@7.15.1`, `dist/vite.js`: 4233 `serverFileRE`, 4234 `serverDirRE = /\\/\\.server\\//`, 4235 ors them, and the only exits before the throw at 4265 are a missing importer and an `.html` importer. The akasha half is `page-file-name.module.code.ts:57`, `basename(path).split(".")`, so a directory name never reaches the grammar.\n\nReading is not firing. In `temper/web`, `root.tsx` importing a probe from `app/probe-plain/` built in 2.8s; the same file at the same import site under `app/.server/` refused with `Server-only module referenced by client`. The control is what makes the refusal mean something.\n\nA move is mechanical and runs no check, so the index was proved separately: a clean body at `.server/served-watcher-version` passed 28 checks and the same body plus `const wrongOnPurpose: number = "..."` drew `TS2322` on that path.\n\nTen slugs are behind the boundary: `answer-ask`, `answer-pages`, `answer-page-types`, `answer-page-write`, `supabase-service-client` at `215bcafe9e`, then `addons-bundle-dir`, `watcher-dir`, `served-watcher-version`, `character-import`, `companion-import` at `dd807fdb20`. Every importer of all eleven candidates is a route calling from a `loader`, which React Router strips from the client bundle, so no caller breaks and none was a live defect.\n\n`watcher-token-check` is the eleventh and is held flat. It is the only one carrying a test, and no test under a hidden folder can be run \u2014 see `a-test-inside-a-dot-server-folder-is-unreachable-by-the-test-command`.\n\nThis closes `@akasha/supabase-server`\'s own invariant, `Nothing made here is ever handed to a browser`.',
} as const satisfies Finding
