import type { Finding } from "../finding.page-type.ts"

export const aSlugReachedThroughAReExportedConstantSurvivesTheAblationGrep = {
  id: "01a06890-375b-7f98-acc4-20bf3f5c3c40",
  pageTypeSlug: "finding",
  slug: "a-slug-reached-through-a-re-exported-constant-survives-the-ablation-grep",
  domainSlug: "domain/akasha-migration",
  claim:
    "The fourth part of the ablation test — grep the slug across `tools/` and `page/` — misses a reader that names the slug through a constant defined in another file. `tools/lib/surplus-fall/tick.ts:57` asked the old registry for page type `notification` as `NOTIFICATION_PAGE_TYPE_SLUG`, imported from `payload.ts`, so grepping the slug matched only two import paths and two prose comments and never the query. Ablating the page type left that reader throwing on every fall it tried to report.",
  evidence:
    "Measured 2026-09-03. The notification repoint landed at 32da702fd4 (12:24:17) and the ablation at dbeae70a0e (12:31:02), so the ordering held: `git ls-tree -r dbeae70a0e^ -- pages` listed exactly the 13 files that commit removed, and the akasha copy stands untouched at md5 1543a14316c65f5e83432c949d487996, 2,334 rows.\n\nWhat the grep missed. `git show dbeae70a0e:tools/lib/surplus-fall/tick.ts | grep notification` returns lines 4 and 5, both import paths, and lines 34 and 38, both comments. The query is line 57, `\"page-type\": NOTIFICATION_PAGE_TYPE_SLUG`, and the slug's text is not there. After the ablation `askComposed` answers `\\`notification\\` names no page type whose pages are files`, which `tierSaidOn` (tick.ts:55-80) turns into a throw, and `runSurplusFallTick` calls it on every fall. It fails loud rather than silent: I ran it and it threw, rather than answering zero rows, which would have re-pushed the same fall every 300s.\n\nATTRIBUTE IT BY TIMESTAMP. `surplus-fall-notifier` was already failed, since 07:17:03, on `daily-tracking` ablated at 06:49:21 — hit at tick.ts:86, which runs before `tierSaidOn`. The notification break was a second landmine behind the first, not the outage. Repairing `daily-tracking` alone would have surfaced it.\n\nFixed at 0431f70161: `newestOfKind` in `feed.ts` reads the rows out of the feed's sidecar and `tierSaidOn` reads through it, still throwing where the feed is unreadable. Verified by running, against a baseline taken from the old registry before it went: 16 rows after 2026-08-25 and a newest of 2026-09-02T17:00:00.820Z, both unchanged, and `tierSaidOn('2026-09-01')` answers `yellow`. `apns-push-notifier` restarted onto the new code at 12:35:20 and reads `from=2026-09-02T17:00:00.820Z` with no error.\n\nTen of the eleven `surplus-fall` rows carry `source: \"readouts\"`, which predates the `surplus-fall/<tier>` spelling, so a null tier for those is the data rather than a defect.",
} as const satisfies Finding
