import type { Finding } from "../finding.page-type.ts"

export const aTypeOnlyBackEdgeIsNoCycleAtRunTimeAndStillBlocksAnIncrementalLanding = {
  id: "01a064e5-aa53-7a3b-bbbf-ed3a46a97c27",
  pageTypeSlug: "finding",
  slug: "a-type-only-back-edge-is-no-cycle-at-run-time-and-still-blocks-an-incremental-landing",
  domainSlug: "domain/akasha-migration",
  claim:
    "A cycle whose back edge is a type-only import is no runtime cycle and `no-import-cycle` is right to erase it. It still blocks landing modules one at a time: whichever of the pair lands first names a package specifier for a module that does not exist yet. The landing fails at typecheck with nothing pointing at the cause. Two such pairs sit in the editor extension.",
  evidence:
    "Found 2026-09-03 while computing the landing order for the 68 unported extension files.\n\nThe two pairs. `features/agent-tree/forest.ts:11` imports `readSeatPlaces` from `./lookup.ts` as a value while `features/agent-tree/lookup.ts:2` imports `AgentNode` from `./forest.ts` as a type. `features/work-tree/harness.ts:3` imports `rollUp` from `./colors.ts` as a value while `features/work-tree/colors.ts:1` imports three types back from `./harness.ts`.\n\nWhy the check is silent and correct. `no-import-cycle.code-check.code.ts` erases a type-only import at lines 19 to 26 including the form where every named element carries its own `type` keyword. Both back edges are exactly that. TypeScript erases them too so neither pair is a cycle at run time and refusing them would be wrong.\n\nWhy a migration cares anyway. Modules land one at a time and each landed body reaches its sibling by package specifier rather than by relative path. A specifier naming a module with no page yet is refused before any cycle question is asked. So the requirement incremental landing carries is stricter than the one the check enforces and the gap is invisible from either side.\n\nWhat it costs is small and the remedy is cheap. Merge each pair into one module — `colors.ts` is 40 lines and `lookup.ts` is 44 so both stay far under the 15000 byte ceiling — or land the shared types first as a third module. The second shape is cleaner and costs two extra modules.\n\nThe general point is the one worth keeping: a check that is correct about run time can still be silent about a constraint that only exists while a tree is half moved.",
} as const satisfies Finding
