import type { Finding } from "../finding.page-type.ts"

export const akashaDeployReadsTheIosAppMarkdownRatherThanTheAkashaPages = {
  id: "01a06280-2ec8-7021-829a-2a40795c33a9",
  pageTypeSlug: "finding",
  slug: "akasha-deploy-reads-the-ios-app-markdown-rather-than-the-akasha-pages",
  domainSlug: "domain/akasha-migration",
  claim:
    "The new system depends on the widget road's markdown after all. `akasha deploy` resolves which iOS app to build by reading `pages/ios-app/*.ios-app.md`, and the module page records that as an invariant rather than as an oversight. Ablating those three files would refuse every iOS deploy, including the road that uploaded build 202, so removing them waits on a migration still owed four properties and a whole missing atlas page.",
  evidence:
    'Run 2026-09-02. `akasha deploy amy-no-such-app` answered `3 ios apps have one: alanwalton, atlas, smilingjenny`. mobileApps() gathers that list at akasha/mobile-cli/mobile-app/mobile-app.module.code.ts:99 from readFilePages("ios-app", APP_KEYS). kindNamed(cwd, "alanwalton") answered {kind:"ios-app",pagePath:"akasha:pages/ios-app/alanwalton-ios.ios-app.md"}. With that file moved aside, the same call answered a refusal naming only atlas and smilingjenny; the file was put back and the earlier answer returned. `akasha test --file-path akasha/mobile-cli/mobile-app` gave 18 pass, 0 fail, all reading that markdown.\n\nThe coupling is deliberate and written down. mobile-app.module.ts:14 gives the departure `The ios-app pages read here are markdown files under pages/ios-app at the checkout root`, and line 18 the absence `The akasha ios-app pages written in TypeScript are not read here`. mobile-cli.workspace-package.ts:52 gives the same as a stopgap over the whole package.\n\nWhat the migration is owed: APP_KEYS at mobile-app.module.code.ts:33 names 18 keys. asc-capabilities and web-env-path, which an earlier finding recorded as absent, are on the akasha page type now. Four are absent everywhere in akasha: mac-build-lock-dir, mac-build-number-file, mac-www-staging-rel and default-device-udid. atlas has no akasha page at all, ios-app.page-type.ts:41 naming only alanwalton and smilingjenny, and an akasha ios-app requires a manifest, a capacitor config and a gitignore beside it.\n\nA second reader of the same shape, which no import graph shows: checkout-roots.module.code.ts:11 sets REPO_PAGES to `pages/repo` and readdirSync reads that directory at line 24 to work out which repositories exist, falling back at line 41 to the folder two above. Every readFilePages call goes through it.\n\nresolveApp defaults to alanwalton at line 115, but deploy-ios-shipping.module.code.ts:83 reaches it only with a slug kindNamed already matched, so that default is not reached on this road.',
} as const satisfies Finding
