import type { Finding } from "../finding.page-type.ts"

export const akashasExtensionEntryDanglesOnModulesNoOneHasLanded = {
  id: "01a0685e-7a29-7746-bb5a-17354b0d7681",
  pageTypeSlug: "finding",
  slug: "akashas-extension-entry-dangles-on-modules-no-one-has-landed",
  domainSlug: "domain/akasha-migration",
  claim:
    "Akasha's extension entry point does not resolve. `extension-entry.module.code.ts` imports twelve modules by `@akasha/editor-extension/<name>` and only three of them resolve. Four — `agent-tree-panel`, `domain-tree-panel`, `page-tree-panel` and `work-tree-panel` — exist nowhere in the repository. Five more exist on disk but are absent from the package manifest's `exports`, which enumerates and carries no `./*` fallback, so nothing reaches them under that specifier.",
  evidence:
    'Measured 2026-09-03 while migrating the 34 files of `editor-extension/src`.\n\n`akasha/editor-extension/ops-extension/extension-entry/extension-entry.module.code.ts` imports, at lines 1 to 16: activation, agent-tree-panel, domain-tree-panel, editor-layout-panel, harness-call, observation-store, page-tree-panel, status-bar-panel, terminal-renaming, transcript-panel, window-identity, work-tree-panel. Checking each for a `<name>.module.code.ts` under `akasha/editor-extension/` and for a `"./<name>"` key in `akasha/editor-extension/package.json`:\n\n  resolve (on disk and exported): activation, harness-call, window-identity — 3 of 12.\n  on disk but unexported: editor-layout-panel, observation-store, status-bar-panel, terminal-renaming, transcript-panel — 5 of 12.\n  absent entirely: agent-tree-panel, domain-tree-panel, page-tree-panel, work-tree-panel — 4 of 12.\n\nThe manifest\'s `exports` block enumerates 31 specifiers and ends without a `./*` entry, so the five unexported modules are unreachable under `@akasha/editor-extension/<name>` however they are spelled. This is the opposite shape to the blind spot the initiative\'s third intent records for `@tools/lib`, where a `./*` pattern matching nothing let an import ride; here the enumeration is complete enough to refuse.\n\nThe four absent modules are not a separate defect. They are the migration\'s own unfinished work: `editor-extension/src/features/agent-tree/` (21 files), `features/domain-tree/` (3), `features/page-tree/` (3) and `features/work-tree/` (5) are still outside akasha, and they are what those four specifiers are waiting for. Commit `98435f5b24`, "the extension reaches the twenty-three modules akasha already holds", repointed the old extension at akasha and migrated five of its eight features, ablating their old copies; `editor-extension/src/extension.ts` was left importing `./features/editor-layout/activate.ts`, `./features/status-bar/activate.ts`, `./features/terminal-rename/activate.ts`, `./features/transcript/activate.ts` and `./seat/observation-store.ts`, all five of which are gone from disk. So both the old entry point and the new one have been dangling since that commit, each on the half the other holds.\n\nThis is worth reviewing with Alan against constraint 1, which releases us from keeping systems outside akasha stable while the migration runs. Nothing here breaks that constraint. It is recorded because a broken entry point is invisible to a per-file migration check: every file involved is individually accounted for, and only the import graph shows it.',
} as const satisfies Finding
