import type { Finding } from "../finding.page-type.ts"

export const akashaAnswersPagePlacementDirectlySoTheTwoUnrepointableModulesRepoint = {
  id: "01a06896-07c5-72f9-a7be-e9b727048a7d",
  pageTypeSlug: "finding",
  slug: "akasha-answers-page-placement-directly-so-the-two-unrepointable-modules-repoint",
  domainSlug: "domain/akasha-migration",
  claim:
    "The conclusion of `two-akasha-modules-reach-out-for-markdown-machinery-akasha-will-not-carry` does not follow. `editor-page-sweeping` asks `whereFor` only for a landed page, and akasha answers that directly on-workstation today: `listedAt` gives an existing page's path, `composedFor` computes a new one, neither through the pages-system-service. What blocks `page/` is a registry that reads markdown alone, not two modules with nothing to point at.",
  evidence:
    'Measured 2026-09-03 at HEAD c740276920.\n\nWHY IT LOOKED TERMINAL. `file-write-backing.module.code.ts:27-31` throws and names `@akasha/pages-system-service` as where placement belongs. Constraint 19 forbids on-workstation code from calling that service, so the refusal points at a road that is closed for exactly the callers that need it. The refusal is sound for `pages-access`, which declares at `pages-access.workspace-package.ts:53` that every page it reaches is asked of the service — that is the off-workstation road.\n\nTHE THIRD ROAD NEITHER NAMES. `@akasha/pages-system/indexes` reads `.git/data/index` off disk; 193 files import it. `listedAt(given, pageTypeSlug, slug)` at `indexes/index-reading/index-reading.module.code.ts:127` returns `Listed = {path, id}`; run live, `listedAt(root,"page-type","car-make")` answered `akasha/alan/car-research/car-makes/car-make.page-type.ts`. For a page that does not exist yet, `composedFor(root, named)` at `service/page-composing/page-composing.module.code.ts:79` answered a full `put.path` for an unused slug; its manifest states `Nothing here writes a file`. `asking(root, query)` at `service/page-asking/page-asking.module.code.ts:216` is synchronous with no socket and answered 435 rows for `page-type`, exactly the 435 `*.page-type.ts` on disk.\n\nWHAT THE MODULE ACTUALLY NEEDS. `editor-page-sweeping.module.code.ts:19-28` calls `whereFor` inside `processPresence` and then reads frontmatter at `at.path` — the landed-page half alone, which `listedAt` answers.\n\nTHE SECOND MODULE IS A DIFFERENT DEPENDENCY. `royal-road-syncing` takes `parseFrontmatter`, `listField` and `textField` for markdown and never calls `registryOf`. It blocks deleting `page/frontmatter.ts`, not the registry, and is held by its own data still being markdown.\n\nNot measured: I did not repoint either module. `editor-page-sweeping` is live — a running editor window writes through this road every 250ms.',
} as const satisfies Finding
