import type { Finding } from "../finding.page-type.ts"

export const anAddonManifestNamesALuaFileTheNamingGrammarCannotHold = {
  id: "01a06122-bbe3-7278-9462-d043c276fb1b",
  pageTypeSlug: "finding",
  slug: "an-addon-manifest-names-a-lua-file-the-naming-grammar-cannot-hold",
  domainSlug: "domain/temper",
  claim:
    "An addon manifest names its extra Lua by a bare file name at the package root, and akasha's naming grammar holds no such name. A `lua-module` lands at `<slug>/<slug>.lua-module.lua.lua`, so a build reading `additionalLuaFiles` throws on a path that is not there and writes a load-order line naming a file the addon folder will not hold. The three earlier failures between a landed eso-addon and Lua are mended, so this is the one left.",
  evidence:
    'Measured on 2026-09-02 while landing `temper/game-companions-addon` as `akasha/temper/temper-companions-addon` at commit 800131cc34.\n\n`temper/game-companions-addon/addon.json` line 14 states `"additionalLuaFiles": ["TemperCompanionsConfig.lua"]`. The file beside it holds one line, `TemperCompanionsConfig = nil`, which the game fills from the saved variables file before the compiled bundle runs. The manifest was carried across unchanged rather than quietly rewritten, so the entry now names nothing.\n\nThree places read the entry and each takes it as a path under the addon folder. `tools/commands/temper/addon/copy-metadata.ts:91-93` calls `readFile(join(addonDir, filename))`, and a missing file throws rather than being skipped. `tools/lib/addon-load-order-metadata.ts:94` spreads the same strings into the load-order lines the game reads, ahead of the bundle, so a build past the read would still name a file the folder does not hold. `tools/commands/temper/addon/install.ts:138` reads the array a third time.\n\nIn akasha the file landed as the `lua-module` page `companions-config`, at `companions-config/companions-config.lua-module.lua.lua`, the name the naming grammar requires. No `additionalLuaFiles` string can name it. The handle that answers this is already on the page: `temper-companions-addon.eso-addon.ts` states `luaModuleSlugs: ["lua-module/companions-config"]`, so a mended build can resolve a slug to its path and to the name the game wants.\n\nThis was the fourth of four failures between a landed eso-addon and Lua. The other three are mended: `listWorkspaceDirs` expands the `akasha/**` glob, `addonManifestPathIn` finds a `.eso-addon.addon-manifest.json`, and an akasha addon compiles to Lua and exits 0. So this one is reachable now rather than sitting behind walls.\n\nThree temper addons carry the same shape and none has landed: `catalog-addon`, `game-items-addon` and `player-completion-addon` each name a `Temper*Config.lua`.',
} as const satisfies Finding
