import type { Finding } from "../finding.page-type.ts"

export const anAddonShipsAnEmptyDocumentUnderItsOwnNameNoLoadOrderLists = {
  id: "01a06206-b00c-746b-9a11-f49c44da36c5",
  pageTypeSlug: "finding",
  slug: "an-addon-ships-an-empty-document-under-its-own-name-no-load-order-lists",
  domainSlug: "domain/temper",
  claim:
    "`copy-metadata` writes `<CanonicalName>.xml` into every addon's dist folder, falling back to an 18-byte `<GuiXml></GuiXml>` where nothing holds that name. Of 34 akasha eso-addons, 33 get the empty one. No load-order file lists it unless the manifest names it, so for those 33 it is output the game never loads. The write predates the manifest-driven copy that supersedes it, and nothing took it away.",
  evidence:
    "Measured 2026-09-02 at `bf805b42c2`, by asking `namedFilePathOrNull` for the addon's own name plus `.xml` across all 34 folders under `akasha/temper/` holding an `*.eso-addon.ts` page.\n\nOne answers: TemperEvents, 3,271 bytes, at `temper-events-addon/next-boss-layout/next-boss-layout.eso-interface.markup.xml`. The other 33 answer nothing and take the 18-byte document.\n\nBefore `bf805b42c2` the lookup read only the addon folder's `metadata` subfolder, which no akasha addon has, so all 34 took 18 bytes. TemperEvents was rescued only because its manifest also names `TemperEvents.xml`, so the later shipped-files loop wrote the real 3,271 bytes over the empty one. That is the same coincidence that kept the 22-byte `Bindings.xml` default harmless. `bf805b42c2` routes the write through the name resolution every other shipped file uses, so the rescue is no longer luck.\n\nWhat remains is the 33. `temper/addons/dist/TemperCombat/TemperCombat.txt` lists `build-id.lua`, `TemperCombat.lua` and the three `TemperCombat_*.xml` the manifest names, and never `TemperCombat.xml`, while `temper/addons/dist/TemperCombat/TemperCombat.xml` is 18 bytes. `TemperEvents.txt` lists `TemperEvents.xml` because its manifest names it. The load order carries what the manifest names, and this write reaches past it.\n\nNothing is lost by it. The one addon whose twin ships a real file under its own name is TemperCombat, at 164,528 bytes, and akasha splits that into the three documents the manifest names, which splice back inside the twin's `GuiXml` wrapper with an 18-line diff that is entirely the two Controls seams. The claim is that the write is unreferenced output, not that anything went missing.\n\nTaking the write away needs someone to establish that no addon depends on ESO reading a same-named file by convention. I did not establish that, so I left it alone.",
} as const satisfies Finding
