import type { Finding } from "../finding.page-type.ts"

export const eightAkashaExerciseCommandsReachAFileThatIsGone = {
  id: "01a06867-9eee-7a8e-b8d9-e372947bf9c1",
  pageTypeSlug: "finding",
  slug: "eight-akasha-exercise-commands-reach-a-file-that-is-gone",
  domainSlug: "domain/akasha-migration",
  claim:
    "Eight exercise commands under `akasha/alan/fitness/commands/` import `@collections/exercises/pages/access` or `/pages/page`, and both files were ablated at 3e585db2c3 once their akasha counterpart stood. The counterpart is no rename: `getPages` threw where `rowsFor` answers a union, and `createPage` and `patchPage` were not carried at all, so 21 call sites need their refusal read rather than caught.",
  evidence:
    "Measured 2026-09-03, straight after ablating the ten files of `collections/exercises/src/pages/` and `src/free-exercise-db/`.\n\nThe counterpart is `akasha/alan/fitness/exercise-access/exercise-rows/exercise-rows.module.code.ts`, landed by a sibling lane before this. It carries every export of `access.ts` but two, renamed: `getPages` is `rowsFor`, `getPage` is `rowFor`, `pageOfRow` is `rowOf`, `Page` is `Row`, `Json` is `Value`, `PageQuery` is `Asking`, `PageCondition` is `Test`, `PageOrder` is `Ordering`, `PagesRead` is `Rows`, `kebabKey` is `dashed`, `camelKey` is `humped`. `composedFor` keeps its name. The two not carried are `createPage` and `patchPage`, whose whole body was a throw; the finding `two-throwing-exercise-writers-died-with-their-file` records that.\n\nThe eight and their lines: `exercise-next-set:6`, `exercise-ranks:5,6`, `exercise-schedule-create:3`, `exercise-session-finish:5,6`, `exercise-session-show:5,6`, `exercise-session-start:4,5`, `exercise-today:4`, each in its own `.command.code.ts`. Nothing under `akasha/alan/fitness/commands/` names `exercise-rows` yet.\n\nWhy no check caught it: the finding `the-import-gate-resolves-a-package-specifier-by-exact-export-key-only` shows `@collections/exercises/pages/access` is an exact export key the import gate refuses. These commands landed at `df0f20a085` as mechanical changes, which run no check.\n\nThe repointing is no specifier swap. `getPages` threw on a failed read and each command catches; `rowsFor` answers `{ rows } | { unread }`, so each call site reads its refusal instead. The same eight also import `@collections/exercises/cli/fields`, `/cli/resolve` and `/tracking/day-of-week`, which stand outside akasha too, so the lane holding `src/cli/` and `src/tracking/` reaches these files anyway.\n\nThe call taken: they were left alone. Rewriting 21 call sites in files another lane is actively editing would clobber that lane's work.",
} as const satisfies Finding
