import type { Finding } from "../finding.page-type.ts"

export const esoEnumDeclarationsCarryNoValueToKeepInStep = {
  id: "01a060bd-c11a-7c54-becf-4bb007031f58",
  pageTypeSlug: "finding",
  slug: "eso-enum-declarations-carry-no-value-to-keep-in-step",
  domainSlug: "domain/temper",
  claim:
    "The generated ESO enum declarations name 4,343 constants and give a numeric value to none, because the upstream documentation the generator reads carries no value either. So a runtime module of ESO constant values could never be emitted by the same generator as the declarations, and the two could drift apart with no check able to notice.",
  evidence:
    'Every line of `temper/addons/types/eso/generated/enums.d.ts` has the shape `declare const EQUIP_TYPE_CHEST: number`, across 4,343 constants and 246,745 bytes. A type alias such as `type EquipType = number` heads each group and adds nothing beyond `number`.\n\nWhy the generator emits no value. `tools/lib/eso-typings/generate.ts:41` pushes one line per constant, of the shape `declare const NAME: number`, and the generator has nothing better to push. Its source is `~/esoui/ESOUIDocumentation.txt`, where the EquipType group at lines 4957 to 4973 is a bare alphabetical list: `* EQUIP_TYPE_CHEST`, `* EQUIP_TYPE_COSTUME`, `* EQUIP_TYPE_FEET` and so on. No number appears beside a member anywhere in the file. The ordering is alphabetical rather than ordinal, so position carries no value either: `EQUIP_TYPE_CHEST` is listed first and its runtime value is 3.\n\nWhere the values that exist did come from. The 24 pages under `akasha/temper/temper-catalog/temper-companions/eso-companion-equipment-constants/pages/` each carry a `valueNum` — `equip-type-equip-type-chest.temper-eso-companion-equipment-constant.ts` holds `keyText: "EQUIP_TYPE_CHEST"` and `valueNum: 3`. `@akasha/temper-addon-generators/temper-eso-companion-equipment-constant` turns those pages into `ESO_EQUIP_TYPES_GENERATED` in `temper/game-items-core/src/generated/`. So the values are curated in akasha pages by hand, reaching akasha from a live game rather than from the documentation.\n\nWhat follows. Two origins feed the two halves, and only the name is common to both. A constant renamed upstream shows in the declarations at the next regeneration and leaves the page untouched; a value changed by a game patch shows in neither. Any value module written against these declarations should say which game version its numbers were read at.',
} as const satisfies Finding
