import type { Finding } from "../finding.page-type.ts"

export const everyTemperPageTypeAlreadyExistsSoTheTemperFoldersAreCheckedRatherThanDesigned = {
  id: "01a06550-638b-7000-a3e9-6eb9b5ba942e",
  pageTypeSlug: "finding",
  slug: "every-temper-page-type-already-exists-so-the-temper-folders-are-checked-rather-than-designed",
  domainSlug: "domain/temper",
  claim:
    "The temper page types are built and the temper pages are already migrated. `akasha/temper` holds 121 page types descending from one root, `temper-thing`, and the 99 `pages/temper-*` folders hold 5,557 markdown pages of which 5,445 match a landed page by slug. Only `temper-net-worth-day` and `temper-completed-month` reach no page type at all. What is left for these folders is checking each file and ablating it, so a second scheme for them would be a duplicate rather than a design.",
  evidence:
    "Measured 2026-09-02 over every `pages/temper-*` folder. The page type a folder lands in is found by `find akasha/temper -name '<folder>.page-type.ts'`, and 97 of the 99 resolve. The types sit under four domains — `temper-catalog` (itself grouped into `temper-companions`, `temper-effects`, `temper-gear`, `temper-pursuits` and `temper-skills`), `temper-character`, `temper-holdings` and `temper-progress`. Each concrete type extends a middle type such as `temper-catalog-thing`, and every middle type extends `temper-thing`, which carries `title`, `key`, `description`, `icon` and the shared ids. A folder's pages land at `<type-folder>/pages/<slug>.<type>.ts`.\n\nThree renamings account for every slug that does not match its markdown stem. A stem opening with a digit takes a word ahead of it, because a slug must become an export name: `at-` for a moment, under `temper-inventory-chunk` and `temper-inventory-snapshot`, and `hour-` for an hour. A stem that is a bare uuid takes its type as a prefix, `account-` and `player-`. A stem colliding with a sibling is widened: `class` is `class-set` under `temper-set-category` and `character-class` under `temper-skill-line-category`. Six folders hold the twelve pages this covers — `temper-account`, `temper-player`, `temper-watcher-enrolment`, `temper-completion-override`, `temper-set-category`, `temper-skill-line-category` — and they are checked by content rather than by slug.\n\nA sidecar beside a markdown page lands as a `.jsonl` beside the `.ts`. `temper-companion-skill` holds 121 `.effects.attachment.json` and 24 `.cast-conditions.attachment.json` outside, against 121 `.skill-effects.jsonl` and 24 `.cast-conditions.jsonl` inside.",
} as const satisfies Finding
