import type { Finding } from "../finding.page-type.ts"

export const familyOfFiveNeverCosted = {
  id: "01a06555-9f3d-7321-9b61-224b0093ee78",
  pageTypeSlug: "finding",
  slug: "family-of-five-never-costed",
  domainSlug: "domain/all-about-alan",
  claim:
    "Every cost figure ranking the second-passport destinations is priced for a family of four, and the family is five. Both synthesis files state the correction once — add ~12–15% to living costs, 25–40% to rent — and never apply it. The tables, the cheapest lists and the €4,500-a-month sweet-spot filter run on unadjusted numbers. Athens at €3,873 clears that threshold as written and fails it under the file's own uplift, so a city listed among the cheapest is one this arithmetic excludes.",
  evidence:
    'Read 2026-08-16. Both files read directly.\n\nThe correction, stated identically at `active-income.md` line 37 and `passive-income.md` line 44: "Family of 4 monthly cost incl. 3BR outside city centre, sorted cheapest first. **For your family of 5, add ~12–15% on living costs and ~25–40% on the rent component (4BR vs 3BR).**"\n\nThe tables it heads stay at four. Both column headers read "City f4 €/mo (outside-CC 3BR)". `active-income.md`: "Bucharest … ~€3,061 | Athens … ~€3,873 | Warsaw … ~€4,090 | Lisbon … ~€4,425 | Rome … ~€4,800–5,200 | Brussels … ~€5,264 | Berlin … ~€5,338 | Paris … ~€5,783". Both add "Montevideo, Uruguay: ~USD 2,500–3,500/mo f4 outside-CC."\n\nThe rankings run on those numbers. `active-income.md`: "**Cheapest 5 (city f4 cost):** 1. Bucharest … 2. Athens … €3,873/mo 3. Warsaw … 4. Lisbon … 5. Brussels". `passive-income.md`: "**Cheapest 3 (city f4 cost):**".\n\nSo does the threshold. `active-income.md`: "**Sweet-spot (clock ≤7y AND city cost ≤€4,500/mo)** … Cheapest EU cities below €4,500/mo (Bucharest, Athens, Warsaw, Lisbon) all have clocks ≥8y."\n\nThe uplift raises every figure at least 12% before rent is touched. Athens at €3,873 exceeds €4,500 above about 16%; Warsaw at €4,090 above about 10%; Lisbon at €4,425 above about 2%. All three are listed as below it. The files do not split their figures into living and rent components, so I state that the threshold is crossed under the stated uplift, not by how much.\n\nAlso unpriced anywhere in the thread: schooling for three children, health cover, US tax filing, and moving or exit costs. No file names any of them.\n\nNot measured: I checked no cost source and re-derived no city figure. That the household is five I take from these two files — "married + 3 kids relocating together", and the correction addressed to "your family of 5" — not from Alan.',
} as const satisfies Finding
