import type { Finding } from "../finding.page-type.ts"

export const fiveRowsFilesNoPageNamesAreTheOnlyCopyOfTheirLines = {
  id: "01a06143-f4d5-7468-9fdf-69a84a06c603",
  pageTypeSlug: "finding",
  slug: "five-rows-files-no-page-names-are-the-only-copy-of-their-lines",
  domainSlug: "workspace-package/pages-system",
  claim:
    "Five `.uncommitted.jsonl` files under `pages/seat-log-day/`, 17,775,639 bytes, are reachable by nothing and hold the only copy of 56,322 log lines. Their names lack the `.seat-log-day` page type token, so no page claims them and no reader opens them. They are not what a removal left behind: the pages they belong to are present under the correct name. What wrote them has not been found. They read as debris, and clearing them would destroy the lines.",
  evidence:
    "Measured 2026-09-02. `pagesOfSidecar` in page/sidecar/sidecar.ts, asked of every one of the 14,676 rows files under pages/ and akasha/, answers a page that is absent for exactly five, all in pages/seat-log-day/ and none anywhere else:\n\n2,416,530 oauth-proxy-console-ryn-2026-08-26.lines.part12.uncommitted.jsonl; 8,388,338 the same at part13; 2,353,010 at part14; 8,158 supervisor-console-ryn-2026-08-26.lines.uncommitted.jsonl; 4,609,603 supervisor-transport-ryn-2026-08-26.lines.part5.uncommitted.jsonl.\n\nEach answers a page named `<seat>-2026-08-26.md`, and what is there is `<seat>-2026-08-26.seat-log-day.md`, so the page type token is missing from the middle of every one. The three pages are all present under the correct name, with their own base file and 18, 1 and 7 parts, which is why a removal taking only the base file is NOT what left these. That defect was real and is mended at 7dd6d79790; it does not explain these five, and the writer that does has not been found.\n\nThe lines are unique. Against every correctly named file of the same page, the orphans share zero ids (46,999 against 517,041; 9,302 against 104,539; 21 against 3,896) and zero (written-at, text) pairs. The correctly named files have a hole: over 12:04:42 to 12:32:57 on 2026-08-26 they hold 14, 3 and 0 lines, and the orphans hold 46,999, 9,302 and 21 across exactly that window.\n\nNothing reads or writes them. tools/lib/log-append.ts:49 reaches a day through `whereFor`, which builds the correct name, and services/sweep-log-days.ts:95 clears a page through `sidecarsOf`, which resolves the correct stem only.\n\nRenaming them in is possible - parts 19, 20 and 21, part 8 and part 2 are free - but `rowsPartsOf` reads parts in number order, so it would put these lines after their pages' later rows rather than in time order. That call belongs to whoever owns the spool. I left all five where they are.",
} as const satisfies Finding
