import type { Finding } from "../finding.page-type.ts"

export const fiveClusterRbacModulesLostTheirOnlyReaderWhenTheCheckRbacCommandsWent = {
  id: "01a06864-8745-7001-b5d6-5756736a2577",
  pageTypeSlug: "finding",
  slug: "five-cluster-rbac-modules-lost-their-only-reader-when-the-check-rbac-commands-went",
  domainSlug: "domain/akasha-migration",
  claim:
    "Five of the ten modules in tools/lib/cluster-rbac had no importer anywhere in the tree when this lane reached them, because the `ops check-rbac-escalation`, `check-rbac-pipelines` and `check-rbac-cluster-resource-names` commands they existed to serve were taken away earlier in this migration. They were migrated or ablated on that ground rather than left, and two of them stand still because their own dependencies have not moved yet.",
  evidence:
    "Measured by searching every export name of every file in the folder across the tree and excluding the folder itself. The instrument is not blind to its subject: the same search found the two live consumers of `profileSources`, `tupleOf` and `clusterRoleRules` in the same pass, so a zero from it is a true zero rather than a search that matched nothing.\n\nWith no reader: applies.ts, engine-steps.ts, kinds.ts, kubectl.ts, synth.ts, and the `buildPermissions`, `isCovered` and `patchRuleWhitelist` half of permissions.ts. The check entries themselves went at 0f241126ac and the machinery around them at 2253cdeb11, both swarm landings; tools/lib/check-workflow/repo-wide-ts-scanners.ts still carries the three `rbac-check-*` descriptions with no check behind them.\n\nsynth.ts was ablated rather than carried: `discoverSynthFiles` was a literal re-export of @akasha/k8s-synth/synth-discovery, `loadSynthOutputs` held the same zod schema and the same refusal message as @akasha/k8s-synth/synth-loading, and `generatedPathOf` is `generatedPathFor` of @akasha/k8s-synth/generated-file taking a directory instead of a file path. Its `loadEverySynth` matched nothing in akasha and was ablated on the zero-reader ground alone; the whole file is blob 0000a04f41b3039a74dcac63c6d3a7cb818f11af.\n\napplies.ts and engine-steps.ts stand still in tools/lib/cluster-rbac. They are not leaves: applies.ts reads PROBE_CONTEXTS out of tools/lib/workflow-surface/surface.ts and engine-steps.ts reads discoverWorkflows out of tools/lib/workflow-dsl/discovery.ts, neither of which has migrated. Carrying them now would mean two new @tools/lib imports out of @akasha/cluster-manifests, and a dependency on @tools/lib in a package that has just been freed of one, for code nothing calls. They belong with whoever moves workflow-surface and workflow-dsl.",
} as const satisfies Finding
