import type { Finding } from "../finding.page-type.ts"

export const fourAddonLibraryFoldersAreImportedByTheUpstreamDataVerifiers = {
  id: "01a0624b-feed-732c-9cf8-3e10a3ace8f0",
  pageTypeSlug: "finding",
  slug: "four-addon-library-folders-are-imported-by-the-upstream-data-verifiers",
  domainSlug: "domain/temper",
  claim:
    "Four folders scheduled for teardown are imported by live tool code. `lib-treasure`, `lib-zone`, `lib-map-data` and `game-housing-addon` are each reached by a `verify.ts` under `tools/lib/temper-upstream-data/`, so deleting any of them ends `ops temper upstream-data verify`. The page this replaces said no file anywhere imports the addon libraries, which is the opposite of what the tree holds.",
  evidence:
    "The importers, file and line, measured 2026-09-02 over the whole tree with node_modules and build output left out. `tools/lib/temper-upstream-data/lib-treasure/verify.ts` lines 3 to 6 take BOOK_ID, ALL_DATA, icons and AllData from `@temper/shared-addon-libraries-lib-treasure`. `lib-zone/verify.ts` lines 2 and 6 take GEO_DATA_REFERENCE_TABLE and the zone tables from `@temper/shared-addon-libraries-lib-zone`. `lib-map-data/verify.ts` line 5 takes the map table from `@temper/shared-addon-libraries-lib-map-data`. `housing/verify.ts` lines 2 to 4 take two library tables and LibraryEntry from `@temper/game-housing-addon`. Each verifier is reached by `ops temper upstream-data verify`, so deleting any of the four ends that command.\n\nThe sibling page `temper-upstream-ports-are-clear-to-enter` already recorded these same four edges, so the tree carried both readings at once and the more inviting one was wrong.\n\nFour other addon libraries are reached by no import of any kind, by package specifier, by relative path, or by a bare side-effect import: lib-async, lib-debug-logger, lib-extended-journal and lib-character-knowledge. Their akasha twins each compile to Lua and exit 0, at 38,346, 48,621, 67,178 and 214,163 bytes.\n\nTwo akasha twins do not compile while both temper copies do. `temper-selector-addon` exits 2 on TS90002 at `selector-addon-manager.module.code.ts` line 17, a LuaMultiReturn read without destructuring. `temper-lib-addon-menu-order-list-box` exits 2 on TS2339 at `order-list-box-list-methods.module.code.ts` line 55, where SetMaxLineCount is declared on Control in the temper copy and missing from OrderRowControl in the akasha shape file. The page this replaces recorded both as TS90002; one is a dropped declaration rather than a multi-return misuse, and the two need different repairs. Deleting either temper copy would take a shipping addon to one that does not build.",
} as const satisfies Finding
