import type { Finding } from "../finding.page-type.ts"

export const laneSizeAgainstTheBackupSaysWhoIsWorkingBetterThanTheDispatchRecord = {
  id: "01a06576-00b3-7a23-95cd-e7125f59c957",
  pageTypeSlug: "finding",
  slug: "lane-size-against-the-backup-says-who-is-working-better-than-the-dispatch-record",
  domainSlug: "domain/akasha-migration",
  claim:
    "Sixty-one thousand eight hundred and ninety-five files are outside akasha in 311 folders that ever held one, and 168 of those folders hold today exactly what they held before the migration opened. Dispatch says a lane is owned. Only the count against the backup says its owner ever landed anything, and after nineteen agents were killed mid-assignment the two answers differ across most of the tree.",
  evidence:
    "Measured 2026-09-02 at 22:30 by counting `git ls-files` in this checkout against `git ls-files` in the read-only backup at /var/home/walton/repos/akasha-backup-2026-09-02, grouped into one lane for each `pages/` subfolder, each top-level directory and each tracked file at the repository root. 102,800 files then, 98,808 now; 32,906 inside akasha then, 36,913 now.\n\nOf the 311 lanes, 118 are cleared to zero, 24 shrank without emptying, 1 grew, and 168 are unchanged holding 38,510 files. The one that grew is `pages/story-chapter-royal-road`, from 18,090 to 18,091, because the Royal Road reader is still writing chapters into the old tree. So the largest single lane outside akasha is not merely unmigrated but filling as the migration runs. Unchanged and filling together hold 56,601 of the 61,895 files outside, which leaves 5,294 in lanes anyone has begun.\n\nThe movement is concentrated. The largest reductions are `pages/temper-skill` 1,636 to 0, `dirty/` 1,506 to 563, `pages/temper-set` 707 to 0, `pages/temper-inventory-chunk` 916 to 458, `pages/temper-item-category-tree` 439 to 0, `alanwalton/` 282 to 87 and `pages/monarch-month` 126 to 0. Every `pages/monarch-*` folder is empty, every `pages/temper-*` folder but `temper-inventory-chunk` is empty, and `ops-cli/` went 35 to 0.\n\nThe largest unchanged lanes are `pages/skill` 8,972, `pages/class` 8,380, `pages/spell` 3,597, `pages/persona-day` 2,079, `pages/page-property-definition` 2,074, `pages/book` 1,579, `pages/location` 1,210, `pages/great-course` 1,123, `pages/exercise` 884, `pages/story-chapter-wandering-inn` 832, `pages/relationship` 697 and `temper/` 516. Each of these had an owner dispatched.",
} as const satisfies Finding
