import type { Finding } from "../finding.page-type.ts"

export const mostOfNoRuleInTwoFilesIsTheTemperMove = {
  id: "01a060ee-0a02-7000-a758-0d032b6f6435",
  pageTypeSlug: "finding",
  slug: "most-of-no-rule-in-two-files-is-the-temper-move",
  domainSlug: "domain/akasha-migration",
  claim:
    "`no-rule-in-two-files` is 91 percent of the tree's refusals, and 143 of its 180 are under `akasha/temper/`, a move landing tonight whose seat is already cutting them. The rest of that 143 goes to that seat rather than to a sweep by anyone else. Of the 37 elsewhere, most need a shared home added rather than a stale copy deleted, and the gates guard addition. Only where an owner is already there is the copy free to go; two such were cleared.",
  evidence:
    "Measured 2026-09-02 at `b6994b2301` by calling `noRuleInTwoFiles` alone over `everythingIn(root)`: 180 refusals over 26564 paths. `akasha audit` caps its answer at 28000 bytes and printed 196 refusals with 97 unreached, which is why nobody had looked at this class.\n\nThe 180 fall into 50 rules. 33 are spelled in two files, 4 in six or more. The largest is 25 temper inventory rule commands sharing one body, then 13 more temper commands sharing another, then 11 `asGlobalTable` across `temper-lib-*-casts`. By folder: 143 `akasha/temper`, 9 `pages-system`, 8 `readout-system`, 7 `command-system`, 5 `checks`, 8 elsewhere. None is outside `akasha/`.\n\nAll 118 files were added between 2026-08-29 and 2026-09-02, the temper ones by commits saying `recreate the addon data generators in akasha` and `the other 65 temper commands come into akasha as command pages`. No group pairs an old path with a new one, so none is a half-done move whose stale side could be picked.\n\nThat seat is cutting this class already: `a8d2a84799`, `752bd9760d`, `3c11705ed4` and `4ebfac4bb1` landed between 23:58 and 00:31, each folding restated casts into shared declarations, one deleting a module outright. Temper fell 143 to 130 while this was written, with nothing of mine touching it.\n\nOf the 14 rules with no temper file, 5 are one-line wrappers over `fetch`, `TextEncoder`, `JSON.stringify`, `Promise.resolve` or `textIn`, where sharing costs a module and buys nothing. 3 are the old query engine beside the new service while that move runs. 3 are held by the deploy and TestFlight lanes.\n\nCleared: `30206fdd94`, where `declaredThreshold` said what `statedAt` says and two modules already reach `statedAt`; and `e879fb899a`, where `scanned` was copied into a check that already reaches `@akasha/plain-language`.",
} as const satisfies Finding
