import type { Finding } from "../finding.page-type.ts"

export const nineChecksReachARowFileAndNoneOpensALine = {
  id: "01a06065-7e0d-7945-bf6e-f3012277f555",
  pageTypeSlug: "finding",
  slug: "nine-checks-reach-a-row-file-and-none-opens-a-line",
  domainSlug: "domain/akasha-migration",
  claim:
    "A `.jsonl` beside an akasha page is judged as a file and never as rows. Nine checks reach one, and every one asks about the file: whether a page names it, what it is named, how long it is, what bytes it holds. None reads a line. A row with kebab keys, a row naming a `dailyTracking` no page carries, a row whose `id` is no uuid, a row carrying an undeclared key, and a line that is not JSON at all each passed all nine.",
  evidence:
    'Measured 2026-09-02 in an isolated copy at /var/home/walton/akasha-change-kind, byte-identical to `90b45b96e9` for every file it turned on. A day page was landed declaring `sessions: "jsonl"`, and six bodies were handed to the patch gate for `akasha/alan/wake-day/daily-trackings/day-2026-09-01.wake-day.sessions.jsonl` one at a time. The checks that woke, identical for all six: file-has-its-page, file-length, manifest-lands-on-a-file, manifest-names-what-is-reached, name-format-judges-by-one-shape, no-raw-nul-bytes, package-reached-where-named, page-named-as-stated, page-property-has-its-file. All six answered code 0. The one thing that does protect a row is `file-has-its-page`: run against the same six bodies before the day page declared `sessions`, every one was refused with `no page claims this file`. So the file\'s standing is judged and its contents are not. What would close it is one check that opens the file: read the page beside it, find the `page-property-entry` that page names for that file, and judge every line against the properties the entry declares — the file parses as one JSON object to a line, every required property is there, no key is one the entry does not declare, and `id` is a uuid. `entriesIn` in `akasha/pages-system/page/page-entries` already parses jsonl and already refuses a line that is not a JSON object; `sessions.page-property-entry.ts` already declares twelve properties and which are required. Nothing puts the two together. This lane did not build it: a check page, its code, its test and its own invariants are more than one lane, and the change kind it landed is worth much less until it exists.',
} as const satisfies Finding
