import type { Finding } from "../finding.page-type.ts"

export const noEsoAddonTypechecksUntilTheGameApiTypesMoveIn = {
  id: "01a06053-6e0e-7687-b954-8e71a0242521",
  pageTypeSlug: "finding",
  slug: "no-eso-addon-typechecks-until-the-game-api-types-move-in",
  domainSlug: "domain/temper",
  claim:
    "No ESO addon typechecks inside akasha. One fourteen-module library, LibDebugLogger, drew 189 type refusals naming 84 globals it cannot reach: GetTimeStamp, EVENT_MANAGER, SOUNDS, ZO_Object, and the Lua 5.1 library itself, meaning pcall, pairs, string, table, os and debug. Temper answers all of these from 482KB of `.d.ts` generated from the game's own documentation. akasha compiles one program under one set of settings, so no half of the tree reaches those globals alone.",
  evidence:
    "Measured, not guessed. `akasha write --dry-run` over a recreated temper/shared-addon-libraries-lib-debug-logger, fourteen module pages and their code, answers 153 TS2304, 30 TS2693, 3 TS2686 and 3 TS2339, and the TS2304 lines name 84 distinct identifiers. akasha/code-system/code-typing/code-typing.module.code.ts lines 15 to 25 hold SETTINGS, which sets no `types` and no `lib`, and the page beside it says `The settings the akasha folder compiles under are said here alone`. Two refusals prove the single program already binds these names otherwise: TS2686 says `debug` is a UMD global, and TS2693 says `string` only refers to a type. temper/addons/types/eso holds 41 declaration files totalling 481,684 bytes, of which generated/enums.d.ts is 246,745 and generated/functions.d.ts is 131,887, both far past the 15,000 byte ceiling; `ops eso generate-typings` writes them from ESOUIDocumentation.txt and check-eso-typings-fresh pins them to API version 101050. The other three level-0 libraries reach the same surface: lib-media-provider reaches CALLBACK_MANAGER, IsConsoleUI, SOUNDS, ZO_DeepTableCopy and d; lib-async reaches GetFrameTimeSeconds, GetGameTimeSeconds, GetFramerate and GetTotalUserAddOnCPUTimeAvailableEachFrameMS; lib-gps reaches the world-map API. No `.eso-addon.ts`, `.eso-interface.ts` or `.lua-module.ts` file is under akasha today, so no addon has yet landed and this is the first measurement of the gate. Three mends are open. The generated typings could land as akasha modules carrying `declare global`, which puts twenty thousand game globals into the same program as the web code. SETTINGS could name a Lua types entry, which reaches just as far. The API could become modules that are imported rather than globals, which costs a rewrite of every call site across 63 packages and drops the freshness check. Secondary and fixable by any seat: akasha refuses PascalCase functions and lower-camel module constants in this code, 18 and 7 times here.",
} as const satisfies Finding
