import type { Finding } from "../finding.page-type.ts"

export const noToolHereCanRenameAPropertyOnAPageThatMoved = {
  id: "01a060e6-791c-7c13-a833-7c8949d778a0",
  pageTypeSlug: "finding",
  slug: "no-tool-here-can-rename-a-property-on-a-page-that-moved",
  domainSlug: "domain/akasha-migration",
  claim:
    "`page rename-property` gathers all 133 of Alan's moved days now and refuses on them by name, where before it gathered none and reported a rename done over nobody. It refuses because it can neither read a key a TypeScript page declares nor land a change to one, so no property on `daily-tracking` is renamable by any tool here. The call taken: refuse rather than rename the markdown half, which is what the silent skip did.",
  evidence:
    'Measured 2026-09-02 by running, against the checkout as it is and against an isolated tree holding copies of the 133 days.\n\nWhat it does now: `bun tools/rename-property.ts --page-type daily-tracking --old safety-level --new safety-rung --dry-run` exits 1 naming all 133 day pages. `carriersOf` answers 0 carrying and 133 unread. Before the repair in `11c7a265f3` it answered 0 carriers and the command printed "0 page(s) carry the key, resolved through the page type system" and would have landed.\n\nThe markdown half is unmoved by the same measurement: 2111 carriers for `key` on `page-property-definition`, 366 for `extends-slug` on `page-type`, 0 unread for either.\n\nTwo things are missing, and they are different acts. Reading is one: a key on a TypeScript page is camel and sits in an object literal, so `blockOf` and `frontmatterKeyAt` read nothing there, and what would read it is the pages system\'s own page value rather than a frontmatter parser. Landing is the other: `land` in tools/lib/command.ts composes a git commit itself, and a page under `akasha/` is written by `akasha write`, which gates and commits for itself. A rename spanning both halves is one act that has to reach two writers, and nothing here says how.\n\nThe deleted finding on this named the wrong line. It said the days were dropped by `blockOf` at :222-223. Measured before the repair: `claimant` refused all 133 at :218-219 with "its name carries no page type", and `blockOf` was never reached for one of them.\n\nWhat was left alone deliberately: `pageTypeOf`, whose module page is `markdown-page-type` and whose definition is "the page type a markdown file\'s name carries". The akasha half went beside it as `typeSlotOf`, asked by `claimant`, which is the one call here holding both a path and the set of page types the akasha rule needs. 11 further call sites ask `pageTypeOf` directly and still read the markdown half alone.',
} as const satisfies Finding
