import type { Finding } from "../finding.page-type.ts"

export const nothingHoldsThePackagePagesToTheWorkspace = {
  id: "01a0608e-e175-73bd-ae3e-dd4a4c642564",
  pageTypeSlug: "finding",
  slug: "nothing-holds-the-package-pages-to-the-workspace",
  domainSlug: "domain/akasha-migration",
  claim:
    "`pages/package/` is read hourly and never held to the workspace it describes. Five audits reach all 135 pages through the page-type list, and no audit asks whether the package is still there, so a page outlives its folder unseen. 77 stale pages were swept on 2026-09-01, 13 more accrued inside a day, and those 13 came down on 2026-09-02. No akasha check can close the gap, so the guard would have to be a sixth audit, and that was declined because the population it would hold is draining.",
  evidence:
    "Swept 2026-09-01: 77 of 232 pages failed three tests \u2014 folder absent, specifier unreached, named as a parent by no page. All 77 went.\n\nRe-measured 2026-09-02. 135 pages were there and 13 failed those same three tests, every one under `temper-`: game-crafting-capture-addon, game-trading-post-addon, game-trading-pricing-client, player-build-validation, player-economics-core, player-quests-addon-cli, shared-build-deploy-addon-bundle-runtime, shared-capture-core, shared-capture-datamining-reader, shared-capture-perf, shared-engine, shared-foundation-misc-codec, shared-interface-hud-scene-catalog. Since the sweep 29 temper packages were torn down and 28 of them held a page. 15 teardowns took the page down and 13 left the page behind.\n\nThe pages are read. `pages/workstation-service/audits-watchdog.workstation-service.md` is enabled hourly, and `tools/audits/audits.ts` names five audits reaching them through the page-type list rather than by path: domain-edges, pages-hold-properties, pages-hold-shape, pages-named-as-stated, relations-resolve. The selection `pages-hold-shape` judges answers 55,128 pages over 368 page types, 135 under `pages/package/`. No reader asks whether the workspace is there, which is why searching for the literal `pages/package` answers no reader at all.\n\nNo akasha check can ask either: a check is handed only paths beginning `akasha/`, so one written for this would read green forever. See a-check-guarding-outside-akasha-reads-green.\n\nDecided 2026-09-02. The 13 came down at a443a0c8ca. A sixth audit was weighed and declined: the population it would hold is draining as the migration empties `temper/`, and 91 of the 122 pages left are temper. What closes the gap instead is the teardown taking the page down in its own commit, which 15 of 28 already did. If the count climbs again once that habit is written down, the audit earns its place.",
} as const satisfies Finding
