import type { Finding } from "../finding.page-type.ts"

export const nothingHoldsThePackagePagesToTheWorkspace = {
  id: "01a0608e-e175-73bd-ae3e-dd4a4c642564",
  pageTypeSlug: "finding",
  slug: "nothing-holds-the-package-pages-to-the-workspace",
  domainSlug: "domain/akasha-migration",
  claim:
    "Nothing holds `pages/package/` to the workspace the tree describes. 77 of its 232 pages named packages the akasha migration deleted, and no check refuses such a page: no audit, no cluster check and no akasha code check names `pages/package` or `*.package.md`. The tree also carries no page for any of the 141 workspace packages under `akasha/`, so a package recreated inside akasha drops out of the domain tree the `package` page type builds.",
  evidence:
    "Swept 2026-09-01. `pages/package/` held 232 markdown pages. Mapping each page slug onto a workspace folder path, 77 slugs matched no folder holding a `package.json`: 25 under `temper-`, 36 under `shared-` and 16 under `alanwalton-`. Each of the 77 was checked three further ways before deletion. The folder was absent. The package specifier the slug spells, `@temper/catalog-core` and its like, reached no manifest and no source file, only the prose of findings. And no page anywhere carried `domain-parent-slug: package/<slug>`. All 77 were deleted, and `pages/package/` now holds 155 pages with no stale one among them.\n\nThe 25 temper deletions are the twelve `@temper/game-*-capture-core` pages, six `game-*-capture-host` pages, `temper-catalog-core`, `temper-catalog-host`, `temper-shared-capture-host`, `temper-shared-capture-descriptor`, `temper-shared-saved-variables`, `temper-shared-interface-lam` and `temper-game-characters-capture-core`. Two of the 25 were torn down while this sweep ran, which is how fast the tree ages under the wave.\n\nNothing keeps it honest. Searching the repository for `pages/package` and for `package.md`, leaving out `pages/` itself and the findings, answers no audit, no cluster check and no akasha code check. `pages/page-type/package.page-type.md` gives a package page `files: akasha:**/*.package.md` and says a package's files are read off the workspace declaring them, so a page whose workspace is gone has no files and no way to report the absence.\n\nThe other half of the gap: 141 `package.json` files sit under `akasha/` and not one has a page under `pages/package/`. 56 of those are the `temper-*` packages this wave recreated. Outside akasha 190 workspace packages answer to 155 pages, and most of the 35 without one are web apps, which take a `web-app` page instead.",
} as const satisfies Finding
