import type { Finding } from "../finding.page-type.ts"

export const oneFreshnessRefusalCoversAStaleRecordAndAPartialReadAndNamesOnlyOne = {
  id: "01a068f5-7f47-7ff0-bebd-59b45ef78c63",
  pageTypeSlug: "finding",
  slug: "one-freshness-refusal-covers-a-stale-record-and-a-partial-read-and-names-only-one",
  domainSlug: "domain/akasha-migration",
  claim:
    "The moved-on-disk refusal at landing.module.code.ts:280 has two causes and its wording names only the first, so the remedy it implies is wrong half the time. `sameBody` at reading.module.code.ts:118-121 returns false on either of two grounds: the recorded body differs from the disk, or `partly(held)` is true, which holds whenever the reading carries a `readThrough` and is therefore true for any file delivered in runs rather than whole. The first is cleared by reading the file again. The second is not, because reading again in runs records another partial reading; it is cleared only by taking the body whole. The refusal says the disk disagrees with what was read, which describes the first cause and misdescribes the second as disagreement when the real defect is incompleteness.",
  evidence:
    "Traced end to end while writing up a related hazard, and every line was opened rather than taken on report.\n\nThe predicate, at akasha/command-system/reading/reading.module.code.ts:118-121, is `if (held === null || partly(held)) return false` followed by `return held.oid === oid || held.mechanicalOid === oid`. The first line is an unconditional refusal for a partial reading: no comparison against the disk happens at all, so no state of the file can satisfy it. `partly` at :73 is `held !== null && reachOf(held.readThrough) !== null`, and `reachOf` at :67 admits any positive integer.\n\nThat the partial road is reachable rather than theoretical: akasha/command-system/commands/read/read.command.code.ts:333 writes `readThrough: reachedTo(long.run)` when a long file comes back in runs, and :208 and :210 both branch on `partly` when deciding what a later read answers. The read command truncates at 28,000 bytes per answer without breaking a file partway, so any file over that ceiling is read in runs and every one of them records a partial reading.\n\nThe caller: `movedOnDisk` at akasha/command-system/change-freshness/change-freshness.module.code.ts:8 blob-ids what is on disk and asks `sameBody` for each recorded reading, collecting the failures; landing.module.code.ts:280 turns each into a refusal saying the disk holds something other than the body that was read, and adds a tail telling the writer to read them again.\n\nWhy the wording matters rather than being a quibble. For the stale-record cause the advice is right and one read clears it. For the partial cause the advice is wrong in a way that wastes a lane: reading again the same way records another partial reading, the refusal returns unchanged, and the writer has every reason to think the file is being changed underneath by another agent, because that is what the message describes and a swarm is running. The remedy is to take the body whole with `--full`, which the refusal never mentions.\n\nThe two causes are also told apart cheaply, which is worth writing down: a stale record is cleared by one read, so a refusal that survives a clean re-read of an unchanged file is the partial cause rather than the stale one.\n\nA third case already on file is neither, and is worth naming so it is not merged into these two: `a-stale-lockfile-record-locks-one-agent-out-of-the-root-manifest` records a path outside `akasha/`, where the read the refusal asks for cannot be run at all, the read command answering only for what is inside the folder.\n\nControls. `rg --no-ignore --hidden -l 'readThrough|partly\\(|sameBody' akasha/domain-system/findings/pages/` exits 1 with no hits, so none of this was already recorded, and the same search shape returns 30 finding pages for `landedMechanically`, so the instrument is sighted and the zero is real.",
} as const satisfies Finding
