import type { Finding } from "../finding.page-type.ts"

export const oneSetTableBlocksTheEquipmentPackageAndHoldsACodecIndex = {
  id: "01a060a8-6dfc-751b-bb25-80f079bfc2d4",
  pageTypeSlug: "finding",
  slug: "one-set-table-blocks-the-equipment-package-and-holds-a-codec-index",
  domainSlug: "domain/temper",
  claim:
    "temper/game-characters-equipment is otherwise ready for akasha: no `@temper/` import is left and 57 of its 58 source files are under the byte ceiling. The 58th, sets/generated/temper-set.generated.ts, is 1,362,516 bytes holding 707 sets in one literal, ninety-one times the 15,000 ceiling. `setsAll.ids` is the build codec's wire index, so splitting that table is the operation that already corrupted the crafted potion order. The package was left where the package was.",
  evidence:
    "Every `from` under temper/game-characters-equipment/src names @akasha/temper-formula-framework, @akasha/utils-narrow, or a sibling by relative path, so the closure is clear. The package manifest also declares @akasha/temper-skill-lines, which no file under src imports. Of the 58 source files, 57 are under 15,000 bytes and the largest of those is 11,653. The remaining file is sets/generated/temper-set.generated.ts at 1,362,516 bytes, keying 707 sets in one object literal with `no-set` first. Clearing the ceiling takes at least 91 modules of pure data.\n\nsets-all-data.ts spreads `setsFromPages.data` into SETS_ALL_DATA and hands the result to createDataFile, so `setsAll.ids` keeps the generated key order. temper/game-codec/src/character/build-codec-indices.ts line 64 takes setIds from setsAll.ids, line 112 sets SET_BITS to bitsNeeded(707), which is 10, line 154 builds setIndexMap, and getSetId(index) at line 346 turns a wire index back into a set id for build-codec v48 through v52. The generated file's own banner declares the invariant: `no-set` is sorted to index 0 by the generator so getSetId(index) finds the sentinel where the character codec expects the sentinel. The same index reaches the addons through temper/game-characters-capture-addon/src/generated/codec-constants.generated.ts and temper/game-companions-addon/src/generated/codec-constants.generated.ts, so a reorder would drift the addons as well, exactly as the crafted potion split drifted them.\n\n230 import lines in 83 files outside the package name @temper/game-characters-equipment, so recreating only the part under the ceiling would leave two copies of the sets with nothing keeping the two equal. Nothing was split and nothing was deleted.",
} as const satisfies Finding
