import type { Finding } from "../finding.page-type.ts"

export const oneInventoryReadingIsFiledUnderTwoMomentsWithTwoTotals = {
  id: "01a0675d-dda6-7352-b1c5-61ec83c8cb19",
  pageTypeSlug: "finding",
  slug: "one-inventory-reading-is-filed-under-two-moments-with-two-totals",
  domainSlug: "domain/temper-holdings",
  claim:
    "`totalValue` is not derived from the bytes it is filed beside. The captures 2026-08-19-23-46-47 and 2026-08-20-13-58-00 are byte-identical across all 3 shards and share one `meta.lastFullScan`, and their two snapshot pages state different totals, 516395436.74359727 against 516795362.2235968. That number was worked out at file time against price data outside the scan. It holds for every capture rather than this pair alone, and the 790 `temper-net-worth-hour` pages rest on it.",
  evidence:
    "Measured 2026-09-03 by sha256 over each of the 458 files under `pages/temper-inventory-chunk`, one file at a time: 458 files, 454 distinct hashes. Two of the four repeats are the three shards of 2026-08-19-23-46-47 matching the three of 2026-08-20-13-58-00 index for index, 900,002, 900,001 and 630,048 bytes, and the two concatenations hash the same. Walking `meta.lastFullScan` over all 151 parsing captures gives 150 distinct values, and the single collision is exactly this pair, at 1787234280.\n\nBoth snapshot pages are landed with a sidecar of 4,422 rows. With `id` removed from every row the two files hash the same. No row id is shared between them, so the recreation minted a fresh set for each and nothing links the two.\n\nThe retired `the-inventory-chunk-gap-is-already-closed-for-every-capture-that-parses` wrote `meta.lastFullScan`, 150 distinct values, one per capture, with 151 captures named on the same line. The measurement was right and the reading of it was wrong: the collision sat inside a sentence asserting there was none, and the 150 was never held against the 151 beside it. That is the part worth carrying rather than the duplicate itself, and it is the shape of a file count reported as a page count, which is how 16 currency pages were read as 17.\n\nWhy nothing caught it: a carriage proof runs per file, and a per-file proof cannot see a duplicate in what it carries, because both copies carry correctly. Closing that gap needs no second walk, only distinct digests against file count, and anyone who has already built a hash arm holds both numbers. A gap costing nothing to close is one that gets closed.",
} as const satisfies Finding
