import type { Finding } from "../finding.page-type.ts"

export const readingAComponentOffAReturnRefusesARealComponent = {
  id: "01a0629e-cbfa-71fb-8d2d-2b37e4438298",
  pageTypeSlug: "finding",
  slug: "reading-a-component-off-a-return-refuses-a-real-component",
  domainSlug: "domain/akasha-check",
  claim:
    "Reading a component off what a function answers with, rather than off JSX anywhere in its body, refuses `BlockAccessoryBar`, a real component whose element is opened at `block-editor.module.code.tsx:248`, because it answers with `createPortal(<div/>, target)`, a call rather than JSX. Measured over 20,625 files that rule lifts 2 refusals and adds 2. A narrower one, JSX held as an object literal property value being data, lifts the same 2 and adds none.",
  evidence:
    "Measured 2026-09-02 against the check's own `refusedIn` over every `.ts` and `.tsx` git tracks under `akasha/`, 20,624 files, together with `shared/pages-ui/src/components/use-app-nav-items.tsx`. A seeded file whose function answers with `{ slot: <p/> }` flipped under all three rules, so the instrument sees a flip rather than reporting clean.\n\nThree refusals hold today. `error-capture-installer.module.code.tsx:16` `ErrorCaptureInstaller`, which holds no JSX and whose element is opened in seven other files, is a live instance of `a-component-is-read-from-its-body-rather-than-from-its-callers`. The other two are `use-app-nav-items.tsx:44` `useAppNavItems` and `:197` `toNavItem`.\n\nRule A, a component is what a function answers with, unwrapped through parens, casts, conditionals and logical operators: 3 files flip, 4 refusal lines. It lifts both on the hook. It adds `ProcessSelectChildren` at `select-control.module.code.tsx:90`, a helper called with three positional arguments whose element is opened nowhere, so that one is a correction. It adds `BlockAccessoryBar` at `block-accessory-bar.module.code.tsx:40`, and that one is wrong.\n\nRule B, A widened by one level of call arguments: 2 files, 3 lines. `BlockAccessoryBar` is rescued and `ProcessSelectChildren` remains.\n\nRule C, JSX held as an object literal property value is data rather than an element the function makes: 1 file, 2 lines. It lifts exactly the two on the hook and adds nothing anywhere in the tree. All 42 of the check's own tests hold under each of the three.\n\nNone was made. The check's own page says at line 58 that a function whose body holds a JSX element is judged a component, so every rule here alters what the check refuses, which `Alan Approves Checks` reserves. `the-tsx-blindness-has-two-halves-and-one-widens-safely` was filed rather than made for the same reason.\n\nThe file lands under the check as it is if its JSX is written as `createElement` calls instead, measured on a reduction of it.",
} as const satisfies Finding
