import type { Finding } from "../finding.page-type.ts"

export const retiringTheWritesLayerLeaves105Of126GeneratorsCallerless = {
  id: "01a062e8-8dde-703b-ac31-cdc2380144a5",
  pageTypeSlug: "finding",
  slug: "retiring-the-writes-layer-leaves-105-of-126-generators-callerless",
  domainSlug: "domain/temper",
  claim:
    "Retiring tools/lib/temper-addon-data would leave 105 of the 126 generators callerless rather than all 126. 55 have a caller today and 71 have none; 34 of the 55 are reached only from the writes layer, while 21 keep callers elsewhere under tools/. The command body must still land first, but the loss the retirement threatens is a third of the population rather than the whole of it, and the survivors are named here so nobody re-derives them under time pressure.",
  evidence:
    "Measured 2026-09-02 at commit 01f072a1a2, parsing with the TypeScript compiler's preProcessFile rather than grep, because quotations of a specifier inside template literals outnumber real imports here by roughly twenty to one, and because Bun.Transpiler.scanImports silently drops import type.\n\nDENOMINATORS, PRINTED AND NON-ZERO. 28,086 files walked off the filesystem, not from git ls-files, so no index failure can hand back a zero off an empty population. 28,086 parsed, 0 failed. 59,091 import specifiers seen. 126 generator module folders found. A seeded pair of specifiers, one of them import type, was planted and both were found, so the instrument is not blind to its subject.\n\nTHE COUNT. 55 of 126 modules have at least one importer through the @akasha/temper-addon-generators specifier; 71 have none. All 28 importing files are under tools/ and none is under akasha/, which is what makes the command body a precondition for the retirement.\n\nTHE BLAST RADIUS. 13 of the 28 importers are inside tools/lib/temper-addon-data and 15 are outside it: tools/addon-data-proof.ts, tools/companion-tables-regenerate.ts, tools/equipment-trait-tables-regenerate.ts, and 12 files under tools/cand. Because those 15 survive, only 34 of the 55 lose their last importer when that folder goes. Callerless would move from 71 to 105 of 126.\n\nWHY IT MATTERS. The plan this seat was given says the retirement takes all 126 to callerless. That over-states it by 21 modules. The direction of the correction is the dangerous one: a smaller blast radius invites doing the retirement earlier, and 34 modules going quiet is still a pipeline that is absent rather than broken.",
} as const satisfies Finding
