import type { Finding } from "../finding.page-type.ts"

export const sevenAkashaReadersAskTheMarkdownQueryRoadForPageTypesItCannotReach = {
  id: "01a06932-0222-720c-9760-bd3070049557",
  pageTypeSlug: "finding",
  slug: "seven-akasha-readers-ask-the-markdown-query-road-for-page-types-it-cannot-reach",
  domainSlug: "domain/akasha-migration",
  claim:
    "`answer()` in `tools/lib/page-query.ts` reaches only four markdown page types — `alert`, `daily-tracking`, `food-entry` and `message`. The seven akasha modules importing it ask for `pipeline`, `workflow`, `step` or an exercise policy type, and it answers `null` for every one. Those page types hold no rows on the akasha index either, so repointing these seven loses no value and is owed under the constraint removing the markdown system. `ci-reaper-step-pages` makes that `null` a throw, so the repoint also takes out a trap.",
  evidence:
    'Measured 2026-09-03 at commit f6c7099dfc, in this checkout, roots `{akasha: /var/home/walton/repos/akasha}`.\n\n`backedTypes(roots)` (`tools/lib/page-query.ts:217`) answers four: `alert`, `daily-tracking`, `food-entry`, `message`. `reaches(roots, type)` is false and `answer(roots, {pageType: type})` is `null` for `pipeline`, `workflow`, `step`, `selection-policy`, `exercise-selection-policy`, `session`, `seat-conditions` and `wake-day`. Controls: `daily-tracking` answers n=135 and a page type nobody has, `nonesuch-xyzzy`, answers `null`, so the probe discriminates. The record named five reachable types including `seat-conditions`; that one has since gone, so it is four.\n\nThe nine importers of `tools/lib/page-query.ts`: `tools/lib/page-query-answer.ts` and `tools/lib/workflow-dsl/discovery.ts` inside the block, and seven under akasha — `alan/fitness/exercise-access/selection-policy`, `changes/pipelines/creator-page-reading`, `changes/pipeline-orchestration/pipeline-page-rows`, `changes/pipeline-sweep/sweep-page-reading`, `infrastructure/commands/pipeline-page-reading`, `infrastructure/ci-containers/ci-dispatch-candidates` and `infrastructure/ci-containers/ci-reaper-step-pages`. All seven spell `@tools/lib/page-query` with no extension, which a census spelling the extension misses.\n\n`everyOfType`, `slugsOfType` and `valuesOfType` from `@akasha/indexes` each answer 0 for `step`, `pipeline` and `workflow`. Controls both ways: `subagent` answers 300, `nonesuch-xyzzy` answers 0. So neither road holds these rows and the before and after of a repoint is zero against zero — which is what makes these seven the cheap ones to move.\n\n`ci-reaper-step-pages.module.code.ts:37-42` makes the `null` a throw. Called directly: `stepsByContainerName(roots, [])` and `pipelineStatusBySeq(roots, [])` answer 0 without throwing, which is the empty-input return and proves the module loads and runs; `stepsByContainerName(roots, ["any-container-name"])` and `pipelineStatusBySeq(roots, ["1"])` both throw ``\\`step\\` names no page type whose pages are files``. Above it, `akasha/changes/steps/container-reaping` reaches `@akasha/ci-containers/ci-reaper-tick`, which calls both at `ci-reaper-tick.module.code.ts:50` and `:58`. It is armed rather than firing: with no pipeline pages there are no container names to hand it, so the empty-input return is what runs today.\n\nNot settled here: whether each of the seven runs on the workstation or off it, which is what decides between the direct functions and `pages-system-service`.',
} as const satisfies Finding
