import type { Finding } from "../finding.page-type.ts"

export const symbolParityClearsAnEntryPointScriptByComparingNothingToNothing = {
  id: "01a06882-e4e3-74f4-90bb-cd64b8cfefc0",
  pageTypeSlug: "finding",
  slug: "symbol-parity-clears-an-entry-point-script-by-comparing-nothing-to-nothing",
  domainSlug: "domain/akasha-migration",
  claim:
    "Symbol parity is the swarm's usual gate for ablating a carried file: take the exported names on each side and ablate where the old set is covered. Over the fifty monarch originals two files exported nothing at all, because an entry-point script keeps its work in module scope and behind import.meta.main. For those the gate compares an empty set to an empty set and reports the strongest verdict it has. A script is exactly the file whose loss is least visible, since nothing imports it and only a timer or a person runs it. The gate is most confident precisely where it knows least.",
  evidence:
    "Measured over monarch/ before ablating it. Of the fifty tracked files, forty-seven carried a non-empty export set and matched their successor's. monarch/agree.ts and monarch/propose.ts exported nothing: agree.ts is 177 lines of claims printed as they are weighed, propose.ts is 58 lines ending in an import.meta.main block. Both cleared a symbol-parity gate on 0 names against 0 names.\n\nWhat settled them was running them. propose.ts and its successor printed 1,100 lines each, differing on one line and only in the timestamp in the header. agree.ts differed by design: its synthetic twelve-row half had been moved into the rules module's own test, and its live half printed the same 104 rules over 11,018 transactions and the same 205-of-205 three times. The moved half was located by its fixtures rather than its prose, since E-not-a-leg, B-leg-1 and C-leg appear in exactly one file in akasha, and it now stands as 18 passing tests.\n\nThe same pass showed what symbol parity does not see in the other direction. Repointing each original's imports to the successor convention and running both sides through formattedBody at one path proved 42 of 49 byte-equal, and reduced the rest to six differences that were each read: prose and error text naming a module rather than a file, evidence's usage line, seat's path constants, rules' import of a renamed module, and land-files trading tools/lib/gated-landing for landedMechanically. That check also caught a rename symbol parity would have survived without noticing, monarch/merchant.ts having carried as monarch-merchant-naming.\n\nThis is the shape already filed for the check harness as not-applicable-over-a-zero-population-is-the-one-verdict-nothing-catches, arriving in a gate whose false green destroys a file rather than skipping a check. What answers it is that a zero-name comparison is no evidence and should be refused rather than passed, sending the file to a behavioural check instead.",
} as const satisfies Finding
