import type { Finding } from "../finding.page-type.ts"

export const temperWebModulesLandFlatAndDotServerIsTheOneException = {
  id: "01a06428-7ccb-7b6c-ae29-024698992ecb",
  pageTypeSlug: "finding",
  slug: "temper-web-modules-land-flat-and-dot-server-is-the-one-exception",
  domainSlug: "domain/temper",
  claim:
    "temper-web modules land flat, at `temper-web/<slug>/<slug>.module.ts`, and `temper-web/.server/` is the one exception. The ruling was needed because nothing refuses either depth: a part slug names a module by its slug wherever the folder sits, so four seats grouped their components three ways and every check passed. Anyone reading the flat rule and applying it to `.server/` would dissolve a bundler boundary that throws rather than warns.",
  evidence:
    'The count behind the ruling: of 5,196 module pages outside temper-web, 4,785 sit one level below their package root, so grouping is legal and is the 8% minority. Imports inside a package are always relative, so depth is visible to every importer; flat makes a sibling import `../<slug>/<slug>.module.code.tsx`, derivable from the slug alone.\n\nBefore the ruling, completion landed under `temper-web/components/completion`, keeping the level `appDirectory: "."` maps from the source; the companion groups landed under `temper-web/<group>`; `components/ui` was landing deep as well. Nothing refused any of them. `temper-web.router-app.ts` names them all alike whatever the depth, as a flat sorted list of `module/<slug>` that grew from 22 entries to 168 lines while four seats landed into it.\n\nThe exception is load-bearing. `@react-router/dev/dist/vite.js` matches `serverDirRE = /\\/\\.server\\//` on the path as well as `serverFileRE` on the file name, and throws `Server-only module referenced by client`. akasha\'s naming grammar reads the base name only, so `.server` suits both systems at once. Eleven slugs are in scope there, five of them landed.\n\nFlattening the 60 completion modules changed no byte: the sibling imports were already `../<slug>/<slug>.module.code.*` and both ends came up a level together, so `akasha move` answered `no file naming what moved needed repointing` and the bytes hashed the same before and after. None of the 60 belongs in `.server/` or reaches into it.\n\nA move is judged by nothing: `a change-mechanical change runs no check, so this landing was judged by none`. What proved the flattened tree ran afterwards — the carried test passed at its new path, the 60 slugs were checked against the router-app, an unchanged body carrying five sibling imports passed 28 checks at the new depth, and a seeded TS2322 was refused there, which is what says the typecheck was looking rather than absent.',
} as const satisfies Finding
