import type { Finding } from "../finding.page-type.ts"

export const temperWebLandedUnstyledBecauseItsTailwindEntryIsNotOneOfTheFourNamedFiles = {
  id: "01a06409-36cc-7801-a40b-5ffc24ed50b6",
  pageTypeSlug: "finding",
  slug: "temper-web-landed-unstyled-because-its-tailwind-entry-is-not-one-of-the-four-named-files",
  domainSlug: "domain/temper",
  claim:
    '`akasha/temper/temper-web` landed with its `root.tsx` importing `@akasha/design-system/styles.css` in place of the temper entry it had. `temper/web/app/globals.css` is 43 lines carrying `@import "tailwindcss"`, a katex import, twelve `@source` globs relative to `temper/web/app/`, and an `@theme` block. Until it crosses as its own stylesheet page with those globs rewritten, every Tailwind utility class and the whole temper theme are unstyled.',
  evidence:
    "Landed 2026-09-02 at `d16bff5292`, 40 checks over 8 paths, none refused. The seat named this the largest single loss of the recreation and it is right.\n\nThe reason is structural rather than an oversight. The new `router-app` page type declares four named file properties — `root.tsx`, `routes.ts`, `entry.server.tsx`, `react-router.config.ts` — because those four are names React Router fixes and akasha's file-name grammar cannot build. `globals.css` is none of them. It needs a page of its own, and the precedent is settled: ten `*.stylesheet.styles.css` files already sit beside their `*.stylesheet.ts` pages under `akasha/design/system` and `akasha/alan/chess`. The work is not inventing a shape, it is the twelve `@source` globs, each of which points at `temper/web/app/` and would have to name the new tree.\n\nFour smaller departures came with the same landing, and I am recording them here rather than as four pages, because three of them are not losses and one is trivial. My call, and the reasoning:\n\nThe `rel=preload` hint for the Geist woff2 is a real but slight loss — akasha already serves that exact font through an `@font-face` in `design-look.stylesheet.styles.css`, so only the preload went, and no `?url` import exists anywhere under `akasha/`.\n\nThe side-effect import of `~/action-verbs/declared-effects` is deferred, not lost: the file belongs to the components migration that has not run.\n\nThe manifest's `build`, `dev`, `start`, `typecheck`, `lint` and `test` scripts did not cross because **zero of the 241 manifests under `akasha/` carry a `scripts` key**. That is a property of akasha, not a thing temper lost.\n\nThe `AppLoadContext` nonce augmentation was replaced by narrowing at the boundary rather than carrying a `declare module` into a route file. That is an improvement and I am not filing it as a loss.",
} as const satisfies Finding
