import type { Finding } from "../finding.page-type.ts"

export const theArrowPropertyRewriteCollidesThirtyFiveNamesNotTwo = {
  id: "01a060ce-5012-76e6-975d-49f01e37b83e",
  pageTypeSlug: "finding",
  slug: "the-arrow-property-rewrite-collides-thirty-five-names-not-two",
  domainSlug: "domain/temper",
  claim:
    "Two ESO methods were known to have lost their overloads. Parsing the whole landed set against its source finds 35 cross-file collisions the migration introduced, 21 of them losing a call shape. Seven collide with the TypeScript standard library rather than a sibling file, and three of those are Object.keys, Object.values and Object.entries, so any program holding tstl-language-extensions refuses the ordinary form of each.",
  evidence:
    "Measured at 3cb5dfe by ts.createProgram with strict over the 102 source .d.ts under temper/addons/types and, separately, the 100 landed .type-declaration.d.ts. The source answers 17 diagnostics, the landed set 68. TS2717 rises 2 to 23, TS2451 rises 5 to 21, TS17020 rises 0 to 17; TS2300 and TS2314 fall by 3, the deliberate LinkStyle and InstanceType drop.\\n\\n45 names are declared in two akasha files in a colliding form. 10 already collided in the source (eight CT_ constants, SI_MAPFILTER8, LibCodesCommonCode). Of the 35 introduced, 11 are legal because the two arrow properties agree, 3 are hard TS2451 with nothing lost (ZO_CheckButton_SetLabelText, ZO_Tooltip_AddDivider, ZO_CheckButton_SetToggleFunction), and 21 lose a call shape: BackdropControl.SetCenterColor, SetCenterTexture, SetEdgeColor, SetEdgeTexture; ButtonControl.SetState; Control.SetDimensionConstraints, SetHandler; EditControl.SetColor, SetDefaultText, SetDefaultTextColor, SetFont, SetMaxInputChars, SetText; KeybindStripObject.AddKeybindButtonGroup, RemoveKeybindButtonGroup; TextBufferControl.AddMessage; ZoColorDefClass.New, three signatures down to one; LibCodesCommonCodeApi.GetLibAddonMenu; SecurePostHook; ZO_ClearTable; ZO_PostHook. SetHandler and SetState were still broken at this commit.\\n\\nThe widest reach is against the standard library. tstl-language-extensions lines 111 to 115 augment ObjectConstructor for Lua iterables; as methods they merged with lib.es5 and both forms bound, as arrow properties they replace it and answer three TS2717. eso-timers turned the void returners clearTimeout, clearInterval and queueMicrotask into declare const and each now redeclares a DOM global, while setTimeout and setInterval return number, were left as declare function, and merge cleanly. print does the same in tstl-eso-sandbox.\\n\\nSame-file overload stacks all survived as overloaded object types, so only cross-file merges broke. Every site and signature is in scratchpad/ember/DECL-PROVENANCE.md.",
} as const satisfies Finding
