import type { Finding } from "../finding.page-type.ts"

export const theCompletionDataIsLandedAsEntriesAndChecksEqualToTheGeneratedModules = {
  id: "01a0634c-b246-7000-9b24-aec03d69477b",
  pageTypeSlug: "finding",
  slug: "the-completion-data-is-landed-as-entries-and-checks-equal-to-the-generated-modules",
  domainSlug: "domain/temper",
  claim:
    "The completion transforms are not blocked on their data. All eleven generated tables are in akasha as pages carrying `page-property-entry` rows, checked equal to the legacy modules leaf by leaf. What scores zero is the symbol names rather than the data: `collectiblesData` is 130 `temper-collectible-category` pages with a `collectibles` jsonl beside each. A transform reads them through `askComposed`, which answers each entry property as an array.",
  evidence:
    "Measured at 8e9a75deb6: 26,370 leaves compared across 11 tables, 0 differences. Each leaf carries its ancestors, so the grouping is compared as well as the leaf. cadwellData 78, poiData 2,077, questData 2,253, zoneCompletionData 3,795, collectiblesData 12,906, tributeData 48, antiquityData 751, traitResearchData 324, accountAchievementData 3,775, characterAchievementData 66, shalidorLibraryCollections 297.\n\nThe legacy modules were imported; the akasha side was read from the page files with their jsonl. The two traversals share nothing, since the landed keys differ from the legacy ones (`esoCollectibleId` against `id`) and collectibles is 130 leaf pages against 16 legacy categories.\n\nThe comparator was made red before it was believed. A one-character change to one leaf's last field turns each of the 11 tables red at differences=2; dropping a leaf gives 1, duplicating one gives 1. A control asking for a property slug that is not there answers 0 files over 0 rows, so the landed side does read the disk.\n\nTen tables were already landed under `akasha/temper/temper-catalog/temper-pursuits` and `temper-world/world-zones`. The eleventh, Shalidor's Library, landed here as page type `temper-lore-collection` at 71b9665bb4 and 8e9a75deb6: 29 collection pages, 297 book rows.\n\nA consumer reads them with `askComposed` from `@shared/pages-query/ask`. A POST to /ask naming page type `temper-lore-collection` answered rows whose `books` key is an array of the jsonl lines in file order. `asking` resolves that at page-asking.module.code.ts:191 through `entriedValue`, which a script may also call directly with no index.",
} as const satisfies Finding
