import type { Finding } from "../finding.page-type.ts"

export const theMarkerFormOfEditCannotExpressAPassageEndingMidLine = {
  id: "01a0622d-203c-74fc-9551-35f4255cf4a0",
  pageTypeSlug: "finding",
  slug: "the-marker-form-of-edit-cannot-express-a-passage-ending-mid-line",
  domainSlug: "domain/akasha-system",
  claim:
    '`akasha edit` reads passages from the input as marker blocks, and `linedOf` in `piping.module.code.ts` keeps each line\'s terminator, so `old.join("")` always ends a passage at a line end. A passage ending mid-line matches nothing and is refused as matching no passage while its text is plainly in the file. The `--old-file`/`--new-file` form carries the bytes exactly and repeats under one `--file-path`, so the capability is there and one input form lacks it.',
  evidence:
    "Read out of the source on 2026-09-02 rather than reproduced by running it, so the mechanism is traced and the refusal is reported second-hand from the agent who met it.\n\n`akasha/command-system/piping/piping.module.code.ts`, `linedOf` at line 128, slices each line as `said.slice(from, at + 1)` — the terminator is kept. `passagesIn` at 156 pushes that same `line` into `old`, and closes the block with `old.join(\"\")`. The last line of a passage is always followed by the split marker on its own line, so it always carries a newline, and there is no way to write a marker passage that ends mid-line.\n\nThe matcher itself has no such limit. `working` in `akasha/command-system/command/edit/edit.command.code.ts` calls `counted` and `substituted`, both plain `body.indexOf(said)`, and a passage read from `--old-file` is the file's bytes untouched.\n\nSo the workaround is not one substitution per commit, which is what the agent who met this concluded. `readIn` accumulates: a `--file-path` opens an entry, and every `--old-file X --new-file Y` pair after it appends to that entry's `stated` list, which `working` then applies in order. Several mid-line substitutions in one file land in one call and one commit, byte-exact.\n\nWhat it cost: an agent amending a page whose properties are long single-line strings read the refusal, concluded `edit` allowed one substitution per commit, and took a whole-file `akasha write` instead. Under a swarm that is the trade the brief warns against, because a whole-file body overwrites whatever another lane landed between the read and the write. The call was defensible on its own facts — a six-minute-old file nobody else was touching — but it was taken to route around a limit that is not there.\n\nThe mend is either to let a marker block say its passage ends mid-line, or to have the refusal name the file-pair form when the passage it was handed differs from the file only by a trailing newline. The second is smaller and catches the case at the moment it bites.",
} as const satisfies Finding
