import type { Finding } from "../finding.page-type.ts"

export const theFormattersInflationIsPredictableBeforeTheWrite = {
  id: "01a061a9-f299-7107-8fa1-7a1599d42b21",
  pageTypeSlug: "finding",
  slug: "the-formatters-inflation-is-predictable-before-the-write",
  domainSlug: "domain/temper",
  claim:
    "The inflation akasha's formatter adds is reproducible outside akasha, so a division can be packed to the byte ceiling exactly rather than at a guessed ratio. The gear set table inflated by 1.13 rather than the 1.5 that `the-file-size-ceiling-is-read-after-formatting-not-before` offers as the number to hold to, and a budget set by 1.5 would have made about 190 parts where 124 hold. A printer at the formatter's fixpoint is checked for free against bodies akasha has already landed.",
  evidence:
    "Measured 2026-09-02 while dividing temper/game-characters-equipment/src/sets/generated/temper-set.generated.ts, 1,362,588 bytes over 707 rows, into 124 modules under akasha/temper/temper-characters-equipment.\n\nA printer reproducing biome's object and array layout was checked against bodies akasha had already formatted, which is a free oracle: all 37 of akasha/temper/temper-completion/lore-collections-00 through 36, 433,173 bytes, came back byte for byte. It then predicted 124 part bodies and their gatherer, and all 125 landed byte-identical to what was handed in, across commits 5d0ba6878e to cce085ad65. Only the two hand-written modules in the same landing were reformatted, and only their import order moved.\n\nThe rules that matter are prettier's: an object literal is flat where it fits in 100 columns and expanded otherwise, an array the same, a key whose sibling needs quotes keeps its own quotes, and the quote chosen is whichever needs fewer escapes. One rule was missing on the first attempt, and the first landing is what exposed it: where a property's value is a string too long to fit, the break goes after the colon and the string sits at two more spaces of indent. That costs exactly 10 bytes each time. Parts 000 and 001 grew by 30 and 40 bytes, for three and four such strings.\n\nThe formatted table came to 1,538,622 bytes against 1,362,588 raw, a ratio of 1.129. The 1.5 in the earlier finding was measured on icon shards, where one long line per icon breaks into one line per keyword; it is an upper bound for rows dense with prose rather than a constant. A raw budget of 13,800 bytes gave a largest landed file of 13,782 against the ceiling of 15,000.\n\nbiome cannot be run here, since block-biome refuses every call to it, reading as well as writing. So the printer was checked against landed bytes rather than against biome itself.",
} as const satisfies Finding
