import type { Finding } from "../finding.page-type.ts"

export const theTwoCompletionAddonsCycleThroughOneModuleAnUnlandedTypeHolds = {
  id: "01a060f0-4c35-70b3-8552-be81d1d2bb60",
  pageTypeSlug: "finding",
  slug: "the-two-completion-addons-cycle-through-one-module-an-unlanded-type-holds",
  domainSlug: "domain/temper",
  claim:
    "`player-completion-addon` and `game-characters-skills-morphs-addon` import each other, and the cycle passes through one module, `saved-variables`. The shape that breaks it is a third package both depend on, rather than a mutual dependency or one addon absorbing the other. That third package cannot land yet. `saved-variables` takes `CompletionOverride` from `@temper/player-completion`, which has not landed, so the one module that would break the cycle is also the one module blocked.",
  evidence:
    'Measured on 2026-09-02 against the whole of both packages, 98 TypeScript files.\n\nThe cycle. Four files of `game-characters-skills-morphs-addon` reach `../../../player-completion-addon/src/saved-variables` by relative path, carrying no package name, so no grep for a specifier finds them: `tracking/skill-morphs.ts:2`, `ui/task-auto-complete-skill-morphs.ts:1`, `ui/task-hud-skill-morphs.ts:18`, `ui/task-progress-resolver-skill-morphs.ts:13`. A fifth reach at `ui/task-progress-resolver-skill-morphs.ts:14` takes `TaskProgress` from `../../../player-completion-addon/src/ui/task-progress-resolver-types`, a 90-byte module holding one interface. Eight files of `player-completion-addon` import back by package name.\n\nWhy a third package. Every name the two packages share is one shape or one accessor: `getSavedVariables`, `TaskData`, `SavedCharacterEntry`, `TaskProgress`. A mutual dependency would make neither package landable alone and would need both in one commit; absorption would fold a feature that has its own core package into an addon that is not its own. Extraction moves six modules and leaves both addons depending downward.\n\nWhy it is blocked. `saved-variables.ts:5` states `import type { CompletionOverride } from "@temper/player-completion/completion-overrides"`, used at lines 47 and 209 to type two persisted fields. An akasha file may import no file outside akasha, and 16 of the 17 outside specifiers these two packages reach are unlanded.\n\nThe call taken: no duplicate `CompletionOverride` was written. A five-line interface defined twice is the collision that thirteen `declare global` modules just cost this initiative a day to undo.',
} as const satisfies Finding
