import type { Finding } from "../finding.page-type.ts"

export const theVscodeTypesShimCrossesOnlyWithTheExtensionThatResolvesIt = {
  id: "01a06558-bbb0-7005-ac39-7c4f4b32c540",
  pageTypeSlug: "finding",
  slug: "the-vscode-types-shim-crosses-only-with-the-extension-that-resolves-it",
  domainSlug: "domain/akasha-migration",
  claim:
    "`shared/vscode-typings` is reached by nothing that imports it. Its whole purpose is to be a workspace package literally named `@types/vscode`, so TypeScript resolves it automatically for the editor extension. Carried into akasha as a `type-declaration` page it would no longer be resolved, because a page's declaration file is named for its slug rather than presented under `@types/`. It crosses with the editor extension or not at all.",
  evidence:
    'Measured 2026-09-02. Two tracked files: `shared/vscode-typings/package.json` and `shared/vscode-typings/types/index.d.ts`. The manifest\'s own description says it is "the editor fork\'s own API, presented where a typecheck under akasha/ can find it". It declares `"name": "@types/vscode"`, `"version": "1.110.0"` and `"types": "types/index.d.ts"`, and no `exports`.\n\nNothing names it. `grep -rn vscode-typings` across `editor-extension`, `akasha/editor-extension`, `tsconfig.json` and `package.json` answers exactly one hit: `package.json:42`, the workspaces entry. So its whole reach is the automatic `@types/*` resolution TypeScript performs on the package name.\n\n`akasha/editor-extension/package.json:43` names `"vscode": "^1.85.0"`, which is what the shim answers for. The akasha page type that fits the content is `type-declaration` at `akasha/code-system/type-declarations/type-declaration.page-type.ts`, whose `ambient-types` property holds the `.d.ts` beside the page. Ten of them are already there under `akasha/temper/temper-lib-*`. But those are imported by name from the modules that need them — `notification-declarations` states the invariant "A file reaching a declared name imports this module for the declaration" — whereas nothing imports the vscode API; the compiler finds it by the package being called `@types/vscode`.\n\nThe call taken: left in place rather than moved. `editor-extension/` is mid-migration in another lane, and where the shim lands depends on where the extension\'s tsconfig ends up, which that lane settles. Moving it first would either break the resolution silently, which a typecheck would not catch while the old copy is installed, or force a guess at a path that lane is about to change. What is not established is whether akasha admits a package whose manifest name is `@types/vscode` at all; no page inside akasha carries a scoped manifest name outside `@akasha/`.',
} as const satisfies Finding
