import type { Finding } from "../finding.page-type.ts"

export const theLibDataEncodeGlobalIsNamedOnlyInsideTheLibraryThatMakesIt = {
  id: "01a06182-848e-76a6-a99b-2be37819e4cf",
  pageTypeSlug: "finding",
  slug: "the-lib-data-encode-global-is-named-only-inside-the-library-that-makes-it",
  domainSlug: "domain/temper",
  claim:
    "`temper-addon-library-types/lib-data-encode` names the shapes LibDataEncode hands back but never names the global itself. The only declaration of `LibDataEncode` in akasha is a private `declare global { var LibDataEncode: LibSurface }` inside `temper-lib-data-encode/data-encode-entry`, which is the package that assigns it. A consumer in another package therefore cannot see the name at all.",
  evidence:
    "Measured on 2026-09-02 while recreating TemperCombat. `temper/game-combat-addon/src/fight-data/saved-fights.ts` line 15 reads `const [LDE] = assert(LibDataEncode, \"LibDataEncode wasn't found\")`, and it carried its own `src/types/lib-data-encode.d.ts` declaring `declare const LibDataEncode: LibDataEncodeApi | undefined` to make that compile.\n\nThe shared set already holds `lib-data-encode`, so that private copy is exactly the duplication the shared set exists to stop. But the shared file declares only `LibDataEncodeDictionary`, `LibDataEncodeTestResult` and `LibDataEncodeSurface` — three shapes and no value. `grep -rn 'declare const LibDataEncode\\b'` over `akasha/temper` answers nothing; the one hit for the name as a value is `akasha/temper/temper-lib-data-encode/data-encode-entry/data-encode-entry.module.code.ts` line 7, `var LibDataEncode: LibSurface`, inside that module's own `declare global`.\n\nThe obvious mend — adding `declare const LibDataEncode: LibDataEncodeSurface | undefined` to the shared file — collides at TS2451 with that private `var` the moment the two compile together, and the library needs `var` because it assigns the global. So the mend is two-sided: the shared set names it, and `data-encode-entry` stops declaring it and assigns through `globalThis` instead.\n\nThe call taken: `temper-combat-addon/combat-saved-fights` reads it as `(globalThis as { LibDataEncode?: LibDataEncodeSurface }).LibDataEncode`, which needs no declaration and takes its type from the shared set. That is a workaround, not the mend, and it is one more consumer to revisit when the two-sided fix lands.",
} as const satisfies Finding
