import type { Finding } from "../finding.page-type.ts"

export const theEsoItemMineNeedsTwentyFourPagesAndNoShardFits = {
  id: "01a06086-b664-7947-a47d-074af9ca89e7",
  pageTypeSlug: "finding",
  slug: "the-eso-item-mine-needs-twenty-four-pages-and-no-shard-fits",
  domainSlug: "domain/temper",
  claim:
    "The `eso` mine's `items` runs to 196,161,960 bytes in 155,440 rows, and one entry file holds 8,388,608, so it needs at least twenty-four pages. No shard the game names fits: weapons alone are 90,160,298 bytes and armour 79,568,470. The mine page and its `quests` rows have landed and `items` has not. Each way forward costs something Alan should pick, because nothing under `pages/` is deleted, so landing the mine keeps two copies of 196MB in one repository.",
  evidence:
    "Measured on 2026-09-01 over all twenty-four source files in `pages/temper-mine/`.\n\n`eso.temper-mine.items.jsonl` and its parts 2 through 24 hold 196,161,960 bytes across 155,440 rows, averaging 1,262 bytes a row. Twenty-three of the twenty-four sit between 8,387,136 and 8,388,607 bytes, which is the old system splitting at the same 8,388,608 that `ceilingFor` now gives an entry file. So the split is not a coincidence of size; both systems drew the same line, and akasha's grammar reads `.part2` as two sections rather than as a continuation, which makes every part a stray rather than an entry.\n\nSharding by `itemType` was measured and does not answer. Type 1 is 90,160,298 bytes over 62,862 rows and type 2 is 79,568,470 over 60,148, so weapons need eleven pages by themselves and armour ten. The next largest are type 61 at 6,924,618 and type 56 at 4,502,872, both of which would fit alone. Sharding by anything the game names therefore still needs a second split inside the two big types, so it buys nothing that an item-id range does not.\n\nWhat akasha already holds: `akasha/temper/temper-character/mines/temper-mine.page-type.ts`, the page `akasha/temper/temper-character/mines/pages/eso/eso.temper-mine.ts`, and its `quests` entries at 665,603 bytes, which landed because they fit. Only `items` is missing, and it is missing for size alone.\n\nThree ways forward, each with a cost that is Alan's to weigh rather than a seat's. Shard the rows into twenty-four or more pages by item-id range: it keeps every row and fits the grammar, but the range is invented rather than meant, and it puts a second 196MB of item data in a repository that already holds the first. Raise the entry ceiling for this property: one file, no invented boundary, and a 196MB blob for git to carry. Leave the raw mine outside akasha and keep only what temper derives from it, which is `pages/item` at 19,501 bytes: cheapest by far, and it is the one option that decides the mine is not something temper keeps.",
} as const satisfies Finding
