import type { Finding } from "../finding.page-type.ts"

export const theManifestCycleThatKeptAFileOutOfSeatSystemAlreadyRunsThroughToolsLib = {
  id: "01a069c6-9041-7401-86e9-d19cf6c2d013",
  pageTypeSlug: "finding",
  slug: "the-manifest-cycle-that-kept-a-file-out-of-seat-system-already-runs-through-tools-lib",
  domainSlug: "domain/akasha-migration",
  claim:
    "A coordinator decision left `seat-start-help` in flat `tools/lib` on the reading that carrying it would make `@akasha/seat-system` and `@akasha/command-system` mutually dependent. The premise is false in both directions. The check that would refuse a cycle reads declared `dependencies`, not imports, and seat-system's manifest names no akasha package the carriage needs, so the carriage adds no edge at all. Meanwhile the two packages are already inside one ten-package declared cycle, through `@tools/lib`. A hazard reasoned about at the import layer was being refused at the manifest layer, where it does not exist.",
  evidence:
    "Measured 2026-09-03 at HEAD 6215316a05, then the carriage landed at ecba56fcf1 and bbbe9cc5bc.\n\nWHAT THE CHECK READS. `acyclic-packages.cluster-check.code.ts` calls `packageDependencyCycles`, and that walks `held.dependencies` filtered by `CYCLE_DEP_KINDS = {dependencies, devDependencies}` (`package-cycles.module.code.ts`). It reads each `package.json`. It never reads an import.\n\nTHE CYCLE IS ALREADY THERE. Reading all 305 workspace manifests and running Tarjan over the declared edges returns one strongly connected component of ten: `@akasha/agents`, `@akasha/workflow-selection`, `@akasha/wandering-inn`, `@akasha/markdown-pages`, `@akasha/pipeline-sweep`, `@akasha/ci-containers`, `@akasha/ci-benchmark`, `@tools/lib`, `@akasha/seat-system`, `@akasha/command-system`. `@tools/lib` declares 17 akasha packages while every akasha package declares `@tools/lib`, so flat `tools/lib` is itself the hinge. Seeding the very edge the decision feared — `@akasha/seat-system` depending on `@akasha/command-system` — returns the identical component, because both are already in it.\n\nTHE INSTRUMENT DISCRIMINATES, so that identity is agreement rather than a dead arm. Removing the real `@akasha/command-system` -> `@akasha/seat-system` edge changes the component's spelling and keeps ten members, the cycle surviving through `@tools/lib`; and `@akasha/utils-narrow` is in no component at all. A negative arm that answers empty and a positive arm that answers differently were both run.\n\nTHE CARRIAGE NEEDED NO MANIFEST EDGE. `akasha/seat-system/package.json` declares `@akasha/supabase-auth`, `@akasha/utils-system`, `@tools/lib` and `zod`. It does not name `@akasha/command-system`, and twenty source files under `akasha/seat-system/` import `@akasha/command-system/*` today regardless. `@akasha/google-email` is the same shape and carries the nearest precedent for the work: `akasha/google/email/email-command-help/` is a `CommandHelp` module living in a domain package, importing the type from `@akasha/command-system/command-declaring`, with no such dependency declared.\n\nSO THE FILE MOVED. `seat-start-help`, `seat-reset-help` and `seat-resume-help` are now `@akasha/seat-system/seat-start-help` and its two siblings, byte-identical below the import block, and `akasha part-census` reads no orphan of them.\n\nWHAT THIS DOES NOT SAY. It does not say the repository is acyclic; it is not, and the component above is the reading. It says the cycle predates this carriage, does not pass through it, and dissolves when `@tools/lib` goes — which is the migration's own objective. NOT MEASURED: whether `acyclic-packages` is scheduled to run at all, or has been failing on this component all along.",
} as const satisfies Finding
