import type { Finding } from "../finding.page-type.ts"

export const theOldGraphTreeIsATombstoneFieldNotAMigration = {
  id: "01a0685e-59a0-7006-9333-3ddd08ee3b2b",
  pageTypeSlug: "finding",
  slug: "the-old-graph-tree-is-a-tombstone-field-not-a-migration",
  domainSlug: "domain/akasha-migration",
  claim:
    "`tools/lib/graph/` is not 64 files awaiting migration. It is the corpse of an architecture akasha already refuted, and most of it carries no content to carry anywhere. Twenty-three of the 64 files hold nothing but exports that throw `oldGraphGone`, and the vocabulary the other 41 declare — `Engine`, `Producer`, `Deriver`, `BuildContext`, `ProducerOutput` — is precisely the assembled-snapshot design that `akasha/graph-system/graph-system.workspace-package.ts` abolishes when it states `The graph is never assembled.` Migrating that vocabulary inward would carry a refuted design into the package whose own page refutes it.",
  evidence:
    "Census by grepping each of the 64 files for `oldGraphGone|goneRecord`: 23 files match and 41 do not. Every export of `ask.ts`, `engine.ts`, `snapshot.ts`, `origin.ts`, `repos.ts`, `identity.ts`, `held-snapshot.ts`, `define-node-deriver.ts`, `queries/closure.ts`, `queries/transitive.ts`, `producers/lib/curation.ts`, `producers/lib/repo-tree.ts`, `producers/lib/workspace-dirs.ts`, `producers/lib/resolve-package-export.ts`, `producers/file/ts-file/parse.ts`, `producers/file/md-file/parse.ts`, `producers/package/scanner-helpers.ts`, `producers/file/file.node.producer.ts` and `producers/package/package.node.producer.ts` throws. `graph-gone.ts` types them `never` through a Proxy, so importing is free and calling is fatal.\n\nThe successor already stands: `akasha/graph-system/graph-asking/graph-asking.module.code.ts`, 207 lines, answers from indexes and declares its own `Edge` type. The workspace package states `The graph reaches no further than the akasha folder` and `The graph is never assembled`.\n\nEvery akasha reader of the old tree is retired. All twelve graph-reading pages under `akasha/checks/cluster-checks/pages/` call `refuseRetired()`, which `akasha/checks/cluster-checks/modules/retired/retired.module.code.ts` defines as printing `this is a retired cluster check. It is NOT to be run` and exiting 2. `akasha/checks/cluster-checks` holds no `package.json` and the root `tsconfig.json` names it nowhere, so no compiler reads it and nothing there can break.\n\nThe per-file-kind boilerplate collapses. Twenty-nine files under `producers/file/<kind>-file/types.ts` each declare a node type constant, and every one of the 32 constants is the kind's own name followed by `-file` without exception — checked by extracting all of them. One rule replaces twenty-nine declarations.\n\nOne file was already duplicated inside akasha: `producers/file/ts-file/discover-workspace-walk.ts` is byte-identical to lines 65-71 of `akasha/checks/cluster-checks/modules/tree-globs/tree-globs.module.code.ts`.\n\nWhat had durable value was the authorship split, which akasha lacked. `akasha/code-system/file-kind/file-kind.module.ts` states `Nothing here says whether a kind is text or bytes`, and no `_NODE_TYPE` constant and no `nodeKey` or `nodeIdPrefix` stands anywhere under `akasha/` outside cluster-checks. That part landed as `akasha/graph-system/file-kind-authorship/`.",
} as const satisfies Finding
