import type { Finding } from "../finding.page-type.ts"

export const theValueChainBreakIsBuriedUnderTheDayTrackingGlobs = {
  id: "01a0616f-268c-7000-9d82-0bb71d6889cb",
  pageTypeSlug: "finding",
  slug: "the-value-chain-break-is-buried-under-the-day-tracking-globs",
  domainSlug: "workspace-package/checks",
  claim:
    "`pages-hold-properties` is the only reader anywhere that turns the `value` chain break into a message, and it cannot show it. Its `SHOWN = 12` ceiling is filled by 367 akasha `.ts` day pages the widened `daily-tracking` and `eso-daily-tracking` `files:` globs reach, and those sort ahead of the six `.value.md` pages. The audit also has no runner. A page type answering 0 properties where it should answer 48 is therefore invisible three times over.",
  evidence:
    "Measured 2026-09-02 by running against the checkout as it is.\n\n`propertiesFor` over a disk tree refuses for `value`: `pages/page-type/value.page-type.md` extends `readout`, which no page type in that registry declares. Over a spanning tree the same call answers 48 properties, the chain reaching `readouts/readout/readout.page-type.md`, then `domain`, then `page`. The break is total rather than a shortened chain — 0 against 48. Six live pages sit under it: `alan/value/` holds `faith`, `fun`, `health`, `learn`, `love` and `wealth`.\n\n`tools/audits/pages-hold-properties.ts:79` is the one place that refusal reaches a message. Running the audit by hand: verdict `advisory`, tally line `373 claimed but not judged`. Broken down by reason, the 373 are 234 `eso-daily-tracking` `.ts` pages, 133 `daily-tracking` `.ts` pages, and the 6 `value` pages. The 367 TypeScript entries are benign by the audit's own words — akasha's own page and folder checks are what hold a TypeScript page to its shape. They are there because the `files:` globs on both markdown day-type pages reach akasha `.ts` pages; `6b31f52fad` widened `daily-tracking` on 2026-09-01. The earlier survey read this same audit at 10 messages.\n\n`SHOWN = 12` at line 13 and `first()` at line 16 truncate the list. Paths sort `akasha/...` before `alan/...`, so all twelve slots go to `.ts` day pages and the six `value` lines can never appear. `advise` at line 120 never returns `fail`. And `tools/audits/` has had no runner since `d3eeca3646`, so nothing runs this at all.\n\nThe two page-type defects surveyed tonight are one mechanism: the widened glob hides the chain break.\n\nNo change is filed. The chain break's own remedy is the design call already taken in `the-audit-page-type-scan-is-folder-scoped-not-suffix-scoped`, and a display ceiling that sorts a real defect behind benign noise is the shape `the-thirty-one-audits-still-work-and-nothing-runs-them` already records twice.",
} as const satisfies Finding
