import type { Finding } from "../finding.page-type.ts"

export const theTwoWrongPathPostsWereThisSeatsOwnProbes = {
  id: "01a06220-eb53-7000-8f8a-64435db74be5",
  pageTypeSlug: "finding",
  slug: "the-two-wrong-path-posts-were-this-seats-own-probes",
  domainSlug: "domain/alan-harness",
  claim:
    "Two POSTs, to `/api/health-samples` and `/api/health`, answered 500 rather than 404, and neither came from Alan's app: build 200 forms one health URL and it is neither of them. The site's catch-all page route matches `api` as a page type and the rest as a page, so an unrouted path reads as a fault in the site rather than as a wrong address. Both instruments watching the health road read the resulting silence as an outage of an ingest route that had in fact never been reached.",
  evidence:
    'The pod log carries, at 2026-09-02T12:18:51.645Z and 12:19:48.737Z: `You made a POST request to "/api/health-samples" but did not provide an `action` for route "routes/page-detail"`, and the same shape for `/api/health` against `routes/api.health`.\n\nThe ingest route is `api/tracking/health-samples` at `alanwalton/web/app/routes.ts:72`. The catch-all is `route(":pageTypeSlug/:pageHrefParam", "routes/page-detail.tsx")` at `routes.ts:8`, which matched `pageTypeSlug="api"` and `pageHrefParam="health-samples"`. That route declares no action, so React Router raised a 500 through `getInternalRouterError`.\n\nTHE SENDER WAS NOT THE PHONE, and this said it was. Emitting the seam at `2ee5df1158`, the commit build 200 was made from 66 minutes before those two POSTs, gives `https://alanwalton.com/api/tracking/health-samples` once and these two paths zero times. One endpoint constant reaches one address, so a second address is a second sender.\n\n`git log --all -S\'"api/health-samples"\' -- alanwalton/web/app/routes.ts` returns nothing, so that path was never a route.\n\nThe request reached the pod. It never reached `resolveDeviceSecretContext`, never reached `upsertHealthSamples`, and never reached the page store.\n\nWhat made this hard to see is that nothing logs on the good path. `api.tracking.health-samples.ts` logs nothing on success or on an empty payload, `device-secrets.server.ts` writes to stderr only on a refusal, and the `web` container logs errors alone — no line in the retained window holds `GET /` or `POST /`. So an absence of log lines was never evidence either way, and I twice treated it as evidence.\n\nTwo instruments read the same silence as an ingest outage: the arrival watchdog ruled SILENT at 242.2h, and four device-secret refusals of shape `absent` at 12:11:33 were read as ordinary probes.',
} as const satisfies Finding
