import type { Finding } from "../finding.page-type.ts"

export const theRefusalFamilyIsTwentySevenPrintedPagesAndSeventyFourThatWent = {
  id: "01a06622-7f10-7c4e-9a3b-6d05e1477b20",
  pageTypeSlug: "finding",
  slug: "the-refusal-family-is-twenty-seven-printed-pages-and-seventy-four-that-went",
  domainSlug: "workspace-package/checks",
  claim:
    "The 101 refusal documents split 27 printed to 74 printed by nothing, and the 74 went. Each of the 27 has a literal `refusalText(` call site; each of the 74 has none, and 68 of them occur nowhere in the repository outside their own file. The 27 are now `refusal` pages under `akasha/checks/refusals/`, and `refusal/refusal.ts` reads them there rather than reading markdown.",
  evidence:
    "Four instruments agreed on 27 and 74. Two of mine: a serial Node walk of 71,924 source files taking the first argument of every `refusalText(` where it is a literal in double quotes, single quotes or backticks; and a serial substring search for each of the 101 slugs over 231,351 readable files outside `pages/refusal/`. Two more were run by a subagent under ripgrep and under grep, serially, over 231,734 files with `-uu`, so node_modules and build output were read. No parallel extractor was used anywhere.\n\nBefore believing any zero I planted `refusalText(` calls in `.ts`, `.tsx`, `.mts` and `.js`, in single-quoted, double-quoted and multi-line forms. The walk found all five and told a non-literal one apart. It reads 740 `.tsx` files here, so the `**/*.ts` narrowing `refusals-bound` had is not repeated.\n\nThe 74 lost their printers when `tools/audits/` went at `394472d8d9`, rehoming barred by checks reaching no further than `akasha/`. `suite-batch-killed` read like a document held for a runner not yet arrived; its printer existed at `c8ad794af4` and went with the audits, so it is orphaned like the rest. Fifty documents went before these on the same ground, each commit naming the instrument that went with them. The folder held 101 files, all markdown, and no sidecar.\n\nTen of the 27 sit in modules nothing imports: `page/shape/words.ts`, `tools/lib/hook-merge.ts`, `tools/lib/email-partition.ts`, `tools/lib/category-partition.ts`. They have call sites, so they migrated; whoever removes those modules takes their documents.\n\nEvery id was minted again as a uuid version 7 keeping the last eight hex of the version 5 it replaced. The `holes` list the front matter carried agreed with the braces marked in the body in 101 of 101, so it is worked out rather than carried. The repointed reader prints all 27 byte-identically to the markdown reader and refuses on an absent slug, an unfilled hole and a surplus value.",
} as const satisfies Finding
