import type { Finding } from "../finding.page-type.ts"

export const theAddonDataWallIsOnePageTypeReaderRatherThanTheWholeLayer = {
  id: "01a0634d-14e0-7101-8d13-d2b5f010e0f0",
  pageTypeSlug: "finding",
  slug: "the-addon-data-wall-is-one-page-type-reader-rather-than-the-whole-layer",
  domainSlug: "domain/temper",
  claim:
    "The addon data port's wall is one reader, not the layer. Every generator now renders inside akasha and renders the same bytes, so the render half is done. What is left outside is the read half, and its one unportable reach is `typesFor`, which wants the root `page/` declaration engine: 40 files and 3,689 lines, larger than the pipeline it serves. Everything else the read half reaches is a small port or already has an akasha twin, so the layer was never the size of the problem.",
  evidence:
    "Measured 2026-09-02 at HEAD 9c31868107, landed at b4f764982789 and a57c2a75278e.\n\nTHE RENDER HALF. The 21 generators of `tools/lib/temper-addon-data/generators` are recreated as modules of `@akasha/temper-addon-data`, importing the real `@akasha/...` specifiers rather than the `code/` shims. Driven old against new and compared byte for byte: denominator 21, SAME 21, DIFF 0, nothing threw, against the landed bytes rather than the drafts, and three files were reformatted on landing. Two seeded faults answered DIFF 2 SAME 19, so the zero is a true zero. The 14-entry mapping table lands as `mapping-renders`, keyed on the rendered file name: denominator 14, SAME 14, DIFF 0, and a seeded fault answers DIFF.\n\nTWO SHIMS WERE STALE. `code/mundus-source.ts` and `code/lore-library-data-generated.ts` alone of the 34 shims point at `@temper/`, while `@akasha/temper-character-sources/mundus-source` and `@akasha/temper-completion/lore-library-data` are both there. Repointed at the akasha twin, mundus-mappings renders the same 1,466 bytes.\n\nTHE READ HALF. `pages-bridge.ts` reaches five things outside akasha. `codeRoot` and `camelizeKey`/`kebabizeKey` already have twins, at `@akasha/pages-system/code-root` and `@akasha/pages-access/file-rows`. `askComposed` has one at `@akasha/pages-query/ask`, wanting only the 45-line spelling adapter `shared/pages-query/src/store-spelling.ts` around it. `asDeclared` is 30 self-contained lines. `typesFor` is the one that does not come: it takes a `FileTree`, and the closure of `diskFileTree` and `compiledPageTypeFor` is 40 files and 3,689 non-blank lines of the root page engine. `askShape` is no substitute — its `Declaration.type` is a property's page-type slug, not the declared value type a generator coerces against.\n\nTHE OLD COUNT. The claim that 21 generators had no akasha twin was true of the folder and false of the port: they had none because nobody had made them, and making them cost one commit.",
} as const satisfies Finding
