import type { Finding } from "../finding.page-type.ts"

export const theLastUnprintedRefusalIsTheRunnersToPrintOrRemove = {
  id: "01a06116-9b82-7e6e-a9db-93c3806aa91a",
  pageTypeSlug: "finding",
  slug: "the-last-unprinted-refusal-is-the-runners-to-print-or-remove",
  domainSlug: "workspace-package/checks",
  claim:
    "`refusals-bound` is down to one refusal, and it belongs to whoever lands the runner. `pages/refusal/checks-ceiling.refusal.md` describes a whole checks run going past its ceiling, and the one call site that filled it went with `tools/run-checks.ts` at `d3eeca3646`. It is not residue to delete: a lane is writing a runner over these same audits now, and its two files are untracked in the tree. That lane prints this document or removes it; nobody outside it can close this honestly.",
  evidence:
    "Measured by building a `RepoView` over the repo root and calling `refusalsBound` by hand, before and after: 12 messages over 120 documents and 35 printers, then 1 over 110 and 34.\n\nThe 11 that went were all one file's. `tools/hooks/agent-hook-block-destructive-git.agent-hook.code.attachment.ts` built its slugs as `` `${HOOK_NAME}-${subcmd}` `` and handed `refusal.slug` to `refusalText`, which the check cannot read, so it reported the file once and then reported all ten documents that file prints as printed by nothing. Both were true of a file that has not run since `95de35dcaf` deregistered it from `settings/agents.json` on 2026-08-28; `b9ebdc6e34` reimplemented the same ten refusals inside akasha the next morning at `akasha/hook-system/agent-hook/block-destructive-git/`, building its prose inline and sharing not one sentence with these documents. Nothing derived it, imported it or named those ten slugs as a literal anywhere. Two of the ten had drifted the way an unread document drifts: `-amend` advised landing a further commit with a CLI the same commit that deregistered the hook turned off, and `-rm` advised a bare `git add <path>`, which the live `block-git-writes` hook refuses. Gone at `bb95900c2f` with the attachment and its page.\n\nWhat is left is one document with holes `elapsed` and `ceiling`, filled at exactly one call site in the deleted runner. `CHECKS_CEILING_MS` is still there at `tools/lib/check.ts:14`, but the one thing that reads it, `tools/audits/suite-runs.ts:180`, takes it as a per-check deadline rather than as the whole-run ceiling this document describes. `tools/audits/audits.ts` and `tools/audits/run-one.ts` sit untracked in the tree and reference neither. So the event this refusal describes cannot happen tonight and can again the hour a runner lands, which is why it remains rather than going.",
} as const satisfies Finding
