import type { Finding } from "../finding.page-type.ts"

export const theFourEditorPageFoldersAreAProjectionOfLiveProcessIds = {
  id: "01a06827-f705-7f94-97f4-b0e2bd7dcb12",
  pageTypeSlug: "finding",
  slug: "the-four-editor-page-folders-are-a-projection-of-live-process-ids",
  domainSlug: "domain/akasha-migration",
  claim:
    "The 388 files in the four `pages/code-editor-*` folders are a projection of the process tree running on this workstation rather than records worth carrying into akasha. Every page's identity is a pid paired with the kernel start time, so nothing in them survives a reboot, and `services/sweep-editor-pages.ts` exists to delete each one when its process dies. They were dropped rather than migrated.",
  evidence:
    "Measured 2026-09-03.\n\nAll 23 markdown pages hold frontmatter and no body. A code-editor-window and a code-editor-terminal each state only `process`, and a terminal may add `seat-name`. A group states `window-name`, `position` and `active`. A tab states `group-name`, `place`, `label`, `active` and `terminal-name`.\n\nEach slug is `<pid>-<starttime>`. I read /proc for all eleven distinct pids in the set and every one was alive, with field 22 of /proc/<pid>/stat equal to the slug's second half. 3075435 with starttime 78466248 is the window, an openvscode-server utility process, and the ten terminals are `/usr/bin/bash --init-file ~/.local/share/code...`. The tab pages were last rewritten at 10:28 today, half an hour before I looked.\n\n`services/sweep-editor-pages.ts` states its purpose as `Delete every editor page whose window or terminal is gone`, and reads liveness from /proc rather than from a timer. A page of these types is defined to stand only while its process stands.\n\nThe sidecars are runtime telemetry. `pages/code-editor-window` holds 160 `.uncommitted.yaml` files for windows already swept, each a `features:` map of sweep counters and worst-latency timings. `pages/code-editor-terminal` holds 195 `.ended.uncommitted.attachment.json` files, each a dead terminal's exit status, pid, ppid and tty.\n\nTwo writers inside akasha still write into the old `pages/` tree. `akasha/editor-extension/observation-store/observation-store.module.code.ts` line 27 sets WINDOW_PAGE_TYPE to `code-editor-window` and patches that page's state after every 250ms of settle. `akasha/seat-system/terminal-init/terminal-ended/terminal-ended.module.code.ts` line 5 sets ENDED_DIR to `pages/code-editor-terminal`. Until those two stop, these folders refill while the editor runs.",
} as const satisfies Finding
