import type { Finding } from "../finding.page-type.ts"

export const theRegistryUnionNowNeedsFourDecisionsRatherThanAHundredAndSeventeen = {
  id: "01a06896-07c5-7e4d-b16b-be2e825d6245",
  pageTypeSlug: "finding",
  slug: "the-registry-union-now-needs-four-decisions-rather-than-a-hundred-and-seventeen",
  domainSlug: "domain/akasha-migration",
  claim:
    "The blocker on unioning the markdown and akasha page types is not the slug decisions. `the-page-type-registry-gap-is-duplicate-declarations-rather-than-missing-types` declined the union because 117 slugs would need a winner; measured 2026-09-02, that count is now 4. What actually blocks it is that the answer-cache mark is built from `.md` alone, so a registry ingesting `.ts` cannot tell it is stale.",
  evidence:
    "Measured 2026-09-03 at HEAD c740276920 by running the reader, not by reading it.\n\nWHY THE SLUG COUNT NO LONGER BLOCKS. `registryOf(diskFileTree(resolveRoots()))` answers 6 types: alert, daily-tracking, food-entry, message, seat-conditions, session-tracking. The earlier finding measured 368-372. `git ls-files 'pages/page-type/*.page-type.md'` is 6; `*.page-type.ts` under `akasha/` is 435. In both: 4 — alert, food-entry, message, seat-conditions. Markdown-only: 2. Akasha-only: 431, and nothing competes with any of them. So the 117 per-slug decisions are 4.\n\nTHE REAL BLOCKER, now cited at primary source. I first took this from the 2026-09-02 finding without reading the code. The code states and measures it: `akasha/markdown-pages/markdown-shape-mark/markdown-shape-mark.module.code.ts:25-33`. The mark reaches page files through `PAGE_SHAPE_GLOBS` and `PAGE_SHAPE_NAMED`, every one of which ends `.md`, so nothing about a `*.page-type.ts` reaches it. Seeded and measured there: renaming the slug inside a `.page-type.ts` left the mark at 7ab1fa35 and a union-shaped reader went on serving the old slug out of the cache, while the same rename in a `.page-type.md` moved the mark to 7ca4e6cf and the answer came back fresh. In its own words, that is \"what has to change first if the registry is ever unioned to read the akasha half\".\n\nTWO LESSER HAZARDS, neither retracted. `placesOf` turns `filed: [{repo, place: null}]` into `pages/<slug>/**/*.<slug>.md`, a path for a file that cannot exist, which `page-write-where.ts:29-42` records as having cost fourteen callers. `claimant` would newly resolve `.ts` files across slugs `relations-resolve` skips today.\n\nA FAMILY RATHER THAN ONE FAULT. Peers report three more, none measured by me: 11 propertySlugs shared across two kinds; `answer()` applying defaults where the index readers apply none; and `propertiesFrom` answering an empty property list for 2 of 428 page types, indistinguishable from declaring nothing.",
} as const satisfies Finding
