import type { Finding } from "../finding.page-type.ts"

export const theTemperCodeAuditNamesEntryPointsThatMatchNoFile = {
  id: "01a06356-354d-71c0-b758-3ed492364b34",
  pageTypeSlug: "finding",
  slug: "the-temper-code-audit-names-entry-points-that-match-no-file",
  domainSlug: "domain/temper",
  claim:
    "`tools/lib/code-audit-ast-unused/ast-unused.temper.config.json` names entry points by glob, and six of its globs match no file. Nine of its fourteen workspaces have no entry point at all, so the unused-code audit reports clean over 225 project files by examining nothing there, `player-inventory-management-ui` at 111 files and `player-completion` at 82 among them. A configured entry glob that has stopped matching is indistinguishable from a workspace that has nothing to audit.",
  evidence:
    'At `5d99892a`, denominator 106,151 tracked files, 14 workspaces in the config. Nine have zero entry points: `player-inventory-management-ui` (111 project files), `player-completion` (82), `player-economics-ui` (19), `player-completion-ui` (4), `game-characters-equipment-ui` (3), `game-companions-ui` (2), `player-completion-skills-morphs-ui` (2), `game-characters-character-ui` (1), `player-profile` (1) \u2014 225 files. Six globs match nothing: `src/**/*.script.ts` in `temper/scripts`, and a `*.test.ts` or `*.test.{ts,tsx}` entry in `player-completion`, `player-economics-ui`, `player-inventory-management-ui`, `shared-build-deploy-checks` and `web`. `temper/scripts` keeps 2 entries, both `.unit.test.ts`, over 54 project files; `main.ts` is not among them, and the worker is reached only by the separate `**/watcher-exe/main.ts` entry in `infra/cluster-checks/src/lib/ast-unused-adapters.ts:44`. The `.script.ts` glob stopped matching when the last loose script, `mined-data-parse.ts`, went in `1fdf10802e`; `09f964f5c5` deleted all 27 test files the package held, leaving none, and `91e49ac5a6` added 2 back on 2026-09-01; those 2 are the whole of its entry set today. That same commit orphaned four helpers still tracked in `temper/scripts` \u2014 `_mined-data-test-helpers.ts`, `watcher-exe/_dispatch-mocks-test-helpers.ts`, `watcher/import-tasks.test-helpers.ts` and `watcher/import-tasks-complete-forever/mocked-pages-access.ts` \u2014 every consumer of each being listed at `09f964f5c5^`. `pages/package/temper-scripts.package.md` is the second instance of the same shape: it still defines the package as "the loose command-line scripts that generate, import, export and check Temper\'s data" when zero loose scripts remain, and `pages/domain/ops-temper.domain.md:17` links it. A config or a definition that stopped matching reality reads exactly like one that never had anything to match.',
} as const satisfies Finding
