import type { Finding } from "../finding.page-type.ts"

export const twoMorePathBuildersAnswerAFixedMarkdownExtension = {
  id: "01a060f1-3c7a-7c3d-82a8-b944c3b8300c",
  pageTypeSlug: "finding",
  slug: "two-more-path-builders-answer-a-fixed-markdown-extension",
  domainSlug: "domain/akasha-migration",
  claim:
    "`findingPathIn` answers a `pages/finding/*.md` path for all 359 findings that are TypeScript pages, so `finding create` names a file that is not there. `sidecarFor` answers nothing for the 9 pages carrying a `.sops.yaml`, so a secret on disk reads as no secret. Both are the fabrication `whereFor` was repaired of in `11c7a265f3`. Left rather than repaired: neither has the round trip a repair deserves.",
  evidence:
    "Measured 2026-09-02 by running, against the checkout as it is.\n\n`tools/lib/finding.ts:22-24` reads `pageFileIn(root, dir, slug) ?? `${dir}/${slug}.finding.md``. `pageFileIn` matches on a fixed `.md` (`akasha/markdown-pages/markdown-page-file/markdown-page-file.module.code.ts:6-9,19`), so it never matches a TypeScript page and the fallback always answers. `findingPathIn(root, 'no-tool-here-can-rename-a-property-on-a-page-that-moved')` answered `pages/finding/no-tool-here-can-rename-a-property-on-a-page-that-moved.finding.md`, which is not on disk, for a finding that is on disk at `akasha/domain-system/findings/pages/…finding.ts`. `pages/finding/` holds 0 files; 359 findings are TypeScript pages. Reached live from `tools/commands/finding/create.ts:14`.\n\n`tools/lib/page-secret.ts:32-36` refuses any name not ending `.md`. `sidecarFor('akasha/agents-system/claude-account/claude-accounts/aawalton.claude-account.ts')` answered nothing, with both that page and its `.sops.yaml` on disk. 9 sops files sit beside a TypeScript page. Reached from `deploy-system/secret/secret.ts:112` and `tools/lib/page-secret-command.ts:53`. `akasha/markdown-pages/markdown-sidecar/markdown-sidecar.module.code.ts` was repaired of this in `4c968403de` and finds all 9; this is the second, unrepaired copy of the same question.\n\nThe two want different hands. `sidecarFor` is mechanical: take the real extension off rather than a fixed three characters. `findingPathIn` is not, because the fallback is a mint path and nothing here says where a new finding lands now that the markdown folder is empty. If the answer is akasha, then `finding create` has to reach `akasha write` rather than compose a commit, which is the same wall the property rename met.\n\nNeither file is followed by `surplus-fall-notifier`, so neither repair restarts it.",
} as const satisfies Finding
