import type { Finding } from "../finding.page-type.ts"

export const twoEnabledWorkstationServicesReachPagesOverHttpAndOneSaysWhy = {
  id: "01a06817-cde8-71cb-bfc4-044dfb74d584",
  pageTypeSlug: "finding",
  slug: "two-enabled-workstation-services-reach-pages-over-http-and-one-says-why",
  domainSlug: "domain/alan-harness",
  claim:
    "The on-workstation breach of the workstation rule reaches past the watcher into the harness. Two enabled workstation services and three families of ops command reach pages over HTTP, and `@akasha/pages-query`'s own page defines that package as the page store reached over HTTP by what runs outside it, so each is a breach in the package's own words. One of them says why in prose: the in-cluster name resolves to nothing on the workstation, so a loopback origin is named instead.",
  evidence:
    "Measured 2026-09-03, sweeping every importer of a pages road in the repo and establishing each one's runtime from what starts it rather than from its own opinion.\n\n`pages/workstation-service/surplus-fall-notifier.workstation-service.md:9-11` runs `bun services/surplus-fall-notifier.ts` and is enabled; that reaches `tools/lib/surplus-fall/readout.ts:2`, which imports `askingFor`. `pages/workstation-service/great-courses-sync.workstation-service.md:9-12` runs `bun services/great-courses-sync.ts`, is enabled and is scheduled daily at 07:35; it reaches `akasha/great-courses/page-query`, which takes `askComposed` from `@akasha/pages-query`.\n\nThree command families take the same road, dispatched from `dotfiles/bin/ops` into `tools/commands`: `tools/lib/daily-tracking/persona-recipe-rows.ts:2` imports `askingFor` and `persona-total-landing.ts:1` imports `@akasha/pages-query`; `tools/lib/temper-inventory/settings-row.ts:5` and `snapshot-read.ts:3` take `askComposed`; `collections/exercises/src/pages/access.ts:2` does too.\n\n`akasha/pages-system/pages-query/pages-query.workspace-package.ts:7` defines the package as the page store reached over HTTP by what runs outside it.\n\n`tools/lib/push-notification/store.ts:7-15` names `ON_THE_WORKSTATION` as `http://127.0.0.1:8787` and explains it: `originOf` in `page-calling` reads two environment names and otherwise falls back to the in-cluster name a pod reaches the service by, which resolves to nothing on the workstation, and the notifier's unit is generated from a page carrying no environment. So the workstation reaching the service over loopback is deliberate and documented rather than accidental.\n\nTwo candidates are dead rather than breaching: `tools/lib/addon-load-order-metadata.ts` and `akasha/alan/library/reading` have no importer, the live addon-load-order twin taking the direct road at `akasha/temper/temper-addon-build/addon-load-order/addon-load-order.module.code.ts:4`.",
} as const satisfies Finding
