import type { Finding } from "../finding.page-type.ts"

export const twoChangesNamingOnePathInOneLandingLoseTheFirst = {
  id: "01a06885-0bab-7006-be8c-d6c28967b297",
  pageTypeSlug: "finding",
  slug: "two-changes-naming-one-path-in-one-landing-lose-the-first",
  domainSlug: "domain/akasha-migration",
  claim:
    "The sibling-clobber that `a-whole-file-landing-reverts-a-sibling-workers-lines-with-code-zero` records between two workers happens just as readily inside ONE worker's own `landedMechanically` array. Two entries naming the same path are two whole bodies, and the later one wins; the earlier edit is dropped with no refusal and no report line distinguishing it. A helper that reads the file from disk at write time — the very fix for the cross-worker case — makes this MORE likely, because each call reads a disk state that does not yet hold the other call's edit.",
  evidence:
    'Measured 2026-09-03 while migrating the four `tools/lib/triage-fanout-*.ts` files into `akasha/changes/test-fanout/`. I wrote two helpers, each of which read the target from disk and pushed one change: one to add `exports` entries to a manifest, one to add `dependencies` entries. I called both on `akasha/changes/test-fanout/package.json`, and both on `akasha/infrastructure/commands/tests-triage-fanout/tests-triage-fanout.command.code.ts` for two separate import lines.\n\nThe landing report at 6a8e5831d7 printed `wrote akasha/changes/test-fanout/package.json` TWICE and `wrote .../tests-triage-fanout.command.code.ts` TWICE, which is the only signal available, and it reads as success rather than as a collision. Answer code was 0.\n\nWhat survived was the second push in each pair. The manifest gained `@akasha/utils-narrow` and `@akasha/verdict` under `dependencies` and gained NONE of the four `./triage-fanout-*` `exports` lines. The command file gained the repointed `triage-fanout-render` import and kept `@tools/lib/triage-fanout-log` — a specifier whose file the same landing had just deleted. So the landing left a module importing a path that no longer existed, while reporting only successes.\n\nIt was caught by `bun build --target=bun` on the reader, which printed `Could not resolve: "@akasha/test-fanout/triage-fanout-render"` and `Could not resolve: "@tools/lib/triage-fanout-log"`. Neither `git show --stat` of the commit nor the landing\'s own report would have shown it: the stat says the two files changed, which they did. Repaired at c10c9b48a7 by folding every edit for one path into a single read-modify-write.\n\nThe practice that prevents it is to key the change list by path and refuse a second entry for a path already present, rather than to trust that separate edits compose. A helper of the shape `edit(path, [{was, now}, ...])` that throws on a repeated path makes the collision loud at authoring time; I added that guard and it is what kept the following landings honest.',
} as const satisfies Finding
