import type { Finding } from "../finding.page-type.ts"

export const whatEachOpsCliCommandBecomesInsideAkasha = {
  id: "01a0655b-e08f-78aa-b003-3a1498d47cd6",
  pageTypeSlug: "finding",
  slug: "what-each-ops-cli-command-becomes-inside-akasha",
  domainSlug: "domain/akasha-migration",
  claim:
    "`ops-cli` holds twelve `.command.md` pages of the old markdown command system, and akasha already carries every one worth carrying. `edit`, `write`, `deploy` and `package move` are inside under the same page type and slug. `rm`, `mv` and `replace` are inside under new names: `remove`, `move` and `refactor`. `search`, `list` and the three worktree commands are replaced by nothing, being wanted by nothing inside.",
  evidence:
    "`akasha/command-system/commands/command.page-type.ts:19-44` names the nineteen commands that landed. Four of the old slugs are among them unchanged: `command/edit`, `command/write`, `command/deploy` and `command/move`, against `ops-cli/global/edit/edit.command.md`, `ops-cli/global/write/write.command.md`, `ops-cli/global/deploy/deploy.command.md` and `ops-cli/package/move/move.command.md`, each of which states `page-type-slug: command` and that same slug.\n\nThree were renamed, and the definition sentence carried over. `remove.command.ts:7` reads \"named paths taken away, gated together and removed or refused as one\", which is `ops-cli/global/rm/rm.command.md:15` word for word, and four of that page's seven design lines are invariants at `remove.command.ts:67,71,142,146`. `move.command.ts:7-8` widens mv's sentence, and mv's two live design lines are at `move.command.ts:54,62`. `replace` was a blind substitution across whatever files carried a string; `refactor` does that work from the index and the type checker instead, over packages, page slugs, page types, property keys and names.\n\nSix are replaced by nothing. `ops list` is 26 lines around `git ls-files`. `ops search` is 196 lines around ripgrep, and `settings/agents.json:36` has blocked every agent from `ops` since the `block-ops-cli` hook landed. The three worktree commands key off `.worktree.md` pages, of which git now tracks none, and `ops worktree merge` has refused every call since `ops worktree check` was deleted. `ops-cli/global/address.ts` and `ops-cli/worktree/worktree.ts` are helpers of those commands and die with them; `move/move.ts:2` was the one importer outside `ops-cli/`.",
} as const satisfies Finding
