import type { Finding } from "../finding.page-type.ts"

export const wholeFileHashingIsBlindToADuplicateGivenAFreshIdAndSlug = {
  id: "01a06769-dbe1-734f-bd0f-8c4c34983f90",
  pageTypeSlug: "finding",
  slug: "whole-file-hashing-is-blind-to-a-duplicate-given-a-fresh-id-and-slug",
  domainSlug: "domain/akasha-migration",
  claim:
    "Hashing whole files finds content re-filed under a different stem and finds nothing when it is re-filed with a fresh id and slug, the shape a migration produces. The body-only arm must take out the export name as well as id and slug, because a page is one exported object named for its slug, so stripping id and slug alone is itself blind. An arm is proven only once a seeded pair of the shape it exists to catch collapses to one digest under it.",
  evidence:
    'Measured 2026-09-03 over the alert, refusal and domain families, and corrected after publishing.\n\nTHE DEMONSTRATION. A landed alert page was copied under a new id, a new slug, and the new export name its slug forces. Whole files answer two digests. Bodies with id, slug and export name taken out answer one. Same pair, same run, opposite answers. A migration re-mints ids and re-slugs pages, so a migration is the process that makes that copy.\n\nTHE STRIP TAKES THE EXPORT NAME TOO, and this is where I was wrong first:\n\n  .replace(/^\\s*(id|slug):\\s*"[^"]*",?\\s*$/gm, "")\n  .replace(/^export const \\w+ = \\{/m, "export const NAME = {")\n\nA page is one exported object named for its slug, so a page re-filed under a new slug carries a new export name as well, and taking out id and slug alone leaves that third difference. My first reading of these families took out id and slug alone. Worse, the copy I seeded it with changed only id and slug, so the seed differed from the real case in the very way the instrument did, and the arm reported itself sound. Read again on the strip above: 65 alert, 27 refusal and 169 domain bodies, every one distinct, no duplicate. The answer held, but it was unproven when first published.\n\nSO AN ARM IS PROVEN ONLY ONCE A SEEDED PAIR OF THE SHAPE IT EXISTS TO CATCH COLLAPSES TO ONE DIGEST UNDER IT. A clean from a blind arm is the same string as a clean from a sound one.\n\nTHE FIRST ARM IS NOT THE WEAK ONE. Over `pages/temper-inventory-chunk` whole-file hashing found duplicates outright, 458 files against 454 digests. The arms add to one another: whole-file catches re-filing under a new stem, body-only additionally catches re-filing under a new identifier, and slug and id catch two pages reached by one name even where bodies differ. None implies another, and the third is not the second: a slug is unique only among the pages of its page type.',
} as const satisfies Finding
