import type { Exercise } from "../../exercise.page-type.ts"

export const tireFlip = {
  id: "019ebc78-aa50-7399-9e6e-4ff4e504087f",
  pageTypeSlug: "exercise",
  slug: "tire-flip",
  title: "Tire Flip",
  exerciseCategory: "strongman",
  equipment: "other",
  exerciseExternalId: "Tire_Flip",
  exerciseExternalLink: "https://github.com/yuhonas/free-exercise-db/tree/main/exercises/Tire_Flip",
  force: "pull",
  gripDemand: "low",
  imageEndUrl:
    "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Tire_Flip/1.jpg",
  imageStartUrl:
    "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Tire_Flip/0.jpg",
  implementCount: 1,
  isBallistic: false,
  exerciseLastSyncedAt: "2026-07-25",
  laterality: "bilateral",
  exerciseLevel: "intermediate",
  loadFactor: 0,
  mechanic: "compound",
  movementPattern: "squat",
  muscleFocus: "legs",
  primaryMuscles: ["quadriceps"],
  scoringMode: "reps",
  secondaryMuscles: [
    "calves",
    "chest",
    "forearms",
    "glutes",
    "hamstrings",
    "lower-back",
    "shoulders",
    "traps",
    "triceps",
  ],
  sfrScore: 3,
  skillCost: "moderate",
  exerciseSource: "free-exercise-db",
  trainsLengthenedRange: false,
  instructions: "txt",
} as const satisfies Exercise
