import type { NonResourceRule, Rule } from "../workflow-dsl/rbac-types.ts"
import { LABELS, SUBJECTS } from "./rules.ts"
import { clusterRoleBinding, clusterRoleWithRules } from "./yaml-format.ts"

const ESCALATE_ROLE_NAME = "pipeline-engine-escalate"
const DEPLOY_ROLE_NAME = "pipeline-engine-cluster-deploy"

export const escalateRules: Array<(Rule | NonResourceRule) & { comment?: string }> = [
  {
    comment:
      "escalate lets pipeline-engine PATCH its own deploy ClusterRole with perms it\n  # does not yet hold (new CRD api-groups). get/update/patch on the role already\n  # live in pipeline-engine-cluster-deploy; escalate is the missing admission verb.",
    apiGroups: ["rbac.authorization.k8s.io"],
    resources: ["clusterroles"],
    verbs: ["escalate"],
    resourceNames: [DEPLOY_ROLE_NAME],
  },
  {
    comment:
      "bind covers re-creation of the (immutable-roleRef) deploy ClusterRoleBinding\n  # without holding every granted perm — defensive; the binding is normally a no-op apply.",
    apiGroups: ["rbac.authorization.k8s.io"],
    resources: ["clusterrolebindings"],
    verbs: ["bind"],
    resourceNames: [DEPLOY_ROLE_NAME],
  },
]

export function generateEscalateRbac(): string {
  const sections: string[] = [
    clusterRoleWithRules(ESCALATE_ROLE_NAME, LABELS, escalateRules),
    clusterRoleBinding(ESCALATE_ROLE_NAME, LABELS, SUBJECTS),
  ]
  const header = `# DO NOT EDIT — generated by tools/lib/cluster-rbac/escalate-manifest.ts
# Grants pipeline-engine the escalate/bind verbs so ci-apply-rbac can self-PATCH
# the ${DEPLOY_ROLE_NAME} ClusterRole when a new CRD api-group is added.
`
  return header + sections.join("\n---\n") + "\n"
}

if (import.meta.main) {
  process.stdout.write(generateEscalateRbac())
}
