{"propertySlug":"import","fileName":"dockerfile-extensions.module.code.ts","path":"infrastructure/container-image/dockerfile/modules/builder/dockerfile-builder.module.code.ts"}
{"propertySlug":"import","fileName":"dockerfile-extensions.module.code.ts","path":"infrastructure/container-image/dockerfile/modules/bun-service/dockerfile-bun-service.module.code.ts"}
{"propertySlug":"import","fileName":"dockerfile-extensions.module.code.ts","path":"infrastructure/container-image/dockerfile/modules/nextjs/dockerfile-nextjs.module.code.ts"}
{"propertySlug":"import","fileName":"dockerfile-extensions.module.code.ts","path":"infrastructure/container-image/dockerfile/modules/services/dockerfile-services.module.code.ts"}
{"propertySlug":"import","fileName":"dockerfile-extensions.module.code.ts","path":"infrastructure/container-image/dockerfile/modules/tool-image/dockerfile-tool-image.module.code.ts"}
{"propertySlug":"import","fileName":"dockerfile-extensions.module.code.ts","path":"infrastructure/container-image/dockerfile/modules/writing/dockerfile-writing.change-generator.code.ts"}
{"propertySlug":"parts","path":"infrastructure/container-image/dockerfile/dockerfile.domain.ts","id":"01a06865-abff-7000-a441-7a4caa49c9d9"}
