export const MORPHABLE_SKILLS_DETAIL_PER_LINE_01: Record<
  number,
  ReadonlyArray<{
    baseName: string
    morph1Name: string
    morph2Name: string
    skillType: "active" | "ultimate"
    lineRankNeeded: number
  }>
> = {
  [42]: [
    {
      baseName: "Summon Unstable Familiar",
      morph1Name: "Summon Unstable Clannfear",
      morph2Name: "Summon Volatile Familiar",
      skillType: "active",
      lineRankNeeded: 1,
    },
    {
      baseName: "Daedric Curse",
      morph1Name: "Daedric Prey",
      morph2Name: "Haunting Curse",
      skillType: "active",
      lineRankNeeded: 4,
    },
    {
      baseName: "Summon Storm Atronach",
      morph1Name: "Greater Storm Atronach",
      morph2Name: "Summon Charged Atronach",
      skillType: "ultimate",
      lineRankNeeded: 12,
    },
    {
      baseName: "Summon Winged Twilight",
      morph1Name: "Summon Twilight Tormentor",
      morph2Name: "Summon Twilight Matriarch",
      skillType: "active",
      lineRankNeeded: 20,
    },
    {
      baseName: "Conjured Ward",
      morph1Name: "Hardened Ward",
      morph2Name: "Regenerative Ward",
      skillType: "active",
      lineRankNeeded: 30,
    },
    {
      baseName: "Bound Armor",
      morph1Name: "Bound Armaments",
      morph2Name: "Bound Aegis",
      skillType: "active",
      lineRankNeeded: 42,
    },
  ],
  [43]: [
    {
      baseName: "Mages' Fury",
      morph1Name: "Mages' Wrath",
      morph2Name: "Endless Fury",
      skillType: "active",
      lineRankNeeded: 1,
    },
    {
      baseName: "Lightning Form",
      morph1Name: "Hurricane",
      morph2Name: "Boundless Storm",
      skillType: "active",
      lineRankNeeded: 4,
    },
    {
      baseName: "Overload",
      morph1Name: "Power Overload",
      morph2Name: "Energy Overload",
      skillType: "ultimate",
      lineRankNeeded: 12,
    },
    {
      baseName: "Lightning Splash",
      morph1Name: "Liquid Lightning",
      morph2Name: "Lightning Flood",
      skillType: "active",
      lineRankNeeded: 20,
    },
    {
      baseName: "Surge",
      morph1Name: "Power Surge",
      morph2Name: "Critical Surge",
      skillType: "active",
      lineRankNeeded: 30,
    },
    {
      baseName: "Bolt Escape",
      morph1Name: "Streak",
      morph2Name: "Ball of Lightning",
      skillType: "active",
      lineRankNeeded: 42,
    },
  ],
  [131]: [
    {
      baseName: "Flame Skull",
      morph1Name: "Venom Skull",
      morph2Name: "Ricochet Skull",
      skillType: "active",
      lineRankNeeded: 1,
    },
    {
      baseName: "Sacrificial Bones",
      morph1Name: "Blighted Blastbones",
      morph2Name: "Grave Lord's Sacrifice",
      skillType: "active",
      lineRankNeeded: 4,
    },
    {
      baseName: "Frozen Colossus",
      morph1Name: "Pestilent Colossus",
      morph2Name: "Glacial Colossus",
      skillType: "ultimate",
      lineRankNeeded: 12,
    },
    {
      baseName: "Boneyard",
      morph1Name: "Unnerving Boneyard",
      morph2Name: "Avid Boneyard",
      skillType: "active",
      lineRankNeeded: 20,
    },
    {
      baseName: "Skeletal Mage",
      morph1Name: "Skeletal Archer",
      morph2Name: "Skeletal Arcanist",
      skillType: "active",
      lineRankNeeded: 30,
    },
    {
      baseName: "Shocking Siphon",
      morph1Name: "Detonating Siphon",
      morph2Name: "Mystic Siphon",
      skillType: "active",
      lineRankNeeded: 42,
    },
  ],
  [132]: [
    {
      baseName: "Death Scythe",
      morph1Name: "Ruinous Scythe",
      morph2Name: "Hungry Scythe",
      skillType: "active",
      lineRankNeeded: 1,
    },
    {
      baseName: "Bone Armor",
      morph1Name: "Beckoning Armor",
      morph2Name: "Summoner's Armor",
      skillType: "active",
      lineRankNeeded: 4,
    },
    {
      baseName: "Bone Goliath Transformation",
      morph1Name: "Pummeling Goliath",
      morph2Name: "Ravenous Goliath",
      skillType: "ultimate",
      lineRankNeeded: 12,
    },
    {
      baseName: "Bitter Harvest",
      morph1Name: "Deaden Pain",
      morph2Name: "Necrotic Potency",
      skillType: "active",
      lineRankNeeded: 20,
    },
    {
      baseName: "Bone Totem",
      morph1Name: "Remote Totem",
      morph2Name: "Agony Totem",
      skillType: "active",
      lineRankNeeded: 30,
    },
    {
      baseName: "Grave Grasp",
      morph1Name: "Ghostly Embrace",
      morph2Name: "Empowering Grasp",
      skillType: "active",
      lineRankNeeded: 42,
    },
  ],
  [133]: [
    {
      baseName: "Render Flesh",
      morph1Name: "Resistant Flesh",
      morph2Name: "Blood Sacrifice",
      skillType: "active",
      lineRankNeeded: 1,
    },
    {
      baseName: "Expunge",
      morph1Name: "Expunge and Modify",
      morph2Name: "Hexproof",
      skillType: "active",
      lineRankNeeded: 4,
    },
    {
      baseName: "Reanimate",
      morph1Name: "Renewing Animation",
      morph2Name: "Animate Blastbones",
      skillType: "ultimate",
      lineRankNeeded: 12,
    },
    {
      baseName: "Life amid Death",
      morph1Name: "Renewing Undeath",
      morph2Name: "Enduring Undeath",
      skillType: "active",
      lineRankNeeded: 20,
    },
    {
      baseName: "Spirit Mender",
      morph1Name: "Spirit Guardian",
      morph2Name: "Intensive Mender",
      skillType: "active",
      lineRankNeeded: 30,
    },
    {
      baseName: "Restoring Tether",
      morph1Name: "Braided Tether",
      morph2Name: "Mortal Coil",
      skillType: "active",
      lineRankNeeded: 42,
    },
  ],
  [218]: [
    {
      baseName: "Runeblades",
      morph1Name: "Writhing Runeblades",
      morph2Name: "Escalating Runeblades",
      skillType: "active",
      lineRankNeeded: 1,
    },
    {
      baseName: "Fatecarver",
      morph1Name: "Exhausting Fatecarver",
      morph2Name: "Pragmatic Fatecarver",
      skillType: "active",
      lineRankNeeded: 4,
    },
    {
      baseName: "The Unblinking Eye",
      morph1Name: "The Tide King's Gaze",
      morph2Name: "The Languid Eye",
      skillType: "ultimate",
      lineRankNeeded: 12,
    },
    {
      baseName: "Abyssal Impact",
      morph1Name: "Cephaliarch's Flail",
      morph2Name: "Tentacular Dread",
      skillType: "active",
      lineRankNeeded: 20,
    },
    {
      baseName: "Tome-Bearer's Inspiration",
      morph1Name: "Inspired Scholarship",
      morph2Name: "Recuperative Treatise",
      skillType: "active",
      lineRankNeeded: 30,
    },
    {
      baseName: "The Imperfect Ring",
      morph1Name: "Rune of Displacement",
      morph2Name: "Fulminating Rune",
      skillType: "active",
      lineRankNeeded: 42,
    },
  ],
  [219]: [
    {
      baseName: "Runic Jolt",
      morph1Name: "Runic Sunder",
      morph2Name: "Runic Embrace",
      skillType: "active",
      lineRankNeeded: 1,
    },
    {
      baseName: "Runespite Ward",
      morph1Name: "Spiteward of the Lucid Mind",
      morph2Name: "Impervious Runeward",
      skillType: "active",
      lineRankNeeded: 4,
    },
    {
      baseName: "Gibbering Shield",
      morph1Name: "Sanctum of the Abyssal Sea",
      morph2Name: "Gibbering Shelter",
      skillType: "ultimate",
      lineRankNeeded: 12,
    },
    {
      baseName: "Fatewoven Armor",
      morph1Name: "Cruxweaver Armor",
      morph2Name: "Unbreakable Fate",
      skillType: "active",
      lineRankNeeded: 20,
    },
    {
      baseName: "Runic Defense",
      morph1Name: "Runeguard of Still Waters",
      morph2Name: "Runeguard of Freedom",
      skillType: "active",
      lineRankNeeded: 30,
    },
    {
      baseName: "Rune of Eldritch Horror",
      morph1Name: "Rune of Uncanny Adoration",
      morph2Name: "Rune of the Colorless Pool",
      skillType: "active",
      lineRankNeeded: 42,
    },
  ],
  [220]: [
    {
      baseName: "Runemend",
      morph1Name: "Evolving Runemend",
      morph2Name: "Audacious Runemend",
      skillType: "active",
      lineRankNeeded: 1,
    },
    {
      baseName: "Remedy Cascade",
      morph1Name: "Cascading Fortune",
      morph2Name: "Curative Surge",
      skillType: "active",
      lineRankNeeded: 4,
    },
    {
      baseName: "Vitalizing Glyphic",
      morph1Name: "Glyphic of the Tides",
      morph2Name: "Resonating Glyphic",
      skillType: "ultimate",
      lineRankNeeded: 12,
    },
    {
      baseName: "Chakram Shields",
      morph1Name: "Chakram of Destiny",
      morph2Name: "Tidal Chakram",
      skillType: "active",
      lineRankNeeded: 20,
    },
    {
      baseName: "Arcanist's Domain",
      morph1Name: "Zenas' Empowering Disc",
      morph2Name: "Reconstructive Domain",
      skillType: "active",
      lineRankNeeded: 30,
    },
    {
      baseName: "Apocryphal Gate",
      morph1Name: "Fleet-Footed Gate",
      morph2Name: "Passage Between Worlds",
      skillType: "active",
      lineRankNeeded: 42,
    },
  ],
  [30]: [
    {
      baseName: "Uppercut",
      morph1Name: "Dizzying Swing",
      morph2Name: "Wrecking Blow",
      skillType: "active",
      lineRankNeeded: 2,
    },
    {
      baseName: "Critical Charge",
      morph1Name: "Stampede",
      morph2Name: "Critical Rush",
      skillType: "active",
      lineRankNeeded: 4,
    },
    {
      baseName: "Cleave",
      morph1Name: "Carve",
      morph2Name: "Brawler",
      skillType: "active",
      lineRankNeeded: 14,
    },
    {
      baseName: "Reverse Slash",
      morph1Name: "Reverse Slice",
      morph2Name: "Executioner",
      skillType: "active",
      lineRankNeeded: 20,
    },
    {
      baseName: "Momentum",
      morph1Name: "Forward Momentum",
      morph2Name: "Rally",
      skillType: "active",
      lineRankNeeded: 38,
    },
    {
      baseName: "Berserker Strike",
      morph1Name: "Onslaught",
      morph2Name: "Berserker Rage",
      skillType: "ultimate",
      lineRankNeeded: 50,
    },
  ],
  [29]: [
    {
      baseName: "Puncture",
      morph1Name: "Ransack",
      morph2Name: "Pierce Armor",
      skillType: "active",
      lineRankNeeded: 2,
    },
    {
      baseName: "Low Slash",
      morph1Name: "Deep Slash",
      morph2Name: "Heroic Slash",
      skillType: "active",
      lineRankNeeded: 4,
    },
    {
      baseName: "Defensive Posture",
      morph1Name: "Defensive Stance",
      morph2Name: "Absorb Missile",
      skillType: "active",
      lineRankNeeded: 14,
    },
    {
      baseName: "Shield Charge",
      morph1Name: "Shielded Assault",
      morph2Name: "Invasion",
      skillType: "active",
      lineRankNeeded: 20,
    },
    {
      baseName: "Power Bash",
      morph1Name: "Reverberating Bash",
      morph2Name: "Power Slam",
      skillType: "active",
      lineRankNeeded: 38,
    },
    {
      baseName: "Shield Wall",
      morph1Name: "Spell Wall",
      morph2Name: "Shield Discipline",
      skillType: "ultimate",
      lineRankNeeded: 50,
    },
  ],
  [31]: [
    {
      baseName: "Flurry",
      morph1Name: "Rapid Strikes",
      morph2Name: "Bloodthirst",
      skillType: "active",
      lineRankNeeded: 2,
    },
    {
      baseName: "Twin Slashes",
      morph1Name: "Rending Slashes",
      morph2Name: "Blood Craze",
      skillType: "active",
      lineRankNeeded: 4,
    },
    {
      baseName: "Whirlwind",
      morph1Name: "Whirling Blades",
      morph2Name: "Steel Tornado",
      skillType: "active",
      lineRankNeeded: 14,
    },
    {
      baseName: "Blade Cloak",
      morph1Name: "Quick Cloak",
      morph2Name: "Deadly Cloak",
      skillType: "active",
      lineRankNeeded: 20,
    },
    {
      baseName: "Hidden Blade",
      morph1Name: "Shrouded Daggers",
      morph2Name: "Flying Blade",
      skillType: "active",
      lineRankNeeded: 38,
    },
    {
      baseName: "Lacerate",
      morph1Name: "Rend",
      morph2Name: "Thrive in Chaos",
      skillType: "ultimate",
      lineRankNeeded: 50,
    },
  ],
  [32]: [
    {
      baseName: "Snipe",
      morph1Name: "Lethal Arrow",
      morph2Name: "Focused Aim",
      skillType: "active",
      lineRankNeeded: 2,
    },
    {
      baseName: "Volley",
      morph1Name: "Endless Hail",
      morph2Name: "Arrow Barrage",
      skillType: "active",
      lineRankNeeded: 4,
    },
    {
      baseName: "Scatter Shot",
      morph1Name: "Magnum Shot",
      morph2Name: "Draining Shot",
      skillType: "active",
      lineRankNeeded: 14,
    },
    {
      baseName: "Arrow Spray",
      morph1Name: "Bombard",
      morph2Name: "Acid Spray",
      skillType: "active",
      lineRankNeeded: 20,
    },
    {
      baseName: "Poison Arrow",
      morph1Name: "Venom Arrow",
      morph2Name: "Poison Injection",
      skillType: "active",
      lineRankNeeded: 38,
    },
    {
      baseName: "Rapid Fire",
      morph1Name: "Toxic Barrage",
      morph2Name: "Ballista",
      skillType: "ultimate",
      lineRankNeeded: 50,
    },
  ],
  [33]: [
    {
      baseName: "Force Shock",
      morph1Name: "Crushing Shock",
      morph2Name: "Force Pulse",
      skillType: "active",
      lineRankNeeded: 2,
    },
    {
      baseName: "Wall of Elements",
      morph1Name: "Unstable Wall of Elements",
      morph2Name: "Elemental Blockade",
      skillType: "active",
      lineRankNeeded: 4,
    },
    {
      baseName: "Destructive Touch",
      morph1Name: "Destructive Clench",
      morph2Name: "Destructive Reach",
      skillType: "active",
      lineRankNeeded: 14,
    },
    {
      baseName: "Weakness to Elements",
      morph1Name: "Elemental Susceptibility",
      morph2Name: "Elemental Drain",
      skillType: "active",
      lineRankNeeded: 20,
    },
    {
      baseName: "Impulse",
      morph1Name: "Elemental Ring",
      morph2Name: "Pulsar",
      skillType: "active",
      lineRankNeeded: 38,
    },
    {
      baseName: "Elemental Storm",
      morph1Name: "Elemental Rage",
      morph2Name: "Eye of the Storm",
      skillType: "ultimate",
      lineRankNeeded: 50,
    },
  ],
}
